### ISSUE TITLE
[Suggestion] Worldless RotationHelper or FakeWorld

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#1002]
I was looking at BuildCraft's issues and I was thinking about using RotationHelper to fix BuildCraft/BuildCraft#1516, but RotationHelper doesn't support something like Block + metadata... Forge also doesn't have a FakeWorld so we can't do that either :/

**Comment by LexManos** [comment]
1.8 removed all need for RotationHelper with it's new block states so this is not needed anymore.
