### ISSUE TITLE
textures don't load

### ISSUE THREAD

**Issue by randomusert** [MinecraftForge/MinecraftForge#10059]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.3.5

**Logs:** _no response_

**Steps to Reproduce:**
 1. add a item
 2. add a texture
 3. and see no texture in game

**Description of issue:**
it doesn't load textures

my mod can be found at https://github.com/randomusert/customcrafting-1.20.1-forge

**Comment by LexManos** [comment]
Use the discord or forums for basic support like this. Most likely you have your path wrong, it should say something in the logs
https://discord.minecraftforge.net/
https://minecraftforge.net/
