### ISSUE TITLE
IForgeItem method getAttributeModifiers is not called

### ISSUE THREAD

**Issue by Corail31** [MinecraftForge/MinecraftForge#10058]
**Minecraft Version:** {1.21}

**Forge Version:** {Forge version. 51.0.24}

**Steps to Reproduce:**
 1. override IForge method ItemAttributeModifiers getAttributeModifiers(EquipmentSlot slot, ItemStack stack) in Item class to provide an attribute
 2. the attribute is not applied in game
 3. override vanilla method ItemAttributeModifiers getDefaultAttributeModifiers() in Item class
 4. the attribute is applied (but with no context on EquipmentSlot and ItemStack)

**Description of issue:**
The method seems to not be used in ItemStack methods.

```java
    public void forEachModifier(EquipmentSlotGroup p_344758_, BiConsumer<Holder<Attribute>, AttributeModifier> p_342345_) {
        ItemAttributeModifiers itemattributemodifiers = this.getOrDefault(DataComponents.ATTRIBUTE_MODIFIERS, ItemAttributeModifiers.EMPTY);
        if (!itemattributemodifiers.modifiers().isEmpty()) {
            itemattributemodifiers.forEach(p_344758_, p_342345_);
        } else {
            this.getItem().getDefaultAttributeModifiers().forEach(p_344758_, p_342345_);
        }

        EnchantmentHelper.forEachModifier(this, p_344758_, p_342345_);
    }

    public void forEachModifier(EquipmentSlot p_331036_, BiConsumer<Holder<Attribute>, AttributeModifier> p_334430_) {
        ItemAttributeModifiers itemattributemodifiers = this.getOrDefault(DataComponents.ATTRIBUTE_MODIFIERS, ItemAttributeModifiers.EMPTY);
        if (!itemattributemodifiers.modifiers().isEmpty()) {
            itemattributemodifiers.forEach(p_331036_, p_334430_);
        } else {
            this.getItem().getDefaultAttributeModifiers().forEach(p_331036_, p_334430_);
        }

        EnchantmentHelper.forEachModifier(this, p_331036_, p_334430_);
    }
```

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/2951c1dac8881e2976476953c5497ee52560af32
Added a ItemStack sensitive version, for any other context {group or slot} if avalible, you can filter out using your Entry.slot
