### ISSUE TITLE
NetworkEvent Not Found

### ISSUE THREAD

**Issue by Sarocesch** [MinecraftForge/MinecraftForge#10057]
**Minecraft Version:** {1.20.4}

**Forge Version:** {49.1.4}

I have updated my 1.20.1 project to 1.20.4 and it no longer finds this import

`import net.minecraftforge.network.NetworkEvent;`

I have been searching for several hours and feel a bit stupid sorry but don't know what to replace it with ?

I have also not found a way to look it up except in the repo but I have not found anything there

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/4649f7af36ac709129a53f7fc2fd639b883474d9

**Comment by Sarocesch** [comment]
Thanks

**Comment by Sarocesch** [comment]
I'm sorry if I come across as lost 

but where can I find help with updating my code don't know what to do

**Comment by LexManos** [comment]
The discord or forums for basic support. But your best bet is to just read the examples in forge itself.
