### ISSUE TITLE
NPE in PacketDistributor when running game tests

### ISSUE THREAD

**Issue by daedalus4096** [MinecraftForge/MinecraftForge#10066]
**Minecraft Version:** 1.21.1

**Forge Version:** 52.0.2

**Logs:**
latest.log: https://pastebin.com/1aWHGnXL
Crash report: https://pastebin.com/gUPMjLar

**Steps to Reproduce:**
 1. Create a game test which sends a packet to multiple players through SimpleChannel, such as through SimpleChannel#send with a PacketDistributor.TargetPoint target parameter.
 2. Run the headless game test server.
 3. Note that this issue does **not** reproduce when run via the /test command in the client.

**Description of issue:**
Upon attempting to send the packet, the game test server will crash with a null pointer exception, as PacketDistributor#getServer returns null. Expected result is that the server either sends the packet (questionable, given the headless environment) or silently refuses to. In either event, the game test server should not crash.

**Comment by LexManos** [comment]
How are you setting up this multiple users? 
Can you provide your simple test?
It sounds like a good test for things, and it would help debug this issue.

The solution seems simple enough add `if (!net.minecraftforge.server.ServerLifecycleHooks.handleServerAboutToStart(this)) return false;` to `GameTestServer.initServer()` But would love to have something actually testing this.

**Comment by daedalus4096** [comment]
Sorry, I misspoke. You don't actually need multiple players receiving the packet, you just have to send it in a way that it it's *possible* for it to go to multiple players. Sending from the server to all clients, or from the server to a target bounding box, or the like. Something that forces the server to query the player list.

The test that I'm currently using tests other mod-specific behavior and isn't exactly lightweight; I discovered the crash by accident, as that behavior sends a packet to the client to trigger some particle effects. But I should be able to write up a simpler, lighter-weight test that produces the same effect. I'll give it a go and report back here.

**Comment by daedalus4096** [comment]
Okay, I've created a stripped down test mod that reproduces the issue in 52.0.4. You can find it [here](https://github.com/daedalus4096/PacketCrashTestMod). As I suspected, sending a packet to all players, or to all players in an area, will cause an NPE. Sending a packet directly to a specific player, however, will not. I also discovered that part of the problem lies with the GameTestHelper's succeedIf and succeedWhen methods: they seem to be less resilient than the base game test methods themselves. If the NPE occurs within succeedIf or succeedWhen, then the game test server will crash and all further tests will be aborted. If not in one of those methods, though, then the test will simply fail, citing the NPE, but other tests will continue running.
