### ISSUE TITLE
Cobblemon server does not let anyone join

### ISSUE THREAD

**Issue by RedMenace0711** [MinecraftForge/MinecraftForge#10060]
I created a cobblemon server and no one is able to join, it gets stuck on loading terrain and the screen becomes gray. Then, it will present the error code of "internal exception io.netty.handler.codec.encoderexception java.lang.nullpointerexception: cannot invoke "net.minecraft.resourceslocation.tostring()" because "p_130086" is null"

Server mod list:
geckolib-forge-1.20.1-4.4.6.jar                   |GeckoLib 4                    |geckolib                      |4.4.6               |COMMON_SET|Manifest: NOSIGNATURE
beautify-2.0.0.jar                                |Beautify                      |beautify                      |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
seafoamsdyeableblocks-1.4.2-forge-fabric.jar      |Seafoam's Dyeable Blocks      |seafoamsdyeableblocks         |1.4.2               |COMMON_SET|Manifest: NOSIGNATURE
Incendium_1.20.1_v5.3.1.jar                       |Incendium                     |incendium                     |5.3.1               |COMMON_SET|Manifest: NOSIGNATURE
sophisticatedcore-1.20.1-0.6.22.611.jar           |Sophisticated Core            |sophisticatedcore             |0.6.22.611          |COMMON_SET|Manifest: NOSIGNATURE
mixinextras-forge-0.2.0-beta.8.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.8        |COMMON_SET|Manifest: NOSIGNATURE
sophisticatedbackpacks-1.20.1-3.20.5.1044.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |3.20.5.1044         |COMMON_SET|Manifest: NOSIGNATURE
balm-forge-1.20.1-7.2.2.jar                       |Balm                          |balm                          |7.2.2               |COMMON_SET|Manifest: NOSIGNATURE
embeddium-0.3.28+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.3.28+mc1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
corpse-forge-1.20.1-1.0.12.jar                    |Corpse                        |corpse                        |1.20.1-1.0.12       |COMMON_SET|Manifest: NOSIGNATURE
FarmersDelight-1.20.1-1.2.4.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |COMMON_SET|Manifest: NOSIGNATURE
ends_delight-1.20.1-2.4.jar                       |End's Delight                 |ends_delight                  |2.4                 |COMMON_SET|Manifest: NOSIGNATURE
handcrafted-forge-1.20.1-3.0.6.jar                |Handcrafted                   |handcrafted                   |3.0.6               |COMMON_SET|Manifest: NOSIGNATURE
CozyHome-2.2.4-1.20.1.jar                         |Cozy Home                     |cozy_home                     |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
Explorify v1.6.1 f10-48.jar                       |Explorify                     |explorify                     |1.6.1               |COMMON_SET|Manifest: NOSIGNATURE
fairylights-7.0.0-1.20.1.jar                      |Fairy Lights                  |fairylights                   |7.0.0               |COMMON_SET|Manifest: NOSIGNATURE
wthit-forge-8.13.4.jar                            |wthit                         |wthit                         |8.13.4              |COMMON_SET|Manifest: NOSIGNATURE
cluttered-2.1-1.20.1.jar                          |Cluttered                     |luphieclutteredmod            |2.1                 |COMMON_SET|Manifest: NOSIGNATURE
touhoulittlemaid-1.20.1-release-1.1.11.jar        |Touhou Little Maid            |touhou_little_maid            |1.1.11              |COMMON_SET|Manifest: NOSIGNATURE
curios-forge-5.9.1+1.20.1.jar                     |Curios API                    |curios                        |5.9.1+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
Patchouli-1.20.1-84-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |COMMON_SET|Manifest: NOSIGNATURE
oculus-mc1.20.1-1.6.15a.jar                       |Oculus                        |oculus                        |1.6.15a             |ERROR     |Manifest: NOSIGNATURE
simplehats-forge-1.20.1-0.2.1.jar                 |SimpleHats                    |simplehats                    |1.20.1-0.2.1        |COMMON_SET|Manifest: NOSIGNATURE
Cobblemon-forge-1.5.2+1.20.1.jar                  |Cobblemon                     |cobblemon                     |1.5.2+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
FramedBlocks-9.2.1.jar                            |FramedBlocks                  |framedblocks                  |9.2.1               |COMMON_SET|Manifest: NOSIGNATURE
dungeons-and-taverns-v2.1.4.jar                   |Dungeons and Taverns          |mr_dungeons_andtaverns        |1-v2.1.4            |COMMON_SET|Manifest: NOSIGNATURE
resourcefullib-forge-1.20.1-2.1.28.jar            |Resourceful Lib               |resourcefullib                |2.1.28              |COMMON_SET|Manifest: NOSIGNATURE
architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |COMMON_SET|Manifest: NOSIGNATURE
letsdo-API-forge-1.2.15-forge.jar                 |[Let's Do] API                |doapi                         |1.2.15              |COMMON_SET|Manifest: NOSIGNATURE
letsdo-candlelight-forge-1.2.13.jar               |[Let's Do] Candlelight        |candlelight                   |1.2.13              |COMMON_SET|Manifest: NOSIGNATURE
letsdo-bakery-forge-1.1.15.jar                    |[Let's Do] Bakery             |bakery                        |1.1.15              |COMMON_SET|Manifest: NOSIGNATURE
letsdo-vinery-forge-1.4.27.jar                    |[Let's Do] Vinery             |vinery                        |1.4.27              |COMMON_SET|Manifest: NOSIGNATURE
letsdo-herbalbrews-forge-1.0.8.jar                |[Let's Do] HerbalBrews        |herbalbrews                   |1.0.8               |COMMON_SET|Manifest: NOSIGNATURE
flib-1.20.1-0.0.14.jar                            |flib                          |flib                          |0.0.14              |COMMON_SET|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
l2library-2.4.11-slim.jar                         |L2 Library                    |l2library                     |2.4.11              |COMMON_SET|Manifest: NOSIGNATURE
cobblemon-unchained-1.5-forge-1.0.1.jar           |Cobblemon Unchained           |unchained                     |1.5-forge-1.0.1     |COMMON_SET|Manifest: NOSIGNATURE
Festive_Delight_1.1_1.20.1.jar                    |Festive Delight               |festive_delight               |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
Fastload-Reforged-mc1.20.1-3.4.0.jar              |Fastload-Reforged             |fastload                      |3.4.0               |COMMON_SET|Manifest: NOSIGNATURE
amendments-1.20-1.2.8.jar                         |Amendments                    |amendments                    |1.20-1.2.8          |COMMON_SET|Manifest: NOSIGNATURE
jei-1.20.1-forge-15.10.0.31.jar                   |Just Enough Items             |jei                           |15.10.0.31          |COMMON_SET|Manifest: NOSIGNATURE
Create-Cobblemon-Forge-v0.4.jar                   |Create: Cobblemon Industrializ|create_cobblemon              |0.4                 |COMMON_SET|Manifest: NOSIGNATURE
obscure_api-15.jar                                |Obscure API                   |obscure_api                   |15                  |COMMON_SET|Manifest: NOSIGNATURE
enlightend-5.0.14-1.20.1.jar                      |Enlightend                    |enlightened_end               |5.0.14              |COMMON_SET|Manifest: NOSIGNATURE
cobblemon-counter-1.5-forge-1.2.0.jar             |Cobblemon Counter             |cobbled_counter               |1.5-forge-1.2.0     |COMMON_SET|Manifest: NOSIGNATURE
waystones-forge-1.20-14.1.0.jar                   |Waystones                     |waystones                     |14.1.0              |COMMON_SET|Manifest: NOSIGNATURE
petyourcobblemon-1.2.0.jar                        |Pet Your Cobblemon            |petyourcobblemon              |1.2.0               |COMMON_SET|Manifest: NOSIGNATURE
comforts-forge-6.4.0+1.20.1.jar                   |Comforts                      |comforts                      |6.4.0+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
NaturesCompass-1.20.1-1.11.2-forge.jar            |Nature's Compass              |naturescompass                |1.20.1-1.11.2-forge |COMMON_SET|Manifest: NOSIGNATURE
SimpleStorageNetwork-1.20.1-1.10.0.jar            |Simple Storage Network        |storagenetwork                |1.10.0              |COMMON_SET|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
badpackets-forge-0.4.3.jar                        |Bad Packets                   |badpackets                    |0.4.3               |COMMON_SET|Manifest: NOSIGNATURE
Terralith_1.20.x_v2.5.4.jar                       |Terralith                     |terralith                     |2.5.4               |COMMON_SET|Manifest: NOSIGNATURE
PineappleDelight-Forge-1.20-1.0.8-Fix.jar         |Pineapple Delight             |pineapple_delight             |1.0.8               |COMMON_SET|Manifest: NOSIGNATURE
CoffeeDelight-Forge-1.20.1-1.4-Fix.jar            |Coffee Delight                |coffee_delight                |1.4                 |COMMON_SET|Manifest: NOSIGNATURE
ars_nouveau-1.20.1-4.6.0-all.jar                  |Ars Nouveau                   |ars_nouveau                   |4.6.0               |COMMON_SET|Manifest: NOSIGNATURE
skinlayers3d-forge-1.6.6-mc1.20.1.jar             |3d-Skin-Layers                |skinlayers3d                  |1.6.6               |COMMON_SET|Manifest: NOSIGNATURE
forge-1.20.1-47.3.5-universal.jar                 |Forge                         |forge                         |47.3.5              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
bloodmagic-1.20.1-3.3.3-45.jar                    |Blood Magic                   |bloodmagic                    |3.3.3-45            |COMMON_SET|Manifest: NOSIGNATURE
tomeofblood-1.20.1-0.4.4-all.jar                  |Tome of Blood: Rebirth        |tomeofblood                   |0.4.4               |COMMON_SET|Manifest: NOSIGNATURE
delightfulsandwich-1.20.1.jar                     |Delightful Sandwiches         |delightfulsandwich            |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
TerraBlender-forge-1.20.1-3.0.1.7.jar             |TerraBlender                  |terrablender                  |3.0.1.7             |COMMON_SET|Manifest: NOSIGNATURE
moonlight-1.20-2.12.9-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.12.9         |COMMON_SET|Manifest: NOSIGNATURE
mixinsquared-forge-0.1.1.jar                      |MixinSquared                  |mixinsquared                  |0.1.1               |COMMON_SET|Manifest: NOSIGNATURE
Jade-1.20.1-forge-11.9.4.jar                      |Jade                          |jade                          |11.9.4+forge        |COMMON_SET|Manifest: NOSIGNATURE
delightfulburgers-1.20.1.jar                      |Delightful Burgers            |delightfulburgers             |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
Oh The Trees You_ll Grow-forge-1.20.1-1.2.0.jar   |Oh The Trees You'll Grow      |ohthetreesyoullgrow           |1.2.0               |COMMON_SET|Manifest: NOSIGNATURE
spectrelib-forge-0.13.15+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.15+1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
corgilib-forge-1.20.1-4.0.2.0.jar                 |CorgiLib                      |corgilib                      |4.0.2.0             |COMMON_SET|Manifest: NOSIGNATURE
Oh-The-Biomes-Weve-Gone-Forge-1.0.5-Beta.jar      |Oh The Biomes We've Gone      |biomeswevegone                |1.0.5-Beta          |COMMON_SET|Manifest: NOSIGNATURE
nethersdelight-1.20.1-4.0.jar                     |Nether's Delight              |nethersdelight                |1.20.1-4.0          |COMMON_SET|Manifest: NOSIGNATURE
kffmod-4.10.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.10.0              |COMMON_SET|Manifest: NOSIGNATURE
plushies-1.4.0-forge.jar                          |Plushie Mod                   |plushies                      |1.4.0               |COMMON_SET|Manifest: NOSIGNATURE
flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |COMMON_SET|Manifest: NOSIGNATURE
create-1.20.1-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |COMMON_SET|Manifest: NOSIGNATURE
ars_creo-1.20.1-4.0.1.jar                         |Ars Creo                      |ars_creo                      |4.0.1               |COMMON_SET|Manifest: NOSIGNATURE
createoreexcavation-1.20-1.5.0.jar                |Create Ore Excavation         |createoreexcavation           |1.5.0               |COMMON_SET|Manifest: NOSIGNATURE
Xaeros_Minimap_24.2.0_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |24.2.0              |COMMON_SET|Manifest: NOSIGNATURE
Nullscape_1.20.1_v1.2.1.jar                       |Nullscape                     |nullscape                     |1.2.1               |COMMON_SET|Manifest: NOSIGNATURE
Zeta-1.0-24.jar                                   |Zeta                          |zeta                          |1.0-24              |COMMON_SET|Manifest: NOSIGNATURE
Cobblepedia-Forge-0.6.6.jar                       |Cobblepedia                   |cobblepedia                   |0.6.6               |COMMON_SET|Manifest: NOSIGNATURE
canary-mc1.20.1-0.3.3.jar                         |Canary                        |canary                        |0.3.3               |COMMON_SET|Manifest: NOSIGNATURE
armourersworkshop-forge-1.20.1-2.1.4.jar          |Armourer's Workshop           |armourers_workshop            |2.1.4               |COMMON_SET|Manifest: 58:d0:3b:4b:a0:4b:43:fb:59:0f:27:f5:39:d5:65:de:9a:24:ee:2e:15:48:b1:4f:78:1a:e1:ef:cd:a4:d9:0a
AFMP_forge_1.20.1_1.2.0.jar                       |AFMP: A Few More Plushies     |afmp_a_few_more_plushies      |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
oceansdelight-1.0.2-1.20.jar                      |Ocean's Delight               |oceansdelight                 |1.0.2-1.20          |COMMON_SET|Manifest: NOSIGNATURE
embersrekindled-1.20.1-1.3.9.jar                  |Embers Rekindled              |embers                        |1.20.1-1.3.9        |COMMON_SET|Manifest: NOSIGNATURE
lootr-forge-1.20-0.7.34.86.jar                    |Lootr                         |lootr                         |0.7.34.85           |COMMON_SET|Manifest: NOSIGNATURE
Quark-4.0-460.jar                                 |Quark                         |quark                         |4.0-460             |COMMON_SET|Manifest: NOSIGNATURE
supplementaries-1.20-2.8.17.jar                   |Supplementaries               |supplementaries               |1.20-2.8.17         |COMMON_SET|Manifest: NOSIGNATURE
cobblemonrider-1.2.4.jar                          |cobblemonrider                |cobblemonrider                |1.2.4               |COMMON_SET|Manifest: NOSIGNATURE
fnaf_plushie_remastered-1.0.0-forge-1.20.1.jar    |Fnaf Plushie Remastered       |fnaf_plushie_remastered       |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
cosmeticarmorreworked-1.20.1-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.20.1-v1a          |COMMON_SET|Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
fruitsdelight-1.0.10.jar                          |Fruits Delight                |fruitsdelight                 |1.0.10              |COMMON_SET|Manifest: NOSIGNATURE
Delightful-1.20.1-3.5.9.jar                       |Delightful                    |delightful                    |3.5.9               |COMMON_SET|Manifest: NOSIGNATURE
aquamirae-6.API15.jar                             |Aquamirae                     |aquamirae                     |6.API15             |COMMON_SET|Manifest: NOSIGNATURE

**Comment by LexManos** [comment]
The github is not a place for basic tech support. Use the forums or discord.
