### ISSUE TITLE
1.20.6 Forge Client occurs NullPointerException while using command "transfer"

### ISSUE THREAD

**Issue by iqpizza6349** [MinecraftForge/MinecraftForge#10067]
> I could not post in forums(occurs forbidden status over and over), so I just report in here. I'm sorry 😥

**Minecraft Version:** 1.20.6

**Forge Version:** forge-1.20.6-50.1.7

**Logs:** 
**Client**
https://pastebin.com/embed_iframe/8sVDEgnB

> I'm working with local: KOR, so Korean is printed in the client log.

**Server**
https://pastebin.com/embed_iframe/uCuHXMk4

**Steps to Reproduce:**
 1. Set up two different forge server.
 2. enable transfer with option in server.properties
 3. give `OP` to yourself.
 4. send command in server `/transfer localhost ${port}` (for me, /transfer localhost 25567)

**Description of issue:**
> Read the log first.
This means that the transfer command is executed normally and the connection to server A (25565) that executed the command is disconnected.
Considering that the connection to server B (25567) to be connected failed, the ACK was completed normally.
Both servers are normal, but it appears to be caused by Forge Client or Forge Server.

Also, I believe that the connection is not possible due to an error in the simple transfer command.
As a result of using the paper version, the paper was moved from server A to server B normally in the same Minecraft version.

Personally, the reason is
* Injected VanillaConnectionNetworkFilter into Connection left in the Client log
* Login issues (if login is a problem, an explanation is needed as to why each server connection is working)
* Occurs because transfer is not considered in Forge Client

I think it's one of the three above.

If anyone has successfully performed transfer (command added in 1.20.5) using forge, please share how you did it.
thank you.

**Comment by LexManos** [comment]
Thanks for the report, just some old code that didn't get updated when transfer was added. Simple fix.
