### ISSUE TITLE
Can't Figure Out Why The Game Is Crashing

### ISSUE THREAD

**Issue by TheMCV3teran** [MinecraftForge/MinecraftForge#10078]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.1.30
**Logs:** [{Link(s) to GitHub Gist with full latest.log and/or crash report}](https://gist.github.com/TheMCV3teran/17614a030c2efa25138f9b913f7b6329)

**Steps to Reproduce:**
There aren't any steps, i think it's something with mods or my pc, i just wanna find out how to fix it

**Description of issue:**
I was creating a vanilla+ modpack for me and my friends to play on a private server with, and it keeps crashing before the loading screen appears with exit code -1073740791

**Comment by RealMangorage** [comment]
Not an issue with Forge itself. Just a general issue.
Go to our discord -> https://discord.minecraftforge.net/ for help.

**Comment by TheMCV3teran** [comment]
> Not an issue with Forge itself. Just a general issue. Go to our discord -> https://discord.minecraftforge.net/ for help.

dang, that was fast.

Thank you for your help
