### ISSUE TITLE
DataComponent Ingredient

### ISSUE THREAD

**Issue by Corail31** [MinecraftForge/MinecraftForge#10080]
Hi, i would like to request a feature:
_Would it be possible to have an ingredient for datacomponents directly in Forge in 1.21.1 ?_

Actually, there are only ingredients for compound (or i didn't notice it).
Even an ingredient strict like the StrictNBTIngredient would be a good start, with a test -> input != null && ItemStack.isSameItemSameComponents(this.stack, input);

Obviously, i can code it in my mod, but i thought i would be better directly in Forge.
Thanks for reading me.

Edit: i precise that i won't make the PR so, if anyone wants to, feel free.
If it can give some motivation, Brewery event is ingredient-based.

**Comment by LexManos** [comment]
I wouldn't be opposed to it, if written correctly. 
Should be simple enough.
