### ISSUE TITLE
Data component type registry is not synced, causing packet errors

### ISSUE THREAD

**Issue by SuperMartijn642** [MinecraftForge/MinecraftForge#10113]
**Minecraft Version:** 1.21.1

**Forge Version:** 52.0.9

**Logs:** [`latest.log` from the client](https://gist.github.com/SuperMartijn642/6684bae066edcf3ac1cd64bfc8cec70a) and [the report generated by the client](https://gist.github.com/SuperMartijn642/b6350fe03f49b590b4a20fdf37947378)

**Steps to Reproduce:**
In general these steps hold for any set of mods which register multiple data component types, but I was somewhat consistently able to reproduce the issue with the set of mods shown in the crash log and a backpack item from Traveler's Backpack.
 1. Install multiple mods which register their own data component type.
 2. Start both a server and a client with the mods and have the client join the server.
 3. Grab an item which has a custom data component set.
 4. If the id for the data component's type happens to differ between client and server, the client will be disconnected because `Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:container_set_content'`

**Description of issue:**
The stream codec for data component patches (`DataComponentPatch#STREAM_CODEC`) serializes each data component type using its integer id. For registries like items and blocks, Forge replaces the vanilla registries and synchronizes element ids during the configuration phase. Currently, the data component type registry is not synchronized and this can lead to situations where the client tries to deserialize a data component using the wrong data component type.
Part of the stream codec for item stacks is serializing the data component patch, thus this can happen basically any time the client tries to deserialize an item stack with a custom data component type.
From the reports I've had, this occurred through the `ClientboundContainerSetContentPacket` packet when a player obtains an item with a custom data component type and the player is then unable to join the server as long as the item remains in their inventory.

Ideally, the registry would be synchronized between client and server similar to other Forge registries like for items and blocks.
I believe the best solution would be to replace the data component type registry with a Forge registry which has the synchronization flag. I am not sure whether this would break mods which currently register their data component types to the vanilla registry.
An alternative, to avoid breaking changes, could be to patch the `DataComponentType` stream codec to serialize data component types by their `ResourceLocation` rather than by their integer id, however this would need to consider Forge-vanilla connections and would of course come at the cost of sending a string for each data component type rather than a single integer.

**Comment by LexManos** [comment]
I did an initial pass of this a while back https://github.com/LexManos/MinecraftForge/commit/4023e978cd97c0ff9a49092cb9e07fb46c4923f2
However that was one hold until @RealMangorage  worked on the component registry system.
I don't recall finding anywhere where things were serialized by numeric id?
The issue with my approach is that it breaks networking with older forge clients.
The benefit of my system is that it allows vanilla and clients without support for a specific component type to connect/parse (ignore) the data.

I'll poke mango and see how his end of things are going.

**Comment by LexManos** [comment]
Okay, so I am an idiot/overlooked something simple.
Older clients will just silently ignore any registries the server sends it that it doesn't know about.
So I didn't have to design a complicated system.
https://github.com/MinecraftForge/MinecraftForge/commit/23b41ce9b359749c8f5d3e385421ce03976cd084#diff-4160c09ca6daa65cc4314e5a700b4d411402774515601b0fae927bea395d4203R127 Should address it.
