### ISSUE TITLE
[1.20.6+] Something is wrong with Gui.java.patch

### ISSUE THREAD

**Issue by BloCamLimb** [MinecraftForge/MinecraftForge#10112]
**Minecraft Version:**
1.20.6 1.21.1

**Forge Version:**
1.20.6 - 50.1.15
1.21.1 - 52.0.10

**Description of issue:**
For 1.20.6, line 65 should be deleted:
https://github.com/MinecraftForge/MinecraftForge/blob/1b44cda8ed15f648c1e3e87a1cf92873670e9539/patches/minecraft/net/minecraft/client/gui/Gui.java.patch#L63-L73

------

For 1.21.1, line 65 should be deleted, and `drawString` at line 68 and 71 should be replaced with `drawStringWithBackdrop`:
https://github.com/MinecraftForge/MinecraftForge/blob/f168ce4499eaa0f48193d7c60c0376ce6b1aa974/patches/minecraft/net/minecraft/client/gui/Gui.java.patch#L64-L72

Otherwise, the item name would be drawn twice. The 1.20.4 version looks fine.

**Comment by LexManos** [comment]
Hurm, seems right. One of the patch fuzzes during update the got overlooked. Feel free to make a PR. Or I'll get to it when I have time.
