### ISSUE TITLE
LootTableLoadEvent might be broken

### ISSUE THREAD

**Issue by Stein-N** [MinecraftForge/MinecraftForge#10144]
**Minecraft Version:** 1.21.3

**Forge Version:** 53.0.2

**Logs:** no logs produced

**Steps to Reproduce:**
 1. Create a class with EventBusSubscriber on any bus
 2. Subscribe Event for LootTableLoadEvent
 3. try to add or try to Log  something

**Description of issue:**
The LootTableLoadEvent seems to be not working or not beeing fired at any time. I tried addin a LootTable and Logging the event.getName() but nothing happens.

**Comment by LexManos** [comment]
Provide code, ideally as a gametest mod and i can take a look on monday.
I know some things with LootTables change during the update but the current tests we have run just fine.

**Comment by Stein-N** [comment]
i can only provide this [repo based on the MDK](https://github.com/Stein-N/forge-loottable-issue), since i never used or tried Gametests sry.

**Comment by LexManos** [comment]
Was essentially a missed patch. Added a test to our test set so it should be detected in the future.
You can look at my commit for an example of how to make something like this into a test.
