### ISSUE TITLE
Low-res texture packs are horribly broken. 

### ISSUE THREAD

**Issue by Apothicon02** [MinecraftForge/MinecraftForge#10155]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.3.7, 47.3.11

**Logs:** N/A

**Steps to Reproduce:**
 1. Open Minecraft
 2. Enable a resource pack with a resolution less than 16x
 3. Raise render distance to 32
 4. Look at blocks in the distance. 

**Description of issue:** Blocks in very far away chunks will appear to be the entirely wrong color (ex. sand can be purple instead of yellow) and water may or may not stop rendering at those distances. Confirmed to happen without any mods, and with the experimental rendering pipeline enabled or disabled, on a freshly installed instance of Forge with either of these resource packs: F8thful or Pollachius. 
![image](https://github.com/user-attachments/assets/6597c8a2-d007-4747-b32a-d58af7721a16)
![image](https://github.com/user-attachments/assets/3892cbd6-2e44-4a01-b814-56e04804efeb)

**Comment by Apothicon02** [comment]
I suspect the issue is related to fog, as it becomes more noticeable with mods that render fog closer.

**Comment by LexManos** [comment]
Link/Include a reproduction texture pack so we can verify.

**Comment by Apothicon02** [comment]
https://www.curseforge.com/minecraft/texture-packs/f8thful

**Comment by Lolothepro** [comment]
it's caused by https://github.com/MinecraftForge/MinecraftForge/pull/8622, fyi

**Comment by LexManos** [comment]
I know, it needs a config option to toggle this feature.
Just havent gotten around to doing it.
I *would* like to do a proper audit of popular modpacks to see if this feature is even needed anymore as it was originally done to fix things like pipes which didnt use standard sized textures. Which I dont think is a thing anymore. So the patch could just be killed.
