### ISSUE TITLE
Smoker Recipes unable to use Tags

### ISSUE THREAD

**Issue by TheCherryCoder** [MinecraftForge/MinecraftForge#10164]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.3.11

**Logs:** {Un Needed}

**Steps to Reproduce:**
 1. Install Any mod that uses smoking recipes with tags (Eg : Architects Palette Charcoal Blocks)
 2. Install EMI/JEI to view recipes
 3.You will see that only the smoking recipes with tags are broken

When adding recipes to smoking, they are broken if they try using tags in smoking (eg : #minecraft:logs_tha_burn)
when the exact same recipe will work if changed to furnace smelting, blast furnace or campfire cooking

**Comment by LexManos** [comment]
Provide an actual example recipe. Because the recipe loading system in 1.20.1 functions just fine. And there is nothing special about smoking recipes vs other recipes save for the marked type. So it should work just fine.

**Comment by TheCherryCoder** [comment]
My bad, this seems to be an issue caused by some library mod. Which one i shall have to find out later but a fresh forge install with a few random recipe mods seems to work properly
