### ISSUE TITLE
[1.21.3] Player Render events patch missing/broken

### ISSUE THREAD

**Issue by tom5454** [MinecraftForge/MinecraftForge#10166]
**Minecraft Version:** 1.21.3

**Forge Version:** 53.0.9

**Description of issue:**
The PlayerRenderer class patch is broken.
https://github.com/MinecraftForge/MinecraftForge/blob/1.21.x/patches/minecraft/net/minecraft/client/renderer/entity/player/PlayerRenderer.java.patch#L44-L46
The player render events never fire.

**Comment by StavWasPlayZ** [comment]
Yes, noticed that as well.  
It instead invokes `RenderLivingEvent`... *twice*. (super calls it too.)

None of the `ForgeEventFactoryClient#onRenderPlayer...` methods are ever actually invoked, nor the event constructor itself.
