### ISSUE TITLE
[1.21.3] `ENTITY_TYPE` registry fired after `ITEM` registry. Impossible to create a `MinecartItem`

### ISSUE THREAD

**Issue by MrCrayfish** [MinecraftForge/MinecraftForge#10179]
I've noticed during registration, the order registries are fired makes it impossible to create a `MinecartItem`. As of 1.21.3, `MinecartItem` now accepts an `EntityType<AbstractMinecart>` instead of a (now removed) minecart type enum. Forge seems to be firing registration of `ENTITY_TYPE` after `ITEM`. The order of the registry builders in `GameData` seem to be causing the issue, and that order is retained in `MappedRegistry.getKnownRegistries()`. I'm not sure if there is any underlying intention behind the order in `GameData`, however `ENTITY_TYPES` before `ITEMS` would solve the issue.

The would also solve the issue of the `SpawnEgg` item, you'd no longer need a `Supplier` and you can just use the vanilla variant.

**Comment by LexManos** [comment]
The order of registry creation in GameData shouldn't have any effect on the ordering as it uses the registration order that vanilla fires to determine the order that we fire events in.
But yes mojang relies on static init just "figuring" it out. Perhaps this is yet another case where we have to patch in a holder/supplier constructor.

**Comment by MrCrayfish** [comment]
My bad, was late last night and I was wrong about GameData affecting the order. However I believe Forge interpreting the static init as the correct order is not completely accurate. For example, during the static init of `Items`, the registration of the item `WHITE_CARPET` triggers the static init of `EntityType`.

Here is the callstack I captured.
```
"pool-5-thread-1@8596" tid=0x28 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at net.minecraft.world.entity.EntityType.register(EntityType.java:902)
	  at net.minecraft.world.entity.EntityType.register(EntityType.java:910)
	  at net.minecraft.world.entity.EntityType.<clinit>(EntityType.java:186)
	  at net.minecraft.world.item.equipment.Equippable.llamaSwag(Equippable.java:73)
	  at net.minecraft.world.item.Items.lambda$static$6(Items.java:524)
	  at net.minecraft.world.item.Items$$Lambda/0x0000026ae5931568.apply(Unknown Source:-1)
	  at net.minecraft.world.item.Items.lambda$registerBlock$319(Items.java:2102)
	  at net.minecraft.world.item.Items$$Lambda/0x0000026ae592b360.apply(Unknown Source:-1)
	  at net.minecraft.world.item.Items.lambda$registerBlock$321(Items.java:2138)
	  at net.minecraft.world.item.Items$$Lambda/0x0000026ae5929008.apply(Unknown Source:-1)
	  at net.minecraft.world.item.Items.registerItem(Items.java:2162)
	  at net.minecraft.world.item.Items.registerBlock(Items.java:2138)
	  at net.minecraft.world.item.Items.registerBlock(Items.java:2134)
	  at net.minecraft.world.item.Items.registerBlock(Items.java:2102)
	  at net.minecraft.world.item.Items.<clinit>(Items.java:523)
	  at net.minecraft.world.level.block.ComposterBlock.bootStrap(ComposterBlock.java:73)
	  at net.minecraft.server.Bootstrap.bootStrap(Bootstrap.java:47)
	  at net.minecraft.client.main.Main$$Lambda/0x0000026ae55eeb68.run(Unknown Source:-1)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	  at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:-1)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	  at java.lang.Thread.runWith(Thread.java:1596)
	  at java.lang.Thread.run(Thread.java:1583)
```

I would argue that if another class, like `EntityType`, needed to be loaded to complete the static initialization of `Items` that it is dependent on it. Therefore Forge should interpret `EntityType` as being loaded before `Items`. However the order is being determined by whoever calls `MappedRegistry#markKnown()` first. Since some items are registered before triggering the static init of `EntityType`, e.g. `Items.AIR`, the registry `minecraft:item` is calling `markKnown()` before the registry `minecraft:entity_type`; which affects `MappedRegistry#getKnownRegistries()`.

Mojang seems to be confirming this order in `EntityType` during the initialization of boats. In the entity builder, they are providing an item in `boatFactory` but it's wrapped in a `Supplier`, which is the same as what Forge trying to compensate for, but for items.

Alongside `MinecartItem`, you'd also need to create a special constructor for `BoatItem`, `FoodOnAStickItem`, `HangingEntityItem`, and `ItemFrameItem` should entity types be registered after items in Forge.

**Comment by Jonathing** [comment]
We already do field redirection for similar classes with this issue, like `BucketItem`, where we have patched in constructors that take suppliers. It's entirely possible that we'll have to do that for `MinecartItem` and its counterparts as well. The underlying issue is also the reason why `ForgeSpawnEggItem` (or whatever its called) exists in the first place. Could we look at this as a point for a potential future registry rework where we delete `DeferredRegister` or even Forge registries?

In any case, just doing the patch and CoreMod for this item and the others you mentioned is the easiest solution.

**Comment by LexManos** [comment]
The CORRECT way to do it would be to have registry objects all use holders/suppliers and be order independent. 
That just results in chasing Mojang doing weird things. So it makes updating annoying.
You're right, in theory if we made it last-seen it should solve the issue where Mojang's code does things in order dependent.

So just as a test, I made it last-wins for markKnown.
Which resulted in the following diff:
```diff
--- first.txt
+++ last.txt
@@ -1,56 +1,56 @@
 	minecraft:root
 	minecraft:sound_event
 	minecraft:fluid
-	minecraft:block
 	minecraft:attribute
-	minecraft:mob_effect
 	minecraft:particle_type
-	minecraft:data_component_type
+	minecraft:mob_effect
+	minecraft:block
 	minecraft:enchantment_effect_component_type
-	minecraft:item
+	minecraft:data_component_type
 	minecraft:entity_type
+	minecraft:item
 	minecraft:game_event
 	minecraft:potion
 	minecraft:block_entity_type
 	minecraft:stat_type
 	minecraft:custom_stat
 	minecraft:chunk_status
 	minecraft:rule_test
 	minecraft:rule_block_entity_modifier
 	minecraft:pos_rule_test
 	minecraft:menu
 	minecraft:recipe_type
 	minecraft:recipe_serializer
 	minecraft:position_source_type
 	minecraft:command_argument_type
 	minecraft:villager_type
 	minecraft:villager_profession
 	minecraft:point_of_interest_type
 	minecraft:memory_module_type
 	minecraft:sensor_type
-	minecraft:schedule
 	minecraft:activity
-	minecraft:loot_number_provider_type
+	minecraft:schedule
 	minecraft:loot_score_provider_type
-	minecraft:loot_function_type
+	minecraft:loot_number_provider_type
 	minecraft:map_decoration_type
 	minecraft:loot_nbt_provider_type
+	minecraft:loot_function_type
 	minecraft:loot_pool_entry_type
 	minecraft:loot_condition_type
 	minecraft:float_provider_type
 	minecraft:int_provider_type
 	minecraft:height_provider_type
 	minecraft:block_predicate_type
 	minecraft:worldgen/carver
-	minecraft:worldgen/feature
 	minecraft:worldgen/structure_processor
+	minecraft:worldgen/feature
 	minecraft:worldgen/structure_placement
 	minecraft:worldgen/structure_piece
 	minecraft:worldgen/structure_type
 	minecraft:worldgen/placement_modifier_type
 	minecraft:worldgen/block_state_provider_type
 	minecraft:worldgen/foliage_placer_type
 	minecraft:worldgen/trunk_placer_type
 	minecraft:worldgen/root_placer_type
 	minecraft:worldgen/tree_decorator_type
 	minecraft:worldgen/feature_size_type
```

**Comment by MrCrayfish** [comment]
> The CORRECT way to do it would be to have registry objects all use holders/suppliers and be order independent.

Agreed. Guess we'll have to wait and see what they do in future updates. It would remove a lot of headaches.

Obviously with this new change (https://github.com/MinecraftForge/MinecraftForge/commit/bd4b059c2ba602886a07c2a62c5eb7c6a715da67), things like `ForgeSpawnEggItem` should be reconsidered.

**Comment by LexManos** [comment]
Ya, it could be a pass done during an update cycle to simplify patches/utility methods to make things unordered.
Tho I would like to see everything go the other way I'm just getting tired of waiting for mojang and then small issues like this popping up. So cleaning up/simplifying Forge is a good idea.
