### ISSUE TITLE
Installation script checks the wrong client jar-file

### ISSUE THREAD

**Issue by Shoxx98** [MinecraftForge/MinecraftForge#10173]
**Minecraft Version:** 1.20.6 and 1.21.3 - others untested

**Forge Version:** 1.20.6 and 1.21.3 - others untested

**Logs:** cannot open logs from the java application.
logs from the terminal: 
```
Processor failed, invalid outputs:
    /home/uname/.minecraft/libraries/net/minecraft/client/1.21.3/client-1.21.3-official.jar
      Expected: 5313fdeba1c1c39418c3e712d77b1e86e70c0876
      Actual:   bbd67a6abb0b2dfcac78723320f74f3358e450ef
There was an error during installation
```

**Steps to Reproduce:**
 1. execute the install script after minecraft installation

**Description of issue:**
the install script runs into the error described above with a 1.21.3.jar and a 1.21.3.json being present in the directory `/home/uname/.minecraft/libraries/net/minecraft/client/1.21.3`

**Comment by Jonathing** [comment]
Delete the jar and run the game with that vanilla version from Minecraft Launcher. Then try running the installer again. Right now it just looks like you have a corrupted install.

**Comment by Shoxx98** [comment]
I tried that and it did not work. Because you mentioned a corrupted install, I also tried reinstalling the client and that did not work either. In the beginning of the install script it also fails to find a lot of classes. I channeled the whole output into a file, which I attached. I hope this helps. 
[forge.log](https://github.com/user-attachments/files/17812961/forge.log)

**Comment by LexManos** [comment]
Join our discord and send me your /home/uname/.minecraft/libraries/net/minecraft/client/1.21.3/client-1.21.3-official.jar
I think the issue is your system's zlib version is broken/non-standard. We've never been able to reproduce the issue on any other system. So if you could provide your zlib version as well that'd be useful.
Other options to get things working is to just run the installer in a docker container/other machine with a non-broken zlib and copy it over.

**Comment by Shoxx98** [comment]
there is no client-1.21.3-official.jar. There is only ever a 1.21.3.jar.
I tried to install zlib and I already had zlib-ng-compat installed, so you are right with that. I cannot, however, install pure zlib as I seem to have some dependencies that disallow an installation.

Edit: It seems like this is a cachyos optimization thing. I would not like to swap this out for anything else, because the description makes it seem like it performs better: "zlib replacement with optimizations for next generation systems - 32-bit (zlib compat)"

**Comment by LexManos** [comment]
Well you can try changing it, and then changing it back. To see if it is indeed the zlib install being weird.
And like I said, to get it to work you could try running the installer in a docker or on another machine. If the files exist the installer won't remake them.

**Comment by Shoxx98** [comment]
you were right, installing zlib did fix the issue.

**Comment by darkphan** [comment]
This is going to continue to be an issue as more linux distros switch over to zlib-ng. The checksums/hashes will differ between jars made with zlib vs zlib-ng (and even between versions of zlib if/when it updates per one of the contributors to the zlib-ng project). I have to imagine that this could easily be mitigated on Forge's side by changing how the verification is done during the install.

**Comment by Jonathing** [comment]
I am running Fedora 40. How can I simulate this new zlib environment?

**Comment by LexManos** [comment]
The various tools that are used during installation have already had the theoretical fix applied. But nobody on our end can reproduce this issue so there is no way to test it.

And sure we could "change how the verification is done". What do you suggest? I eagerly awaiting your PR and explanation on why your solution is better then the current one.

**Comment by itzg** [comment]
@LexManos if you want a way reproduce it, refer to https://github.com/itzg/docker-minecraft-server/issues/3770 using the image variant itzg/minecraft-server:java21-graalvm

In fact, I'm about ready to dump the graalvm variants. They've been nothing but trouble.

**Comment by Jonathing** [comment]
The issue shouldn't have anything to do with GraalVM. If it wasn't difficult to reproduce, this wouldn't be as much of a problem. The best reproduction docker container would be minimal and only containing the libraries (zlib-ng) that can reproduce this issue reliably.

For context on my personal experience: my primary operating systems for the past two years have been Nobara (Fedora) Linux 40-42, and recently switched to CachyOS (Arch) last month. Both rolling, using bleeding-edge packages in some cases, and I have not once encountered this issue in a way where I can properly reproduce it.

**Comment by itzg** [comment]
...hmm maybe I could swap out the zlib packages at image build time 

https://github.com/itzg/docker-minecraft-server/blob/master/build/ol/install-packages.sh

rather than using whatever crap Oracle put there by default. That doesn't help the broader user base, but would be glad to be a guinea pig for potential solutions.

**Comment by Jonathing** [comment]
I appreciate whatever help you're willing to give. But like I said, a minimal docker container would be best to isolate exactly what is causing the issue.

**Comment by itzg** [comment]
Sorry, I should have clarified. It's not about GraalVM but rather it's the one Java base image I have to deal with that is based on Oracle Linux. If you want a minimal image, it's `container-registry.oracle.com/graalvm/jdk:21-ol10`

**Comment by Jonathing** [comment]
Please continue discussion of issues with Installer and zlib-ng-compat in MinecraftForge/Installer#80.
