### ISSUE TITLE
[1.21.3] Custom block model geometry is not baked

### ISSUE THREAD

**Issue by MrCrayfish** [MinecraftForge/MinecraftForge#10178]
Fairly simple, `BlockGeometryBakingContext#bake` is missing from `BlockModel` patches.

**Comment by LexManos** [comment]
Really need to figure out how to write game tests for the rendering stuff.
The main issue during the update was the removal of the override system in vanilla which caused a lot of these patches to get wonkey.
I dont have any tests for this so I can't be sure it works correctly. But I can patch in the function call.
