### ISSUE TITLE
Screen flickering when i use forge

### ISSUE THREAD

**Issue by kurox313** [MinecraftForge/MinecraftForge#10191]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.4.6

**Logs:** https://gist.github.com/nawinlol3211/8221c53b8990b9fafaa9ced8c65b6e09

**Steps to Reproduce:**
 1. run minecraft running forge
 

**Description of issue:** soo, i can use vanila and fabric perfectly fine, no problem, except for forge, i reinstalled java, used some arguments that shows the same results, changing the settings for javaw in the Nvdia control pannel, deleting .minecraft and ms minecraft, nothing works soo if you could help it would be really nice, my friend has no problems but i do

**Comment by LexManos** [comment]
1) use the discord to do basic tech support
2) remove all mods and see if its stil the case your log is nothing but essentials errors so that would be a good place to start.
