### ISSUE TITLE
ItemTintColors & ItemModelProperties (conditional, select, rangeselect)

### ISSUE THREAD

**Issue by Corail31** [MinecraftForge/MinecraftForge#10200]
**Minecraft Version:** 1.21.4

**Forge Version:** 54.0.6

**Description of issue:**
Hi, i wanted to know if something could be done to improve how to add ItemModelProperties in 1.21.4.
Do we have to use AT to access the ID_MAPPER to put new entries ?
In comparaison (and sorry in advance for making comparaison), Neoforge has some events in the bootstrap of ConditionalItemModelProperties/RangeSelectItemModelProperties/SelectItemModelProperties.
Thanks you for reading me.

**Comment by LexManos** [comment]
Please don't make comparisons to that group, you know the history and you know i don't like "but they have it so you have to do it" arguments.

However yes if there is a needed and it isn't a major burden matinance wise we can design something. What exactly are you referring to? I don't have access to my dev machine until Monday so I can't look into it now. So any specifics you can supply for when I do get a chance would be most helpful.

**Comment by Corail31** [comment]
ItemModelProperties like 'fishing_rod_cast' uses a MapCodec in 1.21.4 (and we can't use ItemProperties.register() like in 1.21.3-.
The events in the 3 types of ItemModelProperties(ConditionalItemModelProperties, RangeSelectItemModelProperties, SelectItemModelProperties) would just put the entry in ID_MAPPER.

By looking further, the Item Tint Colors are also missing an event in 1.21.4 (ItemTintSources.class) unlike in 1.21.3- (except if i missed something in code).

![item_model_properties](https://github.com/user-attachments/assets/8ffb91db-6e76-40d0-becb-dffd9d42320e)

**Example for ItemModelProperty:**
In assets/tombstone/items (which contains json describing the tint color & item model properties)
```
{
    "model": {
        "type": "minecraft:condition",
        "on_false": {
            "type": "minecraft:model",
            "model": "tombstone:item/memorial_plaque"
        },
        "on_true": {
            "type": "minecraft:model",
            "model": "tombstone:item/engraved_memorial_plaque"
        },
        "property": "tombstone:is_engraved"
    }
}
```
In code (about memorial plaque being engraved or not which changes the item model):
```java
    @OnlyIn(Dist.CLIENT)
    public record IsEngravedItemProperty() implements ConditionalItemModelProperty {
        private static final MapCodec<IsEngravedItemProperty> MAP_CODEC = MapCodec.unit(new IsEngravedItemProperty());

        @Override
        public boolean get(ItemStack stack, @Nullable ClientLevel level, @Nullable LivingEntity entity, int p_388905_, ItemDisplayContext context) {
            return EngravableHelper.isEngraved(stack);
        }

        @Override
        public MapCodec<IsEngravedItemProperty> type() {
            return MAP_CODEC;
        }
    }
```
**Example for ItemTintSource:**
In assets/tombstone/items
```
{
    "model": {
        "type": "minecraft:model",
        "model": "tombstone:item/lollipop",
        "tints": [
            {
                "type": "tombstone:lollipop_color"
            },
            {
                "type": "minecraft:constant",
                "value": 16777215
            }
        ]
    }
}
```
In code (about a lollipop having a colored part 'tombstone:lollipop_color' in layer0 and a white part 'minecraft:constant' in layer1)
```java
    @OnlyIn(Dist.CLIENT)
    public record LollipopColor() implements ItemTintSource {
        private static final MapCodec<LollipopColor> MAP_CODEC = MapCodec.unit(new LollipopColor());

        @Override
        public int calculate(ItemStack stack, @Nullable ClientLevel level, @Nullable LivingEntity entity) {
            return ARGB.opaque(ItemLollipop.getColor(stack, 0));
        }

        @Override
        public MapCodec<LollipopColor> type() {
            return MAP_CODEC;
        }
    }
```

**Comment by LexManos** [comment]
Are these codes ever used over the network? I know they added some stuff to item nbt that allow control of client side models. So I just want to be sure. 

If they are sent over the network then we need to bundle them in the handshake and DR system.

If they are not sent over the network then my guess would be that we need to make sure the LateBoundIDMapper is bound after the event is fired. Or we rebind it when the backing map changes. Again don't have my dev environment so will look into it when I get home.

But seems simple enough.

**Comment by LexManos** [comment]
So Looking into it, these codecs don't seem to care when things are added.
```java
    @GameTest(template = "forge:empty3x3x3")
    public static void tint(GameTestHelper helper) {
        var ID_MAPPER = ItemTintSources.ID_MAPPER;

        ID_MAPPER.put(rl("test"), Test.CODEC);

        var expected = new Test(10);

        var encoded = ItemTintSources.CODEC.encodeStart(JsonOps.INSTANCE, expected).result().orElse(null);
        if (encoded == null)
            helper.fail("Failed to encode test value");

        var found = ItemTintSources.CODEC.decode(JsonOps.INSTANCE, encoded).result().orElse(Pair.of(null, null)).getFirst();
        if (found == null)
            helper.fail("Failed to decode test value");

        if (!found.equals(expected))
            helper.fail("Decoded value was not the same as encoded");

        helper.succeed();
    }
```
    
So you can add whatever you want, at any time. So it looks like there doesnt need to be any event for any of these, maybe a AT in Forge for the ID_MAPPER fields. But nothing more then that.

I would just suggest throwing an AT in and shoving the registers into your client setup event.

Unless i'm missing something and you guys have a case where this doesn't work?

**Comment by Corail31** [comment]
As far as i tested before using mixin (for my published version), the models weren't all setup in time (not always the same) by using AT in FMLClientSetupEvent. Unless i made a mistake during my tests but i doubt it (if i remember well, i launched the game 3 times to compare which item didn't have a model in creative tab, then i switched to mixin without wasting additional time on it and everything was fine).
I thought that the objective of Forge was to have events for such things (in the past, most things were done without events, like entity renderers, tile entity renderers, ItemModelProperties, keybinds in 1.16.5-). There were events for rendering things (to finally have the render stages that were finally removed completely in 1.21.3).

**Comment by LexManos** [comment]
The goal isnt to have events for everything. Its to have events/hooks for the things that are nessasary.
Like I jut illustrated. The loading order of your mod doesn't matter. The game test literally runs after the world is loaded and i type the command.
So it's just a matter of you providing a better issue report as i've demonstrated with code you can verify yourself that it works fine.

I have a theory that i may be a threading issue and the map is loosing data if written concurrently, but I doubt that. 

I need more information to know what is wrong before I can give you a solution. As I am having no issues on my end.

**Comment by Corail31** [comment]
I did the test again with AT and the problem is the same. Sometime only one item will have no model, sometime it's nearly all items, never the same (if i enqueueWork or not in the client event, it changes nothing).
I don't think that i can provide a better report than all the comments above. I trust you about your gametest (**even if i don't understand why to test if the codec is able to encode/decode when the world is already loaded**) but in my case, the result is visible so, i don't think that i really need to check code (and not happening with mixin in bootstrap methods).
On the same time, i have a working way to add my ItemModelProperties so, feel free to not add events and close my issue.
Edit: the best that i can do is to send you a version using AT to check by yourself.

**Comment by LexManos** [comment]
Provide a small sample mod that demonstrates the issue you're having.
"Something happens in this big mod" isn't useful.
If you cant provide a small demonstration I can debug myself then it falls on you to use your debugger and figure out why the model isnt loading.
Maybe the issue is a race condition like I said, where you're registering the property after/during the model loading process.

Point is I can't reproduce the issue, and I have demonstrated that the issue doesn't exist on our end. And I have no way of reproducing it with your closed source mod.
