### ISSUE TITLE
Unable to create when using "Install Server"

### ISSUE THREAD

**Issue by Furry-XI-GUA-JUN** [MinecraftForge/MinecraftForge#10207]
forge-1.20.1-47.3.0
I have tried it on many computers and I just can't create the server file.
[forge-1.20.1-47.3.0-installer.jar.log](https://github.com/user-attachments/files/18143527/forge-1.20.1-47.3.0-installer.jar.log)
![屏幕截图 2024-12-16 095755](https://github.com/user-attachments/assets/5c450c95-69f8-467a-942a-1be55ef06c89)

**Comment by Jonathing** [comment]
First off, you can get support in our Discord server. https://discord.minecraftforge.net/

Second, it looks like your computer is blocking access to our files site. I am able to connect to it just fine, so it isn't down. You may need to troubleshoot your internet connection in some way.
