### ISSUE TITLE
[1.19.2] game crashes without a reason

### ISSUE THREAD

**Issue by randomusert** [MinecraftForge/MinecraftForge#10201]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.4.6

**Logs:** doesn't help

**Steps to Reproduce:**
I don't know how it manages to do this
**Description of issue:**
crash on game startup saying that allocating more memory could help to fix the crash, but does nothing and it worked earlier be starting the crahs loop eventually and i didn't touch it

**Comment by PaintNinja** [comment]
To be able to help, we need more than "it crashes on startup" and missing logs.
