### ISSUE TITLE
[1.20.1] Minecraft world won't load after the "reading world data" screen when selected

### ISSUE THREAD

**Issue by MalcolmKicks** [MinecraftForge/MinecraftForge#10272]
Just like what the title says. I have a feeling it might have something to do with the jei-server.toml config file because whenever I open it, it ends up blank, but I could be wrong. I only ran into this error maybe ten hours into my minecraft world, and the funny thing is that it isn't even exclusive to this modpack. I need some help pretty badly. Here's the log file.

[latest.log](https://github.com/user-attachments/files/18247691/latest.log)

**Comment by Jonathing** [comment]
Hello! The GitHub page is not tech support. You're much more likely to get help within the forums or in the #player-support channel in our Discord server.
