### ISSUE TITLE
Crash when players quickly login and logout

### ISSUE THREAD

**Issue by zampa00** [MinecraftForge/MinecraftForge#1117]
full console log: http://pastebin.com/kZh4zWsE
crash log: http://pastebin.com/1gJwMCtN

I found this bug during the first day of my server, which unexpectedly crashed after 30 minutes. Server kept crashing in a couple of minutes after every restart.

We did many tries to understand this bug, and seems to happen when players quickly login and logout.
For the latest test, there weren't mods installed and a new map has been generated for the test.
We tried with 5 players and we managed to crash the server in a short time (our try is in the console log)

**Comment by LexManos** [comment]
Closing as we've never been able to reproduce this in any way.
If you can find a way to reproduce this reliably let us know..
