### ISSUE TITLE
Anonymous recipe classes without a sorting entry cause infinite loops

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/MinecraftForge#1154]
As opposed to actually crashing. The report is a few months late of me finding the solution, but it should throw an error so anyone else doing something similar will know what's going on.

https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/setup/recipe/Vanilla.java#L794
https://github.com/skyboy/MineFactoryReloaded/blob/master/src/powercrystals/minefactoryreloaded/setup/recipe/handler/ShapelessMachineTinker.java#L67

**Comment by LexManos** [comment]
Yup fixed before you reported, Another useless post. 
https://github.com/MinecraftForge/MinecraftForge/commit/fd59ab261f363bff18a2a2a7d10b9534cfdee1ab
