### ISSUE TITLE
[Forge 1.7.10-10.13.0.1157] Title Screen bugged up.

### ISSUE THREAD

**Issue by MariaTheDinkus** [MinecraftForge/MinecraftForge#1185]
Whenever I load up Minecraft with the latest version of Forge for 1.7.10 the Mojang symbol does not show, but it goes to the title screen. However, the title screen looks very buggy. Like this: http://puu.sh/9LCKb/eb3695c5d7.jpg

I have no idea what is causing it, and no mods are installed. I am running Java 7 Update 60. Thanks!

**Comment by reznorms** [comment]
This is happening to me again with forge 10.13.2.1291+, even with "-Dforge.forceNoStencil=true" in the jvm argument (wich worked fine till now). I have an Intel 4500, driver updated all the way up. Log -> https://www.dropbox.com/s/9mh8b070i5gmo4o/fml-client-latest-f1291.log?dl=0

**Comment by LexManos** [comment]
Stencil bits were disabled by default quite a few versions back.
Remove COFH and try again.
You should also update to 1.8.
