### ISSUE TITLE
Crash when using many mods. (Internal Execption: io.netty.handler.codec.DecoderException)

### ISSUE THREAD

**Issue by Yabdat** [MinecraftForge/MinecraftForge#1207]
Not completely sure if this is a Forge issue or what, but whenever I try put together a modpack that's larger than about 55ish mods i get this issue when trying to connect the the dedicated server.

![crash](https://cloud.githubusercontent.com/assets/6392309/3488221/c471874c-04d4-11e4-85b1-c8b4ac80e5a8.gif)

It happens basically no matter what mod I add to the modpack. If I get the problem, disable one mod, it works. If i add another mod with the first one disabled, I get the same  problem connection to the server again. 

EDIT:
Using minecraft 1.7.10 w/ Forge 1160.

**Comment by LexManos** [comment]
FML's network has been re-worked to allow massive S->C packets so this shouldn't be a issue anymore. People are also creating massive packs so I don't think this is an issue anymore. Let me know if it is.
