### ISSUE TITLE
ContainerPlayer.transferStackInSlot does not care about Item.isValidArmor

### ISSUE THREAD

**Issue by Victorious3** [MinecraftForge/MinecraftForge#1230]
This flaw allows equipping armor into armor slots by shift-clicking, even tho it shouldn't be possible due to it not being a valid armor.

**Comment by LexManos** [comment]
Looking into it more it does actually care about isValidArmor because transferStackInSlot -> mergeItemStack -> isItemValid -> isValidArmor.
