### ISSUE TITLE
Texture Glitch - GUI

### ISSUE THREAD

**Issue by artdude543** [MinecraftForge/MinecraftForge#1261]
I have thoroughly tested this before posting this issue, but it appears the 1.7.10 version of forge is causing a transparency bug with the "tab_inventory". This seems to effect many resource packs as I've tested a few and they all have the same transparency problem.

In plain Vanilla 1.7.10 this bug does not exists but if I add forge the issue displays. I used an instance with just forge (10.13.0.1189) and a few resource packs. You can see from the screenshot here: http://i.imgur.com/cpJyWwY.png (Soartex Fanver) the background should be transparent but its not. With Sphax the background is display with a white background and the same for some other packs I've tested.

I double checked the textures are in the correct formats and full RGB so this is not the fault of the textures, but seems something in forge is doing something with the textures. Could I have a second opinion on what could be causing this?

If you need more information or logs just ask and I can get some.

**Comment by goldbattle** [comment]
Seems that I run into this problem with just vanilla `1.7.10` and forge `10.13.2.1277`. It seems that that the alpha layer is not being respected properly when rendered. Was this ever figured out @artdude543 @LexManos ? I have had a couple people bring it up to me.

**Vanilla:**
![2015-01-03_14 08 44](https://cloud.githubusercontent.com/assets/2222562/5603409/39786fd6-9352-11e4-8d96-6e09b8f5de8c.png)

**Forge:**
![2015-01-03_14 10 11](https://cloud.githubusercontent.com/assets/2222562/5603410/40f105f2-9352-11e4-9f5c-3cd6331e3257.png)

Using the main JSTR pack build for 1.7.x from [here](http://js-legacy.net/jstr-modded/)

**Comment by Qohelethh** [comment]
I'm having the same problem. Is there a fix?

**Comment by LexManos** [comment]
Works fine on the current version. And from last I looked at it in 1.7, the alpha transparency that the texture pack is taking advantage us is actually a vanilla BUG with leaking GL state, all over the place.
