### ISSUE TITLE
Adding ClientChatSendingEvent

### ISSUE THREAD

**Issue by Moonrise1275** [MinecraftForge/MinecraftForge#1299]
Yeah, we have a ClientChatReceivedEvent
Then why no sending one?

Actually, I'm making a simple client side irc mod.
It will be so useful for me, but why not useful for someone else?

**Comment by williewillus** [comment]
Roll into #1442

**Comment by Actuarius** [comment]
@williewillus closed this issue

**Comment by ghost** [comment]
#3543
