### ISSUE TITLE
NetHandlerPlayServer crashes when a GUI has no slots.

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/MinecraftForge#1354]
The bottom of `net.minecraft.network.NetHandlerPlayServer.processPlayerBlockPlacement(C08PacketPlayerBlockPlacement)` accesses the number of a slot without first checking to see if the slot is null (indicating the gui not having any slots); there are likely many more similar issues, but I do not know where they are.

**Comment by KingLemming** [comment]
This is still present in 1.8.9. Algo's analysis is correct.

**Comment by LexManos** [comment]
The container should have the slots for the players inventory should it not? So how can this return null?

**Comment by skyboy** [comment]
Not all inventories have slots, at all. Like Thermal Expansion's Tesseract. There are even uses for presenting slots, but not the player's inventory: such as a GUI that shows *another* player's inventory (in the form of admin commands, typically).

**Comment by LexManos** [comment]
As there is nothing in vanilla that can reproduce this.
And there hasn't been a mod provided to reproduce this.
But I can see some potential for this.
I've got a patch that MIGHT work but no clue as again there is no way to reproduce this.
