### ISSUE TITLE
Entities that are a "part" of an entity need an interface to define them as such

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/MinecraftForge#1357]
e.g., `EntityDragonPart`, or the various "part" entities for bosses in the TwilightForest, and so on. Not being to detect these things uniformly causes a wide range of x-mod bugs.

**Comment by mezz** [comment]
At least in 1.11, `EntityDragonPart` is basically an interface for parts, it's just named poorly.
It takes in an `IEntityMultiPart` parent, so nothing about it is dragon-specific except the name.
There is an MCP issue open here to fix it: https://github.com/ModCoderPack/MCPBot-Issues/issues/307
