### ISSUE TITLE
No event fired when water "washes away" a plant or block that is destroyed by water

### ISSUE THREAD

**Issue by Niadel** [MinecraftForge/MinecraftForge#1369]
There appears to be no event fired when a water block destroys, or "washes away", a block. Seeing as there aren't many uses for blocks being washed away, I can understand it not being included until now, but this topic at http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/2195876-small-problem-with-events-and-spawning-mobs has an issue with a breaking event not firing when the plant is washed away by water. 

I personally consider it a type of BreakEvent, but I understand that there's no way to get a player for when the BlockEvent.BreakEvent event fires. Perhaps a new type of event, likely extending BlockEvent and called something like BlockWashedAwayEvent, could be fired? Unfortunately, I'm unable to find the code which is in charge of water destroying plant-like blocks, mainly because the source code I have is still largely SRG names in the liquid related classes, which actually makes it harder to read than the original obfuscated code (and I have dependency related issues with Gradle that makes me unable to use ForgeGradle), rendering me unable to do a pull request, so it's probably best if someone else did it.

**Comment by mezz** [comment]
This issue is very old without any progress or support so I am closing it.
If anyone still wants this, please open a pull request or a new issue.
