### ISSUE TITLE
Issue with DummyConfigElement<String>

### ISSUE THREAD

**Issue by XcentY** [MinecraftForge/MinecraftForge#1380]
I will name DV = the defaultValue sets in the constructor
I will name RDV = the realdefaultValue
I will name CV = the currentValue
I will name DummyV = the DummyConstructorValue

let's say you add DummyConfigElement to you class GuiConfig

new DummyConfigElement<String>(String name, String defaultValue, ConfigGuiType Type, String langkey, String[] validValues);

first the so said DV is not really the defaultValue. It's the value displayed when  you enter on the config screen. (As there is not RDV set, it uses it as his default)

void cpw.mods.fml.client.config.DummyConfigElement.set(Object value)
[Property] Sets this property's value.
Specified by: set(...) in IConfigElement

Then you think that set() is "set this property's value". however, when you look at the method

@Override
public void set(T value)
{
defaultValue = value;
}

So the method set() sets the RDV and not the property value.
You can check by constructing the DummyElement with one value in the constructor and another in the .set method

(It was very useful to be able to have real interaction)

Object cpw.mods.fml.client.config.IConfigElement.get()
[Property] Gets this property value.

Then there is the get() method. You may think it will retrieves the actual property value. However in the constructor it sets it as follow.
this.value = defaultValue;

So when you construct the element, it takes what you put as DV to sets his DummyV and if you use the .get method it will always retrieves this DummyV instead of the value you have on screen. You may click as many times you want, you'll always have the same DummyV

Object cpw.mods.fml.client.config.IConfigElement.getDefault()
[Property] Gets this property's default value. If this element is an array, this method should return a String representation of that array using Arrays.toString()

You may think that getDefault() will give you the DV or the RDV but the behavior of this method is very strange. When you click the control to have another value, getDefault() gives you the CV
If you don't click the control and you didn't use the set method, it gives you the DV. and if you don't click the control and you use the set method, it gives you the RDV

The best way I found to get the CV of this control DummyConfigElement was like this
String MyValue;
CycleValueEntry cycleEntry;
List listEntries = this.entryList.listEntries;
for(Object object : listEntries) {
   if (object instanceof CycleValueEntry) {
      cycleEntry = (CycleValueEntry) object;
      MyValue = cycleEntry.getCurrentValue();
   }
}

Which return always the good current value (CV) of the control. That you click or not on it. That you set another default with the set() method.....

There is something wrong with the DummyConfigElement but I found my way around it and now I'm using it to set another property value so the user can't play around with my property value ^^

**Comment by LexManos** [comment]
Wall of text, but what im getting from it is that you want to use the DummyConfigElement as a non-Dummy. Well no that's not gunna happen it's meant to be a fake element that is just there for show.
If you can provide code for exactly what you want without having 10 different definitons of words then I can take a look again, but my understanding is this is a complaint stemming from your misunderstanding what this class is for.

**Comment by XcentY** [comment]
This is typically the type of answer I dislike. "this is a complaint stemming from your misunderstanding what this class is for". Actually, it has been a long time (almost 2 years) without an answer.... so your answer is a little bit borderline... And for what I remember, I made my way into this class to make a customUI because the elements available for a customGui at that time were not sufficient while there was some examples of custom UI controls showed on Forge Mod Config Screen that were not available for direct use. However now, it's almost 2 years and we moved to new versions ==> Of course you can close it but your last statement is rude in regard of the effort you put to understand after a so long time.
