### ISSUE TITLE
gradlew wont run

### ISSUE THREAD

**Issue by jcranky** [MinecraftForge/MinecraftForge#1415]
When I run

```
./gradlew setupForge
```

(or that with any task, it doesn't matter) I get the following error:

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

Now, if I install gradle locally and use that instead, gralde runs and downloads stuff.

**Comment by ewm2000** [comment]
I just ran into this problem. Where would i go for the working files(Sorry but i dont know what a submodule is )

**Comment by diesieben07** [comment]
The advice given here is no longer relevant, as Forge and FML are no longer separate projects.
