### ISSUE TITLE
Rendering creative tabs bug with enchanted item

### ISSUE THREAD

**Issue by TheJulianJES** [MinecraftForge/MinecraftForge#1417]
Images: https://imgur.com/a/Gils7
Code: http://pastebin.com/eYJHBZat

When you have that, achievements render wrong, too. Hope you fix it, hope it is an forge bug and not a vanilla bug! ;)

**Comment by Rukachan** [comment]
This issue seems to have been reintroduced since I can reproduce it in 1448 and 1558 while using enderio.

**Comment by Adaptivity** [comment]
Known. https://github.com/MinecraftForge/MinecraftForge/issues/2075
