### ISSUE TITLE
FluidStacks are holding an ID instead of the Fluid

### ISSUE THREAD

**Issue by OvermindDL1** [MinecraftForge/MinecraftForge#1419]
You know how ItemStacks save the reference to the Item instead of the ItemID, in order to sync them properly and such yes?
FluidStacks... do not, they hold the ID...
NEI seems to be breaking on that when going between single and multiplayer or between different single worlds...  No doubt other issues but this is the first noticed.

**Comment by LexManos** [comment]
When serialized fluids should be storing based on Name. ID is only for network traffic.
If this is still a issue in 1.8 let me know. Work is being done on a generic name registry system that i'll hook into controlling the fluids, potions, biomes, etc...
