### ISSUE TITLE
EntityLivingBase ignores NBT when rendering held items with multiple render passes

### ISSUE THREAD

**Issue by SimonMeskens** [MinecraftForge/MinecraftForge#1439]
In EntityLivingBase:

    @SideOnly(Side.CLIENT)
    public IIcon getItemIcon(ItemStack p_70620_1_, int p_70620_2_)
    {
        return p_70620_1_.getItem().requiresMultipleRenderPasses() ? 
            p_70620_1_.getItem().getIconFromDamageForRenderPass(p_70620_1_.getItemDamage(), p_70620_2_) : 
            p_70620_1_.getIconIndex();
    }

When there's multiple render passes:
- Get the Item
- Try rendering from Item damage and render pass

When there's just one render pass:
- Get the icon index from the ItemStack

In the case of multiple render passes, this means that the stack and thus all NBT is dropped in favor of trying to render from Item Damage. This means that all mods that have items that do NBT-dependent multi-pass rendering (for example, Tinkers Construct), have to write a completely useless item renderer, just so they get access to NBT.

The very simple fix:

    @SideOnly(Side.CLIENT)
    public IIcon getItemIcon(ItemStack p_70620_1_, int p_70620_2_)
    {
        return p_70620_1_.getItem().requiresMultipleRenderPasses() ? 
            p_70620_1_.getItem().getIcon(p_70620_1_, p_70620_2_) : 
            p_70620_1_.getIconIndex();
    }

**Comment by Adaptivity** [comment]
@LexManos shouldn't occur on Forge 1.8. Related to: https://github.com/MinecraftForge/MinecraftForge/issues/1593 So, you can close it.

**Comment by Adaptivity** [comment]
@cpw since 1.7.10 supported again, can you fix it, if it is not hard? The fix should be so: add
*@@ -1373,1 +1409,1 @@
-        return p_70620_1_.func_77973_b().func_77623_v() ? p_70620_1_.func_77973_b().func_77618_c(p_70620_1_.func_77960_j(), p_70620_2_) : p_70620_1_.func_77954_c();
+        return p_70620_1_.func_77973_b().func_149673_e(p_70620_1_, p_70620_2_);*
after line 179 in EntityLivingBase.

**Comment by williewillus** [comment]
getColorFromItemStack in 1.8+ is fully stack aware
Item.getModel (1.8.x) and IPropertyGetters (1.9) are both stack and entity aware

**Comment by Actuarius** [comment]
@williewillus closed this issue
