### ISSUE TITLE
Suggestion: Set Based OreDictionary

### ISSUE THREAD

**Issue by Zot201** [MinecraftForge/MinecraftForge#1446]
Considering a set that does not use standard Object.hashCode and Object.equals, e.g. java.util.TreeSet, it should be acceptable if we integrate the OreDictionary.itemMatches part into the collections.

There are two merits of doing this:

1) Better abstraction. We call OreDictionary.getOres(name).constains(stack) instead of explicit iteration. It could reduce mistakes of common operations around OreDictionary, e.g. wrong boolean value passed to OreDictionary.itemMatches. At the same time, it improves code clarity.

2) Constant running time. We can organize each ore entry into two types: wildcard and non-wildcard. It would results in two collections with proper hashing. Instead of doing an O(n) matching iteration, we do O(1) performing at most two lookups each time.
<br/>

There are many simple and powerful ways to achieve these goals. And I have created a Gist for reference:
https://gist.github.com/Zot201/9eb62e337f254c34fd58

The Gist contains an implementation for OreDictionary with methods substituted with Set outputs, together with an inverted view of the mapping utilizing Guava Cache. Just in case, Feel free to take my code regardless of whether Set based OreDictionary is going into Forge or not. (Perhaps I am going to use it personally with OreRegisterEvent for some of my new mods that access OreDictionary extensively.)

**Comment by DarkGuardsman** [comment]
Not to revive an old post but this should be considered as a solution for Ore Dictionary not having NBT support.

**Comment by mezz** [comment]
This seems nice, but I think using ItemStack as a key should be avoided whenever possible.

To do something like
```java
OreDictionary.getOres(name).constains(stack)
```
you just have to do 
```java
int oreId = OreDictionary.getOreID(name);
int[] stackOreIds = OreDictionary.getOreIDs(stack);
ArrayUtils.contains(stackOreIds , oreId);
```

The performance characteristics are not ideal, but you're not iterating over millions or IDs, more like 1 or 2.
Maybe a helper method could be added to make sure people use it correctly?

**Comment by DarkGuardsman** [comment]
If you implement a HashMap and something like an ItemStackWrapper https://github.com/BuiltBrokenModding/VoltzEngine/blob/development/src/main/scala/com/builtbroken/mc/prefab/items/ItemStackWrapper.java if would work out with O(1) performance given some modifications. 

As well handlers could be registered to deal with the problem rather than forge itself. As a hash table would only work for small NBT value and would have difficulties with massive NBT entries. Plus a handler has the added benefit of allowing more complex logic. Such as the ItemStack containing an NBT value that is the ore name.

**Comment by mezz** [comment]
I understand that you want better performance characteristics, but this is not a performance bottleneck.
Maybe you are comparing O(1) to O(n), but in this case `n` is something between 1 and 5.

**Comment by DarkGuardsman** [comment]
I was not arguing against your point just offering two alterative designs. Plus it is good to keep in mind n may not be between 1 and 5. As I have mods I write that use NBT heavily resulting in potentially 32000^types if I implemented ore dictionary support. Take [Armory Mod](https://github.com/BuiltBrokenModding/Armory), for example, that uses json processing to load guns into the game. It uses a mix of metadata and nbt to support functionality. If I were to implement ore dictionary it would result in `n = meta * weapon part configuration * ammo configurations`. Give or take the number of combinations required to offer different ore dictionary values for recipe crafting.

**Comment by mezz** [comment]
The ore dictionary does not look at NBT.
n is the number of oredict tags on an item, not the number of items in the ore dictionary.
The lookup for the oredict tags on an item is already a map, `stackToId`.
