### ISSUE TITLE
Java runtime shutdown hooks stopped working with Forge 1210 (proposed fix posted)

### ISSUE THREAD

**Issue by bilde2910** [MinecraftForge/MinecraftForge#1468]
Shutdown hooks added with `java.lang.Runtime.getRuntime().addShutdownHook(Thread hook);` are interrupted after a few milliseconds. Try for yourself with:

```java
java.lang.Runtime.getRuntime().addShutdownHook(new Thread() {
    @Override
    public void run() {
        for (int i = 0; i < 10000; i++) {
            try {
                System.out.println(i);
                Thread.sleep(1L);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
});
```

This will add a shutdown hook that, after game exit, will count from 0 to 9,999, incrementing one every millisecond. Take a look at how far it gets. For me, it got to 3 before it simply stopped. Results vary by the CPU of the executing machine. Try removing the thread sleep, it will count finer numbers. (273, 279, 315, different each time.) In Forge 1208 and earlier, it would count all the way to 9,999. It is worth noting that this functionality did not work in 1.6.4 either, but something happened on the way to 1.7.2 so that it worked again on that version. I am not sure if that is related to Minecraft itself or Forge.

3 ms is not nearly enough time to do pretty much any task more complicated than looping `System.out.println(i);` 300 times. There's a reason shutdown hooks exist. I suggest that hooks are either made to work again, or that an event is added which offers the same functionality as shutdown hooks. Shutdown hooks normally run *after* any *normal* program termination (i.e. `System.exit();`, pressing the red X to close the game, but **not** terminating the Java process, forcibly shutting down the computer, etc).

A Java application should not mess with Java to disable shutdown hooks. Plugins/mods that add them do so for good reasons, and there *are* mods which rely on shutdown hooks for core functionality.

**Comment by LexManos** [comment]
So doing research into this, first thing is, 1) Mods shouldnt be writing to System.out/err ESPECIALLY if it's in a shitdown thread it should be writtent o file or something.
2) If you MUST do this you can edit the log4j.xml to invlude  shutdownHook="disable" in the Configuration folder. OR pragmatically remove L4J's shutdown hook. Either way i'm going to say this is the modder's responsibility if they are doing something after the jvm is ending.

**Comment by matthewprenger** [comment]
What would probably be more helpful is a GameExitingEvent. The only event we have that comes close to that is ServerStopping/Stopped, but they can fire multiple times on the integrated server.
