### ISSUE TITLE
Forge energy interface

### ISSUE THREAD

**Issue by immibis** [MinecraftForge/MinecraftForge#1482]
There are quite a few mods that include blocks which consume energy, but "don't really care" about the different energy systems. These mods tend to use Redstone Flux API, designed by the CoFH team. Like any other non-Forge API, this sometimes leads to incompatibilities - particularly when the API changes, or when mods are updated to new Minecraft versions before Redstone Flux is. These mods also tend to have an internal buffer of energy, which they draw from directly, and which is replenished from outside sources.

Given the variety of energy systems, would it be a good idea for Forge to have an API *only* for the purpose of energy-system-implementors interfacing with energy-system-agnostic blocks? The API would consist of only one interface, to be implemented by tile entities which can accept energy, with two methods, similar to `double getNominalPowerDraw();` and `double offerEnergy(double amount, ForgeDirection side);` (with the latter returning the amount of energy actually consumed).

This issue is for discussion; I have not written any code yet, as this API would be more complex politically than technically (all that is required is one interface). If there is a consensus that it this proposed API is desirable, I will submit a pull request.

**Comment by Madsthunder** [comment]
So... Is anybody going to close this issue?

**Comment by ghost** [comment]
**forge should start with creating an electric cable/wire at first**

**Comment by mezz** [comment]
No sorry, this is the wrong place for that discussion.
