### ISSUE TITLE
Forge needs a cross instance backup of all registry ID's

### ISSUE THREAD

**Issue by da3dsoul** [MinecraftForge/MinecraftForge#1496]
A common problem since updating to 1.7 is the renegotiation of ID's in world saves. Add a mod and they all get shifted, remove a mod and they get shifted. Then, the world crashes because BlockConstructionMarker cannot be cast to BlockCullinaryFurnace. The example is sort of made up, but not really because it happened. There needs to be a file "PreviousAssociatedIDs.csv" or something so that if a mod is removed and readded, all of the blocks and items will always receive the same ID's. What if you remove a mod and never put it back and do the same repeatedly? Wouldn't the file get too big? Then delete it and let forge remake it, or be less lazy and edit it to remove the old mods that won't be used again so ID's don't get messed up after your worlds become dependent on it from repeated mod changes. It is a csv, ie a fancy text/excel file.

Put basically:
1. Create a file when mods are loaded and ID's are assigned. "PreviousAssociatedIDs.csv"
2. If a mod is added or removed, renegotiate ID's and then check PreviousAssociatedIDs.csv for differences.
3. When loading a world, give 2 options: Load the world with Previous Associated ID's and don't change the saved ID's (not safe); Repair the world with new ID's. Meaning swap all ID's matching in PreviousAssociatedIDs.csv with the new negotiated ID's in the world chunk data, then load the world.
4. Have an option to use the old style where any ID's (and TileEntities) not vanilla are removed from the world at load and let you start clean to avoid mod update conflicts.

This will prevent world corruption from mod updating, adding or removing mods, and prevent the loss of morale to play minecraft when you finally update COFHCore like it keeps bugging you to, to find that the entire world is now broken and there are so many errors you can't track them down. Then finding out the errors are because there is a Buildcraft quarry tileentity where a TE energy cell now is....
I've ignored this because you would expect a problem this important would be fixed quickly. It hasn't, and there isn't any technical documentation of the problem either, so now there is, and now there is a possible solution well thought out as well. Why don't I do it? Because I work full time and keep other mods updated on top of life and anime...and because I'm simply not familiar enough with Forge's core code to just sit down and do it. I've spent hours just analyzing the code there to see how it is already done, and now I'm tired and need to go to work.

**Comment by mezz** [comment]
I think this changed in recent versions, and Forge is no longer reusing old IDs.
Can you confirm, @cpw ?

**Comment by Madsthunder** [comment]
This should be fixed now, since objects are now shifted and dummied according to the previous ids associated with each object on a per-save basis.

**Comment by VladimirMangos** [comment]
Maybe possible add some way world protection against lost blocks at mods remove?
For example, map removes blocks at detection at Minecraft start to ore dictionary equivalents. This will prevent corruption surface and underground in game. Replace any stone types by plain stone, any ore by iron or coal, liquids by water, etc.

**Comment by LexManos** [comment]
Not gunna happen.
Blocks are replaced by Air dummy blocks. And if the mod is re-added it will attempt to remap those blocks to the ones from the mod.

As it sits, the registry system has been re-written and should be fairly robust now. As stated if you remove things from the world, Forge will detect it and warn you, and potentially make a backup of the world. There isn't anything more that needs to be done.
All the 'corruption' issues you've run into in the past are due to BAD MODS screwing with the Registry system. There is literally nothing we can do about that so if it happens be sure it's not a mod misbehaving.
