### ISSUE TITLE
Disable backup feature on mod changes

### ISSUE THREAD

**Issue by Slind14** [MinecraftForge/MinecraftForge#1505]
Hey,

is there any way to disable the backup feature which comes with the `/fml confirm` when a mod has been removed?

On a high end computer it takes about 40 minutes to create this backup although the world is only 12gb big. When doing the backup my self it is done in 1-2 minutes (fully done, no kernel backend tasks). 

I do fully understand this feature and think it is one of the best for the average user but with big worlds and a lot of experimenting it does cause a lot of long forced breaks.
If there is no way atm, I would like to suggest adding a small jvm argument that does allow to disable the backup feature the same way the auto confirm is done. :)

**Comment by Badcholo** [comment]
How would that look in a .bat file? just wondering.

**Comment by vpontin** [comment]
@Badcholo put this arg in the launcher profile.

**Comment by robin4002** [comment]
@Badcholo 
```java -Xmx1G -Dfml.doNotBackup=true -jar <forgeServerJarName>.jar```

**Comment by Badcholo** [comment]
Thanks

**Comment by ghost** [comment]
Is there any way do this without using a script? I am on a VPS and can't use scripts to do anything. Also, can't have it auto confirm as a result.
