### ISSUE TITLE
1.8: java.lang.IllegalStateException: TickNextTick list out of synch

### ISSUE THREAD

**Issue by Kobata** [MinecraftForge/MinecraftForge#1515]
```
Time: 11/26/14 11:17 AM
Description: Exception ticking world

java.lang.IllegalStateException: TickNextTick list out of synch
    at net.minecraft.world.WorldServer.tickUpdates(WorldServer.java:613)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:226)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:763)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:669)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:171)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540)
    at java.lang.Thread.run(Thread.java:745)
```

Full log: https://dl.dropboxusercontent.com/u/71722326/logs/fml-client-TickNextTick%20list.log

Occurred about 10 seconds after creating a new creative world for testing. Attempting to load that world after restarting the client led to a `ConcurrentModificationException`: https://dl.dropboxusercontent.com/u/71722326/logs/fml-client-CME.log

**Comment by Gaelan** [comment]
This is happening to me on a 1.9.4 dedicated server. The server starts up normally, then crashes around fifteen minutes later. As far as we can tell, there is no explicit player action that triggers it. I'm aware there are coremods; I will see if I can reproduce without them when I get a chance. However, I just want to put it out there that this is still occurring.

[Crash Report][crash]
[Log][log]

[crash]: https://gist.github.com/Gaelan/db9a3ff61b1bfc2b7efbaea64b84895e
[log]: https://gist.github.com/Gaelan/f01ea61f08e0314c359f758655e22839

**Comment by LexManos** [comment]
Remove your mods and try and reproduce.

**Comment by hea3ven** [comment]
It's my fault, see: https://github.com/hea3ven/BuildingBricks/issues/73

**Comment by Gaelan** [comment]
@hea3ven You! It's those grass slabs. I never trusted them. They just weren't natural. Seriously though, thanks for saving me some hair-pulling and server-restating.
