### ISSUE TITLE
1.8: Villager houses "appearing"

### ISSUE THREAD

**Issue by lumien231** [MinecraftForge/MinecraftForge#1525]
Not sure whether i should post this because i can't repeat it right now but whenever i teleported / spawned to a location villager houses rendered all around me. They don't actually exist and render a fixed distance away from me. When i rotate my player the ones in the middle fade away and new ones appear at the sides. After about 5 seconds they also fade into the background and nearly vanish till i teleport somewhere again.

![2014-11-27_19 58 19](https://cloud.githubusercontent.com/assets/3648306/5221014/425c07b0-7670-11e4-9f19-b01b1cb11eae.png)
![2014-11-27_19 57 50](https://cloud.githubusercontent.com/assets/3648306/5221015/425d56ba-7670-11e4-87b3-30af17b11fb6.png)

**Comment by LexManos** [comment]
I'm going to close this and categorize it along with the driver bug that was causing it to appear as if vanilla was re-rendering large chunks in the distance.
This can most likely be fixed by updating your graphics drivers, this is nothing on Forge's end causing this.
