### ISSUE TITLE
[1.8] Brewing stand ejects all contents when an water bottle is inserted.

### ISSUE THREAD

**Issue by KJ4IPS** [MinecraftForge/MinecraftForge#1536]
What I expected to Happen:
Inserting a water bottle into the brewing stand with a valid ingredient should begin the brewing process

What Happened:
When a water bottle was inserted into any of the three slots on a brewing stand, the gui was closed, and all items in the gui were dropped upon the ground

Steps to Reproduce:
1. Place a brewing stand, and open it's GUI
2. (optional) place a valid brewing item in the upper slot of said stand
3. place a water bottle into any of the appropriate slots
4. Observe the reaction

Observed on forge v11.14.0.1247 in both deobfuscated, and obfuscated environments with no extra mods loaded

**Comment by Thog92** [comment]
@LexManos is this fixed? No response? Too old version?

**Comment by LexManos** [comment]
Its fixed a long time ago -.-
