### ISSUE TITLE
1.8 Pillars in the end are not being generated

### ISSUE THREAD

**Issue by VikeStep** [MinecraftForge/MinecraftForge#1538]
Steps to reproduce:
1. Create new world
2. Visit End
3. See that there are no pillars (therefore no ender crystals and an easy to kill dragon)

Screenshot of newly generated end:
![Screenshot](http://i.imgur.com/eWBa9dn.jpg)

Is it reproducible? Yes
Forge: 1.8-11.14.0.1247
No other mods, created on a fresh install.
This does not occur on a vanilla 1.8 instance

**Comment by VikeStep** [comment]
Not sure what changed fixed it, but I have just tested in the latest update and end pillars are being generated. So I am closing this issue

**Comment by LexManos** [comment]
Sorry, I missed over this one I think. Good to know it works :P Probably was fixed in one of the early 1.8 builds.
