### ISSUE TITLE
[1.8] Swimming up in water kicks for flying

### ISSUE THREAD

**Issue by 14mRh4X0r** [MinecraftForge/MinecraftForge#1545]
Swimming up in water for more than 3 seconds triggers the fly kick.
Using Forge 11.14.0.1251 server, vanilla 1.8.1 client

**Comment by EnderStar** [comment]
This bug is present in the latest forge: 1290 for 1.8
Reopen this thicket

**Comment by psxlover** [comment]
The ticket was never closed...

**Comment by utoxin** [comment]
Definitely still happening. Ran into it during a UHC match I ran a couple weeks ago. Would love to see this get fixed.

**Comment by LexManos** [comment]
It has been fixed. https://github.com/MinecraftForge/MinecraftForge/commit/f0d96b7c50cb1aceb101c5e9c0d78806b87e1240

**Comment by Krenath** [comment]
It has not.  It is back for 1.9.
