### ISSUE TITLE
[1.8/1.7.10] Array index out of bounds when retrieving information about mod-generated biome types

### ISSUE THREAD

**Issue by Blackjak34** [MinecraftForge/MinecraftForge#1550]
This is not a duplicate of issue #1326, the issue is still present. Adding a new Type through BiomeDictionary.Type.getType doesn't set the new length of typeInfoList large enough because the array length is set to the ordinal of the new enum when it should be set to ordinal+1. Adding one type, oddly enough, doesn't seem to cause the exception but adding two new types and then calling BiomeDictionary.getBiomesForType on the second type generated will reproduce it.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/1935
