### ISSUE TITLE
[1.8] BlockFluidClassic.flowIntoBlock() doesn't set the block.

### ISSUE THREAD

**Issue by kirderf1** [MinecraftForge/MinecraftForge#1552]
In "BlockFluidClassic.flowIntoBlock(World, BlockPos, int)", it never replaces the block on the new position with the fluid, but instead directly tries to change the property "BlockFluidBase.LEVEL" on the block state, no matter what kind of block that was there before. (And that way crash the game)

**Comment by TechStack** [comment]
I've encountered the same crash as this on build 1290.
Was a PR/ fix ever done to correct the issue?
I'm newer to modding so I'm not sure if should try a PR just yet but it sounds like from what @asiekierka is saying that we just need to implement BlockState on the BlockFluidClasic

**Comment by TechStack** [comment]
Correction that is not the solution. the methods for getMetafromState Etc are already defined in the super class BlockFluidBase.

It appears that in BlockFluidClassic that Flowintoblock () method currently as :   

 protected void flowIntoBlock(World world, BlockPos pos, int meta)
    {
        if (meta < 0) return;
        if (displaceIfPossible(world, pos))
        {
            world.setBlockState(pos, world.getBlockState(pos).withProperty(LEVEL, meta), 3);
        }
    }


is not first setting the block to the Fluid block instead it is taking the blockstate for the current block in this case air and changing it's metadata value / Level property.

changing 
            world.setBlockState(pos, world.getBlockState(pos).withProperty(LEVEL, meta), 3);
to read more like  may fix it
            world.setBlockState(pos, this.getBlockState().withProperty(LEVEL, meta), 3);

this should cause it to set the block its flowing into into the fuild with the proper fluid level defined.


So how do we do PR for forge? 
I'd want to follow the standard & best practices.
Is there a guideline somewhere?
