### ISSUE TITLE
Packets being transmitted or received incorrectly

### ISSUE THREAD

**Issue by AtomicStryker** [MinecraftForge/MinecraftForge#1570]
As reported here, comments 1075+: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284359-atomicstrykers-infernal-mobs-diablo-style?page=54

Some more information here: http://www.minecraftforum.net/forums/support/modded-client-support/2297822-1-8-client-and-server-crash-error-on-a-forge-1-8

Interesting logs on serverside when this happened: http://puu.sh/dqjZ4/78dcb1fc2f.png
Client crashlog: http://pastebin.com/ZwHVfvKa

The packet code being used has been unchanged and working since 1.7.2, only the imports were fixed for 1.8.

https://code.google.com/p/atomicstrykers-minecraft-mods/source/browse/InfernalMobs/src/main/java/atomicstryker/infernalmobs/common/network/NetworkHelper.java?name=1.8
https://code.google.com/p/atomicstrykers-minecraft-mods/source/browse/InfernalMobs/src/main/java/atomicstryker/infernalmobs/common/network/HealthPacket.java?name=1.8

May or may not require 2 players to reproduce, i could not reproduce it. But 2 seperate people have reported issues.

**Comment by LexManos** [comment]
Packet handeling has been re-worked quite a bit seince this report please post again if this is reprodueable in the current versions.
