### ISSUE TITLE
[1.8] Client player sometimes NULL if packet sent from EntityJoinWorldEvent

### ISSUE THREAD

**Issue by coolAlias** [MinecraftForge/MinecraftForge#1583]
Previously I have used EntityJoinWorldEvent to send an update packet to the client player with extended property data that will be needed on the client side with never a problem; now, however, about half the time when I receive the packet the client player is null, and the other half it works as expected, as though sometimes the client is not loaded by the time this event fires.

Perhaps EntityJoinWorldEvent was never meant for this behavior (that's what PlayerLoggedInEvent is for, which I will be using shortly), but it always worked before and doesn't now, so there may be something wrong in the background.

**Comment by Tarig0** [comment]
There is an nbttag called persistent data that will stay with the player through death

**Comment by coolAlias** [comment]
Sorry, Tarig0, that is not a solution for complex extended entity properties, and DataWatcher just sends packets in the background anyway.

The client player has always been valid upon receiving a packet from EntityJoinWorldEvent before, and it is probably a bug that this is no longer the case.

**Comment by LexManos** [comment]
Packets are processed on a network thread now, NOT synced with the world thread.
Thus anything you send that interacts with the world may not of happened yet.
So, check your threads and adapt.

**Comment by coolAlias** [comment]
Thanks for the explanation Lex, that makes sense.

For the issue I mentioned above, I am just null-checking the client player and sending a packet from both events (duplicate packet traffic the first time a player logs in, but it is the only somewhat sensible way I could think of to get it to work).

Is there a preferred way of ensuring that the world thread is up to date when a packet is received?

**Comment by diesieben07** [comment]
You'd do something similar to what Minecraft already does in their packet handling methods. They check the thread and if it's not the main thread, they exit and enqueue the packet to be handled again on the main thread.

**Comment by coolAlias** [comment]
Guess I'll have to take a closer look xD Thanks for your response.

**Comment by diesieben07** [comment]
Not every packet needs to be handled on the main thread.
But yes, the way vanilla does it is... weird at best.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/FML/blob/e3785c28930a218cf9374458c67c34e7fba17922/src/main/java/net/minecraftforge/fml/common/network/internal/EntitySpawnHandler.java#L35 is how FML takes care of things for now. Feel free to emulate, or suggest something better.

**Comment by coolAlias** [comment]
Thanks to both of you - here's mine, which also attempts to allow a reply message (none of my packets return a reply, so that bits untested for now):
https://github.com/coolAlias/DynamicSwordSkills/blob/1.8/src/main/java/dynamicswordskills/network/AbstractMessageHandler.java

It seems that SimpleNetworkHandler#channelRead0(ChannelHandlerContext, REQ) could be a possible location at which to centralize thread checking, if that were something worthwhile.

Seems that all of the vanilla packets wait for the main thread before processing, but if you can think of examples where one wouldn't care which thread processed the packet, then it wouldn't make sense to centralize.

**Comment by LexManos** [comment]
No, we're not going to lock networking to the world thread, that would defeat the point.
As for 'all vanilla packets' doing it, most do yes, but I'm blaming that on just legacy stuff and them not actually updating the packet handlers to be thread safe yet.

**Comment by coolAlias** [comment]
Ah, good points. Guess it's finally time for me to go study up on thread safety... Thanks again.
