### ISSUE TITLE
[1.7.10 - 1277] AnvilUpdateEvent - output not valid when event.cost = 0

### ISSUE THREAD

**Issue by VapourDrive** [MinecraftForge/MinecraftForge#1618]
While subscribing to the AnvilUpdateEvent regardless of what conditionals you have, or the event priority, the output cannot be removed from the anvil if the cost is either unspecified or set specifically to 0;
I tried removing the output while in creative, and survival, neither of which worked.
If the event cost is set to something greater than 0 the anvil "recipe" works perfectly fine.
I would assume that this also affects 1.8 unless something greatly has changed with the anvil mechanics.

**Comment by LexManos** [comment]
return (playerIn.capabilities.isCreativeMode || playerIn.experienceLevel >= ContainerRepair.this.maximumCost) && 
    ContainerRepair.this.maximumCost > 0 && this.getHasStack();

Seems that vanilla doesn't allow for the cost to be zero as it uses that to signify that it is empty.
