### ISSUE TITLE
Installer disturbs pathnames with ü in it

### ISSUE THREAD

**Issue by Wuerfel21** [MinecraftForge/MinecraftForge#1620]
it will install propertly, but all game paths with ü in them get disturbed to some randomnes

**Comment by Victorious3** [comment]
There is a simple solution: NEVER use any non ascii character in your path names. Use ue instead. Or avoid it and use English in the first place.

**Comment by chylex** [comment]
Pretty sure that if you have special characters in your user profile (which is possible), then the advice of "never use non ascii characters in path names" is pretty much useless because it cannot be simply renamed, and it doesn't fix the actual problem.

**Comment by Wuerfel21** [comment]
Meh, im forced to have it in my pathname...

**Comment by chylex** [comment]
On Windows, all Minecraft is stored in AppData which is inside the user profile. Don't know which system you are using, but all I was saying is that Victorious3's simple solution is not actually a proper solution, and it's definitely not simple.

**Comment by Victorious3** [comment]
@Wuerfel21 Why are you not called 'Würfel21' then? It's always a good idea to not use any of those characters, especially when it comes to path names as a lot of older and/or incomplete programs will have problems with it, be it on the functional side or only the display aspect. But you are right, adding support for it might be useful, if only for completeness. Especially in your case as yes, the name of the user directory cannot be changed easily.

**Comment by Wuerfel21** [comment]
I meant profiles are stored in launcher_profiles.json and the installer is only supposed to mess with the versions folder

**Comment by diesieben07** [comment]
The installer creates / updates the Forge profile.

**Comment by Wuerfel21** [comment]
Does anybody ever use that?
If this cant be fixed easyly, i request some kind of checkbox to turn that off

**Comment by diesieben07** [comment]
The versions folder would still be in your user profile...

**Comment by Wuerfel21** [comment]
The problem is that my launcher_profiles.json gets messed up, so i need to manually fix all game paths, after that it works, e.g the files are in the correct folders, my game just dont works afterwards.
So i recommend adding a defaultly non-checked checkbox, that if checked, adds the profile, else leave launcher_profiles.json alone.

OR just friggin fix your JSON lib!!!

**Comment by Lunatrius** [comment]
The vanilla launcher uses `Charset.defaultCharset()` and the Forge installer uses `Charsets.UTF_8`. Works fine if I save the profile file with UTF-8 before installing Forge.

**Comment by LexManos** [comment]
Will keep that in mind, however, this is not a FORGE issue this is a INSTALLER issue, please file in the correct place.
However, utf8 should work, unless the launcher is loading things in a different character set.
