### ISSUE TITLE
1.7.10 (1277): Cannot log in to a non-byte dimension

### ISSUE THREAD

**Issue by keybounce** [MinecraftForge/MinecraftForge#1621]
Attempting to log in to a dimension above 127 (using Mystcraft) gives an error looking for the wrong dimension -- the error is that of the 2's complement of the dimension as a byte. For example, attempting to log into 128 fails to find -128; attempting to log into 129 fails to find -127.

java.lang.IllegalArgumentException: Could not get provider type for dimension -127, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:237)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

Xcw said this is probably a forge issue, not a mystcraft issue.

Full client log: https://gist.githubusercontent.com/keybounce/efc388cb9ef15530af81/raw/28c1303aed50a96fc3920cc5dfcd2798045e7430/fml-client-latest.log

**Comment by cazzar** [comment]
Looking through [here](http://wiki.vg/Protocol#Join_Game) it seems that minecraft itself is limited to the byte dimension number, though, this is inconsistant throughout the page, since, int appears a few times.

**Comment by keybounce** [comment]
If accurate, then yes, the vanilla login protocol would only permit byte dimensions at login. Which matches the idea that maps only permit byte dimensions. Oddly, the "teleport you to a dimension" permits integers.

For vanilla, with only 3 dimensions, it isn't an issue.
For Forge, which permits more, since a vanilla client cannot log on to a forge server, perhaps forge should change the wire login protocol to use integer instead of byte.

I know Lex has said that the map issue is WONT FIX. I understand that it doesn't actually kill play. Being unable to log in, however, does kill play.

**Comment by Kubuxu** [comment]
In my opinion 253 additional dimensions are enough for any application. Changing it would also break compatibility with vanilla protocol.

**Comment by laz2727** [comment]
640_kb.txt

2015-01-04 15:53 GMT+06:00 Jakub Sztandera <notifications@github.com>:

**Comment by keybounce** [comment]
First, I would point out that in 1.4.7, dimensional doors would define a new pocket dimension every time it generated one of it's worldgen structures, whether used or not (had to -- each door had to know where it would go if used). 

Second, I would point out that we now have two different mods that dynamically create dimensions on demand -- RFTools and Mystcraft -- and on a server, 250 extra dimensions across a world of players will be used up very quickly.

Third, the problem actually happens at +128. Unless forge is going to change how it hands out dimension ID's so that after +127 you get -128 -- which could be done, but would be a different fix -- then you only have about 125 additional dimensions.

Fourth, between mods that give us multiple flavors of hell, RPG mods that give us 5+ dimensions at once, storage dimensions, magical dimensions, creeper dimensions, forest dimensions, etc, adding new dimensions is something that a lot of people want to do.

Fifth, we already ran out of biomes. And block ID's. We expanded block ID's from 256 to 4096 -- and people still have to use meta-data or tile entities to house all their blocks even if they have little to nothing in common.

I am aware that this would break vanilla compatibility at login. Forge servers don't let vanilla clients log in. It would be trivial to say "We don't care about compatibility with people that can't log in". If Forge did this, then maybe Mojang would modify vanilla to follow suit.

Or, and this is crazy talk, maybe if Forge wanted to permit vanilla clients to log in if the server only has server-side mods, then maybe forge could first log them into a "temporary" spot, and after logging in, then teleport them to the actual location.

In fact, that is probably doable right now, without any protocol changes. If you would log into a dimension that is outside of -128, +127, then you are logged into a "limbo" world, that is just a superflat, single layer of bedrock; and, once the client is logged in, then you are moved to the full word actual location.

**Comment by Lunatrius** [comment]
A possible fix for this would be a special cased dimension ID. If the dimension ID is not between -128 and 127, send the special cased ID and append the actual ID as an int to the end of the packet. When reading the packet vanilla will ignore the extra int, while Forge can use the additional int.

It's really just an idea - it may work, it may go horribly wrong.

**Comment by jk-5** [comment]
That will not work. Last time i checked vanilla mc will throw an error when all packet data is not fully read

**Comment by Lunatrius** [comment]
Yeah... just checked and it's (still) there. Oh well, was worth a shot.

**Comment by rich1051414** [comment]
Couldn't forge just use it's own packet? Vanilla clients cannot log into forge servers anyways if I am not mistaken.

**Comment by diesieben07** [comment]
They can in 1.8

**Comment by Eurymachus** [comment]
I do wonder why a vanilla client would want to log in to a forge server?

Additionally,  Little blocks mirrors a dimension ID for every real world dimension so yes Dim IDs will fill up fast. 

I like the limbo idea.  (Should be default behaviour imo)

**Comment by diesieben07** [comment]
Vanilla Clients can log into a forge server (with server-only mods of course) for the same reason you can log into bukkit with a vanilla client.

**Comment by LexManos** [comment]
The thing is, we simply do not have the room in the packet to add any more numbers, there is nothing but hackery bullshit we can do about that.
One potential solution is to find out where all 'dimension bytes' are sent across the network and prefix those packets with a 'next time you read a dimension use this number instead' packet.
Which is well.. bad because it would cause a lot of issues with anyone else who happens to be listening on the network, let alone vanilla clients that are connecting.
And yes, vanilla clients are supported in 1.8+.
So, figure out a solution that isn't complicated and crazy and takes into account all the locations dimensions are set, and we may be able to do something.

**Comment by rich1051414** [comment]
That is a troublesome one indeed. The only sane solution(depending on how loosely your definition of sane is) would be a fallback to requiring forge if the dimension ID exceeds the vanilla limitation. Then forge could just use its own packet instead if more than a certain number of dimensions are required, possibly with an option to force it to mods which dynamically allocate dimensions?

**Comment by LexManos** [comment]
How do you propose to actually implement that forcing...
Implementation is a lot of this.

**Comment by Tarig0** [comment]
It is probably safe to put some code in the code the registers/loads a dimension.

'''java
If (!isDimensionPoolOutsideVannila) && (dimid < -127 || dimid > 127) isDimensionPoolOutsideVannila = true
'''

after this you can send a unhandled packet to the vanilla client to boot them off the server

**Comment by keybounce** [comment]
Rather than booting the vanilla client off, have Forge reserve a dimension for login assistance.

[quote]Or, and this is crazy talk, maybe if Forge wanted to permit vanilla clients to log in if the server only has server-side mods, then maybe forge could first log them into a "temporary" spot, and after logging in, then teleport them to the actual location.

In fact, that is probably doable right now, without any protocol changes. If you would log into a dimension that is outside of -128, +127, then you are logged into a "limbo" world, that is just a superflat, single layer of bedrock; and, once the client is logged in, then you are moved to the full word actual location.[/quote]

If the dimension that someone wants to log into is outside of the byte range, then log into the special reserved dimension, and then teleport them to the real dimension.

As long as there is at least one unused dimension in the byte zone for Forge to claim, this should work, right?

**Comment by Tarig0** [comment]
As long as it's just the login packet, I don't see why not, looking at the protocol linked before looks like this is true.

if the flow is

userloginpacket
accept login
Respawnpacket

I don't see why you cant have the player moved to wherever you need them to reside till the respawnpacket comes in, say couple of miles above build limit in the overworld

**Comment by Eurymachus** [comment]
I haven't peaked at the code yet (will do when I get home) so I'm just spit balling here, isnt the issue witht the acceptance of the packet on the 'non forge' vanilla client side? Of which the server has no direct control of?

If you teleport a player on a vanilla client to a dimension < -127 or > 127 won't same result occur?.....

**Comment by Eurymachus** [comment]
Thus, kicking the player and requesting they add forge to their lovely new Mojang MC launcher would be the preferable course of action?

**Comment by laz2727** [comment]
Forge could always lie to the client about what id that dimension has.

**Comment by Lunatrius** [comment]
@Eurymachus Nope. The dimension is stored as an int and written/read as a int in the respawn packets. The login is the only place where it's sent over as a byte from what I can tell.

**Comment by Eurymachus** [comment]
Got you!  Stupid :D
the only way to allow a vanilla client is to indeed log the client in to facade dimension and instantly transport them to the correct dimension. 

I am curious though, are there actually server side mods that manipulate dimensions past the byte allowance?

**Comment by keybounce** [comment]
@Lunatris: Maps also use a byte to identify the dimension.

Server side mod that manipulates dimensions: Multiworld. Static list of predefined dimensions and at least some worldgen options/control. Since it has no limit, you could exceed a byte's worth. 

Note that it defines a cross-dimensional teleport command, but not any items or blocks; a vanilla command block can be used to move you around.

**Comment by radfast** [comment]
> I am curious though, are there actually server side mods that manipulate dimensions past the byte allowance? 

Galacticraft currently adds 5 static dimensions for its planets (ids -26, -27, -28, -29, -30).  We offer an API so that add-on writers can create additional planets with new dimension ids, there are maybe 10 of those currently and guys are writing more.  Our mod will also - similar to Mystcraft - dynamically create and add a new dimension every time a player creates a Space Station.  These Space Station dimensions are given the next available positive id starting at 2, and skipping any id already in use.  On a large public server, you can easily have dimensions 2-70 or more in the saved map.  For a long-running map on a server there would be more and more dimensions as time passes, it would be possible to get up to +127.

[A note on performance: Obviously not all those 70 dimensions are loaded simultaneously, it depends where the players are who online are at.  Anyhow, loading multiple dimensions is not much overhead for a server over and above the normal overhead of loading all the chunks in a radius around the player.  I would argue server overhead is actually __less__ if players are in different dimensions, because the size of "whole world" lists like World.getLoadedEntityList() will be smaller in each different dimension.  Servers get slow if there are hundreds of players and thousands of entities all in the same dimension, because parts of the Minecraft code have an execution speed corresponding to N squared, where N is the size of World.getLoadedEntityList().  So Galacticraft is actually helping server performance by adding more dimensions :) ]

**Comment by Calenria** [comment]
>The thing is, we simply do not have the room in the packet to add any more numbers, there is nothing  but hackery bullshit we can do about that.

Has this changed in 1.7.10? In older versions (1.4-1.6), we have 500-1600 mystcraft worlds per server (each player gets his own world) and no problems.

**Comment by LexManos** [comment]
Mystcraft does hackery stuff that rewrites how worlds are transferred IIRC.

**Comment by XCompWiz** [comment]
"Mystcraft does hackery stuff that rewrites how worlds are transferred IIRC."
I do?  I don't touch how worlds are transferred at all.  At most I send some extra data for rendering the world correctly, but that's along my channel and as one of my packets.

Did we not change the data type for dims in other packets already (in Forge)?  Why is this one different?  Has that all been changed in vanilla now, and this is a remnant?

**Comment by radfast** [comment]
Can I suggest that in Mystcraft whenever new dimensions 128-255 are created as an int, it uses the 2's complement 8-bit value instead.  At least that way players will not encounter the problem until there are more than ~252 new dimensions, instead of ~126 new dimensions as at present.

I'm certainly thinking that's what we will do now in Galacticraft.

**Comment by XCompWiz** [comment]
That's not a fix, and scarcely a workaround. It also poses some weird complexities.  If the problem exists of creating 126 dims, then the problem will exist of creating ~100 more.  Not worth the trouble, not worth doing it weirdly, not worth having locked yourself in once this IS fixed.

Mystcraft is going to do the most logical thing, and trust in Forge to handle this kind of issue.  It's not up to mods to handle this kind of problem, and doing so is more likely to create unnecessary complexity and thus more problems.

Now that I have more time to read over this, I see that it is desired that vanilla clients be able to connect to Forge servers.  That does mean we can't change the size or structure of packets.

That particular requirement actually may make it impossible to fix this, meaning we might be dependent on getting vanilla to fix it.  If Dims > 128 work in other packets, then they should be amicable to getting it fixed here.

That said, this problem can't happen on a vanilla client.  It won't have the dimension manager, anyway.
I don't think vanilla clients can connect to Forge servers which have additional dimensions.  In that regard, we can send a different packet on login.

**Comment by radfast** [comment]
Fair points.

How about this: in could Forge add a string representation of an integer to the end of the "Level Type" string in S01PacketJoinGame, and then pull that integer out of the Level Type string before the vanilla code does anything else with the string?

**Comment by XCompWiz** [comment]
As said, the requirement of vanilla clients connecting means we can't play with the payload of a packet. I'm not sure if we can add things to the end or not, though.  It might be an option.
We certainly can't add to that string, as a vanilla client wouldn't parse it correctly.  At least, I wouldn't expect it to, and it might not always even if it would under the current code.

**Comment by radfast** [comment]
I edited my post.  Add nothing to the string where the player is in a vanilla dimension.  Add something only the player is in a non-vanilla dimension (which a vanilla client will error on anyhow).

**Comment by keybounce** [comment]
To my knowledge, there are three places where dimensions are transferred to the client: login, maps, and teleport. Of those, only teleport permits an int instead of a byte.

Maps has been brought up before, and is WONTFIX.
Any solution to login will therefore result in two types of dimensions, with one able to be mapped, and the other not.

So the first conclusion: When you ask forge for a new dimension, you need to ask for a mappable or a non-mappable dimension.
The issue with login can be resolved with no special change to the login protocol, by logging you into a special, low-numbered dimension first, and then teleporting you to the real location.

**Comment by radfast** [comment]
Please can you link to the maps discussion.

**Comment by XCompWiz** [comment]
That's *a* fix, Keybounce, and perhaps a valid one, but using a special packet for large dims is also a fix, as is specializing the packet handling in that case.
Maps *used to be* fixed; we used to change that packet to handle the larger dim id.  Hence my confusion here.

**Comment by radfast** [comment]
I found the old PR for maps now: https://github.com/MinecraftForge/MinecraftForge/pull/153

**Comment by keybounce** [comment]
When I brought up the issue of Maps earlier with Lex, he mentioned that fixing it would break compatibility with vanilla clients, and that if vanilla did something on the network a given way, forge would not change it.

I know that for 1.8, vanilla clients using a forge server is not just a goal, but now the reality -- so I would not ask for anything that would change the network protocol.

So, yea, how/when/what is this about maps being fixed?

**Comment by XCompWiz** [comment]
A long time ago....  I haven't looked lately, but I remember being involved in finding all the places dim ids were referenced to help fix it.  I even did the map fix, I think.  At least once (though that might have been before I was on Forge, my memory is rather non-temporal).

**Comment by radfast** [comment]
> I found the old PR for maps now: #153

:)

**Comment by XCompWiz** [comment]
Yes.  That was it. :P  Indeed, a long time ago.

**Comment by radfast** [comment]
@XCompWiz  a related question for you: in Mystcraft does the server send the client a packet at login with data on which Mystcraft dimensions have been created on the server?  And if so, have you had compatibility issues with BungeeCord recently?  If not, how do you handle the problem of a server logging a client in in a dimension which the client does not yet know exists?
https://github.com/micdoodle8/Galacticraft/issues/1164

**Comment by McJty** [comment]
I don't know how Mystcraft solves it but RFTools has the same problem and indeed I solve it by sending over all dimension information right after the client connects.

**Comment by heldplayer** [comment]
> The issue with login can be resolved with no special change to the login protocol, by logging you into a special, low-numbered dimension first, and then teleporting you to the real location.

Or, make the packet always send the overworld ID (except for the end/nether) and send the actual dimension ID right after using a forge or FML packet for any dimension not in vanilla.

Alternatively, if a dimension ID is out of bounds for the packet, use 0 and then send the actual ID with another packet.

**Comment by LexManos** [comment]
@XCompWiz As you're the main mod out there as far as I know that adds 'infinite' dimensions, And I trust you for most things. Write something up and propose it.
The main problem is we cant edit any network packets. And no appending to the end of the packet is not an option as it screws up a bunch of things in testing. {Vanilla, and 3rd party tools}.


The 'send a fake dim ID and then send a custom packet with the real one' is the only feasible option. But it doesn't take into account telling the client about the dimensions descriptors {world type stuff that affects client side like rendering} It also is not conducive to vanilla clients so there would need to be severe protection on the server side to make sure vanilla clients can't access those dimensions.
Also, delaying the client side long enough for the second packet to get there with the extra information may be a pain. At Least doing it in such a way that doesn't need massive changes to the vanilla code base.

Is it a problem? Yes, Is it a major one? Not really. Most people don't have hundreds of dimensions. And getting it right with vanilla compatibility needs work.
So feel free to start writing stuff, but like always no promises on anything being pulled. I'm putting Xcomp 'in charge' if anything needs to happen. He's to poke me about anything thats been thought through and tested.

**Comment by XCompWiz** [comment]
Understood.
We'll have to keep vanilla clients out of mod dims, anyway, as they wouldn't have WorldProviders for them.  We can also add a sanity check to log in vanilla clients to the Overworld if they are "out of vanilla bounds," just in case.

I'll see how small I can keep the changes.  I have a solution which might work nicely.  I will PR it once happy with it.

If others have concerns or thoughts I encourage you to bring them to me, so I can be sure we cover everything.

**Comment by cpw** [comment]
Fixed for 1.7.10 : c9fd2b617310fec401b877ad01d96a87a82db6a7
Fix for 1.8 still pending..

**Comment by radfast** [comment]
nice, thank you so much

**Comment by iampyrex** [comment]
Still crashing.

http://pastebin.com/3aBFa2CS

**Comment by liach** [comment]
You should use the latest one in 1.7.10 branch, but not the final build for 1.7.10 on master.

**Comment by keybounce** [comment]
Hmm. Your crashlog says
        FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 160 mods loaded, 160 mods active

But the fix is in 1340, I think. You don't have the latest forge with the fix

http://files.minecraftforge.net/minecraftforge/1.7.10

**Comment by LexManos** [comment]
Server brand: cauldron,craftbukkit,mcpc,fml,forge 
Invalid crash report. This has been fixed in Forge, not whatever random change.
