### ISSUE TITLE
Item.getModel documentation incorrect

### ISSUE THREAD

**Issue by TheGreyGhost** [MinecraftForge/MinecraftForge#1623]
The documentation for Item.getModel parameter useRemaining is not correct.  The useRemaining counts up from zero to maximum, not from maximum down to zero.  Suggest changing to

@param timeInUse The number of ticks this item has been in use, or getMaxItemUseDuration() when not in use.

    /**
     * Player, Render pass, and item usage sensitive version of getIconIndex.
     *
     * @param stack The item stack to get the icon for.
     * @param player The player holding the item
     * @param useRemaining The ticks remaining for the active item.
     * @return Null to use default model, or a custom ModelResourceLocation for the stage of use.
     */
    @SideOnly(Side.CLIENT)
    public net.minecraft.client.resources.model.ModelResourceLocation getModel(ItemStack stack, EntityPlayer player, int useRemaining)
    {
        return null;
    }

**Comment by coolAlias** [comment]
Except that it gets passed "stack.getMaxItemUseDuration() - entityplayer.getItemInUseCount()", just like in Item#onPlayerStoppedUsing, so that it is actually counting down in these cases. Somewhat counter-intuitive, for sure :P

**Comment by TheGreyGhost** [comment]
@coolAlias 

I imagine that's how the bug was introduced - EntityPlayer.getItemInUseCount() counts down from maximum to 0, it doesn't count up from 0 to maximum as the MCP name suggests.

There is another method Entity.getItemInUseDuration() which does count up like you said, and also takes proper account of when the item isn't in use.

So actually maybe it would be better to change the call to 
modelresourcelocation = item.getModel(stack, entityplayer, stack.getMaxItemUseDuration() - entityplayer.getItemInUseDuration());
because otherwise you have to check EntityPlayer.getItemInUse() in getModel yourself.

**Comment by coolAlias** [comment]
My mistake - I didn't look closely at the method name, and thought it was getItemInUseDuration and not getItemInUseCount.
