### ISSUE TITLE
[1.7.10] On our server all of the DIMS show up as loaded when /forge TPS is used.

### ISSUE THREAD

**Issue by BlackJackAres** [MinecraftForge/MinecraftForge#1628]
Ver. Forge 1.7.10
All dimensions are loaded, this includes-
Overworld- MC
Nether - MC
End - MC
Twilight Forest -GCM
Asteroids -GCM
Moon -GCM
Mars - GCM

And it's absolutely butchering out server TPS. I have looked through all the mod .CFG's and such to figure out if any of those are by chance force loading the dims but I haven't come across anything to suggest as much.

Because of this we seem to suffer hourly crashes as out server just runs out of the ability to keep up. It often will display "Can't keep up, 4000MS behind, skipping 83 ticks" etc. etc.

**Comment by DZCreeper** [comment]
What mods are you using? What does your server.properties file have in it?

**Comment by LexManos** [comment]
Forge just displays all loaded worlds, we are not the ones loading them. You probably have some mod installed that is keeping the world loaded.
