### ISSUE TITLE
Bug: Keybind CTRL+Scroll_Lock

### ISSUE THREAD

**Issue by Keridos** [MinecraftForge/MinecraftForge#1636]
Not sure if this is related to Forge, but on Forge Version 7.10.85.1230 I have the issue that CTRL + Scroll_Lock triggers all keybindings that are set to NONE in the keybindings menu. For some reason this just happens on Windows as OS, not on my linux OS.

**Comment by ntzrmtthihu777** [comment]
Wow... what a strange situation.

**Comment by heldplayer** [comment]
A weirder situation is that it does this for me when I change the system volume using a scrollwheel on my headset.

**Comment by LexManos** [comment]
I keep coming back to this issue and testing it out, i can't for the life of me reproduce this.
I have to chalk it up to something is derpy either in lwjgl, or in something higher then that. 
Can't find any way to reproduce. And its such a edge case I don't think it's a real issue.
