### ISSUE TITLE
[1.7] Configurable Lava+Water block replacement

### ISSUE THREAD

**Issue by nicklaslof** [MinecraftForge/MinecraftForge#1639]
Currently the blocks generated when water hits lava (or lava hits water) is hardcoded to Blocks.obsidian, Blocks.stone and Blocks.cobblestone

I'm working on a mod where I want Pumice to be created instead but there is no easy way to do that since stone and cobblestone are hardcoded into BlockLiquid and BlockDynamicLiquid

**Comment by Victorious3** [comment]
Sounds useful to me, more flexibility is always good.

**Comment by LexManos** [comment]
Feel free to make a generic flowing event.
