### ISSUE TITLE
[1.7] Debug/trace not shown in IDE / unable to adjust logger settings

### ISSUE THREAD

**Issue by twothe** [MinecraftForge/MinecraftForge#1643]
When starting the client inside the IDE, then debug and trace log from the developed mod is not shown in the IDE's console log output. It is however written to the log file. There is no documentation (*that I or Google can find) on how to change that, when asked in the forum, no one could answer either.

Expected: Debug/Trace output should be shown during development by default. Logging configuration should be properly documented.

As it currently stands many mod authors just use INFO as log level and if they forget to remove such log entries released versions spam into log files. This is currently an issue with many mods including very popular ones (e.g. Waila). This could be prevented by setting debug/trace to default and documenting how to setup logging.

In addition a downlodable  example logging configuration for debug/trace would allow mod authors to advise users to download and use such file to trace hard to reproduce bugs, and therefore use debug/trace logging for what it was supposed to be used to.

**Comment by LexManos** [comment]
You would have to provide a override [log4j.xml](https://github.com/MinecraftForge/FML/blob/master/src/main/resources/log4j2.xml) that spits things out.

**Comment by twothe** [comment]
Which one would be the logger that I would need to add or modify to get IDE console output to show all debug/trace info of my mod?

And where do I have to put that file so Forge recognizes it?
