### ISSUE TITLE
[1.7.10] Wavefront Object Importer does not allow for integers in obj files

### ISSUE THREAD

**Issue by Tamfoolery** [MinecraftForge/MinecraftForge#1651]
The Wavefront Object Importer doesn't allow for integers in the vertex, vertex normal, or texture coord patterns, only floats. Noticed when trying to import an obj exported from CraftStudio.

Below is (what should hopefully be) a working fix.

```
private static Pattern vertexPattern = Pattern.compile("(v( (\\-){0,1}\\d+(\\.\\d+)?){3,4} *\\n)|(v( (\\-){0,1}\\d+(\\.\\d+)?){3,4} *$)");
private static Pattern vertexNormalPattern = Pattern.compile("(vn( (\\-){0,1}\\d+(\\.\\d+)?){3,4} *\\n)|(vn( (\\-){0,1}\\d+(\\.\\d+)?){3,4} *$)");
private static Pattern textureCoordinatePattern = Pattern.compile("(vt( (\\-){0,1}\\d+\\.\\d+){2,3} *\\n)|(vt( (\\-){0,1}\\d+(\\.\\d+)?){2,3} *$)");
```
Lines 29 - 31 of `net.minecraftforge.client.model.obj.WavefrontObject`

`d+\\.\\d+)` replaced with `d+(\\.\\d+)?)` where appropriate.

Since the tokens are being parsed as floats when they are used, I'm assuming allowing integers shouldn't be a problem.

**Comment by Parker8283** [comment]
Feel free to make a PR :P

**Comment by Tamfoolery** [comment]
PR https://github.com/MinecraftForge/MinecraftForge/pull/1654
