### ISSUE TITLE
A permissions system for Forge

### ISSUE THREAD

**Issue by luacs1998** [MinecraftForge/MinecraftForge#1653]
**This issue is merely for discussion and to gain feedback from modders regarding the introduction of such an API. No code has actually been prepared.**

After having the original Permissions API draft (PR #1403) rejected, I thought I'd start over with designing a Permissions API specification for Forge, seeing as Lex is unwilling to point out what exactly he claims is wrong with PR #1403.

Should a permissions system be prepared for Forge, it will likely exist only to make mods compatible with both Forge-based permission plugins, such as Forge Essentials, and Sponge-based permission plugins, such as PermissionsEx, without having to introduce any 3rdparty dependencies, which could be messy.

The API will be based off what Sponge has, available [here](https://github.com/SpongePowered/SpongeAPI/pull/340), with a few major differences:

- Contexts may or may not exist within any system for Forge.
- Where Sponge has the concept of Subjects, a Forge permissions system will likely just use either EntityPlayers or ICommandSenders, for simplicity.
- A Forge permissions system may or may not be as versatile as anything Sponge or 3rdparty APIs offer.

Any thoughts? Questions? Boilerplate code?

**Comment by JustGregory** [comment]
Actually, are you meaning something that is wholly wrapped into Forge itself, or an individual modular unit, such as is FML being its own part of the overall MinecraftForge install?

First things first, I generally have no interest in playing in multiplayer servers -- except in the interest of testing my own mods. That being said, if it is to be done, I would prefer the latter: something that is part of the total, but separate from the "baseline" Forge experience, and hopefully disable-able by server admins if and when necessary, such as a private server only shared by family or friends.

Second. Need a clarification on the "EntityPlayers or ICommandSenders" part. One mod I'm working on, the original **littleMaidMob** mod, has the helper-maid entities in two parts: the core entity class (a subclass of `EntityTameable`) and a player-like entity (subclass of `EntityPlayer`) with bridging logic connecting the two for online play. The maids use methodology from both EntityTameable and EntityPlayer to function, ... with obvious concerns in operation. Would your submission mean, then, that I would have to code in permissions for these maid-entity-pseudoplayers just to exist in multiplayer?

**Comment by AfterWind** [comment]
Rather than a whole permissions system you can maybe just have the mods register their commands using a unique permission node. That way we can have other mods taking care pretty easily of the permissions. Also some way of registering a new permission manager over over the vanilla one.

**Comment by luacs1998** [comment]
The base idea of such an API is to better connect mods wanting to support permissions, and mods/plugins wanting to provide permissions. It's just a "can X player do this?" method call, returning a boolean.

Such an API would be part of base MinecraftForge and be as unobtrusive as possible. If no permission-providing mod is present, the API just becomes a wrapper around Minecraft's ops system.

**Comment by ezterry** [comment]
This feature request is being discussed in the newer issue: #2899
As such I believe this one ought to be closed (and possible referenced on the newer entry for archival information)

**Comment by Actuarius** [comment]
@diesieben07 added labels [Superseded]
