### ISSUE TITLE
[1.8] OreDictionary does not register new stone types as "stone"

### ISSUE THREAD

**Issue by Anon10W1z** [MinecraftForge/MinecraftForge#1658]
For example, this recipe:

```
craftingmanager.addRecipe(new ShapedOreRecipe(new ItemStack(Items.stone_sword),
        "S",
        "S",
        "T",
        'S', "stone",
        'T', "stickWood"));
```

Will only take vanilla stone as an ingredient. This can be fixed by changing in OreDictionary.class:

```
//initVanillaEntries
registerOre("stone",       Blocks.stone);
replacements.put(new ItemStack(Blocks.stone), "stone");
```

to

```
registerOre("stone",       new ItemStack(Blocks.stone, 1, WILDCARD_VALUE));
replacements.put(new ItemStack(Blocks.stone, 1, WILDCARD_VALUE), "stone");
```

**Comment by chibill** [comment]
but it breaks normal stuff use villinla 1.88 you can;t make a sword with the other stone types....

**Comment by coolsquid** [comment]
@chibill The Vanilla tool recipes doesn't use the oredictionary.

**Comment by heldplayer** [comment]
@chibill I'm assuming this is an example recipe that doesn't come from vanilla, seeing as you can only make stone swords from cobblestone in vanilla, not stone.

**Comment by chibill** [comment]
I see... well i sort of derped up reading that...

**Comment by Parker8283** [comment]
Feel free to make a PR If you know the fix :P

**Comment by Anon10W1z** [comment]
The thing is, I don't know how :P

**Comment by Parker8283** [comment]
Fork the Forge repo, clone the 1.8 branch and make sure to clone the FML submodule as well, create a new branch off of the 1.8 branch, run `gradlew setupForge`. After that's done, you will have an eclipse folder. If you use Eclipse, point your workspace to that folder. If you use IDEA, [it's a little harder.](https://gist.github.com/Parker8283/c8ebc9b8c11772dfda51)

**Comment by Anon10W1z** [comment]
Thanks. How can I keep it up to date between versions?

**Comment by Parker8283** [comment]
There's really no easy way. What I do is just have one folder where I have the 1.7.10 branch cloned and one folder with the 1.8 branch cloned.
