### ISSUE TITLE
Using the ItemTooltipEvent with bold causes an error in the size of the tooltip box.

### ISSUE THREAD

**Issue by ericBG** [MinecraftForge/MinecraftForge#1660]
Take this code:

		@SubscribeEvent
		public void onTooltip(ItemTooltipEvent event)
		{
			if (OreDictionary.getOreIDs(event.itemStack).length == 0) return;
			if (!(Keyboard.isKeyDown(Keyboard.KEY_LSHIFT) || Keyboard.isKeyDown(Keyboard.KEY_RSHIFT)))
			{
				event.toolTip.add(EnumChatFormatting.ITALIC + "To see Ore Dictionary uses of this item, hold " + EnumChatFormatting.BOLD
						+ EnumChatFormatting.AQUA + "SHIFT");
				return;
			}
			event.toolTip.add(EnumChatFormatting.AQUA + EnumChatFormatting.BOLD.toString() + "Ore Dictionary Uses:");
			for (int id : OreDictionary.getOreIDs(event.itemStack))
				event.toolTip.add(EnumChatFormatting.YELLOW + OreDictionary.getOreName(id));
		}

If the "Ore Dictionary Uses" is the biggest part of the tooltip, it'll glitch out, like so:

http://imgur.com/a/MbhFJ

I have a feeling the bounding box does not take into account the bold modifier.

Thanks!

**Comment by LexManos** [comment]
Interesting, would be a vanilla bug with determining the size of a bold string...
Will look at it when back from con.

**Comment by squeek502** [comment]
This is specific to NEI, because CodeChickenLib strips formatting when calculating width. This problem does not exist when NEI is not installed.

Reported here: https://github.com/Chicken-Bones/CodeChickenLib/issues/40

**Comment by RainWarrior** [comment]
Report if this still happens in forge.
