### ISSUE TITLE
Pistons crash the client on a server with forge 1290 1.8

### ISSUE THREAD

**Issue by EnderStar** [MinecraftForge/MinecraftForge#1661]
How to crash your client with pistons:
Join a 1.8 forge server
Place a piston
Activate the piston (i try moving grass down, and i activated it with a redstone torch and a presure plate)
The client crash, then you can join the server and break the piston without crashing

**Comment by coolsquid** [comment]
Crash log (on Pastebin!)

**Comment by RainWarrior** [comment]
A couple of piston-related bugs were fixed, comment if this crash still happens.

**Comment by JakeTBone** [comment]
How do I fix this? Because I have Minecraft Forge 1.8 and the game crashes when I use a piston. And I want to use pistons without causing the game to crash.

**Comment by LexManos** [comment]
This was 2 years ago, its not the same issue.
Also, update to 1.10.2.
