### ISSUE TITLE
Setup Fails

### ISSUE THREAD

**Issue by gegy1000** [MinecraftForge/MinecraftForge#1667]
I want to contribute to Forge, but when I run gradlew.bat setupForge, I get this error: 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating root project 'forge'.
> A problem occurred starting process 'command 'git''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

**Comment by LexManos** [comment]
You need to have git installed and accessible through the path.
