### ISSUE TITLE
BlockFluidBase should override canPlaceBlockAt

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/MinecraftForge#1672]
```
@Override canPlaceBlockAt() {
    return canDisplace();
}
```

Something of this nature ensures transparent compatibility with vanilla, as this method is called when a block is placed into the world when it matters whether or not it can be placed there. And since Fluid doesn't require a BlockFluidBase return from getBlock, it makes support that much easier.

**Comment by hilburn** [comment]
Seems like this would be helpful

**Comment by KingLemming** [comment]
Snuck this in with 1355+
