### ISSUE TITLE
RenderBlockFluid.java 

### ISSUE THREAD

**Issue by TechStack** [MinecraftForge/MinecraftForge#1674]
Not sure if this was intended but RenderBlockFluid.java is nothing but comments in 1.8.

Will this get implemented for 1.8 or should it be considered removed from forge?

Thanks

**Comment by LexManos** [comment]
Depends, Fluids and rendering is very in flux. As it sits its there for reference only for old code. However, people SHOULD be able to use the vanilla fluid mechanics for rendering things right now.

**Comment by RainWarrior** [comment]
Fluid rendering is updates now, look at examples in the test folder.
