### ISSUE TITLE
Weather hooks

### ISSUE THREAD

**Issue by clienthax** [MinecraftForge/MinecraftForge#1677]
I think having hooks to alter the weather for biomes would be usefull,
say if you have a custom biome that has volcanos, you can make the rain texture be ash
and modify the conditions of when the fall occurs, and other weather modifiers such as lightning
You should also be able to change the block type the rain 'drops' onto the ground.

**Comment by cjcool** [comment]
As an addition to this request, it would be nice to be able to disable the particles, textures, and sounds separately (such as only having the rain sound enabled in underground dimensions).

**Comment by jimcarreer** [comment]
I think this could be interesting too, but I'm not entirely sure how it would be implemented.
