### ISSUE TITLE
crash if minecraft path contains special characters

### ISSUE THREAD

**Issue by Lightforger** [MinecraftForge/MinecraftForge#1680]
When running from a custom folder (with the `set APPDATA=%CD%\` trick) it crashes if you use a folder like `..stuff/minecraft+mods/.minecraft`

Edit; Full log: http://pastebin.com/raw.php?i=gdU4wgC8
folder name is "1.8 vanilla+basic" ->
java.io.FileNotFoundException: C:\minecraft\1.8 vanilla basic.minecraft\versions\1.8\1.8.jar

**Comment by LexManos** [comment]
Post full logs, + should be fine ! is not.

**Comment by Lightforger** [comment]
Added log

**Comment by LexManos** [comment]
Interesting, + is a special character alias for ' ' so that's where it has a issue.
Should be encoded but it isn't odd...
