### ISSUE TITLE
Configs need simple scripting or optional segments

### ISSUE THREAD

**Issue by geostyx** [MinecraftForge/MinecraftForge#1688]
So many mods now have integration for other mods, but require specific config settings when those mods are installed.

So configs need to have optional config segments for cases where certain mod(s) are installed.

Example:

```
if(mod.Foo.IsInstalled) {
    # Config settings
}
```

**Comment by LexManos** [comment]
You can do that just fine.
Also there are no plans at this time to expand the config system there are already plenty of other solutions out there. The homebrewed config system is legacy code from back before we had access to libraries like GSON.

**Comment by coolsquid** [comment]
That's easy to do.
if (Loader.isModLoaded("modid")) {
        //Config options
}
