### ISSUE TITLE
I accidentally corrupted a chunk with mods.

### ISSUE THREAD

**Issue by sfxworks** [MinecraftForge/MinecraftForge#1690]
Hello

I accidentally did //set 3008:11 resulting in this after 5 seconds
```javascript
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] java.lang.ArrayIndexOutOfBoundsException: 11
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at resonantinduction.core.blocks.BlockIndustrialStone.func_71858_a(BlockIndustrialStone.java:41)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.block.Block.func_71895_b(Block.java:549)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.client.renderer.RenderBlocks.func_94170_a(RenderBlocks.java:8162)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.client.renderer.RenderBlocks.func_78578_a(RenderBlocks.java:4479)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.client.renderer.RenderBlocks.func_78570_q(RenderBlocks.java:4174)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.client.renderer.RenderBlocks.func_78612_b(RenderBlocks.java:446)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.client.renderer.WorldRenderer.func_78907_a(WorldRenderer.java:224)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1551)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1129)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1006)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:946)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:838)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.client.main.Main.main(SourceFile:101)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at java.lang.reflect.Method.invoke(Unknown Source)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
```

Changing the damage value of this modded block's damage value to a different number to see how it would look ascetically was not a very good idea. [This mod has it so that most of their blocks are given damage values vs id values. I was trying to find the right one.]

So, I open up MCedit when this usually happens to fix the problem with any sort of issue like this. It didn't work.

So, I read and find this.

```javascript
[B#265]  2015-02-07 07:54:09 [INFO] [STDOUT] 	Level spawn location: World: (147,99,644), Chunk: (at 3,6,4 in 9,40; contains blocks 144,0,640 to 159,255,655), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
```

Given:
```javascript
Region: (0,1
```

I follow with 
![NBT](http://oi61.tinypic.com/k4f32b.jpg)

Given that I set a flat area of blocks to this id+dmg value, Id assume it span across multible chunks but not be large enough to go through multible regions. So I need to be able to revert every single block within the defined range back to something like 7.

The range:
```javascript
144,0,640 to 159,255,655[/code]
```

Given this handy dandy replace tool in NBTExplorer, what would I to do find all blocks with the id of 3008 within that range and set their damage value back to 7? IE the equivelant of //set 1008:7 after specifying the x y and z position?

Note: Even though it says y 0 - y 255, it was a flat rectangle. So it wouldn't have more than a height of 1. I don't remember what height level I was at...so I'm having to rely more on this replace too.

![NBT](http://i59.tinypic.com/2h3v9lz.png)

I didn't know Lex's full name until I googled it. Thanks captcha.

**Comment by laz2727** [comment]
NBT? Is MCedit that bad now?

2015-02-07 19:45 GMT+06:00 sfxworks <notifications@github.com>:

**Comment by heldplayer** [comment]
How is this an issue with forge?

**Comment by sfxworks** [comment]
I generalized it....

It was done by a plugin from bukkit on a mod running from forge. Forge absorbed both the mod and the bukkit api...
It's not specficially related to a modding issue...
It's not simple enough to just be a minecraft-general issue unless I went ahead and said "Oh hey how to do I take this vanilla block and change its damage value in NBT Explorer?"
So..>Forge Won

**Comment by LexManos** [comment]
This isn't a forge issue so closing, however, the region file format is well documented so you can easily figure out where the values you need to change are stored. However doing something generically without a program written to specifically replace block ids/meta will be hard considering the meta/blockids are split across 3 arrays in the NBT {Namely the block ID is a byte[] and a nibble[]} Good luck.
