### ISSUE TITLE
[1.8] Textures from Particles are not bound

### ISSUE THREAD

**Issue by Guichaguri** [MinecraftForge/MinecraftForge#1691]
Custom texture from EntityFX.particleIcon is not bound and the vanilla particle texture is rendered instead.

The patch should be easily made by binding the texture before EffectRenderer#284

**Comment by LexManos** [comment]
Where are you loading the textures from and where are you getting the Sprite information for if it is not stitched?

**Comment by Guichaguri** [comment]
I don't know what I was thinking
