### ISSUE TITLE
Block Texture not showing in inventory!

### ISSUE THREAD

**Issue by windows300** [MinecraftForge/MinecraftForge#1692]
I have the code in this repo: https://github.com/EpicMinecraftModders/EquivalentExperienceExchange

I called:  
    RenderItem renderItem = Minecraft.getMinecraft().getRenderItem();
    renderItem.getItemModelMesher().register(Item.getItemFromBlock(experienceOre), 0,
        new ModelResourceLocation(this.MODID + ":" + BlockExperienceOre.name, "inventory"));
from my init() like most tutorials say to do, yet it shows as this:  
![Pic1](http://i.imgur.com/7sZrKdD.png)
![Pic2](http://i.imgur.com/OYlTY48.png)
is there something I'm missing here?

**Comment by RainWarrior** [comment]
Cloned your repo, everything works:
![2015-02-08_05 44 34](https://cloud.githubusercontent.com/assets/669741/6094805/834719d0-af4c-11e4-977b-4922d50ec4f1.png)

**Comment by windows300** [comment]
Problem on my end then. What could it be? Setup Forge correctly and everything went fine. Drivers for my computer are all up to date.

**Comment by windows300** [comment]
Compiled my mod and tried it in a fresh just installed forge11.14.1.1306 game. No dice.  
![:(](http://i.imgur.com/JLVQrVS.png)

**Comment by cazzar** [comment]
Check your item jsons and make sure they correlate with how vanilla does it

**Comment by heldplayer** [comment]
What IDE are you using?

**Comment by windows300** [comment]
Eclipse for java Developers

**Comment by windows300** [comment]
@cazzar I used the Item json files I got from three tutorials, and they all said to use what I put there to render blocks in the inventory. Beside @RainWarrior got it working on his computer, just by cloning my repo. Anything suggestions to make it work?

**Comment by LexManos** [comment]
Nuke your workspace and re-setup. Eclipse may be doing something dumb like not copying resources over to the run folder. Or you may have a casing issue {hint, ALWAYS use lowercase in file/path names}
Fry says he got it working so its not something in the code its something in your setup.

**Comment by windows300** [comment]
Created a new setup up and it's still not working. {Yes i renamed eveything so it's lower case in the assets and Unlocalized Names}. Also made sure eclipse and java are up to date.
![Derpness](http://i.imgur.com/8pVA6VT.png)
I'm begging to think it has something todo with the latest java or the latest version of eclipse.

**Comment by Parker8283** [comment]
You and fry are using the same Java, so it couldn't be that.

**Comment by windows300** [comment]
Could it be my GPU drivers or anything. I've tried so many tutorials and different ways to setup the mod. Nothing works... Thanks to everyone who has help so far.

**Comment by LexManos** [comment]
Logs, logs, logs
Something will tell you that it couldnt find a texture, and you have to look exactly where its trying to find the texture.

**Comment by windows300** [comment]
Don't see any error's. But you guys are the people who make Forge so: [here's my log](http://pastebin.com/VQ4KmL9t)

**Comment by LexManos** [comment]
FML logs -.-

**Comment by windows300** [comment]
Sorry, didn't know they had separate logs. Even though I knew Forge and FML are two separate things. Derp. [Here's the log.](http://pastebin.com/1m5Et3pX)

**Comment by TechStack** [comment]
I cloned your repo & could reproduce your error.
I then started troubeshooting and after trying a few other things like case I realized in your ModEEE.java file you had your preinit method (line 29) defined with the FMLInitializationEvent  parameter instead of the FMLPreInitializationEvent parameter.

After I corrected that then the Blocks started showing textures both in the world and in the inventory.

Have fun modding & Cheers!

**Comment by Thog** [comment]
Have you tried to delete your eclipse project bin dir? (force rebuild and copy resources)

**Comment by windows300** [comment]
@Thog I didn't have to. I nuked (destroyed my forge dir) and created a new one. But @TechStack fixed it. Derp... Sorry guys if I caused any problem and thanks @LexManos @RainWarrior and anyone else involved with Forge/FML, you guys really do make an awesome environment for players and developers.
Thanks, @Windows300
