### ISSUE TITLE
[1.8] Configuration.get() not working with int[]

### ISSUE THREAD

**Issue by Aroma1997** [MinecraftForge/MinecraftForge#1694]
When I want to load config options from the config file using the Configuration class from Forge, everything works perfectliy except int[] values.
When I try to get an int[] value, the config file gets regenerated every time (or at least that part of the config file). When I put a default value there, the value in the config file is still empty. When I add something in the config file, it will be regenerated the next time I restart my minecraft and the property.get() returns an empty int[].

**Comment by LexManos** [comment]
Code and any logs you have are required.

**Comment by Aroma1997** [comment]
Example mod:
http://pastebin.com/eZ7TFrTk
That's what the test mod logs:
[18:36:05] [Client thread/INFO] [TestMod]: 0

**Comment by LexManos** [comment]
I don't know what you're doing but I just ran that exact code and it returned the correct values.
Most likely you have the config entry in your config set to a empty array.
