### ISSUE TITLE
Problems with shifting form server to single player world

### ISSUE THREAD

**Issue by WolfAmaril** [MinecraftForge/MinecraftForge#1696]
When shifting from a server to a single player world, issues arise with ID conflicts that are only fixed by restarting the client.
And by issues I mean a Crash to Desktop.

**Comment by diesieben07** [comment]
Always need logs in such situations.

**Comment by WolfAmaril** [comment]
http://pastebin.com/N4Pc7MdJ

This is my specific instance of the problem. I've already posted it to both Bibliocraft and Thaumcraft's issue trackers, and they pointed me here.

**Comment by LexManos** [comment]
Highly doubt this is a Forge issue. Seems something in there is something in your setup not allowing the blocks to be remapped correctly.
Cofh has been known to derp around in the registry causing broken remaps.
