### ISSUE TITLE
Tessellator PriorityQueue IllegalArgumentException

### ISSUE THREAD

**Issue by Slind14** [MinecraftForge/MinecraftForge#1698]
Hey,

we have the same issue and are currently spending some time trying to figure out more about it. An interesting thing I just encountered with forge 1307 is the following.

I patched the Tessellator get method to return when the rawBuffer is 0 and also give me a quick log output in order to see when the issue appears.
I loaded an area with the issue in singleplayer and started to remove staff. I started by removing chisel blocks on the ground and after finishing the first floor my out print isn't appearing anymore but this startup error:
``[22:01:09] [Server thread/ERROR] [FML]: Detected an attempt by a mod null to perform game activity during mod construction. This is a serious programming error.``
It is happening during the game in singleplayer when moving around at the place with the issue. It does appear in the same manner of frequency as my log output. I don't see how this makes sense and don't know if it can help to figure out the source. 

I'll update once I know more. It doesn't make sense for me at all.

**Update** I removed the patch (non modified forge 1307) the base is not crashing the client anymore. But the mod null error is still appearing whenever moving around at the place.

ref. https://github.com/MinecraftForge/MinecraftForge/issues/981

**Comment by LexManos** [comment]
You provide no logs or anything of use.
As for the constructor issue, that is a bad modder code. As it says, it's trying to create/register blocks in its constructor instead of one of the game state events.
This causes issues with registries and things like that.

**Comment by Slind14** [comment]
mhh, yeah. I was thinking about should I or should I not submit. 
After the my log output was replaced by this error I was wondering how it is even possible. As I thought it can only appear on server start, not afterwards.

I do have a region file pre and after. I have the same issue at 2 more places. (everything based on a modpack) In case you want something let me know. 
I didn't add anything more as I don't think it is liked unless it is a simple setup and easy to reproduce.

I would like to see the issue sorted as it is a freaking hard thing to repair those corrupted areas. However I don't have what you asked for in the other issue, so in case there is nothing of importance I could provide for further investigation..

From my side I would appreciate the simple return null work around to be applied to the official forge version. While I have it patched for my self, it doesn't help others.

**Comment by LexManos** [comment]
I'd rather the crash stay and not support modders producing broken code. The error you linked is caused by modders being bad.. Nobody has yet to supply a valid argument as to why we should encourage and support them writing bad code.

**Comment by Slind14** [comment]
alright. I guess the user looses. Thanks for the quick respond :)

**Comment by LexManos** [comment]
Provide a valid usecase that this error should exist. Hell I could even add extra erroring to the blocks themselves. Sadly modders fuck things up, there isn't much I can do about it.

**Comment by Slind14** [comment]
appreciate. I have a multiple areas I could share, but as stated they require more than 1-2 mods. It would be very very helpful if the log output could be extended to contain block information, if this is in any case possible. Would make things easier for everyone. Users to self repair their corrupted chunks and have an easy time reporting it to the mod causing it. Modder's to have something saying clearly what is causing the issue... 
If that would be possible, I guess everyone would win.

**Comment by LexManos** [comment]
Without going deeper into it and 'guessing' that it'll error we don't have a way to tell what mod is fucking up. So thats not possible.
And no, I asked for a valid use case. A example of a modder doing it wrong is not a valid use case.
