### ISSUE TITLE
[1.7] Unknown QueuedChunk (This should not happen. Please report this error to Forge)

### ISSUE THREAD

**Issue by Superjo149** [MinecraftForge/MinecraftForge#1702]
```
3.02 05:11:46 [Server] INFO Unknown net.minecraftforge.common.chunkio.QueuedChunk {
13.02 05:11:46 [Server] INFO This should not happen. Please report this error to Forge.
13.02 05:11:46 [Server] INFO }
13.02 05:11:46 [Server] INFO provider: biomesoplenty.common.world.WorldProviderSurfaceBOP
13.02 05:11:46 [Server] INFO dimension: 0
13.02 05:11:46 [Server] INFO world: Overworld
13.02 05:11:46 [Server] INFO loader: null
13.02 05:11:46 [Server] INFO z: -569
13.02 05:11:46 [Server] INFO x: 910
```

I am getting this error in my console, i thought i would post it onhere.

**Comment by LexManos** [comment]
How often does it happen. This is caused by chunks being incorrectly queued to be loaded when you're walking around. Somehow, unknown. Will tell the BOP people to look into it. If it's reproduceable.

**Comment by Superjo149** [comment]
@AnodyneEntity Could you explain what you think is causing this?

**Comment by AnodyneEntity** [comment]
This is quite possibly just a Cauldron issue. Because I haven't been able to reproduce this in Single Player.

**Comment by bloodmc** [comment]
@Superjo149 Please provide a complete server log.

**Comment by Superjo149** [comment]
@bloodmc this is one of the many crash reports http://pastebin.com/2SYvJckf

and a log : http://sebsauvage.net/paste/?c0b16fc9e141b786#zMjgYtZZ7LOm6k9H5NVD4qPaHMVcErJs+7vNXBChHYE=

**Comment by bloodmc** [comment]
@Superjo149 Crash was caused by a stackoverflow. The unknown chunk error was just part of the aftermath.

git-Cauldron-MCPC-Plus-1.7.10-1.1236.05.212

This is not a Forge problem.
