### ISSUE TITLE
Using global entities for mob entities with eggs (and the limit of 255 global entity IDs)

### ISSUE THREAD

**Issue by radfast** [MinecraftForge/MinecraftForge#1703]
Hi, I'm co-dev of Galacticraft with micdoodle8.

Our mod currently adds 16 entities to the game and more are planned for future updates
*  8 of them are mobs, for which we register a global entity ID by calling ```EntityRegistry.instance().findGlobalUniqueEntityId()``` and ```EntityRegistry.registerGlobalEntityID```
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/util/GCCoreUtil.java#L56-66

*  8 of them are vehicles, for which we only register a mod entity by calling ``` EntityRegistry.registerModEntity``` but not a global entity ID.

An issue we sometimes encounter if the player has a large modpack is that the game has run out of global entity IDs because it is limited to 255:
https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/common/registry/EntityRegistry.java#L127

(Especially, OreSpawn mod takes a large number of global entity IDs)

Of course changing this would also require patching vanilla network code which expects the entity ID to be a byte.
See ```net.minecraft.network.play.server.S0FPacketSpawnMob.field_149040_b```
But I would think that could fairly easily be patched to a short.

I do not think changing this to a short would involve any changes to saved maps or chunk storage, as the storage uses entity names not IDs: see ```net.minecraft.entity.EntityList.createEntityFromNBT```

**Comment by diesieben07** [comment]
Only global IDs are limited to 255. If you use `registerModEntity` FML will use a custom packet to spawn the entity, which then allows the full integer range to be used.
Saving to disk is not relevant here at all, since that uses the String ID.

So... already there.

**Comment by radfast** [comment]
In certain situations I think it's necessary to use global IDs.  Our belief at Galacticraft is that mobs which are subclasses of EntityLivingBase require a global ID to be registered for some reason (I'm not sure what the reason is).  We may be wrong about that, but certainly a lot of mods do register a global ID for their mobs, otherwise I would not be talking about this issue - it is an issue which players have encountered in practice.
http://forum.micdoodle8.com/index.php?threads/crash.4897/#post-36266

**Comment by diesieben07** [comment]
This is not a forge issue. People should not be using global IDs, there is no reason to use them whatsoever.
If you need a spawn egg, make your own Item.

**Comment by radfast** [comment]
OK, I thought about this some more and that's a reasonable answer.  Closing.

**Comment by LexManos** [comment]
The 'Global ID list' is simply there for compatibility with OTHER mod loading systems. If you make a Forge mod DO NOT use the global list.

**Comment by radfast** [comment]
Hmm, I've been looking at this some more, i.e. how to "create our own items" for the 8 spawn eggs we would need, and it seems there will be loss of functionality in doing that.

Spawn eggs are referenced in some surprising places in the vanilla game code, especially connected with the achievements / stats system.  The vanilla EntityList maintains a HashMap ```entityEggs``` which links mobs which have global entity IDs to data of type ```EntityEggInfo```.  That is then used in the achievements / stats scoring system connected with mobs.

I cannot see a way of staying within the ```EntityEggInfo``` system without using a global entity ID.

**Comment by radfast** [comment]
I can see that MineFactoryReloaded's safari net is also using EntityEggInfo, and includes custom egg handlers for non-vanilla eggs used by mods like Twilight Forest:
Example: https://github.com/RTRGitHub/RTRRedux/issues/87

**Comment by LexManos** [comment]
So, all your reasons boil down to 'Spawn Egg Color's which isn't a reason.
You can easily make your own spawn eggs and go that route. 
Sadly Entities are just not designed to be extended in the vanilla global ID system.
Hence why we have a Forge solution.

**Comment by radfast** [comment]
Spawn Egg Colors, and inclusion in mob statistics on the **Statistics** page (which uses EntityEggInfo), are the two reasons.  Seem like good reasons to me. :)

I found a neat solution to this: https://github.com/micdoodle8/Galacticraft/commit/a692d6fd135e8779d28b2c8c60ef6b312d977dcf

Mods can register their entities the Forge way, and also add EntityEggInfo.

The entity eggs can have IDs greater than 255 in the IDtoClass mappings maintained in net.minecraft.entity.EntityList as those mappings all use Integers for the IDs.  The only network transmission of these IDs is the metadata (damage value) of mob Spawn Eggs, so numbers in the range 256-65535 should work OK.

This is working great now in Galacticraft.

The only weirdness would be, if other mods also use a similar solution, and a server owner adds new mods to an existing world (or new versions of the same mod with more/less creature entities than before) then the spawn egg metadata for a modded mob might change, so existing spawn egg items in the world may suddenly become eggs for a different type of modded mob...  This problem could be reduced if different mods attempt to start the search for an unused egg ID at a different number.  But anyhow, servers are not supposed to change the mod list for existing worlds.

**Comment by radfast** [comment]
Opened for discussion purposes, as I think this is a workable solution which Forge could implement - or if Forge doesn't implement it, mods can do it on a freestanding basis.

**Comment by Spartan322** [comment]
The only solution which is not limited would be to create a spawn egg which doesn't do it through metadata, but that's upto the team.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/c158af902f2a689f612fd20427b5a1590fc2f1ba

**Comment by radfast** [comment]
Great stuff!  Thank you LexManos, nice to see that included in Forge 1.8.  I apologise for re-opening this issue in that case.

AFAICS that is not in 1.7.10: but in 1.7.10 mods can do it the same way "manually".
