### ISSUE TITLE
Can Forge find a workaround for the Minecraft hard limit of 256 biome IDs?

### ISSUE THREAD

**Issue by radfast** [MinecraftForge/MinecraftForge#1704]
Hi, I'm co-dev of Galacticraft, alongside micdoodle8.

We occasionally encounter issues of biome ID conflicts.  Essentially the reason is that the vanilla game is limited to 256 biome IDs (see `net.minecraft.world.biome.BiomeGenBase`, the definition of biomeList as an array size 256).  That is a hard limit because the Anvil chunk format stores the biome ID as a byte, see `net.minecraft.world.chunk.storage.ChunkLoader.convertToAnvilFormat`, the line which reads:

> ```
>             abyte[k << 4 | j2] = (byte)(p_76690_2_.getBiomeGenAt(p_76690_0_.x << 4 | j2, p_76690_0_.z << 4 | k).biomeID & 255);
> ```

The vanilla game already reserves 80 biome IDs in 1.7.10 and I'm sure it will be more in future versions of Minecraft.  That leaves not too many IDs for mods to choose.

In Galacticraft we currently add 4 biome types to the game for our planets and space dimensions, but we are looking at adding a lot more biome types in future, including multiple biomes on Mars and other planets.  We also have third party add-ons for our mod which add many more dimensions and many more biomes (one adds 51 biomes).  Eventually we are going to run out of biomes in the game - sooner if Galacticraft is installed along with a multi-biomes mod like Biomes o' Plenty or Natura.

My question is whether it would be possible for Forge to workaround this hard limit by using a Forge biome ID "custom" and then a mod-specific biome registry - similar to how it is done for mods' internal entity IDs.  That would reduce conflicts and eliminate any problem of the hard limit (unless one mod needs more than 256 biome IDs, which does not seem likely).

**Comment by radfast** [comment]
Just to be clear: I'm happy to make a Pull Request with a proposal if this would, in principle, be an acceptable idea.  But I don't want to work on a Pull Request if it is likely to be rejected.

**Comment by Wulfson** [comment]
Related: #1621

**Comment by diesieben07** [comment]
You will need to make sure that this does not change the vanilla save format. So you would have to split up the IDs into the least significant 8 bits and the rest.

**Comment by radfast** [comment]
My proposal is that in the vanilla save format, only one 8 bit biome ID used, "forgeCustom", so that a Forge-saved map would remain save-compatible with the vanilla game.  When a chunk is loaded with that biomeID in the biomeID array, the game would need to look up additional Forge-specific save data for each chunk which will store the "Forge" biome ID.

I agree this is quite a complicated solution, but I think a solution will be needed as Minecraft grows: the more biome types are added in vanilla, the closer we are getting to the hard limit.

===========================================================

Another approach could maybe be simpler would be dimension-specific biome IDs.  So there can be 256 biome IDs for each dimension, but the IDs do not need to have the same meaning in all dimensions - biome ID 1 can be used for something other than Plains, in a dimension which is not the overworld.

That would not involve any change in the map storage, but would require the code simply to reference a different instance of net.minecraft.world.biome.BiomeGenBase.biomeList for a non-vanilla dimension.  Most likely it would be done through WorldProvider, so a non-vanilla WorldProvider could optionally specify a customBiomeList and if non-null that would be used in place of the vanilla list in net.minecraft.world.biome.BiomeGenBase.biomeList.

I think that is maybe a smarter approach to this problem, and a code change which would not break existing mods.  Calls to the constructor ```public BiomeGenBase(int p_i1971_1_, boolean register)``` would register the biome in the vanilla biomeList, but there can also be a new constructor ```public BiomeGenBase(int p_i1971_1_, boolean register, WorldProvider worldProvider)``` which would register the biome in a custom biomeList used by that World Provider.

This would not eliminate all conflicts but it would totally solve the problem of conflicts for mods which add dimensions with new worldgen, like Twilight Forest, Galacticraft, Tropicraft, etc.

**Comment by diesieben07** [comment]
The first approach is exactly what I meant.

**Comment by LexManos** [comment]
Sadly until we can force Biomes to be registered through our controls we can't really do this.
The Biome registry needs to move from a array based list, to a now-standard namespaced registry.
On top of that, we're not changing the save format. There are ways to get around it, but you also have to take into account network code which IIRC uses bytes, and we can't break that.

There is a lot to consider here, and though I do think something is needed. I think it is on Mojang's end to do.

Best solution in my mind is to store a chunk/region map for everything, block/item/biome/potion/whatever and use local ids in the chunk/region itself.

But ya the problem is keeping compatibility with vanilla.

**Comment by radfast** [comment]
Thanks for looking at this @LexManos 

I think what I will do next is attempt in Galacticraft to make a WorldProvider-specific version of biome types, see how that goes.  Will probably take me a few weeks.  If it works out, then it can maybe be something which other mods which multiple dimensions can borrow from our code.

Biome IDs do not seem to have all that much influence on the game - worldgen code uses biome types obviously, but a worldgen will fix the biome type and generate the blocks it wants to generate based on the biome type (i.e. ignoring the biome ID at generation time), a worldgen usually stores the biome IDs for the chunk only after it has already generated the chunk as it wants to.

In practice the issues we are seeing with biome ID conflicts are:-
*  Occasionally if there are special biome types which change the renderer client-side, grass or the sky changes colour in an unwanted way due to an ID conflict
*  A handful of mods (e.g. Erebus) have code which is based on reading one of their own registered biome types from the biome ID, that will error if there is a conflict
*  Apart from those two things, the main "clash" which players have reported in practice is simply a wrongly-named biome type in the F3 debug screen.

**Comment by LexManos** [comment]
Fibbing the biome id is not feasible, there are way to many client side functions that rely on the biome.
Aside from that, as stated SAVING is the issue. Forge is not in the position to dictate changes to the world format, nore the networking format.

Find solutions for those, and maybe expanding it would be feasible.

**Comment by DevPlayer-** [comment]
I'm out of my league here on this issue. Just throwing this out. Here goes. 

Can you get the BiomeID directly from the function that originally generates the BiomeID in the first place. Wrap the result with your own genearator. So when you get a "ExtremeHills biomeID:3" biome at x:2000,y:1200,z:1500, your hook says, "hey at location x:2000,y:65,z:1500, BiomeID:3 is a "Lunar" biome", that is to say, "load Lunar blocks instead of ExtremeHills blocks".

Think of it this way. If a player is walking around and gets to x:10000,y65,z:10000, you could automaticaly teleport the player to some other location. Instead of teleporting, just report a different biome. Could that work?

**Comment by LexManos** [comment]
No.

**Comment by radfast** [comment]
@DevPlayer  The blocks in the map are lunar blocks anyhow.  Biome ID does not affect the blocks which are in place in a world map, for the reason I gave: any (or most) mods' worldgen code will run by reference to the correct biome (no matter what the ID # is), and will only store the biome ID # after the blocks were already generated.

To give an example of what Biome ID affects, search vanilla code for calls to ```World.getBiomeGenForCoords()``` and ```Chunk.getBiomeGenForWorldCoords()```.   Client side it's things like the Swamp colours and cold biomes when rain turns to snow.  Server side it's actually a lot, quite a bit more than I thought:
* mob spawning for slimes (swamps), horses and snowman
* snow and ice effects in cold biomes
* lightning effects
* rain puddle effects in plains biomes etc
* the test for whether a bed is in the Nether (so it explodes) or not 
* some kind of flower generation effect
* villager AI:  villagers will move indoors if the biome cannot spawn a lightning bolt - who knew?
* WorldProvider.isBlockHighHumidity() - that suppresses fire spreading in some biomes

Any "per WorldProvider" biomes solution can intercept all of that simply by overriding ```WorldProvider.getBiomeGenForCoords(int x, int z)```
so a WorldProvider based solution to these should be feasible I think, though for perfectionists a patch of the F3 debug screen would also be needed.

**Comment by KuroNeko87** [comment]
Dont know if im late to the party or if you found a solutio but you could take a look at how Mevans did it for his lord of the rings mod. His mod adds about 100 or so biomes with their own ids and don't conflict with the vanilla/mod ones.

He's been doing it since 1.6.4

**Comment by radfast** [comment]
Mevans' LOTR mod uses the approach I mentioned [above](https://github.com/MinecraftForge/MinecraftForge/issues/1704#issuecomment-74310365).  It creates a custom ```Biome.biomeList``` for each different dimension.  The mod replaces the standard Overworld dimension with a MiddleEarth dimension with its custom biome list.  The biomeList is an array of 256 biomes ordered by numeric ID.  So the numeric IDs for biomes will have different meanings in different dimensions.  That works OK in Minecraft 1.7.10.  It won't work in later Minecraft/Forge versions which move away from numeric IDs and instead there is a Registry for biomes and only 256 biomes in total can be registered in that Registry.

-----

Of some relevance: [discussion by Benimatic (Twilight Forest author)](https://github.com/Benimatic/twilightforest/issues/6) about the way that vanilla and Biomes o' Plenty deal with "sub-biomes" (i.e. ID + 128)

**Comment by kashike** [comment]
Is this still an issue with 1.9?

**Comment by williewillus** [comment]
yes, because the save format has not changed. I imagine forge will not make a big change like this, and I also imagine that a vanilla save format change is due in the coming versions

**Comment by Madsthunder** [comment]
Why not store a biome as a short in another NBT tag called "ForgeBiomes" or something similar to that. Then, to keep compatibility with vanilla, store any modded biome as an Ocean or Plains in the normal NBT tag.

**Comment by williewillus** [comment]
How would you handle network then?

**Comment by Madsthunder** [comment]
@williewillus Adding a short array in Chunk and a method along the lines of Chunk#getForgeBiomeArray would probably do the trick. And wherever Chunk#getBiomeArray is called, replace the call with a call to a ForgeHooks method that takes in a Biome, byte array, and short array parameters. The method would retain vanilla functionality, but it would also add biomes to the short array. See classes that implement IChunkGenerator#populateChunk

EDIT:
Forgot about network... Change line 151 in SPacketChunkData to 
`p_189555_1_.witeBytes(p_189555_2_.getForgeBiomeArray));`
and line 181 in to
`i += chunkIn.getBiomeArray().length * 2;`

**Comment by williewillus** [comment]
vanilla clients expect SPacketChunkData to have a specific size and contents, if forge changes that it will confuse many vanilla clients (badly)

**Comment by Madsthunder** [comment]
@williewillus I thought vanilla clients can't log onto forge servers

**Comment by kashike** [comment]
@Madsthunder Vanilla clients can connect to Forge servers which require no client-side mods.

**Comment by williewillus** [comment]
^ 
you could have a forge server that just runs something like FTBU or some other management mod and vanilla clients are expected to still be able to connect

**Comment by howtonotwin** [comment]
If a Forge server requires no client mods, then there can't be any new biomes. (At least, I think.) Therefore, if the server allows vanilla clients, then there is no need to hack extra biome data into the chunk. If the server requires Forge clients, then it is safe to hack extra biome data into the chunk, as the clients are known to understand it.

**Comment by Niko-sk2x** [comment]
But then how the client receiving the data would know if it contains additional biome data or not? Any added flag would be incompatible with vanilla. Maybe another way would be to send separate packet with additional biome data? (if forge can do that, the packet would only contain chunk position and extended biome data)

**Comment by howtonotwin** [comment]
A vanilla client doesn't see anything different. A Forge client can deduce whether there's extra data or not from the size. (I don't know if that'll work.) If that seems like it won't work, can't the Forge client sort out whether the server is sending extra data by looking over the mod list with similar logic as the server? Isn't there some kind of handshake that Forge carries out that can send (or does already send) the required data on client join?

<sub><sup>As you can see, I am now completely out of my league.</sup></sub>

**Comment by Niko-sk2x** [comment]
The server would probably send the extra data only if there are biomes that ude id > 256 in that chunk. It should be possible to determine that from length, especially if the additional data is stored at the end of the array, I didn't think of that.

**Comment by Madsthunder** [comment]
Actually, @Barteks2x has a good point... If the server sent extra biome data, then the end of the PacketBuffer parameter in SPacketChunkData would have extra bytes hanging off the end of it. And if I'm correct, the length of the extra bytes at the end of the PacketBuffer would equal exactly 512. So all it would take to find out whether extra biome data is being sent or not is a simple check after line 1238 in Chunk
`if(buf.readableBytes() == this.forgeBiomeArray.length * 2) buf.readBytes(this.forgeBiomeArray)`

But I could always  be wrong :P

**Comment by Madsthunder** [comment]
This is possible, but it would take extensive patching and it would have a minor but noticeable effect on performance.

**Comment by radfast** [comment]
See my post from 13 February 2015 above:
> My proposal is that in the vanilla save format, a standard 8 bit biome ID will be stored, with name "forgeCustom". A Forge-saved map would remain save-compatible with the vanilla game. When a chunk is loaded with that forgeCustom biomeID in the biomeID array, the game would need to look up additional Forge-specific save data for each chunk which will store the true "Forge" biome ID.

A vanilla map will not contain any Biome with name "forgeCustom".  Any vanilla map is therefore network compatible with vanilla clients.

A modded map can contain examples of this new Biome with name "forgeCustom".  The modded map would send additional Biome data either in a separate network packet, or maybe in the same packet with optional Forge-extended data at the end of the packet.

I think the main problem here is community acceptance.  All mods creating new Biomes would need to use the Forge Registry.  I don't think this would be too challenging to code in Forge, but seems to me it's a policy change.

Something will have to happen, because **eventually** the game will run out of Biomes - vanilla Minecraft slowly adds more each version, and eventually there will not be enough Biomes left for mods.

**Comment by diesieben07** [comment]
> All mods creating new Biomes would need to use the Forge Registry.

Biomes already use a forge registry today.

**Comment by liach** [comment]
As far as I know, the id limit will be removed in 1.13.

**Comment by williewillus** [comment]
nope, not for biomes. The limit is only gone for items and blocks

I still think this ticket is mostly invalid since forge will never edit the vanilla save format in a backward incompatible manner. Moreover, the mechanisms used by mods like OTG/BiomeBundle seem to not have a problem adding lots of different environments without actually using more biomes. So with regards to the actual intent of the issue, this is a solved problem.

**Comment by liach** [comment]
https://github.com/fewizz/notenoughids

**Comment by 0Navis0** [comment]
I'm not the best for talking about this subject, I haven't the level in Minecraft modding for knowing correctly how biome works. I just wanted to give my opinion about this fucking annoying issue. I think everything has been already told, it is the intern hardcoding Minecraft code, and Forge doesn't seem to be able to do a lot with it. 

I think the best would be report this issue to Minecraft devs. They seem to be decided to rewrite a lot of the Minecraft base code in 1.13, and I think it would be the good moment for they rewrite the biome part too before the 1.13 is release. Maybe if we are a lot ro report this issue, they could give a care about it.

Here if it can help. https://help.mojang.com/customer/en/portal/articles/920890-where-can-i-submit-suggestions-

**Comment by Madsthunder** [comment]
@Hypsellis You are correct in the the thought that the devs can rewrite the biome code to remove the hardcoded limit on biomes. But in doing so I think they would have two options:

1. Raising the biome limit from 256 to 65536 by changing the code to send shorts rather than bytes

2. Changing the code to send an array of strings with the ids of the biomes contained within the chunk (with a limit of 256, because a chunk is 16 x 16) with the chunk packet along with the usual array of 256 bytes defining what biomes are where according to indices of the aforementioned array of strings.

But the problem with number one is that sending any chunk to the client would be hell, since there is way more data to be sent and chunks would take an excessive amount of time to load (I have tested it, but it was a while back). I can see the same problem occurring with number two in the instance that there are many biomes in one chunk.

Overall, I don't see any way Mojang could expand or remove the biome limit while maintaining a playable experience.

**Comment by Niko-sk2x** [comment]
actually biomes are quite small part of chunk, and they could very well use per-chunk biome palette just like with block IDs, making it possible to send less than 64 bytes per chunk for biomes.

**Comment by radfast** [comment]
Hey guys, I saw this has been resurrected.

The issue seems _reduced_ but not _eliminated_ in 1.12 as the RegistryEvent-based biome registration no longer requires mods to assign biome ID numbers at registration time (I guess Forge auto-assigns the IDs) - therefore you only now have mod biome collisions if total biomes registered exceed 256.   I think a big modpack can still reach 256 biomes - even if each mod registers only two or three biomes, that number can be reached.

@williewillus you mention backward compatibility of the save format, I thought maybe my "in principle" suggestion in [Feb 2017](https://github.com/MinecraftForge/MinecraftForge/issues/1704#issuecomment-282569793) can solve the save format problem - do you not agree?

For our mod (Galacticraft) - which adds new biomes only on non-vanilla dimensions - we are looking in [1.12](https://github.com/micdoodle8/Galacticraft/tree/MC1.12) at reducing the number of biome IDs we use, by re-using the same ```Biome``` object with different sub-biomes according to the dimension - if this works, we will maybe only need to register 3 biomes total (although some Galacticraft add-on mods written by other authors could add more biomes, that's outside our control).

**Comment by Madsthunder** [comment]
Option two in the comment I made about a month ago can be vastly improved. As a third option I think that sending an array of shorts with a variable length (Rather than full strings) with each short corresponding to a biome id in the universal registry for the world would definitely be playable and practical.

**Comment by radfast** [comment]
>   **radfast:** For our mod (Galacticraft) - which adds new biomes only on non-vanilla dimensions - we are looking in 1.12 at reducing the number of biome IDs we use, by re-using the same Biome object with different sub-biomes according to the dimension - if this works, we will maybe only need to register 3 biomes total.

This is now implemented and working properly, in
https://github.com/micdoodle8/Galacticraft/commit/6d18356c4f0cd5bd4cf7c206f550e787c378d504

This results in only 3 biomes being registered instead of 7 biomes before this change.  And even when we add more planets in future (or add-on authors add more planets - there's a third party add-on with many different planets which currently registers 51 biomes!) Galacticraft's biome usage will remain at 3 biomes registered.

(OK, maybe more than 3 biomes will have to be registered if a future planet uses more than 3 different biomes all in the same dimension.)

-----

>  **LexManos:** Fibbing the biome id is not feasible, there are way too many client side functions that rely on the biome.

Testing this system, world gen and client-side rendering is correct and the F3 Debug screen states the correct biome in all my tests.  It works because, as far as I can see, all vanilla/Forge methods which make use of biomes, include a call to ```WorldProvider.getBiomeProvider()```.  In your WorldProvider this can be overridden to set up the re-usable Biome object (```BiomeAdaptive``` here) to be as it needs to be for each different WorldProvider.

There are **performance benefits** in worldgen, because the re-usable array of biomes can be cached very efficiently in the BiomeProvider if the same biome ID is being used over and over.

------

The only slight problems are that

1.  there are no BiomeDictionary ```type``` entries for the different sub-biomes, because the BiomeDictionary includes an (**unnecessary**) check to see whether the Biome object is registered, therefore only the registered BiomeAdaptive object can be registered in the BiomeDictionary

2.  ```DeferredBiomeDecorator``` and its related event cannot be used, because Forge only fires this for registered Biomes.

3.  Advancements which are biome-specific cannot be used for the sub-biomes, because the Advancement .json will error if the referenced biome is not a registered biome.

We can probably live without these three things.  Not having the BiomeDictionary access is a shame, but I guess it doesn't matter too much.

**Comment by 0Navis0** [comment]
Why do you continue to force this feature into Forge while it's clearly out of their reach. There is an awesome occasion with the total rewritting of Minecraft for 1.13 to suggest and support this feature. 

I posted a suggestion on the official Minecraft feedback site. It would be nice if all this discussion could move here, and the most of modders, forge devs, modpack makes, and players support this feature by commenting, voting and sharing it. It will be the only way for pushing Mojang to finally increase or remove biome id limit.

https://feedback.minecraft.net/forums/355914-minecraft-java-edition/suggestions/33627445-increase-biome-id-limit

**Comment by LexManos** [comment]
1.13's world generation re-write has changed a lot related to biomes. Not the least of which is changing a lot of places from using bytes to ints. So In theory 1.13 will solve this correctly on their side.
So, topic closed.
