### ISSUE TITLE
Javadoc's no longer built

### ISSUE THREAD

**Issue by 61352151511** [MinecraftForge/MinecraftForge#1724]
Not the most important issue but the previous two builds for 1.8 do not have javadocs with them.

```
11.14.1.1322	1.8	02/19/2015 09:16:55 PM	(Changelog) (Installer) * (Installer-Win) * (Src) * (Universal) * (Userdev) *
11.14.1.1321	1.8	02/18/2015 10:08:20 PM	(Changelog) (Installer) * (Installer-Win) * (Src) * (Universal) * (Userdev) *
11.14.1.1320	1.8	02/17/2015 07:53:47 PM	(Changelog) (Installer) * (Installer-Win) * (Javadoc) * (Src) * (Universal) * (Userdev) *
11.14.1.1319	1.8	02/17/2015 02:17:55 AM	(Changelog) (Installer) * (Installer-Win) * (Javadoc) * (Src) * (Universal) * (Userdev) *
```

**Comment by matthewprenger** [comment]
MinecraftForge/ForgeGradle@dbbc5885d79df110405cc1297f6812fb3c36abb4 Not sure why though...

**Comment by AbrarSyed** [comment]
By lex's request.
Its also kind of pointless because as of 1.8 you need to specify a mapping (or a default one is chosen for you) and thus the javadocs forge has will not be correct for your mappings...

**Comment by 61352151511** [comment]
Hm ok then, makes sense

**Comment by LexManos** [comment]
It was disabled because 1) its 16MB/build resulting in 80% of our maven disk space.
2) As Abrar said, it's not useful for anyone as you use your own mappings. Abrar may be worth looking into something that can create the javadocs dynamically from a given mappings file and pipe that through a web page?

**Comment by AbrarSyed** [comment]
There is a way to generate javadocs from a jar of class files, can probably modify it to read the mappings as well. Definitely can be done.

**Comment by oddstr13** [comment]
How would I go about generating these javadocs myself?
I find having proper website reference docs essential while programming.

**Comment by liach** [comment]
@oddstr13 The docs are frequently missing or wrong. You should just use `setupDecompWorkspace` and read through the source code.

**Comment by LexManos** [comment]
You can generate your own javadocs web page using the standard javadocs tool on the mc source jar after running setupDecompWorkspace. 

There was an idea to make a javascript based dynamic javadocs site that provided the documentation based on the class structure, and the MCP mappings. But nobody ever got around to doing that.
Feel free to steal that idea if you want to, hell if you make something good it could become official.

**Comment by marvin-roesch** [comment]
I looked into that when it came up originally, but it never got really off the ground.
If anybody feels like working on it again: I've still got a layout lying around if they're not a design-y person and would gladly integrate it with our current theme xD

**Comment by oddstr13** [comment]
Appending the following to `build.gradle` seems to be producing more or less what I want;
```gradle
apply plugin: 'java'

task generateForgeJavadocs(type: Javadoc) {
    source = files('build/tmp/recompileMc/sources')
    options {
        links "http://docs.oracle.com/javase/8/docs/api/"
    }
    failOnError false
}
```

```
./gradlew setupDecompWorkspace
./gradlew generateForgeJavadocs
```

This is probably not the "proper" way of doing it, but seems to work okay.


It is reporting 100 warnings/errors, but producing an output none the less.
Does not look like the javadoc links option is working, however.

When it comes to file size, the javadoc directory is 103MiB uncompressed.
Or about 2.7 MiB when compressed with 7-Zip using LZMA2.

**Comment by Kyu** [comment]
(Came from Google, commenting to help other googlers)  

You can also generate your own javadoc after running `setupDecompWorkspace` by unzipping the contents of `forge-[version]-sources.jar` into a directory(e.g one called ForgeSource), then creating a another directory called ForgeDocs, then running  

`javadoc -d ForgeDocs -sourcepath ForgeSource -subpackages net`   

You'll find you `forge-[version]-sources.jar` (somewhere) in your GradleHome/caches/minecraft/net/minecraftforge/forge/

**Comment by ziyuanzhao2000** [comment]
Hi Kyu, I did what you said, but still got 100 errors when running javadoc from command line. Also, the problem is that I don't see any html output. Any idea? Thank you!

**Comment by Kyu** [comment]
@ziyuanzhao2000 can you send a lot of the errors? It's been a while but i remember it working despite the errors

**Comment by ziyuanzhao2000** [comment]
Hi Kyu, thank you for the quick response!! I will paste the last dozen lines of error messages here:
```
ForgeSource/net/minecraftforge/event/RegistryEvent.java:141: error: cannot find symbol
        public ImmutableList<Mapping<T>> getAllMappings()
               ^
  symbol:   class ImmutableList
  location: class MissingMappings<T>
  where T is a type-variable:
    T extends IForgeRegistryEntry<T> declared in class MissingMappings
ForgeSource/net/minecraftforge/fml/ModContainer.java:57: error: cannot find symbol
    protected final IModInfo modInfo;
                    ^
  symbol:   class IModInfo
  location: class ModContainer
ForgeSource/net/minecraftforge/fml/ModLoadingStage.java:22: error: package cpw.mods.modlauncher.api does not exist
import cpw.mods.modlauncher.api.LamdbaExceptionUtils;
                               ^
ForgeSource/net/minecraftforge/fml/ModLoadingStage.java:24: error: package net.minecraftforge.eventbus.api does not exist
import net.minecraftforge.eventbus.api.Event;
                                      ^
ForgeSource/net/minecraftforge/fml/ExtensionPoint.java:26: error: package org.apache.commons.lang3.tuple does not exist
import org.apache.commons.lang3.tuple.Pair;
                                     ^
ForgeSource/net/minecraftforge/fml/config/ModConfig.java:22: error: package com.electronwill.nightconfig.core does not exist
import com.electronwill.nightconfig.core.CommentedConfig;
                                        ^
ForgeSource/net/minecraftforge/fml/config/ModConfig.java:23: error: package com.electronwill.nightconfig.core.file does not exist
import com.electronwill.nightconfig.core.file.CommentedFileConfig;
                                             ^
ForgeSource/net/minecraftforge/fml/config/ModConfig.java:25: error: package net.minecraftforge.eventbus.api does not exist
import net.minecraftforge.eventbus.api.Event;
                                      ^
ForgeSource/net/minecraftforge/fml/config/ModConfig.java:28: error: package net.minecraftforge.fml.loading does not exist
import net.minecraftforge.fml.loading.StringUtils;
                                     ^
ForgeSource/net/minecraftforge/fml/config/ModConfig.java:137: error: cannot find symbol
    public static class ModConfigEvent extends Event implements IModBusEvent {
                                               ^
  symbol:   class Event
  location: class ModConfig
100 errors
```

So you see there are a lot of things javadoc couldn't find...I wonder if this is similar to what you have seen.

Yeah, I won't bothered if it gives some output, but I still have an empty ForgeDocs folders after using javadoc. Would you mind give a little bit more details? Like, I assume you put the ForgeDocs and ForgeSource folders both in the project directory. Also, did you run javadoc from an IDE or just from commandline? Or perhaps is there anyway to suppress the errors and let it just output whatever html files it can assemble? I'm really quite lost here. Thanks!
