### ISSUE TITLE
My Minecraft Keeps Crashing

### ISSUE THREAD

**Issue by daintydestr0yer** [MinecraftForge/MinecraftForge#1732]
I open minecraft launcher, then I either go to multiplayer or single player, but when I try to join a server, or a world, it crashes and I cant play minecraft anymore. I was on minecraft'
s website, but they said it was from forge. So I don't know what to do.... can you help?

![screenshot 1](https://cloud.githubusercontent.com/assets/11256771/6431032/321bb2b4-bff0-11e4-9086-10a4f6f666c3.png)

**Comment by laz2727** [comment]
I think it corrupted.

2015-03-01 19:52 GMT+06:00 daintydestr0yer <notifications@github.com>:

**Comment by diesieben07** [comment]
That crash cannot occur with forge installed.
