### ISSUE TITLE
Missing patch for RenderPlayerEvent

### ISSUE THREAD

**Issue by robin4002** [MinecraftForge/MinecraftForge#1734]
Hi,
Since 1.8 RenderPlayerEvent doesn't work.
I looked at why, and it turns out that a patches is missing :
1.7.10 : https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/patches/minecraft/net/minecraft/client/renderer/entity/RenderPlayer.java.patch#L58
1.8 : https://github.com/MinecraftForge/MinecraftForge/tree/master/patches/minecraft/net/minecraft/client/renderer/entity -> no patch for RenderPlayer

Is it intentional or is it an oversight ? if this is intentional, what is the alternative to use ?

**Comment by LexManos** [comment]
This is intentional, everything that that event used to be used for, should be able to be done using the new Layer system.
Could of sworn i deprecated and made that note in the event itself asking modders to provide feedback, but meh.

Point is, it shouldn't be needed anymore and it needs to be reviewed by those modders who are using the event.

**Comment by robin4002** [comment]
Thank you for your reply.
I just watched the interface LayerRenderer and some classes of Minecraft (LayerCape, LayerBipedArmor), it seems to have what I need to do what I want (add a hat).
I have one last question, how to register my own Layer ?
Minecraft add the layer in the constructor of the class RenderPlayer with the fonction addLayer.
I made two / three research and I have not found a function that modders can use.

**Comment by LexManos** [comment]
Renderers are singletons so you can just get the default instance and add your own layers like vanilla does.

**Comment by robin4002** [comment]
No, I can't because the method setLayer is protected. Should I use a access transformer or there is another way ?

**Comment by LexManos** [comment]
ASs you only do it once, reflection is always an option. But i'll tag @RainWarrior in this as its rendering related.

**Comment by robin4002** [comment]
Since #1983 was merged this issue can be close.
