### ISSUE TITLE
[1.7.10] Setting a byte in the buffer of an IMessage system can cause the packet system to fail.

### ISSUE THREAD

**Issue by Paul17041993** [MinecraftForge/MinecraftForge#1735]
starting point example/tutorial;
http://www.minecraftforge.net/forum/index.php/topic,20135.msg101552.html#msg101552
works as intended, however, if you use setByte in the toBytes method, there are certain patterns that cause the packet system to fail in a very queer way. Most specifically you end up with 'Undefined message for discriminator x in channel...', where x can be variable, I've had it say -1 and 0, even though 0 would obviously be set anyway but -1 is definitely a sign of error.

particular patterns;
 public void toBytes(ByteBuf buf) {
        buf.setInt(0,0);
        buf.setByte(10,0);
} // fails, disc. 0

 public void toBytes(ByteBuf buf) {
        buf.setInt(0,0);
        buf.setByte(1,0);
} // fails, disc. -1 I think
essentially after any previous set value I think but the disc. varies

 public void toBytes(ByteBuf buf) {
        buf.setByte(0,0);
} // fails, disc. -1

 public void toBytes(ByteBuf buf) {
        buf.setByte(1,0);
} // works correctly (or at least I think it does...)
essentially you cant set the very first byte either, but start at a high index (and the first call) is fine...?

**Comment by Paul17041993** [comment]
now actually when I read over it, is the 'Undefined message for desc. ...' meant to mean the message itself is invalid (corrupt) or it cant map to the registered handler/s? probably need some better logging there...

**Comment by Paul17041993** [comment]
ok now this is very odd, I've also just found that setInt will cause the packet to break regardless of what you give it...

**Comment by Paul17041993** [comment]
ok I'm now beyond confused with whats going on here, one thing I worked out is the writing index isn't offset, so you need to do that yourself (start at 1 or more) otherwise you write over the start data. But then after fixing that its only ever sending a EmptyByteBuf instance to the receiving end, which of course contains absolutely nothing... (IndexOutOfBoundsException on anything)

**Comment by ds84182** [comment]
You may be overwriting the type and size parameters in the packet. I think
it was already advised somewhere to not use the set methods in ByteBuf

**Comment by cazzar** [comment]
I'd advise using the provided writeX and readX methods (where x is the
type) as i show in
http://cazzar.net/tutorials/minecraft/Forge-SimpleImpl-Tutorial/ due to the
way these messages are set to have byte 0 to be the packet discriminator.

**Comment by Paul17041993** [comment]
I'm getting the active start indexes from readerIndex and writerIndex accordingly.

**Comment by LexManos** [comment]
Why are you using set over write?
Write is intended to be used, set overrides anything that is currently there.
Such as the packet header, or any previous packets.

**Comment by Paul17041993** [comment]
I'm a C++ and engine kind of programmer, so naturally use direct methods and was under the impression that the buffers were actually user-data and not the raw packet data (bad practice for that very reason). I never saw any documentation that mentioned not to use said methods either.

Two fixes to prevent this from occurring again would be to either pass a 'user data' buffer in instead of the raw one, or to disable access to the index methods one way or another. A third option may be to just mention in documentation what indexes are currently used, but either way that still promotes packet hijacking...

**Comment by LexManos** [comment]
Where did you get that domain from?
Also, the docs could be changed yes, but its not an issue for everyone as it's kind of a obvious thing.
You can use those methods if you want, when writing you simply need to take into account that 1 byte is used already.

**Comment by Paul17041993** [comment]
yea I don't know where that domain came from, only noticed it when pasting the link and forgot to get back to it...
