### ISSUE TITLE
Allow Emerald Ore to be replaced?

### ISSUE THREAD

**Issue by tgstyle** [MinecraftForge/MinecraftForge#1737]
See this issue on COFH.

https://github.com/CoFH/Feedback/issues/239#event-245715781

**Comment by tgstyle** [comment]
1.7.10

**Comment by LexManos** [comment]
Put some effort into your reports -.-
Not gunna happen for 1.7.10 as thats bug fixes only.
Also Emeralds are special cased by vanilla and don't fall under the same generator setup as the rest so it can't use the same system.

-.-
