### ISSUE TITLE
[1.7.10] Minecraft calls to deprecated removedByPlayer cause server/client desync

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#1740]
When a player breaks a block, the server gets this call:
```java
public boolean removedByPlayer(World world, EntityPlayer player, int x, int y, int z, boolean willHarvest)
{
    return removedByPlayer(world, player, x, y, z);
}
```
 (called from ItemInWorldManager.java removeBlock line 270)

but the client gets this call:
```java
@Deprecated
public boolean removedByPlayer(World world, EntityPlayer player, int x, int y, int z)
{
    return world.setBlockToAir(x, y, z);
}
```
 (called from PlayerControllerMP.java onPlayerDestroyBlock line 154)

Since we were only overriding the new call, not the deprecated one, [the client and server did not agree](https://github.com/ForestryMC/ForestryMC/issues/545).
The temporary solution for us is to override the deprecated call instead.
Ideally Forge should change all Minecraft calls to `removedByPlayer` to the new one.

**Comment by LexManos** [comment]
Things related to this have been reworked in 1.8 and 1.9 so let me know if this is still an issue.
