### ISSUE TITLE
[1.8] Exception caught executing FutureTask upon opening ANY world

### ISSUE THREAD

**Issue by kingbdogz** [MinecraftForge/MinecraftForge#1741]
I continue to get the following stacktraces upon entering either a new or old world. This has only began on a recent version, but I can't pin down when. When entering the world, it will bring me back to the main menu. The stacktraces are outputted continuously until I close the game. I'd like to mention that I have wiped my workspace countless times by now, and have even deleted ALL traces of Gradle off my PC to make sure it wasn't some corrupted files messing with my workspace.

It is currently preventing me from developing any further on my projects.

https://gist.github.com/kingbdogz/6f335a385eef6d352d7b

**Comment by HEmile** [comment]
This can be closed. It was an obscure bug in our own code due to a forgotten world.isRemote check.
