### ISSUE TITLE
Command Post-Execute Callback Proposition

### ISSUE THREAD

**Issue by matthewprenger** [MinecraftForge/MinecraftForge#1742]
Currently there is no way to react _**after**_ a command has been executed. The current [CommandEvent](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/event/CommandEvent.java) only allows you to react before the command is executed. Being able to react after would be beneficial for things like the `/op` command, when you would like to poll the ops list after the the change has been applied.

I see two solutions to this:

1. Add another event, `CommandEvent.Post` or something.
2. Add a callback list to the current CommandEvent that would be executed after the command was executed: 
```java
@SubscribeEvent
public void onCommand(final CommandEvent event) {
    event.addCallback(new Runnable() {
        @Override
        public void run() {
            System.out.println("The command executed!");
        }
    });
}
```

**Comment by luacs1998** [comment]
What uses would this be good for?

**Comment by matthewprenger** [comment]
@luacs1998 Commands like `/op`, `/deop`, `/whitelist`, etc. My specific use-case in ServerTools is managing the `[OP]` tags in chat when op status changes.

**Comment by LexManos** [comment]
How do you propose this is implemented?
Not sure why this is needed tho. It's not a bad idea, but there also needs to be a way of capturing the result of the command. Or extra details.

**Comment by matthewprenger** [comment]
I personally like the callback approach that I mentioned above. That way you could listen for the original command event, do an instanceof check, and if it's the command you want register a callback for when the command is completed.

You really can't get any extra details without special casing every command, except maybe execution count. Having a hook immediately before (CommandEvent) and immediately after (Callback) should be enough to cover most use cases.

**Comment by RainWarrior** [comment]
Does callback approach have any advantages over the Post event?
Post event is how everything else is done - so main point in favor of it is the style consistency. (and no need for a nested callback class)

**Comment by matthewprenger** [comment]
I can't think of any advantage with one over the other. A post event would be fine by me.
