### ISSUE TITLE
Wither immediately attacking after spawning

### ISSUE THREAD

**Issue by lumien231** [MinecraftForge/MinecraftForge#1743]
Normally when you place down a wither he should take a while too "charge up" and not do anything meanwhile. In 1.8 forge he immediately starts to move around and attacks entitys as soon as he spawns. The only difference to the "active" state seems to be that he can't fly and sticks to the ground.

**Comment by LexManos** [comment]
Just tested it out on the latest build, Vanilla he 'Charges up' but still moves around and does things.
The only real effect of the charge up is a health boost. 
It looks and behaves exactly like it does in vanilla in my tests, you'll need to be more specific.

**Comment by Lunatrius** [comment]
The wither used charge up in-place without moving. It was changed in 1.8 - whether this is a bug or feature, no idea.
