### ISSUE TITLE
ItemStack.getItemDamage() performance regression

### ISSUE THREAD

**Issue by sfPlayer1** [MinecraftForge/MinecraftForge#1744]
Forge modifies the method mentioned in the subject in a way that makes it massively slower than the original.

The slowdown comes from calling Item.getDamage(), which becomes a costly virtual call, contrary to the previous field access, as soon as enough Items override it. Those overriding items don't even have to be the ones queried, they can be unrelated since the impact comes from rendering the JVM unable to optimize the virtual calls away or inlining the accesses.

In terms of measurements I have a nps of some List<ItemStack> vs ItemStack matching in recipe processing which ends up spending over 95% of the whole task's time in getItemDamage() calls.

Applications that come to mind where getItemDamage() performance is crucial are recipe analysis, auto crafting or large area block drop analysis (explosions, instability/uu/emc scans) besides some widespread noise wherever item stack comparison is needed.

Considering how few mods actually use the feature and could use other means to achieve their intended goal it's quite a flawed design from a performance pov.

**Comment by LexManos** [comment]
From the performance graphs I've been looking at it's not that big of a deal, yes it is a small change as a getfield is obviously faster than a invokevirtual+ret. 
However, The amount of mods that use this make it worth it. Why are you querying damage values in the recipe handlers instead of metadata? That seems to be the real issue.

What are you proposing? Remove this feature? Not gunna happen. People use it to mixin 'sub-types' with 'data value's without resorting to even more costly NBT accessing.

**Comment by sfPlayer1** [comment]
That's not true at all, look at http://files.player.to/tmp/getItemDamage.png where getItemDamage is even slower than the uncached ore dictionary retrieval. It obviously compares more than 1 item stack per getOres call on average though.
None of the ItemStacks involved in the screenshot have their Item override getDamage, thus it must be purely virtual call overhead. You can't easily measure the performance of it in an artificial environment, presumably the JVM's optimizer has to believe that it can't do any fast path optimization on the invocation or inline it and the access has to be too distributed for efficient cpu cache use. Note that the getItem calls, which are certainly at least as frequent as the getItemDamage calls, don't show up high (part of self time -> inlined).

I don't see where you are going with metadata vs damage values, they are the same and the raw value isn't accessible or reliable with the override facility in place.

There's no alternative to removing this feature, you are bloating a thin data container object to something no longer suitable for bulk data processing. Querying NBT on a few item stacks is much faster than having to do a virtual call on all of them.

The primary use of getDamage I've seen is mapping (nbt value) -> (nbt value / scale) for display purposes, which can be also done by either setting the damage value to (nbt value / scale) when changing the nbt value or using a custom item renderer.

**Comment by LexManos** [comment]
Provide a binary compatible solution that does not remove functionality and i'll pull it.
Removing because some things are abusing it is not an option.
