### ISSUE TITLE
Configuration does not allow for Object Oriented Sub Categorys

### ISSUE THREAD

**Issue by MaPePeR** [MinecraftForge/MinecraftForge#1748]
The Situation: I have a Class, that manages multiple modules, that each have their own Configurations.

I Want the Config to look like this:
```
availableModules {
    enableModule1 = true
    enableModule2 = false
[...]
}

moduleConfigurations {
    module1 {
        //Config options for Module1, that my class does not care about.
        subConfig {
            //Might even have sub categorys!
        }
    }
[...]
}
```

This would be very easy, if the `ConfigCategory`-Object would contain the same Methods to get Configuration Variables as the `Configuration`-Object. (And it should be very easy to move these methods there, because they just call `ConfigCategory getCategory(...)` and work on that object anyway.)

[The dirty workaround](https://github.com/sinkillerj/ProjectE/blob/master/src/main/java/moze_intel/projecte/utils/PrefixConfiguration.java), that works surprisingly well, is to extend `Configuration` and overwrite the `getCategory()`-Method to add a Prefix to the `categoryName` and then use an Empty string as a Category. I would be happy to not need that though.

**Comment by LexManos** [comment]
Configuration is dying and being replaced by a different system that takes Classes and doesn't let modders touch the files directly, so wait tile that's finished.

**Comment by JustGregory** [comment]
@LexManos could you point me toward where this was discussed, the Configuration stuff "dying"? I cannot find where it is.
