### ISSUE TITLE
Allow changing volume and pitch of entity sounds

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [MinecraftForge/MinecraftForge#1750]
[Concerning this event](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/event/entity/PlaySoundAtEntityEvent.java#L28).

The volume and pitch fields are final and are not even used where the events are fired. They are almost pointless to have there if they cannot be modified. I suggest an implementation similar to the one used in [FOVUpdateEvent](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/client/event/FOVUpdateEvent.java#L14), where there is a newVolume and newPitch which are initialized to the values of the existing variables then used where the event is fired. This should be a very simple fix.

The ghetto-fix for this would be to cancel the event and replay the sound with modified variables.

I've had a look at making a pull request about it, but I can't figure out how to make patches for the master branch instead of a version specific one. There also seems to be some coming changes to 1.8 regarding sound that I know little about.

(I need this for a helium gas that will suffocate entities. I hope I can get it to sound silly when anything is damaged by it.)

**Comment by LexManos** [comment]
Make a PR for it.
And you just fork the master not a specific branch if you want to work on master.

**Comment by JamiesWhiteShirt** [comment]
I had made a fork and attempted to add these changes. Only now I just discovered I had set up the workspace incorrectly, causing a ton of errors I could not resolve, leading to the confusion about working on the master branch.

So I had another go. [Here is the pull request](https://github.com/MinecraftForge/MinecraftForge/pull/1751).

**Comment by JamiesWhiteShirt** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/1754
