### ISSUE TITLE
[Suggestion] Entity spectator shader change event

### ISSUE THREAD

**Issue by herbix** [MinecraftForge/MinecraftForge#1760]
Minecraft 1.8 added spectator mode. A spectator could possess a mob's sight by left clicking. When click a creeper, spider or enderman, the shader would change.
But it's only applyed for vanilla mobs. I have an idea of extending this mechanism. So that modders could apply shaders for their mod entities.

**Comment by williewillus** [comment]
`ClientRegistry.registerEntityShader` was added

**Comment by Actuarius** [comment]
@williewillus closed this issue
