### ISSUE TITLE
[Question] How are you building the patches?

### ISSUE THREAD

**Issue by phase** [MinecraftForge/MinecraftForge#1761]
I love the patch system, but how are you building them? I've tried to make shell scripts that do similar things, but the `.java.patch` shows it's an automated process. I'd love to see what you're using.

**Comment by chibill** [comment]
There using  gradle to do it. (There plugin is Forge Gradle) It handles the set up of the dev for people making mods. It also makes the patches when you use it to Dev forge it self.

**Comment by AbrarSyed** [comment]
ForgeGradle, the gradle plugin:  https://github.com/MinecraftForge/ForgeGradle
The task that applies the patches:  https://github.com/MinecraftForge/ForgeGradle/blob/master/src/main/java/net/minecraftforge/gradle/tasks/ProcessSrcJarTask.java
The task that generates the patches: https://github.com/MinecraftForge/ForgeGradle/blob/master/src/main/java/net/minecraftforge/gradle/tasks/dev/GeneratePatches.java

We use Diff4J by cloudbees to generate and apply the patches.  https://github.com/MinecraftForge/ForgeGradle/blob/master/build.gradle#L58


It is planned for ForgeGradle to be made more general and allow for other projects to use the same system as forge to generate and use patches in the upcoming ForgeGradle 2.0

**Comment by phase** [comment]
@AbrarSyed So does Gradle load Java plugins?

**Comment by AbrarSyed** [comment]
Gradle plugins can be written in any JVM language as far as I know. It currently supports Groovy, Java, and Scala, idk about Closure, Kotlin, or Ceylon.

http://gradle.org/docs/1.11/userguide/custom_plugins.html
