### ISSUE TITLE
Threaded loading screen

### ISSUE THREAD

**Issue by CreativeMD** [MinecraftForge/MinecraftForge#1764]
Hello :D,
having some questions about a thread loading screen.
After i set up the work-space i thought i could add a thread to the rendering stuff. WRONG.
http://forum.lwjgl.org/index.php?topic=5743.0
LWJGL 3 supports that, but minecraft uses LWJGL 2 :(.
I used the new thread to load minecaft stuff and the main thread renders the loading screen.
I splitted the parts you can be load in the thread into a new function loadGame().
Looks like this: http://pastebin.com/DBd3HizM

So far so good.
It's working already, but i had some questions about how should i integrate mod events (progressbar).
MinecraftLoader uses the LoadController.propogateStateMessage method, but i get the impression that you didn't like this way?!

I'm open to change my structure etc. :D

**Comment by LexManos** [comment]
My basic idea for this is to to have two progress bars one for the overall FML loading cycle and then one that mods could request. Well in theory this would be infinitely nestable.
progress = LoadProgress.begin("Title", maxSteps)
progress.step(x);
progress.end();


However, THREADING the main load won't work as it would break so many mods.
The only real option here is to make the system able to do callbacks and force the screen to re-render. 
Hook in some input processing into those re-rendering steps and you can fake 'responsivness'

**Comment by CreativeMD** [comment]
Hm, but is it really a problem that the mods don't load in the main thread?
There could be only OpenGL issues, but the main thread doesn't do anything while the mods are loading (no "overlapping").
while(loadingScreen.isAlive())
{
   loadingScreen.renderScreen();
   updateDisplay();
}

**Comment by Kubuxu** [comment]
@LexManos CreativeMD suggests to move mod loading from thread used for OpenGL to some other. It would solve issues with "non responding" window but wouldn't cause any threading problems (mods would still be loaded in one thread just different from that used for OpenGL context creation).

**Comment by LexManos** [comment]
Its possible but last time I tried rolling out this exact solution it exploded when I tested it on mods packs.
Minecraft itself does quite a bit with GL/AL during startup. 
Not to mention those mods who do fancy graphics generation while starting up.

The only solution that I found feasible is to litter the loading process with 'progress update' messages.

**Comment by RainWarrior** [comment]
it's possible to do it other way around - transfer display context to another thread, provide main thread with another context, and swap them back when the loading is done: http://www.youtube.com/watch?v=GqsfaTLtD6c
GL access in main thread should still work fine, except for the actual draw calls (which shouldn't happen during the loading anyway).

**Comment by Kubuxu** [comment]
But on second thought what if mod prepares GL buffers at load time. They would generate them but would be unavailable in main GL context. Option would be to generate context for loading screen only and then transfer screen ownership (if that is possible).

**Comment by CreativeMD** [comment]
@LexManos Loading textures should work. We could set up a new event for exactly that problem.
@RainWarrior I tested it and it didn't work out. (http://forum.lwjgl.org/index.php?topic=5743.0). I can draw something from the thread, but the window would still freeze.
@Kubuxu Everything special should be done in the main thread (a new event: example FMLInitializeSpecialRenderingEvent)

**Comment by Kubuxu** [comment]
Problem is that it would break current mod compatibility.

**Comment by CreativeMD** [comment]
Only a few mods updated to 1.8 already and only a few of them would get in conflict with it. I think only Optifine & Shaders would have to update as far as i know.

**Comment by chibill** [comment]
Still not a very good option there.

**Comment by CreativeMD** [comment]
It's not that big kind of deal. We have the option to implement this in mc1.8.3 so no mods would have to update their existing mod version. I don't think that this would be the big problem.

**Comment by aschmois** [comment]
If fixing this breaks mod compatibility I would suggest doing a 2 stage update. One with all the API calls necessary to fix what needs to be fixed and give enough time to let modders update. If they don't update after a pre-defined date, then the modder should be more responsible. I've always wondered why this would be so hard to fix and now I see, but after so many years maybe it's time to fix it?

**Comment by CreativeMD** [comment]
I could do some testing if mods are incompatible with it, but i have no idea how do reobfuscate my workspace?

**Comment by RainWarrior** [comment]
In the meantime I'll continue with my approach: http://www.youtube.com/watch?v=cNH-gWRhk1Q :P

**Comment by CreativeMD** [comment]
ok? so obviously yours is working, why should i make another one :O ?

**Comment by Kubuxu** [comment]
@RainWarrior you are transferring only display context not OpenGL context right?

**Comment by CreativeMD** [comment]
Ok, i think @RainWarrior does a better job :D . I'm glad that someone else took this challenge because my skills using OpenGL are primitive :D
