### ISSUE TITLE
Crash generating world with latest 1.8 forge

### ISSUE THREAD

**Issue by 61352151511** [MinecraftForge/MinecraftForge#1765]
Has something to do with structure generation, with forge 1344 http://pastebin.com/GeGxM2rC

**Comment by chibill** [comment]
Try with out any mods and also give them the full log.

**Comment by 61352151511** [comment]
This is in a dev environment so it is without mods (Apart from mine which doesn't touch any structure things) That's basically the full log. It contains all the information about the crash from my eclipse console.

**Comment by chibill** [comment]
Have you tried the latest?

**Comment by 61352151511** [comment]
Really? Like seriously? Look at the name of this issue...

**Comment by chibill** [comment]
Well.. I should have checked first...

**Comment by LexManos** [comment]
I know about the issue, it's related to cpw's registry edits. From talking to him it looks like he simply didn't commit everything that he had done. So just gunna wait until he does. 1344 is a bad build, i'll nuke it from the file server.
