### ISSUE TITLE
Allow Customized ID Settings

### ISSUE THREAD

**Issue by Speiger** [MinecraftForge/MinecraftForge#1768]
The new ID System Idea is a thing... Yeah it works.
But it has a really big mistake. And a couple people asking me if i could fix that with a submod.
The problem is that there is the case that you can not remove blocks/Items/Mods because of the current system.
I am not against this idea. It works but add a file that allow to change the BlockIDs/ItemIDs manually.
A Simple File that allow to set a differend ID and after loading minecraft is fully loaded they change the IDs of it.
Sadly i am not able to use ASM else i would have done it already...

**Comment by LexManos** [comment]
You can remove blocks and items.
Once a world is loaded with missing entries it will warn the user, backup the world and then continue.
After that save the missing ids are wiped from the world and can be used again.
So, where exactly is the mistake and what would you have us do 'better'?
The idea is to NOT give end users control over the ID mappings, plus having them in the level NBT is convenient.
If someone REALLY wanted to screw with those they can but we do not support it as the behavior of Forge should be safe as nessasary for the users.

**Comment by Speiger** [comment]
Removing the Controll from users is generally a stupid idea. It is also a stupid idea to force people to setup everything. The middle is the best solution.
First of all the Problem i got often enough is that the worlds got currupted because they removed a mod, because all IDs did merge around and nothing was there where it belongs. 
To solve that there should be a textfile or people should be able to create a textfile where they can put in the Block/Item names and the new id they want to have. 
So that casual players/people that do not want to go deep into the thing can setup customID settings, and other people are free from it. It is simply better to let people the choice if they want.
And NBT Data is not a thing in the case i mean because the Items Itself have No NBTData. ItemStack Stores that. The idea does not mean to have controll over the ItemStack. It is to have controll about the Item/Blocks which are simply static...

I made a basic Layout for the ID Merging, it is the best i could do since i am not able to use ASM or something like that... also it is not working since FML/Forge blocking the access at the point where it is required..

http://www.mediafire.com/download/tc3mgq7zsvd9h33
Just two small Text Files. The Mod Itself and the Entry Class for Blocks so you guys do not get confused.

I hope you could find what my request is if not:
Make it possible (even if it is hidden) that people can setIds so that WorldCurrupting ID Missmatches when a mod gets removed can be solved. (Terrible english i am sorry for that)

**Comment by chibill** [comment]
you do know that the way forge does it now is better then what you just said. As 1. Forge stores that id data as a the unlocalized name to the ID (I think). and 2. There is no reason to make users have to deal with id conflicts again.... As IDs are technically gone.

**Comment by Speiger** [comment]
A: If that would be the case why would a world currupt when you remove a mod, when the ids are stored and not exsisting technical anymore.
B: Technical the ids are merged to a hidden place and the user only get the Strings of it. But these Strings link to the IDs.
C: That option should be for people who want to mess around with that.. And i know people who want that. Even myself.

**Comment by chibill** [comment]
Well to answer 
A: You Might have a bad build of Forge or something. Or just the mods in your pack not registering stuff right.

B: Well you almost understand that...
C: Then make a launcherWrapper to do it yourself as Forge does not want to make the users deal with stuff that can break everything again..

**Comment by Speiger** [comment]
A: I will not use 1.7.x.... Reasons (this one included)

B: I know how that system works. Just a terrible discriber.
C: A + 1.6.4 has that ability already...

**Comment by Speiger** [comment]
An addition: That people that have those trouble used always the recommented version of forge/mods.
So if that is the case the coders made an unstable version public without telling people trouble cases.

**Comment by chibill** [comment]
The only reason 1.6.4 has this ability is because it does not have the better ID system that helps both modders and users....

**Comment by LexManos** [comment]
As stated if a user wishes to screw with the internal mapping of their world they can.
It's just in NBT {which there are literally THOUSANDS of tools to edit} not plain text. Plain text is just ASKING for people to screw things up.
Basically what this issue is boils down to "I do not understand the system make it more friendly to me so I can break things!"
And the simple answer is no, if you wish to break things we will not encourage you to do so.

And a note we deal in registry names, which have NOTHING to do with 'unlocalized' names.

**Comment by Speiger** [comment]
@lexmanos. If there are tool to solve that then fine...

@chibill The only thing that is good about the new ID system is that you can create a block/Item without register them...
Rest of it is just the same thing but with helpers which make some things easier but most things a lot harder...
I think anyway that the current system will change again. So we will see. 
A thing you could remove by the way is the ID limit. It is set by forge anyway

**Comment by diesieben07** [comment]
The ID limit is _not_ set by forge. It's set by the save format. Blocks are saved as numbers in the world file and there are only 12 bits reserved for a BlockID. 12 bits = 4096 possible IDs. This is not a forge thing.

**Comment by Speiger** [comment]
@Diesieben i found only in the forge/fml classes the function that crashes the game if a id get registered over a limit.

**Comment by coolsquid** [comment]
The method that crashes the game is a part of FML, and exists to prevent severe issues and/or world corruption later.

**Comment by Speiger** [comment]
The same could happen with the current system when you remove a mod from a world.
Thankfully forge can not remove ids completly!

**Comment by LexManos** [comment]
This is going in circles, the 'suggestion' has been denied because it would break too many things. End of discussion.
