### ISSUE TITLE
[Feature Request] - Customizable (by server admin) reject message

### ISSUE THREAD

**Issue by hunter688** [MinecraftForge/MinecraftForge#1772]
Will be possible add custom reject message, when client connect to server and have wrong version/missing mods? Instead of mod list rejections server send custom message for example: "You have wrong version of mods, please update modpack" - this message will be configurable at server side and show to client when disconnected.

This feature will be very useful when backported to 1.7.10 too.

Many youngest players does not understand rejecting message with list of mods.

**Comment by luacs1998** [comment]
I personally think this should be done with a mod.

**Comment by LexManos** [comment]
1) Backporting is a no, JUST FREAKIN UPDATE!
2) We've talked about this quite a few times before, and deemed that its not needed and is just advertising BS. But I will leave it up to cpw to decide.

**Comment by asiekierka** [comment]
It's not advertising BS, just a simple matter of user convienence - especially for private modpacks which do not use a launcher.

**Comment by ghost** [comment]
any progress?

**Comment by mezz** [comment]
I think this error message could use a general improvement in Forge so that it can benefit everyone, like with the missing mods error screen done here: https://github.com/MinecraftForge/MinecraftForge/pull/2997

**Comment by ghost** [comment]
no progress?

**Comment by Zidane** [comment]
@mezz 

What is the likelihood of this going into Forge? I'd rather not touch stuff like this in SpongeForge if at all possible.

**Comment by ghost** [comment]
Idk why is this feature request ignored two years. I think implementing will help many and many players understand why cannot join to modded server. This can help grow community around modded servers.

**Comment by raoulvdberge** [comment]
A custom reject message will cause more confusion. Isn't the current reject message clear enough?

**Comment by ghost** [comment]
I prefer custom reject message instead of present list of rejected mods. Try to look at the eyes of an inexperienced player, a rookie in Minecraft, who do not say anything like FML, and so on. That's what's going on here. I just want a message that will be friendly to the newcomers.

**Comment by diesieben07** [comment]
Then you should strive to improve the default message (make a PR?) and not make your own custom one, which will just confuse matters even more.

**Comment by ghost** [comment]
Custom = configurable at server side.

**Comment by ghost** [comment]
For example on my server want message in the czech languange, any other admin on its own server would like message with url to their private modpack etc...

**Comment by raoulvdberge** [comment]
No, the current message should just be improved.

Again, having a custom message is more confusion since the player can't easily identify reject GUIs otherwise.
