### ISSUE TITLE
Add Option function is useless

### ISSUE THREAD

**Issue by Speiger** [MinecraftForge/MinecraftForge#1774]
The Function inside of the EnumHelperClient addOption is useless because it will be dissabled by mc itself.
I tried to add an option and i need to make a huge workaround to make it actually work. (Simply i use the option only to generate the slider and then i use everything else then the option to check where the sliderbar is) that makes it useless.
Please find a way/add a way that you can use that function without that minecraft dissables it.

**Comment by LexManos** [comment]
The EnumHelpers are just there to extend the enums they were created for every enum that exists in the workspace. I'm trying to think of a typesafe way to kill EnumHelpers but until then this is what we have.
However, this does not guarantee extending the enum will actually DO anything. That is not what this is for.

In this case, use your own Mod config screen that is exposed via the config system/FML.

**Comment by Speiger** [comment]
^^" ok good to know... That what you told me i did that already when i made the request.
The thing is that you require an option for a slider button. And there is two ways.
Make your own slider button or use the mc one.
The mc one requires an option. But when you use an custom option. The sliderbutton is automaticly dissabled.
Fml/forge should provide maybe a base slider button so that not every mod need to create its own...

**Comment by diesieben07** [comment]
Thats neither FML's nor Forge's job.
