### ISSUE TITLE
[Question] Brewing stand recipe registry system

### ISSUE THREAD

**Issue by ganymedes01** [MinecraftForge/MinecraftForge#1779]
The forge events for pre/post brewing aren't enough for extrapolating the functionality of the brewing stand, it still restricts the user from inserting anything that isn't a glass bottle or water bottle into the input slots and blah blah.

My question is if a registry system similar to the furnace one could be implemented on top of the vanilla one. A simple registry with 1 input, 1 ingredient and 1 output would be more than enough for mods to do whatever they want to the brewing stand and allow for mods such as NEI to hook into it and show the recipes (the current event model is quite unpredictable, so no recipe viewing mod is be able to handle what modders could do with it).

The event system wouldn't need to be touched or removed, so backwards compatibility would be immaculate.

I can't think of a reason not to do this, it would finally unleash the brewing stand's potential since currently it just sits ignored by mods due to it being hardcoded for recipes.

I'd do the patches myself for both 1.7.10 and 1.8 if this gets a yes. Just wanted to get people's opinions first before writing the whole thing out just to see it shut down for a reason I didn't account for.

**Comment by LexManos** [comment]
The problem is that is not how the brewing system is designed. The brewing system is written in such a way that it's fundamental mechanic is chaos. Basicly, I think the idea went through Notch's head like this "I wanna make a minigame, something with bits! RANDOM EVERYTHING!"
The problem with trying to re-write the system into a one in one out thing is that things can be brewed in dozens of different ways.

**Comment by ganymedes01** [comment]
It wouldn't be a re-write, it would sit on top of the vanilla system. It would check for a recipe using the vanilla mess, if failed, then check for the forge registry (or maybe the other way around, not sure). Plain and simple.

**Comment by ShetiPhian** [comment]
Sounds interesting, I've currently got nothing to use it for but having it as an option would effect future projects.
If you check the forge registry first then fall back to vanilla, people would have the chance to override the default recipes.

**Comment by ganymedes01** [comment]
Closing as this was added months ago.
