### ISSUE TITLE
Server with Forge 1360 crashing

### ISSUE THREAD

**Issue by halvors** [MinecraftForge/MinecraftForge#1785]
Here is the crashlog: http://pastebin.com/xqLBUHXc

**Comment by GirafiStudios** [comment]
Minechem needs to update to a newer version of Forge. This is related to the changes which have been made to Fluids in Forge lately

**Comment by KingLemming** [comment]
Has nothing to do with Minechem updating to a newer version of Forge. It has everything to do with them just not doing things right. They're targeting a null fluid.

**Comment by chibill** [comment]
its a forge problem and it was just fixed today wait for the forge build that the fix is in to be built and be on your way.

**Comment by halvors** [comment]
@chibill #1784 fixes this issue? But i thought that Forge 1360 included that fix, doesn't it?

**Comment by KingLemming** [comment]
This is fundamentally not a Forge issue. Minechem is doing something wrong. We can't backwards compatible the corner cases where mods screwed up. :/

**Comment by KingLemming** [comment]
Okay, I've added stupid proof code. It's the equivalent of child-proofing. We now deny mods the ability to do dumb things with the FluidContainerRegistry. Though the mods still need fixing on their end.

**Comment by Unrepentant-Atheist** [comment]
OOT, but are you back to MC modding King?!?! Done with the PhD? :)
