### ISSUE TITLE
Falling through world on respawn.

### ISSUE THREAD

**Issue by DPxKnightxZero** [MinecraftForge/MinecraftForge#1788]
I am using forge 1.7.10 360 and my players when they respawn keep falling out of the world or spawning in blocks. They used to spawn right on top of their beds which made way more sense ... any reason this is happening? Its making spawn points in houses unusable. Might I suggest implementing precise spawn set to prevent this? Also our ping is great and no desync.

**Comment by laz2727** [comment]
Desync. It should put them back in about 5 seconds, otherwise you have some
serious ping issues.

**Comment by DPxKnightxZero** [comment]
Lol you just wrote what I was adding XD

**Comment by laz2727** [comment]
Do you have any mods that mess with beds/sleeping? And being a little bit
buried happens in vanilla too.

**Comment by DPxKnightxZero** [comment]
Just forge essentials.

**Comment by LexManos** [comment]
Beds find a spot next to them that is free to spawn in. If they cant they spawn on the bed head itself.
If you fall through the world its because your server is laggy and not sending them the chunk data before the respawn packet. Remove 'Forge Essentials' and see what happens.

**Comment by DPxKnightxZero** [comment]
Alright.Well I let them know too since they might be the cause :/ I think it would be faster if you just test it yourself. 

Reference point https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/876

**Comment by DPxKnightxZero** [comment]
Alright this is gotten even worse with 370

**Comment by LexManos** [comment]
If it got worse with 370 of FE then go blame the FE people.
Remove FE and tell me if it happens.

**Comment by DPxKnightxZero** [comment]
Alright. I will test it. Right Now.

**Comment by luacs1998** [comment]
Disable FE's auth module, report back to me. I'll take it over on my side, so Lex, can you close this issue?
