### ISSUE TITLE
[Proposal/Draft] IBlockProxy

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#1792]
Current code: https://gist.github.com/SoniEx2/fd211116ca7c2a850600

Applied Energistics adds P2P Tunnels, Compact Machines adds Compact Machines, Thermal Expansion adds Tesseracts. All of them have something in common and that is that they have blocks that let you access other blocks.

A block set to "Input" would return all blocks set to "Output", a block set to "Output Only" would return null (empty array is for an unlinked "Input" block), a block set to "Input Only" would never be included in the list. "Input | Output" (inclusive or, acts as input and output _at the same time_) blocks should return themselves, "Input ^ Output" (exclusive or, acts as input and output but cannot output to itself) blocks should NOT return themselves.

Chaining of the blocks is up to the mod. (e.g. direct (no cables in between) AE2 P2P -> TE tesseract -> CM may or may not work depending on how the mod author wants to handle it)

cc @amadornes @asiekierka @AlgorithmX2 \<does anyone knows dan200's (ComputerCraft author) github? CC has network cables and stuff\> \<anyone else I missed\>

**Comment by laz2727** [comment]
Currently,  all of them are teleport pipes and only EIO has a block that
works like that.

**Comment by SoniEx2** [comment]
@laz2727 What do you mean? They all support the 3 basics: item, fluid, energy, and CM and AE2 support AE2 and redstone as well, and AE2 also supports light.

**Comment by KingLemming** [comment]
Isn't necessary nor warranted in Forge, frankly.

**Comment by laz2727** [comment]
They don't let you access other blocks. They transmit multiple contents
wirelessly or using basic channels,  and that's it. Rio is the only one
that actually lets access other blocks.

**Comment by SoniEx2** [comment]
@laz2727 Well it would be nice to be able to P2P tunnel CC cables :/

**Comment by laz2727** [comment]
CC? Neither Cubic Chunks nor COFH Core has any.
And it won't get pulled, lex never pulse anything non-vanilla.

**Comment by SoniEx2** [comment]
@laz2727 ComputerCraft. Also, fluids are non-vanilla.

**Comment by laz2727** [comment]
They are, water and lava. Fluid system extends that.

**Comment by SoniEx2** [comment]
One could argue water and lava are liquids, fluids are not liquids (altho liquids are fluids), thus fluids are non-vanilla.

**Comment by laz2727** [comment]
They are called fluids because Lord of the Lemmings had to call them
somehow and liquids were already taken by the inferior bc system.

**Comment by SoniEx2** [comment]
Well Forge does have "Modifications to the Minecraft base files to assist in compatibility between mods." as a motto and this would require a minor change to hoppers and droppers...

**Comment by LexManos** [comment]
This is a fundrmental flaw in design, basically you're moving the work from the one mod implementing speial funtions to every mod that wants to interact with thim. If a block is a "proxy" for another block then they should be a tranpatent proxy to their consumers.
