### ISSUE TITLE
Minecraft Forge Empty NBT string crash.

### ISSUE THREAD

**Issue by AnodyneEntity** [MinecraftForge/MinecraftForge#1797]
Updated all the CoFH mods, Dragon API, RotaryCraft, Mekanism and update the Forge version to 1370 and now I get this crash when the server tries to save the world or I try to manually save the world.

http://pastebin.com/p1rqsqM5

Is this purely a forge issue? Or is one of the mods I updated causing it?

**Comment by cpw** [comment]
Duplicate of #1798
