### ISSUE TITLE
Possible desyncing between FluidRegistry maps

### ISSUE THREAD

**Issue by ZornTaov** [MinecraftForge/MinecraftForge#1798]
So I made a small mod that outputs the contents of FluidRegistry.fluids to the console, which can be seen from line 8791 down to 9204 on this log http://paste.ee/p/gNHr7 .  At the bottom of the log, there is a crash for FluidRegistry.writeDefaultFluidList(FluidRegistry.java:311) where FluidRegistry.getDefaultFluidName is giving the NBTTagStringan empty string.  

I believe the problem lies with some desyncing or the like in the FluidRegistry class or elsewhere that is causing the mappings of FluidRegistry.masterFluidReference to not be the same as FluidRegistry.fluids.

As the log shows, I was able to print all of the names and the ID's for every fluid in FluidRegistry.fluids, but I am unable to see the contents of FluidRegistry.masterFluidReference.  PLEASE add a bit of error handling and tell the user what fluid caused the problem somewhere in here!

**Comment by ZornTaov** [comment]
Just thought of something as I took a moment to walk away from my computer to think. When using FluidRegistry.registerFluid, could you check if the fluid is null before adding it to the masterFluidReference?

**Comment by ReikaKalseki** [comment]
I would definitely recommend that. I see no reason to allow the registration of null, or an empty-name fluid.

**Comment by KingLemming** [comment]
There is a derp somewhere in here. @cpw is the go-to on this particular piece of code.

Adding a null check in registerFluid won't actually matter - if the fluid is null, that function is going to explode anyways.

I'll look into it.

**Comment by cpw** [comment]
Not a derp in syncing - there's nothing to sync really (just a list of strings). The problem is that the fluid isn't in masterFluidRegistry, so someone is reflectively adding their fluid to the fluid list, not using registerFluid. This is now checked in 1377, so you should have a more meaningful crash

**Comment by ReikaKalseki** [comment]
...Who in their right mind would register it reflectively?

**Comment by cpw** [comment]
No idea, but it seems the most plausible reason its in one map and not the other..

**Comment by ReikaKalseki** [comment]
Did anything ever come of this?

**Comment by mezz** [comment]
There is a PR for 1.13 to make the fluid registry a "real" registry like Items and Blocks, so it will work reliably.
https://github.com/MinecraftForge/MinecraftForge/pull/4098
Beyond that I don't think anything has been done for this issue.
