### ISSUE TITLE
ItemArmor.func_151685_b is implemented incorrectly

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/MinecraftForge#1799]
Due to the way that function (getRepairItem) is implemented, if the method is called prior to all new armor types being registered, the game will crash with an ArrayIndexOutOfBoundsExeption when it's called on a newer armor type because switching on an enum creates a private internal class that creates an array of ints for jump indicies in its static initializer, when compiled through javac.

The correct implementation is to retain the vanilla if/else chain, or to switch on the `ordinal()` directly. The latter has potential for issue, however.

**Comment by cpw** [comment]
Should be fixed - I tidied up the ternary and made it return customMaterial.
