### ISSUE TITLE
Block placement (against air/fake blocks) differs from vanilla

### ISSUE THREAD

**Issue by Lunatrius** [MinecraftForge/MinecraftForge#1801]
When placing blocks against ghost/fake client blocks (or against air by computing the required parameters) the block does not get placed where it was supposed to be placed.

Vanilla: https://youtu.be/OjoWJAuS41Y

Forge: https://youtu.be/kVCixy351wk

Example mod: https://gist.github.com/9863af91852020e69bf6

The only thing that I was able to figure out is that the same thing occurs on both sides (can be only noticed when placing against air instead of a fake block).

**Comment by LexManos** [comment]
I'm considering this a bug FIX, vanilla air isn't replaceable, it's considered a solid block. 
We change that: https://github.com/MinecraftForge/MinecraftForge/commits/master/patches/minecraft/net/minecraft/block/BlockAir.java.patch
This is what allows 90% of block automation to work as well as preventing the need to special case AIR all over the place.
If a player does things that cause the client to be desynced between the server like creating false client blocks then that's their problems.
