### ISSUE TITLE
The world may have leaked

### ISSUE THREAD

**Issue by Redlotus99** [MinecraftForge/MinecraftForge#1803]
I am getting an error stating "The World may have leaked" and I think I have narrowed it down to the Hardcore Ender Expansion mod, but I am posting the error and issue here just in case it may be a Forge issue.

The log file can be found here:

https://gist.githubusercontent.com/Redlotus99/8735f0778fa6797362a5/raw/gistfile1.txt

Link to my cross-reference post to HEE:

https://github.com/chylex/Hardcore-Ender-Expansion/issues/110

I am using:

Forge 1370
MC 1.7.10

**Comment by LexManos** [comment]
Its not a forge issue. I've done testing and everything in Forge frees the world.

**Comment by Redlotus99** [comment]
TY Lex
