### ISSUE TITLE
AnvilUpdateEvent only fires when BOTH input slots are full

### ISSUE THREAD

**Issue by AKA-Syenite** [MinecraftForge/MinecraftForge#1807]
https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/inventory/ContainerRepair.java.patch#L25

Hook should be above the null check

**Comment by LexManos** [comment]
The idea is to have both items, what are you doing that requires only one?

**Comment by Shukaro** [comment]
Working with NBT data if the player is renaming an item
