### ISSUE TITLE
[Feature Request] Add "Side" parameter to "BlockEvent.PlaceEvent" event

### ISSUE THREAD

**Issue by wmrojer** [MinecraftForge/MinecraftForge#1808]
Need to know on what "side" of the "placedAgainst" block the new block is place to be able to know what direction to build in.
The "side" parameter is available and use where the event is created, so it should just be a matter of including it in the event class.

**Comment by Speiger** [comment]
Not need since when the event is fired you have access to the EntityPlayer and then you can calculate that relatively easy...

**Comment by Speiger** [comment]
What i would like to know where you got the idea/code to make the block placed event?
Because i created for Eureka the way to detect when a block got placed (and it is part of my mod in 1.6.4) and short after that forge said that they will also make that kind of an event...

**Comment by Speiger** [comment]
that is dublicate...
but i can not find the other one...
Simply not nessesary you can access the Player which allow you to see which direction he is looking, then use the oppsite (i created that system for the mod Eureka too and it is not nessesary at all)

**Comment by williewillus** [comment]
1. this isn't going to be completely reliable. Lots of mods, especially those that place blocks for the player like ProjectE, fire place events and would have no way of giving you something useful
2. If you wanted to guess you can raytrace from the player

**Comment by LexManos** [comment]
What do you mean by 'know what direction to build in.'
What are you trying to do/make that isn't possible with the system already.

**Comment by williewillus** [comment]
I'm guessing some sort of "EnumFacing sideHit"
