### ISSUE TITLE
Latest Forge doesn't work with MCPatcher

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [MinecraftForge/MinecraftForge#1811]
Previously I've been using Forge and MCPatcher without a hitch. I don't like Optifine. Now after a few months hiatus I can't get it work together anymore.

By MCPatcher, I'm referring to: http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1226351-1-8-3-1-7-10-and-earlier-update-2-26-mcpatcher-hd 

The issue is: http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1226351-1-8-3-1-7-10-and-earlier-update-2-26-mcpatcher-hd?page=582#c11825

Somebody thinks it's Forge: http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1226351-1-8-3-1-7-10-and-earlier-update-2-26-mcpatcher-hd?page=582#c11826

**Comment by LexManos** [comment]
MCPatcher is a jarmod, it edits base classes, it's on the same category of Optifine, and Coremods.
As such we do not explicitly support it.
It's up to them to adopt and keep compatibility. 
That being said, we haven't done anything major lately, it may be the rendering changes Fry did a few weeks back that is screwing with it.
Tell them that they are outdated and they need to update.
