### ISSUE TITLE
Possible Forge Fluid problem?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [MinecraftForge/MinecraftForge#1812]
Not sure where to post it, so I went to MFR and here. Referring to this issue: https://github.com/CoFH/Feedback/issues/446

**Comment by LexManos** [comment]
MFR is querying a null Fluid.

**Comment by Unrepentant-Atheist** [comment]
LIES! No but seriously, upgrading to 1387 solved the problem. MFR hasn't been updated in that time span, but Forge has. So...what gives?

**Comment by cpw** [comment]
There was a bug in forge. Fluid ids weren't being remapped properly.. Fixed now..
