### ISSUE TITLE
1.7.10 Vanilla bug With Dark oak breaking through bedrock.

### ISSUE THREAD

**Issue by Razorskills** [MinecraftForge/MinecraftForge#1813]
here is a good bug report that displays the issue well. https://bugs.mojang.com/browse/MC-10176 Mojang has fixed this bug in 1.8, but it is an annoying issue in 1.7.10 servers. And wont be getting fixed for 1.7.10 obviously. Perhaps someone might be able to solve it and implement a dark oak generation fix for 1.7.10

https://bugs.mojang.com/browse/MC-10176

I think they fixed it by making saplings unable to replace blocks

**Comment by LexManos** [comment]
We're not going to become a backporting project... You could go through and pick hundreds of bugs to backport it's just a waste of time. This one in particular has no real bad effects...

**Comment by Razorskills** [comment]
Ok, you are right.
