### ISSUE TITLE
Issue when installing any modpack not complimentary with the technic launcher

### ISSUE THREAD

**Issue by SirSpace** [MinecraftForge/MinecraftForge#1815]
Can someone please help me I am having an issue when getting to the last stage of the install when downloading the libraries of a modpack (that is not built in with the technic laucher) an error pops up saying, "Failed to download http://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config- 1.2.1.jar" I would really like to play the mod but I can't due to this error. P.S. This happens on every modpack I attempted to install so far that does not come with the launcher. T_T D;

**Comment by LexManos** [comment]
Its because that file does not exist, use Forge's installer to install Forge.

**Comment by SirSpace** [comment]
but i am using the technic launcher to attempt to install modpacks
