### ISSUE TITLE
Issue: How do I install forge whilst using the Technic Launcher?

### ISSUE THREAD

**Issue by SirSpace** [MinecraftForge/MinecraftForge#1816]
Can someone please help me I am having an issue when getting to the last stage of the install when downloading the libraries of a modpack (that is not built in with the technic laucher) an error pops up saying, "Failed to download http://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config- 1.2.1.jar" I would really like to play the mod but I can't due to this error. Somebody told me this file does not exist and to install the forge installer but how would I install forge whilst using the technic launcher?

**Comment by matthewprenger** [comment]
Perhaps you ask the Tehnic folks.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/1815#issuecomment-94326952
