### ISSUE TITLE
[1.7.10] Crash with forge 1.7.10-10.13.3.1389-1710ls

### ISSUE THREAD

**Issue by SJ1133** [MinecraftForge/MinecraftForge#1818]
Crash with the latest forge and liteloader.
http://pastebin.com/7m5dxU8C

**Comment by LexManos** [comment]
Keep it in https://github.com/MinecraftForge/FML/issues/644 as instructed.

**Comment by SJ1133** [comment]
Ah sorry. I posted there. Sorry for the hassle
