### ISSUE TITLE
Question to sounds

### ISSUE THREAD

**Issue by Speiger** [MinecraftForge/MinecraftForge#1823]
I saw that the Sound Load event is deprecated. Well yeah since the sound Manager will be no longer really accessable that is understandable.
But this event is nessesary (not with the soundManager in it) because it tells when the sounds get Reloaded. (Without that modded sound engines (like the ic2 one) will crash after the next sound will played).
So the question is will be there a new event that tell, that the sound engine reloades?

**Comment by diesieben07** [comment]
`IResourceManagerReloadListener`

**Comment by Speiger** [comment]
@diesieben07 mit ein bisschen mehr details wäre es einfacher zu verstehen...
Aber danke das beantwortet meine frage...

**Comment by diesieben07** [comment]
Well, this is not a support forum, if you have question about this, make a forum post.
