### ISSUE TITLE
Dropped item stacks look wrong

### ISSUE THREAD

**Issue by Brottweiler** [MinecraftForge/MinecraftForge#1824]
# Without Forge
![image](https://cloud.githubusercontent.com/assets/1613137/7306960/5d974726-ea09-11e4-84d4-dfb271b5d956.png)

# With Forge
![image](https://cloud.githubusercontent.com/assets/1613137/7306970/68701af6-ea09-11e4-8cf4-cd0f32f1c11b.png)

**Comment by DZCreeper** [comment]
Are you using just Forge? This doesn't appear to be a bug, looks like clumped item drops which is better for performance but not included in Forge unless Lex changed his mind since 2012.

**Comment by LexManos** [comment]
This is actually a bugfix that we've added for like.. 5 versions now. It makes it fall in line with the block itemstacks.

**Comment by Brottweiler** [comment]
@LexManos So it's intended that they drop in these "fast mode" stacks, and not the "aligned" stacks, if that makes sense? Hard to explain how they look like.

In vanilla, they look as in the first picture. It is **intended** to make them look like in the second picture?

**Comment by LexManos** [comment]
The second picture is kinda odd, the Z's shouldn't line up that much, But as it uses a RNG you m of gottena bad RNG.
It SHOULD be all overlapping on the Z and offset a bit in each layer. SO yes. The second one is intended.
'Fast Mod' should switch to 2d IIRC.

**Comment by Brottweiler** [comment]
Why do you intend to have it look like that? IMO, how it looks vanilla looks better.

**Comment by LexManos** [comment]
Looking into the z issues, seems somewhere it got messed up. But i'll look into it. They should look more like this: http://puu.sh/hoTQp/0522d0051b.jpg

**Comment by Brottweiler** [comment]
Alright, I understand how they are supposed to look. Although I still don't understand why you want them to look like that, and not like in vanilla? Any specific reason?

**Comment by LexManos** [comment]
Because it matches the 2D version that vanilla has, as well as matching the mechanics of blocks, and honestly just looks better :P

Having it behave like everything else is important.

**Comment by Brottweiler** [comment]
Alright. As long as it's intended I guess it's fine. 😛

**Comment by Brottweiler** [comment]
Thanks for quick response, btw!
