### ISSUE TITLE
[1.7.10ls] java.lang.IllegalStateException: Splash thread

### ISSUE THREAD

**Issue by erkro1** [MinecraftForge/MinecraftForge#1827]
Not sure if we should be using this branch but it's the top on the forge site.
I get this error when I'm starting up Minecraft.

Full crash log:
http://pastebin.com/vBdtHedd

**Comment by portablejim** [comment]
It has to do with MinecraftForge/FML#644 . These crashes should be dealt with there.

Post the full crash report (the ENTIRE file) to https://gist.github.com/ (it works like pastebin; make a public gist) and post the url to the bottom of MinecraftForge/FML#644 saying you crashed.

Also indicate if you have either Optifine or Fastcraft installed.

**Comment by cpw** [comment]
Thank Jim. Submitter, please follow Jim's instructions..
