### ISSUE TITLE
[1710ls] Can't use @ObjectHolder with fluid blocks

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#1828]
Using @ObjectHolder in the class where you register fluid blocks = crash because fluid isn't registered.

Steps to reproduce:
1. Make a fluid
2. Make a Fluids class with "public static final Fluid f = new MyFluid()"
3. Make a (classic) fluid block
4. Make a Blocks class with @ObjectHolder
5. Use the Fluids.f fluid when constructing the fluid block
6. ???
7. Crash

**Comment by LexManos** [comment]
Code

**Comment by SoniEx2** [comment]
Here you go: https://github.com/SoniEx2/Cola

(Couldn't find a minimal test case :/)

**Comment by LexManos** [comment]
Then make a minimal test case.

**Comment by SoniEx2** [comment]
Crash.java:
```java
package crashtest;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

/**
 * @author soniex2
 */
@Mod(modid = "crash", name = "Crash", version = "1.0")
public class Crash {
    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        Fluids.init();
        Blocks.init();
    }
}
```

Blocks.java:
```java
package crashtest;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.material.Material;
import net.minecraftforge.fluids.BlockFluidClassic;

/**
 * @author soniex2
 */
@GameRegistry.ObjectHolder("crash")
public class Blocks {
    public static final BlockFluidClassic fluid = new BlockFluidClassic(Fluids.fluid, Material.water);
    public static void init() {
        GameRegistry.registerBlock(fluid, "fluid");
    }
}
```

Fluids.java:
```java
package crashtest;

import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidRegistry;

/**
 * @author soniex2
 */
public class Fluids {
    public static final Fluid fluid = new Fluid("crash:fluid");
    public static void init() {
        FluidRegistry.registerFluid(fluid);
    }
}
```

**Comment by SoniEx2** [comment]
Hmm, fluids are Forge, ObjectHolders are FML... did I report this to the wrong repo? or should I report to both?

**Comment by immibis** [comment]
Your bug is not directly related to ObjectHolder (that's just the "catalyst"). If *anything* accessed Blocks before Fluids.init was called you would have the same problem. Don't set up Minecraft things in static initializers.
