### ISSUE TITLE
[1.8-Suggestion] Event for getTexture in BlockModelShapes

### ISSUE THREAD

**Issue by 61352151511** [MinecraftForge/MinecraftForge#1835]
As I have no idea how to make Minecraft class patches I'll make a suggestion and hopefully someone likes it and could do it.

In net/minecraft/client/renderer/BlockModelShapes there's a method:
public TextureAtlasSprite getTexture(IBlockState state)

This is how Minecraft handles the breaking particles for vanilla custom modeled tile entities. It returns a texture for what the block breaking particle should be.

If there was a forge event or hook that could pass on the block state so mods could determine the block particle breaking in a similar fashion, that would be really helpful.

**Comment by Parker8283** [comment]
Fork forge and clone it. Make a new branch and run graldew setupForge. If you use Eclipse, then just set your workspace to the eclipse folder. If you use IDEA, it's a little harder. I have a public gist for it I think. Then make your edits. Then run gradlew genPatches. Then push your branch to GH and make the PR.

**Comment by RainWarrior** [comment]
Problem with this method is that it doesn't get the whole IBlockAccess + BlockPos pair - only the state, so usual strategy of calling Block.getExtendedState + ISmartBlockModel.handleBlockState isn't that easy.
I'm thinking about making another getTexture (with those arguments added) and changing all places that can provide IBlockAccess + BlockPos to call that instead, but it's not a 1-line change

**Comment by LexManos** [comment]
Haven't looked at it in a while, but isn't there already a hook way before this for allowing the Block itself to replace the entire breaking entity? https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/block/Block.java.patch#L790

**Comment by 61352151511** [comment]
True, you can probably just override that and return true to stop the particles from appearing, and then spawn the particle on your own in that method passing a block state for whatever particle texture you want to use in it. However I still think having an event to do it might be easier as it can also give you control over other mods blocks breaking textures (Can be good or bad)

**Comment by LexManos** [comment]
Except, that function was specifically added because you CANT do this.
Mainly because where you're wanting to hook in does not have all the proper content to make the callback useful. 
And no it wouldn't be an event because there is no good reason to take control over someone elses break particles. If it were being added {which it isn't} it'd be a callback in either the block or the model.
