### ISSUE TITLE
[Feature Request] Loading screen 'did you know?' messages

### ISSUE THREAD

**Issue by MineMaarten** [MinecraftForge/MinecraftForge#1836]
As addition to the loading bars, I was thinking that it might be a neat idea to allow modders to register 'did you know?' messages. I was thinking of this, because there are quite a few things in PneumaticCraft for example which could be considered details, but are still very good to know. I'm sure that's the case for many more mods. And why not display them in the loading screen like many other games do :)?

As it's in the loading stage I assume it's not feasible to do at least until after PreInit (so mods would register the texts in the PreInit), but that would be fine by me.

**Comment by Kubuxu** [comment]
I think that it is very interesting and valuable idea.

**Comment by LexManos** [comment]
I'm weary of this idea, the ability for abuse is overwhelming. 
We'd have to strictly control the length and formatting, only allowing 1 line/~100 characters. Rendering ourselves, etc..

**Comment by Kubuxu** [comment]
I think the API for just registering a limited length string in a custom event would be enough.

**Comment by coolsquid** [comment]
> I'm weary of this idea, the ability for abuse is overwhelming.

Yes, but should Forge limit itself because a feature might get misused? There are extremely many ways to misuse Forge, so you may as well shut down the whole project. If it really bothers you, you could add a config to choose which mods can use the feature.

**Comment by RainWarrior** [comment]
At some point we should stop adding features to the loading screen - it should load very fast itself, or there will be no point having it.

**Comment by luacs1998** [comment]
Agreed. Large modsets are seeing loading times upwards of 10min - a loading screen helps, but doesn't solve the root cause.

**Comment by LexManos** [comment]
Ya, i'm gunna go with no on this. 1) It  can be misused 2) It's a vanity thing 3) Because 2 1 will happen a lot.
