### ISSUE TITLE
Fluid disconnect NPE

### ISSUE THREAD

**Issue by sfPlayer1** [MinecraftForge/MinecraftForge#1837]
http://pastebin.com/RGbhs7Ew

This happened after getting disconnected due to missing item IDs, causing some timeout screen to show instead of the missing id screen.

**Comment by portablejim** [comment]
Please post the full crashlog.

**Comment by sfPlayer1** [comment]
It is no crash..

**Comment by portablejim** [comment]
Ok. Well maybe a bit more info (like mods installed and forge version).

**Comment by liach** [comment]
Just a fluid id mismatch treated as "timeout" right?

**Comment by LexManos** [comment]
Poking @KingLemming and @cpw  as they are the ones who are working on the fluid stuff.

**Comment by cpw** [comment]
I understand the problem, an error occurred during handshake, but it still gets the fluid ids from the server and fails. It should really just bail without further error..

**Comment by LexManos** [comment]
The fluid, registries and ID systems have been reworked quite a bit since this issue was placed, if this is still an issue in the current version create a new issue with more details.
