### ISSUE TITLE
[Suggestion] Gui Api for containers etc.

### ISSUE THREAD

**Issue by CreativeMD** [MinecraftForge/MinecraftForge#1838]
Hello,
just wanted to start a discussion about a gui api for containers etc.
I did something like this for my mod RandomAdditions. It's not the best one, but it's still very useful.
I think it would be very very cool to have something like this integrated into Forge.
So if it's appreciated, i could do something like this and make a pull request.
Are there any issue which could come up?

Reference (still WIP):
https://github.com/CreativeMD/CreativeCore/tree/master/src/main/java/com/creativemd/creativecore/common/gui
https://github.com/CreativeMD/CreativeCore/tree/master/src/main/java/com/creativemd/creativecore/common/container

**Comment by LexManos** [comment]
You're gunna need to work on your pitch a bit more.
You code shows me nothing besides vanilla functionality.
This isn't well thought out or explained.

**Comment by CreativeMD** [comment]
Yes, it's just a preview and i all the controls are still not copied to my core mod :(. Should have done that before.
