### ISSUE TITLE
ModelLoader suppresses error messages for some causes of missing models

### ISSUE THREAD

**Issue by TheGreyGhost** [MinecraftForge/MinecraftForge#1839]
A common coder mistake in the blockstates file is forgetting the modid in the resource location
for example
"facing=north": { "model": "block_MicrobeExtractorIdle" },
instead of 
"facing=north": { "model": "biowarfare:block_MicrobeExtractorIdle" },

The model loader incorrectly suppresses the error message when this occurs - it appears to be an unintended side effect.

ModelLoader::VanillaLoader::
public IModel loadModel(ResourceLocation modelLocation)  {
   try  {
    return loader.new VanillaModelWrapper(modelLocation, loader.loadModel(modelLocation));
  }  catch(IOException e) {
   if (loader.isLoading) {
                    // holding error until onPostBakeEvent  **** error message suppressed *****
  } else 
    FMLLog.log(Level.ERROR, e, "Exception loading model %s with vanilla loader, skipping", modelLocation);
  return loader.getMissingModel();
   }
}

**Comment by chibill** [comment]
Anyone doing any thing about this?

**Comment by RainWarrior** [comment]
This error is displayed correctly now.
