### ISSUE TITLE
Client seems to attempt to connect multiple times at once occasionally.

### ISSUE THREAD

**Issue by clienthax** [MinecraftForge/MinecraftForge#1840]
Client log
http://pastebin.ubuntu.com/10946521/

Server log
http://pastebin.ubuntu.com/10946523/

**Comment by ryantheleach** [comment]
Might be a client side bug, I've successfully managed to connect to 2 servers at once from 1 client using vanilla.

I was receiving chat packets from one server, but appeared to be in the world of another, I could explore and load chunks in the world. Can't remember if people saw me moving in the chat world.

**Comment by LexManos** [comment]
Thats not helpful, can you reproduce it in any way?

**Comment by clienthax** [comment]
I havn't found an exact way to reproduce it as it only happens occasionally , but it seems to occur only in offline mode.

**Comment by LexManos** [comment]
See what you can do about figuring out how to reproduce.

**Comment by ryantheleach** [comment]
It was a while ago, but I think it happened when I mis-clicked and connected to a server I didn't want to be on. Disconnected from the server while it was still connecting, then immediately connected to the correct server.

**Comment by LexManos** [comment]
Never able to reproduce, may be a misunderstanding of how the pinging system works and you're thinking that a ping is a full connect.
Who knows. Doesn't seem to be a Forge issue.
