### ISSUE TITLE
Hooks for filling glass bottles

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#1841]
(It should really just use the fluid container registry but meh forge likes doing things the hard way)

I want a hook to fill glass bottles, so that rightclicking my Cola fluid gives you Cola bottles, not water bottles. It doesn't matter if it gets added for 1.8 as long as it's available.

**Comment by diesieben07** [comment]
`PlayerInteractEvent`

**Comment by SoniEx2** [comment]
@diesieben07 Why's there a hook for filling buckets?

**Comment by LexManos** [comment]
Because it's old and created before Fluids existed. The proper mechanic would be to try and look into the Fluid registry to see if the container item is found.

**Comment by SoniEx2** [comment]
Shall I open an issue about "Make item use check for fluid container item"?
