### ISSUE TITLE
[Suggestion] Custom Effect System (seperate from PotionEffects)

### ISSUE THREAD

**Issue by Spartan322** [MinecraftForge/MinecraftForge#1842]
My suggestion is that we add a custom effect system which can be displayed on the HUD like regular effects. As the current ways to achieve this require reflection or a complete rewrite of the system, and adding a GUI, and I rather see a direct implementation into forge if no one minds. 

Now if its ok I could write it up and do a PR.
Here is what the CustomEffect class will look like below the imports (Some of it is obviously a copy of PotionEffects to facilitate easier integration)

``` java
public abstract class CustomEffect {
   private final int id;
   private int duration;
   private int amplifier;
   private boolean isAmbient;
   private boolean isEffectMaxDuration;
   private boolean showParticles;
   private List<ItemStack> curativeItems = new ArrayList<ItemStack>();

   public CustomEffect (int id, int duration, int amplifier, boolean ambient, boolean showParticles)
   {
      this.id = id;
      this.duration = duration;
      this.amplifier = amplifier;
      this.isAmbient = ambient;
      this.showParticles = showParticles;
      curativeItems.add(new ItemStack(Items.milk_bucket));
   }

  public final int getId()
  {
      return this.id;
  }

   public final void setDuration(int duration)
   {
      this.duration = duration;
   }

   public final int getDuration()
   {
      return this.duration
   }

   public final boolean getIsAmbient()
   {
      return this.isAmbient;
   }

   public final boolean getIsShowParticles()
   {
      return this.showParticles;
   }

   public void setPotionDurationMax(boolean maxDuration)
    {
        this.isPotionDurationMax = maxDuration;
    }

    public boolean getIsPotionDurationMax()
    {
        return this.isPotionDurationMax;
    }

   public final int deincrementDuration()
   {
      return --this.duration;
   }

   public abstract void onStartEffect(EntityLivingBase entityLiving);

   public abstract boolean onUpdateEffect(EntityLivingBase entityLiving);

   public abstract void onEndEffect(EntityLivingBase entityLiving);

   public abstract CustomEffect onCombineEffect(CustomEffect customEffect);

   public abstract int getTicksBetweenUpdates(EntityLivingBase entityLiving); //For efficency and customization of effect

   public abstract ResourceLocation getIcon();
}
```

Now, first, I only suggest this way, I'd be looking forward to finding a better way to do this. 

Second, I don't know how to handle the NBT data, the only way I could think of was to create HashMap registry using the Mod Id string and then create a List of classes that extends CustomEffect(the id would represent it's position in the list) and load it from there but that is slow to use for every NBTTag (as the only way to read that would be reflection), so does anyone want to suggest a better way.

(also if you rather me put that CustomEffect class thing in a gist instead, please tell me)

**Comment by diesieben07** [comment]
Not really sure what the point is, you can already achieve custom non-potion effects using existing forge hooks (`LivingUpdateEvent`, `IExtendedEntityProperties` and `RenderGameOverlayEvent`).

**Comment by Spartan322** [comment]
I just feel that there should be a simpler way of adding an effect similar to potion effect then running around trying to copy system which is already mostly in place, and I'm not sure `RenderGameOverlayEvent` allows you to modify the position of the effects in the inventory. (please correct me on that) Also, you will have a diffcult time controling how many ticks to let pass in LivingUpdateEvent. I am only suggesting to provide simplicity.
