### ISSUE TITLE
Piston hooks

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#1844]
I wanna know when my item is being pushed against a wall so I can use it as a crafting step. We already have explosion hooks, which @MineMaarten uses for compressed iron crafting.

**Comment by LexManos** [comment]
PR

**Comment by diesieben07** [comment]
You can make a custom `EntityItem` and detect it that way.

**Comment by laz2727** [comment]
You can check for block updates i think.

2015-05-02 15:02 GMT+06:00 diesieben07 <notifications@github.com>:

**Comment by SoniEx2** [comment]
@diesieben07 How? And wouldn't it conflict with water? (and if I check for pistons that wouldn't be quite mod-friendly...)
