### ISSUE TITLE
Build Not Working Properly [CLOSED]

### ISSUE THREAD

**Issue by realmaster42** [MinecraftForge/MinecraftForge#1845]
I acidentally ruinned my code some days ago and built it (again, aciddent).
But now,  i fixed it and it's not working.

1. i need to know how to get log of builds or else i cant even see how to fix
2. Are arrays disallowed inside classes? like, IBlockState[] and int[]?

**Comment by diesieben07** [comment]
1. By "build" you mean `gradlew build`? Just that alone should give you a reasonable error message.
2. Not sure what you mean, but yes, you can make an array of `IBlockState` with `IBlockState[]`.

**Comment by realmaster42** [comment]
Build i mean is 'gradlew build'

**Comment by LexManos** [comment]
Logs

**Comment by realmaster42** [comment]
pls i rlly need logs

**Comment by LexManos** [comment]
I was asking you for them -.-

**Comment by realmaster42** [comment]
Well there are no logs, that's the problem.

**Comment by diesieben07** [comment]
Typing `gradlew build` into the console will generate some sort of output. Post that.

**Comment by LexManos** [comment]
Logs are also stored in the build folder.

**Comment by realmaster42** [comment]
You are not understanding.
When it reaches 'compile', it gives an error and some 25ms later it auto-closes & no logs are stored.

**Comment by diesieben07** [comment]
The cmd won't auto-close when gradle errors, unless the cmd itself crashes, which is highly unlikely.

**Comment by LexManos** [comment]
Yes
That error
That you see on your screen
WE NEED IT!
How to make this more clear.
And it should make a gradle.log file in your .gradle folder.
Or at the worst case you can run the command manually in the console and just copy it out.
Seriously this should not need to be explained if you're a modder... This isn't programming 101.

**Comment by realmaster42** [comment]
k thx

****************************
 Powered By MCP:             
 http://mcp.ocean-labs.de/   
 Searge, ProfMobius, Fesh0r, 
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : snapshot_20141130
****************************
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava UP-TO-DATE
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Cannot find System Java Compiler. Ensure that you have installed a JDK (not just a JRE) and configured your JAVA_HOME system variable to point to the according directory.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.633 secs

**Comment by McJty** [comment]
Well the error you get explains what you have to do.

**Comment by realmaster42** [comment]
It was working before and everything's correct.
I'm pretty sure this is Forge's problem.

**Comment by chibill** [comment]
Well considering its a task that is in Gradle not forge its not forge's problem....

**Comment by realmaster42** [comment]
Updated to java 8 jdk and works now.
Sorry for the confusion.

**Comment by logangorence** [comment]
Can you properly close this issue? There's a button beside the "Comment" button, which says "Close issue".

**Comment by Bogdan-G** [comment]
"Updated to java 8 jdk and works now."
?? Gradle dependency in Java 8, why?

**Comment by liach** [comment]
Nope, just his `JAVA_HOME` was undefined. Reinstall Java fixes this.

**Comment by Bogdan-G** [comment]
Must just had to go into the environment variable and enter `JAVA_HOME`
