### ISSUE TITLE
Enum-based configuration system

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#1846]
I've been toying with an idea I had of an enum-based config system. It would let you do this:

``` java
public class EnumLimitSettings implements Configuration {
    TICK_DELAY("Tick delay", "How many ticks to wait before ticking again", EnumValueType.INTEGER, 2),
    TICK_DUTY("Tick duty", "How many ticks to tick before waiting", EnumValueType.INTEGER, 2),
    TANK_SIZE("Tank size", "How big Cola tanks should be, in mB", EnumValueType.INTEGER, 8000);
    // etc...

    // I really wish Java had abstract enums so that the following boilerplate wouldn't be needed :(
    private final EnumValueType type;
    private final String hrname, comment;
    private final Object defaultValue;
    EnumLimitSettings(String hrname, EnumValueType type, String comment, Object defaultValue) {
        this.hrname = hrname;
        this.type = type;
        this.comment = comment;
        this.defaultValue = defaultValue;
    }
    EnumLimitSettings(String hrname,EnumValueType type,Object defaultValue){this(hrname,type,null,defaultValue);}
    EnumLimitSettings(String hrname,EnumValueType type){this(hrname,type,null);}
    public EnumValueType getType(){return type;}
    public String getHumanReadableName(){return hrname;}
    public Object getDefaultValue(){return defaultValue;}
    public String getComment(){return comment;}
}
```

Then to use it:

``` java
ConfigurationManager cm = new ConfigurationManager(EnumLimitSettings.class, myConfigFile);
cm.load();
tankSize = cm.getInt(EnumLimitSettings.TANK_SIZE);
tickDutyCycle = ((float) cm.getInt(EnumLimitSettings.TICK_DUTY)) / ((float) cm.getInt(EnumLimitSettings.TICK_DUTY) + cm.getInt(EnumLimitSettings.TICK.DELAY))
cm.save();
```

What do you say?

**Comment by Victorious3** [comment]
Is there any specific reason why this has to be an enum? Same thing can be done with an abstract class. You lose the ability to use the enum set, but as you pointed out already, no abstract enums.

**Comment by SoniEx2** [comment]
@Victorious3 It all started when I thought about using enums for config files. So it had to be enums, because that's the whole point.

But other than that, no, there is no reason for it to be an enum.

**Comment by Lunatrius** [comment]
How is this different from the current implementation, other that the fact that it uses enums and might not support more complex (read as nested etc) configs?

**Comment by SoniEx2** [comment]
It lets you very easily make multiple instances of the same config, kinda like gson.

**Comment by LexManos** [comment]
No, I'm wanting to re-do the configuration system to something less asinine. But it's waiting on 
1) Bspkrs and Blood to get back to me about changing around the config guis to work with Configurate
2) Me to write a Commenting Gson writer.
The thought is to have something along these lines:
```java
public class ConfigGlobal {
  @Comment("Comment")
  @Range(min = 0, max = 100)
  public int value = 10;
}
public class ConfigUniverse {
  @Comment("this is used for every 'universe', Meaning 'Minecraft Server' instance.")
  public int value = 10;
}
public class ConfigWorld {
  @Comment("And this one is for each World itself")
  public String random = "";
}

ConfigManager.register(mod, ConfigGlobal.class, ConfigUniverse.class, ConfigWorld.class)
@EventHandler // This one is fired only once, probably between construction and pre-init havent decided yet.
public void onGlobalConfigLoad(ConfigEvent.Global<ConfigGlobal> e){
  ConfigGlobal cfg = e.getConfig();
}
@EventHandler // This one would be right before we start loading all of the worlds for the server.
public void onUniverseConfigLoad(ConfigEvent.Universe<ConfigUniverse> e){
  ConfigUniverse cfg = e.getConfig();
  MinecraftServer server = e.getServer();
}
@EventHandler // This one would be right after World's constructor, AFTER World.Load
public void onWorldConfigLoad(ConfigEvent.World<ConfigWorld> e) {
  ConfigWorld cfg = e.getConfig();
  World world = e.getWorld();
}
```
As for saving, the ConfigManager would manage all of the instances returned in the events and would take care of it's own 'has this changed? if so save the file"

**Comment by SoniEx2** [comment]
> 2) Abstract away ANY file interaction from the modder

... Why? That's precisely what I DON'T want. (I don't like things that abstract file I/O like that. I'd much rather have something that takes InputStream/OutputStream than File, even. Next up you'll be banning file I/O in mods and I'll be unable to load and save files outside a small sandbox, making it impossible to shove standalone programs into Minecraft ([e.g.](https://github.com/eNByeX/NBX-Mod)))

**Comment by portablejim** [comment]
I think that the system Lex proposes is ok, so long as it is seen as only a convenience thing, the same way that the config gui is (i.e. You can write a custom one yourself).

**Comment by cpw** [comment]
Lex, my suggestion is that we adopt typesafe. Perhaps with a couple of tweaks. Its a well defined standard, and we already include the lib for it. There's little we'd need to do to wrap it in something akin to existing forge code..

**Comment by LexManos** [comment]
Switching to Configurate that Sponge uses allows for multiple backends such as GSON, HOCON, and Typesafe.
Its jsut a matter of designing a abstraction over it to make us able to do whatever we want. The point is the backend doesnt matter to the modders. Just this front end.

**Comment by portablejim** [comment]
Lex, if I get what you are saying, you are saying that this configuration abstraction only applies to mods using the 'autobuilt' configuration screen?

**Comment by cpw** [comment]
Jim, we can't easily prevent modders from hacking their own system. However, having a standard, useful system in forge, especially one integrated with the GUI stuff, is highly desirable. Hopefully it will be compelling enough to gain widespread adoption.. The existing config stuff is an example of this, but the files follow no standard but our own, and the code supporting it is frankly arse. Adopting a standard back end will mean we can remove the arse.

**Comment by cpw** [comment]
Lex, configurate sounds like an ideal target..

**Comment by SoniEx2** [comment]
Can I still be allowed to save configs to whatever path I want? I like subdirs and stuff...

**Comment by portablejim** [comment]
Cpw, I agree that for most mods (including some of mine) a standard is desirable and useful. However,  there are some mods (e.g. Veinminer) where a custom configuration GUI and (to some extent) configuration parsing is superior to the standard.

**Comment by cpw** [comment]
Jim, I have no idea why that would be the case, but as I said, there's little we can do to stop you..

**Comment by progwml6** [comment]
@cpw using configurate-hocon is an option that i personally prefer its MUCH easier to work with than typesafe directly

**Comment by LexManos** [comment]
Nothing we can do can prevent modders from doing custom shit.
However, No Soni, it will be HIGHLY DISCOURAGED to touch config folders/files in your mod. The system itself will take care of it.
Providing a standard set/layout for configs is the desireable effect. Most likely the case will be that we serialize all 3 default configs into ./config/{modid}.whatever with the option of the modder to opt for ./config/{modid}/{configtype}.whatever which is more ideal for LARGE configs. 
As for the world/universe option it will follow the same setup but for the world/universe folders. Copying over the default values from the main config folder. This will be done only if the file are changed to prevent file spam, the specifics will be worked out after the technical stuff is done.

**Comment by SoniEx2** [comment]
So if you had submods you'd have ./config/mod|core/<stuff> ./config/mod|machines/<stuff> etc? How would you deal with that, if not manually setting your mod's config dir? Also what about getting other mods' configs?

**Comment by Lunatrius** [comment]
That is already possible. However, you should *NOT* be touching other mod configs. You're just asking for trouble by doing so.

**Comment by cpw** [comment]
When we have the projects merged, FML will be able to directly reference the forge config code, and the preinit event will allow you to directly request a particular kind of config setup. I would like to support two types: compact and exploded. Compact would be a single file, exploded would be a directory, probably with one file per category.. As we have repeatedly said, we can't prevent you from doing your own thing, but hopefully we can make the standard system a bit more compelling than it is today..

Note: none of the above is set in stone, and there is no commitment to do any of it..

**Comment by portablejim** [comment]
I want to learn and so have put my questions on the forum http://www.minecraftforge.net/forum/index.php/topic,30045.0.html
