### ISSUE TITLE
White screen or crashing

### ISSUE THREAD

**Issue by thegamehunter09** [MinecraftForge/MinecraftForge#1849]
Hey I am currently trying to play Agrain Skies 2 but with the recent update the forge version 1387 keeps on giving a white screen. And I when I update date to the one of the newer versions it tryies to load but simply stops working and telling me that the java has stopped working. Also other times with the NEWEST forge it just crashes.Also something about a texture problem and resource loader.

**Comment by Spartan322** [comment]
This is an issue that should be posted to the mod issue tracker (or just messaged to the mod developer or the forum thread if he doesn't give one), if this problem is bug related to Forge, then the mod developer can post about it. This seems like a mod related issue.
