### ISSUE TITLE
New Loading Bars

### ISSUE THREAD

**Issue by Pro457** [MinecraftForge/MinecraftForge#1850]
How do you disable the newly added mod loading bars that display the progress of mods being injected into the code as you wait for the main menu to appear? This is a big issue.

**Comment by luacs1998** [comment]
Are you encountering problems with it? You should ask in MinecraftForge/FML#644

**Comment by LexManos** [comment]
By editing the config file, or providing the environment variable. Either way luacs is right keep this within the linked issue.
