### ISSUE TITLE
Crash on Start-Up....

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [MinecraftForge/MinecraftForge#1851]
I don't think this Forge version likes having to deal with 100+ mods...

http://hastebin.com/dedocayuvo.coffee

**Comment by chibill** [comment]
I have loaded 160 mods with it before (yesterday) it is one of you mods trying to do rendering stuff at the wrong time.

**Comment by Unrepentant-Atheist** [comment]
Hmm...fair point. Any idea where to start looking? I don't fancy removing one mod, starting, another mod, starting, etc..

**Comment by chibill** [comment]
Try removing fastcraft.

**Comment by Unrepentant-Atheist** [comment]
First thing I did. No dice.

**Comment by LexManos** [comment]
Remove CrayFishe's mod, Also keep these issues in MinecraftForge/FML#644
