### ISSUE TITLE
[Forge 10.13.3.1373] Minecraft Stops Responding But Still Works In Background

### ISSUE THREAD

**Issue by Zundrel** [MinecraftForge/MinecraftForge#1855]
Hello. This is has been happening from 1291 and above and it's been bothering me. Basically if I lose focus on Minecraft for like 1 or 2 minutes when I go back it isn't responding but stuff is still working, players are moving, mobs are moving, etc. Currently I'm using 10.13.3.1373-1.7.10 but I can confirm it still happens with 1387 as well. I'm going to try and use 1401 later tonight, so I'm not sure if the problem is still relevant there.

EDIT: Problem is still relevant in 1401. Just tested a few minutes ago.

EDIT 2: Here's my Minecraft log http://pastebin.com/v2wpLWfy

**Comment by AfterWind** [comment]
I had this issue before. I solved it by reinstalling the OS, still not 100% sure what it was, but it's not related to Minecraft. Something to do with the graphics driver afaik.

**Comment by LexManos** [comment]
The 'Not Responding' thing is entirely on the OS/lwjgl side. It is the one polling for and responding to windows updates. You may want to try removing mods you have installed to see if its still happening, there may be mods that are locking the main thread which is supposed to be handling these input requests.

**Comment by Bogdan-G** [comment]
In start? Normal behavior for MC.
In game? World lookup leak, SSP-server is doing likes.

**Comment by williewillus** [comment]
Is this still relevant occurring?

**Comment by Zundrel** [comment]
A Forge build ages ago fixed the issue, so no, it isn't relevant anymore.
