### ISSUE TITLE
ItemTossEvent does not have public EntityItem instance(but it exists in the constructor)

### ISSUE THREAD

**Issue by anti344** [MinecraftForge/MinecraftForge#1860]
Title says it all.

**Comment by diesieben07** [comment]
[Ahem.](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/event/entity/item/ItemEvent.java#L17)

**Comment by anti344** [comment]
Oh, i'm stupid as heck =/

**Comment by anti344** [comment]
Also my IDE for some reason wouldn't show it up. But everything compiles, thanks
