### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by lightning02** [MinecraftForge/MinecraftForge#1861]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 09/05/15 22.12
Description: Exception in server tick loop

cpw.mods.fml.common.MissingModsException
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:244)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:170)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 454759576 bytes (433 MB) / 866123776 bytes (826 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 2 total; -XX:PermSize=2G -XX:MaxPermSize=3G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by diesieben07** [comment]
This is not the correct place, please use the forums for reports like this.

**Comment by chibill** [comment]
Also your missing a mod that another mod needs. Your best bet is to try it on Single Player to solve this stuff then make your server.

**Comment by Bogdan-G** [comment]
Fully log? Strangely, mhm, bug in cauldron?

**Comment by lightning02** [comment]
it may be.. idk I'm a bit noob sometime don't be mean  anyone have a link with a more recent calduron to try out?

**Comment by Prototik** [comment]
@lightning02 [You own me 100$](https://prok.pw/cauldron-1.7.10-2.1403.1.49-installer.jar)

**Comment by chibill** [comment]
Its not a bug... You are missing a dependency of another mod.

**Comment by Bogdan-G** [comment]
@chibill, in theory - it should be written in crash-log.

**Comment by lightning02** [comment]
@Prototik Yeah! You really help me :D but where have you find this version? O.o 
I don't find it anywhere!
