### ISSUE TITLE
GameRegistry#registerBlock can't use Primitives

### ISSUE THREAD

**Issue by CrafterKina** [MinecraftForge/MinecraftForge#1862]
I'm Japanese, so I might use strange English.
itemCtorArgs of registerBlock's fourth argument is all covered in Object.
Therefore primitive type boxed in wrapper type.
If the constructor of ItemBlock are using primitive, can't make Instance.

**Comment by diesieben07** [comment]
I fixed this a long time ago [in FML](https://github.com/MinecraftForge/FML/pull/586), but it never got pulled.

**Comment by CrafterKina** [comment]
Maybe not same.
I mean, for example if I'd like to use ItemColored, can't use it.
(Because it needed boolean.)
I reissue in FML.

**Comment by diesieben07** [comment]
Yes it's exactly the same. With my PR you could just do `GameRegistry.registerBlock(myBlock, new ItemColored(myBlock, true), "myBlock")`.

**Comment by CrafterKina** [comment]
I'm sorry. It was a check mistake.
Although It dealt with an instance in vanilla, I wonder why the fml use a class...

**Comment by diesieben07** [comment]
It's a relic from the times where we had IDs. FML used a class to make sure the IDs were all correct.

**Comment by CrafterKina** [comment]
Oh, I see. I hope that your PR get pulled soon.
