### ISSUE TITLE
[1.8] Three fluid issues

### ISSUE THREAD

**Issue by kirderf1** [MinecraftForge/MinecraftForge#1865]
After having resolved fluid rendering for 1.8 (For those who want to know how, the commit is available here:  mraof/Minestuck@2256601c79e59e87002bf6cb94b20d07a88f1f47), I experimented a little with fluids and found three issues.
- `BlockFluidClassic.isSourceBlock()` compares the block and the blockstate without retriving the block from the block state.
- A classic fluid wont vanish as long as one of the nine blocks above (or below for gases) is of the same block. This does not take into account that the two blocks might not be connected if the block isn't directly above.
- The flow direction doesn't seem to be handled correctly with nearby air. (And possibly also with solid blocks.

**Comment by CrafterKina** [comment]
Can put anything to IBlockState.
For example, put world and pos.
After putting (maybe in getExtendedState), use in ISmartBlockModel.

**Comment by RainWarrior** [comment]
> put world and pos
Be careful with that, as getExtendedState can be called from multiple threads.

**Comment by RainWarrior** [comment]
First issue was fixed in 0cf1f0d51c04cb82f6ffb5773fe5c28fa285c942.
