### ISSUE TITLE
Error upon launch, v10.13.3.1403

### ISSUE THREAD

**Issue by xJon** [MinecraftForge/MinecraftForge#1869]
http://pastebin.com/zCS8Ygi7
What does that mean? It says "Crash Report" but actually the game launches, and there's no crash report generated in the dedicated folder, it's just an error that shows up in the client log.

Also, on line 31, I see "Mod Pack"; Can I insert a modpack name somewhere? how?

Thanks!

**Comment by diesieben07** [comment]
It's debug for the new loading screen.

**Comment by xJon** [comment]
Okay, a bit weird how it says "Crash Report" but if it's okay it's okay.
What about my second question?
Thanks.
