### ISSUE TITLE
fluid crash i don't know if it's forge or ee3

### ISSUE THREAD

**Issue by bigfatpanda22** [MinecraftForge/MinecraftForge#1870]
hi i seem to be getting a crash from a lot of fluids in about 2 or 3 mods as they are well made mode like tinkers construct and forestry this was not happening before i updated forge to use EE3 as the forge that comes with infinity did not work with it just to say i have fastcraft if you can help please thanks
here is the crash report 
http://pastebin.com/rusryQC6

**Comment by LexManos** [comment]
Thats a obvious Forestry issue it's trying to create a invalid FluidStack

**Comment by bigfatpanda22** [comment]
ok sorry i took so long to reply i have updated forestry and tinkers construct (i can't believe that i hadn't done that) and it now works i am sorry for wasting your time i spent 4h trying to fix it when all it took was the click of and update arrow
