### ISSUE TITLE
PlayerOpenContainerEvent fires every tick in Multiplayer

### ISSUE THREAD

**Issue by ryantheleach** [MinecraftForge/MinecraftForge#1871]
Continued from: https://github.com/MinecraftForge/MinecraftForge/commit/53659fca065a600470734d81a168fbdde6ec631a#diff-6776c47576382d999d1ad870348efd36R26

This is causing PlayerOpenContainerEvent to fire every tick, EntityPlayer.java has a null check presumably to fix this: https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch#L73 Is there any way to prevent it firing every tick if it's not needed?

**Comment by diesieben07** [comment]
It has always fired every tick. The name is a bit unfitting if anything.

**Comment by Actuarius** [comment]
@diesieben07 closed this issue
