### ISSUE TITLE
modClassLoader.clearNegativeCacheFor doesn't work in FMLModContainer.constructMod 

### ISSUE THREAD

**Issue by bdew** [MinecraftForge/MinecraftForge#1872]
The list that gets passed is using a different format than what the negative cache uses ("a.b.c" vs "a/b/c"). 

Also the passed list doesn't include inner classes while the negative cache does - this is because they don't match the pattern in ITypeDiscoverer (it excludes $).

This leads to the scenario i've described in Chicken-Bones/CodeChickenCore#38

The short version is more or less:

1. Mod A loads before mod B and tries to access it's classes while constructing (either directly or in my case because of a transformer running on it)
2. Mod B classes get listed in the negative lookup cache
3. Mod B is constructed and can't access it's own classes because the classloader thinks they are not found

**Comment by cpw** [comment]
OK, that is interesting because that means somehow it's changed *again*. Because it was originally doing this, and then I changed it because it wasn't working, due to naming.
