### ISSUE TITLE
"The world ... may have leaked" spam and false reports

### ISSUE THREAD

**Issue by sfPlayer1** [MinecraftForge/MinecraftForge#1874]
Said warnings are highly inaccurate, which is no surprise with how they are being generated.

On FC2 there are currently less than 20 old gen GC cycles after 2 hours of uptime, the warning triggers 1000 ticks / 50s after a world unloaded, which isn't even close to the observed ~400s average between GCs. Startup skews the numbers additionally.

Considering the warnings were never useful to someone like me who does a lot of leak investigation and world leaks aren't that common anymore, it'd be only reasonable to remove this fundamentally broken detection entirely. Alternatively the checking interval should be increased to wait at least 30 minutes before assuming a leak.

Btw. the leakedWorlds collection itself leaks.

**Comment by LexManos** [comment]
The warning system is fine as is. 
If you have issues with it then make a PR to make the delay time configurable. However we're not increasing it to 30 mins as that would make it completely useless.
