### ISSUE TITLE
@Mod(modid = "mymod2", version = "1.0", provides = {{"mymod", "1.0"}, <etc>})

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#1875]
The provides tag (or whatever it's called) would return an array of "provided" mods, so for example if mymod2 v1.0 has the same API and organization as mymod v1.0, but a completely different codebase, mymod2 can provide mymod and things that depend on mymod can work with mymod2.

**Comment by liach** [comment]
It's a provided api array, right?

**Comment by SoniEx2** [comment]
No, mods.

**Comment by liach** [comment]
Forge and FML has the same relationship I think. But why does forge need this? We could just have a container for the submod and use the submod without the main mod.

**Comment by SoniEx2** [comment]
Huh? Forge and FML merged so this is where I should put these things.

**Comment by SoniEx2** [comment]
It's not about submods. Look at package management systems ([Arch Linux's pacman](https://wiki.archlinux.org/index.php/PKGBUILD#provides), Debian's dpkg, and so on), most of them support a "provides" tag.

**Comment by laz2727** [comment]
Soni, i don't think you're helping. Nice idea, though.

**Comment by LexManos** [comment]
No, just toss a second mod class in there if youre gunna do this. The usecase is retardedly small and complexity/chance for breaoing is just to high.

**Comment by SoniEx2** [comment]
It's for when you fork Forestry and change the modid and version to "forestry-emc" and "1.0.0" respectively, but still want compatibility with Forestry addons.

**Comment by LexManos** [comment]
then add a stub that says that it is forestry.
or, you could use a properly defined api and go that route.
