### ISSUE TITLE
No warning when setting global entity IDs to a number above 128

### ISSUE THREAD

**Issue by ganymedes01** [MinecraftForge/MinecraftForge#1880]
the method EntityRegistry.registerGlobalEntityID() allows the ID passed to be an int, but internally that ID must be a byte. Instead of warning the user or throwing an exception whenever a ID is set to a number bigger than 128, FML simply casts that value.

This causes issues that are hard to trace back, as in this instance: https://github.com/ganymedes01/Headcrumbs/issues/35#issuecomment-102814808
The user, unknowingly, set the entity ID to 300, which then got cast to a byte and turned into 44. No warnings were thrown despite the ID 44 already being taken. The crash happened in game once the entities of ID 300 tried to spawn.

My suggestion would be to either simply change the ID parameter in EntityRegistry.registerGlobalEntityID() to a byte (which would probably isn't backwards compatible now that I think about it...) or throw an exception and crash the game whenever a value greater than 128 is passed through it avoiding crashed later on.

**Comment by diesieben07** [comment]
This method is legacy code honestly I don't even know why it's not deprecated yet. Don't use global IDs.

**Comment by ganymedes01** [comment]
I wouldn't have used it if I knew the consequences... but no deprecation or warnings anywhere. Switching now would cause existing stuff to disappear, so I can't.

**Comment by diesieben07** [comment]
That's not true. You can register the old mappings as a fallback (`EntityList.stringToClassMapping.put(<oldName>, YourEntity.class)`) and old worlds will load fine. Converting over the spawn eggs will however not be possible.

**Comment by ganymedes01** [comment]
ohhh... didn't know that! That's excellent news lol

But again... a bit of documentation and a warning would be nice. I know lots of other mod authors who are stuck with global entities and don't know about what you just told me.

**Comment by diesieben07** [comment]
I totally agree.

**Comment by ganymedes01** [comment]
Any idea what are the vanilla values for these?

```JAVA
int trackingRange, int updateFrequency, boolean sendsVelocityUpdates) {
```

Because those parameters are the ones that scared me off of using that method... Perhaps if there were a method where those parameters are already filled in, more modders wouldn't just go for the easier global entity method.

**Comment by diesieben07** [comment]
The values for the various vanilla entities are hardcoded in `EntityTracker.addEntityToTracker`.

**Comment by ganymedes01** [comment]
on nice! But it doesn't seem to have every entity... zombies for example aren't there

**Comment by diesieben07** [comment]
Minecraft groups all living entities using the `IAnimals` interface. The name is not very fitting, but oh well.

**Comment by LexManos** [comment]
Actually this reminds me, gonna talk to cpw about deleting these mechanics completely in 1.8.4. Modders should not be doing this, it was done SOLELY for ModLoader compatibility, ModLoader is dead, there for we can kill it. But yes, as for things 'disappearing' not a problem you just need to register your old string name as alias in the stringToClassMapping to the new one as  described above and you're golden.

**Comment by Bogdan-G** [comment]
Not it easier to transfer most types of bytes in int? All the same memory they take clearly more than occupy themselves, creating a lot-lot of empty seats.

**Comment by RainWarrior** [comment]
EntityRegistry.registerGlobalEntityID is deprecated now.
