### ISSUE TITLE
Differentiate between vanilla and forge methods in vanilla classes

### ISSUE THREAD

**Issue by killjoy1221** [MinecraftForge/MinecraftForge#1887]
As a modder who makes a multi-platform mod, ForgeGradle has made it easy for me to have a single codebase for both Forge, LiteLoader, or anything else. Unfortunately because of the way Forge works, it needs to patch the jar during dev time instead of at runtime. Because of this, I often catch myself using seemingly vanilla methods/fields, but when I run without Forge, they suddenly don't exist or are private, so this is a big no-no for me.

I'm not suggesting anything drastic or having anything be changed. What I *am* suggesting is to simply tack a class-level annotation, similar to Guava's `Beta`, onto any method, field, or constructor we add so we know that it will not be there without forge. We could use a name such as `Patched` or `Added`.

Things that have been access transformed should be annotated with another using `javax.lang.model.element.Modifier` or `java.lang.reflect.Modifier` to represent the old visibility. ForgeGradle would of course need to take care of that automatically.

How it would show in source:
```java
// access changed from private final to public.
@AccessChanged({ Modifier.PRIVATE, Modifier.FINAL })
public void String privateField;

// This is added to EntityPlayerMP
@Patched
public String getDisplayNameString() {
    ...
}
```

Would anyone else find this useful? I would start working on this, but there are over 100 classes that have added methods and fields and want to hear opinions first.

**Comment by chibill** [comment]
Why? This could inflate patch sizes.

**Comment by killjoy1221** [comment]
The .patch files, yes, but we can in-line annotations. We can also strip them when the bin patches are created.

**Comment by OvermindDL1** [comment]
If you are not wanting to use the forge API then why not just use
liteloaders?  Or better yet, why worry about liteloader at all considering
its lack of usefulness and necessity?

**Comment by killjoy1221** [comment]
I think you misunderstand. I do want to use the API where I can, but not where I shouldn't be. Places that I shouldn't be are things that can be run without forge (core). I do the same with LiteLoader.

My preferred solution is to use Forge as a library instead of patching, but that would require the change to Mixins, and I don't know if or when that will happen.

**Comment by LexManos** [comment]
No.
FG is first and foremost for developing with Forge.
Adding things like this just bloat the code.
Yes it would be nice, and there are some areas where we try to change things so that its clear that it's a Forge added method.
However, things like access transformers, no, you're on your own on that.
Basically if you make something that is supposed to work outside the platform that Forge provides its on you to test it in that environment.
