### ISSUE TITLE
[Forge-10.13.3.1408] If installed Optifine, disappears loading bar

### ISSUE THREAD

**Issue by mrAppleXZ** [MinecraftForge/MinecraftForge#1889]
If installed Optifine, disappears loading bar.

**Comment by halvors** [comment]
I think that this is intentional to avoid crash.

**Comment by diesieben07** [comment]
It's up to optifine to re-enable it.

**Comment by Bogdan-G** [comment]
Look -> https://github.com/MinecraftForge/FML/commit/2ed00c4da0ee76eb15e28eb8ee2c07a3096155c2

**Comment by diesieben07** [comment]
Look: https://github.com/MinecraftForge/FML/commit/b2650a0bdb7d69010a55de518e76591a6c417e87
