### ISSUE TITLE
gradle setupDecompWorkspace error

### ISSUE THREAD

**Issue by Kosti1** [MinecraftForge/MinecraftForge#1890]
****************************
 Powered By MCP:             
 http://mcp.ocean-labs.de/   
 Searge, ProfMobius, Fesh0r, 
 R4wk, ZeuX, IngisKahn, bspkrs
 MCP Data version : 9.10
****************************

FAILURE: Build failed with an exception.

* What went wrong:
Task 'setupDecompWorkspace' not found in root project 'forge'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with                                               --info                                                                           or                                                                             --debug                                                                          option to get more log output.

BUILD FAILED

Total time: 4.222 secs

Gradle Version:

------------------------------------------------------------
Gradle 2.4
------------------------------------------------------------

Build time:   2015-05-05 08:09:24 UTC
Build number: none
Revision:     5c9c3bc20ca1c281ac7972643f1e2d190f2c943c

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.4 compiled on April 29 2014
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Linux 3.13.0-53-generic i386

**Comment by Parker8283** [comment]
`setupForge`

**Comment by Kosti1** [comment]
thanks @Parker8283
