### ISSUE TITLE
[1.8] IBlockAccess#getHeight no longer available?

### ISSUE THREAD

**Issue by fnuecke** [MinecraftForge/MinecraftForge#1896]
In 1.7.10 there was a (client only) `getHeight` accessor in `IBlockAccess`, which is no longer available in 1.8. From what I can tell there is no technical reason for this (it could still just in its implementation forward to `provider.getheight()`, as before).

Is there a reason this is missing, or was it an oversight?

**Comment by Kubuxu** [comment]
Now it is in ` World.getHeight`/`World. func_72800_K`, probably as usual there is no reason for that change.

**Comment by fnuecke** [comment]
But some methods only get an `IBlockAccess`. Do I really have to do an instanceof check and fall back to 256 if it's not a world? That seems... suboptimal.

**Comment by Kubuxu** [comment]
I know. Mojang love breaking changes.
