### ISSUE TITLE
1.7.10-10.13.3.1408 opening port 3389 (RDP) - Windows Remote Access

### ISSUE THREAD

**Issue by Slind14** [MinecraftForge/MinecraftForge#1901]
Hey,

why is forge opening port 3389 for rdp? Download from the official site: files.minecraftforge.net
http://i.imgur.com/nacikmo.png
http://i.imgur.com/xaFMCL0.png

**Comment by mikebald** [comment]
I'm running the same version and I'm unable to duplicate what you're experiencing. It's only opening the standard game port on my box.
http://imgur.com/kcikIQj

**Comment by Slind14** [comment]
yeah, just deployed a aws box to make a quick test, I couldn't reproduce it. I'll dig deeper and close. In case I find out more, I'll reopen.
