### ISSUE TITLE
[FML] [1.7.10] [1.8] Exceptions in coremods initialization don't cause a crash or sane logs

### ISSUE THREAD

**Issue by vlad20012** [MinecraftForge/MinecraftForge#1902]
By default logic `com.google.common.eventbus.EventBus` just log message (without stacktrace) to default `java.util.logging.Logger` while catching exception in event post method. Just try to add line `throw new RuntimeException();` at the end of `ForgeModContainer.preInit()` or any other coremod or event handler. You will see:
```
may 30, 2015 2:32:50 AM com.google.common.eventbus.EventBus$LoggingSubscriberExceptionHandler handleException
SEVERE: Could not dispatch event: Forge to public void net.minecraftforge.common.ForgeModContainer.preInit(cpw.mods.fml.common.event.FMLPreInitializationEvent)
```
Exception in coremod initialization should lead to server/client crash and nothing else. `com.google.common.eventbus.EventBus` accepts as constructor parameter `SubscriberExceptionHandler`, where you can implement custom exception handling, but all exceptions in `SubscriberExceptionHandler` is catchind by EventBus too, so you can't propagate exception with it. So you have to use some flags or ASM, or I don't know.

I tested this on 1.7.10, on 1.8 I just browsed source and found `new EventBus(mod.getModId())`...

**Comment by LexManos** [comment]
Been wanting to switch from google's event bus to our own to deal with exceptions.
However, Coremods should be in charge of their own exception. It's their responsibility if they are a coremod.

**Comment by vlad20012** [comment]
Currently it's a breaking change. Maybe better to install (temporal =D) BS hook into log handler? In `SubscriberExceptionHandler` we propagating exception, then in some other place:
```java
private static org.apache.logging.log4j.Logger log = LogManager.getLogger();
	
public static void installEventBusCrashingHook()
{
	java.util.logging.Logger buslog = java.util.logging.Logger.getLogger(EventBus.class.getName());
	buslog.setUseParentHandlers(false);
	buslog.addHandler(new java.util.logging.Handler()
	{
		@Override
		public void publish(LogRecord rec)
		{
			log.error(rec.getMessage());
			if(rec.getLevel() == java.util.logging.Level.SEVERE && rec.getThrown() != null)
				Throwables.propagate(rec.getThrown());
		}
		...
```

**Comment by cpw** [comment]
The only mods that have a problem with this are coremods. Hacking guava is not an option (its loaded outside the launch class loader) and that ridiculous log hook- yeah that's REALLY gonna work well /sarcasm. Coremods are advanced usage, if the author of a coremod doesn't understand exception handling, they really ought to go learn the fundamentals of Java first..

**Comment by diesieben07** [comment]
How is passing an argument to the constructor [here](https://github.com/MinecraftForge/MinecraftForge/blob/master/fml/src/main/java/net/minecraftforge/fml/common/LoadController.java#L95) "hacking"?

**Comment by vlad20012** [comment]
[https://github.com/MinecraftForge/MinecraftForge/blob/master/fml/src/main/java/net/minecraftforge/fml/common/LoadController.java#L95](LoadController.buildModList:95)
```java
EventBus bus = new EventBus(new SubscriberExceptionHandler()
{
	@Override
    public void handleException(Throwable t, SubscriberExceptionContext context)
	{
		errors.put(mod.getModId(), t);
	}
});
```
