### ISSUE TITLE
Forge Mod Loader has found a problem with your minecraft installation

### ISSUE THREAD

**Issue by mhn3a** [MinecraftForge/MinecraftForge#1904]
"Forge Mod Loader has found a problem with your minecraft installation
The mods and versions listed below could not be found
CodeChickenCore : Minimum version required is 1.0.4
The file 'ForgeModLoader-client-0.log' contains more information"

Here is the log: https://pastee.org/3aqmz

Can someone help me?

**Comment by ThePsionic** [comment]
The answer is literally right there, update your version of CodeChickenCore.

**Comment by diesieben07** [comment]
> The mod NotEnoughItems (Not Enough Items) requires mod versions [CodeChickenCore@[1.0.4,)] to be available

And please use the forum for problems like this.
