### ISSUE TITLE
[Suggestion]Multi threaded loading

### ISSUE THREAD

**Issue by laci200270** [MinecraftForge/MinecraftForge#1905]
It will be great if mods loading in multi thread(it might be faster),because lot of modpacks take ~15 minutes to load(If I can can figure out how to do this I will make a PR)

**Comment by diesieben07** [comment]
That is sadly not possible. Mods (and much more importantly, vanilla Minecraft) rely on things being synchronous and stuff will break horribly if you just make things run in parallel.

**Comment by OvermindDL1** [comment]
Mods that take a long time to do something can already do it multithreaded if they are coded to do so (safely), this is not something that forge can do as Java does not have the safety designs to warrant that arbitrarily, the mods themselves have to be designed for it.  Check your logs to see which mods take the longest to process at the various stages and speak to the mod authors to get them to fix that.
