### ISSUE TITLE
TileEntity ID is easy to duplicate.

### ISSUE THREAD

**Issue by CrafterKina** [MinecraftForge/MinecraftForge#1906]
Automatically prefix is attached to the registration of the block and the item.
TileEntity do not do it.
Therefore ID is very easy to duplicate.

**Comment by Speiger** [comment]
simply include the package of the TileEntity file to the Name like: "speiger.src.tinymodularthings.TinyChest" then it can be not dublicated by accident.

**Comment by dmillerw** [comment]
Just... do it yourself?
Granted, it's odd that it's not done by default, but an easy fix

**Comment by CrafterKina** [comment]
It is easy to do it myself, but it is a trap that we easy to get caught.
Furthermore, IDs are difficult to change that it had attached once.
Don't need to solve with Forge?

**Comment by Speiger** [comment]
Why not copy the package into the registration...?

**Comment by Speiger** [comment]
Like this: "net.minecraft.tileEntity.TileEntityChest" instead of "Chest"

**Comment by jk-5** [comment]
Because it is not removed: http://jk-5.nl/screenshots/2015-06-01_13-40-48.png

But yes, just adding your modid or package to the tileentity id should suffice

**Comment by CrafterKina** [comment]
Should I change this issue into PR?
@jk-5 Sorry I can't see your image.

**Comment by jk-5** [comment]
Oops, unmounted the wrong hd

As i said, it is easy enough to add the modid or package to the tileentity id by hand

**Comment by CrafterKina** [comment]
To fix is easy, but to notice is difficult.
At the very least, it can not well-known?

**Comment by heldplayer** [comment]
You're supposed to notice yourself. You're not supposed to copy-paste code like that.

This is not an issue with Forge.

**Comment by CrafterKina** [comment]
This may not be forge's issue.
But not should not to be doing.

**Comment by Kubuxu** [comment]
If general decision is not to fix it, a JavaDoc about this problem should be added.

**Comment by CrafterKina** [comment]
Which is better selection?
I think it is better to attach prefixes automatically.

**Comment by Victorious3** [comment]
@CrafterKina And break everything that already exists.

**Comment by CrafterKina** [comment]
@Victorious3 I think that can take measures to it.

**Comment by Bogdan-G** [comment]
The duplication of ID? When you create a list of frequently come across attempts to replace items or does not work check employment.

**Comment by diesieben07** [comment]
The problem is that you can't "just" fix it. It would break all TileEntities out there.

**Comment by cpw** [comment]
This behaviour has existed since we started modding Minecraft.. Adding automatic prefixes would break every signs save since the dawn of time. In summary, if you're obtuse enough not to understand that the name has to be unique and take exceedingly simple steps to ensure it is, forge really cannot help you..
