### ISSUE TITLE
Race condition with SimpleNetworkWrapper sendToDimension

### ISSUE THREAD

**Issue by TheGreyGhost** [MinecraftForge/MinecraftForge#1908]
There seems to be a race condition with SimpleNetworkWrapper.sendToDimension which causes the bytebuf in an IMessage to be assembled incorrectly (the message discriminator is omitted from one of the sent messages )

Test code:
https://gist.github.com/TheGreyGhost/0e7b5e1d0a868ce311a0

This sends a simple message from the server to the client every 100 ticks:
63 discriminator
100 start marker byte
4 bytes (int) with a tick count
101 end marker byte
total = 7 bytes including discriminator

When I build this to a jar and install it on one machine, it works fine.
If I install it on two machines and Open to LAN, an intermittent crash occurs.  Typically one of two error messages occurs:
On the remote client- 
[17:09:56] [Netty Client IO #0/ERROR] [FML/]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Undefined message for discriminator 100 in channel racecheckchannel
(i.e. the discriminator has been omitted from the transmitted message)

On the machine which is hosting to LAN, a different message occurs intermittently
[18:02:18] [Netty Server IO #4/ERROR]: java.lang.IndexOutOfBoundsException: readerIndex: 8 (expected: 0 <= readerIndex <= writerIndex(7))
For further details:
https://gist.github.com/TheGreyGhost/62d3d37fcef29700eb9a

It should be impossible for single-threaded code to produce an index of 8 after being checked in the first part of AbstractByteBuf::writeBytes()

Creating a new msg for every target EntityPlayerMP works without a problem
https://gist.github.com/TheGreyGhost/f8964ede43732fd1016e

Tested in 1334 and 1419.

**Comment by codahq** [comment]
I'm hitting this frequently as well.  For now, I guess I will use the workaround to create a new message for each player.

**Comment by samdalicious** [comment]
X2
I think I'm encountering this issue as well but not with sendToDimension.  I'm seeing it all the time with SendTo.

**Comment by LexManos** [comment]
Not able to reproduce but this is the only logical thing I could think of that would be the issue.

**Comment by codahq** [comment]
Still happening.

**Comment by codahq** [comment]
Also, it's very easy to reproduce with the code TGG posted here:

https://gist.github.com/TheGreyGhost/0e7b5e1d0a868ce311a0

Turn off online mode on the server and from eclipse start a dedicated server and two clients.  If you want it to happen faster change the code where the incrementing nextID is getting modded to 1 so that messages are sent more frequently.  One or the other client will almost immediately drop with the IOOBE.

**Comment by LexManos** [comment]
Ran his code for an hour, using 15 clients connected to the server.
Tried with local, lan, and remote servers.
No errors.
The Only logical thing that could be causing this was patched,

**Comment by TheGreyGhost** [comment]
I haven't had a chance to test the patch yet, next opportunity this weekend.

**Comment by codahq** [comment]
I just tried again with a fresh install.  I can confirm (now that I'm not derping) that the fix does address the issue.  Thanks, Lex!
