### ISSUE TITLE
Netty Causing ConcurrentModificationException

### ISSUE THREAD

**Issue by codahq** [MinecraftForge/MinecraftForge#1909]
Netty appears to be causing a ConcurrentModificationException because it modifies the entities list of a chunk in a thread while it is being iterated in the main thread.

Here is a simple mod that demonstrates the issue.  

https://github.com/codahq/packet_test_mod

Place one of the test blocks into the world and hold right click.  Eventually, usually less than a minute, you will get an exception.  I have clearly exacerbated the issue by spawning many particles (creating many entities) but I have hit this exception often enough without the exaggerated particle count even though it is extremely rare.

I have tested that this never occurs in 1.7.10.

**Comment by TheGreyGhost** [comment]
Hi

Did you know that network messages are now handled by a separate thread, and you need to use thread-safe code to transfer your message to the client or the server thread?
http://greyminecraftcoder.blogspot.com.au/2015/01/thread-safety-with-network-messages.html

Unless I've misunderstood the symptoms of your problem?

-TGG

**Comment by rich1051414** [comment]
With the game becoming more threaded, I wonder if it would be a good time to add an invokeLater function to the event bus to make doing these cross thread functions less of an ordeal. I only suggest it as it is a feature of java people are used to and helping prevent concurrency is a good thing :)

**Comment by diesieben07** [comment]
It already exists. Described in TGG's post.

**Comment by codahq** [comment]
TGG, no I didn't realize that.  Thank you for pointing it out.  I wish there was a better way to distill this type of change out to the mod developers.

**Comment by diesieben07** [comment]
Yeah, there really should be a central warning. Most mods out there currently do this incorrectly and have lurking weird errors waiting to happen.

**Comment by rich1051414** [comment]
I had no idea this was implemented already :+1:
