### ISSUE TITLE
[10.13.3.1420] splash screen crash due special characters in modid

### ISSUE THREAD

**Issue by hunter688** [MinecraftForge/MinecraftForge#1910]
When have installed Gliby's voice chat mod with special chracters in the modid, new splashscreen crashed. Without this mod or when disable splashscreen client start without this crash.

Crashlog:
http://pastebin.com/w7JrVxhq

**Comment by ThePsionic** [comment]
Tell the author of the mod to not have special characters in the mod ID. Mod IDs shouldn't have color codes.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/3bbf5c04a61882fee1abe25ab0cfb822a606cc6d

**Comment by hunter688** [comment]
Reopen please, issue is still here - forge version - subj - 10.13.3.1420.

**Comment by Bogdan-G** [comment]
Last version forge .1422 for 1.7.10

**Comment by hunter688** [comment]
I know, but there is no changes related to issue...

**Comment by Gliby** [comment]
My mod doesn't have any special characters in the **mod id**, just the name.
"name": "§aGliby's§f Voice Chat Mod",

**Comment by psxlover** [comment]
§ is a special character...
