### ISSUE TITLE
AnvilUpdateEvent does nothing

### ISSUE THREAD

**Issue by Zaphodious** [MinecraftForge/MinecraftForge#1915]
Nothing that I do to the event object makes any difference. I can tell that my subscription is being called and that there are things in the object with a System.out.println, but I see no effect in the game itself.

**Comment by simon816** [comment]
From taking a quick look, I think `onAnvilChange` should return `true` in [`ForgeHooks:651`](https://github.com/MinecraftForge/MinecraftForge/blob/5b28eb53e8623448b1c2bdb46b8924662e690995/src/main/java/net/minecraftforge/common/ForgeHooks.java#L651)

**Comment by 28Smiles** [comment]
Thats not the Problem it's in the patch I've made a fix for this let's see if it will be accepted

**Comment by 28Smiles** [comment]
The Event is right now only fired when you put 2 items in the Anvil, or rename an Item.

**Comment by 28Smiles** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/1919
Look here

**Comment by LexManos** [comment]
No, it should work just fine. And no it shouldn't return true because if it did you would have your stuff overwritten by the vanilla implementation.
If you notice it does  e.output == null, so set the output to something not null.
And then it will copy over the output, and costs to the anvel...

If you still have issues post code.

**Comment by cgcgbcbc** [comment]
> And then it will copy over the output, and costs to the anvel

If I just want to modify the cost, I must set an output, but since the original output is not passed into the invent, so the simplest modify cost task will need a bit bit more work (set correct output from the left and right itemstack)
