### ISSUE TITLE
[Feature Request]Custom Fluids

### ISSUE THREAD

**Issue by 28Smiles** [MinecraftForge/MinecraftForge#1917]
Can you add the posibility to add metadata for Fluids. This is a good feature because you can create a steam fluid with custom temperatures or water amount per volume.

**Comment by Choonster** [comment]
`FluidStack` already has an NBT tag. Could you use that?

**Comment by 28Smiles** [comment]
I don't know if this is posible and will not be undone by save and load.

**Comment by diesieben07** [comment]
You can't "add metadata" to Fluids, because Fluids already need the metadata to keep track of where they are flowing and how high the fluid is.
