### ISSUE TITLE
Track How Long Each Mod Takes To Load

### ISSUE THREAD

**Issue by Gaelan** [MinecraftForge/MinecraftForge#1921]
It would be super nice to have a list of what mods were negatively affecting load time the most.

**Comment by The-Fireplace** [comment]
For now, you can use this mod to achieve this: [Loading Profiler](http://mods.curse.com/mc-mods/minecraft/228513-loading-profiler)

**Comment by LexManos** [comment]
The loading screen already spits out timing information that you can grep for the information you want.
