### ISSUE TITLE
[1.8] Vanilla client login crash or packet spam on 1.8 forge, versions 1290 and latest 1436

### ISSUE THREAD

**Issue by Corosauce** [MinecraftForge/MinecraftForge#1924]
When a vanilla client logs in to a server modded forge, there is an intermittent but common server crash that occurs, and if it happens to not crash, "unexpected packet during modded negotiation" spam occurs in console until player reconnects (which it could crash upon reconnect).

Was having the issue with forge 1290 and just confirmed it still happens on 1436.

Log of crash, took about 5 login attempts: https://gist.githubusercontent.com/Corosauce/f8c6b6476e0dcd5d854c/raw/26741bfcd0535974961338ff1986fa6a88eb0a2c/gistfile1.txt

Log of packet spam if crash doesn't occur: https://gist.githubusercontent.com/Corosauce/107f770e70d2ae5c7431/raw/c45e11bad5259e4210349ee08b0aa77a8ce28e0c/gistfile1.txt

I have not been able to reproduce this when testing a server and client that are on the same local machine, only with remote servers that are far away, possibly a packet order issue caused by latency to server.

Environment reproduced on:
- Amazon Linux AMI server (happens frequently on this one, much less frequently on other servers)
- A Fresh install of forge 1436
- A vanilla client using version 1.8

To reproduce:
1. Install forge 1436 to the Amazon Linux AMI server
2. run it with: java -jar forge-1.8-11.14.2.1436-universal.jar
3. Start up a Vanilla MC 1.8 Client (not 1.8.4 or anything, just plain 1.8)
4. Connect to server that is in another country or at the very least, not locally connected so there is real latency, reconnect until crash occurs, usually happens in less than 5 reconnects.

A short sighted way to patch the problem:
- Comment out this line that does "player.playerNetServerHandler = null;" https://github.com/MinecraftForge/MinecraftForge/blob/master/fml/src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java#L188

Of course my patch is not a very clean idea, but we are launching a service that is going into production in a week and I needed a fix now. As far as I can tell, commenting out that line and the line that logs the packet spam lets the server function as it should. 

But if you guys could investigate the true cause to this and resolve it that would be much appreciated so we could integrate the proper solution into our production environment.

The Amazon Linux AMI server my work has provided me is the only server I have been able to reliably reproduce this issue on, if you require access to it to test, contact me on irc (Corosus), you know where to find me ;)

**Comment by LexManos** [comment]
You 'Comment out' those lines and you completely bork the shit out of networking for mods, ID syncing, EVERYTHING.
And commenting out the line that logs the protocol errors does not stop the errors -.-
What 'service' are you 'launching'?
