### ISSUE TITLE
Weird javadoc in IRetexturableModel

### ISSUE THREAD

**Issue by GotoLink** [MinecraftForge/MinecraftForge#1927]
The doc in IRetexturableModel suggest that using null values for retexturing is valid.
Except that the method input is ImmutableMap whose implementations do not allow null values.
For example, if [this case](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/client/model/ForgeBlockStateV1.java#L419) is ever reached, the variant model parsing will crash.

**Comment by LexManos** [comment]
God dammit, Fry/Zaggy broke it. Must of missed that one line at the end of the javadocs that said will throw  NPE if any VALUEs are null. Its a random limitation in ImmutibleMap.. wonder who's bright idea it was to add that in.
The intention is to allow null values.
