### ISSUE TITLE
[1.8] Custom armor models don't have their attributes set

### ISSUE THREAD

**Issue by fnuecke** [MinecraftForge/MinecraftForge#1939]
The call to `ForgeHooksClient.getArmorModel` in `LayerArmorBase.func_177182_a` should come two lines earlier, i.e. before the calls to `modelbase.setModelAttributes` and `modelbase.setLivingAnimations`, or at least those should also be called on the custom model in `ForgeHooksClient.getArmorModel` if one is found.

As it is now, custom models don't get these attributes set, leading to incorrect rendering, e.g. when sneaking (which was already the case in 1.7.10 due to a missing copy of the `isSneak` attribute), but also, and more importantly, the `isChild` field, leading to completely messed up transformations.

Unless, of course, I'm missing something?

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]
