### ISSUE TITLE
[1.8] Misleading comment on ItemArmor.getArmorModel

### ISSUE THREAD

**Issue by fnuecke** [MinecraftForge/MinecraftForge#1940]
The comment for the `armorSlot` parameter on `ItemArmor.getArmorModel` still states

> 0=head, 1=torso, 2=legs, 3=feet

which no longer appears to be correct in 1.8. It now appears to be

> 4=head, 3=torso, 2=legs,1=feet

or in other words, `armorSlot == 4 - ItemArmor.armorType`. Also see `LayerArmorBase.doRenderLayer`. If this is not a bug in the code, I'd suggest updating the comment.

**Comment by RainWarrior** [comment]
Enum in 1.9, closing
