### ISSUE TITLE
Localized strings have colons unnecessarily escaped

### ISSUE THREAD

**Issue by dgelessus** [MinecraftForge/MinecraftForge#1943]
When using a language other than `en_US` (the default), all colons in localized strings are prefixed with a backslash, even though they don't require escaping. This is visible in-game. The two examples below show the German translation, but this appears to happen for any language.

![forgeupdatenotice](https://cloud.githubusercontent.com/assets/6641959/8173332/080d07a4-13cc-11e5-96a0-4ba9afd4852c.png)
![forgecommandhelp](https://cloud.githubusercontent.com/assets/6641959/8173334/0ac45358-13cc-11e5-80a1-55b1634fbc80.png)

(Tested on Minecraft 1.8 with Forge version 11.14.3.1450, the current latest build.)

**Comment by HenryLoenwind** [comment]
![](http://i.imgur.com/tJgkQmh.png)

It might not be the language, but other parts of the locale.

**Comment by Lunatrius** [comment]
It doesn't depend on the language. The issue lies in ForgeGradle, directly including the Crowdin files. The generated files are generated with extra escapes on colons that have to be removed when packing the jar.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/ForgeGradle/commit/59f33ecef984e6fd85df81ae7b131ef01bff1a8e
