### ISSUE TITLE
FluidThings

### ISSUE THREAD

**Issue by Speiger** [MinecraftForge/MinecraftForge#1946]
I nodest since 1.6.4 problems with the Fluids and got even more from other people which come from forge and should be done with other things.
First: 
You can not insert TileEntities into basic FluidTanks (from forge) even if they have that field. You have to create a extra class for it to make it actually work...
Another thing:
When you drain a fluid from a basic FluidTank it automaticly looses it NBTData as long a modDev does not fix it.... I know making Copies of FluidStacks is totally right but then please copy NBTData with it.
(Note: It is since 1.6.4 and got not fixed until then)

First one: 
https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/fluids/FluidTank.java#L17
only useable if override the FluidTank. (Create a constructor that has a TileEntity requirement in it for people who want it)

Second one:
https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/fluids/FluidTank.java#L172
NBTTag will be not transfered over, simply add it, since there is a not null check in the constructor there is no problem with it...

**Comment by mezz** [comment]
`new FluidStack(FluidStack stack, int amount)` makes a copy of the NBT, at least in 1.9.4.

**Comment by williewillus** [comment]
1. Capabilities obsolete this
2. NBT is now copied by `copy()`

**Comment by Actuarius** [comment]
@williewillus closed this issue
