### ISSUE TITLE
Can't cancel PlayerInteractEvents in activateBlockOrUseItem with Fakeplayers

### ISSUE THREAD

**Issue by NitroxydeX** [MinecraftForge/MinecraftForge#1948]
Hi Guys,

reporting you this Problem, because the ForgeEssentials-Developer can't take care of it at the moment. 

Forge can't handle cancelled PlayerInteractEvents in activateBlockOrUseItem with Fakeplayers. All permission mods will crash the Server if something like this happens.

More Informations on: SleepyTrousers/EnderIO#2575 and ForgeEssentials/ForgeEssentialsMain#1578

**Comment by olee** [comment]
Well I actually intended to have a talk with the EnderIO guys first and then make a proper PR.
But then again maybe Lex can take care of this by himself without the need for a PR...

**Comment by diesieben07** [comment]
Is this still an issue with the new PIE in 1.9?

**Comment by Actuarius** [comment]
@diesieben07 added labels [Needs Update]

**Comment by williewillus** [comment]
It is, I just read through the original reports and it's because players have no NetHandlerPlayServer.
That hasn't changed in forge so it's still an issue.

Solution would be to give FakePlayer a dummied out nethandler
