### ISSUE TITLE
Crash after Updating

### ISSUE THREAD

**Issue by florian96** [MinecraftForge/MinecraftForge#1949]
Hey i have Updated Forge from Build 1307 to build 1452. (1.7.10) But when i Join to a Server, it crashes. Here is the Crash Report.

http://pastebin.com/iRYpsHZd

**Comment by diesieben07** [comment]
One of your mods is sending a broken packet. Take this to the forums please.

**Comment by florian96** [comment]
Its a bug from GregTech. I have Contacted him.
