### ISSUE TITLE
[Feature Request] Item method to control initial equipped progress

### ISSUE THREAD

**Issue by coolAlias** [MinecraftForge/MinecraftForge#1950]
This issue comes up most often with Items that use NBT to store data that changes somewhat frequently, as it causes the 'equipped' animation to play again due to the stacks no longer being considered equal.

While there are many cases where it is trivial to change the manner in which NBT is stored (e.g. check vs. world time instead of a ticking counter, store data in player's IEEP, etc.), there are also many cases where this is not practical.

What I propose is a one-method addition to the Item class, much like the many other methods added by Forge to include ItemStack as a parameter:
    public float getFirstEquippedProgress(ItemStack current, ItemStack previous, float equippedProgress) {
        return equippedProgress; // default implementation changes nothing
    }

This method would be called from ItemRenderer#updateEquippedItem:
    if (this.equippedProgress < 0.1F)
    {
        this.equippedProgress = itemstack.getItem().getFirstEquippedProgress(itemstack, this.itemToRender, this.equippedProgress); // add this line
        this.itemToRender = itemstack;
        this.equippedItemSlot = entityplayersp.inventory.currentItem;
    }

This would finally give modders the ability to control exactly how their item should be rendered in first person so they wouldn't have to resort to crazy hacks like [this] (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/2350828-unequip-equip-animation-on-item-damage?comment=4).

See [this thread] (http://www.minecraftforge.net/forum/index.php/topic,30937.0.html) for the original proposition and discussion.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/453ec39496e85eb3be731ee3279452c6d1e50f89

**Comment by coolAlias** [comment]
I just saw that in the changelog. Sorry for wasting your time :\
