### ISSUE TITLE
Texture Maps load twice during loading

### ISSUE THREAD

**Issue by rwtema** [MinecraftForge/MinecraftForge#1954]
When the Texture Map object is initiated (during the init phase), it registers and loads all textures for both items and blocks. When the resource manager is reloaded after post-init, it does this again. Loading textures can take over two minutes for a large modpack, so I say that preventing that would absolutely be a HUGE benefit.

There is absolutely no reason that a sensibly designed mod should need access to the texture maps before the splash screen disappears.

Note: This bug also applies to the Sound Handler, although that's typically not as long to load.

**Comment by LexManos** [comment]
You expect sensibly designed mods...
Last time we killed this there were mods falling from the trees that they couldn't access their textures in init.
Yes, we could skip the first reload {or potentially short circuit it} but it has the issue of breaking mods.

**Comment by rwtema** [comment]
how about allowing the registering of textures but not load the actual files (just leave the texture map blank)?

**Comment by LexManos** [comment]
http://github.com/MinecraftForge/MinecraftForge/commit/4235ca36ea32a89458e018677418e3fda1b84711 That might do it, everyhting should be 'missingtex' on the first pass but get the real textures on the second.
Added a disable flag in case it breaks shit.
Get some test cases on large packs please. It's build 1469

**Comment by bonii-xx** [comment]
Hm, I'll need to test the effect of this on my texture generation. The pre-stitch event only gets called once now, right? At the point when the manager was reloading before?

**Comment by mrdeadlocked** [comment]
I just tested out the newest 1470 version on my modpack (222 mods) My normal loadtime on (1448) was 3 mimnutes 16 seconds. On the newest version it loaded in 2 minutes 14 seconds. Quite an improvement.

**Comment by LexManos** [comment]
No, the texture stitch events and texture atlases are called twice as usual. It just skips the actual LOADING of the first set of textures and sets everything to missingtex for the first pass so that modders still have their sprites to work with, it's just like the texture pack is broken.

Then the second reload hits and everything gets the correct textures.
Its like the user switched texture packs mid-game. Should work fine on all modders that don't hard rely on anything more then 'this is my uv, there are many like it but this one is mine!'

**Comment by bonii-xx** [comment]
Ah, ok. I'll check for missingtex then in my loading to not waste processing power on the missing texture that will get overwritten by the reload. That was actually one of the points bugging me - that the processing was getting done twice on startup in some cases.

**Comment by LexManos** [comment]
just dont do any generation on the first one, or before post-init.

**Comment by sfPlayer1** [comment]
This breaks ShadersModCore, crashing (http://pastebin.com/Q0FQDywa) and potential further loss of functionality. Disabling the optimization fixes it.

Apparently the mod is (ab?)using the related texture resource loading as a hook/entry point, which when missing causes its resManager field to be null, crashing later on.

**Comment by LexManos** [comment]
I dont care about coremods abusing functions.

**Comment by bonii-xx** [comment]
From what I've worked with that stuff yet it should be fixable by the ShadersModCore itself. It'd probably suffice to simply wait until after postInit before it does anything and then continue as usual.
