### ISSUE TITLE
Fullscreen issue.

### ISSUE THREAD

**Issue by bathos64** [MinecraftForge/MinecraftForge#1960]
Hello, first of all I would like to say that the issue does *NOT* happen with Vanilla, it only happens with Forge. That's why I thought it would be a good idea to put this here. Also, I am using Linux, latest Nvidia drivers. 

Basically, when I start Minecraft Forge and go into fullscreen, only 1/4 of the screen is actually visible, the rest is black.
![screenshot from 2015-06-23 01-07-17](https://cloud.githubusercontent.com/assets/13006022/8295359/db069020-193b-11e5-937a-e8e7c688d9ea.png)

It does not seem to reproduce in Windows.

**Comment by LexManos** [comment]
Move this to the forum, I doubt this anything beyond your drivers derping up.
You could try disabling the splash screen just in case that's the issue.
However basic stuff like this needs to go through the forums first and once its actually determined that it is a actual issue with Forge itself that needs a change on Forge's end, THEN make a issue/PR here.
