### ISSUE TITLE
Tweaker mods are not shown in the mod list

### ISSUE THREAD

**Issue by Guichaguri** [MinecraftForge/MinecraftForge#1961]
Mods based on a tweak class (Optifine, ShadersMod) are not shown in the mod list as they used to be.
I don't really know if it is intended, is a bug or a forgotten feature, but it's always good to let the player know what mods are installed.

**Comment by LexManos** [comment]
Tweakers were never shown in the mods list from what I recall.
Optifine has a special case on our end, but in order for tweakers/coremods to be listed they need to opt-in themselves and add a ModContainer.
If Optifine isn't in, there may be an issue with out special casing for them. Or they changed something.

**Comment by Guichaguri** [comment]
I know ShadersMod have a mcmod.info file to give information to Forge, this worked in 1.7.10
Optifine isn't shown either

**Comment by cpw** [comment]
This is getting an overhaul. I would spare the effort myself..
