### ISSUE TITLE
[1.8] Fluid texture bug

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#1962]
![2558-06-23_12 01 37](https://cloud.githubusercontent.com/assets/6128413/8299179/f3af53d8-199e-11e5-8d63-93cea88c2e8b.png)

Forge new version have a new rendering but, Minecraft Cauldron is bugged with water texture.

**Comment by LexManos** [comment]
Please provide logs and exact versions you are first experiencing this issue with.
If you tell us the exact build number we can match it to a commit which will tell us exactly what broke it.
Either way, poked @RainWarrior about it.
