### ISSUE TITLE
Model loading stuff

### ISSUE THREAD

**Issue by bonii-xx** [MinecraftForge/MinecraftForge#1963]
This issue contains a few things, mostly so as a reminder so we don't forget it.

When loading a model that has a parent model, and something goes wrong while loading the parent model itself (NOT because the parent model is missing) then the error message reports that the child model couldn't be loaded, but doesn't mention the parent.

Example: Foo has Bar as parent model. During the loading of Bar something goes wrong. Error message says Foo couldn't be loaded, while the actual problem lies with Bar.

Connected to the above, errors are hidden so models can be defined in pure code. Should introduce a "dont error on these models because we handle it interally but the names are here in the resource so that resource makers know what to add". Related commit: b8add23d9bc1c225ca0e25a3e3419e6ed89b1879

A defaults json thing that allows to contains a list of blocks that should generate a normal->model blockstate and if needed a minimal cube_al model with the texture based on the blockname.

Possibly add some helper functions and classes that allow to represent quads before they're baked. Vanilla uses ModelBlock internally, but it'd be nice to have something to represent a quad and then simply call bake() on it to get a BakedQuad() out of it. Also a helper function that directly creates a BakedQuad() without the need to go through vanilla generation or mess with the internal vertex representation would be nice.

**Comment by RainWarrior** [comment]
Most of these things are fixed, closing, new issues should be made for things that are still relevant from this one.
