### ISSUE TITLE
public IIcon getIconIndex(ItemStack) not returning the stack's NBT data - Possible vanilla bug

### ISSUE THREAD

**Issue by MicobyteMichael** [MinecraftForge/MinecraftForge#1967]
In net.minecraft.item.Item, there is a method called public IIcon getIconIndex(ItemStack). I am using a custom implementation of ItemBlock to show if the block is 'depleted', and when it is 'depleted', it has a different IIcon, stored in the block class. The data used to determine if it is depleted is in the NBT. However, this data is apparently not accessible from the aforementioned method. Yes, I am sure that the IIcons are different and that my code for determining the 'depletion' state works [it can check the NBT when it is placed and the TileEntity contains the NBT, using the method public IIcon getIcon(IBlockAccess iba, int x, int y, int z, int side) in net.minecraft.block.Block].

Here is my code example: http://pastebin.com/EnjeRQ8Z

**Comment by LexManos** [comment]
Update to 1.8, also this is the exact item stack that its's trying to render, if the NBT data is not shared in it then your syncing is off or something. Either way 1.8, and move simple things like this to the forums until you determine it is an actual issue in forge.

**Comment by MicobyteMichael** [comment]
Hmmm... I was looking into the wrong vanilla method, I think. I still don't get why my NBT is not present, as it is definitely present in the method addInformation(ItemStack, EntityPlayer, List, boolean).
