### ISSUE TITLE
[Suggestion] EntityDeathEvent and/or EntityHurtEvent

### ISSUE THREAD

**Issue by palaster** [MinecraftForge/MinecraftForge#1970]
My suggestion if for there to be an event which I can hook to find when an entity that is not living, but can still be set dead, to have an event that I can cancel. The main reason for me suggesting this is because I want a way to catch any item entities that are destroyed via fire, lava, or by being thrown out the world.

**Comment by LexManos** [comment]
net.minecraft.world.IWorldAccess.onEntityRemoved(Entity)?

**Comment by palaster** [comment]
I didn't know that existed, but how would I implement that?

**Comment by LexManos** [comment]
Its an interface, you implement it like any other interfaces.
And then you look at vanilla and see where it's used and mimic that its straight forward.

**Comment by palaster** [comment]
Thank you for the help, I got it working.
