### ISSUE TITLE
[1.7.10][Forge 1448+]Fluid Registry Crash on client joining server

### ISSUE THREAD

**Issue by Blood-Asp** [MinecraftForge/MinecraftForge#1973]
https://github.com/Blood-Asp/GT5-Unofficial/issues/58
I tried to fix this bug in my side, but seems to be on forge side.
https://github.com/MinecraftForge/MinecraftForge/commit/63f230079473702953173dbf7e4b54276532bca1#diff-a27ff85fc320f1d8269b133701c1c5b2

**Comment by hunter688** [comment]
Same issue is with Growthcraft Cellar (fluids). Client crashes when join to server with ticking screen...

**Comment by Blood-Asp** [comment]
I'm pretty sure, the removal of https://github.com/MinecraftForge/MinecraftForge/blob/50608986fe419c9328b3fc6f65415c805fa140cd/src/main/java/net/minecraftforge/fluids/FluidRegistry.java#L84 is the issue.
 fluidNames.clear(); got removed without a equivalent addition.
The HashMap still contains the client side fluid names when the server side fluid names get synced in. Once there is a difference beween server and client -> crash. And fixing different fluidmaps is exactly what all this stuff is trying to do.

So to fix this, https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/fluids/FluidRegistry.java#L115
localFluidNames must be initialized empty or cleared.

**Comment by cpw** [comment]
Hmm. There was a reason I removed the clear. It causes SSP to break, because there's only one instance of the map..

**Comment by Blood-Asp** [comment]
But the way it is right now, SMP is broken. So how about doing it the same way as with the fluidIDs? Removing only the one Value that gets added directly after, so a crash due to double entry is impossible? 
By now i have about a dozen bugreports because of this, so i hope this gets fixed soon.

**Comment by cpw** [comment]
It's not broken though? Please give a specific error.. I tested this pretty thoroughly..

**Comment by Blood-Asp** [comment]
If client and server fluid ids are out of order, this happens on join: http://www.hephinator.com/crashlogs/fml-client-latest-1.log There are allready multiple similiar reports from different mods. GregTech only is more vunerable to this, as it registers quite a bunch of fluids.

**Comment by hunter688** [comment]
My crash with gregtech, growthcraft installed:

http://pastebin.com/auJLt7Y8

**Comment by ET-Bent** [comment]
See this: https://github.com/Blood-Asp/GT5-Unofficial/issues/86

This happens on a simple Client / Server setup with only GregTech installed.

**Comment by cpw** [comment]
OK I see now. Protip, rather than blaming a specific change that was necessary, how about you just say what the bloody error is next time?? 'Key already present' - that's a simple derp, easily fixed.. Dunno why it didn't show on my testing, but whatever..

**Comment by Blood-Asp** [comment]
The crash reports were linked in the main post for 2 weeks now. Since nothing happend i tried to somehow pinpoint the problem.

**Comment by cpw** [comment]
Should be fixed now. Please try latest forge.

**Comment by Blood-Asp** [comment]
Seems to work fine. Thanks.
