### ISSUE TITLE
[Suggestion] Client/Server Mod Rejections Event

### ISSUE THREAD

**Issue by maxpowa** [MinecraftForge/MinecraftForge#1976]
Forge could fire an event on both the server and the client when a client joins a server with a mismatched mods list. The details of this event are already displayed to the player and in the log, so it wouldn't be difficult to add the event. This could be open up the opportunity for auto-updater and client-updater mods to download mods based on server mod lists. Perhaps the server could also send the client a full list of the mods it requires to successfully join, as this data is already available on the server side when negotiating the handshake.

**Comment by LexManos** [comment]
Encouraging and endorsing bad behavior that exposes way to many security issues is a horrible idea, no.
