### ISSUE TITLE
NEI crash

### ISSUE THREAD

**Issue by florian96** [MinecraftForge/MinecraftForge#1979]
After Updating the Server form 1307 to 1448 and if i Search in the NEI some things, it lost the connection or Crash. Here is the Log: http://pastebin.com/dZn0UtpW

And here the Server Side Log: http://pastebin.com/M0XJmYxg

**Comment by LexManos** [comment]
NEI is creating aim nvalid fluid stack, they should stop doing that. Nothing to do with Forge.
