### ISSUE TITLE
[1.9.4] Custom fluids/Water transparency bug

### ISSUE THREAD

**Issue by Marlor** [MinecraftForge/MinecraftForge#1984]
![51d9cd3496 1](https://cloud.githubusercontent.com/assets/3026213/8458863/c3da65fe-2019-11e5-8869-193363455560.jpg)
![65a1bc84ed 1](https://cloud.githubusercontent.com/assets/3026213/8458871/cf8cca40-2019-11e5-92cf-c102cbc77866.jpg)

By using "ModelFluidDebug"

**Comment by mcenderdragon** [comment]
This is rendering with alpha chanel, it also creates bigs with TilEntitys, more render methods fpr alpha would be very usefull

**Comment by bonii-xx** [comment]
I don't see the bug? Both are rendering transparent correctly?

**Comment by jk-5** [comment]
@bonii-xx In the first picture the entire front face of the water is missing

**Comment by LexManos** [comment]
Ya its a level issue trying to get them to meet up at the corners, poke @RainWarrior

**Comment by bonii-xx** [comment]
I.. did not see the step there at all. o_O

**Comment by mcenderdragon** [comment]
is there a way to add multipli methods for TileEntity rendering or Eventfor World Rendering too ? . like
renderTileAT(...) and renderAlphaChennel(...) ? This would fix many issues with different mods using alpha.

**Comment by mcenderdragon** [comment]
This bug is caused by wrong render order too.
![2015-07-07_15 29 54](https://cloud.githubusercontent.com/assets/6342933/8547151/4b1a8e3e-24bd-11e5-9778-6e1eeeb6794a.png)

**Comment by LexManos** [comment]
That has nothing to do with this fluid issue, and there really isnt a way to fix that without finding some way to do generic depth sorting to alpha stuff. Which really doesnt work.

**Comment by mcenderdragon** [comment]
Well, currently the method to render the TileEntity in another pass would work if TileEntitys are completly tranparenz or completly solid, but sometimes the are both so methods to handel that would be nice. But I know this is a Bug at Minecraft itself. (My picture is the proof for that) .

**Comment by LexManos** [comment]
Again nothing to do with fluids, do not hijack other people's issues -.-

**Comment by mcenderdragon** [comment]
Sorry

**Comment by RainWarrior** [comment]
I suspect the issue is inside BlockFluidBase.getFluidHeightForRender.

**Comment by LexManos** [comment]
Please confirm this is still happeneing in the current rendering engine.

**Comment by Marlor** [comment]
Confirmed on MC 1.9.4 Forge 12.17.0.1926
