### ISSUE TITLE
FML is throwing AIOBException on Splash Screen because it cannot support Partial-Framed Gifs

### ISSUE THREAD

**Issue by Drullkus** [MinecraftForge/MinecraftForge#1986]
Game Version: 1.7.10
Version: 10.13.3.1403 and 0.13.4.1481

Here's the [offending gif](https://dl.dropbox.com/s/a7uzl1au9c2bear/loadingtwirl.gif) that's causing the splash screen to crash. (The game continues launching as normal with a black screen.)

~~I have no idea why this gif would cause a crash. It's the same size as the forge.gif: 256x256. :\~~

See next post on what causes this problem.

```
[03:08:43] [Thread-6/ERROR] [FML]: Splash thread Exception
java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
at sun.awt.image.ByteInterleavedRaster.getDataElements(ByteInterleavedRaster.java:318) ~[?:1.7.0_71]
at java.awt.image.BufferedImage.getRGB(BufferedImage.java:918) ~[?:1.7.0_71]
at cpw.mods.fml.client.SplashProgress$Texture.<init>(SplashProgress.java:632) ~[SplashProgress$Texture.class:?]
at cpw.mods.fml.client.SplashProgress$3.run(SplashProgress.java:214) ~[SplashProgress$3.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
```

**Comment by Drullkus** [comment]
I found the problem:

Photoshop has multiple ways of optimizing gifs. One of them is to use multiple frames, so the first frame may be 256x256 but then the next frame may be 230x230 to crop the background off because both frames are identical. The FML Splash gif loader has no safety measure against multi-framed gifs.

For anyone viewing this issue via google: Here's what you can do in photoshop: Select all of the frames in the animation sequence and switch them from 'Automatic' to 'Do not dispose'.

![screen shot 2015-07-02 at 1 33 21 pm](https://cloud.githubusercontent.com/assets/5010174/8487218/6548b22e-20bf-11e5-8f53-b5d3dc7b80a5.png)

**Comment by cpw** [comment]
This is all code that is from regular Java. We don't do anything special. My suspicion is that they would fail to load in the regular Image code in Java as well. Since it seems simple to fix from an input point of view (disable the silly photoshop optimization?) I would suggest this isn't something that FML can fix..
