### ISSUE TITLE
Format for allowing tweak mods to have a ModContainer

### ISSUE THREAD

**Issue by Guichaguri** [MinecraftForge/MinecraftForge#1988]
Tweak mods can already be loaded by FML if they have `TweakClass` in the manifest file.
This issue is to define the best format for a tweak mod to have a ModContainer.

It cannot have any extra code that forces using Forge as a library, the whole point of they being tweak mods instead of core mods is to make them work in vanilla.

This issue was opened by a request from @cpw. ( #1971 )

**Comment by Guichaguri** [comment]
The tweak mods could have a `mcmod.info` file, but it's better to avoid using it.

The manifest should definitely have the name/id for the mod.

**Comment by killjoy1221** [comment]
LiteLoader currently uses the following manifest entries to define tweak metadata.

- TweakName
- TweakVersion
- TweakAuthor

There is also the option of using Implementation-Title, Implementation-Version, and Implementation-Vendor for these values.

**Comment by cpw** [comment]
Thanks!

My 2c : we should try and be reasonably compatible with LiteLoader. If LL uses the above values, we should support the same.

My thinking would be perhaps, to add a manifest TweakInfoFile: <filename in meta-inf> that has a reasonably standard JSON style format for extended information about the tweak/mod/whatever.

Hey @mumfrey I don't know if you want to weigh in on this?

**Comment by Guichaguri** [comment]
I like the idea of having `TweakName`, `TweakVersion` and `TweakAuthor`, but should also be supported other values like `TweakDescription` and `TweakUrl`.

The problem is that `TweakName` is the display name of the mod in LL, so there are two options: FML can use it for the mod id or add a `TweakId` value

**Comment by cpw** [comment]
My thinking would be that we don't want to overload the Metainf with a dozen or more properties. I think having an extended info file would be the way to go

**Comment by Guichaguri** [comment]
This "extended info file" would be something similar to `mcmod.info`, where you can add extra info about the mod? It's a good idea, but what would be the file format and extension?
(@mumfrey will probably take some time to reply us because he is at Minecon)

**Comment by Mumfrey** [comment]
> (@mumfrey will probably take some time to reply us because he is at Minecon)

I was! Lex hit me in the face with an inflatable hammer! I'm back now.

> My 2c : we should try and be reasonably compatible with LiteLoader. If LL uses the above values, we should support the same.

I'm actually around 98% certain that the values mentioned above are what we originally discussed when `TweakClass` was first added to the standard, I already supported using the Oracle ones 'Implementation-Vendor' etc. so I just added the new keys to my existing code. So yeah, it makes sense to go with those if possible, pretty sure they were your idea in the first place! :smile: 

> My thinking would be perhaps, to add a manifest TweakInfoFile: that has a reasonably standard JSON style format for extended information about the tweak/mod/whatever.

At this point is there any down side to just using `mcmod.info` as a standard though? I don't see any drawbacks to using the existing standard and as you say we should probably avoid polluting the manifest with unrelated cruft.

**Comment by killjoy1221** [comment]
I can think of at least 1 issue with the current system when it comes to tweaks. Presently, each jar can only support 1 tweak at a time, which doesn't have any sort of ID (save the class name). The mcmod.info file however supports multiple mods and requires a modid to determine which is which.

We could always just use the class name as the modid, but that would be confusing. A new format based on mcmod.info that only supports 1 mod would be better.

**Comment by Guichaguri** [comment]
> We could always just use the class name as the modid, but that would be confusing.
That would be worse than not supporting tweak mods, the developer can change the class name at any time.

At this point, I think we all agree that tweaks should have a JSON file with all needed information. Any thoughts about the standard of this file? Maybe the same design of mcmod.info but with a single object instead of an array?

**Comment by killjoy1221** [comment]
Something like this?
```
{
  "name": "Tweak Name",
  "version": "1.0",
  "description": "Some tweak thing",
  "url": "https://somewebsite.com/tweak",
  "tweakClass": "com.example.TweakClass" // etc
}
```
Or perhaps an additional object in the current system.
```
{
  "modListVersion": 3,
  "modList": [],
  "tweak": {}
}
```

**Comment by Guichaguri** [comment]
Both works for me. @cpw, is it all good?

**Comment by Mumfrey** [comment]
Can I just throw into the mix that if it's decided to go with an arbitrary extra file, that this should be defined with an additional metadata key rather than being yet another "hard coded" value. For example

    TweakMetaFile: /tweakinfo.json

**Comment by cpw** [comment]
Agree @Mumfrey I would expect it to be an explicit attribute in manifest, relative to META-INF myself.

**Comment by Guichaguri** [comment]
After almost a year, I'm back working on this feature.
Here is what I was thinking about the file:
```json
{
    "id": "tweakmod",
    "name": "TweakMod",
    "version": "1.0",
    "author": "",
    "description": "A simple tweaker",
    "url": "http://example.org",
    "tweakClass": "org.example.tweakmod.Tweaker",
    "tweakOrder": 1000
}
```
Should I proceed with the implementation?

**Comment by kashike** [comment]
To be consistent with existing manifest entries, keys should have their first character upper-cased as well - ex: `TweakOrder`, `TweakClass`, etc.

**Comment by Guichaguri** [comment]
@kashike Every [JSON key in Forge](https://github.com/MinecraftForge/MinecraftForge/search?l=json) is **camelCased**, I think this file shouldn't be different.

**Comment by Mumfrey** [comment]
@Guichaguri specifying tweakclass and tweakorder in the info file just seems kind of redundant, since all it really does is open up the possibility that it's out of sync with the actual values specified in the manifest. Really the file ought to just have the extra keys which aren't already available in the manifest.

Other than that, my comment about specifying the path to the file in the manifest itself is the only important detail I'd like to see incorporated.

I also agree that camelCase makes sense for a JSON file, manifest entries are Title-Case-With-Hypens and applying that format to JSON keys doesn't make a lot of sense, nor does using PascalCase as suggested by @kashike. Just stick with camelCase for consistency.

One final question. In the instance that values are specified in the manifest and in the JSON (as mentioned above, I already support an extension standard in TweakName etc.) which should take precedence?

**Comment by Guichaguri** [comment]
@Mumfrey Just to "illustrate" what you said, is this what you mean?

META-INF/MANIFEST.MF
```
Manifest-Version: 1.0
TweakClass: org.example.tweakmod.Tweaker
TweakOrder: 1000
TweakMetaFile: tweakmod.json
```

META-INF/tweakmod.json
```json
{
    "id": "tweakmod",
    "name": "TweakMod",
    "version": "1.0",
    "author": "",
    "description": "A simple tweaker",
    "url": "http://example.org"
}
```
The path should be relative from the META-INF

I think the JSON should take priority, since it is dedicated for mod containers.

**Comment by Mumfrey** [comment]
> @Mumfrey Just to "illustrate" what you said, is this what you mean?
> 
> META-INF/MANIFEST.MF
> 
> Manifest-Version: 1.0
> TweakClass: org.example.tweakmod.Tweaker
> TweakOrder: 1000
> TweakMetaFile: tweakmod.json

Yep, that's exactly what I meant :+1: 

> The path should be relative from the META-INF

Again, agree with this, though of course the author would be at liberty to start the location with `/` to make it relative to the container root if they chose.

> I think the JSON should take priority, since it is dedicated for mod containers.

Makes sense, that's what I assumed but I wanted to be absolutely sure.

As soon as you nail this down I will add compatibility to liteloader as well.

**Comment by Guichaguri** [comment]
There are several ways to implement this feature in Forge.

#### Classes
* `TweakModContainer` - Self explanatory. A class that implements `ModContainer`
* `TweakMetadata` - A class for loading tweaker files. Similar to `ModMetadata`

The problem is that a `ModContainer` needs a `ModMetadata` instance

#### Solutions
1. Change `TweakMetadata` to extend `ModMetadata`, and create a Gson type adapter for the right JSON keys
2. Create a metadata interface, both `TweakMetadata` and `ModMetadata` have to implement it. Everywhere in the code will reference the interface instead of `ModMetadata`
3. Initialize a `ModMetadata` from a `TweakMetadata`
4. Forget about `TweakMetadata` and load the JSON directly as a Map setting the `ModMetadata` values manually
5. Change `TweakMetadata` to extend `ModMetadata` and don't care about duplicated fields (such as `modId` and `id`)

I think the best solutions are 1 and 3.
And before is too late, I think `author` should be an array `authors` instead of a string

**Comment by kashike** [comment]
Solution 1 sounds nice.

:+1: on `authors` instead of `author` (`authorList` in metadata to be consistent with `authorList` in `mcmod.info`?)

**Comment by Mumfrey** [comment]
+1 for `authors` vs. `author` since the keys for the shared mod entries (per the `modList` blackboard key) is

* `modsystem`
* `id`
* `version`
* `name`
* `url`
* `authors` <- note plural
* `description`

**Comment by Guichaguri** [comment]
Should I create a type discoverer (`ITypeDiscoverer`) for tweakers? Mod containers will only be created when `TweakMetaFile` is specified
As I'm looking into the FML code, I think this is the best way to implement it

**Comment by Guichaguri** [comment]
@cpw Here's the commit, I want to know what needs to be changed. Can you check the code before I open a PR? https://github.com/Guichaguri/MinecraftForge/commit/0d7bf610b83292fad4cfcd2e5a37fb2372ed3146

I was going to parse the JSON with `ModMetadata` using a `FieldNamingStrategy` to change the key names, but that did not work because the `SerializedName` annotation takes priority. There is a work-around using a `TypeAdapter`, but it would take more code than just parsing manually. And also, it looks a lot less hacky this way.

**Comment by Guichaguri** [comment]
Just so you know, I opened a PR with the code (#2892). Let me know if anything needs to be changed

**Comment by mezz** [comment]
@cpw this seems relevant to your fml rewrite, may be worth looking this over again to have these things fresh in mind.
