### ISSUE TITLE
[1.8] Block model rotation not working

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#1989]
I using Forge build 1480. Vanilla TNT block rotation not display.
![2558-07-02_23 36 50](https://cloud.githubusercontent.com/assets/6128413/8507301/181fd942-2267-11e5-8d23-fa0d9a29b653.png)

**Comment by ThePsionic** [comment]
That is probably because it's also not in Vanilla.
![TNT doesn't rotate in Vanilla](http://assets.thepsionic.com/ss/Minecraft_1.8_2015-07-04_18-03-16.png)

**Comment by SteveKunG** [comment]
What!? Why you close this @LexManos? In my vanilla minecraft block model rotation is work!!

@ThePsionic You are turn on Alternate Block option to On?

![2558-07-07_10 46 24](https://cloud.githubusercontent.com/assets/6128413/8538279/6c12c756-2494-11e5-9834-f7e5a4ffd835.png)

**Comment by ThePsionic** [comment]
I did not turn it on, but seems you didn't either in your Forge instance
![imgur](http://i.imgur.com/tr3EkXC.png)
