### ISSUE TITLE
[1.8] [Suggestion] A way to change camera viewpoint

### ISSUE THREAD

**Issue by gegy1000** [MinecraftForge/MinecraftForge#1990]
In 1.7.10, this was possible by changing yOffset and eyeHeight on the player. However, in 1.8 these values are hardcoded into some methods on the EntityPlayer class. I can think of a few ways to get around it, but a simple way to do it would be very useful. Here is a topic where coolAlias changed the eye height in 1.7.10. http://www.minecraftforge.net/forum/index.php?topic=17968.0

**Comment by chibill** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/1858

**Comment by chibill** [comment]
Also as seen there there is a method to change the viewpoint. (Mentioned in that PR.)

**Comment by RainWarrior** [comment]
#1858 was merged, tell if you need anything else.
