### ISSUE TITLE
Multithread mipmap generation

### ISSUE THREAD

**Issue by PlasmaPower** [MinecraftForge/MinecraftForge#1993]
This could be fixed by making the TextureAtlasSprite loop in TextureMap concurrent (in 1.7.10). If this should be made into a separate coremod, I'll do that, but I wanted to check here first. I thought it would fit in forge as the problem only really appears when you have texture packs that span across thousands of blocks.

**Comment by LexManos** [comment]
no... why? resource loading is the issue mipping not so much.
Multi threading this would just cause more issues with the rendering engine then the splash screen already does.

**Comment by PlasmaPower** [comment]
Okay, my Minecraft was always taking forever on the mipmap generation bar (5 minutes load time, 90% of that on mipmap generation). I'm assuming "Generating mipmaps" encompasses more than just generating mipmaps?

**Comment by LexManos** [comment]
Anecdotal 'evidence' is not accepted here, logs, profiling info, etc.. Either way your computer is slow and threading wouldn't really help.

**Comment by PlasmaPower** [comment]
Okay, I'll try to do some profiling, but threading would help because I have an AMD FX-8350 which has 8 cores. When I generate mipmaps one core jumps to 100% and the others stay at around 30%. Even for a 4 core system this improvement would probably speed up generating mipmaps by at least 3x. I'll see if I can record the usage of my CPU cores along with profiling, then get back to you with the results.

As for why this is happening, I would guess it would be that I am playing with Jadedcat's resource pack which encompasses a ton of mods.

**Comment by gamerforEA** [comment]
RAM: 8 GB
CPU: Intel Core i5 3570 3.4 GHz (4 cores)
OS: Windows 8.1 x64
MC Version: 1.8

ResourcePack: MISA Realistic 1.8 (x64)
SingleThread: ~7500000000 ns
MultiThread: ~2050000000 ns

ResourcePack: Default (x16)
SingleThread: ~160000000 ns
MultiThread: ~100000000 ns

Source code (multithread): http://pastebin.com/05e3MGps

**Comment by PlasmaPower** [comment]
@gamerforEA What profiler did you use? I would like to try to replicate your test on my system.

**Comment by gamerforEA** [comment]
This is not profiler. I was edit vanilla code and make 4 run's (sorry for my English).

long time = System.nanoTime();
/* Original code:
Iterator iter = ...
*/
com.gamerforea.MipMapUtils.generateMipMaps_MultiThread(this.mapRegisteredSprites.values().iterator(), bar, this.mipmapLevels);
System.out.println(System.nanoTime() - time);

**Comment by gamerforEA** [comment]
https://drive.google.com/file/d/0B4yS8pONzKkwSDhiMHc3R3Utak0/view?usp=sharing

**Comment by PlasmaPower** [comment]
Thanks! That barely crossed my mind. BTW, check out [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/) for highlighting code.
