### ISSUE TITLE
HarvestLevel not suport metas over 16

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#1994]
with the BlockState ist possible do create Block with metas over 16, for example 30,
(i have tested it). But if you set a harvest level it crashes, because the array storing the tools, and the array storing the harvestLevel have a length from only 16.

Please create them with the Block instance and chnage there size dynamic (base on the BlockState length).

**Comment by diesieben07** [comment]
No, you cannot have meta over 15. If you try, Minecraft will silently ignore it. The world only stores metadata 0-15.

**Comment by mcenderdragon** [comment]
I have tried it with 20, after world reload it was still 20 (I have tried with propertie Integer)

**Comment by diesieben07** [comment]
That is literally impossible :)

**Comment by mcenderdragon** [comment]
I will try it again and make screen shots

**Comment by mcenderdragon** [comment]
ahh ok, sorry it removes the metas below so it can raise to 20 and higher bur metas below are deleted so I only think its posible. Sorry for that mistake
