### ISSUE TITLE
[1.7.10] Random anvil break sounds/tool break sounds playing

### ISSUE THREAD

**Issue by SuperSandro2000** [MinecraftForge/MinecraftForge#1995]
I don't know why and it's driving me crazy but minecraft plays random anvil break sounds/tool break sounds. It's sometimes every 10 minutes and sometimes ever interaction. I don't know why and don't know which mod this is causing so I simply post it here.

**Comment by LexManos** [comment]
Not a forge thing. Start removing your mods.
