### ISSUE TITLE
issue report with dw20/optifine/forge

### ISSUE THREAD

**Issue by jdog141176** [MinecraftForge/MinecraftForge#1997]
Hello there, my crash report is posted here http://pastebin.com/XzCv4A2h

not sure what the exact problem is what i was told to post it here

**Comment by Emilio17MC** [comment]
Direwolf mod pack not is compatible with Forge

**Comment by jdog141176** [comment]
then why are other people able to play it, but not me? what do i need to remove in order to play on a server??

**Comment by diesieben07** [comment]
It's a problem with Optifine, they need to update.

**Comment by jdog141176** [comment]
well a friend of mine is using it with the pack and has no issues... (1.7.10 on 1.3.1, updating to 1.5 atm)

**Comment by diesieben07** [comment]
It is a change in forge that optifine needs to adapt to. So if your friend has an older forge version...

**Comment by jdog141176** [comment]
she's running the server from the ftb launcher... which is currently being updated to 1.5, but she uses optifine while playing on the 1.3.1 version

**Comment by diesieben07** [comment]
Either way, this is not a forge issue.

**Comment by jdog141176** [comment]
well it would be nice if someone could actually HELP me here -.-

**Comment by Termin8or** [comment]
Go to the forums GitHub issues are for bugs with the forge code, not problems with users or other mods not doing stuff right.

**Comment by cpw** [comment]
Not a forge bug..
