### ISSUE TITLE
B3D issuse

### ISSUE THREAD

**Issue by laci200270** [MinecraftForge/MinecraftForge#2000]
When i try to export a model from blender with rainwarirors plugin MC can't handle that. The model itself has a cuboid and a cylinder with 6 vertexes. I think the problem with the cylinder which formated to a hexagon. With other models it works. There are not any errors in the log. Forge version: latest 1.8

**Comment by LexManos** [comment]
Provide the exact models, and sample to load it.

**Comment by laci200270** [comment]
Oh I found an error in the console here: https://gist.github.com/laci200270/897c9b924d0aa9b8b4b6#file-gistfile1-txt-L94  this is happens with every b3d model that has a cylinder with 6 vertexes and a cuboid.Here is an example model: https://github.com/laci200270/Energy-mod/blob/f42c24021368e5e916c800cb54075115d22aa631/src/main/resources/assets/energymod/models/block/engine.b3d and an example enviroment: https://github.com/laci200270/Energy-mod/tree/f42c24021368e5e916c800cb54075115d22aa631

**Comment by RainWarrior** [comment]
"No root mesh" means you have multiple objects in your b3d; you need to either merge them to 1 object in blender, or specify the mesh name (right now in the resource location, in the future - via the custom property in the blockstate json).

**Comment by laci200270** [comment]
Thanks!
