### ISSUE TITLE
Already tesselating

### ISSUE THREAD

**Issue by AegisLesha** [MinecraftForge/MinecraftForge#2005]
Crashlog: http://pastebin.com/qaVsnk1a
Might be related to Coloured Lights
Might also be related to dan200/ComputerCraft#14

**Comment by AegisLesha** [comment]
Might also be related to https://github.com/dan200/ComputerCraft/issues/14

**Comment by LexManos** [comment]
Use the forums, this is basic tech support not a issue with Forge. It appears the CC is rendering something wrong.
