### ISSUE TITLE
ObjectHolderRegistry

### ISSUE THREAD

**Issue by DanielHuisman** [MinecraftForge/MinecraftForge#2006]
Shoudn't this line: https://github.com/MinecraftForge/MinecraftForge/blob/master/fml%2Fsrc%2Fmain%2Fjava%2Fnet%2Fminecraftforge%2Ffml%2Fcommon%2Fregistry%2FObjectHolderRegistry.java#L117

Be: `if (!isMatch || !f.isAnnotationPresent(ObjectHolder.class))`

Then it would skip any fields that don't have the ObjectHolder annotation, currently it skips everything that does have that annotation.

**Comment by LexManos** [comment]
Seems to be the case. Poke @cpw

**Comment by cpw** [comment]
Nope. This is to skip @objectholder when the class has the annotation, so you can have field level overrides. They're picked up in the non-class target pass..

**Comment by DanielHuisman** [comment]
Ok, but when I make all fields public (no other edits), the ObjectHolderRegistry causes a crash, because some field gets added which isn't a block or item. In the source code I can't find anything that has a ObjectHolder annotation. Why does this crash then?

**Comment by cpw** [comment]
Log?

**Comment by cpw** [comment]
Also, does your class have the annotation? Because the class level annotation treats EVERY public static final field as a candidate block or item.. You can't mix non-game-stuff in such a class, so don't..

**Comment by DanielHuisman** [comment]
I don't use the ObjectHolder annotation and using Eclipse I can't find anything that uses it either.
(Source: https://github.com/AgeCraft/Hookinator/blob/master/src/main/java/org/agecraft/hookinator/asm/Transformer.java)

```
java.lang.IllegalStateException: The ObjectHolder annotation cannot apply to a field that is not an Item or Block
	at net.minecraftforge.fml.common.registry.ObjectHolderRef.<init>(ObjectHolderRef.java:68)
	at net.minecraftforge.fml.common.registry.ObjectHolderRegistry.scanClassForFields(ObjectHolderRegistry.java:121)
	at net.minecraftforge.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:83)
	at net.minecraftforge.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:56)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:548)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:248)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:446)
	at net.minecraft.client.Minecraft.run(Minecraft.java:356)
	at net.minecraft.client.main.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by DanielHuisman** [comment]
And another question what is ObjectHolder even used for?

**Comment by cpw** [comment]
So, you're hooking every class in the game with a coremod, and you don't know what you're doing.. This is 100% my bug, REALLY..

You're hooking classes which have the object holder from other mods. THEY are working fine. Your hook is what's broken.. My suggestion, skip any class which has the annotation.


Also, don't hook every bloody class. You're gonna find yourself in a world of hurt..

**Comment by DanielHuisman** [comment]
I'm not blaming you, I'm just curious what causes this, in my opinion, not
so obvious problem.

Ok, but the only mods installed: Forge, FML, CodeChickenCore and
CodeChickenLib. And in none of the mods there is an ObjectHolder or at
least I can't find any.

I will try skipping ObjectHolder classes. Also I'm not hooking all methods,
I'm just making everything public for easy access (yes I know that is
stupid).

**Comment by cpw** [comment]
Yeah, don't do that. FML used to do that, and it caused no end of problems. Changing visibility can actually break some code, as the linker no longer understands which of two identically named fields it should be referring anymore (in extreme cases).

ObjectHolder is sort-of dependency injection for Items and Blocks. Declare it on a class or field, and it'll try and dependency inject Items or Blocks based on field names or the value in the annotation. It removes a lot of silly boilerplate code.

The code you've been looking at injects blocks or items based on their fieldname, derived from an ObjectHolder specified on the class. 

I have pushed a small tweak to the exception so you can figure out where it's finding an ObjectHolder.

**Comment by DanielHuisman** [comment]
Ok, thanks for the explanation and tips.

**Comment by DanielHuisman** [comment]
It was `net.minecraft.init.Blocks` and `net.minecraft.init.Items` causing problems, because you added them manually without annotation. So I just skip those two and all classes with `@ObjectHolder` annotations.
