### ISSUE TITLE
ItemStackHolder-Annotation does not take class-ObjectHolder-domain into account

### ISSUE THREAD

**Issue by bonii-xx** [MinecraftForge/MinecraftForge#2007]
When annotating a class with ObjectHolder it uses this modid as the domain for all ObjectHolder annotations in the class. ItemStackHolder does not.

Working example:

``` java
@GameRegistry.ObjectHolder("myMod")
public class FooHolder {
  @GameRegistry.ObjectHolder("foo")
  public static Item fooItem;

  @GameRegistry.ItemStackHolder("myMod:foo")
  public static ItemStack fooItemStack;
}
```

The "myMod:" domain is needed on the ItemStackHolder.

**Comment by cpw** [comment]
Yes, the two systems do not interact. ItemStackHolder is not dependent on ObjectHolder and vice versa. ItemStackHolder is meant to be a bit simpler. It's a bit more verbose perhaps, because of it, but I think that's a reasonable compromise.
