### ISSUE TITLE
[Suggestion] Remove Vanilla's cloning of currently equipped item

### ISSUE THREAD

**Issue by lumien231** [MinecraftForge/MinecraftForge#2008]
In NetHandlerPlayServer.processPlayerBlockPlacement, minecraft clones the currently selected item when (or rather after) an item is right clicked:

```
        if (itemstack == null || itemstack.getMaxItemUseDuration() == 0)
        {
            this.playerEntity.isChangingQuantityOnly = true;
            this.playerEntity.inventory.mainInventory[this.playerEntity.inventory.currentItem] = ItemStack.copyItemStack(this.playerEntity.inventory.mainInventory[this.playerEntity.inventory.currentItem]);
            Slot slot = this.playerEntity.openContainer.getSlotFromInventory(this.playerEntity.inventory, this.playerEntity.inventory.currentItem);
            this.playerEntity.openContainer.detectAndSendChanges();
            this.playerEntity.isChangingQuantityOnly = false;

            if (!ItemStack.areItemStacksEqual(this.playerEntity.inventory.getCurrentItem(), packetIn.getStack()) || !placeResult) // force client itemstack update if place event was cancelled
            {
                this.sendPacket(new S2FPacketSetSlot(this.playerEntity.openContainer.windowId, slot.slotNumber, this.playerEntity.inventory.getCurrentItem()));
            }
        }
```

I can't find the purpose of that (Which doesn't mean that there isn't one :P), but it makes creating "bag like" items ( / items with inventories) harder as you can't just let it save back into the itemstack you get in your container. That's why in case there is no reason for this to exist i would suggest removing it.

**Comment by LexManos** [comment]
No, there are plenty of ways to do exactly what you wont without changing this behavior or minecraft.
There is not sufficient reason for this removal and you yourself admit to not knowing the repercussions that this may cause.
