### ISSUE TITLE
[Suggestion] /title control

### ISSUE THREAD

**Issue by Emilio17MC** [MinecraftForge/MinecraftForge#2010]
Add title for show Text in screen example

player.addTitleMessage(new ChatComponentText("Hi, this is title"));

**Comment by diesieben07** [comment]
It's as simple as sending a `S45PacketTitle` to the player.

**Comment by Emilio17MC** [comment]
In that version it was added S45PacketTitle?

**Comment by diesieben07** [comment]
1.8 of course, what else. The version that added titles.

**Comment by Emilio17MC** [comment]
I need make method for use?

**Comment by diesieben07** [comment]
No, you just send the packet to the player, it's not hard.

**Comment by Emilio17MC** [comment]
So?

>player.S45PacketTitle

**Comment by diesieben07** [comment]
This is not something that should be discussed here in the Github issues. Make a forum post.
