### ISSUE TITLE
[Suggestion] Easy Splash Adding

### ISSUE THREAD

**Issue by Emilio17MC** [MinecraftForge/MinecraftForge#2011]
Add Easy Splash for Main Screen Minecraft

> MinecraftSplash splash;
> 
> splash.addMinecraft("This is new Splash");

**Comment by diesieben07** [comment]
What should this do?

**Comment by Emilio17MC** [comment]
This should add Minecraft splashes more easy without using Resource Packs o 

![minecraftsplashexample](https://cloud.githubusercontent.com/assets/6946456/8631496/2a6693e0-273d-11e5-804a-f7c2b6da5f60.jpg)
modifying splashes.txt

**Comment by diesieben07** [comment]
You can do that already with `GuiInitEvent`.

**Comment by LexManos** [comment]
Why? I dont think vanity things like this should be accessible to modders. It's really not worth it. People already fight over who's text should show...

**Comment by Parker8283** [comment]
Maybe just a way for mod authors to add splash texts to the pool for the game to choose from? I've thought about this a little bit in the past, but since it's not something terribly important, I didn't really care.

**Comment by LexManos** [comment]
I've thought about it but people already reflectively hack in and break it forcing it to be their text because of nothing more then vanity.
But then again people have asked for it and its not that hard of a edit.
Can you do it in a 1 line patch?

**Comment by mezz** [comment]
Is this resolved? The PR for this issue was closed.
