### ISSUE TITLE
Icon registering to lower case

### ISSUE THREAD

**Issue by SCAREXgaming** [MinecraftForge/MinecraftForge#2013]
If you register your texture with the method registerIcons, the path is set to lower case in development but once exported in the mods folder, the texture are not found because the path is not set to lower case.
Explanation :
@Override
	public void registerIcons(IIconRegister r) {
		for (GunType t : GunType.values()) {
			icons[t.ordinal()] = r.registerIcon(Hilium.MODID + ":" + "charger_" + t.name().toLowerCase());
		}
	}

I'm using an enum and I get the name of the enum (like AWP) and my texture is "charger_awp" so in eclipse the texture is correctly loaded but without the ".toLowerCase()" the texture isn't found in the mods folder. I'm using the same version of forge (1.7.10-10.13.4.1448).

**Comment by LexManos** [comment]
You're a windows developer arnt you?
Zip files are case sensitive. Windows file systems are not. Hence the discrepancy.
Either way you're really over complicating things, but to each his own.
This isn't a Forge issue. You're just shipping things badly.

**Comment by SCAREXgaming** [comment]
Ok, I didn't know.
