### ISSUE TITLE
Use proffiler for mods callbacks

### ISSUE THREAD

**Issue by Kubuxu** [MinecraftForge/MinecraftForge#2015]
MC has build-in profiler (`Shift-F3`). Unfortunately it does not function well with mods as mods are not using its methods. If forge was registering whose callback it is before passing control over main thread this profiler would become powerful debugging tool without need to use `Java VisialVM`.

**Comment by Chimaine** [comment]
There the mod Opis by ProfMobius that does exactly that.

**Comment by Kubuxu** [comment]
Opis do same thing as `VisualVM` it samples mods and it has support for rendering but it would be good to use tool that is already in the game. The main difference is that MC uses profiling meaning it saves entry and exit times. Opis uses sampling which can fail in some cases.

**Comment by LexManos** [comment]
The vanilla profiler is rather useless for these types of things as its not the events or anything that re causing it it's a lot of things such as TEs which are not grouped by mod.
Your best bet is to use Opis/VisualVM.
Not to mention the major performance issues we ran into when trying to do this type of profiling makes it extremely not worth it.
When you need to find out what is wrong, use a tool actually designed for that job not the hack thats in the MC debug screen.
