### ISSUE TITLE
[1.8]Mod Items and Blocks not registering modid correctly if modid has any capital letters

### ISSUE THREAD

**Issue by CoderAtParadise** [MinecraftForge/MinecraftForge#2016]
I first discovered this issue with NEI not able to find my mod container for its subsets.

Say if your modid was "Modid" with the first letter capitalized as a number of mods do 
If you where to get your modid from and item or block using
"GameRegistry.findUniqueIdentifierFor(yourItemOrBlock).modid", you would get returned a lowercase version of your modid and if you where to look that modid up in the mod container registry you would not be able to find it.

Esentially when items and blocks are registered with their unique identifiers, capitalization of the modid is not saved.

**Comment by diesieben07** [comment]
That is correct, but it's what vanilla enforces. Resource domains (which is a bit like mod IDs) are all lowercase, and that is not a thing that forge does.

**Comment by CoderAtParadise** [comment]
k so mods will have have to have modid's as lowercase not with any caps as some are if you want to search via that way
