### ISSUE TITLE
Lighting problem on registered block (e.g. : Impossible to reproduce vanilla BlockStairs lighting)

### ISSUE THREAD

**Issue by Zyfarok** [MinecraftForge/MinecraftForge#2019]
I got a lighting bug with the block I was creating and couldn't find why...
To go further I tried to create a stairs block with the same model (my block extend BlockStairs and use a copy of the blockstates/brick_stairs.json file), and the bug is still here !
The copy of the stairs have some lighting problems (dark sides, when against another block, that the vanilla stairs doesn't have).

Here you can see some images and read more about the bug (the "second bug") :
http://www.minecraftforge.net/forum/index.php/topic,32060.html

Here you can have the code for the stairs :
https://github.com/Zyfarok/Stairs-Test

Maybe I did something wrong but the code is so simple that I don't know where I could fail !
(The bug is happening with json models and also IBakedModel (test with ISmartBlockModel available in the repo with the slope block))

**Comment by Zyfarok** [comment]
Problem "solved" :
In the Block.registerBlocks() method, I found this :
```java
Iterator iterator = blockRegistry.iterator();
Block block13;
while (iterator.hasNext())
{
    block13 = (Block)iterator.next();
    if (block13.blockMaterial == Material.air)
    {
        block13.useNeighborBrightness = false;
    }
    else
    {
        boolean flag = false;
        boolean flag1 = block13 instanceof BlockStairs;
        boolean flag2 = block13 instanceof BlockSlab;
        boolean flag3 = block13 == block6;
        boolean flag4 = block13.translucent;
        boolean flag5 = block13.lightOpacity == 0;
        if (flag1 || flag2 || flag3 || flag4 || flag5)
        {
            flag = true;
        }
        block13.useNeighborBrightness = flag;
    }
}
```
by chance "useNeighborBrightness is a protected field, so I set it to true in my block, but I think this should be done automatically in the forge block registration. (by applying using the same code)

**Comment by LexManos** [comment]
Or, you as a modder could set this and save the hassle of forcing a random standard onto modders. Its been like this for ages, no reason to change functionality now.
