### ISSUE TITLE
I have issues

### ISSUE THREAD

**Issue by cristianolionelmessisuarez** [MinecraftForge/MinecraftForge#2021]
i have mods and it says that i have to go to this website so i can play minecraft :+1:

**Comment by cristianolionelmessisuarez** [comment]
What do i do?

**Comment by loordgek** [comment]
where does it say it

**Comment by hsyyid** [comment]
You're dumb.

**Comment by Spartan322** [comment]
this belongs on the forums, doesn't it?

**Comment by mwoodman** [comment]
Just hazarding a guess:  You want to play using mods, somebody told you that you need Forge for Minecraft, you Googled it, and here you are?  What you need to do is *install* Forge for Minecraft, so head on over to the wiki for instructions: http://www.minecraftforge.net/wiki/Installation/Universal
