### ISSUE TITLE
Chunk Flashing/Vanishing

### ISSUE THREAD

**Issue by DrakoAlcarus** [MinecraftForge/MinecraftForge#2024]
I do not use Optifine, to start off, otherwise I would not be posting this. I keep getting odd chunk flashing. Luckily, I managed to snag a photo of the occurrence.

https://plus.google.com/+Drako9823/posts/MzRdh43m8DN

I'm not %100 sure it's Forge, but  I cannot tell, because there are no errors in the log.

**Comment by LexManos** [comment]
Something you have installed is causing the chunk to de-render, which is odd.
Start by removing all your mods and see if you can reproduce.
Do not create issues here until you are sure it is a Forge issue. Refer to the forums until then.

**Comment by DrakoAlcarus** [comment]
Apparently, it's common in Minecraft itself. I even removed Forge, and the same chunk vanishes while flying over it. It could be the way my computer loads chunks as well, but I noticed this issue suddenly started happening a month ago.

Whateve it is, it's no big deal.

**Comment by DrakoAlcarus** [comment]
I found the problem. Or at least I think.

On the CoFH core config file, it asks if I want to enable chunk sorting during rendering. I remember a while back I tried messing around with options, because MrTJPCore was crashing my game. I've had the annoying chunk issues since.

Sorry for wasting your time.

**Comment by DrakoAlcarus** [comment]
Update: I found the issue. The updated mod, Wild Caves 3, causes rendering issues with these chunks when entering then diagonally from another chunk. On top of that, Advanced OpenGL does this bug every once in a while. I also have a bad graphics card, and will be getting a better one soon.
