### ISSUE TITLE
When ID map for worlds is regenerated it should show this fact in crash logs

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/MinecraftForge#2026]
So it's possible to distinguish crashes caused by garbage data in the world, bad meta/tile/etc. for both 1.7 and 1.8.

**Comment by cpw** [comment]
OK. We talked about this - I understand your point. I'm going to stop any attempts by FML at using the backup. It's 99% of the time gonna be broken. "Rebuilding" should never happen. In my opinion, the only sound way to handle this is by taking regular backups. I have no idea what can be causing world corruption - FML is very careful not to break it.
