### ISSUE TITLE
10.13.3.1389+ retina display fullscreen issue

### ISSUE THREAD

**Issue by squ1b3r** [MinecraftForge/MinecraftForge#2030]
Since 10.13.3.1389 came out (which I believe the first time when that new loading screen was introduced) fullscreen on any retina display doesn't work properly. When I try to enter fullscreen only 1/4 of the screen at the left bottom corner is actually visible, the rest is black (or white, or flashing). If I move my mouse over the screen it seems like everything is in place and actually fullscreen. For example mouse in the middle of the screen actually highlight menu items. F2 also makes proper screenshots with no issues. Tried that on iMac 27 with retina and on Macbook Pro with retina as well. Same result. The only way to fix this is to use optifine and set a resolution to display's maximum. For example for iMac 27 it's 5120x2880 but it's pretty much unplayable because GUI won't scale well for such resolution. It works perfectly with 10.13.3.1388.

The only similar issue here was #1960 where bathos64 described something similar to what I have

<img width="2560" alt="screenshot 2015-07-18 20 27 22" src="https://cloud.githubusercontent.com/assets/221821/8762234/85c7b3c2-2d8c-11e5-95f1-60015afc45a2.png">

**Comment by chibill** [comment]
I remember this also happened with normal not modded Minecraft. You might
want to wait for it to load up all the way.

**Comment by squ1b3r** [comment]
Nope. Definitelly not the case. Works perfectly with vanilla and 10.13.3.1388. It's fully loaded and just won't go fullscreen properly.

**Comment by chibill** [comment]
Well you might want to post the logs... because they can't do anything
without them...

**Comment by LexManos** [comment]
Mac? Then disable the loading screen. Sounds like you're one of the macs who have a crap video driver that breaks things.

**Comment by viktorsec** [comment]
If future googlers wonder how to do this, search for `splash.properties` and set enabled to `false`.
