### ISSUE TITLE
Internal server error on sending chat

### ISSUE THREAD

**Issue by Kubuxu** [MinecraftForge/MinecraftForge#2032]
While trying to use bot working on our server we discovered that sending in chat:
```
table.concat({1,2})
```
causes internal server error.
On SP it causes crash to desktop.
We were able to narrow it down to:
```
t.co{
```
Stack trace: http://hastebin.com/cuhesolego.txt
Steps to reproduce: Just type `t.co{` in chat.
Version: `forge-1.7.10-10.13.4.1448`

**Comment by Vexatos** [comment]
It also appears to happen when typing `test.test(4)[4]` in chat. In this case it crashes at the `[` character.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/5b28eb53e8623448b1c2bdb46b8924662e690995
This was fixed months ago.

**Comment by Kubuxu** [comment]
Looks like only in 1.8 branch.

**Comment by LexManos** [comment]
I know. Because 1.8 is the master branch. If cpw cares he can cherry pick it. However, this isn't a big deal so meh.
