### ISSUE TITLE
Populating chunks does not fire an event when all population is complete

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/MinecraftForge#2034]
The `PopulateChunkEvent` events are fired before and after vanilla generation starts/completes, but then after the `Post` event mod generation begins, and mods have no way to be aware when mod generation has completed.

Firing an event at the beginning/end of `GameRegistry.generateWorld(int, int, World, IChunkProvider, IChunkProvider)` would allow tidier state keeping to avoid performing certain actions in blocks during a chunk's still-not-generated phase.

**Comment by KingLemming** [comment]
Ping @mezz  :)
