### ISSUE TITLE
[1.8] Some EnumFacing methods are client-side only

### ISSUE THREAD

**Issue by rubensworks** [MinecraftForge/MinecraftForge#2036]
Some methods inside the EnumFacing class seem to be annotated with `@SideOnly(Side.CLIENT)` which causes them not to be available server-side.
I think it might be convenient for many modders to simply remove all these annotations in this class since there does not seem to be any reason to have them only on the client.

For example, the method `rotateY()` is available on both sides while the methods `rotateX()` and `rotateZ()` are not, which is not very consistent.

**Comment by laci200270** [comment]
This is because mojang's space saving algorith.If something not used in the seerver that won't be included.

**Comment by diesieben07** [comment]
Yes, that's *why* it is, doesn't mean forge shouldn't fix it.

**Comment by laci200270** [comment]
I not said forge shouldn't fix it.I just  sai the reason.
