### ISSUE TITLE
Trying to loading modpacks 

### ISSUE THREAD

**Issue by TheLegend714** [MinecraftForge/MinecraftForge#2037]
I am unable to launch a modpack with Forge v10.13.4 and I am able to launch with Forge v10.13.2. Here are the logs.
http://paste.ubuntu.com/11915157/
http://paste.ubuntu.com/11915177/

**Comment by laci200270** [comment]
Did you put something to the jar?Use forge installer

**Comment by diesieben07** [comment]
Most likely a problem with the launcher.

**Comment by TheLegend714** [comment]
I have tried reinstalling my launcher libraries too.

**Comment by TheLegend714** [comment]
Why was this closed

**Comment by LexManos** [comment]
Because this has nothing to do with Forge you've installed something incorrectly or are using a broken launcher.
This is not tech support this is for reporting issues with Forge itself, not you screwing something up.
