### ISSUE TITLE
[1.8] EntityDiggingFX does not take into account ISmartBlockModel

### ISSUE THREAD

**Issue by rubensworks** [MinecraftForge/MinecraftForge#2039]
It looks like `EntityDiggingFX` does not take into account the existence of `ISmartBlockModel`s.
The particle icon is being set in the constructor based on the normal block state.
This means that custom models which completely change the appearance of a block based on an `IUnlistedProperty` can not have different breaking particles.

As a solution, some logic like in the `BlockRendererDispatcher` could be added that determines the extended block state and derives an `ISmartBlockModel` from it.

**Comment by LexManos** [comment]
Except BlockRenderDispatcher and the creation of the particles do not support the full world information.
As such you should use the existing hook in blocks that DO have the full world information to spawn your own particles with all the necessary information.

**Comment by rubensworks** [comment]
Oh ok, I wasn't aware such a hook existed, thanks.

For reference if anyone else should stumble upon this later on, you can disable regular breaking particles and use your own with `Block#addHitEffects`.
