### ISSUE TITLE
[1.8] Custom blockstate transformations only work for B3D models

### ISSUE THREAD

**Issue by immortaleeb** [MinecraftForge/MinecraftForge#2040]
The custom state transformations in blockstate files introduced in 20bf76464a61b711c37e7a735e53f5e3d8c1c458 only seem to work for B3D models, or at least they don't seem to work for trivial block models.

I can see this making sense for transforms that are not pre-defined, but pre-defined transforms such as e.g. `forge:default-block` should be available for all block models.

**Comment by shadekiller666** [comment]
Post an example of a json you're trying to use and an example of "trivial block models".

**Comment by immortaleeb** [comment]
An example can be found here: https://gist.github.com/immortaleeb/4efe3dea2c00732325f1
And here's a screenshot illustrating my problem:
![screen shot 2015-07-26 at 15 12 48](https://cloud.githubusercontent.com/assets/1183783/8894055/28cc5fce-33a9-11e5-981a-35ad60148922.png)

When you look at the block in thirdperson mode, the block doesn't getting properly rendered because even though the `forge:default-block` transform is applied (which should, amongst other things, fix the scale of the item).

I've also done some further testing: actually replacing the `forge:default-block` transform by manual transforms (rotation, translation and scale) doesn't fix the problem.

I have found however, that these transforms are actually being applied when you add them in the normal variant, although you can get some weird results (see screenshot below where I applied a rotation of 45 degrees around the y-axis). These results might however be intended, since I'm only trying this on a trivial model and I can see the set of supported transformations for custom models being bigger, since there you have more freedom to manipulate the model.

![screen shot 2015-07-26 at 15 22 33](https://cloud.githubusercontent.com/assets/1183783/8894083/34c0ef4c-33aa-11e5-9106-b8955dc1f730.png)

**Comment by shadekiller666** [comment]
In your main mod class, in clientInit(), instead of doing Minecraft.getMinecraft().getItemModelMesher().register(), try doing ModelLoader.setCustomModelResourceLocation().
That may or may not fix the problem, though you are loading a vanilla model.
You shouldn't need to have a "model" tag in the "normal" block in your json.
I will take a look at the forge-defaultblock values, but I don't think they are the primary issue.

**Comment by immortaleeb** [comment]
> In your main mod class, in clientInit(), instead of doing Minecraft.getMinecraft().getItemModelMesher().register(), try doing ModelLoader.setCustomModelResourceLocation().

`ModelLoader.setCustomModelResourceLocation()` doesn't seem to work; It gives you a missing texture when the block is in your inventory or hand, which probably means it doesn't find the inventory variant.
But I guess that was to be expected since it's not intended to be used for vanilla blocks.

> You shouldn't need to have a "model" tag in the "normal" block in your json.

I haven't really looked into the details of forge's blockstate format, but I know I have a duplication of the property `model` in the `normal` variant since I already declared it in `defaults`. There probably is a way to remove the duplicated property, but since this was just a quick example and it doesn't affect transformations I didn't really look into cleaning that up.

> I will take a look at the forge-defaultblock values, but I don't think they are the primary issue.

Since declaring explicit transformations doesn't seem to work either for inventory variants of regular blocks, my guess would be that it has something to do with the way regular blocks are rendered in the inventory.

**Comment by DanielHuisman** [comment]
> Since declaring explicit transformations doesn't seem to work either for inventory variants of regular blocks, my guess would be that it has something to do with the way regular blocks are rendered in the inventory.
If you create a separate item model json and explicitly declare the transforms it works fine, so there is nothing wrong with inventory rendering itself. Either Forge rendering does something weird, but most likely something goes wrong with the loading of the model from the block state json.

**Comment by RainWarrior** [comment]
This was fixed some time ago. Please comment if it still happens for you.
