### ISSUE TITLE
Build 1.7.10-10.13.4.1490-1.7.10 - Possible Skin Issues

### ISSUE THREAD

**Issue by DPxKnightxZero** [MinecraftForge/MinecraftForge#2043]
I am looking for someone who can confirm issues with skin manager and handshake to minecraft servers. I noticed sometimes my skin will be there and sometimes not. I will enter the nether with my skin but when I return to the over-world my skin is gone and I am Steve again. This does not happen in in single player.

**Comment by LexManos** [comment]
Mojang's server have been having issues. We dont touch this, this has nothing to do with Forge.
