### ISSUE TITLE
modpack crsh???

### ISSUE THREAD

**Issue by sparkmaster2001** [MinecraftForge/MinecraftForge#2049]
http://paste.ee/p/BdEQV

**Comment by GirafiStudios** [comment]
Report it on the forums..

**Comment by sparkmaster2001** [comment]
its a custom modpack

**Comment by GirafiStudios** [comment]
Well I can see that. Doesn't change anything. This is not the place to report those kinds of crash. Report it on the Minecraft Forge forums.

**Comment by sparkmaster2001** [comment]
ah right kk

**Comment by sparkmaster2001** [comment]
thnx
