### ISSUE TITLE
[FML]Load configs from zips

### ISSUE THREAD

**Issue by laci200270** [MinecraftForge/MinecraftForge#2052]
It would be good, if FML can load configs from a zip file instead of the config folder.This would be useful with the -modList switch. This maybe can activated with -configs switch.

**Comment by laci200270** [comment]
Why this get closed?

**Comment by williewillus** [comment]
There's no purpose to it. Why would this ever be used?

**Comment by laci200270** [comment]
For custom launchers like technic.It wouldn't need to tweak inside the game folder,everything can be one place.And one config can be used for multiple packs easly.

**Comment by diesieben07** [comment]
The thing is that Mods rely on configs being an actual file and there is probably some mod out there that does not forge's config system. This can never work reliably.

**Comment by LexManos** [comment]
You can already use one config for multiple packs just use the same working directory.
FML/Forge don't control the config files. 
The mods do.
Simple as that we cant do this.
