### ISSUE TITLE
Holograms not shown with Forge

### ISSUE THREAD

**Issue by bloggy** [MinecraftForge/MinecraftForge#2053]
This should be fixed if possible.Players with with forge client will not be able to see holograms, see also:
http://dev.bukkit.org/bukkit-plugins/holographic-displays/pages/faq/

**Comment by williewillus** [comment]
1. "It's forge's fault" no it's not :p They don't give any details about how exactly it's forge's fault
2. That plugin hasn't been updated in 4+ months..
