### ISSUE TITLE
[1.7.10] Skeleton skulls can't be placed on top of fence posts

### ISSUE THREAD

**Issue by tyrannozaurus** [MinecraftForge/MinecraftForge#2055]
I have noticed that when running forge (10.13.4.1492, and recent previous versions) I can't place skeleton skulls on the top of fence posts.
When I load up vanilla MC 1.7.10, and try, I am able to place them.

**Comment by williewillus** [comment]
This is in 1.8 as well

**Comment by tyrannozaurus** [comment]
Thank you!
