### ISSUE TITLE
OpenGL error with forge versions past 1384

### ISSUE THREAD

**Issue by Woohoojin** [MinecraftForge/MinecraftForge#2057]
Whenever I use a forge version past version 1384, my console is flooded with this : https://i.imgur.com/qPz8nNC.png

When I use forge version 1384, my game runs fine. However, I cannot use fluiducts or void fluid pipes, as they crash my game.

This leads me to believe the error has to do with some rendering of liquids, if that helps at all.

My graphics card is an AMD HD 7870, and my processor is and intel 3570k, I have 16GB of RAM with 4GB of it allocated to minecraft, and a 120GB SSD with minecraft installed on it.

I have updated my drivers, and it did not resolve the issue.

**Comment by Woohoojin** [comment]
This error also occurs on vanilla minecraft with only forge installed. In case you were thinking it was mod related.

The error goes away if I downgrade forge to 1384 or lower.

**Comment by LexManos** [comment]
Provide steps to reproduce.

**Comment by Woohoojin** [comment]
Step 1) Have AMD HD 7870
Step 2) Use forge version past 1384
Step 3) Minecraft is unplayable.

**Comment by LexManos** [comment]
Neither 1384 or 1285 have anything to do with rendering... Post exactly logs and give the exact version that starts it.

**Comment by chibill** [comment]
This can be reproduced in normal 1.7 and 1.8 not a forge bug.

**Comment by Woohoojin** [comment]
Yet it only happens to me when I have forge past 1384...

**Comment by LexManos** [comment]
Logs EXACT VERSIONS
Because as I said 1384 and 1385 have NOTHING to do with rendering.

**Comment by Woohoojin** [comment]
Okay, 1389 is where the bug begins. 1388 is fine.

**Comment by Woohoojin** [comment]
Pastebin from 1389 : http://pastebin.com/Z1fAK8ta

**Comment by LexManos** [comment]
1389 is the introduction of the new loading screen.
Your graphics card is shit have fun.
Disable the loading screen.

**Comment by ShetiPhian** [comment]
@Woohoojin
I have a 7870 and have no issues with the loading screen.
You have another issue somewhere.
Uninstall your driver completely, delete the files, and install the newest version from a fresh download.

**Comment by Woohoojin** [comment]
@ShetiPhian

Okay, I'll try this. Disabling the loading screen fixed the bug for me though.
