### ISSUE TITLE
A few rendering requests

### ISSUE THREAD

**Issue by laci200270** [MinecraftForge/MinecraftForge#2060]
It would be good if modders can control the jsons from the code.(I mean IExtendedBlockState)
A few things:
Scale,rotate,retexture the models based on variables passed to the jsons
An example: https://gist.github.com/laci200270/f78ce09834994b70b4a6
And this combined with sub-models would completty replace TESRs and modders still wouldn't have acces to OpenGL

**Comment by williewillus** [comment]
Can't you already do this?

**Comment by laci200270** [comment]
With the current system you can't animate models without a TESR. For example: you have something rotates based on the strength of a redstone signal. With the current system you need to make a blockstate for every possible rotation. With this you simply pass a rotation value for the submodel.

**Comment by AlexIIL** [comment]
In response to replacing TESR's: block models must be completely static- animating block models just doesn't make sense as you would need to refresh the 16x16x16 mini chunk of rendered terrain every frame, which completely defeats the optimisations that are applied.

In response to rotations (and I assume you mean rotating the block model in increments smaller than 22.5 degrees) I think you would have to implement your own block model generation class... But I could be wrong about all of that. But I guess it depends on what you are trying to do.
