### ISSUE TITLE
When parsing a '%' through ChatComponentTranslation the game crashes

### ISSUE THREAD

**Issue by bl4ckscor3** [MinecraftForge/MinecraftForge#2061]
I noticed this when trying to send a downloadlink to a user via an IRC bridge to Minecraft. After a few seconds the user just quit. After investigating this further, it turned out just parsing a single '%' as a message in ChatComponentTranslation causes a crash with the following crashlog:

http://pastie.org/private/czczjhlfc3fjcsa3afjrmq

Note: This also happens when there is a '%' anywhere in the string, no matter at which position.

**Comment by diesieben07** [comment]
ChatComponentTranslation is passed through String.format and I18n.translate. If you just want to send a String, use ChatComponentText (duh).

**Comment by clienthax** [comment]
I believe if you use a double %% it will give you the percentage sign, we have a similar thing in our lang files
