### ISSUE TITLE
MC-72868 causes invalid moves when there is a block overhead

### ISSUE THREAD

**Issue by Iceee** [MinecraftForge/MinecraftForge#2062]
Mojang fixed this in 1.8.1, and it causes a decent amount of invalid player movements (into blocks).  You can replicate by constructing an area like this and simply sprinting across.

![Example Image](http://puu.sh/jodeg/f385ef3e98.png)

You will notice that in Forge, or any MCP-based client, you will often "glitch" into the block on the far side instead of dropping into the hole or moving over it.  This does not happen in versions before pre-1.8 or after 1.8.1.

I know that fixing Mojang bugs isn't really the job of Forge, but with so many players using it, it would be great for something as fundamental as this to be fixed.  The code change required can be found here:

https://bugs.mojang.com/browse/MC-72868

And here's a direct link:

https://gist.github.com/Panda4994/9d83d261f5edffc3037e/revisions

**Comment by williewillus** [comment]
Forge is already updating to the latest minor release of 1.8 currently, this will get the vanilla fix

**Comment by LexManos** [comment]
Willie is correct, I am in the process of fixing FernFlower so that generics decompile correctly. Once that's done I will be updating to 1.8.8/9

**Comment by RainWarrior** [comment]
Forge is on 1.8.9 now, I assume this is fixed.
