### ISSUE TITLE
SRV domain record bug in Forge?

### ISSUE THREAD

**Issue by diecode** [MinecraftForge/MinecraftForge#2065]
Hi,

When a server using SRV record then I cannot connect to server with Forge. Vanilla Minecraft can connect, Forge cannot with same subdomain ( srv record ) address.

**Comment by LexManos** [comment]
We don't touch any of the code to resolve srv records.
Got a exact server to try?

**Comment by diecode** [comment]
for example: webcraft.mcraft.io

Vanilla connected, Forge: "unknown host"

**Comment by diecode** [comment]
Can you reproduce it?

**Comment by LexManos** [comment]
Ya looking into it, the SRV record is giving us a invalid IP address back.. there shouldn't be anything on our end that is causing this. Will look into it more.

**Comment by diecode** [comment]
No, this is not domain problem. I tested it with other domains and lots of servers. Forge get strange DNS answer but I don't know why..

Try connect to play.legendary.hu with Forge and Vanilla.
You will get an error with Forge ( "If you wish to use IP forwarding..." ) but Vanilla can connect. IP forward enabled in bungeecord config and bungeecord is true in spigot config. Cause this error message the bad dns answer. it is very annoying, lots of people are using Forge, but they cannot connect our servers.

**Comment by LexManos** [comment]
That is not the same issue, that is a bungeecord/spigot being stupid issue that has been fixed in ages. Its up for the servers to update.
