### ISSUE TITLE
[1.8] Custom Minecarts don't render TESR blocks on them

### ISSUE THREAD

**Issue by ganymedes01** [MinecraftForge/MinecraftForge#2066]
Having a custom Minecart that carries a block that is rendered using a TESR doesn't work anymore (it used to on 1.7.10, all you had to do is pass an ItemStack with the block and the default rendered took care of everything).
Now the block isn't rendered at all.

I've traced the issue down to:
``` JAVA
protected void func_180560_a(EntityMinecart minecart, float partialTicks, IBlockState state) {
        GlStateManager.pushMatrix();
        Minecraft.getMinecraft().getBlockRendererDispatcher().renderBlockBrightness(state, minecart.getBrightness(partialTicks));
        GlStateManager.popMatrix();
}
```

The method ``` renderBlockBrightness(...) ``` seems to account for all the vanilla TESRs (so it's still possible to render a minecart with Chests, Ender Chests, Skulls and etc) but not for modded ones.

**Comment by RainWarrior** [comment]
Should be fixed by b175d265b9643faf3408754f6923a8f55f6ee5d3.
