### ISSUE TITLE
SecurityManager permissions

### ISSUE THREAD

**Issue by kashike** [MinecraftForge/MinecraftForge#2067]
https://github.com/MinecraftForge/FML/issues/472
https://github.com/MinecraftForge/FML/issues/593

The [FMLSecurityManager](https://github.com/MinecraftForge/MinecraftForge/blob/master/fml/src/main/java/net/minecraftforge/fml/relauncher/FMLSecurityManager.java) doesn't block anything but system exits, but for some reason (still unknown) it blocks other actions, much as MBean registration (used in mongodb, jedis pools, etc)

Setting the security manager to null fixes the issue for the time being, but is obviously not a permanent solution.

```
SonarBeserk | http://pastebin.com/0takzKms is a lovely stack trace
SonarBeserk | that sources from initing a JedisPool
```

**Comment by LexManos** [comment]
The default security manager blocks it not FML.
If you know what you're dealing with security wise then you can control the security manager all you want. 
However default distribution will leave it as it is.
Also, a message to Sonar, going on IRC and bitching about everything related to minecraft modding and then coming to github to to poke a random thing without doing research is annoying.
