### ISSUE TITLE
Extend Block IDs

### ISSUE THREAD

**Issue by DrZed** [MinecraftForge/MinecraftForge#2070]
I know what it would take LOTS of changes including shifting minimum item ids and stuff, http://puu.sh/jvbHI.txt I know you would have to mess with the save data stuff the world data and lots of other things but at least attempt to look into doing so.

**Comment by diesieben07** [comment]
It's not just about shifting ItemIDs, this would have to change the entire save-format, which Forge is not going to do.

**Comment by Adaptivity** [comment]
Not gonna happen in Forge itself. #1769 #1884
For 1.7.10 use: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2467198-notenoughids-maximum-id-range-exceeded-no-more
For 1.8 use: http://minecraft.curseforge.com/mc-mods/231466-extendedmetadata

**Comment by DrZed** [comment]
Fair enough but can anyone talk to sarge or dinnerbone himself into changing to hashmap for storing blocks and seperate for items? <String, Item> string being the unlocalized name as id.... It'd be easier that way

**Comment by DrZed** [comment]
( ノﾟДﾟ)おはよう
飯絵も再 for dupe was busy with other things >_> early morning to hard to think
さよなら

**Comment by DrZed** [comment]
I decided to yell at the mod author instead of which who made me exceed ids... he uses 1000 himself and no meta is seen anywhere.... so I'll just bother him about shrinking his footprint

**Comment by DrZed** [comment]
ありがとございます　じゃね

**Comment by OvermindDL1** [comment]
How the hell, a thousand?  Gregtech has thousands of blocks and items but uses like 20 or 30 id's total across them all, how did someone manage a thousand?!  What mod is this?

**Comment by DrZed** [comment]
Nevermine 2 - advent of ascention

**Comment by DrZed** [comment]
http://puu.sh/jvMgz.csv Here's the blocks.csv (NEI Block ID Dump)

**Comment by DrZed** [comment]
7th mod in the list Nevermine lines 356 && id 513 to 1234 && ID 1391

**Comment by DrZed** [comment]
so 800 ids

**Comment by OvermindDL1** [comment]
Wow, I found the mod, their coding is fairly.... Surprising in its amount of poor design...

**Comment by DrZed** [comment]
xD If they're open sauce I may think about compressing the id's myself

**Comment by DrZed** [comment]
800+ is not easily acceptable
especially in large modpacks

**Comment by OvermindDL1** [comment]
Not open source, I have a setup that lets me open a mod jar decompiled on the fly in Idea, they have far fewer things than Gregtech and use a lot more id's, very needlessly from what I see.  They also seem to hard bind a few things that may not let them work well in certain cases.  In essence I do not think these people actually know how to mod Minecraft...

**Comment by DrZed** [comment]
You mean cleanly code in general? BTW I love IDEA :D but yeah what you think of my code? :D 
I've been using IDEA for a while I'll never go back to eclipse it's garbage in comparison

**Comment by LexManos** [comment]
Not the place for this discussion.
