### ISSUE TITLE
RenderWorldLastEvent isn't called in a Non-Dev environment.

### ISSUE THREAD

**Issue by me4502** [MinecraftForge/MinecraftForge#2071]
Hi,

In my mod I am doing some rendering in the RenderWorldLastEvent, just using simple OpenGL calls and drawing a line. However, this doesn't work in a non-dev environment. Once it is run inside the standard MC client on the same version of Forge (1502), the event handler isn't called.

**Comment by LexManos** [comment]
You need to provide more details, nothing In forge is dependant on 'dev mode' Patches are patches and applied always.

**Comment by me4502** [comment]
What extra information would assist with the issue the most?

**Comment by LexManos** [comment]
Logs of you running, what mods you have installed. Whatever is telling your game that the EntityRenderer patch isn't applying.
If you look at the code where RenderWorldLastEvent is fired, there are NO conditionals around it.
If that function isnt called then a hell of a lot more then that event would have issues.

**Comment by me4502** [comment]
I erased the .minecraft folder, reinstalled forge, and put in the same mods. It now works.

**Comment by LexManos** [comment]
Thanks, not a forge issue.

**Comment by me4502** [comment]
Yeah, FBOs need to be enabled. Looks like just the way the mc renderer works.
