### ISSUE TITLE
[1.7.10(?) / 1.8] Fluid placement event

### ISSUE THREAD

**Issue by AfterWind** [MinecraftForge/MinecraftForge#2074]
Basically an event that fires whenever a fluid is placed in the world (the source block) by a player.
I need this to easily add protection for any fluids placed near an area that could damage said area.

My question: Is the **idea** of it acceptable? I can make a pull request for it, but I just want to confirm before I do anything.

**Comment by LordIllyohs** [comment]
No new features are being added to 1.7.10

Also couldn't this be done with the block (PlaceEvent)[https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/event/world/BlockEvent.java#L126-L147]

**Comment by AfterWind** [comment]
Alright, just for 1.8 is fine as well.

No, it isn't firing it when right clicking a bucket. Although I know this could be done with PlayerInteractEvent it would be very difficult to do for all fluids since I would need to refer all the possible "bucket" type items which would be incredibly difficult.

**Comment by LexManos** [comment]
Probably just better to just change the fluids to fire the place event like normal blocks, blocks are blocks whether they be fluids or not.

**Comment by AfterWind** [comment]
Alright, will do that. Does that mean it can be implemented in 1.7.10?

**Comment by mezz** [comment]
Any update on this @AfterWind ?
New features or fixes like this are only being accepted on the 1.11 branch.
