### ISSUE TITLE
Enchanted creative tab icon looks weird

### ISSUE THREAD

**Issue by Adaptivity** [MinecraftForge/MinecraftForge#2075]
@tterrag1098 stated that this vanilla/Forge bug. So, if it's even vanilla bug it should be fixable on Forge end. For more information: https://github.com/SleepyTrousers/EnderIO/issues/2710
Can't check if it occurs on 1.8 since I don't know if there are exist mod for 1.8 with enchanted creative tab icon.
Forge: 1492
Any mod with enchanted creative tab icon (Witchery or Ender IO for example)
Screenshot: http://i.imgur.com/RGa5DKU.jpg

**Comment by LexManos** [comment]
3 levels of indirection to see your issue is annoying -.-
Pretty sure this was fixed a while back it may of broke again. Its just a matter of the blending function being diabled/changed by the enchantment renderer.

**Comment by Adaptivity** [comment]
I've moved information here. If someone can confirm that this was fixed in 1.8 I'll immediately close this. The reason I've reported it because there are was no previously reported issues about it.

**Comment by LexManos** [comment]
Doesnt seem to be an issue on current versions.
