### ISSUE TITLE
[1.8] LivingSpawnEvent.java weirdness

### ISSUE THREAD

**Issue by tyronx** [MinecraftForge/MinecraftForge#2079]
The source comments do not seem to correctly reflect the event behaviors.

At line 9: "LivingSpawnEvent is fired whenever a living Entity is spawned"

In Forge #1412 it is also fired **before** the entity is checked for a valid spawning spot via entityliving.getCanSpawnHere(). See SpawnerAnimals.class:

                                                        Result canSpawn = ForgeEventFactory.canEntitySpawn(entityliving, p_77192_1_, f, l2, f1);
                                                        if (canSpawn == Result.ALLOW || (canSpawn == Result.DEFAULT && (entityliving.getCanSpawnHere() && entityliving.handleLavaMovement())))

**Second issue at Line 55-57:** 
     * SpecialSpawn is fired when an Entity is to be spawned from a mob spawner.<br>
     * This event is fired whenever an Entity is spawned in a mob spawner in<br>
     * SpawnerAnimals#findChunksForSpawning(WorldServer, boolean, boolean, boolean).<br>

What has SpawnerAnimals.class to do with mob spawners? Mob spawners have their own spawning code in their TileEntity code from extending MobSpawnerBaseLogin.class

If I read the source correctly, SpecialSpawn is really what LivingSpawnEvent is supposed to do.
According to the code it also does not look like the event cancelation would work.

**Comment by diesieben07** [comment]
So true. And this is not the only place. The event documentation that was merged a long time ago is wrong in a lot of places, misleading in many others and unhelpful pretty much always.

**Comment by williewillus** [comment]
also, a lot of these class names, like SpawnerAnimals, have been there for years in MCP, they might not be accurate to what the class does now

**Comment by diesieben07** [comment]
He's still right. Neither of these events have anything to do with mob-spawners.

**Comment by cpw** [comment]
That's probably a functional change in MC. The animal spawner used to do both normal and mob spawner handling. It probably changed in the recent past. (1.7?)
