### ISSUE TITLE
FMLNetworkHandler.openGui crashes when fed a FakePlayer

### ISSUE THREAD

**Issue by LyraelRayne** [MinecraftForge/MinecraftForge#2082]
If a mod calls FMLNetworkHandler.openGui(...) to open a GUI (for example as a result of a onBlockActivated call) but the player who activated the block is a FakePlayer, the client will crash with 

http://pastebin.com/xMQPSFpa

I made a minimal test mod which will replicate the crash. Simply place a chest, look at it and press "F"
http://pastebin.com/2vtxZQ3E

It looks like Forge is expecting every EntityPlayerMP to have a working NetManager, but FakePlayers don't have one at all. 

This may be avoided by checking whether the player is a FakePlayer but modders probably shouldn't need to know what kind of EntityPlayer they're dealing with nor should they need to know what kinds of EntityPlayer the method supports.

**Comment by LexManos** [comment]
This has been fixed in like 30 different places it should be fine. However, let me know if it's reproducible in 1.8.

**Comment by LyraelRayne** [comment]
I managed to get the same crash in the "latest" Forge forge-1.8-11.14.3.1502-src using this example mod source http://pastebin.com/SV1uvpK4.

This can be fixed by either checking for FakePlayer in FMLNetworkHandler (add it to  if (entityPlayer instanceof EntityPlayerMP)) or by doing a bunch of null guards in FMLOutboundHandler.

`NetworkDispatcher dispatcher = player == null ? null : player.playerNetServerHandler.netManager.channel().attr(NetworkDispatcher.FML_DISPATCHER).get();`

There are a lot of opportunities for null here. In the normal FakePlayer the playerNetServerHandler is null. In CoFH's version of FakePlayer the channel is null so you'd need to check for that too if you don't want to irritate the Thermal Expansion crowd ;)

**Comment by LyraelRayne** [comment]
Will the fix for this ever find its way into 1.7?
