### ISSUE TITLE
Bug in NetworkRegistry class

### ISSUE THREAD

**Issue by Vorquel** [MinecraftForge/MinecraftForge#2084]
The newChannel methods (lines 140ish and 190ish) do not properly check if the name is already in the channels map. Rather than looking at the map of Strings to FML Embedded Channels, it looks at the map of sides to the previous map. This allows duplicate names to overwrite previously made channels.

**Comment by williewillus** [comment]
To elaborate. line 141 of ```NetworkRegistry.newChannel```
Checks ```channel.containsKey(name)```, but channle is an EnumMap<Side, Map<String, Channel>>.
Should instead be something like ```channel.get(someSide).containsKey(name)```

**Comment by Vorquel** [comment]
I made this https://github.com/Vorquel/Network-Test to give an example of how this class fails to protect against duplicates.

**Comment by cpw** [comment]
Heh. Nice catch. Feel free to PR the check of both sides ;-)

**Comment by diesieben07** [comment]
So PRs against the FML code work again?
