### ISSUE TITLE
Forge Server Issue: Security Exception when Server Watchdog Tries to Close Server

### ISSUE THREAD

**Issue by hsyyid** [MinecraftForge/MinecraftForge#2088]
Forge/FML blocks the Minecraft Server Watchdog from closing the server when it's suspected to have crashed, ex. ticks taking too long. And throws a Security Exception rather than shutting down the server.

**Comment by LordIllyohs** [comment]
Logs

**Comment by hsyyid** [comment]
I'd have to get a server to crash. I know this happens though. Talked in IRC they said make an issue

**Comment by heldplayer** [comment]
Then the people who have had the crash happen should have made the issue.

**Comment by simon816** [comment]
I made an issue on FML a while ago, https://github.com/MinecraftForge/FML/issues/584

**Comment by cpw** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/4315637f759ad0b0069dc950cfceda7eed9c5b52
