### ISSUE TITLE
Request - getModList for all plattforms

### ISSUE THREAD

**Issue by Chaos234** [MinecraftForge/MinecraftForge#2092]
Hello,

I asked here https://github.com/MinecraftForge/FML/issues/669 why I can't get any Mods from a modded client (e. g. forge) through bungeecourt but I forgotten to tell that we are using spigot as mc-server so we can't use getModList() from the bungeecourt-api because we don't have a forge server.

This is not good because anybody can connect with any mod and we can't do anything against this. So I ask you to provide a funktion/methode which can be used by the dev's from the bungecourt team to get the same information with bukkit/spigot/sponge/...

I personaly don't have anything against mods but some mods are bad for servers like WorldDownload-Mods. Well, some mods need to be also installed on the servers side but many other mods don't.

I hope that this will be possible :)

**Comment by LexManos** [comment]
BungeeCord knows how to do it.
Your intention are futile tho. You can't write a server side blacklist for mods.
And all of the 'Mods that require server side' already have the support in place and will error out the client when they are missing on the server.
You can go look at our packet classes if you want more details, but without a Forge server you're gunna have to reimplement the entire Forge handshake protocol so you have to go do your research we don't have a magic 'use this code and poof' for you.

**Comment by Chaos234** [comment]
Why should I can't write a server side blakclist for mods?
After the Handshake I can extract the mod's name and then compare this 
with a list. If the mod is listed as "unwanted" the player is kicked 
instantly.
And I duno what the problem is, to send the modlist directly to the 
server regardless of the used server jar. Is it so hard to write it?

Am 20.08.2015 um 20:32 schrieb LexManos:

**Comment by LexManos** [comment]
Because the client will just tell you that it doesn't have the mod you want to blacklist.

**Comment by Chaos234** [comment]
Well, that's bad ... seems to be to complicated. Well, then I've to look 
at the Handshake Protocol on my own to get what I want/need.

Am 21.08.2015 um 00:29 schrieb LexManos:

**Comment by diesieben07** [comment]
It's impossible to do this, you can "look at it" all you want. If you ask somebody "are you lying" you have no idea if they are really lying or not. This is the same thing.

**Comment by Chaos234** [comment]
Thats true ...

Am 21.08.2015 um 00:36 schrieb diesieben07:

**Comment by liach** [comment]
getting the mod list from `@NetworkCheckHandler` method?

**Comment by OvermindDL1** [comment]
I could write a coremod or just alter local forge code to report that I have no mods, almost trivial to do, server detection of mods is an entirely futal endeavor.
