### ISSUE TITLE
IItemRenderer

### ISSUE THREAD

**Issue by clienthax** [MinecraftForge/MinecraftForge#2095]
Is it possible to get this re implemented in 1.8,
Our model system is not suited for baking (has mesh deformation) for the models
and without it we can not render models as items and have to rely on the normal item sprite instead

**Comment by williewillus** [comment]
IItemRenderers as we know it aren't making a return, but we were promised something that was at least as flexible and it hasn't happened yet D:

Smartmodels are fine for most cases but if you need a highly dynamic model where the number of different states that appears is not controllable then we need something more flexible

**Comment by lumien231** [comment]
williewillus you don't have to create all possible models beforehand, you can just create new ones at runtime.

**Comment by williewillus** [comment]
This can be closed as we now have a stopgap until 1.9+
