### ISSUE TITLE
Font color on Splash Progress screen always black

### ISSUE THREAD

**Issue by nmakoto** [MinecraftForge/MinecraftForge#2096]
No matter what font color is in splash.properties - it's always black on loading process.

**Comment by ghost** [comment]
And how long we have to wait for this issue to be resolved?

**Comment by mezz** [comment]
This appears to be working just fine in 1.11.2
![java_2017-04-27_15-39-06](https://cloud.githubusercontent.com/assets/916092/25507247/b55f5716-2b5f-11e7-99f5-f68e1ab2e62f.png)

**Comment by mezz** [comment]
Let me know if you're still having issues and I can reopen this.
