### ISSUE TITLE
IUnlistedProperty does not support nested generics

### ISSUE THREAD

**Issue by tterrag1098** [MinecraftForge/MinecraftForge#2097]
Take for instance an `IUnlistedProperty<List<Integer>>` (yes I know this could be `Integer[]` but it's a good simple case). The `getType()` method of `IUnlistedProperty` returns `Class<T>`. There is no way to get a `Class<List<Integer>>` as that's not how class objects work. Making the return type `Class<? extends T>` allows you to cast `Class<List>` to `Class<? extends List<Integer>>`.

**Comment by asiekierka** [comment]
I think IUnlistedProperty will go away in 1.9 due to the fact Models get the IBlockAccess/IBlockState directly there.

Have you considered making a wrapper object?

**Comment by RainWarrior** [comment]
Workaround is to do (Class<List<Integer>>)(Class<?>)List.class.

**Comment by liach** [comment]
Are unlisted properties going away in 1.13?

**Comment by williewillus** [comment]
no, they are still needed for their original purpose: when all possible values of a property cannot be predetermined ahead of time. 

vanilla IBlockState generate all of their possible variants on startup, and unlisted props/extended states are needed when that is not possible (either the state space is too large or all variants are unknown at startup)

**Comment by liach** [comment]
Can `IUnlistedProperty` use `TypeToken` to store its type instead?

**Comment by liach** [comment]
we should make the unlisted property simply return a type or a type token.
