### ISSUE TITLE
Add md5sums to mod info printout

### ISSUE THREAD

**Issue by clienthax** [MinecraftForge/MinecraftForge#2098]
Usefull for pinpointing exact versions when people rename files + can instantly see if a file is corrupted

**Comment by matthewprenger** [comment]
:+1: This sounds very useful. Not sure how much load time would be affected by hashing every file though.

**Comment by clienthax** [comment]
Takes about half a second to md5sum pixelmon (250mb~) so i don't see it effecting loading time too badly

**Comment by Lunatrius** [comment]
`md5deep64 -lr mods/` on 145 mods finishes in 0.594s (188MiB total).

**Comment by LexManos** [comment]
It'd be interesting, Dont quite like having that much spammed in the list, I trimmed down the print to be smaller as is.
If you care about verification, then just sign your jar. Signatures are already validated.
And it'd address the corrupt downloads you're talking about.

**Comment by clienthax** [comment]
@LexManos Our jar is signed yet fml says no signature found?
```
[02:27:26] [Client thread/DEBUG] [FML/]:  	Missing Signatures:
[02:27:26] [Client thread/DEBUG] [FML/]: 		mcp	(Minecraft Coder Pack	9.05)	minecraft.jar
[02:27:26] [Client thread/DEBUG] [FML/]: 		pixelmon	(Pixelmon	4.0.7)	Pixelmon-1.8-4.0.7-universal.jar
```

```
jarsigner -verify Pixelmon-1.8-4.0.7-universal.jar
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
jar verified.

Warning:
This jar contains entries whose signer certificate will expire within six months.
This jar contains signatures that does not include a timestamp. Without a timestamp, users may not be able to validate this jar after the signer certificate's expiration date (2016-01-12) or after any future revocation date.

Re-run with the -verbose and -certs options for more details.
```

**Comment by LexManos** [comment]
Did you specify your signature in your mod file?

**Comment by clienthax** [comment]
Nope, how do we go about that?

**Comment by matthewprenger** [comment]
Its a field in the `@Mod`. certificateFingerprint IIRC

**Comment by cpw** [comment]
It verifies that the cert used to sign the jar matches the code. You get an event fired if not. It's not unhackable, but it helps, IMO..

**Comment by mezz** [comment]
I think jar signing is definitely the solution for this. Adding another fingerprint feature feels redundant.
