### ISSUE TITLE
Fluid registry errors

### ISSUE THREAD

**Issue by Allalous** [MinecraftForge/MinecraftForge#2099]
Me and my friends play on a custom modpack and we have been getting fatal errors for a few days now. The fluid that is named changes whenever we get the fatal error so no 2 people get the same fluid at the same time

http://pastebin.com/SDw13mza

**Comment by Spartan322** [comment]
pretty sure your suppose to report this to the modpack author (or if you can locate the specific problematic mod, the author of that)
