### ISSUE TITLE
DefaultArtifactVersion.toString Causes a StackOverflow

### ISSUE THREAD

**Issue by Nerdpie** [MinecraftForge/MinecraftForge#2101]
Encountered in a recent [build of Tails] (https://github.com/kihira/Tails/blob/ecf9f465aed0952609a4b2b9157c8097010b0e43/src/main/java/kihira/tails/common/Tails.java#L85); reported on Tails' [side] (https://github.com/kihira/Tails/issues/55).

Re-posted from https://github.com/MinecraftForge/FML/issues/670

**Comment by cpw** [comment]
You shouldn't be using that method. It's internal to FML/Forge. Use ```getDisplayVersion()```
