### ISSUE TITLE
Add more methods to IRecipe interface

### ISSUE THREAD

**Issue by CreativeMD** [MinecraftForge/MinecraftForge#2104]
The IRecipe interface contains 4 methods which are handling everything necessary,
but for some uses these aren't enough. There is no way to get the needed input without having to handle each recipe type (also modd added once). If we add two more methods to IRecipe interface we could solve all those problems without any big issue:
public ItemStack[] getInput();
Could may be changed from ItemStack[] to Object[].

public int getWidth();
There are some issues displaying recipes because you don't know if the recipe size 4 is 1:3 or 2:2 or 3:1, this would solve those problems.

**Comment by laci200270** [comment]
But this would break old mods

**Comment by CreativeMD** [comment]
Indeed, but it's not really a big change, could be fixed within secs.
It doesn't has to be added to 1.7 or 1.8, but it would be really helpful to add it in 1.9

**Comment by diesieben07** [comment]
Except that's not how all recipes work. You don't always know the exact input. E.g. OreDicitionary recipes, they have many possible inputs per recipe.

**Comment by CreativeMD** [comment]
Yes, that i suggest to change ItemStack[] to Object[]

**Comment by diesieben07** [comment]
And then what? Hypothetical example: My Mod adds a recipe from all things whose name ends with "x" to diamond. Stupid example, yes, but it demonstrates the point. What do I return from getInput.

**Comment by CreativeMD** [comment]
It's the same thing as getRecipeOutput in some cases the "author" has to give an example of what could be crafted or just return null.

**Comment by LexManos** [comment]
Adding to an existing interface is not a option it breaks vanilla. But a opt-in system to expoe additional data may work.

**Comment by CreativeMD** [comment]
I see no problem in "breaking" vanilla, but ok.

I would suggest to add a new interface called IRecipeInfo containing these two methods and extending IRecipe.
This should be implemented by ShapedOre/ShapelessOre recipe (the forge recipes).
Also i would change
GameRegistry.addRecipe(IRecipe) to GameRegistry.addRecipe(IRecipeInfo) to force the people to use the new interface.

**Comment by chibill** [comment]
How about no. As that is still a mod breaking change....

**Comment by CreativeMD** [comment]
I suggested to add it into 1.9

**Comment by liach** [comment]
Or add it when minecraft become using java 8.

**Comment by LexManos** [comment]
Ya.. you change a interface, mods who dont update to the new interface crash. Hence breaking shit. Forcing this change is not going to happen.

**Comment by AEnterprise** [comment]
maybe making an IRecipev2 interface is an option? that could extend the current interface and both could be merged in the migration to another MC version?

**Comment by CreativeMD** [comment]
Yes, that is why i suggested add this within the 1.9 update.

**Comment by ganymedes01** [comment]
Not all recipes have set inputs.
This change would limit the existing system...

**Comment by CreativeMD** [comment]
It's the same as getRecipeOutput, it's never used, but it's great for modders to get an "example" result and there is no problem if it's null because of reasons.
In conclusion it doesn't limit anything, but it would be a great opportunity to get the input of "almost" every recipe.

**Comment by CreativeMD** [comment]
Not really, there are a lot of mods which are adding there own recipe without extending one of these.
Also i can't get the width out of a ShapedOreRecipe, because it's private :(

**Comment by ganymedes01** [comment]
> Not really, there are a lot of mods which are adding there own recipe without extending one of these.

I wouldn't say a lot of mods do it, but it's certainly a non-zero amount. But again, the vast majority of recipes extend those 4 classes.

>Also i can't get the width out of a ShapedOreRecipe, because it's private :(

Well you can't get the width of anything using your suggested method =P How you would find out the width from just an array of ItemStacks ?Also, how about using reflection?

**Comment by CreativeMD** [comment]
It's not really a non zero amount for example IC2 uses own recipe classes

You can't calculate the width with only knowing the length of an array. That's way a recipe should have a public getter method for this. ShapedOreRecipe is missing that.
yes i can use reflections, but we it be a problem to implement something like this 1.9?
It wouldn't be that big kind of change, because only a certainly non-zero amount uses other recipes :P

**Comment by heldplayer** [comment]
Just curious, but why do you need the width?

**Comment by CreativeMD** [comment]
I only get the length of a recipe. If i want to fill a 3x3 grid i have to know the width & height.
The length of 4 could be 2x2, 1x3, 3x1, therefore i need to know the width/height (i only need one of them).

**Comment by Spartan322** [comment]
Why do we need to add to a vanilla interface (and break it)? It's not very hard to add a non-vanilla-breaking interface if anyone more then you actually wants it.

**Comment by CreativeMD** [comment]
Why does nobody read the discussion :(
If you want to say something please read the whole conversation to know what is already been said.

Summary:
I would suggest to add a new interface called IRecipeInfo extending IRecipe.
The interface brings to more methods:
public Object[] getInput() <-- May be null or empty if it's not possible to give an input
public int getWidth()
ShapelessOreRecipe and ShapedOreRecipe should implement it.
Change GameRegistry.addRecipe(IRecipe) to GameRegistry.addRecipe(IRecipeInfo).
Yes it's mod breaking and that's why i suggest to implement it once forge updates to 1.9.

I don't think i'm the only person, NEI, CraftGuide, EasyCrafting and maybe some more could use this feature. This new interface would give new possibilities for mods which are focusing crafting.
A autohand crafting mod (similar to factorio) or maybe even more ?
I shouldn't get to excited, but i think it's worth an implementation.

**Comment by Spartan322** [comment]
Except we don't like purposely breaking mods, and it seems people especially hate it when Mojang does that, so we need to keep consistency and not just break something for a feature (especially when there are much better ways of doing this, seriously, we don't need to break the system for this).

**Comment by heldplayer** [comment]
Yes but, _why_ do you need the _width_?

**Comment by CreativeMD** [comment]
@Spartan322 how can i break mods for 1.9, they are already broken. This feature would bother almost nobody except of some mods which are using there own recipes without extending one of the vanilla/forge ones. It would be done within seconds.
If there is a better way to than please tell me.

@heldplayer i don't know how to explain it in other words, but in order to display the input of a recipe you have to know the height or the width of it.
Example: The recipe of a hoe is 2x3 and has a length of 6,
the given input would be: new ItemStack[]{stone, stone, null, stick, null, stick}.
In order to display it correctly you have to know whether it is 3x2 or 2x3.
