### ISSUE TITLE
gradlew setupCIWorkspace build causes errors.

### ISSUE THREAD

**Issue by LordMastodon** [MinecraftForge/MinecraftForge#2105]
Running gradlew setupCIWorkspace build in 1506 causes errors both on a normal computer and on a dedicated Drone server. Here is a link to the full error report from the Drone server: http://pastebin.com/zM62QXwJ. Here is a link to the repository containing the build.gradle file: http://github.com/LordMastodon/Miscal. Side note: I have added a task into the build.gradle called "version" which creates a .txt file in the output with the version number that my mod can download and check for new versions, but testing with and without that task in the command does not seem to affect anything. I'm not sure if this is a bug or an unimplemented feature, but diesieben07 recommended I post a bug report, so here I am. Thank you in advance!

P.S.

It's also worth noting that the Drone server runs on Ubuntu and my computer runs on Windows, making it impossible to fully recreate the situation on my computer, however the crash report seems exactly the same, so I'm pretty sure there's no conflict there.

**Comment by luacs1998** [comment]
https://github.com/MinecraftForge/ForgeGradle/issues

**Comment by LordMastodon** [comment]
Ah. OK, thanks.
