### ISSUE TITLE
Full localization support

### ISSUE THREAD

**Issue by Adaptivity** [MinecraftForge/MinecraftForge#2106]
List of stuff to localize:
GuiModList (lines: 158-159, 287, 361-362, 365, 367-369, 410-413)
GuiWrongMinecraft (lines: 38-45)
GuiSortingProblem (lines: 27-41)
GuiSlotModList lines 84 and 90
GuiOldSaveLoadConfirm (lines 39-42)
GuiModsMissingForServer (lines 50-54)
GuiModsMissing lines (42-61)
GuiModOptionList lines (42-44)
GuiDupesFound lines (44-48)
GuiBackupFailed (lines 50-52)
GuiAccessDenied (lines 50-52)

Really hope to see this in the next PRs merge.

Moved from here: https://github.com/MinecraftForge/FML/issues/438

**Comment by Adaptivity** [comment]
Can I get this in 1.8.8 update? @cpw @LexManos

**Comment by cpw** [comment]
This doesn't seem to be a pull request, so I suspect not. It's not a high priority, fml has never been localized to date.. It will happen, eventually.

**Comment by Adaptivity** [comment]
@cpw I've completed most part of localization support. Please, give me some feedback about it here before I PR it: https://github.com/Adaptivity/MinecraftForge/commit/53334d6de25a7fb0ebb38022d5742a6ec2b97737
Also, can you point me to where [these](http://i.imgur.com/SOLjVEv.jpg) and [this](http://i.imgur.com/o9JKzyJ.jpg) lines located in code? I can't find them maybe I just blind :)

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fml/common/LoaderState.java#L95

**Comment by cpw** [comment]
Yeah, please don't localize the log files, that shit just makes it harder to debug. On screen messages are fine to localize however.

**Comment by Adaptivity** [comment]
@LexManos got it, it's not worth localizing this then.
Here last changes which I want to PR: https://github.com/Adaptivity/MinecraftForge/commit/4dd74a172a450f791d044879975f173c8754825c
I'm need to know yours and @cpw's opinion about it. Please, review my changes and let me know if I need to change something.

**Comment by Lunatrius** [comment]
`I18n` is a client only class, you'll probably want to use `StatCollector` instead in the server/common classes.

**Comment by cpw** [comment]
Please read and understand what @lunatrius is saying. Localized strings that are just appends in source rather than format strings, are a complete waste of everyone's time..

**Comment by Adaptivity** [comment]
@Lunatrius ok, half-done. Where exactly I should use StatCollector? Just in FMLCommonHandler?
New commit here: https://github.com/Adaptivity/MinecraftForge/commit/f2d8877c429054c17e2d786463cc876fad88c11c

**Comment by Lunatrius** [comment]
Yeah, `FMLCommonHandler` would be the only class, the other classes are all part of the `client` package.

Instead of linking individual commits you can use [this](https://github.com/MinecraftForge/MinecraftForge/compare/1.8.8...Adaptivity:fullocalizationsupport) link to compare everything at once.

---

The following is just a *suggestion*: it might not be a bad idea to get a helper method into Forge that can translate multi-line strings like `fml.error.oldSaveLoadConfirm.X`. The following is just pseudocode of what some people used in the past:
```java
public static String[] translateMultilineEntry(String base) {
    int size = Integer.parseInt(StatCollector.format(base + ".size"));
    String[] ret = new String[size];
    for (int i = 0; i < size; i++) {
        ret[i] = StatCollector.format(base + "." + i);
    }
}
```

**Comment by Adaptivity** [comment]
@Lunatrius changed to StatCollector in FMLCommonHandler. The problem is now that changes for GuiModList.java which I made this morning are not working (%s tags won't display any text in GUI). I have no time to find solution for this now (maybe tomorrow), if you have any clues, please share them with me. You also can send me a PR if you have some time for this.

**Comment by Adaptivity** [comment]
Still relevant as I can see but low prio.
