### ISSUE TITLE
Add an additional System Property to disable new loading screen.

### ISSUE THREAD

**Issue by SonarBeserk** [MinecraftForge/MinecraftForge#2107]
I wish to disable the new forge loading screen without needing to manually edit a file. I would like for it to be possible to disable its use in favor of a custom loading screen. However there is not a way to fully disable it without messing with a file and hoping users wont change it back.

**Comment by LexManos** [comment]
No.

**Comment by SonarBeserk** [comment]
What is wrong with the ability to do that? I wish to simple be able to turn it off using an access transformer. I like the new loader but I need to make the look consistent.

**Comment by williewillus** [comment]
That sounds way more complicated than it needs to be, what's wrong with simply writing to a text file?....

**Comment by SonarBeserk** [comment]
Due to a property being cleaner. The intent is why you drop in the mod im working on, it does its own loading with custom loading screens. I would like to simply make it possible to disable it without a file and without creating a file. I want to seamlessly disable it and from code.

**Comment by laci200270** [comment]
Reflection or asm maybe?

**Comment by SonarBeserk** [comment]
The security manager has been catching my attempts to play with reflection. It also has to run as a coremod and stop the menu from ever appearing.

**Comment by laci200270** [comment]
Asm?

**Comment by liach** [comment]
@SonarBeserk You can change the file `config/splash.properties` with your own coremod, instead of hacking into forge source.

**Comment by SonarBeserk** [comment]
Yes but I need to override user changes. How would you propose doing so?

**Comment by Illyohs** [comment]
I still don't see how this is a proper use case. Why do you **need** change forges with your own besides a "mines prettier" argument and why override the the users choice? IIRC you can change the look of it with a resource pack

**Comment by SonarBeserk** [comment]
The intent is basically to provide a totally overhauled client at least by ascetic looks. It is also a thing of I have no control of the Forge Loading menu past the file. And ignoring the user's choice in favor and need of the custom menus. I dont wish to have two menus pop up due to someone messing with a setting,

**Comment by jimcarreer** [comment]
Sounds like an eye twitchy OCD use case.

**Comment by SonarBeserk** [comment]
Would also have the side effect of mods with known incompatibilities with the new menu to auto disable it so they dont have to add a note to do so manually. I also am in favor of allowing settings to be changed within code instead of always by editing a file.

**Comment by heldplayer** [comment]
Allowing regular mods to disable it because they have incompatibilities endorses modders to hide the problem rather than actually fixing it. However letting coremods disable it on the other hand might be acceptable.

It's a fairly specific usecase though and prone to abuse by mods simply wanting to avoid fixing their problems.

**Comment by SonarBeserk** [comment]
Could implement it without fanfare in that case then, leaving an option for those that need it that takes a bit of searching to avoid just anyone messing with it.

**Comment by LexManos** [comment]
We will never condone coremodding internal forge classes and mechanics. The look and feel of the loading screen can be configured. You do not need to create a new system for something that is in place. If you wish for more control or options then that can be addressed but a "screw you guys i'll just make my own shit" is not acceptible on this project.
