### ISSUE TITLE
Adding an onItemRendered event

### ISSUE THREAD

**Issue by ItsAMysterious** [MinecraftForge/MinecraftForge#2109]
It would be good if you could add in an event that is called when the item in the players hand or items in general are rendered, so that you can cancel that event and render a custom model e.g. obj model instead of the actual item model.

**Comment by RainWarrior** [comment]
Use the model system directly instead of bypassing it.

**Comment by ItsAMysterious** [comment]
Yea, i tried that, but loading up B3D models is really complicated atm, can't you make it like the obj stuff with an IModelCustom that loads from a ResourceLocation and just define that the block is rendered by a custom renderer in the .json file?

**Comment by williewillus** [comment]
that's almost literally what the forge blockstate jsons are...

**Comment by ItsAMysterious** [comment]
Well, yes but they aren't the best idea forge had, yes theys are usefull, but it is really annoying that youll have to create them for every file. If you are interested, im working on a powerful generator(even in code as plugin) if you want i can contact you if its finished

**Comment by williewillus** [comment]
you can literally do what you're trying to remake using smartmodels and your own bakedquads in code. No JSON at all.
Don't reinvent the wheel...

**Comment by LexManos** [comment]
Its also important to note that you SHOULD create a json for every block, at the very least the blockstates so that external people dont need to disect your code to figure out what the hell youre doing.

There is NO reason besides being lazy and not wanting to take the 10 seconds to create the json to not do it.
And tons of reasons to do it.
Stop being lazy its a one time thing, and most jsons can be 1 fkin line.

**Comment by ItsAMysterious** [comment]
Yes, i do create them for normal blocks and stuff, now how do i make this smartmodelthing? I can't find any tutorials on that?

**Comment by laci200270** [comment]
You should look at TheGreyGhost/MinecraftByExample

**Comment by ItsAMysterious** [comment]
Ah okay

**Comment by ItsAMysterious** [comment]
Also i think i detected a bug where do i report it?

**Comment by Spartan322** [comment]
Either search for a similar/same issue of the bug, or post a new issue (only if it relates to Forge, and isn't you hacking up something wacky and despised)
