### ISSUE TITLE
FMLNetworkEvent.ServerDisconnectionFromClientEvent doesn't get called under normal circumstances

### ISSUE THREAD

**Issue by heldplayer** [MinecraftForge/MinecraftForge#2110]
Tested on Minecraft 1.8 forge 11.14.1.1334 as well as Minecraft 1.7.10 forge 10.13.4.1448.

The [ServerDisconnectionFromClientEvent](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fml/common/network/FMLNetworkEvent.java#L62) never gets called on a dedicated server instance or internal server instance if a player disconnects by pressing the disconnect button on the menu.
The event does get called however when the client gets disconnected by the server (if the client times out, or if the client gets kicked from the server)

The relevant code that is supposed to call the event is located [here](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java#L446-L474).

Adding breakpoints to the method to test this support the findings (the breakpoints get triggered on the client only if the client disconnects, etc.)

**Comment by cpw** [comment]
You know that's netty right? Netty code calls that method (both of them, I believe). Makes me wonder what the client is doing..

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]

**Comment by LexManos** [comment]
So did a small lookup on this the close method we are overriding is only called from the OUTBOUND handler which means it only firing on the client side makes sense.
Apparently the proper way to do this is to add a listener to the closeFuture as described here:
http://stackoverflow.com/questions/8785949/netty-channel-closed-detection
But testing that again only has it called on the client side. So i'm going to look into this more mater.
