### ISSUE TITLE
OreDictionaryStack

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#2111]
Apparently it's easier to add a hack to ItemStacks (or ASM other mods, which's slightly harder than simply doing the hack) than to get mods to do recipes (read: non-crafting-table recipes) properly.

It'll also encourage more mods to not register their ore items if another mod already registered them.

**Comment by diesieben07** [comment]
> It'll also encourage more mods to not register their ore items if another mod already registered them.

That is _not_ the purpose of the OreDict.

**Comment by SoniEx2** [comment]
It basically does 2 things:

1. Makes it so _all_ recipes (mainly e.g. furnace recipes or <insert some mod's crafting system here: IC2 Macerator, Mariculture Vat, etc> support ore dictionary items.
2. Lets the thing with only a single mod registering ore items work. So e.g. you have IC2 ores, you remove IC2 and install Thermal Expansion, all your IC2 ores become TE ores if they were OreDictionaryStacks.

It would be opt-in, i.e. you'd have to explicit specify you want an OreDictionaryStack instead of an ItemStack. (this'd probably be done by specifying an ore dict string while constructing an ItemStack. it would use an ore dict item for the ItemStack's Item, but would serialize the ore dict string instead of the Item)

If the mod *manually* compares the ItemStacks then it wouldn't work... but w/e.

**Comment by diesieben07** [comment]
This sounds like a horribly inconsistent solution to me.

**Comment by jk-5** [comment]
Just throwing these in here

https://github.com/MinecraftForge/MinecraftForge/pull/485
https://github.com/MinecraftForge/MinecraftForge/pull/553
https://github.com/MinecraftForge/MinecraftForge/pull/578

**Comment by SoniEx2** [comment]
The 2. is most useful for the end user. The 1. is most useful for mod makers.

**Comment by diesieben07** [comment]
The first thing that this breaks with is the vanilla furnace. Which really tells you a lot already...

**Comment by SoniEx2** [comment]
It doesn't break anything, only changes how it works.

**Comment by diesieben07** [comment]
yes, and it does so in a very inconsistent way. You have no way of predicting which mods check equality with things like `getItem() == ...` and which don't.
