### ISSUE TITLE
EntityRegistry.addSpawn creates duplicate entry

### ISSUE THREAD

**Issue by Blargerist** [MinecraftForge/MinecraftForge#2112]
Hopefully I'm on the correct repo this time....

Noticed this on 1.7.10. Method appears to be exactly the same on master branch.
Method: https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fml/common/registry/EntityRegistry.java#L311

During the method, if while searching the spawns list it finds an already existing entry for the mob, it still adds a brand new entry to the list.

Checked to be sure by adding an entry for EntityDragon, printing the list, adding another entry for the EntityDragon and printing a second time.

Result:
EntitySpider(4-4):100
EntityZombie(4-4):100
EntitySkeleton(4-4):100
EntitySlime(4-4):100
EntityEnderman(1-4):10
EntityWitch(1-1):5
EntityDragon*(1-5):100

EntitySpider(4-4):100
EntityZombie(4-4):100
EntitySkeleton(4-4):100
EntitySlime(4-4):100
EntityEnderman(1-4):10
EntityWitch(1-1):5
EntityDragon(2-10):5
EntityDragon(2-10):5

As you can see, two entries for EntityDragon in the list.

**Comment by Corosauce** [comment]
Noticed this too while making use of the addSpawn code, could probably use a boolean to check if it found an entry then prevent adding a second spawn entry of that same entity class.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]
