### ISSUE TITLE
Mod keybinding config merges with vanilla config; gets deleted upon loading vanilla game

### ISSUE THREAD

**Issue by Xemiru** [MinecraftForge/MinecraftForge#2119]
I'm still sort of in an earlier version for 1.7.10, so I'm not exactly sure if this is fixed yet. Pretty much just a very minor enhancement; feel free to ignore.

tl;dr first if you don't want that paragraph of use case and observation: *vanilla mc pretty much deletes forge-defined (or anything-not-vanilla-defined) settings saved in options.txt, can we separate them?*

I like to toggle between vanilla and modded Minecraft setups to play some vanilla servers without much issues like performance and stuffs (the launcher helps organize this a lot). This wasn't a problem before the launcher, since I always just replaced my .minecraft folder with an archived version of my modded files. Now, since I don't replace all my files anymore and just toggle between, both versions share files.

Mod keybindings seem to be saved inside vanilla's options.txt in the root folder. As far as I'm concerned, looking from what Minecraft does (nothing internal, just observations), Minecraft seems to like to overwrite that options.txt file completely, by what seems to be just deleting the old file and writing a new one with all the options it recognizes. Evidently, any other modifications to the file, i.e. those mods' keybindings, disappear. Can we separate the two to prevent this from happening?

**Comment by GotoLink** [comment]
You can set each profile directory to different folders.

**Comment by laci200270** [comment]
Use MultiMC or similar launcher

**Comment by LexManos** [comment]
Official answer, use different game directories.
We can't control the fact that Minecraft Overrides the the config.
