### ISSUE TITLE
Iron Door Right-Clicking

### ISSUE THREAD

**Issue by natedogith1** [MinecraftForge/MinecraftForge#2124]
Forge modifies Iron Doors so that they don't intercept right-clicking. This causes an issue with afk fish farms.

**Comment by GirafiStudios** [comment]
Minecraft 1.7.10 or 1.8?

**Comment by natedogith1** [comment]
Minecraft 1.7.10 forge-10.13.4.1492

**Comment by cpw** [comment]
No, we don't?

**Comment by natedogith1** [comment]
Well, it works iron doors intercept right-clicking in vanilla. Also, I think that's what this code piece does (though I can't say for certain) https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/block/BlockDoor.java.patch#L8

**Comment by diesieben07** [comment]
I think this is considered a vanilla bug-fix.

**Comment by Actuarius** [comment]
@diesieben07 added labels [RFC]

**Comment by mezz** [comment]
Does Forge still handle this differently from vanilla in 1.11?

**Comment by bs2609** [comment]
No, vanilla fixed this for 1.11 (see #4167). This can probably be closed now.
