### ISSUE TITLE
[1.8] Unable to send messages directly after handshake

### ISSUE THREAD

**Issue by spaceemotion** [MinecraftForge/MinecraftForge#2130]
The example code sadly does not work. It is trying to send the message, but the server is never reading it, so the debug output is never being displayed. However, on the client the message is being created and the method to write into the buffer is being called.

This seems to be either a bug inside forge or minecraft internals, as it is the server that fails to read the message. There is not exception or error being thrown either. Trying different classes and/or IDs did not work as well. Sending packets after the player is in the world (and already is running around) works like a charm.

**_Full SSCE: http://hastebin.com/zaxotiyali.avrasm**_
(The class is being registered at the correct bus in my main mod class)

``` java
public class TestChannel {
    private final SimpleNetworkWrapper channel;


    public TestChannel(Side side) {
        channel = NetworkRegistry.INSTANCE.newSimpleChannel("X|test");
        channel.registerMessage(new MessageHandler(), TestMessage.class, 0, side);
    }

    @SubscribeEvent
    public void onClientConnectedToServer(FMLNetworkEvent.ClientConnectedToServerEvent ev) {
        channel.sendToServer(new TestMessage());
    }


    private class MessageHandler implements IMessageHandler<TestMessage, IMessage> {

        @Override
        public IMessage onMessage(TestMessage message, MessageContext ctx) {
            System.out.println("onMessage: " + message);
            return null;
        }

    }

    private class TestMessage implements IMessage {

        @Override
        public void fromBytes(ByteBuf buf) {
            System.out.println("from Bytes");
        }

        @Override
        public void toBytes(ByteBuf buf) {
            System.out.println("to Bytes");
        }

    }

}
```

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]
