### ISSUE TITLE
[SplashScreen] Race condition causes hang

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/MinecraftForge#2136]
`SplashProgress` calls `thread.join();` in its `finish` method, calling `join(0)` where this section of code is reached:

```java
	if (millis == 0) {
	    while (isAlive()) {
		wait(0);
	    }
	}
```

`wait` has this javadoc:
> The current thread (<tt>T</tt>) becomes disabled for thread scheduling purposes and lies dormant until one of four things happens:
> 
> * Some other thread invokes the <tt>notify</tt> method for this object and thread <var>T</var> happens to be arbitrarily chosen as the thread to be awakened. 
> * Some other thread invokes the <tt>notifyAll</tt> method for this object. 
> * Some other thread {@linkplain Thread#interrupt() interrupts} thread <var>T</var>. 
> * The specified amount of real time has elapsed, more or less.  If <tt>timeout</tt> is zero, however, then real time is not taken into consideration and the thread simply waits until notified. 

What's occurring is that the child thread is exiting and notifying the main thread after `isAlive()` has passed but before `wait` is called, resulting in an infinite hang. Simplest solution is to call `join(30)` or something similar.

It finally occurred in-dev and the thread list did not include the child thread, but the main thread was stalled on `thread.join()`.

**Comment by RainWarrior** [comment]
According to this: http://stackoverflow.com/questions/19455159/java-thread-join-method-freezes-if-the-thread-is-finishing there's no race condition due to Thread.join() being synchronized. As far as I know, Thread.join() is a perfectly acceptable way to wait for threads to finish, the problem must be unrelated to it.

**Comment by skyboy** [comment]
`synchronized` specifically requires the thread's exiting code is also synchronized on the same object (this code appears to be native, and thus not checkable); but the fact that the thread being joined here does not exist in the list of alive threads would indicate that the exiting code is *not* synchronized. It's a state that is otherwise impossible, so regardless of how unlikely it seems, simply adding the 30 millisecond delay to the loop will ensure that wait doesn't hang forever.

**Comment by cpw** [comment]
@skyboy the construct @RainWarrior is using is absolutely common. It is the standard way to wait for another thread. Other issues caused the thread to go away.
