### ISSUE TITLE
Applying forge patch fails when access transformer is used to make SpawnerAnimals non-final.

### ISSUE THREAD

**Issue by Barteks2x** [MinecraftForge/MinecraftForge#2137]
AccessTransformer with the following line:

    public-f net.minecraft.world.SpawnerAnimals

causes applying patches to fail.

**Comment by LexManos** [comment]
And thus is the issue with using base edits like access transformers.
Don't do it. We've done what we can to allows for access changes but can't catch everything.
Why do you need to unfanilize SpawnerAnimals?

**Comment by Barteks2x** [comment]
To extend it and replace the object in World class.
I'm working on mod that extends world height and depth to about +/-8 million blocks. Mob spawning code needs to be modified to allow that. And code to do that using ASM would be really complex.
I;ve seen the SpawnerAnimal patch file and it could be fixed by removing additional imports and using fully qualified class names.

**Comment by jk-5** [comment]
That won't make any difference. In bytecode there is no such thing as imports. Everything is compiled to fully qualified class names.

**Comment by Barteks2x** [comment]
but it's the pach that fails to apply.

**Comment by jk-5** [comment]
Oh you're talking about source patches. Ignore my comment above

**Comment by LexManos** [comment]
You're going to hack to hack A LOT of things with ASM if you're going to be editing something as fundamental as the world/chunk format. Doing this on your own isnt that much more complicated.
Yes, It's the rule that our patches should not import but instead use fully qualified names.
For this, and similar reasons. However stuff like this is a extremely low priority 

The imports will be fixed next time we update MC as everything is getting a full audit and overhaul.
For now you can just use the normal CI workspace not the decomp workspace.
