### ISSUE TITLE
Add date to log messages

### ISSUE THREAD

**Issue by Baughn** [MinecraftForge/MinecraftForge#2138]
At least as a header at the top of fml-server-*.log, would be nice.

**Comment by cpw** [comment]
Explain? Every message is timestamped.

**Comment by TehNut** [comment]
He means the generated files, not the messages themselves.

**Comment by cpw** [comment]
Log files with timestamps in the name? You can just supply a custom log4j2 config to get that. I prefer not to make the names too annoyingly verbose..

**Comment by Baughn** [comment]
I meant the messages inside the logfiles. They have the timestamp, but not the date.

**Comment by AEnterprise** [comment]
if you want a date: check when the file properties to see when it was made

**Comment by Baughn** [comment]
Check when it was made, hope mtime didn't get modified at some point, then walk the file while keeping track of what the current date is, since they usually span multiple days?

Yes, that would work, but it's a hell of a lot harder than using grep.

**Comment by heldplayer** [comment]
What you might want is a line added to the start of the log with the current date?

Adding the date to every line is a horrible thing to do for both readability and disk usage.

**Comment by cpw** [comment]
If you want to customize the log output, go read about log4j2. You can supply your own. Forge will not do this- there is no benefit, and it will waste a lot of disk.
