### ISSUE TITLE
TickEvent.WorldTickEvent is never called for client world

### ISSUE THREAD

**Issue by Barteks2x** [MinecraftForge/MinecraftForge#2142]
I tested it with MDK version 11.14.3.1521.
Example code:
```java
package com.example.examplemod;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.TickEvent;

@Mod(modid = ExampleMod.MODID, version = ExampleMod.VERSION) public class ExampleMod {
    public static final String MODID = "examplemod";
    public static final String VERSION = "1.0";

    @EventHandler public void init(FMLInitializationEvent event) {
        FMLCommonHandler.instance().bus().register(new Object() {
            @SubscribeEvent public void onWorldTick(TickEvent.WorldTickEvent evt) {
                System.out.println("Tick event: side=" + evt.side + ", phase="+ evt.phase + ", world=" + evt.world);
            }
        });
    }
}
```

It only prints messages with side=SERVER.

**Comment by diesieben07** [comment]
Since the client only ever has one world, this is not needed. You can just use `ClientTickEvent` for the client.

**Comment by Barteks2x** [comment]
So why there even is event.side field if it's always server?

**Comment by diesieben07** [comment]
Because it's a field in `TickEvent`.

**Comment by Barteks2x** [comment]
The class isn't called WorldServerTickEvent, it's called WorldTickEvent. And the fact that there is only one world clientside doesn't make it not-a-world. It seems reasonable to assume it also works for client world (and this is what I did, only to be suprised that it isn't the case when trying to find out why my code doesn't work)

**Comment by Lunatrius** [comment]
There's a few things you have to consider when using `ClientTickEvent`. You have to keep checking whether the client world exists. The event is also triggered in SP even when the game is paused, which *might* cause weird side effects if you're not aware of this.

**Comment by diesieben07** [comment]
You might call it a bug. But you cannot fix this or you will break every mod out there that relies on it. Which includes mine for example.

**Comment by Barteks2x** [comment]
So at least it should be documented somewhere.

**Comment by Lunatrius** [comment]
If you're referring to `ClientTickEvent` - it's not really a bug, that's just how it works.

The previously mentioned "issues"/quirks are just something that you have to *consider* when you want your stuff to run *only when you're in game*.

**Comment by Barteks2x** [comment]
I was referring to TickEvent.WorldTickEvent.
In my case - updating lighting even when game is paused may not be so bad idea.

**Comment by cpw** [comment]
OK. This tick has never fired on the client, since the client world doesn't really "tick" in the normal sense. As everyone has already said, use the ClientTickEvent.
