### ISSUE TITLE
[1.7.10] Crash on unknown attribute

### ISSUE THREAD

**Issue by Xfel** [MinecraftForge/MinecraftForge#2144]
I noticed a bug in minecraft core code in Forge 10.13.4.1448 in the part handling S20PacketEntityProperties on the client. If the client receives an unknown attribute, it will create a default instance with default bound values. The code used for this is `new RangedAttribute(snapshot.func_151409_a(), 0.0D, 2.2250738585072014E-308D, Double.MAX_VALUE)`. However, This will always crash with an IllegalArgumentException, as the passed default value `0.0` is smaller than the passed minimum value `2.2250738585072014E-308`. This seems to come from minecraft itself, but it would still be good if forge could fix this as we had this error multiple times on our server, and having to clear out the affected entities manually is not a viable option.

**Comment by LexManos** [comment]
Who or what is sending invalid attributes?

**Comment by Xfel** [comment]
We now traced it down to a problem with mismatching enderio configs on server/client side. However, the problem remains that if I have a server only mod adding a custom attribute, it will crash.

**Comment by LexManos** [comment]
There are a lot of things the server can do that crashes the client.
I am reluctant to think of this as an error unless you can come up with a valid point where invalid attributes should be sent to the client WITHOUT the client crashing/erroring in some way.
Silently ignoring errors like this is not a good thing.

**Comment by diesieben07** [comment]
Closing, since apparently there are no valid points to be made where this is needed.

**Comment by Actuarius** [comment]
@diesieben07 closed this issue

**Comment by williewillus** [comment]
(for archival purposes, this is a vanilla bug)
