### ISSUE TITLE
[1.8] Fluid model performance

### ISSUE THREAD

**Issue by kirderf1** [MinecraftForge/MinecraftForge#2145]
Based on mraof/Minestuck#94.
The current method of handling fluid models (create a new one everytime it's needed) isn't very efficient when it comes to rendering larger amounts of fluid where the same models are repeatedly used. (oceans being the most common example)

The method I used when implementing my own fluid models (before the forge fluid model was implemented) was to use a hashmap with a list of parameters (corner heights and flow direction) as the key and the compiled fluid model as value, thus letting me to re-use the compiled models when the same parameters are used.

**Comment by RainWarrior** [comment]
I'd like to add a cache, but the problem currently is that all the level computations return float, and I didn't dig too deep into them; so, either they should change to return int, of the resulting float can be rounded up to some precision; I don't know enough about fluids to know that precision though :)

**Comment by LexManos** [comment]
If I understand what hes saying he's referring to the normal Forge fluid, which is metadata based.
Which allows for 1/16th block intervals for 'full' so round to there?
