### ISSUE TITLE
Canceling the stop using item event, clears itemInUseCount

### ISSUE THREAD

**Issue by idc-github-account** [MinecraftForge/MinecraftForge#2149]
If you cancel the event PlayerUseItemEvent.Stop(player, item, duration) the method EntityPlayer.clearItemInUse() is still executed which sets itemInUseCount to zero.

I want to make an item that when you right click it will be used until the max item use duration is reached.

**Comment by diesieben07** [comment]
Please clarify. If the event is canceled, the player still stopped using the item. You cannot cancel the fact that the user is no longer pressing the right mouse button.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Needs Update]
