### ISSUE TITLE
E-mail set as username instead of the real username

### ISSUE THREAD

**Issue by MarcuzD** [MinecraftForge/MinecraftForge#2152]
When launching Minecraft with the following arguments, my E-mail address is used as my displayname instead of my real username.

    --username email_here --password my_password_here --version 1.7.10 --gameDir . --assetsDir assets --assetIndex 1.7.10 --tweakClass=cpw.mods.fml.common.launcher.FMLTweaker

I'm using Minecraft 1.7.10 with Forge#1448 universal and LiteLoader placed in the mods folder. It looks like LiteLoader messes up the loading/login sequence, so it never sets the username as my real username. And because of this when Minecraft finally starts to load, it says "Setting user: my email address".
(This issue is also reported to LiteLoader's author, so it may be possible to fix this problem on both sides)

Also, a sidenote: when I died, a mod caused my head to drop (vanilla head item), and it had "my email address's head" as the item name. Placing it down downloaded my skin, and after picking it up it said "my username's head".

**Comment by Spartan322** [comment]
I thought you're supposed to use your username for the username...

**Comment by LexManos** [comment]
Forge does not log you in in the production environment. 
That's a feature purely for the devs. So no user a normal launcher.
And if you're talking about dev world, then update to 1.8, and use GradleStart.

**Comment by MarcuzD** [comment]
It **IS** working without LiteLoader! I was able to join an online-mode=true vanilla server when launching MC with --username myemail --password mypassword, and I'm not in a devenv. Also, it says "Setting user: my name" instead of my email address when launching wrapped MC, and ingame I have my username displayed instead of my email address, so the above statement is false, because I was able to log in in a production env with the --username and --pasworrd arguments. If  you need proof, just ask.

**Comment by LexManos** [comment]
Interesting it shouldn't ship those files if it does i'll have to yell at Abrar.
So you say it works fine without LiteLoader, then it's LiteLoader screwing things up. Go talk to him.
I hear he injects himself before forge so it's up to him to deal with stuff like this.
