### ISSUE TITLE
NoteBlockEvent constructor should be protected

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#2153]
It's currently default/package-private. This means there's no NoteBlockEvent-compatible way to add custom noteblocks with corresponding custom events.

For example, in my mod, I need a NoteBetterEvent and a Play sub-event. A NoteBetterEvent.Play event would take a ResourceLocation for instrument instead of an int/Instrument.

**Comment by liach** [comment]
Sux use AccessTransformer plz

**Comment by skyboy** [comment]
ResourceLocations and the `Instrument` enum are incompatible anyway. There's no way for you to do what you want to do and have mods just automatically support it.

**Comment by SoniEx2** [comment]
but NoteBlockEvent doesn't care about Instrument.

**Comment by SoniEx2** [comment]
1.9 adds getInstrument and setInstrument. [It's pretty good!](https://github.com/eNByeX/NoteBetter/blob/master/src/main/java/com/github/soniex2/notebetter/api/NoteBetterPlayEvent.java)

**Comment by Actuarius** [comment]
@diesieben07 closed this issue

**Comment by SoniEx2** [comment]
Please reopen. The constructor still is not protected.

**Comment by diesieben07** [comment]
And? You should not be firing raw `NoteBlockEvent` instances, only instances of one of the subclasses. Hence the constructor is not exposed.

**Comment by williewillus** [comment]
He wants to add his own subclasses

**Comment by diesieben07** [comment]
He can go ahead. The `NoteBlockEvent.Change` and `NoteBlockEvent.Play` constructors are public.

**Comment by SoniEx2** [comment]
Subclasses of NoteBlockEvent that don't conflict with either NoteBlockEvent.Play or NoteBlockEvent.Change.

**Comment by williewillus** [comment]
What else would you need?..

**Comment by SoniEx2** [comment]
`FetchInstrument` I guess.

**Comment by LexManos** [comment]
Because I don't feel like the bitching anymore, here you go. The hacks you do for note blocks should not be done. However this should make you shutup and leave us alone.
