### ISSUE TITLE
MultiMC 1.7.10 Windows10 Terra-Firma-Craft

### ISSUE THREAD

**Issue by supmah10** [MinecraftForge/MinecraftForge#2156]
Hello, I just wanted to play some minecraft with my firend (terrafirmacraft) today on technic launcher... It didnt work, so we moved all mods to multimc and I got it to work, but my friend didn't, but thats another story... The problem is that when I try to join the server that works just fine with only the one mod we need, it crashes with the code -1

Here is everything that i have got info way...

http://paste.ee/p/RqLuY    (client log i think)

http://paste.ee/p/zFsjb      (crash log 1st try)

http://paste.ee/p/i8y0P      (crash log 2nd try)

Thank you for the help!

**Comment by Spartan322** [comment]
This is not a forge problem, don't report mod issues here. Report them to the mod author(s)

**Comment by supmah10** [comment]
hu, I saw that someone had posted something at a MultiMC thingy but didnt found it
i jsut made an accound in hope for some help

**Comment by Spartan322** [comment]
Only forge related issues are to be reported here (eg: forge crashes without any mods installed)

**Comment by supmah10** [comment]
well then, where can i find this mod author thing.... cant see it

**Comment by Spartan322** [comment]
Often times, a mod author will provide a method of issue tracking, if they do not, your best bet is to tell them on the forums or in a pm, but probably the less intrusive forum post would be preferred. Try looking up the mod (either thread, or if it has a website, the site) and search from there.

**Comment by supmah10** [comment]
My friend is helping me and said it was liteloader... 
Thanks for evern trying.... -.-
