### ISSUE TITLE
gradlew setupForge eclipse not working

### ISSUE THREAD

**Issue by Dijkstra1** [MinecraftForge/MinecraftForge#2159]
when I run gradlew setupForge eclipse

i get this error

FAILURE: Build failed with an exception.

* What went wrong:
Task 'eclipse' not found in root project 'forge'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option
 to get the stack trace. Run with                                              -
-info
or                                                                             -
-debug
option to get more log output.

what do i nee to fix this

**Comment by diesieben07** [comment]
Just `setupForge` is enough these days. After that import the generated Clean and Forge projects into whatever workspace you like.

**Comment by Dijkstra1** [comment]
thanks maybe the wiki should upgrade.
