### ISSUE TITLE
I can't update Forge [1.7.10]

### ISSUE THREAD

**Issue by 828bkg** [MinecraftForge/MinecraftForge#2165]
I use a very old forge version,and I can't use new mods,if I update forge to 10.13.4.1448 or newest my game doesn't start, this is from console

    http://pastebin.com/rgWMAeGF

Please help me!!! (Sorry for my bad english,but it isn't my main language)

**Comment by diesieben07** [comment]
You have a cracked launcher, those are not supported. Buy the game.
