### ISSUE TITLE
Slot-sensitive getInventoryStackLimit

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#2166]
Forge should add a slot-sensitive IInventory.getInventoryStackLimit. This could be useful for brewing stands.

**Comment by AEnterprise** [comment]
sounds usefull, not only for brewing stands but alot of modded blocks that enforce a stack limit. Charging station for charging RF tools or machines to fill fluid containers are good examples i think, they usualy limit stack side of what they are processing to 1 to prevent dupe bugs

**Comment by ganymedes01** [comment]
I'd love that too.
There could be a patch done to the method in IInventory, and to avoid breaking current mods we could use ASM to fix them at runtime (like it was done when forge did changes to to fluids a few months back).

**Comment by AlexIIL** [comment]
@ganymedes01 That wouldn't work for compile time though- suddenly all mods would fail to compile everywhere. Also any mod class that implements IInventory would need to have a new method added (at runtime), which may fail in weird and horrible ways if there was already a method with the same name (say, an internal private method that is used for stuffs).
It would probably be better to deprecate the old method, and create a new method that is slot-sensitive.

**Comment by ganymedes01** [comment]
-Well if the author is going to be recompiling his mod they can very well add a single argument to the existing method. If they don't want to, then just stay in an old version of Forge.
-They wouldn't have private a method with the same name because that already wouldn't compile.
-Adding a new method to an interface would also break every mod. And because modders take years to adapt to any change, any mods that relies on the new method will have problems with mods that don't still it.

**Comment by diesieben07** [comment]
> They wouldn't have private a method with the same name because that already wouldn't compile.

No, it would not. Methods with same name and different arguments are completely separate from one another.

> Adding a new method to an interface would also break every mod. And because modders take years to adapt to any change, any mods that relies on the new method will have problems with mods that don't still it.

And there is nothing that any ASM magic can do to fix this. At least not with mods _calling_ this method. Which is quite a few I would assume, considering the amount of machines that are out there.

**Comment by SoniEx2** [comment]
> > Adding a new method to an interface would also break every mod. And because modders take years to adapt to any change, any mods that relies on the new method will have problems with mods that don't still it.
>
> And there is nothing that any ASM magic can do to fix this. At least not with mods *calling* this method. Which is quite a few I would assume, considering the amount of machines that are out there.

Mark the old method as deprecated, add the new method, use ASM magic to provide a dummy which just calls the old method. It's *good enough*.

**Comment by jk-5** [comment]
*Or* just wait for the next breaking update

**Comment by SoniEx2** [comment]
Hmm... Sure!

**Comment by ganymedes01** [comment]
@jk-5 That's a good idea actually, seen as 1.8.8 is looming.

**Comment by LexManos** [comment]
-.- Actually think this through and provide a implementation that doesn't break shit.
Also keep in mind we have to support non-Forge mods.

**Comment by SoniEx2** [comment]
It's "Let's bug Mojang" time!

Oh well, I tried.

**Comment by grum** [comment]
Ignored.
