### ISSUE TITLE
Cant get the DecompWorkspace setup 

### ISSUE THREAD

**Issue by ewm2000** [MinecraftForge/MinecraftForge#2169]
I just tried running Gradlew on my mac to setup the workspace and I ran into this error
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

Do I need to manually install gradle?

**Comment by TehNut** [comment]
Make sure `/gradle/` is in your root directory.

**Comment by ewm2000** [comment]
Which root directory? I have the Gradle files in the folder where i will make my mod

**Comment by ewm2000** [comment]
<img width="633" alt="issue" src="https://cloud.githubusercontent.com/assets/8990377/11001895/cb14923c-8477-11e5-87f9-a60c0cb3227e.png">

**Comment by liach** [comment]
Btw close ForgeGradle#290 please

**Comment by ewm2000** [comment]
sorry did not know which repo to put the issue in?

**Comment by ewm2000** [comment]
So how do I fix this issue?

**Comment by liach** [comment]
Download the newest Forge mdk, extract it, and try to run `./gradlew setupDecompWorkspace` in the directory of the extracted mdk.

**Comment by ewm2000** [comment]
I did that and i got this error 
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by ewm2000** [comment]
Yet i just did that in its own folder insted of the github folder and it worked

**Comment by ewm2000** [comment]
Why doesnt it work in the cloned folder of my Github Repo?

**Comment by ewm2000** [comment]
Thanks for the help. Figured it out
