### ISSUE TITLE
Enchanted Effect make lag again

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#2170]
![2558-11-07_01 59 12](https://cloud.githubusercontent.com/assets/6128413/11014098/6bcef392-855a-11e5-8d4d-9ddce93bff13.png)
![2558-11-07_01 59 17](https://cloud.githubusercontent.com/assets/6128413/11014099/6bd8b17a-855a-11e5-8e2f-77e1c150850b.png)

**Comment by cpw** [comment]
Wow, that is a very old graphics card..

**Comment by SteveKunG** [comment]
Really? But when I playing 15w45a it not make my game lag.

**Comment by LexManos** [comment]
@RainWarrior is looking into it. It's not your GFX card, he fucked something up.

**Comment by RainWarrior** [comment]
Fixed in 3d03461a524c9aa2f5cd6e1623dc480ad50fe563.
