### ISSUE TITLE
I have seen a lot of errors with the word forge in, so naturally it must be a forge issue. So please help me debug why my world is broken.

### ISSUE THREAD

**Issue by mockthebear** [MinecraftForge/MinecraftForge#2171]
Well i am getting alot of errors in some areas. These areas are common regions where ppl make their stuff.

The error is:

07.11 16:11:52 [Servidor] INFO ... 27 more
07.11 16:11:52 [Servidor] INFO at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:196) ~[mn.class:?]
07.11 16:11:52 [Servidor] INFO Caused by: java.lang.IllegalStateException: Entity is already tracked!
07.11 16:11:52 [Servidor] INFO at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.tileentity.TileEntityChest.func_145845_h(SourceFile:207) [aow.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.tileentity.TileEntityChest.func_145979_i(SourceFile:186) [aow.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.tileentity.TileEntityChest.func_145977_a(SourceFile:200) [aow.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) [ChunkIOProvider.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) [apx.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.world.World.func_72868_a(World.java:3304) [ahb.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:844) [mt.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.world.World.func_72923_a(World.java:1347) [ahb.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.world.WorldManager.func_72703_a(SourceFile:31) [mp.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:61) [mn.class:?]
07.11 16:11:52 [Servidor] INFO at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:364) [EntityRegistry.class:?]
07.11 16:11:52 [Servidor] INFO at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:230) [mn.class:?]
07.11 16:11:52 [Servidor] INFO net.minecraft.util.ReportedException: Adding entity to track
07.11 16:11:52 [Servidor] INFO [16:11:52] [Server thread/ERROR]: "Silently" catching entity tracking error.

i have deleted all block using mcedit and i still got this error. Any idea how to fix?

**Comment by mockthebear** [comment]
seems to be FML related

**Comment by chibill** [comment]
They need the WHOLE log.

**Comment by mockthebear** [comment]
http://pastebin.com/CFrtbQr5

**Comment by Spartan322** [comment]
How are you registering entities?

**Comment by mockthebear** [comment]
actually i dont know. i just hosting an FTB infinity server with one less and nome more mods. I can post the list.

maybe some mod messing with chunk interface, but i had no idea what mod is. I am thinking it might me the forge

mod list: https://www.dropbox.com/s/4o7s9h21grmth40/mods.png?dl=0

**Comment by mockthebear** [comment]
I just fixed this error by goingg in the region that gives me the error, with this mod:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2161485-1-6-4-1-7-2-1-7-10-1-8-forge-entity-lagfix-2-0-2

and /nukeall

this solved the million errors that was showing, but there is still a issue in somewhere that causes this

**Comment by chibill** [comment]
THIS is a mod propblem not forge. Some mod is messing up entities.

**Comment by cpw** [comment]
You have a mod causing entities to break on loading. Probably, you have entity types in an area that no longer exist. I recommend you talk to the fine folks over on the ftb forums if this is FTB infinity. Make sure you take **complete** logs with you!
