### ISSUE TITLE
Help :(

### ISSUE THREAD

**Issue by PootisDispenser** [MinecraftForge/MinecraftForge#2172]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 11/7/15 1:44 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraft.client.renderer.texture.TextureMap.<init>(ILjava/lang/String;Z)V
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:540)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 161298328 bytes (153 MB) / 314187776 bytes (299 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1541 Optifine OptiFine_1.7.10_HD_B7 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1541-1.7.10.jar) 
	U	Forge{10.13.4.1541} [Minecraft Forge] (forge-1.7.10-10.13.4.1541-1.7.10.jar) 
	U	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	U	aether{Alpha 1.7.10-1.2} [Aether II] (Aether-2-1.7.10.jar) 
	U	alluwant{2.1} [All U Want] (All-U-Want-Mod-1.7.10.jar) 
	U	apocabuckets{1.2} [ApocaBuckets] (apocabuckets-1.7.10-1.2.jar) 
	U	TestEnvironmentMod{1.0} [TestEnvironmentMod] (Bedrock-Mod-1.7.10.jar) 
	U	BuildCraft|Energy{7.0.23} [BC Energy] (buildcraft-7.0.23.jar) 
	U	BuildCraft|Factory{7.0.23} [BC Factory] (buildcraft-7.0.23.jar) 
	U	BuildCraft|Silicon{7.0.23} [BC Silicon] (buildcraft-7.0.23.jar) 
	U	BuildCraft|Transport{7.0.23} [BC Transport] (buildcraft-7.0.23.jar) 
	U	BuildCraft|Builders{7.0.23} [BC Builders] (buildcraft-7.0.23.jar) 
	U	BuildCraft|Core{7.0.23} [BuildCraft] (buildcraft-7.0.23.jar) 
	U	BuildCraft|Robotics{7.0.23} [BC Robotics] (buildcraft-7.0.23.jar) 
	U	BuildCraft|Compat{7.0.12} [BuildCraft Compat] (buildcraft-compat-7.0.12.jar) 
	U	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	U	explosives_pp{1.7b} [§6Explosives§4++] (ExplosivesPP-1.7.10-1.7b.jar) 
	U	ExtendingLadder{3.1.1} [Extendable Ladders] (Extendable-Ladders-Mod-1.7.10.jar) 
	U	meteors{2.13} [Falling Meteors] (Falling-Meteors-Mod-1.7.10.jar) 
	U	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.403.jar) 
	U	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.403.jar) 
	U	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212-Core-1.7.10.jar) 
	U	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	U	MobDismemberment{4.0.0} [MobDismemberment] (MobDismemberment-4.0.0.jar) 
	U	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10 (1).jar) 
	U	clearingblock{0.3} [ClearingBlock Mod] (Nuclear-Bomb-Mod-1.7.10.jar) 
	U	nuclearcraft{V0.1 - 1.7.10} [Nuclear Craft] (Nuclear-Craft-Mod-1.7.10.jar) 
	U	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	Launched Version: 1.7.10-Forge10.13.4.1541-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.3.0 - Build 10.18.15.4256, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by jimcarreer** [comment]
Please provide a paste of the full log.  This is probably caused by a mod, not forge.

**Comment by PootisDispenser** [comment]
what do you mean

**Comment by PootisDispenser** [comment]
sorry im new

**Comment by Spartan322** [comment]
And if it is caused by a mod, you came to the wrong place, also "Help :(" is not a type of title for the issue tracker, please be a bit more descriptive

**Comment by PootisDispenser** [comment]
i dont know if it caused by a mod or not

**Comment by jimcarreer** [comment]
@PootisDispenser Go to http://pastebin.com/ and paste the ENTIRE log. You've only pasted part of it

**Comment by Spartan322** [comment]
Remove all mods and restart the game, if it still crashes, it might be forge, or a corrupt forge (this means reinstall forge), if it doesn't, then your mods are crashing your game

**Comment by PootisDispenser** [comment]
okay

**Comment by PootisDispenser** [comment]
its a mod, but i dont know which one

**Comment by jimcarreer** [comment]
@PootisDispenser the full log will help me determine which mod is causing it, but this is *NOT* the appropriate place to ask for help with bad mods.  If you know how to use IRC, jump on #minecraftforge on EsperNet and I can help you.

**Comment by Spartan322** [comment]
This issue is to be closed then

**Comment by PootisDispenser** [comment]
link to espernet please i am new

**Comment by Spartan322** [comment]
http://webchat.esper.net/?nick=Guest&channels=minecraftforge&prompt=1

**Comment by PootisDispenser** [comment]
im so confused i dont know how to irc

**Comment by PootisDispenser** [comment]
;-;

**Comment by Spartan322** [comment]
Stop spamming, you don't need to constantly post, even though bumping doesn't exist on the issue tracker

**Comment by robin4002** [comment]
Remove optifine. 
Also next time please post on the forum. Github issues aren't for end users.

**Comment by PootisDispenser** [comment]
im confused

**Comment by PootisDispenser** [comment]
i think its ichun actually

**Comment by jimcarreer** [comment]
@PootisDispenser stop posting here, either go to IRC or Post your problem to the forum, you wont get any help here, you're asking your question the wrong place and frankly it's very annoying.

**Comment by PootisDispenser** [comment]
I dont know how to IRC

**Comment by diesieben07** [comment]
Remove Optifine.

**Comment by cpw** [comment]
remove optifine. Do NOT report this kind of issue here. Optifine needs to update to support 1541.
