### ISSUE TITLE
(1.7.10) OreDictionary.getOreIDs and world changes

### ISSUE THREAD

**Issue by malte0811** [MinecraftForge/MinecraftForge#2175]
Forge version: happens on 1541, found on 1448
The problem:
`OreDictionary.getOreIDs(ItemStack)` returns wrong data when changing to a world (singleplayer) that has a different id map (I think)
Steps to reproduce:
1. start a forge instance with immersive engineering (or ic2) and blood magic (optional: NEI to see the item id's)
2. Create a new creative mode world and somehow check that said method returns the id for `oreTin` for a tin ore block. The id of ic2 tin ore was, in my case, 226.
3. close minecraft, remove blood magic, restart minecraft
4. enter the old world, pressing yes when forge asks about missing items, check that said method still returns the id of `oreTin` for a tin ore block.
5. Exit the old world and create a new creative mode world.
6. Notice that `OreDictionary.getOreIDs(ItemStack)` returns nothing (or, with different versions,  some nonsense) for tin ore.
7. Check `OreDictionary.getOreIDs(ItemStack)` for whatever item has the id that tin ore had in the old world, in my case a nuke. Check `OreDictionary.getOreIDs(ItemStack)` to see that it apears to be registered as `oreTin`

**Comment by cpw** [comment]
Explain? 1541 has some fixes in this area. It happens in both versions?

**Comment by cobra** [comment]
It apparently does.

**Comment by cpw** [comment]
@cobra without log files, and a clearer explanation of the issue, your comment is not helpful. Thanks!

**Comment by malte0811** [comment]
1. It does happen with forge 1541 (installed by MultiMC)
2. Log from the first launch: https://gist.github.com/malte0811/efc267200fd9bfd1c3bd
3. Log from second launch: https://gist.github.com/malte0811/9077646e876f0ae29a13

Explanation of the issue: `OreDictionary.getOreIDs(ItemStack)` returns incorrect values when different worlds with different item id maps are loaded without mc restart in between. I don't know whether this is what you meant by `a clearer explanation`, if it isn't, please tell me what information you need

**Comment by cpw** [comment]
The oreId is worldspecific. It has to be, it's tied to items ID in the world. Names are persistent. Explain why this is an issue?

**Comment by LexManos** [comment]
Its not.

**Comment by malte0811** [comment]
I discussed this on IRC with cpw after i opened this issue. If i read the changelog correctly, this was caused by the remap event sometimes not being fired or something like that. It is fixed now, but in the old version the oredict would sometimes report an ic2 nuke to be registered as ore id 181 which mapped to oreTin. If that is not an issue, then i missunderstood what a nuke is.
