### ISSUE TITLE
Armor Coloring doesn't Work for custom Armors

### ISSUE THREAD

**Issue by arideus101** [MinecraftForge/MinecraftForge#2178]
MinecraftForge/patches/minecraft/net/minecraft/client/renderer/entity/layers/LayerArmorBase.java.patch
LayerArmorBase missing an else at Line 32 (Possibly, line with //Non-Cloth), resets the color for any non-cloth armor to blank.

**Comment by GirafiStudios** [comment]
I had the same issue and thought something was wrong too. But i'm afraid you're just doing something wrong.
Feel free look at my repo or contact me if you need any help @arideus101 ^^
