### ISSUE TITLE
Entity Render Provider based on entity fields

### ISSUE THREAD

**Issue by cjcool** [MinecraftForge/MinecraftForge#2180]
Please correct me if I am wrong. As far as I am aware, their is no way to provide an entity Renderer instance based on an entity's fields (such as a Gender gender, or int job) without creating a separate entity or modifying a Minecraft class. If this truly is the case, I would like to request possible implementations, use cases, and workarounds from people and I would like to attempt to provide a pull request to solve this limitation if necessary based on the feedback given.

One concept I have so far to solve this limitation would be to create a registry that would hook into the RenderManager and attempt to provide a Renderer (if the entity has not been registered with an existing handler) for the entity based on the registered provider instances. With a provider inheriting an interface that defines a method that takes an entity and returns a Renderer or null if it can't. This would match how the Fuel Provider functions on the front-end.

**Comment by williewillus** [comment]
Entity renderers can already read the state of the entity they're supposed to render...
You're passed the entity in the doRender method
How else do you think players, zombies, witches, render their held items and armor, or splash potions render the correct potion color? They have to get it from the entity.

**Comment by cjcool** [comment]
Glad to hear I passed over what I was looking for, rather then it being missing. Thank you for your help.
