### ISSUE TITLE
1.8.8 (mappings not found)

### ISSUE THREAD

**Issue by gamerforEA** [MinecraftForge/MinecraftForge#2181]
Gradle: 2.8
OS: Windows 8.1 x64
JRE: 1.8.0_60
Log: http://pastebin.com/umhmiMDJ

**Comment by DanielHuisman** [comment]
The 1.8.8 mappings aren't public yet, so that's why you get that error.

**Comment by gamerforEA** [comment]
We know when they will be public?

**Comment by DanielHuisman** [comment]
No, I'm waiting on them aswell

**Comment by gamerforEA** [comment]
Well I'll wait.

**Comment by cpw** [comment]
The branch isn't finished yet. It's not even 30% done. We only push it so that we can collaborate.. Please let us finish.

**Comment by DanielHuisman** [comment]
I'm not waiting for Forge, I'm waiting for the MCP 1.8.8 mappings.

**Comment by cpw** [comment]
And since we're still verifying them, they're currently unreleased..
