### ISSUE TITLE
MinecraftForge gradlesetupDecompWorkspace failed

### ISSUE THREAD

**Issue by LOLDERP** [MinecraftForge/MinecraftForge#2183]
When i did the gradle setupDecompWorkspace it gave me a build fail 

Macbook-pro:forge-1.8-11.14.4.1563-mdk derp$ ./gradlew setupDecompWorkspace
Downloading https://services.gradle.org/distributions/gradle-2.7-bin.zip
................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /Users/derp/.gradle/wrapper/dists/gradle-2.7-bin/4s0fcuuppw3tjb1sxpzh16mne/gradle-2.7-bin.zip to /Users/derp/.gradle/wrapper/dists/gradle-2.7-bin/4s0fcuuppw3tjb1sxpzh16mne
Set executable permissions for: /Users/derp/.gradle/wrapper/dists/gradle-2.7-bin/4s0fcuuppw3tjb1sxpzh16mne/gradle-2.7/bin/gradle
Download https://plugins.gradle.org/m2/gradle/plugin/net/minecraftforge/gradle/ForgeGradle/2.0.2/ForgeGradle-2.0.2.pom
Download https://plugins.gradle.org/m2/org/ow2/asm/asm-debug-all/5.0.3/asm-debug-all-5.0.3.pom
Download https://plugins.gradle.org/m2/com/google/guava/guava/18.0/guava-18.0.pom
Download https://plugins.gradle.org/m2/com/google/guava/guava-parent/18.0/guava-parent-18.0.pom
Download https://plugins.gradle.org/m2/net/sf/opencsv/opencsv/2.3/opencsv-2.3.pom
Download https://plugins.gradle.org/m2/com/cloudbees/diff4j/1.1/diff4j-1.1.pom
Download https://plugins.gradle.org/m2/com/cloudbees/cloudbees-oss-parent/1/cloudbees-oss-parent-1.pom
Download https://plugins.gradle.org/m2/com/github/abrarsyed/jastyle/jAstyle/1.2/jAstyle-1.2.pom
Download https://plugins.gradle.org/m2/net/sf/trove4j/trove4j/2.1.0/trove4j-2.1.0.pom
Download https://plugins.gradle.org/m2/com/github/jponge/lzma-java/1.3/lzma-java-1.3.pom
Download https://plugins.gradle.org/m2/com/nothome/javaxdelta/2.0.1/javaxdelta-2.0.1.pom
Download https://plugins.gradle.org/m2/com/github/tony19/named-regexp/0.2.3/named-regexp-0.2.3.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-client/4.3.3/httpcomponents-client-4.3.3.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/project/7/project-7.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpmime/4.3.3/httpmime-4.3.3.pom
Download https://plugins.gradle.org/m2/org/jvnet/localizer/localizer/1.12/localizer-1.12.pom
Download https://plugins.gradle.org/m2/org/jvnet/localizer/localizer-parent/1.12/localizer-parent-1.12.pom
Download https://plugins.gradle.org/m2/trove/trove/1.0.2/trove-1.0.2.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.pom
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcomponents-core/4.3.2/httpcomponents-core-4.3.2.pom
Download https://plugins.gradle.org/m2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.pom
Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/28/commons-parent-28.pom
Download https://plugins.gradle.org/m2/commons-codec/commons-codec/1.6/commons-codec-1.6.pom
Download https://plugins.gradle.org/m2/org/apache/commons/commons-parent/22/commons-parent-22.pom
Download https://plugins.gradle.org/m2/gradle/plugin/net/minecraftforge/gradle/ForgeGradle/2.0.2/ForgeGradle-2.0.2.jar
Download https://plugins.gradle.org/m2/org/ow2/asm/asm-debug-all/5.0.3/asm-debug-all-5.0.3.jar
Download https://plugins.gradle.org/m2/com/google/guava/guava/18.0/guava-18.0.jar
Download https://plugins.gradle.org/m2/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar
Download https://plugins.gradle.org/m2/com/cloudbees/diff4j/1.1/diff4j-1.1.jar
Download https://plugins.gradle.org/m2/com/github/abrarsyed/jastyle/jAstyle/1.2/jAstyle-1.2.jar
Download https://plugins.gradle.org/m2/net/sf/trove4j/trove4j/2.1.0/trove4j-2.1.0.jar
Download https://plugins.gradle.org/m2/com/github/jponge/lzma-java/1.3/lzma-java-1.3.jar
Download https://plugins.gradle.org/m2/com/nothome/javaxdelta/2.0.1/javaxdelta-2.0.1.jar
Download https://plugins.gradle.org/m2/com/github/tony19/named-regexp/0.2.3/named-regexp-0.2.3.jar
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpmime/4.3.3/httpmime-4.3.3.jar
Download https://plugins.gradle.org/m2/org/jvnet/localizer/localizer/1.12/localizer-1.12.jar
Download https://plugins.gradle.org/m2/trove/trove/1.0.2/trove-1.0.2.jar
Download https://plugins.gradle.org/m2/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
Download https://plugins.gradle.org/m2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
Download https://plugins.gradle.org/m2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
#################################################
         ForgeGradle 2.0-SNAPSHOT        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
               Powered by MCP 9.10               
             http://modcoderpack.com             
         by: Searge, ProfMobius, Fesh0r,         
         R4wk, ZeuX, IngisKahn, bspkrs           
#################################################
:deobfCompileDummyTask
:deobfProvidedDummyTask
:getVersionJson
:extractUserdev
Download http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.8-11.14.4.1563/forge-1.8-11.14.4.1563.pom
Download http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.8-11.14.4.1563/forge-1.8-11.14.4.1563-userdev.jar
:extractDependencyATs SKIPPED
:extractMcpData
Download http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.8/mcp-1.8-srg.zip
:extractMcpMappings
Download http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_snapshot/20141130-1.8/mcp_snapshot-20141130-1.8.zip
:genSrgs
:downloadClient
:downloadServer
:splitServerJar
:mergeJars
:deobfMcSRG
Applying SpecialSource...
Applying Exceptor...
:getFernFlower
:decompileMc
:fixMcSources
:applySourcePatches
:remapMcSources
:recompileMc
Download https://libraries.minecraft.net/java3d/vecmath/1.5.2/vecmath-1.5.2.pom
Download https://repo1.maven.org/maven2/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.pom
Download https://libraries.minecraft.net/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.pom
Download https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.pom
Download https://libraries.minecraft.net/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.pom
Download https://libraries.minecraft.net/com/paulscode/codecwav/20101023/codecwav-20101023.pom
Download https://libraries.minecraft.net/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.pom
Download https://libraries.minecraft.net/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.pom
Download https://libraries.minecraft.net/com/paulscode/soundsystem/20120107/soundsystem-20120107.pom
Download https://repo1.maven.org/maven2/io/netty/netty-all/4.0.15.Final/netty-all-4.0.15.Final.pom
Download https://repo1.maven.org/maven2/io/netty/netty-parent/4.0.15.Final/netty-parent-4.0.15.Final.pom
Download https://repo1.maven.org/maven2/net/java/jinput/jinput/2.0.5/jinput-2.0.5.pom
Download https://repo1.maven.org/maven2/net/java/jutils/jutils/1.0.0/jutils-1.0.0.pom
Download https://libraries.minecraft.net/com/mojang/authlib/1.5.21/authlib-1.5.21.pom
Download https://libraries.minecraft.net/com/mojang/realms/1.6.1/realms-1.6.1.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.pom
Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.pom
Download https://libraries.minecraft.net/org/lwjgl/lwjgl/parent/2.9.2-nightly-20140822/parent-2.9.2-nightly-20140822.pom
Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.pom
Download https://libraries.minecraft.net/tv/twitch/twitch/6.5/twitch-6.5.pom
Download https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.pom
Download https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.pom
Download https://repo1.maven.org/maven2/com/typesafe/config/1.2.1/config-1.2.1.pom
Download https://repo1.maven.org/maven2/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.pom
Download https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.pom
Download https://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.pom
Download https://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.pom
Download https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.pom
Download https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.pom
Download https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.pom
Download https://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.pom
Download https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.pom
Download https://libraries.minecraft.net/lzma/lzma/0.0.1/lzma-0.0.1.pom
Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5.pom
Download https://libraries.minecraft.net/tv/twitch/twitch-platform/6.5/twitch-platform-6.5.pom
Download https://libraries.minecraft.net/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5.pom
Download https://repo1.maven.org/maven2/org/scala-lang/scala-actors/2.11.0/scala-actors-2.11.0.pom
Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
Download https://libraries.minecraft.net/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
Download https://repo1.maven.org/maven2/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
Download https://libraries.minecraft.net/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
Download https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
Download https://libraries.minecraft.net/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
Download https://libraries.minecraft.net/com/paulscode/codecwav/20101023/codecwav-20101023.jar
Download https://libraries.minecraft.net/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
Download https://libraries.minecraft.net/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
Download https://libraries.minecraft.net/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
Download https://repo1.maven.org/maven2/io/netty/netty-all/4.0.15.Final/netty-all-4.0.15.Final.jar
Download https://repo1.maven.org/maven2/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
Download https://repo1.maven.org/maven2/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
Download https://libraries.minecraft.net/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
Download https://libraries.minecraft.net/com/mojang/realms/1.6.1/realms-1.6.1.jar
Download https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar
Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar
Download https://libraries.minecraft.net/tv/twitch/twitch/6.5/twitch-6.5.jar
Download https://libraries.minecraft.net/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
Download https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
Download https://repo1.maven.org/maven2/com/typesafe/config/1.2.1/config-1.2.1.jar
Download https://repo1.maven.org/maven2/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
Download https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
Download https://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
Download https://repo1.maven.org/maven2/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
Download https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
Download https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
Download https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
Download https://repo1.maven.org/maven2/org/scala-lang/modules/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
Download https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
Download https://libraries.minecraft.net/lzma/lzma/0.0.1/lzma-0.0.1.jar
Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
Download https://repo1.maven.org/maven2/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar
Download https://libraries.minecraft.net/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-32.jar
Download https://libraries.minecraft.net/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-64.jar
Download https://libraries.minecraft.net/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-osx.jar
Download https://libraries.minecraft.net/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-32.jar
Download https://libraries.minecraft.net/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar
Download https://repo1.maven.org/maven2/org/scala-lang/scala-actors/2.11.0/scala-actors-2.11.0.jar
Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-windows.jar
Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-linux.jar
Download https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822-natives-osx.jar
[ant:javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
[ant:javac] /Users/derp/Desktop/forge-1.8-11.14.4.1563-mdk/build/tmp/recompileMc/sources/net/minecraftforge/client/model/obj/OBJModel.java:617: error: cannot find symbol
[ant:javac]                     material.getColor().setW(alpha);
[ant:javac]                                        ^
[ant:javac]   symbol:   method setW(float)
[ant:javac]   location: class Vector4f
[ant:javac] Note: Some input files use or override a deprecated API.
[ant:javac] Note: Recompile with -Xlint:deprecation for details.
[ant:javac] Note: Some input files use unchecked or unsafe operations.
[ant:javac] Note: Recompile with -Xlint:unchecked for details.
[ant:javac] 1 error
[ant:javac] 1 warning
:recompileMc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':recompileMc'.
> Compile failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8 mins 45.513 secs

**Comment by matthewprenger** [comment]
@kenzierocks had the same problem. IIRC it was an old version of vecmath in her java system extensions.

**Comment by LOLDERP** [comment]
this one is for 1.8

**Comment by matthewprenger** [comment]
Yes... I never said it wasn't. Check your extensions folder in your JDK install. If you find a vecmath jar in there, delete it.

**Comment by LOLDERP** [comment]
for some resson it wont let me delete it 
why os x why

**Comment by williewillus** [comment]
Please use pastebin or similar in the future

**Comment by corbanvilla** [comment]
hmm... I don't have anything in the extenstions folder, but I'm still getting that error :(

**Comment by kenzierocks** [comment]
@corbanvilla Under `/System/Library/Java/Extensions` what JARs are present?

**Comment by LOLDERP** [comment]
@corbanvilla if you have os x 10.11 you might get a message that tells you that you can't delete or modfiy the file just restart your os x and do command and r and hold  it for a 5 seconds and it will take you to the recover system just
open terminal in there and just do csrutil disable it will disable the Configuring System Integrity Protection
if you want to enable it just change the disable to enable

**Comment by corbanvilla** [comment]
Yay! I got it working. Mac just wasn't showing me the files through finder, but through terminal they showed up just fine. Thank you for your help! :)

**Comment by jjfoley** [comment]
This thread was extremely helpful.
But rather than fooling around disabling protection systems designed to stop you from screwing up your OS, a better solution may be to:
1) download a new vecmath.jar - perhaps vecmath-1.5.2.jar from http://www.java2s.com/Code/Jar/v/Downloadvecmathjar.htm
2) rename it vecmath.jar
3) place it in /Library/Java/Extensions/ so that it takes precedence over the OS X version provided in /System/Library/Java/Extensions/

Then re-run the `./gradlew setupDecompWorkspace eclipse` command and it should work.

**Comment by kenzierocks** [comment]
There is a patch for this on the latest SNAPSHOT of FG, so none of this is necessary.

**Comment by karlthepagan** [comment]
Same here. Broken in ForgeGradle 2.0.2

Fixed in 2.0-SNAPSHOT (build 20151130.223416-156)

**Comment by Hanse00** [comment]
Just wanted to drop in a quick update on an easier way to resolve this problem.

I'm running OS X 10.11.2 and ran into the exact same error as @LOLDERP whilst running the task `./gradlew setupDecompWorkspace` with the default FG setup for Forge 1.8-11.14.4.1563 and 1.8-11.14.4.1577:

```
[ant:javac]                     material.getColor().setW(alpha);
[ant:javac]                                        ^
[ant:javac]   symbol:   method setW(float)
[ant:javac]   location: class Vector4f
[ant:javac] Note: Some input files use or override a deprecated API.
[ant:javac] Note: Recompile with -Xlint:deprecation for details.
[ant:javac] Note: Some input files use unchecked or unsafe operations.
[ant:javac] Note: Recompile with -Xlint:unchecked for details.
[ant:javac] 1 error
[ant:javac] 1 warning
:recompileMc FAILED

FAILURE: Build failed with an exception.
```

As indicated by @karlthepagan above, this error does not seem to present itself with FG 2.0-SNAPSHOT, however it does with FG 2.0.2.

By default, the *build.gradle* file for both these versions of Minecraft Forge, include the following lines:

```groovy
/*
// For those who want the bleeding edge
buildscript {
    repositories {
        jcenter()
        maven {
            name = "forge"
            url = "http://files.minecraftforge.net/maven"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.0-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'
*/

// for people who want stable
plugins {
    id "net.minecraftforge.gradle.forge" version "2.0.2"
}
```

By uncommenting the section which defiles the bleeding edge version, and commenting the stable out, the problem is resolved, as such:

```groovy
// For those who want the bleeding edge
buildscript {
    repositories {
        jcenter()
        maven {
            name = "forge"
            url = "http://files.minecraftforge.net/maven"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.0-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

/*
// for people who want stable - Incompatible with OS X 10.11
// See https://github.com/MinecraftForge/MinecraftForge/issues/2183
plugins {
    id "net.minecraftforge.gradle.forge" version "2.0.2"
}
*/
```

**Note:** This does mean you're using the bleeding edge of FG as the comment indicates, you should be prepared that it may mean you'll run into some stability issues down the line. I don't make any guarantees there.

**Comment by LOLDERP** [comment]
Quick thing i forgot to say if you install java 6 you should have this problem so just disable the csrutil and then delete the java 6 folders once you do that install java 8 and disable the csrutil and also they no longer have the extensions folder in java 8

**Comment by Hanse00** [comment]
That's a really bad idea, the files are there for a reason, mindlessly deleting files which may end being important for other systems, is not a good idea.

Just use the version of forge grade which doesn't have a problem with OS X.

**Comment by LOLDERP** [comment]
i delete java 6 itself so i didn't have the problem again.
I also did it to install java 8 
now i didn't need any of those stuff 
plus those stuff where outdated

**Comment by thecodewarrior** [comment]
Just for the record and for other people in the future, I was having this problem and the installer posted [here](http://www.minecraftforge.net/forum/index.php/topic,35273.msg185825.html) fixed it.

Link for the lazy: http://create.ife.no/vr/tools/j3d/java3d_1_5_2-macosx.pkg.zip
