### ISSUE TITLE
Block breaking particles appear more than once and in different positions

### ISSUE THREAD

**Issue by Eudaldca** [MinecraftForge/MinecraftForge#2184]
Basically, what the title describes. The thing is that this has been unnoticed, because it isn't too obvious. However, in [this video](https://youtu.be/J8v1Eo4QmMc) it is really obvious, because particles are abundant. And no, I've never noticed it happening in vanilla. That was clean forge install, latest recommended (11.14.3.1450). I'm not sure about this, but with littleloader the bug was more "intense".
![](http://i.imgur.com/LTqTelY.png)
For example, in the screenshot above, only the right beam is the real one.

**Comment by liach** [comment]
Are you sure that this is not a LiteLoader issue, since LiteLoader took part in this bug?

**Comment by LexManos** [comment]
How are those particles being produced?

**Comment by Eudaldca** [comment]
@LexManos A plugin makes those particles appear. In vanilla, this glitch doesn't reproduce.
@liach littleloader makes the issue worse, but it still exists with forge (no mods)

**Comment by LexManos** [comment]
Find me a way to reproduce this issue.

**Comment by Eudaldca** [comment]
I tried to ask, but I don't know, I don't have access to that plugin.

**Comment by GirafiStudios** [comment]
What plugin then at least?..

**Comment by Eudaldca** [comment]
Overcast Network's PGM. @GirafiStudios

**Comment by LexManos** [comment]
Cant reproduce, will need access to whatever plugin you're using to spawn all the custom prarticles, my guess is they are spawning them with invalid positions.
