### ISSUE TITLE
[1.7.10] Skulls aren't placable on the tops of fences.

### ISSUE THREAD

**Issue by tyrannozaurus** [MinecraftForge/MinecraftForge#2185]
As per this ticket: https://github.com/MinecraftForge/MinecraftForge/issues/2055
The issue seems to have been resolved for 1.8, and the ticket closed, but it's still not working for 1.7.10.
Steve's hand moves like he is placing the skull, but no skull appears on the fence.

**Comment by LexManos** [comment]
Why wasn't this reported a year ago?

**Comment by LexManos** [comment]
Would of been nice if you buggers would of told me this 6 god damn months ago -.- it's been sitting in my push queue because github derped -.-
