### ISSUE TITLE
Armor equips into wrong slot

### ISSUE THREAD

**Issue by EzerArch** [MinecraftForge/MinecraftForge#2187]
It was believed that this bug was fixed already.

This issue (http://www.minecraftforge.net/forum/index.php?topic=28881.0) is still happening in Forge 1448 and 1564 for Minecraft 1.7.10. No mods installed.

Screenshots show the setup.

![2015-11-14_10 40 57](https://cloud.githubusercontent.com/assets/6743303/11163595/ab09860a-8abc-11e5-9ed9-5971fd301fe9.png)
![2015-11-14_10 37 39](https://cloud.githubusercontent.com/assets/6743303/11163599/ab0df500-8abc-11e5-8684-6f8f971b5b30.png)
![2015-11-14_10 38 01](https://cloud.githubusercontent.com/assets/6743303/11163597/ab0c1852-8abc-11e5-9ac7-d67c94c77a5e.png)
![2015-11-14_10 37 48](https://cloud.githubusercontent.com/assets/6743303/11163596/ab0aae86-8abc-11e5-9105-424b4e318077.png)
![2015-11-14_10 38 15](https://cloud.githubusercontent.com/assets/6743303/11163600/ab0ed5ce-8abc-11e5-8baa-740834ff3ebe.png)
![2015-11-14_10 38 26](https://cloud.githubusercontent.com/assets/6743303/11163598/ab0ce8ea-8abc-11e5-8930-eccceb6c73a3.png)

**Comment by ganymedes01** [comment]
#1649
