### ISSUE TITLE
[1.8] PopulateChunkEvent no longer posted in ChunkProviderHell?

### ISSUE THREAD

**Issue by coolAlias** [MinecraftForge/MinecraftForge#2197]
Pre-1.8 I used various forms of the PopulateChunkEvent for doing some structure generation during world gen, specifically in the Nether; in 1.8, they no longer generate.

PopulateChunkEvent.Post is posted from ChunkProviderEnd and ChunkProviderGenerate, but not any of the other IChunkProviders such as ChunkProviderHell (where it used to be).

PopulateChunkEvent.Populate IS called for ChunkProviderHell, but not for ChunkProviderEnd, though it probably never was.

Anyway, was the Nether's PopulateChunkEvent.Post removed for a reason, or is this a bug?

**Comment by williewillus** [comment]
Probably missed in patches

**Comment by cpw** [comment]
Yup, fixed at 1.8.8. Noticed this when applying..

**Comment by Amsterdam1910** [comment]
If it is a problem with forge ? Could I resolve it by myself going in the forge configuration ? If it is possible could you tell me coolAlias how to change it and fix it ? Thanks !

**Comment by williewillus** [comment]
It's fixed in 18.8, if you are still using 1.8.0 just update to 1.8.8

**Comment by Amsterdam1910** [comment]
We can't because zss mod is stuck to version 1.8

**Comment by chibill** [comment]
is it a core mod? if not it should work on 1.8.8

**Comment by LexManos** [comment]
Then sucks to be you, yell at the 'zss mod' maker.
