### ISSUE TITLE
BlockState Abstraction

### ISSUE THREAD

**Issue by rubensworks** [MinecraftForge/MinecraftForge#2198]
As mentioned in #2163, I am looking for an abstraction for the BlockState system, so that it can be used without needing to register blocks.
First, let me explain why I would need such a thing.

I have the following multiblock cables:
![Cables](http://imgur.com/LUFZwdu.png "Cables")
On the left, you can see a single cable block, on the right you can see another cable block that has several *parts* on it.
Currently, these parts are actually implemented as *blocks*, while they shouldn't be.

These parts have different properties, like for example if they active or not, or their rotation, which influences their appearance (=model).
These part id's are simply added to the tileentity of this cable block, so the part block instances are never actually used.
My TESR then simply renders the virtual blockstates for all these parts.
I however did implement them as blocks, because I wanted to use the nice blockstate property abstraction, which makes it possible for me to easily define models for these different *part-blockstates*.

Ideally, I would like to be able to somehow register such virtual blockstates, without needing to register a separate block for this.
I don't know if this would be possible, or if there would be better alternatives to this, but I am happy to discuss this.

I can imagine that such a system would be needed for many other mods as well (BuildCraft, Thermal Dynamics ...), so it could be interesting to add this functionality to Forge.

Note that it is not possible to just add these *part-properties* to the cable block itself, because these properties depend on the actual part that is used, which can be different on a per-part basis.

**Comment by DanielHuisman** [comment]
Can't you use the ExtendedBlockState and unlisted properties for this?
I haven't used them myself, but I'm guessing you can use save them in your tile entity's NBT tags.

**Comment by rubensworks** [comment]
@DanielHuisman No, because I actually want those properties to be *listed*, so that I can use them to determine the variant model of the part.

**Comment by AlexIIL** [comment]
Also because the parts may come from add-ons, or separate mods that would require overriding the block-state file on a per add-on basis- which is not pretty as you would somehow have to skirt around the vanilla resource pack system and somehow join them together to make it work.

**Comment by LexManos** [comment]
You should use Extended Block states. And register extra models through your mod as needed.
You can always dynamically register state mappings, and/or use a 'smart model'.
We are not going to re-write the Block state system to not use blocks, that's retarded.
