### ISSUE TITLE
Can't run any gradle commands for 1.8.8 yet?

### ISSUE THREAD

**Issue by 61352151511** [MinecraftForge/MinecraftForge#2202]
I know Forge 1.8.8 just came out yesterday, so we might not be intended to be able to make mods for it yet, but they're being released so why wouldn't we be?

Anyway any time I attempt to run a gradle command (setupDecompWorkspace, cleanCache, setupDevWorkspace, clean, etc.) It errors, the gist is 'There are no mappings for MC 1.8.8' here's the entire console log http://pastebin.com/4bFtnn09

Mappings in my gradle build file are snapshot_20151123

**Comment by ShetiPhian** [comment]
The build.gradle that is in the 1.8.8 zip has "snapshot_20141130"
but cpw posted on twitter you needed to use the same mappings as forge, and its build.gradle has "snapshot_nodoc_20141130"

One of those should work.

**Comment by cpw** [comment]
Use forgegradle2.1. Anything else is not compatible. You might need to refresh dependencies too. And yes this is extremely provisional at the moment.
