### ISSUE TITLE
Add net.minecraft.server.dedicated.ServerHangWatchdog to the list of exclusions in TerminalTransformer

### ISSUE THREAD

**Issue by JBYoshi** [MinecraftForge/MinecraftForge#2203]
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fml/common/asm/transformers/TerminalTransformer.java#L136

**Comment by simon816** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/2089 should have fixed this
