### ISSUE TITLE
[1.8.8]Buttons and levers don't place

### ISSUE THREAD

**Issue by The-Fireplace** [MinecraftForge/MinecraftForge#2204]
With Forge installed, levers and buttons won't place. Tested on the latest version, Forge 11.14.4.1581.

**Comment by GirafiStudios** [comment]
They can place in certain places, but they are indeed acting wonky.

**Comment by The-Fireplace** [comment]
Can you give me an example of where they do place? I haven't been able to make them place anywhere.

**Comment by GirafiStudios** [comment]
If you make a 1x1 hole, you can place it on the sides within that hole.

**Comment by williewillus** [comment]
Probably a patch error in Block, maybe canPlaceBlockAt?

**Comment by cpw** [comment]
Definitely. There's new solid side tests shared with the button, and I probably missed patching it properly..
