### ISSUE TITLE
[1.8.8] Clicking "no" on the "missing blocks/items" screen freezes the game

### ISSUE THREAD

**Issue by ljfa-ag** [MinecraftForge/MinecraftForge#2206]
When I try to open a world where the "missing blocks/items" screen appears, clicking the "no" button will not go back to the list of worlds, but rather freeze the game and make it not respond, so that I have to kill Java:

![not-responding](https://cloud.githubusercontent.com/assets/3437174/11398982/9e9966c6-9384-11e5-951c-7dd5a9c24833.png)

At the same time, a stack trace is printed to stderr, see the log: [fml-client-latest.log](https://github.com/MinecraftForge/MinecraftForge/files/43911/fml-client-latest.log.txt)
Clicking "yes" works fine.
This happens with Forge version 11.14.4.1589.

**Comment by clienthax** [comment]
This has happened since cpw "fixed" the registry remapping back in 1.8

**Comment by ljfa-ag** [comment]
Nice, that was quick ^^
