### ISSUE TITLE
[1.8 and 1.8.8] Item lighting bug in the third person mode

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#2215]
![2558-11-24_18 14 09](https://cloud.githubusercontent.com/assets/6128413/11432653/7c533724-94e5-11e5-8a53-494e767c3d9c.png)
![2558-11-24_18 14 12](https://cloud.githubusercontent.com/assets/6128413/11432654/7cbf60ac-94e5-11e5-86e4-c5a37141edc1.png)

**Comment by RainWarrior** [comment]
First screenshot appears to be broken for me, can you please reupload it?

**Comment by SteveKunG** [comment]
![2558-11-27_14 39 54](https://cloud.githubusercontent.com/assets/6128413/11436060/a7250d14-9513-11e5-9823-1cd5f197005f.png)
![2558-11-27_14 40 05](https://cloud.githubusercontent.com/assets/6128413/11436061/a72a7d80-9513-11e5-8389-e286c04bbe4c.png)

My bad internet. Sorry!
