### ISSUE TITLE
[1.8.8] Block updates cause performance drops

### ISSUE THREAD

**Issue by gigaherz** [MinecraftForge/MinecraftForge#2220]
My [magic mod](https://github.com/gigaherz/ElementsOfPower) has spells that spawn balls of dust and flowing water. After upgrading to 1.8.8, I noticed that using those spells resulting in massive stuttering of the game, coindicing with the blocks changing state.

This isn't just a slowdown, there's short pauses in between bursts of normal framerate, causing visible stuttering.
 
So far as I can tell, It's not related to fluids because my dust clouds are non-fluid blocks, and it's not specific to mod blocks because it happens to water blocks too.

Using Shift-F3 to show the pie chart didn't reveal anything interesting.

EDIT: Uploaded an alpha build of the mod in case it's needed for testing. [here](https://github.com/gigaherz/ElementsOfPower/releases/tag/0.1alpha).
To reproduce using my mod: spawn a creative wand or staff from the creative tab, with the wand selected, hold rightclick, press '2' (or '4') up to 5 times in a row, then release.

**Comment by Actuarius** [comment]
@williewillus added labels [Performance]

**Comment by LexManos** [comment]
You need to be more specific about this. Just shoving a 'Here my big ass mod debug it for me!' is not gunna fly.
Block state changes DO cause re-renders of the chunks, doing A LOT without batching and other psudo-optimizations will cause issues.
Sounds more like a issue in the way your mod is written not in Forge/MC.

**Comment by gigaherz** [comment]
Yeah I'm not really sure what changed between 1.8 and 1.8.8 in that regard. I'm not even certain anymore, that it did actually work better in 1.8...
All I really know is that right after upgrading to 1.8.8, I started noticing uneven framerate when using spells with large effects (mostly ball shapes), which I never noticed in the old 1.8.
To be honest, it doesn't even bother me that much anymore. The more massive spells cause framerate issues, people will have to deal with that. I'd be ok with this issue getting closed as incomplete/hard to reproduce.

**Comment by williewillus** [comment]
concur that it was between 1.8 -> 1.8.8, but also can't pin it down quantitatively

**Comment by LexManos** [comment]
Closed until further information is provided.
