### ISSUE TITLE
[1.8 & 1.8.8] Block.canSilkHarvest is called with World.getBlockState

### ISSUE THREAD

**Issue by MattDahEpic** [MinecraftForge/MinecraftForge#2223]
Attempting to use the IBlockState provided in a call to `canSilkHarvest` gives you the state _after_ the block was broken, being air. Offending code is at https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/block/Block.java.patch#L152 and example of breaking behavior is at https://github.com/MattDahEpic/MobDropOres/blob/1.8.8/src/main/java/com/mattdahepic/mobdropores/block/BlockMobOre.java#L35

**Comment by LexManos** [comment]
This has been fixed for a while.
