### ISSUE TITLE
[1.8.8] ClassLoader mismatches

### ISSUE THREAD

**Issue by superckl** [MinecraftForge/MinecraftForge#2227]
It appears the ClassLoaders used for Objectweb ASM and Minecraft classes are different.

Test Case:
http://pastebin.com/sw2bFCjn

Output:
http://pastebin.com/WzkKJj3t

This causes a `ClassNotFoundException` in `ClassWriter.getCommonSuperClass` when resolving superclasses, due to them using the ClassLoader of their class:

```
ClassLoader classLoader = getClass().getClassLoader();
```

I'm unsure how to resolve this without creating a custom `ClassWriter`.

**Comment by liach** [comment]
Yes asm is default url class loader, but mc classes are launchwrapper ones.

**Comment by cpw** [comment]
This is by design. It's not possible to load MC in the same classloader and have coremods still work.

**Comment by superckl** [comment]
Why has this changed in 1.8.8? Am I forced to use my own ClassWriter then?

**Comment by cpw** [comment]
It hasnt? It's always been this way..

**Comment by superckl** [comment]
Did you read the output of the test case I made? It hasn't.

**Comment by superckl** [comment]
I've created a more clear test case. You can find the source here:
https://github.com/superckl/BiomeTweaker/tree/1.8.8/src/test/java/classloader/test

Output of run:
http://pastebin.com/JCEk2kaV

I should mention, the crash only occurs when running in an obfuscated environment, though the ClassLoaders are different regardless...

**Comment by cpw** [comment]
Please bisect and figure out where this change I never made appeared. I'd be interested to know..

**Comment by superckl** [comment]
Did you, by chance, make a change in 1.7.10 -> 1.8 that could cause this? Apparently I'm a terrible dev and didn't test my 1.8 versions in an obfuscated environment. The ClassLoaders are different in 1.8 and 1.8.8, but the same in 1.7.10.

**Comment by diesieben07** [comment]
Honestly, relying on the default implementation of `getCommonSuperclass` is a bad idea. It works most of the time, but as the code itself says, it cannot possibly work all the time. Which is what you are running into here.

**Comment by liach** [comment]
I found its cause @cpw - MinecraftForge/FML#649 and MinecraftForge/FML#650. This issue shall be considered as "caused by bad modding practice"

**Comment by superckl** [comment]
So Mixins require this issue to be a thing? Fantastic.

**Comment by diesieben07** [comment]
Even without this loading classes while transforming them will cause issues. I have run into this problem in 1.7.10 and even 1.6.4 before. So it is not a new thing in 1.8, just maybe a bit more likely.

**Comment by superckl** [comment]
All right. Thanks for the help.

**Comment by Blargerist** [comment]
Thanks for the info, @liach and @diesieben07

**Comment by cpw** [comment]
Yeah, this will also become more of an issue because Java 8 requires frames, sometimes, if the classver says so..

**Comment by diesieben07** [comment]
Actually that was already in Java 7.
