### ISSUE TITLE
[1.8.8] Armor overlay rendering is not working.

### ISSUE THREAD

**Issue by GirafiStudios** [MinecraftForge/MinecraftForge#2235]
Vanilla 1.8.8:
![ardsdkd](https://cloud.githubusercontent.com/assets/6305377/11554792/6aab4092-999b-11e5-828a-0240da2f93d6.png)

Minecraft Forge, version 11.15.0.1608:
![zea0f88](https://cloud.githubusercontent.com/assets/6305377/11554791/638df818-999b-11e5-8f69-d322d40cd6db.png)

**Comment by killjoy1221** [comment]
I blame this else. It wasn't there in 1.8.
https://github.com/MinecraftForge/MinecraftForge/blob/1.8.8/patches/minecraft/net/minecraft/client/renderer/entity/layers/LayerArmorBase.java.patch#L31

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/1f20abde59a9922ccfc2c525046e0c9f57504962
Cpw missed a commit when syncing.

**Comment by killjoy1221** [comment]
That commit broke the overlay textures. The leather armor is supposed to render with the colors, bind the overlay, reset colors, then render again. with that commit, it just renders the color.

**Comment by LexManos** [comment]
Hurr, ya, this is the revert of it: https://github.com/MinecraftForge/MinecraftForge/commit/49d4005805d9d8ccf26ccf27626d331a7068ce38 That wasnt caught by cpw. I knew one of them wasn't ;)

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/12cd28715a6a53d055718a3cb08e6a63cf21e2bd
