### ISSUE TITLE
Error constructing mod (happens with any random mod) [1.8.8]

### ISSUE THREAD

**Issue by Elec332** [MinecraftForge/MinecraftForge#2237]
I get an NPE on FML's side when constructing mods. I tried it with 1 mod installed, and it still happened. I have been able to reproduct this with a couple of different 1.8.8 mods.
(I crashed on every single mod I tried, possibly an borked MC/Forge installation?)
Crash log: http://pastebin.com/1GZjhuA8

**Comment by DanielHuisman** [comment]
Update to the latest Forge, this was fixed in 1608 or 1609

**Comment by liach** [comment]
Fixed in #2231

**Comment by Elec332** [comment]
Aha, I must've missed that, im extremely sorry.
