### ISSUE TITLE
[1.8.8] Netty logs warning when spawning custom entities

### ISSUE THREAD

**Issue by fnuecke** [MinecraftForge/MinecraftForge#2246]
I've run into an issue with the following being logged to the console every time a custom entity is spawned:
```
Dec 07, 2015 10:23:52 PM io.netty.channel.ChannelOutboundBuffer safeSuccess
WARNING: Failed to mark a promise as success because it is done already: DefaultChannelPromise@485b80e8(success)
```

This looks pretty much like #1848, but I'm only seeing this exactly when calling `world.spawnEntityInWorld`. Note that I only tested this in *singleplayer,* which as I understand is different to #1848, where it only happened on dedicated servers?

I've created a (pretty much) minimal repro-mod here: https://github.com/fnuecke/mcforge-netty-issue
It contains an item that can be used (right-click in air) to spawn a custom entity that's simply an empty subclass of an empty minecart. When the entity is spawned, the above message is logged, in my dev-env as well as when run via the MC vanilla launcher.

Is this an issue with my setup (I read something about downgrading the netty library in the other issue?) or an issue in 1.8.8?

Any pointers would be very much appreciated.

**Comment by LexManos** [comment]
Its an issue with netty that 1.8.8 ships/required. There isn't anything we can do about it on our end.

**Comment by cpw** [comment]
It'll happen anywhere a server runs now. In 1.8 the dedi server was shipping a newer netty so you only saw it there. In 1.8.8 the versions are in sync and *required*. So it'll be visible everywhere.

**Comment by fnuecke** [comment]
All right, just wanted to make sure it's not an oversight on my end somewhere (forgetting to register something or such). Thanks. Feel free to close this or leave it open as an info for others as you see fit, then!
