### ISSUE TITLE
FML searches for mods in JRE/JDK provided jars

### ISSUE THREAD

**Issue by gabizou** [MinecraftForge/MinecraftForge#2249]
After a long period of not debugging recently (roughly a few weeks in SpongePowered development), I noticed that FML will spend minutes searching for mods when running in debug mode (depending on Forge 1577), and in debugging the Loader, I found that the `ModDiscoverer` is searching almost all the available jars in the JDK. In fact, the first 26 jars of the 89 jars included are from the JDK:

![debug](http://puu.sh/lNAJp/1239f63f37.png)
![jdk](http://puu.sh/lNAv4/005f1744d5.png)

Now, I did speak about this in #ForgeGradle, but upon further inspection, there IS a small list of [ignored jars](https://github.com/MinecraftForge/MinecraftForge/blob/90829a316439efe7ddeb8f03b030e00366d8d03c/src/main/java/net/minecraftforge/fml/common/ModClassLoader.java#L43), but clearly these jars could also include some more saner understandings that:
1) Mod jars wouldn't by default exist in the JAVA_HOME directories (recursively)
2) Mod jars SHOULDN'T even exist in the JAVA_HOME directories

Furthermore, there are other included jars such as the various Minecraft dependencies that aren't being excluded (I mean, let's be honest, there aren't any such mods ever going to be found in the MC dependencies).

I'm pretty sure that if these were ignored, not only would this debugging issue get better, but mod loading at runtime would result in faster load times.

Just dumping my class path of jars according to FML:
https://gist.github.com/gabizou/c8bb37613e658bcb2a97
If you care to note, of those that are just dependent on the project, a majority are just from dependencies of Minecraft, Forge, and Java.

**Comment by kashike** [comment]
19/79 here:
![i](https://miserable.ninja/i/ZjA1Z.png)

**Comment by gabizou** [comment]
Just going to ping @cpw.

**Comment by cpw** [comment]
Yeah, I want to remove all classpath scanning and get forgegradle's gradle start to tell me where the mod runtimes are instead.

**Comment by gabizou** [comment]
@cpw I'm not sure I'm following. Granted FG does launch the client/server, this issue is more ominous where mod dependencies are involved. With any of the mod dependencies available either through the current class output directories, or through a traditional gradle dependency for compiling, they are technically included in the mod discovery that ModDiscoverer performs with the `ModClassLoader`. 

The primary issue is that in order for that sort of thing to be filtered by FG at runtime is that the mods themselves would have to ship json files indicating their dependencies as well (much like the current TODO in `ModDiscoverer`). At the least for now though, I've written a PR that at the least ignores any jars found in the JAVA_HOME directories (and sub directories thereof).

**Comment by cpw** [comment]
@gabizou classpath scanning for mods is basically legacy. No one should be putting mods in other jar files than their own. 

The only purpose it still truly serves is loading mods in development environments. And that can be fixed by forgegradle simply using the --mods argument to the launch code to point at the compiled mod code.

So, why bother supporting classpath scanning at all?

**Comment by gabizou** [comment]
Well, if you're fine with removing it, by all means. I mean hell, I don't think it'd be too difficult to provide the --mods argument generation since the build.gradle would clearly define the mod dependencies (and transitive dependencies provided that mods distribute their poms).

**Comment by cpw** [comment]
That's the plan!

**Comment by kashike** [comment]
@cpw I'm curious how maven dependencies are included, since those are not part of the compiled code. I'm assuming FG will pass those jar locations into `--mods` as well?

**Comment by cpw** [comment]
They can be supplied via the mods command line argument, or compiled into a modlist and supplied that way.. (Modlist argument then). Mods argument can be repeated on the command line for multiple locations..

**Comment by asiekierka** [comment]
The pull request (#2250) was closed, but the issue never was. Any updates?

**Comment by 0xilly** [comment]
@asiekierka The master was branch was deleted and GitHub auto closed about 60 PRs

**Comment by asiekierka** [comment]
@Illyohs I found that out later, but it's probably good to keep a reminder here as those PRs could easily be forgotten about.
