### ISSUE TITLE
[1.8.0]B3D models refuse to rotate

### ISSUE THREAD

**Issue by Tarig0** [MinecraftForge/MinecraftForge#2251]
I have the following in a json file
please note I haven't implemented facing yet so type is being used to display the issue
```json
{
  "variants": {
    "camo=false,type=cube": {"model":"camolib:slope.b3d"},
    "camo=false,type=slope":{"model":"camolib:slope.b3d","y":90}
    }
}
```

This points to a b3d model of a 45 degree slope created in bartender and exported using fry's plugin. I had to change the point of origin of the shape to get it to slide into place but other than that pretty simple.

Results
![untitled](https://cloud.githubusercontent.com/assets/4108180/11674081/6bb34b16-9deb-11e5-8d4c-4adce6ae7ca0.png)

![image](https://cloud.githubusercontent.com/assets/4108180/11673941/7cd38b8c-9dea-11e5-94d6-2644fbf2701f.png)

as you can see the shape does not rotate between the two states.

**Comment by Tarig0** [comment]
Also verified that Rotation{"y":90} works for json models but not my b3d models

**Comment by Tarig0** [comment]
Also to note the default forge transforms do seem to apply, at least for third person

**Comment by Tarig0** [comment]
I have found a work around by exporting the b3d models with their rotation baked in. I can also achieve the same results by switching to OBJ models, and applying json rotations, but my camo smart model doesn't seem to be able to map UVs correctly on these.

**Comment by williewillus** [comment]
add "flip-v": true in the "custom" section to make OBJ's map UV's correctly

**Comment by Tarig0** [comment]
The flip-v has no effect, probably because i'm applying the textures through a smart model after the base obj model is baked.

**Comment by RainWarrior** [comment]
Make sure you don't have any additional transformations in "defaults" - they don't mesh well with per-property ones.

**Comment by Tarig0** [comment]
OK looks like the issue is that the models I have in shown in the screens did not have any transforms on them, just an origin change.

When I attempt to rotate an object with transforms baked in, it functions as expected
