### ISSUE TITLE
[1.8.8] In-game config scroll box contents overflow their bounds

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#2254]
![2015-12-09_21 25 52](https://cloud.githubusercontent.com/assets/916092/11707618/aed6d018-9ebb-11e5-8a56-5951559bf2b7.png)

The mod list and the mod description overflow their bounds.

**Comment by tterrag1098** [comment]
Easy solution, just render the dirt background like normal.

**Comment by LexManos** [comment]
Naw, its proper in master, but someone enabled the in-game GUI in 1.8.8 without the changes I did in 1.8.0.
@cpw should come along sometime and do a branch merge. Also, we should probably move 1.8.8/9 to master.
