### ISSUE TITLE
[1.8.8] In-game config only shows tooltips for titles, not values

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#2256]
Hovering on title: tooltip. :white_check_mark: 
![2015-12-09_21 31 55](https://cloud.githubusercontent.com/assets/916092/11707667/4cf3bce8-9ebc-11e5-84a2-2da37136619a.png)

Hovering on value (large area for clicking): no tooltip :x: 
![2015-12-09_21 31 48](https://cloud.githubusercontent.com/assets/916092/11707668/4cf478c2-9ebc-11e5-9673-197bf416f43a.png)

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]

**Comment by LexManos** [comment]
Honestly I dont consider this a bug, I consider it a design choice, I'd rather not have my view of the config value obscured when im looking at it specifically. You can override this behavior if you want by subclassing the Entry class you're using and doing your own hover checker.

**Comment by mezz** [comment]
I wouldn't consider it a bug either, it's an enhancement. I would like the forge config to look nicer but I haven't gotten around to messing with it so I made an issue to keep track instead.
