### ISSUE TITLE
[1.8.8] In-game config value tooltips show default values twice

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#2257]
![2015-12-09_21 31 55](https://cloud.githubusercontent.com/assets/916092/11707694/8ef3bb48-9ebc-11e5-8225-a2f015d5ad97.png)

The blue default values is nice, the yellow one is redundant.
I think the yellow part is used for the .cfg file in addition to the in-game config.

**Comment by LexManos** [comment]
The yellow one is your comment you made when you created the config property.

**Comment by mezz** [comment]
Forge's `Configuration.getBoolean` adds that to the end of the comment automatically.

**Comment by LexManos** [comment]
Interesting wonder why its not doing that for the Forge configs. Guess we could add a filter for that one line. Remind me tomarrow.

**Comment by ghost** [comment]
Made a fix proposition for this issue #3338 . First time contributing. Forge configs did not have the [default: ] tags in comments so they did not show. In PR the tag is searched from config comment lines and removed if found.

![changed](https://cloud.githubusercontent.com/assets/6240256/19792018/4b111972-9ccf-11e6-833f-af090afd3b47.png)
