### ISSUE TITLE
README should mention that source download refers to MDK and link to the better documentation

### ISSUE THREAD

**Issue by dsalsman-rdi** [MinecraftForge/MinecraftForge#2260]
A.) There should be a link to this page: http://mcforge.readthedocs.org/en/latest/gettingstarted/

B.) The instructions here should reference the MDK download, as that acronym is not as intuitive as you'd think an easily confused with MD5.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Cleanup]

**Comment by terranix** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/2979
