### ISSUE TITLE
[1.8.8] setHarvestLevel returns void rather than a Block

### ISSUE THREAD

**Issue by ThePsionic** [MinecraftForge/MinecraftForge#2261]
If it would return a Block, it could be used in chaining, which is currently not possible.

**Comment by liach** [comment]
It does not worth to patch to add such a utility method.

**Comment by ci010** [comment]
You could write a BlockAdaptor for this feature though.

**Comment by LexManos** [comment]
Not really worth it, the standard setup would be to set this in the initalizer itself. But also could always add a bouncer to your custom block class anyways. Whats the point? Changing the return value breaks binary comaptibiltiy and screws up the obf.
