### ISSUE TITLE
Readme for contribution should mention that git is required

### ISSUE THREAD

**Issue by Tarig0** [MinecraftForge/MinecraftForge#2262]
I was having issues running gradlew.bat setupforge

Turns out you now need git installed and in your environment paths. This is not mentioned in the contributors section

**Comment by matthewprenger** [comment]
How would you clone the forge repo without git? It is a ***git*** repository after all.

**Comment by Tarig0** [comment]
maybe I did something weird, for some reason it kept saying couldn't start git

**Comment by Spartan322** [comment]
try starting the command prompt in git bash, this is what happens when git doesn't want to fix the path to include itself
