### ISSUE TITLE
Remove deprecated methods in LanguageRegistry

### ISSUE THREAD

**Issue by liach** [MinecraftForge/MinecraftForge#2267]
Deprecated methods:
https://github.com/MinecraftForge/MinecraftForge/blob/1.8.8/src/main/java/net/minecraftforge/fml/common/registry/LanguageRegistry.java#L83-L242

And a patch which calls the deprecated method: https://github.com/MinecraftForge/MinecraftForge/blob/1.8.8/patches/minecraft/net/minecraft/client/resources/LanguageManager.java.patch

**Comment by Adaptivity** [comment]
I want to reminder @LexManos about it since he promised to take a look at this in 1.9 update (instead of 1.8). I hope it's not a big problem.

**Comment by williewillus** [comment]
LanguageRegistry removed in 1.9 refactors

**Comment by Actuarius** [comment]
@williewillus closed this issue

**Comment by liach** [comment]
By the way what is @Actuarius? Is it another @minecraftforgebot?

**Comment by RainWarrior** [comment]
yup
