### ISSUE TITLE
[1.8.8] Enchantment Table Multiple Enchantment Issues

### ISSUE THREAD

**Issue by oitsjustjose** [MinecraftForge/MinecraftForge#2273]
![2015-12-13_20 23 58](https://cloud.githubusercontent.com/assets/3887324/11771618/7c91162a-a1d8-11e5-97b4-5d8c3eca61d0.png)

Multiple enchantments are still not applying properly from a vanilla enchantment table. Looks like a similar issue might've been fixed on Forge 1.8 Build 1.8-11.14.1.1334, but I'm still trying to see what it was specifically.

**Comment by LexManos** [comment]
Provide exact steps to reproduce, also remove NEI/Other mods.

**Comment by GirafiStudios** [comment]
I tried testing with Forge 1628 and no mods. Most of the times when enchanting an item one of the enchants showed up more than once. Can't really seem to find any pattern to this issue tho.

**Comment by williewillus** [comment]
Is it enchanting twice or showing up twice? There's this weird issue I have in ProjectE 1.8.0 and 1.8.8 where the EMC tooltip gets added twice to the itemstack. Recheck the NBT tag of the item with NBTExplorer or something, the enchanting might be correct but is showing up wrong

**Comment by GirafiStudios** [comment]
@williewillus yeah the same thing happens with the Waila mod name tooltip. But only after you have enchanted an item which have an enchantment that show up more than once.

**Comment by oitsjustjose** [comment]
Here's some proof for you Lex :)

![forge_proof](https://cloud.githubusercontent.com/assets/3887324/11776212/eba47d5e-a20a-11e5-9391-a84ba7689cc1.png)

I also went and took a look to see if it was a display issue or enchanting issue; it's an enchanting issue:

![nbt_proof](https://cloud.githubusercontent.com/assets/3887324/11776224/f7962edc-a20a-11e5-8c1c-e809b1265f95.png)

Let me know if there's anything else at all I can do!

**Comment by cpw** [comment]
The patches from 1.8 didn't apply well. I probably mangled the hand application. *sigh*

**Comment by LexManos** [comment]
Ya, you inverted the condition in https://github.com/MinecraftForge/MinecraftForge/blob/1.8.8/patches/minecraft/net/minecraft/enchantment/EnchantmentHelper.java.patch#L28
Tho, things are still being weird in my tests. Adding multiple enchantments of different types when enchanting now...
