### ISSUE TITLE
Need getter function for fire field in Entity class

### ISSUE THREAD

**Issue by jabelar** [MinecraftForge/MinecraftForge#2274]
There is an int field called fire in the Entity class. This is private, but there is a setter method called setFire() and also extinguish() but there is no getter function. A getter function is needed to avoid reflection if you're trying to override a lightning damage source, and generally it is good practice to have public getter method for anything that has a public setter method.

**Comment by liach** [comment]
Can this be resolved by an AT? (AccessTransformer)

**Comment by williewillus** [comment]
reflection and AT's would be usually used in this case.
Not sure on what Forge's stance is on patching in getters, but I don't think that happens often

**Comment by jabelar** [comment]
I know you can do this with reflection and access transformers. But so can most of the things that Forge does. Forge is about creating public interfaces to those things that modders might want to modify. Anyway, just a suggestion.

**Comment by Parker8283** [comment]
You can always add this to the Forge AT so that everyone has it. Not saying it'll be accepted, but it's an option, and a smaller diff to merge.

**Comment by jabelar** [comment]
Okay, I thought you were talking about modder doing the AT. Yeah, it could be in Forge AT (if accepted).

**Comment by mezz** [comment]
This is definitely best solved by an AT.
If you think that more people need this, you can make a PR to add it as an AT to Forge, but nobody else has asked for this in a year so I don't think it's widely needed.
