### ISSUE TITLE
Replace forge gif with high-quality apng

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#2277]
[This GIF](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/resources/assets/fml/textures/gui/forge.gif) and its terrible GIF artifacts should be replaced with a high-quality APNG, without the GIF artifacts.

[This](https://github.com/leonbloy/pngj) seems to have support for APNG, but I'm not sure if its license is compatible with Forge/MC.

**Comment by diesieben07** [comment]
Such a simple animation doesn't need to have artifacts in GIF, it just needs to be exported properly. GIF "artifacts" are dithering, because GIF has a limited set of colors, but this animation has only 2 colors.
So no need to embed a whole new library.

**Comment by SoniEx2** [comment]
APNGs could be used as a replacement for MC's animation format.

**Comment by diesieben07** [comment]
And what is wrong with the current way things are done? This is just unneeded complexity. APNG is (admittedly sadly) not very widespread, but this is not really the place to fight this war, is it.

**Comment by SoniEx2** [comment]
There is nothing wrong with the current way MC animations are done. I am not here to complain. I'm just trying to explore APNG as a better fit for games and game engines. Seems like about the only reasonable use-case for it.

**Comment by liach** [comment]
Do not make players who have bad computers sad.

**Comment by SoniEx2** [comment]
@liach I don't see how replacing an animated GIF with an APNG is gonna make you sad? You're replacing an animation with an animation.

**Comment by liach** [comment]
Will it hurt computers with bad graphic cards? Or make minecraft slower? If you want to add this you should add a configuration option to disable this, since minecraft is not a game just for rendering some beautiful pictures. By the way, you might be able to make coremods to achieve this idea.

**Comment by SoniEx2** [comment]
@liach It already turns a 256x256x20 (or w/e, didn't check) GIF into a single-image 256x5120 or something. Changing it to use APNG would just turn a 256x256x20 APNG into a single-image 256x5120 instead, and because on the GPU all textures are uncompressed, it will have no performance difference once it's loaded.

**Comment by LexManos** [comment]
No, We do not need this, and we are not swapping vanillas animation system to this -.-

**Comment by SoniEx2** [comment]
I didn't mean completely replace the vanilla system. Just add the option.

I do want you to replace that GIF tho.

**Comment by heldplayer** [comment]
@SoniEx2 Why not make a better version and make a pull request, rather than bitch for others to do this stuff for you, like you do every time.

I'm going to repeat this again for you, if you want stuff changed or added to Forge, supply a proper PR rather than make a bitchy issue.

**Comment by SoniEx2** [comment]
@heldplayer Pretty sure I was being polite.
