### ISSUE TITLE
[Forge AT Request] Re-publicize age and delayBeforeCanPickup in EntityItem

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2278]
Before 1.8, these two fields were public. In 1.8+. the only way we can manipulate age is to 1. get it and 2. set it to never despawn. Likewise for the delay.

It was useful having this because you could directly manipulate the pickup delay of items that you dropped, etc.

There doesn't seem to be a setter, from what I've noticed

**Comment by clienthax** [comment]
pickup delay has a setter setPickupDelay
as a work around you could use a AT directly in your mod or modify the nbt of the entityitem

**Comment by williewillus** [comment]
I ended up using a methodhandle for this :P
