### ISSUE TITLE
[1.8.8] Textures on OBJ models are mirrored both horizontally and verticlly

### ISSUE THREAD

**Issue by Nuchaz** [MinecraftForge/MinecraftForge#2284]
It seems that all OBJ models have their textures mirrored both vertically and horizontally. I've tried a few different models, even tried different 3D modeling programs so make sure it wasn't something screwy with the exporter. One of the models, my Bookcase in BiblioCraft is basically the same model I used in 1.7.10 with no problems. I had to edit it a little to add texture support using the mtl command and whatnot. 

I tried with both Forge versions 11.15.0.1618 and I just updated and tried with 11.15.0.1634. The issue is still present in the newest version.

I ran an experiment to see if the obj exporting in my 3d modeling package was acting funny. I tried 5 different 3d modelers for this experiment. I used Modo Indie 801, Modo Indie 901, 3DSMax 2014 student edition, Blender 2.73 and Blender 2.76. I created just a 1x1x1 cube with a texture that would make it easy to see if it was flipped or rotated.

My primary modeling package I like to use is Modo. Both versions of Modo gave me the same result. All the UVs / textures are mirrored vertically and horizontally.
Here is what is should look like.
![modo_example](https://cloud.githubusercontent.com/assets/3758618/11833460/e46e3980-a390-11e5-8869-8e4790ec8759.png)

Here is what it looks like in game.
![modo_ingame](https://cloud.githubusercontent.com/assets/3758618/11833463/e8113510-a390-11e5-8bec-b6c27ae3ca25.png)

So next I tried 3DSmax 2014 student edition to see how that fared. I had some odd results with 3DSmax, not only are they mirrored, but a couple of faces were rotated in game that weren't rotated inside of 3DSmax. 
Here is what it should look like:
![3dsmax_example](https://cloud.githubusercontent.com/assets/3758618/11833472/05cde580-a391-11e5-85bb-6e84de756fbd.png)

Here is what it looks like in game:
![3dsmax_ingame](https://cloud.githubusercontent.com/assets/3758618/11833473/07e551fa-a391-11e5-98cd-d9d92a0203bb.png)

Finally for good measure, I gave Blender a try. I have been running my models through blender anyway (Modo->.fbx->Blender->.obj) because for some things Modo like to express values in the OBJ files as scientific values (e.g. 1.0485e5,  using e as the *10^ as can be done with a calculator). Anyway, both version of Blender I tried produced the same result. World positioning is a little different with Blender it seems, but that is irrelevant, the textures / UVs are the issue here. As we can see, they are mirrored both ways like Modo.
Here is what it should look like:
![blender_example](https://cloud.githubusercontent.com/assets/3758618/11833573/ef58f4b0-a391-11e5-8ce6-fe10b44fc594.png)

Here is what it looks like in game:
![blender_ingame](https://cloud.githubusercontent.com/assets/3758618/11833575/f3f88ff8-a391-11e5-9026-ea667d4a9a11.png)

For reference, this is the json, obj, and mtl files used for this as well as the snippet of code I am using to load my models. 
Code to load my models as my getExtendedState method on the block: http://pastebin.com/j3aXN0AR
My .json for the model: http://pastebin.com/NF4k0C3M
My .mtl: http://pastebin.com/J2jw02Gq
My .obj (exported from Modo Indie 901): http://pastebin.com/9e48J1f9

I can't find any reason why anything I am doing on my end would make the textures mirror. I am using the same techniques for exporting I did in 1.7.10 and earlier which always worked. After my experiment I figured I should make an issue on here and share my results since I think this needs to be addressed. 

Thanks!

**Comment by RainWarrior** [comment]
add "custom": { "flip-v": true } to the blockstate json, after the "model" line.

**Comment by Nuchaz** [comment]
That worked perfectly, Thanks!
