### ISSUE TITLE
GPU memory exhaustion Forge 10.13.4.1566

### ISSUE THREAD

**Issue by darthvader45** [MinecraftForge/MinecraftForge#2288]
When using this Forge version in Minecraft and playing for an extensive amount of time, GPU memory is exhausted, leading to a java crash and sometimes a bsod.  Please fix this.

**Comment by matthewprenger** [comment]
Logs? GPU? Driver? Anything useful?

**Comment by LexManos** [comment]
Closed, go to the forums and determine what you're talking about with basic troubleshooting before reporting issues with Forge.

**Comment by darthvader45** [comment]
GPU is nVidia GT 750M
Driver 359.06
No logs, as it is not a Minecraft crash.
I get an error message stating that the GPU memory has been exhausted, then a Windows error saying that Java stopped working.  Finally I get a browser window pointing to here: http://nvidia.custhelp.com/app/answers/detail/a_id/3553

It's an OpenGL error.

**Comment by chibill** [comment]
does it happen with no mods installed? if not its a mods fault.  Also there are logs everytime you start minecraft. So get them.

**Comment by LexManos** [comment]
Closed, go to the forums and determine what you're talking about with basic troubleshooting before reporting issues with Forge.
