### ISSUE TITLE
WorldProvider#getHeight does not affect height limit

### ISSUE THREAD

**Issue by gegy1000** [MinecraftForge/MinecraftForge#2289]
When attempting to change the height limit in my custom world provider, I discovered WorldProvider#getHeight. I found this being called from multiple places of MC, so I decided to try to use it. I soon found that in many places, the height limit was hardcoded and not referring to that method. I am not sure if this is intentional, but it would be very useful to be able to change the height limit but just overriding that method.

**Comment by LexManos** [comment]
There will always be places that are not respecting this, such as world generation.
However a 'FIX ALL TEH THINGS' post like this will not help.
You say you've gone through and done the research where things dont respect this value, perhaps you should share that research in the form of a PR.

**Comment by gegy1000** [comment]
For example: World#isValid(BlockPos) - at the end of the line is checks  pos.getY() < 256 instead of pos.getY() < getHeight()

I will share that research in a PR ASAP.
