### ISSUE TITLE
FML provides coremodList to coremods but prevents access to the class the list contains

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/MinecraftForge#2290]
In `CoreModManager` a `List<FMLPluginWrapper>` is passed into the loaded coremod in the HashMap of options provided, however the class `FMLPluginWrapper` is `private static` preventing anyone from actually reading anything on the objects in the list provided.

**Comment by cpw** [comment]
I'll add an interface.. What needs to be on it?

**Comment by skyboy** [comment]
Name, dependencies, sort index (?). Would the location be useful? The instance might be too, if the core mods express some sort of mutual API-compat.

**Comment by cpw** [comment]
Hmm. I'm not convinced about api stuffs. That gets annoying fast, because apis in coremods fuck everyone else up..

**Comment by skyboy** [comment]
`@API` does, but if it's specifically for coremods to interact (being on the loadingplugin instance)  then it largely doesn't matter for normal mods and probably wouldn't be marked due to the way it's handled.

**Comment by cpw** [comment]
Yeah, I've tried to make @api in a coremods crash cos it really won't work. I'm concerned that coremods with api could end up moving the problem @api was intended to solve to the coremods layer.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Feature]
