### ISSUE TITLE
[1.8.8] Lever and button placement logic differs from torches

### ISSUE THREAD

**Issue by AlexIIL** [MinecraftForge/MinecraftForge#2291]
In forge specifically levers and buttons can be placed only on the wrong side of blocks, and torches drop off the side they were placed on if they receive a block update.

![screenshot from 2015-12-18 20 46 27](https://cloud.githubusercontent.com/assets/3751138/11907457/fc0f0988-a5cb-11e5-97b0-97c369567943.png)

I tested with just forge 11.15.0.1635 for 1.8.8 installed and separately with BuildCraft. This issue does not happen in vanilla as you cannot place torches or buttons on the side of stairs in vanilla.

Found by AlexIIL/Buildcraft_1.8_Issues/issues/71 with BuildCraft Facades and engines,

**Comment by amadornes** [comment]
Can confirm. I can also add that both normal and redstone torches are placed correctly but drop when they get a block update (they are checking for solidity on the opposite face). In the case of redstone torches, this is right as they are placed.
