### ISSUE TITLE
MultiMc keeps crashing error: 1 device not closed Game excited with exitcode -1. please help the modpack is Forgecraft (v1.1.1) v1.7.10

### ISSUE THREAD

**Issue by Robbercall911** [MinecraftForge/MinecraftForge#2292]
[crash-2015-12-18_18.30.35-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/67353/crash-2015-12-18_18.30.35-client.txt)
heres the link to the crash log if needed (http://paste.ee/p/YvoGb)

**Comment by Robbercall911** [comment]
The modpack is from Feed The Beast laucher if you needed to know.

**Comment by diesieben07** [comment]
Read the error ("Can't fit all textures, use lower resolution texture packs or remove mods."). Also Fastcraft is not supported. And use the forum for problems like this in the future.

**Comment by Robbercall911** [comment]
so that means i have to remove mods? is there a way to remove fastcraft?

**Comment by diesieben07** [comment]
You remove it from your mods folder...
