### ISSUE TITLE
Java path-seals not working

### ISSUE THREAD

**Issue by TechnicianLP** [MinecraftForge/MinecraftForge#2294]
As i dont want other mods to tinker with packageprivate things in my mod i turned on a path-seal vie the MANIFEST.MF

Manifest-Version: 1.0
sealed: true

but i get an error: "\minecraft\mods\Mod-1.4.jar has a security seal for path com.TechnicianLP.Mod, but that path is defined and not secure" and i can still declare classes in that package from a different jarfile which should be disabled by the seal

is there a way to make/keep the seal working?

**Comment by cpw** [comment]
No. Path seals are not supported by the classloading we have to do to make mods work. They interfere in the operation of various parts of the system.
