### ISSUE TITLE
No event for fluid defaults change

### ISSUE THREAD

**Issue by immibis** [MinecraftForge/MinecraftForge#2296]
No event is fired when the fluid default map changes.

See https://github.com/MinecraftForge/MinecraftForge/blob/1.8.8/src/main/java/net/minecraftforge/fluids/FluidRegistry.java#L89 which loads the defaults (from saved world data on the server, or from the server's map on the client)

**Comment by immibis** [comment]
Ah yes, the good old [CADT model for software development](https://www.jwz.org/doc/cadt.html)

**Comment by mezz** [comment]
Do you still need this event?

**Comment by mezz** [comment]
In 1.13 Fluids will use a proper registry and you can listen for when they are synced from the server, just like Blocks and Items now. https://github.com/MinecraftForge/MinecraftForge/pull/4098
