### ISSUE TITLE
[1.8.8] Variable references empty selection

### ISSUE THREAD

**Issue by Nedelosk** [MinecraftForge/MinecraftForge#2297]
When I run my client on Eclipse. I become a Variable references empty selection: ${project_loc}. When I select the project it's work. In old Forge Versions it's work without that i select the project every time
when i will run my client.

Forge Version : 1.8.8-11.15.0.1625-1.8.8

Sorry for my bad english :)

**Comment by LexManos** [comment]
${project_loc} is something defined by eclipse itself nothing in Forge.
What exactly are you having an issue with....
