### ISSUE TITLE
Type signature adjustment in ClientRegistry.bindTileEntitySpecialRenderer

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2301]
This generic signature issue is more substantiated than my other two tickets (partially because it's in forge code so easily changeable)

ClientRegistry.bindTileEntitySpecialRenderer has type parameter T extends TileEntity, and takes a T, and a TESR\<T\>. The way the generic signature is right now, we cannot register TESRs that can render subclasses of the original Tile Entity. This was possible in 1.8.0 before generics.

A use case of this was present in Botania in MC 1.7.10. It has a modified TileGaiaHead, which extends TileEntitySkull. It also has a modified vanilla TESR RenderTileSkullOverride, which indirectly extends TESR\<TileEntitySkull\>.

Thus the call ClientRegistry.bindTileEntitySpecialRenderer(TileGaiaHead.class, new RenderTileSkullOverride()) fails because it enforces a strict type bound, and it sees a TileGaiaHead and a TESR\<TileEntitySkull\>. Even though TileGaiaHead subclasses TileEntitySkull.

So I think it should be changed to TileEntitySpecialRenderer ~~\<? extends T\>~~ \<? super T\>. This should be a non-breaking change because it merely restores what was possible before.

**Comment by diesieben07** [comment]
`<? super T>`. `extends` would mean it is ok to render ´Superclass` with a `TESR<Subclass>` which is not right.

**Comment by RainWarrior** [comment]
Fixed in cf2bbd1353df3b87e004bbd8a86324eb82f278e3.
