### ISSUE TITLE
Blockregistry reuses IDs of previously existing blocks in the world

### ISSUE THREAD

**Issue by bonii-xx** [MinecraftForge/MinecraftForge#2302]
Forge 1639

Setup: Full Metal Blocks and Ore Blocks. Full metal blocks were added first, then ores where added, meaning the ores should have the higher ID.
![2015-12-22_15 52 45](https://cloud.githubusercontent.com/assets/722449/11957862/904e5ad6-a8c4-11e5-8270-3fc7d863a0c7.png)

Removing both blocks, forge gives the appropriate warning on world load.
![2015-12-22_15 53 35](https://cloud.githubusercontent.com/assets/722449/11957864/904fd3ca-a8c4-11e5-8915-20c010379da0.png)

Readding the ores. They take the place of the full metal blocks:
![2015-12-22_15 54 33](https://cloud.githubusercontent.com/assets/722449/11957863/904f2650-a8c4-11e5-9c76-9c6c756d6a34.png)

Readding the full metal blocks. They take the place of the original ore blocks. The manyullyn block is from earlier testing.
![2015-12-22_15 55 40](https://cloud.githubusercontent.com/assets/722449/11957865/905575aa-a8c4-11e5-9698-8078a7d257ab.png)

The world was not newly created for this test, Both blocks have existed in the world before.

**Comment by bonii-xx** [comment]
Just tested this in a fresh world. Can reproduce in a newly created world with both blocks registered from the beginning.

**Comment by bonii-xx** [comment]
Removing the blocks again and placing blocks in the same chunk (for example directly under them) does not have any affect. The blocks are there again when added.
Replacing a block instead of just placing them in the same chunk will keep the newly placed one.

**Comment by cpw** [comment]
Yeah, it looks like the block ids are not reset, when the blocks themselves are removed.

**Comment by cpw** [comment]
Rather than treat it as a bug, lets treat it as a feature: https://github.com/MinecraftForge/MinecraftForge/commit/bcecf59a875527f09738ef9493f763791b329f1b

**Comment by williewillus** [comment]
Apparently a feature now, so closing :P

**Comment by Actuarius** [comment]
@williewillus closed this issue
