### ISSUE TITLE
Sugestion: Old File Cleanup

### ISSUE THREAD

**Issue by Blue64** [MinecraftForge/MinecraftForge#2304]
I was going through my files recently (trying to locate a list of ```Biome Types``` for ```EnderIO``` Mod), and I came across this folder tree in my ```%appdata%\.minecraft\libraries\net\minecraftforge\forge\``` folder, and I noticed that it contained all of the old Libraries for all my older Forge installs!

This can kind of take up a little room, and I know y'all are interested in streamlining stuff, so I figured I'd recommend this idea:
```
Compare "Installed versions" against "Existing Libraries" (at least for forge versions)
then delete any "Existing Libraries" that aren't also "Installed"
(I for example had about 7 different Libraries that weren't installed)
```

here's my runtime specs:
```
ripped straight from fml-client-latest:
-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 40319472 bytes (38 MB) / 111497216 bytes (106 MB) up to 1861615616 bytes (1775 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1792M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.4.12874 Compatibility Profile Context 14.100.0.0' Renderer: 'AMD Radeon HD 6310 Graphics'
```

* Edit: I'm unsure if this was recommended before, and I tend to suck at searching for stuff, especially since most people tend to label stuff differently. If this was recommended before, you can simply direct me to the appropriate thread.

**Comment by williewillus** [comment]
How would a newer forge know whether or not an old forge is also being played at the same time? (you have separate launcher profiles for 1.6/7/8 packs, for example)

**Comment by Blue64** [comment]
it would checked if the forge is installed, not running/being played. It could compare it to the available "installed versions" (which you pick before you click play to initialize the startup)

**Comment by Spartan322** [comment]
Pretty sure hard drive cleanup is the owner's job

**Comment by Blue64** [comment]
I didn't even know that these files existed. Plus, there's already hard drive cleanup going on, so I know it has access.
```
Launcher Log:
[20:25:25 INFO]: Ignoring visibility rule and showing launcher due to a game crash
[20:25:26 INFO]: Crash report detected, opening: %AppData%.minecraft\crash-reports\crash-2015-12-22_20.25.23-client.txt
[20:25:26 INFO]: Deleting %AppData%.minecraft\versions\1.7.10-Forge10.13.4.1558-1.7.10\1.7.10-Forge10.13.4.1558-1.7.10-natives-9212003807065
```
It already has access to delete the old Natives so that it doesn't fill the hard drive with tons of old useless files. All I'm suggesting is basically a file verification check so people don't end up with, (currently, up to) ```1558``` versions of ```Forge``` installed into their computer (without their knowledge).

As we all are painfully aware of, probably close to half the people that play modded MineCraft are for the most part programmatically or technologically illiterate to some degree or another.

At over ```2MB``` per library, I just freed up over 0.01 GB by deleting these older versions, and I don't exactly have the capability to keep all my mods "up-to-date" (including ```Forge```), so I can only imagine how much space is being wasted on other people's computers (Windows, Mac, Unix), simply because they're unaware of these files existing.

**Comment by chibill** [comment]
The cleaning natives is part of the launcher. Not forge.

**Comment by Blue64** [comment]
@chibill true, but it inherits it's access (as demonstrated by setting the ```Launcher``` to ```Low Priority``` for it's ```Processor Access```, and ```MineCraft``` automatically being set to it's predecessor's access level, instead of the default ```Normal```), and the file access portion is also demonstrated by the Config Files.

I'm just saying, if all these versions are being made available to be installed for use, once the installation is undone (making it inaccessible from the launcher), shouldn't forge at least *ATTEMPT* to remove it's old orphaned files that it otherwise will never access again (unless the version get re-installed)? Especially since there's no display during Installation on ```Windows``` telling us where all of these files are being placed (I have no idea if this feature is present in ```Mac``` or ```Unix```, but I'm assuming it isn't present there either).

It's a simple little bit of code really. Basically:
```
If (FileExist)
  If (VersionInstalled)
    Return
  Else
    Delete (FileExist)
    Return
```
(give or take, I don't know how exactly it'd look in ```Java Code```, as I don't know that much ```Java Code```)

**Comment by chibill** [comment]
Forge does not handle the uninstall... The launcher does. While yes forge handles the install. (They have to.) But they don't have an uninstaller.

**Comment by Blue64** [comment]
But Forge could handle the uninstall, since the Launcher obviously knows nothing about these files.

All I'm recommending is a cleanup of the old junk files that the end user is otherwise unaware of (unless you seriously expect to have all the end users of Forge to know how to track down any remnant files when they remove an older version, reference earlier comment of inability for half of end users to not know how)

It doesn't alter any already existing code, just adds a few lines to verify that the files aren't orphaned.

**Comment by diesieben07** [comment]
The problem is that forge does not know which files you do not need anymore.
If the file is there, the version is installed, you can select it in the version box in the "Edit Profile" screen. Just because you don't have a profile set up with it doesn't mean the files are no longer needed (what if you want to use the version in the future?).
Forge cannot know this.

**Comment by diesieben07** [comment]
What I mean is: "Installed Version" is not the same as "Existing Profile". You can have a version installed but no profile pointing to it and you can have more than profile pointing to one version.

**Comment by Blue64** [comment]
I'm not saying "```Profile pointing to it```", I'm saying "```Version Installed```", if it's an invalid install for a version, then it's never going to get called, thus it's just wasting space.for example, I just updated my ```Forge``` Version to the ```MC 1.7.10 Experimental``` (as opposed to ```Recommended```), so if I delete the ```Recommended``` so that I am unable to select it from the ```Edit Profile > Use Version Dropdown menu```, then why shouldn't ```Forge``` delete any files I missed? If I'm unaware that these files are gunking up my hard drive, then how can I know that it's ok to delete them? I don't even know which files ```Forge``` adds! ```x.x'``` It has no ```GUI``` telling me any info beyond 
```
What type of function do you want?
* Client Install
* Server Install
* Extract"
```
I don't know what entries it'll never call again unless it's explicitly named after the no longer existing version. I see lots of stuff in these installers, but I have zero clue where it puts any of it. Not to mention, pretty much *```EVERY```* program on ```Windows``` has an ```un-installer``` (most of the ones that don't are usually flagged by Anti-Virus Software as ```PUPS``` (```Potentially Unwanted Program``` basically)).

I'm just saying you can check against the ```Edit Profile > Use Version Dropdown menu``` (which contains all the valid versions, obviously), and if the ```File``` exists for a version that's not on there, it can delete it. "```Profile pointing to it```" or not; if it can't be loaded, it's ```Orphaned```, and thus just a waste of space.

Y'all are aware that you're defending Junk Files right? ```O.o?```

If "```There's no possible way to get the list of available versions```" is your next argument, I'd like to point out, there *```OBVIOUSLY```* must be *```SOME```* way, as Minecraft Launcher does it (```Edit Profile > Use Version Dropdown menu```)

**Comment by Blue64** [comment]
I'd also like to point out, the ```0.01 GB``` I freed up by deleting the old versions from that folder, were all uninstalled months ago (one was as old as the 1,300 range, current versions are ```1558```/```1614```)

**Comment by Spartan322** [comment]
This doesn't appear feasible, its not a forge issue, and I'm pretty sure not a game's responsibility.

**Comment by LexManos** [comment]
No, Forge has no 'uninstall' if you decided to 'uninstall' it by deleting the versions folder then you're responsible for deleting anything else that's related to it.
You can run multiple versions of minecraft and forge from the same launcher and as far as I know the technology to scan your brain to determine your wishes on the computer and infer what it needs to do.
So, simple solution, If you screw around in the files its on you to do everything else.
When you 'uninstall' a version go through and delete the libraries the version lists.
If you're REALLY worried about space. Go spend $5 on a USB drive and hold every version of Forge ever created twice over.

**Comment by Blue64** [comment]
I still don't know what forge actually installs on my computer, nor do I know where. I'm not saying to predict what I want deleted before I delete it, I'm saying to delete the forge files that it's never going to be able to access unless I redownload that specific version and install it.

I would have uninstalled the older versions some other way if I knew of it's existence. Y'all are telling me that the only way I can be sure to delete all the orphaned Forge Files is to open Command Prompt and format my hard drive.

**Comment by Blue64** [comment]
If my only options are to launch ```MC 1.7.10```/```Forge 1558```/```Forge 1614``` then it obviously can clean up any ```Forge 1336``` files it finds.

If there was a way to uninstall ```Forge``` properly, I'd love to use it! Or even if it's a list of all the files it installs and where it puts them, that would be useful too! But as it obviously doesn't exist, I'm recommending it, and y'all are being dicks about it! I found old files somewhere on my computer that I was never informed were put there, and you expect me to ***MAGICALLY*** know ***WHERE*** all of it's related files are, and ***WHICH ONES*** are ```Forge```? In case you forgot: ***```Forge``` INSTALLS IN THE MINECRAFT DIRECTORY!*** It's rather difficult to tell the two apart.

Unless it's specifically named after the version, I'm going to miss anything it installed.

**Comment by chibill** [comment]
Lex just lock this. Also you want forge to guess at of your still using an
old version. Jsut deal with cleaning up your .Minecraft every now and then
or use a custom launcher that does that. NOT A FORGE PROBLEM.

**Comment by Blue64** [comment]
P. S. I can't afford a $5 USB. I only buy a Soda at McDonald's, that's my "food" for the day.

**Comment by Blue64** [comment]
I'm not saying guess

**Comment by Blue64** [comment]
I'm saying compare to the already existing list of accessible versions

**Comment by Blue64** [comment]
Also, I know of no "custom launcher" either, I have the MineCraft launcher, and Forge Mod Loader.

**Comment by Blue64** [comment]
There's a ***HUGE*** difference between a guess, and a comparison. If the ***COMPARISON*** shows that it can't run that version, then it's obviously orphaned!

**Comment by TehNut** [comment]
This isn't a chat. Add to your existing comments...

**Comment by Blue64** [comment]
Mobile browser doesn't have edit function, need to switch to desktop view, which is notably slower at 8KB/s

**Comment by Spartan322** [comment]
If you really want to be lazy, you could simply delete most of the .minecraft (with exceptions for folders like saves) and just use the forge installer, its not like forge is actually aware where those old files are, or even exist, it has no idea they exist, and thus can't actually delete them, only a custom installer can do this.

Ok I think we are done here, this issue is over, and should be locked to prevent further pointless arguing.

**Comment by Blue64** [comment]
@Spartan322 there should be at least SOME info SOMEWHERE as to what to delete, that was one of my many points. I have no idea which folders MineCraft actually needs to run (kind of important since I can't play online very often), much less which folders that the valid installations of Forge still need. Y'all are just telling me to magically know this information already, well guess what, I don't know that information!

**Comment by Spartan322** [comment]
Delete the .minecraft folder, and just backup the saves folder (and mods folder if you don't want to re-download them) in it, its not that hard, and if you've been using Forge, then what you just said is no excuse. Then you just restart the Minecraft launcher once, close it down, and then start the forge installer, its that simple if you really want to get rid of all previous forge version, and stating that you only want to rid of some Forge versions is also a useless excuse because there is no point not having the latest recommend (or just latest) Forge for your respective Minecraft version (and you can still download it either way).

**Comment by Blue64** [comment]
@Spartan322 Did you not catch the part where I stated that I can't go online often? I'm browsing github from my phone with an 8KB/s connection because this is my only internet, and I can't tether. Meaning I can't just "run 1.7.10 again", no, I need to wait until I can connect online so 1.7.10 can download all the files it required that I'd have just wiped out, then run it, then Forge, then spend a day or two setting up the configs you forgot to mention to keep for the 100+ mods that I use.

The only 2 versions of Forge I can launch are the Release and the Beta of MC 1.7.10

I have been using forge, and I seriously don't know which files are native MineCraft and which are native Forge. I start browsing my assets folder and everything is named in Hexadecimal, I spent a month alone just in my Mods folder so I could get everything to launch, and you expect me to now magically know some information that nobody has ever plainly stated on any of the official pages for getting forge or even on their github?

Pardon me if I'm aggravated or annoyed after being told my idea was stupid and that I'm dumb for not knowing information that is only limited to people who have ripped apart forge and understand the base workings of it. I just wanted to idiot proof a text file list of files that forge installed along with the locations within which it installed them. ***I'm sorry if I offended anyone by trying to make people's lives better.***

**Comment by Spartan322** [comment]
You do realize even if we do implement a system like that, you would still need to download a new Forge (if we even bothered to put it in, which btw, we can't). That is a flaw argument in itself, and how is a problem that you just came up with that everyone else fighting against you over making anyone else's lives better?

**Comment by chibill** [comment]
Just stop. If you don't know which files are forge and which are Minecraft.
You really have a problem. Forge only adds a few libraries and the forge
jar. The assets folder is all Minecraft stuff like textures and sounds. So
stop spamming this. As some people like to not have there inbox filled with
invalid issues.

**Comment by RainWarrior** [comment]
Everything that could've been said was said.

**Comment by LexManos** [comment]
One last note, reiterating that you're a moron, and the installer creates a log file of everything that is installed it is in the same folder and has the same name as the installer.
If you're THAT worried the information is there and has been there forever.

Having Forge try to assume what you are using or not is NOT feasible.
And having Forge start randomly deleting shit on your computer is A HORRIBLE president to set for modders. Next thing you know you have mods formatting your hard drives because they think its funny.
