### ISSUE TITLE
Gradle failed with an exception at :fixMcSources

### ISSUE THREAD

**Issue by TheDoctorSoda** [MinecraftForge/MinecraftForge#2305]
![image](https://cloud.githubusercontent.com/assets/6166773/11971821/db6df73c-a8f7-11e5-9ba5-cf3e5d58d765.png)

I can get you the stack trace, but how do upload it? It's in the terminal, and most of the top part is cut off. Forgive me, I am a gradle noob.

This happens on every single version of forge I've tried in the past few weeks--all cleaned workspaces, and decided to take a look at the forge documentation to see if any of the installation instructions have changed. Steps on there were exactly what I've done in the past.

**Comment by williewillus** [comment]
what forge build, mapping versions, and gradle(w) version?
try running setupDecompWorkspace with flag `--refresh-dependencies`

**Comment by TheDoctorSoda** [comment]
That flag worked. Thanks ;)
