### ISSUE TITLE
[1.7.10] Very, very minor typo (Forge 1566)

### ISSUE THREAD

**Issue by Alaberti** [MinecraftForge/MinecraftForge#2307]
Have a very, very, very low priority typo. In the fml console log, a friend of mine happened to notice a typo at ore registration. Attached in a screenshot. It says "recipies" instead of "recipes."

I say let the people have pie myself.

Edit: http://prntscr.com/9i4n3t (better view if you need it).

![3e3d944cd020904572747a12d38d710a81f0305e60af403564 tfile_urlpv](https://cloud.githubusercontent.com/assets/10929796/11996945/6e923a1e-aa6f-11e5-8bc9-401c6bc7b468.png)

**Comment by Math321** [comment]
FML version 10.13.5.1566, by the way.

**Comment by williewillus** [comment]
Someone should just round up all the typo issues/PR's and make one big spelling PR lol

**Comment by LexManos** [comment]
Someone should. Until then these are useless will keep note MAYBE in the future.
