### ISSUE TITLE
No response while uploading gl texture for atlas

### ISSUE THREAD

**Issue by 2ndkirbyever** [MinecraftForge/MinecraftForge#2310]
I have had a problem recently with Forge 10.13.4.1566 for Minecraft 1.7.10 where while it is uploading the GL texture for minecraft:textures/atlas/blocks.png, Java stops responding and takes more time than usual to finish loading. Once it is finished loading, my game takes about 20 seconds to register a click on the home screen to do anything. According to the log file attached:
* [22:13:57] [Client thread/DEBUG] [FML/]: Bar Finished: Texture creation took 466.204s
* [22:13:57] [Client thread/DEBUG] [FML/]: Bar Step: Reloading Texture Manager - minecraft:textures/atlas/blocks.png took 493.415s

Also:
* [22:18:13] [Client thread/DEBUG] [FML/]: Bar Finished: Texture creation took 249.793s
* [22:18:13] [Client thread/DEBUG] [FML/]: Bar Step: Reloading Texture Manager - minecraft:textures/atlas/items.png took 256.236s
* [22:18:13] [Client thread/DEBUG] [FML/]: Bar Finished: Reloading Texture Manager took 749.668s

I am using the Technic launcher to launch my private modpack which includes that version of Forge and the following mods: [Mod List](https://github.com/MinecraftForge/MinecraftForge/files/72248/Mod.List.txt)
I am using Java 8 update 66 with this version of Forge. I appreciate any help anyone can provide.
Thank you for your time.

[Latest log file](https://github.com/MinecraftForge/MinecraftForge/files/72243/fml-client-latest.txt)

**Comment by LexManos** [comment]
Due to threading issues yes, if you click on the screen during the loading phase it will give you the 'not responding' message. This is normal there is nothing we can do about it. Just ignore it and let it finish loading. 
As for the time it takes tobload, the more mods the longer itll take.

**Comment by RainWarrior** [comment]
Try disabling the splash screen, and see if the loading time changes at all.

**Comment by 2ndkirbyever** [comment]
@RainWarrior I have tried that, and it does not work. It still gets stuck in the same spot

**Comment by psxlover** [comment]
Allocating 8GB of Ram to minecraft, while your computer has 8GB Ram total is a bad idea. My guess is that you are running out of memory and you are using the page file.

**Comment by 2ndkirbyever** [comment]
@psxlover I have 16GB of RAM. My computer is not running out of RAM during startup because I still have 8GB of un-allocated space to work with

**Comment by LexManos** [comment]
Let me know if this is still a issue on 1.8 versions.
However im not sure what we can do about this as this isnt the stitch event its the actual 'gpu.uploadData()' call.
