### ISSUE TITLE
FMLModIdMappingEvent not fired when connecting to a Vanilla server

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#2315]
Tested on 1.8.8, assuming it affects 1.8 a well.

When connecting to a vanilla server, `FMLModIdMappingEvent` is not fired. 
On disconnect, it is fired as expected.

This is necessary for JEI to work with vanilla servers, https://github.com/mezz/JustEnoughItems/issues/73.

**Comment by cpw** [comment]
Thanks mezz..

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]
