### ISSUE TITLE
minecraft:lit_redstone_ore bug 1.7.10

### ISSUE THREAD

**Issue by Blue64** [MinecraftForge/MinecraftForge#2323]
well, this is an interesting development! ```minecraft:lit_redstone_ore``` apparently "[***```doesn't exist```***](http://i.imgur.com/V5CPUiK.png)"!
```

[12:15:06] [Client thread/INFO] [inventorytweaks]: codechicken.nei.GuiExtendedCreativeInv
[12:15:06] [Client thread/INFO] [inventorytweaks]: codechicken.nei.ContainerCreativeInv
[12:15:12] [Client thread/INFO]: [CHAT] You are now playing survival
[12:15:25] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiChat
[12:15:47] [Client thread/INFO]: [CHAT] There is no such item with ID minecraft:lit_redstone_ore
[12:15:59] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiChat
[12:16:02] [Client thread/INFO]: [CHAT] There is no such item with ID 74
[12:16:03] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiChat
[12:16:06] [Client thread/INFO]: [CHAT] There is no such item with ID 74
[12:16:17] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.inventory.GuiInventory
[12:16:17] [Client thread/INFO] [inventorytweaks]: net.minecraft.inventory.ContainerPlayer
[12:16:20] [Client thread/INFO]: [CHAT] You are now playing creative+
[12:16:41] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.GuiIngameMenu
[12:16:41] [Server thread/INFO]: Saving and pausing game...
```
I even tried to copy the block (I remapped it to my Tab Key because I don't have a Mouse Wheel), the lit redstone doesn't copy, but the standard does.

NEI also doesn't detect the lit ore.

This issue was discovered because of [an old bug](https://github.com/WayofTime/BloodMagic/issues/347) resurfacing within ```Blood Magic``` Mod. If I'm not mistaken, I believe the error here is that the block "exists" (so to speak, as it's temporarily "create-able" via interacting with the standard ```Redstone Ore```), but I am guessing it was never actually properly registered (or perhaps blocked access to it in some way for some reason or another). any input/assistance y'all could provide would be great.

* Edit: Oh yeah, and Happy New Year ```:)```
* Edit: my Specs:
```
-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 305836512 bytes (291 MB) / 762667008 bytes (727 MB) up to 1861615616 bytes (1775 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1792M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 155 mods loaded, 155 mods active
```

**Comment by LexManos** [comment]
Vanilla does not have a item for these transient blocks. You can not make item stacks with them.
This is not a bug.

**Comment by Blue64** [comment]
so...Won't fix? Because I'm guessing you guys are awesome enough to think of some way to work around that. Also, I could have sworn that I used to see it as an available block in 1.7.10 months ago, it was even in the ```/give``` command's list at some point (hence how i knew to look for it via ```/give``` first)

**Comment by diesieben07** [comment]
Yes, in 1.7.10 these Blocks exist, in 1.8 they don't.

**Comment by Blue64** [comment]
Ah, I'm referring to 1.7.10 though, and also, the lit Redstone doesn't appear to be wanting to "turn off" (despite the fact that the signal is only supposed to exist for 16 ticks beyond it's activation at most if I'm not mistaken)

**Comment by diesieben07** [comment]
Yes, it doesn't turn off, that is normal behavior. Lit redstone is an internal block and not designed to be placed directly into the world. It will only work properly if it is created by activating unlit redstone.
This is not a bug and this is just how it works in vanilla.

**Comment by Blue64** [comment]
well, that solves the problem that lead to this finding. I still don't really see the need to remove the blocks before making sure they won't be accidentally permanently placed via, say, a Pickaxe starting to break it and stopping before it breaks (basically just gotta throw some redstone dust down and a button and it reverts to unlit ore right?)

**Comment by diesieben07** [comment]
Well, tell that to Mojang. They removed those blocks.

**Comment by Blue64** [comment]
I would if I could, I have no idea how to contact them, I also have no idea if I should be contacting them, or Microsoft. They still have the custom Mob Heads left in, so if they were worried about space, they could have eyeballed those instead.

**Comment by LexManos** [comment]
Please do not have these stupid discussion in github issues.
We will not 'fix' it because there is nothing to 'fix'. 
Logic/Transient blocks like this, fire, tripwires, and more should never be in ItemStacks so there are no items for them.
This is not a bug, this is intentional. This has nothing to do with space, it has everything to do with logic/gameplay.
Lit Redstone will revert back to normal redstone when it gets updates, which is done 'randomly' so there is no telling when it will revert.
If you have a system that mines ores, then they should allow for all ores including the lit version. This is nothing on our end.
