### ISSUE TITLE
[1.8.9] Realms button icon shows on Mods button

### ISSUE THREAD

**Issue by iLexiconn** [MinecraftForge/MinecraftForge#2327]
Screenshot: https://media.ilexiconn.net/wYQQ52r.png

**Comment by williewillus** [comment]
I suggest we leave it that way ;)

**Comment by iLexiconn** [comment]
Fixed in https://github.com/MinecraftForge/MinecraftForge/commit/755df95c96e698cc12cdb51b2d5e4e4f1d1be467
