### ISSUE TITLE
[1.8-1.8.9] Boss bar rendering issue

### ISSUE THREAD

**Issue by 61352151511** [MinecraftForge/MinecraftForge#2328]
So this is a long standing bug I'm assuming caused by something in forge (As it occurs in a development environment with only my mod, that does not touch rendering). I don't know how many versions it covers but I know it started at some point in 1.8 and still exists now in 1.8.9.

The bug is that when the debug menu is open and a boss bar is being rendered, it renders incorrectly as seen below.

![2015-12-31_17 00 47](https://cloud.githubusercontent.com/assets/2399411/12068251/2bdfc49a-afe0-11e5-9c0f-a9801ad2b096.png)

**Comment by GirafiStudios** [comment]
Can you reproduce this on a fresh 1.8.9 world?

**Comment by LexManos** [comment]
Bound texture leakage that is not done in Forge's gui.
