### ISSUE TITLE
[1.8.9] Using Commons-IO 1.4

### ISSUE THREAD

**Issue by iLexiconn** [MinecraftForge/MinecraftForge#2330]
For some reason, Minecraft 1.8.9 uses Comming IO 1.4. It gets downloaded into the gradle chache (https://media.ilexiconn.net/BjByLQD.png) and causes this error: https://media.ilexiconn.net/GgMCRAo.png

**Comment by LexManos** [comment]
Um no, no it doesn't.
Nothing in Forge or MC references that version.
https://github.com/MinecraftForge/MinecraftForge/blob/master/jsons/1.8.9-dev.json
https://s3.amazonaws.com/Minecraft.Download/versions/1.8.9/1.8.9.json

Something on your end is derping up majorly. Perhaps a dependancy you have outside of Forge/Minecraft is pulling in the old version. But it's not Forge.

**Comment by iLexiconn** [comment]
It's not only happening for me, and clearing the gradle cache didn't fix it.

**Comment by LexManos** [comment]
Then perhaps you should do something useful and you know, GIVE US LOGS.

**Comment by iLexiconn** [comment]
Here's the log (after removing the 1.4 lib): https://media.ilexiconn.net/6sQNwRS.txt
And here's the build file: https://github.com/iLexiconn/LLibrary/blob/1.8.9/build.gradle

**Comment by cpw** [comment]
Share what your problem was and the solution. Don't be denvercoder9.

**Comment by iLexiconn** [comment]
I'm using Diff4j, and it has CIO 1.4 as dependency.

**Comment by cpw** [comment]
Ah, that would explain it.
