### ISSUE TITLE
Server console is not showing any colors

### ISSUE THREAD

**Issue by Minecrell** [MinecraftForge/MinecraftForge#2334]
The current server console doesn't show any colors, because [the line adding the colors to the logged message](https://github.com/MinecraftForge/MinecraftForge/pull/2200#discussion-diff-45550411R53) was removed in https://github.com/MinecraftForge/MinecraftForge/commit/cf4c0ca0011026e74a0fe93396b4b8a036276f7d#diff-d1ce36a3a5f637e8af4930dd4f51a610L53. It is necessary for the console to show any colors, because otherwise the server will always only log the plain text message, and not the formatted one.

Without the line:
![screenshot_20160102_174817](https://cloud.githubusercontent.com/assets/3035868/12075236/0af78c9a-b17a-11e5-8d8c-45833c05b8ca.png)
vs. with the missing line:
![screenshot_20160102_175022](https://cloud.githubusercontent.com/assets/3035868/12075237/0e1aa8ee-b17a-11e5-8c04-c961240a07a3.png)

**Comment by cpw** [comment]
What's the diff? Is there a patch missing? Please PR it.
