### ISSUE TITLE
[OBJ loader] can't use verts over index 9 if no VT idx specified

### ISSUE THREAD

**Issue by Tarig0** [MinecraftForge/MinecraftForge#2338]
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/client/model/obj/OBJModel.java#L336

The code highlighted forces all integers to be seen as one character so 10 = 1 for example

**Comment by Tarig0** [comment]
I'm not able to make the changes and verify them locally (issues with forge env setup) else I would PR a quick change and a test model

**Comment by shadekiller666** [comment]
This has been fixed in a PR that is currently waiting for review, and should be in a forge release within the next week or so.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Superseded]
