### ISSUE TITLE
[1.8.9] Item Frames don't render in 1687

### ISSUE THREAD

**Issue by joacmc** [MinecraftForge/MinecraftForge#2339]
![2016-01-06_23 14 34](https://cloud.githubusercontent.com/assets/16583426/12156480/5cea31ca-b4cb-11e5-92c3-809f2670dd60.png)
![2016-01-06_23 15 55](https://cloud.githubusercontent.com/assets/16583426/12156499/78f5bf42-b4cb-11e5-91cd-60b167aabdf9.png)

*Forgot to remove resource pack on first

**Comment by RainWarrior** [comment]
Should be fixed in 1688.
