### ISSUE TITLE
[1.7.10] ChestGenHooks not implemented for Nether Fortresses

### ISSUE THREAD

**Issue by Mace134** [MinecraftForge/MinecraftForge#2341]
It would seem the 1.8 version had this added last May, but it is glaringly absent for 1.7.10. Apologies if this is an improper way to call attention to this issue. I would fix it myself if I had the ability.

**Comment by TehNut** [comment]
1.7.10 has reached EOL. You won't get this fixed.

**Comment by Mace134** [comment]
:-( I was afraid that might be the case.

**Comment by LexManos** [comment]
You've had 2 years to bring this up. Not our problem.
