### ISSUE TITLE
[1.8.9] Desperatly need the AdvancedModelLoader for 1.8

### ISSUE THREAD

**Issue by Bitterholz** [MinecraftForge/MinecraftForge#2344]
Hi,
Me and my Team just started our first MC Mod and we desperatly need to be able to render our Wavefront Object Models for our Pipes.
Spend alot of time making them and we just noticed we're unable to use them due to the missing AdvancedModelLoader from Forge.

It really stops us from developing it further because we're currently working with the TESR to do our pipes.
We could use reflection to modify the vanilla rendering method to have a 4th case allowing us to port over the Forge 1.7.10 version of the AML but we don't want to do it and then port it back to your version once its out.
(Despite it being illegal as far as I recall)

Id love if you get the AML out soon it would get our Dev team back goin :)

In big appreciation
-Bitterholz and the Caledios-Team

**Comment by asiekierka** [comment]
OBJ model loading, ModelLoader, etc. You have a lot to learn.

2016-01-07 19:57 GMT+01:00 Bitterholz <notifications@github.com>:

**Comment by Bitterholz** [comment]
@asiekierka I know XD
But I wont release a Pipe-mod with a square pipe that looks ugly. Thats a restriction me and my Team have set for ourselfs.
So there IS a method of loading OBJ Files for 1.8 if I read your statement right...?

**Comment by diesieben07** [comment]
Yes, there is. You can find some example code [here](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/test/java/net/minecraftforge/debug/ModelLoaderRegistryDebug.java).

**Comment by Bitterholz** [comment]
Wow thanks alot @diesieben07 ! very helpfull!

**Comment by Bitterholz** [comment]
Thanks @asiekierka @diesieben07 for pointing me there! Super helpfull

**Comment by shadekiller666** [comment]
You're welcome for the loader btw... :P

**Comment by TechStack** [comment]
@shadekiller666 & @RainWarrior  Thank you for this. I had ported the Advanced model loader in the early days of 1.8 but I'd much rather use an official method. 
I've been trying to get it to work for custom model on entities and it seems that it is possible.
Been hung up on getting textures working but i think its a possibility.
Not sure if you had any plans for official support for entities using the new  OBJ loader system.

**Comment by williewillus** [comment]
you can render anything you want in an entity render, including, yes, OBJ models. These: https://i.gyazo.com/c8c9c93767a0a9affda3333406157bc0.png are TESRs rendering OBJ models loaded with the new loader

**Comment by shadekiller666** [comment]
the OBJLoader gives no shits about what you use the models for... just that they're formatted properly :P

**Comment by TechStack** [comment]
Thank you I wasn't sure if it was necessary to tie a blockstate json file to the model.

**Comment by shadekiller666** [comment]
It is not, though one is required if you're trying to do item-only, but not for TESR-only or entity models, though i recommend sticking with forge blockstate jsons as much as you can, they make things easier in most situations.
