### ISSUE TITLE
[Non Issue] [Minor] [Log Coherency] Mod Dependencies

### ISSUE THREAD

**Issue by khionu** [MinecraftForge/MinecraftForge#2345]
I'm a moderator on the Official Technic Discord, and, from my time in our Help channel, it's apparent that people can't take the hint that says they're missing a dependency. Easy fix, however.... it's not very clear in the logs, kinda tucked away.

It would be greatly appreciated if this could be formatted to be more clear to 3rd parties who only see the logs.

**Comment by williewillus** [comment]
Doesn't FML display a big dirt screen saying "mising dependencies: mod <x> wants mod <y>"?

**Comment by khionu** [comment]
Yes. The Help channel can be depressing..... [this is actually something we had to add out of necessity](http://i.imgur.com/7cXUcRR.png). It's not our only `how2` command, either.

Point is, we don't see that screen, they do. We ask for logs and look them over.

**Comment by khionu** [comment]
I know this was a while ago, but I thought for the record it would be nice to share this
http://i.imgur.com/qH0VmIQ.jpg
