### ISSUE TITLE
Very minor issue in JarDiscoverer

### ISSUE THREAD

**Issue by Mathe172** [MinecraftForge/MinecraftForge#2346]
While trying to develop my coremod, I stumbled upon a small problem:
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fml/common/discovery/JarDiscoverer.java#L45
This line will never work, since Attributes.get() should be called with an Instance of Attributes.Name instead of String.
I didn't create a simple pull request, because I don't understand the purpose of this line. Why shouldn't a mod-file that contains a coremod get its mcmod.info-data?

**Comment by liach** [comment]
That parameter is an object, assumed that the `String` object is also acceptable.

**Comment by Mathe172** [comment]
Yeah, you can pass a `String` to it, but that will never return anything

**Comment by killjoy1221** [comment]
Except it works because an Attribute hashcode uses the name's hashcode.  Keys in a map are special, so multiple objects of different types can represent the same one.

**Comment by Mathe172** [comment]
But 'Name.equals' only returns true if the other object is also a `Name`-object, so it still won't work if you try to get it with a `String`. Besides, `Name.hashCode` doesn't return the hashcode of the name as far as I can tell

**Comment by LexManos** [comment]
As I freaking told you on IRC THIS IS DEAD CODE.
The Coremod/Tweaker filter is elsewhere. And if this WAS working it would break the 'ContainsFMLMod' feature. But since you are SOOOOOOOOOOOO worried about I will delete these lines. Because they literally do nothing. -.-

**Comment by Mathe172** [comment]
Thanks. If you note the creation time you'll see that I created this issue before you notified me about it being irrelevant ;-)

**Comment by LexManos** [comment]
Yes, but your guy's bitching about it in the comments was after the fact.
