### ISSUE TITLE
WorldServer.getTileEntitiesIn() does not cover whole range

### ISSUE THREAD

**Issue by ljfa-ag** [MinecraftForge/MinecraftForge#2350]
The patches Forge does to WorldServer.getTileEntitiesIn() appear to break it and make it not find all tile entities within the range.
Forge's patched version is looping through the blocks like this:
```java
for (int x = minX; x < maxX; x += 16)
{
    for (int z = minZ; z < maxZ; z += 16)
    {
```
for example, consider the case minX = 14, maxX = 17. In this case the range goes over a chunk boundary, even though is itself narrower than a chunk. So the loop ends after one iteration (14 + 16 > 17), even though it would have to check two chunks.

Edit: A solution might look like this:
```java
for (int cx = minX >> 4; cx <= maxX >> 4; cx++)
{
    for (int cz = minZ >> 4; cz <= maxZ >> 4; cz++)
    {
```
and World.getEntitiesWithinAABB is doing something similar already.

**Comment by LexManos** [comment]
The problem with that is that the way you specified it the issue the extra loop when it comes to things because the end point is NON-inclusive. So {0, 16} will get you all the TEs in that chunk. But this should work due to bit mathc magic. Basically i'm flooring the mins by 16.
