### ISSUE TITLE
World.getDifficultyForLocation() event

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#2351]
getDifficultyForLocation() controls the precise difficulty level for a given in-world area, taking into account things such as the world time, the time spent inhabited in one chunk and the moon phase. Sadly, it cannot be hooked without a coremod as its DifficultyInstance creation is hardcoded inside the function and unmodifiable. Any ideas on the best way to design an event for it?

**Comment by Actuarius** [comment]
@diesieben07 added labels [Feature]
