### ISSUE TITLE
Configurable SRV Record (for Modpacks)

### ISSUE THREAD

**Issue by rallias** [MinecraftForge/MinecraftForge#2352]
Vanilla Minecraft (and modpacks by extension) have the ability to do a DNS lookup for the SRV record _minecraft._tcp, which allows a server maintainer to point their domain, say retards-r.in, to their minecraft server. However, this can be at odds, if, for example, I have a 1.7.10 pack and a 1.8.9 pack. I'd like to be able to set the 1.7.10 pack to use _minecraft._tcp (because as I understand it, 1.7.10 is feature frozen), but have the 1.8.9 pack use _retardscraft189._tcp instead.

(and yes, the domain name and pack name are real, although rtc189 isn't setup yet)

**Comment by jk-5** [comment]
I think SRV records are a nasty hack. What is wrong in using just a subdomain like mc.retards-r.in, modded.retards-r.in. My experience with SRV records is that they do not work all the times. Could be me, but to me this sounds really hacky.

**Comment by rallias** [comment]
Well, for a subdomain in the first place (as opposed to srv records), because I'm probably going to need to define a port if I add another server, and some people live up to the server's hostname.

As opposed to diff sub for different modded servers... well that's the point of this feature request.

**Comment by LexManos** [comment]
Havnt looked into this particular mechanic, but you usually configure the srv records in your domain/host not in Minecraft itself.. {I may be wrong}
What exactly are you wanting us to configure? Where in the code do you want us to change? Better with a PR.

**Comment by rallias** [comment]
With forgeSrc 1683, this ends up on line 97 of net.minecraft.client.multiplayer.ServerAddress as the following:

    Attributes attributes = dircontext.getAttributes("_minecraft._tcp." + p_78863_0_, new String[] {"SRV"});

I'd like to have the first argument of the dircontext.getAttributes configurable in some means.

I can look into a pull request, although, to be quite honest, my java is jacked.

**Comment by LexManos** [comment]
Why.... this just doesn't make sense.. you're a minecraft client..... 
I'm trying to think of what this would be of use for?
Maybe running two servers on the same server. But this would be an issue.
This doesn't seem like something we want to get into because it breaks standards, we'd also have to setup a system where we list ALL servers on that address.
Is there a way to list all records/attributes? I haven't done anything with this before.

**Comment by rallias** [comment]
As Minecraft (vanilla) currently works (ignoring the <hostname>:<port> bits, which I don't see atm), it tries to lookup _minecraft._tcp.<provided hostname> type SRV. If this fails (I'm in a 1.7.10 env, but the implementation looks the same), it falls back to <hostname>:25565. All I'm saying is, as a pack creator, I want to be able to set a different value for this attribute. I don't think there should really need to be a fallback mechanism (except perhaps to _minecraft._tcp.<provided hostname>, although this is debatable).

Implementation would be (at a high level) replacing the above line with something similar to the following (not exact functions, I'm not currently knowledgeable on how forge handles its internal configuration):

    Attributes attributes = dircontext.getAttributes((ForgeConfig.hasConfig("srv_record")?ForgeConfig.getString("srv_record"):"_minecraft")+"._tcp" + p_78863_0_, new String[] {"SRV"});

**Comment by heldplayer** [comment]
You can use subdomains to achieve this without having Forge change standard behaviour.

For example, if you have 2 servers running at the same IP but want each to be accessible from different hostnames (smp.example.com and cmp.example.com) without having to manually enter a port to connect to you'd have the following in your DNS zone configuration:

```
smp                     15M     IN      A       93.184.216.34
cmp                     15M     IN      A       93.184.216.34
; _service._proto.name. TTL     class   SRV     priority   weight  port    target.
_minecraft._tcp.smp     1d      IN      SRV     10         10      25569   smp.example.com.
_minecraft._tcp.cmp     1d      IN      SRV     10         10      25568   cmp.example.com.
```

**Comment by rallias** [comment]
> You can use subdomains to achieve this without having Forge change standard behaviour.

I already acknowledge this. The point of this request is such that a hypothetical future pack can say "You use the SRV record _example._tcp rather than _minecraft._tcp".

**Comment by LexManos** [comment]
I can see what you want, and it does have *some* merriat allowing a server provider to run multiple 'packs' on the same domain and let users access it using the same IP.
This traditionally is done using a bouncer service like BungeeCord, but could be possible to do via the SRV record.
What I would suggest tho is finding a way to either query ALL the records.  Or finding a way to make adding 'some.server' to your multiplayer list popup as two separate servers one of the '_minecraft' one for the '_custom'. With some representation of which is which {MOTD would probably be fine}

The eventual goal of Forge is to be a 'Hey end user, install ALL THE MODS' and then connecting to a server gives you a subset of them. Our tech is in place for that, modders just need to cleanup some of the stuff they do. So allowing packs to override the vanilla pull gets kinda weird.
Also remember that even if you have a modpack installed it should still allow you to connect to vanilla servers as that's something Forge supports. {This goes back to that subset thing, Forge detects vanilla and uses the 'vanilla subset'}

**Comment by rallias** [comment]
Well, if that's the way you feel that what I propose should be accomplished, I can write the patch if you point out to me how to deal with the configuration option. It'll be a (relative) monster patch, need a couple revisions, but I think I can do it.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Feature]
