### ISSUE TITLE
Possibility to separate TESR item hook and BlockRendererDispatcher.renderBlockBrightness()

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2353]
Request for @RainWarrior.

#2066 Resolved the rendering of modded TESRs on minecarts. However, it ties the rendering into the TEISR (item TESR render) hook. In the edge case where the item model is a model system model and the block is TESR rendered, this is becomes a problem.

For example, the Botania pylons are a static OBJ model in item form, but they become TESRs in block form to animate and control group visibility. Since renderBlockBrightness calls the TEISR, trying to render a pylon using renderBlockBrightness does nothing.

Another example are the Botania mana pools. They are static json models in item form, but need a TESR in block form to apply dynamic coloring to the model (fabulous pool). So the mana pool minecart doesn't render anything because it attempts to render an the item form, which is not registered to the TEISR.

Is there some way we can change the renderBlockBrightness hook to directly render the TE? I know it diverges from vanilla behavior in this regard but it really makes more sense to actually render the TE instead of throwing it to a seemingly irrelevant item renderer.

**Comment by RainWarrior** [comment]
renderBlockBrightness doens't use the item renderer, it uses the block model for the specified blockstate, which for minecarts comes from EntityMinecart.getDisplayTile()

**Comment by williewillus** [comment]
For tile entities, it does.

BlockRendererDispatcher.renderBlockBrightness checks the render type. If it is 2, as it is in this case, then it calls chestRenderer.renderChestBrightness which directly calles the TEISR (TileEntityItemStackRenderer.renderByItem()). Which will do nothing if the block has a model system item model.

So blocks with model system item form and TESR block form can't be rendered with renderBlockBrightness

**Comment by RainWarrior** [comment]
use render type 3 then.

**Comment by williewillus** [comment]
but then the static model will render in world, which I don't want happening because I have a TESR to animate it

**Comment by RainWarrior** [comment]
Use an empty model for in-world state, and non-empty one for the minecart

**Comment by ljfa-ag** [comment]
How do I make an empty model in JSON? When I try to make a model with an empty "elements" array it complains that a model needs at least "parent" or "elements".

**Comment by williewillus** [comment]
^ I just have a single face with "from" and "to" both set to [0, 0, 0], and some bogus texture name and UV's. Works fine and no errors for me

**Comment by williewillus** [comment]
I've found my own solution for this, as suggested above
