### ISSUE TITLE
Inconsistent cache key reference in OBJLoader (build 1688)

### ISSUE THREAD

**Issue by grondag** [MinecraftForge/MinecraftForge#2361]
The file and modelLocation variables are used interchangeably as cache keys.  For example:

    cache.put(modelLocation, model);

and then a few lines later...

    OBJModel model = cache.get(file);
        if (model == null) return ModelLoaderRegistry.getMissingModel();

This doesn't cause a problem unless modelLocation includes a suffix like #normal.  

I found it because my code was passing in a ModelResourceLocation value that included a suffix. This worked before a recent update.  Workaround was to construct and pass in a ResourceLocation value that did not include a suffix.

Probably not going to show up for most mod developers, but seems like asking for trouble to use inconsistent values as keys.

**Comment by shadekiller666** [comment]
This has been fixed and is sitting in a PR awaiting review, should be in forge in a week or so.

**Comment by grondag** [comment]
Saw that.  Looks good.  Thanks for the quick response.

**Comment by shadekiller666** [comment]
You're welcome.
