### ISSUE TITLE
Capability proposal: Dyeable items

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#2368]
amadornes told me to post this here, so here it is:

A capability which defines an item which can be dyed in a similar manner to vanilla's leather armor. The storage involves storing an integer which contains the color of the item (or -1 if the item is not colored). The API contains three methods: getColor(), hasColor() and setColor().

Also, vanilla has a recipe handler for dyeing armor, which is re-used in a lot of mods. It might be a good idea to adapt that recipe handler to support the dyeable item capability.

**Comment by LexManos** [comment]
I'm looking for PRs. Easier to discuss and understand code then rough ideas.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Feature]
