### ISSUE TITLE
Detecting JVM version incompatibilities

### ISSUE THREAD

**Issue by ljfa-ag** [MinecraftForge/MinecraftForge#2369]
I recieved a crash report from someone who tried to use Java 7 with my mod which requires Java 8, obviously leading to an UnsupportedClassVersionError. This is arguably an error on the user's side, but the crash report begins like this:

>---- Minecraft Crash Report ----
>
>*** ATTENTION: detected classes with unsupported format ***
>*** DO NOT SUBMIT THIS CRASH REPORT TO FORGE ***
>
>__Contact authors of the following mods:__
> ...

This is a counterproductive because I do not want to receive invalid bug reports if someone uses the wrong JVM version for my mod.
It would be nice if Forge could detect that e.g. a class of version 52.0 will not run on Java 7, and produce a clear error message along the lines of "mod X requires at least Java Y".

**Comment by LexManos** [comment]
It's possible to scan and just skip mods that have class files that are in the incorrect JRE version.
However it is the official stance of Forge that this is a DEVELOPER error not a user error.
Minecraft is J6. Your mod should be J6.
If you MUST use J8 syntax because you feel like it, there are options for automatically converting the bytecode to J6 compatible formats.

**Comment by Deamon5550** [comment]
You could also setup your mod such that the first class (either your mod or coremod class) is compiled for java 6 and perform the check and return a nice error from there.

**Comment by ljfa-ag** [comment]
Well that's unfortunate.

Okay so how would I set up gradle so that it compiles only one class for Java 6?

**Comment by diesieben07** [comment]
You can check out my [build.gradle](https://github.com/diesieben07/SevenCommons/blob/1.7/build.gradle#L83-L102) and this [warning window](https://github.com/diesieben07/SevenCommons/blob/1.7/src/main/java/de/take_weiland/mods/commons/util/JavaCompatibility.java). Feel free to use them.

**Comment by ljfa-ag** [comment]
Alright, thank you ^^

**Comment by chylex** [comment]
@ljfa-ag You can also shade Java Checker into your mod, admittedly it's a bit hacky but it's well tested and requires less work for you.
