### ISSUE TITLE
EXTREMELY broken textures

### ISSUE THREAD

**Issue by Dvx105** [MinecraftForge/MinecraftForge#2372]
Hello,

I have had huge problems with textures working since I downloaded Forge. Many textures seem to glitch and not work properly on world startup:

![2016-01-13_15 51 04](https://cloud.githubusercontent.com/assets/16628771/12308950/b986a7d2-ba0d-11e5-9d0e-fa55d8932a22.png)

![2016-01-13_15 50 59](https://cloud.githubusercontent.com/assets/16628771/12308946/b393343a-ba0d-11e5-94ee-e40cfb6ffe3b.png)

How can I fix this problem?

I have Minecraft version 1.8 and Forge version 11.14.4.1563.

**Comment by LexManos** [comment]
1) Update forge
2) Disable the loading screen
3) Stop using a mac, they are shit.

**Comment by iTitus** [comment]
Also update MC to 1.8.9 and Forge appropriately.
