### ISSUE TITLE
PotionEffect still uses numerical ID's

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2374]
#2225 brought us a potion registry that automatically handles assigning and remapping of ID's as appropriate. However, the primary form we deal with using and applying these potions is through PotionEffect objects. PotionEffects however, unlike their FluidStack and ItemStack counterparts (which use delegate of Fluid and Item respectively), still rely on int ID's, with no indicator of either the ResourceLocation name or Potion object of their actual potion effect. I feel like this half defeats the purpose of the registry, which is to abstract and encapsulate the int ID's away from modders so they don't have to worry about them. 
Shouldn't we patch PotionEffect to also use a delegate of Potion?

In addition, many of the methods in PotionEffect also look up ID's in the raw potion array instead of the registry, is this intended?

Currently we have to do GameData.getPotionRegistry().getObjectById(effect.getPotionId()) or worse yet most ported code will still keep Potion.potionEffects[effect.getPotionId()].

Thoughts?

**Comment by Spartan322** [comment]
We need to get PotionEffects off of all the vanilla packets (PotionEffects I think have some of the most complex packet handling iirc), otherwise this idea won't work, which currently no one has bothered to do. That is why it hasn't been done yet.

**Comment by williewillus** [comment]
I don't think that'll be the problem because when packets are sent the ID maps are already synchronized on both sides. That's how vanilla packets that use number id's for ItemStacks are still working

**Comment by diesieben07** [comment]
Really there should just be a method `getPotion` added to `PotionEffect`.

**Comment by Spartan322** [comment]
Might do better to get out of using the Potion class anyway.

**Comment by williewillus** [comment]
? no, that's what we *should* be using instead of number ID's
See: How ItemStacks use Item instead of number ID's, or how FluidStacks use Fluid instead of number ID's

**Comment by LexManos** [comment]
This is something that can be looked into however a lot of the internals of MC code still deal with IDs and the arrays directly. The patch to benifit ratio may be not worth it.
But Adding a getPotion delegate to PotionEffect most likely should be done yes.

**Comment by asiekierka** [comment]
From what I know, 1.9 removes ID-based access from potions in much the same way 1.7 removed it for blocks. Might be worth it to simply wait.

**Comment by williewillus** [comment]
Yeah, just took a look in the snapshot. Everything is using string ID's, but still manually assigned. We can hold off until 1.9 then

**Comment by williewillus** [comment]
Just a side note / followup

This bit me because Botania registers some Brews, which are composed of one or more PotionEffects. Since PotionEffect still uses integer ID's, the idmap shifts when connecting to a server and screws all my Brews.

My temp solution for this was making my own shim class that uses the Potion object instead of integer id.

How is this planned to be resolved in 1.9, or are there systems in place to do that already?

**Comment by LexManos** [comment]
1.9 has moved potions to a registry system just like Blocks and Items.
And in 1.8 there is the registry remap event that you can listen for and handle your things correctly.
You should be doing this anyways so ya.. get on that.

**Comment by williewillus** [comment]
Ah lol, I forgot that existed >.> 
thanks

**Comment by williewillus** [comment]
Actually wait - the id remap event doesn't seem to be fired for potions. the enum inside it only has BLOCK and ITEM.

and the method that fires the event only has two maps, again for block and item.
