### ISSUE TITLE
[1.8.8] Block Gui not opening while holding a block

### ISSUE THREAD

**Issue by MrHappyKilller** [MinecraftForge/MinecraftForge#2379]
So, this is quite simple. My block, extending BlockContainer, using a Container, GUI, and TileEntity; will not open if I am holding a block of any kind in my hand. Not sure if this is an issue with forge, but people on the Minecraft Forge Forums said it must be considering my classes are all correct. Hope this get's fixed soon!

**Comment by LexManos** [comment]
This is not a bug in Forge. As you an see many vanilla Containers open just fine when holding items in your hand.
You must have some issue somewhere that is causing the issue.
As this has no context, no reproducability, this is closed. Please return to the forums and figure out where your code is wrong.
