### ISSUE TITLE
[1.8.9] GatherCapabilities will not create a CapabilityDispatcher when no capabilities are attached but an ICapabilityProvider parent is present through Item.initCapabilities

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#2383]
See this line:

    return event.getCapabilities().size() > 0 ? new CapabilityDispatcher(event.getCapabilities(), parent) : null;

It either needs to be corrected to:

    return (event.getCapabilities().size() > 0 || parent != null) ? new CapabilityDispatcher(event.getCapabilities(), parent) : null;

or another fix devised, otherwise a non-null parent with no capabilities registered via events will not create a CapabilityDispatcher.

EDIT: This affects ItemStacks, for which the parent getCapability/hasCapability method cannot be overwritten on the stack directly.

**Comment by LexManos** [comment]
Right, parents were added on at the end. I knew I missed something. If only this was a PR and I could click the button to pull it in right now.. Oh well guess I have to do it myself.
