### ISSUE TITLE
[1.8.9] OreDictionary.doesOreNameExist() was removed

### ISSUE THREAD

**Issue by BluSunrize** [MinecraftForge/MinecraftForge#2397]
Basically what the title says.
There used to be a method in the OreDictionary labelled "doesOreNameExist", which checked the presence of a name in the Dictionary. This method vanished somewhere between 

https://github.com/MinecraftForge/MinecraftForge/blob/c474da04b3cae97c05f2f49b0a1f4bfb57763f8c/src/main/java/net/minecraftforge/oredict/OreDictionary.java#L414-L417

and 

https://github.com/MinecraftForge/MinecraftForge/blob/112c41a70777de47ecc68c804e548e0ed951c4e3/src/main/java/net/minecraftforge/oredict/OreDictionary.java

But no commit actually shows its deletion.
The method allowed the checking of a names presence WITHOUT generating a new ID. Without this method, our only option is getOres(name).isEmpty(), and this WILL generate a new Ore ID.
Could we maybe get this added back in? It was very useful for OreDict-based compatibility, like adding recipes only when a certain name was already present.

**Comment by TehNut** [comment]
The method was added after 1.8 was started and was never ported over.

**Comment by BluSunrize** [comment]
AH! Well then, it would be great to get it ported!

**Comment by ganymedes01** [comment]
Adding a recipe for an ore that isn't present doesn't really matter much, it will never get matched so the user would never know.

**Comment by LexManos** [comment]
The only reason this is needed is because dumb people screw with the interal arrays/lists so allocating more then is needed is slow because they used interal shit.
Anything else that is missing? It probably got skipped in the branch merge cuz stupid git.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/82647f5b669cc6f3947de5f09fa6043e61dd315c
