### ISSUE TITLE
Custom armor model hook does not consider block breaking / riding state of entity

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2400]
This was missed in the porting of patches to 1.8, I believe.

This is the code in question, located in LayerArmorBase.renderLayer (func_177182_a)
```
T t = this.func_177175_a(armorSlot);
t.setModelAttributes(this.renderer.getMainModel());
t.setLivingAnimations(entitylivingbaseIn, p_177182_2_, p_177182_3_, p_177182_4_);
t = getArmorModelHook(entitylivingbaseIn, itemstack, armorSlot, t);
```

Local variable t is of type \<T extends ModelBase\> and represents the ModelBase to be rendered on the player. setModelAttributes and setLivingAnimations updates this modelbase with relevant information important to rendering, such as whether the entity is a child, whether it is riding, and whether it is breaking blocks.

Note that the forge hook to get custom mod-provided modelbase for armor render is placed after setModelAttributes and setLivingAnimations, causing the custom model to not receive updated information about the entity it is rendering on.

As a result, a mod with custom armor I am porting from 1.7 fails to correctly offset the armor when the player is sitting or mining, both of which are set in setModelAttributes, which never gets called on the custom model.

The solution is to move the hook line up, as follows:
```
T t = this.func_177175_a(armorSlot);
t = getArmorModelHook(entitylivingbaseIn, itemstack, armorSlot, t);
t.setModelAttributes(this.renderer.getMainModel());
t.setLivingAnimations(entitylivingbaseIn, p_177182_2_, p_177182_3_, p_177182_4_);
```

Since this change is so trivial, I did not make a PR. Please indicate if I should do that.

**Comment by asiekierka** [comment]
You probably should. I was asked to do a PR for a one-line fix.

2016-01-22 8:33 GMT+01:00 Vincent Lee <notifications@github.com>:

**Comment by williewillus** [comment]
this was fixed
