### ISSUE TITLE
Capability proposal: Worker Capability

### ISSUE THREAD

**Issue by rubensworks** [MinecraftForge/MinecraftForge#2403]
The aim of this issue is to discuss a way to expose the _working_ status of a (vanilla) machine using Forge capabilities.
The way I see it, vanilla Minecraft has two blocks that would be able to expose a _working_ status, namely the _furnace_ and _brewing stand_, however I believe there is no reason why such a capability would only have to be limited to those two blocks. As such, I would like to make it general enough so it can be used to expose the working status of any modded machines (or even items), or any future ones Mojang might add.

Just to make clear what I’m talking about, a _worker_ capability would basically describe the following information about the given block:
- Furnace: Is the furnace currently cooking/smelting something? If it’s not smelting, could I actually smelt something in it (i.e. does it have enough fuel) ?
- Brewing stand: Is it brewing something at the moment? If not, can I add stuff to it to start brewing or is it perhaps missing something (eg water bottles, or blaze powder in 1.9)
- Pulverizer: Is it currently grinding something? If not, can I grind something (i.e. does it have enough power to do so) ?

Due to the large amount of machines that exist in various mods (including vanilla), I would like to hear your input before starting on an actual implementation.
I do however have two ideas in mind of what such a general capability could look and will discuss them below. 
## WorkCapability

A first simple approach on defining this capability would be to use an interface similar to BuildCraft’s `IHasWork` interface. This capability could thus consist of the following methods:

```
boolean hasWork(); // If the tile has things to process
boolean canWork(); // If the tile is able to work
```

If this capability would be applied to the furnace, `hasWork()` would check if there is a smeltable item in the input slot, while `canWork()` would check if there is fuel in the tile.
Note that it is possible to add a third method to this capability:

```
boolean isWorking(); // If the tile is currently working
```

This method would however be little more then a convenience method because it can be expressed as the conjunction of the other two methods.
## ConditionalWorkerCapability

While the previous capability might be enough for most cases, some machines might have multiple work tasks, like for example Steve’s Workshop.
This capability would expose the following method:

```
Collection<IWorker> getWorkers(); // All work tasks in this tile
```

The `IWorker` interface represents one work task of a tile and can contain the following methods:

```
Collection<IWorkCondition> getConditions(); // All conditions for this task
boolean isCondition(IWorkCondition workCondition); // If this condition is met
boolean areAllConditions(); // If all conditions are met, convenience method
```

The `IWorkCondition` could possibly contain a method to show the type of work, but this would require a set of categories to be defined. One category would be the `FuelCondition`.

A vanilla furnace would for example return one `IWorker` in its capability, which will have two `IWorkCondition`s. The first condition would apply to the input slot contents, while the second one would represent its fuel status.

Other mods which provide machines with for example multiple furnaces in one block could return a separate `IWorker` for each furnace.
## Conclusion

I welcome any feedback on this proposal to build a _working_ capability. It is clear that the first capability proposal is sufficient for the two vanilla machines, but it might be too limited for some mods. On the other hand, the second proposal could be overkill for only vanilla machines. I would like to hear if modders are 1) interested in such a capability and which use cases they foresee with this, 2) have any reasons for _not_ adding this capability, 3) preferences for the first or second approach and 4) any suggestions for any of the two approaches.

Note: This post is the result of discussion between myself and @immortaleeb.

**Comment by rubensworks** [comment]
A first use case I foresee is the possibility for BuildCraft gate-like systems to be used to detect the status on machines.

**Comment by asiekierka** [comment]
Look into IHasWork in BuildCraft.

The first part is neat and has been implemented by the entire BuildCraft
ecosystem back in the day. The second part, however, is potentially
troubling: you still have to be aware of all the IWorkConditions, unless an
IWorkCondition gives it some unique identifier - and then we get into
incomaptible IWorkConditions.

2016-01-22 20:39 GMT+01:00 Ruben Taelman <notifications@github.com>:

**Comment by rubensworks** [comment]
Exactly, the second approach might be too generic in its current state.
This problem could however be partially solved by defining a set of pre-defined conditions which can be reused across several `IWorker`'s, like for example a `IWorkCondition.FUEL` and `IWorkCondition .BREWING_INGREDIENTS`.
When mods require other custom conditions they will indeed be incompatible with similar conditions from other mods unless these are standardized as well.

**Comment by ganymedes01** [comment]
+1

**Comment by AlexIIL** [comment]
This sounds interesting, but I am wondering what your definition of ````IWorkCondition```` is and what it would do. Is it meant to be from an enum constant group (````FUEL````, ````INGREDIENTS````) or any number of separate classes that could return specific values (for example, ````IEnergyCondition```` that could return the amount of energy that it requires, and the amount that it has). Obviously in the case of separate classes you wouldn't know anything other than "this needs something", but it might be useful for consumers (for example logistics pipes might use this in order to keep a machine filled up with specific items or fluids).

**Comment by rubensworks** [comment]
@AlexIIL I wouldn't make the `IWorkCondition` a fixed enum group, but rather a marker interface with some default Forge implementations (`FUEL`, `INGREDIENTS`) like you mentioned.

The `IWorkCondition` implementations that are provided by other mods (like `IEnergyCondition`) could be part of their API so that other mods can detect their usability.
But I'm now actually wondering how much sense these conditions would make when such information (like from `IEnergyCondition`) can be perfectly be exposed using capabilities.
So this second approach might be a bit of overkill, unless someone can give a clear use case where the first approach would be insufficient. Otherwise, I will soon start looking into implementing the (simple) first approach.

**Comment by LexManos** [comment]
Show the actual implementation because I can tell you right now this IWorkCondition will not be going in as a generic marker interface. Doing so negates the point of Capabilities to safely type things. 
This is way to generic to be considered right now.

**Comment by Gaelan** [comment]
`isWorking` isn't necessarily just `hasWork() && canWork()`: This doesn't apply to vanilla, but many mod machines have the ability to be disabled (often by Redstone). Maybe add a `willWork()`?

**Comment by rubensworks** [comment]
@Gaelan If a machine were to be disabled by redstone, I would say that the tile is not able to work in its current state, and I would simply return false for `canWork()`. I think adding a third, semantically similar method will make the interface quite difficult to understand.
This means that indeed the interface is not expressive enough to make a distinction between disabled work by redstone and low power, but this is something that could be detected ad hoc by using an energy capability for reading its power level.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Feature]

**Comment by Alpvax** [comment]
> This method would however be little more then a convenience method because it can be expressed as the conjunction of the other two methods.

Not strictly, it could satisfy both of those but still require a button click in a gui to start

**Comment by HenryLoenwind** [comment]
Really, necroing this after it was closed?

Whatever, let me give my 1.9979 cents: A machine is either:

* working (duh)
* idle (no input materials)
* blocked (input mats but no fuel, full output slot, ...)
* stopped (by user, redstone, other logic)

If it is `working`, it either has a task percentage or is running continuously.

That's about 110% of the maximum similarities between different mods we can get; e.g. machines that are `idle` and `blocked` could report either or both. This really depends on how a machine works and its code is written.

**Comment by Alpvax** [comment]
Sorry, the PR link didn't display on my phone. I just thought this had been forgotten about.

Could somebody please close this issue again.

**Comment by AlexIIL** [comment]
It is closed.

I don't think this is going into forge as the PR for it was closed without an explicit reason.
