### ISSUE TITLE
Forge 11.15.0.1715 for MC 1.8.9 has an MCP version mismatch

### ISSUE THREAD

**Issue by jeep70** [MinecraftForge/MinecraftForge#2405]
https://dl.dropboxusercontent.com/u/8082184/ShareX/2016/01/2016-01-22_21-28-47.mp4

**Comment by LexManos** [comment]
Meh just a visual bug in the mcmod.info. Nothing really important whenever someone gets around to it they'll fix it.

**Comment by jeep70** [comment]
Seems like it's fixed as of 11.15.1.1722
