### ISSUE TITLE
Forge 11.15.0.1715 BlockPos.offset(EnumFacing) doesn't seem to be working

### ISSUE THREAD

**Issue by AKTheKnight** [MinecraftForge/MinecraftForge#2408]
Checked BlockPos before and after offset and values are the same

**Comment by iLexiconn** [comment]
Did you do `pos = pos.offset(EnumFacing.NORTH)`?

**Comment by AKTheKnight** [comment]
Nope. Stupid mistake by me. Forgot to do pos =
