### ISSUE TITLE
Latest shouldRefresh fix still causing "refresh-issues"

### ISSUE THREAD

**Issue by Lordmau5** [MinecraftForge/MinecraftForge#2409]
So, I saw that there was a commit a few days ago regarding the shouldRefresh method in the Block class, that should've fixed refreshes on tile entities:
https://github.com/MinecraftForge/MinecraftForge/commit/66895a520a9823ce2bba4aa233edd5f0b74125b9

**However**:
This issue occured to me first on Forge 1696, as seen in the following 2 videos:
https://i.lordmau5.com/1453414189-578
https://i.lordmau5.com/1453414492-580
I have heard from another user (and cpw) on Twitter that this should've been resolved in 1700+, so I updated my dev-environment to 1715 (the newest at that time).
I tried it again, but the issue still occured.

**Comment by LexManos** [comment]
The second issue is a z-fighting issue nothing related to the refreshing of TEs.
As our shouldRefresh change simply restored the mechanics of 'By default only refresh when metadata changes' If mods are still broken, then its a matter of their override of shouldRefresh being broken.
