### ISSUE TITLE
Texture pack issue with 11.15.0.1715?

### ISSUE THREAD

**Issue by Thiana** [MinecraftForge/MinecraftForge#2410]
I'm not sure if this is a bug with forge or with the texture packs, but it occurs with multiple packs and is only present with forge installed.

The problem is that textures are sometimes displaying as missing on forge (with no mods) when they show correctly with vanilla. I've attached 3 sets of screenshots showing the problem with and without forge.

The log  complains about missing models yet those models seem to be there on vanilla?

Each set is (1) Forge with Alternate Blocks On, (2) Forge without AltBlocks, (3) Vanilla with AltBlocks, (4) Vanilla without AltBlocks.

With http://www.curse.com/texture-packs/minecraft/lithos-core-32x-1-8-1-9-snapshot-complete:
Forge:
![forge-lithoscore18-alt](https://cloud.githubusercontent.com/assets/405832/12531794/f827ba46-c1d1-11e5-87cb-b582cce837d3.jpg)
![forge-lithoscore18-noalt](https://cloud.githubusercontent.com/assets/405832/12531795/f8293ca4-c1d1-11e5-91be-cfec19c571ea.jpg)
Vanilla:
![vanilla-lithoscore18-alt](https://cloud.githubusercontent.com/assets/405832/12531800/f83daa5e-c1d1-11e5-858e-4fd2bedd629e.jpg)
![vanilla-lithoscore18-noalt](https://cloud.githubusercontent.com/assets/405832/12531801/f8408ada-c1d1-11e5-8e7d-6f982e64e54d.jpg)

With http://www.curse.com/texture-packs/minecraft/marvelouscraft
Forge:
![forge-marvelouscraft162-alt](https://cloud.githubusercontent.com/assets/405832/12531796/f82be6c0-c1d1-11e5-9591-bb9d89c80286.jpg)
![forge-marvelouscraft162-noalt](https://cloud.githubusercontent.com/assets/405832/12531798/f833b8d2-c1d1-11e5-9b66-69701b08a78e.jpg)
Vanilla:
![vanilla-marvelouscraft162-alt](https://cloud.githubusercontent.com/assets/405832/12531846/3e96cf5c-c1d3-11e5-85c1-39a0d7be4e6c.jpg)
![vanilla-marvelouscraft162-noalt](https://cloud.githubusercontent.com/assets/405832/12531847/3e9946e2-c1d3-11e5-8360-e2362199c7d7.jpg)

No Texture Pack:
Forge:
![forge-nopack-alt](https://cloud.githubusercontent.com/assets/405832/12531797/f8334c94-c1d1-11e5-8913-e68e61cd3970.jpg)
![forge-nopack-noalt](https://cloud.githubusercontent.com/assets/405832/12531799/f83a49f4-c1d1-11e5-82b4-a459aac84052.jpg)
Vanilla:
![vanilla-nopack-alt](https://cloud.githubusercontent.com/assets/405832/12531804/f84c44f6-c1d1-11e5-9c8b-d2757db5ea6a.jpg)
![vanilla-nopack-noalt](https://cloud.githubusercontent.com/assets/405832/12531805/f84e2bc2-c1d1-11e5-94e8-0791916e610f.jpg)

Thanks.

**Comment by Thiana** [comment]
The blocks (from left to right) are Granite, Andesite, Stone, Diorite and Dandelions.

**Comment by LexManos** [comment]
Forge complaining about missing textures is most likely because the texture pack is missing them.
Vanilla has a bug in it where it silently ignore malformed resource packs and missing models. Forge does not. It is our opinion that it is better for the people who are making the resource pack to know they screwed up then to silently hide it.

So ya, basically the texture packs are most likely broken and specifying variants with invalid models.

**Comment by Thiana** [comment]
If the vanilla behavior is to compensate for missing models, wouldn't it be better for forge to do that and just post a warning to the log?

**Comment by LexManos** [comment]
No it wouldn't because then you run around with broken texture packs, nobody reads the logs.
You SHOULD go yell at the author of the texture pack to stop releasing broken stuff.
