### ISSUE TITLE
Shade colors are ignored when models are rendered in inventory

### ISSUE THREAD

**Issue by immortaleeb** [MinecraftForge/MinecraftForge#2412]
I've created a model that's both an `ISmartBlockModel` and `ISmartItemModel` which overrides `getGeneralQuads()` and provides quads which I shade with a certain color.

The colors seem to be applied properly when rendered in the world as a block, but when held in the inventory the shade color seems to be ignored:

![http://cl.ly/0b390h0h3S16](https://s3.amazonaws.com/f.cl.ly/items/2H2y3k3v0S0c1X2F1111/Screen%20Shot%202016-01-24%20at%2020.05.17.png?v=9ef0b662)

Example code can be found here: https://gist.github.com/immortaleeb/9c94563f7d804bea7d6b

Tested with forge 11.15.0.1716

**Comment by RainWarrior** [comment]
Use ColoredBakedQuad instead of normal BakedQuad.

**Comment by immortaleeb** [comment]
Is there anything different you need to do when using `ColorBakedQuads`?
If I simply replace my `BakedQuads` with `ColorBakedQuad` the item doesn't render at all when in the inventory.
