### ISSUE TITLE
[1.8.9] hasCapability queries getCapability in TileEntity by default

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#2415]
Is this by design or not?

    public boolean hasCapability(net.minecraftforge.common.capabilities.Capability<?> capability, net.minecraft.util.EnumFacing facing)
    {
        if (getCapability(capability, facing) != null)
            return true;
        return capabilities == null ? false : capabilities.hasCapability(capability, facing);
    }

I feel it voids the point of using hasCapability() to run the "is capability present?" checks and not repeating them in getCapability() later on. Therefore, I believe the getCapability() if-check should be removed. Is that OK?

**Comment by LexManos** [comment]
Its intentional yes because everyone argued that there should be a 'sane default' for lazy modders. 
Does it defeat the purpose of lazy loading stuff? Yes. But This entire thing is based on hoping that modders implement these functions in fast/sane ways.

**Comment by asiekierka** [comment]
Actually, if we want to leave supercalls around for capabilities added to our tiles via events by other mods, we cannot work around this and the "getCapability != null" bit will always be called. I argue that the sane default should be removed because, after all, modding Minecraft was never for the lazy ones due to the difficulty involved...

One possible solution would be to split

    return capabilities == null ? false : capabilities.hasCapability(capability, facing);

into an internal, protected method a modder can call to skip a part of the logic.

**Comment by LexManos** [comment]
Screw it, this is how I wanted it in the first place, but people bitched at me. 
I don't need to much convincing to revert it.
