### ISSUE TITLE
Revisiting PR #767: The Item Dictionary

### ISSUE THREAD

**Issue by TheDoctorSoda** [MinecraftForge/MinecraftForge#2416]
This is still a problem we face. We really do need a universal way for mod authors to share an item without depending on eachother. Even if this is just going to get closed immediately because of the whining that went on in #767, I would still like to have a little dicussion on how this could be implemented in the best way possible.

**Comment by LexManos** [comment]
Find a solution that wasnt addressed and discarded in that thread.
The OreDictionary exists and CAN BE USED to do exactly what you want. 
You just have to use it as such.

**Comment by ljfa-ag** [comment]
Just out of curiosity, may I ask what was this "feature coming in 1.7" mentioned in that thread? Doesn't seem like 1.7 was having something like that after all.

**Comment by LexManos** [comment]
The registry, our @ObjectHolder, delegates and the like IIRC.

**Comment by immibis** [comment]
@LexManos What is your recommended way to use the ore dictionary for this?
