### ISSUE TITLE
If the chunk a TileEntity is in goes out of the viewport, its TESR stops rendering

### ISSUE THREAD

**Issue by amadornes** [MinecraftForge/MinecraftForge#2419]
When a TileEntity is placed in a chunk and the player moves to another one and looks away, that chunk the TE is on stops rendering. This is a vanilla feature but the problem is that I need my TE to render even if the player is looking away from the chunk because the frustum still contains part of the TE's render bounds (I've expanded them by quite a few blocks). I've tried using infinite render bounds and the same thing happens.
It seems that not only is it not rendering the chunk behind you statically, but is also ignoring all TESRs, no matter what the TEs' render bounds are.

**Comment by diesieben07** [comment]
Override `getRenderBoundingBox` in your TE.

**Comment by diesieben07** [comment]
I think you also need `forceTileEntityRender` to be true now.

**Comment by amadornes** [comment]
Where would I find that? In the TESR? If so, why would it not be on by default? :/

**Comment by williewillus** [comment]
it's in the TESR, in my version it's unmapped as func_181055_a

the beacon overrides it to get special treatment and not get culled.
Not sure why it does both that and getMaxRenderDistance ?shrug

**Comment by amadornes** [comment]
Hmkay... I guess that's the way to do it now... Thanks! :)
