### ISSUE TITLE
forge blockstates json - empty fully-defined variant causes loading error

### ISSUE THREAD

**Issue by bdew** [MinecraftForge/MinecraftForge#2420]
This is valid:

    "variants": {
        "foo=bar": [{}],
    }

This should be valid too, but currently gives error:

    "variants": {
        "foo=bar": {},
    }

Stack trace here: https://gist.github.com/bdew/191bef66833e0256f560

Error is in  [this line](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/client/model/ForgeBlockStateV1.java#L81)

Should probably check for empty object before looking up fist element in it.

**Comment by williewillus** [comment]
Second one isn't valid, it has to be an array. Otherwise it treats "foo=bar" as a property and tries to find values inside

**Comment by bdew** [comment]
Look at the line of code i linked, it treats it as a property only if the first element in the object is another object - that check throws an error if it's empty.

Non-empty objects work correctly without being wrapped in an array. Even if they don't contain anything valid. eg:

    "variants": {
        "foo=bar": { "nothinghere":true },
    }

is valid (but stupid).

**Comment by LexManos** [comment]
Why would those ever be valid jsons? What would you expect that to do...

**Comment by bdew** [comment]
The same thing that [{}]

**Comment by UndeadZeratul** [comment]
could you just not include "foo=bar" and get the same effect, or am I not understanding how these are being parsed correctly?

**Comment by bdew** [comment]
That would generate a warning about a missing variant, wouldn't it?

I'm not asking for some groundbreaking change here, the code is already doing what it needs to be doing, just not checking input correctly.

Right now (in pseudocode)

  if (element is array) {
     for (each array entry) {
       parse variant
     }
  } else if (first entry in element is an object) {
      parse properties
  } else {
      parse variant
  }
   
If this runs on an empty object - the second check throws a NoSuchElementException.

What i'm suggesting is checking for that case and not crashing, that's it. I can PR it if needed but it's a really trivial one liner.

**Comment by LexManos** [comment]
Fry can make the decision, but i am of the opinion that this is a non-issue, or more precisely a user issue as doing what you're doing is stupid.

**Comment by williewillus** [comment]
Doing [{}] or {} is really common to inherit all attributes of the variant from defaults, in the case where many variants may share the same model.

e.g. 
```
"defaults": {
    "model": "<foo>",
},
"variants": {
    "normal": [{}], // full variant
    "inventory": [{}] // full variant
}
```

^That would be the standard blockstate for a block and item to share the same model.

**Comment by LexManos** [comment]
[{}] is fine, {} is meh, I intended the fully qualified block states to not inherit from the defaults like that but more as a hack to get around the old system, but meh. As I said i'll leave it to fry to decide on this.
I dont want to setup a workspace on this laptop right now as I'm about to leave the hotel and you guys didn't bother to make this a PR.

**Comment by RainWarrior** [comment]
Using array form only for full variants and object form for partial variants is imho the way it should be done, since it's much clearer what you're looking at from a first glance. Sadly, that's not how it was done originally, and now we have to live with a couple of special cases, at least until v2 of the format. I'd rather not add anything else to the logic deciding between full and partial variant.

**Comment by bdew** [comment]
@RainWarrior Even your "spec" says that objects are valid for full varian strings.

And again, it works for non-empty objects, why would it be so bad making it not crash for empty ones?

All the "logic" you would need to add is "!obj.entrySet().isEmpty()".

But i guess sanity and consistency is too much to ask for in this system, why do i even bother..

**Comment by LexManos** [comment]
What spec are you referring to? And jut because its your point of view does not make ours 'inconsistent' or 'insane'. Being a dick is not helping your argument, i can see your point of view, however I think you are wrong and the intention of the spec was not to do stupid things like this. And considering I was the one who wrote it, i am the best to judge what the intention was. 

However as I said, I couldn't care less. Fry has made his decision, insulting us and throwing a fit will not help you.

**Comment by bdew** [comment]
> What spec are you referring to?

https://gist.github.com/RainWarrior/0618131f51b8d37b80a6

This is (i guess) not an official document, hence the quotation marks in "spec", but it's the closest I've seen to actual documentation of the format. If there's anything better - i haven't managed to find it.

> stupid things like this

Is having an empty variant that just inherits from defaults stupid? Why?

Why is writing [{}] and less stupid than {}.

Why throwing NoSuchElementException any better than allowing the above?

> does not make ours 'inconsistent' 

By inconsistent i'm referring to the current state "We accept non-empty objects and arrays of both empty and non-empty objects. But for empty objects we crash" - this seems inconsistent to me, YMMV.

> or 'insane'

I'm not saying your viewpoint is insane, i'm saying that the current state is not entirely sane. Again, that's my opinion, YMMV.
