### ISSUE TITLE
TRSRTransformation.toItemTransform() produces incorrect translation

### ISSUE THREAD

**Issue by TheGreyGhost** [MinecraftForge/MinecraftForge#2425]
It appears that TRSRTransformation.toItemTransform() doesn't work properly.
For example a round trip of the Identity ItemTransformVec3f doesn't give the original back.

Demonstration code:
          Vector3f rotation = new Vector3f(0, 0, 0);
          Vector3f scale = new Vector3f(1, 1, 1);
          Vector3f translation = new Vector3f(0, 0, 0);
          ItemTransformVec3f testITV3f = new ItemTransformVec3f(rotation, translation, scale);
          TRSRTransformation trTest = new TRSRTransformation(testITV3f);
          ItemTransformVec3f backCalc = trTest.toItemTransform();
          System.out.format("initial: rot %s; trans %s; scale %s\n",
                  testITV3f.rotation.toString(), testITV3f.translation.toString(), testITV3f.scale.toString());
          System.out.format("final: rot %s; trans %s; scale %s\n",
                  backCalc.rotation.toString(), backCalc.translation.toString(), backCalc.scale.toString());

Output:
initial: rot (0.0, 0.0, 0.0); trans (0.0, 0.0, 0.0); scale (1.0, 1.0, 1.0)
final: rot (0.0, 0.0, 0.0); trans (1.5707964, 0.78539854, 3.1415927); scale (1.0, 1.0, 1.0)

Looks suspiciously like PI/2, PI/4, and PI.

I'm trying to figure out the bug myself but it is heavy going!

**Comment by ThexXTURBOXx** [comment]
Looks like this commit changed it: https://github.com/MinecraftForge/MinecraftForge/commit/c4f370a7e6e5b91813f93a14c45b64a7c0b30958 (When the version of Forge a3626a said is right, I mean the 1.8-11.14.3.1502-2.0)

**Comment by RainWarrior** [comment]
Can't reproduce:
```
initial: rot Vector3f[0.0, 0.0, 0.0]; trans Vector3f[0.0, 0.0, 0.0]; scale Vector3f[1.0, 1.0, 1.0]
final: rot Vector3f[0.0, 0.0, 0.0]; trans Vector3f[0.0, 0.0, 0.0]; scale Vector3f[1.0, 1.0, 1.0]
```
Please provide your OS, Java and Forge versions, and if you're not using the latest forge, try that.

**Comment by ThexXTURBOXx** [comment]
Using Windows 8.1, Java 1.8_u74 (newest) and latest Forge (1.8 - 11.14.4.1577).
Still doesn't work. I don't know, if this is a bug of [TGG's mod](https://github.com/TheGreyGhost/ItemTransformHelper) or of Forge. Even though the Version of Forge, which was told by a3626a isn't correct. So the commit i said isn't, too.

**Comment by RainWarrior** [comment]
1577 is 1.5 months old. Can you test on 1.8.9?

**Comment by TheGreyGhost** [comment]
Hi
I haven't installed 1.8.9 at the moment, still trying to fix for a 1.8 mod.

I've found a few bugs so far but looking at the github I think you've fixed most of them already.
This one still seems to be there:
    public ItemTransformVec3f toItemTransform()
    {
        return new ItemTransformVec3f(getTranslation(), toYXZ(getLeftRot()), getScale());
    }
I think should be
        return new ItemTransformVec3f(toYXZ(getLeftRot()), getTranslation(), getScale());
because of
    public ItemTransformVec3f(Vector3f rotation, Vector3f translation, Vector3f scale)

Also I think your SVD splitting the mat3 into left and right (due to the corner to centre translation) might also be part of the problem since your conversion throws the right away.

I have been trying to code up a work around based on direct conversion of matrix3d (from toAffine.getLeft() and removing scale) to euler angles, not finished yet:
    /*
    The rotation matrix is the product of the three euler angle rotation matrices

    R = Ry.Rx.Rz

    This matrix will have the values:

    m00 = cy.cz + sx.sy.sz
    m01 = -cy.sz + sx.sy.cz
    m02 = cx.sy
    m10 = cx.sz
    m11 = cx.cz
    m12 = -sx
    m20 = -sy.cz + sx.cy.sz
    m21 = sy.sz + sx.cy.cz
    m22 = cx.cy

    where cx = cos(x), sx = sin(x), cy = cos(y), etc

    This can be converted back to the euler angles x, y, z as follows:
    1) x1 = arcsin(-m12) or x2 = pi() - arcsin(-m12)
       We can choose either one of these answers to get a correct answer- there are two sets of euler angles that
       will give identical orientation in space.
       One will have cx = positive, the other will have cx = negative, i.e. cx2 = -cx1

    2) a) if cx == 0 (sx==1) then we have 'gimbal lock' and there is infinite solutions for y and z.
            https://sundaram.wordpress.com/2013/03/08/mathematical-reason-behind-gimbal-lock-in-euler-angles/
      In this case,
       m00 = cy.cz + sy.sz = cos(y-z)
       m01 = -cy.sz + sy.cz = sin(y-z)
      Solve using m01 / m00 = sin(y-z)/cos(y-z) = tan(y-z) hence y-z = atan2(m01, m00)
      Then choose arbitrary (extremes of z1 = 0 -> y1; and y2 = 0 -> z2)

      b) otherwise :
       calculate sy from m02 and cy from m22 -> y = atan2(sy, cy)
       calculate sz from m10 and cz from m11 -> z = atan2(sz, cz)

function returns both solutions [x1,y1,z1] and [x2,y2,z2];
*/

I will try installing 1.8.9 in the next few days and testing it.

Cheers
  TGG

**Comment by ThexXTURBOXx** [comment]
Well, I just found out, that TGG's mod works in Forge 1404 for 1.8...
The bug appeared between Forge 1404 and 1487 (Tested both).
I try to find out the exact version of Forge.

**Comment by ThexXTURBOXx** [comment]
Ok, in any version of Forge between 1450 and 1475 gets the "RESET"-button (of TGG's mod) broken.
In version 1479 of Forge, the Item Transformation doesn't work anymore.
Either this commit: https://github.com/MinecraftForge/MinecraftForge/commit/1582e401ed439dc3b6e72bf2d2c91ec91a230ec8
or this commit: https://github.com/MinecraftForge/MinecraftForge/commit/510b5523d53fc4173ecbeb3e2e624277ac3a9af4
broke it.

**Comment by ThexXTURBOXx** [comment]
Thanks! Will there be an update for Forge for 1.8, too? Or will you only include this in 1.8.9?

**Comment by RainWarrior** [comment]
There probably won't be any more updates for 1.8.nothing. You should be trivially able to update any mod you're developing to 1.8.9 though, there wasn't many heavy changes.

**Comment by ThexXTURBOXx** [comment]
Ok, thanks anyway ^^
