### ISSUE TITLE
Eclipse fix needs fixing for optional dependencies

### ISSUE THREAD

**Issue by kenzierocks** [MinecraftForge/MinecraftForge#2426]
As shown in https://github.com/SpongePowered/SpongeCommon/issues/459, https://github.com/MinecraftForge/MinecraftForge/commit/f3c2eb8e9cda873678d0e2308e4b7904fe8e3d61#diff-01042e0e40a00cc58f70263a1aaf84e7R29 does not work with optional dependencies, so a custom implementation of `ClassWriter.getCommonSuperClass` may be needed for optional dependencies.

**Comment by LexManos** [comment]
Optional dependancies are a runtime only thing, they are required in dev time. As such these two things are unrelated. But yes eventually a custom implementation of compute aupers is planned but its very low priority.

**Comment by kenzierocks** [comment]
So I must provide all optional dependencies of my _dependencies_ and their dependencies and so on? That seems unreasonable.

**Comment by LexManos** [comment]
At dev time? Yes, and as we use standard dependancy managent systems this isnt unresonable its standard practice.

**Comment by kenzierocks** [comment]
The point of mavens optional dependencies is that I don't need to provide then if I don't want too.

Say I have a dependency `A`. `A` has an optional dependency on `B, C, D`. I never use `B, C, D`, but now I must make then optional dependencies of my project and keep track of when they change upstream. This is a lot to keep track of, especially with multiple layers of transitive dependencies.

**Comment by LexManos** [comment]
There are mechanics to optin to all optional dependancies depending on what built in systems you use. 
Again this isndev time thenoptions are simple:
1) dont enable this flag and see what happens with evlipses bug.
2) enable this flag and provide all deps as needed
3) write and pr the proper implementation of class writer. 

I dont have time to do that myself as im away on busniess. And the fact that this is a highly specialized bug only related or your specific setup in dev its low priority. 
Writing a proper classwriter is always a pain considering we live in a transfo hackery world. So we have to take into account all coremods.

So ya, for now we wont be doing anything about it. Provide all deps that are needed.
