### ISSUE TITLE
Bug in block.onNeighborChange(IBlockAccess, BlockPos, BlockPos);

### ISSUE THREAD

**Issue by Elec332** [MinecraftForge/MinecraftForge#2428]
> /**
     * Called when a tile entity on a side of this block changes is created or is destroyed.
     * @param world The world
     * @param pos Block position in world
     * @param neighbor Block position of neighbor
     */
    public void onNeighborChange(IBlockAccess world, BlockPos pos, BlockPos neighbor){}     

> 

According to the description, this should get called when a tile on a side of the block get changed, added or removed, though IDEA tells me that this only gets called here:
`world.updateComparatorOutputLevel(BlockPos pos, Block blockIn)`
And even when this gets called, it only notifies tiles in the horizontal facing plane, so it skips the tiles below and above. This method gets called in tile.markDirty(), but not when the tile is placed/removed.

EDIT: It does seem to get called when a tile gets added or removed, since that also triggers `world.updateComparatorOutputLevel(BlockPos pos, Block blockIn)`, but that still leaves the issue that it doesn't notify the tiles above or below

**Comment by williewillus** [comment]
The comment is just outdated, and the mcp name is probably a misnomer

**Comment by asiekierka** [comment]
onNeighborChange is used for tile entity state updates in general (*state*, not type) - and the markDirty/comparator are the only two major use cases that would have in vanilla.
