### ISSUE TITLE
Possible NPE in FMLProxyPacket

### ISSUE THREAD

**Issue by Glease** [MinecraftForge/MinecraftForge#2430]
<del>http://pastebin.com/YXmV5uKb</del>
http://pastebin.com/T4s8vJy6

I don't know if it's just another stupid-coder-using-internal-stuff bug.

**Comment by asiekierka** [comment]
Your modlist is truncated.

2016-01-31 11:34 GMT+01:00 Glease <notifications@github.com>:

**Comment by Glease** [comment]
@asiekierka link updated, sorry for that. pastebin or internet just seems unhappy.

new link: http://pastebin.com/T4s8vJy6

**Comment by LexManos** [comment]
Please let me know if this is reproducible on 1.8.9, guessing from your log its a mod screwing up the packet sending order.
