### ISSUE TITLE
Add a built-in Kotlin language adapter

### ISSUE THREAD

**Issue by The-Fireplace** [MinecraftForge/MinecraftForge#2435]
Could you possibly work to make the Kotlin language adapter a built-in feature of Forge? I would gladly convert all of my mods to it if it were added. There is already an [adapter mod](https://github.com/Emberwalker/Forgelin), but I feel that it would be better to provide built-in support if possible.

**Comment by matthewprenger** [comment]
Good luck with this one. The big problem with this is Forge would have to host all of the required Kotlin libraries, which would cost a lot of bandwidth (keep in mind how many people download Forge every day).

**Comment by LexManos** [comment]
No, we will not be adding more languages especially ones that require additional libs.

**Comment by anti344** [comment]
Kotlin perfectly works if you use class as Mod annotation host, if you use object - these lines work(only from Kotlin 1.0.0-RC):
```kotlin
  @JvmStatic
  @InstanceFactory
  fun hack(): MainObject = this
```
But you'll still need to ship kotlin libs by yourself

**Comment by williewillus** [comment]
you can shade the libs and use this bridge https://github.com/Emberwalker/Forgelin
