### ISSUE TITLE
Broken behavior from expecting BlockPos to be constant

### ISSUE THREAD

**Issue by sfPlayer1** [MinecraftForge/MinecraftForge#2438]
There are multiple instances where BlockPos parameters are assumed to be constant, although they technical are mutable as MutableBlockPos and other subclasses are type compatible.

I've found the following two problematic cases so far:

Forge's block snapshot creation in World.setBlockState stores a reference to the original BlockPos object. If said object changes internally afterwards, e.g. when being reused afterwards in tree generator code, the snapshots will lose the position reference and eventually drop the postponed block updates.

Chunk.getTileEntity with Chunk.EnumCreateEntityType.QUEUED, as used by the renderer, adds the position object to a queue which is likely to change again. The renderer uses a MutableBlockPos object to iterate over the blocks and may pass it eventually to getTileEntity through some Block forward.

I haven't seen Vanilla call setBlockState with MutableBlockPos, it seems to be used only for read-type operations, so there is some room for debating whether mutability has to be expected there. However there are neither restrictions from the BlockPos type/hierarchy itself nor runtime validation by the methods accepting it as an input to ensure the position can't change. The 2nd instance likely affects vanilla MC as well, but it's possibly hard to notice and mods tend to use tile entities a lot more.

My investigation so far is rather cursory, the problem needs some in depth look and IMO something needs to be done to prevent people from tripping over it.

**Comment by LexManos** [comment]
Yes, BlockPos does have a Mutable subclass however the general contract is that it's immutable.
If there are specific cases where this is actually causing an issue we can address it. I'll look into snapshots when I can get a chance. However there isn't anything Forge can do to 'prevent people from tripping over it' aside from warn modders. Which is a documentation/community thing not a code one. 

So unless you have a code facing solution thanks for the warning.
