### ISSUE TITLE
[Pre-Pull Feedback Request] -- Punch/Run/Fall Incorrect Patticle Fix

### ISSUE THREAD

**Issue by ShetiPhian** [MinecraftForge/MinecraftForge#2440]
Thin blocks, like carpet, do not have the correct run or fall particles.
Mod blocks that rely on  tile entity data for texture doesn't have the correct punch, run. or fall particles.

The punch particles is a simple fix in EffectRenderer, just a single line is needed.

The run an fall on the other had requires a bit more, but I've got two options.
Option 1 needs:
- 1 line patch in EntityLivingBase
- 1 line patch in Entity
- 1 added in EntityBlockDustFX
- 2 lines added and one line patched (all together) in EntityDiggingFX
- Some code added to ForgeHooksClient

Option 2 needs:
- 1 line added to EntityDiggingFX
- Some code added to ForgeHooksClient (bit more then option 1)

Option 2 edits fewer classes but has the downfall of using the wrong particle if it spawns with a different x or z position then the block it came from.

I'm thinking 2 is the best one to choose due to the fewer edits, and the wrong particle is rare, but wanted feedback before I made the pull request.

**Comment by williewillus** [comment]
Running particles being that of the block below them in some cases is a vanilla thing and as far as I know, is intended.

**Comment by ShetiPhian** [comment]
That causes a issue, because regardless of thickness if a mod block uses tile data for texture the run and fall particles are incorrect.

If I apply the fix for mods it will have the side effect for breaking the the intended effect for carpet.
To exempt carpet from rendering its particles I'd need to use option 1 and increase the patch size on both EntityLivingBase and Entity to include a check for it.

I guess there is now three options with 1b being; option 1 but adding extra code to exempt vanilla blocks.

**Comment by LexManos** [comment]
The other issue is this is simply not possible to do.
These particles can be spawned at any position even ones unrelated to a block at all so that we can't rely on the world being what you think it is.

**Comment by ShetiPhian** [comment]
Ah.. right..  if another mod directly spawns particles for another use, the best guess made by the logic in option 2 fails. (wouldn't crash, but wouldn't produce the expected particles, still bad)

While Option 1 only does its work if the extra data is provided by the previous methods, otherwise uses the default, making it the only reliable way.

**Comment by ShetiPhian** [comment]
Thought of something else for run & fall.
Fall can be scrapped completely due to block.addLandingEffects
Run can be changed to be similar by adding block.addRunningEffects
Might just as well do the same for the block hit to keep everything consistant.

**Comment by ShetiPhian** [comment]
Done: https://github.com/MinecraftForge/MinecraftForge/pull/2446
That, along with the existing, will allow the particles to be fixed.
Not automatic like my first pull but far less edits and it fits in with the existing code.

With the old method scrapped there is no point in leaving this open to discus it.
