### ISSUE TITLE
Containers - ItemStack.areItemStacksEqual, and Caps

### ISSUE THREAD

**Issue by AlgorithmX2** [MinecraftForge/MinecraftForge#2444]
When items with Caps change containers can't detectAndSendChanges() since presently they only check the NBT.

----

I'd make a PR for this.. but I honestly don't know what the preferred solution would be.. I can only imagine something involving equals() and that would be a more involved patch.. so I'm just posting an issue instead for now.

**Comment by LexManos** [comment]
Interesting, something to look into but may not be feasible given my time right now.
Caps can work around this like they used to in the old days by directly modifying the itemstack.. but that's not the best solution... Humm

**Comment by williewillus** [comment]
closing in favor of duplicate issue #2726 which mentions some code positions where this happens

**Comment by Actuarius** [comment]
@williewillus closed this issue
