### ISSUE TITLE
Suggestion for Optional class 

### ISSUE THREAD

**Issue by Speiger** [MinecraftForge/MinecraftForge#2447]
the Optional Class is really good to hide classes/methodes/functions and all that stuff but what i am missing is that you can not use a Inverted Mode.
Lets say i have a function that requires 2 mods. Well i can use the optional class to load it if these mods are there. But if i want to make this function deleted/not there if a third mod is installed that is sadly not possible.
What i try to discribe is: I woud like to support a mod but when another which i do not want to support is installed i can not do that. I have to support it with it. Or if i want to make the game harder by not supporting something it is sadly not possible. That would be a nice feature (also for 1.7.10)
(simply a option inside this interface where i can say: If one of these is loaded then say that the required mod is not there (even if it is or not))

**Comment by LexManos** [comment]
You should be using standard java practices like if statements to do this NOT hacky ASM stuff that is designed SOLEY to prevent crashes from 'ClassNotFoundExceptions'
You're going outside the scope of @Optional and you shouldn't.

**Comment by Speiger** [comment]
@LexManos well i can not argue with you in that case simply because the only reason i request it because another one do not want to support a second modid since we share a modid. So i asked for a inverted to solve this problem....

**Comment by LexManos** [comment]
You 'share' a modid? What? No modids need to be unique....
It sounds like you're doing things horribly wrong... The ONLY reason @Optional exists is to help CNFE's so an inverted thing would not make sense. This should NOT be used for gameplay mechanics you should use normal programming practices.

**Comment by Speiger** [comment]
@LexManos we simply share the modid because it is the same mod but 2 differend versions...
IC2 Exp and IC2 Classic. (The author of Exp) sees no reason to support a second modid simply to see the differences between the mods... Sadly Optional has only a whitelist function and not a blacklist function... Which would be really helpfull with this...
And the shared modID is simply there to support addons/API usesers better and for more detailed class use there should be a second modid which exp does not have...

**Comment by LexManos** [comment]
Then the author of Exp is wrong, he should be using a seperate ID.
If you must trick others into loading with your setup you can use the API system Forge has.

**Comment by Speiger** [comment]
How can i trick them when they (addons/other mods) search for the modid which we share? IC2...
They wont load their stuff or causes crashes when they do not find it...

**Comment by ShetiPhian** [comment]
This is quite the mess you've got,
I've got a few thoughts that may help you out but this isn't the place to discuss mod coding.
You should post on the forums.

**Comment by Speiger** [comment]
@ShetiPhian i think i am not able to join the forums because i got kicked long a go when i asked for help and was annoying xD

**Comment by ShetiPhian** [comment]
It would be better to have more then just my input, but PM me on the Minecraft forums.
