### ISSUE TITLE
EntityThrowable Rotations

### ISSUE THREAD

**Issue by ThexXTURBOXx** [MinecraftForge/MinecraftForge#2449]
I don't know if I am just silly, but I can't get the setLocationAndAngles-method working...
http://www.minecraftforge.net/forum/index.php/topic,36629.0.html (That's solved, but I had to do it via OpenGL-Rotations).
What did I do wrong?
Ingame I saw the entity flashing up a bit, when thrown. Maybe in the onUpdate()-method the values get changed again, so the old ones don't exist anymore.
Update 12.02.16: I noticed, that even the rotate-methods in the ModelBase-class don't work. I really don't know if I am doing it wrong :/

**Comment by ThexXTURBOXx** [comment]
Now I have wasted 5 hours to set the rotations, but I can not make it...I tested every method I found, but all don't work.

**Comment by williewillus** [comment]
Ask on the forums/irc for modding help

**Comment by ThexXTURBOXx** [comment]
I did, but i think its an issue of forge...

**Comment by williewillus** [comment]
Well, give us more details that indicate why you think that

**Comment by ThexXTURBOXx** [comment]
I have solved it via OpenGL-Rendering, but the setPositionandRotation-methods (and all the other ones which should to the same) don't rotate the entity. As I said in the beginning, I think, that something resets the yaw of the entity every tick.

**Comment by williewillus** [comment]
Because the rotation fields are reset every tick in onUpdate. you need to override that to prevent it from happening

**Comment by ThexXTURBOXx** [comment]
Ok, then I think I can close this... Thanks!
