### ISSUE TITLE
RegionRenderCache.isSideSolid() =!= RegionRenderCache.getBlockState().getBlock().isSideSolid()

### ISSUE THREAD

**Issue by HenryLoenwind** [MinecraftForge/MinecraftForge#2451]
In my getActualState() I only get _default from worldIn.isSideSolid() when worldIn is a RegionRenderCache while worldIn.getBlockState().getBlock().isSideSolid() is working fine. (BlockPos is in range, as I can see from the correct block returned.)

I have noticed there's a variable mixup at:

https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/world/ChunkCache.java.patch#L57
https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/world/ChunkCache.java.patch#L42
https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/world/ChunkCache.java.patch#L16

where ```i < 0 || i >= field_72817_c.length || j < 0 || ```**i**``` >= field_72817_c[i].length```should actually be ```i < 0 || i >= field_72817_c.length || j < 0 || ```**j**``` >= field_72817_c[i].length``` that may be the reason or totally unrelated.

Forge 1.8.9-11.15.1.1732

**Comment by RainWarrior** [comment]
Please try build 1737 or later, and see if the issue is fixed there.

**Comment by HenryLoenwind** [comment]
Thx for the fast action. Sadly it either isn't fixed or I'm not yet awake enough:

```
    if (worldIn.getBlockState(blockPosAboveTarget).getBlock() == BlockMvesWire.block && worldIn.isAirBlock(blockPosAboveUs)
        && worldIn.getBlockState(blockPosTarget).getBlock().isSideSolid(worldIn, blockPosTarget, direction.getOpposite())) {
      //        && worldIn.isSideSolid(blockPosTarget, direction.getOpposite(), false)) {
      if (!worldIn.isSideSolid(blockPosTarget, direction.getOpposite(), false)) {
        System.out.println("NOT FIXED"); // <- fires
      }
```

Seems the mixup was unrelated after-all.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]

**Comment by LexManos** [comment]
Verify this is still happening on the latest Forge.
I'm looking at the code and it all looks fine...
