### ISSUE TITLE
Block/Item Maps changing on Single Player World to Server 1.8.9(11.15.1.1724)

### ISSUE THREAD

**Issue by pauljoda** [MinecraftForge/MinecraftForge#2452]
On forge version 11.15.1.1724 there seems to be an issue with old worlds and servers. I had an old single player world where most of the mods and items had changed, I went to load it and selected no to not load the world and go back to the main menu. Upon joining a server with mods matching the current client, most items and blocks were not the correct ones. Furnaces were glass blocks, copper dust was a thaumcraft harness, things were very shuffled. 

It seem like if you choose not to load an old world with outdated worlds in single player, and then join a server that has been updated (maybe even a different single player world) the ids get very messed up.

Just wanted to give you a heads up in case it is something you want to look into. I know its expected to have ids change with mods coming in and out but when it can happen to a client joining an updated world after cancelling loading an old world, that may cause issues

**Comment by Flashback083** [comment]
Yup, just want confirm this issue, cause i dont see other person which have this bug, but when i load world (1.8) in solo with forge 1.8.9, the mod hasnt the same id :s, i try different thing, the bug is not present in 1.8.8 but pixelmon dont work in 1.8.8.
Thanks  for your works <3

**Comment by diesieben07** [comment]
Is this still an issue? Or fixed by #2477?

**Comment by Actuarius** [comment]
@diesieben07 added labels [Needs Update]
