### ISSUE TITLE
Statistic objects for modded blocks/items not registered

### ISSUE THREAD

**Issue by TherminatorX** [MinecraftForge/MinecraftForge#2454]
Recently, I tried to make a command block contraption to detect when a player crafted a certain mod item. When trying to add an objective for the scoreboard, I found something interesting: Forge/the mod doesn't do statistics, at all. After crafting another mod's chisel and opening the items page of the "Statistics" menu, it didn't show anything, just that I've used an iron pick 73 times, and crafted 4 sticks.

Has no one ever brought this up? Is it too complicated to add? Or do individual mod authors have to add in this feature and they've never bothered to do so? I talked with the team behind the mod and they had never thought about it (mainly because who uses scoreboards in the modding community).

I would love for this vanilla feature to show up in the world of modding. I know vanilla mapmakers have LOVED using these for little quirks, and can see a lot of potential for them here.

**Comment by williewillus** [comment]
This is up to the individual mid to add support for (usually its just one method call at the place you want to increment the stat)

**Comment by heldplayer** [comment]
From what this issue describes, no stats are being gathered from non-mod blocks and/or items? (this includes placing and breaking of blocks, and crafting, using, and breaking of items)

**Comment by Choonster** [comment]
I add block mine, item use, item break and item craft stats for all modded items in my 1.7.10 test mod [here](https://github.com/Choonster/TestMod2/blob/1d0fb1cdcdd392719349344f557273d3145c6259/src/main/java/com/choonster/testmod2/tweak/moddedstatsfix/ModdedStatsFix.java).

Block and item ID management has changed slightly in 1.8.9, so the ID gathering and remapping code may need changes.

**Comment by TherminatorX** [comment]
@heldplayer No, the problem is that MOD item/block do not have statistics associated with them. Vanilla statistics work as intended.

**Comment by williewillus** [comment]
I think that is something that forge should be doing
perhaps the title could more precisely be "Statistic objects for modded blocks and items not registered"

**Comment by TherminatorX** [comment]
Updated title as requested, a bit more technical than I'm used to, however.
I know code lingo to about the same level as a post-graduation high school student knows Spanish after 2 years of the required course. :)

I agree though that it would be a lot easier on modders if Forge did this by default. :+1:

**Comment by Choonster** [comment]
@TherminatorX I don't mind if someone adapts my code into a PR, as long as that PR links to the original code and mentions my name.

**Comment by LexManos** [comment]
If there is something lacking regarding this automatic registration {right now MC uses IDs which is dumb} feel free to submit a PR.

**Comment by TherminatorX** [comment]
If I had any idea how to make code do stuff I want in MC, I would. However, my coding/1337 knowledge is limited to a few basic concepts and how to navigate a directory in command prompt. I am completely useless in writing mod code, so help from others is required. ;)

**Comment by williewillus** [comment]
This is because StatList.init() is called very very early in the startup process (in the area of preinit, when vanilla items get registered)

Could be solved by clearing all the lists and calling it again after init, though its not a very clean solution

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]

**Comment by LexManos** [comment]
Added the reinitalization, I don't like it its really hackey but it SHOULD work. Tested most of the vanilla stats and they work just fine. Let me know.
