### ISSUE TITLE
Make a IFluidHandler capability

### ISSUE THREAD

**Issue by rwtema** [MinecraftForge/MinecraftForge#2455]
This shouldn't be too difficult in principle but there is the question of what level of backwards comparability we wish to have. 

We will need to change IFluidHandler to remove the sidedness, so do we wish to make a hard break with the previous version(s) and break everyones code, or do we deprecate the old interface and make a completely new one, and once everyone switches over remove the old interface.

**Comment by LexManos** [comment]
The method would be to deprecate and remove in 1.9.
Simplest solution would be to rework the interfaces and do it in a 'cap' subpackage. 
Then in 1.9 just bump it up one package and delete the old ones.

**Comment by mezz** [comment]
I've been thinking about this for a while, I might take it on if I can manage my time well.

**Comment by mezz** [comment]
Closed by https://github.com/MinecraftForge/MinecraftForge/pull/2942

**Comment by Actuarius** [comment]
@mezz closed this issue
