### ISSUE TITLE
EnumFacing.UNKNOWN

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#2456]
Can we get EnumFacing.UNKNOWN? It would be useful for my PowerRouters mod which can get things (items, fluids, power) from remote things. (e.g. RF API for 1.8.9 doesn't have an extractEnergyUnknown which means I can't use it >.>)

ping @KingLemming

**Comment by asiekierka** [comment]
If you fix the entirety of vanilla to make sure it handles
EnumFacing.UNKNOWN properly everywhere and make it a small enough set of
patches to maintain by the Forge developers, yes.

Otherwise, no. Never.

2016-02-10 17:15 GMT+01:00 Soni L. <notifications@github.com>:

**Comment by SoniEx2** [comment]
Well I'll use null then. That solves everything right?

**Comment by asiekierka** [comment]
No, you make your own wrapped direction enum if you need to have seven
defined directions.



2016-02-10 17:27 GMT+01:00 Soni L. <notifications@github.com>:

**Comment by williewillus** [comment]
This has been discussed many times over - search the GitHub before blindly making reports.
Patching this in will cause undefined behaviour in vanilla where an extra enum value isn't expected, unless you can patch every single one

**Comment by SoniEx2** [comment]
I did search but didn't find anything.

**Comment by williewillus** [comment]
#2014 and associated issues/PR's. Also search the RF API issues.

**Comment by LexManos** [comment]
Use Null
