### ISSUE TITLE
Thorns Enchantment bypasses ISpecialArmor#damageArmor()

### ISSUE THREAD

**Issue by TehNut** [MinecraftForge/MinecraftForge#2463]
The Thorns enchantment is meant to damage the attacker's armor, however because `ItemStack#damageItem()` does not respect ISpecialArmor's method of damaging its armor, either ItemStack's method should check for ISpecialArmor or Thorns should check for the armor itself.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]
