### ISSUE TITLE
Crash on entering server, SP world not enterable 1.7.10

### ISSUE THREAD

**Issue by Vanir2314** [MinecraftForge/MinecraftForge#2471]
Whenever I join a server I crash, creating or entering a singleplayer world just puts me pack to the main menu.
Crash log for multiplayer: http://pastebin.com/E8KUBG4L

Modpack: For the Love of Adventure 1.5.1b
Forge: 10.13.4.1614

Reporting here, cause told so and no mods in stack trace

Anything more you need/ I can do to play the pack?

**Comment by LexManos** [comment]
These are not issues with Forge, take them to the forum to be debugged.
