### ISSUE TITLE
Potion#renderInventoryEffect/shouldRenderInvText minor fix required

### ISSUE THREAD

**Issue by maxanier** [MinecraftForge/MinecraftForge#2473]
Hello,

I would like to hide the potion duration of one Potion from the player.  
The method in getDurationString() is unfortunatly static so I can't modify that, but there already are the methods Potion#renderInventoryEffect and Potion#shouldRenderInvText.
With those I can easily render my own String and cancel the the default String rendering, but there is a minor issue with that:

If multiple potions are active mine is "overrendered" since there is no space reservered for it when  Potion#shouldRenderInvText returns false, because "j += l;" is not done.
Adding this to the [if clause](https://github.com/MinecraftForge/MinecraftForge/blob/9760b3b52f71044a21911ecbc314d4d54b4944ca/patches/minecraft/net/minecraft/client/renderer/InventoryEffectRenderer.java.patch#L30-Lundefined) "if (!potion.shouldRenderInvText(potioneffect)) continue;" should solve this. Even if some modder wants no text rendered, the old implementation won't really help, since the icon is "overrendered" as well, so I don't think this fix would "hurt" any mod.

If someone can provide a link for a introduction how to work with java.path files, I could try myself on a PR, but it probably are only  a few lines anyway.

Thanks :)

Maxanier

**Example Code** (of the custom Potion)
https://github.com/TeamLapen/Vampirism/blob/5edf4d8811db1d687422aa09e10c9337a1b2d16f/src/main/java/de/teamlapen/vampirism/potion/PotionSanguinare.java#L35-L51

**Render Result**
https://picload.org/image/wladrwr/clipboard0

**Comment by LexManos** [comment]
No adding extra hook like this shouldn't be necessary, and allowing/encouraging the direct use of GL rendering is bad.
If this was ever to be considered it would have to be in the form of asking the specific potion for it's text and then rendering a smaller offset/box if there was no text.
This could also be expanded to make the text wrapper it all depends on how things go in that section of code.

**Comment by maxanier** [comment]
I'm just wondering wondering what the current implementation can be used for.
There already is a "renderInventoryEffect" method in the Potion which was added by @diesieben07 https://github.com/MinecraftForge/MinecraftForge/commit/9662b5a657fa51c38f9ebcd4c06c866730ea9c1d, which apparently allows/encourages rendering in a custom potion class. I understand that this is not good practice, but since it is already there and there is no custom text option, I would like to use that.

The problem actually referring to, is that the method "shouldRenderInvText" (added in the same commit by @diesieben07) is more or less useless, at least as far as I can tell. If this method returns false, the renderer does not reserve any space for the potion, so it sometimes overrendered. I can't find any reason why this should be intented (if you want to hide the potion you can always use "shouldRender"), or did I miss something?
