### ISSUE TITLE
level.dat from 1.8 is ingored when loading in 1.8.9 [Fix]

### ISSUE THREAD

**Issue by Jay113355** [MinecraftForge/MinecraftForge#2477]
So in this commit: https://github.com/MinecraftForge/MinecraftForge/commit/6e90348dc546164b21735aefd83ed0bac0d8283c That was added into forge version 1.8.9-11.15.0.1666
Forge/FML started saving dummy block and item entry's into the level.dat.
Line 309 Of the readData method of FMLContainer.java: 
`if (!regs.getCompoundTag(key).hasKey("dummied")) return;`

Checks to see if the dummied tag is present (it is not in 1.8 worlds) if it is not, it then **returns** thus exiting the reading of the block/item id mappings. (aka level.dat)

This was probably meant to be a `continue;`.

I've build forge my self and tested the fix. The level.dat is successfully loaded when you change line 309 to `if (!regs.getCompoundTag(key).hasKey("dummied")) continue;`

**Comment by Jay113355** [comment]
Related: #2452

**Comment by LexManos** [comment]
This is indeed the case, thanks for catching this. There are other parts where there are issues in the registry code. If you can come up with any other cases where things mess up let us know.
