### ISSUE TITLE
Pass objectMouseOver.hitVec into PlayerInteractEvent

### ISSUE THREAD

**Issue by me4502** [MinecraftForge/MinecraftForge#2482]
This would allow for mods to determine exactly where a block was clicked, rather than just what block was clicked.

**Comment by diesieben07** [comment]
This can only work on the client, since the client does not tell this information to the server. And then you might as well just access `Minecraft.objectMouseOver` directly.

**Comment by LexManos** [comment]
Actually, the client *should* tell the server. We have that information for placement {such as how slabs determine their placement}
It may be feasible to find that information and pass it along.
However, me should know better then to submit issues opposed to PRs. -.-

**Comment by diesieben07** [comment]
Right, for right clicking we do know. Just not for left clicks. I can make a PR out of that.

**Comment by me4502** [comment]
I submitted an issue to cause a discussion. A PR was doing to follow after the discussion.

**Comment by me4502** [comment]
The client does give the server this information, it's available in this packet, http://wiki.vg/Protocol#Player_Block_Placement
