### ISSUE TITLE
Blacklist events

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#2484]
If I extend a Forge event, some mods may not play nice with my logic (I can see this might happen with my own mod, NoteBetter). Currently there's no way to skip their event handlers; all we can do is tell the creator to change their mod or tell users to not use conflicting mods.

If you have a big mod this isn't a problem, other modders will happily comply, but if you have a small mod you'll most likely have to tell your users to not use conflicting mods together, and depending on the user's preferences and which mod is bigger, you'll probably lose users.

The blacklist would be provided when posting the event.

**Comment by diesieben07** [comment]
What are you on about? If your mod breaks the event's contract so that mods don't play nice with it it's your fault to fix that in your mod and not to change everyone else's mod to comply with your logic...

**Comment by Spartan322** [comment]
If you properly handle your event, there would be no need for a blacklist.

**Comment by liach** [comment]
Um... I suggest when posting event add an option of whether allow the param has the superclass of the event, if you choose not then the issue could be fixed.

**Comment by gigaherz** [comment]
If it shouldn't allow being handled by superclasses, then it may as well NOT inherit from the other one?

**Comment by liach** [comment]
@gigaherz It means that if a `WorldEvent` is posted, then the handler that feeds on an `Event` would receive it if the post allows inheritance, or not if the post does not allow.

**Comment by SoniEx2** [comment]
@diesieben07 Let's say we change NoteBlockEvent.Play to use accessors. Then some mod author decides to do this:

```java
@EventHandlerAnnotationThingy
public void onNotePlay(NoteBlockEvent.Play event) {
    Instrument i = event.getInstrument();
    if (shouldDoSomeChange(event)) {
        i = doSomeChange(event);
    }
    if (shouldDoAnotherChange(event) {
        i = doAnotherChange(event);
    }
    event.setInstrument(i);
}
```

(Yes, there are many things wrong with this code, this is intentional because those things do happen in the real world.)

So, basically, setInstrument is always called. If your setInstrument overrides custom instruments with vanilla instruments, this'll block all your custom instruments.

Example event, again assuming accessors:

```java
public class NoteBetterPlayEvent extends NoteBlockEvent.Play {
  private ResourceLocation customInstrument;
  public NoteBetterPlayEvent(ResourceLocation customInstrument, /* stuff */) {
    super(/* stuff */);
    this.customInstrument = customInstrument;
  }
  @Override
  public void setInstrument(Insturment i) {
    customInstrument = getResLocForVanillaInstrument(i);
  }
}
```

This should only be used for bad event handlers.

**Comment by Spartan322** [comment]
Then that's the developers fault, and he shouldn't being doing something dumb. Forge doesn't prevent stupid, and if a developer is being dumb, he should either learn or stop.

**Comment by diesieben07** [comment]
Just make your `setInstrument` method check if there is a change in instrument.

**Comment by SoniEx2** [comment]
@diesieben07 But that's not the semantics I want.

**Comment by williewillus** [comment]
Chiming in on this..

This is a general OOP thing...if you don't fulfill the contract of the superclass then do NOT extend it..
just make a separate event instead...

**Comment by SoniEx2** [comment]
@williewillus The basic idea is that setInstrument should always set the instrument to the target. If you extend upon it (allow custom instruments) then you aren't breaking any contracts. I can't allow setInstrument only if there is a change in instrument.

**Comment by diesieben07** [comment]
If you aren't breaking any contracts then your changes cannot break other mods.
If you are doing things that break other mods (=users of an API) then you are breaking the contract. That's literally the definition of "breaking the contract"...

**Comment by liach** [comment]
For your example it calls the method of the subclass, that is the modified `setInstrument(Instrument)`

**Comment by LexManos** [comment]
> This is a general OOP thing...if you don't fulfill the contract of the superclass then do NOT extend it..
just make a separate event instead...

**Comment by SoniEx2** [comment]
Looks like I'll have to ASM forge... again...

**Comment by LexManos** [comment]
Fuck off soni, explain your shit better or follow standard programming practices.
We can't help you when you break compatibility and then yell at us that it's OUR fault YOU are breaking compatibility.
