### ISSUE TITLE
ArrowLooseEvent only triggers if player has a vanilla arrow in their inventory in ItemBow

### ISSUE THREAD

**Issue by Azanor** [MinecraftForge/MinecraftForge#2486]
Pretty much as the title says. The ArrowLooseEvent event is only triggered in onPlayerStoppedUsing after the vanilla bow checks if the player has a vanilla arrow in their inventory. This means that any custom arrows (like the primal arrows from TC) can only be fired if the player also carries vanilla arrows around.

See https://github.com/Azanor/thaumcraft-5/issues/380

**Comment by GotoLink** [comment]
See ArrowNockEvent.

**Comment by LexManos** [comment]
Yes, this is the same issue with the infinity enchant. We've decided not to check in to not circumvent vanilla mechanics. Unless there is a argument made for how it could be done without screwing that up.
Also as Goto said Nock is there for you to control the rest of the flow. Because using a non-vanilla arrow in a bow would cause amungst other things, uninformative renders.

**Comment by Azanor** [comment]
I do use ArrowNockEvent for my custom arrows and that works fine. The point I am making is that I can only actually fire my custom arrows in response to the ArrowLooseEvent and that does not get triggered unless you have a vanilla arrow in your inventory. 'Controlling the flow' is fine and all, but you can't exactly do that with a vanilla bow beyond waiting for the event.

The change will not alter vanilla functionality at all - the event simple needs to be fired before the if that checks for the presence of the arrow.

**Comment by LexManos** [comment]
Thats the point, for the vanilla bow to be used you need a vanilla arrow.
Its dumb but infinity works that way and rendering on the vanilla bow only ever shows the vanilla arrow.
To have a custom model you need a custom item.

**Comment by GotoLink** [comment]
I stand corrected, i didn't realize the patch changed from https://github.com/MinecraftForge/MinecraftForge/blob/b1aa31215f0817244c8823d9232d404482039411/patches.mcp/minecraft/net/minecraft/item/ItemBow.java.patch

If the hard-coded arrow rendering is a concern, a patch could be added in RenderItem#renderItemModelForEntity where the bow takes its pulling resources.

**Comment by LexManos** [comment]
Actually, it hasn't. https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/item/ItemBow.java.patch
It's still fired before the arrow check, so what the hell are you talking about?

**Comment by LexManos** [comment]
Humm ya, seems like @RainWarrior screwed up the patch.... Interesting, the issue still remains with the rendering of custom arrows...

**Comment by diesieben07** [comment]
1.9.4 fires the event even if there is no ammo.

**Comment by Actuarius** [comment]
@diesieben07 closed this issue
