### ISSUE TITLE
removing and readding a mod make everything in the mod invisible on Dedicated Server

### ISSUE THREAD

**Issue by bushbaby1234** [MinecraftForge/MinecraftForge#2487]
on a dedicated server if you remove a mod and readd it it makes all the blocks in the mod invisible even blocks placed after the readdition. they are there but they cant be seen or interacted with. this only seems to be a problem on a dedicated server. if you do the same procedure on a client instance it works as intended.

tested with forge 1751, thaumcraft 5.1.6, and hydraulicraft 3.1.65.

Update: i just retested on 1752 and the issue is still there. if you load the world in single player none of the blocks are invisible but if you take it back to the server the bug returns
i believe this is a issue with the newish feature of forge remembering previously registered blocks even after a mod is removed

reposting this here since it makes more sense than the forum... derp

**Comment by bushbaby1234** [comment]
Update: tested again with newest versions while doing pack dev
https://www.dropbox.com/sh/l7gyytsalfhwejv/AADXODoPF4Aeamh1nBq3EQxHa?dl=0

there is the modlist and all of the logs for the server and client used to replicate this
Process:
generate a world
place down/find something from a mod
stop server
disable/remove that mod
start server
confirm mod removal
stop server
enable/readd the mod
start server
join server and you can see all in world blocks from that mod are invisible but there server side because you can get stuck in it and use tnt to obtain some of the things

**Comment by knoxhack** [comment]
It would be cool to have a fix for this, I removed a mod after it was crashing my server, but the mod got updated and bugs fixex, when I added back the mod i get invisible blocks too

**Comment by knoxhack** [comment]
Also: https://youtu.be/DtRNg5uSKQ0

**Comment by LexManos** [comment]
Potential fix, these are the steps i've done to test and it works fine.
Install ModA
New World
Place BlockA Twice
Shutdown
Remove ModA
Start
Confirm
BlockA's Invisible {Air}
Shutdown
Install ModB
Start
Place BlockB By itself
Place BlockB over old one BlockA {It's still air}
Shutdown
Install ModA
Start

Blocks are as expected:
BlockA That wasn't over written reappeared
BlockA that was overwritten stayed BlockB
BlockB appeared fine.

**Comment by bushbaby1234** [comment]
i forgot to thank you. Thanks a million Lex!
