### ISSUE TITLE
Problem setting up Decompiled Workspace (forge-1.8.9-11.15.1.1758-mdk)

### ISSUE THREAD

**Issue by yovliporat** [MinecraftForge/MinecraftForge#2494]
Whenever I try to decompile the workspace it gets stuck on DecompileMC 56%

As I have gathered from Asiekiera (I probably spelled the name wrong, sorry >.<) this is caused by a change in forge 1.8.9 which makes ForgeGradle take up more RAM. I've tried many ways to dedicate more RAM to gradle using advices from /r/forgemodding but nothing worked.

If you want to contact me about details or a solution you can PM me on youtube: https://www.youtube.com/channel/UCVnZKu6Z7TkhmCeU-SwdfPQ or obviously reply here.

Thanks in advance!

**Comment by Jerzerak** [comment]
Refer to [this](https://github.com/MinecraftForge/ForgeGradle/issues/324) issue from the ForgeGradle repository

**Comment by yovliporat** [comment]
Thank you so much! It worked!

**Comment by Termin8or** [comment]
Even using that my decompileMC gets stuck at 44% and maxes out my cpu, so if it doesn't run out of memory it fails because it uses too much cpu power. Any idea on a fix?

**Comment by yovliporat** [comment]
Just try more RAM, I dunno. 2 gigs worked for me.

2016-03-02 19:35 GMT+02:00 Luke Warlow <notifications@github.com>:

> Even using that my decompileMC gets stuck at 44% and maxes out my cpu, so
> if it doesn't run out of memory it fails because it uses too much cpu
> power. Any idea on a fix?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MinecraftForge/MinecraftForge/issues/2494#issuecomment-191342265>
> .
>



-- 
*Y~*

**Comment by louwers** [comment]
This should probably be in the docs?

**Comment by williewillus** [comment]
it is

**Comment by louwers** [comment]
Which docs?

I was alluding to the wiki:
http://www.minecraftforge.net/wiki/Installation/Source

It's not in the README.txt either.

**Comment by williewillus** [comment]
wiki is old and frankly should be taken down. See http://mcforge.readthedocs.io/en/latest/gettingstarted/

**Comment by louwers** [comment]
Thanks for the link.

I hope it won't be, because it contains information that is not on the readthedocs page (such as http://www.minecraftforge.net/wiki/Event_Reference).

**Comment by shadowfacts** [comment]
You shouldn't be using the event reference on the wiki, it is old and out of date. You can use your IDE to view all the subclasses of `net.minecraftforge.fml.common.eventhandler.Event` if you want to see all the events.

**Comment by louwers** [comment]
All those events are not subclasses of Event:

![screenshot_2016-05-11_03-07-04](https://cloud.githubusercontent.com/assets/649392/15167042/762e1e64-1725-11e6-81c3-ca152b20ac16.png)

**Comment by shadowfacts** [comment]
You're not using your IDE correctly. [Try this](http://lmgtfy.com/?q=eclipse+find+all+subclasses)
