### ISSUE TITLE
Universal fluids

### ISSUE THREAD

**Issue by border999** [MinecraftForge/MinecraftForge#2501]
https://github.com/BluSunrize/ImmersiveEngineering/issues/942#issuecomment-189173371

**Comment by williewillus** [comment]
What precisely is this asking for? A "fluid dictionary"? The system as it is already selects one implementation to use. Forge to add fluids? Forge will never add extra content (the buckets were already stretching it a lot)

**Comment by LexManos** [comment]
Your issue/request is not well thought out, nore descriptive and I've already given in more effort in just reading it then you did in submitting it so closing until you actually try.

**Comment by PrincessRTFM** [comment]
I think the request is centered around the idea of registering burn time for fluids, directly in the dictionary. Other properties can be registered, but there is apparently no global fuel value mechanic of any kind, as there is with items that can be burned in furnaces.

**Comment by williewillus** [comment]
What is a "burn time" though? There is no such concept in vanilla, it's a mod-made-up concept. Unless lots of mods need "fluid burn time" it should stay managed by mods

**Comment by border999** [comment]
several examples are available for mods that use burn times. The simplest example I can conjure is any mod that uses items or fluids to products something via 'burning' it. Endoflame, geothermal generator, etc. Vanilla furnaces included, coal has a specific amount of time it burns in one. That is 'burn time'.

**Comment by border999** [comment]
This problem is rather annoying for people that can't use fuel sources from one mod in another one. Such as immersive engineering's bio-diesel being nonburnable in a railcraft liquid-fueled boiler,

**Comment by williewillus** [comment]
I'm saying I can't think of any mod besides a certain niche that needs burn times for FLUIDS

**Comment by Pokechu22** [comment]
Vanilla Minecraft makes use of burn time for lava buckets.

**Comment by williewillus** [comment]
Eh, that's literally the lava bucket item that's set to have a burn time, not the fluid itself
But maybe theres a case for this
