### ISSUE TITLE
RenderHandEvent is fired from a location with too wide scope

### ISSUE THREAD

**Issue by Emoniph** [MinecraftForge/MinecraftForge#2503]
The cancelable RenderHandEvent is currently fired prior to EntityRenderer.renderHand() and EntityRenderer.renderWorldDirections(), canceling both if it is canceled. The issue is that the actual rendering of the hand is done by the call:

 this.itemRenderer.renderItemInFirstPerson(partialTicks);

deep within the EntityRenderer.renderHand() method. Most other parts of renderHand() are not to do with the hand render, and should not be involved in the canceling of the event.

It seems moving the RenderHandEvent to just prior to the renderItemInFirstPerson() method call would be more inline with the intention of the event, and then canceling only that following call if the event is canceled.

A second request: it may also be useful to fire a RenderHandEvent.Post type event after the call to renderItemInFirstPerson() (if it is not canceled), so mods may render overlays after the hand has been rendered.

**Comment by williewillus** [comment]
+1 on this
also a vote that if we move it, keep the current one as a "RenderHandEvent.Pre"

**Comment by RainWarrior** [comment]
Event moved some time during the 1.9 update.
