### ISSUE TITLE
FluidContainerRegistry Ignores the Universal Bucket

### ISSUE THREAD

**Issue by shadowfacts** [MinecraftForge/MinecraftForge#2506]
When trying to use `FluidContainerRegistry.fillFluidContainer` and `FluidContainerRegistry.drainFluidContainer` to fill an empty bucket with a fluid that uses the universal bucket, it won't fill/drain the bucket because `FluidContainerRegistry` doesn't take the universal bucket into account. 

`FluidContainerRegistry` uses `filledContainerMap` and `containerFluidMap` which only contain thing registered with the registry. `FluidRegistry.addBucketForFluid` should automatically register the correct entries with the `FluidContainerRegistry`.

As a temporary work around, `FluidContainerRegistry.registerFluidContainer` can be called manually with the correct empty/full values.

**Comment by LexManos** [comment]
Thats because it's not supposed to.
FluidContainerRegistry is for things that don't implement IFluidContainerItem, which the bucket does.

**Comment by LexManos** [comment]
Read your comment wrong, The vanilla bucket needs to be moved away from the FluidRegsitry and instead implement IFluidContainerItem, nobody should be using the registry.
IFluidContainerItem can change the ItemStacks's Item {its nasty but yes it works} which would make this work fine.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Feature]

**Comment by mezz** [comment]
This is fixed by Fluid Capabilities https://github.com/MinecraftForge/MinecraftForge/pull/2942. 
You can get a fluid handler for a single bucket with `FluidUtil.getFluidHandler(ItemStack)` and fill it like anything else using `IFluidHandler`.

**Comment by Actuarius** [comment]
@mezz closed this issue
