### ISSUE TITLE
Capabilities not exposed for vanilla entities?

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2507]
Just starting to look at these, and it looks like vanilla entities such as the player or horses or even zombies don't expose their inventories via capabilities. Is there a reason for this? Right now every mod that wants to use unified capa code on entities has to manually wrap around IInventory.

**Comment by LexManos** [comment]
That has not been implemented yet no. The IItemHandler has not been applied to entities yet.

**Comment by williewillus** [comment]
Okay, was just wondering if there was a explicit reason for it - if I have time I'll take a look at doing that

**Comment by williewillus** [comment]
#2614 2614
