### ISSUE TITLE
Armorstand head rotation not inherited to custom armor models

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2508]
See: https://github.com/williewillus/Botania/issues/23
and 
https://embed.gyazo.com/b30c8e3317bb015aab1f74047b8762fc.png from https://github.com/Vazkii/Psi/issues/85

It seems that armor stands seem to not provide the proper head rotations, causing armor that has a custom model from getArmorModel to always face south.

This is not related to the setModelAttributes bug, that got fixed when forge started passing the original model into getArmorModel

**Comment by williewillus** [comment]
I've tried setting a bunch of model angles manually in getArmorModel, but so far nothing is working.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]

**Comment by LexManos** [comment]
I think this has been fixed by https://github.com/MinecraftForge/MinecraftForge/commit/c0840da355181ea49c3b66a911d72b813e4154ad let me know

**Comment by williewillus** [comment]
This hasn't been fixed, all armor stands, when you place a helmet with a custom ModelBiped on it, said helmet always faces south.

I found a workaround though.
In that ModelBiped's render method, if you set the `netHeadYaw` parameter to 0, then the helmet faces the way the armorstand is facing.

I'm not sure why this is happening but hopefully the workaround gives a hint where to look

**Comment by LexManos** [comment]
Mind finding me a small test mod. And we'll sick fry on it.

**Comment by williewillus** [comment]
Yup, here you go

http://pastebin.com/c5b0TuAK


Very lazy mod, essentially stole one of Botania's armor models and applied the vanilla diamond texture to it. 

Put it on your head to see how it should look and feel, then plop it on an armor stand. It always faces south no matter where the armor stand faces.

Then, uncomment the if statement at the top of ArmorModel.render(). Now faces correctly on an armor stand.

**Comment by williewillus** [comment]
The most confusing thing is what makes the armor stands a special case vs a normal player/entitylivingbase

**Comment by williewillus** [comment]
I figured this one out. Armor stands use their own weird `ModelArmorStandArmor` that then grab the real armor model and render it.

The fix is to copy `ModelArmorStandArmor.setRotationAngles` into your own custom armor model class, deferring to super if the entity isn't an armor stand. The logic there does all the armor stand hardcoding which fixes things like helmets looking wrong or the armor "breathing"

**Comment by HenryLoenwind** [comment]
I only understand half of what you're saying without trying it out. But sorry, "copy over that code from somewhere if you make a custom helmet so it renders correctly in a rare case you most probably miss" is not a 'fix' in my eyes. At best it is a workaround.

**Comment by williewillus** [comment]
This is not just helmets facing the wrong way, it's also the armor "breathing". I also think if the armor stand is in any non-standard pose via command blocks, it won't render armor properly transformed.


Here goes:

In a normal living entity say a player, the flow of rendering goes like this:
* `RenderPlayer` -> `LayerBipedArmor` -> `LayerArmorBase` -> `ItemStack.getArmorModel` -> `ModelBase.setModelAttributes` -> `ModelBase.setLivingAnimations` -> render, which calls `ModelBase.setRotationAngles`

`LayerArmorBase` has two `ModelBase` fields to hold the armor being rendered, but in the case of custom models these fields are ignored in favour of `ItemStack.getArmorModel`.

However, armor stands have a special case
* `RenderArmorStand` -> anonymous subclass of `LayerBipedArmor` overwriting the two `ModelBase` fields with a special `ModelArmorStandArmor`. The rest of the flow is the same.

`ModelArmorStandArmor.setRotationAngles` does the proper reading of the armor stand's rotation states (arms, legs, head, etc.). 

But note that the two fields in `LayerArmorBase` are *ignored* completely in favour of the result of `ItemStack.getArmorModel`. This means the original implementation of `setRotationAngles` is called instead of the one in `ModelArmorStandArmor` that handles setting up the armor stand angles.

The result is that the armor stand's actual rotation states are ignored and its entity rotations are instead used, which are accurate for the most part so long as the armor stand is in a nice standard position, except the head facing is wrong and the armor "breathes" because `ModelBiped` adds in motion based on ticks existed.

Thus the workaround is to reintroduce this special case logic for armorstands to our own custom armor models.
