### ISSUE TITLE
Model Render Bug

### ISSUE THREAD

**Issue by Nedelosk** [MinecraftForge/MinecraftForge#2509]
When a model has on a corner the same color on two sides, minecraft renders little holes.
![2016-02-29_17 54 50](https://cloud.githubusercontent.com/assets/10259214/13401759/bd61648a-df0d-11e5-8b23-b5df7ecf5e57.png)

**Comment by williewillus** [comment]
Vanilla bug. not sure if forge can fix it

**Comment by Victorious3** [comment]
Probably an UV offset failure, Forge should be able to correct that for its own models at least @williewillus

**Comment by williewillus** [comment]
for reference: https://bugs.mojang.com/browse/MC-1794

**Comment by RainWarrior** [comment]
Should've been fixed by 4c8da35655d3947015abb4e2bd9277e52b1afac6
