### ISSUE TITLE
Entity.canTriggerWalking() no longer prevents farmland from being trampled.

### ISSUE THREAD

**Issue by Azanor** [MinecraftForge/MinecraftForge#2510]
In previous versions Entity.canTriggerWalking() could be set to false to prevent mobs from triggering certain events from happening - including farmland being trampled. The javadoc for that method even indicates this to still be the case, but farmland trampling now happens inside Block.onLanded which is called in Entity.moveEntity just before the check for canTriggerWalking().

**Comment by Actuarius** [comment]
@diesieben07 added labels [Superseded]

**Comment by diesieben07** [comment]
Closed in favor of #2730.
