### ISSUE TITLE
Can you add plant grow event, please?

### ISSUE THREAD

**Issue by Artem226** [MinecraftForge/MinecraftForge#2511]
Hello, MinecraftForge team!

I know, that in Forge there are a TreeGrowEvent, but there aren't a PlantGrowEvent(for example, then wheat grows). In my opinion it is important event, that allow modders to control a plant's growing process. For example, create mutations or pause plant's growing process. 

Please, add this event.

**Comment by williewillus** [comment]
More generally, I think an event for random ticks would be better

**Comment by Artem226** [comment]
@williewillus I think that an event for random ticks will cause a big load to the minecraft, but plant grow event will fired only then plant is about to grow.

**Comment by williewillus** [comment]
We have rendering events firing every frame, I doubt random ticks will be comparatively heavy

**Comment by Artem226** [comment]
So, may be, but this issue isn't for that. This issue is about event that will be called then plant is about to grow, not then every tick. If you want to offer block tick event(Why?) to the Forge's autors create a new issue.

**Comment by williewillus** [comment]
plants grow using random ticks...

**Comment by Spartan322** [comment]
I'm gonna bet Lex is gonna come here and say submit a PR, and the fact that a general random tick event could probably close this just as easily means it entirely pertains to this issue.

**Comment by OvermindDL1** [comment]
Random rendering ticks are client-side only and nearby only.  Random ticks happen in all loaded chunks hundreds of times per tick.  A plant specific thing would be better.

**Comment by Benimatic** [comment]
I'd be interested in a random tick event that would allow some control over whether they happen or not. Random ticks happen 3 times per loaded chunk per tick.

A plant specific thing would have to be implemented for each plant, and each modded plant, no?

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]
