### ISSUE TITLE
FMLCommonHandler.instance().getEffectiveSide() Returns client when using Nettys Epoll threads

### ISSUE THREAD

**Issue by Jay113355** [MinecraftForge/MinecraftForge#2512]
getEffectiveSide() in FMLCommonHandler: 

> thr = Thread.currentThread();
    if (thr.getName().equals("Server thread") || thr.getName().startsWith("Netty Server IO")) {
        return Side.SERVER;
    }
    return Side.CLIENT;

If your on a server and the server has 'use-native-transport=true' set in the server.properties
The Netty thread name becomes 'Netty Epoll Server IO' instead of 'Netty Server IO'

The if should include `thr.getName().startsWith("Netty Epoll Server IO")` to compensate.

**Comment by kashike** [comment]
https://github.com/MinecraftForge/FML/issues/583#issuecomment-68610324
https://github.com/MinecraftForge/MinecraftForge/pull/2113#issuecomment-139697564

**Comment by Jay113355** [comment]
Hmm okay then. Looks like this needs a bit more of an overhaul then i was expecting.

Off the top of my head, one thing i can propose is adding a check to see if we are running in a dedicated server environment. I'm 90% sure if we are a dedicated server there is no client code and thus:
```java 
if (this.getSide() == Side.SERVER) return Side.SERVER;
````
Should be valid. And then the hack is limited to only failing on the client end of things.

So far I'm not coming up with any good ways for figuring this out on the client environment.
Unless we can track what thread is started by whom. 

Well anyway, i had a mod trying to call a client only class on a dedicated server and with the Netty thread name change only effecting Linux server users with 'use-native-transport=true' i think my above proposal should help clear things up.

**Comment by williewillus** [comment]
"Calling client only class" shouldn't even be checking getEffectiveSide, whatever mod that is, has an incorrect understanding of sides and the difference between getEffectiveSide and getSide

**Comment by Jay113355** [comment]
I think the mod maker was trying to use getEffectiveSide as a combo method of getSide and getEffectiveSide. And up until now it wasn't a problem. 
But yeah i see your point. There is probably a better way of doing this, for this mod at least.

Back to the topic: Would it be possible to split the client and server up via ThreadGroups?

**Comment by LexManos** [comment]
getEffectiveSide is a hacky attempt to get the side into it has no garentes about its return.
Anyone who is relying on it for using client only code is doping it wrong.
