### ISSUE TITLE
ForgeHooks.initTools() being called in static initializer

### ISSUE THREAD

**Issue by Victorious3** [MinecraftForge/MinecraftForge#2525]
Long story short, this workaround was required to query the harvest levels from postInit:
```scala
// Force - initialize harvest levels, I don't know why this hasn't loaded yet...
Class.forName(classOf[ForgeHooks].getName)
```
Due to the nature of static initializers, initTools is being called just after loading the first world. I'd suggest moving it to somewhere it's being initialized reliably.

**Comment by LexManos** [comment]
What are you talking about, and there is nothing wrong with initalizing something statically it will be run first time it's accessed. That's how static works. Querying them from post init would invoke the static initalizer and everything would be fine. 

Explain yourself better and the issue you're having. There will never be a need for you to call Class.forName

**Comment by Victorious3** [comment]
@LexManos No it doesn't since they are saved in Block.harvestTool and Block.harvestLevel. Note that I need the *raw* harvest levels to create a map of "tool class/meta" -> "harvest level" for the block so `ForgeHooks.canHarvestBlock` / `ForgeHooks.canHarvestBlock` don't work for this.

**Comment by hea3ven** [comment]
Yeah, the problem is that ForgeHooks is the one that initializes the Block's harvestLevel/harvestTools, but the Block class doesn't load the ForgeHooks class, so there is a chance to have blocks without these properties initialized. BuildCraft has done this https://github.com/BuildCraft/BuildCraft/blob/7.2.x/common/buildcraft/core/properties/WorldPropertyIsOre.java#L47-L53 for some time to go around the issue.

**Comment by LexManos** [comment]
Right I see the issue, it seems that sometime in the past the init call got removed from our early inializing. And with the fact that {Honestly I forgot as this is really old code} that the Blocks cache the values and don't actually have a call to the ForgeHooks class themselves it won't initialize it.
So there is nothing wrong with having this done in a static initialize, the proper issue is that that initializer isn't being called by Forge early enough for you guys. A call needs to be made to it in MinecraftForge.initalize()

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]
