### ISSUE TITLE
Performance problems with ClassInheritanceMultimap/getEntitiesInAABB in 1.8.9 vs 1.8.0/1.7.10

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2526]
Before I start let's get some points out of the way.
* The mod code in question should not be slow. It runs just fine in 1.8.0 and 1.7.10, before this change to the vanilla code was made.
* ClassInheritanceMultimap is a data structure in each Chunk that organizes the stored entity based on their class, supposedly making retrieval of specific entity types more efficient. It is used heavily used in getEntitiesInAABB.

However, I've found the opposite to be true.
In Botania, there are two LivingSpawnEvent.CheckSpawn event handlers. Here's one (https://github.com/williewillus/Botania/blob/MC18/src/main/java/vazkii/botania/common/brew/potion/PotionBloodthirst.java#L46)
The commented out one is fine for use in 1.7.10 and 1.8.0, but in 1.8.9 generates *millions* of `ClassInheritanceMultimap$1`'s every second.

Some experimental results are as follows, with the latest version of Baubles and Botania on the respective versions. VBO on when available, render distance 12, VSync off, frame cap to 120.

Steps:
1. Create default superflat world with seed "-1". Let it settle until it's about midday. Look up at sky to decrease influence of rendering.
2. /gamerule doDaylightCycle false
3. /time set day
4. start CPU sampling in visualvm and watch
5. start memory sampling in visualvm and watch

1.7.10 observations:
* Not much CPU usage on anything
* Memory is fine in general. About 40-60k AABB's created each sampler tick, but that seems about normal.

1.8.9 (with same code as 1.7.10):
* ClassInheritanceMultimap.initializeClassLookup is hovering constantly from 15-20% of the total CPU time
* Eventually settles to about 5%, everything else looks okay
* Filter memory to AABB: Couple thousand every sampler tick, occassionally spikes to 300k at peak. Nothing too big.
* Filter memory to ClassInheritanceMultimap: oh god.
    * At peak, we reach nearly *eight million* instances
    * Most of the 8 million are allocated pretty much at all within the same sampler tick
    * Permanently more instances of ClassInheritanceMultimap$1 than BlockPos (yeah...)
    * Removing the respective code from the mod completely eliminates the problem

This tells us something is really, really wrong in ClassInheritanceMultimap and/or how getEntitiesInAABB works when called repeatedly in 1.8.9+ 
Posting this here to discuss possible ways to patch it or for further investigation (or if I'm being retarded somehow)

**Comment by williewillus** [comment]
Additional info: It appears the intensity of this issue is greatly increased the bigger the search BB is. In the code above I'm searching 64 blocks to each side of the origin point (128^3 centered on the point). In contrast, vanilla only ever searches tiny 1x1x1 areas, leading this issue to be almost nonexistent for them.

Some numbers: (Search BB radius -> Approximate peak instances of ClassInheritanceMultimap$1)
Only one of the event handlers was enabled, hence 64 only being 4 mil instead of 8 as tested above.
* 1 -> 66k
* 2 -> 83k
* 4 -> 83k
* 8 ->107k
* 16 -> 340k
* 32 -> 741k
* 64 -> 4mil

**Comment by diesieben07** [comment]
I did some investigation on the code. Generally what `ClassInheritanceMultimap` is doing is trading memory for CPU time (seems to be a common theme in 1.8+).
Basically there is a global static set of classes that have been queried for, ever. When a new ClassInheritanceMultimap is constructed, it keeps separate Lists for each of those classes, pre-sorted by type.
So a creeper would be in the list for Entity, EntityLivingBase, EntityLiving, etc. 
The `ClassInheritanceMultimap$1` thingy is the dynamic iterable returned from a query to this class. Personally I do not get why they do this, the Iterable does some filtering, but that filter should be pointless, since the data is pre-filtered already.
All they'd have to is just return the list that they already have (`map.get(<classKey>)`) in `getByClass`. This would eliminate the object spam you are seeing.

Your search searches 128 x 128 x 128 blocks. This is 8 x 8 x 8 = 512 chunks. Each chunk has 16 layers (entity lists in a chunk are layered, like blocks in the save file). So that is 512 x 16 = 8192 entity lists to search per tick. Not sure where your 8 million figure comes from (then again I do not know how long the profile sampler tick is).

**Comment by LexManos** [comment]
Well obviously something that does more work and is more generic about how it does it will create these temporary objects. And yes when you're doing it per spawn check which happens roughly 17x17x5x3x4(17340) times per tick... Times that by the 1024 objects made per query, and the fact that a sampler timeframe isn't one tick. It's easy to see wherer the sampler would be in the millions.

When you're doing something on that scale you should be doing a optimized version of just searching the player list {which has 1 entry in it...}

But yes, Diesiben is correct however, it does seem dub that they are filtering an already filtered list. I'll look into that when I get a chance and see if we at forge and opt that out.

**Comment by williewillus** [comment]
yup, I'm gonna go with just iterating the player list
interesting to see them trading off like this and spamming the gc, thanks for investigating!

**Comment by cpw** [comment]
Hmmm, this should only be a problem if there's a significant escape from new to old gen. It's not ideal to be spam creating objects, but the GC should handle it, if there isn't significant escapage. Additionally, depending on what this object actually is doing, it might get ripped apart into stackvars, if it's nothing but a field holder and doesn't escape a particular context.

**Comment by diesieben07** [comment]
Yes, I don't think the "problem" here is the Iterable. But there is not just the Iterable. There is also the list iterator, the filter (InstanceOfPredicate) and the filtering iterator.
The Iterable might be properly inlined and folded away, but no way this is happening for all that iterator filtering.

**Comment by williewillus** [comment]
I think this is something better resolved by me optimizing (which I've done). theres not really anything forge can do to vanilla to help heavily so gonna close this now. Thanks for the investigation!
