### ISSUE TITLE
FluidUtil interactWithTank method

### ISSUE THREAD

**Issue by korti11** [MinecraftForge/MinecraftForge#2527]
If i use the universal bucket to fill a tank and use the interactWithTank method of the FluidUtil class, it doesn't check if it can fill in to the tank. So if i have a tank with lava in it, i can filled with a custom fluid that use the universal bucket.

**Comment by diesieben07** [comment]
It [checks just fine](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L171).

**Comment by korti11** [comment]
Yeah, but that is only if it is the minecraft bucket and not the forge bucket.

**Comment by diesieben07** [comment]
Actually, the universal bucket itself as well as the vanilla bucket do not perform any filling, at all.

**Comment by korti11** [comment]
It works for me, except that it don't check if it can fill. It goes in this [else block](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L58) and in the methods [tryFillFluidContainerItem](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L222) and [tryEmptyFluidContainerItem](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L321) it doesn't check if the tank can be filled.

**Comment by diesieben07** [comment]
True, it should check that.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]
