### ISSUE TITLE
Block.getLightOpacity(world, pos) invocations for unregistered chunks

### ISSUE THREAD

**Issue by sfPlayer1** [MinecraftForge/MinecraftForge#2529]
Forge's position-aware getLightOpacity method is being called from Chunk.generateSkylightMap() during chunk generation. The chunks aren't in the world's position->chunk map yet, leading to infinite generation recursion for any reasonable implementation of Block.getLightOpacity(world, pos).

The problem could be fixed by postponing generateSkylightMap() to be executed later in ChunkProviderServer.originalLoadChunk(). Calling the no-parameter Block.getLightOpacity() method would avoid the recursion as well, but yields potentially incorrect skylight and height map values.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]
