### ISSUE TITLE
1.8: Missed Block.getLightOpacity() patches

### ISSUE THREAD

**Issue by sfPlayer1** [MinecraftForge/MinecraftForge#2530]
There's multiple instances of direct invocations of the non-position-aware getLightOpacity method:

World.checkLightFor(EnumSkyBlock, BlockPos)
TileEntityBeacon.updateSegmentColors()
World.canBlockSeeSky(BlockPos)

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]
