### ISSUE TITLE
Enum issues in ASMData

### ISSUE THREAD

**Issue by Elec332** [MinecraftForge/MinecraftForge#2535]
When you have an annotation that you want to process, EG:
 `public @interface EnumInterface {`
`public Enumfacing[] value(); //Just using EnumFacing as an example Enum`
`
}       
`  
and you want to process it during PreInit, where you can get the ASMDataTable from the event,
you'll encounter an issue.

The first is not really an issue, but its just weird:
-If you pull the Annotation-map from the annotationdata, and you try to retrieve "value", you always get an empty ArrayList, even if there is a value specified in the annotation.
-The real "data" for the "value" key can be retrieven by using Map.get(null)   

But, as you can see, I want to retrieve an Enum Array, well, when I pull the data, I do not get a List or array of the Enum. Instean, I get a "net.minecraftforge.fml.common.discovery.asm.ModAnnotation$EnumHolder". The first problem is, that even if I define multiple Enum values, I always get only one of those "EnumHolders", and the value always seems to be the last Enum in the array you defined in the Annotation.
The second problem is that you cannot access the values of the EnumHolder. It has 2 fields, a desc (description) field, and a value field (Enum value), but both of those fields are private.

This makes it basically impossible to process Enum values in an Annotation with Forge's cool ASMDataTable.

**Comment by cpw** [comment]
Heh, I never really handled arrays in the scanner properly..

**Comment by Actuarius** [comment]
@diesieben07 added labels [Superseded]

**Comment by bs2609** [comment]
This should be closed (addressed by #2911)

**Comment by mezz** [comment]
Thanks
