### ISSUE TITLE
please fix the 1.9 branch mcp version to 9.24

### ISSUE THREAD

**Issue by LOLGAMES** [MinecraftForge/MinecraftForge#2536]

**Comment by cpw** [comment]
No! We're following a process here. Unhelpful issues like this waste our time! Forge 1.9 delayed a week by idiot harassing developers!

**Comment by Jishaxe** [comment]
Ouch!

**Comment by liach** [comment]
When will you fix all the patches by the way? There's still 3 more reject files to go.

**Comment by Termin8or** [comment]
People are such twats, just leave developers alone.

**Comment by LOLGAMES** [comment]
@cpw i'm really sorry i didn't know you were following a process
