### ISSUE TITLE
Strange errors

### ISSUE THREAD

**Issue by xLivan** [MinecraftForge/MinecraftForge#2538]
I have strange bugs with, I think, chunk generation. This happens when players dies or login.
Log 1: http://pastebin.com/rPPgEYGT
Crash 1: http://pastebin.com/PNgjWeeh
Log 2: http://pastebin.com/zEWJqQAh
Crash 2: http://pastebin.com/DmW1u9rc
Log 3: http://pastebin.com/Q9UVAFaD (without crash)
Log 4: http://pastebin.com/tqD2gJMW
Crash 4: http://pastebin.com/h6V2C6V2

Sometimes, when player dies, there are messages like this:
Log 5: http://pastebin.com/hMYLQmxa

And sometimes, when player login, server kick him with Internal server error:
Log 6: http://pastebin.com/F1A98PP9

I don't know what it is cause. Tell me if I need to post this somewhere else.

**Comment by covers1624** [comment]
To me this seems to be a Cauldron style server (Bukkit + Forge), I Assume the Forge guys can't help here, i suggest submitting this to whoever made the server software you are using.

**Comment by LexManos** [comment]
Github is not the place to do basic tech support like this. Use the forums.
