### ISSUE TITLE
1.9: Dropping an item creates a client sided clone

### ISSUE THREAD

**Issue by Vazkii** [MinecraftForge/MinecraftForge#2549]

**Comment by williewillus** [comment]
Doesn't happen in latest forge anymore?

**Comment by TehNut** [comment]
Forge 1770: http://tehnut.info/share/MLYB0rqwMw.mp4

**Comment by Lanrik** [comment]
Only if it dropped in any kind ui. Inventory, chest etc. Forge 1770
http://imgur.com/NDXf2hE

**Comment by LexManos** [comment]
I'll look into it when i get back in town.

**Comment by Lanrik** [comment]
Forge 1776, not fixed.

**Comment by williewillus** [comment]
Can be closed: #2593

**Comment by Lanrik** [comment]
How about render bug? I need create a another issue?
