### ISSUE TITLE
1.9: Item.shouldCauseReequipAnimation is ignored

### ISSUE THREAD

**Issue by Vazkii** [MinecraftForge/MinecraftForge#2550]
The method should also be updated to have an EnumHand parameter.

**Comment by LexManos** [comment]
I decided against the EnumHand part because that really shouldn't matter.
Also can you post a small same to test it. It *should* work but i'll look into it.

**Comment by Vazkii** [comment]
Sure, throw this in any item and you'll see it doing the requip animation constantly https://gist.github.com/Vazkii/a431564ab6bbbe240787

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by LexManos** [comment]
This has been fixed IIRC, and I also can not reproduce it using your code. So closing.
