### ISSUE TITLE
1.9: Clicking 'No' on missing blocks/item gui stalls the game

### ISSUE THREAD

**Issue by modmuss50** [MinecraftForge/MinecraftForge#2553]
When clicking 'No' on the missing item/block gui after trying to open a world. The game stalls, with a gui saying 0%.

https://modmuss50.me/shots/java_2016-03-16_17-50-15.png

There is no log output.

**Comment by williewillus** [comment]
does this still happen?

**Comment by modmuss50** [comment]
Yes it does @williewillus, just tested it. Like I said no log output

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]

**Comment by mezz** [comment]
I don't think this is still an issue in 1.11. Can you confirm?

**Comment by TehNut** [comment]
I have not noticed this issue even in 1.10.2.

**Comment by GirafiStudios** [comment]
This was fixed quite a while ago on 1.10.2.

**Comment by modmuss50** [comment]
Yeah, it was fixed a while back, just forgot to be closed.
