### ISSUE TITLE
1.9: Error in ItemSlab class.

### ISSUE THREAD

**Issue by Termin8or** [MinecraftForge/MinecraftForge#2554]
I currently can't test the forge developer environment, to make a pull request, due to an issue with func_185055_a in ItemSlab.java, the final parameter that gets passed to the method, within is not the type that is expected. 
![screenshot from 2016-03-16 20 46 21](https://cloud.githubusercontent.com/assets/8021352/13828199/4a75f564-ebb8-11e5-9965-8c705cdf2568.png)

**Comment by LexManos** [comment]
Clean your cache this was fixed last week.
