### ISSUE TITLE
1.9: Some bugs I found while testing

### ISSUE THREAD

**Issue by ProfessorProspector** [MinecraftForge/MinecraftForge#2556]
These are just a bunch of random ones I found while testing. I put them all in one issue to prevent issue spam, but if you want me to separate them let me know, I'll do it.

* Placing blocks where they can't be placed causes a crash, ONLY when holding shift

To replicate, place redstone dust on the ground. Hold shift and try to place redstone dust on top of it. Crash. If you don't hold shift, no crash and no place. This can be done with trapdoors, doors, buttons, etc. Any block that has special conditions on where it can be placed. (Trapdoors are a little different because in vanilla 1.9 they can be placed anywhere, not sure why they cause issues in forge)

* Blocks with gravity do not actually fall.

Simple to reproduce. Just place sand/gravel/anvil and watch it not fall

* When shooting arrows it shoots two arrows

Again, easy to reproduce. Shoot an arrow and hope it's not invisible (see next bullet point). It both fires 2 arrows, and uses up 2 arrows.

* Most of the time arrows are invisible

Shooting arrows they are most of the time invisible. Sometimes when they land or when you first shoot them, they appear, but most of the time they're invisible.

* Potion arrows are consumed in creative mode

Shoot a potion arrow in creative. Boom. Two arrows consumed.

* You can pick up a potion arrow in creative

Again, related to last issue. Normal arrows cannot be picked up in creative and are not consumed.

* Tools held in offhand are upsidedown in third person and wonky in first-person.

Just put a tool in your offhand.

* Player does not render in third person when above world height (sometimes)

The reason I say sometimes is because sometimes when flying up there with the Elytra my player did render for a few seconds, then disappeared again.

**Comment by williewillus** [comment]
Regarding some of these

* Potion arrows consumed in creative is a vanilla bug, 
* Same for picking them up (I believe)
* Arrows invisible actually extends to all entities, they get randomly removed clientside for no reason
* Tools held weird was fixed
* Player not rendering above world height is a vanilla bug

**Comment by ProfessorProspector** [comment]
All entities including what? The only two I noticed having issues were the arrow and ender eye. The rest seemed fine.

**Comment by williewillus** [comment]
everything. mobs from spawn eggs, minecarts, upon spawning they disappear from the client. I found the cause: #2558

**Comment by LexManos** [comment]
Fixed all those issues in recent commit.
Except the players/entities rendering above the world height when the top chunk is culled.
Not exactly sure how to fix these as it's a culling issue. We'll need to look into it more, but it's a vanilla bug not a Forge bug.
