### ISSUE TITLE
[1.9] Entities being removed from the client

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2558]
In the latest 1.9 head, entities spawned are usually removed clientside moments after spawning. This can be tested with mobs, minecarts, arrows, etc. It only happens sometimes, and they usually don't reappear but may. 
You know they are still serverside because if you do it with slimes you can still see the particles from them bouncing around, but whenever you kill a large slime it splits and the children disappear shortly after spawning but you still see the hop particles.

I've narrowed it down to this patch here. If removed everything works alright: https://github.com/MinecraftForge/MinecraftForge/blob/1.9/patches/minecraft/net/minecraft/entity/EntityTrackerEntry.java.patch#L12

However, that patch is probably there for a good reason, which I don't know. So this is just a heads up on where to look

**Comment by LexManos** [comment]
This is a old fix for a position issue that they seem to of fixed in vanilla in 1.9. Going to remove this patch and related code and we'll see if we need it anymore.

**Comment by FM22** [comment]
I am still having entities vanish on me intermittently.
