### ISSUE TITLE
Block Harvesting only supports a single ToolClass per Block Meta

### ISSUE THREAD

**Issue by CovertJaguar** [MinecraftForge/MinecraftForge#2561]
Before the Harvest functions were moved to the Block, it was possible to have multiple valid tool classes on a single block/metadata. This is no longer the case.

**Comment by LexManos** [comment]
The original version was a hack, and this version is working fine.
It may need some expansion or cleanup to be what people want but these tool classes stuff is old legacy crap that needs to actually be re-done. Look into it ;)

**Comment by diesieben07** [comment]
Can be achieved via `HarvestCheck` and `BreakSpeed` events.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Feature]
