### ISSUE TITLE
1.9: blocks adjacent to slabs or stairs don't render properly.

### ISSUE THREAD

**Issue by EXTER7** [MinecraftForge/MinecraftForge#2564]
Blocks adjacent to slabs or stairs become invisible. This happens with vanilla slab/stairs with no mods other than Forge installed. This doesn't happen on vanilla 1.9.

Screenshots:

![2016-03-18_10 23 51](https://cloud.githubusercontent.com/assets/3077881/13880884/d2f0e6dc-ecf4-11e5-9962-5142e35d9828.png)
![2016-03-18_10 23 57](https://cloud.githubusercontent.com/assets/3077881/13880890/d5e444a6-ecf4-11e5-93be-e6ec86067b47.png)
![2016-03-18_10 24 10](https://cloud.githubusercontent.com/assets/3077881/13880891/d7929c4e-ecf4-11e5-9b86-9e08b27b7393.png)

**Comment by KnightMiner** [comment]
Seems like slabs and stairs are acting as solid blocks when it culling
