### ISSUE TITLE
1.9 PlayerDestroyItemEvent issues/inconsistencies

### ISSUE THREAD

**Issue by gigaherz** [MinecraftForge/MinecraftForge#2565]
The event seems to fire in very strange/inconsistent situations.

1. It won't fire when the item breaks as a result of the player attacking an entity.
2. It only fires on the client side (player.worldObj.isRemote is only ever true), when the item is broken from mining.
3. It won't fire when an armor piece breaks due to received damage (this was.
4. It fires (client and server) when placing or using the last item in a stack of items, which does not really match the event name.

EDIT: I know some of these were also the case in 1.8.9, #.2 seems to be a new issue.

**Comment by williewillus** [comment]
@gigaherz might wanna recheck this/start on a PR now that PIE's been pulled

**Comment by gigaherz** [comment]
Yep, I was hoping to take a look at it over the weekend. If I can't do that, I don't know when I'll be able to work on it, cos I start my new job on Monday.

**Comment by diesieben07** [comment]
Should be fixed by https://github.com/MinecraftForge/MinecraftForge/commit/6b8466778e23226e686bcd0c83769804541eac49. Please comment if not.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]
