### ISSUE TITLE
1.9 mod entity (throwable) disappears shortly after spawning

### ISSUE THREAD

**Issue by gigaherz** [MinecraftForge/MinecraftForge#2567]
The code is mostly copied over from other entities I have done in the past on 1.8, with bits from the 1.9 snowball.

Demonstration: https://dl.dropboxusercontent.com/u/743491/2016-03-18-1725-04.mp4
Alpha build, for testing: https://dl.dropboxusercontent.com/u/743491/Survivalist-1.4.0.jar

Code links:
Registration: https://github.com/gigaherz/Survivalist/blob/1.9/src/main/java/gigaherz/survivalist/Survivalist.java#L314
Rendering: https://github.com/gigaherz/Survivalist/blob/1.9/src/main/java/gigaherz/survivalist/client/ClientProxy.java#L26
Entity: https://github.com/gigaherz/Survivalist/blob/1.9/src/main/java/gigaherz/survivalist/rocks/EntityRock.java

**Comment by williewillus** [comment]
@LexManos This could be related to that patch I told you about / you removed that made vanilla entities disappear shortly after spawning.

Maybe only modded entities need it now? No idea.

**Comment by Adubbz** [comment]
Had this same issue occur with mud balls in BoP. It doesn't appear to be a rendering issue, bounding boxes are also removed upon disappearing after using F3 + B

**Comment by Katrix-** [comment]
Chiming in here with the testing I did. It seems to be a client side issue. The entities are still there on the server side, but on the client they are teleported to something around 0, 0, 0

**Comment by LexManos** [comment]
It may be related to the issues in the spawn fixing, i'll look at forge's code later. However modders will have to update themselves for the new scale/location values that vanilla uses. 1.8's positioning code will not work in 1.9

**Comment by flammpfeil** [comment]
net.minecraftforge.fml.common.network.internal.EntitySpawnHandler
spawnEntity()
```
-            entity.serverPosX = spawnMsg.rawX;
-            entity.serverPosY = spawnMsg.rawY;
-            entity.serverPosZ = spawnMsg.rawZ;
+            entity.serverPosX = spawnMsg.rawX * 128l;
+            entity.serverPosY = spawnMsg.rawY * 128l;
+            entity.serverPosZ = spawnMsg.rawZ * 128l;
```

or 
Changed to "long" and scaling factor from 32 to 4096 the rawX,Y,Z variable of EntitySpawnMessage

**Comment by LexManos** [comment]
Oh right, custom entity spawn packet wonder why I forgot about that class. I'll address it on Monday. Should be a simple fix. Just need to do a little bit more research. Most likely i'll just mimic the data sent by the vanilla spawn packet, as this packet is faithfully designed after it.

**Comment by LexManos** [comment]
That should do it. Let me know.

**Comment by gigaherz** [comment]
My throwable does not appear to work, crashes upon trying to send a message: https://gist.github.com/gigaherz/0f49da0013396ca8b1e5
The cause would appear to be entityUUID not being initialized.

**Comment by Katrix-** [comment]
I've been getting this error for other entities too, Not just throwables when trying to spawn them with spawn eggs.

**Comment by LexManos** [comment]
Whops, fixed https://github.com/MinecraftForge/MinecraftForge/commit/0ce790ca2bdf53a7115c2a1e1fee4aee4c9d4517
