### ISSUE TITLE
1.9 item rendering bug

### ISSUE THREAD

**Issue by TheChronomancer** [MinecraftForge/MinecraftForge#2569]
when i hold a CAD (from Psi) in first person it doesn't render in the right position and sometimes the CAD derps when being held
![image](https://cloud.githubusercontent.com/assets/8211402/13890233/9e21305c-ed07-11e5-99c9-01e56922cbd6.png)

**Comment by williewillus** [comment]
update forge

**Comment by TheChronomancer** [comment]
i am using the latest (and only) version of Forge for 1.9 as of today!

**Comment by GirafiStudios** [comment]
No you're not. There is two versions on 1.9 atm.

**Comment by TheChronomancer** [comment]
i only see one

**Comment by TheChronomancer** [comment]
im using 1767 version of forge 1.9

**Comment by GirafiStudios** [comment]
1767 is the latest.

**Comment by TheChronomancer** [comment]
i still get the bug no matter what i do
the only time it didn't happen was when i put it on my offhand and that only happened once

**Comment by RainWarrior** [comment]
Why is this a forge bug? report it to @Vazkii.

**Comment by TheChronomancer** [comment]
I did she said it was a forge bug

**Comment by Vazkii** [comment]
It is, it's #2550
