### ISSUE TITLE
[1.9] ISpecialArmor needs modernizing

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2571]
specifically, the `int slot`s everywhere need to become `EntityEquipmentSlot`

**Comment by TheOldOne822** [comment]
ISpecialArmor translation on the damage reduction calculation for vanilla armor needs to be updated to match the new vanilla calculation too.

**Comment by LexManos** [comment]
It should be updated for the new calculations already unless I missed something.
If I have feel free to point it out with the new proper calculations.

**Comment by williewillus** [comment]
they changed something about armor in 1.9.1 (with the toughness attribute and stuff), idk if that's what @TheOldOne822 was mentioning

**Comment by LexManos** [comment]
Yes i've seen the 1.9.1 changes, i'll be sure to adhear to them when I do the update.

**Comment by TheOldOne822** [comment]
Actually I was referring to what WayofTime posted in #2720

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]

**Comment by diesieben07** [comment]
Closed in favor of the PR: #2765.
