### ISSUE TITLE
[1.9] No way to register potions

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2574]
* The 1.8.9 Potion constructor that autoregisters you is gone
* Accessing the vanilla potion registry is probably bad
* The register method on the fml potion registry is deprecated saying to use GameRegistry
* GameRegistry has nothing about potions

**Comment by LexManos** [comment]
for now, add(-1, name, object) is the way you should go. it's deprecated yes, however we are intending to make a slimer interface that JUST does the mapping stuff and decouples from vanilla's methods.
Untill that time, use add(-1) on any registry that isn't in the game data.

I also plan on doing quite a BIT of registry related helper fixups, but that's when i get time.

**Comment by williewillus** [comment]
assuming this is closed by new registry stuff
