### ISSUE TITLE
[1.9 request] Pull isAir up into IBlockProperties

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2575]
it's the only one of the commonly used methods that isn't in IBlockProperties, which means we have to do the whole state.getBlock().isAir(state ...) thing

**Comment by LexManos** [comment]
Or use world.isAir.
I havent decided how intrusive to the IBlockProperties I want to go because we are a J6 target, which means we can't do defauly implementations of methods. Which could cause potential errors in interactions with other mods.

**Comment by williewillus** [comment]
heh, didn't know that existed. I'll stick with that for now
