### ISSUE TITLE
[1.9] SoundEvents (and Enchantments and PotionTypes) need a FML registry

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2576]
SoundEvent currently uses a vanilla namespaced registry, with a statically incrementing integer ID. 

Would it be in our interest to put an FML registry on this as well, so servers and clients with mismatching mod sets (think MATmos or something clientside only) wouldn't get wrong sounds playing? (the sound packet uses this integer ID, so they must match on both sides)

**Comment by williewillus** [comment]
Another note is that its currently impossible to register new SoundEvents without reflection as the register method is private :P. The registry itself its public but to access the next ID you still need reflection since it's also private :P

But mainly my concern is with the original thing, and also adding FML registries for everything vanilla has a registry for that we haven't fml-ed yet (`Enchantment`s, `PotionType`s, `SoundEvent`s)

**Comment by SoniEx2** [comment]
I think they should be namespaced so syncing is easier.

**Comment by williewillus** [comment]
they already are

**Comment by SoniEx2** [comment]
I mean namespace IDs and event IDs separate.

**Comment by williewillus** [comment]
that's not how FML's registries work

**Comment by SoniEx2** [comment]
It'd make syncing easier. It'd require some changes to vanilla packet handling but those are actually pretty minor changes.

**Comment by williewillus** [comment]
if you're going to suggest they rewrite the entire way registries work do it on the right issue.
And no vanilla packets will never be patched  because that breaks network compatibility

**Comment by diesieben07** [comment]
How would it make syncing easier? 
"You send an int" vs. "You send an int". I do not get it.

**Comment by SoniEx2** [comment]
You sync the modid ints and hope the event ints are already synced. Then blame it on the modder.

**Comment by SoniEx2** [comment]
@williewillus `if (id < 0) { modid = -id; eventid = readInt(); } else { modid = 0; eventid = id }`, fully network compatible if you don't add more events.

**Comment by williewillus** [comment]
you have no clue how FML synced registries work

**Comment by diesieben07** [comment]
The point of FML registries is that the IDs (shared between all mods) are stored in the world save and also synced to the client on connection.
ID order does not matter, since FML makes sure the IDs stay consistent.

**Comment by williewillus** [comment]
\o/

**Comment by LexManos** [comment]
Perfect examples of how stupid simple it is now that we have all the mechanics in place for registries in generic ways <3

**Comment by Spaceshipable** [comment]
Has a work-around been found for this?

**Comment by LexManos** [comment]
They have registries.

**Comment by williewillus** [comment]
@Spaceshipable see ForgeRegistries class

**Comment by Spaceshipable** [comment]
Got that all working now. Thanks.
