### ISSUE TITLE
[1.8.9/1.9] The Capability of TileEntity

### ISSUE THREAD

**Issue by ci010** [MinecraftForge/MinecraftForge#2577]
` public TileEntity() {`
`      capabilities = net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(this);`
` }`
Since TileEntity doesn't have any init method(and the field of capabilities is private),
if I want to inject another `ICapabilityProvider` to a type of TileEntity which is writen by myself, and the delegate of `ICapabilityProvider` will be passed by the parameter of constructor, the event just cannot approach this delegate.....

**Comment by williewillus** [comment]
Use AttachCapabilityEvent

**Comment by ci010** [comment]
Yes... I'm talking about the AttachCapabilityEvent which is fire at first, so that the event handler cannot get the delegate which is passed by the constructor later.

**Comment by diesieben07** [comment]
If you want to attach capabilities to your own stuff you override the methods inherited from `ICapabilityProvider`, which TileEntity already implements.

**Comment by gigaherz** [comment]
You don't attach/inject capabilities on your own TileEntity/Entity, you override hasCapability/getCapability directly, and in it you do like (pseudocode):
```java
if (capability == TheCapability.INSTANCE)
    return theCapability;
return super.has/getCapability(cap, facing);
```
