### ISSUE TITLE
Cannot find jcenter.bintary.com/com/github/abrarsyed/jastyle/jAstyle/1.3/jAstyle-1.3.pom

### ISSUE THREAD

**Issue by CM12000** [MinecraftForge/MinecraftForge#2580]
When I try to setup the Forge workspace (Forge: 12.16.01770), it fails with an error saying that it is unable to find https://jcenter.bintary.com/com/github/abrarsyed/jastyle/jAstyle/1.3/jAstyle-1.3.pom. I checked, and it seems that the file specified is recently removed or something (not quite sure about what happened to it). Then, I attempted an older version for 1.8.9, and it generated the exact same error.

In another attemp, I looked jAstyle up, and found version that forge requires, but I don't know how to set the Forge to manually load libraries instead of downloading them everytime, so any help about that would also be appreciated.

**Comment by LexManos** [comment]
Not a Forge issue.
