### ISSUE TITLE
Spawn Eggs created using FML spawn pigs.

### ISSUE THREAD

**Issue by FM22** [MinecraftForge/MinecraftForge#2581]
In my mod I am using the method `EntityRegistry.registerModEntity(Class<? extends Entity>, String, int, Object, int, int, boolean, int, int)` to register my mobs. I found this method also registers a new entity egg by adding to the `EntityList.entityEggs` map. The entity is indeed added to that map (I got it to print out), but when I use the spawn egg in-game it always spawns a pig. Summoning the entity (/summon) still works.

**Comment by LexManos** [comment]
Thought I updated all the patches for this. As Vanilla now Incorporated our "use entity name instead of metadata id" change. 
How are you getting the ItemStack for the egg?

**Comment by diesieben07** [comment]
The problem is that the spawning goes through the vanillla int ID for some stupid reason.

**Comment by LexManos** [comment]
No.. it doesn't.... it pases in a string name. So it should be fine. I'll look at it when im in town monday.

**Comment by diesieben07** [comment]
It passes in a string name,yes.
Which then gets translated (in EntityList!) to the int ID which then gets translated to the class. See in the other thread.

**Comment by FM22** [comment]
I'm not getting any ItemStacks; the method auto-generates the egg.

**Comment by FM22** [comment]
I can confirm that the egg itself is generated with the correct NBT.

**Comment by FM22** [comment]
Tracked the issue down to `EntityList.getIdFromString`. Why is the `spawnCreature` method using this at all?

**Comment by diesieben07** [comment]
Yes, I already know the fix. Going to update my PR now.
