### ISSUE TITLE
Forge Updater "Update Available" Notification 

### ISSUE THREAD

**Issue by MattDahEpic** [MinecraftForge/MinecraftForge#2582]
I think there should be some way to notify the user that there are updates for their mods installed. I also agree that the current trend of putting a message in chat on game join is a bit too messy.

If there are updates available for mods using the forge updater, I suggest that an emblem (like the realms notification) be placed on the Mods button. Mock up below:

![Updater Mockup](http://i.imgur.com/SCV3ES2.png)

This is non-intrusive, yet still prompts the end user's attention, which can be an integral factor to keeping packs on a somewhat recent version of mods.

**Comment by kashike** [comment]
I like this idea. :+1:

**Comment by luacs1998** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/d79000835348d76735b93a147d703549462c2334

**Comment by iLexiconn** [comment]
I think he wants to extend that system with this feature, not make a new one.

**Comment by LexManos** [comment]
Interesting, I await your PR. Problem with using the realms icon tho is that asset is in the realms library not MC. And copying it to our distro would be bad for copyrights.

**Comment by WayofTime** [comment]
Well, we could retexture it so that it is like an emerald instead. Would give the same idea, but also be in the realms of fair use.

**Comment by gigaherz** [comment]
I just drew this little 8x8 badge, with the same shape as the realms badge, but based on the color palette from the emerald. Feel free to use it:

![emerald](https://cloud.githubusercontent.com/assets/685851/13923153/b1fa6fd8-ef7f-11e5-8184-b1760a29684a.png)

**Comment by iTitus** [comment]
I will have a PR ready in a few minutes ;)

**Comment by tterrag1098** [comment]
Superseded by #2616

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Superseded]

**Comment by williewillus** [comment]
PR merged

**Comment by Actuarius** [comment]
@williewillus closed this issue
