### ISSUE TITLE
[1.9] ArrowNock/LooseEvent should be widened to EntityLivingBase

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2583]

**Comment by LexManos** [comment]
Not really sure it should. The point of these events is to allow for swapping of custom bows/arrows in the players inventory. Mobs don't have a Arrow inventory...

**Comment by williewillus** [comment]
yeah, I was seeing the onItemUseFinishes being widened and thought it'd be cool to have it fire for mobs as well.
We'd probably do with a general item use finish and item use tick event, closing for now
