### ISSUE TITLE
[1.9] PlayerInteractionEvent DISCUSSION

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2591]
Here'll be the discussion for the next iteration of player interaction events (mainly, right clicks. the left click block interact event still works)
MC interactions are bloody and ugly, so we should put some thought into making these as painless and easy to understand as possible

I have traced the full interaction logic here, if you want to understand how it all flows: https://gist.github.com/williewillus/c781d9824df3ae723bff

Mainly we need to find/determine
* Hook points
* Semantics upon cancellation (old one had all sorts of ugly stuff if you canceled on only one side, etc. etc.)
* If it's possible, a writeup of the proper values to return from the various interaction callbacks in item, block, entity, to get the desired behaviour. (e.g. "must return the same thing on both sides in this method or else you get desync!" and stuff like that)

**Comment by oitsjustjose** [comment]
So let me ask this: V-Tweaks mostly uses PlayerInteractEvents, and I'm noticing they're getting called, but failing my `event.action == Action.RIGHT_CLICK_BLOCK` check. Is this why? I don't want to make a bug-report for something that's already known to be WIP / not fully implemented, and people can go without with V-Tweaks. But I've noticed that almost every player interact event-based feature I add isn't working because of the action check.

**Comment by williewillus** [comment]
PlayerInteractEvent is not implemented at all in 1.9

**Comment by williewillus** [comment]
if you'd like, you could help by maybe cloning this branch and running your mod with it and seeing if it works?

**Comment by oitsjustjose** [comment]
Cool! I'll give it a try tomorrow, I've got an 8AM and it's already almost midnight here (tomorrow's a long day, nonstop from 8A-3P of classes / labs / bullcrap) :)

**Comment by williewillus** [comment]
Just gonna close this - redirect all discussion to the PR #2604

**Comment by oitsjustjose** [comment]
Sorry - I've been swamped with school exams and a large program (in Java) for my Software Design class, I haven't really had a ton of time to spend on actual modding :(
