### ISSUE TITLE
1.9 InventoryPlayer issue

### ISSUE THREAD

**Issue by ThexXTURBOXx** [MinecraftForge/MinecraftForge#2595]
The inv.getSlotFor(ItemStack istack)-method returns -1, if the stack is in the offHand-Slot (inv is a instance of the Inventory of the player).
But if I give the value to the inv.getStackInSlot(int index)-method, then it gives me a ArrayIndexOutOfBoundsException.
I think it doesn't check the offHand-Slot or the offHand-Slot has a other index there.
My full code is here (maybe the error is my fault): [Reforged Repo](https://github.com/TheOnlySilverClaw/Reforged/blob/1.9-%280.6.1%29/java/org/silvercatcher/reforged/util/Helpers1dot9.java#L16)

**Comment by gigaherz** [comment]
So far as I can see, InventoryPlayer functions only work with the main inventory, not the armor/offhand. To get those slots, you have to use player.getStackFromSlot(EntityEquipmentSlot) and player.setItemStackToSlot(EntityEquipmentSlot, ItemStack). Weirdly enough, InventoryPlayer.getSizeInventory DOES count those slots. I'd guess that's a vanilla bug.

**Comment by williewillus** [comment]
We should really just be exposing caps on all vanilla entities (and not just using those wrappers around them in IInventory form)

**Comment by LexManos** [comment]
The idea is to expand caps as needed.
The player one has a few wrappers, one for the main inventory, and one for the armor/extra.
Probably needs to be updated to include offhand in one of those {i'd say armor}
And then there is a wrapper that chains inventories together.
So it's all covered, just needs some testing.
In 1.9 modders should NEVER, let me repeat NEVER use IInventory from vanilla directly. Use caps.
If we don't expose a entities inv via caps let us know, {we love PRs! ;) }

**Comment by williewillus** [comment]
side note: see #2614

**Comment by williewillus** [comment]
Can be closed since caps are now exposed on players
