### ISSUE TITLE
Suggestion: Add banner support to OreDictionary

### ISSUE THREAD

**Issue by FM22** [MinecraftForge/MinecraftForge#2596]
Any dyes mods add cannot be used to colour banners.

**Comment by FM22** [comment]
This patch does not fix it. To see why, I printed out the contents of `colored` and `dyes`. I got the following for `colored`:
> Black:
> 1xitem.dyePowder@0
> Red:
> 1xitem.dyePowder@1
> 1xitem.redCactusDye@0
> Green:
> 1xitem.dyePowder@2
> Brown:
> 1xitem.dyePowder@3
> Blue:
> 1xitem.dyePowder@4
> Purple:
> 1xitem.dyePowder@5
> Cyan:
> 1xitem.dyePowder@6
> LightGray:
> 1xitem.dyePowder@7
> Gray:
> 1xitem.dyePowder@8
> Pink:
> 1xitem.dyePowder@9
> Lime:
> 1xitem.dyePowder@10
> Yellow:
> 1xitem.dyePowder@11
> LightBlue:
> 1xitem.dyePowder@12
> Magenta:
> 1xitem.dyePowder@13
> Orange:
> 1xitem.dyePowder@14
> White:
> 1xitem.dyePowder@15
So it found the vanilla dyes and also my mod dye as expected.

However, the only element in `dyes` was:
> 1xitem.dyePowder@32767
So it could not find the dyes.

**Comment by diesieben07** [comment]
That is a special metadata value (constant in OreDictionary.WILDCARD_VALUE). It means "any metadata".

**Comment by FM22** [comment]
It still does not add item.redCactusDye@0.
