### ISSUE TITLE
Sounds/Cooldowns

### ISSUE THREAD

**Issue by Gamesaw-Drew** [MinecraftForge/MinecraftForge#2598]
I want to update my mod to 1.9, but I can't find a way to add sounds.

**Comment by williewillus** [comment]
See #2576

**Comment by Gamesaw-Drew** [comment]
Alright. Didn't really answer it for me. I just want a yes or no :P. But anyway I also would like to now if there is any way to add a cooldown for custom weapons? I cant find anything about it.

**Comment by williewillus** [comment]
It's an attribute, override getAttribyteModifiers

**Comment by Gamesaw-Drew** [comment]
Alright. Thanks!

**Comment by Gamesaw-Drew** [comment]
Do u have any examples anywhere? I'm still somewhat of a beginner and what I did, nothing happened. still used diamond swor dspeed

**Comment by williewillus** [comment]
Don't change issues around, if you need modder help come to #minecraftforge irc

**Comment by Gamesaw-Drew** [comment]
Alrigfht.

**Comment by Gamesaw-Drew** [comment]
The irc keeps kicking me and putting me into #RegisterYourNameMoron. it wont let me register it anywhere

**Comment by diesieben07** [comment]
If you cannot figure out how to register your nick then you fall into the exact category that this filter is supposed to keep out.

**Comment by Gamesaw-Drew** [comment]
How do I fall into a category they want to keep out? There is nothing there to register nickname. Not my fault

**Comment by diesieben07** [comment]
http://lmgtfy.com/?q=nickserv
