### ISSUE TITLE
[1.9] ItemInWorldManager was renamed

### ISSUE THREAD

**Issue by kenzierocks** [MinecraftForge/MinecraftForge#2600]
ItemInWorldManager was renamed to PlayerInteractionManager, and therefore [this patch](https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/server/management/ItemInWorldManager.java.patch) is not being applied. This prevents many features like the `RIGHT_CLICK_BLOCK` action of `PlayerInteractEvent` from working.

**Comment by LexManos** [comment]
We know, we are redesigning the player interact event because it is rewritten in 1.9
