### ISSUE TITLE
1.9 Black square behind hotbar

### ISSUE THREAD

**Issue by ThexXTURBOXx** [MinecraftForge/MinecraftForge#2603]
I don't know, if this is just a bug of my mod.
There is a black square behind the hotbar. If I take an Item in the left hand, then you can see the black square better. It even makes the corners of the offHand-Slot white.

**Comment by williewillus** [comment]
a screenshot would help...

**Comment by ThexXTURBOXx** [comment]
![2016-03-20_22 48 15](https://cloud.githubusercontent.com/assets/12763829/13907423/0cc7cdda-eeee-11e5-8ecc-9e777c16c656.png)
![2016-03-20_22 48 45](https://cloud.githubusercontent.com/assets/12763829/13907422/0cc711e2-eeee-11e5-9095-048c8532cfc8.png)
Of course... Sorry

**Comment by GirafiStudios** [comment]
Does this happen with only Forge installed and no mods?

**Comment by ThexXTURBOXx** [comment]
I will test that, the only mod installed is mine right now ^^

**Comment by ThexXTURBOXx** [comment]
Ok, tested it without mods installed (that means: Without my mod outside of ForgeGradle).
I can't see the bug there.
It seems to be either fault of my mod or of ForgeGradle.

**Comment by williewillus** [comment]
It's probably your mod then, come  to the irc chan and maybe we can help

**Comment by gigaherz** [comment]
Sounds like one of your renderers is leaving alpha blending disabled when MC expects it enabled. You may be missing a `GlStateManager.enableBlending()` somewhere.

**Comment by LexManos** [comment]
Closed until you are able to replicate in Forge alone as it's most likely a rendering issue with your mod. {See guys this is why direct GL access is bad!}
