### ISSUE TITLE
[1.9] Absent models for vanilla blocks

### ISSUE THREAD

**Issue by Wehttam664** [MinecraftForge/MinecraftForge#2611]
When launching the game through the gradle `runClient` task, a large number of models are completely missing, causing the items to render invisible (not with the purple/black grid).

Basically anything 3D is missing entirely, that being the block models in the inventory and anything held in hand.
**The Inventory**
![Missing Models](https://i.gyazo.com/a6da38db96bf20a499102c7f93e7035b.png "Missing Models")

Note how I have a sword selected and pickaxe off-hand and neither are rending. All of the block models are invisible, but I can place them just fine.

[Here's](http://pastebin.com/3Z98MpdS) the stack trace, even though there appears to be no errors other than the "Too many requests" thing at the end.
I'm running version `12.16.0.1776` for 1.9. This is in an Ubuntu 14.04 system.

**Comment by LexManos** [comment]
This sounds more like you're missing assets on your end.
It SHOULD show the missing model so im going to ping @RainWarrior on this one see what he has to say.
But I would suggest you try cleaning your assets folder and having FG re-download them.

**Comment by RainWarrior** [comment]
Please also post fml-client-latest.log

**Comment by Wehttam664** [comment]
Per request, [here](http://pastebin.com/CrwdiY5t) is the latest FML log if that helps.

**Comment by RainWarrior** [comment]
Closing due to #2666.
