### ISSUE TITLE
Dropping items causes a dupe

### ISSUE THREAD

**Issue by yrsegal** [MinecraftForge/MinecraftForge#2619]
Mods: PSIonic Upgrades (https://github.com/yrsegal/PSIonic-Upgrades), Psi, JEI

dropping items from the inventory spawns an entity that gives max(2, maxstacksize) of that item when picked up, and a ghost entity that can only be removed by a relog or by lava/similar.

**Comment by williewillus** [comment]
Issue about dupe items is itself a dupe ;)
See #2549, PR to fix is pending: #2593
