### ISSUE TITLE
[1.9] Crash rendering ModelDebugAnimation

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2628]
on latest master (March 22), was searching in creative and crashed with this

https://gist.github.com/anonymous/5fda1ac58d598a84bf24

**Comment by williewillus** [comment]
Actually crashes on the animation tesr's as well, same NPE.
Looking at the code, seems like the capability is never registered, leading CapabilityAnimation.ANIMATION_CAPABILITY to stay null.
@RainWarrior Did you forget to add everything to the commit again? ;P

**Comment by RainWarrior** [comment]
fixed in 1d608c6fe479fbdf7c2029b8f56e8d8425c4608f
