### ISSUE TITLE
[1.9] getOverrides (IBakedModel, ItemOverrideList)

### ISSUE THREAD

**Issue by tomevoll** [MinecraftForge/MinecraftForge#2631]
Can one of these be renamed, when implementing IBakedModel on a ItemOverrideList the functions collide having 2 different return types. 16.0.1797 was working on 1767

**Comment by LexManos** [comment]
These are MCP crowd named classes nothing to do with Forge.

**Comment by williewillus** [comment]
https://github.com/ModCoderPack/MCPBot-Issues/issues for mapping issues (though, @fry named both of them so he might change them if you get his attention haha)
