### ISSUE TITLE
[1.9] Out of place biomes

### ISSUE THREAD

**Issue by ezterry** [MinecraftForge/MinecraftForge#2632]
I've been noticing some occurrences of biomes appearing out of place (most noticeable is the deserts, but I've seen some others + what almost looks like biome blending inconsistency causing walls like this in other locations)

In the example shown when loaded in vanilla 1.9, the swamp continues to the extreme hills in the background, yet in forge the desert appears to be cutting the swamp literally in half.

<img src="https://cloud.githubusercontent.com/assets/395227/13962793/f903eb34-f038-11e5-963b-13d777414ac3.png" alt="forge 1.9 biome bug" width="250px">

Test case:
- seed: 5379835038257694226
- cords: 982,106,2038
- Process, create a new creative world with the seed and teleport to the cords
- Expectation in the middle of a swamp without any desert in sight
- Result: a swamp cut in half by a desert.
- Forge version(s) tested: 1.9-12.16.0.1795 and 1.9-12.16.0.1797 no additional mods used for these tests.

**Comment by iTitus** [comment]
Can reproduce: 
![2016-03-22_20 47 08](https://cloud.githubusercontent.com/assets/5154317/13965620/52c09a88-f06f-11e5-8876-df44fc30038e.png)

**Comment by cpw** [comment]
Does a dediserver have the same problem? I would guess so but it might be an idea to check.. Is the biome actually desert?

**Comment by Lanrik** [comment]
Confirm. Something very very bad with generator.
![be8f83a629 1](https://cloud.githubusercontent.com/assets/17798784/13972405/872b632c-f0a9-11e5-9a87-2fb4f5ecc598.jpg)

**Comment by LexManos** [comment]
Interesting, it popped up one 1/2 way through the patch updates, and then went away just assumed it was a 1/2 patch.
I'll look into it and see what I can do.
I suspect it has to do with a couple of patches that I re-wrote to be less... explody....

**Comment by ezterry** [comment]
Same thing with the dedicated server (thought so.. but double checked)

Running the same seed area side by side with vanilla in the screen shot, you can see it thinks its a desert, so does rain, and the biome generator even if I call it on those cords when not cached/generated and I'm at spawn.

![vanilla_vs_forge](https://cloud.githubusercontent.com/assets/395227/13972892/583d50b0-f073-11e5-8d8a-6cc25254e5ce.png)
 near them.
