### ISSUE TITLE
Parent Block States

### ISSUE THREAD

**Issue by SonarSonic** [MinecraftForge/MinecraftForge#2633]
Hello,

I've recently been getting to know the Forge Block State system and was wondering if it would be possible to have add a 'parent' block state. For example you can have a parent Block State for adding stairs you'd only have to assign textures and the models and everything would be taken from the parent. As I could find no Forge Block State version for it I made [one](https://gist.github.com/SonarSonic/8a57fb3a301fb3f8c9df), this may not be the best way to do it though. This would make life easier for those new to the system (myself included).

Thanks for all your work making 1.8 usable ;)
Ollie

**Comment by williewillus** [comment]
That's already possible... check out the defaults block.
Example: https://github.com/williewillus/Botania/blob/MC18/src/main/resources/assets/botania/blockstates/biomeStoneA0Stairs.json

**Comment by SonarSonic** [comment]
I mean inheriting variants as well, so to create some new stairs you'd end up with something like this.

https://gist.github.com/SonarSonic/8a57fb3a301fb3f8c9df#file-newstairs-json

**Comment by williewillus** [comment]
hm, interesting. maybe in the v2 format?

**Comment by SonarSonic** [comment]
Yeah, it would definitely save a lot of copying and pasting therefore reducing mod size and loading time. It would also allow modders to extend from other mods Block States meaning add-ons would be much easier.

**Comment by mezz** [comment]
Implementing Forestry's 29 wood variants of every type of item is painfully redundant without this.

**Comment by LexManos** [comment]
MultiModles and 1.9's semi-multi-model system should be a good enough solution for this.
I am kinda interested in seeing how the inhertance works because in theory all of the models and everything should be supported, and potentially you should be able to retexture it in your default block.
Worth asking @RainWarrior
