### ISSUE TITLE
Block/(Item?) Capabilities.

### ISSUE THREAD

**Issue by gjgfuj** [MinecraftForge/MinecraftForge#2644]
Basically: Allow for capabilities that are only logic based or ones that can be stored using purely blockstates to attach to Blocks.
basically: add `hasCapability(world,pos,side,cap)` and `getCapability(world,pos,side,cap)` to Block.

A use case is that I have a Lasers API that is currently broken up into two parts, a Block version and a Capability version, which could really just be one if Blocks had capabilities. Things that implement the API don't necessarily need to store any data, for instance the receptor implements the capability but then passes it on to the block in front of it, without touching it's data at all. I also have blocks that store all information necessary in their IBlockState, like the mirror which stores it's rotation data as a property.

Items were also discussed but they aren't really necessary as any item would always be in an ItemStack, which already keep capabilities. This is not the case for blocks, as blocks don't neccessarily have a tile entity, and have no method of having capabilities if they don't.

Preferably, this would also pass the method onto a TE's capabilities if it has any (and possibly vice versa?), to allow for things to only call the method on the block to retrieve any caps on the block.

I would write a PR but I am worried about messing it up and getting it wrong so I am providing an issue.

(We discussed this in #minecraftforge a week or two ago.)

**Comment by OvermindDL1** [comment]
Why do so many mods make half ECS systems when MC itself really just needs ECS baked in.  If only someone would write an ECS forge library...

**Comment by LexManos** [comment]
This has been thought about, and may happen. The IComponentProvider is designed to NOT have nbt serialization functions so it in theory could be applied to blocks. We just need to design how we want it to go.

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Feature]

**Comment by tterrag1098** [comment]
I would also have uses for caps on blocks. In fact, I think it would be worthwhile to convert some vanilla things (such as sustaining crops, rotation, etc.) to capabilities on blocks. I would be willing to do a PR on this if you have some more details on what you think it should look like.

**Comment by gjgfuj** [comment]
GetCapability and HasCapability methods on Block, that take a world, pos
parameter in addition to the regular thing.
Alternatively, a getCapabilityProvider method on Block which takes said
parameters and returns either the TE as ICapabilityProvider (if it is a
tile entity container) or can be overridden to return a custom one.
Either way, you would then use this method instead of reading components
directly from the TE, because it would allow for stateless components.

I'm leaning towards the 2nd personally now that I've written it, but what
do you think.

**Comment by LexManos** [comment]
The better option would be a getProvider(state, world, pos) ICapProvider.
That way we can treat everything normally.
Probably is having to have that intermediate step :/ And it could be A LOT of object churn, or well not to much if you just keep it a simple data class that bounces to a static class or something.

**Comment by gjgfuj** [comment]
Yeah, that idea is probably the best. I'd suggest that it default to the
TE's one when it's a TE, and deprecate the use of TE's methods directly.
(Because blocks may have any cap that TEs have.) If there's a TE, it's
unlikely for the block to need caps themselves.

**Comment by LexManos** [comment]
no

**Comment by JamiesWhiteShirt** [comment]
I believe this is still relevant.

**Comment by liach** [comment]
I don't think so. I think tile entities exist to carry data, especially when they can be non-tickable.
