### ISSUE TITLE
[1.9] [Suggestion] IBlockState argument for getParticleTexture

### ISSUE THREAD

**Issue by feldim2425** [MinecraftForge/MinecraftForge#2647]
If the Block State determines the texture of a block it would be nice if the getParticleTexture() method in the IBakedModel Interface has a IBlockState argument.

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by ShetiPhian** [comment]
Just ran into this issue myself.
With the old system, handleBlockState returned an IBakedModel, allowing the return of a model with the correct particles.
The new system uses the BakedQuads directly but provides no way to change the particles based on state.

After a quick look, it appears like it can be done as both SimpleBakedModel.Builder and BlockModelShapes.getTexture have the block state available. (might be other places needing patching, these are just the two that stood out after a quick search)

The only other option is to return the missing sprite and use the particle overrides in the block to spawn the correct ones.
