### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dokman** [MinecraftForge/MinecraftForge#2648]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 24/03/16 22:31
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access field net.minecraftforge.event.terraingen.PopulateChunkEvent.world from class com.shinoow.abyssalcraft.common.handlers.AbyssalCraftEventHooks
	at com.shinoow.abyssalcraft.common.handlers.AbyssalCraftEventHooks.populateChunk(AbyssalCraftEventHooks.java:72)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_8_AbyssalCraftEventHooks_populateChunk_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:551)
	at net.minecraft.world.gen.ChunkProviderOverworld.func_185931_b(ChunkProviderOverworld.java:389)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:996)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:979)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:175)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:96)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:295)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:172)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:195)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 527348024 bytes (502 MB) / 968589312 bytes (923 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.23 Powered by Forge 12.16.0.1805 Optifine OptiFine_1.9_HD_U_A5_pre 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1805-1.9.jar) 
	UCHIJAA	Forge{12.16.0.1805} [Minecraft Forge] (forge-1.9-12.16.0.1805-1.9.jar) 
	UCHIJAA	abyssalcraft{1.9.1-pre-1} [AbyssalCraft] (AbyssalCraft-1.9-1.9.1-pre-1.jar) 
	UCHIJAA	bdlib{1.11.0.8} [BD Lib] (bdlib-1.11.0.8-mc1.9.jar) 
	UCHIJAA	BloodMagic{1.9-2.0.0-22} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9-2.0.0-22.jar) 
	UCHIJAA	IronChest{6.0.129.773} [Iron Chest] (ironchest-1.9-6.0.129.773.jar) 
	UCHIJAA	planttech{1.3.0} [Planttech] (planttech-1.3.0 - 1.9.jar) 
	UCHIJAA	pressure{1.3.1.7} [Pressure Pipes] (pressure-1.3.1.7-mc1.9.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	List of loaded APIs: 
		* AbyssalCraftAPI|Block (1.6.5) from AbyssalCraft-1.9-1.9.1-pre-1.jar
		* AbyssalCraftAPI|Core (1.6.5) from AbyssalCraft-1.9-1.9.1-pre-1.jar
		* AbyssalCraftAPI|Disruption (1.6.5) from AbyssalCraft-1.9-1.9.1-pre-1.jar
		* AbyssalCraftAPI|Energy (1.6.5) from AbyssalCraft-1.9-1.9.1-pre-1.jar
		* AbyssalCraftAPI|Entity (1.6.5) from AbyssalCraft-1.9-1.9.1-pre-1.jar
		* AbyssalCraftAPI|Event (1.6.5) from AbyssalCraft-1.9-1.9.1-pre-1.jar
		* AbyssalCraftAPI|Integration (1.6.5) from AbyssalCraft-1.9-1.9.1-pre-1.jar
		* AbyssalCraftAPI|Internal (1.6.5) from AbyssalCraft-1.9-1.9.1-pre-1.jar
		* AbyssalCraftAPI|Item (1.6.5) from AbyssalCraft-1.9-1.9.1-pre-1.jar
		* AbyssalCraftAPI|Necronomicon (1.6.5) from AbyssalCraft-1.9-1.9.1-pre-1.jar
		* AbyssalCraftAPI|Recipe (1.6.5) from AbyssalCraft-1.9-1.9.1-pre-1.jar
		* AbyssalCraftAPI|Ritual (1.6.5) from AbyssalCraft-1.9-1.9.1-pre-1.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.9-2.0.0-22.jar
		* pressureAPI (1.3.1.7) from pressure-1.3.1.7-mc1.9.jar
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.9_HD_U_A5_pre
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: KUDA-Shaders v6.1.13 BETA - Ultra.zip
	OpenGlVersion: 4.5.13431 Compatibility Profile Context 16.150.2111.0
	OpenGlRenderer: AMD Radeon R9 200 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by GirafiStudios** [comment]
This is a crash with AbyssalCraft, not with Forge..

**Comment by Dokman** [comment]
yes but... i deleted every mod and when i put opticraft and another mod it crashses

**Comment by williewillus** [comment]
it's not a forge issue

**Comment by LexManos** [comment]
https://twitter.com/LexManos/status/713081449994276865?s=09
