### ISSUE TITLE
[1.8.9] Fly-kick in multiplayer

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#2654]
with forge 1808 the player is kicked in Multiplayer if falling for too lang (about 4 seconds). This happens if you jump from ~250 to 64 (on high ~90 you will be kicked) this is tested with forge version: 11.15.1.1764 and 11.15.1.1808.

No Mods where installed (and its not a Vanilla Bug, the Vanilla server dont kick you)

**Comment by OvermindDL1** [comment]
Have you enabled the allowing flying option in the server config?  That is a vanilla setting.  It will kick people if 'in the air too long' if not allowed.

**Comment by mcenderdragon** [comment]
Yes, it kicks you if you are for too long in the air without falling.  By default it is false. So Cheat CLients will be kicked by vanilla. But If i jump in vanilla from 255 in survival i will just land (and die if not water). But with forge i get kicked. So its a bug from forge. And it rely anoing if you jump down a high cliff and get kicket after 4 seconds

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by LexManos** [comment]
Verify it happens in the latest version i fixed the issue quite a while back.
