### ISSUE TITLE
[1.7.10] Random texture glitches in inventory

### ISSUE THREAD

**Issue by firecrafty** [MinecraftForge/MinecraftForge#2657]
In the recommended build for 1.7.10 (10.13.4.1558), there are strange texture glitches. Random items (the items affected change every launch) are textured weirdly. This is better shown by the images below
![screen shot 2016-03-26 at 7 38 22 pm](https://cloud.githubusercontent.com/assets/13878527/14063002/172ea1d4-f38c-11e5-9f80-56f66c76b775.png)
![screen shot 2016-03-26 at 7 36 02 pm](https://cloud.githubusercontent.com/assets/13878527/14063003/1c23a914-f38c-11e5-8f56-ae986d08a07e.png)
Also, the textures change every time. Sometimes they are speckled red green and blue with a clear or white background, and sometimes they are just clear. This happens on a clean installation of Forge (no mods installed in the mods directory) as well as in an installation of a development environment that I have installed.

I am running this on OS X 10.10.5 and Java 1.8.0_60 if this helps any.

**Comment by LexManos** [comment]
Disable the loading screen the osx drivers are dumb and deal with textures badly. Not a forge or mc issue. Purely a osx thing.

**Comment by firecrafty** [comment]
Thank you! Sorry about that. I figured it would be an OS X thing. Apple has issues

**Comment by ImpotentRage** [comment]
@LexManos how do you disable the loading screen?

**Comment by diesieben07** [comment]
Read the EAQ on the forums.
