### ISSUE TITLE
[1.9] Shrubs not generating in Jungles

### ISSUE THREAD

**Issue by TDWPFTW** [MinecraftForge/MinecraftForge#2663]
As the title says, the shrubs that generate on the floors of Jungles are not generating in 1.9 when using Forge (Vanilla works fine obviously).

![2016-03-28_10 43 29](https://cloud.githubusercontent.com/assets/1512908/14080284/0e1139bc-f4d2-11e5-9d91-8e34ec5a0d6a.png)

Tested on Forge 12.16.0.1811.

**Comment by Actuarius** [comment]
@Adubbz added labels [Bug]
