### ISSUE TITLE
[1.9] Block model completely missing

### ISSUE THREAD

**Issue by Wehttam664** [MinecraftForge/MinecraftForge#2666]
This is a follow-up on #2611 since it wasn't really solved and I have since learned a bit more about the problem.

I'm currently trying to work with Forge to create a mod, but simply cannot since *all* block models are completely invisible in the inventory, making adding blocks extremely difficult. This seems to be an issue with the `block/block` cube model and the way it renders.

**Building Blocks**
[![https://gyazo.com/558ebe15aebd214fc81d889d3433a4f1](https://i.gyazo.com/558ebe15aebd214fc81d889d3433a4f1.png)](https://gyazo.com/558ebe15aebd214fc81d889d3433a4f1)
This is what the *Building Blocks* creative tab looks like. The blocks are there and can be placed, but are invisible in the inventory. With an empty hand, the hand is visible, but the off-hand pickaxe is not.

**Decoration Items**
[![https://gyazo.com/9812614213566d61249788dab6c4f427](https://i.gyazo.com/9812614213566d61249788dab6c4f427.png)](https://gyazo.com/9812614213566d61249788dab6c4f427)
This is the *Decoration Items* tab. Items and blocks with non-cube models render fine while cube-based blocks are invisible. Note how here I am now holding a sword which is not visible, nor is the off-hand pickaxe.

[Here](http://pastebin.com/BWyVp6UB) is the console output of the IDE after deleting the `run` directory, creating a new world, then closing the game.
[Here](http://pastebin.com/dxiTnRPT) is the `fml-client-latest.log`.

I'm running in an Ubuntu 14.04 LTS Virtual Machine using FML `1.9-12.16.0.1811-1.9` in IntelliJ 15.0.4.

I have cleared the caches and deleted build/asset directories several times and have even tried disabling the mod, none of which seem to affect these invisible blocks. Any suggestions?

**Comment by chibill** [comment]
Try disabling the splash screen... Might be a bug like on OSX.

**Comment by Wehttam664** [comment]
I changed `splash.properties` to have `enabled=false`, but this has no affect on the invisible blocks.

It did greatly decrease load times, however. Interesting.

**Comment by iLexiconn** [comment]
I think this got fixed in the latest commit.

**Comment by Wehttam664** [comment]
Okay, so this issue has now infected my completely stock vanilla client, which is having the same issue.

I'm closing this issue since this is apparently not Forge's fault.

**Comment by williewillus** [comment]
Most likely graphics

**Comment by Wehttam664** [comment]
It seems to be an issue with the way VMWare handles 3D acceleration and graphics drivers, not Ubuntu's fault either.

For anyone else with the problem, bug them about it. I'll edit this if I find a fix.
