### ISSUE TITLE
[1.9] World Generation events

### ISSUE THREAD

**Issue by jtmnf** [MinecraftForge/MinecraftForge#2668]
Denying a a vanilla ore gen is simple because an event is generated (**OreGenEvent.GenerateMinable**), but for other mods that's not the case.

My question is: is there a way to implement a system where an event (maybe keeping the OreGenEvent.GenerateMinable) is fired, and, depending on the result, we can deny it if it is a, for example, event.getType() == Event.ORE? With this, the interface IWorldGenerator could changed to have an ArrayList<WorldGenMinable> that is filled, with the desired blocks for generation (or with something else that can handle the block information that is passed when the object WorldGenMiable is cretead), when the instance of the IWorldGenerator is created.

This is a simple idea that can allow more control on the world generation, and also merge the **vanilla and mods oregen in the same event** and category. For now, there isn't any event when a specific worldGenerator is running.

Thanks,
João Fernandes

**Comment by LexManos** [comment]
Mods can fire the oregen event themselves just fine.. and they should if the want to support customization. There is nothing extra needed by forge to make this happen.

**Comment by jtmnf** [comment]
Thanks for the answer LexManos. But having a getter in the WorldGenMinable class for the block might be useful if we want to make the WorldGen cleaner. In other words, if there are 2 copper ores, there is no way to distinguish amoung them, because the WorldGenMinable only let's me generate in a certain position in the world. But with the getter of the blocks, it will possible to make just one copper ore to spawn. 

Once again, thanks for the answer, it was very useful!
João Fernandes

**Comment by LexManos** [comment]
That should fall under the event type. And should be all you need. You *shouldn't* need to know the exact type of ore being generated.

When it comes to this situation you just exampled, it's not up to the modder to cancel the second oregen it's up to the user to configure his mods correctly for the gen he wants.

**Comment by jtmnf** [comment]
Thanks for the answer. I managed, thanks to your answers, to get something working (only because I didn't thought about firing the events).

João Fernandes
