### ISSUE TITLE
[1.9] Armour damaged twice when EntityPlayer attacked

### ISSUE THREAD

**Issue by WayofTime** [MinecraftForge/MinecraftForge#2670]
Forge version: 12.16.0.1813
I was playing around with ISpecialArmor today when attempting to have my armour damaged in a special way. However, even when I set it so that my armour should not be damaged at all by leaving the method damageArmor(EntityLivingBase, ItemStack, DamageSource, int, int) blank, the stacks were still being damaged. 

When digging through the Forge code I looked at EntityPlayer#damageEntity(DamageSource, float) and saw that at line 1154 it called applyArmorCalculations(DamageSource, float), but at line 1156 it also called net.minecraftforge.common.ISpecialArmor.ArmorProperties.applyArmor(EntityLivingBase, ItemStack[], DamageSource, float). applyArmorCalculations(DamageSource, float) calls damageArmor(float) at line 1345, which in the case of EntityPlayer damages all itemstacks regardless of armour type, whereas net.minecraftforge.common.ISpecialArmor.ArmorProperties.applyArmor() either calls damageArmor() on the ISpecialArmor if it is an instance of ISpecialArmor (line 148) or calls ItemStack#damageItem() if it is not.

From this it can be seen that Forge is either damaging the ItemStack twice if it is a normal piece of armour, or damaging it once when it is not supposed to when it is an ISpecialArmor. My suggestion is to possibly override the method applyArmorCalculations(DamageSource, float) in EntityPlayer so that it no longer calls damageArmor(DamageSource).

**Comment by LexManos** [comment]
Actually the proper solution is to nuke the call to that like we have in the past. Our applyArmor function does the same thing... albeit a bit more complex for the special armor, but the same thing.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]
