### ISSUE TITLE
[1.9] Edge case in Item.shouldCauseReequipAnimation leads to outdated firstperson model

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2672]
Reproduction explains it better:
1. Survival mode, 1 bow, 1 arrow
2. Fire the arrow a good distance away
3. Walk into the arrow, wait  until you've fully collected it, then fire. Everything should be normal
4. This time, hold your right click button down as you run into the arrow. You'll get something like:
http://imgur.com/U1RWi6V. (Interestingly, note that the inventory icon is fine)

My suspicion is that Item.shouldCauseReequipAnimation does this. In vanilla if you hold a bow down with no ammo it just plays the reequip animation over and over again annoyingly, which allows the model to immediately refresh.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by raoulvdberge** [comment]
Still having this bug on latest Forge (1826), see this gif: http://i.imgur.com/TEWgieF.gifv

**Comment by LexManos** [comment]
That's not a bug in Forge that's you derping the system up. We can add safeguards against it but that would screw up some legitimate usecases.
