### ISSUE TITLE
[1.9] OBJLoader doesn't recognize commands

### ISSUE THREAD

**Issue by Swingdude** [MinecraftForge/MinecraftForge#2673]
The title says it all. As you can see a t[http://imgur.com/a/EMQi2](url), the model looks vastly different in Blender (the program I use to make .objs) and Minecraft. When I run Minecraft, I get the following output from OBJ loader: http://pastebin.com/seA3YvUG. I know it is possible because it was done in 1.7 with Advanced Model Loader, I just wonder if it is possible in 1.9.
Just tell me if I've been missing something or if this isn't just me.
Thank you!

**Comment by RainWarrior** [comment]
add "custom": {"flip-v": true} to the blockstate json.

**Comment by shadekiller666** [comment]
Whenever the OBJLoader prints a "Command '<x>' is not supported, skipping" line in the console, it means that that "command" in the .obj/.mtl file is not processed by the OBJLoader, and can be removed from the file in question. This is normal, and will not have an effect on how the model renders in-game (as no data from unsupported commands is processed).

**Comment by Swingdude** [comment]
Ack. I thought it was an issue with forge, but it seems that I've forgotten something. 
I was thinking that the OBJLoader's inability to read those commands was the problem, but it seems just the line I forgot was the issue.
Sorry about opening an issue here.
