### ISSUE TITLE
""

### ISSUE THREAD

**Issue by SoniEx2** [MinecraftForge/MinecraftForge#2675]

**Comment by laci200270** [comment]
Look at #2264

**Comment by williewillus** [comment]
I already use it as such
Not sure what this is asking for other than a javadoc update :P

**Comment by SoniEx2** [comment]
Just a javadoc update. See #2456

**Comment by tterrag1098** [comment]
Is it a vanilla method? Then you can update the docs with MCPBot. Otherwise make a PR.

**Comment by williewillus** [comment]
It's the doc on ICapabilityProvider.has/getCapability
