### ISSUE TITLE
The "WTF" Loading Screen for Forge - [11.14.3.1450]

### ISSUE THREAD

**Issue by TappinBooty** [MinecraftForge/MinecraftForge#2676]
Alright, so I wanted to make my own ModPack for my Minecraft and so I did, got the right forge and the right mods to go with it. Keep in mind this is 1.8 forge --- so I load up Minecraft and this comes up
https://gyazo.com/af0cc51fd32044ffa13bbaf078df061e
uhh so yeahhh
I can provide I guess anything you want! 
Sincerely,
    Sameer

**Comment by LexManos** [comment]
This would be your really shitty graphics card not supporting threaded loading and as such you need to disable it in the splash.properties.
This is not a bug in Forge. You should not be coming here for support. Use the forums.
