### ISSUE TITLE
[1.9] BlockFluidBase is missing collision override

### ISSUE THREAD

**Issue by bonii-xx** [MinecraftForge/MinecraftForge#2680]
Liquid blocks have collision, so you can walk on them. Should probably be this piece of code:

```
public AxisAlignedBB getCollisionBoundingBox(IBlockState blockState, World worldIn, BlockPos pos)
{
  return NULL_AABB;
}
```

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Bug]

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Fluids]

**Comment by iLexiconn** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/cb7685a3b0448f389d9ad2069c2cbe2f14eaa069

**Comment by Actuarius** [comment]
@diesieben07 closed this issue

**Comment by iTitus** [comment]
The commit uses `getSelectedBoundingBox`, shouldn't it be `getCollisionBoundingBox `?
