### ISSUE TITLE
[1.9] Blocks disappear where old mod blocks used to be

### ISSUE THREAD

**Issue by ostenvighx** [MinecraftForge/MinecraftForge#2681]
Found with a world update and adding in the new command blocks (pulse, chain, etc).

I had chisel & bits blocks above command blocks to hold item frames up, and when updating, those blocks disappeared (because no C&B). I found that trying to place any block in a space where a mod block was (perhaps just related to C&B, not sure of the scope) and adding an item frame removes the block.

Saving and reloading the world removes the new block as well, which likely means the new block being placed isn't actually updating something?

I've tested it with bedrock, barriers, and stained glass. All the blocks disappear.

**Comment by LexManos** [comment]
Please provide more details, as these are the same situations in which we have tested and they work.
Placing ModBlock, Removing Mod, Placing new Block in same position. 
Works fine in testing.

**Comment by cpw** [comment]
Try latest forge as well, there's a couple of small bug fixes in this area that may make a difference.

**Comment by williewillus** [comment]
@ostenvighx does this still happen?

**Comment by ostenvighx** [comment]
@williewillus Seems to be fixed now. Placing a block there and updating it is working as intended.

**Comment by williewillus** [comment]
awesome, thanks!

**Comment by Actuarius** [comment]
@williewillus closed this issue
