### ISSUE TITLE
[1.9] Registered entities crash, freeze, or kick the layer from the game

### ISSUE THREAD

**Issue by Alex-the-666** [MinecraftForge/MinecraftForge#2682]
Hello. I've have a class which registers my entities here:
[code]
public class ModEntities {

	public static void registerSpawnable(Class entityClass, String name, int id, int mainColor, int subColor){
		EntityRegistry.registerModEntity(entityClass, name, id, IceAndFire.instance, 64, 1, true, mainColor, subColor);
	}
	public static void registerUnspawnable(Class entityClass, String name, int id){
		EntityRegistry.registerModEntity(entityClass, name, id, IceAndFire.instance, 64, 1, true);
	}
	
	public static void init() {
		registerUnspawnable(EntityDragonEgg.class, "dragonegg", 1);	
		registerUnspawnable(EntityDragonArrow.class, "dragonarrow", 2);	
		registerUnspawnable(EntityDragonSkull.class, "dragonskull", 3);	
		registerUnspawnable(EntityDragonFire.class, "dragonfire", 4);	
		registerSpawnable(EntityFireDragon.class, "firedragon", 5, 0X340000, 0XA52929);	
	}
}
[/code]

The only issue is that I get very lengthy crashes, such as:

http://pastebin.com/TmXcpRkU

Is anyone else getting these issues?

**Comment by LexManos** [comment]
Use the forums before posting errors to make sure you are indeed experiencing a Forge issue and not modder error.

**Comment by Alex-the-666** [comment]
Well i tried to make an account on your forums for a few hours but it wouldn't let me register.
