### ISSUE TITLE
[1.9] New Registry ignores keys

### ISSUE THREAD

**Issue by Vorquel** [MinecraftForge/MinecraftForge#2684]
The second argument of GameRegistry.register() does nothing, always taking the current registry name as a key.

**Comment by LexManos** [comment]
We'll take a look, however the second argument shouldn't exist.
It should be purely a name attached to the object.

**Comment by cpw** [comment]
Yeah, the object's registry name is used.

**Comment by cpw** [comment]
I'm going to make this method call setregistryname on the passed object, and add one that has no name if you're doing it elsewhere..

**Comment by cpw** [comment]
OK, there you go, I think that's the sanest way to do it. If you have an existing named object, use the one that doesn't take a name, if you have an unnamed object use the one that does.
