### ISSUE TITLE
/give command (and potentially other places) attempts to localize item names on the server

### ISSUE THREAD

**Issue by tterrag1098** [MinecraftForge/MinecraftForge#2688]
`Item.getItemStackDisplayName()` which is called by `ItemStack.getChatComponent()` uses `I18n`. `ItemStack.getChatComponent` should probably be using a `TextComponentTranslation` so that the chat component is localized once it reaches the server, as no mod localizations exist on the server. The effect is that all mod items show as unlocalized when using /give.

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Vanilla Bug]

**Comment by williewillus** [comment]
still valid

**Comment by mezz** [comment]
@williewillus please give a little more context or explanation when you bump a stale issue. I assume you looked at the code or saw the issue in a mod to verify this, so just a link to the relevant current code or a screenshot would be very helpful.
