### ISSUE TITLE
Invalid forge blockstate gives no output.

### ISSUE THREAD

**Issue by Wehttam664** [MinecraftForge/MinecraftForge#2689]
At the moment, when Forge attempts to load an invalid (either syntactically or logically) block state, there is absolutely no error to the console other than a complete spam of `MissingVariantException` stack traces.

While I can tell I've made a mistake in the JSON when my console is flooded, I have no idea where the mistake was made.

In short: Forge yields no output when (Forge?) block states are invalid, and this makes debugging extremely difficult as there are no comments in JSON. Can we get something that tells us what was done wrong?

**Comment by LexManos** [comment]
Define invalid, we scream as much as we can on invalid syntax's, but we can't do anything for invalid values.

**Comment by Wehttam664** [comment]
As in, there's no output if an extra or missing variant is defined other than the `MissingVariantException`. While annoying, it's acceptable assuming actual errors get their own exceptions, which they don't.

A syntax error, incorrectly defined entry, and missing variant all get the `MissingVariantException`, while only the latter really should, thus the name. At the least, they should get a different message than just "Missing variant for model"

If the file is missing all together, the exception's cause is a `FileNotFoundException`. Why can't the other errors get this?
