### ISSUE TITLE
Overprotective warning in new registry system

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2690]
I do `GameRegistry.register(this, new ResourceLocation(LibMisc.MOD_ID, name));` in my registration. On started, even though the modid is indeed mine, the game throws a ton of warnings in my face: 
"Dangerous alternative prefix botania for name enchantedSoil, invalid registry invocation/invalid name?"
at Impl.setRegistryName. For all of my blocks items and potions

Using no prefix in ResourceLocation (`new ResourceLocation(name)`) fails because then the ctor prepends the "minecraft" domain

**Comment by williewillus** [comment]
Ah, this is because Botania has the literal modid "Botania", and ResourceLocation auto lowercases the domain

**Comment by LexManos** [comment]
Yes, things are case sensitive in the registry, EVERYTHING should be lower case.

**Comment by williewillus** [comment]
Is there a possibility that the check that throws that warning be changed to a case-insensitive compare with the modid, or am I forced to change my modid? (I have no idea what that will implicate)

**Comment by LexManos** [comment]
it's advised you change your mod id because it's used in folder accesses in anything that has to do with ResourceLocations. And it's just better practice to be lower case.

**Comment by williewillus** [comment]
Kk
