### ISSUE TITLE
[1.9] Ctrl, Alt, and Shift Issue

### ISSUE THREAD

**Issue by LogicTechCorp** [MinecraftForge/MinecraftForge#2694]
There seems to be an issue with the Ctrl, Alt, and Shift keys. If you press a key/mouse button that performs an action and then hold Ctrl, Alt, or Shift and release the key/mouse button, it will cause the player to repeatedly perform the action until the action key/mouse button is pressed again. Possibly related to commit #2692

**Comment by willies952002** [comment]
I'm having the same issue with keys being stuck, but a slightly different behaviour when it comes to Ctrl, Alt, and Shift. they don't function one bit.

**Comment by Savvy0787** [comment]
Confirmed, same here ALT, SHIFT, and CTRL keys with mouse clicks

**Comment by covers1624** [comment]
@mezz  ^^

**Comment by mezz** [comment]
I'm aware and fixing it.

**Comment by covers1624** [comment]
ah, kay :)

**Comment by willies952002** [comment]
Confirmed fixed in 1831

**Comment by LexManos** [comment]
Check 1832 please. 1831 reverted his inital commit. 1832 added his 'fixed' one.

**Comment by mezz** [comment]
This should be completely resolved as of 1833.
