### ISSUE TITLE
[1.9] Syntax error in item model is never logged

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#2696]
This is similar to #2689, but for item models rather than blockstates JSONs.

When Forge tries to load an item model in `ModelLoader#loadItemModels` and an exception is thrown, it then tries to load the model specified by the blockstates JSON of the same name.

If this second model load throws an exception (e.g. `ModelBlockDefinition$MissingVariantException` because there is no blockstates JSON), the exception is stored and logged. The original exception is never stored or logged, even if it's caused by a syntax error rather than a `FileNotFoundException`.

**Comment by Actuarius** [comment]
@williewillus assigned @RainWarrior
