### ISSUE TITLE
[1.9] No proper way to inject localization.

### ISSUE THREAD

**Issue by Ordinastie** [MinecraftForge/MinecraftForge#2699]
With LanguageRegistry gone, there is no proper way to inject externally loaded lang files.
This is an issue for mods that rely on data that is not directly part of the mod.

**Comment by LexManos** [comment]
Why are you injecting external lang files? You could always load them as resource packs like vanilla does for everything. However it'd advised that you don't do anything pragmatically Forge takes care of everything related to languages automatically if you have the files in place.

**Comment by tterrag1098** [comment]
@LexManos Even loading it as a resourcepack requires some reflection. It's still a hack. I believe what @Ordinastie is referring to is loading files from i.e. the config folder.

**Comment by kashike** [comment]
The `injectLanguage` method wasn't deprecated, either: https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fml/common/registry/LanguageRegistry.java#L243
A simple method in `GameRegistry` would work, no?

**Comment by Ordinastie** [comment]
My use case is user provided block packs as zip, containing textures and lang files. Forge provides way to custom load the textures, but since LanguageRegistry.injectLanguage is no more, the only way is reflection to access both LanguageManager.currentLocale and Locale.loadLocaleData().

A GameRegistry method could indeed work, or an event fired from LanguageManager.onResourceManagerReload() passing the lang list and currentLocale (provided its relevant methods are made public).

**Comment by OrionDevelopment** [comment]
I would need this as well, my mod provides a flexible tutorial guide which automatically updates from Github. It downloads the correct translations, if available, and injected them into the LangReg. Afterwards it just translated them like a standard string and rendered them.

It would not be very feasible when I have to write my own custom LangReg, to make this possible.

**Comment by jaredlll08** [comment]
I was wondering what was happening to this, Minetweaker3 needs to inject the localization so that a user can set localization from it's script files.

**Comment by diesieben07** [comment]
This can all be accomplished by implementing `IResourcePack` and providing whatever InputStream you want for the localization files. Minecraft will then merge them all into one.

**Comment by LexManos** [comment]
Again, rather then hacking shit about, Treat things like resource packs.
No special casing or manual hacking into the registries needed.
We are NOT going to add a way for you to inject languages and translations in code. This defeats the entire point of the translation system and resource system.

I have my own opinons on some of your guy's mods but i'll leave it at this.
If you have 'dynamic' content like this you shouldn't. Downloading data like this is gateway to downloading other things that could be harmful to the end user without their knowledge.
