### ISSUE TITLE
onEntityColidedWithBlock

### ISSUE THREAD

**Issue by DiMuRie** [MinecraftForge/MinecraftForge#2713]
it is rly broken!I cannot get an effect with stepping on one of the multiple colisions on my block
plz make this happen!

**Comment by williewillus** [comment]
1. Use proper grammar. Please
2. It got renamed incorrectly in 1.8+. See https://github.com/ModCoderPack/MCPBot-Issues/issues/64

**Comment by Actuarius** [comment]
@williewillus closed this issue

**Comment by DiMuRie** [comment]
thanks,and sorry
