### ISSUE TITLE
[1.8.9] IFlexibleBakedModel still requires getItemCameraTransforms()

### ISSUE THREAD

**Issue by JakeStanger** [MinecraftForge/MinecraftForge#2715]
If an item implementing `IFlexibleBakedModel `is dropped onto the ground and becomes and `EntityItem`, the deprecated `getItemCameraTransforms` method is called and expects a return. The return type, `ItemCameraTransforms` is also deprecated.

This is using Forge 1.8.9 - 11.15.1.1722 (1.8.9 recommended build)

**Comment by RainWarrior** [comment]
You should be able to avoid deprecation warnings in 1.9.

**Comment by diesieben07** [comment]
@RainWarrior This still exist in 1.9:
In `RenderEntityItem#doRender`:
![image](https://cloud.githubusercontent.com/assets/1915984/14296747/d83e3ef6-fb7b-11e5-85b4-20a0c83695ee.png)
