### ISSUE TITLE
[1.9] Low enderman spawn

### ISSUE THREAD

**Issue by ThuCommix** [MinecraftForge/MinecraftForge#2716]
Hi I encountered a low enderman spawn at my enderman farm (with an endermite). In vanilla 1.9 I can't keep up with killing them but with forge forge-1.9-12.16.0.1833-1.9-universal they spawn very slow. Does forge limit spawn rates or is this a bug?

**Comment by LexManos** [comment]
We shouldn't be doing anything that would limit the amount spawned.
We do have a few hooks in that area to make the spawning more evenly spread out.
Perhaps you have space outside your farm where they are spawning and not being direct to you.
This is a case where we need A LOT more information then this anecdotal "Well it FEELS slower"

Your world for a start.
Perhaps a video with the debug info showing of both vanilla and Forge so we can better see what you're meaning.

**Comment by williewillus** [comment]
Closing from lack of response, follow up with a video or world dl or some numbers (entity counts) and we'll reopen

**Comment by Actuarius** [comment]
@williewillus closed this issue
