### ISSUE TITLE
[1.9] Pick block (Middle click) in creative menu isn't working

### ISSUE THREAD

**Issue by TDWPFTW** [MinecraftForge/MinecraftForge#2717]
Using the pick block button (Which defaults to middle click) on an item in the creative menu doesn't give a full stack in Forge 12.16.0.1846.

It seems like this was just broken within the past day or so, as it works on 12.16.0.1834.

**Comment by williewillus** [comment]
Keybinding PR? @mezz

**Comment by mezz** [comment]
Yeah, certainly from the key binding PR. I'll fix it when I get home.

**Comment by mezz** [comment]
This is fixed as of Forge 12.16.0.1849
