### ISSUE TITLE
[1.9] Armour calculation differs from Vanilla for EntityPlayer

### ISSUE THREAD

**Issue by WayofTime** [MinecraftForge/MinecraftForge#2720]
In 1.9 the calculations for the protection from armour has changed, and the changes required to implement the ISpecialArmor in EntityPlayer made it so that these changes to the armour are not respected. 

In protected void damageEntity(DamageSource damageSrc, float damageAmount) for EntityLivingBase, EntityLivingBase#applyArmorCalculations is called which uses the vanilla method for calculating the damage remaining. EntityPlayer instead uses net.minecraftforge.common.ISpecialArmor.ArmorProperties#applyArmor, which handles special armour but also treats vanilla armour as having a flat reduction. 

I won't go too deep into the details of why this is incorrect. What I suggest is that ISpecialArmor should be used to reduce the -remaining- damage after the vanilla armour calculations instead of representing that a piece of armour should absorb, say, 15% of the total damage. To do this, EntityPlayer should override EntityLivingBase#applyArmorCalculations(DamageSource, float) so that that method does not apply damage to the armour but remains functionally the same. (**EDIT:** We can also change the armour damaging so that it respects ISpecialArmor and remove the item damaging component from ISpecialArmor.ArmorProperties.applyArmor.) EntityPlayer#damageEntity(DamageSource, float) should then be changed to:

`damageAmount = net.minecraftforge.common.ForgeHooks.onLivingHurt(this, damageSrc, damageAmount);
            if (damageAmount <= 0) return;
            damageAmount = this.applyArmorCalculations(damageSrc, damageAmount);
            if (damageAmount <= 0) return;
            damageAmount = net.minecraftforge.common.ISpecialArmor.ArmorProperties.applyArmor(this, inventory.armorInventory, damageSrc, damageAmount);
            if (damageAmount <= 0) return;`

Basically inserting the vanilla armour calculations between posting the onLivingHurt event and the calculations for ISpecialArmor.ArmorProperties.applyArmor. Finally, ISpecialArmor.ArmorProperties.applyArmor() needs to be changed so that it does not factor in the damage reduction from the vanilla armour a second time, while still making sure that all pieces of armour can still be properly damaged. This may mean that the damageArmor method in EntityPlayer would need to be changed to respect ISpecialArmor - would probably be the easiest way, and would also fix #2463.

I don't trust myself with compiling a patch, so I don't think I will be able to compose the PR myself. I hope that I have put sufficient evidence for this issue and hope that it can be resolved with little issue! If you have further queries, let me know!

**Comment by LexManos** [comment]
Short answer, No because vanilla's mechanics don't distinguish between types of armors and screws with everything individually.
What SHOULD be done is to properly document the actual armor formula so that we can properly mimic it using our ISpecialArmor system which is what we've been doing in the past. Hacking in two systems by special casing each of them limits the ability of both. So we should replace the vanilla system with ours like we have been.
So, ya you should see if you can figure out and document the changed formula.

**Comment by WayofTime** [comment]
As requested, I'll document Vanilla's method for applying their armour reductions here. Then I'll submit my revised opinion about what needs to be changed. Because I assume that enchantments and potion reductions will stay the same (since they use the vanilla methods), I won't bother documenting those.

In EntityLivingBase, Vanilla applies the armour calculations by the method applyArmorCalculations(DamageSource, float). If the DamageSource is not isUnblockable(), all four pieces of armour will be damaged equally using EntityLivingBase#damageArmor(float). The damage passed into applyArmorCalculations will then be changed by CombatRules.func_188402_a(damage, (float)this.getTotalArmorValue());

this.getTotalArmorValue() gets the floored integer value for the armour, which is grabbed by this.getEntityAttribute(SharedMonsterAttributes.ARMOR); Each vanilla piece of armour sets their armour value as an AttributeModifier in ItemArmor (line 254), and this.getTotalArmorValue() simply looks at the attributes of the player's items and applied attributes (As a side note, potions in the future could conceivably add armor to the player, which is something that we need to be mindful of).

Back to the CombatRules. The function called calculates the damage after the armour by using this armour value and the incoming damage. The code (decoded) is as follows:

`float f = MathHelper.clamp_float(armor - damage / 2, armor / 5, 20);`
`float newDamage = damage * (1 - f / 25);`
`return newDamage;`

So vanilla code has a max possible armour value of 100, and using its method of EntityLivingBase#getTotalArmorValue() returns an integer. As seen, it scales the damage inflicted so that it is lower percentage-wise when you are hit with weak attacks compared to high-powered attacks. This is the end of the vanilla damage calculations for armour.

Now, for what I suggest, there are two options that I see personally - take these as you will.

**Option 1)** We make it so that ArmorProperties (which is returned by ISpecialArmor as the way to calculate percent damage mitigated) has a fourth parameter, so that it is instead: 

`public ArmorProperties(int priority, double ratio, double armor, int max)`

where "armor" would give the amount of armour this piece of equipment provides using the vanilla calculation, and "ratio" is used for flat percentage-reduction for any remaining damage. So we would make it so that we reduce the damage using the vanilla method of damage reduction based on the strength of the hit using the combined "armor" values while allowing the modder the option to still reduce the amount of damage by a static percentage. This would then change vanilla's armour so that it returns:

`prop = new ArmorProperties(0, 0, armor.damageReduceAmount, Integer.MAX_VALUE);`

The issue with this is that, depending on how it is implemented, this method would ignore the SharedMonsterAttributes.ARMOR that is added through other means from a modder, such as potions or held weapons. We could mitigate/eliminate this by still grabbing the value added by other means through getTotalArmorValue(), but we would need to make sure that the Vanilla armour does not have the ARMOR property when public Multimap<String, AttributeModifier> getItemAttributeModifiers(EntityEquipmentSlot equipmentSlot) is called. It would be up to the modder to make sure they do the same.

Calculations for the damage to the armour pieces itself might be a little finicky, especially since there would be two layers of deductions, but I imagine it would be easy enough to figure out - probably just based on the percentage that was blocked as it is currently modified slightly by a flat reduction if it applies armour protection through the vanilla method.

**Option 2)** This would be to leave ArmorProperties as it is and then leave adding the vanilla armour values up to the modder by implementing ItemArmor's public Multimap<String, AttributeModifier> getItemAttributeModifiers(EntityEquipmentSlot equipmentSlot), or similar. We would then need to still use vanilla's normal armour calculation at the beginning (as outlined in my original post) and then apply the ISpecialArmor's damage reductions on the remaining damage. ISpecialArmor's damage calculation would need to remove vanilla's contribution, because that would have already been contributed using (the overridden) this.applyArmorCalculations(damageSrc, damageAmount);.

This method would probably be easier to implement, but may be against the spirit of how we do things with Forge. It would still have the same effect, however, provided we properly damage the armour.

There are probably a few tweaks needed in my solutions. I think Option 1 gives the modder enough choice when implementing their own armour while respecting what Vanilla wants to do with their armour. In any event, I hope that I gave enough information on how vanilla handles damage reduction using armour to add your own implementation!

**Comment by TheOldOne822** [comment]
Actually I was referring to the use of generic.armor attribute to give armor custom armor values in vanilla. You can actually make a leather helmet in vanilla with generic.armor attribute set to 20 and it will protect as well as full diamond but with forge while that still holds true if a mod has that armor it provides normal leather helmet protection to the player.

**Comment by bs2609** [comment]
Is this resolved now by #3838?

**Comment by mezz** [comment]
Pretty much yes. Only https://github.com/MinecraftForge/MinecraftForge/issues/3933 needs to be resolved for it to match vanilla.
