### ISSUE TITLE
Chunk Rendering duplicates

### ISSUE THREAD

**Issue by sky0-1** [MinecraftForge/MinecraftForge#2722]
Using the latest version (1.9-12.16.0.1849-1.9), I loaded a new world in Creative and generated at least a few dozen chunks. I then exited the world and logged back in immediately. Instead of chunks rendering individually, each chunk flickered its rendering over all the others in turn.

Logging off and restarting client resolves this temporarily. Sometimes logging back in before restarting client does not cause the problem, but it always seems to happen when I load more than a few dozen chunks, save, and re-enter.
![2016-04-05_23 53 28](https://cloud.githubusercontent.com/assets/15920401/14307079/b69707f2-fb89-11e5-8076-6a62c5436903.png)
![2016-04-05_23 53 20](https://cloud.githubusercontent.com/assets/15920401/14307093/c933f1e0-fb89-11e5-9104-a84ee4498ac8.png)

**Comment by RainWarrior** [comment]
Looks almost exactly like https://bugs.mojang.com/browse/MC-62958
Do you have an AMD graphics card, and what driver version are you using?
![screenshot](https://bugs.mojang.com/secure/attachment/78780/2014-08-18_15.38.41.png)

**Comment by sky0-1** [comment]
Yes, using Windows 8 with graphics card AMD Radeon HD 7520G. Driver version 13.151.0.0, but I'm checking to see if there are updates available.

**Comment by robin4002** [comment]
This is the last driver for HD 7520G/Windows 8 : http://support.amd.com/fr-fr/download/desktop?os=Windows%208%20-%2064
If this driver don't resolve the problem, I think you should update to Windows 8.1 and use this newer driver : http://support.amd.com/fr-fr/download/desktop/legacy?product=legacy3&os=Windows%208.1%20-%2064

> I assume since this is a client issue, my mod will not corrupt other clients if I continue using this graphics card, correct?

Yes.

**Comment by LexManos** [comment]
Not a Forge issue, and not really fixable by us.
