### ISSUE TITLE
DimensionManager doesn't support multiple servers

### ISSUE THREAD

**Issue by immibis** [MinecraftForge/MinecraftForge#2725]
In 1.9 it appears Mojang are preparing to have multiple MinecraftServer instances in the same process.

DimensionManager is still static, not per-server - so there's no provision for separate servers having separate worlds in Forge. (It looks like vanilla would handle it fine)

DimensionManager's methods and fields shouldn't be static, and each MinecraftServer should have its own DimensionManager.

This cannot be fixed without breaking the API, and it will break a *lot* of mods, so it needs to be done while Forge in 1.9 is still unstable. I could submit a PR this weekend.

**Comment by immibis** [comment]
... you know what, FMLServerHandler also assumes there's only one server, and that can't be fixed without rewriting a lot of Forge. Darn.

**Comment by gigaherz** [comment]
If that's the case, since 1.9 still does not make use of that as it is, it may be best to prepare such a breaking change for 1.10 instead?

**Comment by immibis** [comment]
@LexManos No explanation for closure, besides what @gigaherz said above?
