### ISSUE TITLE
[1.9] ItemStacks are merged ignoring Capabilities

### ISSUE THREAD

**Issue by kanomiya** [MinecraftForge/MinecraftForge#2726]
Container checks ItemStack's 'Item', 'Metadata', 'Tag', but doesn't check 'Capabilities'.

This code is at Container#canAddItemToSlot(Slot, ItemStack, boolean), and Container#func_184997_a(ItemStack, ItemStack).

And also, ItemStack#isItemStackEqual(ItemStack) ignores 'Capabilities'.

These may cause to lose capabilities in ItemStack merging(putting two different ItemStacks instance together).

Container: net.minecraft.inventory.Container
ItemStack: net.minecraft.item.ItemStack

**Comment by asiekierka** [comment]
This is a serious problem for any kind of serious capability adoption in mass contexts in ItemStacks.
