### ISSUE TITLE
[1.9] cannot add drop within HarvestDropsEvent handler

### ISSUE THREAD

**Issue by Torgas** [MinecraftForge/MinecraftForge#2727]
Recent public/private refactoring removed possibility to alter drop while handling HarvestDropsEvent . Leaving drops variable as private without any set/add method.

Can we have at least addDrop() method to add item on the drop list?

Problem seems to be introduced by [this change](https://github.com/MinecraftForge/MinecraftForge/commit/756c58d5cb01ed33e9bbc165ab62cc62244d6bb1#diff-3168eef80c674ad5e4c39fe89d628362)

**Comment by blay09** [comment]
You can still do all the things you could before:

event.getDrops().clear(); to clear the drops
event.getDrops().add(whatever); to add a drop
