### ISSUE TITLE
Can't use item model with ForgeBlockStateLoader

### ISSUE THREAD

**Issue by CrafterKina** [MinecraftForge/MinecraftForge#2732]
Forge set prefix "block/" to "model" location.
So we can not set item model to parent model.
For example, torch json rewrite in forge syntax:

``` json
{
  "forge_marker": 1,
  "defaults":{},
  "variants": {
    "normal": {
      "model": "torch",
      "textures": {
        "torch": "blocks/torch_on"
      }
    },
    "inventory": {
      "model": "item/generated",
      "textures": {
        "layer0": "blocks/torch_on"
      },
      "transform": "forge:default-item"
    }
  }
}
```

but parent model of inventory become "block/item/generated".(and it is wrong path)

**Comment by williewillus** [comment]
I believe this is to preserve compat with the vanilla blockstate format (which assumes everything under models/block) but changing it would be nice, maybe in v2 format?

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]

**Comment by KnightMiner** [comment]
Is this still relevant since we have `forge:item-layer`? People could also just create a model under `models/block` with parent set to the item model for other cases.
