### ISSUE TITLE
NullPointerException: Unexpected error (1.7.10)

### ISSUE THREAD

**Issue by lightning02** [MinecraftForge/MinecraftForge#2735]
http://pastebin.com/14MhTTz8

hello guys, I've looked around on Google first but I am at a standstill actually, the problem is kinda this;
When I play on a custom modpack server it happens that sometime my client crash apparently with no reason, then, when I try to join again in the overworld I just crash again and can't join that world anymore (except if I manually delete my position). Now, you'll say "it's a rendering issue, ther's something in the chunk that make you crash", but, the problem is that other people may tp at my location while I try to log in and they are just fine, the issue seems not related with the chunk itself. Again, the problem is that this could once happen to me, but another time can happen to  others as well, then I can exclude an hardware problem.
I would exclude the entity render then and may focus on the "Item Render" part, but the problem is: .ItemRenderer.func_78446_a  .... (Unknown Source)  .. yeah, unknow source..
We also tryed to identify a single mod causing this, but is not a single mod, seems more like an interaction of mods or a forge problem itself?
If we exclude a mod from the modpack, after the "/fml confirm" for the server world, people that had this issue become able to log in again, but this happen always, no matter what mod we cut off.
So we can't figure out what the problem is related with.. (even tryed to put out optifine just let you know).
Any idea how to identify the source of the problem?

http://pastebin.com/FL7JEXWb

**Comment by LexManos** [comment]
1.7.10? REALLY!?!?!?
