### ISSUE TITLE
dont know if bug in system or what.. please let me know

### ISSUE THREAD

**Issue by Prophious** [MinecraftForge/MinecraftForge#2739]
every time i create a new map it stalls displaying the "0%" in the middle of the screen, now the issue seems to happen with all the mods  i have ready... and as i remove some it still happens... so i dont know what to do

http://pastebin.com/gs3QL5h6

even if this is not a forge issue please let me know what it could be

**Comment by SteveKunG** [comment]
Not the Forge issue. It's Minecraft screen bug fix.

**Comment by Prophious** [comment]
how to fix?

**Comment by williewillus** [comment]
@SteveKunG according to the log, it is forge's Comparator that is breaking

**Comment by Prophious** [comment]
i have gotten the same thing from 1816... only recently tried again to start a new map.... with results shown above

**Comment by LexManos** [comment]
Not the place, use the forums.
