### ISSUE TITLE
IItemHandler needs a public slot limit method in order to support comparators

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2740]
cc @rwtema - in case you had a rationale for not including this

This is a request for the modification of the public interface of IItemHandler to have some sort of "get slot limit" method like what is on IInventory.

Why?
- This is _necessary_ for any inventory that wants to support comparators. Comparators are implemented by dividing the current stack size by min(item's max stack size, inv.slotlimit(slot)).
  It is impossible to implement the vanilla comparator formula for IItemHandler at the moment because although ItemStackHandler has such a method, it is protected and not part of the interface.

Where?
- Add getSlotLimit(int, ItemStack): int to the IItemHandler interface. Retrofit ItemStackHandler.getStackLimit.

Implications?
- 1.9 only since we are still in the breaking changes phase

If this gets a nod, I will proceed with a PR

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by gigaherz** [comment]
This may be the appropriate time to propose an IComparatorLevelProvider interface of sorts, that has a "getComparatorLevel" provided by the implementation, so that comparing non-inventories is also possible?

**Comment by diesieben07** [comment]
Uhm, `Block.getComparatorInputOverride`?

**Comment by gigaherz** [comment]
Ah I wasn't aware of that. Nevermind, then.

**Comment by Actuarius** [comment]
@williewillus added labels [Superseded]

**Comment by williewillus** [comment]
#3445
