### ISSUE TITLE
[1.9] FluidRegistry.lookupFluidForBlock not getting the correct value on flowing vanilla fluid blocks

### ISSUE THREAD

**Issue by sham1** [MinecraftForge/MinecraftForge#2741]
I noticed a bug with FluidRegistry's lookupFluidForBlock, that made it so that if you have either a flowing lava or water block, it would return `null` instead of `FluidRegistry.LAVA` and `FluidRegistry.WATER` respectively.

![Lava](http://i.imgur.com/i7OQ5Cu.png)
![Water](http://i.imgur.com/YukV1cd.png)

How to reproduce
==============

To reproduce, you must pass either `Blocks.flowing_lava` or `Blocks_flowing_water` into `FluidRegistry.lookupFluidForBlock`.
I have not verified this bug with custom fluids.

Tested with the latest Forge for 1.9.

**Comment by LexManos** [comment]
Not seeing how this is a bug. This is specifically designed for how the Fluid registry works.
The function you're using looks up source blocks.
Not to mention the fact that Flowing water/lava don't have a amount value because they are not consumable fluids.
