### ISSUE TITLE
[1.9] Hand-specific render event

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2747]
Current RenderHandEvent cancels rendering for both hands completely, This is a request for a more lowerlevel/granular subevent that is hand sensitive and can be be canceled per-hand

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by killjoy1221** [comment]
We could possibly add some fields to the current event. side (`EnumHandSide`) and type (`EnumHand`). We could do logic with that.
