### ISSUE TITLE
Mod packets are handled off the main thread

### ISSUE THREAD

**Issue by immibis** [MinecraftForge/MinecraftForge#2752]
In Forge 12.16.0.1816, SimpleNetworkWrapper IMessageHandlers are run on the Netty thread that received the message, not on the main client thread. The behaviour likely also exists for client-to-server packets, but this wasn't tested.

This behaviour is not documented on SimpleNetworkWrapper, which seems to be the main interface to the networking system. (It might be documented somewhere internally, in a place mod developers are not likely to see)

**Comment by FRedEnergy** [comment]
It's described on Forge's Read the Docs - [SimpleImpl#Making Packets](http://mcforge.readthedocs.org/en/latest/networking/simpleimpl/#making-packets)
But probably should be moved to javadoc

**Comment by williewillus** [comment]
Common knowledge for 1.8+
But sure should be in javadoc

**Comment by Actuarius** [comment]
@diesieben07 added labels [Cleanup]
