### ISSUE TITLE
Register a Block don't register a ItemBlock

### ISSUE THREAD

**Issue by canitzp** [MinecraftForge/MinecraftForge#2755]
Since I updated my Mod to the newest Forge Version I get a Error while registering my Models. I find out that Item.getItemFromBlock does return null, because GameRegistry.register(MyBlock) don't create a ItemBlock. After I manually registering a ItemBlock all things are working.
Forge: 1863

**Comment by blay09** [comment]
It's documented as such in the register() method, you need to register it manually now. Have a look at the deprecated registerBlock() method:

`GameRegistry.register(new ItemBlock(block).setRegistryName(block.getRegistryName()));`

**Comment by canitzp** [comment]
If it is normal than okay
