### ISSUE TITLE
LootEntry.Serializer doesn't distinguish between items and loot tables

### ISSUE THREAD

**Issue by dustine** [MinecraftForge/MinecraftForge#2757]
On `net.minecraft.world.storage.loot.LootEntry.Serializer`, starting on line 92, we have this:

```
if (p_serialize_1_ instanceof LootEntryItem) {
    jsonobject.addProperty("type", "item");
}
else if (p_serialize_1_ instanceof LootEntryTable) {
    jsonobject.addProperty("type", "item");
}
```

The problem here being that, both for `LootEntryItem` and `LootEntryTable`, they're added as `"item"` onto the JSON object, which isn't what the [vanilla specification](http://minecraft.gamepedia.com/Loot_table#Tags) says it should be (`LootEntryTable` should be `"loot_table"` instead).

I figured the loot table aspect for 1.9 Forge is still very on the process of being worked on, so why I submitted this only as a Issue and not a Pull request. Thank you for your time. :bow:

**Comment by Actuarius** [comment]
@williewillus added labels [Vanilla Bug]
