### ISSUE TITLE
Incorrect handling of worldborder and portal-transfer to outside of border

### ISSUE THREAD

**Issue by theboomer** [MinecraftForge/MinecraftForge#2759]
Version: forge-1.8.9-11.15.1.1808-universal
Have done exhaustive testing comparing forge, forgesponge, spongevanilla, and vanilla minecraft server.

In vanilla and sp-vanilla servers:
1) The worldborder can be set both smaller and larger than the server.properties border value, while in Forge it will SAY that the border has been increased using /worldborder get, such as from ie 6000 to 9000, but the borderwalls do not change their location to the larger perimeter.  They do move and change if the border is set smaller, and report so in the /worldborder get, but again, are only pushed back out again to their original loaded position if the border is set larger beyond the initial position.

2) In vanilla and sp-vanilla servers, if a player builds a portal near a mainworld border, goes to the nether, goes further out straight in the direction of the border, builds a portal that should return them hundreds of blocks beyond the border and returns to the main world through it, they are redirected to the same gate they first went in, WITHIN the borderwalls.  Destroy the original gate while they are in the nether, and the main world will build the exit portal WITHIN.  Go to the opposite side of the map, or on and angle somewhere away such that the gate would return them outside of the worldborder, and the nethergate is built WITHIN the confines of the border walls, at the nearest closest construction point within the border walls.
In FORGE, (and subsequently spongeforge), if a player builds a netherportal that should take him outside the border walls when he enters it, one of two things happen: A) If he his in creative mode, regardless of op-status, the portal will spawn outside of the border and he can move around but of course, not break or build anything, and take no damage.  B) If he is in survival mode, regardless of op-status, the portal will spawn outside of the border, he will see the flash of purple-tinted world usually, and immediately dies of suffocation without having several rounds of damage first.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by williewillus** [comment]
is the 1st problem a problem only in forge? what happens in vanilla?

**Comment by theboomer** [comment]
This was a bug I reported a year and a half ago while testing sponge, to determine if it was a vanilla, spongeforge, spongevanilla or forge issue for completeness, and since it happened in forge independant of sponge, I was instructed to post here.   
I don't use forge and have no idea if the issue is still a problem that exists or not, but I can assure you, if it was something that happened in mojang vanilla, or was caused by sponge, I would not have reported it here.

**Comment by williewillus** [comment]
cool, just making sure since I have a PR that fixes the second half and was wondering if the first half was still valid
