### ISSUE TITLE
Extrapolate BlockPos into an interface?

### ISSUE THREAD

**Issue by MrTJP** [MinecraftForge/MinecraftForge#2764]
Not sure if this would be possible or not, don't know how its set up internally. But if BlockPos can be pulled out into an interface (with the one provided being a default implementation) modders can pass in their own positional class to many of the methods, avoiding the many instantiations of BlockPos simply to call methods.

**Comment by AEnterprise** [comment]
technicaly it's possible but that's all, it would require patching ALL functions that use it, breaking all mods that override it, breaking binary compatibility and more

also you can just extend blockpos, use your extended version and cast it to blockpos when passing it to a function that needs it

**Comment by amadornes** [comment]
BlockPos isn't final so you should be able to extend it very easily. There's also MutableBlockPos, which you can modify if you're doing repetitive tasks which would need the instantiation of a new BlockPos every time they run.
Plus, changing the references to it in all the vanilla classes (and all the modders' implementations) could be quite painful. If this ever happened, it'd probably be when moving to 1.10.

**Comment by MrTJP** [comment]
Yea, that was my thought as well. I could just override everything. This change to using BlockPos everywhere adds more problems than it solves, wrong move in my opinion.

**Comment by diesieben07** [comment]
The biggest problem with this is that `BlockPos` has a contract of being immutable. `MutableBlockPos` already caused quite some problems by violating that contract. So: Please don't.

**Comment by covers1624** [comment]
@MrTJP CCL has a BlockCoord lib and methods to got from and to
BlockPos. 

----- Original Message -----
