### ISSUE TITLE
Cooldown overlay is opaque if the itemstack has a damage bar

### ISSUE THREAD

**Issue by bonii-xx** [MinecraftForge/MinecraftForge#2772]
If a cooldown is added to an item by using the players CooldownTracker, the cooldown overlay is completely white instead of halftransparent. In the screenshot below, the item in the offhand slot has a damage bar displayed, while the one in the hotbar does not. You see the difference in rendering.
Offhand/mainhand does not have an influence, just for display purposes in the screenshot.
![2016-04-17_19 15 37](https://cloud.githubusercontent.com/assets/722449/14588766/baabfe96-04d1-11e6-859c-146ad00fb58e.png)

**Comment by williewillus** [comment]
For some context, in vanilla it shows up opaque, but it looks really, really ugly
I think it's actually supposed to be transparent

**Comment by yrsegal** [comment]
This is because the durability bar disables blend, and the cooldown renderer doesn't enable it, so leakage. (RenderItem#renderItemOverlayIntoGUI)

**Comment by williewillus** [comment]
I mean it's opaque all the time in vanilla

**Comment by williewillus** [comment]
So the decision is "Is vanilla wrong"?
Because opaque looks really, really, really ugly .-.

**Comment by yrsegal** [comment]
Wait, it's opaque in vanilla? Ew ew ew ew ew...

**Comment by yrsegal** [comment]
No it isn't, the enderpearl looks perfectly fine when thrown.

**Comment by williewillus** [comment]
Yes it is

**Comment by williewillus** [comment]
It's transparent in forge

**Comment by williewillus** [comment]
http://imgur.com/w2KZrc6

**Comment by yrsegal** [comment]
![2016-04-29_18 20 41](https://cloud.githubusercontent.com/assets/6596492/14931146/286cb2a4-0e37-11e6-8dee-4ceeef063e47.png)

**Comment by williewillus** [comment]
uh what mod is coloring all the text red?

**Comment by yrsegal** [comment]
that's an RP for command blocks. this is vanilla.

**Comment by williewillus** [comment]
welp
I don't know why it works in forge for me then

**Comment by yrsegal** [comment]
if they have a count, it opaques as well.

**Comment by yrsegal** [comment]
that's the difference between us. This is a clear case of "vanilla-is-wrong"

**Comment by williewillus** [comment]
So the title of this ticket should be changed to "Cooldown overlay is opaque if the itemstack has a damage bar or stack count" and it is a vanilla bug

**Comment by yrsegal** [comment]
Yeah, but one easy to fix x3

**Comment by Actuarius** [comment]
@williewillus added labels [Vanilla Bug]
