### ISSUE TITLE
[1.9] Block.getLightValue gets called with adjacent positions

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2773]
When digging a block A in survival with adjacent block B, A.getLightValue gets called with an incorrect position. 
The method takes a world, pos, and state. The state will always be correct, but the position occasionally is that of an adjacent block, e.g. A.getLightValue(world, B's pos, A's state)
Besides not making any sense, this interferes with TE checks for light level.

Note that this ONLY happens when digging in survival

**Comment by LexManos** [comment]
In cases like this give us a stack trace, much easier to dissect in case there are multiple call paths.

**Comment by williewillus** [comment]
The actual Block A is at {356 4 426}

http://pastebin.com/dPG6p5Fz


I've placed different blocks around "Block A": bedrock, sand, glass, stone. Grass is below, air is above.
It seems that this mistake only occurs with the pos offsetting north and west

**Comment by williewillus** [comment]
Forgot to mention, 1.9 only
Probably some missed patch or change somewhere, but I can't seem to pin it down

**Comment by williewillus** [comment]
It also happens when the pipeline is off, and gives a different stacktrace. 

Stacktrace when pipeline is off: http://pastebin.com/dKzUV90y

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by williewillus** [comment]
I tracked it down for the case where the pipeline is off:

In BlockModelRenderer.updateVertexBrightness there's this code

```Java
BlockPos.PooledMutableBlockPos blockpos$pooledmutableblockpos1 = BlockPos.PooledMutableBlockPos.retain(blockpos).offsetMutable(blockmodelrenderer$enumneighborinfo.corners[0]);
BlockPos.PooledMutableBlockPos blockpos$pooledmutableblockpos2 = BlockPos.PooledMutableBlockPos.retain(blockpos).offsetMutable(blockmodelrenderer$enumneighborinfo.corners[1]);
BlockPos.PooledMutableBlockPos blockpos$pooledmutableblockpos3 = BlockPos.PooledMutableBlockPos.retain(blockpos).offsetMutable(blockmodelrenderer$enumneighborinfo.corners[2]);
BlockPos.PooledMutableBlockPos blockpos$pooledmutableblockpos4 = BlockPos.PooledMutableBlockPos.retain(blockpos).offsetMutable(blockmodelrenderer$enumneighborinfo.corners[3]);
int i = state.getPackedLightmapCoords(worldIn, blockpos$pooledmutableblockpos1);
int j = state.getPackedLightmapCoords(worldIn, blockpos$pooledmutableblockpos2);
int k = state.getPackedLightmapCoords(worldIn, blockpos$pooledmutableblockpos3);
int l = state.getPackedLightmapCoords(worldIn, blockpos$pooledmutableblockpos4);
```

as you can see, the pos is being shifted around, but then getPackedLightmapCoords is called on the original state (block at the unshifted pos), which means the block receives a pos that it itself is not placed in.

**Comment by williewillus** [comment]
Similar thing happens for the pipeline in VertexLighterFlat.updateLightmap

**Comment by RainWarrior** [comment]
I don't see a clean way to make getLightValue always have the correct state, and default implementation of Block.getLightValue(state, world, pos) already does that check, so you need to fix your override.

**Comment by williewillus** [comment]
I'll go with this but one of the biggest assumed invariants is that the coords are valid, besides calling blocks to ask for the light value of a DIFFERENT block makes no sense :/

At the very least Javadoc needs to get a humongous warning on top stating that that assumption doesn't hold

**Comment by williewillus** [comment]
On a different note, how didn't this happen in 1.8?

**Comment by diesieben07** [comment]
Well, if the default implementation is to be trusted, you are supposed to check with the world first and then delegate to a potential other Block.
But if that is so, then why does the callee of `getLightValue` not ensure this?
The argument fry made on IRC ("this is called from a different thread, there is no way to ensure this") is not something I buy, just because vanilla does stupid stuff like this (call the world from rendering threads) doesn't mean we (=forge) have to do it.

**Comment by williewillus** [comment]
It's not even a threading problem, it's just incorrect via the code i posted above

**Comment by williewillus** [comment]
Another "how" is how this only happens when survival digging

**Comment by diesieben07** [comment]
That's not really true. `getPackedLightmapCoords` (which calls `getLightValue`) is called from within the rendering thread.

**Comment by williewillus** [comment]
I meant, that the fact that it's threaded isn't the main contributor to this problem, it's that the pos is intentionally shifted around but methods are still called on the same state.

This works for vanilla because getLightValue is only state aware in vanilla
but we patch getPackedLightmapCoords to use Forge getLightValue which is pos aware and should have the right pos
The idea that it *sometimes wouldn't* is silly to me

**Comment by williewillus** [comment]
Further reinforcing it's safe to use the world in BlockModelRenderer.updateVertexBrightness:

Right below the end of that snippet I posted above, it calls the world to get translucency and AO.

Full snippet from pipeline off:

```Java
// ?????? why do these not use the world?
int i = state.getPackedLightmapCoords(worldIn, blockpos$pooledmutableblockpos1);
int j = state.getPackedLightmapCoords(worldIn, blockpos$pooledmutableblockpos2);
int k = state.getPackedLightmapCoords(worldIn, blockpos$pooledmutableblockpos3);
int l = state.getPackedLightmapCoords(worldIn, blockpos$pooledmutableblockpos4);
float f = worldIn.getBlockState(blockpos$pooledmutableblockpos1).getAmbientOcclusionLightValue();
float f1 = worldIn.getBlockState(blockpos$pooledmutableblockpos2).getAmbientOcclusionLightValue();
float f2 = worldIn.getBlockState(blockpos$pooledmutableblockpos3).getAmbientOcclusionLightValue();
float f3 = worldIn.getBlockState(blockpos$pooledmutableblockpos4).getAmbientOcclusionLightValue();
boolean flag = worldIn.getBlockState(blockpos$pooledmutableblockpos.set(blockpos$pooledmutableblockpos1).offsetMutable(direction)).isTranslucent();
boolean flag1 = worldIn.getBlockState(blockpos$pooledmutableblockpos.set(blockpos$pooledmutableblockpos2).offsetMutable(direction)).isTranslucent();
boolean flag2 = worldIn.getBlockState(blockpos$pooledmutableblockpos.set(blockpos$pooledmutableblockpos3).offsetMutable(direction)).isTranslucent();
boolean flag3 = worldIn.getBlockState(blockpos$pooledmutableblockpos.set(blockpos$pooledmutableblockpos4).offsetMutable(direction)).isTranslucent();
```

**Comment by RainWarrior** [comment]
The problem is the change inside getPackedLightmapCoords; vanilla calls position-unaware getLightValue there (always on the original block state), forge needs to call the position-aware version, but the position passed is the shifted one; ideally, fluids and slabs should DIAF, and getPackedLightmapCoords should move to the World, but I doubt we'll get there soon.

**Comment by bs2609** [comment]
Coming here from #4199, so excuse the delay.

In response to fry's last comment here:

As a possible solution, would calling `getPackedLightmapCoords` on the original state with the original pos, but passing a wrapped `IBlockAccess` which maps calls to `getCombinedLight()` to the correct offset position work?
