### ISSUE TITLE
Expand problems

### ISSUE THREAD

**Issue by DiMuRie** [MinecraftForge/MinecraftForge#2776]
If you write this in your te update method:
List<Entity> interestingItems = worldObj.getEntitiesWithinAABB(Entity.class, Elevator.FULL_BLOCK_AABB.expand(3, 3, 3));
It only gets the entity in "FULL_BLOCK_AABB",and does not expand it by 3 blocks

**Comment by DiMuRie** [comment]
on 1.9 ofc

**Comment by williewillus** [comment]
this is really vague.
What kind of entity? Does it fit ENTIRELY inside the expanded box?

**Comment by DiMuRie** [comment]
the BB of my block is the one of the pressure plate.if any Entity colides whith The FULL_BLOCK_AABB
which if 1 entire block it will move in a certain direction using the onColidedWithEntity method

**Comment by DiMuRie** [comment]
It was actualy: onEntityColidedWithBlock

**Comment by LexManos** [comment]
```
    public AxisAlignedBB expand(double x, double y, double z)
    {
        double d0 = this.minX - x;
        double d1 = this.minY - y;
        double d2 = this.minZ - z;
        double d3 = this.maxX + x;
        double d4 = this.maxY + y;
        double d5 = this.maxZ + z;
        return new AxisAlignedBB(d0, d1, d2, d3, d4, d5);
    }
```
Expand is not broken, you're most likely just using it wrong.
Go to the forums for debugging basic things and come back with a DETAILED report of exactly whats wrong this is to vague and well, crap. We have no idea what the hell you're talking about.
