### ISSUE TITLE
[1.9] Potion Items and conversions

### ISSUE THREAD

**Issue by Shinoow** [MinecraftForge/MinecraftForge#2777]
Seeing as the new ways Potions are handled, registering potion conversions and registering items to be used in potions is currently unavailable (since methods for doing said actions in PotionHelper are private). Unless this is meant to be handled elsewhere, it might be a good idea to perhaps switch those methods over to public through the Forge AT.
These are the following methods used to register Potion Item conversion, Potion Items and PotionType conversions (collected from the 20160312 1.9 MCP snapshot):
`func_185201_a, registerPotionItemConversion`
`func_185202_a, registerPotionItem`
`func_185204_a, registerPotionTypeConversion`

**Comment by williewillus** [comment]
+1
The forge brewing recipe registry is still there, but for all but the most complex recipes, the vanilla system suffices and does a quite well job of it

**Comment by williewillus** [comment]
This is an AT request for exposing vanilla brewing recipe system, so not really a bug but not really a feature, bumping for visibility

**Comment by Actuarius** [comment]
@diesieben07 added labels [Feature]

**Comment by Actuarius** [comment]
@williewillus added labels [Superseded]

**Comment by williewillus** [comment]
also merged a while back, can be closed
