### ISSUE TITLE
[Feature Request] - BungeeCord IP forwarding

### ISSUE THREAD

**Issue by hunter688** [MinecraftForge/MinecraftForge#2784]
Will be possible add support for BungeeCord (IP forwarding) like Spigot and SpongeForge? This will allow connect pure Forge Server to BungeeCord network.

**Comment by LexManos** [comment]
Last we looked into the protocol they did it in a hacky way that wasn't compatible with anything else. So no.
If they have redefined how they used that shared field, OR moved to a new protocol that is a bit more secure, then sure, maybe.
