### ISSUE TITLE
[1.9] ArrayIndexOutOfBoundsException at EnumCreatureType switch

### ISSUE THREAD

**Issue by maxanier** [MinecraftForge/MinecraftForge#2787]
Hello,

there seems to be a strange issue with additional EnumCreatureTypes. My mod [Vampirism ](https://github.com/TeamLapen/Vampirism) adds two new types using Forge's [EnumHelper#addCreatureType](https://github.com/MinecraftForge/MinecraftForge/blob/d090c2834b239c0fe4c1c14d6d76460d4e119e2c/src/main/java/net/minecraftforge/common/util/EnumHelper.java#L71), which by itself does not cause any issues. 
But if Vampirism is installed together with either [AbyssalCraft ](https://github.com/Shinoow/AbyssalCraft) or [Evilcraft](https://github.com/CyclopsMC/EvilCraft) the game crashes during world spawn:
[Log File](https://paste.ee/p/ELARk) 
[Crash Report](https://paste.ee/p/QXCB0)  

During Minecraft's spawning process the games iterates over all values of EntityCreatureType and indirectly invokes BiomeGenBase#getSpawnableList(EnumCreatureType creatureType) using them. Within this method there is a switch statement that seems to throw the ArrayIndexOutOfBoundsException when the iteration is at the 5th element (index 4) of EnumCreatureType#values().

```java
BiomeGenBase.class

public List<BiomeGenBase.SpawnListEntry> getSpawnableList(EnumCreatureType creatureType)  
    {  
        switch (creatureType)  
        {  
            case MONSTER:  
                return this.spawnableMonsterList;  
            case CREATURE:  
                return this.spawnableCreatureList;  
            case WATER_CREATURE:  
                return this.spawnableWaterCreatureList;  
            case AMBIENT:  
                return this.spawnableCaveCreatureList;  
            default:  
                return Collections.<BiomeGenBase.SpawnListEntry>emptyList();  
        }  
    }
``` 

Maybe the way Forge is modifying the enum via reflection does not work with switch statements.  
But the real strange part is that it only occurs if either AbyssalCraft or Evilcraft are installed even though both apparently do nothing with EnumCreatureType. I searched AbyssalCraft's source code, but did not find anything related. The authors of the mods also don't really know what could be causing this (see [this issue](https://github.com/TeamLapen/Vampirism/issues/64)).  
**Setup:**
Java 8 
Minecraft Forge 12.16.0.1865
[Vampirism 1.0.0-Alpha+04-21-19-48](http://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2295305)
[AbyssalCraft 1.9.1.1  ](http://minecraft.curseforge.com/projects/abyssalcraft/files/2293482)
OR
[Evilcraft 0.9.6  ](http://minecraft.curseforge.com/projects/evilcraft/files/2295649)

**Comment by GotoLink** [comment]
EnumHelper only works if the enum 'values() hasn't been computed before.
So you'd better make your change before everything else.
Put your change in a static block in your main mod file.

**Comment by LexManos** [comment]
No, the hacky-ness that is the modifications of enums will break in switch statements for classes that are loaded before you add your entry. So as Goto said either do it as early as possible, or don't extend that enum.

**Comment by maxanier** [comment]
Yes, moving the static block to the main mod file, solved the problem (for now).
Thanks GotoLink :)
