### ISSUE TITLE
Default potion ResourceLocation isn't rebound every iteration in IngameGUI

### ISSUE THREAD

**Issue by yrsegal** [MinecraftForge/MinecraftForge#2790]
This causes texture conflicts if someone wants to have a mod effect.
<img width="253" alt="screen shot 2016-04-28 at 10 48 43 pm" src="https://cloud.githubusercontent.com/assets/6596492/14907213/6e59b84c-0d93-11e6-990f-329193a2cf37.png">
<img width="116" alt="screen shot 2016-04-28 at 10 48 39 pm" src="https://cloud.githubusercontent.com/assets/6596492/14907212/6e582b80-0d93-11e6-8bba-b7aaf680d2ac.png">

**Comment by williewillus** [comment]
how are you doing this?

rebinding the texture in getStatusIconIndex is actually the old way, you need to override Potion.renderInventoryEffect

the problem is that one doesn't exist for the hud

**Comment by williewillus** [comment]
See #2774

**Comment by yrsegal** [comment]
Oops, closing
