### ISSUE TITLE
Add an event to ItemSpade to allow making custom path blocks

### ISSUE THREAD

**Issue by KnightMiner** [MinecraftForge/MinecraftForge#2796]
Currently, the shovel is hardcoded to turn grass into grass path. I suggest adding an event there allowing other paths to be made using the shovel, such as for grass variants added by a mod or to use as an in world crafting, basically just like the hoe. This can basically be the same as the event in ItemHoe, only the result of the event will be a different block.

I can write something myself and PR it that preferred over an issue. I mainly didn't since I would basically just be copying the UseHoeEvent and adding the copy to shovels so it seems a little small for a PR.

**Comment by LexManos** [comment]
And you can't do this with the player interact event why? Or the player use callback in your block?

**Comment by KnightMiner** [comment]
That would work if you are using vanilla shovels, but some shovels do not extend the vanilla shovel (such as the ones from Tinkers Construct), meaning you would have no way of actually knowing that the item that right clicked the block is a shovel without manually adding a list of all shovels.

With an event, assuming the mod either directly called ItemSpade.onItemUse or posts the event itself, other mods will be able to get the result. As I said, it is basically the same as the event posted by the hoe (which I figured is there rather than just using PlayerInteractEvent for a reason)

**Comment by LexManos** [comment]
The hoe event is there because it existed before the interact event was put into place. 
It can be considered dead/legacy code.
As for your other issue, there are plenty of ways you can determine if the item is infact a shovel without relying on the class itself.
See the effective tool/harvest level code.

**Comment by KnightMiner** [comment]
Oh, I see what you mean, using the the getToolClasses method for example.

Something else that this would make easier is supporting things such as the Tinkers excavator AOE path making, as it only technically right clicked the one block. There is a Tinkers Construct event posted there though which would allow a mod to add support in Tinkers manually for their block being made into a path, so I'll close this issue.
