### ISSUE TITLE
Incorrect max enchant ID limit

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2799]
The Enchantment ID limit is currently set as int:

https://github.com/MinecraftForge/MinecraftForge/blob/1.9/src/main/java/net/minecraftforge/fml/common/registry/GameData.java#L52

However, ItemStacks serialize enchantments to NBT using the number ID and they use `writeShort`, so the effective maximum enchant ID is limited to a short

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by asiekierka** [comment]
Do we want to make the enchantment ID limit a short or fix ItemStacks to use integer IDs? I feel the former is much less hackier.
