### ISSUE TITLE
[1.9] OBJStates aren't applied to the OBJ models

### ISSUE THREAD

**Issue by Turkey2349** [MinecraftForge/MinecraftForge#2801]
Rendering with OBJ states works in 1.8.9, but in 1.9 the state doesn't seem to affect the OBJ model when it is applied. I use the states to apply translations and rotations. Not sure what other information you need, but I can get you anything that may help you!

**Comment by matt81093** [comment]
Out of curiousity, is that related to the following error?

`[Client thread/ERROR] [FML]: Could not load vanilla model parent 'minecraft:block/wall_nsew' for 'net.minecraft.client.renderer.block.model.ModelBlock@3f362302
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model minecraft:block/wall_nsew with loader VanillaLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:134) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModelOrLogError(ModelLoaderRegistry.java:184) [ModelLoaderRegistry.class:?]`

`Caused by: java.io.FileNotFoundException: minecraft:models/block/wall_nsew.json
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bvz.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:64) ~[bwl.class:?]`

**Comment by williewillus** [comment]
Nah that's some mod using the old or wrong vanilla wall models

**Comment by Turkey2349** [comment]
No it is not @matt81093

**Comment by fnuecke** [comment]
Possibly related to #2568?

**Comment by Turkey2349** [comment]
@fnuecke I've only done a small part of what The OBJ system provides, but they do seem similar. Not sure if we are using the same method, but I could be wrong.

**Comment by fnuecke** [comment]
Aye, it's probably a different use-case. But from what I could tell the faces are baked only once and then cached, so I'm guessing both our cases are symptoms of a common underlying problem.

**Comment by Turkey2349** [comment]
@fnuecke Sounds about right.

**Comment by aidancbrady** [comment]
Seems like OBJBakedModel still hasn't totally completed the 1.9 port.  I got things to work by caching the BakedQuad lists based on the hashes of provided OBJState and returning them in getQuads() accordingly, seems to work pretty well: https://github.com/aidancbrady/Mekanism/blob/1.9.4/src/main/java/mekanism/client/render/obj/OBJBakedModelBase.java#L69

**Comment by Turkey2349** [comment]
@aidancbrady How did you tell your model to use that class?

**Comment by aidancbrady** [comment]
Check out ICustomModelLoader @Turkey2349

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]
