### ISSUE TITLE
Handle ALL chat (local & remote)

### ISSUE THREAD

**Issue by beppe9000** [MinecraftForge/MinecraftForge#2810]
I am working on a mod that streams the chat to a log file. I am currently using this listener class:

```
public class ChatListener {
        @SubscribeEvent
        public void onChatMessage(ClientChatReceivedEvent event) {
            String text = event.message.getUnformattedText();           
            appendLog(text);
        }
    }
```

I have noticed it doesn't completely handle chat.

For example command autocomplete, and chat lines added by other mods (in this case the same mod) with `Minecraft.getMinecraft().thePlayer.addChatComponentMessage(new ChatComponentText(text));` are ignored.

I would like to log these as well (at least chat lines added that way; i could do fine without autocomplete). I don't care about server side. Basically, I would log every line of text printed in the `[Client thread/INFO]: [CHAT]` stream.

Is there some event I am missing that handles all the chat shown to player?

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]
