### ISSUE TITLE
Can you add Mod Auto Updater？

### ISSUE THREAD

**Issue by Observateurs** [MinecraftForge/MinecraftForge#2816]
Modder can offer an update url and forge will check the update and download the new version of the mod.I think it is very useful.

**Comment by AEnterprise** [comment]
been sugested before and it's an bad idea, opens the door for malicious code to be download and executed

**Comment by Observateurs** [comment]
what about only check and notice the player to download the new version？

**Comment by iLexiconn** [comment]
Forge already has a version checker

**Comment by asiekierka** [comment]
And obtrusive notifications would greatly annoy modpack players. See: Reika.

**Comment by cpw** [comment]
Yup, Forge already has a fully functional mod update checker. The flashing green dots are indicators for an update.
