### ISSUE TITLE
[1.9] InitMapGenEvent not being fired ?   forge version "1.9-12.16.1.1888"

### ISSUE THREAD

**Issue by JennyLeeP** [MinecraftForge/MinecraftForge#2822]
not getting any results running this code.
Tried running in my EventHandler class and my main class.
```java 
@SubscribeEvent(priority = EventPriority.HIGHEST)
	public void getMapGenEvent(InitMapGenEvent event)
	{
		System.out.println(event.getType());
		System.out.println("Is this working ?");
    }
```
All my other events are working.
If this is my derp again I swear. :P

**Comment by covers1624** [comment]
It is fired on MinecraftForge.TERRAIN_GEN_BUS

**Comment by JennyLeeP** [comment]
Thanks, registered my EventHandler to the TERRAIN_GEN_BUS and now all is well. 
Loving the quick help around here. Thanks

**Comment by covers1624** [comment]
No problem, the MinecraftFoge IRC channel on Esper.net is also a good place to ask for quick help.
