### ISSUE TITLE
How to cancel a connection to a server?

### ISSUE THREAD

**Issue by beppe9000** [MinecraftForge/MinecraftForge#2824]
Looks like `FMLNetworkEvent.ClientConnectedToServerEvent` is generated after the client is connected to the server. I would like to handle an new server connection before the connection is actually made (handshake), in order to cancel it according to some criteria.

**Comment by LexManos** [comment]
Why? Are you meaning when the socket is created? Because there are ways to access the socket...
What are you trying to do?

**Comment by beppe9000** [comment]
I'm trying to cancel the connection if the server address is in a user-defined list. I would like to act just after the "Join Server" button (or anything that causes a connection) is clicked

**Comment by LexManos** [comment]
Black lists are bad -.- Mojang is getting a lot of shit for theirs {tho their's is reasonable people are abusing their product to make tons of money}
However, Forge will not go out of it's way to make a black list/black list event.
You can already do this yourself if you look hard enough with the hooks java itself gives you. Forge does not need to add more to help you.

**Comment by beppe9000** [comment]
That would not exactly be a black list. I am looking for a way to get the server name we are connecting to and reacting to that connection according to user' s preferences.

I am developing a mod that has per-server configurations that involve complex user-defined tasks that need to be done prior to login (such as registering custom commands or disabling some other mod) and would like to prevent the connection should errors arise.

What do you mean exactly by "the hooks java itself gives" ? You mean using reflection? Could you point me at something useful in this regard?

Pps. What's wrong with blacklists? As long as the user is in power I see no harm. Abuse from modders? I think is not the case.

**Comment by diesieben07** [comment]
Just hook in earlier, forge has an event for when a GUI is opened, you can use this to cancel any GuiConnecting being opened.

**Comment by beppe9000** [comment]
I will check that, thanks.
