### ISSUE TITLE
1.9 LayerHeldItem item not rotating correctly with arm

### ISSUE THREAD

**Issue by ZornTaov** [MinecraftForge/MinecraftForge#2827]
net.minecraft.client.renderer.entity.layers.LayerHeldItem.renderHeldItem has the rotations and translates in the wrong order it seems.  When crouching and holding right click with a bow, if you look up and down the bow moves around in your hand, whereas if you don't hold shift the bow stays in the same place while looking up and down.  If I'm right then lines 55-58 should be moved down below 61 so that the rotation happens before the sneaking offset, though I could be wrong.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Bug]
