### ISSUE TITLE
[Possible Fix] About the Forge Loading Screen issues

### ISSUE THREAD

**Issue by chaNcharge** [MinecraftForge/MinecraftForge#2831]
In issue #1829, people said that on Macs, the items all appear to be glitched when the loading screen is enabled and crashes when OptiFine is enabled. I run a Mac myself, and I am NOT having any of these issues on my Minecraft. The loading screen is enabled, working perfectly fine with OptiFine, no missing textures. The thing is, I created a separate directory for my modded Minecraft, and the forge loading screen issues don't appear to be present at all. However, if I load forge from the main MC directory, the issues return. Below is a picture of my separate MC directory, could this be a possible fix? 

![screenshot at may 05 17-29-02](https://cloud.githubusercontent.com/assets/11594018/15061180/1499495e-12e7-11e6-8781-b23219277408.png)

Page 2

![screenshot at may 05 17-31-44](https://cloud.githubusercontent.com/assets/11594018/15061205/4fd349c0-12e7-11e6-8671-6048cbe991dc.png)

**Comment by LexManos** [comment]
Directories would have nothing to do with this.
It's drivers/config/whatever
If you find the diff between your dirs then maybe.
But either way this isn't the place to be talking about this.
