### ISSUE TITLE
oredictionary

### ISSUE THREAD

**Issue by MineProjectZ** [MinecraftForge/MinecraftForge#2832]
i have seen in other modpacks, the when i break for example a copper ore from ic2 ore mekanism that i get a copper ore from thermal expansion as long as the ore is in the oredictionary with the same name. how i can make this in my modpack?

**Comment by ChunHin** [comment]
Use OreDictionary.registerOre(Parameters...)
See OreDictionary.initVanillaEntries() for reference

**Comment by MineProjectZ** [comment]
where i should use this?

**Comment by ChunHin** [comment]
Are you making a custom modpack or coding a mod youself?
If you are making a custom modpack : Ask mod's author.

**Comment by williewillus** [comment]
Not the place for this, ask on forums or IRC

**Comment by Actuarius** [comment]
@williewillus closed this issue
