### ISSUE TITLE
"Virtual" Itemstacks Bug (or Feature?)

### ISSUE THREAD

**Issue by Robotia** [MinecraftForge/MinecraftForge#2836]
Hello,

I have discovered a strange bug that affects Forge servers. I have confirmed that it is present in 1.7.10 and 1.8.9.

(TL;DR you can have itemstacks with stacksize 0 in your inventory)

If you remember the classic "isUsableByPlayer" dupe where a player keeps a TileEntity inventory open and another player breaks the TileEntity, this is similar. I discovered this issue when working with the ProjectE mod. The inventory stays open when the tile is broken. The server seems to remove all the items, however, it leaves behind these "virtual" itemstacks. They have a stacksize of 0 and can be placed by the player into his/her inventory. 

As long as the itemstack is placed onto an empty slot and the player does not attempt to stack it, Forge is completely oblivious and persists the itemstack to playerdata.

This could create all kinds of problems for mods that do not check stack size, essentially amounting to a potential dupe glitch.

**I am not sure if this is a bug or a feature...has anyone else noticed this?**

**Comment by williewillus** [comment]
It really is just a PE bug, bump the issue on our repo, doesn't have to do with Forge

**Comment by Robotia** [comment]
While it is a PE bug, shouldn't stacksize 0 items simply not be allowed in the inventory?

**Comment by diesieben07** [comment]
There is no way to disallow them except to constantly check (`stackSize` is just a field, anyone can modify it from anywhere).
