### ISSUE TITLE
Chunkloading crash booting person off server on join

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#2837]
Crash report:

http://pastebin.com/4tddLGZX
The chunk from `world.getChunkFromBlockCoords()` is null. 

Speculation:

This seems to point to `ChunkIOExecutor.syncChunkLoad()` in `ChunkProviderServer.loadChunk()` returning null.

That may be happening when `if (!pool.remove(task))` is passed over? https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/chunkio/ChunkIOExecutor.java#L41-L73

It calls `task.syncCallback()` which does `provider.originalLoadChunk()` but the return value is ignored and `task.chunk` is not set:
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/chunkio/ChunkIOProvider.java#L64-L72

and then `task.getChunk()` returns null so `ChunkIOExecutor.syncChunkLoad()` returns null.

**Comment by sfPlayer1** [comment]
Besides the indicated logic problem, the uses of runFinished() should be synchronized to satisfy the Java memory model's requirements. Most importantly its use in conjunction with wait() needs to be synchronized as detailed in the Javadoc for Object.wait().

Currently the following time-sequence of actions is possible:

1. syncChunkLoad queries task.runFinished(), which returns false
2. the task finishes
3. the task sets ran to true and calls notifyAll
4. the task leaves its synchronized block
5. syncChunkLoad enters the synchronized block
6. syncChunkLoad blocks on wait

The wait() call will never return as notify won't be called again, the game hangs until it's being terminated. Moving the synchronized block one level outwards fixes this, notifyAll won't be able to happen between runFinished() and wait().
