### ISSUE TITLE
New Loot hooks: Custom entry names broken

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2848]
Picture says it all:
https://i.gyazo.com/0f82f1a4b928dc1b0348e6c73f8e8e30.png

(entryName vs EntryName)

**Comment by williewillus** [comment]
in ForgeHooks.readLootEntryName

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/34d4b0b93f90793dd06376f804ea2ff55579b61b
