### ISSUE TITLE
FML breaks IPV6 support

### ISSUE THREAD

**Issue by sfPlayer1** [MinecraftForge/MinecraftForge#2850]
FML calls System.setProperty("java.net.preferIPv4Stack", "true"); from net.minecraftforge.fml.common.launcher.FMLTweaker.FMLTweaker(), which effectively disables IPV6. The associated comment is outdated.

Vanilla supports IPV6 in 1.9.

**Comment by LexManos** [comment]
As the internet still runs on ipv4 this is fine. And it solves the issue of the ~50 or so issues a day we were getting on the support forums about broken IP stacks. Not to mention you've given no steps to reproduce or anything.
Nore a proposed solution that doesn't introduce the support burden of having all that broken stack spam Gunna close this.
5/10 for the bug, 0/10 for your effort.

**Comment by sfPlayer1** [comment]
As mentioned Mojang removed it themselves, so your point is questionable at best.

**Comment by LexManos** [comment]
My point is fine and valid.
You've provided no steps to reproduce I can connect to a local ipv6 server just fine. {I do not know of any public ones as in the wild}
You also have shown 0 effort into solving it beyond complaining.
There is still the support issue that removing this would cause.
You of all people should know better then to do shit half way, you're not doing anything to help your reputation with me.
