### ISSUE TITLE
[1.9] Can't add trades to VillagerCareer

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#2854]
I can create a new `VillagerCareer` but I can't `init` it with trades, the method is private.
My workaround is to subclass it for now and override `getTrades`.
Is there something else I'm supposed to do instead?

**Comment by LexManos** [comment]
Yes this is intentional and for you to use the add/remove methods.
init is a hack that allows me to use arrays from vanilla.

**Comment by mezz** [comment]
There are no add/remove methods for trades on VillagerCareer, and the trades array is null until it gets set with `init`.

**Comment by LexManos** [comment]
Ya seems I must of missed that, interesting to see how little people care about villagers. 
Pushing a fix.
