### ISSUE TITLE
No way of adding permissions to security. 

### ISSUE THREAD

**Issue by LapisSea** [MinecraftForge/MinecraftForge#2856]
So I am building a little programmable block, so I noticed that there is no way of stopping people of abusing it in way of accessing and modifying forbidden classes. So the obvious solution is to make a security class that stops that. But Forge already added one and disabled a to changing it. So if there could be a little hook or registry to adding to FMLSecurityManager#checkPermission(Permission, Object) than that would fix the problem.

**Comment by PizzaCrust** [comment]
If your compiling the code, why not analyse it with ASM after you compile.

**Comment by LapisSea** [comment]
Hmmm that is a good point. I will check that out. But this would still be nice.

**Comment by williewillus** [comment]
Why do you need this level of "security"?
What does your block do that needs to be "secured" from everyone else?

**Comment by LapisSea** [comment]
I think I didn't explain the situation really good. I have a block that takes in a string (from an item nbt) that is basically a JavaScript file. It's compiled with the Nashorn compiler that's build into java lib. It has extremely minimal control. So if I restricted nashorn originated classes any interaction except a list of classes that I use that the problem would be fixed. Also I am
