### ISSUE TITLE
[1.8.9] Villager Registry is not updated.

### ISSUE THREAD

**Issue by Orange1861** [MinecraftForge/MinecraftForge#2857]
I noticed that in 1.8.9 forge, the villager registry is not updated to 1.9 yet.

**Comment by iLexiconn** [comment]
Update your mod to 1.9

**Comment by Orange1861** [comment]
I will eventually, but it confuses me why the registry is completed despite that there is still support for 1.8.9.

**Comment by GirafiStudios** [comment]
1.8.9 haven't been worked on for a good while?

**Comment by Orange1861** [comment]
Yes, but there is still bug fixes.

**Comment by williewillus** [comment]
The villager registry was fixed along with the big registry fixup in 1.9, backporting that would be nontrivial to say the least.
