### ISSUE TITLE
[1.9] Event(s) for EntityLivingBase Movement 

### ISSUE THREAD

**Issue by adriantodt** [MinecraftForge/MinecraftForge#2859]
I came here just asking if `EntityLivingBase.moveEntityWithHeading` should be wrapped to events?

The method as-is holds Elytra, Water, Lava and Levitation, and maybe it would help both coders without ASM experience and mods don't overlapping themselves.

I was trying to make a ASM Patch to add Custom Elytras Speed but I don't want to wreck with a method that does a bunch of stuff. Is making Events for it reliable or not?

**Comment by LexManos** [comment]
-.- Protip don't come in here saying you'll hack shit with ASM it puts me in a bad mood and makes me think you're a complete and utter moron.

What exactly are you trying to do. Making a generic 'this entity is trying to move 1px to the left' event is not going to happen. 
That would be WAY to much spam.

**Comment by adriantodt** [comment]
Sorry, first time here.

I think about that too. I'll try to find a way with other events, thanks for replying.

**Comment by williewillus** [comment]
you can already do what you want with LivingUpdateEvent + check for elytra

**Comment by diesieben07** [comment]
Movement events would just fire at the same rate as living update already does.

**Comment by Actuarius** [comment]
@diesieben07 added labels [Feature]
