### ISSUE TITLE
ForgeHooks.LootTableContext.validateEntryName does not allow duplicate names

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#2860]
I want to add two different bees to a loot pool, seen below. `ForgeHooks.LootTableContext.validateEntryName` will not let me because the names are both "forestry:beeDroneGE". It handles this case more leniently for vanilla.

```json
{
    "type": "item",
    "name": "forestry:beeDroneGE",
    "functions": [
        {
            "function": "set_species_nbt",
            "speciesUid": "Forestry.speciesSteadfast"
        }
    ],
    "weight": 5
},
{
    "type": "item",
    "name": "forestry:beeDroneGE",
    "functions": [
        {
            "function": "set_species_nbt",
            "speciesUid": "Forestry.speciesEnded"
        },
        {
            "function": "set_count",
            "count": {
                "min": 2,
                "max": 3
            }
        }
    ],
    "weight": 20
},
{
    "type": "empty",
    "weight": 60
}
```

**Comment by LexManos** [comment]
Yes, this is intentional, you must specify unique names.

**Comment by mezz** [comment]
How can I use unique names in this case?

**Comment by williewillus** [comment]
Explicitly specify the "entryName" key
In most cases entryname is generated from "name" but in this case you have to do it manually

**Comment by LexManos** [comment]
add something like 
"entryName": "bee_steadfast" to the first one and
"entryName": "bee_ended" to the second one.
That way if people want to remove it they an easily find them by asking the pool for those names.

**Comment by mezz** [comment]
Thanks, perfect.
