### ISSUE TITLE
Need an easier way to set villager profession spawns for modded village buildings

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#2861]
`StructureVillagePieces.chooseProfession` requires me to return an int for the villager profession ID, in order to spawn a modded villager in their home building.
The only way for me to get my villager profession ID is some convoluted casting because the villager registry is publicly exposed as an `IForgeRegistry`.

```java
FMLControlledNamespacedRegistry<VillagerRegistry.VillagerProfession> registry = (FMLControlledNamespacedRegistry<VillagerRegistry.VillagerProfession>) VillagerRegistry.instance().getRegistry();
return registry.getId(PluginApiculture.villagerApiarist);
```

Ideally, I would just have to return the `VillagerProfession` and never worry about IDs, but I'm not sure if that would be a mess to implement or not.

**Comment by Actuarius** [comment]
@williewillus added labels [Cleanup]

**Comment by Actuarius** [comment]
@diesieben07 closed this issue

**Comment by diesieben07** [comment]
This has been fixed.
