### ISSUE TITLE
Modded villagers get vanilla names instead of correct names

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#2862]
When I open the gui to trade with my villager, it has a vanilla profession name instead of what it should be. The actual trades are correct.

`EntityVillager.getDisplayName()` checks `this.getProfession()`. 
getProfession uses % 5 on the profession id...
TLDR it's just not implemented yet and there are weird pitfalls.

[`//TODO: Hook into VillagerRegistry to get name`](https://github.com/MinecraftForge/MinecraftForge/blob/d5b93bf262aee8e74098c6bf50d70602b03c9ad9/patches/minecraft/net/minecraft/entity/passive/EntityVillager.java.patch#L148)

**Comment by Actuarius** [comment]
@mezz added labels [Bug]
