### ISSUE TITLE
No LivingDeathEvent or LivingDropEvent for ArmorStands

### ISSUE THREAD

**Issue by topisani** [MinecraftForge/MinecraftForge#2864]
I want an armorstand to drop 2 sticks on death if the arms are visible, but...  

Neither `LivingDeathEvent` or `LivingDropEvent` gets fired when an ArmorStand is destroyed.  
`EntityLivingBase.onDeath()` isn't called either. As far as i can see there is no way to hook in when an Armourstand is destroyed.  
Best option is probably firing `LivingDropEvent` from this:

``` java
    private void dropBlock()
    {
        Block.spawnAsEntity(this.worldObj, new BlockPos(this), new ItemStack(Items.ARMOR_STAND));
        this.dropContents();
    }
```

And `LivingDeathEvent` from this:

``` java
    public void setDead()
    {
        this.isDead = true;
    }
```

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]
