### ISSUE TITLE
[1.9] Saplings will turn ANY plant-sustaining block they grow on into dirt

### ISSUE THREAD

**Issue by yrsegal** [MinecraftForge/MinecraftForge#2866]
You can't have a custom soil, because the tree will turn it into dirt when it grows. It obviously has the expected behavior on Podzol, Grass, and Mycelium, but turns Coarse Dirt into regular dirt.

This might be a vanilla bug, but I haven't verified that.

**Comment by williewillus** [comment]
cannot reproduce on latest 1.9.4 for coarse dirt and spruce sapling

**Comment by williewillus** [comment]
update: cannot reproduce on latest 1.9.4 for coarse dirt and any vanilla sapling

**Comment by yrsegal** [comment]
new info: It's only if it could sustain a plant.

**Comment by williewillus** [comment]
but can't coarse dirt sustain plants?

**Comment by yrsegal** [comment]
by sustain plants, I mean things like wheat and carrots.

**Comment by williewillus** [comment]
did you override onPlantGrow?

**Comment by yrsegal** [comment]
shouldn't matter, since the tree gen calls setDirt if it matches this condition.

**Comment by williewillus** [comment]
where does it do that?

**Comment by iTitus** [comment]
Are you talking about farmland?

**Comment by ChunHin** [comment]
In the class WorldGenAbstractTree, there is a method called _setDirtAt_.
`if (worldIn.getBlockState(pos).getBlock() != Blocks.dirt)`
That means if the plant-sustaining block is not dirt,
`this.setBlockAndNotifyAdequately(worldIn, pos, Blocks.dirt.getDefaultState());`
it will set that block to dirt.
Sapling use generator to generate tree.
Every generator that sapling extends WorldGenAbstractTree.
And they called _setDirtAt_.

Look at BlockDirt.DirtType and BlockDirt's constructor.
In the constructor there is a PropertyEnum that determines that is this block coarse dirt, podzol or normal dirt.
So coarse dirt and podzol are also dirt actual.
So they are _equal_ to dirt.

**Comment by mezz** [comment]
I think the intended purpose of `setDirtAt` is turn grass to dirt.

First, here's all the types of block saplings can grow on:
Saplings are BlockBush, so their canSustain is determined by `BlockBush.canSustainBush()` which has Grass, Dirt, and Farmland. They are Plains plant type, which also only supports Grass, Dirt, and Farmland.

And here's how they react to a tree growing on them, if `setDirtAt` is not used:
Farmland already instantly sets itself to dirt in `BlockFarmland.neighborChanged`, 
Dirt, Mycelium, and Podzol are already dirt and immune from `setDirtAt`.
Grass reverts itself to dirt in `updateTick` which takes a while.

I think the solution here is to check if it's grass in `setDirtAt`.

**Comment by LexManos** [comment]
Pretty sure we have a callback for on plant growth that allows for you to override this mechanic. If not this would be the place to put it in.

**Comment by mcenderdragon** [comment]
On line 86 in `WorldGenBirchTree`  ` state.getBlock().onPlantGrow(state, worldIn, down, position);` is called to notify the block beneath to change to dirt if grass or farmland. 
In `WorldGenTree` (used to generate small oaks and jungle trees) on line 98 ` this.setDirtAt(worldIn, position.down());` is used. I suggest we change that to the onPlantGrow, like any other tree gen does.

**Comment by mcenderdragon** [comment]
If I a make this fix for 1.10.2, what are the chances this gets pulled?
