### ISSUE TITLE
[1.9] Way to iterate all loottables

### ISSUE THREAD

**Issue by way2muchnoise** [MinecraftForge/MinecraftForge#2867]
So we can get all pools and entries without guessing names.

Giving a list of names available is just silly, looking at the way it searches for matches in the list of pools/entries. Performance will drop trough my desk.

**Comment by williewillus** [comment]
Your ticket is not clear at all.

You want an Iterable of all loottables? or all loot POOLS? or the ENTRIES in each pool? which one?

**Comment by way2muchnoise** [comment]
All entries for all pools in every table. So all of the above really.
 For reference [JER](https://github.com/way2muchnoise/JustEnoughResources) and ![](http://puu.sh/oVD0l/48b662ecdd.gif)

**Comment by LexManos** [comment]
no this is a design choice that you shouldn't be doing bulk edits to loot tables pragmatically.
