### ISSUE TITLE
[1.9.4]EnumHelper.addArmorMaterial does not take into account new values and causes a crash

### ISSUE THREAD

**Issue by modmuss50** [MinecraftForge/MinecraftForge#2870]
When using EnumHelper.addArmorMaterial it crashes because EnumHelper.addArmorMaterial does not take into account the new values of ArmorMaterial

I can make a PR to fix if you like

**Comment by AtomicBlom** [comment]
I wrote a fix for this, but I haven't had time to test it. Going to try squeezing it in during idle time at work.

**Comment by LexManos** [comment]
Someone need to go through and write a test mod for all the damn Enum's its getting annoying them changing all the time and not having a generic function instead.
You can use addEnum directly if you want.

**Comment by AtomicBlom** [comment]
@Vazkii is fixing it in https://github.com/MinecraftForge/MinecraftForge/pull/2874

**Comment by AtomicBlom** [comment]
Wrote a unit test to detect the problem: https://github.com/MinecraftForge/MinecraftForge/pull/2875

**Comment by liach** [comment]
Just use `addEnum` for now, it's not really a problem

**Comment by Actuarius** [comment]
@williewillus added labels [Bug, Superseded]
