### ISSUE TITLE
[Suggestion] Event to handle critical hits

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#2871]
In 1.8.9 it is not possible to determin if a player make a critical hit nor prevent him form doing one. An external event for handling it whould be very nice. We could also add an event for handling critical enchantment hits.

If I am allowed, then I can make a pull request. #

**Comment by williewillus** [comment]
You should add it as a field to the entity attack event

**Comment by mcenderdragon** [comment]
this whould result in an complet restructurating of the **attackTargetEntityWithCurrentItem**  in **EntityPlayer**. At the beginning the AttackEntityEvent fired and is cancleable (at this time such thing like critical are not yet determined). I think It whould be bad to run the half attack logic only to cancle it or similar.

**Comment by mcenderdragon** [comment]
I just made a pull request with the important features.

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by mcenderdragon** [comment]
I dont want to annoy anyone but why got the 2883 closed, and should I try it again, or have I made something wrong ?

**Comment by williewillus** [comment]
Because you messed your PR up git-wise

**Comment by mcenderdragon** [comment]
My actuell fork has no conflicts and I fixed the mess, so I can just open a new one, right ?

**Comment by Actuarius** [comment]
@williewillus added labels [Superseded]

**Comment by mcenderdragon** [comment]
What does that "Superseded" label mean? The best explanation I found was "replace". Does that mean this Issue  is rejected ?

**Comment by Choonster** [comment]
The Superseded label means that this issue has been superseded by another issue/PR. In this case, by #3004 (your own PR).

**Comment by heldplayer** [comment]
Basically it means that a new issue or PR has been made that better addresses or fixes the problem.

**Comment by mcenderdragon** [comment]
Oh okay, thank you.
