### ISSUE TITLE
[Suggestion] Capability System for World & Server

### ISSUE THREAD

**Issue by Abastro** [MinecraftForge/MinecraftForge#2877]
Posting this issue before creating a PR to check the possibility of this feature to be accepted.
This will not only expand the consistency of Capability system, but also enables mods to implement compatible features easily and have better designs.
## Expose features of Own World

Currently, there is no way for mods related with Worlds(Dimensions) to expose their own features without using either their own hardcoded API, Maps or using WorldSavedData. This is really bad idea, especially when a mod wants to implement dynamic world system.

**Hardcoded APIs and maps**
 There are high possibility of being broken by dynamic world management, and it is not a good design indeed.

**Specializing WorldProvider to specify own features**
 This case is similar with Items / TileEntities / Entities specifying their own features with interfaces before Capability system existed.

**Using WorldSavedData**
 Might be better than two cases above, but It has huge limitations.
It is hard to create one when the world starts to exist, especially with general world settings.
 Also it should always be gotten from MapStorage when it is needed, without knowing that when it is truly created, which is not appropriate for Per-World management.
 Moreover, it needs additional hooks to make it fit in API, because it is not designed for Per-World handling, but just for saving data.
 Finally, it can be observed that WorldSavedData is really similar with previous IEEP system. They both have load/save methods, got/loaded/saved with ids. So it will be safe to assume that there is enough cause to use Capability System instead of WorldSavedData just like Caps replacing IEEPs.
## Implementing Per-World features

 If a mod tries to implement its own per-world features like Custom Sky, Weather, or World-Specific Effects to apply to any world, there is no way but create their own mapping for worlds, use WorldSavedData, or patch WorldProvider. But as shown above, these leads to bad designs and buggy implementations due to lack of considerations on the features in previous system.
 **Capability System for Worlds** will enable mods to let the World hold their own features which is easy to expose, and load/save the customization data.
 This will introduce **Compatibility in World part**, which was nearly impossible before unlike Inventory / Block / Entity part.
## Server Control

 One can ask: Then why do Server need Capability System? Isn't it redundant? Yes, it had been till 1.8.9, since there could be only one server instance in single moment. 
 **But in 1.9, the Server System had changed.** Now there can be more than one servers for 1.9+, which means that previous APIs which was designed to apply the entire server would have high possibility of being broken. Server Capabilities will help greatly on this part, enabling mods to implement overall feature easily.
 Moreover, it will reduce difference between Integrated Server and Dedicated Server by introducing Per-Server features. (The difference is in their existing time; Integrated Server is, in many case, dynamic. But Dedicated Server had been static till 1.8.9, and is still nearly static on 1.9)

 Then where would be the data saved? World#mapStorage was designed as universal storage, so using this would be fine. It had been very unstable and buggy to use the mapStorage since its behavior varies case by case (especially on Client). Capability System can cure this by wrapping and holding the provider instance separately.

**Comment by LexManos** [comment]
> But in 1.9, the Server System had changed. Now there can be more than one servers for 1.9+, 
Don't know who you're talking to but this is wrong.

**Comment by williewillus** [comment]
Your post is super long-winded and could've just said

Request for World and Server-level capabilities

**Comment by williewillus** [comment]
Though I think Server-level capabilities make 0 sense

**Comment by Abastro** [comment]
@LexManos Yes, but it is fact that server instance is not singleton now. Instead, there is World#getServer(). Currently erver instance is only one in forge, but I think that the direction of Minecraft is going to have multiple servers on one program.

**Comment by williewillus** [comment]
"Might have multiple" =/= "Has multiple"

**Comment by LexManos** [comment]
Let me just state to you, that it has been confirmed that that assumption is WRONG.
Removal of one function does not a total refactor of how MC works make.
Stop spreading false information as truth.

**Comment by Abastro** [comment]
@williewillus If you have worked on some per-server features, you would get into problems from difference with Integrated Server and Dedicated Server since Integrated Server keeps loaded and unloaded. It is quite hard to manage data with it, especially when using mapStorage.
And, if there is only one on most cases, it still can be called as 'multiple' if multiple case is possible.

**Comment by Abastro** [comment]
@LexManos So, current minecraft code still does not allow multiple servers running in single program?

**Comment by williewillus** [comment]
What? If you are ever treating dedi/integ servers differently your mod is broken. 

And to your second question to Lex, no, it doesn't.

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by Abastro** [comment]
@williewillus Yes, I'm not treating them directly, since there are way to compare them implicitly. But it still complicates code.
For example, mapStorage changes in certain cases on Integrated Server, while it is constant on dedicated server. This makes WorldSavedData on mapStorage inappropriate as managing overall server feature.

**Comment by heldplayer** [comment]
World Capabilities sounds like a great idea! :+1: 

Server Capabilities might be a bit pointless/redundant. Instead, what about Save Capabilities? The scope would still be global, but limited to the save. (Maybe this is what you're wanting when you're saying Server Capabilities?)

**Comment by mcenderdragon** [comment]
> Implementing Per-World features ....
So any mod can just change the custom sky of my Dimension? Is there a way to prevent this?

**Comment by Abastro** [comment]
@mcenderdragon That was already possible using ISkyRenderer. While you can prevent it, it is not recommended. There is no reason to block it.. No mod will hijack it without reason.

**Comment by Abastro** [comment]
@heldplayer Thanks. I think the Save Capability could be better.

**Comment by Madsthunder** [comment]
This can be closed by #3069

**Comment by Abastro** [comment]
Well, technically, there's 'Save Capability' left. Though I don't have any plan to make a PR for it.
