### ISSUE TITLE
OBJ model parser attempts to render more than 4 vertices

### ISSUE THREAD

**Issue by Spaceshipable** [MinecraftForge/MinecraftForge#2881]
If the loader detects more than 4 vertices for a face, it will use TextureCoordinate.getDefaultUVs() of which there are only 4 elements. 

The index used, however, will go up to verts.length which appears to be the original no. of vertices from the model (greater than 4) . 

The index should go up to TextureCoordinate.getDefaultUVs().length

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by AtomicBlom** [comment]
Wait... if the Loader detects more than 4 vertices for a face? The system was never designed to do more than 4 vertices per face. It specifically works with Quads for performance reasons, even triangles get converted to quads.

What I think you're expecting is for Forge to triangulate your model for you, but there's no triangulation in place to split up a face made with more than 4 vertices.

My suggestion is to triangulate the OBJ in your modelling tool, and use Quads as often as possible.

**Comment by Spaceshipable** [comment]
The bug is that the loader attempts to render more than 4 vertices when only 4 are available. 

TextureCoordinate.getDefaultUVs() is only used when more than 4 verticies are detected but it causes an out of bounds exception because there are more than 4 verticies. This bit of code, therefore can never be used.

At present this makes getDefaultUVs() completely redundant. Either an assert should be made to crash when more than 4 verticies are detected or brie index used to itterate through verticies should go up to 4 only.
