### ISSUE TITLE
[1.9.4] Example mod after fresh install contains mistake

### ISSUE THREAD

**Issue by BVerschaete** [MinecraftForge/MinecraftForge#2882]
in the main class of example mod there is a println statement containing Blocks.dirt.getUnlocalizedName()

should be DIRT

**Comment by iLexiconn** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/7f6f2f0ec19ec09d752ec10eb5be952fd5f3badc

**Comment by Actuarius** [comment]
@williewillus closed this issue
