### ISSUE TITLE
[1.9.4] Vanilla uses hard-coded no-model rendering, so why can't we?

### ISSUE THREAD

**Issue by elix-x** [MinecraftForge/MinecraftForge#2888]
If you look in net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer, you will see that vanilla uses harcoded renderer to render some of it's items, mostly tilentities (chests, banners and skulls), but also shield.
If vanilla can render it's items using hardcoded render methods, then why modders can't?

So, my proposition is to hook into TileEntityItemStackRenderer, and at least allow rendering of items representing tile entities. The best would be to revive IItemRenderer (or it's new iteration)?
After all, again, if vanilla uses it for shield, why can't modders?

**Comment by RainWarrior** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/1.9.4/patches/minecraft/net/minecraft/client/renderer/tileentity/TileEntityItemStackRenderer.java.patch#L7
