### ISSUE TITLE
Tipped Arrows can be fired infinitely with Infinity

### ISSUE THREAD

**Issue by yrsegal** [MinecraftForge/MinecraftForge#2890]
this is not vanilla behavior.

There is also no way for custom ItemArrows to determine whether they can or can't be fired with infinity at the moment.

**Comment by OrionDevelopment** [comment]
PR is already in the works. Check #2853

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/2356f088ee2b36a3e9ae5242c384dd2d179182fd
