### ISSUE TITLE
[1.9.4] Villager Skin are default to Farmer

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#2894]
![2559-05-23_13 15 00](https://cloud.githubusercontent.com/assets/6128413/15461852/8c126dda-20e8-11e6-92cc-ad9806c367ad.png)

No mod used, I testing on the realms server.

**Comment by LexManos** [comment]
No clue what you're doing but it works just fine: http://puu.sh/p2PyX/a19585f32f.png

**Comment by SteveKunG** [comment]
OK. Still bug on the realm server with the latest Forge. Build 1913.

![2559-05-24_06 16 28](https://cloud.githubusercontent.com/assets/6128413/15487456/b26f4ec8-2177-11e6-9625-072a2d9d5b09.png)
![2559-05-24_06 16 31](https://cloud.githubusercontent.com/assets/6128413/15487457/b2732156-2177-11e6-98ee-e6350e010ca2.png)

And no other mods installed (removed resource pack).
![2559-05-24_06 19 11](https://cloud.githubusercontent.com/assets/6128413/15487502/e6050f34-2177-11e6-8d65-55112d10e810.png)

Tested on the client.
![2559-05-24_06 24 43](https://cloud.githubusercontent.com/assets/6128413/15487531/40458942-2178-11e6-917d-45f405c4451a.png)

**Comment by LexManos** [comment]
Send me an invite to your realm server. LexManos IGN

**Comment by SteveKunG** [comment]
Oh, sorry. My realms owner doesn't allow other people to join their realm -.-

But I try to testing on the localhost server. Forge Build 1915.
![untitled](https://cloud.githubusercontent.com/assets/6128413/15488216/6d7eaf64-217e-11e6-89e8-5253686b938c.png)

Villager skin still bug.

**Comment by LexManos** [comment]
Was able to find it, a slight misunderstanding about how Mojang's data watcher worked.
