### ISSUE TITLE
[1.9.4] New ItemAxe constructor should pass float, not int

### ISSUE THREAD

**Issue by PeregrineDev** [MinecraftForge/MinecraftForge#2902]
The alternative constructor ItemAxe(Item.ToolMaterial material, int damage, int speed) uses int for the damage and speed values, these are float in vanilla.

Btw is there a reason this constructor is protected and not public?
If it were public we could register new axes with custom materials and damage/speed values without having to create a (empty) subclass.

**Comment by diesieben07** [comment]
You can make your own axes by using `setHarvestLevel` and specifying `axe` as the tool class.

**Comment by liach** [comment]
Use anonymous subclass.
