### ISSUE TITLE
[1.9.4] Sound replaying issue

### ISSUE THREAD

**Issue by CreativeMD** [MinecraftForge/MinecraftForge#2907]
Hello,
as i was trying to port AmbientSounds to 1.9.4, i ran into a problem. If i leave a world and rejoin again, it will play all the ambient (my sounds, those are tickable) sounds (from the previous session) again. Sadly not as a tickable sound again, but instead as a normal sound (which keeps repeating in background over and over again; will never stop until you close the game).

I spent hours to figure out why this keeps happening and it seems like the list of paused sounds won't be emptied during world load/leave.

My Suggestion:
Add `this.pausedChannels.clear();` to `public void stopAllSounds()` in SoundManager.
That would fix the problem, although i'm not sure if this is the way to go.

So i hope you will be able to help me out. Maybe it's on problem on my end?

In Regards
CreativeMD

**Comment by williewillus** [comment]
Try to repridce in vanilla, might be a bug there

**Comment by CreativeMD** [comment]
Yeah, it might be a vanilla bug, but there is no way to fix it from my end. So i would be rather happy if Forge could fix it, because these sounds are not "marked" as tickable anymore, so there is no way to stop them except of some hacky ways.

**Comment by Actuarius** [comment]
@williewillus added labels [Vanilla Bug]

**Comment by williewillus** [comment]
ref: https://bugs.mojang.com/browse/MC-35856

**Comment by CreativeMD** [comment]
Well, just out of curiosity is there a chance that forge will fix this bug? or is it something forge doesn't do? (Fixing vanilla bugs).

**Comment by Pokechu22** [comment]
If you've got code that fixes it, and you can be sure that it does fix it, _put it in the vanilla bugtracker_.  Here's [a case where I did that](https://bugs.mojang.com/browse/MC-35714).

**Comment by williewillus** [comment]
Yes PR's fixing vanilla bugs are usually taken. Just comment it like `// FORGE - Fix MC-35856` or something like it

**Comment by Actuarius** [comment]
@williewillus added labels [Superseded]
