### ISSUE TITLE
[1.9] getWorld() for LootContext

### ISSUE THREAD

**Issue by kirderf1** [MinecraftForge/MinecraftForge#2916]
The LootContext object is normally created with a WorldServer, which is then never used in that class. I am in need of world access for a custom LootCondition and suggest that we put in a getter for that world object.

**Comment by williewillus** [comment]
+1 I had it in my original loot hooks draft

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by Actuarius** [comment]
@williewillus added labels [Superseded]
