### ISSUE TITLE
Dispensers will pickup any Materal.water as a Water bucket when using a vanilla empty bucket no matter if it is indeed a water block or not

### ISSUE THREAD

**Issue by ThatOneTraitor** [MinecraftForge/MinecraftForge#2918]
There should be a thing that makes dispensers check for what fluid their picking up. Thermal foundation has their own [dispenser utilities ](https://github.com/CoFH/CoFHCore/tree/master/src/main/java/cofh/core/util/fluid) that let their liquid be picked up by dispensers in a fixed way. This should be added into forge so that other mods such as AM2 (The whole reason im making this post) doesn't have to worry about liquid not being handled by dispensers properly

**Comment by LexManos** [comment]
Dispensors use items, and have a registry for there 'attempt to use this item'.
So if there is something that can be used to hold fluids in the dispenser, then it needs a handler to be registered.
So this has very little to do with liquids and more the items. What items are not working? The vanilla bucket picks up lava/water so it should work fine.

**Comment by williewillus** [comment]
I'm gathering that this is requesting something like a dispenser use action for the universal bucket?
That's not going to show up in 1.7.10 with AM2 though, it's going to be in 1.9.4+

**Comment by ThatOneTraitor** [comment]
yeah still, it'd be good to add

**Comment by TheIcyOne** [comment]
Just to note, this is the commit @ThatOneTraitor is referencing.

https://github.com/Mithion/ArsMagica2/commit/0e7da1f88b4a437f83efc4412648e03d2bcdbf05

**Comment by LexManos** [comment]
And this is why context information is important!
The OP is 'Dispensers something something fluids something something'
With your added context 'Dispensers will pickup any Materal.water as a Water bucket when using a vanilla empty bucket no matter if it is indeed a water block or not'
See how context makes things actually make sense?

**Comment by williewillus** [comment]
So this is actually a bug of sorts.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by ChunHin** [comment]
@ThatOneTraitor
I use a way to make any custom liquid with custom liquid material act as a liquid by overriding a method.
```
public Boolean isEntityInsideMaterial(IBlockAccess world, BlockPos blockpos, IBlockState iblockstate, Entity entity, double yToTest, Material materialIn, boolean testingHead)
{
    return null;
    // null for default
}
```
I override with this :
```
public Boolean isEntityInsideMaterial(IBlockAccess world, BlockPos blockpos, IBlockState iblockstate, Entity entity, double yToTest, Material materialIn, boolean testingHead)
{
    if (materialIn == Material.WATER && world.getBlockState(blockpos).getBlock() == this)
    {
        return true;
    }
    else
    {
        return super.isEntityInsideMaterial(world, blockpos, iblockstate, entity, yToTest, materialIn, testingHead);
    }
}
```
And it will act like as liquid.
**This is a short-term fix.**
We still need to fix this bug.

**Comment by ThatOneTraitor** [comment]
ty, ill put this on the AM2 issue

**Comment by Actuarius** [comment]
@mezz added labels [Fluids]

**Comment by mezz** [comment]
I'll get started on this now

**Comment by Actuarius** [comment]
@williewillus added labels [Superseded]
