### ISSUE TITLE
Minor: getCapability/hasCapability annotations

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2922]
the EnumFacing argument on these needs to have @Nullable, or else the mcp package annotations are going to blanket it in a @Nonnull which is definitely not the case

**Comment by blay09** [comment]
Another one I noticed missing @Nullable was GuiContainer.getSlotUnderMouse().

**Comment by LexManos** [comment]
It doesnt matter much in MC code, and the fact is that by default @Nullable means absolutely nothing as eclipse/intellij default to ignoring it.
So the entire system itself is moot.
Anyways We don't care about this 1/2 line fixes if you're gunna nitpick something that doesn't matter, do it comprehensively.

**Comment by blay09** [comment]
Running IntelliJ Ultimate on default settings and it certainly is not ignoring @ParametersAreNonnullByDefault and @MethodsReturnNonnullByDefault.

The only way to get rid of [annoying warnings](http://blay09.net/pics/warningnull.png) right now is to disable the whole inspection ... (in which case yes, the entire system is moot, but why should it be when adding the correct annotations to the few methods added by patches would solve the issue?) 

...or plastering your code with `//noinspection ConstantConditions` so it will let you null-check in peace.

**Comment by LexManos** [comment]
Find a way to make the inspections show up using a default eclipse setup as eclipse is the only IDE we officially support As it's the only one who has a resonably setup procidure for the end modder.
Either way as stated we dont care about these 1/2 nit pickey things, Especially when they are in the MC codebase and not modders. The decompiled code isn't perfect deal with it.

**Comment by wesdean** [comment]
I got this from https://stackoverflow.com/questions/24495448/not-annotated-method-overrides-method-annotated-with-notnull

Add the @Nonnull annotation to the method that is throwing the warning.

**Comment by mezz** [comment]
If you are trying to use strict nullable annotations with Minecraft, check out my project here:
https://github.com/mezz/MinecraftAnnotations
