### ISSUE TITLE
Update 1925 causes EIO to crash at startup 

### ISSUE THREAD

**Issue by CrazyPants** [MinecraftForge/MinecraftForge#2924]
Since this change in 1.9.4-12.17.0.1925:
LexManos: Capture interfaces when scanning classes and preload implementations of ICrashReportDetail.

starting MC with EIO installed causes the crash:
java.lang.ClassNotFoundException: crazypants.enderio.tool.EnderIOCrashCallable

this happens during pre-init when FMLCommonHandler.instance().registerCrashCallable(new EnderIOCrashCallable()); is called.

It seems the class is not available to classloader used by EnderIO. Note that this does not happen in a dev-env (running from eclipse).

[latest.txt](https://github.com/MinecraftForge/MinecraftForge/files/288134/latest.txt)

**Comment by LexManos** [comment]
Alright I see the issue, the mod jars are added to the classpath in the construct event, I missed that. So we're doing it slightly to early. Let me see if I can get something to fix it.

**Comment by LexManos** [comment]
Needed more rework then I thought but there we go, fixed.
