### ISSUE TITLE
Forge Fluids have a collision mask

### ISSUE THREAD

**Issue by KnightMiner** [MinecraftForge/MinecraftForge#2932]
Fluids that extend the Forge BlockFluidBase (and by extension BlockFluidClassic) act as a full block rather than allowing the player to swim in them, as shown in [this picture](http://i.imgur.com/lSry4Ae.png).

It can be fixed by adding the following code to the class which extends the Forge fluid, though really it should be fixed in BlockFluidBase since they should not collide by default:

    @Nullable
    public AxisAlignedBB getCollisionBoundingBox(IBlockState blockState, World worldIn, BlockPos pos)
    {
        return NULL_AABB;
    }

**Comment by williewillus** [comment]
I thought we fixed this? 0.o

**Comment by iLexiconn** [comment]
The collision and selection bounding box names were switched. I think they are fixed now.

**Comment by tterrag1098** [comment]
@KnightMiner what forge version are you testing this in? Can anyone provide proof this is fixed?

**Comment by iLexiconn** [comment]
I meant that the mappings are fixed. The methods are rotated now, that's why it has collision.

**Comment by KnightMiner** [comment]
I am using the latest, 1.9.4 - 12.17.0.1937.  In any case, [BlockFluidBase](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/fluids/BlockFluidBase.java#L646) is setting the selection box to null, which I think is what @iLexiconn is saying: previously `getSelectedBoundingBox()` was setting the collision box, and the MCP mappings were fixed since then.

**Comment by LexManos** [comment]
I forgot about it when I did the MCP mappings update in Forge.
