### ISSUE TITLE
[1.9.4] An unknown persistent registry type "guideapi:books" has been encountered

### ISSUE THREAD

**Issue by unknownname** [MinecraftForge/MinecraftForge#2934]
MC version 1.9.4
Forge version 12.17.0.1937

I am currently getting the error message when i upgrade the Old Minecraft world to Lastest MC version. I opened a bug report with Guide API mod author was advised that this is Forge issue. While i reading old bug report, i thoug it was fixed in 1.9 forge. It seems issue is still occuring.
 Attached is FML logs:

[fml-server-latest.txt](https://github.com/MinecraftForge/MinecraftForge/files/294573/fml-server-latest.txt)

Is any work around for the persistent registry issue? 

How to reproduce:
Create a world with Guide Api mod installed
Then delete the Guide Api and try to restart the server.

**Comment by TehNut** [comment]
Create a world with *any* persistent registry, then try to load without. It is not GuideAPI specific.

**Comment by LexManos** [comment]
Ya I see the issue, and have a potential fix. We just need to wrap it in a warning screen.
I just need to find a way to test it.
