### ISSUE TITLE
[1.9.4] Wrong method name after 1.9.4 update getModdedBiomeGenerators -> getModdedBiomeerators

### ISSUE THREAD

**Issue by JCMais** [MinecraftForge/MinecraftForge#2937]
See: https://github.com/MinecraftForge/MinecraftForge/blob/b9ac73b0f1ac10b6d4cca8ac3771f2e0034597e4/patches/minecraft/net/minecraft/world/biome/BiomeProvider.java.patch#L32

**Comment by Actuarius** [comment]
@williewillus added labels [Cleanup, Bug]

**Comment by LexManos** [comment]
Ya a find/replace issue during the update.
