### ISSUE TITLE
getParticleTexture(IBlockState state) as a separate interface

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#2939]
Would come in very handy for models, for instance barrels with dynamically acquired wood textures.

There is only one patch required - in BlockModelShapes - I'm just curious as to whether that would be the right way to do it.

**Comment by rubensworks** [comment]
@asiekierka You could just override the methods `addLandingEffects`, `addHitEffects` and `addDestroyEffects` in `Block`. I think these are the only places where the particle texture is used.

But I agree that it might be nice to have a `getParticleTexture(IBlockState state)` method to have everything in one place.

**Comment by asiekierka** [comment]
In one place and for other mods to use when necessary, yes.

2016-06-03 12:06 GMT+02:00 Ruben Taelman <notifications@github.com>:

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]
