### ISSUE TITLE
BlockCactus calls canSustainPlant with a blockState and pos that don't match

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#2941]
https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/block/BlockCactus.java.patch#L18

In BlockCactus, `state` comes from `pos.down()`, but `canSustainPlant` is given `pos` instead of `pos.down()`. 
For every other call to `canSustainPlant`, they match.

**Comment by Actuarius** [comment]
@mezz added labels [Bug]

**Comment by Lazarix** [comment]
I am also experiencing this bug
