### ISSUE TITLE
Fluid cap-dyn bucket interop issues

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2944]
Consider a simple item that holds 1000 mB and reverts to a bowl on exhaust.

https://github.com/williewillus/Botania/blob/49a6f00b411d0ce7a32981c8543c334043375cfd/src/main/java/vazkii/botania/common/item/ItemWaterBowl.java

I use the dynbucket model for this.
However, I switch now to the new fluid caps, my bowl no longer renders with water inside.

I've traced it and the offending line is here:
https://github.com/MinecraftForge/MinecraftForge/blob/92914f82ae1e2ca007bdb9629611d120a4c58fe2/src/main/java/net/minecraftforge/fluids/capability/templates/FluidHandlerItemStackSimple.java#L120-L128

The dynamic bucket model determines whether to render the fluid layer or not by attempting to do a simulated drain of Int.max_value from the handler. however at the line shown the requested amount is compared to the handler's capacity (1000). This is not equal so the handler responds that nothing could be drained.

I think this is a logic issue but I haven't looked into it further - if this was intended behaviour it's quite unintuitive.

ping @mezz

**Comment by williewillus** [comment]
Maybe you meant to put something like 

`if (drainAmount <= contained.amount) {` ?

I'm not quite getting the purpose of the == check there

**Comment by williewillus** [comment]
In that case the check should be `>= capacity` instead of `== capacity` since `drainAmount` is simply an upper bound on the amount to drain. if the requestor asks for 2 billion and we have 1000 we should give it to them (provided maxDrain is appropriately set)

**Comment by mezz** [comment]
Look at the line above
```

**Comment by williewillus** [comment]
Yeah, ultra derp

The stacks I was testing with had bad NBT >.<, don't code at 1AM

Thanks for the help anyway
