### ISSUE TITLE
Blocks cannot specify custom colors for the beacon beam

### ISSUE THREAD

**Issue by yrsegal** [MinecraftForge/MinecraftForge#2949]

**Comment by williewillus** [comment]
You should include code points where you think hooks should be injected, the class where this issue appears, etc.

It's very hard to pinpoint things when all you have is a vague title and have to go search around yourself

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by yrsegal** [comment]
TileEntityBeacon#updateSegmentColors()

Blocks implementing this need to update the beacon beam when placed/removed (as in BlockStainedGlass) but that would probably be on the modder's part.

**Comment by gudenau** [comment]
Hey @williewillus could you do this please?

See my PR for details, just do it the right way please.

**Comment by williewillus** [comment]
what was wrong with your attempt? (besides the formatting)

**Comment by williewillus** [comment]
I tried doing it blind and came really close to what you already had :P

**Comment by gudenau** [comment]
I have no idea, but Lex won't ever accept any of my PRs.
