### ISSUE TITLE
Forge Crashes before window is created

### ISSUE THREAD

**Issue by mttprvst13** [MinecraftForge/MinecraftForge#2953]
I am working on a mod, and after doing a lot of coding, I finally tested it out. When I ran the code, though, it would crash for some reason. Here is the log: [http://pastebin.com/Mrtt4Zr0](http://pastebin.com/Mrtt4Zr0), and here is my build.gradle: [http://pastebin.com/P6TV99B8](http://pastebin.com/P6TV99B8). I have no clue if it has to do with on of the mods I am trying to include, or what, but it is continuously erroring. If you need to see the code, it is here: [https://github.com/mttprvst13/OneChunkCompanionMod](https://github.com/mttprvst13/OneChunkCompanionMod).

**Comment by williewillus** [comment]
1. 1.7.10 is not supported
2. Modder issues go on the forums or IRC not here

**Comment by Actuarius** [comment]
@williewillus closed this issue

**Comment by TehNut** [comment]
>at cofh.asm.CoFHAccessTransformer.transform(CoFHAccessTransformer.java:90) ~[CoFHCore-%5b1.7.10%5d3.1.2-325.jar:?]
