### ISSUE TITLE
Models loading and baking twice at startup

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2956]
This process currently happens twice

I propose that it be dummied out the first time around like the texture stitching.

On bigger modpacks (such as the one I'm on) doing this incurs a pretty huge overhead, because it's basically a _ton_ of IO access that immediately gets thrown out the window.

Loading times on huge packs like infinity are going to skyrocket if we don't have some way around this.

**Comment by Thog** [comment]
It's not a feature...

**Comment by williewillus** [comment]
Kinda is kinda isn't. Performance tag would be more appropriate

**Comment by Actuarius** [comment]
@williewillus added labels [Performance]

**Comment by williewillus** [comment]
Considering this closed for now by #3621
