### ISSUE TITLE
No (clean) way to migrate from external NBT to caps

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2957]
This is as far as my experiences tell me thus far, please correct me if I'm wrong.

Basically: If you have old data saved in item NBT and you want to transfer it to a cap and have it start saving in ForgeCaps, you're going to have a bad time.

Consider a backpack, where we saved everything as a tag list and that tag list is set under the stack tag compound as "Items".

``` js
{
    "id": "mymod:backpack",
    "Count": 1,
    "Damage": 0,
    "tag": {
         "Items": [
             { <each individual stack> }, ...
         ]
    },
    "ForgeCaps": {} // This tag doesn't exist in our pre-cap world
}
```

Then one day, caps are released. I'm overjoyed because I'm finally free from inventory hell...except that I have no way of migrating my data.

`Item.initCapabilities` is called. However, the stack received in the first parameter is not fully built yet - the stack tag compound "tag" has not been deserialized yet, and that is where my old data lives. For the second parameter, I'm passed a copy of the "ForgeCaps" tag as it was on disk. Because my backpack had no capabilities (and thus no "ForgeCaps" tag) the second parameter is null.

Is there a way I can get my old data into the cap system?

I know I can do something cheaty like listening in onUpdate, deleting the old tag, then slipstreaming the new data into the cap, but something more dedicated would be great.

Thanks!

**Comment by Choonster** [comment]
If Forge decides to do something with the data fixer system, this may be a good candidate. It may even be possible with the system as it is now, though I haven't looked at it in detail.

**Comment by GotoLink** [comment]
Also applies to conversion from IExtendedEntityProperties to Capability in Entity.

**Comment by williewillus** [comment]
Closing because it's already been quite a while since caps were released, and the compat hack I mentioned in the original ticket worked well enough as a stopgap
