### ISSUE TITLE
ArrayIndexOutOfBounds - ShapedOreRecipe

### ISSUE THREAD

**Issue by Lordmau5** [MinecraftForge/MinecraftForge#2958]
https://gist.github.com/Lordmau5/623d02569eae54f23d7e62e00e8593c8

Line being affected: https://github.com/MinecraftForge/MinecraftForge/blob/1.9.4/src/main/java/net/minecraftforge/oredict/ShapedOreRecipe.java#L205
Potentially other lines around that place as well.

**Comment by heldplayer** [comment]
Looks like a problem in ExtraUtilities2.

**Comment by Lordmau5** [comment]
Well, I can pull @rwtema into this, even though I doubt he's gonna give his two cents to this.

**Comment by LexManos** [comment]
Would not be a forge problem. Someone else is going in and modifying the interal arrays/code of this class. We can not support such hackery. Start killing off mods and see what happens.
