### ISSUE TITLE
FluidUtil.interactWithFluidHandler doesn't modify FluidTank in ItemStack 

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#2961]
When the `IFluidHandler` capability of an `ItemStack` is a `FluidTank` rather than a wrapper around the vanilla NBT (e.g. `FluidHandlerItemStack`), `FluidUtil.interactWithFluidHandler` won't modify its contents.

I use a `FluidTank` in the `ItemBlock` form of my fluid tank [here](https://github.com/Choonster/TestMod3/blob/87bd66f955bb309197edcdfc4d53e3ad164daa76/src/main/java/com/choonster/testmod3/item/block/ItemFluidTank.java#L72-L75) (`SimpleCapabilityProvider` simply provides a single capability handler instance) and interact with held fluid containers in the `Block` form [here](https://github.com/Choonster/TestMod3/blob/87bd66f955bb309197edcdfc4d53e3ad164daa76/src/main/java/com/choonster/testmod3/block/BlockFluidTank.java#L108-L126).

When I right click a tank block while holding a tank item, the block will be drained or filled but the item won't be modified.

**Comment by Actuarius** [comment]
@mezz assigned @mezz

**Comment by Actuarius** [comment]
@RainWarrior assigned @mezz

**Comment by AEnterprise** [comment]
seems like you guys had fun with the bot or the bot is having fun with asigning you guys :P

**Comment by mezz** [comment]
The bot can only assign people who have push access to Forge, but I was not aware of that and neither was the bot.

**Comment by mezz** [comment]
Superseded by PR #2976

**Comment by Actuarius** [comment]
@mezz added labels [Bug, Superseded]
