### ISSUE TITLE
Expose ItemStack#capabilities for custom ItemStack NBT serialization

### ISSUE THREAD

**Issue by raoulvdberge** [MinecraftForge/MinecraftForge#2964]
There is currently no way to serialize the capabilities on an ItemStack without calling `writeToNBT`.

For custom serialization, `writeToNBT` cannot be called.

**Comment by williewillus** [comment]
Why cant you writeToNBT then extract the "ForgeCaps" tag out of the result? WriteToNBT does a full save

**Comment by raoulvdberge** [comment]
> Why cant you writeToNBT then extract the "ForgeCaps" tag out of the result?

That would be kind of wasteful. Sure it's not that big of a performance hit since it's just writing values, but I'd rather just get the `ForgeCaps` immediately.

**Comment by raoulvdberge** [comment]
Now that I think about it, it doesn't have to be exposed. A method that returns `capabilities.serializeNBT()` in `ItemStack` would work too.

**Comment by williewillus** [comment]
I don't feel it's that wasteful.

An itemstack's serialized form is this:

* Registry name
* Damage 
* Count
* NBT tag which is already in NBT form (!)
* Caps in NBT form

So the "extra work" would be writing two more numbers and one more string

**Comment by asiekierka** [comment]
You can use an ICapabilityProvider - in fact, if you control the item, you are encouraged to do it instead of using events.

**Comment by raoulvdberge** [comment]
I don't control the item nor do I know what capabilities said item would have.

**Comment by williewillus** [comment]
I still stand by the opinion that extracting the tag from writetonbt is fine. The overhead is near zero I'm almost sure of it

**Comment by raoulvdberge** [comment]
It's not about overhead, it's about code simplicity / clearness. Sure I could write to a dummy tag and extract stuff from there, but that isn't clean at all.

As I said before, it's doesn't have to be exposed really, a  method that returns `capabilities.serializeNBT()` would be fine too.

**Comment by LexManos** [comment]
Why are you doing 'custom itemstack serialization'?

**Comment by raoulvdberge** [comment]
For getting around the stacksize size limitation

**Comment by LexManos** [comment]
stack size is public, just set it.. This doesn't need to do anything with Forge/capabilities.
