### ISSUE TITLE
AnvilUpdateEvent setCost not work?

### ISSUE THREAD

**Issue by cgcgbcbc** [MinecraftForge/MinecraftForge#2969]
I tried to call setCost but it does not actually modify the level cost

**Comment by cgcgbcbc** [comment]
The version is `1.9-12.16.1.1887`

I think the reason is that in function `updateRepairOutput`, although setCost modify the cost, but in the end of the function (L325) it set the cost to j+1 again.

**Comment by cgcgbcbc** [comment]
seems that I should set a output? But that's very hard since the original output is not passed into `AnvilUpdateEvent`, is this a bug?

**Comment by LexManos** [comment]
Not a bug, just how the hook is, getting the original output is not a simple task hook wise and would require us to basically re-write the whole function because it uses a lot of early escape functions.
If you can suggest a simple way to implement what you want, feel free to write a PR.

**Comment by cgcgbcbc** [comment]
@LexManos how about moving https://github.com/MinecraftForge/MinecraftForge/blob/b9ac73b0f1ac10b6d4cca8ac3771f2e0034597e4/patches/minecraft/net/minecraft/inventory/ContainerRepair.java.patch#L30 this line to the end of the function?

**Comment by williewillus** [comment]
no, then you can't cancel the event to prevent vanilla logic from running right?

**Comment by LexManos** [comment]
What part of 'it uses a lot of early escape functions' don't you get? There are like 6 'end of function' lines.

**Comment by cgcgbcbc** [comment]
> There are like 6 'end of function' lines

I mean the "real" end (above `this.detectAndSendChanges();`), since return in the middle is just setting the output to null in some edge case.

**Comment by cgcgbcbc** [comment]
> can't cancel the event

perhaps setting the output to null is equivalent to cancel the event?

**Comment by williewillus** [comment]
Anything that could possibly change existing behaviour is a no

**Comment by cgcgbcbc** [comment]
> Anything that could possibly change existing behaviour is a no

How about recalculate `j` after this [line](https://github.com/MinecraftForge/MinecraftForge/blob/6a3b734801746ba9695e2a0ad8cd55412a94245c/patches/minecraft/net/minecraft/inventory/ContainerRepair.java.patch#L30), i.e. copy this [line](https://github.com/MinecraftForge/MinecraftForge/blob/6a3b734801746ba9695e2a0ad8cd55412a94245c/patches/minecraft/net/minecraft/inventory/ContainerRepair.java.patch#L23) after that.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by mcenderdragon** [comment]
What about checking after the `onAnvilChange` call if maximumCost is not j (store this as boolean) and then dont call ` this.maximumCost = j + i;`
