### ISSUE TITLE
Allow mod items to dictate whether they are considered Shields

### ISSUE THREAD

**Issue by gabizou** [MinecraftForge/MinecraftForge#2971]
When an `EntityPlayer` is attacked, there is a handy method `damageShield(float)` that is called, but unfortunately, it is a hard coded check of the following:

```
if (damage >= 3.0F && this.activeItemStack != null && this.activeItemStack.getItem() == Items.SHIELD)
```

I'd propose a way for mod items to be "considered" shields for damaging since there already is a rudimentary check for the `EnumAction` of the active item, which can be returned as `EnumAction.BLOCK`.

Some ideas to move forward:
- Change the check for an `instanceof ItemShield`
- Change for a Forge added capability for shield handling
- Change for an event to be thrown with the provided active item stack and delegate that way
- Change to a new method: `this.activeItemStack.getItem().isShield(this.activeItemStack)`

As 1.10 was released today, I can imagine that this is going to be low priority, but it would be a feature none the less to benefit mod content.

**Comment by diesieben07** [comment]
Why not a method in Item like with armor, etc.? `Item#isShield(ItemStack)`

**Comment by williewillus** [comment]
I vote for event.
Looking at adding some shields but currently I can't override any vanilla behaviour at all. (and listening to livinghurtevent is too far away in the code)

**Comment by gabizou** [comment]
> Why not a method in Item like with armor, etc.? Item#isShield(ItemStack)

Added to the list of suggestions:



> I vote for event.
> Looking at adding some shields but currently I can't override any vanilla behaviour at all. (and listening to livinghurtevent is too far away in the code)

I'm somewhat partial to events since a singular event in this case for a shield being damaged is purely circumstantial, if only for determining the amount of damage being dealt to the `ItemStack`, and then perhaps determining how much of a damage reduction the shield will provide (further eliminating the silly hard codedness that is how shield block mechanics work.
```
if (source.isProjectile()) {
    amount = 0.0F;
} else {
    amount *= 0.33F;
```
From a customization standpoint, it'd be entirely possible to eliminate this damage source check and altogether call a new method:
```java
if (amount > 0.0F && this.canBlockDamageSource(source)) {
    amount = this.damageShieldAndReduceDamage(source, amount);
    if (!source.isProjectile()) {
        if (source.getSourceOfDamage() instanceof EntityLivingBase) {
            ((EntityLivingBase) source.getSourceOfDamage())
                    .knockBack((EntityLivingBase) (Object) this, 0.5F, this.posX - source.getSourceOfDamage().posX, this
                            .posZ - source.getSourceOfDamage().posZ);
        }
    }
    flag = true;
}
```

With the new method being specifically overridden in `EntityPlayer` to call the added `Item` method:
```java
public float damageItem(DamageSource source, float damage, int suggestedAmount, EntityLivingBase holder)
```
to where a simple delegation is written for vanilla items, but forge mods adding custom shields would now be able to handle how much damage they want to reduce based on the `DamageSource` and incoming damage, and of course, return the new damage.

**Comment by williewillus** [comment]
I'm not specifically talking about damaging the item, halving damage, or knocking back entities

I mean that, if I wanted to take my own custom actions when someone blocking with a shield is hit, I cannot right now

**Comment by gabizou** [comment]
> I mean that, if I wanted to take my own custom actions when someone blocking with a shield is hit, I cannot right now

So, you're talking about if I'm using an active item, you want to return a custom `EnumAction` when I get damaged to filter through the damage method?

**Comment by Syndaryl** [comment]
Spiked shields causing damage to the attacker, mirrored shields reflecting ghast blasts (or custom monster/weapon attacks), etc sound like obvious places for mod authors to go.

**Comment by williewillus** [comment]
ah I totally missed the original purpose of this PR, which is requesting an edit in damageShield for a generic isShield method. I wanted a general way of hooking into the shield blocking behaviour, which is done in EntityLivingBase.attackEntityFrom.

Disregard my prior comments

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by gabizou** [comment]
@williewillus I've got an idea for this capability, though I'd imagine at this point the feature addition would target 1.10, not 1.9.4, am I right?

**Comment by williewillus** [comment]
I presume both.

**Comment by Madsthunder** [comment]
Can be closed
