### ISSUE TITLE
ModelBakeEventDebug has black textures

### ISSUE THREAD

**Issue by lebertran** [MinecraftForge/MinecraftForge#2972]
The CustomModelBlock from the test mod ModelBakeEventDebug is completely black. This can be "fixed" by setting the applyDiffuseLighting parameter in the BakedQuad constructor to false. Last tested with Forge 1.9.4-1950.

![Example](http://i.imgbox.com/PHtzugIl.jpeg)

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by RainWarrior** [comment]
Can't reproduce on latest 1.11
