### ISSUE TITLE
Multiple item loot entries with the same item name are broken by Forge.

### ISSUE THREAD

**Issue by Zaggy1024** [MinecraftForge/MinecraftForge#2974]
The Forge loot entry "name" key (used as a unique ID for an entry for removal) and the vanilla "name" key (used by LootEntryItem for the item ID) conflict. This causes using the same item name twice in a pool to throw an error. Given that the same item ID can be used with different metadata or NBT (or even for different min/max count values), this complicates things quite a bit.

Relevant lines:
https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/world/storage/loot/LootEntryItem.java.patch#L28
https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/ForgeHooks.java#L1112

**Comment by blay09** [comment]
See #2860
