### ISSUE TITLE
[1.9] Issue with ItemStack capabilities updates in onUsingTick

### ISSUE THREAD

**Issue by P3pp3rF1y** [MinecraftForge/MinecraftForge#2975]
As of [fix](https://github.com/MinecraftForge/MinecraftForge/commit/9df1e4b11e0d2d0fbf938cedae2da130d40cca89) to ItemStack.areItemStackTagsEqual there is an issue now with SPacketSetSlot packet being sent to client whenever capabilities update on Server even if the rest of ItemStack stays the same given that the same method is used to figure out if the packet needs to be sent. 

This causes bad behavior if capability gets updated in onUsingTick (the same bad behavior that NBT udpates do and which I was hoping capabilities could help with solving and did before this change)

I am not completely sure if this was intended to change the way packets work, but it looks to me that a different method needs to be used now to compare the stacks that will ignore capability changes for the purpose of figuring out if packets with itemstack data need to be sent.

**Comment by LexManos** [comment]
If you update the nbt, it sends it to the client. This is how MC works. Im not sure we care to change it.

**Comment by P3pp3rF1y** [comment]
But the issue here is that capabilities nbt doesn't get synced to client in these packets. So it basically detects change in capabilities and syncs the same packet without capabilities data that client already received previously and thus no nbt change sent in those - just deletes capability data on client when this is done.

**Comment by LexManos** [comment]
Caps are stored in the NBT using the standard serialization functions.
I'll look into it, but it should be syncing everything fine.

**Comment by P3pp3rF1y** [comment]
The packets writes the compound with standard buffer method:
`
buf.writeItemStackToBuffer(this.item); 
`
which internally does this:
`
            if(stack.getItem().isDamageable() || stack.getItem().getShareTag()) {
                nbttagcompound = stack.getTagCompound();
            }
            this.writeNBTTagCompoundToBuffer(nbttagcompound);
`
and ItemStack.getTagCompound reads the data from ItemStack.stackTagCompound so only stack NBT data not capNBT. 

At least that's what I see when going through the code and that's what I see sent in the packet in debug. 

Also forge docs say that capabilities syncing needs to be done via special packets so I assumed it's not wanted  to sync them to client the same way as stack NBT.

**Comment by P3pp3rF1y** [comment]
And would you mind reopening this one so that it doesn't fall through the cracks?

**Comment by AEnterprise** [comment]
@P3pp3rF1y give someone who can re-open issues the time to see this, most people don't check github every hour and also have other things to do

**Comment by P3pp3rF1y** [comment]
I didn't want to be pushy or get it done right now, if it sounded like that it's my bad. Just that Lex commented on the issue after it was closed and it sounded like he will look into it on a side without reopening it.

**Comment by P3pp3rF1y** [comment]
@LexManos have you perhaps found out anything about this?

I actually liked that capability changes previously didn't cause update packets to be sent. As that makes them perfect for keeping data that needs to be changed during onUsingTick. 

So my vote would be to not sync capabilities to client automatically (and stop capability changes triggering update packets) and have mod devs sync only data they need to client using their own packets.

The reason for that being that I have some items in mod that have hold right click functionality that uses their charge and at least for some the charge used doesn't depend on just how long the right click was held and thus can't rely on just ticks in use I get in onPlayerStoppedUsing. And ItemStack capabilities seem like a perfect match for that. If they could not be used in this case then I guess the other option would be to use player capabilities, track the data there and then read from there and write to itemstack when player stops using the item.

**Comment by diesieben07** [comment]
It would also make it consistent with every other capability provider, where no magic syncing takes place.

**Comment by LexManos** [comment]
Havent looked at it. But this is a lot of magic that has to be specialcased for itemstacks it's getting rather fucking annoying.
I'll look at it eventually but not a high priority right now.

**Comment by P3pp3rF1y** [comment]
So I have spent a bit of time looking through code for where ItemStacks are being synced to client. 
This is [gist with notes for all occurences](https://gist.github.com/P3pp3rF1y/e4830a82d3ed9733f08fafe3b7e084db).

Out of this investigation there are two places that would need to change to avoid sending packets to client when only capabilities get changed on server in EntityLivingBase.onUpdate and EntityPlayerMP.sendSlotContents. 

In both cases it uses ItemStack.areItemStacksEqual. 

So my thought would be to add a new overload to the method with additional parameter (compareCapabilities?) by default set to true. Then have these two places call it with false. And in areItemStacksEqual return true right before capabilities comparison if capabilities are not to be compared.

Looks like a 5 line change so if that sounds cool to you I will write a PR with the change.

**Comment by williewillus** [comment]
This was intentionally changed to the current behaviour because containers with changing caps were not synchronized properly.
-1 from me for this

**Comment by P3pp3rF1y** [comment]
But how does it synchronize caps today when it doesn't send caps NBT over to client? 
It only writes ItemStack.stackTagCompound to the buffer (in addition to item and meta) and nothing for caps so the only result of reading such a packet on client is that it would delete whatever capabilities data would get there some other way.

Maybe I am missing something, but that's what I see in code and when debugging it.

**Comment by P3pp3rF1y** [comment]
Ohh, I may see what you mean in Container.detectAndSendChanges, it's not syncing to client, but syncing of itemstack inventory with slots.

This code is inside the condition. That certainly should execute when the capabilities change.
```
itemstack1 = itemstack == null ? null : itemstack.copy();
this.inventoryItemStacks.set(i, itemstack1);
```

So in that case there would need to be additional check around this code to make sure that it doesn't get triggered when only capabilities change.

```
for (int j = 0; j < this.listeners.size(); ++j)
{
    ((IContainerListener)this.listeners.get(j)).sendSlotContents(this, i, itemstack1);
}
```

**Comment by williewillus** [comment]
That part of the code isn't relevant. Its synced properly precisely *because* ItemStack.areItemStacksEqual was patched to check caps. That behaviour is important for many items.

**Comment by P3pp3rF1y** [comment]
Well, as I said previously neither of these packets include ItemStack capNBT, they only have item, meta and stackTagCompound. So unless I am missing something the only thing they do today when caps changes is that they resync what client already has and delete any cap data from client that was synced there using some other way. 

The reason I even started looking into this was that my cap data is getting deleted on client and thus items that need to check for it on client don't work. And yes I am using my own packet to sync cap data to client.

**Comment by feldim2425** [comment]
I have the same problem. The initCapabilities() method gets called every tick. But it only happens if something gets changed in the capability and stored in NBT Data.

**Comment by P3pp3rF1y** [comment]
@williewillus where in the forge do the ItemStack capabilities get synced to client? If you have example of an item that relies on that I would like to take a look as that definitely isn't the case for any of my items that have capabilities.

And now that I am actually trying to implement a workaround for this I am feeling more and more that capability changes shouldn't cause sync packets to be sent and that mod devs should be taking care of that. 

The reason is that the only reasonable workaround I can think of is storing data in player capabilities and modifying it there while the item is in use and then get the data back to the item when player stops using it.
However that basically means that for every item that has charge and non trivial (not just time based) use of this charge on hold right click we would be getting new capability on player. 
Some additional notes on that:
- if item can be dual wielded and used at the same time in both hands facing needs to be used to differentiate (e.g. East - Main hand, West - off hand)
- that also means that if the same capability is used by multiple items there can only be up to 3 items in a mod that have onusingtick functionality that uses charge (or there needs to be a different capability created)
- if the capability used by the item is one that is general (like ItemHandler one that I use for my item) there can only ever be one mod in the pack that will use item's charge stored there in a mod pack, if there were two they would very likely break each other by providing wrong implementations (or again there would need to be a different capability implemented for storing the data on player which would complicate the code even more)

There is more on this, but basically with this workaround the code is becoming mess that can pretty easily break. 

And as a side note the method today compares even capabilities that are not serializable which means that even those would need to be stored on player if changed in onUsingTick.
