### ISSUE TITLE
Item overrides broken on all non-builtin/generated models

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#2977]
My case:
* Have an item that has some property overrides (`addPropertyOverride`)
* Have a complex (non-builtin/generated) vanilla json model with overrides specified in the json: https://github.com/williewillus/Botania/blob/5f35b8aef0d473979429493c545057b2242e4925/src/main/resources/assets/botania/models/item/manaGun.json#L1-L1

What I expect to happen:
* My overrides apply

What actually happens:
* My `IItemPropertyGetters` are not even called in code

Why does it happen (traced using a debugger):
* Offending line here: https://github.com/MinecraftForge/MinecraftForge/blob/4248dbc71d77a8288029a7d4612d7a13eaef04f7/src/main/java/net/minecraftforge/client/model/animation/AnimationItemOverrideList.java#L62
* Vanilla-format models' override lists seems to be wrapped in an `AnimationItemOverrideList`, but when the animation cap isn't found it doesn't defer to super, it just returns the original model as-is

Fix: replace `return originalModel` with `return super.handleItemState`
cc @RainWarrior

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by williewillus** [comment]
Also, not sure why it doesn't happen to vanilla's own items (bow, etc.)
According to some discussion on IRC it seems to happen for non-builtin/generated models only, builtin/generated models are fine. Not sure why.

**Comment by OrionDevelopment** [comment]
@williewillus Since when does the vanilla bow animation use a AnimationItemOverrideList? As far as i am aware it uses a standard ItemOverrideList with a IItemProperty.

**Comment by williewillus** [comment]
@OrionDevelopment Forge wraps everything in its own wrappers. It does this for many of the model system's classes, you just aren't aware of it ;p (which is good)

**Comment by OrionDevelopment** [comment]
Allright, just wanted to know was digging into Animation today when i saw this post.
Thanks for the Intel though :P

**Comment by williewillus** [comment]
Okay some further investigation has shown:
builtin/generated models are not affected by this issue because they are baked separately in ModelLoader.bake(). The offensive wrapping occurs for non builtin/entity and non builtin/generated models in ModelLoader.bakeNormal().

I also have a PR for this, as I need this fix in ASAP.
