### ISSUE TITLE
Ticking screen error when trying to join on LAN

### ISSUE THREAD

**Issue by scienceman217** [MinecraftForge/MinecraftForge#2981]
I am currently using the Resonant Rise 3 pack from the AT launcher with a few custom mods added. When I or my girlfriend try to connect to the other's world over lan, we get this in the error logs. 
[crash-2016-06-10_23.00.16-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/310565/crash-2016-06-10_23.00.16-client.txt)

We eventually reinstalled the launcher and were able to play for a solid couple of hours, but had to restart because my game (not the host) kept freezing to the point it was unplayable. we both restarted and got this error again. Any ideas?

**Comment by GirafiStudios** [comment]
This is not the place to report this. You should report it on the Minecraft Forge forums. When that is said, this is most likely caused by one of the mods in the pack you're playing and not Forge.

**Comment by scienceman217** [comment]
Thanks! I apologize. Still newish to all this.
