### ISSUE TITLE
LivingSpawnEvent.SpecialSpawn gets incorrect Y coordinate

### ISSUE THREAD

**Issue by Barteks2x** [MinecraftForge/MinecraftForge#2986]
https://github.com/MinecraftForge/MinecraftForge/blob/dd09da27b5fd52348e1aecf7f0c4b40b45cc8e2a/patches/minecraft/net/minecraft/world/WorldEntitySpawner.java.patch#L31:
```java
if (!net.minecraftforge.event.ForgeEventFactory.doSpecialSpawn(entityliving, p_77192_1_, f, l3, f1))
```
`l3` is not Y coordinate, it's (as I understand the code) random number of mob spawn attempts. `i3` is the Y coordinate.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]
