### ISSUE TITLE
Canceling render events still renders shadows

### ISSUE THREAD

**Issue by darkhax** [MinecraftForge/MinecraftForge#2987]
If you cancel the render events, the shadows will still be rendered. This happens when canceling either RenderLivingEvent.Pre and RenderPlayerEvent.Pre. Cancelling the Specials pre events also has no effect on entity shadows.

**Comment by diesieben07** [comment]
I don't know if there is an easy way to fix this, since the shadow is rendered completely separate from the `doRender` method...
