### ISSUE TITLE
Delayed Update of client light level on some chunks

### ISSUE THREAD

**Issue by Abastro** [MinecraftForge/MinecraftForge#2991]
MC 1.9.4 and Forge 1963,
It takes a while for light levels of chunks to be updated.
![2016-06-16_15 43 16](https://cloud.githubusercontent.com/assets/5730296/16107723/32482552-33d9-11e6-9007-3fea4b99568f.png)
![2016-06-16_15 43 24](https://cloud.githubusercontent.com/assets/5730296/16107724/327426b6-33d9-11e6-9ef7-fea5009194f5.png)
[fml-client-latest.log.txt](https://github.com/MinecraftForge/MinecraftForge/files/317797/fml-client-latest.log.txt)

**Comment by Barteks2x** [comment]
That seems to be vanilla bug: https://bugs.mojang.com/browse/MC-91136

**Comment by Actuarius** [comment]
@williewillus added labels [Vanilla Bug]
