### ISSUE TITLE
Fluid models rendering with gaps

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#2993]
Under some circumstances, fluids are being rendered with gaps between blocks.

Screenshot:
![2016-06-17_17 31 34](https://cloud.githubusercontent.com/assets/878073/16143696/c3f955f6-34b1-11e6-9bb9-4024d5063c1d.png)

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by MCrafterzz** [comment]
Why haven't anyone fixed this?

**Comment by Leviathan143** [comment]
@MCrafterzz 
https://github.com/MinecraftForge/MinecraftForge/issues/assigned/RainWarrior
Rain has a lot to do, be patient.

**Comment by williewillus** [comment]
He is also out until later this month

**Comment by bogger33** [comment]
So the culprit here is shouldSideBeRendered in BlockFluidClassic, which has the following check:

    if (neighbor.getMaterial() == state.getMaterial())
    {
        return false;
    }

However, this check ignores the scenario in which the fluid doesn't have a smooth transition from one height to another, that is to say when the side of a fluid block isn't the same as that of the fluid block next to it. I'm not super familiar with this codebase, but you can fix most rendering issues like this:


	if (neighbor.getMaterial() == state.getMaterial())
	{
		if(side != EnumFacing.UP && side != EnumFacing.DOWN)
		{
			IBlockState above = world.getBlockState(pos.offset(EnumFacing.UP));
			IBlockState diagonal = world.getBlockState(pos.offset(EnumFacing.UP).offset(side));
			if(above.getMaterial() == state.getMaterial() && diagonal.getMaterial() != state.getMaterial())
				return true;
		}
	    return false;
	}

So this basically checks whether the the block that's being rendered is sandwiched in between two fluid materials in a downwards diagonal, and if so, it renders the side. I say that this fixes most rendering issues because you do still get little artifacts when looking at fluids with a 90-degree corner

![gap](https://cloud.githubusercontent.com/assets/10445063/23406611/15f7ad80-fdc0-11e6-995d-4c07b8f852e3.png)

Not immediately sure how you would fix that, but this little change should make a big difference already


Edit: I experimented with it some more, and it should be noted that this fix will render the whole side, rather than just the part that needs to be rendered, which is ugly when you are dealing with a transparent liquid. So this is not a proper fix, more of a hack. However, if you are writing a mod with a non-transparent liquid, you could extend your BlockLiquidBasic class with my code as a workaround

Also, apparently even vanilla water has the issue with 90-degree angles causing artifacts

**Comment by HenryLoenwind** [comment]
The fluid rendering already has a way to calculate the y-max for a side, seems it also needs a z-min calculation to fix his. @bogger33, it seems you identified all error cases for single-fluid rendering, what about multi-fluid rendering? Although, for my fluids I fix that one by replacing the "same material" check with a "same block" check. I feel that gives the better render (with sides completely rendered that face a different fluid) than rendering a y-range only.

Update: Looking at the pic in that other ticket, I'd say the error is a different one. Fluid blocks that connect to a "down flow" block (y=0-1, not 0-0.9 like "full" blocks) should also render to y=1, not just the "full block height". Same if the connect to fluid above a solid block.

**Comment by bogger33** [comment]
I'm not sure if I'm misunderstanding your update, but my code does fix the error in the other ticket (besides it having the still texture and rendering the full length of the side) - by rendering the side of the block sitting behind the two diagonal ones. Can you clarify what you mean? The problem might just be that I don't grasp how the entirety of the rendering process works just yet

**Comment by HenryLoenwind** [comment]
https://imgur.com/a/xvR9A

See how fluid source blocks and "downflow" blocks (blocks that have fluid directly above them) have a different height? And how the flowing blocks next to them render differently to accommodate that?

**Comment by bogger33** [comment]
right I get it now, so basically, the problem is with the blocks horizontally next to downflow blocks, not the downflow blocks themselves (which is what my hack changes). These just always need to start at 1.

**Comment by HenryLoenwind** [comment]
Not "always", but when the block above their neighbor is a (same kind) fluid block, too. If it isn't, and they start "high" because their neighbor is a source (=full) block, then starting at that "nearly top" is fine and correct.

I'd say that is exactly the same case in #3740.

**Comment by bogger33** [comment]
So I added the following check to right before state is being set at the end of getExtendedState:

    @Override
    public IBlockState getExtendedState(IBlockState oldState, IBlockAccess worldIn, BlockPos pos)
    {
        IExtendedBlockState state = (IExtendedBlockState)oldState;
        state = state.withProperty(FLOW_DIRECTION, (float)getFlowDirection(worldIn, pos));
        float[][][] height = new float[3][2][3];
        float[][] corner = new float[2][2];
        height[1][0][1] = getFluidHeightForRender(worldIn, pos);
        if(height[1][0][1] == 1)
        {
            for(int i = 0; i < 2; i++)
            {
                for(int j = 0; j < 2; j++)
                {
                    corner[i][j] = 1;
                }
            }
        }
        else
        {
            for(int i = 0; i < 3; i++)
            {
                for(int j = 0; j < 3; j++)
                {
                    if(i != 1 || j != 1)
                    {
                        height[i][0][j] = getFluidHeightForRender(worldIn, pos.add(i - 1, 0, j - 1));
                        height[i][1][j] = getFluidHeightForRender(worldIn, pos.add(i - 1, 1, j - 1));
                    }
                }
            }
            for(int i = 0; i < 2; i++)
            {
                for(int j = 0; j < 2; j++)
                {
                    corner[i][j] = getFluidHeightAverage(height[i][0][j], height[i][0][j + 1], height[i + 1][0][j], height[i + 1][0][j + 1]);
                }
            }
        }
        
        //check for downflow above corners
        if(height[0][1][0] != 0.0 || height[0][1][1] != 0.0 || height[1][1][0] != 0.0) corner[0][0] = 1;
        if(height[0][1][1] != 0.0 || height[0][1][2] != 0.0 || height[1][1][2] != 0.0) corner[0][1] = 1;
        if(height[1][1][0] != 0.0 || height[2][1][0] != 0.0 || height[2][1][1] != 0.0) corner[1][0] = 1;
        if(height[2][1][1] != 0.0 || height[1][1][2] != 0.0 || height[2][1][2] != 0.0) corner[1][1] = 1;
        state = state.withProperty(LEVEL_CORNERS[0], corner[0][0]);
        state = state.withProperty(LEVEL_CORNERS[1], corner[0][1]);
        state = state.withProperty(LEVEL_CORNERS[2], corner[1][1]);
        state = state.withProperty(LEVEL_CORNERS[3], corner[1][0]);
        return state;
    }


This does seem to fix all rendering issues in terms of gaps, however it seems that getFluidHeightForRender() isn't exactly what I thought it was and doesn't seem to be 0 for non-fluid blocks, at least not always - so it messes up near full blocks. For other fluids I'm not sure what the behaviour should be at all. The code seems to indicate that it doesn't care what fluid it is for calculating the levels (although as previously pointed out it might look better rendering the sides during transitions) 

I think if you undo my changes to the height array and just check for block type like I did in my previous attempt at fixing this, it should prooobably work fine. Does this look conceptually sound? It makes sense to me but like I said, I'm new to the forge codebase and modding in general

Edit:

This could possibly be the code that fixes this bug - but I still have to test multiple fluids, as well as negative density fluids



    private boolean isCoveredWithFluid(IBlockAccess world, BlockPos pos)
    {
        IBlockState here = world.getBlockState(pos);
        IBlockState up = world.getBlockState(pos.down(densityDir));
        if (here.getBlock() == this && (up.getMaterial().isLiquid() || up.getBlock() instanceof IFluidBlock))
        {
                return true;
        }
        return false;
    }
    
    @Override
    public IBlockState getExtendedState(IBlockState oldState, IBlockAccess worldIn, BlockPos pos)
    {
        IExtendedBlockState state = (IExtendedBlockState)oldState;
        state = state.withProperty(FLOW_DIRECTION, (float)getFlowDirection(worldIn, pos));
        float[][] height = new float[3][3];
        float[][] corner = new float[2][2];
        height[1][1] = getFluidHeightForRender(worldIn, pos);
        if(height[1][1] == 1)
        {
            for(int i = 0; i < 2; i++)
            {
                for(int j = 0; j < 2; j++)
                {
                    corner[i][j] = 1;
                }
            }
        }
        else
        {
            for(int i = 0; i < 3; i++)
            {
                for(int j = 0; j < 3; j++)
                {
                    if(i != 1 || j != 1)
                    {
                        height[i][j] = getFluidHeightForRender(worldIn, pos.add(i - 1, 0, j - 1));
                    }
                }
            }
            for(int i = 0; i < 2; i++)
            {
                for(int j = 0; j < 2; j++)
                {
                    corner[i][j] = getFluidHeightAverage(height[i][j], height[i][j + 1], height[i + 1][j], height[i + 1][j + 1]);
                }
            }
        }
        
        //check for downflow above corners
        if(isCoveredWithFluid(worldIn, pos.add(-1, 0, -1)) || isCoveredWithFluid(worldIn, pos.add(-1, 0,  0)) || isCoveredWithFluid(worldIn, pos.add(0, 0, -1)))
            corner[0][0] = 1;
        if(isCoveredWithFluid(worldIn, pos.add(-1, 0,  0)) || isCoveredWithFluid(worldIn, pos.add(-1, 0,  1)) || isCoveredWithFluid(worldIn, pos.add(0, 0,  1)))
            corner[0][1] = 1;
        if(isCoveredWithFluid(worldIn, pos.add( 0, 0, -1)) || isCoveredWithFluid(worldIn, pos.add( 1, 0, -1)) || isCoveredWithFluid(worldIn, pos.add(1, 0,  0)))
            corner[1][0] = 1;
        if(isCoveredWithFluid(worldIn, pos.add( 1, 0,  0)) || isCoveredWithFluid(worldIn, pos.add( 0, 0,  1)) || isCoveredWithFluid(worldIn, pos.add(1, 0,  1)))
            corner[1][1] = 1;

        state = state.withProperty(LEVEL_CORNERS[0], corner[0][0]);
        state = state.withProperty(LEVEL_CORNERS[1], corner[0][1]);
        state = state.withProperty(LEVEL_CORNERS[2], corner[1][1]);
        state = state.withProperty(LEVEL_CORNERS[3], corner[1][0]);
        return state;
    }

**Comment by mezz** [comment]
@bogger33 When you've pinned it down, feel free to make a PR here. It's easier to review the code that way.

**Comment by mezz** [comment]
Looks like they already made a PR here: #3747
