### ISSUE TITLE
Strange bug with server loading

### ISSUE THREAD

**Issue by miuirussia** [MinecraftForge/MinecraftForge#2995]
Can someone tell, what mod doing that?
[fml-client-latest.txt](https://github.com/MinecraftForge/MinecraftForge/files/321216/fml-client-latest.txt)

**Comment by iLexiconn** [comment]
Not the place for support, use the forums instead

**Comment by miuirussia** [comment]
In log Forge issue

**Comment by iLexiconn** [comment]
It's probably a mod adding a wrong item to the ore dict or something, either way it's not a Forge issue.

**Comment by LexManos** [comment]
Use the forums to do basic debugging.
