### ISSUE TITLE
Map system signals to meaningful Forge events.

### ISSUE THREAD

**Issue by AnrDaemon** [MinecraftForge/MinecraftForge#2998]
[Java](http://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html#BABHDABI) [provides](http://docs.oracle.com/javase/8/docs/technotes/tools/unix/java.html#BABHDABI) application with a way (-Xrs) to trap system signals, such as SIGTERM, and meaningfully react to them rather than terminate abruptly.
It would be wonderful, if Forge could do something actually useful in reaction to f.e. SIGTERM and SIGHUP, rather than collapse in an instant.
Would make it hell of  a lot easier to host servers as actual services.

**Comment by LexManos** [comment]
Why?
And you can install your own single handlers, if you're single casing this for your specific hosting needs you don't need Forge in the middle mitigating things....
What it sounds like you're asking for is the hooks that already exist in the JVM itself...

**Comment by AnrDaemon** [comment]
Existing hooks, or your own custom hooks, Forge doesn't use either.
It just flops when JVM catches TERM or HUP.
And this is not "specific" hosting needs, it is a standard good behavior of application to gracefully terminate on SIGTERM.
The config reload on SIGHUP is more a convention for services, than an actual standard, but I believe it is also universally good event, that more than one mod could utilize.
Together, they would allow to drop the ugly wrapping scripts and just launch MC server directly as a system service, drastically simplifying maintenance and usability.

**Comment by LexManos** [comment]
Again, you can handle these events yourself in the system level hooks.
Forge does not need to add any extra events for this.
There is no need for us to translate 'ShutDownHook' -> FORGE_BUS.push(ForgeJVMShutdownEvent())

**Comment by AnrDaemon** [comment]
Are you suggesting to write a mod that translate SIGTERM into a /stop command?
Why Forge doesn't do that by itself already?

**Comment by williewillus** [comment]
You should be asking vanilla that

**Comment by LexManos** [comment]
Again, if you wish to handle system events you can hook into the system events using normal java mechanics.
Translating SIGTERM to /stop would not work as it's on completely separate threads and would have to do a lot more then that.
You want special cased for your hosting service, come in here with vague 'you should do the thing but i dont know what the thing is so DO THE THING!' 
Not gunna fly.
