### ISSUE TITLE
Modstats

### ISSUE THREAD

**Issue by xJon** [MinecraftForge/MinecraftForge#3000]
What's that thing, and if Forge is pinging it address - why?
A lot of antiviruses have it blacklisted, including Avast and ESET.
![image](https://cloud.githubusercontent.com/assets/8945347/16174907/217355f6-35e3-11e6-86ec-84762c7b6a99.png)
```
[05:58:58] [Thread-42/INFO] [FML/]: [Modstats] Stat wasn't reported 'Server returned HTTP response code: 403 for URL: http://sso.anbtr.com/domain/modstats.org
```

**Comment by LexManos** [comment]
Forge is not pining anything, One of the mods you have instlled is.
Do not post issues like this on Github, only use this for things that are verified to be Forge issues.

**Comment by xJon** [comment]
Thanks for the reply
