### ISSUE TITLE
Crash when digging blocks with extended state?

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3008]
Have a model that lazy-loads (Botania special flowers)

Seems to crash when digging.

Perhaps due to this (ForgeHooksClient)?

```
public static IBakedModel getDamageModel(IBakedModel ibakedmodel, TextureAtlasSprite texture, IBlockState state, IBlockAccess world, BlockPos pos)
{
        // TODO custom damage models
        // state = state.block.getExtendedState(state, world, pos);
        return (new SimpleBakedModel.Builder(state, ibakedmodel, texture, pos)).makeBakedModel();
}
```

**Comment by williewillus** [comment]
Trace: https://gist.github.com/anonymous/c33698652c09a41fcf4716b4e9f73485

**Comment by williewillus** [comment]
it seems the state passed into getQuads has the values for one of my extended properties set to null, which is interesting because I set the default value to "daybloom"

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by bs2609** [comment]
Did #3086 fix this?

**Comment by williewillus** [comment]
not sure, let me check

**Comment by williewillus** [comment]
I think so, the place where I had a workaround no longer has the workaround there :P
