### ISSUE TITLE
Elytra glitch into wall and fall into void through blocks

### ISSUE THREAD

**Issue by ZiggyAdventures** [MinecraftForge/MinecraftForge#3011]
#### Issue Description:

I realize this is most likely a vanilla induced bug, but just in case it can be fixed. Thank you for the awesome job!

While using Elytra or the Blood Magic Equivalent with High Speed Boost(Testing suggested around 150% speed boost), rarely while ramming a corner of a wall, the player would fall through blocks into the void. The player sees the outline of blocks above them, visually teleporting upwards and downwards underneath the blocks or bedrock, dying to void damage at very negative y height. Happens in both multiplayer and single player. Usually caused by players who are flying in unrendered chunks unknowingly into walls, or in caves.

---
#### Affected Versions
- Minecraft: 1.9.4
- Forge: forge-12.17.0.1973

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by ZiggyAdventures** [comment]
Closing due to not being relevant in 1.10.2 and up.
