### ISSUE TITLE
[Regression] Crash on startup

### ISSUE THREAD

**Issue by c0rn3j** [MinecraftForge/MinecraftForge#3014]
Client side, didn't test server.
Crash log: http://pastebin.com/u7HgUgmN

Versions tested(1969 loads fine, 1980 crashes): http://i.imgur.com/P8czhEz.png 

Mods in use(didn't test without): http://i.imgur.com/vNlOowH.png

**Comment by covers1624** [comment]
Really? Try without mods, this is a mod specific issue and is best solved on the forums.

**Comment by luacs1998** [comment]
PlayerOpenContainer was removed in the relicense.

Someone needs to re-implement it.

**Comment by cpw** [comment]
A mod author who wishes to reinstate a feature removed due to the relicense is welcome to contribute a new PR. As it is, this is working as intended.

**Comment by diesieben07** [comment]
> Someone needs to re-implement it.

Not sure if needed, you can accomplish the same thing with `PlayerTickEvent`, and less event spam per tick is good.

**Comment by luacs1998** [comment]
#3017
