### ISSUE TITLE
[1.10] Dupe Glitch

### ISSUE THREAD

**Issue by mcNETDev** [MinecraftForge/MinecraftForge#3015]
I installed a fresh version(12.18.0.1982) of Minecraft Forge and started a new World with no mods.

When i pickup any items it will double the amount of items into my Inventory.

No errors will show up in the logs.

Here a quick demo: https://www.youtube.com/watch?v=AGsJd6LIPE8

**Comment by bluemonster122** [comment]
I just found this and laughed. So i have experience this too

**Comment by Melakion** [comment]
/give command will do the same thing, and occasionally drop the item in the world which can't be picked up, but fills your inventory with the item.

**Comment by Actuarius** [comment]
@mezz added labels [Bug]
