### ISSUE TITLE
We've been building 1.9.4 builds on the 1.10 branch

### ISSUE THREAD

**Issue by Matts** [MinecraftForge/MinecraftForge#3021]
"I wonder if this is a attempt to make forge 1.9.4 compatable with 1.10 versions and the other way around"

See 12.17.0.1978 & 12.17.0.1980

http://i.imgur.com/eHBeh4W.png

*crashlog*
http://pastebin.com/v98Q250d

**Comment by cpw** [comment]
Not a bug. You shouldn't be building off branches unless you know what you're doing. The 1.10.0 branch had specific goals, which included fixing up the licensing, work that had to take place prior to merging in the 1.10 changes.

**Comment by gigaherz** [comment]
Uhh Matts didn't explain properly: there's builds downloadable from the files site, under 1.9.4, that were built from the 1.10 branch.

**Comment by Matts** [comment]
Lol indeed sorry <3

**Comment by gigaherz** [comment]
![builds](https://cloud.githubusercontent.com/assets/685851/16322011/9326f1ec-39a0-11e6-970f-c93869096c91.png)

**Comment by LexManos** [comment]
Its because he pushed to the 1.10.0 branch without disabeling jenkins, ignore it.

**Comment by Matts** [comment]
Yeah just im worried because its on the latest download list of 1.9 & 1.9.4 some people who may be novice to forge may download the version that doesn't work 😁

**Comment by LexManos** [comment]
These versions should work just fine.
No code was changed in these builds just license headers.

**Comment by jriwanek** [comment]
Actually 3 commits were removed. Says so in the 1978 changelog.

**Comment by HenryLoenwind** [comment]
We are flooded with crash reports from these versions...

**Comment by jriwanek** [comment]
Also, can confirm this is an issue, (not to add to the deluge): We've had users connecting to our server using said builds and crashing.

**Comment by LexManos** [comment]
Meh, i've nuked the builds as they are not needed.
Shouldnt be an issue.
