### ISSUE TITLE
Forge could terminate gracefully on signals

### ISSUE THREAD

**Issue by Baughn** [MinecraftForge/MinecraftForge#3027]
At present, if Java receives a terminating signal (e.g. because the machine is shutting down, or someone pressed ctrl-c, or an explicit kill, or...), Java's default shutdown handler is invoked.

This sort of works; Vanilla has logic for it, which attempts to save all the worlds and shutdown gracefully. Unfortunately, that is more than can be said for _every_ mod. Some do fine, others throw exceptions. (Example: https://github.com/Chicken-Bones/CodeChickenLib/issues/61)

One solution is to catch the signals, and translate them into regular shutdown as if the user had typed `stop` at the console.

I've written a minimal mod to do so: http://sprunge.us/TMUU

...but IMO, this fits better into Forge itself.

**Comment by AEnterprise** [comment]
duplicate of #2998 , they already said they would not implement this

**Comment by Baughn** [comment]
Hmm~

Not quite a duplicate, I think. That one didn't make its case very well, and didn't include code. SIGTERM is the standard way to programmatically shut down applications across all unix systems. Not windows, since it doesn't exist there, but I think a majority of minecraft servers run on Linux.

More concerningly, vanilla Minecraft does provide a handler for sigterm, via Java's addShutdownHook. Forge doesn't break it, but some mods do. I'm offering a way to un-break it.

I suppose the ideal would be to fix it at the mod level, but that doesn't seem likely to happen.

---

And that's all I'll say on the subject unless asked. I've got this fixed for myself, now; as LexManos pointed out, it absolutely can be done in a mod. The main reason for putting the code inside Forge would be so *every* server gets this benefit.

**Comment by cpw** [comment]
Is this happening with any contemporary mod? Why is chicken bones throwing exceptions? Making the existing shutdown handling robust to mod error is OK, adding weird assed signal handling to forge for an abandoned mod that was questionable even when not abandoned is not.

**Comment by Baughn** [comment]
I assume that, by contemporary, you mean 1.9 series?

I might be able to tell you that once there is an 1.9 modpack to test on. Can't really say right now. Though I don't think SIGTERM handling counts as "weird-assed"; it's very much the standard thing to do on unix systems, for all applications.

**Comment by MrDiamond123** [comment]
If the mods where doing something at the time that is critical, it could corrupet worlds and maybe the whole game to the point that removing the mod won't help.
