### ISSUE TITLE
[1.10] Zombies of Husk type render as standard zombies

### ISSUE THREAD

**Issue by gigaherz** [MinecraftForge/MinecraftForge#3028]
Quick investigation brought me to `func_189777_di` not returning `HUSK`. I didn't follow the issue any further.

**Comment by williewillus** [comment]
Probably related to the fact forge patches zombies to use villager registry for skins...but husks don't have an equivalent villager

**Comment by HenryLoenwind** [comment]
it's this code in the VillagerRgeistry:

```
        if (prof == null)
        {
            if (entity.func_189777_di() != ZombieType.NORMAL)
                entity.func_189778_a(ZombieType.NORMAL);
            return;
        }
```

**Comment by LexManos** [comment]
Ya, mistake in the re-write of this. I'd prefer a better way of detecthing this like having the ZombieType being NORMAL, HUSK, VILLAGER, and the sub-type of villager using the same registry as villagers, but whatever Mojang.
