### ISSUE TITLE
Crash with Liteloader 1.10 + forge build 1995

### ISSUE THREAD

**Issue by Coolboy21** [MinecraftForge/MinecraftForge#3029]
I have a crash using Liteloader1.10+forge build 1995 and macros mod v0.13.0.
http://pastebin.com/S3wX7nSQ
I wrote the developer MacrosMod and Liteloader - Mumfrey, his answer: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1275039-macro-keybind-mod?comment=15033
I hope you manage to find the bug and fix it.

**Comment by LexManos** [comment]
As it sits, He is lookign into it, it is a issue caused in the MixinCode, we do not support coremods. 
If this IS a Forge issue, which I highly doubt, Mimfrey knows how to report it properly.
