### ISSUE TITLE
When I compile my mod, my item textures are not working

### ISSUE THREAD

**Issue by LKloosterman** [MinecraftForge/MinecraftForge#3047]
After learning how 1.9 works I decided to see if I could create a simple "Obsidian Tools" mod, just to see if I've got the hang of how things work. When I run the client version in the development environment everything works perfectly, textures and everything, but when I compile the mod the textures don't show up.

I can't give any crash logs or error information because there aren't any problems being thrown at me. I checked in the jar and the assets folder with the models and textures is in there with the files and everything, but I'm probably overlooking something stupid. 

If I can provide any further information or if you need code snippets I can provide them, just ask.

**Comment by diesieben07** [comment]
Use the forum for help with development, this is for issues with forge.

**Comment by Actuarius** [comment]
@diesieben07 closed this issue

**Comment by LKloosterman** [comment]
@diesieben07 My apologies!
