### ISSUE TITLE
Extreme high village buildings when "baseSize" is set below default in customized preset

### ISSUE THREAD

**Issue by skyli91** [MinecraftForge/MinecraftForge#3050]
In vanilla, everything works fine(same preset):
![2016-06-30_00 43 47](https://cloud.githubusercontent.com/assets/7442913/16471441/04e32a60-3e5d-11e6-9309-00e769dc85d3.png)

But if I set "baseSize":5.901408 and for example: "seaLevel":50(the bug is not from changing sealevel but the basesize), this happens with Forge: 
![image](https://cloud.githubusercontent.com/assets/7442913/16471504/6d2d966e-3e5d-11e6-9f09-c361db20165f.png)

**Comment by ezterry** [comment]
Do you have the full generation customization string, seed, and cords of this village?

**Comment by skyli91** [comment]
{"coordinateScale"\:684.412,"heightScale"\:684.412,"lowerLimitScale"\:458.6549,"upperLimitScale"\:423.45068,"depthNoiseScaleX"\:212.16197,"depthNoiseScaleZ"\:212.16197,"depthNoiseScaleExponent"\:0.71387327,"mainNoiseScaleX"\:80.0,"mainNoiseScaleY"\:212.22534,"mainNoiseScaleZ"\:80.0,"baseSize"\:5.901408,"stretchY"\:8.811057,"biomeDepthWeight"\:1.34,"biomeDepthOffset"\:0.56338024,"biomeScaleWeight"\:4.2112675,"biomeScaleOffset"\:0.0,"seaLevel"\:51,"useCaves"\:true,"useDungeons"\:true,"dungeonChance"\:100,"useStrongholds"\:true,"useVillages"\:true,"useMineShafts"\:true,"useTemples"\:true,"useMonuments"\:true,"useRavines"\:false,"useWaterLakes"\:true,"waterLakeChance"\:5,"useLavaLakes"\:true,"lavaLakeChance"\:94,"useLavaOceans"\:false,"fixedBiome"\:-1,"biomeSize"\:4,"riverSize"\:4,"dirtSize"\:33,"dirtCount"\:23,"dirtMinHeight"\:48,"dirtMaxHeight"\:256,"gravelSize"\:50,"gravelCount"\:7,"gravelMinHeight"\:0,"gravelMaxHeight"\:136,"graniteSize"\:33,"graniteCount"\:14,"graniteMinHeight"\:0,"graniteMaxHeight"\:193,"dioriteSize"\:33,"dioriteCount"\:23,"dioriteMinHeight"\:0,"dioriteMaxHeight"\:255,"andesiteSize"\:33,"andesiteCount"\:19,"andesiteMinHeight"\:0,"andesiteMaxHeight"\:229,"coalSize"\:22,"coalCount"\:40,"coalMinHeight"\:34,"coalMaxHeight"\:141,"ironSize"\:14,"ironCount"\:40,"ironMinHeight"\:0,"ironMaxHeight"\:91,"goldSize"\:9,"goldCount"\:18,"goldMinHeight"\:0,"goldMaxHeight"\:255,"redstoneSize"\:10,"redstoneCount"\:25,"redstoneMinHeight"\:0,"redstoneMaxHeight"\:48,"diamondSize"\:5,"diamondCount"\:30,"diamondMinHeight"\:161,"diamondMaxHeight"\:255,"lapisSize"\:7,"lapisCount"\:15,"lapisCenterHeight"\:23,"lapisSpread"\:50}

Any seed with any village does this. This particular is 3607256501170886309 coords: -300,700

**Comment by LexManos** [comment]
Bug IS from changing the sea level.

**Comment by skyli91** [comment]
oh then i'm stupid :D thank you very much!

**Comment by skyli91** [comment]
but it's not just on 1.10, it's in 1.9 too and maybe 1.8(haven't tested 1.8)?
