### ISSUE TITLE
updateJSON in mcmod.info isn't used.

### ISSUE THREAD

**Issue by Nokiyen** [MinecraftForge/MinecraftForge#3053]
1.10.2-12.18.0.2005

updateJSON value located in mcmod.info file is not used for checking each mod's version.

updateJSON value in @ mod annotation is used correctly.
This might be caused in net.minecraftforge.fml.common.FMLModContainer.bindMetadata() and getUpdateUrl(). In these methods, only updateJSON in the annotation is involved and that in mcmod.info(modMetadata) is not checked.

**Comment by LexManos** [comment]
Nope, it's not.It was never designed to be from the json.

**Comment by Nokiyen** [comment]
Oh really? I just misunderstood it because ModMetadata class has updateJSON as its field.
