### ISSUE TITLE
[Idea] Add ItemAllowBlocking 

### ISSUE THREAD

**Issue by MrDiamond123** [MinecraftForge/MinecraftForge#3056]
There should be a way to allow mods to have items that can block like swords did in 1.8.9 and under.

**Comment by diesieben07** [comment]
There is nothing stopping you.

**Comment by MrDiamond123** [comment]
@diesieben07 I mean as a thing that doesn't need to be coded in the mod fully.

It should be in forge.

**Comment by williewillus** [comment]
I have no idea what this is proposing. EnumAction.BLOCK still exists

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by Madsthunder** [comment]
#4126

**Comment by Madsthunder** [comment]
Can be closed
