### ISSUE TITLE
[1.10.2] Cannot open chest with slab on above

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#3057]
Using Forge Build 2006.

![2559-07-02_19 27 33](https://cloud.githubusercontent.com/assets/6128413/16540334/5dac83dc-408b-11e6-807d-e34fe95e27c8.png)

**Comment by diesieben07** [comment]
Why is this brought up again every single version update?
This is intentional. Slabs are solid on the bottom, hence chests cannot be opened. If the slab is on the top part of the block then the chest can be opened (since the bottom of an upside-down slab is not solid).

**Comment by williewillus** [comment]
^ because it breaks vanilla behaviour

**Comment by covers1624** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/2820#issuecomment-217060795
