### ISSUE TITLE
SlotItemHandler can't replace items that are being held

### ISSUE THREAD

**Issue by raoulvdberge** [MinecraftForge/MinecraftForge#3059]
Mentioned this on the IRC chat and someone was able to reproduce.

A GIF is worth a thousand words:

![demo](http://i.imgur.com/JhI3OO8.gif)

As you see, I can't replace the iron with the iron trapdoors and vice-versa.

**Comment by AlexIIL** [comment]
It seems to be because the implementation of "isItemValid" in SlotItemHandler should return true instead of checking to see if the item matches.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by raoulvdberge** [comment]
Fixed with #3273
