### ISSUE TITLE
[1.9.4] (end?) oregen not working

### ISSUE THREAD

**Issue by ThatGamerBlue** [MinecraftForge/MinecraftForge#3065]
Title, no logs to say anything went wrong, using forge version 12.17.0.1976.

Example repo showing error (for me at least): https://github.com/ThatGamerBlue/amethyst

EDIT: Also happens with 12.18.0.2000 [1.10]

**Comment by diesieben07** [comment]
You already had a thread on the forums, this is not an issue with forge.
If you had posted your code in a usable git repo earlier I could have told you already: 2 is too small of a vein size. Make it bigger.

**Comment by ThatGamerBlue** [comment]
Oh ok, sorry, I thought it was a forge issue, didn't consider the vein size. /closed
