### ISSUE TITLE
[1.10.2, 1.9.4] Remove @SideOnly(Side.CLIENT) on ItemArmor.getEquipmentSlot()

### ISSUE THREAD

**Issue by Corosauce** [MinecraftForge/MinecraftForge#3066]
Didn't see a way to make a PR for this kind of thing, so heres a quick issue on it.

**Comment by kashike** [comment]
You can create a PR like you would with anything else. [Here](https://github.com/MinecraftForge/MinecraftForge/pull/2729/files) is an example.

**Comment by Corosauce** [comment]
Ahhhh right, the patches themselves dont add the SideOnlys but I could adjust the existing ItemArmor patch to actually remove them since they support going about it that way, I will go ahead and make a patch adjustment for that and PR it later today unless someone beats me to it, thanks!

**Comment by Actuarius** [comment]
@williewillus added labels [Cleanup]
