### ISSUE TITLE
[1.10.2] java.io.IOException: Stream closed On Exiting Minecraft

### ISSUE THREAD

**Issue by SnowShock35** [MinecraftForge/MinecraftForge#3068]
Hello,

I believe I've found a bug in [MinecraftForge](https://github.com/MinecraftForge/MinecraftForge) for Minecraft 1.10.2. I've listed further information below regarding the issue...

### Key Info

* Minecraft 1.10.2
* Minecraft Forge 12.18.0.2007

### Issue Description

On exiting Minecraft (Using the Quit Game button on the main menu) the launcher log is repeatedly spammed with the following `[17:29:31 ERROR]: java.io.IOException: Stream closed`. It does this perhaps 100 times before stopping (The amount it prints to the log seems to vary from time to time). 

I've tried to recreate  this issue without Forge installed and doesn't appear to occur which is why I lead to the conclusion of this being a bug with Forge itself.

### Additional Sources

* Launcher Log (Where the issue is occurring): http://pastebin.com/mAZc8pRh
* FML Client Latest Log (Incase necessary): http://pastebin.com/fNLveiE2

**Comment by LexManos** [comment]
Not reproducible, and this is happening on the launcher end not Forge. There isn't much we can do about that.
Us the forums to do basic debugging first before coming here to report issues you think are Forge.
