### ISSUE TITLE
StackOverflowError when accessing blockstate in TileEntity#onLoad

### ISSUE THREAD

**Issue by PaleoCrafter** [MinecraftForge/MinecraftForge#3075]
It appears like `TileEntity#onLoad` is called too early to do anything meaningful with when the world initially is loading. Simply accessing the associated tile entity's state (e.g. through `TileEntity#getBlockType`) results in a StackOverflowError due the chunk not being properly loaded yet.

The detailed crash report can be found [here](https://gist.github.com/PaleoCrafter/7b68f0a0cf35bce3b7fba8cf12d975f6). The game does not crash completely and the `fml-client-latest.log` does not contain any related information since only the internal server crashes.

One might argue that one should simply not access the world in this method, but then it would not serve its purpose as a "first tick check" replacement appropriately.

**Comment by shadowfacts** [comment]
#2365 

This has been known for a long time and isn't going to be fixed.

**Comment by PaleoCrafter** [comment]
Whoops, didn't see that. Thanks!
