### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MidnightKittyCat** [MinecraftForge/MinecraftForge#3077]
So I have a crash...

http://pastebin.com/MwHSyzjK

And I'm sorry if this isn't the right place to post my problem... Also I don't know anything about codes :s

**Comment by williewillus** [comment]
One of your mods is broken - which one isn't really clear from the log

**Comment by MidnightKittyCat** [comment]
Thanks a lot! I don't know which it is either, bu at least now I have an idea of what the problem is!
Also, I'm sorry for the wrong post place. I didn't know where to post it. I'll close it later, but for now I want to see if someone else knows what to do. Do you have any idea of how can I fix this? Thanks in advance.

**Comment by AEnterprise** [comment]
@MidnightKittyCat as you opened the issue you can close it yourself

your log doesn't show what mod is crashing but you don't have alot of mods, i sugest you remove them all and load each one seperatly to find the one that crashes

**Comment by iTitus** [comment]
I would advise you to use the forums for that.
