### ISSUE TITLE
[Suggestion] Provide access to vanilla sky renderers

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#3080]
At present, Forge allows you to either provide your own custom implementation of these renderers, or use the default behavior. The issue is the vanilla renderers are chained to vanilla logic, so, for example, there is no way to use the sky from the End without appearing as the End to all vanilla code (and possibly code from other mods too).

The suggestion would be to provide something like an IRenderHandler wrapper for the vanilla renderers, so they can be used independently.

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]
