### ISSUE TITLE
[1.10.2] Vanilla client support breaks player 1/4 of the time

### ISSUE THREAD

**Issue by Corosauce** [MinecraftForge/MinecraftForge#3084]
When connecting with a vanilla 1.10.2 client to a forge server that has either no mods or server side only mods. The player state is severely broken at least 1/4 of the time. The player entity is connected into the server, but has no player actually ticking. Evidence of this can be seen by the inability to pickup items, or getting "player moved too quickly" upon teleporting. You can interact with chests and other things.

Unable to reproduce with modded forge client, only occurs with vanilla client.

I suspect this is due to how the connection is negotiated between vanilla client and forge server, relating to checking for the FML marker etc, just a guess though.

I have reproduced the issue on build 2005 and 2011 (latest as of this post)

Steps to reproduce:

1. Get forge mdk environment setup.
2. Launch vanilla client instance running MC 1.10.2
3. Run the forge server from the dev environment.
4. Connect to locally hosted server with vanilla client.
5. Attempt to pickup item off the ground (if you cannot, the issue has occured).

At this point if the issue occured you can debug the server state to see that no player events or entity onUpdates for player are being run while you wander around the server.

Happens intermittently, so try steps 3-5 until it occurs, usually only takes me 3 tries before it happens. I restart the server each time between attempts.

**Comment by cpw** [comment]
Hmmm, is it actually that the client thinks the world is running but the server thinks it's still connecting? Does the client see any updates, or did it just get an initial chunk load? Log files on the server would be interesting too..

**Comment by Corosauce** [comment]
I definitely get updates, I can break blocks, and see the dirt items pop and everything, here is a log from me connecting, the issue triggering, me trying to toss down items, break dirt, trying to pickup items but it not happening: https://gist.githubusercontent.com/Corosauce/c0fa69286a0d88882b15cf29d1b48dec/raw/78f99ced4da1fb87084ebb1063cba1091d368529/gistfile1.txt

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by Corosauce** [comment]
In an effort to get this fixed I have started debugging the call stack myself, I have discovered a bit more.

The entityplayer is partially ticking, the parents EntityPlayerMP.onUpdate is called, but EntityPlayer.onUpdate is not, as that one is called via onUpdateEntity, and NetHandlerPlayServer is actually responsible for that one. 

Upon further digging, I have discovered that this line of code is forever true during the problem: https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java#L212

So I guess you were partially correct about the server still being in a weird state where it thinks its still connecting. 

this.playerEntity.connection is not null, but it is a different instance, not sure why.

Going to continue to report findings here in hopes that someone with experience with this code can chime in with a proper fix, if not I will attempt to provide my own fix.

**Comment by Corosauce** [comment]
Aha, I think this is a bug from migrating that code from a patch to being in a different, class, since connection and 'this' arent the same type of objects anyways, as per this commit: https://github.com/MinecraftForge/MinecraftForge/commit/98f606d4d2e8217ab685610a669d2ec28f484bda

**Comment by Corosauce** [comment]
For some reason, threads "Server thread" and "Netty Server IO #1" are both trying to process the same packet and do the same connection handshake negotiation. Causing the problem race condition that sometimes occurs due to 2 threads setting various things for the same objects. Why both threads are processing the same packets I am not sure, I need to dig even deeper to find out why, might be by design and this packet needs additional filtering for all I know.

I was debugging the output of what all is setting the player.connection field, noticed 2 sets of things occuring which was odd:

non issue:

NetworkManager.setNetHandler set this.packetListener to net.minecraft.server.network.NetHandlerHandshakeTCP@71e41cc1
NetworkManager.setNetHandler set this.packetListener to net.minecraft.server.network.NetHandlerLoginServer@7d639252
[13:21:42] [User Authenticator #1/INFO]: UUID of player Corosus is e0bc7f7a-0d68-4e85-bbc4-8bd17e52e9e5
NetworkManager.setNetHandler set this.packetListener to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@63795470
NetworkManager.setNetHandler set this.packetListener to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@5d39a9e6
NetHandlerPlayServer set connection to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@63795470
NetHandlerPlayServer set connection to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@5d39a9e6
serverInitiateHandshake set connection to null, old was: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@63795470
serverInitiateHandshake created instance for later: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@5d39a9e6
serverInitiateHandshake set connection to null, old was: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@5d39a9e6
serverInitiateHandshake created instance for later: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@5d39a9e6
[13:21:42] [Server thread/INFO] [FML]: Connection received without FML marker, assuming vanilla.
[13:21:42] [Server thread/INFO] [FML]: [Server thread] Server side vanilla connection established
[13:21:42] [Server thread/INFO]: Corosus[/127.0.0.1:50065] logged in with entity id 42 at (90.21167802398182, 64.0, -85.42426652636992)
PlayerList.initializeConnectionToPlayer set connection to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@5d39a9e6
[13:21:42] [Server thread/INFO]: Corosus joined the game
this.playerEntity.connection: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@5d39a9e6
this: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@5d39a9e6
serverHandler: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@5d39a9e6

issue:
NetworkManager.setNetHandler set this.packetListener to net.minecraft.server.network.NetHandlerHandshakeTCP@29de99f2
NetworkManager.setNetHandler set this.packetListener to net.minecraft.server.network.NetHandlerLoginServer@2769e7ae
[13:23:29] [User Authenticator #1/INFO]: UUID of player Corosus is e0bc7f7a-0d68-4e85-bbc4-8bd17e52e9e5
NetworkManager.setNetHandler set this.packetListener to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@7454f47c
NetworkManager.setNetHandler set this.packetListener to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@78105f44
NetHandlerPlayServer set connection to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@78105f44
NetHandlerPlayServer set connection to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@7454f47c
serverInitiateHandshake set connection to null, old was: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@7454f47c
serverInitiateHandshake set connection to null, old was: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@7454f47c
serverInitiateHandshake created instance for later: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@7454f47c
serverInitiateHandshake created instance for later: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@7454f47c
[13:23:29] [Server thread/INFO] [FML]: Connection received without FML marker, assuming vanilla.
[13:23:29] [Server thread/INFO] [FML]: [Server thread] Server side vanilla connection established
[13:23:29] [Server thread/INFO]: Corosus[/127.0.0.1:50225] logged in with entity id 42 at (90.21285316691107, 64.0, -85.40541067814053)
PlayerList.initializeConnectionToPlayer set connection to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@7454f47c
[13:23:29] [Server thread/INFO]: Corosus joined the game
this.playerEntity.connection: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@7454f47c
this: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@78105f44
serverHandler: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@7454f47c


Decided to dig deeper and see why 2 sets were running, found out it was those 2 threads I mentioned above, even more debug output on those with stack traces to show more about each thread in play, stack tracing at the top of serverInitiateHandshake at first, and for anything that called NetworkManager.setNetHandler, the stacktrace got a little weird as both threads were outputting the exact same time mixing the traces together:

[13:45:47] [User Authenticator #1/INFO]: UUID of player Corosus is e0bc7f7a-0d68-4e85-bbc4-8bd17e52e9e5
serverInitiateHandshake stack trace: 
thread name: Server thread
java.lang.Thread.getStackTrace(Unknown Source)
net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverInitiateHandshake(NetworkDispatcher.java:207)
net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverToClientHandshake(NetworkDispatcher.java:163)
net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.fmlServerHandshake(FMLNetworkHandler.java:72)
net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(NetHandlerLoginServer.java:137)
net.minecraft.server.network.NetHandlerLoginServer.update(NetHandlerLoginServer.java:64)
net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:322)
net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:195)
net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:811)
net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:411)
net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:692)
net.minecraft.server.MinecraftServer.run(MinecraftServer.java:541)
java.lang.Thread.run(Unknown Source)
serverInitiateHandshake stack trace: 
thread name: Netty Server IO #1
java.lang.Thread.getStackTrace(Unknown Source)
net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverInitiateHandshake(NetworkDispatcher.java:207)
net.minecraftforge.fml.common.network.handshake.FMLHandshakeServerState$1.accept(FMLHandshakeServerState.java:46)
net.minecraftforge.fml.common.network.handshake.FMLHandshakeServerState$1.accept(FMLHandshakeServerState.java:1)
net.minecraftforge.fml.common.network.handshake.HandshakeMessageHandler.userEventTriggered(HandshakeMessageHandler.java:63)
io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:304)
io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:290)
io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:304)
io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:290)
io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:304)
io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:290)
io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:781)
net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handlerAdded(NetworkDispatcher.java:196)
io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:486)
io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:44)
io.netty.channel.DefaultChannelPipeline$3.run(DefaultChannelPipeline.java:476)
io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
java.lang.Thread.run(Unknown Source)
NetworkManager.setNetHandler set this.packetListener to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@3d81511
NetworkManager.setNetHandler set this.packetListener to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@328ea25e
thread name: Netty Server IO #1
thread name: Server thread
java.lang.Thread.getStackTrace(Unknown Source)
java.lang.Thread.getStackTrace(Unknown Source)
net.minecraft.network.NetworkManager.setNetHandler(NetworkManager.java:181)
net.minecraft.network.NetworkManager.setNetHandler(NetworkManager.java:181)
net.minecraft.network.NetHandlerPlayServer.<init>(NetHandlerPlayServer.java:167)
net.minecraft.network.NetHandlerPlayServer.<init>(NetHandlerPlayServer.java:167)
net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.<init>(NetworkDispatcher.java:218)
net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.<init>(NetworkDispatcher.java:218)
net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverInitiateHandshake(NetworkDispatcher.java:218)
net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverInitiateHandshake(NetworkDispatcher.java:218)
net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverToClientHandshake(NetworkDispatcher.java:163)
net.minecraftforge.fml.common.network.handshake.FMLHandshakeServerState$1.accept(FMLHandshakeServerState.java:46)
net.minecraftforge.fml.common.network.handshake.FMLHandshakeServerState$1.accept(FMLHandshakeServerState.java:1)
net.minecraftforge.fml.common.network.handshake.HandshakeMessageHandler.userEventTriggered(HandshakeMessageHandler.java:63)
net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.fmlServerHandshake(FMLNetworkHandler.java:72)
io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:304)
net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(NetHandlerLoginServer.java:137)
io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:290)
net.minecraft.server.network.NetHandlerLoginServer.update(NetHandlerLoginServer.java:64)
io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:322)
io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:304)
net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:195)
io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:290)
net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:811)
io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:411)
io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:304)
net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:692)
io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:290)
net.minecraft.server.MinecraftServer.run(MinecraftServer.java:541)
io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:781)
java.lang.Thread.run(Unknown Source)
net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handlerAdded(NetworkDispatcher.java:196)
io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:486)
io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:44)
io.netty.channel.DefaultChannelPipeline$3.run(DefaultChannelPipeline.java:476)
io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
NetHandlerPlayServer set connection to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@328ea25e
java.lang.Thread.run(Unknown Source)
NetHandlerPlayServer set connection to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@3d81511
serverInitiateHandshake set connection to null, old was: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@328ea25e
serverInitiateHandshake set connection to null, old was: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@3d81511
serverInitiateHandshake created instance for later: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@3d81511
serverInitiateHandshake created instance for later: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@3d81511
[13:45:47] [Server thread/INFO] [FML]: Connection received without FML marker, assuming vanilla.
[13:45:47] [Server thread/INFO] [FML]: [Server thread] Server side vanilla connection established
[13:45:47] [Server thread/INFO]: Corosus[/127.0.0.1:51064] logged in with entity id 42 at (90.21455188594389, 64.0, -85.38587416499078)
PlayerList.initializeConnectionToPlayer set connection to net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@3d81511
[13:45:47] [Server thread/INFO]: Corosus joined the game
this.playerEntity.connection: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@3d81511
this: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@3d81511
serverHandler: net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1@3d81511

**Comment by Corosauce** [comment]
Lex's suggestion of moving insertIntoChannel() into the NOOP area I think he meant seems to have done the trick, will test more in forge/non forge client mode then move to PR.

**Comment by Guard13007** [comment]
Other than a player not being able to do certain actions in-game, does this pose any threat to a vanilla player? A friend of mine alerted me to this issue since I'm running a server like this. I thought it was worse than it sounds here. Should I be telling players to only connect with a Forge client?

**Comment by Corosauce** [comment]
You could either just tell them to reconnect and see if they can pickup an item on join. Or just use a forge client yeah.

**Comment by LexManos** [comment]
Vanilla clients should be able to do everything that isnt mod related on connecting.... Either way I *THINK* this should work, by fixing the race condition so...
