### ISSUE TITLE
[1.10.2] Setting an player to ride another player issue

### ISSUE THREAD

**Issue by palaster** [MinecraftForge/MinecraftForge#3094]
I have an item in my mod that sets an player(1) to start riding another player(2). When the item is used the player(1) using it starts riding another player(2). On the rider(1) side he rides the player(2) normally sitting on the other player(2) head and is able to dismount at any time, but on the player(2) side he isn't being ridden and it looks like nothing happens and the player(1) is still in the same spot, not even in the sitting animation. I thought at first that I wasn't syncing correctly, but then I involved a third player(3) in the situation to watch the other two. He(3) saw what was supposed to happen the first player(1) started riding on top of the second player(2). So, there is something fishy  with the second player(2), the player being ridden, not being update correctly.

This is the code I am using : http://pastebin.com/QjURGnHP.

**Comment by williewillus** [comment]
could be the vanilla mounting bug that's been appearing since 1.9.x

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]
