### ISSUE TITLE
Player armor calculations do not respect new 1.9 mechanisms

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3095]
ISpecialArmor.ArmorProperties.applyArmor, called for player armor calculations does not respect attribute modifiers for the ARMOR and ARMOR_TOUGHNESS attributes added in 1.9.

This means vanilla things will break in forge because items with armor attribute modifiers, etc. do not work on players.

**Comment by Flaxbeard** [comment]
Worth mentioning that ForgeHooks.getTotalArmorValue also does not respect attribute modifiers for the ARMOR attribute

**Comment by LexManos** [comment]
Pretty sure I rewrote all that to support the new systems 1.9 put into place. Comparing it to vanilla all the while.
If it not how you expect it to be shoot a PR in and we can take a look.

**Comment by Flaxbeard** [comment]
Just looking into it quickly, in EntityPlayer.damageEntity, [Forge replaces a call to applyArmorCalculations with ArmorProperties.applyArmor call](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch#L205). EntityLivingBase.applyArmorCalculations, which doesn't look at armor items at all, instead looking at the entity's ARMOR and ARMOR_TOUGHNESS attributes. ArmorProperties.applyArmor references armor items and not the attributes.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by Flaxbeard** [comment]
Just noting that this issue is still present in 1.10.2. It's particularly important because it means that Forge handles player armor in an entirely different way than vanilla Minecraft - anything that impacts the ARMOR or ARMOR_TOUGHNESS attribute in vanilla MC (ie, a held sword with modified NBT tag) will have an effect on the player but will not while Forge is installed.

I've looked into PRing the applyArmor function, but ISpecialArmor's code is particularly esoteric.

**Comment by mezz** [comment]
This is still a present issue, see #3629

**Comment by williewillus** [comment]
looking at it more closely the problem is here: https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/common/ISpecialArmor.java#L140

ItemArmor is casted to directly retrieve the field, whereas in 1.9+ the `armor.damageReduceAmount` field is fed as a linear modifier to the ARMOR attribute.

In addition, the armor toughness attribute is not considered at all by ISpecialArmor.

**Comment by williewillus** [comment]
Because of how flexible attribute modifiers can be I'm not sure how this can be cleanly resolved. 
For linear (+ x) attribute modifiers you could pass that value into ArmorProperties instead, but what about multiplicative attribute modifiers?

**Comment by williewillus** [comment]
Also, this prevents vanilla diamond armor from working as it does in vanilla, since the toughness attribute is not checked.

**Comment by Insane96** [comment]
I hope this will be fixed ASAP as you can't play custom maps with custom items that have Armor (Toughness) attributes

**Comment by Insane96** [comment]
Still in Forge as 13.20.0.2255
Found this #2765 Pull Request too with the fixes, but needs to be updated for 1.11.2
