### ISSUE TITLE
Provide a setter for EntityPlayerMP.invulnerableDimensionChange

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#3096]
The `EntityPlayerMP` class has a `private boolean invulnerableDimensionChange` field. The field is set to true by the `EntityPlayerMP#changeDimension(int)` method, and is read (and also cleared) through public accessor methods `isInvulnerableDimensionChange()` and `clearInvulnerableDimensionChange()` by `NetHandlerPlayServer`.

I think not setting this is causing 'Player moved wrongly!' messages to occur when teleporting players, but as the field is private it can only be set internally, and `changeDimension()` is set to only teleport players using the default teleporter.

Adding a public `setInvulnerableDimensionChange(boolean)` method would allow modded code to set this to true, and hopefully prevent teleporting issues.

**Comment by williewillus** [comment]
this is part of mojang's flaky hackaround for the 1.9 nether portal teleport bug, so I'm not sure exposing to modders would do the original problem any more good. The moved wrongly messages are a vanilla thing I'm almost sure of it

**Comment by bs2609** [comment]
I guess this issue might be related:
[https://bugs.mojang.com/browse/MC-92437](url)
