### ISSUE TITLE
Research how to unregister dimensions

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3097]
the enum DimensionType has a todo "can't really unregister dimensions". This can be a potential pain point for mods that create lots of ad-hoc, temporary dimensions like DimDoors or AE2. 

We need to figure out a way to unregister dims, perhaps ditching vanilla's enum entirely and using our own system. Or maybe patching it into a class (provided nothing switches on it or does enum specific calls). Just throwing out ideas.

**Comment by bs2609** [comment]
There is a distinction between dimension types and dimensions though. Do those mods actually need multiple dimension types?

**Comment by williewillus** [comment]
the dimensiontype enum is also a holder for the integer dimension ID

**Comment by LexManos** [comment]
That shouldnt be the case, we go through every usage of the Type vs Real ID and fix them up.
So @bs2609 is correct, you cant unregister TYPES but you can unregister dimensions in our dimension manager.

**Comment by williewillus** [comment]
ah was unaware we went through and fixed the dimensiontypes
