### ISSUE TITLE
Minecraft 1.10 Forge 12.18.1.2014 Creative Menu 2 Leggings No Chestplate Slot

### ISSUE THREAD

**Issue by davibu** [MinecraftForge/MinecraftForge#3102]
In Creative in the Survival Inventory you only have 2 legging armor slots and no Chestplate Slot, but as it seems it's just a
 wrong icon.
![2016-07-18_16 17 20](https://cloud.githubusercontent.com/assets/9825602/16917788/5cd022e6-4d03-11e6-8958-6652134b60a9.png)

**Comment by blay09** [comment]
Not a Forge Bug. See https://github.com/Vazkii/Charset/issues/8
