### ISSUE TITLE
Feature Request: FastTESR for entities

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3103]
Similar to how we have FastTESR's, it would be nice to have "fast entity renderers" that are batched together. 

Some of my entities only render a flat sprite or baked model directly from the atlas. Redoing that every frame is wasteful, and doing it multiple times every entity is super wasteful. A common use case for this is rendering of Botania spark entities. It's just a 64x64 animated sprite from the atlas but put a ton of them together and people complain about the lag.

Ideally we'd have some block-level caching going on but for now batching would be an improvement.

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]

**Comment by RANKSHANK** [comment]
Does this mean entityItems would be batched?

**Comment by williewillus** [comment]
Potentially

**Comment by RANKSHANK** [comment]
Interesting. If that's the case with regards to #3093 it's looking more and more like I need a custom ResourceLocation implementation that caches an id to String value for custom effect textures for faster comparability.

**Comment by mezz** [comment]
This is still relevant.

**Comment by mcenderdragon** [comment]
When we are doing something like this, we could also try to improve the vanilla EntityModels, they are supper slow if you have eg 24 boxes for a block, at a 5x5x5 cube you can notice significant lag.

Also regarding the TESR: One main problem I am seeing with this is we can only bind one texture while rendering. I dont know if ts better for items to bind the item texture or the block texture. Maybe wee need two passes with both textures to render everything.
Also we have different VertexFormats. Creating an all prupose TESR is difficult but we could start with batching all item rendering.

**Comment by HenryLoenwind** [comment]
@mcenderdragon um, there's only one texture sheet for items and blocks since 1.8.0...

@williewillus if you're rendering a flat sprite, I'd recommend to put that into the block texture map and render it using a particle in fx layer 1. Those *are* batched. You can keep a reference to your particle in your client (tile)entity to spawn/despawn it in sync with the (tile)entity.

**Comment by mcenderdragon** [comment]
THere is only one? Nice. (I though there were two because there are two Texture Fields available.)
