### ISSUE TITLE
[Feature request] Add getStackStringForDisplay

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3106]
So there are getDurabilityForDisplay, you can do almost the same with the string that displays stack size in inventory rendering.
Add this method to Item class

``` java
public String getStackStringForDisplay(ItemStack stack, String originalString) {
    return originalString;
}
```

And then insert a call to it in RenderItem#renderItemOverlayIntoGUI as you do with getDurabilityForDisplay.

Oh and also stack.stackSize != 1 check should be avoided somehow, but you can do that

``` java
public String getStackStringForDisplay(ItemStack stack, String originalString) {
    if(stack.stackSize == 1) return "";
    return originalString;
}
```

And remove the check from original code. However, there is a problem with rendering of slot splitting as it uses originalString in funny ways, but i think this hook is intended for items whose maxStackSize is 1 and they want do display some other useful 4-character data instead of unused stack size (batteries, TCon's ammo etc).

P.S. Had anyone yet noticed that getDurabilityForDisplay is reverted? It says '1.0 for 100% and 0 fo 0%' but actually it's '1.0 for 0% and 0 fo 100%'

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]
