### ISSUE TITLE
[Bug] World generation is broken when flying in spectator mode and going back to previous places

### ISSUE THREAD

**Issue by skyli91** [MinecraftForge/MinecraftForge#3107]
![2016-07-21_20 05 00](https://cloud.githubusercontent.com/assets/7442913/17033703/a5db3b0a-4f7f-11e6-80a7-41540afac099.png)

Trees cut in halves, snow missing. It's a forge server (universal jar of the newest 1.10.2 - 12.18.1.2016 version) without mods.

**Comment by skyli91** [comment]
![image](https://cloud.githubusercontent.com/assets/7442913/17034396/d3c0ce10-4f82-11e6-8b60-196db756ae98.png)
With a vanilla client too (without optifine or anything)

**Comment by heldplayer** [comment]
Could this be related to #3020 ?

**Comment by LexManos** [comment]
Possibly, Let us know if https://github.com/MinecraftForge/MinecraftForge/pull/3090 fixes it.

**Comment by skyli91** [comment]
yup! everything seems to be fixed now!
