### ISSUE TITLE
ModelLoaderRegistry.getModel does not handle the vanilla special case for items

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3111]
Call `ModelLoaderRegistry.getModelOrMissing(new ModelResourceLocation("minecraft:diamond", "inventory"));`

You get the missing model

It seems impossible to access the IModel for any models loaded directly from the item json folder in this manner

**Comment by williewillus** [comment]
I need a single agnostic way of getting the IModel regardless of whether botania:agricarnation#inventory is in a forge blockstate json as the inventory variant, or under models/item as an item json.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by bs2609** [comment]
This is still an issue in 1.12.

The example:
```java
ModelLoaderRegistry.getModelOrMissing(new ModelResourceLocation("minecraft:diamond", "inventory"));
```
still produces the missing model.

**Comment by bs2609** [comment]
There's a PR targeting this at present.
