### ISSUE TITLE
Event handlers do not support Events that use generics

### ISSUE THREAD

**Issue by Leviathan143** [MinecraftForge/MinecraftForge#3113]
An InstantionException is thrown when trying to register an event handler that subscribes to an event that uses generics(e.g RenderLivingEvent).

**Forge Version:** 1.10.2-12.18.1.2018

**Exception**
[Gist](https://gist.github.com/Leviathan143/5301d56341d77d52ab8a0f1b5f568e25)

**Minimum code required to reproduce:**
`public class EventGenericsTest`
`{`
`	@SubscribeEvent`
`	public void test(RenderLivingEvent<EntityLivingBase> event) {}`
`}`

`MinecraftForge.EVENT_BUS.register(new EventGenericsTest());`

**Comment by diesieben07** [comment]
This has nothing to do with generics. You cannot subscribe to event classes that are abstract.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by cpw** [comment]
Your intent is to handle all events, right?

**Comment by Leviathan143** [comment]
@cpw No, I failed to notice the Pre and Post events.
Sorry for the invalid report.
