### ISSUE TITLE
FMLMissingMappingsEvent.get() does not work for mods with capital mod-ids

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3114]
Should call toLowerCase on the active mod container's mod id before searching resourcelocation

I understand that non-lowercase mod-id's are bad but esp for old mods that need to maintain some semblance of backward compat (e.g. Botania) this can't really be fixed on our end.

**Comment by cpw** [comment]
Hmmm, this is risky.

**Comment by williewillus** [comment]
its not a huge problem (getall and scan the resource domain works fine), just thought I'd bring it to you guys attention

**Comment by cpw** [comment]
Yeah. This will literally explode everything in 1.10. It'll probably become a warning state for now, and 11 will probably enforce.

**Comment by Madsthunder** [comment]
I think this can be closed due to lowercase modid enforcement in 1.11
