### ISSUE TITLE
forge texture bug

### ISSUE THREAD

**Issue by CaptainKyros** [MinecraftForge/MinecraftForge#3123]
whenever i use forge with WelsKnight's resource pack, tall grass shows up as a pink/black block,and when i check the logs, it seems Forge is looking for a "tall_grass1.json

**Comment by williewillus** [comment]
The resource pack is broken

**Comment by williewillus** [comment]
Forge only "looks for" what its told to look for so the RP is doing something wrong

**Comment by CaptainKyros** [comment]
this only happens with forge installed

**Comment by williewillus** [comment]
then post the resource pack, logs, anything?
Saying "it no work" doesn't exactly help :P

**Comment by LexManos** [comment]
There are quite a few resource packs out there that are silently broken in vanilla.
Forge remove/fixes this silently broken stuff.
If your resource pack is broken 'by forge' then it is 100% your resource pack that is broken fundamentally. It's just exposed by Forge because we fix vanilla stupidity/bugs.

**Comment by CaptainKyros** [comment]
[WelsTexture.zip](https://github.com/MinecraftForge/MinecraftForge/files/385118/WelsTexture.zip)

[http://pastebin.com/cZ6TXgG5](url)

**Comment by LexManos** [comment]
`{
    "variants": {
        "normal": [
			{ "model": "tall_grass", "weight": 10 },
            { "model": "tall_grass1", "weight": 10 },
            { "model": "tall_grass2", "weight": 10 },
            { "model": "tall_grass3", "weight": 10 },
            { "model": "tall_grass4", "weight": 10 },
            { "model": "tall_grass5", "weight": 10 },
            { "model": "tall_grass6", "weight": 10 },
            { "model": "tall_grass7", "weight": 10 },
            { "model": "tall_grass8", "weight": 10 },
            { "model": "tall_grass9", "weight": 10 }
        ]
    }
}
`THARS YOUR PROBLEM!
Lets load all these variants that don't fkin exist!
