### ISSUE TITLE
Dynamic models in 1.10.2

### ISSUE THREAD

**Issue by CreativeMD** [MinecraftForge/MinecraftForge#3128]
Hello everyone,
I'm the author of LittleTiles, if you don't know this mod here is a short preview:
https://www.youtube.com/watch?v=s6QIxeGwsWQ

**Trying to update**
I'm currently trying to update this mod from 1.7.10 to 1.10.2 and i ran into tones of difficulties.
I think it's rather obvious that this mod cannot use the normal model based system, because it's impossible to make a model for every combination.

**My Attempt**
My attempt was to create an IBakelModel which would create BakedQuads on runtime based on the state. I know this is a rather hacky solution, but the only one i could find so far.
https://github.com/CreativeMD/CreativeCore/blob/1.10.2/src/main/java/com/creativemd/creativecore/client/rendering/model/CreativeBakedModel.java#L51
(Please note that this is a temporary solution and it's meant for testing purpose only, so please ignore the coding style!)

**Problems?**
As i tried to implement some kind of ItemRenderer, i realized that this is completely impossible.
`getQuads()` does not provide any information about the itemstack and there is no way to get it without asm transforming. So this attempt can only work for "placed" blocks (i could add the tileentity to the state).

**Features of the old system**
The old system rendered each block with a giving box (min and max). Through that way, i could support other blocks which were using connected textures (example: chisel) or blocks like grass. I could also apply color to each of the "tiles". (https://www.youtube.com/watch?v=oe46ZKlEKww)
Old system can be found here: https://github.com/CreativeMD/LittleTiles/blob/master/src/main/java/com/creativemd/littletiles/client/render/LittleBlockRenderHelper.java

**So what is my question?**
Is there s a better way to do something like that and if not can something like this be added to forge?
Something which allows a modder to render or to create a bakedmodel based on tileentity or itemstack. It would be a mess to implement something like this via asm transformer (and likely to cause incompatibility with Optifine).

**Why am I posting it here?**
Because it's a feature request in a way.

Maybe, I miss something and there is already a solution for it, if that is the case i'm sorry for blaming anyone. I would love to hear what you think about this and if something like this could be added to Forge.

In Regards
CreativeMD

**Comment by williewillus** [comment]
Other mods seem to have handled things just fine (see tico which has billions of possible combos and they're all baked models)

You might have noticed that baked models have something called getItemOverride on it. That's what you want to look at.

Asking for the old things back is not gonna happen :p

**Comment by williewillus** [comment]
The ItemOverride class has a handleItemState that gets a stack, so you *can* generate models based on stack.

**Comment by loordgek** [comment]
https://mods.curse.com/mc-mods/Minecraft/231095-chisels-bits is this the same ?

**Comment by williewillus** [comment]
Heh I just watched the video. Yeah it's mostly the same as another 1.8+ mod called chisels and bits. You might want to look at it for rendering stuff as it does things in a proper way

**Comment by CreativeMD** [comment]
@williewillus sorry, but i won't copy stuff from other mods.
@loordgek similar but not the same, my system allows to build doors, chairs and other structures: https://www.youtube.com/watch?v=6-WRUAGm86w

**Comment by diesieben07** [comment]
First, nobody said anything about copying. But, this is totally possible with the new system. You can have an IBakedModel that generates new ones on the fly and caches them for performance.

**Comment by cpw** [comment]
Can I suggest that you take this to the forums, or IRC? I don't think that your ask is out of line with what Forge has already provided. I understand the conceptual struggle in adapting to the new mindset for rendering post 1.8 changes, but we're not going to be adding in "missing" functionality from 1.7.10 that is definitely not missing, it is just *different*

**Comment by williewillus** [comment]
And I already told you what you need to be stack-sensitive: In your IBakedModel return a custom ItemOverride

**Comment by CreativeMD** [comment]
@williewillus thank you, yes i will give it a try maybe i can figure it out.
@diesieben07 i looked at his code before. It's far more complex than i thought it could be. His attempt is totally different and as soon as i realized that i stopped reading it, because i don't like to steal/copy other ones ideas how to solve problems.

and please don't blame that i want the old render system back, i just wanted to show you what features i need and if this is possible with the new render system. Obviously it is, so i will have to spent a lot more time to figure it out eventually.

Anyway thanks for all your time.
