### ISSUE TITLE
[1.10.2] Substitution alias should set delegate or registry name of replacement

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#3131]
Forge version: 1.10.2-12.18.1.2039
Test case: [link](https://github.com/Choonster/ForgeSubstitutionAliasTestMod/blob/3243f7f139955ad1b1c4a27e8786522e79622a60/src/main/java/choonster/forgesubstitutionaliastestmod/ForgeSubstitutionAliasTestMod.java)
FML logs: [link](https://gist.github.com/Choonster/016367b0ad2f35a409facd094ee67ba2)

When an `IForgeRegistryEntry` is registered normally, it's expected to have its registry name set beforehand (or provided as an argument); this is then set as the name of its `RegistryDelegate`.

When an `IForgeRegistryEntry` (or more specifically a `Block`/`Item`) is added as a substitution alias, there's no check to see if its registry name has been set and the name of its `RegistryDelegate` is never updated.

If a replacement `Block` doesn't have a registry name, all of its variants display as the missing model in-world.

If a replacement `Item` doesn't have a registry name, it crashes the game with a `NullPointerException` thrown in `ModelLoader#onPostBakeEvent`.

I suggest that adding a substitution alias should set the registry and/or delegate name of the replacement object to the name that the substitution was added for.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by Madsthunder** [comment]
This shouldn't be an issue anymore since you need to set the registry name of the object you're trying to register to the registry name of the object you're trying to replace.

**Comment by Choonster** [comment]
You're correct, this is superseded by the new registry system in 1.12.
