### ISSUE TITLE
[1.10.2] Substitution alias causes replaced item to show twice in Creative menu

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#3134]
Forge version: 1.10.2-12.18.1.2043
Test case: [link](https://github.com/Choonster/ForgeSubstitutionAliasTestMod/blob/6092f75ddae973bbd9cb326e9a799d2f7de7e16c/src/main/java/choonster/forgesubstitutionaliastestmod/ForgeSubstitutionAliasTestMod.java)
Screenshots:

![2016-07-31_06 37 00](https://cloud.githubusercontent.com/assets/878073/17272999/7b07805c-56e9-11e6-840c-b274741d3f6a.png)

![2016-07-31_06 37 07](https://cloud.githubusercontent.com/assets/878073/17273000/7b410584-56e9-11e6-8ec9-940f5789b04f.png)

**Comment by cpw** [comment]
Not fixing this. That's a side effect of the iterator that visits items.
