### ISSUE TITLE
Setting default value of unlisted property to something non-null breaks models.

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3142]
This is an extremely weird problem, but bear with me.

My use case is the Botania flower class: https://github.com/williewillus/Botania/blob/072e3a693b87da2376f5ed0ad31cef4b3bfc8cbd/src/main/java/vazkii/botania/common/block/BlockSpecialFlower.java#L127

This flower has several properties:
* It inherits the vanilla BlockFlower listed property and does nothing with it (it just sets the default value to poppy and doesn't touch it again)
* It declares listed property of EnumDyeColor, and saves that to meta
* It declares unlisted property of type String, which is used by a smart IBakedModel for rendering. The ultimate value for this is drawn from a TE.

Here's how to reproduce the problem (my models get screwed on relog or chunk reload):
1. I call `setDefaultState` in the constructor and give it a non-null value (I use "daybloom")
2. Open a world (I recommend the "The Void" superflat preset), place a pure daisy, and either leave the chunk and come back or relog. They show as missing model.
3. Botania adds extended state information to F3 when you hold shift+ctrl. Doing that shows that the unlisted property has the correct value, but the models are still incorrect(?!)
4. Here's the confusing part. I have a printout in my smart IBakedModel's getQuads method. *getQuads is not called when this problem occurs*. Whenever I relog or leave the chunk and return there are no printouts. This leads me to suspect some other IBakedModel is getting queried instead of my block's!
5. Even more confusing part. If I set my unlisted property's default value to null instead of "" or "daybloom", everything works perfectly.

This happens for the latest forge 2044 (after all the disappearing door fixes) and for sure did not happen in 2018 so I suspect it's the block state changes again.

Code is at the repo linked, a binary can be downloaded to reproduce this here: https://github.com/williewillus/Botania/releases/tag/extStateDebug (you need the latest 1.9.4 Baubles as a dependency from [here](https://minecraft.curseforge.com/projects/baubles/files/2301094))

**Comment by williewillus** [comment]
More investigation: when things go south, it's because the IBlockState passed to BlockRendererDispatcher.getModelForState has my default unlisted property value in there. when things work, the IBlockState passed has Optional.absent() as a value for my unlisted property

**Comment by williewillus** [comment]
I can solve this issue easily by setting my unlisted property's default value to null, but if there is a bug or instability caused by recent changes I would like to help hunt it down.

**Comment by LexManos** [comment]
Dont have extended properties with defaults.
The unlisted properties are data holders.

**Comment by williewillus** [comment]
So just don't set a default value for the extended state?
Cool, not a bug then
