### ISSUE TITLE
[1.10] Latest Forge breaks existing mods using FML registry system

### ISSUE THREAD

**Issue by TehNut** [MinecraftForge/MinecraftForge#3144]
As of https://github.com/MinecraftForge/MinecraftForge/commit/4dcee246d50442123852c66b2351de1e9d533917, the params for `PersistentRegistryManager.createRegistry(...)` have changed. This breaks existing mods that use the system.

Would it be possible to get an overload that defaults the `substitutionCallback` param to `null`?

**Comment by williewillus** [comment]
surprising given how stringent they are about binary compat the rest of the time ;P

Probably an oversight

**Comment by TehNut** [comment]
I assumed as much. Just bringing attention to it since it seems that [my comment](https://github.com/MinecraftForge/MinecraftForge/issues/3127#issuecomment-236399351) was overlooked.
