### ISSUE TITLE
Crash when using Java 6 instead of informative message

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#3145]
Original report here: https://github.com/mezz/JustEnoughItems/issues/371

They should get a friendly "Update your Java" message, not the crash above.
Maybe they did something really strange, but I figured I should report here anyway so we can figure it out.

**Comment by LexManos** [comment]
No, its not. We only have a update nag for J8.
It's still in your end modders to support 6.

**Comment by diesieben07** [comment]
I think it is at least supposed to give a clearer error message: https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/common/Loader.java#L580-L595

**Comment by LexManos** [comment]
Yes thats J8 detection, We havent written anything for J6/7.

**Comment by diesieben07** [comment]
Whoops. I'll shut up.

**Comment by mezz** [comment]
Ok. Is Java 7 detection unwanted or not possible?
JEI supports Java 7 and 8, so this forces me to either support Java 6 too or only support Java 8.

**Comment by LexManos** [comment]
There are no plans on doing any notification system for J6. Not enough people use it for us to care, and on the modders end all you have to do is simply set the binary compatibility.
J7 JDKs can compiled J7 code to J6 perfectly fine.
So it's on you for not setting your config correctly.

**Comment by williewillus** [comment]
That works for J7 syntax but it's not possible if you use standard libraries added in J7

**Comment by mezz** [comment]
Ok. I wasn't aware you could target Java 6 bytecode from a Java 7 source.
When I try, I get a java error even though I'm not using any Java 7 libraries, just diamond operator and multi-catch.
`Error:java: javacTask: source release 1.7 requires target release 1.7`
Searching the error online, people say it's not possible, you can use the J7 or J8 JDK to compile to J6 but the source has to be J6.

**Comment by LexManos** [comment]
There are ways you can do it, go figure it out and document it.
As for the library issue yes, that's a thing., But there are plenty of ways to fix that by setting up a J6 JDK and using it's libraries.
Either way, as stated there is no plans on caring about J6 JREs for the time being. If you give that much shit about it write a god damn PR.

**Comment by mezz** [comment]
I just wanted to know if it was possible or if there was a reason not to do it, and that's fine.
If the change is a pain, I'm probably better off making my source Java 6, but I wanted to be sure I'm doing it for the right reasons.

**Comment by LexManos** [comment]
Minecraft Targets J6, Mods should target J6 simple as that. That's the official stance of Forge.
Only reason we have that nag is for end user security, and because we're tired of the J8 mod erroring posting on our site.

**Comment by AEnterprise** [comment]
@mezz to set the target lvl you can specify it in your build.gradle (https://github.com/AEnterprise/RecipeTree/blob/master/build.gradle#L36-L37)
you might need to re-run the gradle commands for your dev workspace so intellij/eclipse picks it up but i'm not sure for that part

**Comment by mezz** [comment]
Yes, that is what I changed earlier, unfortunately it does not work. 
If I set the target to 1.6 and the source to 1.7 I get this error:
`Error:java: javacTask: source release 1.7 requires target release 1.7`

**Comment by AEnterprise** [comment]
did you also modify the language lvl of the project itself in the settings? (i know there is in intellij, not sure about eclipse)

**Comment by SquidDev** [comment]
I've used [Retrolambda](https://github.com/orfjackal/retrolambda) in the past to convert Java 7 bytecode to Java 6: I also couldn't get set target to 1.6 whilst keeping source at 1.7.
