### ISSUE TITLE
Forge - how to make and add own .patch file? 

### ISSUE THREAD

**Issue by acterhd** [MinecraftForge/MinecraftForge#3146]
Hello. I have question. How I can make own .patch file for Minecraft? How to include to forge sources?

**Comment by AEnterprise** [comment]
it's the the repo readme: https://github.com/MinecraftForge/MinecraftForge#how-to-install-forge-for-those-wishing-to-work-on-forge-itself

**Comment by acterhd** [comment]
I know about installing. I'm interesting how make own .patch files.
