### ISSUE TITLE
Fluid Expansion Bug

### ISSUE THREAD

**Issue by offlain** [MinecraftForge/MinecraftForge#3152]
reproduce:
place 1 liquid slime or substrantum liquid redstone down, relog, it has expanded multiple times.
**it seems the flowing blocks are converted to source blocs**

This issue is very bad when there's for example Tinkers construct liquid slime flowing down from island because the flowing slime will be source blocks when chunk gets saved and reloaded.
I had half an ocean replaced and the water pillar was 10x the original island's size.

downgrading to forge-1.10.2-12.18.1.2014 removes all these blocks
so issue starts somewhere between forge 1.10.2-12.18.2014 and 1.10.2-12.18.2043

tested with
forge-1.10.2-12.18.1.2044
forge-1.10.2-12.18.1.2043
forge-1.10.2-12.18.1.2014

with mods:
TConstruct-1.10-2.3.3a
Mantle-1.10.2-0.10.4
or
Substratum-1.10.2-1.7.0.0.jar

**Comment by bs2609** [comment]
Seems like build 2023 would be most likely to affect this (pull #3110).

**Comment by nzhook** [comment]
If the fix for this has been reverted. Please reopen the bug. Its pretty serious.

**Comment by KnightMiner** [comment]
It wasn't. That commit was added to a fork of the repository by accident (which Github does not properly show in the commit for some reason)
