### ISSUE TITLE
[Question]About the EnumFacing param of IStorage

### ISSUE THREAD

**Issue by ci010** [MinecraftForge/MinecraftForge#3162]
For the situation that one Capability instance is associated with multiple sides, the paramter of IStorage can just pass one EnumFacing. Thought now I could just pass null for the most of cases, I still wonder if this could be better, like a mutable length paramter?

**Comment by LexManos** [comment]
Well, that brings up a good point there is really no use for Side in that function... I think it was mainly just a remnant of one of our earlier designs for Capabilities.
Either way what you pass in would be determined by what capability you're using and what their implementer uses the side parameters for.
None of the Forge caps use it for anything. So ya.
