### ISSUE TITLE
Custom water color events not implemented

### ISSUE THREAD

**Issue by jellysquid3** [MinecraftForge/MinecraftForge#3164]
In the latest version of Forge 1.10 (build 2046), the `BiomeEvent.GetWaterColor` event is never fired and `net.minecraft.world.biome.Biome#getWaterColorMultiplier()` isn't used at all.

This looks like a missed patch to `Biome#getWaterColor()`, and makes it impossible to re-color water in custom biomes.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]
