### ISSUE TITLE
Using a dispenser to fill a bucket from any kind of modded tank (that supports IFluidHandler) destroys the block

### ISSUE THREAD

**Issue by bdew** [MinecraftForge/MinecraftForge#3165]
How to reproduce: 

* Place any kind of tank from a mod and fill some water in it
* Place vanilla dispenser facing it
* Put empty bucket in dispenser
* Give redstone signal
* ???
* Tank goes poof

Problem is here: https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fluids/DispenseFluidContainer.java#L75

Either that setBlockToAir shouldn't be there (instead somehow remove the block in FluidBlockWrapper / BlockLiquidWrapper as needed) or it shouldn't work on actual tanks.

**Comment by mezz** [comment]
`FluidUtil.tryPickUpFluid` is only supposed to pick up fluid blocks, not fluids from machines. I guess it _could_ but that was not my intention. The `setBlockToAir` is probably unnecessary as well, I'll test it out.

**Comment by bdew** [comment]
I think having it fill from machines is a good thing, if it can avoid breaking them :P

**Comment by mezz** [comment]
Hmmmm but then we need to make them pick up from machines too. Maybe you can do it for the next PR? Shouldn't be hard actually, and would allow for some cool builds.
