### ISSUE TITLE
Checkbox in mod list to hide/show library mods

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3166]
There are just too many "library" mods from different mod authors those days.
I think that there should be an option for a mod to define itself in its metadata as a "library mod" - such mods will be hidden by default and in mod list there should be a checkbox to show them.

Or maybe even a separate tab, or category at the bottom of the list - that would be cool and useful.

**Comment by Actuarius** [comment]
@williewillus added labels [Feature]
