### ISSUE TITLE
Custom trees not spawning with certain Forge versions

### ISSUE THREAD

**Issue by Redlotus99** [MinecraftForge/MinecraftForge#3167]
I am unsure if this is a Biomes O Plenty issue or a Forge issue, but custom trees are no longer spawning.  Several people are have reported this issue with BoP, but since it can't be fixed by using a previous Forge version I wanted to report it here and link to the BoP issue.

https://github.com/Glitchfiend/BiomesOPlenty/issues/818

**Comment by LexManos** [comment]
You're going to have to be more specific.
Mods spawn their own trees, and check their own conditions.
Make sure you're using the latest version and if that doesnt work you track down the latest version that it DOES work in.

**Comment by Redlotus99** [comment]
@LexManos I apologize for the lack of info was in a hurry and on the way out. Now that I am back I'll do a bit more testing and let you know the exact versions that work. It appears that Forge 2014 and BoP 2033 work, but I am using Forge 2046 and BoP 2059.

It was verified in issue #818 of BoP that the following versions were tested:

Biomes O' Plenty: 
Versions I've tried so far-
1.9.4-4.1.0.2052
1.9.4-4.1.0.2049
1.9.4-4.1.0.2041

Minecraft: 1.10.2

Forge: 
Versions I've tried so far-
1.10.2-12.18.1.2011
1.10.2-12.18.1.2041
1.10.2-12.18.1.2043

As stated I'll get more specific asap.

**Comment by LexManos** [comment]
32 version to check with a mod I dont have, great...

**Comment by Redlotus99** [comment]
Sorry Lex...

**Comment by Redlotus99** [comment]
In testing so far I've gotten up to Forge 2033 and BoP 2059 seems to spawn trees as intended. I'll push up more on the Forge side and see which version breaks it.

**Comment by Redlotus99** [comment]
Out of guilt I tested and test and found that Forge 2039 is your culprit. 

Build 2039:
	dakotapierone: Update decorate for biomes to support Decorate event
	cpw: Clean up AT file

I tested all versions up to 2039 and all previous to it worked like a charm. When adding 2039 no custom trees spawned. Hope that saves some time.

**Comment by LexManos** [comment]
Interesting, nothing in that PR should effect custom biomes and the like.
Unless BOP is not generating their trees in a standard fashion. Now to see if we can find where they are generating their trees.

**Comment by Redlotus99** [comment]
Let me know if you need me to try and test anything and I'll gladly do so.

**Comment by Unh0lyTigg** [comment]
BoP Generator registering:
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.9.4-4.1.x/src/main/java/biomesoplenty/common/init/ModGenerators.java (called in preinit stage)

BoP tree generators: 
https://github.com/Glitchfiend/BiomesOPlenty/tree/BOP-1.9.4-4.1.x/src/main/java/biomesoplenty/common/world/generator/tree

BoP Generator Registry:
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.9.4-4.1.x/src/main/java/biomesoplenty/common/world/GeneratorRegistry.java

Just thought I would help by providing quick links to BoP tree generation.

**Comment by blay09** [comment]
Not a Forge issue: https://github.com/Glitchfiend/BiomesOPlenty/issues/818#issuecomment-238068781

**Comment by Redlotus99** [comment]
Thanks for the help @LexManos @blay09 @Unh0lyTigg  glad it's fixed.
