### ISSUE TITLE
Placing stairs in a certain pattern creates a hole

### ISSUE THREAD

**Issue by quat1024** [MinecraftForge/MinecraftForge#3170]
Sorry, this is really hard to describe properly...

The problem happens when "inner_left" and "outer_left" (or "inner_right" and "outer_right") stair models are back-to-back.

Here is one way to create this pattern:

* Place a stair facing south
* One block to the north, place a stair facing west
* One block to the west of the first stair, place a stair facing east

![2016-08-07_16 36 03](https://cloud.githubusercontent.com/assets/2068021/17465177/5feddbd8-5cbe-11e6-884f-5514e1da1ce2.png)

Does not happen in vanilla.

**Comment by RANKSHANK** [comment]
Related to 0f6b16cada5d77e094aa2eedbe2a556b76656997

Disabling stair culling fixes this

**Comment by williewillus** [comment]
that means the culling forge does add is a bit faulty as it says a face is hidden when it isn't

**Comment by LexManos** [comment]
How the hell do you place stairs like that?
And no, this shouldn't be faulty it's been working fine for like ~2 years.
Somehow that stair closest to us is saying that it is a full side facing the other block.
Explain EXACTLY how you do this, videos preferred, and make sure you're NOT using resource packs.

**Comment by RANKSHANK** [comment]
@LexManos It's a bit of a contorted procedure, but I got it:
![example](https://cloud.githubusercontent.com/assets/1190024/17467870/d10b2dd2-5d65-11e6-8e65-40401f70e59e.gif)

**Comment by LexManos** [comment]
Alright well look into it. Thats extreamly odd its as if the first block isnt getting the position update to reset its form.

**Comment by quat1024** [comment]
> How the hell do you place stairs like that?

It literally says right in the issue lmaoooooo

**Comment by LatvianModder** [comment]
The real question is why would you ever place stairs like that anyway

**Comment by kinggoesgaming** [comment]
@LatvianModder maybe mapmakers/build teams might have it as a fancy design?
