### ISSUE TITLE
[Suggestion] Add entity.getSpawnPoint

### ISSUE THREAD

**Issue by MCrafterzz** [MinecraftForge/MinecraftForge#3172]
It should return the entitys spawn point, and the world spawn point if it doesn't have a spawn point.

**Comment by diesieben07** [comment]
What is an entity's spawn point exactly?

**Comment by LexManos** [comment]
And why?

**Comment by liach** [comment]
Entity just spawn once. They do not really have a spawn point. If you want to capture them, listen entity spawning events on the bus and record those points to the spawned entities' nbt data.

**Comment by MCrafterzz** [comment]
To be able to teleport to it

**Comment by Leviathan143** [comment]
@MCrafterzz 
There is already an existing method to get the player's spawn location.

**Comment by LexManos** [comment]
You're gunna have to be more descriptive.
ENTITIES do not have a spawn point.
PLAYERS do, and you can already get that information from the players.
