### ISSUE TITLE
[1.10.2] upside down corner stairs crash the game [2047+]

### ISSUE THREAD

**Issue by Tsukiumy** [MinecraftForge/MinecraftForge#3174]
http://pastebin.com/6urfbi3G
running on 2048 get me this crash as soon as the terrain loaded, and again after another try, runing on 2046 and going to the afected block get this screnshot.
http://imgur.com/a/G7nh1
seems likely to not be the desired behavior.
if any more info nedded i will try to get it.

**Comment by LexManos** [comment]
Don't create two issues for the same damn thing -.- https://github.com/MinecraftForge/MinecraftForge/commit/1c11a3622e9936dd6145db5de6442a06b6c6b06f
