### ISSUE TITLE
Block.getFireSpreadSpeed() is not used

### ISSUE THREAD

**Issue by HenryLoenwind** [MinecraftForge/MinecraftForge#3175]
BlockFire uses getFlammability() for everything.

Seems it got lost with the 1.8 update when all calls to BlockFire.func_176534_d() got re-routed to Block.getFlammability() or Block.isFlammable() instead of to Block.getFireSpreadSpeed().

**Comment by LexManos** [comment]
Seems to of gotten transposed sometime in the past.
