### ISSUE TITLE
Bone blocks should not get OD-replaced

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3176]
Currently any mod's `dyeWhite` is being opted into the bone block recipe, which is being OD-replaced from bonemeal to `dyeWhite`

In this case I feel like it doesn't make sense to replace. For example my floral white powder from botania can now craft bone blocks because it's a `dyeWhite` :P

**Comment by LatvianModder** [comment]
Bigger problem is that you can reverse-craft it to get bone meal back. Free resources (in a way)

**Comment by williewillus** [comment]
^ yeah that's the main issue

**Comment by asiekierka** [comment]
That sounds horrible.

**Comment by Actuarius** [comment]
@mezz added labels [Bug]
