### ISSUE TITLE
Why is org.apache classloader-excluded?

### ISSUE THREAD

**Issue by Xfel** [MinecraftForge/MinecraftForge#3177]
Right now, all apache libraries (packages starting with `org.apache`) are excluded from the launch class loader due to this: https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/relauncher/FMLLaunchHandler.java#L69

Is there any reason for this? This means that we cannot use apache libraries in our mods without relocating.

**Comment by fewizz** [comment]
This means, that all classes in package org.apache will be load by parent ClassLoader(which not transforms and caches classes, like 'LaunchClassLoader')

**Comment by covers1624** [comment]
This is not an issue, as fewizz said, this only excludes classes from being passed through IClassTransformer's.

**Comment by fewizz** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/2022

**Comment by simon816** [comment]
I think the comments in #1958 explain the reason clearly enough
