### ISSUE TITLE
Temporary capability equality check workaround was never fixed

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#3179]
https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/common/capabilities/CapabilityDispatcher.java#L138-L143

^ This should have been replaced with a proper equality check on the 1.9->1.10 version change. Since it wasn't (and it's already popping up as a potential performance concern on my sampling reports), I guess the only way to work around this would be to add an interface for capabilities to implement comparability - and get rid of the interface in 1.11.

If you think an interface is too hacky, you might want to check if a given capability overrides equals() with reflection magic, but that's probably even hackier still.

No pull request because I'd rather know which solution to implement before I start implementing it. Thoughts?

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]
