### ISSUE TITLE
Blockstate and item json with same name causes strange issues

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3182]
Blockstate (blockstates/root.json:

```
{
  "variants": {
    "normal": { "model": "botania:root"  } // should point to models/block/root.json
  }
}
```

Item (models/item/root.json) :

```
{
    "parent": "minecraft:item/generated",
    "textures": 
    {
        "layer0": "botania:items/root"
    }
}
```

These two simply happened to be named the same. The former is for a block called "botania:root" the latter is simply a meta variant of "botania:manaResource" mapped to a custom name.

What happens is when I do `ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(myBlock), 0, "botania:root#normal")`, not only does the block's item not take the model specifies `models/block/root.json`, it also _back propagates the item/generated model onto the block model in-world_. That's extremely extremely extremely strange behaviour and I doubt it's intended.

**Comment by williewillus** [comment]
Screenshot (yes, that's what a builtin/generated model looks in world)

https://cloud.githubusercontent.com/assets/2068021/17631030/4380d632-6090-11e6-8b71-110c696f7ae2.png

**Comment by williewillus** [comment]
Renaming the models/block/root.json does not alleviate the problem, meaning the problem is derived from the blockstate and item jsons sharing names, the block json is not in the equation

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]

**Comment by bs2609** [comment]
This is still an issue, I tested and was able to reproduce the same problem with 1.12.
