### ISSUE TITLE
BlockFalling#checkFallable bug?

### ISSUE THREAD

**Issue by Madsthunder** [MinecraftForge/MinecraftForge#3183]
Is this a bug or am I just severely misunderstanding this code?
`if (blockpos.getY() > 0)
{
    worldIn.setBlockState(blockpos.up(), this.getDefaultState());
}`
(BlockFalling#checkFallable, line 78)
I'm pretty sure Red Sand would turn into Sand because of this

**Comment by Madsthunder** [comment]
Yes, this is a bug. Proof:

With Sand set as the default state (Vanilla Basically)
![2016-08-13_17 19 53](https://cloud.githubusercontent.com/assets/12476160/17645669/5bef09a6-617a-11e6-8fe9-6c629e722a46.png)

With Red Sand set as the default state (What A Modder Might Do)
![2016-08-13_17 15 53](https://cloud.githubusercontent.com/assets/12476160/17645674/8435f9d8-617a-11e6-9042-5f7df796b21a.png)

As you can see, the sand variants are in the exact same formation, it's just the combination of new Biomes and the use of IBlockStates with blocks that implement BlockFalling is when this becomes a problem

**Comment by bs2609** [comment]
Vanilla bug reference: https://bugs.mojang.com/browse/MC-93129
