### ISSUE TITLE
[1.10.2-12.18.1.2064] Issue with armor rendering

### ISSUE THREAD

**Issue by P3pp3rF1y** [MinecraftForge/MinecraftForge#3196]
Just updated to 12.18.1.2064 and I have an issue with armor rendering.
![image](https://cloud.githubusercontent.com/assets/2079526/17677816/c49aef86-6334-11e6-8831-5b306fb849e5.png)
As you can see this is just enchanted regular diamond armor 
![image](https://cloud.githubusercontent.com/assets/2079526/17677880/0074fb6e-6335-11e6-837d-361dc3a23b7c.png)

However it affects all armor and just to be sure I have run forge only instance (with no additional mods) and got the same results.

**Comment by GirafiStudios** [comment]
I can confirm this. The problem seem to start to appear in 12.18.1.2057, so must be caused by this commit: https://github.com/MinecraftForge/MinecraftForge/commit/20c662c1d07e833fca4cafbb75af1e610eeca055

**Comment by kiroma** [comment]
![2016-08-15_23 59 06](https://cloud.githubusercontent.com/assets/5281819/17681175/5c4a74c8-6344-11e6-84cd-2a1d7cce5ee6.png)
May confirm, problem affects all types of armor but leather for me.
Also affects not enchanted armor.
![2016-08-16_00 02 07](https://cloud.githubusercontent.com/assets/5281819/17681263/e7880712-6344-11e6-9f0a-050eed70d253.png)

**Comment by LexManos** [comment]
Ugh this is why I usually write with padding y.y
