### ISSUE TITLE
Not able to get EnumHand in handleItemState

### ISSUE THREAD

**Issue by TypicalDarkness** [MinecraftForge/MinecraftForge#3200]
A bug related to this was reported [here](2672) . I animate my model by rebaking it in `handleItemState` in `ItemOverrideList`. This is how I'm finding out in which hand the ItemStack is:

```
EnumHand hand = null;
if (stack.equals(entity.getHeldItemMainhand())) 
{
     hand = EnumHand.MAIN_HAND;
} 
else if (stack.equals(entity.getHeldItemOffhand())) 
{
     hand = EnumHand.OFF_HAND;
}
```

The problem is that I have to override `Item::shouldCauseReequipAnimation` because editing NBT causes the item to move up and down which I want to prevent. Now the code I posted above doesn't work because `stack` equals neither of the stacks in the hands of the entity...

So I either need a different way to prevent the NBT-animation or a new way to get the hand.

**Comment by williewillus** [comment]
try using `==`.

The stack being held should be the exact same one as the one passed to rendering code

**Comment by williewillus** [comment]
Also, link is broken

**Comment by TypicalDarkness** [comment]
Already tried that. ItemStack doesn't override `equals` so it should be the same as `==`. Fixed the link.

**Comment by TehNut** [comment]
Try `ItemStack.areItemsEqual(stack1, stack2) && ItemStack.areItemStackTagsEqual(stack1, stack2)`

**Comment by williewillus** [comment]
I'm not sure why then. the two should be the exact same instance (`ItemRenderer.updateEquippedItem` assigns the held item directly to a field which then is passed to the first person hand render functions directly. which pipes all the way to the handleItemState)

**Comment by TypicalDarkness** [comment]
Maybe that's the problem: I modify the nbt date of the item when the right mouse button is clicked. As soon as that happens the debugger says that the instances are no longer the same. Really weird. Does writeToNBT make a new instance of the itemStack?

**Comment by williewillus** [comment]
how are you modifying the nbt? 0.o writeToNBT should not be involved in this at all

**Comment by TypicalDarkness** [comment]
I'm saving ItemStacks of ItemBullets inside NBT, with the damage representing the left shots.

`  
public void setBulletItemStack(ItemStack gun, ItemStack bullet, int id)
    {
        //If the gun has no tags, give it some
        if(!gun.hasTagCompound())
        {
            gun.setTagCompound(new NBTTagCompound());
        }

```
    //If the gun has no ammo tags, give it some
    if(!gun.getTagCompound().hasKey("ammo"))
    {
        NBTTagList ammoTagsList = new NBTTagList();
        for(int i = 0; i < type.numAmmoItemsInGun; i++)
        {
            ammoTagsList.appendTag(new NBTTagCompound());
        }
        gun.getTagCompound().setTag("ammo", ammoTagsList);
    }

    //Take the list of ammo tags
    NBTTagList ammoTagsList = gun.getTagCompound().getTagList("ammo", Constants.NBT.TAG_COMPOUND);

    //Get the specific ammo tags required
    NBTTagCompound ammoTags = ammoTagsList.getCompoundTagAt(id);


    //Set the tags to match the bullet stack
    bullet.writeToNBT(ammoTags);
}`
```

The mod is not made by me, I'm just updating it.

**Comment by williewillus** [comment]
~~no mod code should be calling `writeToNBT` in normal use like this. Your logic is flawed.~~

Also, your logic is also flawed in that a `null` `bullet` will cause you to NPE on the last line.

**Comment by TypicalDarkness** [comment]
Yes I know I'm currently rewriting big parts of the mod

**Comment by TypicalDarkness** [comment]
Is `ammoTagsList.set(id, bullet.writeToNBT(ammoTags));` legit? Because it works..

**Comment by williewillus** [comment]
so is the original issue still an issue?

**Comment by TypicalDarkness** [comment]
Yes. But it might not be related to forge. The mod I'm updating is huge and it's way harder for me to understand someone elses code than making my own. I'm going to test a bit more and find out what's really causing it...

One more question: What's the right way to store a stack in NBT then?

**Comment by TypicalDarkness** [comment]
Is ammoTagsList.set(id, bullet.writeToNBT(ammoTags)); legit? ~~Because it works..~~

**Comment by williewillus** [comment]
i suggest trying forums or irc, if you're not sure if it's a forge bug then it shouldn't be reported here until you've figured out that it is a forge bug :P

**Comment by TypicalDarkness** [comment]
The problem is that I change the NBTtag on the server. When the client updates, does it create a new instance of the item if it is not the same as on the server? The `item` that will be returned in `HandleItemState` is stored in `ItemRenderer` (`itemStackMainHand` and `itemStackOffHand` fields) These fields are updating in `ItemRenderer::updateEquippedItem` This might cause it to desync when `renderFireInFirstPerson` is called, because it's no longer the actual ItemStack held by the player.
