### ISSUE TITLE
unable to reach maven .jar files in version.json

### ISSUE THREAD

**Issue by ZornTaov** [MinecraftForge/MinecraftForge#3202]
I'm working on a minecraft launcher in C# and I've gotten to the point where I am downloading all library files needed to run minecraft with forge before launching.  I have a chunk of code that converts the maven links in version.json from "com.typesafe:config:1.2.1" into "http://files.minecraftforge.net/maven/com/typesafe/config/1.2.1/config-1.2.1.jar" to download the required jar, however both "com.typesafe.akka:akka-actor_2.11:2.3.3" and "com.typesafe:config:1.2.1" result in 404's.  Is there any reason these two files aren't available as .jar links on the forge maven?

**Comment by LexManos** [comment]
We do not host these files in uncompressed forms.
Either host them yourself or have your users use our installer.

**Comment by shadowfacts** [comment]
Also if you [looked at the JSON](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/jsons/1.10-dev.json#L35) you'd see that it specifies the Maven repo to use for each artifact.

**Comment by ZornTaov** [comment]
@shadowfacts the launcher will use that maven link just fine, however for 1.7.10 since I'm using the release version of the json, so [this](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/jsons/1.7.10-rel.json#L39) is the url I get

**Comment by LexManos** [comment]
Do not download from maven they dont like that.
And as stated USE THE INSTALLER!
Beyond that there is no legitimate reason for you to write your own launcher, so why would we care/help you?

**Comment by ZornTaov** [comment]
I'm hosting those two files, and possibly others, myself as a fallback of the forge maven doesn't supply them, as your other option you gave was to host them myself.
