### ISSUE TITLE
The itemstacks that are used for rendering what's in the hands are only updated when an re-equip animation occurs

### ISSUE THREAD

**Issue by TypicalDarkness** [MinecraftForge/MinecraftForge#3203]
Ok so I did some more research and testing on an [issue](3200) that I reported earlier and found out that it is forge-related.

I will try to explain my problem step-by-step:
I need to vary the animation of my item model based on the hand that it is being held in. I try to find out the hand like this in `ItemOverrideList::handleItemSate`:

```
if (stack == entity.getHeldItemMainhand()) 
{
    hand = EnumHand.MAIN_HAND;
} 
else if (stack == entity.getHeldItemOffhand()) 
{
    hand = EnumHand.OFF_HAND;
}
```

The stack parameter from `handleItemState` is the same as the `itemStackOffHand` and `itemStackOffHand` variables in `ItemRenderer`. These variables are refreshed every tick using `ItemRenderer::updateEquippedItem`.
The thing is, that the mod regularely has to change the itemStack (NBT) while the item is being used and when the client updates, it seems to make a new ItemStack if it's not the same as the existing one. (Not sure how it works but according to the debugger the `stack` parameter in `handleItemState` has a different instance than any of the stacks in the entity's hands as soon as NBT is edited) 

This would also not be a problem, since `itemStackOffHand` and `itemStackOffHand` are normally updated in the next tick. But here comes the problem; I have to override `Item::shouldCauseReequipAnimation` because as soon as NBT is changed  (or the ItemStack in a slot is changed/swaped in any other way), there is an up- and down animation, which I want to prevent. I do this by comparing the itemstacks and ignoring the NBT changes made.

The issue is, that this also prevents `itemStackOffHand` and `itemStackOffHand` from being refreshed
(`ItemRenderer::updateEquippedItem` (`ItemRenderer.java:631`))

So, is there a better way to prevent the up-and-down-animation when a slot is changed?

**Comment by LexManos** [comment]
This isnt a forge issue this is how the game works.
Dont use instance equivalency then use some marker in the NBT, or better yet, dont spam the client with NBT changes every tick.

**Comment by TypicalDarkness** [comment]
I'm not spamming the client. The NBT is changed whenever the item is used by the client. 

How else am I supposed to find out the hand than by instance equivalency if the NBT tag of both items could be the same? I'm one of the people who think that the new rendering system has a lot of potential and that don't give up trying to use it... But there simply have to be essential features like preventing the update-animation or a reliable way to find out the hand the ItemStack is held in to make this system usable...

**Comment by TehNut** [comment]
Doesn't `EntityPlayer` have something like `getActiveHand()`?

Edit: It does. Just checked.

**Comment by TypicalDarkness** [comment]
It seems to be always `null` when I use it in `ItemOverrideList#handleItemState`. Probably because `EntityPlayerSP` overrides it, What I really need is just a way to prevent the reequip-animation without preventing `ItemRenderer#updateEquippedItem` from working... I don't think @LexManos has understood what my problem is (or maybe I haven't explained it well enough)

**Comment by TypicalDarkness** [comment]
I guess I will have to use reflection to manually update the ItemRenderer during the RenderHandEvent :( Exactly what the new system wanted to prevent but I don't see any other possibility.

**Comment by williewillus** [comment]
you're still going to get the exact same problem if you do that.

**Comment by TypicalDarkness** [comment]
No. The itemStack variables in `ItemRenderer` are now synced before rendering the hands. This means the stacks are up-to-date when `handleItemState` is called. I'm essentially doing what `ItemRenderer#updateEquippedItem` would do if`Item#shouldCauseReequipAnimation` is not overridden, just not every game-tick but instead every rendering-tick (which also makes more sense if you think about it because the `ItemStack` variables are only used for rendering.)

**Comment by williewillus** [comment]
alright; if you're going to hack at least do it only for your items so you don't break other mods >.>

**Comment by TypicalDarkness** [comment]
Yes. I will do that.

**Comment by williewillus** [comment]
if you wanted the hand you should have used a perspective aware model in the first place.

**Comment by TypicalDarkness** [comment]
I am using `IPerspectiveAwareModel` but the appearance of my models rely on the `ItemStack` and `handlePerspective` does not provide `ItemStack`s.
The `IPerspectiveAwareModel` provides an `ItemOverrideList` where I can modify the model based on the stack. After that, `handlePerspective` is called where I modify it based on the perspective.

If there's a better solution, I'd be happy to hear it. I'm sure there will be people with the same problem in the future.

**Comment by HenryLoenwind** [comment]
Shouldn't the description be more like: "The itemstacks that are used for rendering what's in the hands are only updated when an re-equip animation occurs"?

**Comment by TypicalDarkness** [comment]
You are right. I changed it.
