### ISSUE TITLE
Dedicated Server calls MinecraftServer.stopServer() twice

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3206]
tldr: `MinecraftServer.stopServer` is run from both the main tick loop and possibly from a registered shutdown hook in `MinecraftServer.main`. This is wasteful and can incur race conditions as neither check if the other is running. I've seen the shutdown hook run half way, all the way, or not at all.

**Comment by williewillus** [comment]
This was wiping a list of stacks stored in one of my player caps because I have something in its  `serializeNbt` method to prune stacks without EMC values.

My EMC value map is cleared on `ServerStoppedEvent` (note past tense)

The shutdown hook has a chance of running _after_ `ServerStoppedEvent`, writing all player data and caps again, making my pruning method clear the entire list because nothing has an EMC value after `ServerStoppedEvent`.

The shutdown hook and the main thread need to coordinate so stopServer is only run once.

**Comment by williewillus** [comment]
Edit: this happens in vanilla's dedicated server too, so it's a vanilla bug.

**Comment by Actuarius** [comment]
@williewillus added labels [Vanilla Bug]

**Comment by bs2609** [comment]
Do you think https://bugs.mojang.com/browse/MC-104592 is related to this in any way?

**Comment by williewillus** [comment]
it is

**Comment by williewillus** [comment]
Valid

**Comment by mezz** [comment]
I'm closing this since it's a stale vanilla bug.
Please subscribe to the mojang bug tracker for this issue, and feel free to submit a PR.
