### ISSUE TITLE
Unpacking a vanilla baked quad POSITION_3F element does not augment vector properly

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3209]
I might be doing this all wrong, please correct me if so.

I want to transform an already baked model that does not have an IModel form (it's dynamically generated by combining two vanilla models).

I do this by unpacking the original model's quads and passing them through a VertexTransformer, like so (fry taught me this a loooonnng time ago ;p):

```
    protected static BakedQuad transform(BakedQuad quad, final TRSRTransformation transform) {
        UnpackedBakedQuad.Builder builder = new UnpackedBakedQuad.Builder(DefaultVertexFormats.ITEM);
        final IVertexConsumer consumer = new VertexTransformer(builder) {
            @Override
            public void put(int element, float... data) {
                VertexFormatElement formatElement = DefaultVertexFormats.ITEM.getElement(element);
                switch(formatElement.getUsage()) {
                    case POSITION: {
                        float[] newData = new float[4];
                        Vector4f vec = new Vector4f(data);
                        transform.getMatrix().transform(vec);
                        vec.get(newData);
                        parent.put(element, newData);
                        break;
                    }
                    default: {
                        parent.put(element, data);
                        break;
                    }
                }
            }
        };
        quad.pipe(consumer);
        return builder.build();
    }
```

My issue is that if I pass a TRSR in that has a translation component, that component is not applied. This is because the float[4] that is created in `LightUtil.unpack()` and passed to `put` does not insert a `1` into the fourth slot, which is needed for the TRSR's augmented matrix to work. If I manually perform `vec.setW(1)` before multiplying it by the TRSR, then the translation works as expected.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]
