### ISSUE TITLE
2068 breaks binary compatibility for getHarvestLevel()

### ISSUE THREAD

**Issue by HenryLoenwind** [MinecraftForge/MinecraftForge#3210]
"ItemTool"s only do their special toolClass handling in the new method, not the old method. Together with Item relaying calls to the new method into the old one (instead of the other way around), this means that ItemTools will no longer respond to getHarvestLevel() the way they did before.

See also line notes in https://github.com/MinecraftForge/MinecraftForge/commit/8dbfe1baad42d1fcb93f44050d44577648da3900

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]
