### ISSUE TITLE
ICapabilityProvider#getCapability not marked nullable in patched MC classes

### ISSUE THREAD

**Issue by fnuecke** [MinecraftForge/MinecraftForge#3213]
Currently `ICapabilityProvider#getCapability`, while due to it's original package location, and going by the documentation may return `null`, is _not_ explicitly marked `@Nullable` where it is patched into MC classes (`World`, `TileEntity`, `ItemStack`, `Entity`). However, due to the new `package.info`s in MC this means they're expected to return non-`null`. This contradiction is at best annoying due to IDEs producing false positives for nullable problems, and at worst misleading and confusing.

I've had a short discussion on Twitter with a few people a few weeks back, and the dominant opinion was that they're not `@Nullable` because "it'd be annoying" and `getCapability` should just throw an exception if `hasCapability` returns `false`, i.e. there should never be a case when `null` is returned in the first place. However, I've now stumbled across the fact that `CapabilityDispatcher#getCapability` does no `hasCapability` checks, but checks for `null` instead. So I now assume that in fact by the original concept `getCapability` should _never_ throw and instead return `null`. If that's true, I propose adjusting the patches to actually mark the injected `getCapability` methods as `@Nullable` (I'd be willing to make a PR for this). Either way, I'd like to get the official stance on how this is meant to be used to known what to go forward with.

**Comment by HenryLoenwind** [comment]
BTW: Same problem with the side parameter.

Same problem with most of Forge's additions to vanilla objects to be exact.

**Comment by williewillus** [comment]
We should just gather these all up into one PR, Lex likes these cleanups in bulk.

**Comment by Actuarius** [comment]
@mezz added labels [Cleanup]

**Comment by Actuarius** [comment]
@mezz added labels [Superseded]

**Comment by bs2609** [comment]
So following this from #3256 to #3394 to #3395, it should be resolved now?

**Comment by mezz** [comment]
Yep, resolved.
