### ISSUE TITLE
Big mushroom generating should trigger event type EventType.BIG_SHROOM, not SHROOM

### ISSUE THREAD

**Issue by ziggurism** [MinecraftForge/MinecraftForge#3217]
In `net.minecraft.world.biome.BiomeForest.java` we check for `EventType.SHROOM` before generating big mushrooms, but it should be `EventType.BIG_SHROOM`. Thanks.

**Comment by Actuarius** [comment]
@mezz added labels [Bug]

**Comment by liach** [comment]
Fixed in #3259

**Comment by Madsthunder** [comment]
Close Please?

**Comment by bs2609** [comment]
@mezz please close
