### ISSUE TITLE
BlockPlace's itemInHand does not respect off_hand

### ISSUE THREAD

**Issue by Polyana-Fontes** [MinecraftForge/MinecraftForge#3221]
If we place a block using our off hand with nothing in our main hand the itemInHand value will be null.

There's not proper way to know which hand was used to place the block.

The event is created in ForgeEventFactory.onPlayerBlockPlace and is fired from ForgeHooks.onPlaceItemIntoWorld. That last method receives an EnumHand value, that could be passed to the event and it could be used to determine which ItemStack was used.

Forge version 12.18.1.2011 (MC 1.10.2)

**Comment by jredfox** [comment]
It only seems to be only ignoring enum offhand hand.  However the entire hand reading system might be glitched and needs to be analyzed.   **I can't even fully update silk spawners to a working state until this forge issue has been resolved.**.

**Comment by Actuarius** [comment]
@mezz added labels [Bug, Superseded]
