### ISSUE TITLE
Structure block lines are getting invisible

### ISSUE THREAD

**Issue by Polyana-Fontes** [MinecraftForge/MinecraftForge#3222]
The line overlay that displays the current selection is getting invisible when the structure block is behind us. It only happens when Minecraft Forge is installed.

I'm planning to use structural blocks to display cuboid selections made in my server-side only mod but this bug is being a barrier

Forge 12.18.1.2073 (MC 1.10.2)

**Comment by LexManos** [comment]
Explain better. I've tested the structure blocks jsut fine and they render normally until i get out of range of the TE itself.

**Comment by Polyana-Fontes** [comment]
I'm uploading a short video, it will show the issue better

**Comment by TehNut** [comment]
IIRC the lines are drawn via TESR, so they would get hidden when the TESR stops drawing.

**Comment by Polyana-Fontes** [comment]
With forge, the lines disappears if we look too high (the top corner is "corner", the bottom corner is "save")
https://www.youtube.com/watch?v=yNdnrjjhSxo&feature=youtu.be

Without forge, it renders without issues:
https://www.youtube.com/watch?v=DaVSDYcpaE4&feature=youtu.be

**Comment by LexManos** [comment]
Yes it is drawn by a tesr and we cull TESRs that arnt on the screen unlike vanilla which will happily render your 10,000 chests behind your back every frame for no reason. 
Meh, whatever I dont care to do the math on how far its possible to see the structure block from as it can go in a lot of different sizes. So i'll just out in an exception for this.
