### ISSUE TITLE
Using per block priority/cost for AI pathfinding.

### ISSUE THREAD

**Issue by LapisSea** [MinecraftForge/MinecraftForge#3223]
So I found that the AI pathfinding lacks some logic when it comes to the fastest path.
By that I mean that the AI will go the shortest route and not the fastest one.
Example: Mob will go over 100 blocks of soul sand instead of 101 stone blocks.
So i thought that there could be an easy fix to this with a bonus of letting modders make mobs smarter if they want to. 
Some of possible uses:
A village/town mod gives a preference to "willagers" to walk on a block "sidewalk_part".
A minion/worker mob (a great example would be the thaumcraft golems) has x% faster move speed on a special block so they will use the longer but faster path that is made out of the special blocks. 

Rough idea on how this would be mplemented: http://pastebin.com/1nJYkcGw

**Comment by Daomephsta** [comment]
As far as I am aware, Forge has a policy of not changing vanilla behaviour; so it is unlikely that this will happen. If you want an entity to use non-vanilla pathfinding, that is already possible for both vanilla and mod added entities.

**Comment by LapisSea** [comment]
Well it's not changing vanilla behaviour at all. It actually really similar to how forge json models are done.
Give some signal (a marker/flag) that the forge extension should be used so everything that is not specifically telling it to do so would not have any sort of change to it.

**Comment by Daomephsta** [comment]
@LapisSea Alright, however this still doesn't meet any need. Custom navigators for entities, whether they are your own or otherwise, are already possible.

**Comment by LapisSea** [comment]
Yeah you are right but I always thought that it needed some kind of a unification as there is confusion on how it is/should be implemented. Oh well I trust you more than myself when it comes to this so if you think that it is not needed than I'll have to agree. :P

Closing in 30min...
