### ISSUE TITLE
Stairs create see-through hole in upper corner

### ISSUE THREAD

**Issue by MitchellShapiro** [MinecraftForge/MinecraftForge#3224]
All types of stairs placed in this pattern will create a see-through hole on blocks placed next to them.

![2016-08-25_15 40 20](https://cloud.githubusercontent.com/assets/13128898/18024492/7ba39672-6bc0-11e6-896f-0c7b179644c5.png)

**Comment by MitchellShapiro** [comment]
Seems to be fixed, was using old forge version

**Comment by MitchellShapiro** [comment]
Nevermind, present in 1.10.2 Forge 2074

**Comment by TehNut** [comment]
Confirmed http://i.imgur.com/OvcFEZZ.png

**Comment by williewillus** [comment]
does toggling the config option do anything?

**Comment by TehNut** [comment]
Disabling the culling fixes it, yes.
