### ISSUE TITLE
Weird Water Rendering Bug

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3225]
In Forge the water is rendered incorrectly at some distence. This fragments are white if you facing west and black if you facing east. This happens not in Vanilla

http://imgur.com/0FhWlp3
http://imgur.com/4xu1Jji
http://imgur.com/qXkcACM

**Comment by heldplayer** [comment]
Is the 2nd screenshot also with Forge?

Do you have Optifine installed or any other mod for increasing performance?

**Comment by mcenderdragon** [comment]
I have noticed it on the 1.9.4 version of forge, installed a clean 1.10.2 and there was it still. No just pure forge. Its nor a large issue but maybe you can fix it

**Comment by Actuarius** [comment]
@mezz added labels [Bug]

**Comment by mcenderdragon** [comment]
Some similar black pixel stribes appear in 1.10.2 if you looking at snow from far away.

**Comment by mcenderdragon** [comment]
Without Mipmapping this is much more worse.

**Comment by ghost** [comment]
I don't have this problem.  Could it be graphic card related?

**Comment by covers1624** [comment]
Its only an issue for modded fluids.

**Comment by mcenderdragon** [comment]
@covers1624 I think that is wrong, since normal vanilla water is not a modded fluid. 
@trollworkout I have an NVIDIA gtx, but I dont think it is GPU related.

**Comment by mcenderdragon** [comment]
It is still happening in 1.12.2.

**Comment by heldplayer** [comment]
Have you tried doing a clean install of your graphics card drivers?

![image](https://user-images.githubusercontent.com/1283085/34343425-604918ba-e9ce-11e7-9274-d7401222b992.png)

**Comment by mcenderdragon** [comment]
yeah and it also happens on other systems...

**Comment by heldplayer** [comment]
Can you provide comparison images between vanilla and Forge please (with the F3 menu open preferably), as it seems there aren't any images of vanilla yet attached to this issue

**Comment by mcenderdragon** [comment]
It got better in 1.12, and it is now in the Z axis https://imgur.com/a/G7dMP

**Comment by heldplayer** [comment]
Had trouble finding the lines so I increased the brightness and contrast https://imgur.com/a/yuP1D

They're indeed there on the picture with Forge, and not there on the picture in vanilla. Although you're not facing the same direction in both pictures, it might be worthwhile for somebody who knows how the rendering works to check if something is done different from vanilla that could cause this.

**Comment by mcenderdragon** [comment]
also depending wich axis you lock the lines are white or black but only towards the positiv axis, I think in 1.10 it was the negative axis.

**Comment by HenryLoenwind** [comment]
Those look like the artifact you get when you look at a quad from the side.

**Comment by mcenderdragon** [comment]
As this seems not to happen in vanilla (at least as far I noticed) what is forge changing in regads of fluid rendering ?

**Comment by mcenderdragon** [comment]
![2018-07-01_15 00 04](https://user-images.githubusercontent.com/6342933/42134609-a17f04b6-7d3f-11e8-811b-fc2d2d9d3aab.png)

**Comment by mcenderdragon** [comment]
it does still happen.

**Comment by tyler489** [comment]
Interestly. This occurs with FTBs Fluid cows mod. If i understand the way there render works it basicly just renders the fluid over a cow.. I have noticed this through walls especially.

**Comment by mcenderdragon** [comment]
I think your problem has nothing to do with this and it is the 'fault' of the mod-authot, but please provide pictures for better understanding :)
