### ISSUE TITLE
Forge tick screws with server MOTDs

### ISSUE THREAD

**Issue by kailan** [MinecraftForge/MinecraftForge#3229]
Some servers like to have fancy graphics in their MOTD message, but the Forge tick can mess this up and cut off the second line as shown below:

![avic.us](https://i.imgur.com/RBxOjux.png)
![us.oc.tc](https://i.imgur.com/CrQAVcC.png)

On vanilla clients these appear as intended.

**Comment by LexManos** [comment]
This is a "we don't really care" area, MOTDs that use banners are dumb {personal opinion} and we need a place to render this actually vital information.

**Comment by kailan** [comment]
@LexManos I understand it isn't a huge issue but it doesn't look to me like the tick is actually in the space where the banner would be – it's just causing it to wrap around for no reason. This could surely be a quick fix for the sake of appearance.

**Comment by LexManos** [comment]
Except it is, according to the font renderer. Thats how line wrapping works.

**Comment by kailan** [comment]
Wouldn't that mean a fix for this is just to make it overlay the entry instead of causing it to wrap?

**Comment by LexManos** [comment]
That looks like shit, no.

**Comment by kashike** [comment]
Is moving the status checkmark  next to the connection bar not an option?

**Comment by kailan** [comment]
I think this should be re-opened because even though "MOTDs that use banners are dumb", this is something that is functional in the vanilla client and is broken by Forge – that counts as a bug in my book.

**Comment by stuntguy3000** [comment]
@LexManos This is a joke right? It's a bug, don't let it slide.

**Comment by The-Fireplace** [comment]
@LexManos seriously? What happened to your whole "Forge alone should not interfere with the behavior of anything Vanilla" thing? This is a valid issue.

**Comment by KnightMiner** [comment]
This is a minor visual bug that is caused by connecting to a vanilla server. If it that much of an issue, use a vanilla client, like most vanilla servers would prefer anyways.

If it's a Forge server, they can shrink their banner slightly to account for the change
