### ISSUE TITLE
Potioneffect shouldRender

### ISSUE THREAD

**Issue by maxanier** [MinecraftForge/MinecraftForge#3230]
It currently does not seem possible to prevent a vanilla potion from being displayed.
My mod Vampirism allows players to always see at night. Since the lighting/night vision code is deeply integrated in the rendering process, I use the night vision potion for that.  But it is quite annoying that the potion is then always displayed in the inventory (and by some other GUI mods).  
There is a check for [Potion#shouldRender(PotionEffect) ](https://github.com/MinecraftForge/MinecraftForge/blob/f9c7caaf0cda38cdc18842d47e216a66f0c7c14e/patches/minecraft/net/minecraft/potion/Potion.java.patch#L34) which could prevent this, but I cannot directly modify the NightVision/Potion class of course.
Because of that I currently use reflection to replace the night vision potion in MobEffects by my own modified one, which is still recognized by the lighting render code, but is not displayed in the inventory.
That is quite dirty and does not work perfectly.

That's why I would like to see some way of determining, if a potion should be rendered, from the "outside". I think there are two possible solutions for that:
1. Create a Forge event which is checked in addition to the Potion#shouldRender.
2. Add a PotionEffect#shouldRender(), which checks Potion#shouldRender(PotionEffect) by default, and check this instead in the rendering process.

If you think there is a chance something like this will be added and we can choose one solution, I could implement it and create a PR.

**Edit**: Same could go for Potion#shouldRenderHUD(PotionEffect effect) and Potion#shouldRenderInvText(PotionEffect effect)

**Comment by mcenderdragon** [comment]
I personaly like the PotionEffect based variant more. And adding this as an PR should be easy, but I dont know what LexManos or any of the other things.

**Comment by williewillus** [comment]
I vote for PotionEffect as well. Events pollute things too much for my taste and when possible an alternative should be used imo

**Comment by LexManos** [comment]
Or now that potions are a registry you could use the sub system...
There are alternatives and ways to do it correctly. Without reflective hacks.
I don't think there is any need for any changes to do what you want.

**Comment by LexManos** [comment]
Or now that potions are a registry you could use the sub system...
There are alternatives and ways to do it correctly. Without reflective hacks.
I don't think there is any need for any changes to do what you want.

**Comment by LexManos** [comment]
Or now that potions are a registry you could use the sub system...
There are alternatives and ways to do it correctly. Without reflective hacks.
I don't think there is any need for any changes to do what you want.

**Comment by LexManos** [comment]
Or now that potions are a registry you could use the sub system...
There are alternatives and ways to do it correctly. Without reflective hacks.
I don't think there is any need for any changes to do what you want.

**Comment by LexManos** [comment]
Or now that potions are a registry you could use the sub system...
There are alternatives and ways to do it correctly. Without reflective hacks.
I don't think there is any need for any changes to do what you want.

**Comment by LexManos** [comment]
Or now that potions are a registry you could use the sub system...
There are alternatives and ways to do it correctly. Without reflective hacks.
I don't think there is any need for any changes to do what you want.

**Comment by LexManos** [comment]
Or now that potions are a registry you could use the sub system...
There are alternatives and ways to do it correctly. Without reflective hacks.
I don't think there is any need for any changes to do what you want.

**Comment by LexManos** [comment]
Or now that potions are a registry you could use the sub system...
There are alternatives and ways to do it correctly. Without reflective hacks.
I don't think there is any need for any changes to do what you want.

**Comment by LexManos** [comment]
Or now that potions are a registry you could use the sub system...
There are alternatives and ways to do it correctly. Without reflective hacks.
I don't think there is any need for any changes to do what you want.

**Comment by LexManos** [comment]
Or now that potions are a registry you could use the sub system...
There are alternatives and ways to do it correctly. Without reflective hacks.
I don't think there is any need for any changes to do what you want.

**Comment by LexManos** [comment]
Or now that potions are a registry you could use the sub system...
There are alternatives and ways to do it correctly. Without reflective hacks.
I don't think there is any need for any changes to do what you want.

**Comment by maxanier** [comment]
Not sure if that can be done.
It is currently not possible to add a substitution alias to the potion registry, because the ["addSubstitutionAlias" method](https://github.com/MinecraftForge/MinecraftForge/blob/f9c7caaf0cda38cdc18842d47e216a66f0c7c14e/src/main/java/net/minecraftforge/fml/common/registry/FMLControlledNamespacedRegistry.java#L631) has package local access, and the [GameData version ](https://github.com/MinecraftForge/MinecraftForge/blob/f9c7caaf0cda38cdc18842d47e216a66f0c7c14e/src/main/java/net/minecraftforge/fml/common/registry/GameData.java#L203) only helps with items and blocks.

And even if that would be changed, it might not work either. The renderer as well as most other potion related things access the fields in MobEffects to get the potion object. This means I have to activate the substitution before MobEffects is accessed for the first time. So I guess other mods could cause some trouble there.

But if you can tell me how I can access the substitution methods, I will give it a try.

**Comment by LexManos** [comment]
I'll put moving the GameData method to generic on my to-do list.
However your concern about order of accessing MobEffects is not warranted because our alias system supports reflectively replacing the instances in static final fields using our @ObjectHolder system.
So that would take care of itself.
The idea is to move all of this stuff to generic IForgeRegistryEntry methods instead of block/item specific.
As the Forge registry system is extreamly powerful and does most of what everyone wants in the correct manor.
Its just a work in progress converting it to a generic system for all things as it was originally designed for specifically blocks/items.

**Comment by maxanier** [comment]
ok, thanks.
The Forge registry system looks indeed quite powerful. I will wait for the generic method then :)
