### ISSUE TITLE
BlockFluidFinite does not conserve quantity of fluid

### ISSUE THREAD

**Issue by droidicus** [MinecraftForge/MinecraftForge#3231]
When a bucket of a finite fluid is placed in the world, the default state of the BlockFluidFinite is used, while a full block is required to pick up in a bucket. This results in quantaPerBlock buckets needing to be placed to make a full BlockFluidFinite, and when picked up with an empty bucket a single bucket is returned. The result is that fluids are not conserved, and most of the fluid is lost.

Comments on IRC from @PaleoCrafter

> 2:47 PM <•PaleoCrafter> it uses the default state, so it appears that's wrong for the finite fluids?
> 2:53 PM <•PaleoCrafter> or actually, FluidUtil.tryPlaceFluid should respect the passed fluid stack's quantity and modify the blockstate accordingly, would require some bigger modifications though
> 2:55 PM <•PaleoCrafter> IFluidBlock would require some sort of FluidStack -> Pair<IBlockState, FluidStack> method (the fluid stack in the pair being the remaining fluid if there's no 1:1 match)

**Comment by Actuarius** [comment]
@mezz added labels [Superseded, Bug]

**Comment by bs2609** [comment]
Is this fixed by #3509?

**Comment by mezz** [comment]
Yep, should be.
