### ISSUE TITLE
Make Animation API more usable from code

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3235]
@RainWarrior 

Here's the current condition:
- I have a model generated at runtime by combining two other models (it has no IModel form, it is two IBakedModels that could be _anything_ at runtime, mashed together using UnpackedBakedQuad)
- I would like to animate it in an animated tesr in some way or another because traditional TESR + bakedmodel render has too much overhead
- I currently have no way of defining the clips because they are tightly coupled to the vanilla/B3D model representations. I want the entire model to bob up and down and spin (so no need to worry about subpart animation), but don't want to define this motion in code. The ModelBlockAnimation armature format is perfect for this but requires binding to an actual ModelBlock (which my model can't have)

Is there a way that I can leverage the animation API/armature/IASM for my hybrid model?

**Comment by heldplayer** [comment]
I'm not sure this belongs on the issue tracker, this would be better suited on the forums as you're asking a question.

**Comment by mcenderdragon** [comment]
You could do a workaroud by making your own TileEntityRenderer extending AnimationTESR.

**Comment by williewillus** [comment]
@mcenderdragon that's not the issue, the issue is that sone things are hard coded to a specific model format and I can't easily use them for dynamically generated models

**Comment by Actuarius** [comment]
@mezz added labels [Feature]

**Comment by williewillus** [comment]
No one cares about the animation api anyway
