### ISSUE TITLE
bad RuntimeInvisibleParameterAnnotations attribute

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3238]
The following exception appears when using a extended `NetHandlerPlayClient` to handle incoming packet data.

```
:compileJava
NetHandlerSub.java:89: error: cannot access AddPlayerData
        for(SPacketPlayerListItem.AddPlayerData data : packetIn.getEntries()) {
        ^
  bad class file: .gradle\minecraft\forgeBin-1.10.2-12.18.1.2011-PROJECT(projectname).jar(net/minecraft/network/play/server/SPacketPlayerListItem$AddPlayerData.class)
    bad RuntimeInvisibleParameterAnnotations attribute: AddPlayerData(GameProfile,int,GameType,ITextComponent)
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

```
mc_version=1.10.2
forge_version=12.18.1.2011
mappings=snapshot_20160518
```

```
    @Override
    public void handlePlayerListItem(SPacketPlayerListItem packetIn) {
        packetIn = (SPacketPlayerListItem) HookManager.packetManager.execute(new NetHandlerData(this, packetIn), Phase.START);

        for(SPacketPlayerListItem.AddPlayerData data : packetIn.getEntries()) {
            // do things
        }

        super.handlePlayerListItem(packetIn);
    }
```

I'm not quite sure how this happens, but would this be an user error, or a problem with Forge or MCP?

**Comment by LexManos** [comment]
There are no Runtime INvisible annotations on the AddPlayerData constructor.
So there is something in your setup that is causing something to be corrupted.
Also, why are you subclassing NetHandlerPlayClient?
There should be no reason you need to be handling the network traffic directly.

**Comment by kashike** [comment]
Are you using the `setupCIWorkspace` task? This issue seems to occur with it if I recall, so try using `setupDecompWorkspace`.
This issue has popped up before - I know @Mumfrey created a test project to reproduce this, although I'm not sure if it still occurs: https://github.com/Mumfrey/SetupCITest

**Comment by ghost** [comment]
@LexManos I'm subclassing `NetHandlerPlayClient` because to my knowledge, there is no other way to easily obtain, intercept or otherwise obtain the data that `SPacketPlayerListItem` transmits on runtime.

@kashike I've been using `gradlew setupDecompWorkspace` and `gradlew build` to build the project.

**Comment by ghost** [comment]
Problem resolved by clearing out `~/.gradle` and `.gradle` and re-running `gradlew setupDecompWorkspace` IDE is not able to pick up any of the dependencies, but at least it builds now.

Sorry for wasting time here, seems that it was a typical PEBKAC
