### ISSUE TITLE
[1.10.2] ForgeHooks.onPickBlock() does not send item capabilities to the server

### ISSUE THREAD

**Issue by kingbdogz** [MinecraftForge/MinecraftForge#3239]
I've noticed that when pick-blocking an item that has capabilities from an Entity or Tile Entity, the capability data is not synced to the server.

From what I'm understanding, when a player pick-blocks an Entity, the result is processed on the client side and then a packet (CPacketCreativeInventoryAction) is sent to the server to notify it of the result. Problem is, when this packet writes the ItemStack to the ByteBuf, it is only writing the NBTTagCompound from ItemStack.getTagCompound(). This does not include capability data.

It is my understanding that the packet should be using ItemStack.serializeNBT() instead. This does not seem to be a problem when playing on an internal server (client), but breaks functionality completely in Multiplayer.

Let me know if I am simply misunderstanding how to manage capability storage here, but I do believe this is a bug.

**Comment by Actuarius** [comment]
@mezz added labels [Bug]

**Comment by Jezza** [comment]
Taking a look at `PacketBuffer#writeItemStackTo()`, I can see that quite a number of packets use (11 at last count), without using `ItemStack.serializeNBT()`, so a bigger question remains:
Should we do this for all packets that attempt to send an ItemStack, or just this one?
Are we likely to have this problem in the future with another packet?
