### ISSUE TITLE
Game crashes upon loading a world [1.10.2]

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3242]
@bloodmc Everytime I try to load a world with mods, it just crashes completely with no reason. I tried fixing and everything but no possible fix but to remove all mods. Make a new recommended version 2012 or latest 2078 with a fix of this crash here. NOTE I don't use pastebin so... Here's the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 16.9.9 23.14
Description: Unexpected error

java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
    at com.google.common.base.Absent.get(Absent.java:47)
    at eu.ha3.matmos.game.mod.MAtMod.onTick(MAtMod.java:305)
    at eu.ha3.mc.haddon.litemod.LiteBase.onTick(LiteBase.java:76)
    at com.mumfrey.liteloader.core.event.HandlerList$Tickable9.onTick(HandlerList$Tickable9.java:102)
    at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onTick(LiteLoaderEventBrokerClient.java:454)
    at com.mumfrey.liteloader.client.ClientProxy.onTick(ClientProxy.java:69)
    at net.minecraft.client.Minecraft.handler$onTick$0(Minecraft.java:68)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at com.google.common.base.Absent.get(Absent.java:47)
    at eu.ha3.matmos.game.mod.MAtMod.onTick(MAtMod.java:305)
    at eu.ha3.mc.haddon.litemod.LiteBase.onTick(LiteBase.java:76)
    at com.mumfrey.liteloader.core.event.HandlerList$Tickable9.onTick(HandlerList$Tickable9.java:102)
    at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onTick(LiteLoaderEventBrokerClient.java:454)
    at com.mumfrey.liteloader.client.ClientProxy.onTick(ClientProxy.java:69)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['BrunoOMG'/378, l='MpServer', x=256,39, y=52,00, z=282,12]]
    Chunk stats: MultiplayerChunkCache: 82, 82
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (247,64,279), Chunk: (at 7,4,7 in 15,17; contains blocks 240,0,272 to 255,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 18453347 game time, 6000 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 53 total; [EntityZombie['Husk'/128, l='MpServer', x=205,50, y=44,00, z=273,50], EntityZombie['Husk'/129, l='MpServer', x=207,50, y=44,00, z=273,50], EntityZombie['Husk'/130, l='MpServer', x=205,50, y=44,00, z=275,50], EntityZombie['Husk'/131, l='MpServer', x=207,50, y=44,00, z=275,50], EntityItem['item.item.egg'/132, l='MpServer', x=198,14, y=44,00, z=272,88], EntityItem['item.item.egg'/133, l='MpServer', x=199,99, y=44,00, z=273,75], EntityItem['item.item.egg'/134, l='MpServer', x=197,68, y=44,00, z=276,41], EntityItem['item.item.egg'/135, l='MpServer', x=199,69, y=44,00, z=275,13], EntityArmorStand['Armor Stand'/64, l='MpServer', x=149,50, y=43,20, z=273,50], EntityArmorStand['Armor Stand'/66, l='MpServer', x=151,50, y=43,20, z=273,50], EntityArmorStand['Armor Stand'/68, l='MpServer', x=150,50, y=43,20, z=275,50], EntityEnderCrystal['entity.EnderCrystal.name'/76, l='MpServer', x=161,50, y=45,00, z=249,50], EntitySheep['jeb_'/88, l='MpServer', x=182,50, y=44,00, z=284,50], EntitySheep['Sheep'/89, l='MpServer', x=185,50, y=44,00, z=284,50], EntitySheep['Sheep'/90, l='MpServer', x=187,50, y=44,00, z=284,50], EntitySheep['Sheep'/91, l='MpServer', x=189,50, y=44,00, z=284,50], EntitySheep['Sheep'/92, l='MpServer', x=191,50, y=44,00, z=284,50], EntitySheep['jeb_'/93, l='MpServer', x=182,50, y=44,00, z=286,50], EntitySheep['Sheep'/94, l='MpServer', x=185,50, y=44,00, z=286,50], EntitySheep['Sheep'/95, l='MpServer', x=187,50, y=44,00, z=286,50], EntitySheep['Sheep'/96, l='MpServer', x=189,50, y=44,00, z=286,50], EntitySheep['Sheep'/97, l='MpServer', x=191,50, y=44,00, z=286,50], EntitySkeleton['Skeleton'/98, l='MpServer', x=181,50, y=44,00, z=273,50], EntitySkeleton['Skeleton'/99, l='MpServer', x=183,50, y=44,00, z=273,50], EntitySkeleton['Skeleton'/100, l='MpServer', x=182,50, y=44,00, z=275,50], EntitySkeleton['Skeleton'/101, l='MpServer', x=189,50, y=44,00, z=273,50], EntitySkeleton['Skeleton'/102, l='MpServer', x=191,50, y=44,00, z=273,50], EntitySkeleton['Skeleton'/103, l='MpServer', x=190,50, y=44,00, z=275,50], EntitySheep['Sheep'/104, l='MpServer', x=193,50, y=44,00, z=284,50], EntitySheep['Sheep'/105, l='MpServer', x=195,50, y=44,00, z=284,50], EntitySheep['Sheep'/106, l='MpServer', x=197,50, y=44,00, z=284,50], EntitySheep['Sheep'/107, l='MpServer', x=199,50, y=44,00, z=284,50], EntitySheep['Sheep'/108, l='MpServer', x=201,50, y=44,00, z=284,50], EntitySheep['Sheep'/109, l='MpServer', x=203,50, y=44,00, z=284,50], EntitySheep['Sheep'/110, l='MpServer', x=205,50, y=44,00, z=284,50], EntitySheep['Sheep'/111, l='MpServer', x=207,50, y=44,00, z=284,50], EntitySheep['Sheep'/112, l='MpServer', x=193,50, y=44,00, z=286,50], EntitySheep['Sheep'/113, l='MpServer', x=195,50, y=44,00, z=286,50], EntitySheep['Sheep'/114, l='MpServer', x=197,50, y=44,00, z=286,50], EntitySheep['Sheep'/115, l='MpServer', x=199,50, y=44,00, z=286,50], EntitySheep['Sheep'/116, l='MpServer', x=201,50, y=44,00, z=286,50], EntitySheep['Sheep'/117, l='MpServer', x=203,50, y=44,00, z=286,50], EntitySheep['Sheep'/118, l='MpServer', x=205,50, y=44,00, z=286,50], EntitySheep['Sheep'/119, l='MpServer', x=207,50, y=44,00, z=286,50], EntityChicken['Chicken'/120, l='MpServer', x=197,50, y=44,00, z=273,50], EntityPigZombie['Zombie'/121, l='MpServer', x=197,50, y=44,35, z=273,40], EntityChicken['Chicken'/122, l='MpServer', x=199,50, y=44,00, z=273,50], EntityPlayerSP['BrunoOMG'/378, l='MpServer', x=256,39, y=52,00, z=282,12], EntityZombie['Husk'/123, l='MpServer', x=199,50, y=44,35, z=273,40], EntityChicken['Chicken'/124, l='MpServer', x=197,50, y=44,00, z=275,50], EntityZombie['Zombie'/125, l='MpServer', x=197,50, y=44,35, z=275,40], EntityChicken['Chicken'/126, l='MpServer', x=199,50, y=44,00, z=275,50], EntityZombie['entity.Zombie.name'/127, l='MpServer', x=199,50, y=44,35, z=275,40]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:498)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_102, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
    Memory: 3347036616 bytes (3191 MB) / 4080271360 bytes (3891 MB) up to 8375238656 bytes (7987 MB)
    Mod Pack: com.mumfrey.liteloader.crashreport.CallableLiteLoaderBrand@31623581
    LiteLoader Mods: com.mumfrey.liteloader.crashreport.CallableLiteLoaderMods@75e2f56f
    LaunchWrapper: com.mumfrey.liteloader.crashreport.CallableLaunchWrapper@3973f4f8
    JVM Flags: 30 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xrs -Xmx8G -Xms4G -Xmn2G -XX:ThreadPriorityPolicy=42 -XX:+TieredCompilation -XX:TargetSurvivorRatio=90 -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=15 -XX:+UnlockExperimentalVMOptions -XX:+UseBiasedLocking -XX:UseSSE=3 -XX:+UseCodeCacheFlushing -XX:+UseThreadPriorities -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -XX:+ReduceSignalUsage -XX:+UseInterpreter -XX:+UseFastEmptyMethods -XX:+UseSharedSpaces -XX:AllocatePrefetchStyle=1 -XX:+AlwaysCompileLoopMethods -XX:SharedReadOnlySize=30m -XX:+UseConcMarkSweepGC -XX:+RewriteFrequentPairs -XX:+OptimizeStringConcat -XX:+CMSCleanOnEnter -XX:+UseSplitVerifier -XX:+UseInlineCaches
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2077 Optifine OptiFine_1.10.2_HD_U_C4_pre 11 mods loaded, 11 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2077.jar) 
    UCHIJAAAA   Forge{12.18.1.2077} [Minecraft Forge](forge-1.10.2-12.18.1.2077.jar) 
    UCHIJAAAA   BetterFoliage{2.1.0} [Better Foliage](BetterFoliage-MC1.10-2.1.0.jar) 
    UCHIJAAAA   CoroAI{v1.1.8} [CoroAI](coroutil-1.10.2-1.1.8.jar) 
    UCHIJAAAA   ExtendedRenderer{v1.0} [Extended Renderer](coroutil-1.10.2-1.1.8.jar) 
    UCHIJAAAA   ConfigMod{v1.0} [Extended Mod Config](coroutil-1.10.2-1.1.8.jar) 
    UCHIJAAAA   HardcoreDarkness{1.8} [Hardcore Darkness](HardcoreDarkness-MC1.9.4-1.8.jar) 
    UCHIJAAAA   soundfilters{0.9_for_1.9} [Sound Filters](SoundFilters-0.9_for_1.9.4.jar) 
    UCHIJAAAA   treechopper{1.0.3a} [Tree Chopper](TreeChopper-1.0.3a.jar) 
    UCHIJAAAA   weather2{v2.3.15} [Localized Weather & Storms](weather2-1.10.2-2.3.15.jar) 
    Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.70' Renderer: 'GeForce GTX 960/PCIe/SSE2'
    Launched Version: 1.10.2-forge1.10.2-12.18.1.2077
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.70, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
OptiFine Version: OptiFine_1.10.2_HD_U_C4_pre
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.0 NVIDIA 372.70
OpenGlRenderer: GeForce GTX 960/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 4
```

Thank you and please fix it.

**Comment by TehNut** [comment]
This is a MATMOS crash which doesn't even use Forge.

> I don't use pastebin

Well start.

**Comment by ghost** [comment]
oh DUH... thanks for telling... matmos you piece of crep!!
