### ISSUE TITLE
PlayerDestroyItemEvent does not fire on the client if Block::onBlockActivated() returns true

### ISSUE THREAD

**Issue by KnightMiner** [MinecraftForge/MinecraftForge#3243]
Currently, `PlayerDestroyItemEvent` is fired on both sides if `Block::onBlockActivated()` returns false, but only on the server side if `Block::onBlockActivated()` returns true.

This causes a problem as anything listening for `PlayerDestroyItemEvent` if a block can break an item as they cannot know whether they need to send packets to the client side or not for client sided behavior since it is called on the client side most of the time (including cases where no block is right clicked)

Using Forge build 1.10.2-12.18.1.2076, so this is after the fix for #2565.

**Comment by Actuarius** [comment]
@mezz added labels [Bug]

**Comment by KnightMiner** [comment]
@bs2609: Did you fix this as a part of #3728? I am wondering if this can be closed now.

**Comment by bs2609** [comment]
Probably?
The event is now fired [here](https://github.com/MinecraftForge/MinecraftForge/pull/3728/files#diff-d04f8781da5b0a341f7909d495447911R269) in `PlayerInteractionManager`, which seems like it would fix this.
Please do check though.

**Comment by KnightMiner** [comment]
Just tested it and it seems it now no longer even calls the event on the server side when right clicking a block. Additionally, even if right clicking the block returns false, it still does not throw the event that chuck of code is skipped entirely for empty itemstacks (which it is empty by that point as the block method made it empty).

Basically, the event only seems to be thrown if a non-empty stack is made empty through a right click through the item method.

**Comment by bs2609** [comment]
Right I see. The event is fired if an item is destroyed after a call to `onItemUse`, but the calls to `onItemUseFirst()`, and `onBlockActivated()` aren't checked.

This is fixable, but I don't know if it's intended to have items be broken by those methods.

**Comment by KnightMiner** [comment]
Yep, still valid. Since there has been no changes to destroy item events recent, behavior is as I described above.
