### ISSUE TITLE
ItemStack.serializeNBT() returning empty ForgeCaps tag

### ISSUE THREAD

**Issue by droidicus** [MinecraftForge/MinecraftForge#3244]
When calling serializeNBT on a ItemStack of a Forge UniversalBucket, the returned NBT data has an empty ForgeCaps tag. JEI has been patched to ignore this empty tab, but according to Lex the ForgeCaps tag should never be empty in the first place.

https://github.com/mezz/JustEnoughItems/blob/1.10/src/main/java/mezz/jei/util/StackHelper.java#L386-L399

**Comment by LexManos** [comment]
This has been fixed.
