### ISSUE TITLE
Forge Energy API and Minecraft-Flux... Coincidence?

### ISSUE THREAD

**Issue by szeweq** [MinecraftForge/MinecraftForge#3249]
I'm a developer of [Minecraft-Flux](https://github.com/Szewek/Minecraft-Flux). I'm not complaining but I found that [Forge Energy API](https://github.com/MinecraftForge/MinecraftForge/tree/1.10.x/src/main/java/net/minecraftforge/energy) and [Minecraft-Flux EX API](https://github.com/Szewek/Minecraft-Flux/tree/master/src/main/java/szewek/mcflux/api/ex) look very similar to each other. Also the time period between these two API implementations is just one week.The only major difference between them is type: Minecraft-Flux uses `long` and Forge – `int`.

@LexManos Is this really a coincidence that energy API you implemented resembles my API? It's great that Forge has its own energy system, but "Heavy RF Inspiration" is a bit exaggerated.

**Comment by LatvianModder** [comment]
Tbh all current capability-based energy APIs look the same. That's exactly why forge added an API that looks like all other ones

**Comment by yuuka-miya** [comment]
I'll just leave this here...

https://github.com/CoFH/CoFHLib/tree/master/src/main/java/cofh/api/energy

**Comment by simon816** [comment]
Did you read the license header of those files?

>  Derived from the Redstone Flux power system designed by King Lemming and originally utilized in Thermal Expansion and related mods.
>  Created with consent and permission of King Lemming and Team CoFH. Released with permission under LGPL 2.1 when bundled with Forge.

**Comment by BlayTheNinth** [comment]
Forge's energy is literally RF minus .setStoredEnergy() plus capability. If it resembles any other power API then that's because that power API resembled RF in the first place.
