### ISSUE TITLE
[Event idea] BlockReplaceEvent

### ISSUE THREAD

**Issue by skyjay1** [MinecraftForge/MinecraftForge#3253]
There are currently no methods to intercept block behavior such as **ice becoming water, snow becoming air, flowing lava becoming stone or cobblestone, still lava becoming obsidian, dirt becoming grass, or sugarcane becoming air**
I suggest adding an event for these situations to allow modders to change that kind of behavior without ASM replacement.
Using current events, such as `BlockPlaceEvent`and `MultiPlaceEvent`, will not work here because those events require an EntityPlayer field. We need a new event to handle the listed conditions above.
`BlockReplaceEvent`would have these properties, possibly extending `BlockEvent`:

```
@Cancelable - this event would be cancelable
Constructor: BlockReplaceEvent(World worldIn, BlockPos posIn, IBlockState currentState, IBlockState defaultNextState) 
World world - the world of this event
BlockPos pos - the position of this event
IBlockState state - the current IBlockState at this position
IBlockState nextState - the IBlockState to replace the block when this event is finished (if it is not canceled). 
  This would need to be accessed in the block's code wherever it specifies which block to become.
public IBlockState getNextState()
public void setNextState(IBlockState nextStateIn)
```

If I missed any conditions in my above list, please comment and I will add them to this post.
Edit: changed from IceThawEvent to BlockReplaceEvent as per Leviathan143's suggestion

**Comment by Daomephsta** [comment]
I think this should be a more generic event. Lava and water forming cobble, stone or obsidian could easily be worked into this event.

**Comment by skyjay1** [comment]
> I think this should be a more generic event. Lava and water forming cobble, stone or obsidian could easily be worked into this event.

Added to main post.

**Comment by Actuarius** [comment]
@mezz added labels [Feature]
