### ISSUE TITLE
Special characters not rendering properly

### ISSUE THREAD

**Issue by jensz12** [MinecraftForge/MinecraftForge#3258]
Forge does not render UTF-8 special charaters like æøåö and so on properly, when used in splash.txt
![char](https://static.jensz12.com/forge.PNG)

Tested using 1.10.2 - 12.18.1.2076 and newer versions

**Comment by iTitus** [comment]
It looks like you are using a resource pack, could you try to reproduce without that?

**Comment by jensz12** [comment]
Same issue :-)

**Comment by jensz12** [comment]
@iTitus ![char](https://static.jensz12.com/splashes1.PNG)

**Comment by LexManos** [comment]
Most notibly, does this work in vanilla as we don not muddle with the rendering of this.
Its all the same font render thats used for everything else and chat. As long as the UTF8 glyphs are in the normal font pack that comes with vanilla then it will work.

Also, be sure your splashes.txt is SAVED properly. Most text editors will default to ASCII over UTF8.

**Comment by jensz12** [comment]
This works fine in vanilla. And my Notepad++ saves in UTF-8. So thats not the issue

**Comment by LexManos** [comment]
Just tested your exmaples and it works just fine http://puu.sh/rh5yB/3e2a5f4b57.jpg
Either you have something else installed on your game or you saved your splashes wrong as your image looks like what it would be converted to ANSI.
But ya this isn't a Forge issue.

**Comment by liach** [comment]
Was that because of forced Unicode character or something else?

**Comment by LexManos** [comment]
All I did was create a a splash.txt with the above text, saved as UTF8 and it loaded just fine.
