### ISSUE TITLE
[1.10.2] Feature Request: Allow automatic @ObjectHolder injection for fields with different case to registry name

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#3261]
I use `CONSTANT_CASE` for my `Block`/`Item` fields to match the Java and MCP naming conventions and `snake_case` for my registry names to prepare for 1.11's restrictions, but this prevents a class-level `@ObjectHolder` annotation from automatically injecting into the fields (requiring each field to be annotated).

Would it be possible to use the field's existing value to get the registry name for injection (like FML does for `Blocks`/`Items`) or try to use the field's lowercase name as the registry name?

**Comment by LexManos** [comment]
@ObjectHolder allows you to specify a different name.

**Comment by Choonster** [comment]
I'm aware of that, but I was hoping for a way to only annotate the class and have the fields automatically injected without having to annotate each field.

**Comment by LexManos** [comment]
Until we{Read vanilla} enforce lower cased names we can't do that because technically two things could have the same name but different case, it would be stupid but I'm pretty sure they could. So we wouldnt know which one to use.

**Comment by Choonster** [comment]
That's fair enough.

It looks like 1.11 will coerce the path component of `ResourceLocation`s to lowercase, so what I'm asking for should automatically work.
