### ISSUE TITLE
[1.10.2] Feature Request: split item NBT into functional and decorative part

### ISSUE THREAD

**Issue by Dragon2488** [MinecraftForge/MinecraftForge#3262]
It's really hard to compare recipe input items because of nbt. Even "display" tag can break item usage in recipes. So the idea is to split items NBT to "functional" part, which is data that used to compare items in recipes and anything like that and "decorative" for things like item name, lore, color which aren't change item usage in recipes. It's really a headache now, especially for items like fluid containers.

**Comment by williewillus** [comment]
I feel like this would make the headache even worse

**Comment by LexManos** [comment]
Yes, it would, And there really isn't a way to have a separation as its just one NBT compound. We'd have to just go through and blacklist every nbt key.
Its far more practical that if you're writing a recipe handler you ONLY handle the keys you want or care about. Just like normal recipes dont care about NBT at all and don't handle it at all.
And then what about recipes that CARE about the lore? 
If you can think of and explain yourself better thwen we may think about it, but there is no generic way to do it.
