### ISSUE TITLE
[1.10.2] Custom EntityHanging doesn't render on a server.

### ISSUE THREAD

**Issue by palaster** [MinecraftForge/MinecraftForge#3263]
I am dealing with a custom entity that extends EntityHanging. But, no matter what I do with the renderer it doesn't show up on servers. I even went as far as to create a clone of the EntityItemFrame and RenderItemFrame and it still doesn't show up on server. I have registered both the entity and the renderer.

This is the original Entity: https://github.com/Vazkii/Charset/blob/1.10/src/main/java/pl/asie/charset/storage/locking/EntityLock.java
This is the original Render:
https://github.com/Vazkii/Charset/blob/1.10/src/main/java/pl/asie/charset/storage/locking/RenderLock.java

**Comment by LexManos** [comment]
This is a place for reporting bugs in Forge not for getting tech support for your mod. Use the forums.
Also, protip for when you do post there, nobody will help you unless you provide the actual code you're working on. Not what you're referencing.
