### ISSUE TITLE
BlockCallbacks IForgeRegistry ArrayIndexOutOfBoundsException: 16

### ISSUE THREAD

**Issue by Zetal911** [MinecraftForge/MinecraftForge#3268]
Registering a block with many different metadatas or states (I'm not sure of the exact circumstance) causes an ArrayIndexOutOfBoundsException that crashes the game on load.

For what it's worth, I'm trying to register a cake block. Works fine in 2043, but not in most recent.

**Comment by LexManos** [comment]
You need to make sure your metadata system doesnt go beyond 15.
Also stack traces are essential to debugging.
Also, you should use the forums to verify its a Forge issue before you bring it to github.
