### ISSUE TITLE
[1.8x],[1.7.10] Not Always Setting Harvest Level

### ISSUE THREAD

**Issue by jredfox** [MinecraftForge/MinecraftForge#3277]
Versions: 1.10.2 ,1.8x, 1.7.10

Both block objects and a direct reference to a field of a block do not set the harvest level unless you just happen to fall into the side of the bug that it doesn't effect.  For example below I set the cobblestone harvest level to 3 and that worked for 1.10.2 but, it didn't work with bedrock. I have tested this in pre-init, init, post init with no other results. 

Code:
//works
 Blocks.COBBLESTONE.setHarvestLevel("pickaxe", 3);

 //Doesn't work
 Blocks.BEDROCK.setHardness(5);
 Blocks.BEDROCK.setHarvestLevel("pickaxe", 3);

If you noticed the cobblestone set harvest level worked but, not the bedrock. I don't know why this is however I think it's because, bedrock didn't have a set harvest level and cobblestone did. This issue has been in here for a long time I am not sure why the maker of the original block properties mod didn't mention this to you.

For version 1.7.10  and 1.8x Code:

  //doesn't work
  Blocks.cobblestone.setHarvestLevel("pickaxe", 3);

  //works 
 Blocks.bedrock.setHardness(5);
 Blocks.bedrock.setHarvestLevel("pickaxe", 3);

As you can see lower versions seem to be inverted from the bug. This time if it has a harvest level already it won't set it otherwise it will.

**Comment by LexManos** [comment]
How are you testing the harvest levels? The code works just fine all it does is set the value in the array.

**Comment by jredfox** [comment]
Well if it drops with a wooden pickaxe it doesn't work. It should only drop it's block if the tool material level or whatever is 3 or above. Why would it active harvest drops event if the harvest level not >= to your new set level? That's the point of setting a harvest level? Have you printed the array maybe it added it twice? Maybe it's not setting it? Or maybe it just an't working?

**Comment by williewillus** [comment]
You should test with something other than bedrock. There may be special cases where it's hardcoded not to be breakable or something

**Comment by jredfox** [comment]
Well either way there is an issue if cobblestone still drops with a wooden pickaxe.

**1.7.10  and 1.8x test**

**1.7.10 only**
Another Issue is I have just tried it using the one with the metadata and the same result happened with stone dropping with no other code.

 Blocks.cobblestone.setHarvestLevel("pickaxe", 3, 0);

**Everything 1.7-1.8x**
I then thought it might be because, the block doesn't drop itself so I tried

 Blocks.iron_block.setHarvestLevel("pickaxe", 3);

This yielded the same output dropping the block with a wooden pickaxe.  **However It shouldn't even activate the harvest drops event or at least not drop it if the tool material isn't high enough that is the point of harvest level**. 

**1.10.2**
It works I just didn't see now that bedrock refuses to drop itself unlike all previous versions. I don't know why anybody else didn't catch that bedrock doesn't drop itself by default.

**1.7.10 and 1.8x**
Please fix this issue for 1.7.10 , 1.8 and 1.8.9 once it should take an hour to fix the issue with 1.7.10 for you and almost no time since your code fixes in 1.10.2 are very similar if not the same for 1.8x.  If you backport could you also fix this one issue for 1.7.10 , 1.8 and maybe 1.8.9 where fuel was stored as short but, the numbers you could pass in were integer. I need this for my other mod called the charcoal block mod. Thanks sorry for my stupidness and seeing bedrock didn't drop itself.   These issues from **1.8x and 1.7.10 came from** #2525

**Comment by williewillus** [comment]
Those two versions are 2/3 major versions behind where we are now, and they aren't "wipe your hard drive" level bugs so those versions aren't being updated.

**Comment by LexManos** [comment]
So, TLDR, is that it is working as intended on 1.10.2, and his understanding of the related code is incorrectly. The issues he was running into was caused by using a special cased block BEDROCK. 

The 1.7.10/1.8.x 'bugs' don't actually seem to be bugs but more a misunderstanding of the code. And even if they were, willie is correct, this is a non critical issue and this does not get backported. You shouldn't be modding for such old versions.

**Comment by jredfox** [comment]
Yeah it's working for version 1.10.2. I was asking for a special update since 1.8.9 is recent and then why not the other two versions that are frequently being modded as well 1.8, 1.7.10

Edit: **No It's Not Working All The Time See Below For Details**

**Comment by jredfox** [comment]
No it's actually not working with all the materials.  I correct myself now.  If you use in **1.10.2**
 Blocks.GRASS.setHarvestLevel("shovel", 3);

It will still drop it's drops you need to support all materials and tools.

**Comment by diesieben07** [comment]
I don't think you are supposed to use those kinds of methods on Blocks that are not yours. Use the events like BreakSpeed and HarvestDrops to control these types of behaviors for Blocks that are not yours..

**Comment by jredfox** [comment]
Um no I perfectly set the harvest levels of modded blocks if the material was **material.rock for 1.10.2** else since vanilla has no need to support it, forge doesn't support it.  I re-brought up this issue here after it closed **when I realized it didn't work with every material** . For 1.8x and below you have to call new forge hooks have to have an event handler and a whole bunch of other stuff.  I am glad they half fixed this for 1.10.2 but, they need to fully fix this.  If a block is publicly accessible so are it's properties.

**Block block = GameRegistry.findBlock(modid, name);**
block.properties

or if vanilla
**Blocks.vanillablock.properties**

This won't work with all properties like fire, I need to figure that out.

**Comment by Choonster** [comment]
If a `Material` isn't set to require a tool, Forge ignores the harvest level of any `Block` that uses it. This appears to be an intended preservation of vanilla behaviour.

**Comment by jredfox** [comment]
Ok well if material.dirt  has a tool assigned to it then open this issue I will make my own event handler for 1.10.2 as well if it doesn't have a tool assigned to it.
