### ISSUE TITLE
Use thread groups to determine effective side

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#3279]
At present, `FMLCommonHandler#getEffectiveSide()` just checks the given name of the thread to determine the thread context.

One possibility for a more reliable method to determine this would be to create a `ThreadGroup` object and use it in the construtor for the initial server `Thread` instance (`MinecraftServer.startServerThread()`).
Then, a thread can be considered to be a 'server' thread if it's thread group is the server thread group, or one of its decendants. (eg `serverThreadGroup.parentOf(Thread.currentThread().getThreadGroup())`)

This would require a patch, but the changes needed should be small (only at initial thread creation)

As I'm not too familiar with how Forge/Minecraft interact at startup though, I'd appreciate anyone with more knowledge weighing in on the feasibility of this.

**Comment by LatvianModder** [comment]
What about threads that are created by modders? Would their side be neither, if its not assigned?

**Comment by bs2609** [comment]
The logic is as follows:
- If a thread is created with no thread group specified, it is assigned to the thread group of the thread that created it.
- Likewise a thread group created with no parent thread group specified will take the creating thread's thread group as a parent.

So if client/server threads are defined as early as possible, all threads normally created should inherit the correct side naturally.

**Comment by diesieben07** [comment]
This would mean that all mods that currently abuse `getEffectiveSide` as an "am I on the main thread" check would break.

**Comment by LatvianModder** [comment]
That's an emergency case check anyway. Almost always there's world.isRemote available

**Comment by LexManos** [comment]
This function should only be used when there is literally no way to tell which side you're on, which need to be proven as a valid case before we care to change how it works. 99.9% of the code base has the world available to it some where

**Comment by bs2609** [comment]
I guess it would be needed if you get an `IBlockAccess` that's not an instance of `World` for whatever reason.
Anyone who uses this function, care to share your use cases?

**Comment by bs2609** [comment]
Resolved by #3644
