### ISSUE TITLE
Fluid Registry does not act like the other registry systems.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#3281]
The fluid registry currently uses a different system which predates the updated namespace registries used. While the system isn't broken, it is missing a few features that the newer registries offer, and also contributes to the amount of duplicate code in forge. The feature I specifically want is the ability to get the ID of a mod which registered a fluid. The newer registries allow for this to be pulled from the ResourceLocation based identifier. While the RegistryDelegate class used by the older system provides a way to get a ResourceLocation, the actual fluid registry does not track or enforce the mod id, so only the second half of the ResourceLocation is appropriately set. 

I don't think the system should be overhauled in 1.10.2, however this seems like a great candidate for the 1.11 update.

**Comment by Madsthunder** [comment]
Agreed. Entities should probably use the new IForgeRegistry system too, but that would mean that forge would need to adapt a warning system similar to the one in 1.7.10 that warned users about blocks that would be incompatible with 1.8 and above. It's definitely not a needed addition but it would be nice to have.

**Comment by Darkhax** [comment]
Entities would also be a nice addition. I don't think the warning should be that big of a deal, we already have several for things like bad mod IDs in the current version.

**Comment by mezz** [comment]
I agree, it would be nice to have a proper registry for Fluids.

As a workaround for now, you can get the fluid modId like this:

``` java
String defaultFluidName = FluidRegistry.getDefaultFluidName(fluidStack.getFluid());
ResourceLocation fluidResourceLocation = new ResourceLocation(defaultFluidName);
return fluidResourceLocation.getResourceDomain();
```

`FluidRegistry.registerFluid(Fluid)` tacks on the modId of the active mod container in `uniqueName(Fluid)`.

**Comment by Darkhax** [comment]
Ah, thanks for the info mezz. That solves the initial issue I was having.

**Comment by Madsthunder** [comment]
Would this be a viable breaking change for 1.12?

**Comment by mezz** [comment]
Yes, this needs a PR and review. It would be good to start it sooner rather than later, even though it would have to wait for 1.12.

**Comment by liach** [comment]
Noop, we have #4098 going on
