### ISSUE TITLE
[oops]

### ISSUE THREAD

**Issue by CrowsOfWar** [MinecraftForge/MinecraftForge#3282]
**EDIT** I'm stupid... I must have done something wrong. It began working just a moment ago...

Hello, I believe that I have found a minor bug in the code.

I subscribed to the RenderGameOverlayEvent$Post event, but it never was called:

``` java
@SubscribeEvent
public void onGuiRender(RenderGameOverlayEvent.Post e) {
    // not called...
}
```

I checked the call hierarchy on its constructor, and it looks like this isn't being instantiated _anywhere_... if someone could check this for me, I'd be grateful.

**Comment by shadowfacts** [comment]
1. Wrong place for [modder support](http://www.minecraftforge.net/forum/index.php?board=73)
2. Did you register your event handler class with `MinecraftForge.EVENT_BUS`?

**Comment by Madsthunder** [comment]
Close please?
