### ISSUE TITLE
Allow rewriting the client entityId for bungeecord servers.

### ISSUE THREAD

**Issue by thomas15v** [MinecraftForge/MinecraftForge#3284]
The bungeecord proxy rewrites the EntityID for all known Packets. However on server switch the EntityId on the Server changes compared to the client. What means that clients will send the wrong EntityId.

Bungeecord itself can not do anything since it cannot counteract every mod sending packets. The most simple solution would be that bungee could sends forge the new entity id on server switch. This way clients stay in sync and mod creators don't have to worry about it.

**Comment by Madsthunder** [comment]
Isn't this a BungeeCord issue?

**Comment by thomas15v** [comment]
No, bungeecord can not rewrite FMLProxy packets. It just sends it trough. Also every mod has it's own kind of packet style, and it's impossible to anticipate on that.

**Comment by LexManos** [comment]
The servers can send entity respawn packets to define the new player entity and they entity id. 
We shouldnt need to do anything special to support this.
Mods will be using whatever entity id its told to in the player entity so there should be no issue,.
Come back with full actual issue cases and explinations then we might care, but for now this sounds more like a theoretical issue.

**Comment by thomas15v** [comment]
Oh wow. I am sorry @LexManos I didn't thought I was allowed to send [JoinGame](http://wiki.vg/Protocol#Join_Game) when the client game was already started.  however after trying it it worked just fine. Thanks :+1:.
