### ISSUE TITLE
[1.10.2] Outdated doc comment on FMLPreInitializationEvent#getModLog

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#3287]
The doc comment on `FMLPreInitializationEvent#getModLog` says that logging can be configured through the **config/logging.properties** file, but this is no longer the case since Minecraft switched to log4j logging.

**Comment by cpw** [comment]
Yup, very true.

**Comment by Choonster** [comment]
Fixed by #4664.

**Comment by mezz** [comment]
Making a note here: to configure logging with log4j, you can set the system property `log4j.configurationFile` to point to your custom config file. 
Forge's log4j config file (as of this comment) is here: [MinecraftForge/src/main/resources/log4j2.xml](https://github.com/MinecraftForge/MinecraftForge/blob/b6f8be6718c6a3bcba96983f37d25a463784d424/src/main/resources/log4j2.xml)
You can find (way too much) information about configuring log4j here: https://logging.apache.org/log4j/2.x/manual/configuration.html
