### ISSUE TITLE
[1.10.2] Blockstate transfer issue in multiplayer.

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3290]
This porblem is realated with this: https://github.com/mcenderdragon/Futurepack-API/issues/11.

Some blockstate flags get not correctly transmitted. On server side the Blockstate are right, but on the client side they are not.
In forge version 2014 this worked. In forge version 2094 this works no longer. I dont know at wich version this break is exactly.

This is somehow realated how the blockstate is conterted to a metadata and wich propertys are set though "getActualState()"

**Comment by williewillus** [comment]
1. Are you setting default state _before_ registering your block?
2. Are your state-meta methods one to one?
3. If you use extended states do not set values for their properties in the default state

In between, forge fixed a vanilla bug that reveals a hidden issue in mods that don't set up their states right. So recheck those steps above

**Comment by mcenderdragon** [comment]
As it all works in the other versions and in single player+ multiply world saves+reloads yes, they work. And no I dont use the extended state. Should I provide the block code I use?

**Comment by williewillus** [comment]
Forge fixed a bug, that was hiding bugs in mods. So the issue is in your mod. Hop on irc and maybe we can take a look but it's not a forge issue

**Comment by LexManos** [comment]
It's your to/from meta code. This is not a forge bug it is a bug is your code. Make sure your meta-> state is correct for what you want

**Comment by mcenderdragon** [comment]
Ok thanks. Sorry for blaming Forge.
