### ISSUE TITLE
[Event] The old client world unloads after the client world loaded when changing dimensions

### ISSUE THREAD

**Issue by liach** [MinecraftForge/MinecraftForge#3291]
This behavior hurts mods which always expect that there will only be one client world. I made a mod that feeds on `WorldEvent.Load` and `WorldEvent.Unload` , and I found that when the player changes dimension, `WorldEvent.Load` is fired before `WorldEvent.Unload`. I expect `WorldEvent.Unload` to come before `WorldEvent.Load`.

**Comment by LexManos** [comment]
Except that's not how the game engine works.
That would leave the engine in a state of having no world for a moment which will cause even more issues. I am not sure what you are doing, but i'm sure you can do it in a safe way to keep track of these multiple client worlds.
