### ISSUE TITLE
[1.10.2] Massive ram usage when turning or chunks loading

### ISSUE THREAD

**Issue by Tencao** [MinecraftForge/MinecraftForge#3297]
Ok so I've been trying to debug whats causing a massive amount of ram usage spikes on my modpack by removing all mods and slowly adding them back one by one, however I noticed even in basic forge with no mods, this issue persists. It's most notable when chunks are first loaded and when the player turns, presumably due to chunks reloading. I've attempted to turn all settings to low to see if a specific issue causes it, however the issue persists regardless. 

This was on a single player world with no mods, Forge version - 1.10.2-12.18.1.2095

**Comment by mezz** [comment]
Can you compare between vanilla and Forge?

**Comment by Tencao** [comment]
Ok so I tested the same world on both forge and vanilla, and on vanilla there is a little spike in ram when loading new chunks however this goes away in a few seconds after the chunks load and the ram usage is very slow to go up, so it does seem to be a forge issue, or at the very least, significantly worse on forge.

For more additional information, I spawned on a small sand island surrounded by water with a sand village not too far away. For a visual view, http://image.prntscr.com/image/e49d4f249bd34fbd92f54a050ea6ace3.png

**Comment by Tencao** [comment]
Ok I've noticed something extremely weird when looking back at the logs. 

http://pastebin.com/jinfkmMk
[02:48:54] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save New World

This seems to be spamming excessively, and also on vanilla when loading the forge world (No mods), it did output these errors

> [10:45:01] [Server thread/ERROR]: "Silently" catching entity tracking error.
> f: Adding entity to track
>     at lp.a(SourceFile:172) [1.10.2.jar:?]
>     at lp.a(SourceFile:111) [1.10.2.jar:?]
>     at lt.a(SourceFile:37) [1.10.2.jar:?]
>     at aid.b(SourceFile:898) [1.10.2.jar:?]
>     at ls.b(SourceFile:974) [1.10.2.jar:?]
>     at aid.a(SourceFile:890) [1.10.2.jar:?]
>     at ls.a(SourceFile:933) [1.10.2.jar:?]
>     at aik.a(SourceFile:151) [1.10.2.jar:?]
>     at ls.d(SourceFile:199) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.D(SourceFile:618) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.C(SourceFile:554) [1.10.2.jar:?]
>     at bzl.C(SourceFile:155) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.run(SourceFile:458) [1.10.2.jar:?]
>     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
> Caused by: java.lang.IllegalStateException: Entity is already tracked!
>     at lp.a(SourceFile:146) ~[1.10.2.jar:?]
>     ... 13 more
> [11:01:07] [Server thread/ERROR]: "Silently" catching entity tracking error.
> f: Adding entity to track
>     at lp.a(SourceFile:172) [1.10.2.jar:?]
>     at lp.a(SourceFile:111) [1.10.2.jar:?]
>     at lt.a(SourceFile:37) [1.10.2.jar:?]
>     at aid.b(SourceFile:898) [1.10.2.jar:?]
>     at ls.b(SourceFile:974) [1.10.2.jar:?]
>     at aid.a(SourceFile:890) [1.10.2.jar:?]
>     at ls.a(SourceFile:933) [1.10.2.jar:?]
>     at aik.a(SourceFile:151) [1.10.2.jar:?]
>     at ls.d(SourceFile:199) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.D(SourceFile:618) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.C(SourceFile:554) [1.10.2.jar:?]
>     at bzl.C(SourceFile:155) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.run(SourceFile:458) [1.10.2.jar:?]
>     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
> Caused by: java.lang.IllegalStateException: Entity is already tracked!
>     at lp.a(SourceFile:146) ~[1.10.2.jar:?]
>     ... 13 more
> [11:09:18] [Server thread/ERROR]: "Silently" catching entity tracking error.
> f: Adding entity to track
>     at lp.a(SourceFile:172) [1.10.2.jar:?]
>     at lp.a(SourceFile:111) [1.10.2.jar:?]
>     at lt.a(SourceFile:37) [1.10.2.jar:?]
>     at aid.b(SourceFile:898) [1.10.2.jar:?]
>     at ls.b(SourceFile:974) [1.10.2.jar:?]
>     at aid.a(SourceFile:890) [1.10.2.jar:?]
>     at ls.a(SourceFile:933) [1.10.2.jar:?]
>     at aik.a(SourceFile:151) [1.10.2.jar:?]
>     at ls.d(SourceFile:199) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.D(SourceFile:618) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.C(SourceFile:554) [1.10.2.jar:?]
>     at bzl.C(SourceFile:155) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.run(SourceFile:458) [1.10.2.jar:?]
>     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
> Caused by: java.lang.IllegalStateException: Entity is already tracked!
>     at lp.a(SourceFile:146) ~[1.10.2.jar:?]
>     ... 13 more
> [11:24:47] [Server thread/ERROR]: "Silently" catching entity tracking error.
> f: Adding entity to track
>     at lp.a(SourceFile:172) [1.10.2.jar:?]
>     at lp.a(SourceFile:111) [1.10.2.jar:?]
>     at lt.a(SourceFile:37) [1.10.2.jar:?]
>     at aid.b(SourceFile:898) [1.10.2.jar:?]
>     at ls.b(SourceFile:974) [1.10.2.jar:?]
>     at aid.a(SourceFile:890) [1.10.2.jar:?]
>     at ls.a(SourceFile:933) [1.10.2.jar:?]
>     at aik.a(SourceFile:151) [1.10.2.jar:?]
>     at ls.d(SourceFile:199) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.D(SourceFile:618) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.C(SourceFile:554) [1.10.2.jar:?]
>     at bzl.C(SourceFile:155) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.run(SourceFile:458) [1.10.2.jar:?]
>     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
> Caused by: java.lang.IllegalStateException: Entity is already tracked!
>     at lp.a(SourceFile:146) ~[1.10.2.jar:?]
>     ... 13 more
> [11:25:09] [Server thread/ERROR]: "Silently" catching entity tracking error.
> f: Adding entity to track
>     at lp.a(SourceFile:172) [1.10.2.jar:?]
>     at lp.a(SourceFile:111) [1.10.2.jar:?]
>     at lt.a(SourceFile:37) [1.10.2.jar:?]
>     at aid.b(SourceFile:898) [1.10.2.jar:?]
>     at ls.b(SourceFile:974) [1.10.2.jar:?]
>     at aid.a(SourceFile:890) [1.10.2.jar:?]
>     at ls.a(SourceFile:933) [1.10.2.jar:?]
>     at aik.a(SourceFile:151) [1.10.2.jar:?]
>     at ls.d(SourceFile:199) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.D(SourceFile:618) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.C(SourceFile:554) [1.10.2.jar:?]
>     at bzl.C(SourceFile:155) [1.10.2.jar:?]
>     at net.minecraft.server.MinecraftServer.run(SourceFile:458) [1.10.2.jar:?]
>     at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
> Caused by: java.lang.IllegalStateException: Entity is already tracked!
>     at lp.a(SourceFile:146) ~[1.10.2.jar:?]
>     ... 13 more

These may be completely unrelated to the issue, but hopefully it may help point to any potential issues

**Comment by SDUBZ** [comment]
ive  been noticing spikes when something world gens both in ram and cpu 
sometimes cpu hitting upto 80% and ram getting to 8gbs at times, but note i have like 183 mods installed.

must do testing with all world gen mods not installed
