### ISSUE TITLE
ClassTransformers applied out of order(?)

### ISSUE THREAD

**Issue by kutschkem** [MinecraftForge/MinecraftForge#3298]
1.7.10, see https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/995
It appears that the DragonAPI class transformers and ThaumicInfusion class transformers are not, like I would expect, executed in the order of the mods loading, but TI transformers, according to the log, get applied in between the DragonAPI transformers.

I can reproduce as follows:

Pack with DragonAPI v16a, ThaumicInfusion 4.32, Thaumcraft 4.2.3.5
crashes (see other issue)

The problem here, imho, is that the TI transformer is applied before some of the DragonAPI transformers (namely the one that adds a FIRESPREADEVENT), where my expectation would be that all DragonAPI transformers are applied, then the TI transformers.

**Comment by 0xilly** [comment]
How is this a forge bug? Also 1.7.10 is not supported.

**Comment by kutschkem** [comment]
If it's not, ignore me, but isn't Forge the one who applies the ClassTransformers? I honestly don't know how that works, but from reading other mod's code I was assuming that they return a list of class transformers to apply, which Forge then applies(?)

**Comment by covers1624** [comment]
This is an issue with those mods being broken. NOT forge. Don't blame forge for mods having broken ClassTransformers. No, forge has nothing to do with it. MC has a lib called LaunchWrapper, as classes are loaded it calls registered IClassTransformers to edit the bytes of the classes being loaded. It is the mod that registers the IClassTransformer, FML just wraps it in a nice friendly way.

**Comment by kutschkem** [comment]
Ok I think I see. In what order are the ClassTransformers registered?

**Comment by covers1624** [comment]
FML has a sorting index annotation mods can use on their coremod to determine when they are called. like i said, it is completely out of Forge/fml's control on when they are called. This is NOT a forge issue. Plus this is 1.7.10 and it is no longer maintained by forge at this point. forge focuses on 1.10.X at the moment. This issue should be closed.

**Comment by diesieben07** [comment]
This is why only people who know what they are doing should write coremods...

**Comment by LexManos** [comment]
1) 1.7.10 is not supported
2) Reika's distribution system for his 'API' breaks quite a lot of things Forge/Mojang does with the transformers.
3) As stated we have a sorting annotation so this is a non-issue.
