### ISSUE TITLE
[1.10.2] ConcurrentModificationException on server - no other mods installed

### ISSUE THREAD

**Issue by Kuboczoch** [MinecraftForge/MinecraftForge#3299]
This is my crash report: http://hastebin.com/ozonibinak.pl
This can be easily triggered by issuing save-off, save-all via rcon

**Comment by marcin212** [comment]
Same problem without rcon
http://hastebin.com/ezalopoyeq.scala

**Comment by Aaron1011** [comment]
@Kuboczoch: This is a fundamental issue with RCon, not a Forge bug - it executes all of commands on another thread. A better solution is to simply avoid using RCon - it's completely unencrypted, so the password it uses is visible to anyone watching the network.

@marcin212: That appears to be a completely different issue, as you're using 71 mods.

**Comment by Kuboczoch** [comment]
I use RCon on localhost... @Aaron1011

**Comment by magik6k** [comment]
I fixed it with simple transformer, https://git.starchasers.ovh/magik6k/CMEFix/src/master/src/main/java/pl/starchasers/cmefix/Transformer.java, running fine since 2 days, with hourly rcon connection to prepare server for backup(save-off/all/on)

**Comment by Pokechu22** [comment]
It's a vanilla issue, see [MC-72390](https://bugs.mojang.com/browse/MC-72390).  Forge isn't really in the position to fix it (it could, but really it should be fixed on mojang's end).

**Comment by Heufneutje** [comment]
Forge fixes a few vanilla bugs. Usually they are submitted with the Mojang bug tracker number in a comment in the patch so it can easily be removed once Mojang fixes it.

**Comment by JustGregory-zz** [comment]
That really begs the question, does Mojang care what Forge "fixes" or not? If so, why wouldn't they adopt Forge's fixes even more quickly?

**Comment by Pokechu22** [comment]
Mojang does apply fixes from the community if they're on their bug tracker (at least, occasionally; for bigger fixes or "hacky" fixes they tend to use it as advice rather than a direct patch).  I've contributed several bug fixes that way.

There is one other thing to consider (and I'm not completely in the know about it): [Forge is LGPL](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/LICENSE-new.txt), which makes it legally complicated for Mojang to use Forge patches.  Just something to consider...

**Comment by Pokechu22** [comment]
The issue is still present and the MC ticket has been updated.

**Comment by mezz** [comment]
I'm not sure if it is useful to keep Forge issues open for vanilla bugs unless there is active discussion.
I think it is probably good to keep discussion centralized on the Mojang tracker unless a PR is open for Forge. What do you think?

**Comment by Pokechu22** [comment]
Yeah, it'd be fine to close this and just keep the discussion on the tracker, just wanted to make it clear that the issue is still present.

**Comment by mezz** [comment]
Thanks! I will close this now. 
For anyone reading, you should still feel free to open PRs to fix vanilla bugs if the fix is not too large.
