### ISSUE TITLE
[1.10.2] Registry issue with downgraded/missing blocks

### ISSUE THREAD

**Issue by LemADEC** [MinecraftForge/MinecraftForge#3301]
As reported initially on Chisel mod, it appears downgraded/missing blocks aren't handled properly in the registry: https://github.com/Chisel-Team/Chisel/issues/246

**Comment by LexManos** [comment]
As stated to @tterrag1098 on irc, if this is a bug on our end he will need to come to use with a proper bug report and reproduction case.

**Comment by tterrag1098** [comment]
@LexManos this is something different. With `@ObjectHolder`, when you downgrade it tries to place the "dummy air" block into the holder reference, which causes a cast exception if you use a subclass of Block, and spams the log.

**Comment by LexManos** [comment]
Please report it properly so I know what you're talking about. 
I can look into what I _think_ you're saying and see if I can find anything.

**Comment by LexManos** [comment]
The fix is in but there isnt a build yet as @cpw is working on another fix for other parts of the registry issue.
