### ISSUE TITLE
hacking  minecarft

### ISSUE THREAD

**Issue by pierre123412345** [MinecraftForge/MinecraftForge#3302]

**Comment by pierre123412345** [comment]
How can you hack minecraft? you can hack minecraft on computer first you go on minecraft then you go on minecraft and click F12 write any update you want lets say i pick 1.10 i can change it during the time i am playing.

**Comment by liach** [comment]
Such a noob is really rare.

**Comment by Madsthunder** [comment]
First, there is this magical thing in Eclipse called "Debug Mode".
Second, there is also this magical land called Google where you can search how to hack Minecraft (If that's what you were actually implying).
Third, if you consider hacking editing the Minecraft code, then you should use ASM transformers, but ASM can be pretty dangerous, especially if you have absolutely no idea what you're doing.
Finally, if it isn't an issue in the MCForge code, take it to the forums [http://www.minecraftforge.net/forum/index.php?board=73.0].
