### ISSUE TITLE
Netty error when assertions are enabled

### ISSUE THREAD

**Issue by AlexiyOrlov** [MinecraftForge/MinecraftForge#3309]
I used to program with assertions enabled. Now, if I open a Gui which has an associated container, this Netty error happens:
[Error](http://pastebin.com/vPUxWWTm)

Is it vanilla bug? Happens only when assertions are enabled.

**Comment by LexManos** [comment]
Known netty  bug we've tried to work around but failed to. It used to haunt the non-assert world until they changed it to an assert.
