### ISSUE TITLE
getStateFromMeta  says deprecated in Block but is actually required to a variant/multi state block

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3311]
I'm not sure what's going on but getStateFromMeta is necessary for the game to remember FACING or other blockstate property between game sessions. Without it the blocks reset to NORTH facing or whatever the default state is.

But in Bock says is Deprecated but is not deprecated. Is obviously needed to make a block with different states.

What gives?

mind you I am using the newest halfstar 1.10 forge MDK 12.18.2.2105

Tells me is deprecated
![screen shot 2016-10-14 at 2 12 10 pm](https://cloud.githubusercontent.com/assets/6987027/19397965/3e3efbcc-9218-11e6-8683-d82f2f15ca43.png)

But without it my steamBoiler resets FACING every time I restart or reload the game
![screen shot 2016-10-14 at 2 13 00 pm](https://cloud.githubusercontent.com/assets/6987027/19398008/6c1e4822-9218-11e6-8f00-d2d46911dfdd.png)

**Comment by TehNut** [comment]
Ignore it. This should have been a question on the forums or IRC.

**Comment by ghost** [comment]
Could you direct me to the forums I will close it and ask the question there. Or is there a Discord or IRC channel you guys use?

**Comment by kashike** [comment]
http://minecraftforge.net/forum/

**Comment by LexManos** [comment]
It is deprecated, as in you should not CALL it.
As Mojang is still working on the internals to move away from this and other functions in Block in favor of BlockState they have marked a lot of Functions @Deprecated in a 'Do not call this but if you MUST override it, then do so' 
Minecraft has been, is, and always will be a work in progress. Its just one of the quirks.

**Comment by ghost** [comment]
@LexManos  Gotcha thanks. I was suggested to simply ask on the forums rather than report issues here. I was gonna close this anway way. Made a post on the forum but I guess I got my answer already. Thanks 👍
