### ISSUE TITLE
[New Event Idea] ItemGetMaxDamageEvent

### ISSUE THREAD

**Issue by Zetal911** [MinecraftForge/MinecraftForge#3312]
When you want to customize ItemStack damage via NBT values, right now you have to also create your own Item class- so if you want to rehash how Vanilla tools/armor work, you need to replace all of them manually. It's a huge hassle!

So instead, an event call would simplify things greatly; in Item.getMaxDamage(ItemStack stack):

```
public int getMaxDamage(ItemStack stack)
{
    return getMaxDamage();
}
```

Replace this with, instead:

```
public int getMaxDamage(ItemStack stack)
{
    // If the event returns -1, use the vanilla method. Otherwise, it's been modified!
    ItemGetMaxDamageEvent event = new ItemGetMaxDamageEvent(stack);
    MinecraftForge.EVENT_BUS.post(event);
    int damage = event.getMaxDamage();
    if(damage != -1)
    {
        return damage;
    }
    return getMaxDamage();
}
```

Or something to that effect, anyways. This would also improve compatibility between mods that modify vanilla weapons/tools/armor, since it's one less thing they might need to modify directly.

Thanks!

**Comment by liach** [comment]
Use case please. Events are slower than simple overrides.

**Comment by Zetal911** [comment]
Use case is already addressed in my original post. Determining maximum damage from itemstack NBT makes a mod 'feature' incompatible with any other mod that adds any items of their own, and would make a mod 'functionally' incompatible with any other mod that modifies vanilla items.

I can't imagine this hypothetical event would slow things down much at all, but I could be wrong. The main point stands- there is a lack of compatibility options for mods that change maxDamage for an ItemStack.

**Comment by LexManos** [comment]
No, this is to low level for an event. You're asking to edit fundamental data values for arbitrary objects.
If you want to claim control over another's objects then you sub it with your own.
If you have a mod pack that overhauls how vanilla items work that in incompatible with another mod, then sorry you have to choose one or the other. This isn't a compatibility thing this is a logic thing.
