### ISSUE TITLE
Friends GUI not working properly gives me this error (hermitcraft 1.10.2 server first release)

### ISSUE THREAD

**Issue by xcnxclutch** [MinecraftForge/MinecraftForge#3315]
this is the error report it told me to send over (I had to put copy it from my server computer which is why it is in docs... its a text document on the server)
![hermitcraft error](https://cloud.githubusercontent.com/assets/15936686/19458612/229d864c-949b-11e6-913c-49ed827c5553.JPG)

[error report copied over.docx](https://github.com/MinecraftForge/MinecraftForge/files/534846/error.report.copied.over.docx)

**Comment by kashike** [comment]
You've created this issue in the wrong repository - please re-open this issue on the [OpenComputers repository](https://github.com/MightyPirates/OpenComputers/issues).
