### ISSUE TITLE
Tile Entities persist one tick after being removed from the world 

### ISSUE THREAD

**Issue by Vazkii** [MinecraftForge/MinecraftForge#3319]
https://github.com/Vazkii/Botania/issues/1955

**Comment by LexManos** [comment]
Reporting something with just a link to another repo showing a stacktrace from a sponge server is not the proper way to report anything.
Forge gates ticking tile entites behind the normal valid check which is toggeled when the block is removed, or should be unless you messup that code in your block.
If this IS a Forge issue report it correctly. You know better then this.

**Comment by Vazkii** [comment]
I completely missed the fact it was sponge. Sorry for that.
