### ISSUE TITLE
No smooth lighting on TESR bug?

### ISSUE THREAD

**Issue by LapisSea** [MinecraftForge/MinecraftForge#3322]
So I was working on some special block rendering and I really quickly noticed that the "old" way of accomplishing smooth lighting does not work anymore. 
http://prnt.sc/cx8lc4
So I looked for some vanilla examples and on my complete surprise I found out that vanilla blocks have the same problem!
http://prnt.sc/cx8nks
http://prnt.sc/cx8ny2
Notice how the existing chest block becomes darker because it is rendered by the other chest block that is less bright.

**Comment by williewillus** [comment]
does it happen in vanilla?

**Comment by LapisSea** [comment]
Yeah. See the last 2 images.

**Comment by RainWarrior** [comment]
Vanilla never had smooth lighting for TESRs, as far as I know. You can reuse the block lighting, if your TESRs use models. No idea what you mean by the "old" way.

**Comment by LapisSea** [comment]
Well sorry, for not clearing it up. Before you used to be able to just enable smooth blending model and the shades would be auto handled. Now it seems as thou that that is not the case anymore.
