### ISSUE TITLE
Brewing RecipeRegistry: cannot add recipes using existing potion ingredients (redstone) as ingredients.

### ISSUE THREAD

**Issue by Lothrazar** [MinecraftForge/MinecraftForge#3323]
Using forge 12.18.2.2099

Following the example and the sample code in https://github.com/MinecraftForge/MinecraftForge/blob/f08f3c11053d414b57d03192dd72fcbfaef100f7/src/test/java/net/minecraftforge/test/BrewingRecipeRegistryTest.java

If i add the recipe like this and run the unit test

`BrewingRecipeRegistry.addRecipe(new ItemStack(Items.DIAMOND_SWORD), new ItemStack(Items.REDSTONE), new ItemStack(Items.DIAMOND_HOE));

```
  ItemStack output0 = BrewingRecipeRegistry.getOutput(new ItemStack(Items.DIAMOND_SWORD), new ItemStack(Items.REDSTONE));

  if(output0.getItem() == Items.DIAMOND_HOE)
    System.out.println("Recipe succefully registered and working");

  else
    System.out.println("Recipe FAILED : output0 =  "+output0.getUnlocalizedName());`
```

Then my console output shows: 

"Recipe FAILED : output0 =  item.swordDiamond"

NOTE: This bug only happens with items used by vanilla brewing such as redstone or glowstone dust.  If I use ROTTEN_FLESH as in the example it works.

**Comment by williewillus** [comment]
If your recipe is simple enough you can use the vanilla system to add your recipe (but this is still a bug)

**Comment by Lothrazar** [comment]
Thanks for replying.

Ill look into what the vanilla system is for adding potion recipes, ive only ever used brewing registry and i assumed it was the only way.

**Comment by williewillus** [comment]
look at the PotionHelper class to see how vanilla does it

**Comment by joeflatt** [comment]
@PrinceOfAmber 's test case using Items.REDSTONE seems to be working now.  Running it I get back Items.DIAMOND_HOE.
