### ISSUE TITLE
Dormant chunk cache causing TE data(?) to get lost

### ISSUE THREAD

**Issue by SharkWipf** [MinecraftForge/MinecraftForge#3325]
Tested on Forge Build 2107, Java version "1.8.0_102".
Mod list: [pastebin](http://pastebin.com/aiuxKuij)
Log: N/A

When setting the `I:dormantChunkCacheSize` option in `forgeChunkLoading.cfg` to something non-zero (tested with 1024), tile entities will lose data on chunk unloads and/or server restarts.
At least, that's what I assume happens, my knowledge of MC internals is limited.

Some results of this I noticed, when chunks unload: 
- Botania Mana pools lose their mana
- Botania mana spreaders lose their target
- Wooden pressure plates get stuck in "down" state when an item was on them before
- I think this caused my progressive automation chopper to stop seeing trees as well some times, not 100% sure as it seemed to recover by itself eventually.

The mana pools and spreaders are the easiest way to test for this issue I've found, as they are easiest to set up and make it very clear when their data is lost.

If you need any more data to reproduce this please let me know.

EDIT: Naturally, all of the above works perfectly fine with `I:dormantChunkCacheSize` set to 0, no other changes made

**Comment by Daomephsta** [comment]
I'd try to cull that modlist down to the necessary mods to reproduce this. You haven't eliminated other mods as the cause of the issue.

**Comment by SharkWipf** [comment]
I'll see if I can reproduce it tomorrow with just Forge and Botania (for ease of testing). 
Theoretically, if it would be caused by a mod, can it only be caused by a coremod or could any mod mess with core Forge functionality like this?

**Comment by LexManos** [comment]
See if this is reproducible with vanilla tile entities as they go through the same exact process as modded ones when it comes to this.
If you can't then it's not a Forge/vanilla issue.
Don't have the code in front of me but all the dormant chunk cache does is hold the objects in memory for a short time. TEs are still removed/added to the world on load/unload. Even if going to the cache itself so there should be no reason this data is lost.

**Comment by SharkWipf** [comment]
Sadly I unexpectedly have a lot less free time atm, and won't be able to test this for a while.  
I don't know when I'll be able to test this again, judging by above reference I'm not the only one with this issue so I won't close it yet, but feel free to close it to clean things up. Once I have time to properly test this I'll just reopen it again if necessary.

**Comment by bs2609** [comment]
Following #3940 and #4162, this shouldn't be an issue.

**Comment by liach** [comment]
We will see if there is any report.

**Comment by mezz** [comment]
I will close this for now. Please reply if you see this issue again.

**Comment by Tencao** [comment]
Would like to say I'm still getting this issue on 1.12.2, forge 14.23.0.2529+. Everything from vanilla chests and furnaces to modded tile entities kept getting reset, the moment I set the chunk cache to 0, the issue went away.

**Comment by mezz** [comment]
This should be fixed by https://github.com/MinecraftForge/MinecraftForge/pull/4528.
