### ISSUE TITLE
Water breaks snow layers as snowball items

### ISSUE THREAD

**Issue by quat1024** [MinecraftForge/MinecraftForge#3326]
If you create a snow layer and pour water over it, you get snowball items. In vanilla, the snow layer just disappears.

![](http://i.imgur.com/z18E0bS.png)

**Comment by LatvianModder** [comment]
But.. It's a feature!

**Comment by quat1024** [comment]
Fair enough ;) I'm not going to [pretend I don't like it](http://i.imgur.com/faBMXcl.png), but it's still a difference from vanilla behavior.

It doesn't make much sense, considering that you need a shovel to get snowball items, and punching them with a fist, pushing them with a piston, or pulling the block underneath them with a piston doesn't drop an item either.

**Comment by LexManos** [comment]
Interesting, I wonder what broke it this time. We've been having a cat and mouse with this for a while.
Guess i'll do the nasty and special case this out of water being able to drop. I really hate this special case in Vanilla.
