### ISSUE TITLE
Forge's Stitcher "bugfix" causes the allocation limits to be exceeded

### ISSUE THREAD

**Issue by Player3324** [MinecraftForge/MinecraftForge#3330]
If my analysis is correct the fix in commit 1eee6cd38282a80958444ee5979eb9cbe55ff509 introduces a regression, leading to the atlas to grow wide again after it hit the width limit instead of growing down. This effectively halves the users' usable atlas texture area/space.

Scenario:
width = n, height = n/2, maxWidth = maxHeight = n
flag1=false, flag2=true
flag3=false, flag4=true
flag=true (with the Forge patch)
-> The atlas grows to the right and is then wider than maxWidth (new aspect ratio 4:1)
-> The texture allocation is likely to fail later on since the size limits are derived from previous limit testing

Something like the following should actually fix the problem, needs testing though:

``` java
[...]
boolean canAllocRight = reqWidth <= this.maxWidth;
boolean canAllocDown = reqHeight <= this.maxHeight;

if (!canAllocRight && !canAllocDown) {
    return false;
} else {
    boolean allocRight;

    if (canAllocRight != canAllocDown) { // only one direction is suitable
        allocRight = canAllocRight;
    } else { // both canAllocRight and canAllocDown are true
        boolean needToExpandIfRight = width != reqWidth;
        boolean needToExpandIfDown = height != reqHeight;

        if (needToExpandIfRight != needToExpandIfDown) {
            allocRight = !needToExpandIfRight;
        } else { // both sides would need to expand
            allocRight = width <= height;
        }
    }

    Stitcher.Slot stitcher$slot;
[...]
```

Better research before applying arbitrary fixes would be appreciated.

**Comment by LexManos** [comment]
Unable to verify issue due to lack of information. So added a safeguard https://github.com/MinecraftForge/MinecraftForge/commit/858056c08999dd86685bf9f32846c380c4c86e03
