### ISSUE TITLE
LootingLevelEvent does not apply to loot tables. 

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#3337]
Since the addition of LootingLevelEvent, the ways in which the looting modifier is calculated have changed. The first case that is not accounted for is the loot function `LootingEnchantBonus` and the second is the LootCondition `RandomChanceWithLooting`.

**Comment by williewillus** [comment]
still valid

**Comment by mezz** [comment]
I trust that @williewillus looked into this.
I don't believe he would bump these for no reason and you really shouldn't delete comments, it makes drama.
Willie, please try to be a little more descriptive. Just say if you looked at the code or how you believe it's still valid.

**Comment by Darkhax** [comment]
I have checked the code and this is still relevant because the event does not fire for loot tables. With the game moving towards loot tables for more and more things, this has severely impacted the usefulness of this event.

**Comment by LexManos** [comment]
Then submit a PR with how you think it should work.
Because as it is it looks perfectly fine to me. And your current description is not useful enough to get anything done.
