### ISSUE TITLE
[Request] Make FMLModContainer look for all methods instead of only declared methods

### ISSUE THREAD

**Issue by InfinityRaider** [MinecraftForge/MinecraftForge#3341]
Is it possible to have this:
https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/common/FMLModContainer.java#L377

to be changed from getDeclaredMethods() to getMethods()?
This is so I do not have to explicitly declare a method for every FMLEvent just to call super:
https://github.com/InfinityRaider/AgriCraft/blob/c026bbd215d93659e144bfe58e241ebeef44bfb3/src/main/java/com/infinityraider/agricraft/AgriCraft.java#L105-L122

superclass:
https://github.com/InfinityRaider/InfinityLib/blob/878f286a882bc327603499df01ad479fb3576b19/src/main/java/com/infinityraider/infinitylib/InfinityMod.java#L71-L119

P.S. I'd make a PR for something as trivial as this, if only I knew how to set up a MinecraftForge dev env.

**Comment by diesieben07** [comment]
If the original methods are annotated, FML will find them. In fact, `getDeclaredMethods` will only find methods in the current class, not inherited methods. `getMethod` specifically includes the inherted methods (as opposed to `getDeclaredMethods`).
If you don't annotate a method, how did you expect FML to find it?

**Comment by InfinityRaider** [comment]
They are not annotated in the parent class because its no use to do so at the moment.

If I annotate the methods in the parent class and not declare them in the extending class, none of the methods get called. Which is to be expeced as FML only scans the declared methods. Because of this, in each of my mods I have to declare a set of methods which just call super.
With this change I can simply annotate them in my base class and never worry about them anymore.

**Comment by InfinityRaider** [comment]
I guess the issue with this is that if a method is overridden and annotated as well, it will be called twice in this case.

**Comment by diesieben07** [comment]
I misread your initial post, i thought you wanted getMethods => getDeclaredMethods. Nevermind me then.

> I guess the issue with this is that if a method is overridden and annotated as well, it will be called twice in this case.

No that I know of.

**Comment by InfinityRaider** [comment]
Hmm yes you're right, somehow I thought FML would scan the parent class and the extending class seperatly, and in this case the method would be added twice. But there is no reason that this would happen.

**Comment by Deamon5550** [comment]
Using `getMethods` would exclude event listeners declared as private [which are currently allowed](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/common/FMLModContainer.java#L385). So if you want event listeners in super classes you're going to need to walk up the superclass hierarchy and check each level.

**Comment by Jezza** [comment]
I'd agree with @Deamon5550 in that `getMethods` wouldn't be an ideal solution.
We'd lose the ability to use private methods as event listeners.

There are two solutions I can think of.
1. Introduce an annotation that says "Check my superclass as well", which might not be ideal, as it might pass through undiscovered for a while.
2. The second one, is as @Deamon5550 also said, always walk the hierarchy, which definitely isn't ideal.

Personally, I don't think you should be declaring EventHandlers in super classes if they don't explicitly need them.
Failing that, you can always attempt to register the object directly onto Forge's EventBus, but at that point, you're on your own, as the error handling is going to be different...

**Comment by heldplayer** [comment]
The gathering of annotations only happens once, so it shouldn't cause any extra overhead to traverse the class hierarchy rather than looking only at the current class only.

What I do remember is at least one other issue or PR addressing this in the past and it not getting fixed/accepted. Not sure where to find it though.

**Comment by Jezza** [comment]
By the looks of it, this is called to get some of the basic annotations, such as the aforementioned `@Mod.EventHandler`, but also the instance factory, so there's a couple of things to consider. 

The `ASMDataTable` isn't used to grab the `@Mod.EventHandler` annotations, so we might be able to make use of that.
If we decide forgo the use of `ASMDataTable` in favour of just looping through annotations, we also need to ask if we should allow other annotations from the superclass, such as `@Mod.InstanceFactory`, which is also discovered in this loop.
Personally, it doesn't make much sense in that regard, as it's an instance factory.

**Comment by InfinityRaider** [comment]
I agree with @Deamon5550  and @Jezza that private methods should not lose support, I forgot to take this into consideration, changing to getMethods() is out of the question then.

It seems to me the best bet would be to go through the hierarchy as @Deamon5550 suggested. I give my vote to doing this recursively. This also avoids messing with annotations.

**Comment by mcenderdragon** [comment]
What is about an annotation at the class like @ UsesSuperClass so thje EventHandler only checks the super classes, if this annotation is present. Because i think everything else can cause a performance issue. (And maybe is not wanted)

**Comment by Jezza** [comment]
@mcenderdragon That's what I recommended earlier, but @heldplayer raises a valid point; it's only ever fired once per mod (via `FMLConstructionEvent`), so performance isn't really an issue.
If we really wanted to improve performance, we could make use of `ASMDataTable`, as it's available from the calling method.

**Comment by mcenderdragon** [comment]
@Jezza well I through of also adding this to the EventBus from Forge but if this is only for the mods then perfomance is realy not an issue.

**Comment by Jezza** [comment]
@mcenderdragon nah, it's an internal method.
[`FMLModContainer`](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/fml/common/FMLModContainer.java#L381) if you want to take a look.

**Comment by mcenderdragon** [comment]
how about adding a boolean parameter to the register method ?

**Comment by Jezza** [comment]
I was just thinking about making it recursive. At the end of the method, obviously.

```
if (clazz.getSuperclass() == Object.class) {
  return factoryMethod;
}
Method superFactoryMethod = gatherAnnotations(clazz.getSuperclass());
return factoryMethod != null ? factoryMethod : superFactoryMethod;
```

Something like that.

**Comment by Jezza** [comment]
There is only one comprise with this system, due to how the `FMLModContainer` stores `EventHandlers`.
It stores the methods by the event class, which means there's going to be a conflict when a hierarchy declares multiple handlers for any given event.
Should a subclass take precedence?

eg:

```
public class MyBaseModClass {
  @Mod.EventHandler
  public void myEventHandler(SameEventevent) {
    // blah
  }
}
```

and

```
public class MyModClass {
  @Mod.EventHandler
  public void someOtherRandomMethod(SameEvent event) {
    // blah
  }
}
```

Given how I've written the hierarchy traversal, the superclass currently takes precedence.
I'd expect subclasses to take priority over superclasses, so I'm going to change it, but does anyone else have any thoughts?

**Comment by Jezza** [comment]
Oh, I was wrong.
It's a multimap... How did I not spot that...
Ok, so we can easily register multiple methods that accept the same method across the hierarchy.
The main problem now, is we can accidentally register the same method multiple times.

**Comment by Jezza** [comment]
Detecting this isn't entirely simple, as we have to verify that any given method is a parent of another.
And that's not simple thanks to bridge methods.

**Comment by Jezza** [comment]
Looking back at this, it's actually fairly easy to implement.
I'd have to look at the code again to make sure, but it's straight-forward.
Just check if any given method is a bridge method.
