### ISSUE TITLE
Allow custom EntitySelectors in commands

### ISSUE THREAD

**Issue by maxanier** [MinecraftForge/MinecraftForge#3345]
A few server admins have asked me if it is possible to use the entity selectors ("@a[...]") to select players depending on attributes added by my mod Vampirism.
After taking a look at vanilla MC does in the selector code it seems like it should be quite easy to add to Forge.
In net.minecraft.command.EntitySelector@110 MC collects all kinds of Predicated (XP, name, gamemode, etc.), so it should be possible to add an event there that can be used by mods to add their own predicates.
Maybe with a special notation, e.g. "@e[modid:argument=value,gamemode=1]".

If there is a chance that it would be accepted, I could create a PR.

**Comment by Mathe172** [comment]
We're currently looking into creating a PR that would allow you to override selector parsing. Although not perfect for your case, it would still allow you to achieve what you're looking for. (Not quite sure if that PR will be accepted, though)

**Comment by LexManos** [comment]
All this needs is a simple event to gather a list of custom predicates...
Nothing complicated like changing the command format. Just extra key-value pairs int eh command then predicates to filter things out.
