### ISSUE TITLE
no EntityPlayerSP.sendHorseLand (MC 1.10.2)

### ISSUE THREAD

**Issue by ZornTaov** [MinecraftForge/MinecraftForge#3348]
There is no CPacketEntityAction sent that uses CPacketEntityAction.Action.STOP_RIDING_JUMP, which looks like it should either fire for when a player jumps while riding a IJumpingMount entity is canceled or when you land.  Would like to ask this be added in for when the player lands their IJumpingMount entity.

**Comment by LexManos** [comment]
We are not in the habit of editing the Minecraft protocol to add arbitrary extra states.
Yes this is a existing enum value but vanilla has no specification of what it is used for and if we just decide a random spot to put this then we will undoubtedly conflict if they ever decide to put it anywhere.
You suggestion doesn't seem to fix in it as well as its a client action, not a end-of-state event.
