### ISSUE TITLE
Crash during loading screen

### ISSUE THREAD

**Issue by tehbasshunter** [MinecraftForge/MinecraftForge#3351]
Created a fresh new world earlier and went to add a supposedly updated version of a 1.7.10 mod. However when I would start the instance with MultiMC it would crash towards the end of the forge loading screen and close without indicating any version conflict.

I'm using MultiMC version 1.10.2 with forge 2099/2104 (Needed minimum for one mod)/2118

[Crash Log](http://paste.ee/p/mJzsB)
[Full Log](http://paste.ee/p/02bmS)

**Comment by tehbasshunter** [comment]
Those are the 3 specific builds I tried as they're the recommended/latest version and one was the minimum need for a mod.

**Comment by diesieben07** [comment]
There is a mod specifying some kind of invalid dependency information. You need to remove mods one by one; and please use the forums for issues like this.

**Comment by tehbasshunter** [comment]
Probably should've mentioned it in the original post but it was Bspkrs and Armor Status HUD causing the issue.  

The problem is that it gave no indication what the issue was. It would go through loading screen and nearly finish before it would simply close without indicating what was causing the issue was like the image below would've similarly shown.  When I was speaking on the MultiMC IRC one of the makers he believed the issue that I was having appeared to be a forge bug since it occured during loading.  

![Similar mod issue](http://i61.tinypic.com/2b4hur.jpg)

**Comment by diesieben07** [comment]
That crash suggests a bug on the mod side to me. If the mod makers believe this is a forge bug, they should submit proper bug report.
