### ISSUE TITLE
Players consistently kicked from server/can't join [nettyIO issue]

### ISSUE THREAD

**Issue by AussieWarGod** [MinecraftForge/MinecraftForge#3363]
We are unsure of the root of this problem but have narrowed it down to a sponge or a forge issue (we think) and so are pushing this issue to both sponge and forge git's.

Basically at random intervals a single player will be disconnected, pushing out a nettyIO error message.
Then at other intervals everyone will be kicked with another nettyIO error.
nettyIO errors also come up when some people try to connect and on occasion those players will be completely unable to connect until after the next restart.

This is persistent across all our 1.10 modpacks/servers. I will include the latest logs from our Infinity Lite and Hermitpack servers.

Infinity:
[Infinity Lite fml-server-3.txt](https://github.com/MinecraftForge/MinecraftForge/files/574682/Infinity.Lite.fml-server-3.txt)
[Infinity Lite fml-server-latest.txt](https://github.com/MinecraftForge/MinecraftForge/files/574683/Infinity.Lite.fml-server-latest.txt)
[Infinity Lite fml-junk-earlystartup.txt](https://github.com/MinecraftForge/MinecraftForge/files/574684/Infinity.Lite.fml-junk-earlystartup.txt)
[Infinity Lite fml-server-1.txt](https://github.com/MinecraftForge/MinecraftForge/files/574685/Infinity.Lite.fml-server-1.txt)
[Infinity Lite fml-server-2.txt](https://github.com/MinecraftForge/MinecraftForge/files/574686/Infinity.Lite.fml-server-2.txt)

Hermit:
[HermitPack fml-server-2.txt](https://github.com/MinecraftForge/MinecraftForge/files/574687/HermitPack.fml-server-2.txt)
[HermitPack fml-server-3.txt](https://github.com/MinecraftForge/MinecraftForge/files/574688/HermitPack.fml-server-3.txt)
[HermitPack fml-server-latest.txt](https://github.com/MinecraftForge/MinecraftForge/files/574689/HermitPack.fml-server-latest.txt)
[HermitPack fml-junk-earlystartup.txt](https://github.com/MinecraftForge/MinecraftForge/files/574690/HermitPack.fml-junk-earlystartup.txt)
[HermitPack fml-server-1.txt](https://github.com/MinecraftForge/MinecraftForge/files/574691/HermitPack.fml-server-1.txt)

SpongeAPI: 6.0.0
SpongeForge: 1.10.2-2107-6.0.0-BETA-1864
Minecraft Forge: 12.18.2.2119

If this is in fact not either a sponge or forge issue any assistance in identifying the problem would be greatly appreciated. Thank you in advance.

**Comment by AshIndigo** [comment]
Try reproducing it without sponge.

**Comment by AussieWarGod** [comment]
It is not reliably reproduceable at any point, we do not have a public server we can push people to without sponge.

If it were possible i would not be asking for assistance.

**Comment by AussieWarGod** [comment]
The disconnects are completely random, some people are unaffected, some are.

**Comment by diesieben07** [comment]
This is not the place to ask for assistance, this is a place to report forge bugs.

**Comment by AussieWarGod** [comment]
Super helpful dudes. -sarcasm- 

Evidently it's not something you recognise off the top of your heads, which is what i was hoping for.

Or you didn't read it.

Anyway i will /attempt/ to test it without sponge and get back to you

**Comment by diesieben07** [comment]
Even if it was something "we recognise", this is still not the right place to discuss it.
This is a bugtracker, not a forum for help.

**Comment by AshIndigo** [comment]
http://www.minecraftforge.net/forum/index.php?board=15.0 

Go post it on there since diesbien said this isnt a forum for help.
