### ISSUE TITLE
Custom Dimension load error "Loading terrain" forever

### ISSUE THREAD

**Issue by gmbr3** [MinecraftForge/MinecraftForge#3365]
MINECRAFT LOG REPORTS:
[MinecraftLog.txt](https://github.com/MinecraftForge/MinecraftForge/files/575982/MinecraftLog.txt)

**Comment by LexManos** [comment]
Seems like a error in how you're teleporting the entity to the custom dimension.
Its erroring on what I assume is this part of the code:
entityIn.getLastPortalVec().yCoord

So teleport your entities correctly, not a Forge issue.
Also, stop using mcreator learn to make real mods -.-
