### ISSUE TITLE
Fluids don't work

### ISSUE THREAD

**Issue by gmbr3** [MinecraftForge/MinecraftForge#3366]
MINECRAFT LOG:
[MinecraftLog2.txt](https://github.com/MinecraftForge/MinecraftForge/files/576377/MinecraftLog2.txt)

**Comment by williewillus** [comment]
Gonna need more details than just that

**Comment by gmbr3** [comment]
What do you want?

**Comment by gmbr3** [comment]
Code:
[ChocolateCode.txt](https://github.com/MinecraftForge/MinecraftForge/files/576408/ChocolateCode.txt)

**Comment by diesieben07** [comment]
This is a bugtracker for forge bugs, not a forum for help with code. Use [the forums](http://www.minecraftforge.net/forum/index.php?board=73.0).

**Comment by LexManos** [comment]
STOP using mcreator, and write real mods.

You need a level of understanding of what you're doing. mcreator just teaches you how to do everything wrong.
