### ISSUE TITLE
Connect to a modded server

### ISSUE THREAD

**Issue by THEJean-Kevin** [MinecraftForge/MinecraftForge#3367]
Hello,
I am currently an administrator of many modded servers, and I would like to know if this is possible with a mod or a plugin to connect to a server with any modpack (replacing modded blocks with a another texture).

It's to manage all server without change modpack

Thanks you

**Comment by LexManos** [comment]
This is not a Q&A Forums, thats what the Forums are for. This is for issues with Forge itself.
