### ISSUE TITLE
Unable to launch java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by 0Navis0** [MinecraftForge/MinecraftForge#3369]
I get this crash on 12.18.2.2124 and 12.18.2.2123 Forge version. http://pastebin.com/feUh0J4N

**Comment by simon816** [comment]
Not a forge issue, some mod is conflicting with another

**Comment by Chocohead** [comment]
A mod's screwed up ASMing BlockCrops, probably ToughAsNails as it warns about a different hash than the one it expected.

**Comment by xlxAciDxlx** [comment]
Is it safe to assume the mod right before the crash is the cause? I have the same crash/inability to launch, but instantly and right before it mentions "BetterFPS." I only get the crash on 2123 and 2124. 2122 works fine.

**Comment by Chocohead** [comment]
It's not necessarily it's fault alone, but there's definitely something different than what it's expecting. 998a78c could well be the cause as that modified BlockCrops (and was the commit for 2123). Of course if it is, it's any mod ASMing it to fix what they're doing, not Forge.

**Comment by LexManos** [comment]
Stop using coremods, simple as that.
And this is not tech support. This is for reporting issues you KNOW are Forge. Not random coremods you have.
