### ISSUE TITLE
Crash In Anvil On Server

### ISSUE THREAD

**Issue by MitchellShapiro** [MinecraftForge/MinecraftForge#3370]
Use following mods:
[1.10]RealTimeTranslation-4.1.1
Batty's Coordinates PLUS Mod (1.10.2_001)
LunatriusCore-1.10.2-1.1.2.36-universal
Optifine_1.10.2_HD_U_D2
Schematica-1.10.2-1.7.8.152-universal

Here is the crash report:
[http://pastebin.com/RMq8Ndf5](http://pastebin.com/RMq8Ndf5)

In an anvil, I had a custom enchanted shovel in the first slot. I tried to place an Unbreaking III book in the right slot, but as soon as I clicked, my game crashed to desktop. I am using Forge 
1.10.2-forge1.10.2-12.18.2.2114, which is not the latest but I am scared to test again in the latest as I almost lost my stuff.

**Comment by bs2609** [comment]
Post crash reports on the forums, rather than opening an issue here.
http://www.minecraftforge.net/forum/index.php?board=15.0
