### ISSUE TITLE
setSubstituteAlias item shows up twice in creative tabs or none at all

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3371]
if you set a creative tab
the substituted Item shows up  once it's normal spot and  a second time into wherever creative tab you added it to

if you don't set a creative tab
the substituted item does not show up at all in any creative tab   . searching for it finds nothing.

version = "1.10.2-12.18.2.2122

as far as i can tell everything works

**Comment by howtonotwin** [comment]
Duplicate of #3134.

**Comment by ghost** [comment]
Oh nvm I see now cpw left this one in and is not fixing. It can be closed.  Is not a big deal since it actually works just fine.
