### ISSUE TITLE
Request - include facing/side in the BlockEvent.BreakEvent

### ISSUE THREAD

**Issue by AlexiyOrlov** [MinecraftForge/MinecraftForge#3372]
It would be useful to obtain a side of the block being broken, because `Minecraft.getMinecraft().objectMouseOver` gets the side after the block is broken, thus gets the side of the block behind it.
The use case is getting the blocks around given event's block position based on broken block's targeted side.

**Comment by diesieben07** [comment]
You have to check if this is actually possible, because I'm pretty sure this information is not available on the server, where this event is fired.

**Comment by AlexiyOrlov** [comment]
I looked at the code and yes, related method `net.minecraft.entity.Entity#rayTrace` is client-only. This method calls client-side method `net.minecraft.entity.Entity#getPositionEyes` which contents, I guess, can be copied into another method. Other methods aren't sided.

**Comment by diesieben07** [comment]
Yes, but by default the server doesn't ray-trace. If you add it, just for the event, make sure you perform adequate tests so that it does not degrade performance. Also note that server-side raytracing can never be as accurate as the client-side one.

**Comment by simon816** [comment]
The `CPacketPlayerDigging` packet already contains the `EnumFacing` for the face of the block. It gets passed to `PlayerInteractionManager#onBlockClicked`. You could probably save the face for the event later

**Comment by AlexiyOrlov** [comment]
@simon816 ok, so the best workaround is to get the facing from PlayerInteractEvent.LeftClickBlock and send it to the server event handler?

**Comment by AlexiyOrlov** [comment]
I guess this can be closed, as I've made a workaround. But a some kind of player event involving breaking block at specific facing could be helpful.
