### ISSUE TITLE
Maven Error (500) when attempting to compile MDK

### ISSUE THREAD

**Issue by zliebersbach** [MinecraftForge/MinecraftForge#3376]
I just got myself a fresh copy of the MDK and have set it up with Intellij IDEA. However, when I try to compile it I get the following warning:
```
Unindexed remote maven repositories found. Disable...
The following repositories used in your gradle projects were not indexed yet: 
http://files.minecraftforge.net/maven
If you want to use dependency completion for these repositories artifacts,
Open Repositories List, select required repositories and press "Update" button
```

When I do press "Update", it throws an error (with no description). So then I visited the failing [URL](http://files.minecraftforge.net/maven), and sure enough, I got a 500 Internal Server error.

Any thoughts on the issue? Seems like a problem with the repository to me.

**Comment by JustGregory-zz** [comment]
I asked this very same thing once upon a time in the forums, to which Lex responded it's not a Maven repo. I think it may be Ivy or something else, but Gradle can still pull artifacts from it.

**Comment by LexManos** [comment]
It is a maven repo, however what you're looking at is either a non-standard or optional repo feature.
It is trying to download the index of everything that is on the repo server.
We do not provide that. There is no real reason for it as all this feature lets you do is when you go to edit your project dependencies it gives you hints as to what you can add {like if you know you want to add guava but not what version, typing guava would give you a list of versions}

As a modder you do not manage your Forge/Vanilla dependencies, so this is doesn't matter for our server.
As for other types of deps served from our server, the version numbers are listed on their page. So just using the number is a option.
Point is, having this auto-complete is optional and doesn't really matter. Move on with the setup process.

**Comment by liach** [comment]
@wincinderith Just ignore that note. It is useless and has no effect.
