### ISSUE TITLE
Execution failed for task ":deobfMcSRG"

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3384]
When I run setup decompworkspace, I get the error

> Execution failed for task ":deobfMcSRG"
Here is a screenshot of the entire output from gradlew:
![forgeerror](https://cloud.githubusercontent.com/assets/17693001/20362664/1292acfe-ac02-11e6-9c30-c4ece2192fab.PNG)
(I tried piping the output to plain text, but some of the output stayed in the console anyway. :( )
Is this a bug, or merely an error on my part?

**Comment by kashike** [comment]
> ```
> > Your Access Transformers be broke!
> ```
