### ISSUE TITLE
[1.11] Weird durability color

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#3389]
![2559-11-16_23 38 36](https://cloud.githubusercontent.com/assets/6128413/20370291/8d4e32fe-ac90-11e6-8af9-107c8c01c548.png)

**Comment by LexManos** [comment]
Remove all mods and try again.

**Comment by shadowfacts** [comment]
Confirmed in the Forge dev-env:

![2016-11-16_18 46 41](https://cloud.githubusercontent.com/assets/7091588/20370498/0713f3a8-ac2d-11e6-8122-a0e726398cec.png)
