### ISSUE TITLE
1.11 ItemStack  stackSize has been made private . need getStackSize() or if exists needs to be renamed

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3390]

**Comment by ShetiPhian** [comment]
Its all at the bottom of ItemStack but is unnamed

GetStackSize = ItemStack.func_190916_E
SetStackSize = ItemStack.func_190920_e
IncreaseStackSizeBy = ItemStack.func_190917_f
DecreaseStackSizeBy = ItemStack.func_190918_g

**Comment by shadowfacts** [comment]
It exists, `func_190916_E`, it just doesn't have a name yet because MCP for 1.11 hasn't been released.

**Comment by ghost** [comment]
COPY thanks!

**Comment by ghost** [comment]
closing because 1.11 hasn't been released yet I guess

**Comment by afannnn** [comment]
http://www.mediafire.com/file/450x418crh55156/mcp935-rc1.zip Think again ;).

**Comment by afannnn** [comment]
@shadowfacts ^^^^*

**Comment by LexManos** [comment]
Closing because we have nothing to do with this.
The bot will eventually be updated and people will start naming new things.
This is how updates work, just live with it.

**Comment by ghost** [comment]
@LexManos no problem I'm working with what I can right now :D
