### ISSUE TITLE
1.11 onItemUse function (in ItemSlab) variables don't match type

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3391]
onItemUse(EntityPlayer stack, World playerIn, BlockPos worldIn, EnumHand pos, EnumFacing hand, float facing, float hitX, float hitY)

EntityPlayer stack??
World playerIn ??
... etc

**Comment by shadowfacts** [comment]
Quote from your other issue:

> MCP for 1.11 hasn't been released.
1. That's the cause of the naming issues
2. The Forge repo is the wrong place to report them

**Comment by ghost** [comment]
should i close this?

**Comment by shadowfacts** [comment]
Yes, and the other one should be closed.

**Comment by ghost** [comment]
done
