### ISSUE TITLE
[1.11]Large number of recipes don't work

### ISSUE THREAD

**Issue by CoderAtParadise** [MinecraftForge/MinecraftForge#3396]
List of all recipes that were test to not work in a clean forge environment
[Link](https://gist.github.com/CoderAtParadise/848f110609a41245b0838e2c901ccc41)

**Comment by GirafiStudios** [comment]
What version of Forge are you using?

**Comment by CoderAtParadise** [comment]
1.11-13.19.0.2141

**Comment by robin4002** [comment]
The ore dictionary seems broken. All recipe listed here used items or blocs that is in the dictionary.

**Comment by CoderAtParadise** [comment]
Yeah a quick look at Ore Dict shows that parts of the ore dict need to be updated to use nonnull lists and to change the null checks on stacks

**Comment by Larsg310** [comment]
I have made a PR which fixes this, it was indeed caused by null ItemStacks. #3400
