### ISSUE TITLE
[Question]Forge 12.18.2.2099+

### ISSUE THREAD

**Issue by Dushess** [MinecraftForge/MinecraftForge#3403]
Hello, I'm using Win XP and my launcher cannot update Forge to newest version.
In other place (other PC) on Win 7 he successfully update it to 2125.

It's really related?

**Comment by Dushess** [comment]
Strange, but in this try on Win 7 (my PC) i got 2099 again.

**Comment by LexManos** [comment]
Use the forums this is not the place for PEBKAC errors.
