### ISSUE TITLE
[Request] Add BlockSpreadEvent

### ISSUE THREAD

**Issue by joekaiser** [MinecraftForge/MinecraftForge#3406]
There is currently no event that fires when a block (grass, mushroom, etc) spreads to an adjacent block. It would be useful to have an event that is fired when this happens.

I am willing to do the work, but I wanted to get feedback on the usefulness of this before I do the work.

Relevant code from blockMushroom

 ```
public void updateTick(World worldIn, BlockPos pos, IBlockState state, Random rand)
    {
        if (rand.nextInt(25) == 0)
        {
            int i = 5;
            int j = 4;

            for (BlockPos blockpos : BlockPos.getAllInBoxMutable(pos.add(-4, -1, -4), pos.add(4, 1, 4)))
            {
                if (worldIn.getBlockState(blockpos).getBlock() == this)
                {
                    --i;

                    if (i <= 0)
                    {
                        return;
                    }
                }
            }

            BlockPos blockpos1 = pos.add(rand.nextInt(3) - 1, rand.nextInt(2) - rand.nextInt(2), rand.nextInt(3) - 1);

            for (int k = 0; k < 4; ++k)
            {
                if (worldIn.isAirBlock(blockpos1) && this.canBlockStay(worldIn, blockpos1, this.getDefaultState()))
                {
                    pos = blockpos1;
                }

                blockpos1 = pos.add(rand.nextInt(3) - 1, rand.nextInt(2) - rand.nextInt(2), rand.nextInt(3) - 1);
            }

            if (worldIn.isAirBlock(blockpos1) && this.canBlockStay(worldIn, blockpos1, this.getDefaultState()))
            {
                worldIn.setBlockState(blockpos1, this.getDefaultState(), 2);
            }
        }
    }
```

**Comment by LexManos** [comment]
Why just mushrooms? There are a lot of blocks that "spread"

**Comment by joekaiser** [comment]
Because I only need it for mushrooms :)

In all seriousness, it should be expanded then. Perhaps a generic BlockSpreadEvent?

**Comment by mezz** [comment]
Why do you need this? Please give a specific example.

**Comment by joekaiser** [comment]
I had two examples in mind.

1) if you needed a way to prevent something like grass from spreading you can subscribe to the event and cancel it.

2) more specifically, I have a desire to know when a mushroom spreads next to a log. There would be a chance that log will become spalted from the fungus next to it.

My thought was I could watch for the event, and when it fires get the blocks directly next to the BlockPos of the new mushroom. If one of those blocks is a log, I would run the code needed to spalt it.

It isn't a huge issue for me. I can always fall back on making my own mushroom and it will handle it. I was hoping to utilize the vanilla blocks (and other modded mushrooms if they exist) without needing to ASM

**Comment by mezz** [comment]
1. I suspect this is only a theoretical point. If you're making a mod that prevents the spread of grass then sure let's look deeper, but otherwise let's not.
2. I think you can use `Block.neighborChanged` to detect when a mushroom is placed next to your log.

**Comment by joekaiser** [comment]
By log I mean any wood. Oak, spruce, birch, Forestry tress..etc. OnNeighborChanged wouldn't work.

**Comment by mezz** [comment]
Ok, makes sense thanks.
I think in the meantime you can do this without ASM by using `World.addEventListener(IWorldEventListener)` and implementing your check for mushrooms and logs in `IWorldEventListener.notifyBlockUpdate`?
Probably not the best idea for performance though.

**Comment by joekaiser** [comment]
I wasn't aware of that. I will take a look for sure.

To be clear, I don't mind writing the PR. I just want to make sure it has a chance of being accepted first :)

**Comment by camerondm9** [comment]
I would also be interesting in this kind of event, specifically for preventing fire from spreading into specific places, while allowing it to behave normally elsewhere. The event could have (World world, BlockPos source, BlockPos target, IBlockState newTarget) or something like that? It could also apply to water and lava spreading in BlockDynamicLiquid, since that is something that would also be valuable to control.

**Comment by mezz** [comment]
In theory it sounds like a useful and reasonable event, I think you should write a PR.
