### ISSUE TITLE
[1.11] Crash when clicking on the "Miscellaneous" Tab

### ISSUE THREAD

**Issue by vladfrangu** [MinecraftForge/MinecraftForge#3418]
Using the latest beta version of Forge for 1.11, I've accidentally clicked on the miscellaneous tab, only to find an instant crash, apparently due to a missing field when looking for the color of the eggs (or so I think)

Heres the [log](https://gist.github.com/KingDGrizzle/b6b8666ffbb03105eae2c73468e59679). I wasn't using any resource packs other than a sky one, to add fancy clouds.

**Comment by LexManos** [comment]
Optifine/CraftBukkit issue.
They need to update to our entity changes.

**Comment by vladfrangu** [comment]
Seems to be Optifine related, will wait and see what happens
