### ISSUE TITLE
[1.11 - build 2153] Disconnecting from a server does not actually disconnect.

### ISSUE THREAD

**Issue by skyerzz** [MinecraftForge/MinecraftForge#3420]
When clicking "disconnect" when on a server, you return to the server list. You however, do not log out. Sounds and chat keep going (chat invisible normally, through a mod still can be picked up.) Your user also stays on the server in place.

Only way to **really** log out on a server is to shut down the whole client.

**Comment by mattmess1221** [comment]
I'm curious what happens when you join another server after disconnecting.

**Comment by mezz** [comment]
Is this still an issue with the latest version of Forge? It looks like one of the recent fixes may affect this.
