### ISSUE TITLE
[1.11 2153] Rendering entities sometimes crashes game

### ISSUE THREAD

**Issue by skyerzz** [MinecraftForge/MinecraftForge#3421]
[crash-2016-11-19_17.06.54-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/601550/crash-2016-11-19_17.06.54-client.txt)
[crash-2016-11-19_16.55.17-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/601551/crash-2016-11-19_16.55.17-client.txt)

I notice that both times its about the entity EntityOtherPlayerMP , which results in null? Im not the best at reading these things. Issue was non-existent on previous build 2141.

**Comment by LexManos** [comment]
Optifine needs an update,
