### ISSUE TITLE
[1.11 - 2153] ItemCraftedEvent returns air when shift-clicking

### ISSUE THREAD

**Issue by Ellpeck** [MinecraftForge/MinecraftForge#3424]
When subscribing to `PlayerEvent.ItemCraftedEvent`, `crafting` is the item or block that was crafted when pulling the item out of the result slot with the mouse directly.
When shift-clicking, however, `crafting` will always be air.
`

**Comment by mezz** [comment]
Fixed in 1.11-13.19.0.2157
