### ISSUE TITLE
[1.11 - 2153] FMLControlledNamespacedRegistry calling abstract method

### ISSUE THREAD

**Issue by Syndaryl** [MinecraftForge/MinecraftForge#3427]
When I execute my command block, Minecraft crashes with Forge throwing an exception. I can reproduce this with no mods installed, and with mods installed.

Command block code: http://pastebin.com/ip95vma8
(Set block to always active, you may need to toggle it back and forth a few times to react?)

Repro notes: Command block wants to be executed near world origin (0,X,0 - at the surface somewhere within less than a chunk of that co-ordinate).
Command block script is to set yourself to spectator and teleport around the world, forcing chunk generation while you're AFK getting a sandwich and a coffee. Instead, it crashes with java.lang.AbstractMethodError: Method net/minecraftforge/fml/common/registry/FMLControlledNamespacedRegistry.getKeys()Ljava/util/Set; is abstract

Crash Log: http://pastebin.com/HAZ4c5j5

Attached full latest log
[latest.txt](https://github.com/MinecraftForge/MinecraftForge/files/602387/latest.txt)

EDIT: Should have mentioned, I can confirm it does not crash w/out Forge loaded. It doesn't do what I expected it to, but it doesn't crash.

**Comment by liach** [comment]
Related to these lines: https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/patches/minecraft/net/minecraft/entity/EntityList.java.patch#L95-L99
