### ISSUE TITLE
Anyone can edit the forge wiki on github

### ISSUE THREAD

**Issue by raphydaphy** [MinecraftForge/MinecraftForge#3428]
By default, github allows anyone to edit the wiki, and since you haven't changed the setting, anyone can do that on the forge wiki in github. You should probably change this to avoid spam and other bad things 👍 

Steps to replicate:

1. Log into a github account that dosent have a role on forge github
2. Goto https://github.com/MinecraftForge/MinecraftForge/wiki
3. Click Edit

**Comment by williewillus** [comment]
1. That's the purpose of a wiki
2. That's not the official documentation site, [https://mcforge.readthedocs.io](https://mcforge.readthedocs.io) is. and that requires pull requests to modify

**Comment by raphydaphy** [comment]
O ok sorry :(
