### ISSUE TITLE
Unexpected, unknown crash, don't know the cause

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3431]
I don't know what owner of mod belongs to, but I can send it back to the mod creator.
http://pastebin.com/QkA2hYKJ
Please give me some advice and help.

**Comment by diesieben07** [comment]
For a start stop using a cracked launcher. Also this a bugtracker for forge, for tech support please use the forums.

**Comment by GirafiStudios** [comment]
This have nothing to do with Forge, but is caused by Tough as Nails. Please report the issue here: https://github.com/Glitchfiend/ToughAsNails instead :)

**Comment by ghost** [comment]
thanks for the help i am not good in dealing with crashes that i dont even know... its too detailed and huge!!

**Comment by ghost** [comment]
_insert my stupid excuse for why I use a cracked launcher which I should never do because I should just buy the damn game._
_Fix that for you.. -Lex_
