### ISSUE TITLE
[1.11 - 2154] Redstone mechanics inconsistency

### ISSUE THREAD

**Issue by Greymerk** [MinecraftForge/MinecraftForge#3432]
I've created a couple of simple upward dropper/downward hopper devices hooked up to a clock, each one contains a wooden sword. These function differently in vanilla than in forge.

In vanilla both comparators flash.
In forge only the one on the right flashes.

![2016-11-21_19 13 38](https://cloud.githubusercontent.com/assets/4789166/20509856/90616dce-b020-11e6-995a-1e134196f21e.png)

**Comment by Greymerk** [comment]
The one on the right only behaves correctly because the hopper is being indirectly powered by the repeater. I believe there's a delay missing when items are put into hoppers. Normally there's a delay long enough to be registered by a comparator.

**Comment by mezz** [comment]
Would you say this is a hopper inconsistency then, rather than a redstone one?

**Comment by mezz** [comment]
I set this up and I can confirm that with Forge the left hopper outputs the stack much more quickly than the timer-locked right one. With vanilla they take about the same time.

**Comment by mezz** [comment]
Fixed with a PR, there were some inconsistencies with how hoppers and droppers move items in Forge compared to Vanilla.
After the fix is in, please help test it more by trying to break it with other vanilla contraptions.

**Comment by Greymerk** [comment]
I've tested the new build against the problem I was having and it is fixed as far as I'm concerned. Thanks for fixing this 👍
