### ISSUE TITLE
[1.11] ItemStack has missing patches

### ISSUE THREAD

**Issue by maruohon** [MinecraftForge/MinecraftForge#3452]
ItemStack is missing some patches, at least the areItemStackTagsEqual() and isItemStackEqual() methods don't take capabilities into account.

**Comment by mezz** [comment]
It looks like this will be fixed by https://github.com/MinecraftForge/MinecraftForge/pull/3500

**Comment by bs2609** [comment]
@mezz Is this resolved now?

**Comment by mezz** [comment]
Yep, looks like it.
