### ISSUE TITLE
Substitutions for all FMLControlledNamespacedRegistries

### ISSUE THREAD

**Issue by maxanier** [MinecraftForge/MinecraftForge#3453]
As I found out in #3230 the substitution system of Forge/FML is really powerful.
Unfortunately it is still limited to blocks and items, but I did not find a real reason for this.
The main problem is that `GameRegistry#addSubstitutionAlias` only accepts blocks and items and that `ObjectHolderRegistry#findObjectHolders` only adds ObjectHolders to net.minecraft.init.Blocks and net.minecraft.init.Items.

I've extended the system https://github.com/maxanier/MinecraftForge/commit/00a3bd5b4e49d9d32158eeae0440d7806631a21f and tested it for potions. It works.
Maybe I missed some possible issues, since the whole registry stuff is quite complex.
But if you can not see any issue, maybe the system could be activated for all registries, or at least for potions and enchantments (I could imagine that biome substitution could cause problems, but don't know).

**Comment by williewillus** [comment]
Make a pull request instead if you want to submit code changes

**Comment by maxanier** [comment]
But because I'm really not sure if I missed something, I thought it would be better to discuss it here first. Also Lex mentioned that he put it on his TODO list, maybe he has a different approach in mind. Just wanted to show that the system already works, and just needs a modder facing method.

**Comment by howtonotwin** [comment]
Pull requests are not just for completed ideas, they are also for discussion and revision of partially complete (and sometimes completely unimplemented) ones.

**Comment by maxanier** [comment]
As 1.12 finally solves this problem (in a different way)
