### ISSUE TITLE
[1.11 - Forge 2160] Mob Sprawner don't save Entity NBT.

### ISSUE THREAD

**Issue by Sejoslaw** [MinecraftForge/MinecraftForge#3454]
I did try to save MobSpawner NBT data like so:
`myTag.setTag("serializeNBT", ((TileEntityMobSpawner) tileEntity).serializeNBT());`

It only saved position of the `TileEntity` and it's id:

![mobspawnernbt](https://cloud.githubusercontent.com/assets/13147684/20640178/b43fba2e-b3d7-11e6-9a15-4f0c369ed968.PNG)

I'm sure in 100 % that the tile I'm saving is a `TileEntityMobSpawner`

It looks like it did not save the `spawnerLogic` data.

Using `writeToNBT` I had the same issue:
`myTag.setTag("writeToNBT", ((TileEntityMobSpawner) tileEntity).writeToNBT(new NBTTagCompound()));`

![writetonbt](https://cloud.githubusercontent.com/assets/13147684/20640248/024c0ca8-b3d9-11e6-9eaf-af4fc2d262a1.PNG)

**Comment by Choonster** [comment]
`MobSpawnerBaseLogic#writeToNBT` won't write anything to the compound tag if `MobSpawnerBaseLogic#getEntityId` returns `null`. Is this the case for the `TileEntityMobSpawner` you're saving?

**Comment by Sejoslaw** [comment]
`tileMobSpawner.getSpawnerBaseLogic().getCachedEntity()` always returns me `EntityPig` with random id:
`[STDOUT]: EntityPig['Pig'/487827, l='New World', x=0,00, y=0,00, z=0,00]` 
where id is like so `tileMobSpawner.getSpawnerBaseLogic().getCachedEntity().getEntityId()` = `487827`

**Comment by Choonster** [comment]
That's not the method I was talking about. `Entity#getEntityId` isn't `MobSpawnerBaseLogic#getEntityId`.

Is there a way to reliably reproduce this issue?

**Comment by Sejoslaw** [comment]
Eclipse can't find `MobSpawnerBaseLogic#getEntityId`. I'm sorry.
If You use VanillaMagic Mod, there is a way to "store" `TileEntity` inside a book.
It will save all NBT data inside `ItemStack`. I tried to "store" MobSpawner but it only saves position and id of this `TileEntity`.

This is the method which I use to save all the data:
[https://github.com/Sejoslaw/VanillaMagic/blob/1.11/VanillaMagic/src/main/java/seia/vanillamagic/quest/QuestMoveBlock.java#L136](https://github.com/Sejoslaw/VanillaMagic/blob/1.11/VanillaMagic/src/main/java/seia/vanillamagic/quest/QuestMoveBlock.java#L136)

I also use NBTExplorer to see the written NBT data.

**Comment by HenryLoenwind** [comment]
Come on, just LOOK at the code you're calling. Then set a breakpoint at your call and single-step into it. Then **you** can see what actually happens there, and **we** don't need to guess.

My guess: "new ResourceLocation("Pig").equals("Pig") === false" so the MobSpawnerBaseLogic is rejected. What is that check supposed to guard against?

**Comment by Sejoslaw** [comment]
My point is that I'm using basic `writeToNBT` method. It work nice for all other TileEntities.

**Comment by mezz** [comment]
~~The mob spawner item is always a pig. If you saw other kind of spawner items before, I believe it was from some NEI magic.
Middle-click a spawner in vanilla creative and see that you get the pig one back.
In vanilla you can set the pig spawner to another entity once it's in the world by right-clicking it with a spawn egg.
If you want to store block information, you can't trust the ItemStack to have everything necessary to recreate the block.~~

Sorry I misinterpreted, you are getting NBT from the tile, not the item.

**Comment by mezz** [comment]
How are you creating this spawner in the first place?

**Comment by Sejoslaw** [comment]
Yes, from the tile.
I did try few methods but finally I used the command:
`/setblock ~ ~1 ~ mob_spawner 0 replace {SpawnData:{id:entity_name}}` in the Command Block.
It spawned me a Mob Spawner.

**Comment by HenryLoenwind** [comment]
So it seems to really run into that Resourcelocation check. I'm guessing you're not giving the entity id in the "minecraft:lowercasename" form?

PS: I'm talking about the check in net.minecraft.tileentity.MobSpawnerBaseLogic.getEntityId()

PPS: Please try spawning a spawner with that command in both Forge and vanilla, then save and load the world. Does the spawner keep the type you set?

**Comment by Sejoslaw** [comment]
No, It is something like Cow, Zombie, etc.
I'm using Forge 2160 and Eclipse shows me that there is no method called `getEntityId()` in class `net.minecraft.tileentity.MobSpawnerBaseLogic`. I'm sorry.
No, it does not keep the type but when I use Spawn Egg with (for instance) Cow it does keep the type but when I try to save it to my `ItemStack` using `writeToNBT` it does not save the type.

**Comment by HenryLoenwind** [comment]
Then report it to the Mojang bug tracker.

**Comment by HenryLoenwind** [comment]
![](http://i.imgur.com/geqtAKL.png)

**Comment by Sejoslaw** [comment]
Now I know why it did not found me this function:

![getentityid](https://cloud.githubusercontent.com/assets/13147684/20643816/a1e6a40a-b422-11e6-9d12-a53f302e6ebe.PNG)

**Comment by HenryLoenwind** [comment]
oh, you're still using 1.10.2 mappings. Try snapshot_20161118 instead of snapshot_20161111, that'll make so many things have nice names...

**Comment by Sejoslaw** [comment]
I will do it. Thank You.

**Comment by Sejoslaw** [comment]
I did fix the issue. The issue was that in few places it has mismatches between for instance: "minecraft:cow" and "cow".
Sorry for bothering You. Thank You for Your time and help.
