### ISSUE TITLE
1.11 skulls/heads inventory item flipped facing away (shows back of the head)

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3456]
dunno if this has been reported yet or even if is a forge of MC issue.

this is build 13.19.0.2148

also related when placing the head/skull it always faces away for 2 milliseconds then it flips towards you. i assume it's probably a vanilla mc issue

**Comment by RANKSHANK** [comment]
Probably just a syncing delay like the double tall plants flashing the sunflower texture

**Comment by GirafiStudios** [comment]
@trollworkout can you reproduce this in vanilla Minecraft?

**Comment by williewillus** [comment]
this is just syncing delay in vanilla. rotation is stored in the tile entity which is sent after the block is placed

**Comment by mezz** [comment]
Might be this Vanilla bug: 
https://bugs.mojang.com/browse/MC-109831

**Comment by ghost** [comment]
guys it appears is a vanilla bug . sorry I am closing this unless I got actual proof is a forge issue not mc issue. One of Mojang devs said is fixed in 1.11.1  . The issue is the json models are backwards
