### ISSUE TITLE
[Request] 1.11 More furnace hooks

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3459]
as was discussed here http://www.minecraftforge.net/forum/index.php?topic=43604.0 seems some things are impossible to do without having some proper Furnace hooks

1. hook to conditionally allow furnace to produce alternative output (that is some furnaces can do this some can't)
for example  tell it to turn raw meat into boiled meat instead of cooked meat. produce alternative item
this would require some kind of smeltingResultEvent which fires when a furnace is about to output an item . you hook into it and give it an alternative item istead

2. hook to conditionally allow furnace to smelt new things that normally would not be possible otherwise (that is some furnaces can do this some can't)
this would require canSmeltEvent  which would tell a furnace it can  or cannot use a recipe or it can or cannot smelt an item.

3. this would also be nice a furnace fuel hook

I feel this may or may have not been requested before . probably has and maybe there's a good reason it was never implemented. i'm just putting it out there and hoping for the best.  I will probably have to replace the furnace with a custom block that extends FurnaceBlock and custom tile entity that extends FurnaceTileEntity .  I have a feeling it may also be possible by accessing the furnace tile directly and working on it. Maybe.

**Comment by Daomephsta** [comment]
You need to elaborate and clarify exactly what it is you want. Both of the problems you have described here are solvable without any new hooks. What you have described here is the ability to replace and add furnace recipes. What you actually want, judging by the linked thread, is the ability to conditionally change recipes depending on blocks in the world. 

You may be interested in joining the discussion about #3450. Please ensure that you clearly and accurately describe what you want.

**Comment by ghost** [comment]
@Leviathan143  you are correct. Conditionally change or replace recipes PER furnace via events and coding and such.

**Comment by HenryLoenwind** [comment]
we usually just make our own furnace block for such things...

**Comment by ghost** [comment]
@HenryLoenwind  I think I'm gonnan do the same

**Comment by ghost** [comment]
I realize not everyone needs what I need in my mod but the hooks may be useful in variety of ways not just how I plan to use them  here. 

I leave it up to you guys to decide .  You guys know better than me.

**Comment by mezz** [comment]
Sorry I don't think this would be accepted. You can gain complete control by creating your own furnace block that has its own unique behavior.

**Comment by ghost** [comment]
@mezz  No problem  That's what I'm working on next actually. Thanks guys
