### ISSUE TITLE
[1.11] Shift clicking item OUT of container that uses SlotItemHandler doesn't call ItemStackHandler#onContentsChanged

### ISSUE THREAD

**Issue by raoulvdberge** [MinecraftForge/MinecraftForge#3465]
This issue doesn't happen when regularly clicking out the item. When shift clicking, it doesn't fire the method.

**Comment by raoulvdberge** [comment]
Okay, after some investigation I figured out why this is happening.
Given this inventory handling code:

```java
    @Override
    public ItemStack transferStackInSlot(EntityPlayer player, int index) {
        ItemStack stack = ItemStack.EMPTY;

        Slot slot = getSlot(index);

        if (slot.getHasStack()) {
            stack = slot.getStack();

            if (index < 8) {
                if (!mergeItemStack(stack, 8 + 9, inventorySlots.size(), false)) {
                    return ItemStack.EMPTY;
                }
            } else if (!mergeItemStack(stack, 0, 8, false)) {
                return mergeItemStackToSpecimen(stack, 8, 8 + 9);
            }

            if (stack.getCount() == 0) {
                slot.putStack(ItemStack.EMPTY);
            } else {
                slot.onSlotChanged();
            }
        }

        return stack;
    }
```
Assume that the `mergeItemStack` call in `if (!mergeItemStack(stack, 8 + 9, inventorySlots.size(), false))` returns true. In that case, the code will fall back to the `if (stack.getCount() == 0)` check and call `slot.putStack(ItemStack.EMPTY)`.

The `putStack` call calls `ItemStackHandler#setStackInSlot` which does this:

```java
    @Override
    public void setStackInSlot(int slot, @Nonnull ItemStack stack)
    {
        validateSlotIndex(slot);
        if (ItemStack.areItemStacksEqual(this.stacks.get(slot), stack))
            return;
        this.stacks.set(slot, stack);
        onContentsChanged(slot);
    }
```

What happens there is that the `ItemStack.areItemStacksEqual(this.stacks.get(slot), stack)` check returns true, which short-circuits the method and doesn't change anything.

Why is this? Both `this.stacks.get(slot)` and `stack` are empty stacks, which evaluates to true:

```java
    public static boolean areItemStacksEqual(ItemStack stackA, ItemStack stackB)
    {
        return stackA.isEmpty() && stackB.isEmpty() ? true : (!stackA.isEmpty() && !stackB.isEmpty() ? stackA.isItemStackEqual(stackB) : false);
    }
```

You might wonder why they are both empty stacks: that is because the `mergeItemStack` call modifies the stack to be empty. But, **`mergeItemStack` never notifies the inventory about this as it calls `splitStack` and _modifies_ the original stack to be empty**.

So I don't know if this is a bug / unwanted behavior, or if I should change my code.

**Comment by raoulvdberge** [comment]
After a bit of discussion in IRC, we think that the best course of action is to remove the check. Some arguments for it:

```
<Player> more like the empty stack handling being awful ;)
<Player> i'd say the test in setStackInSlot has to go
<Player> it's faulty due to lack of proper "before" reference
<Player> and vanilla apparently maintains the semantics that it's always at least a change notification from splitstack's implementation apparently
```

**Comment by mezz** [comment]
Sounds good. Please make a PR, and if it solves the issue and doesn't cause problems in other places we can merge it.

**Comment by mezz** [comment]
@raoulvdberge is this still an issue?

**Comment by raoulvdberge** [comment]
Not sure... I think I added a workaround for this, but I can't check now.

**Comment by Echo343** [comment]
I'm using Forge 1.12.2-14.23.0.2517 and it is still a problem in that version.  As a work around, I just extended ItemStackHandler and overloaded the method which seems to solve the immediate issue.  Glad I found this ticket; I've been trying to find this fix for days.

**Comment by mezz** [comment]
I'd be willing to help out with a simple fix for this in Forge if you are interested in creating a Pull Request for it.

**Comment by Echo343** [comment]
I'll take you up on that, but it will probably be a few weeks before I get around to updating my current mod to the latest forge.  When I do, I'll create the pull request for this with the fix.

I think the difficult part will be the analysis to make sure the fix doesn't break anything else.  Is there a suite of unit tests to run or an area of the code I should look at?  Perhaps, I'll create the pull request and then ask those questions.
