### ISSUE TITLE
[request] [1.11] uv map should #repeat texure beyond tex  size

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3467]
say i have an element that is 32 x 5 x 8 and i wanna put oak planks texture on it

the 5 and 8 sides work fine but the 32 faces will show only 16 then the rest 16 will be randomly glitched textures picked from memory whatever is nearby (sometimes grass, sometimes fire is random)

would be nice if textures would repeat forever so you can make any length element form any texture

or at least a feature for forge spec 2 blockstate/model . some kind of "repeat" property

**Comment by williewillus** [comment]
All textures are combined into a large texture sheet at runtime. So obviously running out of bounds will give you your neighbors. this is a fundamental property of the texture sheet. 

why do you need this "repeating" thing?

**Comment by ghost** [comment]
@williewillus  so you could build longer / larger elements out of smaller textures without having to create filler blocks because your element is bigger than tex size . Reduces model complexity. It might be worth especially if it's a smaller change.

**Comment by ghost** [comment]
OK I understand the benefit / worth is debatable so I'll leave it to you guys   to decide.  You guys know better.  Is just a thought I had when I was making my own model  and I wanted to share it .

**Comment by HenryLoenwind** [comment]
That is not really possible. OpenGL will automatically wrap the texture if there's an overflow, but that will be the complete texture sheet. To manually wrap the texture, the quad would have to be split to give gl new texture coordinates. So the result for the GPU will be the same, one quad per texture repetition.

**Comment by RANKSHANK** [comment]
Actually it is possible to constrain the texels to repeat a particular region in the UV using GLSL. 

However the performance impact is trumped by the quad batching.

I was beating my head against the wall on this exact issue with tiling from the sheet for a while trying to see if I could get the glint texture to work when it is stitched on. The shader calls were worse off than the texture state changes :P

**Comment by LexManos** [comment]
Do you have a example model/screenshots/etc for this. This sounds like a re-work of how models are defined, which means it will not happen. And no, we're not introducing shaders for this.
However, i'd still be interested in seeing what you're talking about.
As a possible solution is it not possible to simple have a second face in the model that has the same texture?

**Comment by ghost** [comment]
@LexManos seems like a big change TBH. I thought it may be a much more simpler change. Maybe is ultimately not worth the effort. I just make it out of small parts.

**Comment by RANKSHANK** [comment]
@LexManos if that was directed at me I don't have anything relating to it as I was messing with the concept around a year ago now. The only proof on concepts I found were white papers on the matter, and the usage of the GLSL calls required Fragment shaders so it wasn't a tangible solution for forge.
