### ISSUE TITLE
Syncing ItemStack capabilities data to client on Dedicated servers

### ISSUE THREAD

**Issue by P3pp3rF1y** [MinecraftForge/MinecraftForge#3483]
ItemStack capabilities as it stands don't sync to client and the reasoning behind that as I was told was to keep them working the same way as they do for player and tile entity caps and any cap data can be synced by custom packets.

However after dealing with these for a pretty long time there's a fundamental difference between the two categories. Player/Tile entity instances stick around for a very long time and have very well defined events when they get created so it's easy to sync caps then. 
ItemStack instances on the other hand tend to be destroyed/created and majority of these instance creations are for itemstacks that actually haven't changed.

Following are packets that trigger new ItemStack creation/recreation on client which doesn't include cap data (and thus effectively deletes cap data on client) and actions that can trigger them. Most of these affect not only stacks being changed in some way.
SPacketSetSlot
	- Switching items in hands (just equipment slots)
	- Shift right clicking armor into slot (just equipment slots)
	- Non player Inventory/container open
	- Itemstack with capNBT moved in non player inventory

SpacketWindowsItems
	- Non player inventory/container open 
	- Itemstack with capNBT moved in non player inventory
	- Shift right clicking armor into slot (just equipment slots)

SPacketEntityEquipment
	- Shift right clicking armor into slot (just affected slots)
Switching items in hands (just affected slots)

To keep up with these packets deleting cap data developer can send their own sync packet in onUpdate, but because these can happen any time that means syncing capability data every tick. Also when stacks are in inventories the only way to sync cap data is to have a listener listen to any container being open and changes being made to it, scan it for existence of the itemstack and send separate packet in that case. However this one is even worse as that could possibly mean in larger packs many mods having their listeners listen to container changes and each one of them scanning the full inventory separately.

So I would like to yet again propose that we implement a way for itemstack capabilities to be synced to client with ItemStack data itself. #3099 included syncing of all of the caps which I feel was unnecessary and should be a developer's choice what to sync if anything. Initial thoughts on the implementation are a new interface that developer's could choose to implement that would include method for serialization/deserialization of cap data.

Before digging more into this and creating a test mod, do others feel like we should have a way to get these to sync automatically with ItemStack data? And if so any other thoughts on how this should be implemented?

**Comment by liach** [comment]
Syncing decreases performance and is not compatible with vanilla, I guess.

**Comment by HenryLoenwind** [comment]
It may be enough to give the capabilities the chance to add their data to the normal nbt each time that nbt is serialized (and a chance to read the nbt when it is set). Maybe set aside a sub-tag that is "reserved" for capabilities. That way each cap can choose what data is synced, if it needs syncing at all.

Many cap impls already work that way---they save their data in the stack's nbt all the time and don't hold it in the cap object. However, I do understand that people prefer to keep data in the cap's fields and not read them from nbt all the time. For those, getting a callback to store their data for syncing would make sense.

One might also question if it was the right decision to store cap data in separate nbt anyway. It's not as if it was hard to avoid collisions in the main nbt...

**Comment by P3pp3rF1y** [comment]
I would say that very large part of the cap data we don't need synced to client with itemstacks - example being all the slots in item handlers as those get synced separately when the container gets open (in most cases). 

So i can understand why the thought was that these should be server only.

I am not so keen on an idea of reserving a slot for these in nbt as if you updated that it would cause the app to sync the full itemstack data and recreate it on client. I know for a fact that this was causing me issues for some items that have hold right click functionality that changed the charge in nbt - the items either stopped being used even though user was still holding right click which was the better case or they in some cases continued being used even after released right click in some cases for a very long time (some quite odd behavior which I attribute to the previous instance of the itemstack somehow surviving behind the scenes because it was referred to somewhere in the client code). 
If you use caps data you don't have this issue (well after the #3283 gets applied) because the changes to cap data don't trigger recreation of itemstacks on client and you can quite easily sync just the cap changes to the client separately without itemstack being recreated.

**Comment by HenryLoenwind** [comment]
@P3pp3rF1y look up Item.shouldCauseReequipAnimation() and Item.shouldCauseBlockBreakReset and the use of the ".".

**Comment by P3pp3rF1y** [comment]
I know shouldCauseReequipAnimation and use it in quite a few places and guess that blockbreak one is the same for left click. But as far as i can see this is only used for rendering. Are you saying that this can cause the issue I had previously with item interrupting use or continuing even after user stops holding right click?

Not sure what you mean by use of "."?
