### ISSUE TITLE
[1.11] Getting kicked from non-LAN singleplayer twices freezes the game

### ISSUE THREAD

**Issue by Gamebuster19901** [MinecraftForge/MinecraftForge#3488]
If you get kicked from a non-LAN singleplayer game twice, the game freezes. You can get kicked form singleplayer by spamming chat or sending illegal characters in chat.

This does not occur in 1.11 Vanilla.

**Comment by mezz** [comment]
Have you tried with the latest Forge version? cpw made a recent change https://github.com/MinecraftForge/MinecraftForge/commit/45aa74454beb8f6f7e8bfa95bc006c0190451f4a that seems related to this issue.

**Comment by Gamebuster19901** [comment]
Sorry with the late response, I'll try later today.

**Comment by Gamebuster19901** [comment]
This issue no longer occurs, it has been fixed.
