### ISSUE TITLE
@Mod.depencies Documentation

### ISSUE THREAD

**Issue by TechnicianLP** [MinecraftForge/MinecraftForge#3490]
This Field in the @Mod-Annotation refers to the Modloader-Priorities String to which i could not find any information. It would be great if the javadoc could be updated to containe the syntax.

**Comment by mezz** [comment]
I agree, I remember thinking the documentation for that was hard to find when I first went looking for it too.

**Comment by ExE-Boss** [comment]
[NOVA](https://github.com/NOVA-Team/NOVA-Core) has it’s dependencies format very well documented, but I’m not entirely sure if Minecraft Forge uses the same format. (The NOVA format is documented in NOVA’s javadoc [here](https://github.com/NOVA-Team/NOVA-Core/blob/master/src/main/java/nova/core/loader/Mod.java))

**Comment by mezz** [comment]
It's not the same format,

**Comment by Drullkus** [comment]
I would appreciate information on this as well. ^^

**Comment by marvin-roesch** [comment]
Adressed in 75433345ba2b9f5aff0b10c25c592a13b7c962cc, so this can be closed :P

**Comment by TechnicianLP** [comment]
Thanks

**Comment by Drullkus** [comment]
Excellent! I appreciate the closure @mezz ^^
