### ISSUE TITLE
Joining non forge server may yield empty world/empty chunk in some cases

### ISSUE THREAD

**Issue by Shevchik** [MinecraftForge/MinecraftForge#3492]
Caused by BlockStateContainer

When reading a chunk section with > 8 bitsPerBlock from network (13 for vanilla global palette) client uses client bitsPerBlock value instead of network one which results in inability to properly read block data from BitArray

```java
    private void setBits(int bitsIn)
    {
        if (bitsIn != this.bits)
        {
            this.bits = bitsIn;

            if (this.bits <= 4)
            {
                this.bits = 4;
                this.palette = new BlockStatePaletteLinear(this.bits, this);
            }
            else if (this.bits <= 8)
            {
                this.palette = new BlockStatePaletteHashMap(this.bits, this);
            }
            else
            {
                this.palette = REGISTRY_BASED_PALETTE;
                this.bits = MathHelper.log2DeBruijn(Block.BLOCK_STATE_IDS.size());  <-- here is the issue, it should use network one, at least for reading block data
            }

            this.palette.idFor(AIR_BLOCK_STATE);
            this.storage = new BitArray(this.bits, 4096);
        }
    }
```

To reproduce that set all blocks with their states in single column on non forge server, install mods that add many blocks (so bitsPerBlock becomes > 13) and join the server, chunk will be empty

**Comment by Shevchik** [comment]
https://ss.myftb.de/yhFsWy2g.png 
Left - forge, Right - vanilla.

**Comment by mezz** [comment]
Thanks for the report! Very interesting.
Do you think you could make a PR to fix it and show a before/after/vanilla picture?

**Comment by Shevchik** [comment]
That is not easy, due to Palette controling BitArray resize. It will require to always use HashPalette (until the client maximum bitsPerBlock reached) but that decreases performance. But most of the time HashPalette is used anyway (because all blockstates in a column usually fit in 8 bits), so i can try to do this, but still...

**Comment by LexManos** [comment]
Do you have a world save to test with this?
The fix is rather simple but i'd like a test case to make sure it works.

**Comment by dogboy21** [comment]
I can provide the world we tested this in tomorrow

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/daf21e4dcf246cfa15c362800effc5dc787ab777 Should fix it.

**Comment by dogboy21** [comment]
![](https://ss.myftb.de/MGrhxyKK.png)
Top left - Old forge
Top right - Vanilla
Bottom - New forge

Works perfectly! We tested the problem in [this](https://ss.myftb.de/uSyNyxWY.zip) world

**Comment by mezz** [comment]
Good catch. That's a really strange bug.
I wonder if it was the cause of the mostly-missing chunk at BTM 2016. There were lots of mod booths stacked on top of each other pretty densely, and one of the chunks always seemed to be messed up and the booths had to move out of it.
