### ISSUE TITLE
[1.11] IItemhandler still relies on 0-sized itemStacks

### ISSUE THREAD

**Issue by HenryLoenwind** [MinecraftForge/MinecraftForge#3493]
The functionality of getStackInSlot() to inform the caller about slots that are empty but only accept a certain type of item doesn't work anymore because it relies on itemStacks with 0-size, which are not legal itemStacks anymore.

The javadoc for the rest of IItemHandler still instructs the user to return/expect null, but those methods are now annotated @Nonnull. This is a simple doc-out-of-date error.

**Comment by mezz** [comment]
The javadoc has been updated recently, since we can no longer use 0-size itemstacks or null.
