### ISSUE TITLE
[1.11] SlotItemHandler doesn't override Slot#getSlotStackLimit

### ISSUE THREAD

**Issue by raoulvdberge** [MinecraftForge/MinecraftForge#3497]
`SlotItemHandler` needs to override `getSlotStackLimit` and return the `IItemHandler`'s slot limit. At the moment, when not overriding, it falls back to the dummy `IInventory` slot stack limit.

This is needed for correct shift clicking functionality in `mergeItemStack` for example (shift clicking a stack of 64 items to a slot that has a max slot size of 1 (as defined in `IItemHandler#getSlotLimit`) will dump the whole stack of 64 items in there because the dummy `IInventory` doesn't specify the slot stack limit represented by the `IItemHandler`)

**Comment by loordgek** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/2793#issuecomment-250823473
and the respond https://github.com/MinecraftForge/MinecraftForge/pull/2793#issuecomment-260150709
dont know why @williewillus did not do that

**Comment by raoulvdberge** [comment]
@williewillus probably thought you were talking about `Slot#getItemStackLimit`, while in fact, `Slot#getSlotStackLimit` is a different method.
