### ISSUE TITLE
Anything that extends ItemBlockSpecial doesn't have a block to item conversion

### ISSUE THREAD

**Issue by rguy96** [MinecraftForge/MinecraftForge#3505]
Although there is an ItemBlockSpecial#getBlock in ~~1.11~~ 1.10 now, there is no way to convert a Block to its respective ItemBlockSpecial instance.

For example, whenever a Flower Pot block is converted into an item, it doesn't return an item when there is obviously an item for a Flower Pot. 

This is the same for String, Reeds, Cake, Bed, Repeater, Brewing Stand, Cauldron, and Comparators. All of which should have a block to item mapping.

**Comment by raoulvdberge** [comment]
ItemBlockSpecial#getBlock isn't in 1.11 yet, only on 1.10

**Comment by rguy96** [comment]
Oh, didn't see that

**Comment by LexManos** [comment]
And this is why I didn't want to go along this route. Vanilla does not nativly assign this association. So the vanilla mechanics that utilize this map do not work.
ItemBlockSpecial is for items that DO NOT want any of this special block treatment.
So we will not be adding it.
