### ISSUE TITLE
[1.11] UpdateAnvilEvent.setCost() doesn't change the final cost

### ISSUE THREAD

**Issue by The-Fireplace** [MinecraftForge/MinecraftForge#3510]
When I use AnvilUpdateEvent.setCost(), the cost updates for the event, but the final cost of the repair doesn't get changed.
I tested with the following code:
`@SubscribeEvent
    public void anvilUpdate(AnvilUpdateEvent event){
        System.out.println(event.getCost());
        event.setCost(1);
        System.out.println(event.getCost());`
Which printed:
> 15
1

However, the repair still costs 16 levels, as if I never changed the cost.

**Comment by bs2609** [comment]
See #2969

**Comment by mezz** [comment]
Closing as a duplicate.
For anyone interested, please make a PR.
