### ISSUE TITLE
ASM transformer broken in 1.11?

### ISSUE THREAD

**Issue by Sedridor** [MinecraftForge/MinecraftForge#3511]
I'm trying to transform **net.minecraft.client.renderer.RenderGlobal**, but that class (and many others) never gets sent to the transformer. I then checked the log to find that only about 170 classes get sent before it just stops.
Oddly, this issue doesn't appear in the dev environment, it only appears when running the compiled mod in the actual minecraft.

http://pastebin.com/3dZxSVJ0

**Comment by LexManos** [comment]
Don't make coremods.

**Comment by LatvianModder** [comment]
@Sedridor put your _at.cfg in /src/main/resources/META-INF/ folder. I had a similar issue
