### ISSUE TITLE
[1.11] Deprecated IModGuiFactory.RuntimeOptionGuiHandler class

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#3512]
It said will be removed in 1.11.

https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/client/IModGuiFactory.java#L145-L188

https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/client/IModGuiFactory.java#L71-L94

**Comment by bs2609** [comment]
This can be closed now. (commit 9a09ff68aac457d4297355bd9cb30286af92ec05)
