### ISSUE TITLE
I forget... (decompiling Minecraft)

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3523]
I forget - how to decompile Minecraft with Forge? I early did it for implement High DPI, but now I forget how I did it, and decompiled Minecraft. Please, remind, how to decompile MInecraft, and use with Idea? 

Also, I forget how to run compiled Minecraft with Forge?

**Comment by ghost** [comment]
Also, in MDK found bug. ExampleMod not compiling with Intelij. 

```
C:\Users\acterhd\Documents\MDK\src\main\java\com\example\examplemod\ExampleMod.java
Error:(3, 26) java: package net.minecraft.init does not exist
Error:(4, 37) java: package net.minecraftforge.fml.common does not exist
Error:(5, 41) java: package net.minecraftforge.fml.common.Mod does not exist
Error:(6, 43) java: package net.minecraftforge.fml.common.event does not exist
Error:(8, 2) java: cannot find symbol
  symbol: class Mod
Error:(15, 22) java: cannot find symbol
  symbol:   class FMLInitializationEvent
  location: class com.example.examplemod.ExampleMod
Error:(14, 6) java: cannot find symbol
  symbol:   class EventHandler
  location: class com.example.examplemod.ExampleMod
Error:(18, 51) java: package Blocks does not exist
```

**Comment by Mathe172** [comment]
If you'd care to read the [README.md](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/README.md), you'd have seen that there is a video that explains everything nicely ;)
