### ISSUE TITLE
Tile entities not always sent to client on chunkloading

### ISSUE THREAD

**Issue by LemADEC** [MinecraftForge/MinecraftForge#3524]
As of 1.10.2-12.18.3.2185, when client receive chunk, tile entities updates are not sent until another event forces a refresh.
This is a regression from the observed behavior on 1.7.10-10.13.4.1492.
This was observed while porting my mod Forcefield projector between both version.

From reviewing the code, it seems we're missing a Forge patch related to clumpingThreshold :

On 1.7.10 in net.minecraft.server.management.PlayerManager.PlayerInstance.sendChunkUpdate()
https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/patches/minecraft/net/minecraft/server/management/PlayerManager.java.patch
We're sending selected tile entity updates when above the threshold (and apparently re-sending the updated ones?)
```
        public void sendChunkUpdate()
        {
            if (this.numberOfTilesToUpdate != 0)
            {
                int i;
                int j;
                int k;

                if (this.numberOfTilesToUpdate == 1)
                {
                    i = this.chunkLocation.chunkXPos * 16 + (this.locationOfBlockChange[0] >> 12 & 15);
                    j = this.locationOfBlockChange[0] & 255;
                    k = this.chunkLocation.chunkZPos * 16 + (this.locationOfBlockChange[0] >> 8 & 15);
                    this.sendToAllPlayersWatchingChunk(new S23PacketBlockChange(i, j, k, PlayerManager.this.theWorldServer));

                    if (PlayerManager.this.theWorldServer.getBlock(i, j, k).hasTileEntity(PlayerManager.this.theWorldServer.getBlockMetadata(i, j, k)))
                    {
                        this.sendTileToAllPlayersWatchingChunk(PlayerManager.this.theWorldServer.getTileEntity(i, j, k));
                    }
                }
                else
                {
                    int l;

                    if (this.numberOfTilesToUpdate >= net.minecraftforge.common.ForgeModContainer.clumpingThreshold)
                    {
                        i = this.chunkLocation.chunkXPos * 16;
                        j = this.chunkLocation.chunkZPos * 16;
                        this.sendToAllPlayersWatchingChunk(new S21PacketChunkData(PlayerManager.this.theWorldServer.getChunkFromChunkCoords(this.chunkLocation.chunkXPos, this.chunkLocation.chunkZPos), false, this.flagsYAreasToUpdate));

                        // Forge: Grabs ALL tile entities is costly on a modded server, only send needed ones
                        for (k = 0; false && k < 16; ++k)
                        {
                            if ((this.flagsYAreasToUpdate & 1 << k) != 0)
                            {
                                l = k << 4;
                                List list = PlayerManager.this.theWorldServer.func_147486_a(i, l, j, i + 16, l + 16, j + 16);

                                for (int i1 = 0; i1 < list.size(); ++i1)
                                {
                                    this.sendTileToAllPlayersWatchingChunk((TileEntity)list.get(i1));
                                }
                            }
                        }
                    }
                    else
                    {
                        this.sendToAllPlayersWatchingChunk(new S22PacketMultiBlockChange(this.numberOfTilesToUpdate, this.locationOfBlockChange, PlayerManager.this.theWorldServer.getChunkFromChunkCoords(this.chunkLocation.chunkXPos, this.chunkLocation.chunkZPos)));
                    }

                    { //Forge: Send only the tile entities that are updated, Adding this brace lets us keep the indent and the patch small
                        WorldServer world = PlayerManager.this.theWorldServer;
                        for (i = 0; i < this.numberOfTilesToUpdate; ++i)
                        {
                            j = this.chunkLocation.chunkXPos * 16 + (this.locationOfBlockChange[i] >> 12 & 15);
                            k = this.locationOfBlockChange[i] & 255;
                            l = this.chunkLocation.chunkZPos * 16 + (this.locationOfBlockChange[i] >> 8 & 15);

                            if (world.getBlock(j, k, l).hasTileEntity(world.getBlockMetadata(j, k, l)))
                            {
                                this.sendTileToAllPlayersWatchingChunk(PlayerManager.this.theWorldServer.getTileEntity(j, k, l));
                            }
                        }
                    }
                }

                this.numberOfTilesToUpdate = 0;
                this.flagsYAreasToUpdate = 0;
            }
        }
```

On 1.10.2 and 1.11.x in net.minecraft.server.management.PlayerChunkMapEntry.update()
https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/patches/minecraft/net/minecraft/server/management/PlayerChunkMapEntry.java.patch
We're not sending any tile entity update when above the threshold
```
On 1.10.2 and 1.11.x in net.minecraft.server.management.PlayerChunkMapEntry.update()
https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/patches/minecraft/net/minecraft/server/management/PlayerChunkMapEntry.java.patch
We're not sending any tile entity update when above the threshold
```
    public void update()
    {
        if (this.sentToPlayers && this.chunk != null)
        {
            if (this.changes != 0)
            {
                if (this.changes == 1)
                {
                    int i = (this.changedBlocks[0] >> 12 & 15) + this.pos.chunkXPos * 16;
                    int j = this.changedBlocks[0] & 255;
                    int k = (this.changedBlocks[0] >> 8 & 15) + this.pos.chunkZPos * 16;
                    BlockPos blockpos = new BlockPos(i, j, k);
                    this.sendPacket(new SPacketBlockChange(this.playerChunkMap.getWorldServer(), blockpos));
                    net.minecraft.block.state.IBlockState state = this.playerChunkMap.getWorldServer().getBlockState(blockpos);

                    if (state.getBlock().hasTileEntity(state))
                    {
                        this.sendBlockEntity(this.playerChunkMap.getWorldServer().getTileEntity(blockpos));
                    }
                }
                else if (this.changes >= net.minecraftforge.common.ForgeModContainer.clumpingThreshold)
                {
                    this.sendPacket(new SPacketChunkData(this.chunk, this.changedSectionFilter));
                    //TODO: FDix Mojang's fuckup to modded by combining all TE data into the chunk data packet... seriously... packet size explosion!
                }
                else
                {
                    this.sendPacket(new SPacketMultiBlockChange(this.changes, this.changedBlocks, this.chunk));
                //} Keep this in the else until we figure out a fix for mojang's derpitude on the data packet so we don't double send crap.
                //{// Forge: Send only the tile entities that are updated, Adding this brace lets us keep the indent and the patch small
                    for (int l = 0; l < this.changes; ++l)
                    {
                        int i1 = (this.changedBlocks[l] >> 12 & 15) + this.pos.chunkXPos * 16;
                        int j1 = this.changedBlocks[l] & 255;
                        int k1 = (this.changedBlocks[l] >> 8 & 15) + this.pos.chunkZPos * 16;
                        BlockPos blockpos1 = new BlockPos(i1, j1, k1);
                        net.minecraft.block.state.IBlockState state = this.playerChunkMap.getWorldServer().getBlockState(blockpos1);

                        if (state.getBlock().hasTileEntity(state))
                        {
                            this.sendBlockEntity(this.playerChunkMap.getWorldServer().getTileEntity(blockpos1));
                        }
                    }
                }

                this.changes = 0;
                this.changedSectionFilter = 0;
            }
        }
    }
```

**Comment by williewillus** [comment]
I don't quite understand what's wrong with the code as it is right now.
`SPacketChunkData` *includes tile entities* as described by `changedSectionFilter`

**Comment by LemADEC** [comment]
When testing, I've noted that my tile entities aren't updated when there's a lot of them in the same chunk.
Specifically, when my forcefield blocks are projected in the same chunk as the projector.

**Comment by williewillus** [comment]
it would be better if you could produce a minimal test mod that reproduces this in as little as possible, because the code looks right on paper.

**Comment by LemADEC** [comment]
My understanding of `SPacketChunkData` on 1.10.2 is that tile entities are only sent when `changedSectionFilter` is 65535. The missing forge patch is when `changedSectionFilter` only covers a subset of the chunk.

**Comment by williewillus** [comment]
In SPacketChunkData constructor:
```
            if (this.doChunkLoad() || (p_i47124_2_ & 1 << i) != 0)
            {
                NBTTagCompound nbttagcompound = tileentity.getUpdateTag();
                this.tileEntityTags.add(nbttagcompound);
            }
```

second part of the if statement is checking the changed section filter and adding the TE if it's part of the filter.

**Comment by LemADEC** [comment]
Yeah, it doesn't really add up since my issue is on chunkloading. There's something else interfering.

**Comment by LemADEC** [comment]
It's not the number of tiles entities, it's the chunkloading itself sending 'empty' NBT data to client.
This is because `SPacketChunkData` is using `TileEntity::getUpdateTag()` while `sendBlockEntity` uses `TileEntity::getUpdatePacket()`.
That's a change in behavior since 1.7.10 that mods need to adapt too: getDescriptionPacket() -> getUpdateTag().

**Comment by williewillus** [comment]
@LemADEC this may help https://gist.github.com/williewillus/7945c4959b1142ece9828706b527c5a4
