### ISSUE TITLE
Forge's Blockstate : subblocks will remove the Translucent model from multi-layer (aka base cannot be translucent)

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3535]
For example this code will work fine except when north = true then the Translucent layer gets removed. I tried making the base translucent but it seems base must be Solid for some reason.

```
{
    "forge_marker": 1,
    "defaults": {
        "textures": {
            "particle": "blocks/stone"
        },
        "model": "forge:multi-layer",
        "custom": {
            "base": "technorcery:deposits_vat#base",
            "Solid": "technorcery:deposits_vat#base",
            "Translucent": "technorcery:deposits_vat#water"
        }
    },
    "variants": {
        "normal": [{}],
        "north": {
            "true": {
                "submodel": {
                    "spout_north": {
                        "model": "technorcery:deposits_vat_spout"
                    }
                }
            },
            "false": {}
        },
        "base": [{ "model": "technorcery:deposits_vat" }], //this here can not be set to Translucent is simply invisible
        "water": [{ "model": "technorcery:deposits_vat_water" }] //this here only works when north = false
    }
}
```

The block also has this set to render on both layers.

```
    @Override
    public boolean canRenderInLayer(IBlockState state, BlockRenderLayer layer)
    {
	return layer == BlockRenderLayer.TRANSLUCENT || layer == BlockRenderLayer.SOLID;
    }

```

The best way to fix this (if a fix is desired) is to allow the base to be Translucent. Currently it does not seem to be possible. It simply doesn't show up. 

Since a subblock is always Solid, a bool property that is always on can serve as a Solid base and the default base would be allowed to be Translucent. This will allow models to be both multipart and multi-layer at the same time.

**Comment by ghost** [comment]
The code above in 1.11 

As you can see whenever a subblock is on, it will remove any transparency from the block. 

![rec1](https://cloud.githubusercontent.com/assets/6987027/21129685/4587b3c8-c0d1-11e6-8601-a83ef2160ca2.gif)


What is interesting is if you keep TRANSLUCENT  ONLY then it water does not vanish when a subblock is true. My assumption is any subblock on the solid layer will kill the translucent model unless solid is turned off in which case only translucent shows up.

**Comment by williewillus** [comment]
I'm not sure what your issue is describing. The `base` model isn't solid, *nor* is it translucent. It's used to provide things like camera transforms. Its quads don't actually render.

**Comment by KnightMiner** [comment]
If you have property enums, normal shouldn't be used, instead there should be multiple property enums. Water specifically should be something like the cauldron uses (a list of properties) rather than a flat "water" string.

**Comment by williewillus** [comment]
I think this issue should be moved to forums or irc unless it can be reduced to a case that clearly demonstrates a forge bug
