### ISSUE TITLE
Working on porting a mod from 1.7.10 to 1.11 net.minecraftforge.fluids.FluidContainerRegistry missing

### ISSUE THREAD

**Issue by veronicaalange** [MinecraftForge/MinecraftForge#3536]
I understand the fluid classes have been undergoing change. But am i just missing the replacement functions for net.minecraftforge.fluids.FluidContainerRegistry?

**Comment by RANKSHANK** [comment]
I'm fairly certain they were removed in favor of capabilities.

**Comment by TehNut** [comment]
This is not the place for modding support. Use the forums.

**Comment by mezz** [comment]
The modder support forum is here: http://www.minecraftforge.net/forum/index.php?board=73.0
