### ISSUE TITLE
[meta] Add guidelines on creating issues

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#3538]
The readme could do with a section on what is worth making an issue here for, and what's better addressed elsewhere, along with links to appropriate forum sections/docs/etc.

**Comment by Heufneutje** [comment]
If something like that were to be done, it would be better to use GitHub's actual [issue templates](https://github.com/blog/2111-issue-and-pull-request-templates).

**Comment by HenryLoenwind** [comment]
We have an issue template in our repo since they exist and found that it is mostly useless. People either ignore them completely, or just fill in what they want anyway. And if we tell them that they should post their suggestions somewhere else, they tend to get very enraged if they just created a github account for that.

**Comment by Alpvax** [comment]
If people ignore the template it is likely that they would ignore the readme section, so the problem would not be solved. I would suggest having a template with large text about what is inappropriate for the github and where to look instead. Actual issues would just delete said message, but it is displayed when you want to create an issue. However, adding a support section to the README (above PRs) telling people where to go for crashes, suggestions and development help couldn't hurt.
I would rather people get angry and go elsewhere if it means people like mezz have less junk to sift through.

**Comment by mezz** [comment]
I have had reasonable success with using issue templates for JEI.
It doesn't fix everything, but it does somewhat cut down on the number of bad issues and it helps out people who are actually concerned with creating good issues.

**Comment by bs2609** [comment]
Think this is reasonably addressed by #4323.
