### ISSUE TITLE
GuiContainer button duplicates

### ISSUE THREAD

**Issue by tomevoll** [MinecraftForge/MinecraftForge#3542]
initGui() in GuiContainer called on window resize as it should, but buttonlist is never cleared causing duplicates.

Forge 1.10.2-12.18.3.2185

**Comment by RANKSHANK** [comment]
buttonList is cleared in GuiScreen::setWorldAndResolution

**Comment by tomevoll** [comment]
What i got was old buttons stuck in the old position and scale while new buttons added in initGui() on resize was drawn in the correct scale and position after the resize, adding more buttons every time i resize the window.

Closing it as it is not Forge doing it, caused by another mod, i should have checked that first.
