### ISSUE TITLE
isBookEnchantable returning false throws NPE

### ISSUE THREAD

**Issue by zliebersbach** [MinecraftForge/MinecraftForge#3548]
I have an [Item](https://github.com/plutomc/core/blob/master/src/main/java/com/plutomc/core/common/items/ItemHandStone.java#L66) which is enchantable. However, as the commented out code shows, I only want certain enchantments to be able to be applied to the item.

If I return false from `isBookEnchantable` in my Item class, I get a NPE. It is introduced in [this line](https://github.com/MinecraftForge/MinecraftForge/blob/babe0c2d539cd99c27233ea42962d5df0333d87e/patches/minecraft/net/minecraft/inventory/ContainerRepair.java.patch#L48) from ContainerRepair.java, because when `itemstack1` is referenced later in the code it is `null`.

Seems like a bug, but workarounds are welcome.

**Comment by bs2609** [comment]
Should be changed to use `ItemStack.field_190927_a` instead of `null`.

What version of Minecraft/Forge are you using here?

**Comment by Chocohead** [comment]
It'll be a 1.11 only thing as that's when itemstacks changed to never be null, and since the line is unchanged from when cpw ported the patch over, all the Forge versions for 1.11 will crash from it.

**Comment by zliebersbach** [comment]
@bs2609 I'm using Forge 1.11-13.19.1.2189.

@Chocohead so does this mean we need to implement @bs2609's fix?

**Comment by liach** [comment]
Someone can just send a pull for this. @mezz Please add a tag.

**Comment by bs2609** [comment]
Ok, made a PR for this.

**Comment by bs2609** [comment]
This can be closed now. (a718077a2e17d17534a6975377ccfcf584838913)
