### ISSUE TITLE
[1.11] Update IShearable

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#3556]
`onSheared` should be `@Nonnull` and ought to return a `NonNullList<ItemStack>`. The javadocs need updating too.

Making this an issue, not a PR, as this has compatibility implications, and I'd like to know peoples' thoughts.

**Comment by LexManos** [comment]
Not a fan of that, Nothing wrong with things returning null. Just handle it correctly.

**Comment by mezz** [comment]
I think it would be nice to have everything consistent, but it's not worth breaking compatibility.

**Comment by bs2609** [comment]
As it stands, violating either would likely cause a `NullPointerException`, it's not handled by `ItemShears`.

**Comment by mezz** [comment]
In that case we should probably mark it `@Nonnull` and fix the documentation.
