### ISSUE TITLE
Custom EntitySelector predicates are broken [1.11+]

### ISSUE THREAD

**Issue by Mathe172** [MinecraftForge/MinecraftForge#3558]
Minecraft 1.11 introduced a change in the handling of unknown selector arguments:
```JAVA
//Snippet from EntitySelector.getArgumentMap
if (!IS_VALID_ARGUMENT.apply(name))
{
    throw new CommandException("commands.generic.selector_argument", new Object[] {s});
}
```
`IS_VALID_ARGUMENT.apply` does the following:
```JAVA
 return name != null && (EntitySelector.VALID_ARGUMENTS.contains(name) || name.length() > "score_".length() && name.startsWith("score_"));
```

This means that the current event based solution for handling custom predicates (introduced by #3356) should no longer work, as a list of known parameter names has to exist beforehand.

One possible solution would be register a parameter name together with a `Predicate<Entity>`-factory that creates the predicate.

**Comment by williewillus** [comment]
@maxanier have you looked at this?

**Comment by maxanier** [comment]
I haven't dealt with 1.11 very much yet, but I can take a look tomorrow

**Comment by maxanier** [comment]
Ok, after looking into this, there seem to be two solutions:

1. Just make it possible to register a valid argument either at startup or in a static context.
    Thereby modders just have to register the argument strings they expect once and that's it.
This would be a simple fix, but modders should not forget to register the argument strings.
2. The Predicate Factory way suggested by @Mathe172 sounds reasonable too, **but it would break compatibility with mods that already use the existing system.**
Mods would then have to register their Predicate factory (during init or similar) together with a list of expected argument strings. The factory would then be used during entity selector gathering in the same way the event is currently used. It would receive the argument map together with other relevant parameters and return the Predicate(s).

So which way to go?

**Comment by Mathe172** [comment]
I think it would be very strange to register a string and then listen to an event - if you already register the name, why not the rest? As current implementations are already broken (they at least have to add a line to register the name), it shouldn't be that much harder to rework the code into a Factory - you just return the Predicate instead of adding it.

Also, the factory forces you to register the name, the other approach allows you to forget it.

**Comment by maxanier** [comment]
Yes, solution 1 requires two independent actions which can easily be forgotten.
So what about using 2 and deprecating the event. It won't be thrown anymore, but existent mods (if there are any) remain binary compatible.
