### ISSUE TITLE
[1.11] No LivingAttackEvent for EntityPlayer on client-side

### ISSUE THREAD

**Issue by CreativeMD** [MinecraftForge/MinecraftForge#3560]
As i found out recently, LivingAttackEvent will not be called on client side for EntityPlayer.

Eventually i found out why ...
EntityPlayerSP.class:
`public boolean attackEntityFrom(DamageSource source, float amount){
return false;
}`

I'm sure there is a reason for it, but it seems like somebody forgot to implement calling this event.

**Comment by williewillus** [comment]
because attackEntityFrom is not usually (and shouldn't be) called from client side

**Comment by CreativeMD** [comment]
It is called, for all entities including players, all entities except of players will raise an LivingAttackEvent, this doesn't look intentional, and it's something different from the versions before.

**Comment by williewillus** [comment]
not the event, the method itself. it's not called clientside by vanilla.

**Comment by CreativeMD** [comment]
Yes, but Forge does it to raise a LivingAttackEvent.

**Comment by williewillus** [comment]
show me a place where attackEntityFrom is called intentionally from the client side :p 
my point is: just because the patch is on both sides doesn't mean the method is ever called on both sides,
I'll check on this.

**Comment by williewillus** [comment]
your statement still makes no sense to me, but it does seem to be called by vanilla. I stand corrected.

**Comment by CreativeMD** [comment]
I'm using this event since 1.8 without any issues for Enhanced Visuals (https://minecraft.curseforge.com/projects/enhancedvisuals). In 1.11 this event is not working anymore, i don't know what was orginally intented with attackEntityFrom or whatever, but they somehow excluded players to raise it.
