### ISSUE TITLE
Remove NeighborNotifyEvent in 1.12

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#3566]
The NeighborNotifyEvent added here is no longer needed: https://github.com/MinecraftForge/MinecraftForge/pull/1721
There are block update events in 1.11 that make it unnecessary, and I talked with Sponge and they don't need it any more either.

**Comment by bs2609** [comment]
Should this be marked as deprecated in 1.11?

**Comment by mezz** [comment]
Talked to @bloodmc and this is needed after all for protection mods.
