### ISSUE TITLE
Block#getDrops should return a NonNullList

### ISSUE THREAD

**Issue by raoulvdberge** [MinecraftForge/MinecraftForge#3567]
I'm already getting bug reports of people putting null in the list.

**Comment by bs2609** [comment]
This probably also applies to `captureDrops()`

**Comment by LexManos** [comment]
As with the other one 'issue' about this, I don't particularily care. The system has never specified if it allows nulls or not and so you should support nulls.
I'd rather the non-binary breaking change of not caring, vs forcing everyone else to update.

**Comment by raoulvdberge** [comment]
Ideally, this would be for 1.12.

**Comment by mezz** [comment]
Closed in 1.12, see https://github.com/MinecraftForge/MinecraftForge/pull/3778
