### ISSUE TITLE
[1.11.2] Add iron nugget to ore dictionary

### ISSUE THREAD

**Issue by modmuss50** [MinecraftForge/MinecraftForge#3570]
In 1.11.2 mojang added an iron nugget, this should be added to the ore dictionary.

Let me know if you need a PR, but I feel like as its a one line change its not worth me setting up forge.

**Comment by williewillus** [comment]
can be closed

**Comment by aequasi** [comment]
Whats with the name on this? Why not IRON_NUGGET
