### ISSUE TITLE
[1.11.2] @Nullable missing for creative tabs

### ISSUE THREAD

**Issue by HenryLoenwind** [MinecraftForge/MinecraftForge#3575]
@Nullable is missing for:

* net.minecraft.block.Block.setCreativeTab(CreativeTabs) (the parameter)
* net.minecraft.block.Block.getCreativeTabToDisplayOn()
* net.minecraft.item.ItemBlock.getCreativeTab()

All vanilla methods calling these are doing null checks and have valid logic in the null case (item will not be listed on any creative tab).

**Comment by HenryLoenwind** [comment]
More missing @Nullables:

* net.minecraft.entity.player.EntityPlayer.addStat(@Nullable StatBase)
* net.minecraft.entity.player.EntityPlayer.addStat(@Nullable StatBase, int)
* net.minecraft.entity.player.EntityPlayer.takeStat(@Nullable StatBase)
* TileEntityChest.adjacentChest...
* net.minecraft.client.Minecraft.player
* net.minecraft.entity.EntityList.getClass(ResourceLocation)
* net.minecraft.client.Minecraft.world

**Comment by williewillus** [comment]
https://github.com/mezz/MinecraftAnnotations might be a better tool/place

**Comment by HenryLoenwind** [comment]
Not really. I just discovered that newer Eclipse versions ignore external annotations if the code already is annotated...

Also, there's no standard for external annotations, so you need different ones for each IDE.
