### ISSUE TITLE
[1.11.2] (13.20.0.2201) no rain sounds

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3588]
Seems like rain is now silent. Not sure if is a Forge issue or MC issue. It happened after I updated from 1.11 to 1.11.2

also I am wondering if any other ambient sound like cave sounds are also affected. Haven't tested this.

**Comment by CoderAtParadise** [comment]
Just tested and the rain has sounds on both vanilla and forge(clean install)

**Comment by ghost** [comment]
@CoderAtParadise  I m trying to clean update but I can no longer test run it now gives me invoke0 error with the same setup

**Comment by ghost** [comment]
@CoderAtParadise Finally got it working did a clean install problem fixed nvm false alarm
