### ISSUE TITLE
AttachCapabilitiesEvent.Item migrated incorrectly

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3603]
Offending line: `AttachCapabilitiesEvent.Item extends AttachCapabilitiesEvent<Item>`

The legacy event is still the one that is fired by Forge. It was retrofitted to use the new generic event system, except the type was wrongly coded.
It should have been AttachCapabilitiesEvent\<Item**Stack**\>.

The problem is that whoever uses the new event `AttachCapabilitiesEvent<Item>` cannot see the ItemStack. They can only see the Item via `getObject` (since that is the type parameter).

They have to use the legacy event `AttachCapabilitiesEvent.Item` instead if they want to see the ItemStack.

**Comment by williewillus** [comment]
looking to make a PR for this, what do you guys think should be the way we resolve this?

It's a pretty big issue preventing people from getting off the old event if you need the stack (many use cases do).

If we just change it back to `extends ...<ItemStack>` it'll break mods that have already started using the wrong signature `AttachCapabilitiesEvent<Item>`

**Comment by diesieben07** [comment]
> If we just change it back to `extends ...<ItemStack>` it'll break mods that have already started using the wrong signature `AttachCapabilitiesEvent<Item>`

Not if we fire _both_.

**Comment by Alpvax** [comment]
Fire both and deprecate the Item version, remove it next major update?

**Comment by bs2609** [comment]
This can be closed now. (bf154730bdc76a3ca299ec334f99c6727ea43da6)
