### ISSUE TITLE
[1.11.2] `Biome#getSpawnableList` returns `EmptyList` for non-vanilla `EnumCreatureType` values

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#3605]
When `Biome#getSpawnableList` is called with a non-vanilla `EnumCreatureType` value, it returns an `EmptyList`.

When a method like `EntityRegistry.addSpawn` tries to add a value to this list, the game crashes with an `UnsupportedOperationException` thrown from `AbstractList#add`:

```
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at net.minecraftforge.fml.common.registry.EntityRegistry.addSpawn(EntityRegistry.java:251)
	at com.github.choonster.forgeenumcreaturetypetestmod.ForgeEnumCreatureTypeTestMod.preInit(ForgeEnumCreatureTypeTestMod.java:24)
```

[Test mod](https://github.com/Choonster/ForgeEnumCreatureTypeTestMod)
[FML log](https://github.com/Choonster/ForgeEnumCreatureTypeTestMod/blob/4368b0a29afa475be8fd2918d19daf4ec969d8e2/fml-client-latest.log)

Originally reported by TheMattyBoy [here](http://www.minecraftforge.net/forum/index.php?topic=44456.0).

A potential solution to this problem is to have an `ArrayListMultimap<EnumCreatureType, Biome.SpawnListEntry>` field in `Biome` to provide the spawn lists for non-vanilla `EnumCreatureType`s. I can create a PR for this if requested.

**Comment by mezz** [comment]
That makes sense, and sounds like a good solution.
Personally I think extending enums like this is pretty questionable, but Forge supports it elsewhere so it should probably do it here too.
