### ISSUE TITLE
Crash from ContainerRepair patches

### ISSUE THREAD

**Issue by Chocohead** [MinecraftForge/MinecraftForge#3606]
https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/patches/minecraft/net/minecraft/inventory/ContainerRepair.java.patch#L39 is the line causing the trouble.

On 1.10.x and below:
If the input item returns false for `Item#isBookEnchantable(ItemStack, ItemStack)` but is attempted to be renamed in an anvil with an item in the other slot, the output is set to null before it is renamed, causing the following NPE crash: http://pastebin.com/MerPLMWh

On 1.11.x:
In the same situation happens, although it would anyway as the output is set to null instead of `ItemStack.EMPTY`.

**Comment by diesieben07** [comment]
#3548 #3553

**Comment by Chocohead** [comment]
Oh yeah, silly me
