### ISSUE TITLE
[1.10.2]PlaceEvent cancel do not effect chets and trapped chests 

### ISSUE THREAD

**Issue by stefan-weiss** [MinecraftForge/MinecraftForge#3608]
If PlaceEvent would be cancled it have no effect on chests or trapped chests and they would be placed. I do not think that this is idented. If I be wrong sorry for this issue

**Comment by stefan-weiss** [comment]
Hey it would be nice if someone can answer whether it is a bug or I did something wrong in my code. But I can not find any bug in my code and I tried it now for days.

**Comment by williewillus** [comment]
Post a sample mod that reproduces the issue

**Comment by stefan-weiss** [comment]
Here is your reproduction of the issue https://github.com/stefan-weiss/forgeChestIssue. I canceled the PlaceEvent and I can place chest but no other things. I think it is a bug that you can place chests.

**Comment by stefan-weiss** [comment]
Is the sample enough or you need any more information about the issue? I need my mod really quick for my public server.

**Comment by AEnterprise** [comment]
@stefan-weiss if you want this fixed soon you can look into it yourself and submit a PR

if you realy need a fix soon you can temp work arround it in your mod by checking for the use/click event and cancel that if it's a chest and it would place
