### ISSUE TITLE
Sounds hilariously wrong for common minecraft things

### ISSUE THREAD

**Issue by kashike** [MinecraftForge/MinecraftForge#3613]
https://github.com/SpongePowered/SpongeCommon/issues/1058 appears to be a bug with Forge, most likely due to the registry changes.
> Lightning flash? That's the sound of a shovel breaking!
Zombie spawned and caught fire? Oh no, sounds like a villager in drowning...

As far as I'm aware, you can almost always reproduce it - a Forge client is not required to reproduce, although I'm not sure if a Forge client fixes the issue yet.

**Comment by liach** [comment]
This issue's description is not helpful. You should mention this at least:
https://github.com/SpongePowered/SpongeCommon/issues/1058#issuecomment-271086444

> Definitely reproducable but it only happens with spongeforge. spongevailla works fine. It also happens with just forge installed so i think it is a forge bug and has nothing to do with sponge.

And to mention that this is probably caused by inconsistency between registries.

**Comment by kashike** [comment]
As far as I know this has been fixed with the registry rewrite.
