### ISSUE TITLE
[Feature Request] Cancelable ItemCraftedEvent

### ISSUE THREAD

**Issue by disconsented** [MinecraftForge/MinecraftForge#3616]
Being able to cancel ItemCraftedEvent would be nice for conditional crafting, especially since #3017 killed off the ability to directly poll for changes (ticker handlers still work for this).

**Comment by shadowfacts** [comment]
You don't need a cancelable event, use a custom IRecipe implementation.

**Comment by williewillus** [comment]
@shadowfacts not if you don't control the recipe in question

**Comment by disconsented** [comment]
Doesn't work as its not conditional, I want this to be able to stop some people crafting x some of the time not all people crafting x some of the time.

**Comment by diesieben07** [comment]
You can get the player in `IRecipe` using [some tricks](http://www.minecraftforge.net/forum/index.php?topic=23133.0). And you can wrap other people's recipes in your own `IRecipe` implementation, just adding the condition.

**Comment by disconsented** [comment]
Sorry I wasn't clear, I am interested in the result not whats in the crafting grid which (at least without reflection) that doesn't provide. Which is why being able to cancel the crafting event would be useful for me as I only need to verify once unlike previously it was with every OpenContainerEvent/hooking into a tickhandler.
