### ISSUE TITLE
{Request} Adding Mods To This ForgeCraft S3

### ISSUE THREAD

**Issue by MiscMC** [MinecraftForge/MinecraftForge#3618]
Lets us make a Orgainzation called ForgeCraft3 for the minecraft

**Comment by williewillus** [comment]
This repo is for issues with the modding framework Forge itself.
Community "issues" should go elsewhere

**Comment by liach** [comment]
What is forgecraft? Isn't it dead already?

**Comment by MiscMC** [comment]
no it's not dead.
