### ISSUE TITLE
Shears taking two durability rather than one.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#3624]
When using shears such as the ones in vanilla, and most modded shears, it will take two durability for breaking a block rather than one. This is because the `damageItem` method is added by the forge patch, within `onBlockStartBreak`, however vanilla already accounts for this in `onBlockDestroyed`. A simple way to reproduce this issue is to spawn in a tree and shears, turn on debug mode (f3 + h) and look at the durability. Breaking grass will consume one durability, while breaking leaves or any other block which implements IShearable will consume two durability. 

Edit: This issue effects 1.11 and 1.10.2.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/403eda184abb405779a39df2614f2fe992c66d36
