### ISSUE TITLE
Armor does not respect Attribute modifiers

### ISSUE THREAD

**Issue by CoderAtParadise** [MinecraftForge/MinecraftForge#3629]
[Initial Report](http://www.minecraftforge.net/forum/index.php?topic=44666.0)
The ISpecialArmor changes does not respect armor attribute modifiers

**Comment by mezz** [comment]
Is this a duplicate of https://github.com/MinecraftForge/MinecraftForge/issues/3095 ?

**Comment by CoderAtParadise** [comment]
It is and is still present it seems

**Comment by mezz** [comment]
Ok, thanks.
