### ISSUE TITLE
[Feature Request] Determine missing dependencies summarily

### ISSUE THREAD

**Issue by khionu** [MinecraftForge/MinecraftForge#3631]
It would decrease the redundancy in modpack creation if Forge check all mods' dependencies for anything missing prior to throwing, so all dependency issues can be handled after a single launch, rather than having to start up Minecraft once per missing dependency.

**Comment by GirafiStudios** [comment]
Can be closed, since https://github.com/MinecraftForge/MinecraftForge/pull/3636 got merged.
