### ISSUE TITLE
FMLCommonHandler.instance().effectiveSide returns Side.CLIENT on Linux server

### ISSUE THREAD

**Issue by sirsavary** [MinecraftForge/MinecraftForge#3633]
Problematic line: https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/fml/common/FMLCommonHandler.java#L205

Everything works as intended on my Windows machine but my Linux server has differently named Netty threads:
![Threads Screenshot](http://i.imgur.com/M9PyfeE.png)

Fix should be as simple as adding another clause to the if statement in FMLCommonHandler.

**Comment by diesieben07** [comment]
We really just need to get rid of this silly effective side thing... 😆

**Comment by sirsavary** [comment]
Agreed, tracking this down was not fun. Had to attach a debugger to my production server.

**Comment by diesieben07** [comment]
I am curious, what problem does this cause?

**Comment by bs2609** [comment]
Might as well just do `getName().contains("Server")` if we're going to stick with "thread analysis"

**Comment by sirsavary** [comment]
@diesieben07 caused some clientside-only code to run on the server, resulting in a NoSuchMethodFound exception.

**Comment by diesieben07** [comment]
Yeah, the mod doing that needs to be fixed. getEffectiveSide is for debugging and logging purposes only. It is not a reliable check.

**Comment by sirsavary** [comment]
What's the best way to go about ensuring that code is running on a side in a situation where you can't do something like world.isRemote?

**Comment by diesieben07** [comment]
Read and understand this: http://mcforge.readthedocs.io/en/latest/concepts/sides/

**Comment by williewillus** [comment]
Unfortunately, not much besides world.isRemote and  "thread analysis" can be used to establish logical side

**Comment by bs2609** [comment]
See the issue I raised: #3279

**Comment by sirsavary** [comment]
I understand the concept of physical and logical sides. I've already fixed the problem in my code, it was a method called by some networking stuff so it was trivial to figure out what side I was on.

My question is if I have no way to figure out what logical side I'm on (no world object, no networking, etc) is there anything other than getEffectiveSide I can use?

**Comment by diesieben07** [comment]
No, there isn't. Although I have found whenever you find yourself in that situation then either you aren't actually (you do have a world or something like it) or your design is flawed anyways.
But this is something for the forums, not a github issue.

**Comment by raoulvdberge** [comment]
It's not because something is not the recommended way to solve something that it should stay broken. Either fix it, or remove it.

**Comment by diesieben07** [comment]
I didn't say this wasn't a valid issue. This should definitely be fixed.
I would prefer getEffectiveSide to disappear, but I know that's not possible.

**Comment by sirsavary** [comment]
Right, was just curious and wanted to know in case it ever comes up. 

In regards to the actual issue, I'm more than happy to submit a PR that adds the extra clause.

**Comment by Alpvax** [comment]
How are proxies handled? Could you check if your Mod.proxy was a ClientProxy or does that have to do with physical side?

**Comment by bs2609** [comment]
Proxies are to do with physical sides, they work like `getSide()`, not `getEffectiveSide()`
