### ISSUE TITLE
Piston Bugs. Rotation. Block Dissapearing 1.11.2

### ISSUE THREAD

**Issue by ThomasAunvik** [MinecraftForge/MinecraftForge#3634]
EnderIO: 1.10.2-3.1.161
EnderCore: 0.4.1.64-beta
Minecraft: 1.10.2
Forge:12.18.3.2209

**Issue Description:**

Difficult to explain, but see the images to understand it. Better watch the videos too.

When i extend the piston then wrench it, it gets a bug that it wrenches the block, means it rotates it. but when you replace the redstone signal it will return to normal.

But, if your piston is rotated to a block and you update the redstone signal on and off again, you will see that the block disapears. It will do to any kind of block. Even bedrock. (only normal piston)

**What happens:**
Images:
http://i.imgur.com/N30YZYC.png
http://i.imgur.com/HEOz7we.png
http://i.imgur.com/4fno5hN.png

Videos:
https://vimeo.com/199477886
https://vimeo.com/199477948

How to break bedrock or any block:
https://vimeo.com/199478691

**What you expected to happen:**

To not do a glitch, and to not destroy a block.

**Steps to reproduce:**

1.Place down piston (any kind)
2.Place a redstone block at the corner of piston. meaning 1 block to the side, then 1 block up.
3.Wrench the extended piston.

Tried to post it on EnderIO but it got rejected and said this was forges problem:
https://github.com/SleepyTrousers/EnderIO/issues/3993#issue-200827096

Quote from the github said by HenryLoenwind:
Quote
Please report this to Forge, we are just asking the block to rotate itself, the rotation code for vanilla blocks is added by Forge.

---------------------------------------------------

This also works for 1.11.2, i tested it with a mod called Chisels & Bits. And using and item called Wooden Wrench, it can do the same thing.

Note: what my conclusion is that it works with anything that can rotate a block. as HenryLoenwind said, that it is only asking a block to rotate.

**Info:**
Forge Version: forge-13.20.0.2216
MCVersion: 1.11.2

Mod: Chisels & Bits by AlgorithmX2
Mod Version: 13.9

**Comment by williewillus** [comment]
It seems we should just be disallowing rotation of piston bases when they're extended. one method patch to BlockPistonBase

**Comment by mezz** [comment]
Last I checked, wrenches can also rotate double chests in a strange way. It would be worth looking into that as well.

**Comment by mezz** [comment]
Also, I appreciate the effort you went to in reporting this, but in the future please try to keep it more concise.

Something like this is fine:

>Using a wrench on an extended piston breaks it. 
I reported this to EnderIO [here](https://github.com/SleepyTrousers/EnderIO/issues/3993#issue-200827096) and they said it was caused by the rotation code added by Forge.
![](http://i.imgur.com/N30YZYC.png)

**Comment by ThomasAunvik** [comment]
Thanks for the reply.
And the chest bug. does it seem like this? https://vimeo.com/199754566

**Comment by mezz** [comment]
Yeah, exactly.

**Comment by ThomasAunvik** [comment]
Did a small test:
![GIF TEST](http://i.imgur.com/anrpIQ9.gif)

**Comment by quat1024** [comment]
Headless pistons erasing the block in front of them when depowered is a vanilla bug, and not related to this bug, by the way. You can make headless pistons in vanilla survival, without a wrench, and they still do the same thing.
