### ISSUE TITLE
Coal Block recipe not being replaced

### ISSUE THREAD

**Issue by awebneck** [MinecraftForge/MinecraftForge#3635]
The default MC coal block recipe is not being replaced by the `OreDictionary` as part of its initialization - this causes the server-side recipe to be accounted as requiring 9 coals in *each slot* for a total of 81 coals. While this can be overridden by implementing mods, I wonder if such a replacement doesn't belong in the OreDictionary (similar to the manner in which the recipe for Iron blocks is replaced, whose original MC recipe also implies requiring 9 items in each slot). This issue was discovered by attempting to use the Immersive Engineering 0.10-54 assembler to craft 9 coals into one coal block. However, because it accounts the recipes requiring the quantities as represented, it did not permit this and instead requires 81 total coals in order to form a coal block.

**Comment by liach** [comment]
@awebneck Give a screenshot for prove, at least.

**Comment by awebneck** [comment]
Here we see the recipe retrieved from the `CraftingManager` for a `blockIron`:
<img width="1111" alt="screenshot 2017-01-17 01 49 44" src="https://cloud.githubusercontent.com/assets/153561/22012018/9e8bb716-dc57-11e6-83c1-5aca29180e01.png">
Note the recipe as being an instance of the Forge `ShapedOreRecipe` class, and requiring only a single item per slot.
Now here is the recipe for `blockCoal`:
<img width="1103" alt="screenshot 2017-01-17 01 47 18" src="https://cloud.githubusercontent.com/assets/153561/22012040/cf8c73d2-dc57-11e6-9109-c413102989a8.png">
In this we can see that it's the original Minecraft recipe, and calls for 9 coals in each recipe slot.

While the actual repercussions of this are difficult to show in a static screenshot, I've tried as follows.
First, iron behaving as expected - this is the result of defining the recipe and then placing a full stack of iron into the inventory:
<img width="843" alt="screenshot 2017-01-17 01 51 01" src="https://cloud.githubusercontent.com/assets/153561/22012095/0893b64a-dc58-11e6-8ce3-bdc7babfe78e.png">
Note that the iron blocks form as expected, and the ratio is as expected as well - `6*9+10=64`.
However, when I try the same with coal:
<img width="851" alt="screenshot 2017-01-17 01 51 40" src="https://cloud.githubusercontent.com/assets/153561/22012120/2d6ab2f2-dc58-11e6-8f70-d45001daa978.png">
Nothing - no crafting takes place, and the stack of coal just sits there because it's below the total required coal of 81 according to the recipe. However, when I place two stacks of coal in, we get this:
<img width="848" alt="screenshot 2017-01-17 01 58 08" src="https://cloud.githubusercontent.com/assets/153561/22012179/6a5536ec-dc58-11e6-8fc6-f954b7a52a15.png">
Showing that it is indeed consuming 81 coal (`64*2-47`) but outputting only a single coal block.

Let me know if you need further info!

**Comment by mezz** [comment]
This is related to a vanilla bug that I reported here: https://bugs.mojang.com/browse/MC-103403

**Comment by awebneck** [comment]
@mezz the response to that bug so far does not instill a great deal of hope. :) I can obvs fix with CraftTweaker or otherwise, but was wondering if it might be something that would be better addressed in the meantime by OreDictionary, given that it already overwrites the recipes for blockIron, blockGold, etc.

**Comment by mezz** [comment]
There are blocks for hay and slime as well, and I assume they have the same problem.
We should be able to fix the vanilla bug without too much effort, and without touching the ore dictionary.

**Comment by awebneck** [comment]
Lovely - thanks all!
