### ISSUE TITLE
[Feature Request] Capabilities for Villages

### ISSUE THREAD

**Issue by rguy96** [MinecraftForge/MinecraftForge#3647]
Similar to how capabilities were introduced for worlds, it would also be nice if capabilities were introduced for Villages.

**Comment by williewillus** [comment]
What would you want to use it for ? (having a good use case helps push your point)

**Comment by rguy96** [comment]
Maybe for marking positions for farms or storing UUIDs representing important villagers.

**Comment by mezz** [comment]
PR is here https://github.com/MinecraftForge/MinecraftForge/pull/3648

**Comment by bs2609** [comment]
Can close this as the PR got merged.
