### ISSUE TITLE
Custom Fence Gates Blockstates error

### ISSUE THREAD

**Issue by CJMinecraft01** [MinecraftForge/MinecraftForge#3649]
When trying to create a custom fence gate for my mod I came upon this error where the fence gate renders fine in the inventory but when you place it, it renders incorrectly. To see if I was making an error in my blockstate json file I used the acacia fence gate blockstate to test if it would work. Again it failed to work correctly and I have no clue how to fix this. I believe this may have something to do with the Block Class I used which was a replica of that of the Block Fence gate other than changing the material and map colour to that of the iron material. Please fix this as I am using Forge 1.11.2-13.20.0.2223!

**Comment by diesieben07** [comment]
Please use the forums for tech support. This issue tracker is for issues with Forge itself.

**Comment by CJMinecraft01** [comment]
Oh sorry
