### ISSUE TITLE
[1.11.2] Crash after trying to break a block without a model/blockstate

### ISSUE THREAD

**Issue by sokratis12GR** [MinecraftForge/MinecraftForge#3653]
After registering a block without a model & texture it crashes MC after some seconds of trying to break the block. I've tested it with other blocks without model too, this doesn't happen to blocks with model and/or texture.

**MC Version**: 1.11.2
**Forge Version**: ~~1.11.2-13.20.0.2224~~ this issue still happens on forge every version after that 1.11.2 - 13.20.0.2232
**Client or Server**: Both
**Crashlog**: [Here while in dev environment](https://gist.github.com/anonymous/7ea22300de82b3fd1aa977d1c53ed881) ; 
[Here while using the normal Minecraft evironment](https://gist.github.com/sokratis12GR/cfd561a4f70082bcfba1d109211d3097)

**Comment by Myknakryu** [comment]
<del>Ummm... I think this issue is similar to problems with forge 2223, and 2224 with optifine. Game crashes if you're desperate enough to install optifine. Game only crashes when game is trying to render missing texture or model.</del>
<del>
Minecraft version: 1.11.2
Forge version: 2223 and 2224
</del><del>
Crashlog:
http://pastebin.com/pUrzU1gC
</del>
Fixed in latest preview version of optifine.

**Comment by sokratis12GR** [comment]
Here is a video of how to reproduce it: https://sokratis12gr.com/uploads/98gUBpFg.webm

**Comment by sokratis12GR** [comment]
Here is the code used:
```java
public class TestBlock extends Block {

    public BlockBase() {
        super(material);
        this.setRegistryName("test_block");
        this.setUnlocalizedName(setName("test_block"));
        this.setResistance(10);
        this.setHardness(10);
        GameRegistry.register(this);
        GameRegistry.register(new ItemBlock(this), getRegistryName());
    }

    @SideOnly(Side.CLIENT)
    public void initModel() {
        ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(this), 0, new ModelResourceLocation(getRegistryName(), "inventory"));
    }
}
```

**Comment by HenryLoenwind** [comment]
We had the same crash with conduits that were created with an error texture. It seems the code that creates the breaking overlay uses that (relatively) new additional texture field and crashes if its not set...and it is easy to not set it.
