### ISSUE TITLE
[1.11.2]Milk bucket does not have texture.

### ISSUE THREAD

**Issue by Myknakryu** [MinecraftForge/MinecraftForge#3654]
Minecraft version: 1.11.2
Forge version: 2224

After changing boolean value for replaceVanillaBucketModel in forge.cfg to true milk bucket does not have texture.

Picture:
<a href="http://imgur.com/0HCHhdA"><img src="http://i.imgur.com/0HCHhdA.png" title="source: imgur.com" /></a>

**Comment by Madsthunder** [comment]
Is the fourth loaded mod the ExampleMod?

**Comment by Myknakryu** [comment]
Mod list from mods:
Minecraft
MCP
Forge Mod Loader
Minecraft Forge

**Comment by LexManos** [comment]
@RainWarrior

**Comment by Balketh** [comment]
Issue persists into 2282.

**Comment by bs2609** [comment]
This can be closed now.
