### ISSUE TITLE
SidedInvWrapper forces expensive check to be done needlessly

### ISSUE THREAD

**Issue by HenryLoenwind** [MinecraftForge/MinecraftForge#3658]
When SidedInvWrapper tries to insert an item into an inventory it calls both isItemValidForSlot() and canInsertItem() (in that order!) to check if it can do so.

```
    /**
     * Returns true if automation is allowed to insert the given stack (ignoring stack size) into the given slot.
     */
    boolean isItemValidForSlot(int index, ItemStack stack);

    /**
     * Returns true if automation can insert the given item in the given slot from the given side.
     */
    boolean canInsertItem(int index, ItemStack itemStackIn, EnumFacing direction);
```

The call to isItemValidForSlot() is the more expensive call but is made first. canInsertItem() can do optimizations like checking if the slot already is full that isItemValidForSlot() is not allowed to do (see Javadoc above). Also, isItemValidForSlot() is usually used for the GUI, so short circuiting based on the current content is not wanted there because it would prevent swapping items in the slot with the item on the mouse cursor.

Additionally, both calls must check the same things (see Javadoc above), so even if the item could be inserted that checking code would run twice. If the item then really is inserted that may not be a huge deal, but for machines that do not do their own "stack full" check in there it is potentially repeated quite often.

This came to my attention because Ender IO's SAG Mill in combination with Refined Storage's autocrafting had a hotspot in isItemValidForSlot(). That hotspot is caused by a full "could I accept this item as a replacement for the current one" check that would not have happened for canInsertItem(), which would have rejected the insert very fast based on the fact that the slot already was full.

My recommendation is to either drop the call to isItemValidForSlot() completely, or at least swap the order in which those two methods are called. It might also be helpful to check if the stack that's already in the slot is full, like it is done for it's stackability already.

(Note: Ender IO conduits have been using canInsertItem() alone for sided inventories for as long as I could find in our repo (3+ years) with no ill effects reported.)

(Found in 1.10 but SidedInvWrapper is doing the same in 1.11)

**Comment by Rob5Underscores-zz** [comment]
Any progress on this? This could possibly alleviate numerous causes of lag (from various mods).

Cheers

**Comment by williewillus** [comment]
I think it was in this order because that was the logic originally used by the hopper.
See `TileEntityHopper.canInsertItemInSlot(IInventory inventoryIn, ItemStack stack, int index, EnumFacing side)`

**Comment by bs2609** [comment]
Giving this a bump, as 1.12 is impending, and it might be nice to get at least some improvement into 1.11.
