### ISSUE TITLE
[Feature Request] Have the EULA check happen right after starting a server, instead of after PreInit

### ISSUE THREAD

**Issue by starg09** [MinecraftForge/MinecraftForge#3659]
Well, this is pretty minor... But I think it would be nice for people with older machines, who may forget to add the `eula.txt` before starting their new server for the first time, to be notified about it earlier on, right as the server is started if possible.

On servers with a handful of mods this may not affect much, but when people make a server for modpacks with 150+ mods (as many are nowadays), it may be nice for them not having to wait 5-10 minutes of mods loading only for everything to shutdown due to not changing a `false` to a `true`.

**Comment by raoulvdberge** [comment]
Agreed, this is especially a pain in the devenv when you have a client and server running at the same time.

**Comment by kingdevnl** [comment]
I agree aswell, I had this happening a few times

**Comment by 0xilly** [comment]
This was already asked before https://github.com/MinecraftForge/MinecraftForge/pull/3661#issuecomment-275598282

**Comment by starg09** [comment]
Uhm... If you check the issue/PR numbers you'd notice that pr was made from this issue... Still a needed feature, even if lex prefers to wait for vanilla itself to implement it, or mojang to give permission.

**Comment by Aaron1011** [comment]
If there's still interest, I'd be interested in adding this. As long as we don't remove the existing check, and display exactly the same message, I don't think there should be any legal problems.

**Comment by grum** [comment]
Keep it in somewhere before the server starts and it should be fine.

**Comment by vico93** [comment]
Thanks for allow this @grum !
