### ISSUE TITLE
[1.11.2] Items render backwards in item frames

### ISSUE THREAD

**Issue by Alec-WAM** [MinecraftForge/MinecraftForge#3662]
If you add an item with the default-item Forge Transform it will render backwards in an item frame. I assume this has to do with the FIXED Transform Type.

![2017-01-26_20 14 36](https://cloud.githubusercontent.com/assets/7232670/22358394/70949314-e404-11e6-8afc-2698b8693f29.png)

Notice how the drip is on the left in my hand but on the right in the frame. 
Forge 13.20.0.2223

**Comment by williewillus** [comment]
seems like just a missing case [here](https://github.com/MinecraftForge/MinecraftForge/blob/c545b8ecd4e96107ccf134c8fd89906357d586ad/src/main/java/net/minecraftforge/client/model/ForgeBlockStateV1.java#L548)

vanilla json for reference has 
```
"fixed": {
    "rotation": [ 0, 180, 0 ],
    "scale": [ 1, 1, 1 ]
}
```
which is missing for forge. this seems consistent with the bug described above (rotate 180 around Y mirrors it)
