### ISSUE TITLE
EntityThrowable's onImpact Immediately Called

### ISSUE THREAD

**Issue by codahq** [MinecraftForge/MinecraftForge#3669]
In 1.11.2 if you put a break point in the EntitySnowball's onImpact it is called immediately when the player right clicks the ItemSnowball and then again when the entity again impacts something after the thrower.

What seems to be happening is the EntityThrowable's onUpdate is performing logic to store an ignoreEntity and a grace period in ignoreTime but then never checks either of those before performing a RayTraceResult and calling onImpact.  

The snowball's onImpact method is written in a way that no harm is done.  However, mods that extend and override methods on EntityThrowable are affected. 

This behavior was not present in 1.8.  It has been introduced sometime between then and now.  I also don't know if this is a vanilla bug or a forge bug.  I'm not good at github and figuring out if there was a PR that broke this.  I apologize in advance for that.

**Comment by williewillus** [comment]
this is a vanilla bug

**Comment by williewillus** [comment]
https://bugs.mojang.com/browse/MC-88491

**Comment by codahq** [comment]
It's been around since 1.9. In situations like this did we typically wait for a fix or PR a fix in Forge?

**Comment by williewillus** [comment]
it's always been "if someone cares about it badly enough they make a PR"
Though, I don't know of a good solution so it needs some research, the solutions proposed on the ticket are kind of sketchy.
