### ISSUE TITLE
[Req] getRGBDurabilityForDisplay

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3670]
Request for Item.getRGBDurabilityForDisplay

Instead of directly replicating the vanilla algorithm which checks the stack meta, I request that it just uses the result of `getDurabilityForDisplay`.
It saves modders from having to remember to override both in order to have not-ugly durability bars:

```
@Override
public int getRGBDurabilityForDisplay(ItemStack stack) {
	// vanilla uses (float) ((maxDamage - getDamage) / maxDamage) which is the same as 1 - getDurabilityForDisplay
	return MathHelper.hsvToRGB(Math.max(0.0F, (float) (1 - getDurabilityForDisplay(stack))) / 3.0F, 1.0F, 1.0F);
}
```

p.s. the doc on getDurabilityForDisplay is flipped, it's 1.0 for an empty bar (100% consumed) or 0 for a full bar (0% consumed)

**Comment by mezz** [comment]
Makes perfect sense, why not PR?
