### ISSUE TITLE
ClassPatchManager instance always has a null tempDir -> NPE crash with -Dfml.dumpPatchedClasses=true

### ISSUE THREAD

**Issue by Mysteryem** [MinecraftForge/MinecraftForge#3674]
The `ClassPatchManager` constructor uses the static field `dumpPatched` to determine the value of its instance field `tempDir`.

The bug is that the static field `INSTANCE` is assigned a new instance of `ClassPatchManager` before `dumpPatched` has had a value assigned to it (unassigned boolean fields are false)

New instance creation to be assigned to static field `INSTANCE`: [ClassPatchManager.java#L55](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/fml/common/patcher/ClassPatchManager.java#L55)
Constructor reads static field `dumpPatched` (not yet assigned a value): [ClassPatchManager.java#L67](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/fml/common/patcher/ClassPatchManager.java#L67)
static field `dumpPatched` gets assigned a value: [ClassPatchManager.java#L57](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/fml/common/patcher/ClassPatchManager.java#L57)

This causes a crash later on at [ClassPatchManager.java#L160](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/fml/common/patcher/ClassPatchManager.java#L160) when `tempDir.getAbsolutePath()` is called.

Here's a crash log (no mods, only Forge): https://gist.github.com/Mysteryem/2f95c6134a7796926fd9d1aef2fe66d1

**Comment by LexManos** [comment]
Interesting somehow the fields got moved down, will look at ti later this is a non-important bug that'll be fixed when there is some free time.
