### ISSUE TITLE
ReflectionHelper findMethod extra `E instance` param

### ISSUE THREAD

**Issue by RedRelay** [MinecraftForge/MinecraftForge#3676]
Hi,
In [net.minecraftforge.fml.relauncher.ReflectionHelper](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/fml/relauncher/ReflectionHelper.java)
 
```java
public static <E> Method findMethod(Class<? super E> clazz, E instance, String[] methodNames, Class<?>... methodTypes)
    {
        Exception failed = null;
        for (String methodName : methodNames)
        {
            try
            {
                Method m = clazz.getDeclaredMethod(methodName, methodTypes);
                m.setAccessible(true);
                return m;
            }
            catch (Exception e)
            {
                failed = e;
            }
        }
        throw new UnableToFindMethodException(methodNames, failed);
}
```

We have a never used parameter `E instance`. It seems to be just here for wildcard but is it very usefull ?
This method definition should be enought : 
```java
public static Method findMethod(Class<?> clazz, String[] methodNames, Class<?>... methodTypes)
```

I'm making a generic class for my own reflection and when I use this I don't even know the instance or the instance's class.
I'd like to use MinecraftForge code as possible instead of duplicate.

Should I do a pull request ?
I know you are very restrictive on pull request when it's not a critical bug.
I guess it could be a good enhancement, even if we keep the old method but just mark it with a deprecated annotation for backward compatibility.

**Comment by liach** [comment]
Making a pull for 1.12 would be good. Use `null` for now.

**Comment by RedRelay** [comment]
I can't use null actually :/
`The method findMethod(Class<? super E>, E, String[], Class<?>...) in the type ReflectionHelper is not applicable for the arguments (Class<capture#10-of ?>, null, String[], Class<?>[])`

**Comment by liach** [comment]
Use `(E) null` or `(E) (Object) null` then.

**Comment by RedRelay** [comment]
I can't my wildcard are not defined.
I've duplicate code atm

**Comment by liach** [comment]
cast `Class<capture#10-of ?>` to `Class` then.

**Comment by williewillus** [comment]
This is becoming a help post, move it to forums or irc

**Comment by liach** [comment]
@williewillus It is a bug that in [`findMethod`](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/fml/relauncher/ReflectionHelper.java#L174) method, the parameter `instance` is not used.

**Comment by williewillus** [comment]
Yes but the last 4 comments have been "help with compile error"

**Comment by mezz** [comment]
I'm writing a PR that happens to fix this issue as well.

**Comment by bs2609** [comment]
@mezz, can this be closed now?

**Comment by mezz** [comment]
Yes thanks
