### ISSUE TITLE
FML network targetpoint for tracking players

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3677]
This was mentioned some time ago but I couldn't find a formal ticket for it so here goes.

This is a request for a FML outbound target "all around point loaded"

The current "all around" target does not consider if the player is tracking the chunk containing the target. A common pitfall example is a TE that sends a packet to everyone within say 64 of it's position to update something. Except if the player/server's view distance is set at say 2 chunks, the TE is not tracked/loaded clientside and the client packet handler npe's trying to find said TE.

There's lots of other usecases of course, but we should have a "send to everyone who has this position loaded" target, optionally constrained by distance.

**Comment by diesieben07** [comment]
I would also find a "everyone who has this entity loaded" useful. More useful than the chunk version even, because the entity version has no built-in equivalent, where as with a TE you _could_ just use the normal TE syncing.

**Comment by mezz** [comment]
For networking in Forestry I send packets to players watching the chunk like this:

```java
public <P extends IForestryPacketClient> void sendNetworkPacket(P packet, BlockPos pos, World world) {
	if (!(world instanceof WorldServer)) {
		return;
	}

	WorldServer worldServer = (WorldServer) world;
	PlayerChunkMap playerManager = worldServer.getPlayerChunkMap();

	int chunkX = pos.getX() >> 4;
	int chunkZ = pos.getZ() >> 4;

	for (Object playerObj : world.playerEntities) {
		if (playerObj instanceof EntityPlayerMP) {
			EntityPlayerMP player = (EntityPlayerMP) playerObj;

			if (playerManager.isPlayerWatchingChunk(player, chunkX, chunkZ)) {
				sendToPlayer(packet, player);
			}
		}
	}
}
```

I don't think it would be too hard to implement as an FML target if you started with the code from `ALLAROUNDPOINT`. 
I think the big question is if it should replace the existing `ALLAROUNDPOINT` implementation or be its own thing.

**Comment by williewillus** [comment]
I was playing around with a prototype and came up with almost exactly that, but yea was thinking about if we want to update ALLAROUNDPOINT or just make another one.

@cpw thoughts?

**Comment by bs2609** [comment]
Posting to dispel stalebot as there's a PR now.
