### ISSUE TITLE
Read and write blockstates from NBT

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3687]
It would be extremely helpful to add methods for reading and writing blockstates to NBT. Currently it's a hassle to write all of their properties to a NBT compound and it would be much easier to have a built in method for it.

**Comment by williewillus** [comment]
What? All states are identifiable by their state ID via a pallette.
Look at how vanilla saves chunks itself.

**Comment by Niko-sk2x** [comment]
The only place where it could be useful is configuration, to avoid using metadata there. And I think vanilla has methods for that in code of some commands.

**Comment by LexManos** [comment]
This is not the place for these types of discussions, use the forums.
You can easily serialize to human readable names using toString() but Willie is correct the proper way to do it is registry name + metadata.

**Comment by HenryLoenwind** [comment]
Those methods are in ```net.minecraft.nbt.NBTUtil```.
