### ISSUE TITLE
Some files contain two licence headers

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/MinecraftForge#3692]
There 13 files which contain the old license information ("This software is provided under the terms of the Minecraft Forge Public License v1.0.") and the LGPL 2.1 license headers. Should the old license header be removed?
The following files are affected:
Property.java
ConfigElement.java
ConfigCategory.java
Configuration.java
ISpecialArmor.java
ForgeChunkManager.java
ForgeModContainer.java
AchievementPage.java
ForgeVersion.java
IRenderContextHandler.java
MinecraftForgeClient.java
ForgeGuiFactory.java

**Comment by bs2609** [comment]
There are also some files which are missing any license info header:
*  `client/event`
    *  `RenderSpecificHandEvent.java`
    *  `RenderTooltipEvent.java`
*  `common/util/WorldCapabilityData.java`
*  `energy`
    *  `CapabilityEnergy.java`
    *  `EnergyStorage.java`
    *  `IEnergyStorage.java`
*  `event/entity/ThrowableImpactEvent.java`
*  `event/entity/living/LootingLevelEvent.java`
*  `fml/common/eventhandler/IContextSetter.java`

**Comment by ichttt** [comment]
Solved by #4051
