### ISSUE TITLE
[Feature request] Event for EntityTick

### ISSUE THREAD

**Issue by Da-Technomancer** [MinecraftForge/MinecraftForge#3694]
Currently, there is an event for EntityLivingUpdate. However, there is no similar event for all entities. The base entity class contains an onUpdate method, so why can't there be an event for onUpdate with any instance of Entity (not just EntityLivingBase)? Otherwise, the only way to, for example cancel a non-living entity update (like an arrow) is with ASM.

**Comment by diesieben07** [comment]
Every entity can be stopped from updating using `EntityEvent.CanUpdate`.

**Comment by Da-Technomancer** [comment]
This wouldn't be for stopping them from updating permanently, this would be for cancelling specific updates (For example, stopping an entity from ticking while touching cactus, or whatever).

**Comment by diesieben07** [comment]
I just noticed that event fires only when an entity would _not_ update, so never mind anyways.

**Comment by LexManos** [comment]
IF this was going to be re-worked it would be into a 'canUpdate' flag on the entity and simply READ every tick.
There is no reason to fire a expensive event every tick for every entity.

**Comment by Da-Technomancer** [comment]
That could work as long as the flag is public and non-final.
