### ISSUE TITLE
No output on new launcher 

### ISSUE THREAD

**Issue by jredfox** [MinecraftForge/MinecraftForge#3696]
No output on new launcher  Latest version and all versions below.

Image:
http://imgur.com/N9v5BA8

This is due to mc changing their .json file output system so there is currently no output. I don't want to have to use another launcher to mod this or past versions of  mc. Please patch the .json files each version for only the latest. Thanks... or at least reasonable (1.7.10, 1.8-1.11.2)

**Comment by Drakoflame** [comment]
this needs to be addressed ASAP, I can't figure out how to get the old, working, better, fixed, improved, nice launcher that everyone was used to and loved, so I'm suck with the shitty new one that is an ungodly eye sore every time I have to open up minecraft. I can't close it fast enough, and the output log doesn't even work, so I don't know why my game keeps freezing when trying to open up a new world. I don't know what mod is causing the issue, so I can't report it to the mod author so they can fix it...
I know this is ranty and annoying and rude, but this is a serious issue that needs to be addressed.

**Comment by LexManos** [comment]
Yell at Dinnerbone, not on us. We can take a look but in all my tests logging to the text file works fine.

**Comment by LexManos** [comment]
Found it, literally nothing we can do about it for older versions. Yelling at dinnerbone about to it see if we can get them to fix the launcher.

**Comment by jredfox** [comment]
Thanks maybe they can make it so older versions have output again. The issue is reported here: https://bugs.mojang.com/browse/MCL-5830

**Comment by bs2609** [comment]
The old launcher is still available, go to:
https://minecraft.net/en-us/download/alternative
and pick the 'older version' download.

**Comment by LexManos** [comment]
It seems they are fiddeling around with it, the latest.log now contains the FML output. Tho not with any mod names so its a little hard to read. I've asked for them to make the inheritance of the logging config a opt-in setting, as we have no way of updating older versions. Best we can do is wait and see what happens.

**Comment by maxashen** [comment]
I'm seeing log output with the 4/10 launcher build (2.0.847) and Forge 13.20.0.2228, although we should add `-Dlog4j.skipJansi=true` to the launcher profile's JVM arguments since the launcher does its own colors.

**Comment by jredfox** [comment]
Hey does that argument work with older versions of forge in 1.7.10-1.8.9?

**Comment by Darkhax** [comment]
This is still an issue. I noticed that some of the FMLLog entries are not being included with the `latest.log` file. The missing info includes mod sorting data, the bar step messages, and several other things which can be useful when tracking down issues.

**Comment by jredfox** [comment]
If it works for the newer versions they could back port their .json files so the launcher has output. I realized that nobody is fixing this so I am still using the old launcher with a shortcut to the .jar file.

**No the launcher I am using isn't the alternative one that's really old 2012 I am using 2016 launcher**

**Comment by jredfox** [comment]
@LexManos tell me how it goes thanks.

**Comment by jredfox** [comment]
I just tried this on a fresh launch in 1.7.10 with forge it's working I can't let you know how it is with newer versions. If no one has any further issues I am closing this
