### ISSUE TITLE
[1.11.2] Can't open chest with a slab over it.

### ISSUE THREAD

**Issue by AfterRebelion** [MinecraftForge/MinecraftForge#3698]
If you have a bottomside slab over a chest, it won't open, but it opens if the slab is upperside.
This is against Vanilla behaviour, as there it will open regardless of the position of the slab.

**Comment by PrincessOfEvil** [comment]
One of Forge "fixes".

2017-02-13 21:19 GMT+05:00 AfterRebelion <notifications@github.com>:

**Comment by williewillus** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/2820

**Comment by AfterRebelion** [comment]
Oh, I did search the issue tracker for the issue, not the Pull Requests. EDIT: WTF!? I am very drunk or idk, as I thought it opened in the pull request section.
That is really unfortunate, as I will have to make something complicated to recreate a build in a vanilla server so I can play with forge clientside mods.

**Comment by liach** [comment]
Should this feature be moved to ForgeUtils? According to MinecraftForge/ForgeUtils#1,
> All the actual gameplay/features that couldn't go into Forge because Forge doesn't edit gameplay.

**Comment by AfterRebelion** [comment]
As Lex said it is a vanilla bug.. is there a entry for this in the mojang bugtracker?

**Comment by williewillus** [comment]
it's not an actual "bug" because there isn't a method in vanilla to say "is the bottom solid", there's only a method for "is the top solid". forge adds sided solidness, introducing this situation.

**Comment by Levertion** [comment]
You might consider it a bug, and I understand that there don't seem to be any good ways to easily solve this, but I thought that this was relevant:

https://bugs.mojang.com/browse/MC-378

Crucially:  
>Works as intended

**Comment by atimholt** [comment]
Why is this closed? It cannot be sanely argued that this is intended behavior.

**Comment by williewillus** [comment]
this has been addressed in 1.12 build 2569 and above. it respects vanilla behaviour now. bug mezz if you want a backport
