### ISSUE TITLE
Using Item.hasCustomEntity and Item.createEntity causes StackOverflowError.

### ISSUE THREAD

**Issue by palaster** [MinecraftForge/MinecraftForge#3699]
[fml-client.log](http://pastebin.com/gbfMPmr3)

If an Item return true on Item.hasCustomEntity and doesn't return a null entity for Item.createEntity. When you go to create the new EntityItem(i.e. Throwing the new item of your inventory) it causes the EntityJoinWorldEvent to go into an infinite loop and crash with StackOverflowError, because ForgeInternalHandler.onEntityJoinWorld doesn't have an exit case.

**Comment by LexManos** [comment]
This is not a bug in Forge, this is a issue in the mod who is stupid enough to say it has a custom entity and then NOT use a custom entity. It is a contract violation to return true from hasCustomEntity and return a default instance of EntityItem, note Subclasses are fine, we're talking specifically Vanilla EntityItem.
