### ISSUE TITLE
Too long Item names dont work

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3706]
If a Item name is to long, the rendering in gui stops working.
I made an Block and called it "wireless_redstone_receiver". In the world everything worked but in the inventory the item was flat and pink&black. After renaming everything to "wr_receiver" this inventory bug was suddenly fixed.

**Comment by williewillus** [comment]
I highly doubt that's the cause, recheck your registrations and jsons (this is a forum/irc kind of thing unless you can point to a specific spot in forge or vanilla that causes it)

**Comment by mcenderdragon** [comment]
I will try to make a test mod that reproduces this.
