### ISSUE TITLE
IShearable javadoc ItemStack arg

### ISSUE THREAD

**Issue by GotoLink** [MinecraftForge/MinecraftForge#3707]
The doc in IShearable:

> @param item The itemstack that is being used, Possible to be null

Except that argument is annotated with Nonnull, as you'd except from the usage of ItemStack through the game.
Would recommend "empty" or ItemStack.EMPTY, for replacement.

Also at onSheared:

> @return A ArrayList containing all items from this shearing. Possible to be null.
Null case isn't handled by ItemShears, so it shouldn't be recommended.

**Comment by bs2609** [comment]
Also see #3556
