### ISSUE TITLE
Not able to use trowing items - Help me discover the problem

### ISSUE THREAD

**Issue by Stann0x** [MinecraftForge/MinecraftForge#3708]
I can use a bow - or a pistol from reliquary -, a snowball or any kind of projectile items ONLY when block range is reacheable. If I try to use a trowable item aiming away from a next block, nothing happens.
The server log give me this:
(I think SpongeForge is triggering the wrong event.)
(I am using several mods)

22:22:28 [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@738f72eb:
22:22:28 [Server thread/ERROR] [FML]: Index: 8 Listeners:
22:22:28 [Server thread/ERROR] [FML]: 0: HIGHEST
22:22:28 [Server thread/ERROR] [FML]: 1: ASM: com.attributestudios.wolfarmor.event.WolfArmorPlayerEventHandler@23d957d onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:28 [Server thread/ERROR] [FML]: 2: HIGH
22:22:28 [Server thread/ERROR] [FML]: 3: ASM: ItemSickle{Name=extrautils2:sickle_wood} rightClickHandler(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:28 [Server thread/ERROR] [FML]: 4: ASM: ItemSickle{Name=extrautils2:sickle_stone} rightClickHandler(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:28 [Server thread/ERROR] [FML]: 5: ASM: ItemSickle{Name=extrautils2:sickle_iron} rightClickHandler(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:28 [Server thread/ERROR] [FML]: 6: ASM: ItemSickle{Name=extrautils2:sickle_gold} rightClickHandler(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 7: ASM: ItemSickle{Name=extrautils2:sickle_diamond} rightClickHandler(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 8: ASM: me.ferdz.placeableitems.event.RightClickHandler@74c8781 onItemRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 9: NORMAL
22:22:29 [Server thread/ERROR] [FML]: 10: ASM: vazkii.quark.misc.feature.NoteBlockInterface@1ec46b1 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 11: ASM: vazkii.quark.tweaks.feature.DoubleDoors@31d3ef0 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 12: ASM: vazkii.quark.tweaks.feature.DeployLaddersDown@18ff1e3 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 13: ASM: vazkii.quark.tweaks.feature.RemoveSnowLayers@333711b onPlayerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 14: ASM: vazkii.quark.tweaks.feature.RightClickSignEdit@297ac04 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 15: ASM: vazkii.quark.vanity.feature.SitInStairs@1c155c2 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 16: ASM: biomesoplenty.common.handler.GrassPathEventHandler@737f436 onBlockRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 17: ASM: noppes.npcs.ServerEventsHandler@63f2909 invoke(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 18: ASM: noppes.npcs.ScriptPlayerEventHandler@d4c8601 invoke(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 19: ASM: ItemFlatTransferNode{Name=null} run(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:29 [Server thread/ERROR] [FML]: 20: ASM: realdrops.handlers.EventHandler@57723ff onPlayerClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:30 [Server thread/ERROR] [FML]: 21: ASM: Block{null} onRightClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:30 [Server thread/ERROR] [FML]: 22: ASM: Block{null} onRightClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:30 [Server thread/ERROR] [FML]: 23: ASM: net.mcft.copy.backpacks.ProxyCommon@ef7fc27 onPlayerInteractBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:30 [Server thread/ERROR] [FML]: 24: ASM: net.mcft.copy.backpacks.item.DyeWashingHandler@7af4104 onPlayerInteractBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:30 [Server thread/ERROR] [FML]: 25: ASM: com.jaquadro.minecraft.storagedrawers.core.CommonProxy@207e4d9 playerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;)V
22:22:30 [Server thread/ERROR] [FML]: 26: ASM: com.sk89q.worldedit.forge.ForgeWorldEdit@35d27cc onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
22:22:30 [Server thread/FATAL]: Error executing task
22:22:31 at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]

How can I solve this? I tryied some things but I cant figure out where is the problem.
Here a pastebin with the outputs when trying to use a pistol, bow and the snowball
http://pastebin.com/AZsLVA8q

**Comment by bs2609** [comment]
Post issues such as this in the support forums:
http://www.minecraftforge.net/forum/forum/18-support-bug-reports/

**Comment by Stann0x** [comment]
But I cant make an account there ;-;

**Comment by LexManos** [comment]
Then hop on irc and figure out why.
This is not the place for basic tech support.
As long as you have a valid email you should be able to make an account on the forums.
