### ISSUE TITLE
Minecraft Uses A Lot of RAM When Minimize the Minecraft Window

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3710]
i tried it with only Forge is installed.
1- Install Minecraft 1.11.2
2- Install Forge 2232
3- Run Minecraft with Forge 2232
4- Create a new world with default settings
5- Game is using 1700 MB of RAM while playing it, okay it is normal
6- Press ESC in the game, then minimize the Minecraft window. Just see your desktop.
7- Wait a little bit time, open task manager, and you will see Minecraft is using a lot of (~7GB on my machine) memory. And If you have a modpack, it is about 20GB sometimes, and it **keeps increasing**

I hope this issue be fixed, it is really terrible.

**Comment by loordgek** [comment]
how long do i need to wait ?

**Comment by ghost** [comment]
i don't really understand but it is not happening now. it was happening for 1 month, and it was a terrible problem but it is not happening now. **i will update this issue when it happen again.**
thanks for quick response!

**Comment by ghost** [comment]
Okay, i got it happening again. How can i show you happening? Want me make a gif? Or send the logs?

**Comment by ghost** [comment]
Here is the log maybe you want to see.
[latest.log.txt](https://github.com/MinecraftForge/MinecraftForge/files/785975/latest.log.txt)
as you can see the line that **[18:15:51] [Server thread/INFO]: Saving and pausing game...** is the moment that i pressed ESC key. and after that, i minimized the minecraft down, waited about 10 mins, then open task manager, and i saw that minecraft was using 4 GB of ram. and i came back to the game, it freezed for 4-5 seconds then normal; and i just looked to the task manager, game was using 800 MB of ram.

**Comment by RainWarrior** [comment]
Can you reproduce it with only forge installed, and nothing else?

**Comment by ghost** [comment]
Adding more resources:
I got it happening again without any mod. Also deleted all config files. But the world was stolen from my modpack. I just pressed ESC, minimized Minecraft, task manager: Minecraft 1.4 GB, 1.6 GB, 1.9 GB, 2.2GB......
**Okay.** Uploading a video about it. Just give me 10 mins.

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=9BDxq7_ThSk **here it is.**

**Comment by raoulvdberge** [comment]
Slightly offtopic, but I like the musical choice you made on the video.

**Comment by iTitus** [comment]
It looks like you have a Resource Pack, could you try it without that too?

**Comment by ghost** [comment]
YEAH, i forgot to delete the resource packs. And just after that, i deleted all of them and tried again, same thing happened. Please believe me, i don't want to upload a new video again...

**Comment by loordgek** [comment]
i can not reproduce it only forge on the MC new launcher

**Comment by ghost** [comment]
yeah i know, if you create a world on stock minecraft with forge, it is not happening. but i made a modpack, and this thing happening all the time. and i don't know which mod causes this. But it is so weird that why it is happening with NO any mods or no texture packs or nothing except the forge. Then i thought it is a forge problem. If it isn't, please let me know what causes this. You can try my modpack also, it is [here](http://www.technicpack.net/modpack/magenji.968153)

**Comment by ghost** [comment]
Or, do you want me send you my world, @loordgek ? The world that in the video. Maybe it can let you know what causes this problem.

**Comment by LexManos** [comment]
Please move to the forums to do basic debugging. However I would advise that the amount of ram shown in standard task manage is the total of the heap. Which can grow to the maximum you set in the launch arguments. For your case 6GB.
When you minimize the game it doesn't have to do some of the constant rendering {the GPU knows that it isnt actually rendering anything} so it can quickly go through the chunks that are still being loaded when you enter the world.
For a proper test, joined the world, hit f3, wait till the number of chunk updates stabilizes/goes to zero. THEN minimize the game and see what happens.
Also as per usual, we need log files. But again, go to the forums.

**Comment by ghost** [comment]
:::c i tried 0 chunks, same thing happened. and the RAM in task manager keeps increasing FOREVER. i saw 20 GB... but i gave 6 gb. how it can be?

**Comment by LexManos** [comment]
Forums
