### ISSUE TITLE
'Remove erroring [tile]entities' treats crash report as a format string

### ISSUE THREAD

**Issue by Aaron1011** [MinecraftForge/MinecraftForge#3713]
When the 'remove erroring [tile]entities' option is turned on, tileentity/entioty crash reports [are logged using FMLLog.sever](https://github.com/MinecraftForge/MinecraftForge/blob/0e9d741/patches/minecraft/net/minecraft/world/World.java.patch#L380). However, this method interprets the message as a format string. If the crash report text happens to contain any format string sequences, the server will crash with an `UnknownFormatConversionException` - meaning that the original exception is lost.

**Comment by diesieben07** [comment]
This is far from the only occurrence of this problem. That method should not be using `String.format` imho.

**Comment by LexManos** [comment]
It pops up every now and again, the format is fine.
We just need to filter cases where we want to protect against bad things being formatted twice.

**Comment by everseeking** [comment]
Have seen this pop up occasionally, [most recently in the FTB Crash subreddit](https://www.reddit.com/r/FeedTheBeastCrashes/comments/6exs3q/crash_when_entering_world_atm/).

[Crash report](https://pastebin.com/5ZntLRWm) from the thread.

**Comment by diesieben07** [comment]
The format is (in theory) fine, yes. But if we keep it we need to add escaping at every possible entrypoint. This is just like passing raw data into an SQL query or whatever. In the linked crash the issue is that just an entire crash-report output is shoved through `String.format`. At some point there will be some invalid formatting codes in there.
I think we should clean up the few places that rely on the `String.format` and remove it.

**Comment by mezz** [comment]
Easy solution is just make sure you always give logs a format string:
`net.minecraftforge.fml.common.FMLLog.severe("Removing erroring tile entity. Crash report:\n{}", crashreport.func_71502_e());`
or skip formatting when there are no data arguments given to the log.

**Comment by diesieben07** [comment]
You mean `"Crash report:\n%s"`, what you posted is Log4j formatting, which is _also_ applied, in addition to String.format.

**Comment by mezz** [comment]
Oh ok. I use a log4j logger directly, I didn't know FMLLog had an additional wrapper over it that applies `String.format`.
I agree with what you said earlier then.
