### ISSUE TITLE
[1.11] Specifications don't follow annotations

### ISSUE THREAD

**Issue by Da-Technomancer** [MinecraftForge/MinecraftForge#3714]
With the 1.11 update invalidating null itemstacks, many forge methods are now (correctly) marked with @Nonnull. However, many of these methods still have the 1.10 specifications on them, which (incorrectly) specify cases to return null (for example, IItemHandler.extractItem). The specifications need to be changed to require returning ItemStack.EMPTY instead.

**Comment by LexManos** [comment]
Feel free to writeup a comprehensive javadocs update PR.
This should of been done in the handful of @Nullable PRs we've had but either way its annoying as crap.
