### ISSUE TITLE
Include capabilities in ItemStack equality checks

### ISSUE THREAD

**Issue by averixus** [MinecraftForge/MinecraftForge#3718]
Is there any reason why `ItemStack` capabilities aren't checked in `ItemStack#areItemStackTagsEqual` and `ItemStack#areItemStacksEqual`? This would allow maxstacksize > 1 items with capabilities to be stacked if their capabilities are compatible, but not otherwise.

**Comment by HenryLoenwind** [comment]
I don't have my decomp workspace at hand, but I'm quite sure areCapsCompatible() is called there...

**Comment by averixus** [comment]
Oops. You are totally right, my forge version was just in need of updating.
