### ISSUE TITLE
Crash when trying to hover over an Ender Eye in an inventory

### ISSUE THREAD

**Issue by MastaC729** [MinecraftForge/MinecraftForge#3719]
I get the following crash when hovering over an Ender Eye in my inventory:

http://pastebin.com/9ALQ4eck

I understand that this crash is generic, but I am not using Anarchy Foamfix or any dev builds of other coremods from what I can tell that would screw up the rendering system. Let me know if you have any suggestions.

**Comment by mezz** [comment]
This is not the right place for support, please use the Forge Forums:
http://www.minecraftforge.net/forum/
