### ISSUE TITLE
Accessing fields that have no accessor.

### ISSUE THREAD

**Issue by colemannoah** [MinecraftForge/MinecraftForge#3720]
I'm trying to access `modelManager` in the Minecraft class.

`Minecraft.getMinecraft().modelManager` and it's not visible and I don't know how to access it, and I'm trying to do the same thing with `timer` in the Minecraft class to but that is also not visible.

I'm using the forge1.8-11.14.4.1577 MDK.

**Comment by shadowfacts** [comment]
Use [Reflection](https://docs.oracle.com/javase/tutorial/reflect/).

**Comment by raoulvdberge** [comment]
Don't use reflection, use an AT (accesstransformer)

**Comment by colemannoah** [comment]
How do I use Reflection to get the `modelmanager` or `timer`? I don't understand how to from the link.

**Comment by codahq** [comment]
This isn't a bug.  It should be handled on the forums (or in IRC).  Do a search on "ObfuscationReflectionHelper"

**Comment by RainWarrior** [comment]
If something is private, first thing you should do is try to figure out why it's private; maybe there's another way to access what you want? For the model manager, you can get it using Minecraft.getRenderItem().getItemModelMesher().getModelManager(), but you probably don't need to use it directly. Timer is not exposed directly, but most code that needs something from it already gets that data some other way.
