### ISSUE TITLE
PlaySoundAtEntityEvent hasn't been updated to match World.playSound changes.

### ISSUE THREAD

**Issue by Mysteryem** [MinecraftForge/MinecraftForge#3721]
The [`PlaySoundAtEntityEvent`](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/event/entity/PlaySoundAtEntityEvent.java) is fired through calls to[`ForgeEventFactory.onPlaySoundAtEntity(...)`](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/event/ForgeEventFactory.java#L397) in both [`EntityPlayerSP.playSound(...)`](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/patches/minecraft/net/minecraft/client/entity/EntityPlayerSP.java.patch#L74) and [`World.playSound(@Nullable EntityPlayer player, double x, double y, double z, SoundEvent soundIn, SoundCategory category, float volume, float pitch)`](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/patches/minecraft/net/minecraft/world/World.java.patch#L192).

The issue is with the method in the `World` class, specified above.

Originally, it looks like the method used the `EntityPlayer` argument to determine the position the sound should be played at: https://github.com/MinecraftForge/MinecraftForge/blob/adddfab850cbe733986bd98bcc86d494d4fde5e5/patches/minecraft/net/minecraft/world/World.java.patch#L173

The `playSoundAtEntity` and `playSoundToNearExcept` methods have since been merged together into the current `World.playSound` method that takes x/y/z position arguments that are used instead of the `EntityPlayer`'s position. The `EntityPlayer` argument is then used to specify a player who should not hear the sound, allowing the new method to replace both of the old ones.

The current `PlaySoundAtEntityEvent` is misleading due to the sound not being played at the location of the passed entity any more when fired from `World.playSound` (the event is still correct when fired from `EntityPlayerSP.playSound`). And there is currently no way to determine 'sidedness' or position from the event if the passed `EntityPlayer` argument is `null`.

It's probably worth noting that the event will only be fired on the server-side when fired from `World.playSound` since `WorldClient` overrides the method and changes the semantics.

**Comment by williewillus** [comment]
i don't really see a clean solution to reimplementing the original behaviour, I'd say just remove the event since we have PlaySoundEvent already.

For reference, RTD has docs on what the methods do currently: https://mcforge.readthedocs.io/en/latest/effects/sounds/#playing-sounds

**Comment by Phylogeny** [comment]
The ```PlaySoundAtEntityEvent``` allows the server to change sounds and to prevent them from ever being sent to clients in the first place. The ```PlaySoundEvent``` is not a replacement for it, since it's client-only.
