### ISSUE TITLE
Translation issue (only "vanilla english")

### ISSUE THREAD

**Issue by DeadSix27** [MinecraftForge/MinecraftForge#3722]
As I posted on the forums:
http://www.minecraftforge.net/forum/topic/50812-weird-language-translations-issue/

Forge version: forge-1.10.2-12.18.3.2234

On my server and client combination, some messages are not translated, e.g commands respond like:

```
> forge
[14:32:57] [Server thread/INFO]: Usage: commands.forge.usage
> forge tps
[14:33:29] [Server thread/INFO]: commands.forge.tps.summary
```

**Comment by diesieben07** [comment]
I looked more into this and I don't think there is an easy solution for this. The command itself cannot know whether or not the text is going to be displayed on the console or not.

We would need a new method in ICommandSender like `canTranslate` which is false for console. But that is still pretty ugly.

**Comment by kashike** [comment]
This is also broken when used on vanilla clients, not just the server console.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/7c9b67b574836729dd73f04fd49d800a67dd121f
