### ISSUE TITLE
Feature request: Get fakePlayers list of FakePlayerFactory without reflection

### ISSUE THREAD

**Issue by Raycoms** [MinecraftForge/MinecraftForge#3723]
There should be a way to get that map to check the usernames of the fake players.
A copy of that map would be great.

**Comment by LexManos** [comment]
Why?

**Comment by Raycoms** [comment]
In some cases it would be helpful to know which the registered fakePlayers
are

2017-02-22 16:48 GMT-03:00 LexManos <notifications@github.com>:

**Comment by KnightMiner** [comment]
Such as? Only cases I can think of a simple instance of check on FakePlayer is sufficient.

**Comment by Raycoms** [comment]
We have certain colonies wich have their colony protection. Our players can
add friends or other players to their colony to give them rights to attack
entities, change blocks etc.
They should also be able to add fakePlayers via username. But for that we
need to access that list.

2017-02-22 16:59 GMT-03:00 KnightMiner <notifications@github.com>:

**Comment by LexManos** [comment]
Not really, you should just create fake players under the owners username. 
That or you should log a message when someone tries to edit things they arnt allowed to and show the username there. Sot he process would go:
Place block down, Do thing, Read username, add permission.

**Comment by williewillus** [comment]
I think you're better off looking at individual mods' fake player names, instead of getting the list and hoping they have meaningful names :P

**Comment by Raycoms** [comment]
We're not worried about our own fake players. We're worried about enderIO,
thaumcraft etc fakePlayers.
And if we want to support them we need to be able to say if a certain
username is connected with a fake player inside that list.

2017-02-22 17:14 GMT-03:00 Vincent Lee <notifications@github.com>:

**Comment by LexManos** [comment]
Again, no you don't require access to the list you require access to the fake player trying to do things in your region. Which again can be retreived by having it spit out the name when it tries to do something and you block it.
As for other mods they should be using owner names as well. So if you run into issues with toher mods you should speak with them to get it fixed. You can still do your half-fix and whitelist their global name but they shouldn't be using a global name if they can avoid it.

If you jsut want top know IF a player IS a fake player then a instanceof FakePlayer is the way to go.

So, long answer short, no you don't need direct access to this list. You, and other modders, should be doing things properly.

**Comment by williewillus** [comment]
@Raycoms what you want to do is check that specific mod's repo to find out what they name their fake player. Instead of just dumping the whole list. Like for example BuildCraft's fake player back in the day was "[Buildcraft]"

**Comment by Raycoms** [comment]
Yeah I know, I have a list of like 6-7 fakePlayer names.
But I don't like to have a static list I add fakePlayers to. I'd like to
make it dynamically.

2017-02-22 17:59 GMT-03:00 Vincent Lee <notifications@github.com>:

**Comment by HenryLoenwind** [comment]
Lex, please don't tell people to store and trust user names in the time of changeable usernames and UUIDs. There are already too many mods out there that key things to a username and totally fail when a user changes theirs...

**Comment by LexManos** [comment]
Ya ya UUIDs shush. The entire system should be run off UUIDs I used the wrong word to mean what i meant.

**Comment by AEnterprise** [comment]
for the fake players check the startup logs, buildcraft and a few other mods print out their fake player name (and in the case of bc the uuid as well) to the log so people can find it more easely
