### ISSUE TITLE
Forge Version Change

### ISSUE THREAD

**Issue by yario-o** [MinecraftForge/MinecraftForge#3724]
I am trying to work on forge itself. So I did: `gradlew setupForge`.
I edited some class but when I compile with: 'gradlew build' It gets a forge named: 
'forge-1.7.10-10.13.4.0-1.7.10-installer.jar'
How Can I modify the version 10.13.4.0?
I've already tried to change in src\main\java\net\minecraftforge\common\ForgeVersion.java
but it only changes the version in the game but not in the installer or in the launcher.

**Comment by diesieben07** [comment]
You need to check out the correct branch.

**Comment by yario-o** [comment]
I have the correct branch but the buildVersion of forge is always **_0_**: (10.13.4,**_0_**).

**Comment by diesieben07** [comment]
That is normal, the build version is only set when built by jenkins.

**Comment by LexManos** [comment]
Why are you making a custom build of Forge? 
All details on how to do what you can want be grocked if you read the build.gradle.

**Comment by DeadSix27** [comment]
@yario-o set env. var "BUILD_NUMBER"

**Comment by yario-o** [comment]
Thanks you.
