### ISSUE TITLE
Add informative crash message for invalid arguments to forge.jar

### ISSUE THREAD

**Issue by Gaelan** [MinecraftForge/MinecraftForge#3727]
I spent several hours pulling my hair out yesterday because I was running `java -jar forge.jar -Xmx3g…`. I doubt I'm the only one who's made this mistake, and it seems pretty easy to catch it in FMLTweaker and crash the game.

**Comment by williewillus** [comment]
why are you executing the (game) jar without a launcher in the first place? :P

**Comment by Gaelan** [comment]
@williewillus Server. :P

**Comment by williewillus** [comment]
oh derp :P It doesn't happen for me in a dev environment dedicated server though

**Comment by Gaelan** [comment]
@williewillus Nothing happens, and that's the problem. Xmx etc get silently ignored, and you get really confused about why 5G memory is not enough.

**Comment by LexManos** [comment]
We're not really in the roll of holding people hands for stupid mistakes like this.
