### ISSUE TITLE
[Feature Request] GuiConfig incompatible with @Config-based Configurations

### ISSUE THREAD

**Issue by thilokru** [MinecraftForge/MinecraftForge#3729]
While moving to the annotation based config system, I noticed, that there is no easy method to provide a ingame configuration gui (when using the system mentioned above), as the Configuration object is handled internally and the modder doesn't get access to it, as it is stored in private fields.

I'd propose to implement an additional constructor for the GuiConfig class, which does not require a List of all configuration elements, but instead looks them up based on the provided modid if the mod uses the annotation based system and if not throws an Exception to notify the modder.

I can start working on a pull request, but first, I'd like to get feedback, whether this feature is desirable, if there already have been attempts to implement this etc.

**Comment by LexManos** [comment]
It is it's been on my todo for a while just never got around to doing it with other things in the backend i've been needing to do.
The idea is the annotation system is to be a complete abstraction away from the current system and for modders to have a much more, slimmed, cleaner interface for dealing with configs.
There are also expansions on what I want to do with the annotations that i've described a few times {and laid the groundwork for with the 'type' value}, but that's later after we get feature parity and deprecate the current config system.

**Comment by thilokru** [comment]
@LexManos So, work on this topic is currently unwanted?

**Comment by thilokru** [comment]
Closed by PR #3735.
