### ISSUE TITLE
[1.11.2]Unformatted error messages

### ISSUE THREAD

**Issue by The-Fireplace** [MinecraftForge/MinecraftForge#3732]
I just launched Minecraft with some mods present that were intended for 1.10.2, and the error screen is not localized.
![image](https://cloud.githubusercontent.com/assets/5914284/23335948/4ca826ac-fb86-11e6-9be0-d22009ff40e0.png)

**Comment by ichttt** [comment]
Strange, it worked inside my dev environment when I wrote the PR...

**Comment by ichttt** [comment]
I think it is a problem with the crowdin synchronization, as the new strings I added to the en_US.lang are entirely missing in the compiled jar that has been rolled out.

**Comment by LexManos** [comment]
you added new strings y.y yes thats not automatically pulled in. As crowdin doesnt have an API where i can auto-update those. @mezz is supposed to either update it himself or tell me for PRs. I'll get it updated here in a second and any builds after that will be fine.
