### ISSUE TITLE
[1.10.2] Propably wrong OreGen order

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3734]
I noticed OreGenEvent.Post is called before IWorldGenerator.generate. I dont know if this is an intended behavior but this was about 5 month ago different. 

If this is an intended behavior I am sorry, but is there another event called after all Mods have placed their ores inside a chunk ?

**Comment by diesieben07** [comment]
Ideally mods should not generate their ores in `IWorldGenerator` but in `OreGenEvent.Post`. `IWorldGenerator` is the last thing that happens as part of chunk population.
You can however register an `IWorldGenerator` with a very high weight, it will run later.

**Comment by mcenderdragon** [comment]
Ahh okay, any refernce of what value other mods use ?

**Comment by diesieben07** [comment]
Most probably use 0 unless they have specific reason to generate after someone else. If you want to catch every other ore, use `Integer.MAX_VALUE`. This is turning into a support question though, I suggest you open a thread on the forums.

**Comment by mcenderdragon** [comment]
Well I think I will just add this to the config file. Thanks for your patients.
