### ISSUE TITLE
fluids show still texture when they should be flowing under certain conditions

### ISSUE THREAD

**Issue by bogger33** [MinecraftForge/MinecraftForge#3740]
![forgevsvanilla2](https://cloud.githubusercontent.com/assets/10445063/23407958/82efb9e0-fdc6-11e6-9b78-20da27fc703f.png)

left - forge fluid with vanilla water texture 
right - vanilla water. As you can see forge thinks the water at the bottom is still - presumably because it starts at a full 1 block height, but i haven't looked into the code

( as you can see there is also a gap in the forge fluid rendering, this is bug #2993 )

**Comment by bs2609** [comment]
This is still currently an issue:
![2018-02-21_01 50 03](https://user-images.githubusercontent.com/1447117/36459013-91cab09e-16a9-11e8-80b9-e8b95b9dcdc0.png)

**Comment by bs2609** [comment]
This might be difficult to fix without breaking something else. I'll have a look at the flow vector code to see if it can be handled there.

**Comment by bs2609** [comment]
Should also be fixed by #4763.

![2018-02-27_15 05 29](https://user-images.githubusercontent.com/1447117/36736174-d9c057b6-1bcf-11e8-8e3a-b03e53349e9b.png)
