### ISSUE TITLE
Minecraft Eats the Memory When You Set Max FPS to Unlimited

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3745]
i can reminder my old issue. https://github.com/MinecraftForge/MinecraftForge/issues/3710
finally, i solved what causes it. just set the "Max FPS" option to unlimited. it will happen again. please go that issue that i linked, you can watch my video also on that topic. thanks.
it happens on forge 2252 too.
https://www.youtube.com/watch?v=9BDxq7_ThSk

**Comment by mezz** [comment]
The memory usage you see in the Task Manager is not meaningful. You give Java a certain amount of RAM to work with, and it will eventually use all of that in the Task Manager.

**Comment by ghost** [comment]
i did... i repoduced it billion times... with different amounts of RAM for Java... It's happening all the time, and it will increase FOREVER. you can reproduce it too. However, i am using Nvidia gtx970m, and using the latest driver 378.66. Maybe another GPU doesn't have same problem.

**Comment by mezz** [comment]
If it's growing forever you need to set a maximum memory limit on java like `-Xmx4g`.
Check the ram used by F3 in-game or with something like the [Memory Bar](https://minecraft.curseforge.com/projects/memory-bar) mod for a more accurate reading.

**Comment by ghost** [comment]
i did. I was using -Xmx6G in the video. and i tried with different amounts, i tried -Xmx1G and it didn't work, RAM usage gone over the 1G and also the 6G too. it's a different problem, i don't know. and it happens only when minimize the minecraft window.

**Comment by mezz** [comment]
Your video does not show it going forever, or even over 6G.

I tested with `-Xmx2g`, vsync disabled, unlimited framerate, minimized window, and I was unable to see memory increasing beyond 2G.

**Comment by ghost** [comment]
okay i will prepare a video that shows this happening. What gpu are u using?

**Comment by mezz** [comment]
GeForce GTX 680.
Video?

**Comment by ghost** [comment]
it's not happening after updating my GPU driver (7 March 378.78 update, gtx 970m)

**Comment by mezz** [comment]
Ok, glad it's working
