### ISSUE TITLE
Negative density fluids render wrong

### ISSUE THREAD

**Issue by bogger33** [MinecraftForge/MinecraftForge#3746]
![2017-03-01_20 08 25](https://cloud.githubusercontent.com/assets/10445063/23476389/e890db4a-feba-11e6-9392-dd75c06db9a6.png)

I think the picture basically says it all.

**Comment by williewillus** [comment]
also, #698 :P

**Comment by bogger33** [comment]
So apparently this happens when you have a negative density fluid that has gaseous set to false (which is the default value)

however, shouldn't a negative density fluid by definition be gaseous? There doesn't seem to be any advantage to having those two things coexist. I think isGaseous should be deprecated and isGaseous() replaced with a density check.

**Comment by Prospector** [comment]
This is not resolved, and the reverse is true as well, a gaseous fluid with a positive density will be upside down but flow normally, looking really weird. 

Simply put, a fluid should not have positive and gaseous, or negative and not gaseous. Fix I would recommend would be setting isGaseous automatically if it's negative.
