### ISSUE TITLE
[Feature] Reach distance as an attribute

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3749]
I see that we patch reach distance checks into PlayerInteractionManager

It would be really nice if we could change this into an attribute and check that instead, so modders don't have to fight over setting the reach distance and can just use an additive attribute modifier to do it. It also makes things like reach potions and amulets much more easy to implement.

**Comment by JamiesWhiteShirt** [comment]
+1 on this. I already use an attribute that accumulates extra reach distance. Its value is added to the base value in PlayerInteractionManager and PlayerControllerMP with a small ASM patch. Moving it entirely to an attribute would make it a lot simpler.

The only issue I see is that forge will have to define the min and max values of the attribute, which may conflict with some mods.

**Comment by Alpvax** [comment]
Min value would probably be 0 (i.e. can't reach anything, clicking on air) and you could always have it unrestricted (i.e. MAX_VALUE). Or you could limit it to the loaded chunk radius.

**Comment by bs2609** [comment]
Can this be closed now #4331 has been merged?
