### ISSUE TITLE
forge fluids do not disperse correctly in specific scenarios

### ISSUE THREAD

**Issue by bogger33** [MinecraftForge/MinecraftForge#3750]
So here's the setup:
![setup](https://cloud.githubusercontent.com/assets/10445063/23510022/3ed1fa8c-ff58-11e6-9f99-a29d140476d5.png)

two source blocks (both on the upper level of the glass structure) - if you get rid of the right one first, the water at the bottom does not disperse. Even if you get rid of the left one after. Vanilla handles this correctly. 

![steptwo](https://cloud.githubusercontent.com/assets/10445063/23510234/faa901ba-ff58-11e6-9ee4-b3ef95eddeb1.png)

It does disperse if you update it.

**Comment by bs2609** [comment]
Just so I don't forget about it, this should be fixed by #4763.

**Comment by bs2609** [comment]
Flow mid-decay:

![2018-02-27_15 04 26](https://user-images.githubusercontent.com/1447117/36736227-ffabad7c-1bcf-11e8-896f-54f4b2f6e43e.png)

**Comment by bs2609** [comment]
As that PR was merged, this can be closed now.
