### ISSUE TITLE
PacketBuffer's read and write ItemStack methods ignore capabilities

### ISSUE THREAD

**Issue by averixus** [MinecraftForge/MinecraftForge#3751]
I'm not sure if I'm missing the point here. There's been [talk](https://github.com/MinecraftForge/MinecraftForge/pull/3283) about using `Item#getNBTShareTag` to send capability data to the client with packets. But wouldn't it be easier to simply add capability data to the read and write methods so that it's automatically sent with the packet?

**Comment by williewillus** [comment]
the discussion is that some items don't need their caps sent to the client, so it would waste a lot of net traffic to always do so

**Comment by averixus** [comment]
Could there maybe be a method in `Item` to check whether capabilities should be synced to the client? With no control over the way `getNBTShareTag` is read, it's impossible to efficiently convert it back into capability data which means there's no way to properly sync capabilities. If there was some way to optionally send capabilities in the `PacketBuffer` methods then people would have the option to sync the entire capability (with the `PacketBuffer` methods), or to sync just the bits of data relevant for rendering etc (with `getNBTShareTag`), or to send nothing if it's not needed.

**Comment by williewillus** [comment]
the packetbuffer methods are used any time an itemstack travels through the net, so changes there affect everything

**Comment by averixus** [comment]
Is that a problem though? If including capabilities is made an optional operation (which can be defaulted to false), then it doesn't have to affect anything except when it's needed.

**Comment by averixus** [comment]
As a completely different alternative solution to `ItemStack` syncing, could there be some kind of event that's fired whenever a stack is synced with `PacketBuffer`, that could then be used as a prompt to sync capabilities manually when needed?

**Comment by mezz** [comment]
The solution we are trending toward is to use `getNBTShareTag` to add the data you need for the client. You don't really need the capability on the client, normally you just need some text info to display which should fit easily in an nbt tag.
