### ISSUE TITLE
[1.1X] FluidBucketWrapper ignores FluidStack NBT

### ISSUE THREAD

**Issue by BluSunrize** [MinecraftForge/MinecraftForge#3757]
Heya!
While working with FluidStacks that rely on NBT data, I noticed that the UniversalBucket does not handle them properly and effectively wipes this data.
The source of said issue appears to be here:

https://github.com/MinecraftForge/MinecraftForge/blob/c545b8ecd4e96107ccf134c8fd89906357d586ad/src/main/java/net/minecraftforge/fluids/capability/wrappers/FluidBucketWrapper.java#L138
Caused by the fact that only the Fluid itself is saved, rather than the FluidStack, and as such, the NBT data on said FluidStack is lost.

For any vanilla application and probably most modded cases this is never noticed since FluidStacks rarely make use of the NBT data, however in my specific case, a potion fluid that stores the PotionType in NBT, this results in a pretty critical loss of data and makes the fluid basically impossible to transport in the player's inventory.
Any chance of this being changed to accommodate NBT data?

**Comment by bs2609** [comment]
Can this be closed now?

**Comment by mezz** [comment]
Yes, thanks.
