### ISSUE TITLE
AutomaticEventSubscriber does not work with Scala

### ISSUE THREAD

**Issue by marvin-roesch** [MinecraftForge/MinecraftForge#3764]
While trying to make use of `AutomaticEventSubscriber` to erase the need to manually register my `RegistryEvent.Register` handlers, I noticed that the method employed by the `inject` method is incompatible with Scala.

The method simply registers the class to the event bus, which will result in static methods being used as the event handlers. Unfortunately, Scala (and some other JVM languages) do not have a concept of static methods as such and hence the automatic subscriber does not work here. A similar issue already arises with `@Mod` classes, but it is mitigated by `ILanguageAdapter` which adds support for Scala's object concept.

The obvious solution to the issue is adding a new method to language adapters along the lines of `Object getStaticHolder(Class<?>)` and to expose the adapters more publically (either by making it package-private and hence giving access to `AutomaticEventSubscriber` or making it public alltogether). Then the automatic subscriber as well as third parties can make use of that function to seemlessly work with all languages.

I haven't investigated this issue any further up until now, but other parts of FML/Forge could be affected by the same problem of assuming Java as the source language of some class. If possible, they should be using the language adapters appropriately as well.

**Comment by JamiesWhiteShirt** [comment]
As a Kotlin dev, I'd say this is a non-issue. You should only need a single line to register a singleton object on the event bus.

**Comment by marvin-roesch** [comment]
It of course isn't a glaring issue, after all any mod can implement what AutomaticEventSubscriber does on its own and as you say, it doesn't make a lot of a difference code-wise. But the necessary means to "solve" this problem basically already are in place, so why not address this thing and make Forge effectively compatible with every JVM language there is.

Also, regarding Kotlin: Unlike Scala (right now, there's a proposal to change this already), you have access to the `JvmStatic` annotation in Kotlin which enables you to use `@EventBusSubscriber` already. Note however, that Kotlin and Scala aren't the only non-Java JVM languages out there and a generic solution on Forge's side is easy and could come in handy later on.

**Comment by LexManos** [comment]
Ya no i've made the executive decision that scala is being downgraded to any other language on the JVM.
When the re-write happens we'll stop shipping it by default. {We have optional mod support in the installer for a reason, and the plethora of ways modders can ship dependencies}.


HOWEVER, if you wish to make a PR expanding the language adapter to fix anything like this we can entertain that. But as is, i'm not calling this a bug.
