### ISSUE TITLE
[1.11.2] Grass path shadow effect is missing

### ISSUE THREAD

**Issue by Glassmaker** [MinecraftForge/MinecraftForge#3766]
![Forge Grass path](https://i.imgur.com/spIi6Eo.png)
Grass path in Forge 1.11.2-13.20.0.2252

![Vanilla Grass path](https://i.imgur.com/xg7h8Zq.png)
Grass path in Vanilla 1.11.2

**Comment by mezz** [comment]
@RainWarrior any idea what's happening here? I took a look but couldn't figure it out.

**Comment by CrafterKina** [comment]
Forge2228: ![2017-03-12_13 52 43](https://cloud.githubusercontent.com/assets/6761325/23829108/4a18c6b6-072b-11e7-9e81-2b2afbe599dd.png)
Vanilla: ![2017-03-12_13 51 38](https://cloud.githubusercontent.com/assets/6761325/23829109/4a38fa30-072b-11e7-9082-9fa7218978d1.png)
I found that it was the same in Farmland, so  ``setLightOpacity(255)`` for non-full block is issue.

**Comment by mezz** [comment]
Ah so in vanilla the ambient occlusion is being applied for that tiny step down. 
Seems like an accident, but it looks nice.

**Comment by mezz** [comment]
@bs2609 you seem to be on a roll with fixing subtle rendering issues, can you look in to this one?

**Comment by bs2609** [comment]
Comparing vanilla to forge:

* Vanilla:
![2017-08-17_020023](https://user-images.githubusercontent.com/1447117/29391581-3cfd6d88-82f0-11e7-9075-b22ac00665d0.png)

* Forge:
![2017-08-17_020118](https://user-images.githubusercontent.com/1447117/29391583-4323c1bc-82f0-11e7-914f-a0321463633c.png)

It seems like Forge is scaling the effect with the height difference and vanilla isn't.

Looking more closely at the grass path example:

* Vanilla without the effect applied to grass paths (tweaking the relevant 'full block' threshold):
![vanilla](https://user-images.githubusercontent.com/1447117/29391750-473706fa-82f1-11e7-9875-c69e249ee8db.png)

* Forge:
![forge](https://user-images.githubusercontent.com/1447117/29391756-4ee19870-82f1-11e7-993c-fe37c3e957cb.png)

Poking at the pixels in an image editor, there does appear to be a tiny amount of darkening applied around the edges by Forge's lighting - it's just not really noticeable, especially compared to the full strength effect vanilla uses.

**Edit:**
See snow layers for a good example:
![2017-08-27_201201](https://user-images.githubusercontent.com/1447117/29753213-1d4d0bf2-8b64-11e7-8a56-8f6f56641529.png)

**Comment by bs2609** [comment]
Also looking at the comparison screenshots I took, it seems what looks like #4178 is visible as well.

**Comment by bs2609** [comment]
Also see [MC-11783](https://bugs.mojang.com/browse/MC-11783).
