### ISSUE TITLE
Wasting time while missing a dependancy

### ISSUE THREAD

**Issue by ManMan36** [MinecraftForge/MinecraftForge#3768]
I have always wondered why Forge even bothers to load all of the models for vanilla when there is a missing mod dependency if it will just yell at me that the game can't load any farther due to the missing dependency, wasting a good amount of time.

Is it possible to stop the mod loading right after Forge realizes such a problem occurs and throw the missing dependency error right there and then?

**Comment by Madsthunder** [comment]
Because Forge needs to load the background and font textures before it displays the missing dependency error.

**Comment by mezz** [comment]
Might be worth looking into since the resources required to show the error are pretty minimal. 
The faster you get to that screen, the easier it is for pack makers to update or change mods.

**Comment by bookerthegeek** [comment]
Could you not just throw it into the log very noticeably without a gui?

**Comment by mezz** [comment]
There is a log for it, so that's basically what happens when you run a server by itself.
The GUI message is nice when you're on a client though, it's lot friendlier that way instead of just having the game crash immediately.

**Comment by LexManos** [comment]
Users don't read the log file, Users don't usually read the GUI, but more users read the GUI then read the logs. SO ya...
It SHOULD be early enough that most things are not done. Yes it will look like its stitching the vanilla textures, but that's the first pass. We should be skipping out on most of the second pass of things IIRC.

**Comment by bookerthegeek** [comment]
Could forge not just have a baked in generic prebuilt background and font texture for "your an idiot and missing a mod" ?

**Comment by mezz** [comment]
I looked into it and the slow part is model loading, which is really simple to skip. PR incoming
