### ISSUE TITLE
StatList.reinit() adding duplicates to AchievementList.ACHIEVEMENTS

### ISSUE THREAD

**Issue by Earthcomputer** [MinecraftForge/MinecraftForge#3770]
**What happens**
When `StatList.reinit()` is called, it loops through all stats, calling `registerStat()` on each one. Since the `Achievement` class is a type of stat, it also calls `registerStat()` on all the achievements. `Achievement` overrides this method to add itself to `AchievementList.ACHIEVEMENTS`, hence when `StatList.reinit()` is called, all the achievements get added to this list. Since this list is not cleared beforehand, the achievements in the list are duplicated.

**Why this is a problem**
* I came across this problem when making a GUI to select an achievement from the list of achievements, and I noticed that all the achievements had been duplicated.
* If you go into the normal achievements GUI, vanilla achievements are rendered more than once, though this is not usually noticable.
* The most serious issue is the effect on the `/achievement` command.

How to reproduce the issue with the `/achievement` command:
1. Start a new world
1. Run the following commands:
   1. `/scoreboard objectives add inventory achievement.openInventory`
   1. `/scoreboard objectives setdisplay sidebar inventory`
1. Open your inventory and close it again. The new score objective should appear on the right.
1. Run the command `/achievement give *`
   1. In vanilla, this increases the counter on the side by 1
   1. In Forge you will see it increase by 2 every time you run the command.
1. Relog
1. Run the command `/achievement give *` again
   1. This time, you should see the count increase by 4 every time.
   1. In vanilla, it still only increases by 1.
1. Relog again
1. Run the same command again, it will increase by 6 this time
1. etc...

**Suggested fix**
At the beginning of the `StatBase.reinit()` method, call `AchievementList.ACHIEVEMENTS.clear()`.

**Comment by Earthcomputer** [comment]
Is this worth a PR? I am willing to make one, but it would be a very small one.

**Comment by mezz** [comment]
Go for it. Let me know if you need help setting up or testing.

**Comment by bs2609** [comment]
This can be closed now.
