### ISSUE TITLE
Potion of Night Vision Not Doing Anything

### ISSUE THREAD

**Issue by AlexCouch** [MinecraftForge/MinecraftForge#3784]
I was testing out a mod earlier and I tried to use the potion of night vision so I can easily see underground and it didn't do anything. I set my gamemode to survival and still nothing. I even set the time to night and it, again, did nothing. I'm assuming that must be a bug. Anybody else having this issue?

Forge Version: 1.11.2-13.20.0.2255

**Comment by mezz** [comment]
Works fine for me. If you need help troubleshooting please ask on the Forge Forum not here.
