### ISSUE TITLE
Forge needs to fix their dimension type handling to tolerate mod removal/changes

### ISSUE THREAD

**Issue by DietmarKrause** [MinecraftForge/MinecraftForge#3786]
In the modpack "all the mods" there is an issue with dimension types. Something registered a dimension type with id -31 before, but doesn't do so in the new version anymore. Note that this is not the usual dimension id, but the dimension type id. This leads to old worlds not compatible any more.  In the discussion it is stated that Forge needs to fix their dimension type handling to tolerate mod removal/changes which would help in the future to avoid problems like that.
The discussion can be followed here: 
https://github.com/fewizz/NotEnoughIDs/issues/55
https://github.com/whatthedrunk/allthemods/issues/447
Is there a chance to help solve problems like this via forge?
Any help would be nice.

**Comment by bs2609** [comment]
Is this related to isssue #3331?

**Comment by DietmarKrause** [comment]
looks like. That means this is an old problem . Oct 2016. :)

**Comment by LexManos** [comment]
Right, forgot about this one.
Its another one of the many cases where Mojang still hasn't separated dimension TYPE from dimension INSTANCE.
This particular instance they need to save by INSTANCE, they were saving by TYPE.

**Comment by DietmarKrause** [comment]
thank you ! :)
