### ISSUE TITLE
Improve WorldGenMinable API

### ISSUE THREAD

**Issue by elifoster** [MinecraftForge/MinecraftForge#3787]
`WorldGenMinable#generate(World, Random, BlockPos)` calls `Block#isReplaceableOreGen(IBlockState, World, BlockPos, Predicate<IBlockState>)` in order to determine whether the ore can be generated in that position. However, this is not world or position specific, which can be a problem. I propose that instead, a new function be added to the `WorldGenMinable` class that replaces that line with the following default implementation:

```java
public boolean canGenerate(IBlockState state, World world, BlockPos position) {
    return state.getBlock().isReplaceableOreGen(state, world, position, this.predicate);
}
```

which would allow subclasses of WorldGenMinable to do things like prevent it from generating when exposed to air blocks:

```java
@Override
public boolean canGenerate(IBlockState state, World world, BlockPos position) {
    return super.canGenerate(state, world, position) && WorldHelper.isExposedToAir(world, position);
}
```

without having to reimplement `generate` entirely just to replace that one line.

**Comment by mezz** [comment]
Could Forge create an improved copy of `WorldGenMinable` or is it important to use this exact class?
I think everything just needs a `WorldGenerator` and not `WorldGenMinable` in particular but I haven't checked.

**Comment by elifoster** [comment]
I mean it could, but that honestly sounds like a lot more effort (both for Forge maintenance and for people already inheriting `WorldGenMinable`) compared to what would be a 4 line patch and require no transition for people who have child classes of `WorldGenMinable`.

**Comment by LexManos** [comment]
Dont think this will happen, the fact that you are checking if its exposed to air leads me to beleive you are not fully understanding the order in which the world is populated.
Beyond that if you really need to just write your own custom generator, all this one does is loop 3 times and pick a random place to put the ore, it's not super complex.
IF we were in the market of making utility classes like this we would make a proper suite, but we are not. This in my opinion is out of the scope of Forge.

**Comment by elifoster** [comment]
>Dont think this will happen, the fact that you are checking if its exposed to air leads me to beleive you are not fully understanding the order in which the world is populated.

Can you provide more info on what you mean by this?

>Beyond that if you really need to just write your own custom generator, all this one does is loop 3 times and pick a random place to put the ore, it's not super complex.

Yes but duplicating code is still annoying.

>IF we were in the market of making utility classes like this we would make a proper suite, but we are not. This in my opinion is out of the scope of Forge.

This isn't a utility class, it is an improvement on the existing API. If Forge is not for improving Minecraft to make modding easier by providing decent APIs (you know, like all those position aware methods in the IBlockState parents, tool classes, Block, etc.), then what exactly is the scope of Forge?

**Comment by powerboat9** [comment]
Ore generates before caves, so even if your ore isn't exposed to air when generated, it could be later.

**Comment by Niko-sk2x** [comment]
Caves are generated before ores, but oress don't replace air. Checking if ore is exposed to air would make it not generate on the cave walls. I could see how it's useful but there is no way to guarantee that other mod won't generate underground structure that exposes the ore anyway. So the idea seems a bit flawed.

**Comment by elifoster** [comment]
Even so, it was an example. My request is just for the improved API that allows for things similar to that.

**Comment by LexManos** [comment]
You have location information literally one function up, where you're calling the WorldGenMineable.
I do not see a reason to take on the maintaining debt of this 'improved API' for something that you can already do.
