### ISSUE TITLE
[suggestion] Add retry command to Travis build script

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#3793]
As the Forge maven isn't totally reliable, perhaps we should add `travis_retry` to the `./gradlew --refresh-dependencies` command in the `travis.yml` file, might help salvage a few builds.
Any thoughts?

**Comment by bs2609** [comment]
@mezz, you wrote the original travis buildscript, what do you think?

**Comment by mezz** [comment]
I think Forge maven should be more reliable... I wonder what's up with it.

**Comment by LexManos** [comment]
Essentially we have started to outgrow our current servers, Which is why we are trying to setup a new one.
However OVH is taking their sweet ol time to deliver the server we ordered 6 days ago -.-
Once thats up and running things should even out.
