### ISSUE TITLE
Shift left click in enchantment table causes server freeze

### ISSUE THREAD

**Issue by KappaKiddie** [MinecraftForge/MinecraftForge#3794]
I use Shift Left click in enchantment table and the server stops, only Killing to play again

And modpack freezes too, 5 mins to disconnect from server, but in the console, i don't quit.

[Netty Epoll Server IO #0/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException
[Netty Epoll Server IO #7/ERROR] [FML]: NetworkDispatcher exception io.netty.handler.timeout.ReadTimeoutException
[Netty Epoll Server IO #9/ERROR] [FML]: NetworkDispatcher exception io.netty.handler.timeout.ReadTimeoutException
[Netty Epoll Server IO #11/ERROR] [FML]: NetworkDispatcher exception io.netty.handler.timeout.ReadTimeoutException

Server Log: (https://github.com/MinecraftForge/MinecraftForge/files/856634/Log.zip)

**Comment by diesieben07** [comment]
This is a bugtracker for bugs in Forge. Please use the forums for tech support.

**Comment by KappaKiddie** [comment]
This is a bug, looks like https://github.com/MinecraftForge/MinecraftForge/pull/3688, but I think they don't fixed yet.

**Comment by williewillus** [comment]
that's not related.
