### ISSUE TITLE
ItemStack passed in Item.itemInteractionForEntity is copy stack in creative mode.

### ISSUE THREAD

**Issue by sks0315** [MinecraftForge/MinecraftForge#3795]
ItemStack passed in Item.itemInteractionForEntity is a copy of the original stack in creative mode.
Steps to reproduce : make a test item class and paste in this code snip and click on any animal/monster.
`public boolean itemInteractionForEntity(ItemStack stack, EntityPlayer playerIn, EntityLivingBase target, EnumHand hand) {
	ItemStack handItem = playerIn.getHeldItem(hand);
	System.out.println("ItemStacks equals() : " + stack.equals(handItem));
	return true;
}`
In survival or adventure mode, it will return true and everything will work as intended(saving nbt, modifying damage). But in creative mode, it will return false. And any changes to the stack will not be saved. But any changes to the handItem will get saved.

**Comment by liach** [comment]
`stack.equals(handItem)` should never be used. Use `ItemStack.areStacksEqual()` and similar methods.

**Comment by sks0315** [comment]
I was showing that they aren't same instance. The passed in stack should be same instance with the playerIn.getHeldItem(hand). They are in survival and adventure, but not in creative mode.

**Comment by LexManos** [comment]
Thats the point, using items in creative will not modify them. If you manually go in and grab the stack in the player's hand then you're breaking the creative design.
