### ISSUE TITLE
FakePlayer doesn't override addChatMessage to blank method

### ISSUE THREAD

**Issue by LatvianModder** [MinecraftForge/MinecraftForge#3796]
It has
```@Override public void addChatComponentMessage(ITextComponent chatmessagecomponent){}```
But not
```@Override public void addChatMessage(ITextComponent chatmessagecomponent){}```

**Comment by bs2609** [comment]
That's `sendStatusMessage` and `sendMessage` respectively, for people who aren't on out-of-date mappings.

**Comment by LatvianModder** [comment]
Yes, sorry, I'm on 1.10, but seems like this problem still exists on 1.11 :P

**Comment by diesieben07** [comment]
Yeah I don't think 1.10.x will receive updates for minor issues like this.

**Comment by bs2609** [comment]
The `stable_29` mappings for 1.10.2 have the 'good' names, btw.

**Comment by cha0s** [comment]
Is this the crash-on-start issue I reported here: https://github.com/Ellpeck/ActuallyAdditions/issues/710#issuecomment-289197094 ?

That isn't a "minor" issue, if so.

**Comment by diesieben07** [comment]
It is a minor issue for forge because it can be easily worked around in the mods that call `addChatMessage`.

**Comment by LatvianModder** [comment]
Yeah, for now I just added FakePlayer check
