### ISSUE TITLE
Add a way to add multiple DispenserBehaviors to a item

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/MinecraftForge#3797]
Currently, if you register two mods register a DispenserBehaviour for the same item, only one will be called. It would be nice if forge could patch this so multiple DispenserBehavours can be registered for one item.

**Comment by diesieben07** [comment]
There is not really a good way for Forge to patch this in, as behaviors are registered by raw `putObject` calls on the registry.
You can however easily accomplish this by first checking if a behavior is already registered and if so delegating to that in yours. If all mods follow this practice, behaviors stack cleanly.
