### ISSUE TITLE
[Error: java.lang.RuntimeException] What should i do?

### ISSUE THREAD

**Issue by Jorppi** [MinecraftForge/MinecraftForge#3799]
So i was adding some mods to Minecraft and started getting an error message pop up every time i tried to start the game and now it loads for a while but it crashes just before finishing. Here's the full report: [http://pastebin.com/QhS2h4Hq](http://pastebin.com/QhS2h4Hq)

**Comment by liach** [comment]
Use forums

**Comment by bs2609** [comment]
http://www.minecraftforge.net/forum/forum/18-support-bug-reports/
