### ISSUE TITLE
Client Side events

### ISSUE THREAD

**Issue by BinaryAura** [MinecraftForge/MinecraftForge#3803]
I'm looking for an event that will be seen client side when the first tick starts, or when a game starts. FMLServerStartingEvent works for singleplayer but what about when connecting to a server?

**Comment by mezz** [comment]
The best strategy here is to listen to `PlayerEvent.PlayerLoggedInEvent` on the server, and send a packet to the client which tells it that the game has started and the server connection is established. I use this to sync Forestry's player data like their Mail when they join a server. This works for singleplayer and multiplayer.

**Comment by BinaryAura** [comment]
The reason I ask is I'm making a client side mod. I'd like to not rely on the server to have the mod.

**Comment by mezz** [comment]
That makes sense, maybe Forge could create that packet and fire an event on the client.

**Comment by BinaryAura** [comment]
If changing Forge files were an option I'd make an event at net.minecraftforge.fml.client.FMLClientHandler.instance().onInitializationComplete(); This event would signal the the client side Minecraft is done assigning variable and mods can now adjust them if needed.

**Comment by BinaryAura** [comment]
However, I think you're missing the point. As a client side mod it should do anything with packets.

**Comment by LexManos** [comment]
Go to the forums and flesh out your idea more. There are plenty of options to do what you want depending on what you want.

**Comment by BinaryAura** [comment]
Done. http://www.minecraftforge.net/forum/topic/53281-new-forge-event/
