### ISSUE TITLE
Impossible to set defaults for custom registry using RegistryBuilder

### ISSUE THREAD

**Issue by Alpvax** [MinecraftForge/MinecraftForge#3804]
I want to add a fallback object (like air is for blocks), but the optionaldefault is not accessible through the RegistryBuilder, and there is no setter. This means I need to use the deprecated PersistantRegistryManager.create approach.

Also, on the topic of registries, should I be casting the registry obtained from GameRegistry.findRegistry in order to access the assigned IDs (for use in packets) or is there a better approach?

**Comment by LexManos** [comment]
I guess I missed the default values. I'll fix that up.
As for getting things by IDs this was never intended for you as a modder to access. But my repeated requests for people to explain what they are using the registries and ids for has fell on deaf ears.
Ideally we'd jut add a standardized PacketBuffer.append(IRegistryEntry) and hide all that magic to ourselves.

**Comment by Alpvax** [comment]
I am using registries for an ability system, and need to sync the abilities with NBT somewhat similar to the way potions are synced, so the client can display icons and effects etc.
What is the current way to sync registry entries?

**Comment by diesieben07** [comment]
> What is the current way to sync registry entries?

Send the registry name.

**Comment by williewillus** [comment]
It would be better to send ids though, sending the full name is several times larger, and ID's are stable within a single network session

**Comment by Alpvax** [comment]
> Send the registry name.

In that case, why use a registry over a simple hashmap?

**Comment by williewillus** [comment]
@Alpvax: @diesieben07 is saying that's the best solution at this time without peering into the registry internals

**Comment by mezz** [comment]
That's why a registry entry serialization method would be useful.

**Comment by Alpvax** [comment]
@williewillus Yes, I know what @diesieben07 meant, I was just asking why that is the best solution currently, if you have to send the registry name anyway. I thought being able to use the ids was the main advantage of the registry system.

**Comment by diesieben07** [comment]
It is. And IDs are being used when storing things in the world.
See #3806.
