### ISSUE TITLE
Comparator state doesnt update after items are pulled from chest.

### ISSUE THREAD

**Issue by Rader2146** [MinecraftForge/MinecraftForge#3810]
forge-1.11.2-13.20.0.2228

Using a Comparator to monitor chest contents in a sorting system.  ~~Adding items will turn on the comparator, but any comparator oriented south or east will not update and turn off when a hopper pulls all items from the chest.  North and West oriented comparator work as intended.~~  Must be a double chest.  Single chests work as intended.

Edited:  After further testing, it seems that the side of the chest and location of the items in the inventory have more to do with it than cardinal direction does.  See new screenshots below.

Verified with no additional mods installed (forge only) in singleplayer and on a server.

Locked hopper, 8 cobble in the chest.  Both lamps on.
![2017-03-29_19 33 19](https://cloud.githubusercontent.com/assets/10893728/24485174/60d141aa-14b7-11e7-98cd-9764469d4d43.png)

![2017-03-29_19 33 23](https://cloud.githubusercontent.com/assets/10893728/24485176/60e386da-14b7-11e7-8fb5-76f1f3a160aa.png)

Unlocked hopper, pulled cobble out.  North comparator updated, south does not.
![2017-03-29_19 33 48](https://cloud.githubusercontent.com/assets/10893728/24485175/60d468da-14b7-11e7-9b3e-7788e69a1ac8.png)

Comparator will update when the chest is opened with r-click.  Both lamps off.
![2017-03-29_19 33 54](https://cloud.githubusercontent.com/assets/10893728/24485177/60e6c69c-14b7-11e7-8d2d-31f3f52097c9.png)

New shots:
Items in first slot:
![2017-03-29_20 37 11](https://cloud.githubusercontent.com/assets/10893728/24486733/6a4a9002-14c0-11e7-8b11-0469b476a6f4.png)

All lamps on.
![2017-03-29_20 36 30](https://cloud.githubusercontent.com/assets/10893728/24486739/74444940-14c0-11e7-8021-9afefccbba2f.png)

Only the comparator monitoring the left half of the chest is updated.
![2017-03-29_20 36 44](https://cloud.githubusercontent.com/assets/10893728/24486977/c3539dc8-14c1-11e7-9f95-9912465c1b39.png)

Items in "other half"
![2017-03-29_20 37 23](https://cloud.githubusercontent.com/assets/10893728/24486986/cc30d79e-14c1-11e7-9050-0165397f0d7f.png)

All comparators monitoring the right half are updated.
![2017-03-29_20 37 36](https://cloud.githubusercontent.com/assets/10893728/24486992/d2008d72-14c1-11e7-9f0e-ba45c76203c4.png)

**Comment by HenryLoenwind** [comment]
It's quite obvious what's happening here (no markDirty() for the unchanged chest), but...does it work in vanilla?

**Comment by bs2609** [comment]
Tested and works correctly in vanilla 1.11.2.
