### ISSUE TITLE
JSON parser fails when reading files saved in certain text editors

### ISSUE THREAD

**Issue by thearchitector** [MinecraftForge/MinecraftForge#3811]
It would seem that the JSON loading system is sensitive to the text editor JSONs are saved in, as certain editors leave formatting artifacts. See [this forum post](http://www.minecraftforge.net/forum/topic/53462-solved-strange-forge-error/).

**Comment by shadowfacts** [comment]
That's probably the fault of the text editor being stupid or misconfigured, not Forge or Gson, because which text editor you use should have literally zero effect on the saved file.

**Comment by LexManos** [comment]
It is, we will not go out of our way to add support for invalid json files... That's just a stupid idea.

**Comment by HenryLoenwind** [comment]
Let me guess, it added a BOM?

http://stackoverflow.com/questions/4990095/json-specification-and-usage-of-bom-charset-encoding
