### ISSUE TITLE
Random ID Changes in level.dat

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3814]
Block and Item ID's are randomly (Or seemingly) being shuffled resulting in items/blocks changing to another. I've tried restoring the level.dat file from a backup and it does work but then ID's shuffle again after a day or two.

**Comment by diesieben07** [comment]
Please go to the forums for debugging things like this. Post your log files there.

**Comment by LexManos** [comment]
Typically caused by mods hacking into things they shouldn't. The registry system passes all tests we have for it. So start killing off mods and seeing what one is being naughty.
And yes as Diesieben said, use the forums for basic debugging.
