### ISSUE TITLE
Forge Fluid Model Fix

### ISSUE THREAD

**Issue by Liahim85** [MinecraftForge/MinecraftForge#3818]
The following code removes the differences in the vanilla and forge fluid model.

`public class BlockFluidClassicFix extends BlockFluidClassic {

	public MistWaterBlock(Fluid fluid) {
		super(fluid, Material.WATER);
	}

	@Override
	public float getFluidHeightForRender(IBlockAccess world, BlockPos pos) {
		IBlockState here = world.getBlockState(pos);
		IBlockState up = world.getBlockState(pos.down(densityDir));
		if (here.getBlock() == this) {
			if (up.getMaterial() == Material.WATER) return 1;
			if (getMetaFromState(here) == getMaxRenderHeightMeta()) return 8F/9;
		}
		if (here.getBlock() instanceof BlockLiquid) {
			if (here.getValue(BlockLiquid.LEVEL) == 8) return 1;
			else if (up.getMaterial() == Material.WATER) return 1;
			return Math.min(1 - BlockLiquid.getLiquidHeightPercent(here.getValue(BlockLiquid.LEVEL)), 8F/9);
		}
		return !here.getMaterial().isSolid() && up.getMaterial() == Material.WATER ? 1 : here.getBlock() == Blocks.AIR ? 0.0F : this.getQuantaPercentage(world, pos) * 8F/9;
	}

	@Override
	public float getFluidHeightAverage(float... flow) {
		float total = 0;
		int count = 0;
		float end = 0;
		for (int i = 0; i < flow.length; i++) {
			if (flow[i] == 1) return 1;
			if (flow[i] >= 8F/9) {
				total += flow[i] * 10;
				count += 10;
			}
			if (flow[i] >= 0) {
				total += flow[i];
				count++;
			}
		}
		if (end == 0) end = total / count;
		return end - 0.001F;
	}

	@Override
	public boolean displaceIfPossible(World world, BlockPos pos) {
		if (world.isAirBlock(pos)) return true;
		IBlockState state = world.getBlockState(pos);
		Block block = state.getBlock();
		if (block == this || block instanceof BlockLiquid) return false;
		if (displacements.containsKey(block)) {
			if (displacements.get(block)) {
				if (state.getBlock() != Blocks.SNOW_LAYER)
					block.dropBlockAsItem(world, pos, state, 0);
				return true;
			}
			return false;
		}
		Material material = state.getMaterial();
		if (material.blocksMovement() || material == Material.PORTAL) {
			return false;
		}
		int density = getDensity(world, pos);
		if (density == Integer.MAX_VALUE) {
			block.dropBlockAsItem(world, pos, state, 0);
			return true;
		}
		return this.density > density;
	}

	@Override
	public int getQuantaValue(IBlockAccess world, BlockPos pos) {
		IBlockState state = world.getBlockState(pos);
		if (state.getBlock() == Blocks.AIR) return 0;
		if (state.getBlock() instanceof BlockLiquid) return quantaPerBlock - state.getValue(BlockLiquid.LEVEL);
		if (state.getBlock() != this) return -1;
		return quantaPerBlock - state.getValue(LEVEL);
	}
}`

**Comment by liach** [comment]
open a pull instead

**Comment by Liahim85** [comment]
Sorry, I do't know how to work on GithHub.
How can I do it?

**Comment by mezz** [comment]
[Here is the documentation for creating a pull request from a fork.](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)

**Comment by bogger33** [comment]
>if (up.getMaterial() == Material.WATER) return 1;

is this just the vanilla code? that's not going to work

**Comment by Liahim85** [comment]
I wrote this for myself and it works for me.
You can optimize the code )

**Comment by mezz** [comment]
I think this issue has been fixed here already, thanks though.
https://github.com/MinecraftForge/MinecraftForge/pull/3747
