### ISSUE TITLE
RenderLivingEvent does not store the partialRenderTick

### ISSUE THREAD

**Issue by EliteMasterEric** [MinecraftForge/MinecraftForge#3820]
RenderPlayerEvent stores the partialRenderTick, while the very similar class RenderLivingEvent does not. This makes adding rendering to entities other than the player glitchy.

Is there a reason for this?

**Comment by EliteMasterEric** [comment]
After more investigation, I've found that RenderLivingBase#renderName does not receive the partialTicks, but it throws RenderLivingEvent.Specials events anyway. My current solution is to make the partialTicks the default value of 0 for these calls.

I've also found these other render events store partial render ticks, making the case for storing the value in RenderLivingEvent stronger:
- RenderBlockOverlayEvent#renderPartialTicks
- RenderGameOverlayEvent#partialTicks
- RenderHandEvent#partialTicks
- RenderSpecificHandEvent#partialTicks
- RenderWorldLastEvent#partialTicks

Also, looking at the RenderLivingBase#doRender method, it also includes the entityYaw, but this is easily calculated from the entity information, but the RenderLivingEvent has otherwise no way to access partialTicks.

**Comment by JamiesWhiteShirt** [comment]
You can get the current partial ticks using Minecraft#getRenderPartialTicks()

**Comment by EliteMasterEric** [comment]
Discussing the problem on Discord, we found that, besides the convenience it provides, there is a use case for this to be added.

If you are calling `doRender` yourself, maybe by cancelling the event to reimplement it yourself or maybe by trying to render an entity in a GUI, a complex situation occurs where the `renderPartialTicks` used for that `doRender` call can be different from the global `Minecraft#getRenderPartialTicks()`. As a result, there is no way to know the partialTicks being passed into `doRender` without this field.

I will fix the issues pointed out to me in the pull request and make a commit.
