### ISSUE TITLE
[MC-2518] Fixing missing break sound and particles.

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3821]
In 1.11 the tools dont spawn particles nor making sounds because in the method ItemTool.onBlockDestroyed() is now a "!world.isRemote". 

This was pointed out [here](http://www.minecraftforge.net/forum/topic/44668-11021112-itemtoolonblockdestroyed-different-between-versions/) And we could easily fix that by removing the "!world.isRemote".

**Comment by williewillus** [comment]
That was added on purpose to fix the tools desyncing due to unbreaking enchantment (client thinks it's broken, but server saved it using unbreaking so it reappears)

**Comment by williewillus** [comment]
So I don't think we should be fixing this just to unfix something else

**Comment by mcenderdragon** [comment]
Ahh so thats why its there. Do you know where the package for removing/updating items is progressed ?

**Comment by mcenderdragon** [comment]
it might be a dirty solution, but we can use either the SPacketSetSlot (NetHandlerPlayClient:1257) and check for windows id 37 and trigger the breaking animation if the should be replaced to air is in the mainhand and has no durability left. Or we could check the active gui but i dont know if any event is called between the itemstack replace packet and the removal of th item in IventoryPlayer (L:553)

**Comment by williewillus** [comment]
I would rather just not do anything, it's a minor enough bug, it's not worth adding patches for it.

**Comment by mcenderdragon** [comment]
well, for someone who is neraly blind this is a huge things and makes minig realy dificult as it is hard to tell when weapon/tool breaks. THis makes things alot easyer. But for nomrla people this is a minor bug (sadly, so it is not fixed -.- )

**Comment by mezz** [comment]
When a tool breaks, the server should send that information to the client and the sound and particles should play then. `EntityLivingBase#renderBrokenItemStack` is called on the server, but it seems like it does not properly send the sound and particle to the client.

**Comment by williewillus** [comment]
We can just patch that one method to use the server side particle method/sound then

**Comment by mcenderdragon** [comment]
Well I already wrote a Mod fixing that. And I dont like paket spam, thats why I suggested the SPacketSetSlot. But yeah on the Server this gets acalled correctly.

**Comment by Madsthunder** [comment]
I have to agree with @mcenderdragon, as it does get annoying when I don't realize my some of my armor is broken until I'm dead

**Comment by williewillus** [comment]
It's not packet spam unless you're breaking your tools many times per tick :P

**Comment by mcenderdragon** [comment]
Heh, It will stack up to the even now realy bad packet handling. I mean 1mb/s is a bit much for normal building. And entitys and pipes makes things worse, but this is an completly other issue.

**Comment by LexManos** [comment]
Properly fixed it, the main issue is that the item break is called on the server side, and Mojang still has code for creating the sounds client side so it excludes the local player from the packet from the server.
This fixes that for both the sound and the particles.

Please next time DO NOT go the "screw you I'll coremod it" route. Actually let people dig in and discover the real issue and why. So we can develop a real fix. Your coremod is wrong in so many places I could go on rants all day but I won't.
