### ISSUE TITLE
Incorrect documentation in relation to null itemstacks.

### ISSUE THREAD

**Issue by darkevilmac** [MinecraftForge/MinecraftForge#3826]
https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/items/IItemHandler.java#L52

Documentation states that the return value for some methods in IItemHandler may be null, this changed in 1.11 so the documentation is no longer correct. This may be confusing for new modders and is a quick thing to fix.

**Comment by TehNut** [comment]
#3714

**Comment by bs2609** [comment]
#3493

**Comment by liach** [comment]
@mezz Can you close this since this is no longer a valid issue? https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/items/IItemHandler.java#L50
