### ISSUE TITLE
how to fix forge 1.7.10 cannot open minecraft

### ISSUE THREAD

**Issue by KirakiBP** [MinecraftForge/MinecraftForge#3827]
Gave up trying to download https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10-Forge10.13.4.1558-1.7.10/1.7.10-Forge10.13.4.1558-1.7.10.jar for job 'Version & Libraries'
Job 'Version & Libraries' finished with 1 failure(s)!

**Comment by covers1624** [comment]
First, Forge for 1.7 is no longer supported.
Second, This is a place for forge bugs not user support, go to the forums.
