### ISSUE TITLE
Report unregistered Item id's

### ISSUE THREAD

**Issue by gabizou** [MinecraftForge/MinecraftForge#3828]
Granted, this is occurring with SpongeForge installed, but I'm fairly sure this will happen without SpongeForge being involved. That being said, here's the issue I've noticed:

When a chunk is being deserialized and entities are being read from NBT, the inventories of those entities are naturally deserialized and the way that Items are attempted are looking up through the registry, then being looked up by numerical id.

Essentially for lack of better words:
```java
    public static Item getByNameOrId(String id)
    {
        Item item = (Item)REGISTRY.getObject(new ResourceLocation(id));

        if (item == null)
        {
            try
            {
                return getItemById(Integer.parseInt(id));
            }
            catch (NumberFormatException var3)
            {
                ;
            }
        }

        return item;
    }
```

The issue with this is the caught `NumberFormatException`. I have no hard evidence of what `Item`s are failing to be retrieved from the registry, but I've found from a server startup that over 1 million exceptions have been thrown:

![exceptions](https://puu.sh/vcBt9/edb68d694a.png)

Now, it would be beneficial I'd think to *know* what the id's are that are failing to retrieve valid `Item`s. What I'd propose is a cumulative case where the failed id's are gathered in a `Set` and printed out to log (or hell, even another logging file to make it aware for users) to be able to report to mod developers that those items are not being registered properly with the registry.

Of course, I could totally be wrong here as well, but this is what I believe to be the current case.

And note, this is with Forge 12.18.3.2254

**Comment by LexManos** [comment]
If this was a issue with the registries it would display it when the registries are loaded. With our 'do you wanna make a backup' prompt. Beside a modder serializing the registry name completely wrong there should be no case where this needs to be handled without already giving you the warning at the registry level.

**Comment by gabizou** [comment]
I don't believe it's an issue with the registries themselves, I believe it's more of an issue that an `Item` is being constructed and used, but not actually registered with the registry itself, ergo an unknown `Item` that can't be deserialized properly, causing this sort of massive exception issue.

**Comment by LexManos** [comment]
Then it shouldnt be serialized properly. And in most likely case would crash the game due to our re-write of how ItemStack works to use delegates. As stated on IRC i'd be interested in seeing the details expanded about your test case. But I do not think that this is something that needs to be pushed out as a public 'feature'. I'm more concerned how you got so much bad data.

**Comment by gabizou** [comment]
Upon deep thorough investigation, this is a vanilla issue where empty `NBTTagCompound`s being deserialized through `ItemStack.loadItemStackFromNBT`, the empty `String` for the `id` will cause the `NumberFormatException` to be thrown. After discussing with Lex, the proper solution is to patch Forge for 1.10.2, and potentially re-investigate the issue for 1.11.2 as the serialization methods have changed.
