### ISSUE TITLE
[1.10.2] Clicking on Villager Trades for Railroads within JEI causes Minecraft Forge to throw a RuntimeException

### ISSUE THREAD

**Issue by jarquafelmu** [MinecraftForge/MinecraftForge#3829]
When viewing Railroad crafting recipes and clicking on VillagerTrades caused a CTD. The error was `java.lang.RuntimeException: Attempted to set villager profession to unregistered profession: 5 null`.

Crash log: 
[crash-2017-04-09_18.17.48-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/908677/crash-2017-04-09_18.17.48-client.txt)

****
**Modpack:** FTB 1.4.2
**Minecraft:** 1.10.2
**Forge:** 12.18.3.2254

**Comment by williewillus** [comment]
railcraft bug

**Comment by liach** [comment]
@williewillus It is not Railcraft bug-This is dupe of way2muchnoise/JustEnoughResources#106
