### ISSUE TITLE
MultiLayerModel: Please restore the way to create an invisible (air) layer model like how it was in 1.8.9

### ISSUE THREAD

**Issue by radfast** [MinecraftForge/MinecraftForge#3832]
**Previously** in Forge 1.8.9 (build 11.15.1.1764):

If a mod had a blockstate .json containing this as the model for a specified renderBlockLayer (e.g. SOLID) it caused the ModelLoader to create an **empty model** like an Air block, I mean a model with no elements and no quads:

    { "model": "forge:multi-layer" }

This was useful:
1.  for creating blocks which can go totally invisible in some blockstates
2.  for creating models where some renderBlockLayers are empty of elements, in some blockstates (even though other renderBlockLayers have something in them)

Here is a longer example:

    "variants": {
    "type_a": { "custom": {
        "base": [{  "model": "minecraft:cube_all", "textures": { "all": _some_texture_ }  }],
        "Solid": [{  "model": "forge:multi-layer"  }],
        "Translucent": [{  "model": _some_model_, "textures": { "all": _some_texture_ }  }]
        }},
    "type_b": { "custom": {
        "base": [{  "model": "minecraft:cube_all", "textures": { "all": _some_texture_ }  }],
        "Solid": [{  "model": "minecraft:cube_all", "textures": { "all": _some_texture_ }  }],
        "Translucent": [{  "model": _some_model_, "textures": { "all": _some_texture_ }  }]
        }}
    }

So variant ```type_a``` renders nothing in the Solid layer, and variant ```type_b``` has a Solid layer.  Both variants have a Translucent layer.

Like I say, **this worked in Forge 1.8.9** and was pretty sweet.

It has **not worked since Forge 1.10.2**.  The ModelLoader now creates a missing model for any layer which uses ```"model": "forge:multi-layer"```.

Is there any way the older functionality can be restored?  I guess I'm not the only person who wants to create invisible blocks or blocklayers, it does seem to be a recurring question on the forums.

(Currently my workaround is to switch the whole model to use the CUTOUT blocklayer instead of the SOLID blocklayer for the solid parts of the model, and where I want an invisible layer, to supply a standard cube model with _fully transparent_ textures.  This is inelegant, and looks different if the player has his head _inside_ the block.)

**Comment by shadowfacts** [comment]
You can return `INVISIBLE` from `Block.getRenderType` to prevent a model from being used at all.

**Comment by radfast** [comment]
But ... I want to render the block, just wanting to omit certain renderlayers for certain blockstates.

**Comment by williewillus** [comment]
just create an empty model json with a dummy element inside: [example](https://github.com/sinkillerj/ProjectE/blob/master/src/main/resources/assets/projecte/models/block/dummy.json)

**Comment by radfast** [comment]
oh, that works?  that's awesome, thank you
