### ISSUE TITLE
[Suggestion] Make a LTS version.

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3835]
Those of us who open the server, can not afford too frequent updates. Minecraft biggest problem is that the change is too fast, after all, Mod server data can not be upgraded or interoperability. Thank you very much for all job, but I think why don't we to make a Long Term Support version for Minecraft Forge ( Like Ubuntu or Kernel )?
This can also avoid the Mod author just updated a version, and then he must to update the next version. And then there's an abandoned version of that mod. Just like in the 1.7.10 era, we can't always follow Mojang, right? After all, Mod developers have their own work and life, they do not have so much energy to continue to follow the update of Minecraft.
This constant update, especially too fast update speed and frequency (Mojang has always liked or is super fast update, or super slow). Will only make developers more impatient, and even stop his work, give up his Mod.
Please think about it, I was thinking for a long time to release this issues, even if it is not a issues, but as a loyal MC game player and a server owner, I think it is necessary to stand up and say, even if nobody listen, nobody saw.

**Comment by williewillus** [comment]
This is up to the community to decide, not forge. Forge already has recommended builds for each major version, and catastrophic bugs get patched in the last 1-2 versions as well.

**Comment by LexManos** [comment]
No, our update cycle is reasonable. Modders get 6 months->year of the 'acceptible' minecraft version. As Mojang typically releases in a 6 month cycle.
This is a perfectly fine pace for working in the modded world.
