### ISSUE TITLE
[Suggestion] Throw NPE if IItemHandler is null

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3840]
The ItemHandlerHelper#insertItem return and Empty ItemStack if the IItemHandler is null, but an Empty ItemStack means the insertion of the complet stack is possible. 

I dont know but this should be changed as it could easily result in item removal.

**Comment by HashtagShell** [comment]
If the IItemHandler is null, there is nowhere to insert items, so no insertion is possible, and thus there is nowhere to delete items from. Callers can also check the argument for nullity.

**Comment by mcenderdragon** [comment]
>  If the IItemHandler is null, there is nowhere to insert items, so no insertion is possible

Correct but null/Empty ItemStack means insertion is possible.

**Comment by HashtagShell** [comment]
Give a concrete example of where this would cause an issue?
An empty itemstack doesn't mean insertion is possible, an empty itemstack means insertion is possible if there somewhere to insert into.

**Comment by loordgek** [comment]
i agree w/ @mcenderdragon here.
but don't throw a npe here but fix the ItemHandlerHelper#insertItem
in the branch 1.10.2 it is returning the stack given 
https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/src/main/java/net/minecraftforge/items/ItemHandlerHelper.java#L36

**Comment by LexManos** [comment]
Yes this was an error in the null -> ItemStack.EMPTY translation pass. Returning stack is the correct value.
We typically do not hard crash on errors like this because it breaks users more then it makes modders fix their bad code.
