### ISSUE TITLE
Synchronized or Concurrent - WorldServer

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3841]
I want to figure out why WorldServer variables
```
private final Set<NextTickListEntry> pendingTickListEntriesHashSet = Sets.<NextTickListEntry>newHashSet();
private final TreeSet<NextTickListEntry> pendingTickListEntriesTreeSet = new TreeSet();
```
Is not Collections.synchronizedSet and generally not synchronized?
And why did you use two collections for one ?
I want to 
immediateBlockTick, setBlockState, tick, tickUpdates,  updateNeightbours in threads but not working, because non-concurrent and non-synchronized.

**Comment by raoulvdberge** [comment]
A synchronized collection doesn't necessarily make it a concurrent collection.

**Comment by williewillus** [comment]
1. These are vanilla variables so you gotta ask mojang
2. You should not be touching core server data structures on different threads

**Comment by ghost** [comment]
Is that means I can't change block state in threads?

**Comment by williewillus** [comment]
No, or you risk breaking everything :P
World and anything in it should only be touched by main thread

**Comment by ghost** [comment]
But it's inconvenient. Is it mojang fault? I'm absolutely sure that logically all such things can be realized thread safe without code huge outgrowth or game deceleration. Is this not even in the plans?
I think I can mark issue closed because it's not forge problem as I can realize. But problem not disappeared.

**Comment by diesieben07** [comment]
Mojang has not made these things thread safe, because they do not need it. Thread safety always incurs an overhead, so there is no point making them thread safe if they do not need it.

**Comment by ghost** [comment]
I think that animal/mobs freezing looks a bit abnormal when some single-band routines appears like pasting 256x256x256 schematic for instance. I know that I can make update-queue that devide my process  to parts and interpret all it through the time, but it's not so nice like doing in one thread by lots of reasons.

**Comment by diesieben07** [comment]
Of course, it's not ideal. But that's the world we live in.

**Comment by mezz** [comment]
There is almost no support for concurrency in the World at all, so adding it would be a very big change and way outside the scope of Forge unfortunately. Even separate dimensions are run all on the same thread. Hopefully Mojang changes that some day.
