### ISSUE TITLE
[Future suggestion] setBlockState for range of blocks 

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3842]
World can set single block state to new one.
But it's so slow for multi-update, because there is redundant actions that can be simplified to one-action when setting blocks range. Detailed, you can send all changes in a single packet when you update range, not separately cause it's really braked even for medium volumes.
I had to create my crutch to paste schematics faster and I even can't parallel it due #3841

**Comment by williewillus** [comment]
Look at how /fill command does it, it seems fast enough for most people's usages.

**Comment by ghost** [comment]
Ok. I had tested on my mod and **world.setBlockState(pos, state, 2);** like in CommandFill and other features gives me drastically low performance. My method - changing ChunkBlockStorageArrays and after all send chunk to player is much more faster.

**Comment by PhiProven** [comment]
The problem with this is, that `setBlockState` does more than only changing an entry in `ChunkBlockStorageArrays`. There are some methods and events that are invoked when a block is changed. Most of them will effectively do nothing, but in some cases they do.
IIRC, multiple block changes are collected in a single network packet anyways.
`World.setBlockState` has to lookup the chunk for every call. This could be optimized by directly setting a whole range of blocks. But according to my benchmarks, this lookup is already relatively cheap, as it is only a lookup in a `Long2ObjectHashmap` (or however it is called).

**Comment by ghost** [comment]
As I suppose, the most part of calculations consumes light recalculations. Ticking and notifying are slow also because of light. Why there is no special optimized method to re-render light in range?
I believe that calculating single-block lightnings are touching it's neighbours in a big radius. If so there is possibility to optimize that process for block-volume.

**Comment by ternsip** [comment]
I think I found it up.
World class:
```
is a temporary list of blocks and light values used when updating light levels. Holds up to 32x32x32 blocks (the
maximum influence of a light source.) Every element is a packed bit value: 0000000000LLLLzzzzzzyyyyyyxxxxxx. The
4-bit L is a light level used when darkening blocks. 6-bit numbers x, y and z represent the block's offset from
the original block, plus 32 (i.e. value of 31 would mean a -1 offset
this.lightUpdateBlockList = new int[32768];
```
That's why /fill works not more than 32768 blocks
And we can use it to manipulate.

**Comment by liach** [comment]
Since the light calc one is dead, we may still expose some api for batch block changing.

**Comment by PhiProven** [comment]
@liach What exactly do you want to optimize with that?

**Comment by liach** [comment]
Update blocks after the batch operation instead of one by one in the original method.

**Comment by PhiProven** [comment]
Which updates are you referring to? I'm not sure if there are many things that can actually profit from delaying some updates.
If you mean the light updates, I wouldn't advise doing that, because of the Vanila bug I described [here](https://github.com/MinecraftForge/MinecraftForge/pull/4263#issuecomment-328614440). This bug applies in general to situations where large areas of light sources are updated before the lighting engine is issued, eg. by placing some lava lakes in a batch operation and running the lighting engine afterwards.

**Comment by liach** [comment]
We also need to update neighbor states in batch so that blocks within the volume don't need to update neighbor states too many times.

**Comment by williewillus** [comment]
if it's not light, I honestly don't think it's worth the complexity to batch anything. Neighbor updates are not expensive, the light updates that they bring are

**Comment by ghost** [comment]
Honestly, we need normal command to paste schematic or common world fragment with tile entities (ideally with mob-entities, particles, etc), including arguments for rotation (x,y,z), and flipping (x, y, z). And it should calculate the light properly and fast as possible. My mod - [structpro](https://github.com/ternsip/StructPro) do that thing, so it's not impossible. Yes, default forge tools for changing blocks really expensive and really slow for big batch updates.

**Comment by Niko-sk2x** [comment]
Not really an expert here, but wouldn't it potentially improve performance on sponge, as it could post just one event for mass block changes, instead of an event for every block? It could also allow to do far less chunk lookups, far less isValid checks, and these things do add up. Much less isAreaLoaded checks for lighting. While they are all inexpensive on their own, as I said it does add up to very noticable amount of time.
