### ISSUE TITLE
[Bug] Forge BLockstates are partial broken.

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3843]
Like descripte [here](http://www.minecraftforge.net/forum/topic/54667-are-the-forge-blockstates-broken/) The forge Blockstates seem to break if you add a kompltet blockstate line, like "down=true,east=false,north=false,south=false,up=false,west=false". 

in Forge version: 13.20.0.2282

**Comment by KnightMiner** [comment]
Add extra square brackets to the special variant like inventory has, they are needed if you don't have a model tag inside.

**Comment by mcenderdragon** [comment]
You are a life saver, and this is very simple thanks!
