### ISSUE TITLE
A potential issue when saving .ATBack file?

### ISSUE THREAD

**Issue by lifove** [MinecraftForge/MinecraftForge#3844]
Hi

As args[0] is from a command line, the path may include "/" or not based on a provided input.
If args[0] is "aaa/", temp will be aaa/.ATBack. otherwise, it will be aaa.ATBack.
If this inconsistency happens when these classes are executed by main frequently in real world, it could be an issue.

This might not be an issue as this could affect only on testing or debugging but wanted to report just in case. Thanks!

src/main/java/net/minecraftforge/fml/common/asm/transformers/MarkerTransformer.java
```
158         File orig = new File(args[0]);
159         File temp = new File(args[0] + ".ATBack");
160         if (!orig.exists() && !temp.exists())
161         {
162             System.out.println("Could not find target jar: " + orig);
163             return;
164         }
```

src/main/java/net/minecraftforge/fml/common/asm/transformers/AccessTransformer.java
```
371         File orig = new File(args[0]);
372         File temp = new File(args[0] + ".ATBack");
373         if (!orig.exists() && !temp.exists())
374         {
375             System.out.println("Could not find target jar: " + orig);
376             System.exit(1);
377         }
378 
379         if (!orig.renameTo(temp))
380         {
381             System.out.println("Could not rename file: " + orig + " -> " + temp);
382             System.exit(1);
383         }
```

**Comment by LexManos** [comment]
Considering we are working with files, passing in a path ending in / is invalid. As that denotes a directory. Yes we could clean this up a bit, however, this main() function is designed for people who know what they are doing and are doing debug. So having things crash on orig.renameTo trying to rename a directory to a file is fine.
