### ISSUE TITLE
Hopper behaviour inconsistency/bug

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#3854]
See [this](http://www.minecraftforge.net/forum/topic/54670-comparator-doesnt-turn-off/) bug report from the forums.

The vanilla hopper code calls `markDirty()` on the other inventories it's pulling from/pushing to, but the code in `VanillaInventoryCodeHooks` doesn't.

The `IInventory` wrappers don't call `markDirty()` on their underlying inventories either.

**Comment by bs2609** [comment]
@mezz, you worked on this code in #3442, any thoughts?

**Comment by mezz** [comment]
It should match vanilla behavior exactly, otherwise it's a bug.

**Comment by mezz** [comment]
As far as implementation goes, I don't have much to comment on... it's pretty complicated so the best way to be sure the implementation is good is to test it very thoroughly against previous bug reports.

**Comment by bs2609** [comment]
#3810 also somewhat related - that's to do with double chest handling.
