### ISSUE TITLE
[Suggestion] Enchantment Descriptions

### ISSUE THREAD

**Issue by ImelchorI** [MinecraftForge/MinecraftForge#3855]
would it be possible to make mod makers add descriptions to their own custom enchantments, that show up in the tooltip of enchanted books?

im probably not the only one who had this issue before. playing in a pack with a large number of mods that add their own custom enchantments, and no idea what most of them actually do when they show up as books or in the enchantment table.

examples for tooltips:

**Enchanted Book**
Protection I
_Decreases damage taken_

**Enchanted Book**
Infinity
_Bows do not consume arrows when fired_

**Enchanted Book**
Mending
_The item consumes player XP to repair itself_

**Comment by williewillus** [comment]
I don't think forge should have a hand in doing this. There's mods that already do this with the tooltip event

**Comment by LexManos** [comment]
Sadly there is nothing in vanilla that displays this information, at least nothing i've seen.
So there is no way we can force this.
And there isn't anywhere we could shove this information without having to have translations for all the languages vanilla supports.

**Comment by ImelchorI** [comment]
aw, thats a shame i guess. google isnt always helpful with these things.
