### ISSUE TITLE
I really need help with this one

### ISSUE THREAD

**Issue by PSILONCRAFT** [MinecraftForge/MinecraftForge#3863]
I am the creator of PROJEC PSILONCRAFTED and i use yor mod. its amazing but since i use 153 mods there are bound to be problems. Im sending you this issue because your mod is one that prints out with a error in my setup. i will send you the server log and hope for a proper answer to the adressing issue

Best regards PSILONCRAFT
[crash-2017-04-30_23.33.02-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/967063/crash-2017-04-30_23.33.02-server.txt)

**Comment by shadowfacts** [comment]
Wrong place, use [the forums](http://www.minecraftforge.net/forum/forum/18-support-bug-reports/) for support.
