### ISSUE TITLE
How To Restart The Server?

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3865]
i just need the /restart command, how can i enable it? or what should i do to restart my server? thanks.

**Comment by Alpvax** [comment]
This is a topic for the forum, not an issue with forge.

**Comment by mezz** [comment]
Sorry this is the wrong place, use [the forums](http://www.minecraftforge.net/forum/forum/18-support-bug-reports/) for support.

This is your third issue opened here when it should have been the forum. If you do it again I will have to permanently block you from contributing here.
