### ISSUE TITLE
Missing Potion Hooks

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3867]
We have currently no events firing on adding/changing potion effect to a living entity, I think this should be changed.
I suggest a event for:
- EntityLivingBase.onNewPotionEffect
- EntityLivingBase.onChangedPotionEffect
- EntityLivingBase.isPotionApplicable
- ~~EntityLivingBase.onFinishedPotionEffect~~ EntityLivingBase.removePotionEffect

bacause I want to manipulate the effects of the player and a tickhandler whould be a bit overkill.

**Comment by Alpvax** [comment]
Do we need separate added and changed events? Could we not just have a way of checking whether the effect was already applied?

**Comment by mcenderdragon** [comment]
I thorugh about sub events like the tick event. For added/changed I think a boolean is enough.

**Comment by mcenderdragon** [comment]
I opened a new PR to fix this.

**Comment by mcenderdragon** [comment]
The PR is still open. I have refractored my code so some feedback would be nice.

**Comment by Alpvax** [comment]
Let this go stale, the discussion can continue on the PR.
