### ISSUE TITLE
[Question]Getting world by dimension name

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3869]
How to get the world instance by dimension name? 
DimensionManager does not help for unloaded worlds.
PS
This code to load unloaded dimensions produce lots exceptions  "Silently" catching entity tracking error.
```
for (DimensionType dimType : DimensionType.values()) {
   DimensionManager.initDimension(dimType.getId());
}
```

**Comment by Alpvax** [comment]
This should be on the forum.

**Comment by ghost** [comment]
But works when I use
```
for (int dim : DimensionManager.getStaticDimensionIDs()) {
    if (dim == 0) {
        continue;
    }
    DimensionManager.initDimension(dim);
}
```
But if I do this in nether - I will loop continious each tick
Unloading dimension -1
Loading dimension -1
Unloading dimension -1
Loading dimension -1
...

I believe that exists some better way to load world dimensions.

This works fine:
```
for (int dim : DimensionManager.getStaticDimensionIDs()) {
   if (DimensionManager.getWorld(dim) == null) {
       DimensionManager.initDimension(dim);
   }
}
```

**Comment by diesieben07** [comment]
> This should be on the forum.

**Comment by mezz** [comment]
Sorry this is the wrong place, use [the forums](http://www.minecraftforge.net/forum/forum/18-support-bug-reports/) for support.
