### ISSUE TITLE
[Future suggestion] Forge provided fluid rendering

### ISSUE THREAD

**Issue by LasmGratel** [MinecraftForge/MinecraftForge#3877]
Yet we have IFluidTank here to store the fluid, but we have to write rendering ourselves.
Why not make a universal fluid rendering utility/system? That would be a good news for developers(especially for new mod developers).

**Comment by raoulvdberge** [comment]
Good idea! I had to copy code from JEI to do it.

https://github.com/raoulvdberge/refinedstorage/blob/mc1.11/src/main/java/com/raoulvdberge/refinedstorage/RSUtils.java#L474-L593

**Comment by loordgek** [comment]
i used code from enderio https://github.com/loordgek/Extragenarators/blob/trytofix/src/main/java/loordgek/extragenarators/client/gui/RenderUtils.java#L42-L84

**Comment by RainWarrior** [comment]
There is one: https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/client/model/ModelFluid.java
This is what's rendering for fluids in-world. X and Z bounds are static constants in code right now, but it should be possible to change those to be parameters instead easily. And add tiling for tanks that are bigger than 1 block.

**Comment by loordgek** [comment]
we want it for gui rendering

**Comment by LasmGratel** [comment]
@RainWarrior Yes we have fluid rendering in the world, but we also need a flexible GUI for players or developers.

**Comment by RainWarrior** [comment]
Whether you're rendering in the GUI or in the world doesn't make much difference for the rendering code itself. I don't see how that's relevant at all.

**Comment by AEnterprise** [comment]
@RainWarrior i think their question is a forge provided method where they can have forge render a fluid in a gui by just passing the fluid and dimensions

**Comment by liach** [comment]
I believe such a utility is still useful.

**Comment by LasmGratel** [comment]
@mezz Maybe you can migrate the render functions in JEI into Forge as a util gui class?

**Comment by mezz** [comment]
That would work, but usually we don't add utility functions to Forge that aren't being used somewhere. Someone needs to discuss with Lex to see if something like this would be accepted.
