### ISSUE TITLE
[Question?] About ArrowNockEvent

### ISSUE THREAD

**Issue by mainrs** [MinecraftForge/MinecraftForge#3880]
I am fairly new to Minecraft Modding (I have around 5 years Java experience). 
I want to prevent vanilla bows from firing. Looking into the docs for Forge I came across the `ArrowNockEvent` which should allow me to cancel any bow actions.
But even thought the event is marked as `@Cancelable`, Forge still throws an `IllegalArgumentException` when I try to cancel the event.
Here is the code if I am doing something wrong:
```java
@SubscribeEvent(priority = EventPriority.HIGHEST)
    public void onHit(ArrowNockEvent event) {
        // not sure if machines can trigger this event
        if (event.getEntityPlayer() != null) {
            ItemStack bow = event.getBow();
            System.out.println(bow);
            System.out.println("Empty? " + ItemStackTools.isEmpty(bow));
            if (!ItemStackTools.isEmpty(bow)) {
                if(bow.getItem() instanceof ItemBow) {
                    event.setCanceled(true);
                }
            }
        }
    }
```

**Comment by Alpvax** [comment]
This should be on the forums.

**Comment by mainrs** [comment]
On the forums? What exactly do you mean? Posting in the forums? Sorry, I didn't see that their were any -.-

**Comment by williewillus** [comment]
`minecraftforge.net`

Also, according to the current repo code, ArrowNockEvent isn't cancelable. You might want to look at PlayerInteractEvent.RightClickItem instead

**Comment by mainrs** [comment]
Btw, do you guys need help with documentation? Doesn't look like a lot is documented that well.

**Comment by williewillus** [comment]
no @Cancelable annotation => it's not cancelable :P 

there's other parts of the code that need documenting but this area is self-explanatory as it is, IMO

**Comment by mainrs** [comment]
Not meaning this part, but some `{@inheritDoc}` would be fine. Which parts need some more docs in general?

**Comment by LexManos** [comment]
As for javadocs, we typically don't take single nitpicky things, if you want to do a massive overhaul of all the javadocs we MIGHT entertain it.
But the better option is to contribute to our RTD repo: https://github.com/MinecraftForge/Documentation

But yes, as a basic rule non-issues should be posted on the forums not here.

**Comment by mainrs** [comment]
> As for javadocs, we typically don't take single nitpicky things, if you want to do a massive overhaul of all the javadocs we MIGHT entertain it. 

> there's other parts of the code that need documenting but this area is self-explanatory as it is, IMO

Those might be self explainitory for those people who already have a lot of experience with Forge/Minecraft. But I really have a hard time to get the information that I would need to write some stuff. But I didn't know about the RTD, will check it out.

For example `getEntity()` and `getEntityPlayer()`. Both are available in a lot of events. But their isn't any description about what their relation is. Does `getEntityPlayer()` return the same entity as `getEntity()`? Will `getEntityPlayer()` always be non null if available (it's a player action, so it theoretically should). Those are some information that are imo missing.

Not sure if RTD is the right place for stuff like this. RTD looks more like a tutorial kind of thing. Those are implementation specific details I guess.

**Comment by Alpvax** [comment]
You could always use your IDE to check those things. May I suggest that you open a thread on the forums (http://www.minecraftforge.net/forum/) rather than commenting on this if you wish to continue this conversation.

**Comment by mainrs** [comment]
Ye sure I can, I know. The thing is, without doc there isn't much information to get out of the source code. Like, each event is just a POJO. 
Will do so. Not sure why you are against code comments to clarify stuff like that.

**Comment by Alpvax** [comment]
Then go back one level further, to where the event is created, and see what the parameters are set to. And we aren't opposed to better javadocs, we just don't want to bloat changelogs with "improved javadoc for X" commits.
Will not be responding to this issue. Move to the forums.

**Comment by mainrs** [comment]
No need to respond anymore, will create a forum entry. But "improved javadoc for X" commits are not a good reason to keep docs at all from source code. Whatever...
