### ISSUE TITLE
Mc - 1.11.2, Concurrent error during chunk generation and world saving

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3881]
My mod generates 4 chunks and decorates one of them, that phase repeats step times (default 16),
after that it use world.saveAllWorlds.
This is called in serverTick event.
https://gist.github.com/Endmateria/b5aa25206a4635db045cc2b861ef15b0#file-gistfile1-txt

**Comment by ghost** [comment]
Any response?

**Comment by LexManos** [comment]
Quit spamming our issue tracker, use the forums.
