### ISSUE TITLE
Game crash when creating/openning a world [since 2296]

### ISSUE THREAD

**Issue by ChuckNoxis** [MinecraftForge/MinecraftForge#3903]
Hi,

I've a lot of mods and I found a bug when I was updating my forge & mods.
When I'm trying to open an existant map or create a new one, it's crash for versions < 2295.

Here is my crash report.

[crash-2017-05-17_17.57.59-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/1008336/crash-2017-05-17_17.57.59-server.txt)

**Comment by Chocohead** [comment]
You need to update Optifine to the latest preview version (B9 pre)
