### ISSUE TITLE
[Vanilla Bug] The Frostwaker Enchanment breaks Forge Liquids

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3904]
The Frost Walker Enchanment turn any Block from Material Water into their Ice, wich smelt back to normal Water. This will turn any "modded" liquid into water.

**Comment by mcenderdragon** [comment]
What would be the better solution to fix this, adding a TIleEntity to the frozen ice wich stores the old block, or a (Weak)HashMap ? The problem with the mPa would be world saving and loading, but adding a TileEntity also feels not quite right.

**Comment by PrincessOfEvil** [comment]
Probably a getFrozenBlock in the fluid class and check for it and if it's
null, skip the enchantment.

**Comment by mcenderdragon** [comment]
I also noticed if someone makes a non BlockLiquid water block the frostwalker enchanment will most likely crash, because it tries to access the LEVEL property.

**Comment by Alpvax** [comment]
I would rather have a slightly raised ice "plane" (1px high) above the fluid rather than bypass the enchantment.

**Comment by diesieben07** [comment]
> I would rather have a slightly raised ice "plane" (1px high) above the fluid rather than bypass the enchantment.

How would that even work...

**Comment by PrincessOfEvil** [comment]
Well, not without adding a custom block, so probably unrealistic to add to Forge.

**Comment by diesieben07** [comment]
And if we do a `getFrozenBlock` there would need to be two variants, one for frost-walker and one for "normal ice".

**Comment by PrincessOfEvil** [comment]
boolean canMelt?

**Comment by diesieben07** [comment]
It's actually not just that. There are 3 types of ice in vanilla: the never-melting packed ice, the normally-melting ice and the always-melting frostwalker-ice.

**Comment by PrincessOfEvil** [comment]
Can you actually make packed ice from water, though?

**Comment by diesieben07** [comment]
No, but if we add such a method it would be nice to make it as useful as possible. One can imagine a "deep froster" from a mod which creates packed ice from liquids.

In any case, adding a method to IFluidBlock is not possible before 1.12 anyways.

**Comment by PrincessOfEvil** [comment]
I'm still thinking we're overthinking it. Why would anyone register three different blocks just for freezing? Special-casing vanilla is nothing weird in modding.

**Comment by mcenderdragon** [comment]
thats why is suggested a Map or TileEntity

**Comment by PrincessOfEvil** [comment]
Map is basically the same and tile is probably a vanilla-compat breaking
change.

**Comment by diesieben07** [comment]
This would be a simple fix: https://github.com/MinecraftForge/MinecraftForge/compare/1.11.x...diesieben07:frozen-blocks

**Comment by mcenderdragon** [comment]
@diesieben07 well then it is hard to add support for it as a Mod. But we can post an Event so a mod can do it, maybe a cancelable one to give the ability to block vanilla from freezing water.

**Comment by diesieben07** [comment]
Yes, and that's when we go down the rabbit hole...

**Comment by mcenderdragon** [comment]
But an event would be a clean solution and doesnt need any adition of getFrozenBlock or any of it, but has the power to prevent vanilla behauvier and adding own frozen blocks.

**Comment by AlexIIL** [comment]
Note that this doesn't happen for all modded fluids, as its possible to get all of the same effects as normal water by overriding a few methods and have a different material (which bypasses this issue)

**Comment by mezz** [comment]
I think the simplest solution here is to make them only work on water.
If you want something like oil-walker enchanted boots, it might be best to leave the implementation to a mod instead of extending vanilla functionality.

**Comment by diesieben07** [comment]
I will submit my implementation as a PR then.
