### ISSUE TITLE
Game Crashes When Loading Any World After Closing It (sp) Till Game Restart

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3910]
[crash-2017-05-21_12.41.59-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/1016808/crash-2017-05-21_12.41.59-server.txt)

If i close a world (disconnect) then try to load it again, game crashes. It's happening for a long time, i just wanted to report it. Sorry if it's not Forge's fault. I tried waiting 2 minutes before load, didn't help.
(used forge 2300 on mc 1.11.2)

**Comment by AEnterprise** [comment]
you do realize the top of your crash report states that you have alot of coremods and you should remove those before reporting to forge (like it sais in the report itself even), one of them is almost surely the cause of the crash

**Comment by ghost** [comment]
yes i'm working on it, but what if it's Forge's fault? cus it crashes only with Forge in crash log. this is why i reported to Forge, but i don't say it's Forge's fault. i just say it may be...

**Comment by diesieben07** [comment]
Use the forums for tech support.

**Comment by ghost** [comment]
tech support? you say it can't be Forge's fault? if it, then ok; i will report only the causing mod's github. but didn't understand what u mean with tech support

**Comment by diesieben07** [comment]
Tech support = help with figuring out what the problem is.

**Comment by mezz** [comment]
@kenijey you should not post on the Forge Github again. You have to go through the forums now.
You were given a final warning last time: https://github.com/MinecraftForge/MinecraftForge/issues/3865#issuecomment-298408963

http://www.minecraftforge.net/forum/
