### ISSUE TITLE
Biome tags are incomplete and erroneous

### ISSUE THREAD

**Issue by Robijnvogel** [MinecraftForge/MinecraftForge#3911]
Mesa biomes aren't tagged as DRY:
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/BiomeDictionary.java#L446-L448

Mutated biomes are tagged as SAVANNA:
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/BiomeDictionary.java#L468-L470

And there are probably quite a few other issues with biome tags.

Would it be okay for me to assemble a small team to go over the list with tags and submit a pull-request?

**Comment by liach** [comment]
Yes, you should absolutely create a pull request.

**Comment by liach** [comment]
@mezz Can you tag this one? I will work on this super easy one.

**Comment by Robijnvogel** [comment]
I've been meaning to really look into the list, since some other tags might be missing or incorrect as well, but I just have not gotten around to actually doing it.

**Comment by dargonforce** [comment]
taking a look at this, gonna make a branch
