### ISSUE TITLE
[1.11.2-2300] Bug names textures

### ISSUE THREAD

**Issue by Icosider** [MinecraftForge/MinecraftForge#3912]
Hi, found a bug, if the texture name written in small letters, then the texture will not work. Before such was not. Example:
Working
`"textures": {
        "layer0": "modid:items/food/myapple"
    }`
Not Working
`"textures": {
        "layer0": "modid:items/food/myApple"
    }`

**Comment by ichttt** [comment]
This is not a bug. It's the new Resource Pack version 3 introduced in minecraft 1.11. All resources have to be lowercase, or you must specify pack version 2 in your pack.mcmeta

**Comment by Icosider** [comment]
A very strange change.

**Comment by mezz** [comment]
This change is from vanilla Minecraft. 
I think we can agree it's strange to change it, but at least the format is consistent now.
