### ISSUE TITLE
[1.11.2] Netty Leak Error and Cascading World Gen Error

### ISSUE THREAD

**Issue by Stapleton** [MinecraftForge/MinecraftForge#3913]
This post is being made 10-20 minutes after seeing some errors in the console just after it finished loading the server.

MC Version: 1.11.2
Forge Version: 13.20.0.2303
Attached Log: fml-server-latest.log
Snippet from Multicraft server console: https://pastebin.com/x6wE0NbY

[fml-server-latest.txt](https://github.com/MinecraftForge/MinecraftForge/files/1017419/fml-server-latest.txt)

Don't really know how to continue with this but if you need any extra info, let me know.

**Comment by LexManos** [comment]
This is not the place for tech support, use the forums. http://MinecraftForge.net/

**Comment by Stapleton** [comment]
Not here for tech support. The server works. I am putting that there because I found out about these less than one hour after 2303 was released and thought that this is probably a thing that should be added to a 'to be fixed list' if it is of importance or if it is something that shouldn't be worried about, but I digress.

**Comment by LexManos** [comment]
This isn't a issue in forge, if it is 2303 wouldn't cause it.
Its most likely the coremods/mods you have installed, Again, this sin't the place for basic tech support. Use the forums.
