### ISSUE TITLE
[Vanilla Bug] StructureVillagePieces ignores removed components' weights when expanding village

### ISSUE THREAD

**Issue by Ivorforce** [MinecraftForge/MinecraftForge#3918]
# The Symptoms

When adding a larger number of buildings, the road networks get crazy large.

# The Problem

For reference: See class  c => func_176067_c => generateComponent

There is a 'total weight' variable i, which is calculated from the village's structureVillageWeightedPieceList sum of weights. After a component piece has reached its limit, it is removed from the list, but the total weight is not adjusted. This leads to an increasing amount of just torch roads returned later in the method.

# Solution Approach

Subtract the removed components' weight from the total weight on removal. Test if total weight reached < 0 and if so, return with null from the method.

**Comment by bs2609** [comment]
For reference, the vanilla bug is [MC-117872](https://bugs.mojang.com/browse/MC-117872).

**Comment by LexManos** [comment]
Looking at the code, this isn't what happening. If you'll notice when it selects a village piece and removes them from the list.
It immediately exits the function. Which means that next time the function is called the total weight is calculated again.
It would more seem that the mod you're using is trying to spawn pieces that can never/hardly ever be spawned so the village is trying to grow in radius to find a place for it to spawn.

Do you have a simple mod to show this issue?

**Comment by Ivorforce** [comment]
I think you might be correct. I'l reopen if I find anything else but I might just have been tired.
