### ISSUE TITLE
1.11 custom structures and /locate

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3932]
In 1.11, mojang added `/locate` to find nearest structures, but there's some problems with it:

1. Tab completion for the locate command uses a hardcoded list instead of the names registered with `MapGenStructureIO`. This can be easily fixed
2. The nearest structure is found via a call to the `IChunkGenerator`, which similarly has a long hardcoded if else chain delegating to the various `MapGenStructures.getClosestStrongholdPos` implementations. This is okay if the mod has its own `IChunkGenerator`, but if a modder adds their own MapGenStructure to the overworld there's no way for it to participate in `/locate`

Modders need a way to have their own `MapGenStructures.getClosestStrongholdPos` called from the overworld (and similarly other dims they don't control) `IChunkGenerator`, but I'm not exactly sure how it should be implemented.

**Comment by mezz** [comment]
If you look at `ChunkProviderFlat#getStrongholdGen` it has an implementation using a map. I think the overworld one could have a similar thing added just before the vanilla `return` line.

Also maybe I'm missing something but there doesn't seem to be a Forge hook in `ChunkProviderOverworld#provideChunk` or nearby for modded structures to generate.
It may be worth looking at if we want modded stuff to be able to generate at the right time and place.

I think we should also [open issues with MCP](https://github.com/ModCoderPack/MCPBot-Issues/issues) to rename `getStrongholdGen` and other stuff like that to be have a more general name.

**Comment by mezz** [comment]
Submitted an MCP issue here: https://github.com/ModCoderPack/MCPBot-Issues/issues/416

**Comment by maxanier** [comment]
I think the main issue here is that it is not possible to add your own MapGenStructure to the vanilla overworld generator (At least I haven't found one yet).

Therefore I have created #4496 some time ago. If this is merged, one could consider adding autocomplete to the locate command for the custom structures (in overworld or custom chunk generator)

**Comment by CatRabbit499** [comment]
This limitation of the /locate command is still an issue. There have been no forge hooks for adding or removing structures from the locate command since it was introduced in 1.11; 1.12.x and 1.13-pre as far as I can tell currently include no implementation of this feature. It would provide a valuable tool for modders to find and debug their custom structures with a direct query to the MapGenStructureIO and MapGenStructures.
