### ISSUE TITLE
Armors resist magic damage

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#3933]
I think the merge of #3838 caused this (paging @Flaxbeard)

Reproduction:
1. Put on diamond armor
2. Drink a poison potion
3. Open inventory and watch your armor take damage instead of you
4. Redo in vanilla and notice how you take damage and your armor doesn't

Forge 2309

**Comment by Flaxbeard** [comment]
Should be a fairly straightforward fix - just need to add `&& !source.isUnblockable()` on line 210 of ISpecialArmor.
https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/common/ISpecialArmor.java#L210

**Comment by williewillus** [comment]
@Flaxbeard can you make a PR if possible? I don't want to mess around without fully understanding the code, and this is a pretty major issue (it basically breaks any kind of armor piercing damage)

**Comment by talandar** [comment]
@Flaxbeard I'm not entirely sure that goes far enough.  Damage could be reduced in the block above (between 167 and about 208) and there are quite a few things going on there, like damaging the armor's ItemStack (188, 196).

Seems to me that if the damage is supposed to be unblockable, it should probably skip this function to apply armor entirely - either by returning the input damage amount near the top of ISpecialArmor::applyArmor or in the calling method in EntityPlayer (https://github.com/MinecraftForge/MinecraftForge/blob/c6f181dcb2a0a1fbc236e269b03b9fe5743e1246/patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch#L222)

I'll gladly make a PR to fix this, but I'm not familiar with the ISpecialArmor stuff, so I'm hesitant to just cancel the call entirely, in case there's something in ISpecialArmor that would mean it should ignore the `source.isUnblockable()` value.

Edit:
I should mention that the list of things this is breaking is rather large - hunger, poison, being on fire, in-a-wall damage, entity cramming, drowning, falling, and both wither damage and dragons breath damage.

**Comment by williewillus** [comment]
it would be nice if we can get a fix in before rb since this is a pretty mechanic-breaking bug

**Comment by KingLemming** [comment]
So...yeah, this actually breaks a game mechanic, guys.

*Some* armors should be able to partially block "Unblockable" damage.
