### ISSUE TITLE
ExtendedStateImplementation.getClean() optimisation?

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#3936]
While modding, I was looking at some sampling results during worldgen, and I saw that a lot of time was shown taken up by `getClean()`, which is called by `ExtendedBlockStorage.set()` if an extended state is passed in.
`getClean()` provides the 'clean' version of an extended state - that is, the state with no extended properties set. It does this by looking up the 'clean' state which corresponds to the set of property/value pairs the 'extended' state has.

The issue is that doing so requires a map lookup with the (property -> value) map as the key, which is fairly expensive, and more costly than operations on 'regular' blockstates.

Despite this, it's not a particularly noticable performance concern in most cases, as there are a whole load of other costs to something like `World.setBlockState()`. It is noticable when doing worldgen with many blocks that can have extended properties, though.

![worldgen_pre](https://cloud.githubusercontent.com/assets/1447117/26574077/ee7143c6-4517-11e7-9310-5c1e35d6f5b3.png)

Getting the clean state can be optimised for the usual case where the state in question is clean already. If this can be determined, then nothing else needs to be done, and the expensive part of the operation can be skipped.

As a result using extended states in this way has a much smaller overhead.

![worldgen_post](https://cloud.githubusercontent.com/assets/1447117/26574247/850d2386-4518-11e7-91d5-794116fea8c4.png)

Making this an issue instead of a pull request as it's not a huge deal, extended states are not massively used, and I'm not totally sure about the best implementation of a 'fast path'.

My initial attempt can be seen in this [gist](https://gist.github.com/bs2609/ccb56c1395f073df08dc99bf82c7d190).

**Comment by bs2609** [comment]
`withProperty()` could probably also be optimised for 'clean' states.

**Comment by LexManos** [comment]
Looking through this, and i'll have to discuss with fry, but this could be optimized quite a lot by skipping the whole caching of the propertyValueTable and just passing around the 'clean' IBlockState so getClean turns into return cleanState;

Leaving this here incase @RainWarrior wants to take a look at it: https://gist.github.com/LexManos/ab1ff6d17d3945158198893b1c4b3860

**Comment by bs2609** [comment]
The issue is about states that do have extended properties declared, but without values assigned. (basically where [this condition](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/common/property/ExtendedBlockState.java#L114) applies). Sorry if the "no extended properties set" wording was unclear.

**Comment by LexManos** [comment]
Ya, I was misunderstanding the first pass, i've edited my post since then.
I think my solution works, and it's a lot cleaner. The few debug mods in Forge seem to work fine. 
I'd just like Fry/someone else to take a look who is more familiar with the rendering system.
