### ISSUE TITLE
[1.11.2/1.12] Forge Liquids are not colorable

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3937]
Created fluids with forge are not colorable. I have both tried with IBlockColor and with Fluid.getColor(World,BlockPos).
I think they are uncolorable because they forge model doesn't set a tint index. I suggest to add setQuadTint(0) to the BakedQuad builder in ModelFluid (net.minecraftforge.client.model)

**Comment by RainWarrior** [comment]
Fluid.getColor() works, do you actually need different color value based on the world/position?

**Comment by mcenderdragon** [comment]
Yeah, because I have a custom water-like-fluid so I need biome specific colors.

**Comment by mcenderdragon** [comment]
This does also happen in 1.12
