### ISSUE TITLE
Kicked Whilst Connecting:  Packet was larger than expected

### ISSUE THREAD

**Issue by TrickyTroller** [MinecraftForge/MinecraftForge#3939]
Hello, recently I have been working on creating a custom modpack with about 200 mods.  I got it working today and was able to create a thermos server for it.  Upon joining the server, I get kicked with the message: "Internal Exception: io.netty.handler.codec.DecoderException:  java.io.IOException:  Packet was larger than I expected, found 71 bytes extra whilst reading packet 28" I have spent over four hours trying to fix this error but to no avail.  I suspect that it has something to do with forge.  Any ideas?

Forge Version: Forge-10.13.4.1614 (To my knowledge)
Java Version: Java 8u51
Full Error: https://pastebin.com/Q1ZLbf7V
(too large for pastebin)
Server FML Log:  https://we.tl/QxVE4q99yj
Server latest.log:  https://we.tl/XpIHkUh5ly
Client FML Log:  https://we.tl/ZDA8mYacKk
Client latest.log:  https://we.tl/M9orH4UrHi

**Comment by mezz** [comment]
Please use the [Forge forums](http://www.minecraftforge.net/forum/forum/18-support-bug-reports/) for troubleshooting this type of bug. 
This place is for when you are more certain it is a Forge bug.
Please use https://gist.github.com for long logs, it has no size limit and doesn't require downloading anything.
