### ISSUE TITLE
No seed entries causes a crash.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#3943]
When the game loads with no seed entries registered, the game will crash. The stack trace can be found [here](https://gist.github.com/darkhax/c89b868956bf44303c3ef85c1f1e6390). While forge offers no way to directly remove seed entries, several mods such as CraftTweaker provide ways to remove entries, and certain mods and modpacks have wanted the ability to remove all seed drops. 

Issue on 1.11.2, and tested using forge 13.20.0.2310

**Comment by LexManos** [comment]
Ah another mod reflectively hacking into things and breaking them.
I can add a workaround, But you should talk to CraftTweaker and tell it to fix situations like this.
