### ISSUE TITLE
[RFC] OreDictionary enhancement

### ISSUE THREAD

**Issue by HenryLoenwind** [MinecraftForge/MinecraftForge#3944]
(Sorry if I mess something up in the 1st writedown, I'm tired.)

After lengthy discussion and a good while of thinking about it, I think there may be a solution to fix most of the problems that nowadays arise from using the ore dictionary for things it was not intended for.

The current ore dictionary is meant to provide alternatives as the INPUT of recipes ("recipe" in the widest sense possible). So it very properly answers the question "I want to accept something with is oredicted as A, now I got the item X...does it match?". 

But often the ore dictionary is asked "my recipe should provide an item of oredict entry B, which one could I use?" (e.g. "oreCopper"->"dustCopper"->"ingotCopper"). Or the question: "I got item Y, to which item can I unify it based on oredict?" Using the current ore dictionary will get funny answers. For example, on the FC1 server, if you want to know what the result of a smelting recipe "cobblestone->stone" is, the answer may very well be "flint".

A simple an pragmatic solution may be to duplicate the ore dictionary. Instead of a static class it'd be an object with two instances: INPUT and OUTPUT. Mods would register their oredicting for recipe inputs in the INPUT dictionary, and oredict recipes would use this one to match input items. The new OUTPUT dictionary would be used to register output a.k. equivalency relations. That means, that all items that are registered to the same oredict key there can be freely exchanged. Recipes that produce oredict entries would look up the possible items there, and preferably use the first item in the list. Mods that want to unify items (e.g. Storage Drawers) would do their lookup there, too.

There are a number of pitfalls with this. First, an item can be registered with multiple OUTPUT oredict names. Semantics would dictate that this links those 2 names, making their item lists identical. This could be implemented in the oredict, or could be left as exercise to the oredict consumer. Secondly, there is no way for the user (or modpack maker) to select which item is the "winner" (s.k.a. first) item of a lookup. While I personally do not care, in a pack it might be desirable to select as many items as possible from the same mod to have a uniform look to the items. However, I'm really sure it would be very easy to write a tiny mod (or add it to modtweaker) to re-order the list.

**Comment by Darkhax** [comment]
Splitting them up sounds good to me, and I would definitely take advantage of a reliable output dictionary. Im not so sure that two output groups with the same item should be merged though, at least not on Forge's end. As for priority, I think going with the first entry is perfectly fine, and modpacks can re-order the list. I could add it to CraftTweaker/ModTweaker pretty easily. Also with 1.12 coming up, this is a good chance to discuss this.
