### ISSUE TITLE
[1.10.2] Crash when held ItemStack is set to null

### ISSUE THREAD

**Issue by ThexXTURBOXx** [MinecraftForge/MinecraftForge#3948]
Crashlog here: https://pastebin.com/x6V1jNY3

It happens, when I throw a boomerang or dynamite etc. from my mod "Reforged".

**Comment by Alpvax** [comment]
ItemStacks should no longer be null. Set them to ItemStack.EMPTY instead.

**Comment by KnightMiner** [comment]
@Alpvax this is a 1.10.2 crash

**Comment by ThexXTURBOXx** [comment]
Is 1.10.2 discontinued or why is this closed?

**Comment by TehNut** [comment]
Because tech support should go to the forums.

**Comment by Alpvax** [comment]
@KnightMiner my mistake, I skipped over 1.10 missing, I thought that was when it changed. Thanks
