### ISSUE TITLE
[1.12/1.11] HarvestCheck event not fired in important situation. 

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#3956]
I am not sure if this is intentional, but the HarvestCheck event is only fired when no item is used, the tool type of the item is null, or the harvest level of the tool is less than 0. These specific requirements really limit the event, and what it can do. For example, if I wanted to make a potion effect that temporarily made the player fail this check, or a curse enchantment that makes the item fail this effect, I couldn't do that with this event. 

In my specific situation I am trying to lower the mining requirements of ore blocks to that of stone.

**Comment by Aareon** [comment]
Please include the branch that you're using when creating an issue.

**Comment by Darkhax** [comment]
While this is still an issue, it would require breaking changes to properly fix. In the use cases I provided, it is possible to accomplish using the BreakSpeed event and factoring in the hardness before hand.
