### ISSUE TITLE
Support early freezing of forge registries

### ISSUE THREAD

**Issue by liach** [MinecraftForge/MinecraftForge#3957]
Some registries need early freezing. An example is a registry for tile entity block state property; they should be frozen right before the registry of textures. Currently, all registries are frozen around load completion; if you agree, I might make a pull request to allow registries to freeze early.

**Comment by williewillus** [comment]
You say "need" in the first sentence then follow with "should". Which is it? Can you give details why it's "need"?

**Comment by liach** [comment]
It is needed. An example is Railcraft's track kit/track type registry in which registered entries need to provide textures.

**Comment by LexManos** [comment]
It was decided that we are not making a registry sorting/prioritization system.
All registries could be 'frozen' at pre-init as all registry functions are fired by then so you should be fine relying on the data in them at the time. However in reality you should only ever trust whats in the registry at world load as thats after all id syncing and the like.
