### ISSUE TITLE
A fatal exception occurred during the server about to start event

### ISSUE THREAD

**Issue by CorneliusCornbread** [MinecraftForge/MinecraftForge#3960]
From time to time when I try and load up or create a world, it will refuse to get beyond the loading screen and will spit this out into console: https://pastebin.com/sMs9ZWAe
I'm using forge version: 12.18.3.2316
And MC version: 1.10.2

**Comment by covers1624** [comment]
Use the forums for Tech Support. http://www.minecraftforge.net/forum/
