### ISSUE TITLE
[1.12] Error downloading asm-all-5.1.jar

### ISSUE THREAD

**Issue by mcadventurecity** [MinecraftForge/MinecraftForge#3961]
So, I was testing Forge 1.12 (version 2321) and cannot launch the game, apparently due to an error downloading the library asm-all-5.1.jar. I have tried using the vanilla launcher and MultiMC, and get the error with both. Here is the segment of the log:
`23:12:18	launcher	Unable to download https://libraries.minecraft.net/org/ow2/asm/asm-all/5.1/asm-all-5.1.jar to C:/Users\owner\AppData\Roaming\.minecraft\libraries\org/ow2/asm/asm-all/5.1/asm-all-5.1.jar`

Thanks for your time,

MCA

**Comment by SteveKunG** [comment]
[Quick Fix] Download this to it directory : https://mvnrepository.com/artifact/org.ow2.asm/asm-all/5.1

**Comment by loordgek** [comment]
fixed
https://github.com/MinecraftForge/MinecraftForge/commit/54d26cb4cc3aef51728116f9ca9cff7e3f502dfd

**Comment by Nieki111** [comment]
Once i got the asm-all-5.1.jar where do i place this file?

**Comment by Nieki111** [comment]
Nevermind i got it i downloaded the file and put it in ".minecraft\libraries\org\ow2\asm\asm-all" i made a file named 5.2 and renamed the jar file to asm-all-5.2.jar and got it to work.

**Comment by VitinhowMitow** [comment]
Should I download this link? Or paste into some folder?

**Comment by WonderingReaper** [comment]
where is the asm-all-5.2 .jar?
