### ISSUE TITLE
[1.12] Chest not being rendered (sometime)

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#3962]
![2017-06-11_13 37 54](https://user-images.githubusercontent.com/6128413/27008955-47375102-4eab-11e7-8c0e-c8a7d0f5f441.png)

Forge : Build 2321
Testing on server side (realm)

Edit : Client side work fine.
![2017-06-11_14 30 23](https://user-images.githubusercontent.com/6128413/27009205-9c9d6b48-4eb2-11e7-8ab7-711d66c363e1.png)

Edit 2 : Really weird, it reappeared again.
![2017-06-11_15 08 31](https://user-images.githubusercontent.com/6128413/27009418-f1835294-4eb7-11e7-8332-718ad0aa671a.png)

**Comment by mezz** [comment]
@SteveKunG  Was this fixed?

**Comment by SteveKunG** [comment]
Can't reproduce with Forge 2364. Tested on both side (client/server)
