### ISSUE TITLE
[1.12] Remove IForgeRegistryEntry.Impl

### ISSUE THREAD

**Issue by liach** [MinecraftForge/MinecraftForge#3963]
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/registry/IForgeRegistryEntry.java#L67

Now we use Java 8, according to the comment this is safe to remove. This issue serves as a side note.

**Comment by williewillus** [comment]
I'm not sure if that's actually possible. The Impl defines several fields common to all registry entries and you can't define fields on interfaces (unless you want to patch it into everything which is more dirty than this.

**Comment by kashike** [comment]
The comment on that class means to move some of the methods (`setRegistryName(ResourceLocation)`, `setRegistryName(String, String)`) as `default` methods on the interface, most likely.

**Comment by loordgek** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/registry/IForgeRegistryEntry.java#L65 nope
how important/nice is it to remove Impl ??
can you stick those fields in a map and use V to get the fields ???

**Comment by liach** [comment]
This is not really possible now because of all the recipes.

**Comment by williewillus** [comment]
close?

**Comment by LexManos** [comment]
Its not possible because you can't have non-static fields in default interfaces which is required for delegate and name system.
So ya, Impl is never going away
