### ISSUE TITLE
[1.12] MercuriusUpdater not available for 1.12

### ISSUE THREAD

**Issue by Aareon** [MinecraftForge/MinecraftForge#3966]
Not sure if deprecated or not, but the installer is trying to access this file on the webserver and it cannot be found. Further research concludes that it does not exist. The following link causes a distasteful experience;
[http://files.minecraftforge.net/maven/net/minecraftforge/MercuriusUpdater/1.12/MercuriusUpdater-1.12.jar](http://files.minecraftforge.net/maven/net/minecraftforge/MercuriusUpdater/1.12/MercuriusUpdater-1.12.jar)

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MercuriusUpdater/commit/75f1d8c6504d0b7cbda9b497f4ac652797704d66
