### ISSUE TITLE
[1.12] GUIButton method drawButton has new argument, decompiled as func_191745_a

### ISSUE THREAD

**Issue by Daedalus1400** [MinecraftForge/MinecraftForge#3971]
GUIButton method valid in 1.11.2:

    drawButton(Minecraft minecraft, int mouseX, int mouseY);

has been replaced by the following in 1.12:

    func_191745_a(Minecraft p_191745_1_, int p_191745_2_, int p_191745_3_, float p_191745_4_);

Passing (this.mc, mouseX, mouseY, partialTicks) to the above 1.12 function produces normal GUIButton behavior.

Suggested:
Rename

    func_191745_a(Minecraft p_191745_1_, int p_191745_2_, int p_191745_3_, float p_191745_4_);

to  

    drawButton(Minecraft minecraft, int mouseX, int mouseY, float partialTicks);

**Comment by kashike** [comment]
...and it will be named soon. This repository is not for suggesting member names.

**Comment by Daedalus1400** [comment]
My apologies.  Where should something like this be reported?

**Comment by kashike** [comment]
Nowhere. It's an unnamed method and it will be named by someone as soon as possible.

**Comment by Actuarius** [comment]
@tterrag1098 closed this issue

**Comment by Alpvax** [comment]
> My apologies. Where should something like this be reported?

[MCPBot](http://mcpbot.bspk.rs/)
