### ISSUE TITLE
launcher.java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by EmanYm** [MinecraftForge/MinecraftForge#3972]
[This](https://hastebin.com/jufuhemaco.vbs) is all I get in my console.  Rinse and repeat ten times...

Hosted server
`Java is OpenJDK 64-Bit Server VM, version 1.8.0_45-internal, running on Linux:amd64:2.6.32-44-pve, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre`
Minecraft Forge: 1.11.2-13.20.0.2315
SpongeForge: 1.11.2-6.1.0-Build 2378

**Comment by covers1624** [comment]
Use the Forums for Tech Support http://www.minecraftforge.net/forum/.

**Comment by EmanYm** [comment]
I am not seeking tech support.  I am seeking help with an issue, and I assumed that was what this tab was for.
Posting on the forum would also requiring me to create a forum account.

Now that it's not one o'clock in the morning I know what the problem is.
I still had `minecraft_server.1.10.2.jar`.
I just installed forge server files locally and uploaded the .jar and libraries to my server.  No longer getting this issue.

**Comment by raoulvdberge** [comment]
> I am not seeking tech support

> I am seeking help with an issue

I do not see the difference.

This is for actual Forge bugs, not support.

**Comment by EmanYm** [comment]
From my side, it seemed like a bug.  (At that time of night everything feels like a bug.)
It turns out is was `ERROR ID: 10T`

Regardless, I fixed it.  I apologize for posting on the wrong platform.
