### ISSUE TITLE
[1.12] Patch CraftingManager.func_193376_a() to support modded recipe types

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3973]
Currently this method gets a JsonObject and returns an IRecipe.
I think we can easily implement a RecipeTypeRegistry to add modded recipes (wich can then support stuff like oreDict or complette custom stuff)

**Comment by Darkhax** [comment]
Lex has opened a discussion on the recipe changes here: https://gist.github.com/LexManos/2a11d4f7aa9d680d861dae4faf9dcfa6

**Comment by mcenderdragon** [comment]
Seems like the _factories.json is exactly what I want.

**Comment by williewillus** [comment]
can be closed now?
