### ISSUE TITLE
[1.12] Possible race condition when joining SP

### ISSUE THREAD

**Issue by Johni0702** [MinecraftForge/MinecraftForge#3974]
Using MDK 2322, joining SP sometimes locks up MC.
It shows a "0%" dirt screen, throws several similar looking exceptions into the log (fist join was fine, the second one got stuck https://pastebin.com/raw/m9913ixK) and leaves one no choice but to close it.

This seems to be reliably reproducible by putting a thread-only breakpoint [on the first line of NetworkDispatcher.clientListenForServerHandshake()](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java#L237) and thereby artificially delaying that thread by a few moments when the bp is first hit.

I could not reproduce it on 1.11.2 (tried build 2216 because I had it laying around).

**Comment by bs2609** [comment]
Think this was fixed by #4220.

**Comment by Johni0702** [comment]
Just tested it again with build 2456, MC is still locked up when placing the thread-only bp [at that line](https://github.com/MinecraftForge/MinecraftForge/blob/28e341002f7f338bb9cc490ef3a7270c7b9c99f6/src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java#L234) and waiting for a few seconds after it's hit.
I no longer see any errors in the log though.

**Comment by Niko-sk2x** [comment]
Can you test if #4304  fixes it? I think it may be the same issue, just clientside, and my PR should fix both.

**Comment by Johni0702** [comment]
@Barteks2x, doesn't seem like it. Still locks up if delayed at that bp. No errors in the log.

**Comment by Niko-sk2x** [comment]
I will see if I can also debug and fix that, while I'm on fixing network code. Also does it happen in 1.11.2?

**Comment by Johni0702** [comment]
> I could not reproduce it on 1.11.2 (tried build 2216 because I had it laying around).

**Comment by Niko-sk2x** [comment]
Can you confirm that together with #4304 adding this line:
```java
this.manager.channel().pipeline().addBefore("packet_handler", "fml:flow_control", new FlowControlHandler());
```
before
```java
ChannelPipeline cp = this.manager.channel().pipeline().addBefore("packet_handler", "fml:packet_handler", this);
```
in `NetworkDispatcher#insertIntoChannel` fixes it?

**Comment by Johni0702** [comment]
I can **not** confirm that. It seems to still lock up when delayed at that bp. This is what I'm running:
![NetworkDispatcher#insertIntoChannel](https://i.johni0702.de/Jn.png)

**Comment by Niko-sk2x** [comment]
Strange... It worked for me.. I will debug more tomorrow

**Comment by Niko-sk2x** [comment]
This can also be closed now
