### ISSUE TITLE
[1.12] Horse Armor/Cantle hook?

### ISSUE THREAD

**Issue by LeScooter** [MinecraftForge/MinecraftForge#3975]
Since the 1.12 API is relatively new, it would be great to finally have a hook into custom horse armor.
Would be great for people who have new ingots/resources they'd like players to be able to craft into horse armor.

Fetching horse armor/saddle, setting horse armor/saddle etc. It'd be neat

**Comment by 3TUSK** [comment]
There was an attempt (#3185), but has been closed for a while due to inactivity. You might want to consider about updating that pull request.

**Comment by Darkhax** [comment]
Horse armor is actually pretty tricky to add. You have to make sure that the vanilla horse's code is being extended, without breaking compatibility for vanilla clients connecting, and also make sure that horses won't crash if the armor they have is no longer valid. It's possible to do, but it's actually a fairly big patch. That is why I abandoned my PR attempt for it. Feel free to make a PR based off of mine.

**Comment by mezz** [comment]
This has a PR in-progress, not stale.
