### ISSUE TITLE
[Suggestion] ObjectDictionaries

### ISSUE THREAD

**Issue by rguy96** [MinecraftForge/MinecraftForge#3977]
As a replacement for the OreDictionary and BiomeDictionary, I suggest an ObjectDictionary of sorts. Essentially it would be the same as the those two, but it would be oriented around IForgeRegistryEntry instances and use tags to index them. There should also be sub-dictionaries, so it would be easy to differentiate between recipes and some sort of weird elemental system from another mod. It would be centered around jsons, similar to the new [recipe system](https://gist.github.com/LexManos/2a11d4f7aa9d680d861dae4faf9dcfa6), jsons like this:

assets/MODID/dictionary/minecraft/items/ender_rod.json

`"tags": [ "magical", "weapon", "ranged" ]`

And for sub dictionaries, an array in the same file named "sub_dictionaries"
`[
     {
        "name": "minecraft:recipes",
        "inherit": true
    },
    {
       {
            "name": "thaumcraft:elements",
            "tags": [ "magic/10", "water:10", "ender:64" ]
       }
    }
]`

Conditionals should be supported too.

The actual coding and the logic is a bit more complex.

First, the class

`public static final class ObjectDictionary<I extends IForgeRegistryEntry> implements Function<Predicate<Set<String>>, Set<I>`

`I` is refers to object's type. Why the class implements `Function` will be explained below.

Second, the variables:

`public final Map<I, Set<String>> OBJECT_TO_TAGS`,
`public final Map<String, Set<I>>TAG_TO_OBJECTS`,
`public final Set<String> TAGS`.

Those should be pretty self explanatory. All three of these variables should be unmodifiable maps and sets

Now methods:

A method named `apply(Predicate<Set<String>>)`, will scan through the `OBJECT_TO_TAGS` map and return `Set<I>` of the objects that apply to the provided predicate. And for simplicity a method named `withTags(String[])` would take all of the provided strings, ensure that they all exist in the `TAGS` , and make a call to `apply`, scanning for objects that contain all of the provided tags. Unused tags should be permitted.

The purpose of this should be to make creating APIs and standards easier to link between mods.

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Feature, Needs PR]
