### ISSUE TITLE
JVM crash when using Narrator on OS X

### ISSUE THREAD

**Issue by shadowfacts** [MinecraftForge/MinecraftForge#3978]
[JVM crash report](https://gist.github.com/shadowfacts/5f71513c228f67611c58231e32fb7e46)

While Hwyla/Waila appears in this stack trace, that's just because it's the first thing to use the Narrator and this would happen without Hwyla whenever Vanilla first uses the Narrator.

This is a Forge bug as the narrator works normally on Vanilla.

**Comment by JDLogic** [comment]
It looks like this is actually an issue with Hwyla. The mod is repeatedly spamming the `Narrator.getNarrator()` function in Mojang's text2speech lib, which is bad.

**Comment by shadowfacts** [comment]
Ah, yup, this is an Hwyla issue. https://github.com/TehNut/HWYLA/pull/73
