### ISSUE TITLE
[1.12] ShapedOreRecipe throws UnsupportedOperationException

### ISSUE THREAD

**Issue by darkevilmac** [MinecraftForge/MinecraftForge#3979]
This is due to a call of NonNullList.add on a list backed by a list that can't be resized. Replacing these calls with NonNullList.set will fix the issue.

The exception is on line 152 of net.minecraftforge.oredict.ShapedOreRecipe

**Comment by LexManos** [comment]
Ya, it's in my local copy of a major re-write of the recipe system. Just waiting for cpw to help me out on part of it {registry fun y.y} before pushing.

**Comment by fnuecke** [comment]
If this is on your screen please ignore this comment, just to make sure it doesn't slip through: in the changes pushed earlier which look like said major rewrite this has moved into [CraftingHelper.parseShaped](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java#L337).

**Comment by tterrag1098** [comment]
I think this commit may have broken using spaces for 'empty' spots in recipes. I get this exception now:

```
Caused by: java.lang.IllegalArgumentException: Pattern references symbol ' ' but it's not defined in the key
	at net.minecraftforge.common.crafting.CraftingHelper.parseShaped(CraftingHelper.java:343)
	at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:67)
```

for this recipe:

```
                addShapedRecipe(new ItemStack(bookshelves[c], 1), "S S", "BBB", "S S", 'S', new ItemStack(stairs[c], 1), 'B', new ItemStack(Items.BOOK, 1));
```

(addShapedRecipe is my own method which directly proxies to `new ShapedOreRecipe`)

**Comment by Shadows-of-Fire** [comment]
I saw the same issue when i was fixing ShapedOreRecipe locally, but it was due to calling `input.set(x, itemMap.get(chr));` when spaces aren't registered to that map.  Doing a nullcheck and passing `Ingredient.EMPTY` when the map returns null fixes this issue.

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/3990

**Comment by darkevilmac** [comment]
Odd, I'm not having this issue.

**Comment by LexManos** [comment]
Been fixed
