### ISSUE TITLE
[1.12] Item.getItemFromBlock returns null (air) for all vanilla doors.

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#3981]
Since `Item.getItemFromBlock` returns `Item item = BLOCK_TO_ITEM.get(block);` with a null check to return `Items.AIR`, it appears that an Item for all the vanilla doors (`Blocks.IRON_DOOR` etc.) is not registered to this map.

**Comment by Shadows-of-Fire** [comment]
Upon further inspection this seems to be the case for all vanilla blocks with custom itemblocks, such as cauldrons and brewing stands.

**Comment by diesieben07** [comment]
Yes, this is not a bug.

**Comment by Actuarius** [comment]
@tterrag1098 closed this issue

**Comment by tterrag1098** [comment]
This is true for any block without a trivial mapping to an itemblock. Doors have been special cased like this for a long time.
