### ISSUE TITLE
[1.12][Suggestion] Add multiple Listeners to AdvancementList

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#3982]
Currently an AdvancementsList as a singel field storing only one Listener. I am pretty sure if 2 mods use this they will more or less overrite each other.
I suggest changing them to some kind of collection.
If we patch this into vanilla code we also need a remove function, else we will create memory leaks because vanilla handles things differntly (it overide just the old listener).

**Comment by williewillus** [comment]
that's because there is only supposed to be one listener.

what do you need to listen here for?

**Comment by loordgek** [comment]
is using events a option ??

**Comment by williewillus** [comment]
there aren't any events yet because this is new, but the use case should be better articulated so we know where to add things

**Comment by mcenderdragon** [comment]
As I uccrently dotn know how forge is going to support advancements, I started to implement my own loader and due to possible reloads e.g. F3+T all my advancements would get deleted sp I need to listen to func_191930_a/advancementscleared to re add them.

Edit: Also yes events would be propably nice.

**Comment by williewillus** [comment]
So you need it to support a temporary hack?

**Comment by mcenderdragon** [comment]
If forge add full support then this is not needed. But I need Events fired before & after the player gets an advancement.
