### ISSUE TITLE
[1.12] The recipe book won't work on modded guiContainer

### ISSUE THREAD

**Issue by zlainsama** [MinecraftForge/MinecraftForge#3984]
There is a hard-coded line to check if the container is 'ContainerWorkbench' or 'ContainerPlayer'.
The recipe book won't put items into the crafting grid if the guiContainer does not derive from those two vanilla containers.

It's in GuiRecipeBook
private void func_193945_a(IRecipe p_193945_1_, RecipeList p_193945_2_)

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Feature, Needs PR]
