### ISSUE TITLE
[1.12] Crash when going into the "Controls" tab of options

### ISSUE THREAD

**Issue by Fortanono** [MinecraftForge/MinecraftForge#3985]
"The game crashed whilst updating screen events"

Also, crash report: https://pastebin.com/5NsqamA0

**Comment by marvin-roesch** [comment]
This is due to custom key binding categories (which mods often use to group their own key bindings) not being included in the `CATEGORY_RANKINGS` (`field_193627_d`) map. Forge needs to expose that map via an AT or some registry functions.
