### ISSUE TITLE
Tile entity registry is not in ForgeRegistries class

### ISSUE THREAD

**Issue by liach** [MinecraftForge/MinecraftForge#3986]
Now blocks, crafting recipes, entities, and items are all organized by registries. Should block entities be organized by registries too?

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/tileentity/TileEntity.java.patch#L11

**Comment by liach** [comment]
However it is not all: https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/registry/ForgeRegistries.java
The tile entity registry is not in `ForgeRegistries` yet.

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Cleanup]

**Comment by maxanier** [comment]
However, the TileEntity registry is a LegacyNamespacedRegistry and not a FMLControlledNamespacedRegistries and thereby does not implement IForgeRegistry. So I don't think it would fit to ForgeRegistries.
Not sure if the tileentity registry can migrate to a FMLControlledNamespacedRegistry as they are tightly connected to a block (via class name).
So converting it to a FMLControlledNamespaced Registry would only make sense if the ITileEntityProvider#createTileEntity would use ObjectHolder variables for tile instantiation.

Converting this would allow to use a RegistryEvent for registration as well as substituting block's tiles without substituting the block itself.

**Edit:**
But Lex says it's not worth it and that's probably true:
https://github.com/MinecraftForge/MinecraftForge/pull/4046#issuecomment-310454978
