### ISSUE TITLE
[1.12] java.lang.reflect.InvocationTargetException on startup

### ISSUE THREAD

**Issue by MiningMark48** [MinecraftForge/MinecraftForge#3991]
On startup, `java.lang.reflect.InvocationTargetException` is thrown and says it is caused by `java.lang.NoSuchMethodError: org.apache.logging.log4j.Logger.info(Ljava/lang/String;Ljava/lang/Object;)V`.

**Using:** 1.12-14.21.0.2325

Full log: [Here](https://pastebin.com/DMzKyAtY)

**Comment by williewillus** [comment]
> Loading deobfuscation resource C:\Users\Mark\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_snapshot\20161220\1.12\srgs\srg-mcp.srg with 36059 records

Try some newer mappings :P

**Comment by LexManos** [comment]
Most likely you're missing dependencies, make sure you update FG's dep and clean your workspace.

**Comment by MiningMark48** [comment]
Tried newer mappings and tried refreshing dependencies as well as cleaning workspace using `gradlew cleanCache clean setupDecompWorkspace --refresh-dependencies` but still no luck.

**Comment by LexManos** [comment]
http://puu.sh/wkrEf/8e1624003c.jpg
log4j clearly has the function, what version of log4j do you have in your workspace, Mojang did update it, so if you have any custom stuff you will need to update.

**Comment by MiningMark48** [comment]
Updated to 2.8.1, works past that point. Then crashes on a NoSuchMethodError with `com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object`

Assuming I need to update that as well.

**Comment by MiningMark48** [comment]
Mostly good now, just gotta update dependencies.

**Comment by MiningMark48** [comment]
All good now and working. Thanks again.
