### ISSUE TITLE
Oredict recipes do not allow null group

### ISSUE THREAD

**Issue by tterrag1098** [MinecraftForge/MinecraftForge#3993]
Vanilla allows `null` for the group, which just returns the empty string from `func_193358_e`. I believe that `ShapedOreRecipe` and `ShapelessOreRecipe` should follow suit and allow null.

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Bug]

**Comment by williewillus** [comment]
is the fix to just change `group.toString()` to `group == null ? "" : group.toString()`?

**Comment by tterrag1098** [comment]
That's what vanilla does, so probably.
