### ISSUE TITLE
One-to-many recipes vs. Recipe Book support (IRecipeFactory? Recipe Book hook?)

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#3996]
I have run into an usecase where I'd like to generate many recipes from one JSON. The specific usecase involves recipes which are used for one item and many combinations (for instance, a barrel which can be crafted out of many wood types and has different NBT tags depending on the particular wood type used, or a shelf which can be crafted out of many wood types. BiblioCraft is a good example, and so are Factorization/Charset barrels).

I am aware that I could just return a single IRecipe, but this leads to sub-par integration with the Recipe Book's grouping functionality. At the same time, I cannot pre-generate the JSONs in question as I cannot predict the set of wood (or metal, or etc.) blocks in a modpack, as I am using an automatic detection system for them. In my opinion, it might be valuable to add one-to-many mapping possibilities for JSON recipe factories (by returning a Collection<IRecipe>), though it has to be kept in mind that ensuring different registry names would then fall on the developer. On the other hand, this could quickly lead to the amount of IRecipes escalating and slowing down modpack functionality such as auto-crafting.

Another solution is to add a hook for an IRecipe to interact with the Recipe Book, providing multiple "example ingredient layouts", or something of the sort (@amadornes suggested an Iterator<Ingredient[]>). I think it could be a better solution, but I'd like to request input on that.

This could be implemented in a non-breaking manner with a "default Collection<IRecipe> parse" which returns a singleton list unless overridden.

I'd like to request thoughts on this issue.

**Comment by liach** [comment]
Such recipes, as long as they don't deal with nbt, should be able to get generated during runtime and write into jsons.

**Comment by liach** [comment]
Or we can just add OreIngredient support for jsons, that may help too.

**Comment by asiekierka** [comment]
@liach It doesn't help my specific case, as ore dictionary allows for many-to-one recipe mappings (many combinations of resources give one item as a result). (Also, you can just add a _factories.json yourself.)

**Comment by liach** [comment]
Don't ingridients already allow different types of item stacks?

**Comment by liach** [comment]
@asiekierka I want to make a follow up discussion. In https://github.com/MinecraftForge/MinecraftForge/pull/4472#issue-267169746, the recipe json shows that one-to many recipe json is possible. You should close this one.

**Comment by asiekierka** [comment]
That issue seems to have nothing to do with what I was talking about, though?

**Comment by liach** [comment]
uhh, i mean that's if you need a few possibilities you can use such mode
