### ISSUE TITLE
[1.12] Ingredient.fromStacks() ignores ItemStacks with Meta

### ISSUE THREAD

**Issue by ThexXTURBOXx** [MinecraftForge/MinecraftForge#3997]
I made a mod, which adds Quarries to the game.
One recipe needs a Wither Skeleton Skull:
https://github.com/ThexXTURBOXx/MegaQuarry/blob/master/src/main/java/de/thexxturboxx/megaquarry/MegaQuarryRegistry.java#L77
The Stack gets converted to a Ingredient, using Ingredient.fromStacks() in Line 32.
This is a pretty weird issue, so I made a video showing, what is wrong (See Video description for more info, about, what I'm showing):
https://www.youtube.com/watch?v=5OIKAAZr-b4

**Comment by TehNut** [comment]
IIRC, Skulls don't have a proper itemblock. You want Items.SKULL

**Comment by ThexXTURBOXx** [comment]
That's odd. In 1.11.2 I could do it like this...
Well, now the recipe works, but there is still a bug, if someone tries it with Blocks.Skull.
So, this is half-fixed for now. Thanks ;)

**Comment by TehNut** [comment]
It's not a bug. That's just how Vanilla works. Other blocks act similarly, like Doors.

**Comment by ThexXTURBOXx** [comment]
No, not that "bug". I mean the bug, that you can use those items and the entire recipe doesn't work (there isn't even anything in the log)

**Comment by TehNut** [comment]
That is also not a bug for the same reason. Look at how the ItemStack constructor that takes a Block works.

**Comment by LexManos** [comment]
Yes sadly Vanilla's implementation of  Ingredient.fromStacks silently ignore empty itemstacks. And the ItemStack constructor does as well. But hey what can you do.. just be more careful with your recipes.
