### ISSUE TITLE
OreIngredient passes ItemStacks the wrong way to the OreDict

### ISSUE THREAD

**Issue by Xalcon** [MinecraftForge/MinecraftForge#3999]
I know the recipe system is still in-flux but since this bug seem to be not known yet, I thought I report it.

I've setup a recipe which contains an OreIngredient entry: https://gist.github.com/Xalcon/06ca8d7ddad47e3980e2c66c84e7ae8c

JEI shows the correct recipe, but its not craftable. If I replace the OreIngredient with a normal item, it works just fine:
`{ "item": "minecraft:log", "data": 0 }`

It looks like the error is in the `OreIngredient` class, inside the `apply()` method. It calls `OreDictionary.itemMatches(target, ore, false)` where `target` is the input itemstack from the craft matrix and `ore` is the OreDict Itemstack. Now, the `itemMatches` method checks the first parameter `target` if its damage value is equal to the OreDict wildcard - but since the `target` parameter is the craft matrix input stack, this check will always fail.

Looks like the parameter names caused a bit of confusion here :)

Edit: Tested on Forge 14.21.0.2327

**Comment by LatvianModder** [comment]
Here's full json for testing:

```json
{
	"type": "minecraft:crafting_shaped",
	"result": {
		"item": "minecraft:log",
		"data": 0
	},
	"pattern": [
		"SSS",
		"S S",
		"SSS"
	],
	"key": {
		"S": [{"type": "forge:ore_dict", "ore": "logWood"}]
	}
}
```
