### ISSUE TITLE
Versions when Building from Master Mismatch

### ISSUE THREAD

**Issue by CDAGaming** [MinecraftForge/MinecraftForge#4001]
When i build forge 1.12, The Version lists as 14.21

However, on [The Forge Downloads Page](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.html) the version displays higher, making the built copy always out of date

**Comment by LexManos** [comment]
What are you doing? 14.21 is the current version. And you shouldn't be manually building Forge for distribution.

**Comment by CDAGaming** [comment]
@LexManos I'll be more specific

Actual Behavior:
Version with Master: 14.21
Version on Forge Downloads: 14.21.0.2328

Expected Behaviour is for Version with Master to be = to or Greater then 14.21.0.2328

Also, i just prefer building forge for my own sake, because I genuinely like to see and test the latest changes.

**Comment by rguy96** [comment]
I think they're referring to the fact that in the main menu it says the version is 14.21.0.0 when it should be 14.21.0.2328.
![image](https://user-images.githubusercontent.com/23139795/27202301-030557b2-51ef-11e7-81e5-89798cbeaccd.png)

**Comment by CDAGaming** [comment]
Yes, as well as the build files themselves saying its 14.21.0.0

**Comment by diesieben07** [comment]
The build number is replaced automatically by the continuous integration build. There is no point in building your own version, CI automatically builds on new commits and pushes it to the website.

**Comment by CDAGaming** [comment]
Ok, thanks. Closing
