### ISSUE TITLE
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by EmanYm** [MinecraftForge/MinecraftForge#4005]
[The error](https://hastebin.com/jexehazagi.vbs)

MinecraftForge 12.18.3.2316
SpongeForge 1.10.2-2281-5.2.0-BETA-2379

My configs are all fine to connect to Bungeecord.  It's basically the same as the other server that is working.
I thought it might have been the libraries, so I grabbed fresh ones.
Then I thought my forge was corrupt, so I downloaded a fresh copy and uploaded that.
Then I figured it might be SpongeForge, so I downloaded a fresh copy of that, too.
Maybe it's one of my chosen mods/plugins.  Nope, happens with nothing in the mods folder.
Let's try downgrading forge one version to 12.18.3.2297.  Nope, still the same message.

The only other thing I can think of is to install a server version locally and move the files generated to my server.

**Comment by LexManos** [comment]
Not the place for basic tech support use the forums.

**Comment by EmanYm** [comment]
How is this not some kind of bug?  I have already tried everything I can think of to remedy the issue with no success.  What more can be suggested on the forum I have not already tried myself?  I have had the same error thrown after each of the steps I tried.

**Comment by LexManos** [comment]
The error is simple, you fucked up the install and it cant find all the libraries you need delete the server and try again. We have an installer for a reason.
This is NOT a bug, its you screwing something up.
And again this is NOT the place for things that are NOT bugs.
