### ISSUE TITLE
Impossible to use NBT on result for regular shapeless crafting recipe

### ISSUE THREAD

**Issue by raoulvdberge** [MinecraftForge/MinecraftForge#4008]
`minecraft:crafting_shaped` uses this:
```java
ItemStack result = CraftingHelper.getItemStack(JsonUtils.getJsonObject(json, "result"), context);
```
`minecraft:crafting_shapeless` uses this:
```java
ItemStack itemstack = ShapedRecipes.deserializeItem(JsonUtils.getJsonObject(json, "result"), true);
```
This is problematic, as `deserializeItem` doesn't allow for an `nbt` field. Perhaps `deserializeItem` should be removed entirely.

Result:

Shaped crafting with NBT as result works
![x](https://raoulvdberge.com/Ynv7Kn)

Shapeless crafting with NBT as result doesn't work
![x](https://raoulvdberge.com/MaxI4j)

`minecraft:crafting_shapeless` should use `CraftingHelper#getItemStack` instead of `ShapedRecipes#deserializeItem`.

This issue is similair to #4004, but that one is for shapeless ORE recipes. This is regular crafting.

**Comment by LatvianModder** [comment]
Another important thing that breaks other than nbt (though, less important) - result item doesn't work without prefix, so you have to use `yabba:barrel` and `barrel` won't work
