### ISSUE TITLE
Inconsistent stackmap frames at branch target 13

### ISSUE THREAD

**Issue by tbasten** [MinecraftForge/MinecraftForge#4009]
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.VerifyError: Inconsistent stackmap frames at branch target 13

**Comment by canitzp** [comment]
Post the whole crash-report or log file please and provide some more information about your environment, like mc version.
It seems like it is a asm error, so it's very likely that it isn't forge at all

**Comment by tbasten** [comment]
How do you get the full crash report? Haven't done this before

**Comment by tbasten** [comment]
Ok, checked the crash-log, found the problem. Thanks!

**Comment by canitzp** [comment]
Inside the folder of your minecraft instance is a crash-reports folder and inside this is a fml client latest log file. I can't tell you where you find your mc instance folder, since this depends on the launcher you're using

**Comment by diesieben07** [comment]
The FML log is in /logs/ not /crash-reports/. For the future: Use the forums for tech-support.

**Comment by tbasten** [comment]
Thought I was helping out. Sorry!
