### ISSUE TITLE
[1.11.2] Crash on start - Forge 1.11.2 - 13.20.0.2315

### ISSUE THREAD

**Issue by Sejoslaw** [MinecraftForge/MinecraftForge#4010]
Minecraft crash when I try to start it.
[Crash log](https://pastebin.com/LtnFA936)
`java.lang.NoClassDefFoundError: 
    at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:221)`

**Comment by diesieben07** [comment]
Use the forums for tech support.
