### ISSUE TITLE
Impossible to use custom conditions/recipes/ingredients registered from code

### ISSUE THREAD

**Issue by shadowfacts** [MinecraftForge/MinecraftForge#4014]
Custom recipe conditions registered via `CraftingHelper.register` currently cannot be used. This is due to `CraftingHelper.init`, which clears the conditions, recipes, and ingredients maps, being called before mod recipes are loaded. Any condition/recipe/ingredient factories registered during pre-init will be cleared from the map upon recipe-loading, preventing them from being used.

**Comment by LexManos** [comment]
I know, that is intended. The idea is to fire an event in the reload sequence to gather code level stuff.
Right now those are not supported. Use the Json system.

**Comment by JamiesWhiteShirt** [comment]
This is still an issue after #4015 was pulled.

The public registration methods are currently useless. I'm guessing we need that event to fire after all minecraft/forge conditions/recipes/ingredient factories are registered and before recipes are parsed.

**Comment by LexManos** [comment]
Use the jsons. I should remove the public register methods they were just boiler plate when I first wrote it.
