### ISSUE TITLE
[1.12] Shaped and ShapelessOreRecipes appear to display missing textures for Item or Block ingredients that are not ItemStacks.

### ISSUE THREAD

**Issue by elucent** [MinecraftForge/MinecraftForge#4016]
Minecraft version: 1.12
Forge version: 1.12-14.21.0.2331

When I use the following code to register a ShapedOreRecipe...

```
    GameRegistry.register(new ShapedOreRecipe(getRL("teabag_empty"),new ItemStack(teabag,4),true,new Object[]{
				"  S",
				"PP ",
				"PP ",
				'S', "string",
				'P', new ItemStack(Items.PAPER)}).setMirrored(true).setRegistryName(getRL("teabag_empty")));
```
...the recipe displays just fine.

![image](https://user-images.githubusercontent.com/9532786/27248385-a499025e-52d0-11e7-8b9b-602d0e88360d.png)

But if I remove the ItemStack constructor around Items.PAPER, for example...

```
    	GameRegistry.register(new ShapedOreRecipe(getRL("teabag_empty"),new ItemStack(teabag,4),true,new Object[]{
				"  S",
				"PP ",
				"PP ",
				'S', "string",
				'P', Items.PAPER}).setMirrored(true).setRegistryName(getRL("teabag_empty")));
```

...the paper items display as missing textures.

![image](https://user-images.githubusercontent.com/9532786/27248415-ec37a0fc-52d0-11e7-8529-ac0e688b073a.png)

This also appears to happen with shapeless recipes and Block ingredients as well. It's easy enough to work around for the time being, but I figured I'd bring it up here.

Thanks for all your hard work!

**Comment by PaleoCrafter** [comment]
I think this is a duplicate of #3976.

**Comment by elucent** [comment]
Oh, you're right, apologies!

**Comment by marvin-roesch** [comment]
Deleted that comment because I thought *I* was mistaken, but yeah, it's the same issue, since `Ingredient.fromItem` uses the wildcard value for the ItemStack it creates.
Apart from that, you should really be defining these recipes via JSON 😝

**Comment by elucent** [comment]
When there's a tangible benefit to defining these recipes via JSON, I'll do that. :P
