### ISSUE TITLE
Recipes not loaded from jars

### ISSUE THREAD

**Issue by Xalcon** [MinecraftForge/MinecraftForge#4020]
It seems the loading mechanism for loading JSON recipes is currently broken. JSON recipes work just fine in dev, but as soon as you try running it from a jar, the recipes no longer get loaded.

This issue has been replicated with multiple mods available on curseforge.

I was able to track down the issue to the [CraftingHelper.loadRecipes()](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java#L662) method. It seems this check always fails - even if its a jar file.

Tested with Forge 2333

![example](http://i.imgur.com/2hZmX30.png)

**Comment by Xalcon** [comment]
I toyed around with the code a bit and I was able to load the jar, recipes work!
The issue is the `URI source = mod.getSource().toURI();` in https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java#L645
This always returns an URI with the `file:/` scheme. 
I simply added the following code afterwards, the jar is loaded just fine, recipes are working:
```java
if(mod.getSource().exists() && mod.getSource().toString().endsWith(".jar"))
    source = new URI("jar:" + source);
```

Since I'm not sure if this is the proper approach to fix this, I wont do a PR. Maybe someone else can pick this up tho :)

**Comment by williewillus** [comment]
yup, looks like `File.toURI()` is defined to always return a `file://` uri.

[javadoc](http://docs.oracle.com/javase/7/docs/api/java/io/File.html#toURI())

**Comment by fnuecke** [comment]
Alternative patch that also appears to work (no idea about dev tho, don't know how to test that) would be to add this before the `if ("jar"...`, feels somewhat hacky due to the `getClass()`, though:
```java

            if (mod.getMod() != null && mod.getMod().getClass().getResource("/assets/" + ctx.getModId() + "/recipes/") != null)
            {
                try
                {
                    source = mod.getMod().getClass().getResource("/assets/" + ctx.getModId() + "/recipes/").toURI();
                }
                catch (URISyntaxException e)
                {
                    FMLLog.log(Level.ERROR, e, "Error accessing mod jar: " + e.toString());
                    return false;
                }
            }
```

**Comment by williewillus** [comment]
I personally prefer the former :P

**Comment by LexManos** [comment]
Humm interesting, oh well.
I was just trying to mimic vanilla's loading.
The solution is simple, mod.getSource().isFile()/isDirectory() like everything else does.

**Comment by williewillus** [comment]
the subtle difference is that vanilla uses `Class.getResource().toURI` which is URL -> URI. the call being made here is File -> URI

**Comment by ThatGamerBlue** [comment]
any way around this until patch gets merged?

**Comment by mezz** [comment]
Fixed here https://github.com/MinecraftForge/MinecraftForge/commit/a2749e450760f7e83dc88a4b5cdf2e9811620e75
