### ISSUE TITLE
Mod advancements are not loaded 

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#4024]
Fairly obvious thing to do, but just thought we should have an issue tracking it.

This should be a lot more straightforward than recipes, as we're not editing the format (afaik)

**Comment by sjx233** [comment]
Insert these instruments into `net.minecraft.advancements.AdvancementManager.func_192777_a/loadBuiltInAdvancements`:
```
aload_0
aload_1
invokestatic <your loader method with (Lnet/minecraft/advancements/AdvancementManager;Ljava/util/Map;)V>
```
And in that method use reflection.

**Comment by liach** [comment]
@williewillus We might need to change advancement and loot table loading to be implemented by mod containers like how those language files are read.

**Comment by Landmaster** [comment]
@liach An event in `AdvancementManager.reload` just after `AdvancementManager.loadBuiltInAdvancements` might also be useful to avoid some ugly core-modding and dynamically add custom advancement objects.

**Comment by williewillus** [comment]
@liach what for?

**Comment by mcenderdragon** [comment]
I think this is a breaking change, so this has probably to be done before the deadline...

**Comment by LexManos** [comment]
It's not a breaking change, but yes it's done. https://github.com/MinecraftForge/MinecraftForge/commit/a4fb33d9459ac73831baec908f18d8f19f3cd6c0
