### ISSUE TITLE
[1.12] Patch issues caused by mappings update

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#4036]
Currently, running `genPatches` on a fresh 1.12.x branch shows changes to the following:

* `command.AdvancementCommand`
* `world.chunk.Chunk`
* `world.Explosion`
* `client.settings.KeyBinding`

**Comment by bs2609** [comment]
The `Chunk` patch is mainly my fault - it needs `this` prepended so as to unambigously refer to the fields (now named `x` and `z`) and not the method params (also `x` and `z`).

**Comment by mezz** [comment]
For `command.AdvancementCommand` and `client.settings.KeyBinding` it looks like there may be an issue with `genPatches`.
I will push a fix for `Chunk` and `Explosion`, they are simple.

**Comment by bs2609** [comment]
The chunk patch you committed isn't quite right. (Sorry, my instructions weren't very clear unless you had the 'correct' patch as reference).

The correct result should look like this:
```java
return !this.loaded ? state.getLightOpacity() : state.getLightOpacity(this.world, new BlockPos(this.x << 4 | x & 15, y, this.z << 4 | z & 15));
```

**Comment by mezz** [comment]
Thanks, I fixed the chunk patch properly now.
Lex fixed the remaining issue and the latest mappings are working correctly again.
