### ISSUE TITLE
ShapedOreRecipe not working correctly with smaller recipes.

### ISSUE THREAD

**Issue by modmuss50** [MinecraftForge/MinecraftForge#4038]
Hi, I think I have found a bug with `ShapedOreRecipe` when adding 3x1 sized recipes. It works as intended when just using `ShapedRecipes`, see bellow for a detailed explanation of the issue.

## Using ShapedOreRecipe (Broken)

I added the following recipe using ShapedOreRecipe and it appears to work fine
```java
ResourceLocation location1 = new ResourceLocation("recipetest", "dirt");
ShapedOreRecipe recipe1 = new ShapedOreRecipe(location1, new ItemStack(Blocks.DIAMOND_BLOCK), "DDD", 'D', new ItemStack(Blocks.DIRT));
recipe1.setRegistryName(location1);
GameRegistry.register(recipe1);
```

![2017-06-20_11 54 21](https://user-images.githubusercontent.com/4324090/27329893-48be1e2e-55af-11e7-999b-60f657736e47.png)

Until you add other random items into the crafting table that aren't part of the recipe: **This is where the issue is visible**

![2017-06-20_11 54 26](https://user-images.githubusercontent.com/4324090/27329941-74bd6bce-55af-11e7-9506-ff46bcf9261f.png)

The first recipe still shows, and can be crafted using up all the items.

## Using ShapedRecipes (Working as Intended)

I then added a similar item using ShapedRecipes from vanilla and it works as expected.

```java
ResourceLocation location2 = new ResourceLocation("recipetest", "stone");
CraftingHelper.ShapedPrimer primer1 = CraftingHelper.parseShaped("SSS", 'S', new ItemStack(Blocks.IRON_BLOCK));
ShapedRecipes recipe2 = new ShapedRecipes(location2.getResourcePath(), primer1.width, primer1.height, primer1.input, new ItemStack(Blocks.GOLD_BLOCK));
recipe2.setRegistryName(location2);
GameRegistry.register(recipe2);
```

![2017-06-20_11 53 49](https://user-images.githubusercontent.com/4324090/27330161-29820d3a-55b0-11e7-88df-0e298fb0b3b1.png)

And then with some other junk invalidating the recipe:

![2017-06-20_11 54 01](https://user-images.githubusercontent.com/4324090/27330173-3520ac8c-55b0-11e7-873c-eb7e09535818.png)

This was tested on forge 14.21.0.2340 without any core mods present.

## Full test mod

```java
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.ShapedRecipes;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.common.crafting.CraftingHelper;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;
import net.minecraftforge.oredict.ShapedOreRecipe;

@Mod(modid = "recipetest")
public class RecipeTestMod {

	@Mod.EventHandler
	public void preinit(FMLPreInitializationEvent event){
		ResourceLocation location1 = new ResourceLocation("recipetest", "dirt");
		ShapedOreRecipe recipe1 = new ShapedOreRecipe(location1, new ItemStack(Blocks.DIAMOND_BLOCK), "DDD", 'D', new ItemStack(Blocks.DIRT));
		recipe1.setRegistryName(location1);
		GameRegistry.register(recipe1);

		ResourceLocation location2 = new ResourceLocation("recipetest", "stone");
		CraftingHelper.ShapedPrimer primer1 = CraftingHelper.parseShaped("SSS", 'S', new ItemStack(Blocks.IRON_BLOCK));
		ShapedRecipes recipe2 = new ShapedRecipes(location2.getResourcePath(), primer1.width, primer1.height, primer1.input, new ItemStack(Blocks.GOLD_BLOCK));
		recipe2.setRegistryName(location2);
		GameRegistry.register(recipe2);

	}

}
```

I hope that is enough detail to go from. I haven't tested this using JSON based recipes. Feel free to ask any questions.

**Comment by modmuss50** [comment]
After more investigation, the issue came in this PR: https://github.com/MinecraftForge/MinecraftForge/commit/8833386ada0967d0f27fb86751b46935bee713e5

I fixed the issue by reverting that PR and changing `Ingredient target = null;` to  `Ingredient target = Ingredient.EMPTY;` see here: https://github.com/MinecraftForge/MinecraftForge/blob/8833386ada0967d0f27fb86751b46935bee713e5/src/main/java/net/minecraftforge/oredict/ShapedOreRecipe.java#L116

**Comment by mezz** [comment]
Thanks, fixed.
