### ISSUE TITLE
[1.12] _factories.json in jar file is loaded as a recipe json and causes an exception

### ISSUE THREAD

**Issue by Iunius118** [MinecraftForge/MinecraftForge#4039]
Test with **1.12-forge1.12-14.21.0.2339**: [stack trace log](https://pastebin.com/cMCwJVFm)

`root.relativize(f).toString().startsWith("_")` in CraftingHelper.loadRecipes(ModContainer) evaluates `"../recipes/_factories".startsWith("_")`.
I think the `Path root` should be "/assets/modid/**recipes**" and not "/assets/modid/**recipes/**".

**Comment by williewillus** [comment]
Yup, I ran into this when trying to make a pr for jar recipe loading. `relativize` doesn't like trailing slashes

**Comment by LexManos** [comment]
Wow.. relativization is dumb. Its pretty common practice to denote directories with a trailing /. It's what distinguishes them from files. Oh well, fixed.
