### ISSUE TITLE
1.7.10 A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by CinnaManBun** [MinecraftForge/MinecraftForge#4041]
Me and a friend are trying to create a server using Bisecthosting/Muticraft and have no idea why the server wont start

[Log.txt](https://github.com/MinecraftForge/MinecraftForge/files/1089566/Log.txt)

**Comment by TechnicianLP** [comment]
Looks like some libraries are missing

**Comment by CinnaManBun** [comment]
well we replaced most of the libraries but it still wont work :/

**Comment by williewillus** [comment]
Go on the forums for tech support

**Comment by CinnaManBun** [comment]
we think it might be something with putting the client side mods in with the server side mods

**Comment by LexManos** [comment]
Go on the forums for tech support
