### ISSUE TITLE
Brainstorming - Advancements

### ISSUE THREAD

**Issue by TechnicianLP** [MinecraftForge/MinecraftForge#4042]
What things do you want the Advancement System to have? (once it gets implemented - absolutely no pressure ....)

- Costum ICreterionTriggers (already doable by reflection (currently private in CriteriaTriggers)) 
- Custom AdvancementRewards? (similiar to the factory system for Recipes?)
- DisplayInfo - ItemStack with nbt? (extend the parser to take nbt into account?)
- Hook into the Toast messages for completing an Advancement? (generic Toast-Events?)

**Comment by williewillus** [comment]
1. You don't need reflection, the field is public I'm pretty sure
2. I would draw inspiration from the loot table system rather than the recipe system
3. Sure
4. Not sure what you mean. I'd rather have a general toast event letting you change text/icon/sound

**Comment by Xalcon** [comment]
Support for more than 26 advancement tabs. Big modpacks already have 100+ creative tabs and I dare to say that mods will most likely have more advancement tabs than creative tabs. Therefore, some sort of paging will be a requirement

**Comment by The-Fireplace** [comment]
Something that I also think we need, or if this functionality exists, we need documentation on, is the ability to use OreDictionary for advancements that have the minecraft:inventory_changed trigger

**Comment by Xalcon** [comment]
Something that might be useful as well would be conditional loading of advancements, similar to recipes.

**Comment by TechnicianLP** [comment]
As the Advancementsystem is stabilized now pretty much in closing this
If someone has an issue with TOastmessages feel free to open another issue
