### ISSUE TITLE
[1.11] [1.12] Lower half slabs and upright stairs block chests from opening under Forge, not Vanilla

### ISSUE THREAD

**Issue by zontargs** [MinecraftForge/MinecraftForge#4048]
If upright stairs or lower half slabs are placed immediately above a chest, this blocks the chest from opening (unless the client is connected to a non-Forge server). Upper half slabs and upside down stairs correctly allow the chest to open. This behavior is not present in Vanilla, where all slabs and stairs allow chests to open. It affects (at least) the current 1.11 and 1.12 versions of Forge.

fml-client-latest.log under 14.21.0.2340:
https://pastebin.com/nQCGA9Br

**Comment by bs2609** [comment]
See previous issues #3698, #3057, #2820

**Comment by zontargs** [comment]
Apologies, apparently I did not search far enough back.
