### ISSUE TITLE
[1.11] [1.12] Incorrect light transmission to opposite faces of stairs and slabs

### ISSUE THREAD

**Issue by zontargs** [MinecraftForge/MinecraftForge#4049]
Forge has slabs and stairs incorrectly lighting their interior faces when lit by an exterior light source. This affects at least the latest 1.11 and 1.12 versions of Forge.

A tube made from stairs and solid blocks:
https://kek.gg/i/5NjLBg.png
 
Correct lighting in vanilla:
https://kek.gg/i/3zr9Qk.png
 
Incorrect lighting in forge:
https://kek.gg/i/x7c76.png
 
Optifine or other mods are not involved.
 
fml-client-latest.log under 14.21.0.2340:
https://pastebin.com/nQCGA9Br

**Comment by bs2609** [comment]
Try setting "forgeLightPipelineEnabled" to 'false' (in `config/forge.cfg`) and show the result

**Comment by zontargs** [comment]
Yes, that fixes the problem:
https://kek.gg/i/7pbymH.png
(different world, same construct)

**Comment by bs2609** [comment]
Issue appears to be with smooth lighting:

![2017-08-23_17 37 07](https://user-images.githubusercontent.com/1447117/29627389-dbce8fd0-8829-11e7-9ba5-7bce2ffabc74.png)

![2017-08-23_17 37 15](https://user-images.githubusercontent.com/1447117/29627394-e032a958-8829-11e7-99f8-9842f053afac.png)
