### ISSUE TITLE
[1.12][1.11] Can't place flowerpot on TE block, possible world.mayPlace issue

### ISSUE THREAD

**Issue by Nuchaz** [MinecraftForge/MinecraftForge#4053]
I think there may be an issue with the mayPlace method in the world class. This seems to exist in both 1.11 and 1.12, possibly earlier versions, but I hadn't tested. Is what is happening is I am trying to make it so I can place a flowerpot on top of some of my TE blocks, but I think I am getting hung up on the mayPlace method returning false. So I started debuging and tracking it down and mayPlace checks for block.canPlaceBlockOnSide however, that is && with block.isReplacable, which I don't think will every both return true since the same block position is fed into both methods. Either the block is replaceable like grass, or something can be placed on the side of that block, but probably never both will be true.

Here is a copy of the method from world class in 1.12:

```'java'
    public boolean mayPlace(Block blockIn, BlockPos pos, boolean p_190527_3_, EnumFacing sidePlacedOn, @Nullable Entity placer)
    {
        IBlockState iblockstate = this.getBlockState(pos);
        AxisAlignedBB axisalignedbb = p_190527_3_ ? null : blockIn.getDefaultState().getCollisionBoundingBox(this, pos);

        if (axisalignedbb != Block.NULL_AABB && !this.checkNoEntityCollision(axisalignedbb.offset(pos), placer))
        {
            return false;
        }
        else if (iblockstate.getMaterial() == Material.CIRCUITS && blockIn == Blocks.ANVIL)
        {
            return true;
        }
        else
        {
            return iblockstate.getBlock().isReplaceable(this, pos) && blockIn.canPlaceBlockOnSide(this, pos, sidePlacedOn);
        }
    }

```
 As we can see, the last bit, getBlock().isReplacable **&&** blockIn.canPlaceBlockOnSide, I am pretty sure should be getBlock().isReplacable **||** blockIn.canPlaceBlockOnSide

**Comment by bs2609** [comment]
As a side note, you can append 'java' to the opening ``` to get some syntax highlighting for your code block.

**Comment by HenryLoenwind** [comment]
isn't that check "if the *block that is there* can be replaced and the *new block* can be placed there instead"?

**Comment by bs2609** [comment]
Base method implementations from `Block`:

```java
    public boolean canPlaceBlockOnSide(World worldIn, BlockPos pos, EnumFacing side)
    {
        return this.canPlaceBlockAt(worldIn, pos);
    }

    public boolean canPlaceBlockAt(World worldIn, BlockPos pos)
    {
        return worldIn.getBlockState(pos).getBlock().isReplaceable(worldIn, pos);
    }
```

So, by substituting the value of `iblockstate`, and the body of `canPlaceBlockOnSide` into the original return we get:
```java
return this.getBlockState(pos).getBlock().isReplaceable(this, pos) && this.getBlockState(pos).getBlock().isReplaceable(this, pos);
```

So the condition is certainly possible to be met, it seems like the intent is for blocks that override these methods to be able to place additional constraints (like crops only planting on soil)
