### ISSUE TITLE
[1.12] ShapedOreRecipe odd behaviour

### ISSUE THREAD

**Issue by desht** [MinecraftForge/MinecraftForge#4055]
I am mostly using JSON recipes in my mod now (which are working fine), but I do have a few custom recipes which are still added programatically; these recipes tend to modify the NBT on certain items from my mod.  To this end, I have an abstract ``ModuleEnhancementRecipe`` class which extends ``ShapedOreRecipe``, and several custom recipe classes which extend that, e.g. ``ModuleResetRecipe``.

That particular recipe is a simple self-craft recipe:
```java
ItemStack stack = ModuleHelper.makeItemStack(type);
ItemStack output = ModuleHelper.makeItemStack(type);
ModuleResetRecipe recipe = new ModuleResetRecipe(output, "M", 'M', stack);
// RL() is just a convenience method for getting a mod-specific resource location
GameRegistry.register(recipe.setRegistryName(RL(type + "_" + "reset")));
```

The problem: in 1.12, although this recipe matches if I drop a single module item into a crafting inventory, it also matches if I drop any other items into the crafting inventory too. E.g. throw the module and a stick in there; the recipe still gets matched by ``ShapedOreRecipe#matches()``.

(If you're wondering why I didn't just use a shapeless recipe, it's because the reset recipe is just one of multiple recipes which all extend ``ModuleEnhancementRecipe``, which extends ``ShapedOreRecipe``).

This worked in 1.10/1.11, and from looking at ``ShapedOreRecipe``, it's changed very significantly (not surprisingly), and it appears that the ``matches()`` and ``checkMatch()`` methods only look for what *should* be in the recipe, and not if there are items which *shouldn't*.

**Comment by SquidDev** [comment]
This seems awfully similar to #4038. Can you confirm you're on the latest Forge version?

**Comment by desht** [comment]
Yeah, looks like the same issue - I missed that when searching, sorry.  I was using the latest version as of about 9 hours ago, which was clearly not new enough :)

Forge build 2344 does indeed resolve the problem.  Apologies again.
