### ISSUE TITLE
[1.12][2349] Vanilla creative tabs items are misordered

### ISSUE THREAD

**Issue by starg09** [MinecraftForge/MinecraftForge#4058]
This seems to happen to every vanilla tab, items/blocks are shown in an different order than the usual vanilla one (it's not random, same odd order persists through restarts of the instance).

As an example:

* [How the redstone tab usually looks](http://i.imgur.com/9RLpHwm.png)
* [How it looks now](http://i.imgur.com/F4iscV6.png)

**Comment by tterrag1098** [comment]
As a test, changing [this line](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/registries/ForgeRegistry.java#L94) to:

```java
Iterator<V> itr = ImmutableSortedMap.copyOf(ids).values().iterator();
```

fixes the bug. But this seems like a harsh penalty to performance for every iteration of any registry. Perhaps the sorting should be done on the CreativeTabs side?

**Comment by tterrag1098** [comment]
Looked into sorting it on the CreativeTabs side, the best impl I could come up with is

```java
    public void displayAllRelevantItems(NonNullList<ItemStack> p_78018_1_)
    {
    	Iterable<Item> sortedItems = () -> StreamSupport.stream(Item.REGISTRY.spliterator(), false).sorted((i1, i2) -> Integer.compare(Item.REGISTRY.getIDForObject(i1), Item.REGISTRY.getIDForObject(i2))).iterator();
    	for (Item item : sortedItems)
        {
            item.getSubItems(this, p_78018_1_);
        }
    }
```

which is obviously not the best. Unfortunately neither the vanilla wrapped-registry nor the forge registry provide any way to get an id->V entry set, so this problem is not so simple.

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Regression]

**Comment by LexManos** [comment]
Honestly, the things shouldn't be sorted by id but by name. I don't find this an issue tho.

**Comment by tterrag1098** [comment]
You don't find it an issue that items are sorted differently from vanilla (and randomly, based on hashes) for every game?

**Comment by LexManos** [comment]
Actually it wouldn't be randomly, the hashes are based on the registry name, so it's stable.
It'd be different across JVM versions but thats cuz they changed the HashMap bucketing system in J8.
I can see what you're getting at, and Honestly I wish Mojang would make a better sorting system. But meh. This can be fixed. I expect your PR soon :P

**Comment by raoulvdberge** [comment]
This can be closed now.
