### ISSUE TITLE
Mod not loading with a CoreMod in same jarFile [1.11.2-13.20.0.2345]

### ISSUE THREAD

**Issue by kingdevnl** [MinecraftForge/MinecraftForge#4061]
So my Mod isnt loading but my CoreMod its

My build.gradle its: https://pastebin.com/BRM34FY4
EDIT: There are also no error traces in the Console and in the DEV Env. it all works,

**Comment by kingdevnl** [comment]
There are also no error traces in the Console and in the DEV Env. it all works,

**Comment by kingdevnl** [comment]
The manifest of the mod jar : https://pastebin.com/BU9Gq0Mf

**Comment by diesieben07** [comment]
1. Don't make a coremod.
2. http://www.minecraftforge.net/forum/topic/58706-regarding-minecraft-112-and-policy-changes/
