### ISSUE TITLE
[1.12]Ore dictionary does not work in vanilla recipes

### ISSUE THREAD

**Issue by ljfa-ag** [MinecraftForge/MinecraftForge#4062]
I have registered my block as plankWood, but I cannot craft sticks, chests, crafting tables etc. from it.

Modded recipes work, I can use vanilla as well as modded planks there.

**Comment by sokratis12GR** [comment]
vanilla recipes are hardcoded to only use their planks, i.e
![image](https://user-images.githubusercontent.com/12274096/27509534-2bb47ea2-5908-11e7-9856-63b2f73b0f9d.png)

**Comment by ljfa-ag** [comment]
Yes, but they are supposed to be replaced so that ore dictionary items also work.

**Comment by sokratis12GR** [comment]
Why not just register the recipe with the oredict via your mod? It should work, right? (I don't know ow if it will be good or bad tho)

**Comment by HellFirePvP** [comment]
Would lead to duplicate recipes. It was forge that did this in the past to sweep over vanilla recipes, unregister them and re-register them with oredict equivalents where necessary.
Seems like that thing broke now though or it's just not re-added yet.

**Comment by sokratis12GR** [comment]
Lol, yeah I forgot to mention to unregister the first one tho.. Ty HellFire :)

**Comment by HellFirePvP** [comment]
That then defeats the purpose, cause you'd do something that forge already does - or seemingly _did_ until it's fixed or re-added.

**Comment by marvin-roesch** [comment]
The recipe system isn't completely finished yet, iirc. Lex still has to figure out a good way to do the automatic oredict replacements in Vanilla recipes.

**Comment by ljfa-ag** [comment]
I see some code in OreDict for that. But seems like it does not work even though it logs "Replaced 921 ore ingredients".

**Comment by LexManos** [comment]
Its on my todo list:
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/oredict/OreDictionary.java#L353
I need to think of a better/more robust way of replacing vanilla ingredients.

**Comment by bs2609** [comment]
Is this resolved by #4310?

**Comment by mezz** [comment]
Yes this is working now.
