### ISSUE TITLE
Removed blocks are corrupted and become unbreakable

### ISSUE THREAD

**Issue by adrwa** [MinecraftForge/MinecraftForge#4063]
Using the latest forge (14.21.0.2359) when loading a world with blocks that have since been removed, expected behaviour is for them to turn to air but they don't seem to do this and become unbreakable blocks even in creative. 

https://streamable.com/tonrd

when raytracing it shows that the block does seem to have the original registry name

![image](https://user-images.githubusercontent.com/17037059/27509522-faea792c-58f6-11e7-885a-a2c20bfdf036.png)

**Comment by LexManos** [comment]
Having the original registry name is intended.
Thats how they maintain position if you re-add the mod later.
They are replaced by dummy blocks that *should* filter back into air like blocks.
I'll look into it.

Can you look into the current version: https://github.com/MinecraftForge/MinecraftForge/commit/b542179242f9d6ea464b20aedde7a8c2738f905a

**Comment by raoulvdberge** [comment]
This can be closed
