### ISSUE TITLE
Block and items being initialized after preInit causes problems

### ISSUE THREAD

**Issue by ljfa-ag** [MinecraftForge/MinecraftForge#4064]
This concerns ModelLoader.setCustomModelResourceLocation, ModelLoader.setCustomStateMapper and probably some other things too:

Those methods require the items or blocks to exist, so they cannot be called in preInit. But they have to be called before init, otherwise you get black-purple missing models everywhere. This makes matters complicated, especially when you want to use ObjectHolders.

I am not sure if these methods are intended to be called directly from item or block constructors, otherwise it should probably be arranged so that they work properly when called in init.

**Comment by marvin-roesch** [comment]
Use `ModelRegistryEvent`, it is called right after the other registry events but before init.

**Comment by ljfa-ag** [comment]
Thanks, I missed that one.
