### ISSUE TITLE
lower requirements for @ObjectHolder fields

### ISSUE THREAD

**Issue by Xalcon** [MinecraftForge/MinecraftForge#4065]
I would like to start a discussion on fields that are annotated by `@GameRegistry.ObjectHolder` (either explicitly or implicitly through the containing class).

Currently, objectholder fields have to be `public static final` in order to work and their default value should be set to null. The issue with this is the IntelliJ code inspection will mark access to those fields as *possibly null at runtime* - which make sense. One way to fix this on my end would be disabling null/nonnull inspection, but I really like using that feature.

**NOTE:** If there is a reason these fields have to be `public final static` i'd like to learn about it.

My suggestion would be to lower the requirements for such fields by implement any of these options:
* allow the use of private fields. This would allow using getters without polluting the code completion feature with "dangerous fields"
* allow the use of non-final fields. Not as good as the other solution, but atleast IntelliJ accepts this workaround since values can now be realistically changed at runtime without using black magic (asm, reflection, etc)
* Allow explicitly annotated fields to be only static. Only implicit object holder fields would need to be `public final static` in this case, giving a bit more freedom to the user.

There are obviously a lot of workarounds for this, like creating another class that provides getters for those fields or using a dummy object that is used at compile time. But all of them seem to be solutions for a problem that (IMHO!) shouldnt exist in the first place :/

I'm open for alternative solutions though.

**Comment by LexManos** [comment]
Private fields are allowed but not in Class level scanning. Tho, using getters still works on public fields... So im not sure you argument is good on that one.
2) Not gunna happen. We've tried, modders didn't get the point that they shouldn't be constructing things to these directly.
3) All fields must be static as we do not have the owning instance.

Honestly, your complaint is with your IDE, which *should* be able to be told to shut up with a few //noinspects

**Comment by Xalcon** [comment]
I'm sorry, this was an error on my part.
I was still on an "old" version (14.21.0.2347) and that version wasnt able to write to private fields. (my suggestion number 3)
This was fixed in 14.21.0.2348.

Again, sorry for bothering you. I'm happy now!
