### ISSUE TITLE
[1.12] JSON recipe input NBT insensitive

### ISSUE THREAD

**Issue by tomelfring** [MinecraftForge/MinecraftForge#4066]
The default implementation of the `Ingredient` "minecraft:item_nbt" returns a NBT insensitive version. When this Ingredient is used as input in a crafting recipe it will ignore all NBT values.

As discussed on the [forums](http://www.minecraftforge.net/forum/topic/58852-112-json-recipe-input-nbt-insensitive/) the solution would be to return a NBT sensitive version.

**Comment by LexManos** [comment]
The intention was for it to be NBT sensitive, seems i missed that i'll add it to my TODO.

**Comment by tomelfring** [comment]
Fixed in commits: 405a16aea1714f8e2bd44ca227569f7e3a40319f efd8b38be9fe7ce4521a0dfbe660f3167aa27e9f

Thanks for the quick fix!
