### ISSUE TITLE
Question on runtime maven dependencies

### ISSUE THREAD

**Issue by UpcraftLP** [MinecraftForge/MinecraftForge#4086]
Would it be possible to download dependencies when running mods, meaning that you can just include the download in the manifest instead of packaging the dependencies?

**Comment by marvin-roesch** [comment]
The general stance is that Forge will never download any third party software, mainly for security reasons. Extracting and loading is the best we get, the rest is up to launchers such as the Twitch client.

**Comment by UpcraftLP** [comment]
Well, Lex also stated that you'll need to accept each coremod when first launching the game with that coremod installed, so I think there could be something similar for downloaded dependencies´...

**Comment by LexManos** [comment]
Not gunna happen, shade/package in your deps
