### ISSUE TITLE
[1.12] Recipe Book ghost recipe width depends on ShapedRecipes class

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#4088]
>int k = p_193951_1_ instanceof ShapedRecipes ? ((ShapedRecipes)p_193951_1_).getWidth() : i;

This line in GuiRecipeBook prevents ShapedOreRecipes, as well as modded recipes, of incorrect width from being automatically filled in by the Recipe Book.

I propose solving this by adding a default method to IRecipe (getWidth()? getPitch()?) which returns -1 if the width/pitch is unknown (shapeless recipe) or the correct value if it is known (shaped ore/mod recipes).

**Comment by KnightMiner** [comment]
Oh, that's what was going on with my recipes in my test yesterday. The recipe book was showing the completely wrong arrangement for a few when JEI worked fine.

**Comment by KnightMiner** [comment]
Didn't Lex fix this is awhile ago? I think this can be closed.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/036191cd52c2901fc881a488fa595835feaa4217
