### ISSUE TITLE
[1.12] CommandEvent fired after ICommand#checkPermission

### ISSUE THREAD

**Issue by BrokenSwing** [MinecraftForge/MinecraftForge#4093]
In `CommandManager#executeCommand`, the event `CommandEvent` is fired ONLY if  `ICommand#checkPermission` returns true. It certainly works as expected but I have problems when trying to allow players to execute a command that they can't execute by default (example : players who aren't operators can't execute tp command, but I want allow them to execute it). A way to solve it is to annotate `CommandEvent` with `@HasResult` indeed of `@Cancelable` and :

- if result is ALLOW : allow player to execute the command
- if result is DENY : it cancels the command
- if result is DEFAULT : we let ICommand#checkPermission handle it

Should I make a PR or will this be refused ?

**Comment by mezz** [comment]
I'm not sure, I don't think it's right for mods to override the vanilla server configs.
There may be a better way to do what you want, without relying on vanilla commands.
For example JEI uses `/give` on vanilla servers since there is no other option, but uses its own implementation for giving items when it is installed on the server.
Can you explain what you want to do more specifically?

**Comment by BrokenSwing** [comment]
I want to make a server-side only mod which uses the PermissionAPI implemented by Forge, but I can't give permissions for vanilla commands if the player isn't operator. I would like to do something like that :
```
@SubscribeEvent
    public static void onCommand(CommandEvent event) {
        if (event.getSender() instanceof EntityPlayer)
            if (PermissionAPI.hasPermission((EntityPlayer) event.getSender(), "command." + event.getCommand().getName()))
                event.setResult(Result.ALLOW);
            else
                event.setResult(Result.DENY);
    }
```

For commands from mods, MAYBE that they use directly something like that :
```
@Override
public boolean checkPermission(MinecraftServer server, ICommandSender sender) {
    if(sender instanceof EntityPlayer)
        return PermissionAPI.hasPermission((EntityPlayer)sender, "command." + this.getName());
    return true;
}
```

Or directly the condition in the `ICommand#execute` : 
```
@Override
public void execute(MinecraftServer server, ICommandSender sender, String[] args) throws CommandException {
      if(sender instanceof EntityPlayer)
          if(!PermissionAPI.hasPermission((EntityPlayer)sender, "command." + this.getName()))
              //You can't use this command
}
```

But for Minecraft commands, it's the operator level which indicates if the player can use it or not. For the moment I use a bad hack : when a player connects to the server I set him operator, and then cancel the `CommandEvent` if necessary. But others mod certainly allow actions only if players are operators and it breaks their code.
As you said I could override all Minecraft commands, but I don't think it's clean. And I can't be sure that mods ask the PermissionAPI to check if the player can execute their commands.

**Comment by Alpvax** [comment]
Is it worth patching the vanilla CommandBase to use the permissions API?

**Comment by BrokenSwing** [comment]
I think change `CommandEvent` from `@Cancelable` to `@HasResult` and patch CommandManager to handle the result is a better solution, of course it's a breaking change and it's why I propose it now (1.12 released very very soon). Patching `CommandBase` to make it use the PermissionAPI will cause that all commands will be usable by all the players (default implementation of PermissionAPI always returns true to PermissionAPI#hasPermission)

**Comment by Alpvax** [comment]
I thought the default implementation allowed differentiating between op and non-op. As it doesn't, modifying the event is probably the best option.

**Comment by BrokenSwing** [comment]
You was right, default implementation differentiate op and non-op, but it still don't solve the problem for the commands added by mods, if they don't ask the permission to the PermissionAPI. I'll make a PR modifying the `CommandEvent` and I'll see what they'll say to me. But patch the `CommandBase` class seems a nice idea.

EDIT : Call PermissionAPI#hasPermission in CommandBase#checkPermission isn't a good idea finally, it just allows operators to execute commands or we'll have to register nodes. But vanilla commands have different permission levels and the PermissionAPI can't support it, there is just ALL, NONE and OP. The modification of the event is the best soluce.

**Comment by Alpvax** [comment]
> it just allows operators to execute commands or we'll have to register nodes.

Would that not be a good idea anyway? Create a CommandBase#registerPermissionNodes which could default to <modid>.command.<commandname> and use the existing permissions to set op or non-op.
Then people could override it to change the node name or register multiple nodes for finer grained control.
