### ISSUE TITLE
[1.12] Search tree manager initialized too early

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#4094]
While items and recipes are expected to be registered before init(), that is using RegistryEvents, I do not think the same can be said for things such as initializing the output of getSubItems() - these can rely on mod integration, the OreDictionary, or other information typically available *after* preInit. (In particular, my list of getSubItems() relies on the OreDictionary and other mods' recipes being initialized at the moment.)

However, the SearchTreeManager (used for lookups in the creative menu, among other things) is populated immediately after preInit. I believe that, if Forge's goal is to allow disabling and enabling of content on world change, this should be moved to around the time of FMLServerStartingEvent - if not, it should be moved to after the init phase at the earliest (mods like NEI or JEI usually did their own lookup information generation after postInit, which is also fair):

>        this.populateSearchTreeManager();
>        this.mcResourceManager.registerReloadListener(this.searchTreeManager);

Do note that the searchTreeManager ReloadListener may have to be called manually after this. The ReloadListener alone is not terribly useful, however, as it does not re-scan for new items or recipes - perhaps moving populateSearchTreeManager *to* the reload listener could be a good idea?

**Comment by LexManos** [comment]
Err ignore my last, i was mistaken they are just delegates.
However yes. The part that gathers the list of recipes needs to be updated.
