### ISSUE TITLE
[1.12] Minor server console spam about missing translations

### ISSUE THREAD

**Issue by maruohon** [MinecraftForge/MinecraftForge#4099]
A 1.12 dedicated server currently spams the console a little bit on server start about missing translations:
* https://pastebin.com/raw/hEJpKaHm

**Comment by mezz** [comment]
This log has been reduced to just one line per mod by https://github.com/MinecraftForge/MinecraftForge/commit/a886dbde491d7c453cc4ace640352b1f96a22974

**Comment by bs2609** [comment]
This also affects 1.11.2, could the fix be backported?

**Comment by liach** [comment]
This is rather minor IMO.
