### ISSUE TITLE
Item search is broken

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#4100]
![](https://i.gyazo.com/783868708873e8692b97f0dc4c6de15d.png)

This is on a clean world on build 2379, with an in-dev version of Botania. All the mod recipes are json recipes.

JEI shows the correct results

**Comment by williewillus** [comment]
For completeness: The three items shown have the names "infused grass", "mutated grass", and "animated torch". no "redstone" in localized nor registry name.

**Comment by LexManos** [comment]
Right, it does some nasty baking on reload that I misread.

**Comment by bs2609** [comment]
This can be closed now.
