### ISSUE TITLE
ObjectHolders not created for MobEffects or SoundEvents registries.

### ISSUE THREAD

**Issue by maxanier** [MinecraftForge/MinecraftForge#4104]
The ObjectHolderRegistry do not scan MobEffects, Soundevents etc. so you cannot use ObjectHolders for these objects (and replacing vanilla things with custom ones does not really work because of this).

Solution would be to make the registry scan the relevant classes. 
https://github.com/maxanier/MinecraftForge/blob/c96c403c5326f81994db8736cf8b3f488dcc9c7f/src/main/java/net/minecraftforge/fml/common/registry/ObjectHolderRegistry.java#L78-L84

**Comment by LexManos** [comment]
Right, Not sure why you went through the effort of making a fork, and then updating it. Just to make a issue report not a pull request. But sure I can add these.

**Comment by maxanier** [comment]
thx
Created that fork for my Substitution PR a while ago ;)
