### ISSUE TITLE
[1.12] Can't register new ICriterionTrigger

### ISSUE THREAD

**Issue by C6H2Cl2** [MinecraftForge/MinecraftForge#4109]
I want to register new ICriterionTrigger with CriteriaTriggers to use it in advancement-json, but ICriterionTrigger.REGISTRY and ICriterionTrigger.register is private so I can't do it.

**Comment by Alpvax** [comment]
Try using the registry events
`RegistryEvent.Register<ICriterionTrigger>`

**Comment by C6H2Cl2** [comment]
RegistryEvent.Register can't use for registering ICriterionTrigger because ICriterionTrigger do not extend(implement) IForgeRegistryEntry

**Comment by liach** [comment]
@Alpvax It is not in forge registries yet. Use reflections for now, or Access Transformers.

**Comment by Alpvax** [comment]
Ah, my mistake

**Comment by mezz** [comment]
Advancements are still being looked at, there is a lot to consider still. Forge does not have full support for modded advancements yet.

**Comment by liach** [comment]
I am shocked that we haven't dealt with this yet

**Comment by Lomeli12** [comment]
Yeah, I have to use reflection in Trophy Slots to add my own criterion trigger. A non-hacky method would be nice.

**Comment by mezz** [comment]
@Lomeli12 since you already know how to do it for Trophy Slots, can you make a PR to Forge to make a clean way of doing it?

**Comment by williewillus** [comment]
I mean, this should just be adding the relevant method to the forge AT right?

**Comment by liach** [comment]
I think we need a more extensive api for the future.

**Comment by williewillus** [comment]
"extensive" meaning what?

Let's just focus on the singular issue at hand: can't register triggers. Solution? Make the method public. Done. Anything else can go in another ticket or PR
