### ISSUE TITLE
[1.12] Items which have setHasSubtypes(true) shown in all creative tabs

### ISSUE THREAD

**Issue by DreenDex** [MinecraftForge/MinecraftForge#4110]
All items which have setHasSubtypes(true) can be found in any creative tab with ignoring all rules.
In this example i using forestry to show it in the game. And its working with all other mods.
![image](https://user-images.githubusercontent.com/6661231/27755862-3f78fab0-5dfb-11e7-9f28-0544d4b7f121.png)
![image](https://user-images.githubusercontent.com/6661231/27755890-7ed107ac-5dfb-11e7-96d2-0b1b3d286424.png)

**Comment by williewillus** [comment]
It's a mod problem, they need to update getSubItems to check isInTab before adding.

**Comment by DreenDex** [comment]
Oops... Sorry for that. My mistake.
