### ISSUE TITLE
[Forge Animation System] Loss of Precision Over Time

### ISSUE THREAD

**Issue by Aeronica** [MinecraftForge/MinecraftForge#4121]
Because the Forge Animation System Time relies on a conversion of a long value to a float there is marked loss of decimal precision which results in a loss of animation quality over time.

```java
package net.minecraftforge.client.model.animation;
public enum Animation
{
    INSTANCE;
...
    /**
     * Get the global world time for the current tick + partial tick progress, in seconds.
     */
    public static float getWorldTime(World world, float tickProgress)
    {
        return world.getTotalWorldTime() + tickProgress) / 20;
    }
...
```
To correct the issue I suggest using doubles instead of floats for this and the related classes that make up the Animation State Machine.

I have already started a PR for this.  Testing has already shown that using a total world time value of 63072000000000 ticks (100,000 years) results in no perceptible loss in precision and no loss in animation quality.

## Example Video Showing the Issue
[![Forge Animation Precision Loss](https://i.ytimg.com/vi/PRib2nibJY4/hqdefault.jpg)](https://www.youtube.com/watch?v=PRib2nibJY4 "Forge Animation Precision Loss")

## Further reading on the subject

https://randomascii.wordpress.com/2012/02/13/dont-store-that-in-a-float/

https://stackoverflow.com/questions/1293819/why-does-java-implicitly-without-cast-convert-a-long-to-a-float

**Comment by liach** [comment]
Should not be stale anymore because of the pull request
