### ISSUE TITLE
Small code issue in ForgeRegistry

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#4129]
Whilst running inspections for other things, I noticed [this](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/registries/ForgeRegistry.java#L658).
The `equals()` method here is comparing a `String` to an `OverrideOwner`, so it will never return true.

**Comment by liach** [comment]
Fixed already
