### ISSUE TITLE
1.10.2 rendering issue startup crash.

### ISSUE THREAD

**Issue by border999** [MinecraftForge/MinecraftForge#4131]
I am having a continual issue where when I try to start my minecraft it crashes with the same crash.
I would appreciate assistance in identifying the issue and perhaps help me to resolve it.
Minecraft version: 1.10.2
Forge: 1.10.2-forge1.10.2-12.18.3.2316

https://pastebin.com/B1pk14qV

**Comment by Daomephsta** [comment]
The github issue tracker is only for issues that are confirmed to be caused by Forge. Other issues belong on the [Support section](http://www.minecraftforge.net/forum/forum/18-support-bug-reports/) of the  forums.
