### ISSUE TITLE
[1.12] Overriding a registry entry from the same owner crashes the game with an unobvious message

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#4132]
Forge version: 1.12-14.21.1.2395
Test mod: [link](https://github.com/Choonster-Minecraft-Mods/ForgeRegistryOverrideTestMod/blob/7a12b727de6b0ae11e5869f9ba1d39fd5b2c6d8f/src/main/java/com/github/choonster/forgeregistryoverridetestmod/ForgeRegistryOverrideTestMod.java)

When one mod registers two different objects with the same name, the second one will override the first as expected.

However, since both the old and the new objects have the same owner (mod ID), the new `OverrideOwner` and object will replace the old one in the `ForgeRegistry#owners` `BiMap`. 

When `ForgeRegistry#sync` is called, it will log [this warning](https://github.com/MinecraftForge/MinecraftForge/blob/03b7885aa6a514ce01eef54e93ed6e775575c660/src/main/java/net/minecraftforge/registries/ForgeRegistry.java#L504) for the old value and then crash the game with [this exception](https://github.com/MinecraftForge/MinecraftForge/blob/03b7885aa6a514ce01eef54e93ed6e775575c660/src/main/java/net/minecraftforge/registries/ForgeRegistry.java#L523).

If the old and new objects have different owners, the old `OverrideOwner` and object will be preserved and this won't happen.

Since it doesn't make much sense to override an object from your own mod, it might be best to detect this and throw an `IllegalArgumentException` in `ForgeRegistry#add`.

**Comment by KnightMiner** [comment]
Is this possibly related to/caused by #4129? That issue points to a case where the owner is compared to a string of the owner thus they can never be equal, thus skipping preventing from skipping some code.

**Comment by Choonster** [comment]
I don't think the issues are directly related. This issue removes the `OverrideOwner` for the old name, so it won't reach that check.

**Comment by LexManos** [comment]
Why would you ever override your own stuff?

**Comment by diesieben07** [comment]
Because of a mistake. As far as I understand it, the intend of this issue is to make the error message more descriptive.

**Comment by LexManos** [comment]
Alright, I'd just say if someone tries to override themselves, then error in the add method instead of elseware. It'll be on my list of things to do later.

**Comment by Choonster** [comment]
This issue is still present.

**Comment by Draco18s** [comment]
Just thought I'd pop in here and say "this is still an issue in 1.19" as I managed to cause this error and had to google it.

**Comment by Toastunn** [comment]
still an issue in 1.20.1
