### ISSUE TITLE
[1.12] Mod name is no longer added to System.out.println calls. 

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#4135]
Previously when `System.out.println` was used, the output would contain the location of the call. While modders should be using their own loggers now, a lot don't. Not sure if the old code was intentionally removed, however it was very useful for tracking down mods that are spamming the log with pointless/debug data. 

Tested for this with 2395, in the default mdk environment. 

Test code
```java
        boolean is = true;
        while (is) {
            
            System.out.println("test");
        }
```

Output

```
[14:32:41] [main/INFO]: [STDOUT]: test
[14:32:41] [main/INFO]: [STDOUT]: test
[14:32:41] [main/INFO]: [STDOUT]: test
[14:32:41] [main/INFO]: [STDOUT]: test
[14:32:41] [main/INFO]: [STDOUT]: test
[14:32:41] [main/INFO]: [STDOUT]: test
```

**Comment by mezz** [comment]
The relevant code is in `net.minecraftforge.fml.common.FMLLog`'s static initialize section.
It wraps the streams in `net.minecraftforge.fml.common.TracingPrintStream`
I'm not sure how it broke.

**Comment by bs2609** [comment]
I suspect `Bootstrap.redirectOutputToLog()` may have something to do with it.

**Comment by mezz** [comment]
Yeah looks like they redirect much later than FML does.
