### ISSUE TITLE
[1.12] Crash With Registry System (No Error On Mods)

### ISSUE THREAD

**Issue by CluelessPhil** [MinecraftForge/MinecraftForge#4136]
I am playing around with a test pack and noticed it crashes after 2/7 finishes. I've updated all the mods that are using the registry and deleted those not, but I  still have an issue with it. 
Crash: [crash-2017-07-04_16.30.48-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/1123021/crash-2017-07-04_16.30.48-client.txt)

**Comment by SquidDev** [comment]
This is a bug in the armorplus mod, not in Forge. This has already been reported on their issue tracker (TheDragonTeam/ArmorPlus#154).
