### ISSUE TITLE
[1.12] Overriding Registry Entry casuing missing models when on playing on servers

### ISSUE THREAD

**Issue by Sandro0000** [MinecraftForge/MinecraftForge#4140]
My mod, Redstone++ has replaced several registry entries. In single player everything works fine, but when connecting to a server, all replaced blocks/items show missing models. I have tested and confirmed that the registry names and block states are correct on both client and server. No errors are given in the console or the logs.

As a example I'll make the unusual case of posing the source to my current 1.12 build here:
[http://lordsandro.com/Redstone++_sources.jar](http://lordsandro.com/Redstone++_sources.jar)

It's a small mod, and gives several different cases to this issue:
Crafting Tables and Sea Lanterns have a new property added to their blockstate. Here the missing model only shows for a split second or until the next block update before displaying correctly.

BlockPistonBase does not add any properties and show a missing model no matter what I do. I've tried copying the blockstate.json and model.json in several different locations, changing the references, ect. to no avail. The TileEntitySpecialRenderer works fine.

The Sign Blocks use a TileEntitySpecialRenderer and work fine; however, ItemSign (currently the only item being replaced) shows missing model textures as well.

What I can't figure out is why connecting to a server breaks the model rendering on the client. All blocks/items render correctly in single player and not connected to a server.

**Comment by loordgek** [comment]
did this fix it  https://github.com/MinecraftForge/MinecraftForge/commit/b0edb23dba279b69fca774ce6dad04bee6c6c40e ?

**Comment by LexManos** [comment]
That fixes the items, I wanted @RainWarrior to take a look at the blocks. We could do it a similiar way but I'd prefer to make the loader bake all the models for each override type as there is no real simple way to translate one blockstate to the other.

**Comment by Sandro0000** [comment]
Just update to Latest Forge Build. As expected Overriding Items now works in Single Player and on Servers. Overriding Blocks only works in Single Player; still shows missing Models when connecting to Servers.

**Comment by marvin-roesch** [comment]
Pinging @RainWarrior again since he probably is the one required to properly fix this. Substituting blocks is really not feasible at the moment given this restriction.

**Comment by Sandro0000** [comment]
Sorry, I haven't got around to checking this until now. The above mentioned patch did correct my issue. As far as I can tell this can be closed.
