### ISSUE TITLE
[1.10.2] Custom NPCs crash

### ISSUE THREAD

**Issue by kasdo** [MinecraftForge/MinecraftForge#4142]
Forge Mod Loader version 12.18.3.2316
spongeforge-1.10.2-2281-5.2.0-BETA-2424
Mods: CustomNpcs, Mo'Creatures, CustomMobSpawner, LotsOfFood
Plugins: WorldEdit, RedProtect, EssentialCMDs, ProjectWorlds, ProjectPortals, Twentyticks, PermissionsEx, Holograms
Crash: https://hastebin.com/uqoluponow.xml
Noppes (custom npcs author) say its sponge bug.

I have this crash on cauldron 1.7.10 too (2-3 years ago)

**Comment by raoulvdberge** [comment]
This is the Forge issue tracker, NOT the Sponge issue tracker.

**Comment by kasdo** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1629
No one know how to fix this in sponge. Mb here I can found help
