### ISSUE TITLE
How to manually patch Forge for clients without gui

### ISSUE THREAD

**Issue by MGlolenstine** [MinecraftForge/MinecraftForge#4145]
Ok, I want to make modpack launcher and I don't want user to click in the forge's gui. How can I do that? What does forge do during the installation? Copies files? Changes classes? Replaces classes?

**Comment by MGlolenstine** [comment]
Can I at least install it from cli like I can with server version? If not why?

**Comment by diesieben07** [comment]
- Installing forge automatically is discouraged. Forge pays it's cost with the ads on the installer downloads.
- The Installer is open source.
