### ISSUE TITLE
Resizing the window too small in the mod page makes Minecraft freeze

### ISSUE THREAD

**Issue by dblsaiko** [MinecraftForge/MinecraftForge#4148]
Tested with 1.12-14.21.1.2402. When you open the mod page and select any mod (Forge will do) and then resize the window so the width of the window doesn't allow the mod description on the right to display, it completely locks up. I think this happens because it tries to insert a line break into the text when it runs out of space, and when there's no space for any letters, it keeps trying to insert line breaks so it gets caught in an infinite loop.

**Comment by mezz** [comment]
Thanks for the report, that's exactly what was happening.
