### ISSUE TITLE
[1.12] Text bug on Forge Server

### ISSUE THREAD

**Issue by ImAK9** [MinecraftForge/MinecraftForge#4150]
Forge Build: 14.21.1.2404

Issue: https://gyazo.com/ba026f83183a11e90c0d6311efdc6e1a

It seems like this only happens on Servers... I jumped onto Single Player too see if this was happening there too but it wasn't. Everything works fine on Single Player. Ive tried with only Forge installed too without any Core mods but it still glitches out.

**Comment by ImAK9** [comment]
Notice the Item Name above the hotbar changing too... Tab also goes dark grey...

**Comment by ImAK9** [comment]
It seems like Tools don't have this issue, it stays as white text when changed to.

**Comment by shadowfacts** [comment]
Use the forums for basic debugging. The Forge issue tracker is for confirmed Forge issues only.

**Comment by ImAK9** [comment]
Well, i am not getting any help anywhere...
