### ISSUE TITLE
[1.12] PlayerEvent$NameFormat and prefixes/suffix do not affect GuiPlayerTabOverlay

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#4151]
When using the NameFormat event to modify the display name for the player, changes made will not effect the server player list. This is because the player list does not use the player's display name, and will instead use the name from the GameProfile. The following shows the basic flow of how the tab name works and a possible entry point to fix the issue. 

GuiPlayerTabOveraly#getPlayerName gets the name from NetworkPlayerInfo#getDisplayName, if that name is null, get the name using the scoreboard team prefix, and the GameProfile name. 

NetworkPlayerInfo#getDisplayName returns a value this is set by SPacketPlayerListItem$AddPlayerData

AddPlayerData's display name is set in the constructor. This packet is constructed and sent to the client in SPacketPlayerListItem's constructor from the server. This packet is created in two places, both using EntityPlayerMP#getTabListDisplayName for the name that they send to the client. 

EntityPlayerMP#getTabListDisplayName returns null, is never overriden, and does not override anything else. 

Based on how the data flows, changing the return from null, to the display name of the player if the name has changed, should allow the name to be replaced with the correct one. Additionally, the prefix/suffix system added by https://github.com/MinecraftForge/MinecraftForge/pull/1708 does not affect the display tab either, for the same reason mentioned above. Prefix/Suffix are both applied as part of the display name in EntityPlayer, so fixing the above issue should also fix this one. 

My intended use case for this is to allow players to prefix their name on a server to represent their status. For example, if a player on a server is currently streaming, other players may want to know, so they don't say something they shouldn't. There have been mods which do something similar such as [Recording Status](https://minecraft.curseforge.com/projects/recording-status-mod). The way the mentioned mod does it is to [cancel the rendering](https://github.com/SlimeKnights/RecMod/blob/master/src/fuj1n/recmod/client/event/EventRenderGame.java#L39-L51) in `RenderGameOverlayEvent.Pre` and then render their own version of the hud, however this creates incompatibilities between mods that need to modify the tab gui.

**Comment by ghost** [comment]
The name on the tab overlay is sent via a SPacketPlayerListItem. It's then added to NetHandlerPlayClient's playerInfoMap. This field is final so you might need to use reflection to modify it.

**Comment by Darkhax** [comment]
@v0idst4r That is one way to do it, however that would introduce a client side component to this. This is something that should be handled by the server.
