### ISSUE TITLE
Coremod transformer isn't getting passed the classes that I want

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4152]
Basically I have a IClassTransformer that manages a bunch of my own sub transformers (I call them editors) (see https://i.imgur.com/wSHOJNK.png). Anyway I have a IFMLLoadingPlugin and I make getASMTransformerClass() return new String[]{TransformerManager.class.getName()}. I want it to transform the classes NetHandlerLoginClient and TransformerManager with it but for some reason it isn't passing those classes to the transform method. Now when I make a very simple IClassTransformer (see https://i.imgur.com/UCNncgx.png) and make getASMTransformerClass() return that class' name it **does** pass all the classes that I want it to pass to my TransformerManager. (I've checked by putting a simple System.out.println(transformedName);) Can someone please tell me what the hell is going on?

**Comment by v0idst4r** [comment]
I'll upload some screencaptures instead so it isn't so blurry in a sec.

**Comment by v0idst4r** [comment]
Just realised I uploaded a picture of something I was testing which also didn't work.

**Comment by ghost** [comment]
I could make a seperate IClassTransformer for every class I wanted to transform but thats inefficient and I plan on making a bunch more "editors" later.

**Comment by ghost** [comment]
Also on a sidenote when I make an ITweaker that registers the transformer it doesn't pass the classes I want whatsoever.

**Comment by ghost** [comment]
Figured it out basically my sub transformers were making the class load (I was using TheClass.class.getName()) before it got to transform it.
