### ISSUE TITLE
[1.12] Crash on RecipeBook click.

### ISSUE THREAD

**Issue by ImAK9** [MinecraftForge/MinecraftForge#4153]
https://pastebin.com/xT29j335

Crashing on pressing the Recipe Book in inventory.

No mods installed.

**Comment by KnightMiner** [comment]
You still have mods installed, the crash log says you are using Chisel, Storage Drawers, BlockDrops, and JEI (plus their dependencies). If this is really a Forge issue get a clean crash report with none of those.

**Comment by covers1624** [comment]
I'm 99.9% sure this ISN'T forge and is one of the mods you have installed, narrow it down, then report it to them.

**Comment by LexManos** [comment]
I added debug to better track this down, but yes its a case where a mod is screwing up a recipe and its somehow not in the registry.
Not a Forge issue.
