### ISSUE TITLE
Hiding vanilla item subtypes from creative inventory

### ISSUE THREAD

**Issue by averixus** [MinecraftForge/MinecraftForge#4161]
I want to be able to, say, hide polished granite but leave regular granite. Maybe an event could be added when a creative tab is populated so modders can edit the list of items before they are put into the inventory?

**Comment by LexManos** [comment]
No, it's the creative inventory it's supposed to show everything. There is no reason to hide someone else's things. If you REALLY have to be special, the registry substitution system allows you to do what you want.
