### ISSUE TITLE
[1.12] Calling getBedLocation() on a client side player object always returns the world spawn

### ISSUE THREAD

**Issue by Saalvage** [MinecraftForge/MinecraftForge#4163]
This makes getting a player's bed location in a client side only method impossible.

**Comment by williewillus** [comment]
Well, that makes sense. The client never knows it because it never needs to so the server doesnt send it.
If you need it you need to send it to the client yourself from the server

**Comment by Saalvage** [comment]
If that's the case then the method should only exist in EntityPlayerMP I suppose?

**Comment by LatvianModder** [comment]
The real issue is that it should only exist in EntityPlayerMP, and spawn point should only exist on WorldServer, but those can't be moved

**Comment by williewillus** [comment]
It's probably left over from the 1.3 SP/MP merge. Lots of things clientside are left unset/unused.

**Comment by LexManos** [comment]
Not a Forge issue, Forge is not in the busniess of Mojang code cleanup. If we were there would be A LOT more changes then there is. But ya, the data should only be accessible server side. Nothing syncs this data to the client.

**Comment by JamiesWhiteShirt** [comment]
If you need to be able to access the spawn point on the client side you can probably find a way to synchronise it manually with a packet and a capability on players.
