### ISSUE TITLE
Universal Bucket and Ore Dictionary

### ISSUE THREAD

**Issue by elifoster** [MinecraftForge/MinecraftForge#4165]
I'd like to register a specific bucket with the ore dictionary, but when the universal bucket is enabled, that doesn't seem possible, as the universal bucket uses NBT to differentiate fluids, and the ore dictionary completely ignores NBT (which means that registering one filled bucket registers *all* filled buckets).

The obvious way around this would be to create my own bucket and add that to the OreDict, but (unless I'm missing something), my fluid would still get added as a universal bucket in `getSubItems`, and so there would sort-of be two buckets for the same fluid, and (again, unless I'm missing something), there's no way to opt-out with a specific fluid from the universal bucket.

So, I'm wondering if there's an intended method for adding a bucket to the ore dictionary now that the universal bucket is in place.

**Comment by KingLemming** [comment]
This shouldn't be required - what specifically are you trying to do?

If you just want a certain fluid to be used in a crafting recipe, then yeah...I have a PR I really need to submit. :P

**Comment by elifoster** [comment]
The goal is to make a bucketed fluid that can be used in recipes the same as the vanilla milk bucket utilizing the Ore Dictionary.

**Comment by KingLemming** [comment]
Right so...yeah, I have some things that address this in an even better fashion in CoFHCore right now. I'll get them PR'd.

Basically though, you don't specify a bucket at all - you specify a Fluid, and then *any* fluid container (bucket, cell, can, tank) will work.

I'll reference the PR here when I send it in, but basically *that* will be the correct way to handle this, not OreDict at all.

**Comment by elifoster** [comment]
Does milk actually have a fluid though? I don't think it does.

**Comment by KingLemming** [comment]
It doesn't but that's a whole separate can of worms tbh - there are a host of issues caused by the Milk Bucket and we gotta figure that one out on a Forge level.

**Comment by iTitus** [comment]
Basically they issue for https://github.com/MinecraftForge/MinecraftForge/pull/4449
