### ISSUE TITLE
Crafting Recipe Search not working

### ISSUE THREAD

**Issue by santa4nt** [MinecraftForge/MinecraftForge#4166]
I just installed Forge (1.12-forge1.12-14.21.1.2387) and Optifine on top, and everything works fine for me, except that when crafting, I can't seem to search anything (see screenshot)!

![minecraft 1 12 7_11_2017 9_51_52 pm](https://user-images.githubusercontent.com/152710/28102395-bdbc2d44-6683-11e7-8621-d28f49773eea.png)

I'm sure it's not the resource pack that I use, because when I quit and used vanilla launcher, recipe book searching works as normal.

**Comment by mezz** [comment]
Please go to the forum first for tech support, if they find it's a Forge error then report here.
http://www.minecraftforge.net/forum/forum/18-support-bug-reports/

**Comment by santa4nt** [comment]
@mezz,

Thanks, I didn't know about the forum.

I posted here: http://www.minecraftforge.net/forum/topic/59394-112-crafting-recipe-search-not-working/

At least one other person reported the same issue.
