### ISSUE TITLE
Mod.dependencies javadoc should be updated, ModLoader no longer exists

### ISSUE THREAD

**Issue by Niko-sk2x** [MinecraftForge/MinecraftForge#4168]
The javadocs say:
`A simple dependency string for this mod (see modloader's "priorities" string specification)`

This javadoc was changed to this form in 2a19eca517b86d2958facba90a4927cb15cfe750 (https://github.com/MinecraftForge/MinecraftForge/blob/2a19eca517b86d2958facba90a4927cb15cfe750/fml/common/cpw/mods/fml/common/Mod.java)

ModLoader no longer exists, and any documentation on it may be very hard/impossible to find. I'm not submitting a PR because I don't know exactly how the dependency string works, and can't find any real documentation on it.

**Comment by Alpvax** [comment]
Link is broken. I think it should point to [https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/Mod.java](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/Mod.java)

**Comment by Niko-sk2x** [comment]
Updated, I accidentally pressed ctrl+x instead of ctrl+c

**Comment by mezz** [comment]
Good call. I remember digging into it at first, it felt pretty mysterious.
Fixed the javadoc here: https://github.com/MinecraftForge/MinecraftForge/commit/75433345ba2b9f5aff0b10c25c592a13b7c962cc
