### ISSUE TITLE
OnLivingAttack Hook Gets Called Twice on Players

### ISSUE THREAD

**Issue by Flashfyre** [MinecraftForge/MinecraftForge#4171]
EntityPlayer.attackEntityFrom calls net.minecraftforge.common.ForgeHooks.onLivingAttack but at the end of the method, if the damage amount is greater than 0, it calls super.attackEntityFrom (EntityLivingBase) which calls it again.

Edit: I'll also point out that this is interfering with the use of the hook for my mod where it adds a health-altering potion effect on hit and it's being added twice when players are hit, resulting in twice as much damage being done as is intended.

**Comment by MercurialPony** [comment]
This still hasn't been fixed? I can't continue working on my mod because of this.

**Comment by williewillus** [comment]
there isn't really a clean solution to it, besides removing the calls from the subclasses

but some people need them down there so they can cancel before specific logic runs

**Comment by jabelar** [comment]
> there isn't really a clean solution to it, besides removing the calls from the subclasses but some people need them down there so they can cancel before specific logic runs

If some people actually need something to hook in both locations, we should make a way to tell which location it was called from. Either add a field to the existing event or make them two sub-events.
