### ISSUE TITLE
[1.12] Item.shouldCauseReequipAnimation issues

### ISSUE THREAD

**Issue by pWn3d1337** [MinecraftForge/MinecraftForge#4175]
This method can be used to cancel the reequip anim, but has the side effects of the ItemRenderer not updating the held items in mainhand/offhand if you cancel the animation. This causes rendering bugs. 

The only way to fix this is by manually setting the fields in the ItemRenderer with Reflection (private fields).

Currently there is no clean way to cancel the anim on an item that changes its nbt tags without causing the ItemRenderer to glitch out.

**Comment by daxum** [comment]
Have you tried returning `changed || !(oldStack.getItem() == newStack.getItem())`?
It fixed the bugs for me.

**Comment by pWn3d1337** [comment]
your solution does not solve this problem. It does not matter how you formulate it, when the anim gets cancelled, the ItemRender is not in sync with the actual item you hold anymore. This is noticeable when you change nbt tags. ItemStack in your bar has the new tags, but the rendered item in your hand doesn't.

**Comment by LexManos** [comment]
You're actually correct, due to a short circuiting things. I've fixed it.
