### ISSUE TITLE
[1.12] minecraft forge handshakehandler exception on 2410

### ISSUE THREAD

**Issue by NarigudoBR** [MinecraftForge/MinecraftForge#4177]
When I create a world it sometimes just freezes at 0% when loading. full log(instance with no mods but forge): https://pastebin.com/PEg4EyfZ
-- System Details --
Details:
    Minecraft Version: 1.12
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1297137272 bytes (1237 MB) / 1529872384 bytes (1459 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx3072m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML:
    Loaded coremods (and transformers):
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Mobility Radeon HD 4500 Series'

**Comment by LexManos** [comment]
Forums.
