### ISSUE TITLE
Vanilla block rotations of 90° turning slightly darker with Forge

### ISSUE THREAD

**Issue by Maluscat** [MinecraftForge/MinecraftForge#4178]
Hey!

I've encountered a pretty annoying bug in Forge:
When the vanilla blockstates file, meaning "assets/minecraft/blockstates", contains block rotations of 90°, the blocks turn slightly darker ingame when Forge is installed, but only when a resourcepack is applied.
I've already tested it with the resourcepack solely containing the "dirt" texture in /blocks and the necessary pack.mcmeta, at which point I should add that the blockstates file with the rotations doesn't have to be provided by the resourcepack, for dirt I used the vanilla minecraft rotation, but also with this smallest resourcepack ever, the bug was still there. It does not appear with the vanilla resources
This happens at both rotation possibility, x and y.
Of course I've also checked in vanilla, but as one expects, nothing is found there.
Using solely Forge, no mod at all. (No, also not Optifine) on Minecraft 1.11.2, Forge version 13.20.1.2393, although: I've tested since which version this bug exists, and it appears to 
exists since minecraft version 1.9.0

Here are some screenshots:
![2017-07-14_05 56 28](https://user-images.githubusercontent.com/21200815/28197764-5b700eda-6859-11e7-8e5d-1f70af5df935.png)
Very visible on snow blocks

![2017-07-14_05 56 41](https://user-images.githubusercontent.com/21200815/28197775-6d3c23c4-6859-11e7-90b4-05228f04195b.png)
"x" rotation

![2017-07-14_05 56 51](https://user-images.githubusercontent.com/21200815/28197785-7a80c152-6859-11e7-90c4-ebc36332a98f.png)
Here's a picture of everything. The whole grass is dotted

**Comment by williewillus** [comment]
maybe upload a minimal RP that reproduces the issue?

**Comment by RainWarrior** [comment]
Please check if this still happens on the latest 1.12 version, there was a small bugfix in the lighting code that possibly affected it.

**Comment by Maluscat** [comment]
Nope, on 1.12 it still exists (Using the latest version 14.21.1.2412)

@williewillus Here, it's basically just this
[Testing texturepack.zip](https://github.com/MinecraftForge/MinecraftForge/files/1148782/Testing.texturepack.zip)
