### ISSUE TITLE
RecipeSorter

### ISSUE THREAD

**Issue by AEnterprise** [MinecraftForge/MinecraftForge#4181]
The recipe sorter has been marked as deprecated with a message that we should not use it and it would most likely be removed

https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/oredict/RecipeSorter.java#L54

a quick look shows forge doesn't apear to be using this anymore, is there a replacement that we should be using or is recipe sorting somehow no longer needed in 1.12?

**Comment by LexManos** [comment]
Recipe sorting is no longer done in 1.12, it uses a tree based search for doing things based on inputs. Which really can't be sorted.

**Comment by AEnterprise** [comment]
Should i keep this open as a reminder to remove this in 1.13 then as it cant be removed now without potentially breaking mods?

**Comment by raoulvdberge** [comment]
Keep open

**Comment by LexManos** [comment]
Closing unless someone can come up with valid soltution, and usecase.
