### ISSUE TITLE
[1.12] Launcher unable to load Forge profile

### ISSUE THREAD

**Issue by Flayzuh** [MinecraftForge/MinecraftForge#4191]
I've been trying to install a shaders mod via Forge API and the launcher is unable to process, let alone run, the Forge profile. 

The only thing I can think of to fix it is that it seems to crash as it unpacks the 0209-natives-windows.jar folder, at the very start of the launch, while all other versions (even as old as 1.7.10) run fine. Is there any way I can fix this?

**Comment by Flashfyre** [comment]
I feel like this is a Forge forums kind of thing...
