### ISSUE TITLE
CreativeTabs.hasSearchBar=true causes Forge to remove Items (1.12)

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4192]
Hi,

you can't create a Creativetab with searchbar and set Items using displayAllRelevantItems
(for NBT tags)

https://gist.github.com/MCmodding4K/4d9c30ac67fb5a74f26e6a1c58a0a180

**Comment by ghost** [comment]
btw, this is due to updateCreativeSearch

**Comment by ghost** [comment]
to fix it, i would either change it back to the old way (i have no idea when that was xD),
or i would move GuiContainerCreative.updateCreativeSearch to CreativeTabs.updateCreativeSearch, cause its not used to render anything, but the selection of the items in the tab

**Comment by ghost** [comment]
https://minecraft.curseforge.com/forums/general/general-discussion/228161-custom-creative-tab-search-bar-doesnt-seem-to-work

**Comment by ghost** [comment]
it was like that
https://gist.github.com/MCmodding4K/ba5470026362820d04199fa9317b2b12

**Comment by mezz** [comment]
Until you are certain about this being a bug in Forge, please use the Forge forums for debugging.
http://www.minecraftforge.net/forum/forum/18-support-bug-reports/
