### ISSUE TITLE
[Opinions Needed] More 'basic' OreDictionary lists for Vanilla Items

### ISSUE THREAD

**Issue by Baylem** [MinecraftForge/MinecraftForge#4195]
Why are there not default OreDictionary lists for default vanilla items? like Seeds, Planks, Logs, etc?

[Please read my latest comment for more clarification]

**Comment by shadowfacts** [comment]
What are you talking about? There are [lots of](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/oredict/OreDictionary.java#L85-L313) vanilla ore dictionary entries.

**Comment by DaedalusGame** [comment]
yeah there are several, this issue was likely triggered by the "listAllseed","listAllSeeds","seed","seeds" controversy

**Comment by Baylem** [comment]
I'm referring to things like seeds and things like that. and just simply adding more "basic" ore dicts than just the ones listed

**Comment by shadowfacts** [comment]
Then give more concrete suggestions, rather than just saying "there should be more".

**Comment by primetoxinz** [comment]
For the seed issue, to avoid capitalization issues `seed` would be the best to use.

**Comment by Baylem** [comment]
Thanks ^^ @primetoxinz

**Comment by DaedalusGame** [comment]
cookedMeat and meat could be other ones for other stuff

**Comment by Baylem** [comment]
@shadowfacts I'm going to wait for people to leave suggestions on the Thread then create a PR to add these. Sorry for not being descriptive enough to begin with.

**Comment by Baylem** [comment]
Alright, so I've been told I need to clarify more on what I want from this thread and the issue itself. I want to create a common consensus on how to label oredict lists for vanilla items. From what I understand there are several mods that include their own oredict tags for vanilla items and variants thereof. So I wanted to do this to create a naming 'standard' that would help the community move towards a better oredict usage than each and every mod adding their own tags. 

Wheat seeds currently have tags such as seed, seeds, listAllSeed, listAllSeeds, listAllseed, listAllseeds. 
These all fulfill the same purpose. 

All suggestions are welcome and I am open for discussion over how this should be done.

**Comment by Darkhax** [comment]
I have a list of ore dict entries for vanilla content, that have been used by several mods. 

```
        OreDictionary.registerOre(BED, Items.BED);

        OreDictionary.registerOre(HOPPER, Blocks.HOPPER);

        OreDictionary.registerOre(BOOKSHELF, Blocks.BOOKSHELF);

        OreDictionary.registerOre(CROP_BEETROOT, Items.BEETROOT);

        OreDictionary.registerOre(BLOCK_MAGMA, Blocks.MAGMA);

        OreDictionary.registerOre(BLOCK_NETHER_WART, Blocks.NETHER_WART_BLOCK);

        OreDictionary.registerOre(BLOCK_BONE, Blocks.BONE_BLOCK);

        OreDictionary.registerOre(SHULKER_SHELL, Items.SHULKER_SHELL);
        OreDictionary.registerOre(FENCE_WOOD, Blocks.OAK_FENCE);
        OreDictionary.registerOre(FENCE_WOOD, Blocks.SPRUCE_FENCE);
        OreDictionary.registerOre(FENCE_WOOD, Blocks.BIRCH_FENCE);
        OreDictionary.registerOre(FENCE_WOOD, Blocks.JUNGLE_FENCE);
        OreDictionary.registerOre(FENCE_WOOD, Blocks.ACACIA_FENCE);
        OreDictionary.registerOre(FENCE_WOOD, Blocks.DARK_OAK_FENCE);

        OreDictionary.registerOre(FENCE_GATE_WOOD, Blocks.OAK_FENCE_GATE);
        OreDictionary.registerOre(FENCE_GATE_WOOD, Blocks.SPRUCE_FENCE_GATE);
        OreDictionary.registerOre(FENCE_GATE_WOOD, Blocks.BIRCH_FENCE_GATE);
        OreDictionary.registerOre(FENCE_GATE_WOOD, Blocks.JUNGLE_FENCE_GATE);
        OreDictionary.registerOre(FENCE_GATE_WOOD, Blocks.ACACIA_FENCE_GATE);
        OreDictionary.registerOre(FENCE_GATE_WOOD, Blocks.DARK_OAK_FENCE_GATE);

        OreDictionary.registerOre(SHULKER_BOX, Blocks.WHITE_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.ORANGE_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.MAGENTA_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.LIGHT_BLUE_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.YELLOW_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.LIME_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.PINK_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.GRAY_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.SILVER_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.CYAN_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.PURPLE_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.BLUE_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.BROWN_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.GREEN_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.RED_SHULKER_BOX);
        OreDictionary.registerOre(SHULKER_BOX, Blocks.BLACK_SHULKER_BOX);

        OreDictionary.registerOre(CHEST, Blocks.WHITE_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.ORANGE_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.MAGENTA_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.LIGHT_BLUE_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.YELLOW_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.LIME_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.PINK_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.GRAY_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.SILVER_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.CYAN_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.PURPLE_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.BLUE_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.BROWN_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.GREEN_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.RED_SHULKER_BOX);
        OreDictionary.registerOre(CHEST, Blocks.BLACK_SHULKER_BOX);

        OreDictionary.registerOre(SEED, Items.WHEAT_SEEDS);
        OreDictionary.registerOre(SEED, Items.PUMPKIN_SEEDS);
        OreDictionary.registerOre(SEED, Items.MELON_SEEDS);
        OreDictionary.registerOre(SEED, Items.BEETROOT_SEEDS);

        OreDictionary.registerOre(RAIL, Blocks.RAIL);
        OreDictionary.registerOre(RAIL, Blocks.ACTIVATOR_RAIL);
        OreDictionary.registerOre(RAIL, Blocks.DETECTOR_RAIL);
        OreDictionary.registerOre(RAIL, Blocks.GOLDEN_RAIL);

        OreDictionary.registerOre(ARROW, Items.ARROW);
        OreDictionary.registerOre(ARROW, Items.SPECTRAL_ARROW);
        OreDictionary.registerOre(ARROW, Items.TIPPED_ARROW);
```

**Comment by primetoxinz** [comment]
Assuming all of those constants are the same as the string camelcased?

**Comment by Darkhax** [comment]
Yep, Constant case to camel case.

**Comment by KingLemming** [comment]
Yeah, just gonna state outright that some of those aren't good ideas.

Should we list every ore as "ore" in addition to ore<whatever>? Also, equating Shulker Boxes to chests? No thanks - they aren't equivalent.

**Comment by primetoxinz** [comment]
Which ones _are_ good ideas @KingLemming?

**Comment by DaedalusGame** [comment]
I'd admit that shulker boxes as chests isn't such a good idea, because it breaks an existing tag. The other ones seem fine tho?

**Comment by Darkhax** [comment]
Having access to a general list of known ores would be useful in multiple circumstances. I think shulker boxes are more equivalent to chests than you think. Compared to the vanilla chest entries (normal, trap and nether), the only thing that sets the shulker box apart is the name and animation. (Ender chests keep their contents). If you still find shulker boxes being labeled as chests unacceptable, how about creating another grouping for things which are used for the purpose of storage?

**Comment by DaedalusGame** [comment]
hm i dunno about this, i think having a general storage tag would be too broad. think about it, you can probably think of a recipe that would require any seed, or any chest, or any fence, but can you really say that you'd want a recipe that takes any storage container that stores 27 items, regardless of whether you can obtain it in 15 minutes of playtime or 15 hours? (the chest tag already kinda breaks this rule, as ender chests are pretty expensive compared to regular wooden chests)

**Comment by KingLemming** [comment]
Okay so here's the thing. A LOT of mods already do blanket scans of the oredictionary to set up recipes. However, when you name the meta-grouping "ore", then that screws up the substring() logic used by basically all of these mods, since they look for ore<something>.

Also, just as there is a standard with ore<something>, dust<something>, etc...the meta-tag should really be list<something> such as "listAllOre" or "listOre." But having it as "ore" is confusing and very unhelpful.

**Comment by KingLemming** [comment]
Or, even better, "list:ore"

That way it is explicitly shown as a meta-tag and can be discarded /ignored by the overwhelming majority of mods which see no need for it.

**Comment by DaedalusGame** [comment]
Ah, I understand now, you're suggesting a blanket tag for ores to be added, similar to "dye", but it would screw up existing mods. From what I've heard, list and listAll shouldn't be used as oredictionary tags? Not really sure why that is. The way it's currently handled is a bit of a pitfall I suppose, dye tags must already be implemented properly, as "dye" is a tag aswell as e.g. "dyeBlack"; whereas ore* and ingot* can be handled with more leeway...

**Comment by Alpvax** [comment]
@darkhax Ender Chests do not store their inventory, they just allow access to an inventory that is linked to the player. I don't think that they should be oredicted with chests.
Shulker Boxes have more in common with mod-added backpacks than with chests, so they also should not be oredicted either.

**Comment by DaedalusGame** [comment]
not really much choice in that matter, ender chests are already oredicted as chest, i agree that they probably shouldn't be?

**Comment by Baylem** [comment]
@Alpvax @DaedalusGame I will seperate Shulker Boxes, Chests, and Ender Chest as different oredict because they have different properties. @Alpvax Is correct.

But I made add them to a list of all chests or storage. Which may or may not make it into the PR. However I'm still debating on how the naming of the lists is going to go.

**Comment by SocraticPhoenix** [comment]
So... No one hate me for this suggestion.. couldn't we use something like `ResourceLocation` or a specialized alternative to have the meta tags & names separate... That would break most things that use the ore dict though... It's just, the more complex the convention, the harder it is to enforce/rely on, and - correct me if I'm wrong - but the ore dict is the only registry-type-thing I know of that doesn't use resource locations... Maybe a `type, category, name` system? For example, iron ore would have the type `block` (or item), the category `ore`, and the name `iron`... This is probably a silly idea...

**Comment by primetoxinz** [comment]
@SocraticPhoenix see [#4139](https://github.com/MinecraftForge/MinecraftForge/pull/4139)
