### ISSUE TITLE
Block.getLightValue unnecessarily slow

### ISSUE THREAD

**Issue by PhiProven** [MinecraftForge/MinecraftForge#4199]
During our rewrite of the lighting engine we came across the strange implementation of `Block.getLightValue(IBlockState, IBlockAccess, BlockPos)`. Instead of delegating the call to the given state, it fetches the state from the given world and pos. IMHO, this seems strange for a member function of `Block` and really should be a static helper function, if needed at all. Furthermore this behavior is not fullfilled by `BlockFluidBase` and `BlockFluidClassic`, so the specification is currently a bit broken anyway.
This behavior was introduces due to #349. I can't reproduce the issue with reverting the commit.

While fetching the chunk and blockstate are quite cheap operations per se, the lighting engine uses almost all of its time for such cheap things. It's a bit hard to measure the exact impact of `Block.getLightValue` on the lighting engine, as it is called at many different places, but I think it should be quite a bit (`World.getRawLightFor` has to get 6 chunks and blockstates for the neighbors. `Block.getLightValue` introduces an additional one, so the impact should be something like 1/7).  Additionally, `Chunk.checkLight(int, int)` directly calls `Block.getLightValue`. This call already takes up ~10% of total worldgen time, which is quite a lot.

Vanilla just uses the provided state and it seems really strange why the method should be called with a non matching state and position pair at all. Strangely, there are two places where they are indeed inconsistent:
* In `world.setBlockState` during worldgen: As far as I can tell, Vanilla simulates fluids instantly and replaces the dynamic blocks with their static counterparts. Hence, `setBlockState` is called recursively and the static block is placed before the call for the dynamic block is finished. `getLightValue` is only called to determine whether `checkLight` has to be called. Since the innermost call to `setBlcokState` already makes the right decision, it is irrelevant if the outer calls do the calculation on the wrong block state.
* `Block.getPackedLightmapCoords` is sometimes called with non matching state and position pairs. `BlockModelRenderer.renderModelFlat` (and some other rendering related methods) can call it with a shifted pos without adjusting the block state. Does anyone know, why this is so? Interestingly, Vanilla uses the provided state instead of the actual state, so it should produce a different result from Forge. If the light value really should be fetched from the actual state, then I think the code should be put in a static helper method instead of `Block.getLightValue`.

I can make a PR for this, but I need to know, whether Forge or Vanilla is "right" about using the provided state vs. actual state for the light value in `Block.getPackedLightmapCoords`.

**Comment by bs2609** [comment]
I also wondered about this here: https://github.com/MinecraftForge/MinecraftForge/issues/3754#issuecomment-304770290

I think Fry is the only one who can give a definitive answer about what's intended behaviour in this case.

**Comment by williewillus** [comment]
Related: #2773

**Comment by PhiProven** [comment]
As I'm completely unfimiliar with the rendering code: Why is the `Block.getLightValue` included in the `packedLightmapCoords` at all?
With the current default implementation, `getLightValue` is always delegated to the actual block. But the lighting engine already takes this contribution into account. So we could also just pass `0` to `getCombinedLight` and would get the same result.
~~Is there a reason to include the source block light (ie. `Block.getLightValue`) of the neighbors and not the overall block light (ie. `World.getLightFor`) similar to `World.getLightFromNeighbors`? (Again, I don't know what the code is supposed to do)~~
`IBlockAccess.getPackedLightCoords` already calls/implements something like `World.getLightFromNeighbors` in both implementations. This already takes into account the overall light values of the neighbors (and hence in particular their source light values, ie. `getLightValue`) (at least if `Block.useNeighborBrightness()` returns `true`). This means that the calls to `getLightValue` can just be replaced by `0`, as long as `getPackedLightmapCoords` is at most shifted by 1 block. Is there an instance where this is not the case?

**Edit:**
I'm not sure, though, why `World.getLightFromNeighbors` doesn't take into account the block itself. For example, it would return `14` for torches. In this case the additional source value indeed makes a difference. But I have the feeling that it makes more sense to include the block itself in `getLightFromNeighbors` instead of adding the source light value only for rendering.
With this patch to `getLightFromNeighbors`, I think we could remove the calls to `getLightValue` inside `getPackedLightmapCoords` completely, as the lighting engine + `getLightFromNeighbors` already take care of everything. This should also resolve #3754.
What are your thoughts on that?
(Btw. `World.getLightFromNeighbors` and `ChunkCache.getLightForExt` don't do exactly the same, as `ChunkCache` includes the block below while `World` doesn't)

**Comment by bs2609** [comment]
~~It's (I think) possible for the position to be shifted by +/-1 in all x, y, z directions.~~ In any case, as you said, that would only apply if `Block.useNeighborBrightness()` was true.

**Edit:**
Actually, giving it a more proper look, I think only a shift of one is possible.

**Comment by PhiProven** [comment]
The question is whether the source light value of the neighbor should even be taken into account if `Block.useNeighborBrightness()` was `false`. Unfortunately I don't understand the code enough to judge about that...

**Comment by bs2609** [comment]
OK, what I think the intent of this is:

We want to know what the lighting for our block looks like at positions where our block is _not actually present_.

The world lighting corresponds to the original position of our block only. 
In cases where our block's light is the dominant light source at a position, we will get an incorrect value

We need to know what the light level at a position would look like _if our block was actually there_, although it isn't, and the calculated light grid doesn't account for this.

As any block light caused by our block will be reduced at all positions other than our blocks actual position, we take our own source light level as a minimum value for block light.

This applies regardless of the result of `useNeighborBrightness`.

**Comment by PhiProven** [comment]
"We want to know what the lighting for our block looks like at positions where our block is not actually present."
Why do we want that?

**Comment by bs2609** [comment]
Because our block faces point outwards, not inwards.

**Comment by PhiProven** [comment]
~~If I disable the lighting engine, the faces of `sea_lantern`s are still rendererd bright (even though the neighbors have a light value of `0`). However, the current implementation of `Block.getLightValue` fetches the actual block state for the given position. Hence it doesn't simulate the sea lanterns at the neighbor positions.
So, the faces of light sources are rendered correctly even without this piece of code.~~
(Shouldn't write comments based on memory...)

**Comment by PhiProven** [comment]
I'm currently tracing all calls to `Block.getLightValue`.
So far, I have found a fundamental difference between Forge and Vanilla: Falling blocks. In Forge, a falling sea lantern is dark, while it is bright in Vanilla.
This indeed cannot be done with the cached result of the lighting engine. Is there a simpler fix for this particular case than always calculating `Block.getLightValue` even if this could be ommitted in all other cases? Would it instead be possible to somehow apply this patch to `RenderFallingBlock`?

**Comment by PhiProven** [comment]
From what I have seen so far, the intention of the code is indeed to correct the faces of light sources.
In fact, my comment above was quite wrong... If I disable the lighting engine, sea lanterns are rendered dark in Forge but bright in Vanilla.
I assume that with enabled lighting engine, Forge renders the faces with a light value of `14` while Vanilla uses the correct light value of `15`. This means that the Forge code that fetches the actual block is probably "wrong".
However, I'm not sure why only the source light but not the overall light value is taken into account for the brightness of the faces.

**Comment by PhiProven** [comment]
Does it make sense to take into account the overall light value calculated by the lighting engine instead of just the source light value?
In this case, I think the call to  `getLightValue` can be removed and the calculated light value could instead be passed to `getPackedLightmapCoords` as additional parameter.
This would remove the strange specification that the `state` and `pos` parameter for `getLightValue` are not related in general. This would also remove concurrency issues related to calucation of `getLightValue` on some possibly outdated data.
However, this would not cover the case of falling blocks. I'm not sure, though, how relevant this edge case really is. As this inconsistency with Vanilla exists for a couple of years now and nobody has complained yet, I think it shouldn't be that much of a problem :)

**Comment by PhiProven** [comment]
What I had in mind with my previous comment should look something like [this](https://github.com/Mathe172/MinecraftForge/tree/cleanup_getLightValue_rendering). It's just a draft and shouldn't be taken too serious :) (I don't think that I'm going to make a PR out of it though)
Unfortunately, it's quite a lot of patches...
What are your thoughts on this approach for solving #2773 and #3754?

**Comment by thecodewarrior** [comment]
In my opinion, while this may help make #3754 less pronounced, it still doesn't address the fact that it gets called hundreds or sometimes thousands of times per block model. Some mods may use tile entity info for lighting, so it _really_ should be cached in the vertex lighter.

**Comment by PhiProven** [comment]
I was talking about https://github.com/Mathe172/MinecraftForge/tree/cleanup_getLightValue_rendering (ie. not calling `getLightValue` at all) as a possible approach for solving the two issues :)
But as that's not really concerning my original issue (ie. the default implementation of `getLightValue` being "slow"), I should probably move the discussion to one of the other two topics.

**Comment by bs2609** [comment]
Can this be considered 'resolved' by #4202/#4203?
