### ISSUE TITLE
[1.10.2-1.12] Missing nodes from graph.

### ISSUE THREAD

**Issue by LXGaming** [MinecraftForge/MinecraftForge#4211]
Attempting to start Minecraft after disabling mods via the 'fmlModState.properties' file results in this crash https://pastebin.com/sdd0auH2

I believe the issue to due to 'CreeperHost' being disabled but still having its API registered. I was able to delete 'net.creeperhost.creeperhost.api.packet-info.class' from within the Jar and did not experience a crash.

I have tested this and have had the same results on the following forge versions:
 - 1.10.2-forge1.10.2-12.18.3.2316
 - 1.12-forge1.12-14.21.1.2415

**Comment by mezz** [comment]
I don't think disabling mods with FML is properly supported, it's more like an experimental feature.
You should be able to just delete the mod and connect to the server, I think it's client-side only.

**Comment by Alpvax** [comment]
Or just rename the .jar to .jar.disabled or some other invalid extension, then you can easily restore it in future.

**Comment by CloudyPSP** [comment]
Additionally, the mod itself allows you to disable all its functions through the configuration UI (I'm the author, lost my regular account due to misplacing my yubikey, d'oh!)

**Comment by Cloudhunter** [comment]
Correct - client side only. You can also disable the mod entirely from the config GUI included in the mod.
