### ISSUE TITLE
Enhance @Config annotation system with server-overridable config values

### ISSUE THREAD

**Issue by magneticflux-** [MinecraftForge/MinecraftForge#4214]
In many mods, config values are used on both the client and the server to determine results of recipes, burn times of fuel, and other gameplay features. Issues arise, however, when these values are not the same.<sup>[[1]](http://www.minecraftforge.net/forum/topic/30596-solved18-syncing-config-files-across-server-and-client/)</sup>

Take, for example, the case of a mod's fuel burn time. The user has a value of 8000 ticks in their local config. In single player, the issue is moot: only one set of files matters. Unfortunately, when the user connects to a server with a 4000 tick burn time in their config, graphical bugs emerge due to the inconsistency in configuration.<sup>[[2]](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/2244728-how-to-make-server-config-override-client-config)</sup>

I propose that after server and client mod compatibility is checked and the client is about to connect, ~fields~ classes that are using the `@Config` annotation system and have opted-in to being overridden using a new annotation should have the server's field values written to them.

Additional annotations or an Enum type may be useful for defining client-only config options such as rendering options, server-only options, client-overrides-server options, and server-overrides-client options.

For reference, the Mekanism mod (and likely many others) works around this by implementing a [massive custom message](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/network/PacketConfigSync.java) that is sent when a [client connects](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/CommonPlayerTracker.java).
- [1] http://www.minecraftforge.net/forum/topic/30596-solved18-syncing-config-files-across-server-and-client/
- [2] http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/modification-development/2244728-how-to-make-server-config-override-client-config

I'd love to try my hand at implementing this myself, but I'm not quite sure about where/when I would hook into the client-server connection process from inside of Forge.

**Comment by Xalcon** [comment]
"Client-overrides-server options"? Do you have a usecase for that?

**Comment by tomelfring** [comment]
I **think** "client-overrides-server" is how it's currently, the client does nothing with the value and keeps the original value (Just the same as not sending the value at all). If it's overwriting something on the server it would be a huge mistake.

**Comment by thilokru** [comment]
I can't support this. The player is able to edit his local configs, even ingame, messing up your sync. As far as I remember, the config system isn't inteded to be used for relevant game play constants.

**Comment by diesieben07** [comment]
If something like this is added we need a 2nd set of the config, one that represents the local data (client) and one that is received from the server.

**Comment by magneticflux-** [comment]
@Xalcon @thommy101 Client-specific rendering options was really what I had in mind, but that can fall under client-only. I guess client-overrides-server could be removed unless someone else comes up with a compelling use case.

@thilokru You're right, which is why options annotation to be overridden should be hidden while connected to a server. For your second point, many mods are extremely configurable in their balance, some even allowing users to choose the amount of items they receive from recipes. If configs weren't made for gameplay reasons, large modpacks would have no way to balance hundreds of mods together and niche modpacks would have no way to dramatically change game balance.

@diesieben07 Many mods ([CoFHCore](https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/CoFHCore.java#L73), [Thermal Foundation](https://github.com/CoFH/ThermalFoundation/blob/master/src/main/java/cofh/thermalfoundation/ThermalFoundation.java#L73), [Mekanism](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/config/MekanismConfig.java#L78), and others) already do this, but a standardized system would make it much easier for modders to create mods and much less likely that bugs get introduced by mods.

I'm always open to more suggestions and improvements!

**Comment by thilokru** [comment]
To follow up on @diesieben07's argument, many config options will be stored in static fields. For them, server side syncing will be really ugly, as you'd need somewhere to store the clients config. Also, what about single player? Single player uses a server, but will access the same config as "the client".

IF you create a PR, its annotation should only be allowed on fields with object types, because the mod will most likely access fields of the object and not the objects instance itself. Then you'd need to come up with a nice way to store the original copy of these objects.

I really hope you can come up with something, as I can't think of a nice way, but would really (personally) appreciate this functionality.

EDIT: Grammar and logic issue fixed.

**Comment by marvin-roesch** [comment]
"Client overriding server" could be useful, but it'd require maintaing a mapping from players/clients to their respective configs. As others have mentioned, the current system isn't really designed for different instances of a config, so it would require a somewhat major rework.

**Comment by magneticflux-** [comment]
Here's my idea that would enable us to treat singleplayer the same as multiplayer with regard to settings:

Client options would reside in a separate file `$MODID_client.cfg` and would always be available to the player. They can be changed during single- and multi-player modes and they get assigned to their fields immediately. Perhaps a `Property<T>` system that would allow object to be listened to for changes? That way mods could add listeners to certain config options and adjust rendering options in response to individual changes rather than check every single property every time one changes.

Common options would reside in the `$MODID_common.cfg` file. In this file, settings like fuel burn times, block hardness/resistance, recipe results, difficulty settings, etc. would reside. Here's the most important part: if the player is an `op` on the server, the common options would appear alongside the client options. When an op changes any common options, the common options object would be serialized into bytes and sent in a message to the server. Servers would also be required to fire `ConfigChangedEvent`s, which would be propagated to all clients.

Server options would reside in the `$MODID_server.cfg` file. I don't really know what this file could contain, but it would only be available to the server. Maybe something like port information? It would have to be edited by hand and the server would have to be restarted to get the new config. Like the client configs, this config would only be available on the the server side. I don't see it getting much use, but I guess it should be here for the sake of completeness.

In order to prevent the client from directly accessing the server configuration (the static fields problem), a `SidedProxy` system must be used.
- The `ClientProxy` would have a *non-static* reference to two config ***objects***: the client config and the common config.
- The `ServerProxy` would have a *non-static* reference to two config ***objects***: the common config and the server config.

Both the server and the client would accept updates to the common config: the client side will accept updates from the server and the server side will accept updates *only* from clients that are operators.

I think that this system would cover nearly every mod's case, and mods that have more complex configuration (CoFH World perhaps?) would have to either improve this system by allowing an arbitrary number of configurations to be marked as `Client`, `Server`, or `Common`, or simply write their own syncing system.

Anyone more familiar than me with Forge want to chime in on the feasibility of this idea?

EDIT: To summarize my thought process, playing singleplayer would be treated the same as playing multiplayer as an operator. On a server, non-ops would see client config only and ops would see client *and* common config. On a singleplayer world, the owner of the world would see client and common config, just like an operator on a server.

**Comment by KnightMiner** [comment]
I'd rather not have every mod triple it's number of config files. The distinction is decent, but I feel it better fits on an option by option basis. So keep one file, but mark the options based on their side.

**Comment by thilokru** [comment]
Forcing a mod programmer to use a proxy to access his own static fields? Good luck. With that.

**Comment by magneticflux-** [comment]
@thilokru That's the thing, the only static field should be the proxy. We can't stop modders from abusing static fields; every new Java developer just marks everything as `static` when the compiler tells them to. This system would likely require the proxies to implement an interface, perhaps `IClientConfigStore` and `IServerConfigStore` which both extend `ICommonConfigStore`? If the config fields were static, the client and server would be writing over the same common config file. Keeping two config files is necessary to simplify the process of opening a local world to LAN.

@KnightMiner While preventing absurd numbers of config files is good, many larger mods already have several config files for different modules. I would like to keep these options in separate files so that users can copy the common config file from server to client  and copy the client/server configs between clients/servers without any issue. Would putting the files in `$MODID/$MODID_client.cfg` be better?

**Comment by thilokru** [comment]
@magneticflux- I want to point out, that your root config class is required to have public static fields.

**Comment by magneticflux-** [comment]
@thilokru Actually, looking through the code, it checks for a static `instance` field of the same type as the class. If that is found, it draws fields from that instance rather than ignoring non-static fields. The relevant lines are [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/config/ConfigManager.java#L221) and [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/config/ConfigManager.java#L300).

**Comment by thilokru** [comment]
No, it doesn't. If your reflecting on an instance, it only accepts non-static fields. But if you are indeed in the root class, and therefore no instance exists, it will only accept static fields. Look at your first link.

**Comment by magneticflux-** [comment]
@thilokru Ah, I see now. There is, however, already logic in place to accept an instance instead of a class, which would make it easy to extend this to instances. I think an overloaded public `sync` method that takes an Object along with a class would do the trick.

**Comment by KnightMiner** [comment]
@magneticflux- yes, large mods already use multiple files. But your proposal triples those files as well. Some method to keep different config types in the same file makes more sense, either by having a client, common, and server section or marking individual properties with their type

**Comment by thilokru** [comment]
`@Config` annotates a class, not a field. If you'd annotate a field, which would then contain your config object, you can't be certain about its type. Therefore, you must annotate a class. I can't see how you want to use objects as root.

**Comment by magneticflux-** [comment]
@KnightMiner What about a directory structure like this? `config/client/$MODID.cfg` and `config/common/$MODID.cfg`

@thilokru I was thinking of adapting the `@Config` annotation for fields. I don't quite understand why you can't be certain of its type though. Don't you have access to the `Field` object? The end goal in mind with annotating fields is so that there can be two instances of a `MyModCommonConfig` object in a single Java process. This is needed because the server and client should not be able to override each other: all communication should go through messages sent instead of accessing static fields from server and client code.

**Comment by thilokru** [comment]
OK, I'm out of arguments. Let's see what you can come up with.

**Comment by magneticflux-** [comment]
@thilokru ~~~Should I target 1.12.x with my changes, or base them off of 1.11.x?~~~ Nevermind, it's literally at the bottom of the readme lol

**Comment by thilokru** [comment]
According to previous discussions in other threads, you should always base it on the most current version. But that is not my decission.

**Comment by LexManos** [comment]
A system that I have had in mind, but never gotten around to doing was creating a tiered config system.
Global - What we have now, loaded once at startup, mainly a 'template' for the others and other values that can't be changed at runtime.
Universe - Server/Save level configs that get loaded by the server when the server starts. This could be expanded to sent to the client when connecting to a server. Either way its a seperate config that the modder would know about that gets reloaded multiple times in a lifecycle.
World - As you can imagine per-world config values. Again potentially synced S->C be it on world switch, or server connect. 

This is just something that hasn't really been a priority so I haven't gone through and done it yet. As I have other things to work on. If you guys want to start implementing it. I'll give it consideration. I won't be here to hold your hand on it. But @mezz can do at least the first sanity checking on things. And him and I can talk so that he knows what I want from it.

**Comment by magneticflux-** [comment]
Do we want to get a Google Document or something and start writing up a draft of this config overhaul? I think there's some good ideas here but we need some precise requirements before we move forward so we don't make a mess.

**Comment by magneticflux-** [comment]
Here is a draft design document I whipped up: [Link](https://docs.google.com/document/d/1dhDEznXwx61Wq-WX60R8qfWa-UkV091agFg3WQaxrvQ/edit?usp=sharing)

I'll add people as editors if they request so in a comment.
