### ISSUE TITLE
装了Forge之后,切换语言和材质包,java会崩溃

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4215]
装了Forge之后,切换语言和材质包,java会崩溃

Forge版本: forge1.12-14.21.1.2413
java版本: 1.8.0_141
Minecraft版本: 1.12

![qq 20170721121737](https://user-images.githubusercontent.com/25134114/28448951-9fe50bd2-6e0e-11e7-9da5-37d7177c75b6.png)

**Comment by magneticflux-** [comment]
@Rsplwe Could you provide the Forge logs from the crash? A Windows 7 dialog that I can't Google Translate isn't going to be much help.

**Comment by mezz** [comment]
我们不会说中文 (we cannot speak Chinese)
Sorry try http://www.mcbbs.net/forum.php
