### ISSUE TITLE
[Feature Request] Add PickEvent

### ISSUE THREAD

**Issue by sokratis12GR** [MinecraftForge/MinecraftForge#4216]
You currently can't do the pick on blocks/entities unless you do a hacky way around it.
This could help if modders want the players to recieve given itemstacks with custom properties for players (in creative ofc).
i.e: have an entity and give it nbt data, if you pick the entity again it will get the nbt data. (already in vanilla)
but this event would allow to modify this, and/or change the given itemstack and etc...

**Comment by diesieben07** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/3668
