### ISSUE TITLE
[Feature Request] Add AdvancementReloadEvent

### ISSUE THREAD

**Issue by sokratis12GR** [MinecraftForge/MinecraftForge#4217]
A reload event with two stages:
* ReloadEvent.Pre which is cancelable
* ReloadEvent.Post which is ran after everything reloads

In Pre, modders would be able to stop the reload, from reloading specific advancements.
While in Post, modders would be able to do things with the advancements that have reloaded.

**Comment by mattmess1221** [comment]
Might as well catch the loot tables and structures as well. Maybe put the hook with the /reload command.
