### ISSUE TITLE
After installing the forge, switching the language or resource pack will cause the java to crash

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4218]
After installing the forge, switching the language or resource pack will cause the java to crash

Jave Version : 1.8.0_141
Forge Version : forge1.12-14.21.1.2413
Minecraft Version : 1.12
OS Version : Windows 7 x64

log:
[fml-client-latest.txt](https://github.com/MinecraftForge/MinecraftForge/files/1165434/fml-client-latest.txt)
[fml-junk-earlystartup.txt](https://github.com/MinecraftForge/MinecraftForge/files/1165437/fml-junk-earlystartup.txt)
[latest.txt](https://github.com/MinecraftForge/MinecraftForge/files/1165438/latest.txt)

![qq 20170721121737](https://user-images.githubusercontent.com/25134114/28462971-7a351098-6e50-11e7-9306-1ff2e1c5535c.png)

**Comment by TechnicianLP** [comment]
Reloading Resources can take a while - how long did you wait before telling windows to close the programm? 
If you did wait for more than (let's say) 10 minutes and the problem still persists, someone will help to find the problem

**Comment by LexManos** [comment]
This is not tech support.
