### ISSUE TITLE
[1.12] Shulker Boxes cannot be dyed using oredicted dyes

### ISSUE THREAD

**Issue by KnightMiner** [MinecraftForge/MinecraftForge#4222]
Unlike most other vanilla recipes, shulker boxes cannot currently be dyed using moded dyes. It was not caught by the recipe replacer since shulker box dyeing uses a custom recipe (`net.minecraft.item.crafting.ShulkerBoxRecipes.ShulkerBoxColoring`) in order to preserve inventory contents when dyeing.

I tested based off build 1.12-14.21.1.2413 which is after the recipe fix, so custom dyes do indeed work in other recipes such as wool, just not shulker boxes.

**Comment by Landmaster** [comment]
@KnightMiner see pull request #4223 for a possible fix
