### ISSUE TITLE
Finite Fluid Density Swapping

### ISSUE THREAD

**Issue by rslink** [MinecraftForge/MinecraftForge#4235]
In `BlockFluidFinite.java` Lines 235-238 are all set to `other` 236, and 238 should be set to use the `pos` position:
```
world.setBlockState(other, myState.withProperty(LEVEL, amtToInput - 1), 3);
world.setBlockState(pos, state, 3);
world.scheduleUpdate(other, this,  tickRate);
world.scheduleUpdate(pos, state.getBlock(), state.getBlock().tickRate(world));
```

**Comment by mezz** [comment]
Thanks, looks like this is supposed to match the code block above it.
I'll take a look at what this might be breaking.
