### ISSUE TITLE
Game freezes when minimizing title screen

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4239]
There is no stack trace, the game stops responding when you try unminimizing it.

**Comment by EmanYm** [comment]
Going to need a little more information than that...
You also might want to go post this on the forums before you're yelled at for posting in the wrong place.

**Comment by mezz** [comment]
From the issue template,
Please go to the forum first for support with crashes and issues.
http://www.minecraftforge.net/forum/forum/18-support-bug-reports/

**Comment by ghost** [comment]
There is no more information that I can provide. It happens on various forge version up to the latest 1.12. On Windows 10, stay on the title screen and press the [-] button, come back after 5 minutes or so and the game will be completely frozen and you'll have to force close it.

**Comment by mezz** [comment]
There are logs. 
Please go to the forum first for support with crashes and issues, they have a lot of experience solving this type of thing.
This is simply not the right place to report this kind of thing, the forums are.
