### ISSUE TITLE
Vec3 pool size error

### ISSUE THREAD

**Issue by Masterspvpro** [MinecraftForge/MinecraftForge#4240]
This is what happens when i launch my Mc with 1.5.2 with forge but no mods

Minecraft has stopped running because it encountered a problem; Failed to start game

--- BEGIN ERROR REPORT ed8f8775 --------

Generated 27/7/2017 

-- System Details --
Details:
	Minecraft Version: 1.5.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 61164544 bytes (58 MB) / 191148032 bytes (182 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v7.51 FML v5.2.23.737 Minecraft Forge 7.8.1.737 16 mods loaded, 16 mods active
	mcp{7.51} [Minecraft Coder Pack] (minecraft.jar) Unloaded
	FML{5.2.23.737} [Forge Mod Loader] (coremods) Unloaded
	Forge{7.8.1.737} [Minecraft Forge] (coremods) Unloaded
	AtomicScience{0.6.2} [Atomic Science] (Atomic_Science_v0.6.2.117.jar) Unloaded
	ExtrabiomesXL{3.13.4} [ExtrabiomesXL] (ExtrabiomesXL-universal-1.5.2-3.13.4.jar) Unloaded
	ICBM|Contraption{1.2.1} [ICBM|Contraption] (ICBM_Contraption_v1.2.1.172.jar) Unloaded
	ICBM|Explosion{1.2.1} [ICBM|Explosion] (ICBM_Explosion_v1.2.1.172.jar) Unloaded
	ICBM|Sentry{1.2.1} [ICBM|Sentry] (ICBM_Sentry_v1.2.1.172.jar) Unloaded
	ImmibisCore{55.1.6} [Immibis Core] (immibis-core-55.1.6.jar) Unloaded
	inventorytweaks{1.54b} [Inventory Tweaks] (InventoryTweaks-1.54b.jar) Unloaded
	Mekanism{5.5.6} [Mekanism] (Mekanism-v5.5.6.bugfix1.jar) Unloaded
	MekanismGenerators{5.5.6} [MekanismGenerators] (MekanismGenerators-v5.5.6.bugfix1.jar) Unloaded
	MekanismTools{5.5.6} [MekanismTools] (MekanismTools-v5.5.6.bugfix1.jar) Unloaded
	MFFS{3.1.0} [Modular Force Field System] (MFFS_v3.1.0.175.jar) Unloaded
	PowersuitAddons{0.2.3-144} [Andrew2448's Modular Powersuits Addon] (MPSA-0.2.3-144_MPS-531+.jar) Unloaded
	NEIPlugins{1.0.9.3} [NEI Plugins] (NEIPlugins-1.0.9.3.jar) Unloaded
	LWJGL: 2.9.0
	OpenGL: GeForce 9800 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Texture Pack: Default
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at net.minecraft.util.StringTranslate.func_74812_a(StringTranslate.java:88)
	at net.minecraft.util.StringTranslate.func_74810_a(StringTranslate.java:129)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:415)
	at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
	at net.minecraft.client.Minecraft.run(Minecraft.java:733)
	at java.lang.Thread.run(Thread.java:745)
--- END ERROR REPORT f6ff1cda ----------

**Comment by Masterspvpro** [comment]
someone please help :(

**Comment by Masterspvpro** [comment]
--- BEGIN ERROR REPORT be3bcae8 --------
Full report at:
C:\Users\Uliana\AppData\Roaming\.minecraft\crash-reports\crash-2017-07-27_14.15.50-client.txt
Please show that file to Mojang, NOT just this screen!

Generated 27/7/2017 2:15 μμ

-- System Details --
Details:
	Minecraft Version: 1.5.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 70347568 bytes (67 MB) / 185843712 bytes (177 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v7.51 FML v5.2.23.737 Minecraft Forge 7.8.1.737 3 mods loaded, 3 mods active
	mcp{7.51} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{5.2.23.737} [Forge Mod Loader] (coremods) Unloaded->Constructed->Pre-initialized
	Forge{7.8.1.737} [Minecraft Forge] (coremods) Unloaded->Constructed->Pre-initialized
	LWJGL: 2.9.0
	OpenGL: GeForce 9800 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Texture Pack: Default
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at net.minecraft.util.StringTranslate.func_74812_a(StringTranslate.java:88)
	at net.minecraft.util.StringTranslate.func_74810_a(StringTranslate.java:129)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:415)
	at net.minecraft.client.MinecraftAppletImpl.func_71384_a(SourceFile:56)
	at net.minecraft.client.Minecraft.run(Minecraft.java:733)
	at java.lang.Thread.run(Thread.java:745)
--- END ERROR REPORT dfcdb118 ----------

**Comment by Masterspvpro** [comment]
even without mods it crashes
:(

**Comment by Masterspvpro** [comment]
it only has forge :(

**Comment by marvin-roesch** [comment]
For basic support, please go to the Forge forums. I doubt you'll find much help there either, though: 1.5.2 is very old already and not officially supported anymore. You might want to consider updating :P

**Comment by Masterspvpro** [comment]
i did but they said they dont support 1.5.2

**Comment by Masterspvpro** [comment]
:(

**Comment by Masterspvpro** [comment]
and i can't update beacuse the mod that i want to play with is only 1.5.2 ;(

**Comment by Messen** [comment]
Try to downgrade your java version. 1.8 java and 1.5.2 Minecraft doesn't like each other.
