### ISSUE TITLE
Block.addRunningEffects hook for Entity.createRunningParticles

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#4246]
Would be similar in spirit and implementation to addLandingEffects.

**Comment by covers1624** [comment]
Heh, i started to write a pr for this recently, ill finish it up then. Thanks for the reminder :D

**Comment by asiekierka** [comment]
Thanks a lot! I'd find it very useful.

**Comment by covers1624** [comment]
K done, https://github.com/MinecraftForge/MinecraftForge/pull/4248

**Comment by covers1624** [comment]
This can be closed, my pr was merged.
