### ISSUE TITLE
Inconsistencies when sneak-right-clicking blocks with one hand empty

### ISSUE THREAD

**Issue by Virtuoel** [MinecraftForge/MinecraftForge#4254]
Inconsistencies occur when sneak-right-clicking a block that can be interacted with while one hand is empty: 
In Vanilla the block is never activated. 
In Forge the block is activated if the main hand is empty. The contents of the offhand are ignored. 
It is also activated if the offhand is empty and the main hand cannot perform its right-click action or does not have one.

**Comment by williewillus** [comment]
Can you name a specific setup to test this?

**Comment by Virtuoel** [comment]
Example:
Try to place a Torch on the top side of a Chest or Wooden Trapdoor while sneaking. The Block will still activate. In Vanilla nothing appears to happen.
One hand must be empty.

**Comment by JamiesWhiteShirt** [comment]
I can see there is some inconsistency that might be causing this.

In vanilla the condition for attempting the block interaction is `!player.isSneaking() || player.getHeldItemMainhand().isEmpty() && player.getHeldItemOffhand().isEmpty()`.

Forge's patch can be reduced to this: `!player.isSneaking() || stack.isEmpty()` where `stack` is the held item in the hand the client is trying to use (first main hand then off hand). It's a bit more complicated than that, but this is what you can reduce it to respecting sneaking and stack emptiness.

The notable part is that vanilla checks both hands for emptiness whereas forge only checks the selected hand for emptiness. This should actually be very simple to fix.

**Comment by JamiesWhiteShirt** [comment]
~~I tried applying a fix for the above, didn't seem to affect the issue at all, and actually made it _more_ inconsistent. It must be elsewere.~~

Nevermind, I'm an idiot, that resolves the issue. PR coming up.

**Comment by williewillus** [comment]
make sure all the cases in the PlayerInteractEvent test mod still work.
