### ISSUE TITLE
[1.12] NoSuchField/MethodError outside of development environment

### ISSUE THREAD

**Issue by Leo40Git** [MinecraftForge/MinecraftForge#4258]
Attempting to access Item.setUnlocalizedName causes a NoSuchMethodError, and attempting to access any field from CreativeTabs causes a NoSuchFieldError.
This might have something to do with building the JAR, as this only happens outside of a dev environment.
[Here](https://pastebin.com/4eVnXCyj) is an example crash report that was caused by the CreativeTabs error.
This is happening on version 14.21.1.2426, the latest 1.12 Forge as of this issue.

**Comment by LexManos** [comment]
No the place for basic tech support. And read the tutorials correctly.

**Comment by Leo40Git** [comment]
Oops, this was entirely my fault. Sorry!
