### ISSUE TITLE
Edit Forge code

### ISSUE THREAD

**Issue by SkymaxPlay** [MinecraftForge/MinecraftForge#4269]
Hello,
I have a question. How to edit source code of Forge? I can't find anywhere src of Forge.

**Comment by shadowfacts** [comment]
... It's in the repo you're posting on...

I can't even (or odd) comprehend how you got here without noticing the source code...

**Comment by williewillus** [comment]
If you're asking how to set up a forge proper workspace, there are videos on the repo's front page https://github.com/MinecraftForge/MinecraftForge

**Comment by mezz** [comment]
You can get more information by asking in the Forge Forums, the Github issue tracker is not for this kind of support.
http://www.minecraftforge.net/forum/forum/18-support-bug-reports/

**Comment by SkymaxPlay** [comment]
@shadowfacts No and No. I want Forge src + Minecraft src.

**Comment by williewillus** [comment]
It's right there if you set up your workspace properly. Use the forums

**Comment by SkymaxPlay** [comment]
@williewillus 
https://mcforge.readthedocs.io/en/latest/gettingstarted/#terminal-free-intellij-idea-configuration
I done all steps and still I dont have src Forge with Minecraft
gradle setupDecompWorkspace does not meet my requirements

**Comment by diesieben07** [comment]
> Use the forums

**Comment by marvin-roesch** [comment]
Assuming you actually intend to contribute to Forge, see [this guide](http://mcforge.readthedocs.io/en/latest/forgedev/). Otherwise (e.g. a normal dev environment) or if you have any further questions left, consult the forums like others have pointed out.
