### ISSUE TITLE
MouseInputEvent doesn't actually fire on mouse input, but rather once per tick

### ISSUE THREAD

**Issue by Pokechu22** [MinecraftForge/MinecraftForge#4270]
Perhaps I'm just blind, but it looks like `MouseInputEvent` is fired (via `FMLCommonHandler.fireMouseInput`) at the wrong time.

I'd expect it to be called when mouse input is processed (at the bottom of <ruby><rb>`Minecraft.runTickMouse`</rb><rp> (</rp><rt>func_184124_aB</rt><rp>)</rp></ruby> in the same way that `KeyInputEvent` is in <ruby><rb>`Minecraft.runTickKeyboard`</rb><rp> (</rp><rt>func_184118_az</rt><rp>)</rp></ruby>, but instead it's called during a part of <ruby><rb>`Minecraft.runTick`</rb><rp> (</rp><rt>func_71407_l</rt><rp>)</rp></ruby> that manages <ruby><rb>`joinPlayerCounter`</rb><rp> (</rp><rt>field_71457_ai</rt><rp>)</rp></ruby>, which seems to have nothing to deal with mouse input.

This doesn't affect `MouseEvent` (fired via `ForgeHooksClient.postMouseEvent`).  But it does affect things that listen to just `InputEvent`, or specifically listen to `MouseInputEvent`.

Looks like it was broken [in this (large) commit](https://github.com/minecraftforge/minecraftforge/commit/52e877bdd03d53848c824b7175906a8e76ed37c3#diff-0bd1d200e8528dffd6283858ac697a13L216), probably by a failed merge.

**Comment by Pokechu22** [comment]
Right, should have included this info but I forgot:

* MC version 1.12
* Forge build 2415, although the code in question still looks wrong on the latest patch.

**Comment by mezz** [comment]
In 1.7.10 and 1.8 it's fired at the end of the loop inside `while (Mouse.next())`
Checked 1.10, 1.11, and 1.12 and they're broken the same way as now.

I'll fix this for 1.12 but I'm not sure I should touch it for the other versions or not, I don't want to break stuff that's working now and not being actively developed.

**Comment by Pokechu22** [comment]
If they're no longer being updated/maintained, I wouldn't bother (this event wouldn't have worked for their entire lifetime, and modders shouldn't be developing for it anymore (right?) so re-adding it wouldn't be needed).  Though I don't know forge's normal policy on older MC versions.

**Comment by mezz** [comment]
Yeah. We're fine with backporting fixes, I just don't want to break older mods.
