### ISSUE TITLE
mcpmod.info file needs updating

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#4275]
The [mcpmod.info](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/resources/mcpmod.info) file hasn't been updated since 1.8.9.

As a result the modlist (and possibly some other places) still show MCP 9.19.

For regular mods, there are `${version}` and `${mcversion}` tags that can be used, perhaps something similar could be used to avoid needing to apply manual updates here?

**Comment by LexManos** [comment]
Honestly, the MCP versions means nothing. I should probably remove it entirely... Or just replace it with the MC version.
