### ISSUE TITLE
Error loading up 1.12.1 Forge

### ISSUE THREAD

**Issue by Jay9519** [MinecraftForge/MinecraftForge#4278]
Tried starting up a 1.12.1 forge server but got this error straight away and for some weird reason nothing is saving in the logs or even a crash report about it

Forge-1.12.1-14.22.0.2444-universal

https://www.dropbox.com/s/zr5ld7cegwdgaik/error.png?dl=0

**Comment by LexManos** [comment]
You're running the server wrong, use the forums for basic debugging

**Comment by DBotThePony** [comment]
1.12 starts, 1.12.1 doesn't start with `java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/IOUtils`

**Comment by Madsthunder** [comment]
I think that's an unrelated issue

**Comment by tomelfring** [comment]
That's related to https://github.com/MinecraftForge/MinecraftForge/commit/ee6805397f605c2c30297aa25badd38a59f68ce5#commitcomment-23555340
