### ISSUE TITLE
[Feature Request] Add CommandRegistryEvent and ClientCommandRegistryEvent

### ISSUE THREAD

**Issue by LatvianModder** [MinecraftForge/MinecraftForge#4280]
Since Forge is moving towards registering everything with events, this seems appropriate. Previous methods of registering would be @Depricated

**Comment by liach** [comment]
I don't think there is a registry for commands yet.

**Comment by ghost** [comment]
You should be asking for adding registry for the commands, since RegistryEvent.Register is generic and works out of the box with any registry, if there is such registry available (even custom registries added by mods) and there is no registry for commands yet.

**Comment by LatvianModder** [comment]
No, I'm only asking to replace registering server commands in some FML event and client commands in postInit, because commands dont have a ResourceLocation ID, and they have a diffetent registry logic in backend

**Comment by liach** [comment]
Oh. When do you plan to fire them, still?

**Comment by liach** [comment]
fyi bukkit has colon commands. will forge add that too?

**Comment by LexManos** [comment]
No, and dont bump with useless stuff.
If you want a register command event, you could PR it. We already essentially have them for the server commands.
Client commands can be registered at any time. As they persist beyond the integrated servers lifecycle.

**Comment by LatvianModder** [comment]
Yeah, I had forgotten about this issue, and added to my forge PR to-do list. And I know they can be registered any time, but imo it would be nicer if there was an event for it, just like there is an event for model registry, even if its blank
