### ISSUE TITLE
[1.12] Netty ByteBuf leaking

### ISSUE THREAD

**Issue by Xalcon** [MinecraftForge/MinecraftForge#4282]
While developing my mod, i noticed the following error in the dedicated server console when connecting for the first time (after a server reboot) to a dedicated server:
```
LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetectionLevel=advanced' or call ResourceLeakDetector.setLevel()
```

This error does not show up everytime, atleast not with the default settings. Its also not logged to the log file, it is only printed to STDERR.

I was able to replicate it with just forge by setting the leakDetection level to PARANOID:

* Install latest forge dedicated server (14.21.1.2443), DEV workspace works as well.
* Run forge with the following parameters `java -Dio.netty.leakDetection.level=PARANOID -jar forge-1.12-14.21.1.2443-universal.jar > stdout.txt 2> stderr.txt`
* Connect with a suitable MC client (I used14.21.1.2443 here as well)
* Check the stderr.txt file
> Subsequent logins will not produce said error (atleast not for me). Only after restarting the server, the error shows up again.

Here is an example of said stderr output: https://gist.github.com/Xalcon/3fceee18fee1e9a33a30db0ae0861e9a

This issue does not happen when connecting to a 1.11.2-13.20.1.2429 server.

**Comment by bs2609** [comment]
Possibly due to https://netty.io/wiki/new-and-noteworthy-in-4.1.html#wiki-h3-7?
