### ISSUE TITLE
[Yet another event request] Override Item.getItemUseAction

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4287]
So, there are already `LivingEntityUseItemEvent`s subclasses, which allow you to control usage of any items, that are not yours (yours too, but you can simply override methods obviosly).
But right now there is no way to override `EnumUseAction` returned from such items.

For example, i am making a super-duper-hardcore mod and i want to make dirt edible. For that i use `PlayerInteractEvent.RightClickItem` for setActiveHand, `LivingEntityUseItemEvent.Start` to set duration and `LivingEntityUseItemEvent.Finish` to reduce dirt count and get the advancement '~Death~Dirt Eater'. But for it to render correctly while eating(and also particles and sounds) i need to override getItemUseAction of `ItemBlock` somehow without replacing it with my own class, since, y'know, compatibility.
And of couse, this is super-duper-hardcore mod, you cannot just craft 1xDirt->1x[edible dirt item].
There could be other applications ofc, drinking, making random items behave like bows, disabling vanilla food/bows by setting `EnumAction.NONE` and so on.

So this event should have `(get/set)ItemUseAction` obviously and an `ItemStack`. Also, in all places where `getItemUseAction` is called there is an entity available, it is just not passed to the method, but to catch it in event context would be useful.

**Comment by williewillus** [comment]
can't you use the substitution/override system to replace vanilla dirt with your own?

**Comment by ghost** [comment]
>  i need to override getItemUseAction of ItemBlock somehow without replacing it with my own class, since, y'know, compatibility.

And dirt was a simple and stupid example, i've said about other applications.

Also:
Replacing held item without reequip animation is actually very hard, since it checks reference equality (btw that check is in Forge code) and even if you replace held stack AND the one in ItemRenderer (reflection/ATs), container network update still breaks it because when you use an item all slots get updated from the server and held item on client is replaced with identical one yet being a different Java object so `==` equality fails (network update does not care about stored copy in ItemRenderer) and animations starts again.

**Comment by williewillus** [comment]
No, that's not what I mean. You can override things in the registry such that the actual id minecraft:dirt points to *your* object

**Comment by ghost** [comment]
Yes i can, but for example other mod wants to replace dirt(or any other item i would have replaced) by their custom object - of course that rarely happens, but that approach reduces compatibility between mods.

**Comment by Alpvax** [comment]
This doesn't fix that compatibility issue though.
Mod A makes dirt throwable on right clicking air.
Mod B makes dirt edible.
Player right clicks... What should the result be? Replacing the entire item reduces ambiguity, the modder can add item text to say the dirt is throwable/edible, and it is guaranteed to match the action.

**Comment by ghost** [comment]
For that there is event priority and cancellation.
Unless specifically requested, mod B would not receive the event cancelled by mod A.

**Comment by Alpvax** [comment]
Yes, but why is that any better than the substitution system for this case?
