### ISSUE TITLE
[1.12.x] BiomeEvent.GetGrassColor/GetFoliageColor not fired for all biomes

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#4288]
`Biome#getGrassColorAtPos` and `Biome#getFoliageColorAtPos` fire the `BiomeEvent.GetGrassColor` and `BiomeEvent.GetFoliageColor` events respectively, but `BiomeSwamp` and `BiomeMesa` override these methods without firing the events.

Is this intended, or is it an oversight?

**Comment by Choonster** [comment]
This issue is still present.

**Comment by mezz** [comment]
Based on what I can see I think this is an oversight.
