### ISSUE TITLE
genIntellijRuns Broken With Directory Junction

### ISSUE THREAD

**Issue by gudenau** [MinecraftForge/MinecraftForge#4289]
Issue:
When running the gradle task "genIntellijRuns" after "setupDevWorkspace" the Minecraft client and server run configurations no longer appear in Intelij Idea.

How to reprodue:
Download MDK 1.12-14.21.1.2443
Extract in a folder in a directory junction
Open "build.gradle" as a project
Accept dialog
Run "setupDevWorkspace"
Run "genIntellijRuns"
Refresh all gradle projects

What happens:
The environment is setup, but there are no run configurations for Minecraft in Idea.

What should happen:
A Minecraft client and Minecraft Server run configuration should appear in Idea.

Software versions:
Windows 10 Pro x64
InteliJ Idea Ultimate 1017.2.1
MDK 1.12-14.21.1.2443
JDK 1.8.0-144
Minecraft 1.12

**Comment by Niko-sk2x** [comment]
I had similar issue when I had the project location going through a symlink. Seems like IDEA has some issues with that. Are you sure you didn't import the project from location that goes through one? (it's less likely to be an issue on windows).

And if it's not actual IDEA issue, it's more of an issue with ForgeGradle,

**Comment by gudenau** [comment]
I do think it's going through a hard link, I am using Windows 10 Pro. I'll try without when I can.

**Comment by Niko-sk2x** [comment]
Hard links shouldn't be an issue, but I doubt you actually can have a hard link to a directory. If the original and the linked one can be distinguished in any way - it's not real hard link.

**Comment by gudenau** [comment]
Oh, woops. Directory junction. Explorer acts like it's a normal folder.

**Comment by gudenau** [comment]
@Barteks2x Thanks for that, it works when not using the junction. Issue updated to reflect this.

**Comment by bs2609** [comment]
This should probably be a [ForgeGradle issue](https://github.com/MinecraftForge/ForgeGradle/issues).
