### ISSUE TITLE
Flaw in network code prevents client joining after modpack update (1.12 ver 2443).

### ISSUE THREAD

**Issue by CanisArtorus** [MinecraftForge/MinecraftForge#4290]
While you folks are looking at Netty being troublesome; here's a different part of the network code that got buggy.

[00:20:45] [Netty Client IO /ERROR]: NetworkDispatcher exception
java.lang.ClassCastException: net.minecraftforge.fml.common.network.handshake.FMLHandshakeMessage$HandshakeAck cannot be cast to net.minecraftforge.fml.common.network.handshake.FMLHandshakeMessage$RegistryData
    at net.minecraftforge.fml.common.network.handshake.FMLHandshakeClientState$4.accept(FMLHandshakeClientState.java:122) ~[FMLHandshakeClientState$4.class:?]

This cascades into worse issues when the modpack has removed some blocks since last successful join (by removing the mod "simpletubes" entirely).
[00:20:45] [Netty Client IO 2/ERROR]: HandshakeMessageHandler exception
java.lang.IllegalStateException: Could not determine owner for the override on simpletubes:block_pipe. Value: Block{null}
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:288) ~[ForgeRegistry.class:?]

The client is given the "illegalStateException" message as reason why the server cannot be joined and is now completely incapable of joining our server.

Oddly, only one of our five clients has had this issue.  We have been unable to determine how their system differs from other users without the problem.

p.s. complete stacktrace from log  https://pastebin.com/rvThZjmb  .

**Comment by Kris1432** [comment]
this is a serious problem that my server is now getting, almost every player can't join now.

**Comment by DeKleineKobini** [comment]
Got this same error, 1 out of the 2 players (me) can't join.

java.lang.IllegalStateException: Could not determine owner for the override on quark:hardened_clay_tiles. Value: Block{null}

While I could join until just now (could join today until some minutes ago), and I removed Quark a while ago (5 days).

**Comment by mezz** [comment]
It looks to me like this is the cause of the crash:
`IllegalStateException: Could not determine owner for the override on simpletubes:block_pipe.`
and then the network code tries to continue anyway and dies.
Try removing the `simpletubes` mod to see what happens.

**Comment by mezz** [comment]
Hmm this may be an issue with overrides and not the network.
The network code seems to try to continue even though there was a crash, so it eventually dies.
