### ISSUE TITLE
Support for use of Item/Block in annotation-based Config

### ISSUE THREAD

**Issue by octylFractal** [MinecraftForge/MinecraftForge#4292]
It seems like having configurable items or blocks for certain features is a somewhat common usage of configuration (WorldEdit has many configurable wands, Treecapitator allows defining tree blocks and leaves, etc.). However, `@Config` has no support for stating that the field is for a particular set of `ResourceLocations`, which means the mod has to do it themselves, somewhere. I think adding support for `Item`, `Block`, and maybe even `IForgeRegistryEntry` fields would be great for this type of configuration.

**Comment by thilokru** [comment]
This change is rather simple. You just need to add an ITypeAdapter in TypeAdapters to handle Items and Blocks, register them in the static block in ConfigManager and that should be it. (Except maybe for the array remap map).

**Comment by LexManos** [comment]
Registries arnt finalized at config load so this wouldn't return anything. You should use a list of resource locations and bake your list either on server start or the remap event.
