### ISSUE TITLE
Remove/fix the broken typing restriction in configuration entries

### ISSUE THREAD

**Issue by Gamebuster19901** [MinecraftForge/MinecraftForge#4294]
The inner classes in [GuiConfigEntries](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/client/config/GuiConfigEntries.java) disallow the typing of certain valid values. For example, if I have a field that accepts Doubles, I cannot set it to the values -Infinity, Infinity, or NaN by typing, even though they are valid Doubles.

This restriction was added to prevent the typing of invalid values, but it in fact has the opposite effect. Take for example this configuration:

https://gist.github.com/Gamebuster19901/b9725e162ec7c8a655367c059150576c

You can see that the config starts of with three values, ∞, -∞, and NaN

![2017-08-09_06 07 12](https://user-images.githubusercontent.com/7155747/29116562-2bb511fc-7cc9-11e7-959c-55eede5703d7.png)

now, what happens if I type a number into one of the fields?

![2017-08-09_06 09 37](https://user-images.githubusercontent.com/7155747/29116619-5bb15168-7cc9-11e7-804b-78b7ad45a5f9.png)

As you can see from the above image, it allows an invalid entry into the field. **If there is an invalid entry in the field, the config reverts to its default value when saved, so there is no point in restricting what characters can be typed in the field anyway.**

**Comment by Alpvax** [comment]
One approach could be to allow only i and n, and autocomplete them to Infinity and NaN, but that seems awkward (you would also have to remove the entire word if backspace or delete were typed).

**Comment by Gamebuster19901** [comment]
Not stale
