### ISSUE TITLE
RenderSpecificHandEvent#setCanceled does not work

### ISSUE THREAD

**Issue by hohserg** [MinecraftForge/MinecraftForge#4296]
This code should cancel the render of the model, it works, but the model is rendered:
`
//Scala
@SubscribeEvent
def onRenderItem(e:RenderSpecificHandEvent): Unit ={
 val item=e.getItemStack
 if(item.getItem.isInstanceOf[ItemCustomRender]) {
  println("test")//work, test
  e.setCanceled(true)
  println("test1",e.isCanceled)//work, test1,true
 }
}`

**Comment by hohserg** [comment]
If RenderSpecificHandEvent is not designed to remove the model, then how do I get an empty model for my item?

**Comment by williewillus** [comment]
I don't understand what the report is trying to say. Botania cancels RenderSpecificHandEvent and it works just fine in the latest stable 1.12 forge version - the hand disappears and is not rendered.

**Comment by AEnterprise** [comment]
with the `empty model for my item` bit i think he is trying to make his own item model empty/invisible?

if so probably something to be taken to the forums
