### ISSUE TITLE
[1.12] Minecraft freezes on world load 

### ISSUE THREAD

**Issue by Blargerist** [MinecraftForge/MinecraftForge#4297]
Freezes on 0% on the dirt screen, where it used to freeze for the network race issue of #4219. Does not happen every time I try to load a world, but is around a 1/3 chance.

Happens between 1.12-14.21.1.2423 and 1.12-14.21.1.2443. Earlier versions freeze for me at the same place, with the #4219 issue that was fixed in the first version that this issue happens on.

[Logs](https://gist.github.com/Blargerist/17d47b7d3c61a51292e018d4d6fac906) of a test with the base example mod workspace. Freeze happens at 16:45:19 or so.

**Comment by DietmarKrause** [comment]
perhaps related? https://github.com/AllTheMods/ATM-3/issues/79

**Comment by mezz** [comment]
14.21.1.2423 is this fix here: https://github.com/MinecraftForge/MinecraftForge/pull/4220
@diesieben07 do you know why this might be happening?

**Comment by diesieben07** [comment]
No, I do not know. The problem is that I never was able to reproduce this bug on my machine at all.

**Comment by bs2609** [comment]
Does this still occur with 14.22.0.2463 or later? Otherwise, it was probably fixed by #4304.

**Comment by Blargerist** [comment]
Spent about 15 minutes attempting to reproduce on 14.22.0.2463. Issue did not happen. Appears to have been fixed by #4304
