### ISSUE TITLE
add a LightningStrikeEvent

### ISSUE THREAD

**Issue by EnderiumSmith** [MinecraftForge/MinecraftForge#4299]
add an event that allows changing the location, changing the effectOnly boolean or canceling the strike.

this would allow mods to add functional lightning rods instead of spawning the strike or require huge horizontal nets as well as effects like the skeleton trap.

**Comment by KnightMiner** [comment]
Part of the reason a lot of mods spawn the strike themselves is because of the presence of other mods that can spawn lightning easily. You don't want just any lightning to work.

**Comment by EnderiumSmith** [comment]
its only a problem for making power. one might want lightning redirection instead. and not all mods spawn it themselves. 

a solution to the power problem could be mods spawning the lightning as effectOnly and doing the damage separately since the default damage is not great for a weapon.
