### ISSUE TITLE
A very small thing about the CapabiltyFluidHandler

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4306]
In the default fluid capability storage readFromNBT (found at fluids/capability/CapabilityFluidHandler), there is a check to see whether the instance passed implements IFluidTank, and then the instance is converted into a FluidTank which has the setCapacitymethod. The "I" shouldn't be there I think.
That's it. A letter too much.
It is critical .(no)

**Comment by mezz** [comment]
Thanks, fixed.
