### ISSUE TITLE
Fatally missing blocks and items

### ISSUE THREAD

**Issue by phit** [MinecraftForge/MinecraftForge#4307]
So this is a complex issue and I'm not sure how far this is supported by Forge, but this is regarding recipe behavior in 1.12+.

I did the following tests with custom recipes, for vanilla I just placed [this custom json file](http://vpaste.net/q56kc) in the vanilla server jar (assets\minecraft\recipes\bedrock.json). 
For Forge I made an empty test mod with this json file in the assets http://vpaste.net/1rn1P.

| Server  | Client | Result |
| ----- | ---- | --- |
| Vanilla + Recipe json | Forge | Recipe works, output shown to client |
| Vanilla + Recipe json | Vanilla | Recipe works, output shown to client |
| Forge + Testmod | Vanilla | Recipe works, output shown to client |
| Forge + Testmod | Forge | [Can't join server due to fatally missing blocks & items](http://vpaste.net/otQwh) |

As you can see only when both client and server are Forge there is an issue, I really hope this gets fixed I would rather not patch my Forge server to not send that kind of data, just to allow custom recipes on my server.

Forge version used for all the tests was 14.22.0.2453.

**Comment by mcenderdragon** [comment]
Has your mod the acceptedRemote versions tag in @Mod ?

**Comment by phit** [comment]
Yes, anyway this was addressed by Lex with https://github.com/MinecraftForge/MinecraftForge/commit/28e341002f7f338bb9cc490ef3a7270c7b9c99f6.
