### ISSUE TITLE
Custom world creation options (not world type customization)

### ISSUE THREAD

**Issue by Niko-sk2x** [MinecraftForge/MinecraftForge#4308]
I want to make a PR that makes it possible, but I'm not sure of the best way to implement it. This may need to be separated into 2 issues or PRs.

#### What I'm trying to do
In my mod I need to create a way for user to toggle an option when creating a world (specifically, whether it is a cubic chunks world or not in my case). It needs to be possible to change for all world types, and it is should be impossible to change for already existing world. And there needs to be a way to set it both from client and from and dedicated server. Since it seems like something other mods may try to do, I think 

Using Forge's GUI events, it's already possible to add a working button that does it, but it's not going to be compatible with any mod that attempts to do similar thing (mainly because vanilla GUIs are very limited). And, the main issue, there seems to be no reasonable way to pass that information from the GUI to appropriate world event. Options I considered:
 * static variable/through a global config option: There is no way to distinguish creating a new world from loading existing one which doesn't have that option set
 * Hacking the generator settings string - while it may work when one mod does it, it's not really possible to assume anything about the format of this string. Any changes to it may break some mod.
 * Extending `GuiCreateWorld` and reimplementing `actionPerformed` - while it would work, it's also incompatible with any mod that attempts to do something similar.

For server - I don't think there is any way to do it.

#### My ideas for PR
To make it possible to pass the data between the GUI and the world all I would need is an event in `GuiCreateWorld#actionPerformed` right after setting generator options string in `WorldSettings` (and for server `MinecraftServer#loadAllWorlds`), and some place to store the data in WorldSettings and WorldInfo (and a way to serialize it to NBT later).  This could be something like `Map<ResourceLocation, NBTTagCompound>` field. 
This could be used by mods either by adding something to world creation gui screen, or by using a mod config option. It could also never be actually serialized or sent to client, and mods would need to actually store it as WorldSavedData/capability, and using WorldSettings/WorldInfo only as a way to pass that data into the world when creating it.

Adding something to `GuiCreateWorld` has potential for compatibility issues, and changing mod options for something like that is very unntuitive for users.

So I think it may be a good idea to also add a way to add actual custom GUI options to world creation screen. Possibly something similar to existing forge config GUI, or per-mod version of something like customization screen GUI, with some "Mod options" button. But at this point it may grow into larger PR so I want to get some feedback before I go and write it.

**Comment by Alpvax** [comment]
I would prefer to make the more options page of the create world screen scrollable, and different mods could add their own buttons and fields to the bottom of it. It would put all advanced world options in one place, rather than clicking through several different pages of mod world generation options.

I am thinking of something similar to the controls list.

**Comment by Niko-sk2x** [comment]
That looks like a good idea. But this is for the GUI part. Any suggestions for passing that data into world? Capability on `WorldSettings` mentioned in #4309 seems like a good idea, but I'm not sure if capabilities really fit there.

**Comment by Alpvax** [comment]
Doesn't World already support capabilities? Could we not just save them to that somehow? Or pass saving them off to the mods themselves. Or even better just have a writeToNBT override for each button/field which is called by forge.

**Comment by Abastro** [comment]
World is not yet prepared on creating the gui.
I think WorldSettings is not appropriate position for caps as it's just for initializing the world.
Rather than that, I'd make WorldInfo a caps provider and put custom data hooks in WorldSettings, and create some events for the migration.

**Comment by Niko-sk2x** [comment]
Alpvax: World caps are enough to store it, even WorldSavedData is enough. But the problem is always getting that data there.
If you want to use static field, or any there currently possible way, you always run into the problem is distinguishing newly created world from already existing vanilla one, unless you add a fair bot of fragile code to reset it in the right moments.

**Comment by Alpvax** [comment]
So we would need to add a parameter into the World constructor which would pass the data from world creation into the world save data. I don't think we need caps.
Why do we need to distinguish between loading a new world with passed in values and an old one which reads them from NBT? If they are only settable on world creation I don't see the issue.

**Comment by Niko-sk2x** [comment]
Adding data to WorldSettings and WorldInfo, and adding an event when these are created for a new world would make it unnecessary to distiguish that. No need to change world contructor. It already takes WorldInfo.

**Comment by Blargerist** [comment]
If your mod makes cubic chunks possible, what case are you imagining where a user makes different worlds with/without cubic chunks? Why would they change their mind world to world instead of just disabling your mod or globally disabling cubic chunks in a config?

**Comment by Abastro** [comment]
In this case, yes, caps are not needed - Events are fine
I'm just considering the possibility with WorldInfo capabilities. It's rather needed for other purposes - global settings per save which is easily exposed. (This is for me)

**Comment by Alpvax** [comment]
So we could have a WorldCreation.Pre event, to add fields and buttons to the world creation screen (I would suggest being able to add a widget interface so it could be extended to add custom widgets e.g. sliders).
Then we could have a WorldCreation.Post event which could modify features of the world before generation, based on the values from the world selection screen.

For the widget field I am thinking a generic getValue() which could return an object in case more is needed than a primitive.

**Comment by Niko-sk2x** [comment]
@Blargerist I want to still allow at least loading vanilla worlds without breaking anything (or at the very least not breaking them). There is no way right now to distinguish loading existing vanilla world and creating new one.

**Comment by Alpvax** [comment]
The vanilla world would just not have any additional data saved. And wouldn't get any data as the world would only get data from the world creation so existing worlds would not be affected
