### ISSUE TITLE
How about Save Capabilities?

### ISSUE THREAD

**Issue by Abastro** [MinecraftForge/MinecraftForge#4309]
I suggested server capabilities a few months ago, and got suggestions to change it into Save Capabilities.
So would this still be useful for now?
Also how would this be implemented - what class will get 'implements ICapabilityProvider'?

I'd like to have it in the MinecraftServer. Would this be fine?

**Comment by LexManos** [comment]
Why? You can already save data in our handful of save events. The fact that you don't know what class would "get 'implements ICapabilityProvider'" shows you haven't thought this through.

What do you want to do? (XY Problem I think..)

**Comment by Abastro** [comment]
The problem is similar with world caps. I want the instance on the data creation.

I wanted caps for each of these two:
1. MinecraftServer (many things about the save can be accessed here via the overworld)
2. WorldSettings (or WorldInfo)

Yes I didn't put much thought when I posted this issue. Sorry about that.

On the XY problem, what I want to do is to store per-save information like information on global objects and global settings. I need to check the server for the settings.

**Comment by Abastro** [comment]
More justifications:
Let's assume that we have a world system which describes the types of dimensions and relations of the dimensions.
Let another mod referencing the world system to get information about it. It does this on world type evaluating the chunk generator, as it want to override it correctly.
Then additional access layer is necessary, as WorldSavedData needs the class.
Then you need static accessor - I see this already problematic as one needs either the misleading World instance or no params - But let's say it's not important.
You now need to evaluate the WorldSavedData.
But, the map storage is not yet prepared here, and the world can't be accessed yet.

Now putting more thoughts about this, this one can be problem even in one mod. When the type is specific to a mod, then the information should be given later. It could get easily hacky I guess.

I'm going to reopen the PR, as the difference ia apparent between WorldSavedData class and caps interface. - Also WorldSavedData version does not alloe implementation by other mods!

**Comment by Alpvax** [comment]
>Let's assume that we have a world system which describes the types of dimensions and relations of the dimensions.

Why does this need to be global? it is linked to each world, so why not store it per-world?

**Comment by Abastro** [comment]
@Alpvax That's not the point and that part could be omitted, but it can't be stored per-world when it determines existence of dimensions. Also something like 'dimension set' is vague to be stored in a specific world.

**Comment by Alpvax** [comment]
If it is to determine the existence of a dimension, why can that not be put in WorldSavedData? There is no reason for a mod to override whether or not the dimension exists that I can see.

I'm sorry, maybe it isn't a great example, but I'm struggling to see where this comes in useful. It sounds to me like "lets replace everything with capabilities because they're the new thing".

**Comment by Abastro** [comment]
@Alpvax, when the data describes both the existence of worlds and the world generation. WorldSavedData can't handle this case as I mentioned earlier.
You know that overriding world type is a thing, right?
And no, this capability has nothing like global WorldSavedData. This describes the property of the global world, while the WorldSavedData should contain the data. The relation with world type shows this well.
Currently, loading world specified by WorldType augmented with saved cfg settings needs additional hacks. (Not creating it but loading it)

**Comment by Alpvax** [comment]
>You know that overriding world type is a thing, right?

Yes, but if you have overridden the world type, it still exists, so why would you need to change that?


This is the part I don't think that I understand:
>This describes the property of the global world, while the WorldSavedData should contain the data.

What exactly are you trying to save to? What does the "global world" mean? Are you just referring to the world save?

What stops you using the WSD to store some stuff, then passing it off to the individual World capabilities for the specifics?
I'm sorry for all the questions, I can tell that I'm missing something, but I still don't understand the use case.

**Comment by Abastro** [comment]
When overriding and inheriting - these are not in its javacode meaning - the world type, you need to get the information about the type. When it's in WSD, it can't be queried in the appropriate time as the map data does not exist. If the override world type is highly dependent to the data, you can't inherit it.

And yeah, I mean the world save by global world.
Again, the criteria above gives the caxe WSD can't be used. Using World Capability for this purpose is just not right, you can't pretend Overworld to be the world save data storage.
The simplest use case would be using configuration settings to augment world type, where the settings are saved later. When re-loading the world, the chunkgenerator can't be set properly since the config data can't be retrieved from the world data at this point.

**Comment by Alpvax** [comment]
Is this similar to what #4308 aims to achieve? EDIT: Just realised you are part of that discussion

From what I understand, you want to attach arbitrary world (generation?) data to something that is accessible before the world is generated or loaded, and persisted across saves.

I'm still not convinced that capabilities are the way to go, as I'm not sure what data you would expose in an interface, but something similar would be useful.

**Comment by Abastro** [comment]
There is a bit of difference between this and #4308. One thing is that the additional save data can be evaluated from config. Also save capability is for exposing save-specific interface.
 Something like dungeon network composed of worlds, and planetary system could be here. I'm not sure about the Interface as well, but it could contain methods regarding the relation between worlds.
I'm going to come up with simpler example on this. (looped world?)

**Comment by Niko-sk2x** [comment]
I think there is no real difference between this and #4308, except of the other one also suggesting clientside GUI.

When using custom world type you are generally free to use generator settingss (json) string for anything. The problem is when you are adding stuff to existing world type (which is also my use case).

Generally, you *could* store the data in WorldSavedData of the overworld, but then as I said in #4308 there is no way to differentiate loading existing world without the data, and creating a new world. And this would probably be the only difference from using Overworld WSD.

In vanilla an example of data stored this way is the world generator settings string.
Clientside, you can change it from GUI, and once it's set - you can't change it in that world. On the server you set it in `server.properties` but once a world is created the value stored in world isn't going to change, no matter what. Probably even if you load an old world from before world customization existed.

Looped world is a good example here. You want it to be used only in new worlds, never added to an existing world. And you need to store a flag that specifies that this is a looped world, and you need to specify the size. This would probably be achieved by world type in a simple implementation, but it's probably possible to make it work with any world type. Then it's basically the same issue as I described in #4308.

If done in a way that allows adding the data only to new worlds, this would also allow mods that add custom biomes to not generate those custom biomes in existing worlds unless user requests it in config. This would allow users to add some new mods that add non-gameplay-essential biomes without adding giant chunk walls into the world.

**Comment by Alpvax** [comment]
@Abastro What do you mean by the relation between worlds?

>Generally, you could store the data in WorldSavedData of the overworld, but then as I said in #4308 there is no way to differentiate loading existing world without the data, and creating a new world. And this would probably be the only difference from using Overworld WSD.

@Barteks2x As I said in #4308, surely the way to differentiate would be that there is no additional saved data for an existing world, but there is no data at all for a new world.

Are we just looking for a place to attach arbitrary data to outside of any world instance?

**Comment by Niko-sk2x** [comment]
Even in the `AttachCapabilitiesEvent<World>`, some `WorldSavedData` will already be created in both cases because the event is fired at the end of `WorldServer#init`.

And relying on `capabilities` WSD not being there when creating the world looks like a very bad hack. And you can't really do many things earlier (are there even earlier World events?).

**Comment by Alpvax** [comment]
I'm not saying that it isn't a useful feature, my question is are capabilities the right way to go? Or do we just want raw data saved that can be accessed through ResourceLocation keys?

**Comment by Niko-sk2x** [comment]
I just want data, for my use case. But API for exposing an interface could probably also be useful.

**Comment by Abastro** [comment]
@Alpvax I mean teleportation capability/coordinates relationships, and other informations - like general property of dongeon in dongeon's case, system configuration in solar system case and such.
And capabilities are, afaik, for exposing the data, which is what I want in this case - interface matching lifecycle of WorldInfo.

**Comment by Alpvax** [comment]
So you are suggesting capabilities for WorldInfo in addition to Worlds?

**Comment by Abastro** [comment]
Yes.

**Comment by Alpvax** [comment]
Doesn't that seem over complicated? Surely just data storage would be fine for WorldInfo?

**Comment by Abastro** [comment]
It needs to be exposed for my use case - which is why capability system is needed. I can't think of any other extra data storage, as similar ones like IEEP and such are removed.
Imo capability system is not overcomplicated and fits in this case pretty well. I think it also matches with how WorldInfo works.

**Comment by Alpvax** [comment]
>I mean teleportation capability/coordinates relationships, and other informations - like general property of dongeon in dongeon's case, system configuration in solar system case and such.
And capabilities are, afaik, for exposing the data, which is what I want in this case - interface matching lifecycle of WorldInfo.

Why can these not be world capabilities, using data which could be stored in WorldInfo?
I think we have to be wary of having capabilities attached to both World and WorldInfo, when should you attach them to the world and when to the worldinfo?

**Comment by Abastro** [comment]
It's because of the same reason why mapStorage exists.
By assuming overworld capability as save capability, overworlds-specific capability becomes vague - it's hard to distinguish them. This issue gets more serious on client, as there's no guarantee of Overworld being loaded. On the other hand, WorldInfo is always loaded there. (Although it gets reloaded every time)
WorldInfo is for general information, like additional informatuon world types and global tick/weather management.

**Comment by Alpvax** [comment]
I have just realised that I've been making a huge mistake this whole time: I thought WorldInfo was specific to individual worlds, but it always delegates to the overworld WorldInfo (i.e. a global WorldInfo).

Adding capabilities might be the right way to go, but we should come up with some guidelines as to which caps are attached to worlds and which are attached to the global worldinfo.

**Comment by Abastro** [comment]
Yes it's only dependent on saves. I'm going to add additional remark, similar with world capabilities.

**Comment by Abastro** [comment]
So are there more problems?
Or was my rationale not sufficient?

**Comment by Abastro** [comment]
Does no reply mean No?

**Comment by JamiesWhiteShirt** [comment]
I think this would be nice to have. I have a mod with cross-dimensional relational data that would be less complex with this system in place.

**Comment by Cloudhunter** [comment]
No reply means simply that - no reply.

**Comment by Alpvax** [comment]
I didn't respond because I think we need some input from others (preferably the forge team). Or someone to make a PR.

**Comment by Abastro** [comment]
Yeah, I meant the response from the forge team.
Anyway, thanks.

**Comment by Abastro** [comment]
I think I can make combination class of WorldSettings and WorldInfo to fire AttachCapabilitiesEvent on, to make migration from WorldSettings to WorldInfo possible. Would it be worse?
