### ISSUE TITLE
In water detection bug in development environment

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4311]
You can float more than you should be able to in water. This happens in my 1.11.2 mdk and 1.12 mdk. I tried it without my mod and it still happens.

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=iQ3b0Ys6CW4

https://www.youtube.com/watch?v=K16gCSxl3f4

**Comment by LexManos** [comment]
Unable to reproduce, Most likely there is a issue with a dependency you have installed or something.

**Comment by ghost** [comment]
Ah you're right.
