### ISSUE TITLE
Game crashing on load (Rendering Screen)

### ISSUE THREAD

**Issue by TobiasDeBruijn** [MinecraftForge/MinecraftForge#4314]
My game crashes when I try to loadthe game, in the first seconds after I pressed "play" in the launcher it crashes.

Log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  OFMDepLoader (OpenFM-1.9.4-0.1.0.22.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.1.jar)
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.107 (1).jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.11.127-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 8/17/17 2:44 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: bxl
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224)
	at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
	at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: net.minecraftforge.fml.client.GuiModsMissing
	Mouse location: Scaled: (0, 383). Absolute: (0, 0)
	Screen size: Scaled: (512, 384). Absolute: (1024, 768). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 979666016 bytes (934 MB) / 1717567488 bytes (1638 MB) up to 6681526272 bytes (6372 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7168m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 97 mods loaded, 97 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316.jar) 
	U	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316.jar) 
	U	appliedenergistics2-core{rv4-stable-1} [Applied Energistics 2 Core] (minecraft.jar) 
	U	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	U	OpenComputers|Core{1.6.2.7} [OpenComputers (Core)] (minecraft.jar) 
	U	securitycraft{v1.8.2.3-hotfix} [SecurityCraft] ([1.10.2] SecurityCraft v1.8.2.3-hotfix.jar) 
	U	actuallyadditions{1.10.2-r105} [Actually Additions] (ActuallyAdditions-1.10.2-r105.jar) 
	U	ae2stuff{0.6.0.9} [AE2 Stuff] (ae2stuff-0.6.0.9-mc1.10.2.jar) 
	U	agricraft{2.0.0-0.10.0-a19} [AgriCraft] (agricraft-2.0.0-0.10.0-a19.jar) 
	U	flyringbaublemod{0.2.4_1.10.2-d71eb9e} [AngelRing 2 Bauble] (angelRingToBauble-1.10.2-0.2.4.19+d71eb9e.jar) 
	U	appliedenergistics2{rv4-stable-1} [Applied Energistics 2] (appliedenergistics2-rv4-stable-1.jar) 
	U	avaritia{${mod_version}} [Avaritia] (Avaritia-1.10.2-2.2.7-universal.jar) 
	U	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	U	bdlib{1.12.4.24} [BD Lib] (bdlib-1.12.4.24-mc1.10.2.jar) 
	U	brandonscore{2.1.11} [Brandon's Core] (BrandonsCore-1.10.2-2.1.11.127-universal.jar) 
	U	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	U	chisel{MC1.10.2-0.0.10.22} [Chisel] (Chisel-MC1.10.2-0.0.10.22.jar) 
	U	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	U	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	U	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	U	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	U	colossalchests{1.6.0} [Colossal Chests] (ColossalChests-1.10.2-1.6.0.jar) 
	U	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.26.jar) 
	U	MineTweaker3{3.0.26} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.26.jar) 
	U	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.26.jar) 
	U	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.5.jar) 
	U	cyclopscore{0.10.7} [Cyclops Core] (CyclopsCore-1.9.4-0.10.7.jar) 
	U	darkutils{1.1.8.finalrc2} [Dark Utilities] (DarkUtilities-1.1.8.finalrc2.jar) 
	U	draconicevolution{2.1.5} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.1.5.262-universal.jar) 
	U	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	U	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	U	EnderIO{1.10.2-3.1.193} [Ender IO] (EnderIO-1.10.2-3.1.193.jar) 
	U	extraplanets{0.6.2} [Extra Planets] (ExtraPlanets-0.6.2.jar) 
	U	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.5.2.jar) 
	U	bigreactors{1.10.2-0.4.5.30} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.30.jar) 
	U	FlatBedrockx{1.2.1} [FlatBedrock Xplosion's Edition] (FlatBedrock-1.2.1_1.9.4.jar) 
	U	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	U	fluxnetworks{1.2.5} [FluxNetworks] (FluxNetworks-1.10.2-1.2.5.jar) 
	U	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
	U	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.5.jar) 
	U	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.0.107 (1).jar) 
	U	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.107 (1).jar) 
	U	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13.jar) 
	U	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	U	infinitylib{1.10.2-0.11.0} [InfinityLib] (infinitylib-0.11.0.jar) 
	U	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	U	ironbackpacks{1.10.2-2.2.31} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.31.jar) 
	U	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	U	journeymap{1.10.2-5.4.7} [JourneyMap] (journeymap-1.10.2-5.4.7.jar) 
	U	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	U	jet{2.1.39} [JustEnoughTooltips] (JustEnoughTooltips-1.10.2-2.1.39.jar) 
	U	malisiscore{1.10.2-4.4.0} [MalisisCore] (malisiscore-1.10.2-4.4.0.jar) 
	U	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
	U	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	U	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	U	minefactoryreloaded{2.9.0B1} [MineFactory Reloaded] (MineFactoryReloaded-[1.10.2]2.9.0B1-226.jar) 
	U	MineFactoryReloaded|CompatVanilla{2.9.0B1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.10.2]2.9.0B1-226.jar) 
	U	moartinkers{0.4.1} [Moar Tinkers] (moartinkers-0.4.1.jar) 
	U	mob_grinding_utils{0.1.8.22} [mob_grinding_utils] (MobGrindingUtils-0.1.8.22.jar) 
	U	moofluids{1.10.2-1.7.02.12b} [Moo Fluids] (MooFluids-1.10.2-1.7.02.12b.jar) 
	U	moreavaritia{1.02} [More Avaritia] (moreavaritia-mc1.10.2-v1.02.jar) 
	U	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	U	mysticalcrops{2.0} [Mystical Crops] (Mystical Crops-1.8.8.jar) 
	U	mysticalagriculture{1.5.8} [Mystical Agriculture] (mysticalagriculture[1.10.2]-1.5.8.jar) 
	U	nethercore{1.10.2-2.0.3} [Nether Core] (nethercore-1.10.2-2.0.3.jar) 
	U	omlib{3.0.0-126} [OMLib] (omlib-1.10.2-3.0.0-126.jar) 
	U	OpenComputers{1.6.2.7} [OpenComputers] (OpenComputers-MC1.10.2-1.6.2.7.jar) 
	U	openfm{0.1.0.22} [OpenFM] (OpenFM-1.9.4-0.1.0.22.jar) 
	U	openmodularturrets{3.0.0-210} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-210.jar) 
	U	openprinter{0.1.0.5} [OpenPrinter] (OpenPrinter-1.9.4-0.1.0.5.jar) 
	U	p455w0rdslib{1.0.13} [p455w0rd's Library] (p455w0rdslib-1.10.2-1.0.13.jar) 
	U	ProjectE{1.10.2-PE1.3.1} [ProjectE] (ProjectE-1.10.2-PE1.3.1.jar) 
	U	railcraft{10.1.2} [Railcraft] (Railcraft_1.10.2-10.1.2.jar) 
	U	randomthings{3.7.7.1} [Random Things] (RandomThings-MC1.10.2-3.7.7.1.jar) 
	U	refinedstorage{1.2.26} [Refined Storage] (refinedstorage-1.2.26.jar) 
	U	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	U	rftools{6.13} [RFTools] (rftools-1.1x-6.13.jar) 
	U	rftoolsdim{5.04} [RFTools Dimensions] (rftoolsdim-1.1x-5.04.jar) 
	U	simplegenerators{1.10.2-0.10.6a} [Simple Generators] (simplegenerators-1.10.2-0.10.6a.jar) 
	U	sonarcore{3.2.8} [SonarCore] (SonarCore-1.10.2-3.2.8.jar) 
	U	stevescarts{2.2.0.86} [Steve's Carts 2] (StevesCarts-1.10.2-2.2.0.86.jar) 
	U	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10.jar) 
	U	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	U	TinkersAddons{1.0.6} [Tinkers' Addons] (Tinkers' Addons-1.10.2-1.0.6.jar) 
	U	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	U	Translocator{2.1.4.55} [Translocator] (Translocators-1.10.2-2.1.4.55-universal.jar) 
	U	valkyrielib{1.10.2-0.10.6} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.6.jar) 
	U	VeinMiner{0.38.1_1.9-5587fc8} [Vein Miner] (VeinMiner-1.9-0.38.1.618+5587fc8.jar) 
	U	VeinMinerModSupport{0.38.1_1.9-5587fc8} [Mod Support] (VeinMiner-1.9-0.38.1.618+5587fc8.jar) 
	U	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	U	wailaplugins{MC1.10.2-0.3.0-26} [WAILA Plugins] (WAILAPlugins-MC1.10.2-0.3.0-26.jar) 
	U	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	U	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	U	wct{0.1.32} [Wireless Crafting Terminal 2] (WirelessCraftingTerminal-1.10.2-0.1.32.jar) 
	U	Woot{1.10.2-1.4.1} [Woot] (woot-1.10.2-1.4.1.jar) 
	U	zerocore{1.10.2-0.1.0.6} [Zero CORE] (zerocore-1.10.2-0.1.0.6.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
OFMDepLoader (OpenFM-1.9.4-0.1.0.22.jar)
  
LoadingPlugin (RandomThings-MC1.10.2-3.7.7.1.jar)
  lumien.randomthings.asm.ClassTransformer
MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.107 (1).jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  team.chisel.common.asm.ChiselTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  appeng.coremod.transformer.IntegrationTransformer
Brandon's Core (BrandonsCore-1.10.2-2.1.11.127-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4062' Renderer: 'Intel(R) HD Graphics 5500'
	Launched Version: forge-12.18.3.2316
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 5500 GL version 4.3.0 - Build 10.18.14.4062, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz

**Comment by diesieben07** [comment]
Use the forums for tech-support.

**Comment by TobiasDeBruijn** [comment]
Ok, Thanks :D

**Comment by Niko-sk2x** [comment]
Also this is very likely a missing galcticraft dependency.
