### ISSUE TITLE
1.11.2-forge1.11.2-13.20.1.2454 wont allow me to create worlds and load them, help?

### ISSUE THREAD

**Issue by DJPhilGaming** [MinecraftForge/MinecraftForge#4318]
I recently installed this version of forge and another with the mods I wanted and both versions won't allow me to create and load into the world. when loading the world the game freezes and won't let me close it, I tried updating java and tried adding more and more ram.

**Comment by DJPhilGaming** [comment]
These are the mods I'm using
![screenshot_2](https://user-images.githubusercontent.com/31137679/29480575-33ee039c-8471-11e7-856c-baa77598b318.png)

**Comment by LexManos** [comment]
Use the forums
