### ISSUE TITLE
TileEntity Registery

### ISSUE THREAD

**Issue by Came1ot** [MinecraftForge/MinecraftForge#4321]
I want to get tile entity class by id or name etc.
New version of for not let me to do it.
```
// this works only for classes, but has for resource locations
 String s = tag.getString("id");
Class <? extends TileEntity> tileClass =  TileEntity.getKey(new ResourceLocation(s));

// not working at all
GameRegistry.findRegistry(TileEntity.class);
```

**Comment by covers1624** [comment]
TileEntities are not in a forge controlled registry and there is no reason they should be imo.

**Comment by Came1ot** [comment]
I want to get tile entity class by it name (string)

**Comment by liach** [comment]
Tile entity class has a static name to class mapping, however.

**Comment by Came1ot** [comment]
@liach, But it has private access, and there is one method
` public static ResourceLocation getKey(Class <? extends TileEntity > p_190559_0_)`
That returns name by class, not class by name

**Comment by covers1624** [comment]
This is general modder help, move it to the forums. There should be no reason you need to manually get the class of a tile. However, you can AT the field or use reflection if you REALLY need it.
