### ISSUE TITLE
[1.12.x] FieldWrapper.MapWrapper doesn't add new properties to the Map

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#4325]
`FieldWrapper.MapWrapper#handlesKey` never returns `true` because it asks if the `name` argument starts with the `category` field followed by the `name` argument itself, which is impossible.  `name` will only ever be the simple name of a property, it will never be a fully-qualified name starting with a category.

This means that properties added to the `Map` field's category in the config file won't be added to the `Map` when `ConfigManager.sync` is called.

**Comment by Choonster** [comment]
I'm not sure how to fix this as I'm not sure what the original intention of this check was.

Should `IFieldWrapper#handlesKey` be called with a fully-qualified name instead of a simple name?

Should `FieldWrapper.MapWrapper#handlesKey` return `true` regardless of the `name` argument?

**Comment by Choonster** [comment]
This issue is still present. I still don't know what the original intention was.

**Comment by mezz** [comment]
Sorry I don't know either. You can look here for the implementation discussion, or ask the implementer:
https://github.com/MinecraftForge/MinecraftForge/pull/3735

**Comment by Choonster** [comment]
@thilokru This appears to be an issue with your code, could you please look into it?

**Comment by thilokru** [comment]
@Choonster Yes, my bad. It seems to be a simple fix. It is just missing a this. The FieldWrapper class has a field called "name" (containing the wrapped fields name), which collides with the method argument. Either add a this or change the method argument name. Sadly, I currently have no time to make a PR, but feel free to do so.

**Comment by Choonster** [comment]
From what I can see, neither the `name` field nor the `name` argument are fully-qualified property names; so I'm not sure how either of them can start with the category name like this code checks for.

**Comment by thilokru** [comment]
You are correct, it seems like I assumed the method parameter name was a fully qualified property name. You can see that if you check how the other methods are called. However, my parameter naming and method calls are poorly documented and inconsistent (i.e. parameters named "name" some times contain the last section of the fully quallified name, and other times the fully quallified name), thus they should be reworked, renamed and documented (especially in the interface IFieldWrapper).

**Comment by thilokru** [comment]
I've started work on a PR to fix this and properly document the code.
