### ISSUE TITLE
MC = 1.12.1, Forge = Latest, Critical code = Biome get name

### ISSUE THREAD

**Issue by Came1ot** [MinecraftForge/MinecraftForge#4327]
package net.minecraft.world.biome;
 
```
@SideOnly(Side.CLIENT)
public final String getBiomeName() {
     return this.biomeName;
}
```

Why it CLIENT side only? It needs for me on the server to determine biome name.

**Comment by TehNut** [comment]
Because Minecraft only ships it in the client jar. Only the client needs to know the name.

**Comment by ghost** [comment]
I need to know biome names during world generation on the server.

**Comment by diesieben07** [comment]
Then access the field directly using reflection or an access transformer.

**Comment by AEnterprise** [comment]
you could also just use their resourcelocations to identify the biomes
