### ISSUE TITLE
[1.12.1 Latest] Minecraft mc.hypixel.net timeout

### ISSUE THREAD

**Issue by Extamov** [MinecraftForge/MinecraftForge#4333]
I cant login to hypixel with forge(14.22.0.2460), i can login to hypixel with 1.12 forge.
When i want to login to hypixel, i have to use 1.12 forge(With liteloader and a couple of mods).
Cant use 1.12.1 forge, even without mods and liteloader.
When i try to login, it just says Logging in... for a long time and then Timed out.
Even without mods and deleting .minecraft and trying again to install forge, hypixel just says timeout.
I can login to almost(if not) any other server with 1.12.1 forge.
Why?

From launcher_log.txt: [Pastebin link](https://pastebin.com/JgbW6c7R)

![image](https://user-images.githubusercontent.com/26222159/29564710-a483ac06-874b-11e7-942d-334fdd621ae9.png)

![image](https://user-images.githubusercontent.com/26222159/29564793-ed8a0530-874b-11e7-8d4c-82ad408930d2.png)

**Comment by marvin-roesch** [comment]
Use Hypixel's [support system](https://support.hypixel.net/) or their [forums](https://hypixel.net/forums/), this issue is most certainly on their end.

**Comment by Extamov** [comment]
Posted a thread in hypixel forums
