### ISSUE TITLE
1.12: Cannot send data to client before connection rejected bc of missing registry entries.

### ISSUE THREAD

**Issue by PG85** [MinecraftForge/MinecraftForge#4338]
Hey there, I'm the dev for OpenTerrainGenerator, I'm working on updating to 1.12. I'll try to keep this short: 

With OTG biomes can be created and customised by users, this means that every world can have any number of biomes with different names and settings. As a consequence biomes aren't known at app start but are loaded and registered when a world/dimension is created (and unregistered when the world/dimension is unloaded). This also means that when a client connects to the server the server sends the biome data to the client, which registers the biomes and then loads the world. For previous versions of Forge it was possible to use FMLNetworkEvent.ServerConnectionFromClientEvent to send the biome data to the client before the player joined the world. However, with 1.12 the connection is rejected when Forge detects that biomes are missing from the registry, resulting in a "Connection lost, Fatally missing blocks and items." error screen. This appears to happen before any events are fired that I can hook into (such as FMLNetworkEvent.ServerConnectionFromClientEvent) so I don't see any way to send the biome data to the client before Forge rejects the connection.

Is there an event I can use to send the biome data before Forge rejects the connection or could such an event be added? Thanks!

**Comment by tterrag1098** [comment]
This is still relevant. @PG85 do you have any proposed solutions?

**Comment by PG85** [comment]
Hey @tterrag1098 , thanks for the update. I've worked around this with a core-mod atm, which modifies the registry check at net.minecraftforge.registries.GameData.injectSnapshot to exclude any missing OTG biomes. See:

Code injection: https://github.com/PG85/OpenTerrainGenerator/blob/1.12-OTG+-V8/platforms/forge/src/main/java/com/pg85/otg/forge/asm/excluded/OTGClassTransformer.java#L299

Injected code: https://github.com/PG85/OpenTerrainGenerator/blob/1.12-OTG%2B-V8/platforms/forge/src/main/java/com/pg85/otg/forge/asm/OTGHooks.java#L177

So basically I'm just white-listing all OTG biomes to get past the missing biomes check, then registering the biomes via a packet sent on FMLNetworkEvent.ServerConnectionFromClientEvent, which the client waits for and processes before joining the world.

I assume OTG is the only mod adding and removing biomes during runtime, instead of only adding biomes once at app start, so I wonder if it's worth your time to implement a fix just for OTG, would be nice ofcourse! Adding/removing biomes during runtime also causes other problems atm, such as other mods indexing all biomes at app start and either caching them indefinitely or only adding their resources/hooks at that point. They never update their biomes cache or don't detect new biomes being added during runtime, so they never add their resources / attach their hooks to those biomes. So ideally, if you'd like to support this, we'd also need at least one event for when a new biome is added. Ofcourse good luck getting mods to implement that if only OTG relies on it :/.

I've always assumed that since this behaviour is specific to OTG, I'd have to fix it on the OTG side. We have an idea for a new OTG feature that would allow you to toggle between two modes:
- Dynamic: Can create/edit/delete and switch between OTG worlds/presets/dimensions during MC session, biomes not registered at app start.
- Static: Select a single OTG preset to be used for the MC session, register the biomes at app start. No switching between presets during session, can only delete and re-create pre-defined dimensions during session.

The idea is that users can create their setup (OTG preset/dimensions) via Dynamic mode, then when they're done tinkering, switch to static mode to play. Ideally only OTG content creators would need to use Dynamic mode, and normal users would use Static mode.

**Comment by DaemonUmbra** [comment]
Is this still relevant in 1.14.x and/or 1.15x?

**Comment by PG85** [comment]
I'm about to start updating to 1.13/1.14/1.15, will let you know asap. Thanks!

**Comment by DaemonUmbra** [comment]
Closing this issue as it appears to be centered on a Forge version that is no longer supported.

If this issue still exists in a supported version, please create a new issue prefixed with the applicable supported branch (``[1.14.x]`` or ``[1.15.x]`` as of this writing) using the applicable template.

Note that an ongoing effort to update legacy MinecraftForge branches to utilize FG_3.0 is ongoing and accepting informed contributions. (For more information [join the Discord](https://discord.gg/UvedJ9m) and  read through the #mcpconfig channel)
