### ISSUE TITLE
Smooth lighting issue with some blocks at 0 light level

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#4342]
Ran into this issue while working on #4339.

![2017-08-24_225220](https://user-images.githubusercontent.com/1447117/29691477-0c601354-8923-11e7-95ab-76a4fad2b391.png)

As can be seen from the screenshot, the lighting on the stair blocks in the middle of the tunnel is incorrect.
The affected blocks are those with skylight 0.

The issue appears to be to do with `BlockInfo.combine`:
```java
    private float combine(int c, int s1, int s2, int s3)
    {
        if(c == 0) c = Math.max(0, Math.max(s1, s2) - 1);
        if(s1 == 0) s1 = Math.max(0, c - 1);
        if(s2 == 0) s2 = Math.max(0, c - 1);
        if(s3 == 0) s3 = Math.max(0, Math.max(s1, s2) - 1);
        return (float)(c + s1 + s2 + s3) * 0x20 / (4 * 0xFFFF);
    }
```
I was able to fix that issue by passing the boolean flag t(x/y/z) through to the function like so:
```java
    private float combine(int c, int s1, int s2, int s3, boolean t)
    {
        if (c == 0 && !t) c = Math.max(0, Math.max(s1, s2) - 1);
        if (s1 == 0) s1 = Math.max(0, c - 1);
        if (s2 == 0) s2 = Math.max(0, c - 1);
        if (s3 == 0) s3 = Math.max(0, Math.max(s1, s2) - 1);
        return (float) (c + s1 + s2 + s3) * 0x20 / (4 * 0xFFFF);
    }
```
Result:
![2017-08-24_225442](https://user-images.githubusercontent.com/1447117/29691676-f7d8b26e-8923-11e7-9ba4-a3638d8f3532.png)

However as this leads to other visible changes, I'm posting this as an issue, not a PR - it needs examining by someone who has a better idea of what the 'correct' behaviour is to ensure there's no regressions.

Other screenshots for comparison:

* Before:
![2017-08-24_230021](https://user-images.githubusercontent.com/1447117/29691768-7024945e-8924-11e7-85e5-63bb5501f0aa.png)
![2017-08-24_231411](https://user-images.githubusercontent.com/1447117/29691772-781717e0-8924-11e7-9942-d373e251db95.png)

* After:
![2017-08-24_225933](https://user-images.githubusercontent.com/1447117/29691781-820f7634-8924-11e7-942d-712e3b1edd2d.png)
![2017-08-24_231108](https://user-images.githubusercontent.com/1447117/29691790-89a48240-8924-11e7-9018-95aa42096aec.png)

**Comment by williewillus** [comment]
What does the vanilla pipeline look like?

**Comment by bs2609** [comment]
* Vanilla:
![2017-08-25_001811](https://user-images.githubusercontent.com/1447117/29693174-1b200724-892c-11e7-87c3-33038d5110bd.png)
![2017-08-25_002040](https://user-images.githubusercontent.com/1447117/29693187-25a9093e-892c-11e7-8a66-6a3a25aee0bc.png)
![2017-08-25_002514](https://user-images.githubusercontent.com/1447117/29693189-2b14cf34-892c-11e7-9e97-78e88001ac58.png)

* Forge (patched):
![2017-08-25_001928](https://user-images.githubusercontent.com/1447117/29693206-3f08092a-892c-11e7-884a-8a28bb39998d.png)
![2017-08-25_002246](https://user-images.githubusercontent.com/1447117/29693210-42b73f14-892c-11e7-87d3-546d39caf04f.png)
![2017-08-25_002609](https://user-images.githubusercontent.com/1447117/29693214-451e2b14-892c-11e7-9caf-c21f21aa42ac.png)

**Comment by bs2609** [comment]
Slightly better attempt code-wise, passing separate translucency flags for each direction:

```java
    private float combine(int c, int s1, int s2, int s3, boolean t1, boolean t2)
    {
        if (c  == 0) c  = Math.max(0, Math.max(t1 ? s1 : 0, t2 ? s2 : 0) - 1);
        if (s1 == 0) s1 = Math.max(0, c - 1);
        if (s2 == 0) s2 = Math.max(0, c - 1);
        if (s3 == 0) s3 = Math.max(0, Math.max(t1 ? s1 : 0, t2 ? s2 : 0) - 1);

        return (float) (c + s1 + s2 + s3) * 0x20 / (4 * 0xFFFF);
    }
```

**Comment by bs2609** [comment]
Minecraft pls :<

* Vanilla:
![2017-08-27_190754](https://user-images.githubusercontent.com/1447117/29752715-323a29ae-8b5b-11e7-9ff3-0ba2e983509c.png)

* Forge (original):
![2017-08-27_190723](https://user-images.githubusercontent.com/1447117/29752722-3aab2f20-8b5b-11e7-9001-abfce84d831d.png)

* Forge (modified):
![2017-08-27_190438](https://user-images.githubusercontent.com/1447117/29752736-62dbf0d8-8b5b-11e7-8b6b-026199f19561.png)

**Comment by bs2609** [comment]
Did a bit more testing, and the first fix still seems to be the best, though I wish I understood the code a little better.
