### ISSUE TITLE
ChunkGeneratorFlat doesn't ask for modded world generators

### ISSUE THREAD

**Issue by CalmBit** [MinecraftForge/MinecraftForge#4345]
While attempting to do some stupid stuff relating to villages, I noticed that no matter what I tried I couldn't seem to get villages to disappear from flat worlds. Tway I was attempting to 'remove' villages was by overriding their generation with an empty generator, hooking into `InitMapGenEvent`:

```java
@SubscribeEvent
public void nukeVillages(InitMapGenEvent event) {
    if(event.getType() == InitMapGenEvent.EventType.VILLAGE) {
        event.setNewGen(new EmptyGen());
    }
}
```

The containing class is then initialized and registered on `TERRAIN_GEN_BUS`.

Upon looking up the chain, I noticed that `ChunkGeneratorOverworld` seems to ask for modded world generators:

```java
villageGenerator = (MapGenVillage)net.minecraftforge.event.terraingen.TerrainGen.getModdedMapGen(villageGenerator, net.minecraftforge.event.terraingen.InitMapGenEvent.EventType.VILLAGE);
```

However, `ChunkGeneratorFlat` does not, opting instead to use the plain `MapGenVillage` class:

```java
if (map.containsKey("village"))
{
    Map<String, String> map1 = (Map)map.get("village");

    if (!map1.containsKey("size"))
    {
        map1.put("size", "1");
    }
    this.structureGenerators.put("Village", new MapGenVillage(map1));
}
```

This might be intentional given the fact that `ChunkGeneratorFlat` allows for specified village sizes, but I'm curious whether or not this is explicitly by design or possibly just an oversight.

**Comment by LexManos** [comment]
Last I recall its intended. You can custommize flat worlds all you want through settings and other things.
