### ISSUE TITLE
Forge 1.7.10 1614 entity teleport bug

### ISSUE THREAD

**Issue by RhythmNz** [MinecraftForge/MinecraftForge#4348]
Use any entity in any module that can deliver entity entities with containers when the entity pods / boxes are delivered around the world
Entities with containers will be delivered to another world, including items inside
But at the same time the original location will drop the items already in the entity
So you can easily and easily have double items

Any mods  Any can store item entity

I use KCauldron 1614

**Comment by Daomephsta** [comment]
You're using KCauldron, report the issue to them, not to Forge.

**Comment by RhythmNz** [comment]
I tested on singleplay 
still have this bug

**Comment by covers1624** [comment]
This sounds like a mod specific bug, and is likely not forge. In any case forge is targeting 1.12 now, and i'm fairly sure 1.7 isn't supported anymore.
