### ISSUE TITLE
netty FMLHandshakeMessage game freeze when entering world in 1.12

### ISSUE THREAD

**Issue by EnderiumSmith** [MinecraftForge/MinecraftForge#4353]
https://pastebin.com/mQr5pkut
about half the times when i open a world on 1.12 the game will freeze with this error and i have to restart it.
its way too annoying to play on 1.12 with more then a few mods if this error makes me have to start the game multiple times.

**Comment by bs2609** [comment]
See #4285.

**Comment by NarigudoBR** [comment]
use version 2459! 2462 gives me this error too!

**Comment by bs2609** [comment]
This should hopefully be fixed (by #4304), please try build 2463.
