### ISSUE TITLE
Custom Particle texture is shared between all particles, and over mods.

### ISSUE THREAD

**Issue by Wyn-Price** [MinecraftForge/MinecraftForge#4357]
So while developing my mod i came into this issue in that the i couldnt summon more than 1 custom particle without all the custom particles i had summoned otherwise also changing texture. And Sure enough i loaded up another mod and the particles changed. Maybe Im doing this wrong but it does seem to be an issue.

[Video here](https://drive.google.com/file/d/0B38KQkz251dQSERLQWNrSTdXMWs/view?usp=sharing)

**Comment by Wyn-Price** [comment]
this is the code i have in my ClientProxy
`@Override
    public void spawnParticle(EnumHarshenParticle type, Vec3d position, Vec3d directionSpeed, float scale, boolean disableMoving, Object...info) {
    	Minecraft minecraft = Minecraft.getMinecraft();
        Particle entityFx = null;
        if(minecraft.world !=  null)
	        switch (type)
	        {
		        case BLOOD:
		            entityFx = new ParticleBlood(minecraft.world, position.x, position.y, position.z, directionSpeed.x, directionSpeed.y, directionSpeed.z, scale, disableMoving);
		            break;
		        case CAULDRON:
		        	if(info[0] instanceof ResourceLocation)
		        		entityFx = new ParticleCauldron(minecraft.world, (ResourceLocation) info[0], position.x, position.y, position.z, directionSpeed.x, directionSpeed.y, directionSpeed.z, scale / 5f, disableMoving);
		        	break;
		        default:
		            break;
	        }
        if (entityFx != null) {minecraft.effectRenderer.addEffect(entityFx);}
    }`

**Comment by Wyn-Price** [comment]
This is the code i have in my Client Proxy
` @Override
   public void spawnParticle(EnumHarshenParticle type, Vec3d position, Vec3d directionSpeed, float scale, boolean disableMoving, Object...info) {
    	Minecraft minecraft = Minecraft.getMinecraft();
        Particle entityFx = null;
        if(minecraft.world !=  null)
	        switch (type)
	        {
		        case BLOOD:
		            entityFx = new ParticleBlood(minecraft.world, position.x, position.y, position.z, directionSpeed.x, directionSpeed.y, directionSpeed.z, scale, disableMoving);
		            break;
		        case CAULDRON:
		        	if(info[0] instanceof ResourceLocation)
		        		entityFx = new ParticleCauldron(minecraft.world, (ResourceLocation) info[0], position.x, position.y, position.z, directionSpeed.x, directionSpeed.y, directionSpeed.z, scale / 5f, disableMoving);
		        	break;
		        default:
		            break;
	        }
        if (entityFx != null) {minecraft.effectRenderer.addEffect(entityFx);}
    }`

**Comment by Wyn-Price** [comment]
In my client proxy im rendering the particles with this:
`minecraft.effectRenderer.addEffect(entityFx);`

**Comment by JamiesWhiteShirt** [comment]
I'm 99% sure this is not an issue with Forge but with what you are doing. Use the forums for support. I still have some suggestions.

Particle rendering is batched per particle texture atlas (it's a bit more complicated than that, but that's the important part), meaning binding textures while rendering particles will have unintended effects. That is probably your issue. I've found an easy workaround is to put the custom particle texture in the block texture atlas and put the particle in the block texture batch.

**Comment by Wyn-Price** [comment]
@JamiesWhiteShirt I think this is an issue with forge for many reasons. First, if I directly copy code from Mods like Biomes O' Plenty, the issue still is there. I also cant exactly put all the textures on the map, as the particles use textures that are more than one file. I also cant use FXEffect 1 and set the texutre with the TextureAtlasSprite as alot of the texures I need arnt blocks or items. The problem also occurs with diffrent mods. In the video I showed that whatever texture I was using for one mod, it would be overridden by another mod. I think i found where the issue arises though. In file ParticleManager, around line 329 there is code that runs a for loop, bulding all of the particles to the BufferBuilder. The tesselator.draw(); is after the for loop, and from what I can tell this means that it can only have 1 texture. I tried adding `Tessellator.getInstance().draw();` to the end of my rendering code, in the particle but it didnt do anything. I dont know enought about how Tesselators and BufferedBuilders work to understand full this problem but if you wanted to look over my code and see if theres anything Ive done wrong here are the links:

[ClientProxy](https://github.com/kenijey/harshencastle/blob/master/src/main/java/kenijey/harshencastle/proxy/ClientProxy.java#L164-L182)

[BaseParticleClass](https://github.com/kenijey/harshencastle/blob/master/src/main/java/kenijey/harshencastle/base/BaseHarshenParticle.java)

I dont think its possible to render more than one particle this way, with diffrent files. This also means between mods. If you could helpo at all that would be great

**Comment by JamiesWhiteShirt** [comment]
It seems I had a slight misconception about the particle system. You are supposed to use custom textures by placing the particle in `FXLayer = 3`, where particle rendering is not batched. Have a look at `ParticleExplosionLarge` or any other particle in `FXLayer = 3` to see how it's handled.

Biomes O' Plenty is doing it wrong by putting it in `FXLayer = 2`, where GL state should not be modified.

Having a texture atlas like the block/item atlas for custom particles would probably be nice, but Mojang could probably beat us to the chase.

**Comment by Wyn-Price** [comment]
The only problem with doing that is it spits out a NullPointerException on the BufferBuilder.java:451, the line being `switch (this.vertexFormatElement.getType())` I cant find a way to set the vertexFormatElement apart from in bufferbuilder.begin, which is already handled by minecraft

**Comment by Wyn-Price** [comment]
ok ive just dug a little deeper and this is really weird. Its not throwing a IndexOutOfBoundsException when its getting the vertedFormatElement, and i went through and printed all of the elements in the list, and none of them are null; so I dont know where the NullPointerException is coming from as it is seeminly not null

**Comment by williewillus** [comment]
your debugging needs to go on the forums, the issue tracker is for clear, undeniable bugs in forge itself

**Comment by Wyn-Price** [comment]
this was originally thought to be a bug in forge, as it was passing particle textures between mods; but I see now that its not.
