### ISSUE TITLE
Suggestion: Graceful handling of Ingredients with zero items when drawing ghost recipes

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#4359]
Using the Recipe Book to place a ghost of a recipe with an `Ingredient` that returns a zero-length array from `Ingredient#getMatchingStacks` will crash the game with an [`ArithmeticException: / by zero`](https://gist.github.com/Choonster/7696660f43cf0fd908fc395ae4d8474a). This was triggered by [this recipe](https://github.com/Choonster-Minecraft-Mods/TestMod3/blob/1.12.1/src/main/resources/assets/testmod3/recipes/acacia_boat_from_nonexistent_ore_ingredient.json).

By contrast, using JEI to auto-fill the same recipe simply does nothing.

Some examples of an `Ingredient` with zero items include an `OreIngredient` for a non-existent ore name or my mod's [`IngredientNever`](https://github.com/Choonster-Minecraft-Mods/TestMod3/blob/c33be5c09ce1c2b104fb5ad6336df34e4a832537/src/main/java/choonster/testmod3/crafting/ingredient/IngredientNever.java) (an `Ingredient` that never matches, used as a fallback for my conditional ingredient factory).

I can see two possible solutions to this:
* Patch `GhostRecipe.GhostIngredient#getItem` to return `ItemStack.EMPTY` if the `ItemStack` array is zero-length.
* Patch `GuiRecipeBook#setupGhostRecipe` to ignore `Ingredient`s with zero items like it does for `Ingredient.EMPTY`.

**Comment by williewillus** [comment]
Tangential comment: your `IngredientNever` can just be replaced with `Ingredient.EMPTY`.

In fact, I'm aware of several spots in the vanilla code (e.g. RecipePicker, which is a helper for the book) that do `== Ingredient.EMPTY` (identity equality), does this crash still happen with `Ingredient.EMPTY`?

**Comment by williewillus** [comment]
Or perhaps, we should replace those checks for Ingredient.EMPTY with checks for the matching stack array length

**Comment by Choonster** [comment]
> Tangential comment: your `IngredientNever` can just be replaced with `Ingredient.EMPTY`.

No, there's a subtle difference between the two: `Ingredient.EMPTY` matches if the `ItemStack` is empty but `IngredientNever` never matches. This doesn't matter for the Vanilla/Forge shapeless recipes because they check that the `ItemStack` isn't empty before checking if the `Ingredient` matches, but the Vanilla/Forge shaped recipes don't check if the `ItemStack` is empty before checking if the `Ingredient` matches.

For my conditional ingredient factory, I don't want the `Ingredient` matching an empty slot if the conditions weren't met; I don't want it to match anything.

> does this crash still happen with `Ingredient.EMPTY`?

Using a `minecraft:empty` ingredient directly won't crash because `GuiRecipeBook#setupGhostRecipe` specifically ignores `Ingredient.EMPTY`. Using an array of two `minecraft:empty` ingredients (i.e. a `CompoundIngredient`) will crash with the same `ArithmeticException`.

**Comment by Choonster** [comment]
This issue is still relevant, neither `GuiRecipeBook` nor `GhostRecipe` has been patched to fix it.

**Comment by Choonster** [comment]
This issue is still relevant, neither `GuiRecipeBook` nor `GhostRecipe` has been patched to fix it.
