### ISSUE TITLE
@Config.LangKey annotation on @Config class is ignored if there's only one @Config class in a mod

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#4361]
`ConfigElement.from` initialises the `DummyCategoryElement` it returns using the `@Config.LangKey` annotation on the `@Config` class, but `GuiConfig.collectConfigElements` will immediately get the child elements of this and discard it if there's only one `@Config` class in the mod.

This means that annotating the `@Config` class with `@Config.LangKey` does nothing when there's only one `@Config` class in the mod (which I suspect is very common). I'd expect this to control the title of the config GUI instead of it being hardcoded to the mod's name.

**Comment by thilokru** [comment]
Can you give me a usecase where the root config doesn't concern the mod? The idea was that the configuration influences each mod independently. This behaviour would give the player a unified behaviour and he could tell at a glance what mod he is currently configuring.

**Comment by Choonster** [comment]
Before you added `@Config`-compatible config GUIs, I used `TestMod3 Config` as the title of my mod's config GUI.

It's not super important, but it just seemed like an oversight that the title was hardcoded instead of being configurable like it was before.

**Comment by LexManos** [comment]
Honestly, I dont think this is a issue. Forcing the main config screen to be titled with the mod name is important. The main intention of LangKey was for elements, not the root config class. If you want more detailed/separated configs you can do it yourself. its a factory system for a reason.
