### ISSUE TITLE
[1.12.1] [2463] SimpleChannelHandlerWrapper exception; java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by MrBurd** [MinecraftForge/MinecraftForge#4364]
Log: https://pastebin.com/TAy0ewgs

Description: Ingame for a while, starts to appear after about 5 minutes into a multiplayer game.
It's spammed to the console with a frequency of about once per three seconds.

Assuming it's a FML error considering that's what throws the error in the first place.

**Comment by FireMasterK** [comment]
`com.pengu.hammercore.net.packetAPI.PacketManager.sendToAllAround(PacketManager.java:121) [PacketManager.class:?]`
This is a mod and not FML's error

**Comment by mezz** [comment]
Please use the forums.
