### ISSUE TITLE
[1.12] Incorrect Cascading Chunk Generation Message

### ISSUE THREAD

**Issue by Draco18s** [MinecraftForge/MinecraftForge#4366]
> [14:37:53] [Server thread/WARN] [FML]: HardLib loaded a new chunk (-88, 43  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

[HardLib](https://github.com/Draco18s/ReasonableRealism/tree/master/src/main/java/com/draco18s/hardlib) does not contain any other world generation class of any kind.

(Linked repo is current to 1.11, but is consistent with my development for 1.12: I've only made changes regarding how items/etc are registered and recipe / advancement json files).

**Comment by LexManos** [comment]
HardLib is the active container. Something up the stack is being controlled by HardLib.
It doesnt need to be a world generating class, it could be a block, a tile entity, a entity, a random function. Anything that loads a chunk.

**Comment by Draco18s** [comment]
Any suggestions on how narrow down the cause?

**Comment by Niko-sk2x** [comment]
It would be nice if there was an option to make Forge show the stacktrace when it happens. That would make it possible to see what is the issue without debugging it in dev environment (is there a different way now?) Especially when sometimes the issue is very hard to reproduce..

**Comment by Draco18s** [comment]
Not sure a stack trace would help. Let me see...ah, it does. Turns out this is originating in Custom Ore Gen. Would not recommend showing the whole stack trace on each of these messages, those get huge and now you've got the overhead of displaying logging information.

Still not sure how that means that HardLib is the (correct) container though. HardLib only has a require-after on COG, it's not *part* of COG (parent/child).
