### ISSUE TITLE
Problem of Sync (Minecraft) ?

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4369]
I want to create a mod for extend minecraft for "easy life" and include my mods with it,
i extends the number of item the player can held.

It's working but if you hold more than 64+ like 65 instant with creative (shift-click) and right click on ground
like block, the block is placed but dispear instant like mob in peaceful after selected.
Is a problem of sync with item or a bug ?
Thanks in advance.

PS: if the stack is 128 and right click for 64/64 and restack it it's working.

**Comment by ghost** [comment]
The ItemStack (NBTTag) is in byte but need to be short minimum for more than 128+

**Comment by ghost** [comment]
Not fixed my problem :(

**Comment by diesieben07** [comment]
Use the forum for help with making mods.
