### ISSUE TITLE
Only 1/4th of the screen is showing with the most recent 1.8.9 Forge.

### ISSUE THREAD

**Issue by Adornable** [MinecraftForge/MinecraftForge#4374]
https://gyazo.com/ec14258c467b7606ab65a317a249fef5

This is all I see and I've already reinstalled it an the issue persists, any idea how to fix this?

**Comment by LatvianModder** [comment]
>most recent 1.8.9

**Comment by Adornable** [comment]
Well using the not most recent 1.8.9 Forge it doesn't even start up

**Comment by raoulvdberge** [comment]
> 1.8.9

**Comment by marvin-roesch** [comment]
> Forge

Wait, what?

**Comment by Daomephsta** [comment]
@Adornable Forge only supports the newest MC version with a stable version of Forge, due to lack of manpower. The only exception is critical bugs.
