### ISSUE TITLE
CropGrowEvent for multiblock crops needs work

### ISSUE THREAD

**Issue by josephcsible** [MinecraftForge/MinecraftForge#4379]
Here's the result of the CropGrowEvent.Pre and CropGrowEvent.Post hooks for multiblock crops today:

Crop | Creating new block | Pre.getPos() | Pre.getState() | Post.getPos() | Post.getOriginalState() | Post.getState()
--- | --- | --- | --- | --- | --- | ---
Cactus | No | The block above the cactus | The state of the cactus | The cactus | The old state of the cactus | The new state of the cactus
Cactus | Yes | The block above the cactus | The state of the cactus | The original cactus | The old state of the original cactus | The new state of the original cactus
Chorus flower | No | The block above the chorus flower | The state of the chorus flower | The chorus flower | The old state of the chorus flower | The new state of the chorus flower
Chorus flower | Yes | The block above the chorus flower | The state of the chorus flower | The original location of the chorus flower | The old state of the chorus flower | The state of the chorus plant where the chorus flower used to be
Sugarcane | No | The sugarcane | The state of the sugarcane | The sugarcane | The old state of the sugarcane | The new state of the sugarcane
Sugarcane | Yes | The sugarcane | The state of the sugarcane | The original sugarcane | The old state of the original sugarcane | The new state of the original sugarcane
Stem (pumpkin/melon) | No | The stem | The state of the stem | The stem | The old state of the stem | The new state of the stem
Stem (pumpkin/melon) | Yes (failed) | The stem | The state of the stem | The attempted location of the new melon/pumpkin | The old state of the stem | The state of whatever was where the pumpkin/melon failed to grow
Stem (pumpkin/melon) | Yes (succeeded) | The stem | The state of the stem | The new melon/pumpkin | The old state of the stem | The new state of the pumpkin/melon

A lot of these results are inconsistent, nonsensical, and/or useless. Here's what I propose that they be changed to:

Crop | Creating new block | Pre.getPos() | Pre.getState() | Post.getPos() | Post.getOriginalState() | Post.getState()
--- | --- | --- | --- | --- | --- | ---
Cactus | No | The cactus | The state of the cactus | The cactus | The old state of the cactus | The new state of the cactus
Cactus | Yes | The cactus | The state of the cactus | The new cactus | The old state of the new cactus (likely air) | The state of the new cactus
Chorus flower | No | The chorus flower | The state of the chorus flower | The chorus flower | The old state of the chorus flower | The new state of the chorus flower
Chorus flower | Yes | The chorus flower | The state of the chorus flower | The original location of the chorus flower | The old state of the chorus flower | The state of the chorus plant where the chorus flower used to be
Sugarcane | No | The sugarcane | The state of the sugarcane | The sugarcane | The old state of the sugarcane | The new state of the sugarcane
Sugarcane | Yes | The sugarcane | The state of the sugarcane | The new sugarcane | The old state of the new sugarcane (likely air) | The state of the new sugarcane
Stem (pumpkin/melon) | No | The stem | The state of the stem | The stem | The old state of the stem | The new state of the stem
Stem (pumpkin/melon) | Yes (failed) | The stem | The state of the stem | N/A | N/A | N/A
Stem (pumpkin/melon) | Yes (succeeded) | The stem | The state of the stem | The new melon/pumpkin | The old state of the pumpkin/melon (likely air) | The new state of the pumpkin/melon

Explanation of changes:
* The Pre event should always give the position and state of the block that's about to do the growing
* The Post event shouldn't fire if no growth took place
* The Post event's states should both be from its given position
* Since the chorus flower can grow in multiple directions at once but we can only pass one BlockPos to Post, it should be the original position
* Since the stem can grow a pumpkin/melon in 4 different spots, its BlockPos should indicate where it grew it at

Does anyone have any comments on these changes? If they seem like a good idea, I'll create a PR for them.

**Comment by jabelar** [comment]
Makes sense to me. The only thing is, in my experience if something seems weird it good to ask the person who did it why they did it the way they did. There might be a good reason for the current behavior. But otherwise it does seem to be weird and your proposal makes sense to me.

The only suggestion I have is that for the case of things that may grow in multiple directions, maybe the event should fire from each of them.

**Comment by josephcsible** [comment]
Good point, pinging @Draco18s

**Comment by Draco18s** [comment]
They should probably be altered to be consistent. I don't recall any specific reason (i.e. I recall no intent) other than the local variables within the existing function may have already been inconsistent, leading to the mismatch.

**Comment by josephcsible** [comment]
I kind of forgot about this. Now that it's been several months with 5 thumbs up and no opposition, I'll start on a PR to make all of the changes.

**Comment by Draco18s** [comment]
I also forgot about it. Ding me in the PR and I'll help review it.
