### ISSUE TITLE
BlockEvent.HarvestDropsEvent doesn't include harvest tool

### ISSUE THREAD

**Issue by Flashfyre** [MinecraftForge/MinecraftForge#4384]
BlockEvent.HarvestDropsEvent doesn't include the ItemStack used to harvest the block.

"But it has the EntityPlayer instance, you can just get the stack they're holding". Yes, usually. Though, there is the case that the harvest is the item's last use before breaking, and the item is actually broken before the harvest code is executed. The harvest tool stack passed to Block.harvestBlock() is actually a copy of the original ItemStack, created for just this scenario. Sure, this doesn't happen very often, but it does happen, and without providing the stack from Block.harvestBlock I don't think it's possible (at least without hacky logic) to be able to perfectly replicate Vanilla harvest drop behaviour like I'm trying to do now. To be precise, I'm trying to override the fortune level and to do this I need to cancel the original drops by setting the drop chance to 0 and calling the drop method directly with the new fortune level. As part of getting this new fortune level, I actually need to access the exact tool used to harvest the block.

**Comment by LordMonoxide** [comment]
I need this too

**Comment by alcatrazEscapee** [comment]
This would help me as well.

**Comment by LexManos** [comment]
The problem with this is that that context doesnt exist for the main callpaths this event is fired from.
It only exists when silktouch is used.

**Comment by alcatrazEscapee** [comment]
Should I look for other workarounds then? I haven't ever contributed to Forge so I don't even know where I would look to try and fix this.

**Comment by LordMonoxide** [comment]
Still relevant
