### ISSUE TITLE
[1.12.1] Broken TestMod ? MapDataTest crashes server

### ISSUE THREAD

**Issue by sokratis12GR** [MinecraftForge/MinecraftForge#4391]
Mods Installed:

* Forge
* Forge's Test Mods

Crash report (server crash): [Link](https://gist.github.com/anonymous/6533dc02dca40b5995646983a45e18f6)

Way to fix this: Make MapDataTest disableable
Way to actually fix this add init() in 
```java
MapData mapdata = CustomMap.loadMapData(message.vanillaPacket.getMapId(), Minecraft.getMinecraft().world<here>);
```

**Comment by williewillus** [comment]
the class that that line is in shouldn't even be loading on the server side 0.o

**Comment by bs2609** [comment]
Swapping from a lambda to a runnable will also fix this.

The issue is that `Minecraft.getMinecraft().world` is defined as a `WorldClient`, and I believe the code there causes a sneaky reference to that class to appear in the bytecode.

**Comment by marvin-roesch** [comment]
@mezz, would it be feasible to have Travis try running the server when testing PRs in order to prevent things like these in the future? It can't cover every case of client references, but at least testing servers will start fine.

**Comment by bs2609** [comment]
How would you handle the EULA?

**Comment by marvin-roesch** [comment]
Have Gradle pre-generate it :P
