### ISSUE TITLE
Repairs in anvils don't work right with the ore dictionary

### ISSUE THREAD

**Issue by josephcsible** [MinecraftForge/MinecraftForge#4397]
Using custom wood to repair wooden tools in an anvil doesn't seem to be possible in any non-hacky way. It looks like this is supposed to work, since it's calling OreDictionary.itemMatches on the items, but that function isn't actually oredict-aware, despite where it is. I originally reported this at http://www.minecraftforge.net/forum/topic/60697-1121-let-new-material-be-used-to-repair-tools-in-anvil/ and was told to take it here.

**Comment by josephcsible** [comment]
In the latest Forge (2625), there still seems to be no way to do this.

**Comment by LexManos** [comment]
Hmm this seems to of fallen through the cracks. Its a vcalid idea just needs some thought put into it. The repair system isnt the best as it doesn't have a recipe syntax it's literally just item == repair item. May be worth having people discuss a syntax for defining these recipes.

**Comment by l-Luna** [comment]
public ItemStack Item.isItemValidForAnvilRepair(ItemStack item, Player player, World world, BlockPos pos) sounds good to me. The more parameters we have, the more we can do. It returns a null if it can't be repaired, or an ItemStack for a repair result.

**Comment by Madsthunder** [comment]
@Leppan I think that's a great idea, but the method would probably be better off being named something along the lines of 'getRepairedItem', since methods beginning with 'is' usually indicate a will be returned. And I think returning 'ItemStack.EMPTY' would be better than returning 'null'.

**Comment by LexManos** [comment]
A function added to Item is not what I meant. As that doesn't open the door for configuration. 
Were essentially talking a two input recipe that has a dynamic output based on one of the inputs. 
So something like:
`{
  "Input": normal_irecipe_ingredient_except_skips_metadata,
  "Reagent" normal_irecipe_ingredient,
  "fixammount": 12345
}`

>

**Comment by josephcsible** [comment]
This is still not possible.

(Side note: Why do we even run stale? Bugs in software don't really ever fix themselves, so why let the reports of the problems get closed without the actual problems being fixed?)

**Comment by Daomephsta** [comment]
The closing part isn't the most helpful sometimes, but stale does prevent PRs and issues from being forgotten.
