### ISSUE TITLE
[Feature] Add Conditions to Advancements

### ISSUE THREAD

**Issue by BrainStone** [MinecraftForge/MinecraftForge#4398]
Conditions similar to how they work with recipes should work with advancements, as that would allow the modders to have advancements that only exist when other mods or items are present.

**Comment by BrainStone** [comment]
This feature request is still relevant.

**Comment by mezz** [comment]
Feature requests like this are fine, but if one has been open for 6 months without discussion it's probably lost deep in the issue tracker and not going to get implemented by anyone. If anyone wants to open a PR to implement this, feel free, but unless there is more interest then there is not really a reason to keep lots of requests open.
