### ISSUE TITLE
Item models generated by Forge don't match Vanilla

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#4401]
See these screenshots, taken at roughly the same angle:

* Vanilla:
![vanilla](https://user-images.githubusercontent.com/1447117/30507743-73600b36-9a80-11e7-9f61-eaf7ea4f9233.png)

* Forge:
![forge](https://user-images.githubusercontent.com/1447117/30507745-774866da-9a80-11e7-93de-2b67bb512cc0.png)

In particular the side facing 'up' at that angle is brighter in vanilla, and darker in forge. It should be bright, as that's how vanilla handles shading of faces.

I think [this](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/client/model/ItemLayerModel.java#L375) code, in `ItemLayerModel`, might have something to do with it, but have no idea what the "something else" is supposed to be, so I'm hesitant to change it.

There's also some differences with what parts of the model can be seen through (although this may be intentional, I'm not sure).

**Comment by bs2609** [comment]
Also possibly related, items are 'flipped' in the offhand:

* Vanilla:
![vanilla_hands](https://user-images.githubusercontent.com/1447117/30508760-4e65136a-9a96-11e7-8b39-c4358d9e6cb7.png)

* Forge:
![forge_hands](https://user-images.githubusercontent.com/1447117/30508762-538d68e2-9a96-11e7-92b6-5001fe036ed0.png)

**Comment by JamiesWhiteShirt** [comment]
I've had the same issue with item rendering and assumed it was a vanilla bug. Seems the normals are somehow inverted on the X axis. The quads seem to be rendered in a different order or with different depth masking and/or blend function.

**Comment by bs2609** [comment]
Here's a comparison showing the result if `getOpposite` is called only for the sides on the Y axis (due to the aforementioned swapping of the V direction).

* Original:
![forge_pre](https://user-images.githubusercontent.com/1447117/30513775-06659f92-9b01-11e7-9584-03d5d2715912.png)


* Changed:
![forge_post](https://user-images.githubusercontent.com/1447117/30513777-0b53f7ec-9b01-11e7-879a-82bca06dd947.png)
