### ISSUE TITLE
EntityEntry event not registering entities correctly causing invisible spawns

### ISSUE THREAD

**Issue by bloodmc** [MinecraftForge/MinecraftForge#4406]
Whenever I attempt to use EntityEntry event with my mod, many entities fail to register correctly causing entities to end up invisible once spawned in game.

Here is the code I am using the register the entities during event 

https://gist.github.com/bloodmc/d75b703c85c8c7dd4a399304716a803f

I added a comment for the workaround I am using in the code which solves the issue.

**Comment by bs2609** [comment]
#4096
