### ISSUE TITLE
[1.12.2] EntityEntryBuilder#id(String, int) defaults to "minecraft" domain

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#4410]
When calling `EntityEntryBuilder#id(String, int)` (added in #4408) with a registry name that doesn't specify a domain, it defaults to `"minecraft"`.

I would have expected it to behave more like `IForgeRegistryEntry.Impl#setRegistryName(String)`, where the domain defaults to the mod ID of the active `ModContainer`.

The `EntityEntryBuilder` already stores the `ModContainer` that was active when it was created, so it should use this container's mod ID as the default domain.

**Comment by LexManos** [comment]
Modders should really be getting in the habit of specifying their resource domain -.-
But yes this is a simple 'fix' for lazy modders.
