### ISSUE TITLE
SlotItemHandler doesn't notify inventory of changes

### ISSUE THREAD

**Issue by daxum** [MinecraftForge/MinecraftForge#4412]
In certain places in `Container`, an `ItemStack` is taken from a slot and modified directly. Every time this happens, the slot is notified with `Slot.onSlotChanged()`.
Aside from the problems with modifying using `getStackInSlot()`, my issue is that `SlotItemHandler` doesn't override `onSlotChanged()` to notify its inventory of the changes, which can result in hard to find bugs.

I can see two possible ways of fixing this:

1. Override `onSlotChanged()` and notify the inventory of the change. This would probably involve moving `onContentsChanged()` from `ItemStackHandler` to `IItemHandlerModifiable` and making it public, or putting something like
```
    if (itemHandler instanceof IItemHandlerModifiable)
    {
        ((IItemHandlerModifiable)itemHandler).setStackInSlot(index, itemHandler.getStackInSlot(index));
    }
```
in `onSlotChanged()` along with removing the equality check in `ItemStackHandler.setStackInSlot()` (as in #3465)

2. Change every occurrence of direct modification in `Container` to instead use something like `Slot.putStack()`

Obviously, both of these are kind of undesirable, as the first one would either break binary compatibility or be needlessly hacky, and the second would require rewriting large portions of vanilla code.

If I'm completely wrong here, or someone has a better idea, please let me know!

**Comment by josephcsible** [comment]
Everything mentioned in the original post is still true as of Forge 2635. In addition, this is complicating the fixing of McJty/McJtyLib#62.

**Comment by daxum** [comment]
I could make a PR to fix this if I knew which solution would be preferred. It's not a difficult issue, I have a temporary solution [here](https://github.com/daxum/TemporalConvergence/blob/master/src/main/java/daxum/temporalconvergence/gui/SlotItemHandlerFix.java)

**Comment by josephcsible** [comment]
Once again, everything mentioned in the original post is still true.
