### ISSUE TITLE
Fernflower crashes on some setups.

### ISSUE THREAD

**Issue by CDAGaming** [MinecraftForge/MinecraftForge#4422]
When switching MCP Snapshots in build.gradle, as shown in https://github.com/CDAGaming/MinecraftForge/commit/4cb9706fcf852551c40fa803e7aae42e2b6b3c8e

Has Errors in Build, so if these can be perhaps fixed for MCP Snapshot support, i'd greatly appreciate it

**Comment by kashike** [comment]
related: https://github.com/MinecraftForge/ForgeGradle/issues/451
related: https://travis-ci.org/CDAGaming/MinecraftForge/builds/279522666#L722

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/ForgeFlower/blob/c88442dba77d20eae0f9e6a120d52428305bbd09/FernFlower-Patches/0016-Support-for-Java-9-Module-and-Package-constant-pool-.patch

**Comment by CDAGaming** [comment]
Reopen this, now its just different issues
https://travis-ci.org/CDAGaming/MinecraftForge

**Comment by CDAGaming** [comment]
@LexManos Found Specific Snapshots that are producing errors
0919,0925 are erroring so far
0916,0917, and 0918 have not been tested yet
After your fixes so far, all MCP Snapshots up to 0915 are working

**Comment by LexManos** [comment]
Ya no, you have no idea what you're doing. Just changing the snapshot in build.gradle IS NOT all you have to do to update the project -.-
Please stop thinking this is an error on our end. This is intended behavior when names change.

The actual issue had absolutely nothing to do with mappings and everything to do with FF not supporting J9 features.
That has been fixed, so closing.
