### ISSUE TITLE
Build obfuscation obfuscates wrong variable to make illegal code.

### ISSUE THREAD

**Issue by Kirdow** [MinecraftForge/MinecraftForge#4424]
**Minecraft Version:** 1.12.0

**Forge Version:** 2387

**Steps to reproduce:**
None really, as this only occurred as I compiled our mod after changing it at our new code and it suddenly broke somewhere we haven't touched in months. Though it has also worked fine without any problem for months on this version and over a year on older versions, so this bug occurred without a change in or near that class without changing the build process nor any of the files that is not the source of our mod.

Anyway I already made a detailed post about this on the forums, as you can see here http://www.minecraftforge.net/forum/topic/60904-112-gradlew-build-compiler-switches-around-variables/
But basicly I have a class named PartyChatbox which extends GuiScreen and is a recreation of GuiChatbox. Then I have a line at the top saying
```
private static final Logger LOGGER = LogManager.GetLogger();
```
And when compiled, gradle sees this code, sees the LOGGER variable which also exists as a private static final, but in the super class, and turns this code into
```
private static final Logger LOGGER;
static {
    field_175287_a = LogManager.GetLogger();
}
```

This all has worked fine and all and compiled into the first same code for over a year but yesterday suddenly it started compiling to this second weird illegal code.

**Comment by ichttt** [comment]
It was a SpecialSource issues that should have been fixed with https://github.com/md-5/SpecialSource/pull/49 , please try it again with --refresh-dependencies so gradle makes sure your ForgeGradle and SpecialSource version is up to date
