### ISSUE TITLE
[MCP // Minecraft Forge] [1.12.x] Recent MCP Snapshots causing Build Errors (Fixed - User Error)

### ISSUE THREAD

**Issue by CDAGaming** [MinecraftForge/MinecraftForge#4425]
### Important
Before Submitting this Issue, I have done the required steps towards updating the MCP snapshot for Forge (genPatches, Refreshing Dependencies, cleaning/clearing Cache, and doing full clean build)

## Issue Info:
With the 3 Most recent MCP Snapshots, 0918, 0919, and 0925, Some errors have raised within forge that prevent it from being built. These issues are defined below:

### Snapshot 20170918
`:Forge:compileJavaE:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\ForgeHooks.java:783: error: cannot find symbol
        if (gameType.isAdventure())
                    ^
  symbol:   method isAdventure()
  location: variable gameType of type GameType
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED`

### Snapshot 20170919
`:Forge:compileJavaE:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\ForgeHooks.java:783: error: cannot find symbol
        if (gameType.isAdventure())
                    ^
  symbol:   method isAdventure()
  location: variable gameType of type GameType
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\registries\GameData.java:426: error: method does not override or implement a method from a supertype
            @Override public boolean isHidden() { return true; }
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
 FAILED`

### Snapshot 20170925
`:Forge:compileJavaE:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\client\ForgeHooksClient.java:274: error: cannot find symbol
                int colour = biome.getSkyColorByTemp(biome.getFloatTemperature(pos));
                                                          ^
  symbol:   method getFloatTemperature(BlockPos)
  location: variable biome of type Biome
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\BiomeDictionary.java:258: error: method getTemperature in class Biome cannot be applied to given types;
            if (biome.isHighHumidity() && biome.getTemperature() >= 0.9F)
                                               ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\BiomeDictionary.java:266: error: method getTemperature in class Biome cannot be applied to given types;
                if (biome.getTemperature() <= 0.2f)
                         ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\BiomeDictionary.java:290: error: method getTemperature in class Biome cannot be applied to given types;
        if (biome.getTemperature() > 0.85f)
                 ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\BiomeDictionary.java:295: error: method getTemperature in class Biome cannot be applied to given types;
        if (biome.getTemperature() < 0.15f)
                 ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\BiomeDictionary.java:341: error: method getTemperature in class Biome cannot be applied to given types;
        if (biome.topBlock != Blocks.SAND && biome.getTemperature() >= 1.0f && biome.getRainfall() < 0.2f)
                                                  ^
  required: BlockPos
  found: no arguments
  reason: actual and formal argument lists differ in length
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\common\ForgeHooks.java:783: error: cannot find symbol
        if (gameType.isAdventure())
                    ^
  symbol:   method isAdventure()
  location: variable gameType of type GameType
E:\Forked Repos\Minecraft Repos\CoreFiles\MinecraftForge\src\main\java\net\minecraftforge\registries\GameData.java:426: error: method does not override or implement a method from a supertype
            @Override public boolean isHidden() { return true; }
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 errors
 FAILED`

## Snapshot 20170926
Same as Snapshot 20170925

If i can get some help in resolving these (If what i mentioned above isn't sufficient for updating MCP within Forge), or if i generally just missed something simple, I'd really appreciate it.

PS if this isn't known already, i am very new to working on forge but even still this is the only time ive had major issues with MCP

**Comment by kashike** [comment]
https://github.com/ModCoderPack/MCPBot-Issues/issues/534#issuecomment-332365342

**Comment by CDAGaming** [comment]
Ok, pushing changes i made now (Just the snapshot update to latest MCP that worked 0917, and a gradle update which didn't effect build success/failure rates)

**Comment by kashike** [comment]
> It doesn't look like you've updated your fork of MinecraftForge. Do so.

You keep opening issues about MCP/Forge/etc being broken, when it is your fault. You haven't updated the actual *code* to use the new names rather than the old.

**Comment by CDAGaming** [comment]
> PS if this isn't known already, i am very new to working on forge but even still this is the only time ive had major issues with MCP

That's why i had put in this last part, that's because im trying to figure out how. I'm fully aware it's not Forge's fault, all i need is just assistance here

**Comment by kashike** [comment]
1. Open the MinecraftForge project in your IDE.
2. Edit code.

**Comment by LexManos** [comment]
Closing this.
This is your final warning. Quit spamming our repos with the fact that you have no idea what you're doing.
Any further posts about this will get you banned from our repos.
This is basic fucking java. If you update names UPDATE THE CODE! It's not magic, working on Forge DOES actually take effort!

**Comment by CDAGaming** [comment]
Well, Lex, it seems you were right, as i originally thought. Looking into the actual MCP, it seems each of the functions did in fact have naming changes, so doing this SHOULD have been easy for me.

I apologize for wasting your time...

**Comment by CDAGaming** [comment]
https://github.com/CDAGaming/MinecraftForge/commit/7b03fa03881e2ae64c9a949a33893a63955c7768
Finally Did what i needed to do properly, may submit as a PR tomorrow for the MCP Supports

**Comment by liach** [comment]
@CDAGaming Well, mappings break complication for they change method and field names. You need to update the test mods, too!

**Comment by LexManos** [comment]
No, The main repo doesn't really take PRs updating the mappings we use. As this has no effect on the end modder they can already edit the mappings all they want.

**Comment by kashike** [comment]
Generally @mezz will update the mappings used in the main repository every once in a while.

**Comment by CDAGaming** [comment]
https://github.com/CDAGaming/MinecraftForge/commit/4d60895c29293446a690de49fe1545b1f565fe9f
https://github.com/CDAGaming/MinecraftForge/commit/a5dbf15f956c331cbe369eb6fe09e27c63b60117

Fixes to Previous Commit, should be all good now :)

**Comment by LexManos** [comment]
We don't care, stop spamming us.
