### ISSUE TITLE
Deprecated method in RenderingRegistry marked to be removed in 1.11

### ISSUE THREAD

**Issue by darkevilmac** [MinecraftForge/MinecraftForge#4426]
``RenderingRegistry.registerEntityRenderingHandler(Class<? extends Entity> entityClass, Render<? extends Entity> renderer)`` is deprecated and the docs state it will be removed in 1.11 (which has already passed), it should probably be either removed now or marked as a todo for 1.13

**Comment by bs2609** [comment]
#4201

**Comment by GirafiStudios** [comment]
Have been removed in 1.13.
