### ISSUE TITLE
Sounds incorrect on server, correct on singleplayer

### ISSUE THREAD

**Issue by kallezz** [MinecraftForge/MinecraftForge#4428]
Minecraft Version: 1.10.2

Forge Version: 12.18.3.2422

I've had this same issue now with FTB Beyond and Foolcraft, I have used hours and hours troubleshootin it.
What happens is whenever I play on server the sounds that are played are incorrect. Reloading tc crossbow sometimes makes squeeky sounds sometimes nothing, shooting arrows in stone makes owl sounds, other players walking on factoryblocks makes ambient noises.

Sometimes server says Founda missing ID from the world tconstruct:crossbow_reload and other sounds.
Weirdest thing is everything is fine in singleplayer if I copy the worldsave over, sounds are correct and if I generate new map for the server sounds are still messed up.

I have tried full reinstall of the server and client, also happens with my friend so issue seems to be the server. Currently hosting on my own computer (Foolcraft 2.1), even more weird is that I had the same issue before on FTB Beyond that was hosted on creeperhost. I have found people reporting about this kind of issues but so far I haven't found any fixes for it.

**Comment by LexManos** [comment]
Mods tend to screw up ids, you need to make sure everything is synced between server and client setup.
However, this is not the place for basic tech support use the forums.
And also update to 1.12.2.
