### ISSUE TITLE
I have friezes

### ISSUE THREAD

**Issue by dronchik1995** [MinecraftForge/MinecraftForge#4439]
Hello, I have a problem with forgeoptifive, I live in Russia, I'm sorry that I know English so badly when I play I have friezes 
[Log Error.txt](https://github.com/MinecraftForge/MinecraftForge/files/1350103/Log.Error.txt)

**Comment by liach** [comment]
Seems there is an invalid villager profession. Anyways, you should post this on forums before coming here.

**Comment by mezz** [comment]
Please report here: http://www.minecraftforge.net/forum/forum/18-support-bug-reports/
