### ISSUE TITLE
FluidUtil helper methods don't play fill/empty sounds correctly.

### ISSUE THREAD

**Issue by Zarathul** [MinecraftForge/MinecraftForge#4440]
`FluidUtil.tryFillContainer(...)` and `FluidUtil.tryEmptyContainer(...)` both use `EntityPlayer.playSound(...)` which sends the sound event to all nearby players **except** the one triggering it. This means if a player fills or empties a fluid container, players around him will hear the sounds but he himself won't. 

To fix this `World.playSound(...)` with the `player` parameter set to `null` should be used instead. `FluidUtil.tryPlaceFluid(...)` already uses `World.playSound(...)` but with a non-null `player` parameter which results in the same buggy behavior.

**Affected lines:**

This one can be fixed by simply replacing the `player` parameter with `null.`
https://github.com/MinecraftForge/MinecraftForge/blob/b361b72515d1fddd4be0d822cb79b9e38187143c/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L612-L613

With these two the `player.playSound(...)` should be replaced by `player.getEntityWorld().playSound(null, ...)`.
https://github.com/MinecraftForge/MinecraftForge/blob/b361b72515d1fddd4be0d822cb79b9e38187143c/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L147-L148

https://github.com/MinecraftForge/MinecraftForge/blob/b361b72515d1fddd4be0d822cb79b9e38187143c/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L190-L191

**Comment by JamiesWhiteShirt** [comment]
`FluidUtil.tryPlaceFluid` is based on `ItemBucket#tryPlaceContainedLiquid`. This method is designed to run on both the server and the client that performs the action. I believe `FluidUtil.tryFillContainer` follows this design, so this method is working as intended. It seems `FluidUtil.tryEmptyContainer` is designed the same way.

[The docs have an explanation for why this sound method is used, see Playing Sounds.](https://mcforge.readthedocs.io/en/latest/effects/sounds/)

**Comment by Zarathul** [comment]
In the case of `FluidUtil.tryPlaceFluid` you are probably right. If the other methods really are intended to be used in the same way I'm gonna stick with the workaround I currently use.

**Comment by mezz** [comment]
I've been thinking about this a bit.
Machines should not sync their fluid levels to the client except to show in the gui, it would cause packet spam to sync all the small changes. That means the client is not able to simulate this interaction properly, so it should be handled entirely by the server and the server should play all the sounds.
These methods should still work on the client if someone wants to simulate them better, but it should not depend on the client simulation in order to work.
I'll make a PR soon to fix this up.
