### ISSUE TITLE
Fields with 'transient' keyword should be ignored by ConfigManager

### ISSUE THREAD

**Issue by LatvianModder** [MinecraftForge/MinecraftForge#4442]
Example:
`public int valueThatWillBePartOfConfig = 393`
`public transient int valueThatWontBePartOfConfig = 854`

Only alternative currently is to have the field private, and make a public getter for it. But I feel like supporting transient fields would be better, since Gson does this too, and it shouldn't be too hard.

**Comment by LexManos** [comment]
I guess you could, but seriously? Why do you have non-config fields in your config object?

**Comment by LatvianModder** [comment]
For example, fields like these: https://github.com/LatvianModder/FTBUtilities/blob/master/src/main/java/com/feed_the_beast/ftbu/FTBUConfig.java#L150-L151

**Comment by thilokru** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/cc058c68af2007be27a99efac509c7506ebdcfff/src/main/java/net/minecraftforge/common/config/ConfigManager.java#L217 It realy is rather easy to implement. Just check for it like we check for static fields in objects.

**Comment by LexManos** [comment]
>For example, fields like these: https://github.com/LatvianModder/FTBUtilities/blob/master/src/main/java/com/feed_the_beast/ftbu/FTBUConfig.java#L150-L151

That's not an explanation.

**Comment by thilokru** [comment]
I've got one. I had a config class which contained temporary data related to and derived from loaded config files, but it should not be stored, as they were complex objects, optimized for runtime. Therefore the possibility to mark them as transient and not having them be saved, would be helpfull.

**Comment by kashike** [comment]
In that example: a cached array of text components built from a string - you don't want to store the components themselves.
I can see other use cases as well.

**Comment by LexManos** [comment]
Or, you could mark them as private as described in the first post.
The problem with using public fiends that are meant to be backed by other config values, is that on writing to those fields doesn't update the real config fields.
Hence why the getter/setter option is better, as you get that 'callback event' when the field is set so you can properly set the underlying config value.
Either way I don't really care. transient in java isn't what transient really is in other languages. 
When I get a chance, or someone PRs it. But its extremely low priority now.
