### ISSUE TITLE
"/forge" should be a CommandTreeBase

### ISSUE THREAD

**Issue by LatvianModder** [MinecraftForge/MinecraftForge#4444]
It's easy to convert existing commands to CommandTreeBase, and even easier to add new commands.

`One personal reason I can think of, is that I can give my players "command.forge.tps" and forbid all others. It could be for players by default, and all others - for OPs, since afaik you can't do any harm with tps.` (from comment below)

**Comment by LexManos** [comment]
It could be, but it doesn't need to be.
Essentially this post is "I don't like how you wrote your code, change it!"

**Comment by LatvianModder** [comment]
No, this is more like... There is a better option available now, which wasn't before, when this code was written, so consider using that one instead. One personal reason I can think of, is that I can give my players "command.forge.tps" and forbid all others. It could be for players by default, and all others - for OPs, since afaik you can't do any harm with tps.

**Comment by liach** [comment]
I suggest keeping things as-is.

**Comment by mezz** [comment]
Please give your reasoning up-front, the original post really gave no reason to do it.
