### ISSUE TITLE
Brewing recipes are not NBT sensitive

### ISSUE THREAD

**Issue by EnderiumSmith** [MinecraftForge/MinecraftForge#4450]
The input can only be a potion. NBT is the only thing that differentiates between them. I tried to register recipes for my potions and it took me a while to figure out why it works with any input.

**Comment by williewillus** [comment]
This needs more details, is this vanilla's brewing recipe system or forge's? show code that doesn't work?

**Comment by KnightMiner** [comment]
I believe he is referencing [Brewing recipe](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/brewing/BrewingRecipe.java) from the forge brewing registry. It currently ignores NBT so if you check against the input being a specific potion, any is accepted.

It is easy enough to extend it to make it NBT sensitive, but it's odd that Forge does not provide such a class by default.
