### ISSUE TITLE
DecorateBiomeEvent.Post is not fired on TERRAIN bus

### ISSUE THREAD

**Issue by AlexiyOrlov** [MinecraftForge/MinecraftForge#4458]
https://github.com/MinecraftForge/MinecraftForge/blob/f2adf0100c016213ed7d570db56420c7685637db/patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch#L136
While 
https://github.com/MinecraftForge/MinecraftForge/blob/f2adf0100c016213ed7d570db56420c7685637db/src/main/java/net/minecraftforge/event/terraingen/DecorateBiomeEvent.java#L45

This has been for a while there, so please, either fix few words in javadoc or make the event fire on terrain bus.

**Comment by bs2609** [comment]
#3541
