### ISSUE TITLE
Which approach to fix do you like: Fluids should act more like water (push, drown, swim, have boat float, etc.) without needing Material.WATER

### ISSUE THREAD

**Issue by jabelar** [MinecraftForge/MinecraftForge#4463]
So the Forge fluid system is really cool, but not quite complete. One of the major issues is that Material.WATER is hard-coded throughout Minecraft vanilla code when testing for things like pushing, fog overlay, drowning, having boat float and swimming. Furthermore, it forces the map color to the same as water.

Now, with some work you can code around this. For example, I have successfully in the past used events to entirely override the player movement code with a copy of vanilla modified to also account for fluids. However, it is a lot of work and not very easy to maintain.

Therefore, I would like to work on a pull request to fix this. However, while looking at it I found there are a few different ways to accomplish it and wanted to get feedback.

There is a very, very simple way where you can in BlockFluidBase override the isEntityInsideMaterial() method and check if the vanilla code is checking for material water and return true (even if your material isn't water). This works well except it doesn't allow you to select which water behavior you want -- you either get all or nothing. However, I feel that modders might want to allow a person to drown without being allowed to swim, or might want to be pushed without being able to drown, and so forth.

Unfortunately, the isEntityInsideMaterial() method has no idea why it is being called, so if we want to give modders control over each water-like behavior then we'll have to hook into each vanilla code area and modify to accomodate fluids as well.

Please let me know which approach you would prefer -- simple approach where you can set your fluid to do all the stuff water does, or more precise approach with control over each behavior.

The next thing is I have some questions about what you'd prefer in order to control whether this water-like behavior is enabled:

Question 1) Should the control be in the Fluid class, in the Material class, or in BlockFluidBase class? For example if we want to add a setCanDrown() method, which class would you like that in? I kinda feel that logically it is a feature of the fluid so putting it in the Fluid class makes most sense to me. However, the vanilla code is working with the Material.WATER so maybe it more of a Material thing? 

Question 2) Should the whole mechanism be tied to the Material.isLiquid() method? Like if you want any of the water-like features you would either use MaterialLiquid, or create your own material that returns true for isLiquid() and then the rest of the water-like stuff could function? I sort of feel like this would work. In fact, we could go as far as simply replacing all tests for Material.WATER with a test for Material.isLiquid() instead (with some care being taken to differentiate LAVA where needed).

Anyway, what are your thoughts? I think most people who have worked with Fluids would like easy access to these water-like behaviors, right? If so, I suspect people would want fine control over each aspect.

So my main proposal is this: wherever there is water-like behavior in the vanilla code we would test if the material isLiquid() and if so we would check for a non-null Fluid and if so would check if the behavior is enabled (drowining, swimming, etc.).

But I could also make it super simple where every liquid by default has all water-like behavior.

**Comment by jabelar** [comment]
So I did a test and got it to work quite well by simply making all relevant tests for WATER change to test for Material.isLiquid(). My custom fluid would push me, drown me, I could swim, I could use a boat, it would extinguish fire, and I could soak it up with a sponge. The changes were actually quite simple and not really that crazy of a patch set.

I'll probably generate a PR for it. However, there are a couple details that would need to be discussed. 

For example, there several tests for WATER which I chose not to change to work for all liquids:
- I felt that anything related to plant growth, such as whether a plant could spawn or be sustained, or whether the fluid would convert farmland, should be left to actual WATER. But that is something that could be argued.
- The splash particles are blue like water. If we wanted to have splashes that matched the fluid color, there would be more work to do, it fact might be a fair bit of work to do since spawning custom particles works a fair bit differently than vanilla particles. So seems that splashing is something we would not want all liquids to do.
- Water creatures and whether they could spawn or survive in the fluids would need to be discussed. The simple implementation I did doesn't spawn them in the fluid, but can allow them to survive/swim in it.
- mixing with lava to create obsidian. I didn't enable that although it is easy to do. I think the proper way would be to check the temperature of the fluid and if it was sufficiently cool you could mix it.

There is also some detail to consider wherever the isLiquid() test would return true for lava. For example, pathfinding, you wouldn't want entities going through lava like water. This is easy to do though, and is simply a matter of checking if not LAVA at time you check for isLiquid().

Other refinements based on fluid fields can be made as well, like maybe boats should only float if the density of the fluid was as dense as water or greater. The fluid should probably only extinquish fire if the material is also false for canBurn(), the fluid should probably only drown you if the isGaseous() is false, and so forth. Or perhaps, either material or fluids should have a couple additional fields for these things "canDrown", "canFloatBoat", "isSwimmable" type things. Any thoughts?

Overall, it was actually pretty easy to have any liquid act mostly like water. 

Should I go ahead and work on a PR for review, or do you guys want to debate either the details or the whole idea here first?

I personally think we need to take some action to complete the Fluid system. It is close, but the fact that fluids don't do many water-like things is quite a loss to those modding with custom fluids IMO.

**Comment by EnderiumSmith** [comment]
I dont think sponges should work as you can extract water later from them. Also endermen should only take damage from water. A gaseous fluid should drown you unless its oxygen. I think it should have fields for each property.

**Comment by jabelar** [comment]
Okay, I issued PR #4478 to address all this.

> I dont think sponges should work as you can extract water later from them.

Good point. But I created a separate enable setCanBeAbsorbed() setter so it can be up to the modder. It would be cool future enhancement where sponge can contain different fluids. 

> I think it should have fields for each property.

Yep, I went ahead and did it. Not really too hard logically. You can now set and get each property directly and also I provided convenience predicates. So if you want to know if it can float a boat, just call Material.canFloatBoat() and if you want to know if it can drown an entity just call Material.canDrownEntity().

> A gaseous fluid should drown you unless its oxygen. 

Since I provided separate controls, it can be up to the modder.

**Comment by l-Luna** [comment]
What about a 'getHasProperty(EnumFluidProperty)' type thing?
EnumFluidProperty would then have all the specific properties:
canBoatFloat, canMobDrown, canMobSwim, canPlantGrow, etc.

**Comment by jabelar** [comment]
That would be good except it would be inconsistent with the methods that already existed, which were separate getters for each property. Also, technically they all have every property but the property has different values so it would instead be a getProperty(EnumFluidProperty). 

While it would look "cleaner" I don't think it really matters in terms of usefulness -- about the same amount of typing and IDE can help auto-suggest the getter methods almost as easily as an enum value.
