### ISSUE TITLE
WorldProvider.getMovementFactor not applied to non-player entities?

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#4470]
WorldProvider.getMovementFactor allows one to adjust the 8x nether "fast travel" multiplier

However, it's only patched in in PlayerList and not into Entity.changeDimension, meaning all non-player entities ignore it. Is this intended?

**Comment by mezz** [comment]
It looks like that method goes back earlier than Forge for 1.2.5.
The javadoc says it's applied to a player's position, but I think leaving out other entities is an oversight.
If you push something through a portal, it's reasonable to expect it to show up in the same place you do.
