### ISSUE TITLE
Trace/Debug outputs in log

### ISSUE THREAD

**Issue by chaNcharge** [MinecraftForge/MinecraftForge#4483]
I'm not sure if this is a bug or not, but I need a way to decrease the logging level for Forge. It appears to have a significant impact on the game's performance and it makes the log look like a mess. I looked on google on how to try to reduce it, yet none of them worked. This occurs on 1.11.2-forge1.11.2-13.20.1.2513 without any mods installed.

**Comment by LexManos** [comment]
You can specify your own log4j.xml using normal Log4J mechanics. However we have not seen an significant performance issues related to logging, And it's better to log more then you need to in case things go wrong. So this is what we ship.
