### ISSUE TITLE
Quick Question regarding Forge's Installer (1.12.X

### ISSUE THREAD

**Issue by CDAGaming** [MinecraftForge/MinecraftForge#4484]
This might seem like a very idiotic question to ask, but i am kind of confused here

In Forge's Build.gradle file the installerVersion is set to "1.5", while at `http://files.minecraftforge.net/maven/net/minecraftforge/installer/` it says the latest installer version is "1.7"

I would just like to know what id need to edit besides  `installerVersion = "1.7"`
Thanks in advance for any help with this question

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/Installer
It all depends on if you need the functionality added in the later versions, Forge does not. So there isn't need to update.

**Comment by CDAGaming** [comment]
Ok, thanks for the answer :)
