### ISSUE TITLE
World#getTopSolidOrLiquidBlock ignores liquids 

### ISSUE THREAD

**Issue by Matryoshika** [MinecraftForge/MinecraftForge#4497]
Minecraft Version: 1.12.2
Forge Version: 14.23.0.2491

I used World#getTopSolidOrLiquidBlock in an implementation of an IWorldGenerator, but eventually found my blocks underwater. 

After looking at World#getTopSolidOrLiquidBlock, I found out that it only stops the for-loop when it encounters a BlockState whose material blocks movement, and isn't leaves/foliage.
This essentially makes the method 50% useless, as it cannot see any materials that are, or are derivatives of, MaterialLiquid.

**Comment by bs2609** [comment]
That's just because the method is poorly named, see https://github.com/ModCoderPack/MCPBot-Issues/issues/392.
