### ISSUE TITLE
ForgeHooksClient.RenderTileItem Hard-Coded Null Crash

### ISSUE THREAD

**Issue by Itszuvalex** [MinecraftForge/MinecraftForge#4498]
Minecraft Version: 1.12.2
Forge Version: 14.23.0.2528

https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/client/ForgeHooksClient.java#L563

Passing null for te as first parameter will lead to a null dereference as TileEntitySpecialRenderer attempts to call te.getDisplayName() in render().

Obviously as this is an abstract class, you can avoid the crash by never calling super.render() or checking for null yourself, but it seems incorrect to have an unsafe usage that requires the deriving class to handle.

**Comment by williewillus** [comment]
I suggest changing the interface to just accept registrations of (item, meta) -> TileEntity, instead of Class<TileEntity>, then just calling that TE's TESR and passing that TE in.

**Comment by LexManos** [comment]
This is only a issue when you use the default renderer as it tries to render a missing model essentially.
If you're rendering a custom TE for your itemstack you should code it to take into account you can have a null TE.
This is a ugly ugly system, and honestly, 99% of the time you don't need a TESR, you can do what you want with standard models, so welcome to the hacks of dealing with special renders/GL code.
