### ISSUE TITLE
Waterflow in 1.12.2 (latest version)

### ISSUE THREAD

**Issue by TimGoll** [MinecraftForge/MinecraftForge#4499]
Placed Water in a canal with an end stops the waterflow one block before the canal actually ends. (Just vanilla with forge, no mods installed)

![image](https://user-images.githubusercontent.com/13639408/32416537-e6119446-c24a-11e7-85dd-ef0b24faae95.png)

**Comment by williewillus** [comment]
Does it happen in the other directions? Which direction is this if not?
Can you show a screenshot of vanilla too?

**Comment by TimGoll** [comment]
It happens in all directions, none in vanilla

looks like this in vanilla:
![image](https://user-images.githubusercontent.com/13639408/32416914-6ef6ce06-c251-11e7-8657-b93e286348fc.png)

**Comment by williewillus** [comment]
I suspect this is due to https://github.com/MinecraftForge/MinecraftForge/commit/57e6559fa4da168e22df807e4cb5f4de688ab886 

Does it happen in 2519 (the build before that commit)?

**Comment by TimGoll** [comment]
I can Test it.
At least it worked two weeks ago
