### ISSUE TITLE
[1.12] Removing recipes/entities can cause extreme log spam from advancement parsing errors

### ISSUE THREAD

**Issue by Blargerist** [MinecraftForge/MinecraftForge#4500]
Removing recipes/entities that advancements require cause an error message with stack trace to be printed to the log. This is of course an entirely legitimate error, but for modpacks which modify recipes heavily, this can result in thousands of lines of errors, heavily spamming the log. To show off how bad the log spam can get, here's a log section from the upcoming modpack SevTech Ages: https://gist.github.com/Blargerist/f43b34a6b29829a8bc5b4dd7a7acb614

Thought it would be best to make an issue, for community ideas on how to best handle this.

EDIT:
Ideas on how to handle it:

- Add option to Forge to condense error logs into a single message
- Improve the ability of mods to cancel/modify advancement loading

**Comment by josephcsible** [comment]
Why can't you just fix or remove the advancements?

**Comment by williewillus** [comment]
there's not a clean way to do that yet, these are vanilla advancements that are throwing errors, so we would need a way to cancel or modifying their loading (like `LootTableLoadEvent`)

**Comment by josephcsible** [comment]
IMO, we should look into making that possible rather than silencing legitimate errors.

**Comment by Blargerist** [comment]
Unfortunately, fixing/removing advancements is not a particularly easy thing to do (although possible with a certain mod that uses some light core modding).

I'm specifically trying to figure out a way to handle this without a mod, because this issue is likely to effect a significant number of modpacks, and I don't think it's best that highly customized modpacks are required to use an advancements mod in order to fix error spam from changing recipes, if it can be avoided in some way.

**Comment by williewillus** [comment]
As a stopgap you can just disable the logging system (using log4j configs or just grabbing the object in code and disabling it)

**Comment by josephcsible** [comment]
See also #4398

**Comment by josephcsible** [comment]
This is still an issue. Even in the latest version of Forge, there's still no way for a mod to have advancements that depend on something that isn't always present (like some cross-mod dependency) without massive logspam.

**Comment by XakepSDK** [comment]
Bump

**Comment by LemADEC** [comment]
According mezz comment here https://github.com/MinecraftForge/MinecraftForge/pull/4541 "So for now, just log the syntax errors less noisily."
Is that still the plan?

**Comment by tterrag1098** [comment]
Superseded by #5255

**Comment by Unnoen** [comment]
Issue can be closed, PR merged: https://github.com/MinecraftForge/MinecraftForge/pull/5255
