### ISSUE TITLE
1.12.2 Crash on load due to java.lang.ClassNotFoundException [2523-2532]

### ISSUE THREAD

**Issue by imrgr** [MinecraftForge/MinecraftForge#4504]
The client crashes during loading.
**Crash Log**
[crash-2017-11-08_14.50.34-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/1455710/crash-2017-11-08_14.50.34-client.txt)
**Latest Log**
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/1455712/latest.log)

**Comment by diesieben07** [comment]
Not a Forge issue.
Also use the [forums](http://www.minecraftforge.net/forum/) for general help.
