### ISSUE TITLE
Tile unload lag spike fix

### ISSUE THREAD

**Issue by Sir-Will** [MinecraftForge/MinecraftForge#4505]
I frequently get lag spikes and the thread lock shows this:
```
java.util.ArrayList.indexOf(ArrayList.java:317)
java.util.ArrayList.contains(ArrayList.java:300)
java.util.ArrayList.batchRemove(ArrayList.java:720)
java.util.ArrayList.removeAll(ArrayList.java:690)
net.minecraft.world.World.func_72939_s(World.java:6111)
net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2197)
net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
java.lang.Thread.run(Thread.java:748)
```
In the forge build 2477 was this fix added https://github.com/MinecraftForge/MinecraftForge/commit/16127a61c797c80563ab424f1eecdbb1f7ca6bc1 

Shouldn't those lag spikes no longer show up after that fix or am I missing something?

`forge-1.10.2-12.18.3.2477-universal`

**Profiling of 3 different servers:**
![](https://i.imgur.com/Sl5da8h.jpg)
![](https://i.imgur.com/p1xcJsW.jpg)
![](https://i.imgur.com/iwB6P3D.jpg)

**Comment by bs2609** [comment]
That change only applies to tile entities, it could be the regular entity list causing lag here?

**Comment by Sir-Will** [comment]
There are overall only 125 entities, so this shouldn't be the issue.

**Comment by Sir-Will** [comment]
Added profiling screenshots from 3 different servers to the issue description.

**Comment by liach** [comment]
@Sir-Will Keep it to sponge. Apparently this is caused by actions done by sponge before the tile entities are unloaded.

**Comment by Sir-Will** [comment]
I wasn't aware of this. I assumed it's a forge issue as this is forge patch. Closing the issue here then.
