### ISSUE TITLE
setRevengeTarget should not fire LivingSetAttackEvent

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#4506]
The AI entities generally have two methods:
`setAttackTarget` representing the entity the owner is actively trying to get to and injure.

`setRevengeTarget` representing an entity that has *recently injured the owner*. This set on damage and cleared after 5 seconds. It is not used by any active attack tasks, but rather is used to *hint* to AI tasks that maybe the owner should turn its attention on it. We see this in action in `EntityAIHurtByTarget.startExecuting`, which does `owner.setAttackTarget(owner.getRevengeTarget())`. A given revenge target might never become the main target if EntityAIHurtByTarget doesn't get to execute.

What this means is that a revenged entity ends up having this event fired twice for it, once on setRevengeTarget, and once when (and if) it becomes the real attack target.

Either a new event should be created or the firing in setRevengeTarget eliminated, because just because an entity is the revenge target doesn't mean it will ever become the real target.

**Comment by williewillus** [comment]
I will make a PR for this by the end of the week

**Comment by williewillus** [comment]
unstale: made the pr finally

**Comment by mezz** [comment]
Closed by https://github.com/MinecraftForge/MinecraftForge/pull/5217
