### ISSUE TITLE
Netty direct buffer leak when client connected to dedicated server (and probably serverside leak too)

### ISSUE THREAD

**Issue by Niko-sk2x** [MinecraftForge/MinecraftForge#4509]
This is an example mod that relatively quickly shows the issue, but it happens with just about any packet size just takes much longer (it has been tested with sizes down to 64kB, but it's safe to assume it happens at least with any size down to compression threshold, if not with any size)
[ExampleMod.java.txt](https://github.com/MinecraftForge/MinecraftForge/files/1463990/ExampleMod.java.txt) (it's txt file because github wont let me upload .java file)

To reproduce:
 * Run dedicated server with the mod, and join with a client
 * ~~If the server doesn't have a lot of free memory, it may throw OutOfMemoryError, kick the client and go back to normal~~ if the packet size is above 1MB  (`1024*1024-smallValue`) and so needs splitting, the server may run out of memory
 * If the server ha s a lot of memory assigned or the packet is below 1MB, then the client will eventually throw [this exception](https://pastebin.com/raw/1rSNyiuz) (`io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 1048496 byte(s) of direct memory (used: 1060346534, max: 1060372480)`)

This means that with any mods that send custom packets, eventually the client connected to dedicated server will run out of direct memory, and also possibly cause major system slowdown (paging/swapping).

I first noticed it when my mod broke after about 15 minutes of playing (this issue: https://github.com/OpenCubicChunks/CubicChunks/issues/310). I also think it didn't happen some versions earlier so I will try to bisect it.

**Comment by Niko-sk2x** [comment]
I verified that the issue does not happen in 1.11.2 forge 13.20.1.2530, but it does happen even in early 1.12 versions. So this is likely to be caused by some internal change in netty, or a netty bug.

**Comment by liach** [comment]
Pro tip: Next time, you can post the file on [GitHub Gist](https://gist.github.com).

So, should you report this to netty?

**Comment by Niko-sk2x** [comment]
I will try to debug it first.

**Comment by MJRLegends** [comment]
This might be related to this https://github.com/netty/netty/issues/7396

**Comment by Niko-sk2x** [comment]
This has been fixed in some of the mentioned PRs

**Comment by RGFTheCoder** [comment]
I'm getting this issue on the client side once again; i have to restart mc occasionally
