### ISSUE TITLE
Cannot reload singleplayer world because of ongoing internal server transition is in progress

### ISSUE THREAD

**Issue by skupr** [MinecraftForge/MinecraftForge#4515]
Scenario:
Enter the singleplayer game, load saved world.
Exit from world into menu.
As soon as menu is available, load world again (another or the same, does not matter).
Game is stuck at "Loading World" message forever.

This happens to me very often on modpack "Modern Skyblock 2", but I've seen other people complaining that too:
https://www.reddit.com/r/FeedTheBeastCrashes/comments/753f4q/atm3_loading_world_issue/
From talking with other people, it seems that the problem occurs on big modpacks. Probably - on PC with good specs.

Log file (it has some additional log messages that I've injected during debug):
[2017-11-12-4.log](https://github.com/MinecraftForge/MinecraftForge/files/1465625/2017-11-12-4.log)
Minecraft Forge in my case is of version 14.23.0.2532.

My investigations so far:
As can be seen from the log, the problem is that when I try to load new world, it complaining about server's state:

```
[23:18:15] [Server thread/FATAL]: Fatal errors were detected during the transition from SERVER_STOPPING to SERVER_ABOUT_TO_START (actual SERVER_STOPPED). Loading cannot continue
....
[23:18:15] [Server thread/FATAL]: The ForgeModLoader state engine has become corrupted. Probably, a state was missed by and invalid modification to a base classForgeModLoader depends on. Thi
s is a critical error and not recoverable. Investigate any modifications to base classes outside ofForgeModLoader, especially Optifine, to see if there are fixes available.
[23:18:15] [Server thread/ERROR]: A fatal exception occurred during the server about to start event
java.lang.RuntimeException: The ForgeModLoader state engine is invalid
        at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:193) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:841) [Loader.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:290) [FMLCommonHandler.class:?]
        at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:155) [chd.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
```

 I've found out that when exiting from the world, internal server is switching first to SERVER_STOPPING state, and stays in that state after client already exited from world and is able to load world again. But when I'm trying to load the world again, code assumes that server is in an AVAILABLE state, and that causes the unrecoverable error.
As a result, entire game process needs to be relaunched, which usually takes quite a time on big modpacks.

Workaround for the player is to wait for some time between exiting the world and then (re-)loading world. But it's problematic - hard to guess exact timing. To be sure, one has to look in logs and wait for specific log messages that indicate server has stopped (by the way, there's no direct message about that in standard log).
In my situation, it's about 15 seconds of waiting.

So as far as I can understand, there is a miscommunication between server and client - generally, client should wait until server is fully stopped - either at the end of exiting world, or when loading new one.

I've also investigated a bit deeper down, maybe that will be useful too. The delay between SERVER_STOPPING and SERVER_STOPPED is caused mostly by call
FMLCommonHandler.instance().reloadSearchTrees()
which is called in that sequence:
- MinecraftServer.run()
- FMLCommonHandler.handleServerStopped()
- Loader.serverStopped()
- GameData.revertToFrozen()
- Loader.fireRemapEvent(Map<ResourceLocation, Map<ResourceLocation, Integer[]>>, boolean)
- LoadController.propogateStateMessage()
- sendEventToModContainer(state, mc) where mc is ForgeModContainer, and state is FMLModIdMappingEvent, which in turn calls
- ForgeModContainer.mappingChanged()
-FMLCommonHandler.instance().reloadSearchTrees();

This is what I've got so far.

**Comment by BrisingrAerowing** [comment]
I'm getting this error as well. It usually ends up corrupting the forge state engine and corrupting the world, even after a restart. Thank God for AromaBackup!

**Comment by LexManos** [comment]
Use the forums for basic debugging. This is 99% not a Forge issue but a issue in your mods pack. We include mechanics when shutting down integrated server to wait for it to fully close before going back to the main screen.

**Comment by skupr** [comment]
Ok, I understand that it may not be a Forge issue. Could you please help me understanding MCForge logic so I can track down this issue? From my current understanding (which is currently very weak), the problem is that on some conditions client does not wait for internal server to be fully stopped. Because of that, I have two (related) questsions:
Where is that mechanics in the code? How mods can interfere in that process?

**Comment by skupr** [comment]
Ok, my further investigations:
Client waits for server to be shut down at
net/minecraft/client/Minecraft.java:2451
```
                while (!integratedServer.isServerStopped())
                {
                    try
                    {
                        Thread.sleep(10);
                    }
                    catch (InterruptedException ie) {}
                }
```
net/minecraft/server/MinecraftServer.java:1212
```
    public boolean isServerStopped()
    {
        return this.serverStopped;
    }
```
So it just wait for server's property serverStopped to be true.
But:
net/minecraft/server/MinecraftServer.java:575
```
            try
            {
                this.stopServer();
                this.serverStopped = true;
            }
            catch (Throwable throwable)
            {
                LOGGER.error("Exception stopping the server", throwable);
            }
            finally
            {
                net.minecraftforge.fml.common.FMLCommonHandler.instance().handleServerStopped();
                this.serverStopped = true;
                this.systemExitNow();
            }
```
So, handleServerStopped() is executed AFTER this.serverStopped = true
And handleServerStopped is peforming transition of LoadController to SERVER_STOPPED and then AVAILABLE state. So I still think that's a problem in forge.
The mods in this case are only responsible for long transition from SERVER_STOPPING to SERVER_STOPPED.

**Comment by skupr** [comment]
So I suppose the fix is to remove
this.serverStopped = true;
that is directly after
this.stopSever()

**Comment by mezz** [comment]
This is not the right place for investigating, please copy your report here instead: 
http://www.minecraftforge.net/forum/forum/18-support-bug-reports/
