### ISSUE TITLE
RenderLivingEvent firing for all entities event tho i have a type argument supplied

### ISSUE THREAD

**Issue by m00nwtchr** [MinecraftForge/MinecraftForge#4522]
My code:
```java
    @SubscribeEvent
    public static void onSheepRender(RenderLivingEvent.Pre<EntitySheep> e) {
        EntitySheep sheep = (EntitySheep) e.getEntity();

        EnumDyeColor color = sheep.getFleeceColor();
        ResourceLocation sheepTexture = color == EnumDyeColor.WHITE ? new ResourceLocation("textures/entity/sheep/sheep.png") : new ResourceLocation("textures/entity/sheep/sheep_"+color.getDyeColorName()+".png");

        Minecraft.getMinecraft().getTextureManager().bindTexture(sheepTexture);
    }
```

if i understand correctly this code shloud only be executed for sheeps
however i get class cast exceptions when joining the world

Forge version:
1.12.2-14.23.0.2542

**Comment by AlexCouch** [comment]
For anyone that wants to find this I would suggest using this bit of code I wrote in the ModDef Cafe modding help channel (and bright humiliated me because I started asking questions before reading the chat prior which answered my questions haha jokes on you I already figured that)

```
public static void methodName(RenderLivingEvent event){
    if(event.getEntity() instanceof EntitySheep){
        EntitySheep sheep = (EntitySheep) event.getEntity();
        //do stuff here
    }
    //But not outside here, you want it for the sheep only
}
```

**Comment by williewillus** [comment]
@AlexCouch you don't want that, that's going to fire for both Pre and Post (and Specials)

**Comment by AlexCouch** [comment]
I'm talking to lukas right now and he gave me information that completely bunks my answer. I misinterpreted what he needed. He needs a new renderer for rendering a different texture for sheared sheep.

**Comment by diesieben07** [comment]
That's not how the event bus works, there is no dynamic type checking being done. For normal events (like `RenderLivingEvent`, not extending `GenericEvent`) only the raw type is looked at.
And even for generic events, you can only subscribe with the exact signature, there are no subclass checks, etc. being done.

**Comment by LexManos** [comment]
Yes, Forge's generic events are rahter limited they do not have the full extent of the generic typecasting for performance reasons.
And for type linking reasons.
There was a PR to add in full generic support but it failed to provide any performance statistics on its impact.
If someone else wants to try they are free to open a PR.
But this is not a bug, this is your misunderstanding of how the events are fired. We're been fairly clear about it.

**Comment by AlexCouch** [comment]
It's kinda hard to search through all the discussions and issues and whatnot to find any mentions on exactly the reasons for the design of the events. Quick funny story: this guy came into my discord server and was like "how can I get rid of events from minecraft. They take too much resource and they're useless" but I'm sure he's a troll but I digress. And going off topic.

Anyways, I think the events right now are fine the way they are. They get the job done without any kind of high cost to performance. If there was a better way of structuring the events so that they're more powerful then that'd be cool. I could do some research and see if I can dig anything up but if you guys can't find anything then what are the odds I'll find anything.

**Comment by m00nwtchr** [comment]
but wait if you cant use it like that then why does the RenderLivingEvent has a type argument?

**Comment by diesieben07** [comment]
It was added in [this commit](https://github.com/MinecraftForge/MinecraftForge/commit/5549b06f966d6129cd5b82e8328cea57a5c88c9e), most likely (judging by the commit message) as a way to get rid of the warning for the usage of the raw type `RenderLivingBase`. However this is not very helpful here, a wildcard should have been used instead.
