### ISSUE TITLE
forge mod loader optimization.

### ISSUE THREAD

**Issue by FengqianLi** [MinecraftForge/MinecraftForge#4530]
I profiled the process of forge loading mods and find that the code snippet in method public ModContainer build(ASMModParser modParser, File modSource, ModCandidate container) of ModContainerFactory.Java costs a lot of time. But as i know these codes is useless, could delete these codes?
![image](https://user-images.githubusercontent.com/1449173/32934653-7436e7c0-cba7-11e7-807f-63cdedcbb834.png)

the problem is the RE process in line 62.

**Comment by LexManos** [comment]
Claiming you profiled something and found a significant performance issue. Yet provides no actual numbers.... right.... anyways yes modloader mod style has been dropped for a while so we could probably remove the warnings. But now you’ve got me curious, so post some actual justification.

**Comment by FengqianLi** [comment]
Sorry for forgetting to post the profile result. 
I profiled with forge version 1.7.10 loading 8 mods
![image](https://user-images.githubusercontent.com/1449173/32942043-c16e89d8-cbc2-11e7-8e21-d14de4fb55a1.png)

as we can see, the regex.Matcher costs almost 2 seconds.

thanks

**Comment by ghost** [comment]
Shouldn't you profile with a more up to date version....?
1.7.10 has been unsupported for a long time now

**Comment by diesieben07** [comment]
1.7.10... 3 1/2 years old. _Highly_ relevant.

**Comment by mezz** [comment]
Please profile on 1.12 and check the timings for `ModContainerFactory#build`.

**Comment by FengqianLi** [comment]
Sorry for leaving some days because of holiday.

I profiled the 1.12, which has a better improvement.
running without mods costs 140ms and with 8 mods costs 171ms.

Here is the snapshot.

without mod:
![1](https://user-images.githubusercontent.com/1449173/33012931-448e8dc0-ce1d-11e7-81bf-c9f4478230cf.png)

with 8 mods (China Version official mods):
![2](https://user-images.githubusercontent.com/1449173/33012936-466e60b6-ce1d-11e7-91f3-c88da56bbdf4.png)


There are two things I'm wondering. One is how long it will cost if running with dozens of mods, and another one is how it performs for other versions.

**Comment by FengqianLi** [comment]
Also it seems that the RE matching is useless since version 1.7 according to http://www.minecraftforge.net/forum/topic/13871-forge-9111-minecraft-164/

**Comment by liach** [comment]
>China Version official mods

What's that?

**Comment by FengqianLi** [comment]
China version official mods are the mods provided by Netease which always loaded in minecraft China version.
http://mc.163.com/ you can see it here.

**Comment by liach** [comment]
See #4185 
This is **NOT** forge. Grab a clean install of forge on an "International" (Mojang) version (even a pirated version is better!) and make a profile out of it.

网易国服是魔改过的，看看#4185就知道了。你最好搞个真正的正版的然后安装forge测试，或者干脆盗版的都比网易魔改可靠。

**Comment by mezz** [comment]
In any case I think it is worth cleaning up, you have shown that it is not used at all.

**Comment by FengqianLi** [comment]
> This is NOT forge. Grab a clean install of forge on an "International" (Mojang) version (even a pirated version is better!) and make a profile out of it.

I know that they have modified minecraft. So I profiled both versions including mojang version with forge downloaded from forge website and also chinese version. 
In these two versions, this performance issues are same.

**Comment by mezz** [comment]
I have submitted a fix for 1.12 here:
https://github.com/MinecraftForge/MinecraftForge/pull/4540

**Comment by FengqianLi** [comment]
> I have submitted a fix for 1.12 here:
#4540

thanks mezz. Are you going to fix for other versions?

**Comment by mezz** [comment]
We think it may actually be used on 1.7.10, so I can't safely remove it there.
Since it does not seem to have a big impact on later versions, I am just cleaning it up on the latest.

**Comment by liach** [comment]
@FengqianLi You can ask netease to fix it though.

**Comment by covers1624** [comment]
I agree, ModLoader mods have been dead for ages now, there is no point in keeping the checking for their format. (Edit, Thanks chrome, i totally refreshed the page..)

**Comment by LexManos** [comment]
Its fine to remove in 1.12+, but 1.7.10 is still in the age of modloader mods. So having that check there is actually important. Its just something we never got around to removing. I'm still not convinced that it's actually a performance issue as it's just startup time. But whatever. As for Netease, we do not discuss them here, we also do not endorse using them in any way. There are other non-public issues related to them. So please stop the discussion on here.

**Comment by 3TUSK** [comment]
> One is how long it will cost if running with dozens of mods

@FengqianLi evoked my curiosity. 
For better or worse, I tested with [Age of Engineering](https://minecraft.curseforge.com/projects/age-of-engineering) on a Mid-2010 MacBook Pro (w/ macOS 10.13.1), using MultiMC 0.6.0-develop-1052 to auto-import, allocating 4G memory to jvm:
![image](https://user-images.githubusercontent.com/9113033/33091826-0feeda30-cead-11e7-9346-9fe83ac97c72.png)
``Matcher::find`` costs 6872ms in my profiling. 

I bet I can get similar (or proportional) result w/ FTB Present Direwolf 20 (1.12.2 ver.), but I don't really get time to conduct the actual experiment...

**Comment by zuorong-zhang** [comment]
> China version official mods are the mods provided by Netease which always loaded in minecraft China version.
> http://mc.163.com/ you can see it here.

"Chian version" or "China edition"?
