### ISSUE TITLE
enchanted item in hand

### ISSUE THREAD

**Issue by seema84** [MinecraftForge/MinecraftForge#4531]
Since a long time i have a issue with enchanted (in right or left hand) items and no shader.

Picture: https://picload.org/view/drlgrpgi/2017-11-18_16.06.21.png.html

With internal shader option or other shader i dont have this bug. Only with shader "off" it will show.

Forge Version: 14.23.0.2531 but this bug stay since the first version of forge with glsl/shader support.

**Comment by ghost** [comment]
Isn't this more an issue with optifine that forge? Presuming you're referring to optifine shaders..

**Comment by seema84** [comment]
It's just a combination of forge and optifine.

**Comment by TehNut** [comment]
Then it's an Optifine problem.
