### ISSUE TITLE
IllegalReferenceCountException on player join

### ISSUE THREAD

**Issue by LXGaming** [MinecraftForge/MinecraftForge#4533]
Running Forge 14.23.0.2546 (1.12.2)

I'm unsure if this is an issue with Forge or the mod everlastingabilities.

Error: https://pastebin.com/fAsHVFyU

**Comment by liach** [comment]
@LXGaming Close this, report to the mod author first.

**Comment by williewillus** [comment]
duplicate of #4523 , update to 2543+ to fix it

**Comment by liach** [comment]
> Running Forge 14.23.0.2546

@williewillus

**Comment by bs2609** [comment]
See https://github.com/CyclopsMC/CyclopsCore/pull/94.
