### ISSUE TITLE
1.10.2 Seems to depend on ForgeGradle:2.2-SNAPSHOT which implies building with java 1.6

### ISSUE THREAD

**Issue by artheus** [MinecraftForge/MinecraftForge#4542]
I have checked out the Branch 1.10.x.
I am trying to do some development on this, but it failed because of it wanting to build for java 1.6, thought it uses eg. vecmath:1.5.2 which is for 1.8+

Is this something you override in your build scripts?

To solve this locally, I had to clone the ForgeGradle repo at version 2.2 and substitute all occurrences of 1.6 that had to do with the java version, with 1.8. I changed the local version variable to `2.2.123-SNAPSHOT` and I ran `./gradlew install`
Then I set the dependency in build.gradle for my MinecraftForge checkout to my local version.

Now I can build. But it does not seem to be completely compliant with the way that you build it. Since I cannot run the jar with modpacks that usually run good.

**Comment by m00nwtchr** [comment]
just... update the forgegradle to 2.3?

**Comment by artheus** [comment]
@lukas2005 I tried this solution, but it gave me a bunch of exceptions when building. Therefore I did not continue on that path, as I assumed 2.3 were only for later versions of Minecraft.
Maybe it should be the solution, though.

**Comment by liach** [comment]
@artheus Add this to your `build.gradle`:
````gradle
sourceCompatibility = 1.8
targetCompatibility = 1.8

compileJava {
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
}
````
Then Java 8 would compile, and your mod can only be used by Java 8 users.

**Comment by artheus** [comment]
Sorry about being unclear. I am actually developing with the full forge source. So, I am not creating a mod.
This is specifically about the projects directory which is generated by ForgeGradle, and the build.gradle files in there gets the variables mentioned by @liach in the above comment, but all set to 1.6. This makes the build fail, due to parts of the source not being compliant with 1.6.

**Comment by liach** [comment]
Can you give a log from gradle?
