### ISSUE TITLE
[Request] More config annotations?

### ISSUE THREAD

**Issue by DevScyu** [MinecraftForge/MinecraftForge#4543]
There aren't all that many config annotations at the moment and it would be really useful to have them, such as the Sliders and buttons that cycle through arrays.

**Comment by DevScyu** [comment]
No one else thinks this should be implemented?

**Comment by canitzp** [comment]
You can create a pr. The config system isn't that complicated

**Comment by mainrs** [comment]
What exactly do you want to add annotations for? An example would be nice to have, as I do not really understand what you want to be honest :smile:

**Comment by DarkEyeDragon** [comment]
I could name a few:
- selection list (like FML's example config shows)
https://i.imgur.com/MKFzKrb.png

- buttons to cycle trough a set list (again like FML's example config)
https://i.imgur.com/7jEYdlW.png

Basically the entire FML example config redone to support the annotation system.

Sorry for reopening this but Seeing this getting closed right after i came to the same conclusion is rather upsetting. There's so much more potential for this!

**Comment by kierajreed** [comment]
There will be sliders soon - #5026 is adding them.
