### ISSUE TITLE
Item overrides are not inherited from parent json-models

### ISSUE THREAD

**Issue by MajorTuvok** [MinecraftForge/MinecraftForge#4554]
I have been working all day on the Problme,  that my ItemProperty Getter didn't seem to get called.
I attempted to use one parent json model to provide overrides for all sub-models (there are 10 different textures, and I only wanted to copy it once, so that if I ever had to change something I wouldn't have to take a look at each and every one of them).
But the debugger told me the getProperty override method would never get called!
So as a last Resort I just copied the override to one of the sub-models and retrieved a corresponding instance in-game: et-violà the getPropertyGetter(@Nonnull ResourceLocation key):IItemPropertyGetter Method was called! 

=>Maybe Item overrides  are not inherited from parent json-models? I suppose, that this behaviour is not wished => here's the Issue

**Comment by williewillus** [comment]
I think that's by design from vanilla. overrides are only active in the specific file they are declared in.

Changing it would be changing the vanilla model format so I'm not sure if we can do that

**Comment by MajorTuvok** [comment]
Maybe it is a vanilla bug  (Isn't the parent element supposed to provide inheritance for every other element?)
(I could not see any model, where vanilla explicitly tries not to inherit the overrides element...(e.g. I couldn't find an model with an overrides element which could be inherited))

**Comment by MajorTuvok** [comment]
(I mean they don't seem to inhert from models with overrides elements... (although I might have overseen one...))

**Comment by williewillus** [comment]
Not a bug, it just isn't implemented in vanilla

**Comment by MajorTuvok** [comment]
Ok, you guys know mor about vanilla mc...
If you say so...

**Comment by MajorTuvok** [comment]
more
