### ISSUE TITLE
Issue with Shapeless Recipes

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#4557]
If you have a recipe that has multiple Ingredients matching the same oredict, such as [this one](https://gist.github.com/Shadows-of-Fire/437e1b8907fb03d758b1c6a55246c9c3), the recipe will accept inputs as long as you have a single ItemStack with a stacksize >= to the number of that ore requested, whether or not they are in different slots, and a total number of ItemStacks == to the number of Ingredients as a whole.

That provided JSON recipe can be matched like this 
![](https://cdn.discordapp.com/attachments/254799354248822785/384459149510967296/unknown.png)
and that wheat can be replaced with any ItemStack, so as long as the stacksize of the planks remains >= 2.  It will not match if the stacksize hits one. 
![](https://i.imgur.com/xiJzcue.png)

This was tested on Forge 14.23.1.2554.  The matching error is present in both ShapelessOreRecipe and ShapelessRecipes.  ShapelessOreRecipe was tested via the provided JSON recipe, and I tested a ShapelessRecipes in code.

https://github.com/ForestryMC/ForestryMC/issues/1895 may be related.

**Comment by LexManos** [comment]
This is not only limited to Shapeless Ore recipes, this is an issue with Vanilla's solution to the shapeless recipe matching problem.
Example:
```json
{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
    {
      "item": "minecraft:stone",
      "data": 0
    },
    {
      "item": "minecraft:stone",
      "data": 0
    }
  ],
  "result": {
    "item": "minecraft:stone",
    "data": 1
  }
}
```
![](https://puu.sh/yu8YU/64604eb2e9.jpg)

I have solved this issue for now, by just forcing the recipes to use my 'non-simple' implementation of the matching algorithm.
