### ISSUE TITLE
[1.13] Update some Block methods from World->IBlockAccess params

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#4559]
Somewhat related to #4459.

There's a few functions added to `Block` that have `World` params, even though it's not really needed (e.g. for querying properties, where it's not needed to modify the state of the world).

Using `IBlockAccess` where possible allows for more flexibility in using these methods, as it allows for alternate interface implementations to be used.

As this would be a change to method signatures, I'm proposing it now so there's time for discussion before 1.13 hits, so it can make the breaking changes window then.

**Comment by mezz** [comment]
Sounds good to me. They're pretty inconsistent now and modders have to cast stuff awkwardly sometimes.

**Comment by williewillus** [comment]
This is still valid, though we'll have to do some more thinking about exactly what type things should be (with the whole reader/writer split)

**Comment by LexManos** [comment]
All Forge added methods are going to be audited.
But sufficent to day, they will be changed to one of the many interfaces IBlockAccess has been exploded onto.
It will however be to these Interface, NOT world directly. We shouldn't be doing that anymore.

**Comment by bs2609** [comment]
This is "in-progress" for 1.13 - it can probably be considered finished when patches have been ported and looked over.

**Comment by LexManos** [comment]
This should be considered done as I ported and changed all the Block functions.
