### ISSUE TITLE
Can Minecraft handle data from Bluetooth?

### ISSUE THREAD

**Issue by gawen1** [MinecraftForge/MinecraftForge#4561]
Our hardware can connect to our software system, and now we want to connect the hardware to Minecraft. But I have no idea now.

**Comment by liach** [comment]
http://minecraftforge.net/ 
go there for help instead

**Comment by williewillus** [comment]
Forge and Minecraft Java Edition run on a standard JVM, if you can find native bluetooth libs and java bindings for them you can do whatever you want
