### ISSUE TITLE
[1.12] Custom Tools are pretty limited

### ISSUE THREAD

**Issue by MetatableIndex** [MinecraftForge/MinecraftForge#4566]
Hello.

I am currently working on a mod where I add new tools to the game, as in different types of blocks/items but still Spade, Pickaxe, Axe, Hoe and Sword.

My issue is that for my custom tool materials to have their special properties, my tools are pretty limited and I cannot make them function with minecraft's attacks, as they can't even do the sweeping that any sword should have.

My suggestion: Some sort of function call on Player's "**attackTargetEntityWithCurrentItem**" on the held item, some sort of **hasSweeping** that by default returns false. This would be extremelly useful on my mod, as I would be able to override it to return true, and therefore allow my tools to have their sweeping...
This is the place where **flag3** is called, apparently, as it checks if the held item is a sword. If possible, the additional bool can added there as a "or". (itemstack.getItem() instanceof ItemSword **|| itemstack.getItem().hasSweeping()**)

Thanks in advance!

**Comment by AlexiyOrlov** [comment]
For clarification, do you use EnumHelper to create a custom tool material?

**Comment by MetatableIndex** [comment]
@AlexiyOrlov I am using the same logics as ToolMaterial, so yes I use enum.
This is the paradox though: In one side, I have much more access to modifying the tools, their properties and how they behave... but on the other hand, Minecraft doesn't apply basic logics to them. That means sweeping and repairing etc aren't done by default...

**Comment by MetatableIndex** [comment]
Hello? I believe this could easily be done...
Should I make a pull request?

**Comment by Eragonn1490** [comment]
Never hurts to try.

**Comment by mezz** [comment]
Feel free to make a PR, it is much easier to discuss that way. Also, it's much easier to see the pros and cons of adding a feature like this when the code for it is written with a small test mod to demonstrate it.  This seems to be basic, and pretty much along the same lines as many other PRs, so I think you should go ahead.
