### ISSUE TITLE
Permission system for capabilities

### ISSUE THREAD

**Issue by AlexiyOrlov** [MinecraftForge/MinecraftForge#4581]
Currently, `hasCapability` method only provides capability and facing parameters. I think it would be useful to have a parameter which defines an object that is attempting to access given capability, so a modder can allow or deny the access. Is this possible or in the works somewhere?

**Comment by Daomephsta** [comment]
What are some scenarios where you would want to allow or deny access depending on what is attempting to access the capability?

**Comment by LexManos** [comment]
No, this would just over complicate the system. On top of that people haven't agreed on a simple system to check boolean permissions.

**Comment by liach** [comment]
You can incorporate permissions in the method of capability interfaces.

**Comment by AlexiyOrlov** [comment]
@Leviathan143 For example, if a tile entity is "locked" by a player, the item extraction by hopper and similar machines would be denied, but allowed for that player.
`hasCapability` doesn't provide a context whether it's a player or a block accessing a capability.
@liach yes, I figured one can check 'simulate' flag and stack size in the 'extractItem'/'insertItem' of the item handler to determine what is using it, but it's not intuitive at all.
