### ISSUE TITLE
Entity.hasCapability() always calls getCapability()

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#4589]
See:
https://github.com/MinecraftForge/MinecraftForge/blob/83b7010ddfad3943d4039b13f3dc3523094f3f54/patches/minecraft/net/minecraft/entity/Entity.java.patch#L318-L324

As far as I understand it `hasCapability` is supposed to be a 'fast' check, so this implementation seems wrong. It's also inconsistent with other uses of `CapabilityDispatcher`.

Should this be removed, or is it needed for some reason?

**Comment by bs2609** [comment]
Looking back, it seems `TileEntity` had similar code originally, but it was removed by b71b96330111ee7abe7d72d11f429a207a8dbf7d.

**Comment by LexManos** [comment]
You're actually right, looking at the history this looks like my old first pass that I never got around to fixing/optimizing.
