### ISSUE TITLE
Forge 14.23.1.2577 - Can't open Chests

### ISSUE THREAD

**Issue by Dragnier** [MinecraftForge/MinecraftForge#4603]
Forge 14.23.1.2577

Can't open any chests for some reason.

Reverted to the previous version of Forge I was using (14.23.1.2566) and it was fine.

**Comment by LexManos** [comment]
Not reproducible, there was a change to how chests are opened to re-instate a vanilla bug that Forge has fixed for years. But apparently people like to bitch about it so we re-added the bug.
But I just verified everything works as 'intended'. Use the forums for basic debugging.

**Comment by Neb2566** [comment]
Well can confirm this issue aswell.. Rolled back forge, issue solved.

**Comment by HenryLoenwind** [comment]
-> http://www.minecraftforge.net/forum/topic/62078-cant-open-chests-with-forge-1122-142312569-and-higher/

**Comment by Roxforbraynz** [comment]
https://github.com/sp614x/optifine/issues/1071
Remove Optifine and wait for an update, or stay on an older version of Forge if your mods don't require the latest versions.

**Comment by liach** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/4584/files#diff-a11c1bfb3a77552647e2eac0c84e2ef4R27
