### ISSUE TITLE
[Crash]Updating forge from from 1.12.2-14.23.1.2562 to 1.12.2-14.23.1.2578 introduced a crash

### ISSUE THREAD

**Issue by ProgrammedSoul** [MinecraftForge/MinecraftForge#4605]
Hi, quick crash report. I recently updated forge from 2562 to 2578 version on my random personal modpack and that lead to a crash. Reverse forge back to 2562 will solve the crash. The crash is caused by ::

java.lang.NullPointerException: Initializing game
	at net.minecraftforge.client.model.ModelStateComposition.apply(ModelStateComposition.java:43)

Which I can find nothing online beside a forge pull request. Also since forge update caused the issue, it seems report the crash here is the right place to begin with. So here is my crash report:

[crash-2017-12-19_02.33.37-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/1570758/crash-2017-12-19_02.33.37-client.txt)

Thank you for your attention.

**Comment by malte0811** [comment]
Does this happen without Immersive Engineering? If it doesn't it is an IE bug I fixed 2 days ago, but don't ask me when the next build will be on CurseForge.

**Comment by ProgrammedSoul** [comment]
Yes removing IE will fix the problem. I'll try to find a updated version or just wait for Curse to update...

[Edit]No not really. It's just me forgot to press save after changing profile. Something else is still causing the crash. Here is the evidence:

[crash-2017-12-19_03.09.52-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/1570828/crash-2017-12-19_03.09.52-client.txt)

**Comment by liach** [comment]
> WARNING: coremods are present:
  JechCore (JustEnoughCharacters-1.12.0-2.2.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b130.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.2.6-37.jar)
  LoadingPlugin (Quark-r1.4-120.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.8.3-1.12.2-anarchy.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.5.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.1.43.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
**Contact their authors BEFORE contacting forge**

This belongs to the forums at least. Even if you report to the forums, you should remove as many coremods as possible.
