### ISSUE TITLE
1.12.2 forge 2578 and above... does not allow fire bows nor open vanilla chests.

### ISSUE THREAD

**Issue by jonabrv1965** [MinecraftForge/MinecraftForge#4613]
I downgrade to forge 2662 and the bows and chest work just fine again.

The bows glitch apply to all kind of bows (from vanilla to draconic evolution megabow).

The chests issue apply only to vanilla one. The rest of chests works just fine (from several mods, AE2, Draconic Evolution, etc...)

**Comment by josephcsible** [comment]
I can't reproduce this on Forge 2581.

**Comment by liach** [comment]
Someone please tag forum for this one

**Comment by LexManos** [comment]
Remove Optifine.
