### ISSUE TITLE
World#SpawnAlwaysVisibleParticle() is defaulting ignoreRange to false erroneously

### ISSUE THREAD

**Issue by jabelar** [MinecraftForge/MinecraftForge#4617]
In more recent versions, World now contains multiple "spawn particle" methods. There is a boolean parameter which is described as "ignoreRange" which is ORed with the ParticleType#shouldIgnoreRange() result and presumably (based on comments) does what is says.

However, one version of the spawn particle methods is called SpawnAlwaysVisibleParticle() which doesn't take the parameter but instead sets it to false. This is apparently backwards and in conflict with the comment for the method. 

For the most part this method isn't used -- it is only called by cloud particle (which I don't think is really actually used?). But I've seen modders attempt to use the method, and have looked at it myself, so figured it might be worth fixing.

**Comment by bs2609** [comment]
This isn't a method that's patched by Forge.

https://github.com/ModCoderPack/MCPBot-Issues/issues is the place to report issues with MCP-named methods.

**Comment by jabelar** [comment]
The problem isn't the name. The method is buggy. Is that something MCP fixes, or just the naming?

I'm fairly sure it is a bug because it is used for clouds but setting the ignoreRange to false.

**Comment by LexManos** [comment]
It may just be the name doesn't accurately describe what it does. Can you find the mojang bug report for this? If not then we're gunna call it just a badly named function.

**Comment by bs2609** [comment]
See the method description:
"Spawns particles that will always show regardless of the Video Settings -> Particles setting. Range restrictions still apply."
