### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#4618]
Use this issue to list all typos in documentation and anywhere else in the codebase.
I can fix them when there are a lot listed here.

**Comment by liach** [comment]
#3533

**Comment by jabelar** [comment]
Not exactly typos, but inconsistencies and misnamings that might be nice to fix:

- Material#setBurning() is misnamed because it sets the canBurn field. So grammatically it doesn't set it to actually burning but rather setCanBurn() to be consistent. 
- Block#silk_check_state field uses snake case instead of camel case
- EntityLivingBase#_combatTracker has a preceding underscore for some reason (I know some coding standards do this for non-final static fields, but this is final field...)
- EntityLivingBase#getIsInvulnerable() should really be just isInvulnerable() to match other "is" boolean getters in the Entity type classes.

**Comment by Daomephsta** [comment]
@jabelar Naming of vanilla methods/classes/fields is done by the MCP mappings. Issues with names of vanilla methods/classes/fields should go on the [MCP issue repo](https://github.com/ModCoderPack/MCPBot-Issues/issues).

**Comment by ALongStringOfNumbers** [comment]
There are probably some in here 
https://github.com/MinecraftForge/MinecraftForge/pull/3518
as this has been the post people refer to to tell people that single, typo fixing changes will generally not be accepted

**Comment by liach** [comment]
#3287

**Comment by mainrs** [comment]
The readme file contains the wrong main branch. It should be 1.12.x and not 1.10.x.

**Comment by liach** [comment]
@SirWindfield Same as #3533.

**Comment by mezz** [comment]
Adding this to the list as well since I'll be editing the readme: https://github.com/MinecraftForge/MinecraftForge/issues/2260

**Comment by liach** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/cfbcfeaf4b5d55d5fd1af70b84139ff0d205a9b8/src/main/java/net/minecraftforge/common/property/ExtendedBlockState.java#L101
Can use the predicate to check `isEmpty` instead of checking equality

Edit: More exactly, change this line to
```java
if (unlistedProperties.values().stream().noneMatch(Optional::isPresent))
```

**Comment by AEnterprise** [comment]
not exactly a typo but the documentation for the pre-init event still talks about registering things there with  the gameregistry, this should probably be updated to mention the new registry events instead

**Comment by modmuss50** [comment]
I doubt you are going to fix typo's in MC code, but ill post it anyway:

WorldSever.tickUpdates line 726 `throw new IllegalStateException("TickNextTick list out of synch");`

**Comment by bs2609** [comment]
Will link this draft of an update to the readme I made:
https://gist.github.com/bs2609/0ff0b4f31c86cfb2325260dd95748f79

**Comment by mezz** [comment]
Fixing vanilla typos is out of scope for this issue, yeah.

**Comment by ALongStringOfNumbers** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/3707

**Comment by bs2609** [comment]
Also might be nice to clean up the example mod in the MDK a bit, to show better practices.
Something like this: https://gist.github.com/bs2609/0f31067433ea9a9481e0339b01ad75fc

**Comment by ALongStringOfNumbers** [comment]
If the example mod would be updated, it might be a good idea to include comments in the pre-init ,init, and post-init to say what is initialized at what time.

**Comment by mezz** [comment]
The documentation for the pre/init/post events should have that information.

**Comment by mezz** [comment]
This is superseded by a PR, please move any discussion there: https://github.com/MinecraftForge/MinecraftForge/pull/4664
