### ISSUE TITLE
[RFC] Test Mod Guidelines

### ISSUE THREAD

**Issue by Daomephsta** [MinecraftForge/MinecraftForge#4620]
Recently there have been several PRs to cleanup and fix issues with test mods, such as #4616, #4477 & #4469, plus several more. The test mods fixed/cleaned up in those PRs are both old and new, so I think it would be beneficial to setup some guidelines to reduce the need for test mod cleanup PRs.

The current unwritten guidelines I am aware of are:

- Test mods should be minimal
- Each test mod should be contained in a single compilation unit
- Test mods should follow best practices at the time of their creation
- All test mods that affect gameplay should include a method of disabling them, and be disabled by default 

I'd be happy to write up the guidelines if I can get some feedback on exactly what they need to be, particularly from the Forge devs.

I'll be leaving this here for a week to see what comments are made, then I'll make a PR.

**Comment by mezz** [comment]
Sounds good. This could be included as a `readme.md` in the test mod directory.
Additional guidelines off the top of my head, may think of more later:
 * They should not crash when connected to a vanilla server, or a vanilla client.
 * It should be clear in the code what the tester needs to do in-game to use the test, optionally a short script can be included as a comment at the top of the file saying what to do and what to expect.
 * Test mods should not log anything when disabled or not in use.
 * Test mods should not create errors during startup except to demonstrate a specific error when they are enabled.

**Comment by jabelar** [comment]
Thanks for doing this. I was super tempted to disable a bunch of other mods when working on my latest PR. There is so much stuff from other mods cluttering up the creative tabs, as well as the console spam for missing textures and such.

With my first PR I made a test mod where I started from my typical starting mod code, but quickly found that even that was way, way too generalized. Test mod should have no cute registry wrappers, doesn't even need things like the lang file or texture assets, and so forth. So somehow emphasizing the sheer minimalism desired would be helpful to new contributors.

**Comment by Daomephsta** [comment]
I've written an initial draft, which can be found [here](https://gist.github.com/Leviathan143/44d4edd3ea49029dcbda02b694b9b40f).

**Comment by jabelar** [comment]
Looks good. Number 1 summarizes the other stuff I was going to suggest (readable field/method names and FML formatting template).

**Comment by kierajreed** [comment]
I have checked the code and this issue is still relevant because right now there are no guidelines about writing test mods, and there should be; and there is no README in the test mod directory.

**Comment by mezz** [comment]
@Leviathan143 could you submit your draft as a PR?

**Comment by Daomephsta** [comment]
@mezz Sure
