### ISSUE TITLE
GuiOpenEvent should be enhanced to pass in "old" GUI as well

### ISSUE THREAD

**Issue by jabelar** [MinecraftForge/MinecraftForge#4624]
Currently the GuiOpenEvent passes in only the "new" GuiScreen that is intended to be opened. However, at the point where the Minecraft#displayGuiScreen() fires the event it has just recorded whether any current screen was active. Here's the current code:
`        GuiScreen old = this.currentScreen;
        net.minecraftforge.client.event.GuiOpenEvent event = new net.minecraftforge.client.event.GuiOpenEvent(guiScreenIn);

        if (net.minecraftforge.common.MinecraftForge.EVENT_BUS.post(event)) return;

        guiScreenIn = event.getGui();
        if (old != null && guiScreenIn != old)
        {
            old.onGuiClosed();
        }
`

There are cases when it would be good to know what the previous GUI was, so it would be cool is the "old" value was also passed (in an immutable way) to the event.

**Comment by marvin-roesch** [comment]
Well, while it is technically mutable, `Minecraft#currentScreen` contains exactly that information. But a PR to include the old GUI in the event shouldn't take more than a minute :P

**Comment by jabelar** [comment]
Actually, I guess that is valid point. The screen is always called from within the Minecraft class on the client side, so it is safe to grab it again with Minecraft#currentScreen. So never mind, this isn't needed.
