### ISSUE TITLE
Should consider creating new server packet for attack damage sources instead of SPacketEntityStatus

### ISSUE THREAD

**Issue by jabelar** [MinecraftForge/MinecraftForge#4636]
I'm entering this on behalf of someone who ran into an issue trying to do a client-side mod to add visual effects based damage source type. Figured it was kinda interesting.

So, some people may not realize but damage source is mostly only used on the server side. When an attack happens, no damage source is sent to the client rather an SPacketEntityStatus packet is sent. That packet has simply a byte of information and so is very minimalistic. The only distinction it makes is for a couple damage types that vanilla client needs to know about such as FIRE, DROWN, and ENCHANTMENT_THORNS_HIT because there is visual effect associated with these. But information in the damage source such as the immediate and true sources or even many of the types is lost.

On the client side, the damage source is entirely re-instantiated in the Entity#handleStatusUpdate() method and defaults to DamageSource.GENERIC. If the status is one of the special codes, then the source type is updated. But in no case is any of the other information available.

So if you wanted to make a client-only mod that did some visual embellishment based on the damage source information, it is not available.

Since getting damaged is an infrequent occurrence, it really doesn't need the performance optimization of squashing it into a couple possible byte codes. So it would be cool if someone made a pull request where there was a separate packet type for full transfer of the damage source information, and client damage was handled separately from the entity status update including having things like the living attack event get that full damage source information.

Not a super critical issue, but could open up some interesting client-side modding opportunities.

**Comment by williewillus** [comment]
whatever comes out of this has to be 100% compatible with vanilla clients

**Comment by mezz** [comment]
I'm not sure it makes sense for Forge to support this kind of request, because (I assume) it can be done by a mod with a server-side component. Client-side modding is convenient but Forge is a compatibility layer, it's not really intended to be the server-side half of your mod.
