### ISSUE TITLE
Client misses Advancements

### ISSUE THREAD

**Issue by MissPotato** [MinecraftForge/MinecraftForge#4637]
https://i.imgur.com/pz0xzo2.png

For some reason, the client is not showing advancements until they've beaten one of the advancements contained in one of the tabs. This is also affecting vanilla Advancements. As displayed in the image. Only mod installed is forge version 1.12.2-14.23.1.2582.

**Comment by bs2609** [comment]
This is how it works in the vanilla game.

**Comment by MissPotato** [comment]
For real? That's dumb.
