### ISSUE TITLE
[1.13] Change IRenderHandler to an interface

### ISSUE THREAD

**Issue by josephcsible** [MinecraftForge/MinecraftForge#4640]
We should change [IRenderHandler](https://github.com/MinecraftForge/MinecraftForge/blob/cfbcfeaf4b5d55d5fd1af70b84139ff0d205a9b8/src/main/java/net/minecraftforge/client/IRenderHandler.java) to be an interface instead of an abstract class, so that lambdas can be used for it. This is a breaking change, so I'm opening this issue so that we remember to do this come 1.13 (otherwise I'd just PR it now).

**Comment by bs2609** [comment]
Would be also good to update the interface to pass through the render pass as well.

**Comment by diesieben07** [comment]
This can be done in a backwards compatible way, just make a new interface and let `IRenderHandler` implement it (it's an abstract class after all).

**Comment by liach** [comment]
@diesieben07 How about existing mods that uses this abstract class as a parameter in methods?

**Comment by diesieben07** [comment]
> How about existing mods that uses this abstract class as a parameter in methods?

What about them?

**Comment by williewillus** [comment]
@liach it's 1.13, we can make backwards incompatible changes

**Comment by liach** [comment]
@diesieben07 I thought you'd apply this change in 1.12. If that's the case, old mods cannot utilize the new interface, much like the `Teleporter` and `ITeleporter` change.

**Comment by diesieben07** [comment]
Why would they not be able to? They can require a minimum Forge version.

**Comment by liach** [comment]
`old mods` -> mods compiled before this change in 1.12

**Comment by diesieben07** [comment]
They would continue to use the abstract class, which now implements the interface and is thus compatible.

**Comment by liach** [comment]
Yes. I meant that new functional interfaces by mods from later forge cannot be utilized by those "old mods", so we should leave it for 1.13

**Comment by diesieben07** [comment]
Why would other mods need to utilize them? The methods in this class are only called by Forge.

**Comment by mezz** [comment]
1.13 should be in the next few months if I had to make a guess based on snapshots.
I think we should just wait until then. I can put this on my personal "1.13 todo" list.

**Comment by liach** [comment]
Ok @diesieben07 I am ending this discussion. :+1: for mezz

**Comment by Unnoen** [comment]
Issue can be closed, commit: https://github.com/MinecraftForge/MinecraftForge/commit/9245975955f533e291e27f748c1456e8a879e318
