### ISSUE TITLE
Beetroot crops don't break/drop when trampled

### ISSUE THREAD

**Issue by LXGaming** [MinecraftForge/MinecraftForge#4643]
When you jump on the farmland block it will change to dirt and any crops on top will break.
Beetroot crops don't break when the farmland block changes to dirt.

No mods were present on the server during testing.

Testing on the following:
- forge-1.12.2-14.23.1.2582
- forge-1.12.2-14.23.1.2581
- forge-1.10.2-12.18.3.2511

![Image](https://i.imgur.com/qmvo3cq.png)

**Comment by mezz** [comment]
Thanks for the report!
Confirmed, and confirmed this is not a vanilla bug.

**Comment by KnightMiner** [comment]
Looks like an easy fix, Block is just missing from the getPlantType patch in BlockCrop. I'll have a PR shortly unless its easier for you to just commit directly
