### ISSUE TITLE
Minecraft GuiButtonImage colors itself as hovered if any other ordinary GuiButton which is before it in the ButtonList get's hovered

### ISSUE THREAD

**Issue by MajorTuvok** [MinecraftForge/MinecraftForge#4657]
Hello I'have been trying to add an ImageButton in InitGui to the ButtonList after another simple TextDisplying GuiButton, but that didn't work.
After solving several faults I did ([in this forum topic](http://www.minecraftforge.net/forum/topic/62462-guiimagebutton-and-custom-imagebutton-doesnt-draw-correct-and-respond-to-a-different-indepent-buttons-hover-event/)) I noticed, that this strange drawing can only be reverted by either adding the ImageButton **BEFORE** the GuiButton or by overriding the draw Method and simply adding an 
`GlStateManager.color(1,1,1,1); ` statement to clear away any previous coloring. This may be considered as a fault of GuiButton which doesn't clear away it's coloring after drawing or of GuiImageButton which doesn't clear it away before drawing (like f.e. GuiButton does).

A corrected version of GuiButtonImage's drawing code can be found at the end of [the given forum topic](http://www.minecraftforge.net/forum/topic/62462-guiimagebutton-and-custom-imagebutton-doesnt-draw-correct-and-respond-to-a-different-indepent-buttons-hover-event/) (it simply adds `GLStateManager.color(1,1,1,1)`).

**Comment by MajorTuvok** [comment]
(Note that with "drawing itself as hovered" I mean drawing itself with an color tint like the other hovered Button)

**Comment by Cloudhunter** [comment]
While it is a bug, it's a bug in Vanilla code rather than Forge code.

Given the simplicity of the code, I'm not entirely sure it is worth fixing, at least on Forge's side - and it won't affect Vanilla as they never use a GuiButtonImage in a list - so I'm not sure how you'd go about reporting it to Mojang either.

**Comment by mezz** [comment]
A lot of Minecraft GUI things do not clean up their OpenGL state perfectly, it is definitely something you will have to look out for and work around when building GUIs that differ too much from vanilla ones unfortunately.

**Comment by MajorTuvok** [comment]
ok, so very well...
As this change seems to be too small to be removed, I'll just close it and work around it in the future...
Thank you guys anyway...
