### ISSUE TITLE
Rotation doesn't work for blocks with submodels anymore

### ISSUE THREAD

**Issue by josephcsible** [MinecraftForge/MinecraftForge#4659]
Originally reported as McJty/RFTools#1549

In Forge 2575 and below, the RFTools Modular Storage block (along with some other blocks) has its front side rendered on whichever side that its "facing" block state property is set to, as it should be. In Forge 2576 and above, this doesn't work correctly. Instead, it does this:
* If facing is west or east, the front side is rendered on the south face
* If facing is north or south, the front side is rendered on the north face
* If facing is up or down, the front side is rendered on the south face, but upside-down

I determined that this is because Modular Storage uses submodels. With the block normally, both the main model and the submodels are incorrectly rotated. When I remove the submodels, the main model is correctly rotated.

In particular, of the 5 commits that make up 2576, it's 9fdb79a that causes this, so pinging @boq.

**Comment by tomelfring** [comment]
See also #4650

**Comment by josephcsible** [comment]
I just tested #4629, and it fixes this, so once/if it's merged, this can be closed.
