### ISSUE TITLE
Provide a TE for getDrops

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#4674]
Currently, to access TE data in getDrops, you have to do some trickery involving deleting the block later than normal (see patches to BlockFlowerPot).

However, recently a nullable TileEntity argument was added in vanilla to harvestBlock, which means we can just pass it directly to getDrops (via a threadlocal similar to the silk check state).

This would make it easier/more intuitive to read TE data for getDrops instead of having to do tricks.

**Comment by KingLemming** [comment]
There's not any trickery needed. You have an IBlockAccess and a BlockPos. You can grab the tile yourself without issue - I do this all the time with CoFH stuff.

**Comment by KnightMiner** [comment]
I've had issues with this myself as well. Yes, you have world access in `Block::getDrops`, but the TE is almost always null. I've had to override [`Block::onRemovedByPlayer`](https://github.com/KnightMiner/Inspirations/blob/master/src/main/java/knightminer/inspirations/building/block/BlockEnlightenedBush.java#L117-L129) to change the order block breaking happens in order to make it work.

**Comment by williewillus** [comment]
When harvesting by digging, getdrops is called after the block (and TE) are already deleted from the world.

**Comment by HenryLoenwind** [comment]
KingLemming, that is exactly what "some trickery involving deleting the block later than normal" meant...

**Comment by raoulvdberge** [comment]
The current state is that it's a confusing mess.

**Comment by asiekierka** [comment]
@williewillus harvestBlock provides a correct reference to a TileEntity and you can forward it to a custom implementation of getDrops.

**Comment by JamiesWhiteShirt** [comment]
Looking at the related PR, this is scheduled to be fixed in 1.13.

For now, @McJty demonstrates an example workaround here: https://twitter.com/McJty/status/1002546886161596416

**Comment by HenryLoenwind** [comment]
That is the standard workaround everyone has been using for ages...

**Comment by JamiesWhiteShirt** [comment]
You might not find it useful. I left it here for those who might.

**Comment by raoulvdberge** [comment]
It's not a nice workaround, this change makes it much nicer.

**Comment by asiekierka** [comment]
Personally, I simply implement my own harvestBlock, as shown [here](https://github.com/CharsetMC/Charset/blob/1.12/src/main/java/pl/asie/charset/lib/block/BlockBase.java#L221-L241). It's the cleanest solution I've found, though coremods which modify harvestBlock might not like it . . .

**Comment by HenryLoenwind** [comment]
...and then people ask why implementing breaking a plant with a hoe is such a big deal in the Farming Station...
