### ISSUE TITLE
Please Change the Readme to a Markdown File for the MDK

### ISSUE THREAD

**Issue by AlexCouch** [MinecraftForge/MinecraftForge#4676]
It'd be so much better if the mdk readme was a markdown file by default. Most IDE's (if not, all) have a markdown editor and github has a markdown editor as well, and that's the main way of creating readme's. It's too small of a change to make a PR. This can easily be done by one of the main devs in like 5 minutes tops (if changes are made to the file).

**Comment by LexManos** [comment]
Why? The point is that it's a text file that doesn't need any use, or special tool, and is by default associated with something on all oses

**Comment by kierajreed** [comment]
Well, you can have both, they aren't going to cause any issues if both a `.txt` and a `.md` README exist.

**Comment by marvin-roesch** [comment]
@SkyHawkB, maintaining both a Markdown and a plain text file would lead to unnecessary duplication and inevitably to some desynchronization between the two.

The argument that most IDEs have a Markdown editor is invalid, in my opinion, as I know for a fact that in IDEA at least you'd have to install a plugin anyways, so it's extra effort for the user just to get some *slightly* nicer rendering.

**Comment by kierajreed** [comment]
The other way I've seen it done is an HTML file, as most people have a browser, but that's hard to maintain. I see what Lex meant about universality of a TXT so you can leave it at that and close this issue I guess.

**Comment by LexManos** [comment]
Ya, things in the programming world exist as plain text for a reason. It's the simplest and everyone can access it.
