### ISSUE TITLE
[1.12.2] Incorrect spawn spot after teleporting to another world

### ISSUE THREAD

**Issue by KorDum** [MinecraftForge/MinecraftForge#4677]
This problem actually for 1.11.2.
If client crashes with OutOfMemory on the teleportation to Nether (or End too) and connected to the server again later, then the player is in coordinates of portal in OVERWORLD, not coordinates / 8 for Nether or safe area for End.

In result players are in lava or void...

**Comment by bs2609** [comment]
https://bugs.mojang.com/browse/MC-102641

**Comment by KorDum** [comment]
27/May/16 oh...
