### ISSUE TITLE
There is no official way to get a list of the BiomeDictionary.Types

### ISSUE THREAD

**Issue by ChiriVulpes** [MinecraftForge/MinecraftForge#4684]
There is currently no official way to get a list of existing biome types (unless I'm blind). These are the current options that I've found:

- `BiomeDictionary.Type.byName` is a private field that maps biome types with their names. I could use `setAccessible` to use it anyway. (this is what I'm currently doing)

- `BiomeDictionary.getTypes` returns only types that match a given biome. I could loop through the results for every biome returned from `getBiomes` to build a map on my end.

- `BiomeDictionary.Type.getType` returns an existing type, or a new one, if it doesn't exist. I need to use the type if it exists, but do nothing if it doesn't. So new types are created that won't ever be used.

None of these are a great solution. It would be nice if there was a method to return a map of the current biome types (or even just making `byName` public), so that I don't have to jump through these hoops.

**Comment by mezz** [comment]
Makes sense. Feel free to make a PR to add a method like this:
```java
public class BiomeDictionary {
//...
    public static Collection<Type> getAllTypes()
    {
        return Collections.unmodifiableCollection(Type.byName.values());
    }
//...
}
```
What do you need all the types for?

**Comment by ChiriVulpes** [comment]
I would think it would make more sense to be `BiomeDictionary.Type.getAll` instead of `BiomeDictionary.getAllTypes`, simply because all current `BiomeDictionary` methods are in relation to biomes, while all static `BiomeDictionary.Type` methods (just `getType`, at the moment) are in relation to types.

I made a PR with it this way. Let me know if I should just do exactly as you have it, tho.
