### ISSUE TITLE
Provide an API for transforming ClassNode instead of raw byte[]

### ISSUE THREAD

**Issue by GUIpsp** [MinecraftForge/MinecraftForge#4687]
Quite a few mods start off their bytecode transformations by converting the classes to the ASM Tree API. This can take a non-trivial amount of time. Forge can convert to the tree or to byte[] as necessary in order not to break old code.

**Comment by LexManos** [comment]
The new re-write of the launch wrapper will be in this form. I'm not going to go into specifics until @cpw finishes the first iteration of it. But this is one of the many reasons why we need/are making a new wrapper.

**Comment by GUIpsp** [comment]
OK, where can I get some details on the new wrapper? Also I think this is a small change that will be impactful and backwards-compatible enough to be worth doing.
