### ISSUE TITLE
[Help Request] Custom Forge Version ID

### ISSUE THREAD

**Issue by CDAGaming** [MinecraftForge/MinecraftForge#4695]
This isn't an issue so much as it is just a help request. I have made modifications to Forge for my own build, however each time I build it, the version comes back as 14.23.1.0.

What I'd like to do is have the Version ID of my Build still matching the number on Jenkins (14.23.1.2601). Is there a way to achieve this or perhaps set the ID locally

**Comment by CDAGaming** [comment]
Closing. Put in a patch for my build to do this.

**Comment by mezz** [comment]
For anyone else with the same issue, the solution is to set `ForgeVersion#buildVersion` to a high number like 9999, or set the `BUILD_NUMBER` system property on your computer to something high like that to simulate the Jenkins build machine.

**Comment by CDAGaming** [comment]
Patch Link: https://github.com/CDAGaming/MinecraftForge/commit/f188308d0cb05781010b5dae24e6e00562239b4d

**Comment by LexManos** [comment]
@CDAGaming You're doing it wrong, there is no need for any 'patch' or code modification.
All you do is literally set the BUILD_NUMBER environment variable when running the build.
That's the entire point of this...
Also... Looking at your branch.. all I can think is... why....
