### ISSUE TITLE
Vanilla-representing Fluid objects return incorrect unlocalized name

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#4712]
Expected:

FluidRegistry.WATER.getUnlocalizedName() => "tile.water" // has a valid localization key "tile.water.name"

Actual:

FluidRegistry.WATER.getUnlocalizedName() => "fluid.tile.water" // does not have a localization key

**Comment by jabelar** [comment]
Interestingly, for some reason FluidRegistry seems to be bypassing the unlocalized name. It has:
`    public static final Fluid WATER = new Fluid("water", new ResourceLocation("blocks/water_still"), new ResourceLocation("blocks/water_flow")) {
        @Override
        public String getLocalizedName(FluidStack fs) {
            return I18n.translateToLocal("tile.water.name");
        }
    }.setBlock(Blocks.WATER).setUnlocalizedName(Blocks.WATER.getUnlocalizedName());

    public static final Fluid LAVA = new Fluid("lava", new ResourceLocation("blocks/lava_still"), new ResourceLocation("blocks/lava_flow")) {
        @Override
        public String getLocalizedName(FluidStack fs) {
            return I18n.translateToLocal("tile.lava.name");
        }
    }.setBlock(Blocks.LAVA).setLuminosity(15).setDensity(3000).setViscosity(6000).setTemperature(1300).setUnlocalizedName(Blocks.LAVA.getUnlocalizedName());
`
I think what should happen instead is that those overrides of the localized name should be deleted and the Fluid#getUnlocalizedName() needs to handle these special cases for vanilla. I think check for those two types and return the vanilla unlocalized name would do it.

**Comment by asiekierka** [comment]
No. The issue is simple. getLocalizedName(FluidStack) is being overridden - overriding getUnlocalizedName() instead will work fine.

**Comment by jabelar** [comment]
No. The unlocalized name is adding the "fluid." which you don't want. That is the root problem. They added the override to the localized name to fix that problem but that is the wrong fix since someone might still try to get the unlocalized name (as happened to the original poster).

This code is wrong unless it handles water and lava as exceptions:
`    /**
     * Returns the unlocalized name of this fluid.
     */
    public String getUnlocalizedName()
    {
        return "fluid." + this.unlocalizedName;
    }
`

Fix that and then you don't need to override the localized name.
