### ISSUE TITLE
Big Memory Leak issue on my Minecraft Forge Server. Help?

### ISSUE THREAD

**Issue by Spike5032** [MinecraftForge/MinecraftForge#4715]
Issue
https://i.gyazo.com/64abfa2b2cbd9e95113d8669e0258c83.png

Mods
https://i.gyazo.com/b751c05bf25d88759a156ecef8a9df08.png

This is a picture of the issue. It constantly is leaking and I need to find what is causing it.

If you require anything else let me know.

**Comment by TehNut** [comment]
Use the forums for tech support.
