### ISSUE TITLE
Forge Not Getting Offhand Stack Properly 1.12.2 BlockPlaceEvent

### ISSUE THREAD

**Issue by jredfox** [MinecraftForge/MinecraftForge#4718]
Issue: forge stack != stack that is being placed but, it is for the main hand and only the main hand. I also tried player.getActiveItemStack() and that returned null.  **same code works perfect for the main hand not the offhand and my code is suppose to get the hand and stack from the active hand from the forge event not my code**

Code:
https://pastebin.com/SBQamUDB

Screenshot of Stack:
https://imgur.com/qp8Xwcn
    	
Output:
[14:31:29] [Server thread/INFO] [STDOUT]: [com.EvilNotch.silkspawners.MainJava:read:142]: Stack:minecraft meta:0 null

I noticed the hand didn't return null so I printed out the stack string id it just said minecraft, meta is 0 which happens to be the only thing right and then nbt says null when I have 9 tags. This bug is preventing me from doing stuff in block place event for silkspawners which I need the actual stack if it's a mob spawner, the nbt tags stuff like that **it works perfect in main hand**

**Comment by williewillus** [comment]
use the forums or IRC for basic modding support

**Comment by jredfox** [comment]
this isn't modding support it's an issue the stack from forge is returning an invalid stack for the **hand** I posted code as proof.

this is forge's code at fault not mine. **In the event forge is returning an invalid itemstack that I can do nothing with if and only if it's the off hand I was showing code as proof.** Also read what it says I was proving that it was forges fault not my own code.

**Comment by Choonster** [comment]
`EntityLivingBase#getActiveHand` only returns a valid result when the player is actively using an item (e.g. eating food, blocking with a shield), which won't be the case when they're placing a block.

Use `BlockEvent.PlaceEvent#getHand` to get the hand that the player used to place the block.
