### ISSUE TITLE
Initial skylight and relighting area loaded checks disagree (vanilla, performance)

### ISSUE THREAD

**Issue by Player3324** [MinecraftForge/MinecraftForge#4723]
Chunk.checkLight() is responsible for computing the skylight values in a newly generated/decorated chunk for locations that aren't directly exposed to the sky. It does so by calling World.checkLight(BlockPos) for each xz column in the chunk.

Chunk.checkLight() requires the 9 surrounding chunks to be loaded to do anything (+- 1 chunk).

World.checkLight(BlockPos) however requires +- 17 blocks from the operating position to be loaded, which at the extremes equals (0-17) >> 4 = -2 .. (15+17) >> 4 = +2 chunks.

If World.checkLight detects that the operating area is not fully loaded, it'll return false, which in turn causes Chunk.checkLight to abort the light initialization to be retried the next tick.

Since World.checkLight only checks +- 17 blocks from its current position and Chunk.checkLight calls it for all 256 xz positions in a chunk, light values for almost all positions may have already been computed before it bails out to start over another time.

This is a very significant waste of time that continues indefinitely until the required adjacent chunks happen to be loaded by some means. I've observed < 10 TPS for over 20 minutes on a fresh Twilight Forest world, 90% of the server thread CPU time were spent in Chunk.checkLight.

There are two ways to fix this:

a) Require a larger area to be loaded before Chunk.checkLight does something:

Replace `blockpos.add(-1, 0, -1), blockpos.add(16, this.world.getSeaLevel(), 16)` with `blockpos.add(-17, 0, -17), blockpos.add(32, this.world.getSeaLevel(), 32)` in Chunk.checkLight().

This shouldn't have any side effects besides no longer doing the partial light updates. World.checkLight shouldn't abort anymore.

b) Lower the range of World.checkLight to stay within +- 1 chunks, adjusting the area check:

Replace the three instances of 17 with 16 in World.checkLightFor(EnumSkyBlock, BlockPos).

The real range a light source can affect is only 14, but Minecraft recomputes light in a larger range as part of its "deglitching" routine that fixes incorrect light values. While 14 should be sufficient for a light update in a perfect world, decreasing the range from 17 severely lowers the effectiveness of repairing the many inaccuracies MC's light propagation leaves behind.

I recommend approach a.

**Comment by mezz** [comment]
Fixed in https://github.com/MinecraftForge/MinecraftForge/pull/4729
