### ISSUE TITLE
Game crashes when opening the controls menu

### ISSUE THREAD

**Issue by strikerrocker** [MinecraftForge/MinecraftForge#4730]
This bug can replicated by instantialising a keybind. But not registering it. This apparently crashes the game. 

The following code in clientproxy causes this . 
public static final KeyBinding bauble = new KeyBinding("key.vt:zoom", KeyConflictContext.IN_GAME, Keyboard.KEY_Z, CATEGORY);

    public void registerKey() {
        if (vt.baubles) ClientRegistry.registerKeyBinding(bauble);
    }

**Comment by LexManos** [comment]
This, amung many other things, is why statically initializing things is BAD. Don't do it.
