### ISSUE TITLE
Certificate fingerprint validation for core mods

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [MinecraftForge/MinecraftForge#4733]
Annotated class mods support fingerprint validation using the `certificateFingerprint` annotation field and `FMLFingerprintViolationEvent`, but this is lacking for core mods.

Since the guidelines require core mods jars to be signed, it would make sense for `IFMLLoadingPlugin`s to have a certificate fingerprint validation mechanism.

**Comment by LexManos** [comment]
Coremods have and will coremod that out so there is no point in doing that.
Only practical way to do it would be to scan the jar and not load if it finds any violations data side.
But that isn't going to be in place until the LaunchWrapper re-write.

**Comment by TechnicianLP** [comment]
bump
