### ISSUE TITLE
Possible key collision in net.minecraft.network.datasync.EntityDataManager

### ISSUE THREAD

**Issue by tyra314** [MinecraftForge/MinecraftForge#4743]
After digging a bit into the crash reported here: https://github.com/Alex-the-666/Ice_and_Fire/issues/460
I had a look at the method `createKey` from the class `net.minecraft.network.datasync.EntityDataManager`. From what I understand, this method shall generate a unique id, which is used to transform a `DataParameter<T>` into an integer used as the key in the `EntityDataManager.entries` field. However, if I understand the code correctly, then the generated integers aren't necessarily unique. Collisions can happen if two different classes share a common base class and this base class has been added before adding the two classes. As all entities inherit from `net.minecraft.entity.Entity` and this class already calls the `createKey `method, one can assume that many keys will collide.

In fact, the original crash report indicates that two mods using the same internal key, as Fire and Ice never added a `Byte `to the `EntityDataManager`. Personly, I think the whole method is over-engineered and should merely return the value of a static int variable after increasing it by one.

**Comment by williewillus** [comment]
The only way you get conflicts is if the classloading order is not the same between the server and client, or a mod tries to add entries for entities that it doesn't own. If you read the code closer, it in fact does respect the class. I suspect the crash you are getting is because another mod is trying to add entries for entities it doesn't own, which manifests as a crash in your mod.

The system isn't perfect,  but Forge isn't in the business of reengineering vanilla systems for no reason, not to mention changing it would completely screw network compat with vanilla clients

**Comment by tyra314** [comment]
Thank you for taking the time, but after having a second look, I'm still convinced that the code is indeed wrong.

Here is the code snippet (I stripped some casting and Java-Integer voodoo):
```
int j;
if (NEXT_ID_MAP.containsKey(clazz))
{
    j = NEXT_ID_MAP.get(clazz) + 1;
}
else
{
    int i = 0;
    Class<?> oclass1 = clazz;

    while (oclass1 != Entity.class)
    {
        oclass1 = oclass1.getSuperclass();

        if (NEXT_ID_MAP.containsKey(oclass1))
        {
            i = NEXT_ID_MAP.get(oclass1) + 1;
            break;
        }
    }

    j = i;
}

// check if j < 254
NEXT_ID_MAP.put(clazz, j);
return serializer.createKey(j);
```
For simplicity, let's say, only `Entity`, `ModAEntity` and `ModBEntity` exist. `ModAEntity `and `ModBEntity` directly inherit from `Entity`. And `createKey()` is called six times for `Entity`, once for `ModAEntity` and once for `ModBEntity`, in that order. 

What happens during each call:

1. The `NEXT_ID_MAP` is empty. Therefore the else branch is taken, and the while condition is false. The generated key is 0.
2. The key `Entity.class` is contained in the map, the then branch is taken. The generated key is 0+1=1.
3. Like 2: The generated key is 2.
4. Like 2: The generated key is 3.
5. Like 2: The generated key is 4.
6. Like 2: The generated key is 5.
7. The key `ModAEntity.class` is not in the map. Therefore the else branch is executed. `oclass1` is set to `ModAEntity`. The while condition is not false yet. `oclass1` gets set to the superclass of `ModAEntity`, which is `Entity`. The map does contain the key `Entity.class`; its value is 5. i=5+1=6. We break out of the while loop. The generated key is 6.
8. The key `ModBEntity.class` is not in the map. Therefore the else branch is executed. `oclass1` is set to `ModBEntity`. The while condition is not false yet. `oclass1` gets set to the superclass of `ModBEntity`, which is `Entity`. The map does contain the key `Entity.class`; **its value still is 5**. i=5+1=6. We break out of the while loop. **The generated key is 6.**

If I'm not missing something fundamental here, the code does not work.

**Comment by diesieben07** [comment]
Yes, in both cases the generated key will be 6. However, since `ModAEntity` and `ModBEntity` form completely separate class hierarchies this is not a problem. Data for `ModAEntity` will never be sent to something that is also a `ModBEntity` and vice versa. There is no data collision.

**Comment by williewillus** [comment]
^, if there were data collisions, vanilla would be crashing all over the place, but it hasn't for the last 4 major versions (this was introduced in 1.9)

**Comment by tyra314** [comment]
Okay, I get it, thank you.

And here is the root cause: https://github.com/Daveyx0/PrimitiveMobs/issues/53
