### ISSUE TITLE
minecraft 1.10.2 crashing when crafting a crafting table

### ISSUE THREAD

**Issue by DerpyNinja476** [MinecraftForge/MinecraftForge#4754]
hello, i have a problem with forge that when i join my single player world on a custom modpack, when i try to make a crafting table, the third piece of wood that i place in the crafting grid, the whole game freezes and crashes.

i couldnt find anything in the logs when i looked myself, but maybe a professional could look through it.

https://pastebin.com/FdKkawN4
https://pastebin.com/UG953bNR

**Comment by kierajreed** [comment]
use the forums

**Comment by DerpyNinja476** [comment]
Ok sorry i didnt know where to post this since this was such a broad issue, could you give me the link to the forums

**Comment by DerpyNinja476** [comment]
Never mind i found it sorry
