### ISSUE TITLE
Suggestion- Universial Fluid XP

### ISSUE THREAD

**Issue by CTH999** [MinecraftForge/MinecraftForge#4755]
So, you now have Forge Energy, but a lot of mods (Such As [Thermal Foundation](https://minecraft.curseforge.com/projects/thermalexpansion) and [Industrial Forgoing](https://minecraft.curseforge.com/projects/industrial-foregoing?gameCategorySlug=mc-mods&projectID=266515)+ Open Blocks+ More I don't know about)

So, what about a universial Liquid XP, it would make mods much more compatible, which is what forge is all about.

However, this is just a suggestion!

**Comment by KingLemming** [comment]
I don't actually think this is a good idea, for the record.

**Comment by CTH999** [comment]
Why? (Is it due to the code, or another reason?)

Also, maybe other things could be made universal.

**Comment by KingLemming** [comment]
Forge isn't in the business of adding concrete things to the game. RF is a capability. Fluids are capabilities. Those are both systems, not things.

This is a thing and not a system. Anytime you put something like this in Forge, it potentially stifles modder creativity, by making it so that there is a "one true way." And for Fluid XP, there shouldn't necessarily be that.

**Comment by CTH999** [comment]
Ok, I understand. However, why did you add in FE? Just wondering. I do see exactly what you mean though!

**Comment by ShetiPhian** [comment]
Adding stuff like this can quickly get out of hand also.
Where would you draw the line? for each thing you accept it becomes harder to decline something else.

Better off sticking with systems.
[The universal bucket was an exception as it directly supports a system.]

**Comment by CTH999** [comment]
Ok! I compleley understand! Would it be usefule, Yes.
Is it a good idea? No!

Thanks For explaining!

**Comment by HenryLoenwind** [comment]
Doesn't sound that useful. There's a common fluid name ("xpjuice") with a commonly agreed ratio (20:1) and that works. Any mod that wants to do something else can do so by using another fluid name with another ratio.

However, `milk` would be really interesting. ;)

**Comment by CTH999** [comment]
ok. fair enough! It's just that even if they have the same ratio, they aren't ore-dict. However, I completely agree with you!

**Comment by HenryLoenwind** [comment]
The fluid name *is* an "oredict"-like mechanism...

**Comment by CTH999** [comment]
ok...

The thing is the essence and EX-Thing from TE Is the same ration, just not compatible. However, you're right!
