### ISSUE TITLE
LayerEntityOnShoulder hard-coded for Parrot

### ISSUE THREAD

**Issue by jabelar** [MinecraftForge/MinecraftForge#4756]
I'm logging this after seeing this thread: http://www.minecraftforge.net/forum/topic/63146-1122-rendering-custom-shoulder-entity/

Maybe I'm missing something and there may be a nice solution already?

Basically the LayerEntityOnShoulder class has a lot of hard-coding for Parrot. If you want to make a custom shoulder entity it seems you have to use the RenderPlayerEvent and replace the entire player renderer with a version that has a more flexible version of this layer.

It seems it would be nice to create a hook to make this more flexible. One fix might be for LayerEntityOnShoulder to check for instanceof EntityShoulderRiding instead of exact match with parrot.

**Comment by HenryLoenwind** [comment]
That is just a normal `LayerRenderer`, simply fetch it and wrap it into your own LayerRenderer that diverts to your code if it founds your entity and passes on to the wrapped on if not.

Just make sure you (1) `extend` LayerEntityOnShoulder so mods that run after you can find your renderer when looking for the shoulder renderer and (2) call the wrapped one (not super) in case you wrapped another mod's shoulder renderer.

See https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-base/src/main/java/crazypants/enderio/base/handler/darksteel/UpgradeRenderManager.java#L53 and https://github.com/SleepyTrousers/EnderIO/blob/master/enderio-base/src/main/java/crazypants/enderio/base/item/darksteel/upgrade/elytra/CapeFilterLayer.java#L24

**Comment by jabelar** [comment]
Yes, I understand that you can replace the layer renderer easily, and if you do it smartly can make it likely to be compatible with other mods. But I suspect that entities on shoulders will be of reasonable interest to modders so why not make it flexible to automatically accept all EntityShoulderRiding?
