### ISSUE TITLE
Add config option to display what mod is currently running during world generation.

### ISSUE THREAD

**Issue by border999** [MinecraftForge/MinecraftForge#4757]
This would be very useful for conflict testing when it comes to mods that alter how a minecraft world is generated. Cubic Chunks being my primary example.
Since it alters the entire chunk system, being able to see what mod is trying to add to the world when it locks up would make debugging and improving compatibility of the mod exponentially easier.

**Comment by mezz** [comment]
This is a good suggestion but I can't think of another mod that changes these things quite as dramatically as Cubic Chunks. I think it would be a better idea to ask them to add this config option. Anything added by Forge directly would be of limited use and might be overridden with code from Cubic Chunks anyway, they would still need to implement support for it.

**Comment by border999** [comment]
Already suggested on their end

**Comment by LexManos** [comment]
Not feasible. Best thing you will get is for cubic chunks to dump a stack trace when things lock up. Nothing on our end we can do as there is no way to tag what mod is running when.

**Comment by CTH999** [comment]
Well, there probably is...

Just don't think you want to re-write all of forge for 1 suggestion, eh?

**Comment by mezz** [comment]
That goes without saying, really. So please don't. :P
