### ISSUE TITLE
2^64, not 2^32!

### ISSUE THREAD

**Issue by CTH999** [MinecraftForge/MinecraftForge#4760]
So, from this suggestion right [here](https://github.com/Ellpeck/ActuallyAdditions/issues/1033), I found out that forge only supports up to the 32-bit integer limit. (Which, btw, explains why Draconic evolution uses the RF Api)

So, my suggestion is this: Make it to where the Forge Energy can support up to the 64-bit integer limit instead of the 32-bit integer limit.

However, that's just a suggestion!

**Comment by KingLemming** [comment]
RF also only supports 32 bit. Forge Energy is simply a capability adaptation of that.

32 bits is more than enough and anything going over that is using larger numbers just because. There's no need for 64 bits, period.

**Comment by CTH999** [comment]
However, sometimes there is. (I.E. Draconic Evolution. Since they had to use 64-bit, they had to put it in themselves. If it's able to do 2^64, then it would be better for other mods that want to use the 64-bit integer, but want to use FE, which, right now, can only go to the 32-bit integer limit. However, this is just a suggestion.

**Comment by LexManos** [comment]
We've thought about this and honestly there isnt a real good reason for the overhead just because people like big numbers.
Machines are the like are all fine working in 32-bit per tick, you can deal with more with your own special stuff.
Things like Tesla just want to be special because big numbers are cool(tm).

**Comment by CTH999** [comment]
Ok, that seems logical! Thanks!
Have a good day!

**Comment by HenryLoenwind** [comment]
Only 64 bits? And what should I do to fill my AbsurdSuperDuperSagMill that uses 7900000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000.00000000000000000000008947 RF/t?

**Comment by Madsthunder** [comment]
@HenryLoenwind At that point you'd need to rebuild MC and forge to work on a quantum computer.
