### ISSUE TITLE
playShoulderEntityAmbientSound client crash with 1.12.2 Forge

### ISSUE THREAD

**Issue by johnfriedrich** [MinecraftForge/MinecraftForge#4764]
This crash is not very common and due to that, almost impossible to reproduce.

This crash affects some mc networks, not just us.
Things we all have in common:

BungeeCord 1.12.2 or HexaCord 1.12.2, not older than a month.
A spigot hub. Can be 1.11.2 or 1.12.2, the version doesn't seem to be important
A Sponge-Forge 1.12.2 server with either Pixelmon or Direwolf20 installed.

A 1.12.2 Forge client with either Pixelmon or Direwolf20 installed

How to reproduce:
Login via BungeeCord on your spigot lobby server.
Now use /server pixelmon or /server direwolf to switch to pixelmon or direwolf
(Try to be lucky)

We are not sure if SpongeForge is the issue, but we don't think so as it's a client crash and we don't get an error serverside. We can't really test without Sponge,as this error is not occuring that often.

Now, your client can crash with a small chance with the following error:
EntityPlayer.func_192028_j
https://pastebin.com/CcywjKzt
https://pastebin.com/P5ASABrU

We weren't able to discover a pattern in these crashlogs.

Here are some guesses:
![1](https://image.prntscr.com/image/kHyLgBO2SKOGKzQYsCjfxw.jpeg)
![2](https://image.prntscr.com/image/_h-enSr_SVupyCmJM61fug.jpeg)

**Comment by kierajreed** [comment]
use the forums

**Comment by williewillus** [comment]
also, this is not a forge issue at all. The posted code snippet is exactly the same logic as vanilla has.

**Comment by johnfriedrich** [comment]
I know that this is pretty much vanilla if you look at the stacktrace. However I have never seen this crash with vanilla Minecraft 1.12.2 at all

**Comment by williewillus** [comment]
but the logic is completely in vanilla, and forge has no business modifying entity ID tags. I'd chalk it up to a buggy mod.

**Comment by johnfriedrich** [comment]
I thought that aswell, but it happens with just Pixelmon installed. And Pixelmon does not touch Parrots or shoulder entities at all

**Comment by bs2609** [comment]
`NBTTagCompound#getString` doesn't return null, it defaults to an empty string. The more likely thing to be returning null is `EntityList.getKey`.

**Comment by williewillus** [comment]
well, does it happen without pixelmon (pure forge)? if so, there's your problem :P

**Comment by johnfriedrich** [comment]
It does happen with 1.12.2 Direwolf20 aswell. (Pixelmon is not included in this pack)
That pretty much says that Pixelmon is not the cause.
Also bungee seems not to be the cause:
https://github.com/SpigotMC/BungeeCord/issues/2350

You say that EntityList.getKey is likely null? Can bungee somehow interfere with that?
