### ISSUE TITLE
Conversion 1.7.10 > 1.12.2 World Bug

### ISSUE THREAD

**Issue by jredfox** [MinecraftForge/MinecraftForge#4768]
Issue: 1.7.10 forge doesn't convert to 1.12.2 forge
Versions 1.7.10: 1.7.10-Forge10.13.4.1558-1.7.10,1.12.2-forge1.12.2-14.23.2.2611
Screenshot: https://imgur.com/IpASVwb

**Forge Specified in the screenshot that it can't convert < 1.7.10 well it is 1.7.10.**

Tests
Vanilla World 1.7.10 > 1.12.2 Vanilla SUCCESS
Forge World 1.7.10 > Vanilla 1.12.2 SUCESS
Forge World 1.7.10 > Forge 1.12.2 FAIL

**Comment by LexManos** [comment]
Yes, we removed some of the intermediate steps.
Go through 1.8.9 and 1.10.2 before doing 1.12.2.
As described by the error message -.-

**Comment by jredfox** [comment]
**Well change the message** to world is too old rather then saying world predates 1.7.10. Or world is older then 1.8 forge or older then 1.7.10 vanilla something like that
