### ISSUE TITLE
ICrashReportDetail masks StackOverflowErrors

### ISSUE THREAD

**Issue by josephcsible** [MinecraftForge/MinecraftForge#4769]
If you accidentally cause a StackOverflowError in something that uses ICrashReportDetail to catch exceptions, the StackOverflowError isn't shown; instead, a NoClassDefFoundError occurs for the anonymous subclass of ICrashReportDetail. Minimal test case:
```java
package com.example.examplemod;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.block.state.IBlockState;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Mod(modid = ExampleMod.MODID)
@Mod.EventBusSubscriber
public class ExampleMod
{
    public static final String MODID = "examplemod";

    @SubscribeEvent
    public static void registerBlocks(RegistryEvent.Register<Block> event)
    {
        event.getRegistry().register(new Block(Material.ROCK)
        {
            @Override
            public void neighborChanged(IBlockState state, World worldIn, BlockPos pos, Block blockIn, BlockPos fromPos)
            {
                throw new RuntimeException();
            }
        }.setRegistryName(new ResourceLocation(MODID, "runtimeexceptionblock")));

        event.getRegistry().register(new Block(Material.ROCK)
        {
            @Override
            public void neighborChanged(IBlockState state, World worldIn, BlockPos pos, Block blockIn, BlockPos fromPos)
            {
                worldIn.neighborChanged(pos, blockIn, fromPos); // intentionally cause infinite recursion and a StackOverflowError
            }
        }.setRegistryName(new ResourceLocation(MODID, "stackoverflowblock")));
    }
```

If you /setblock an `examplemod:stackoverflowblock` and then change one of its neighbors, you'll get this error:
```
java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:556)
	at net.minecraft.world.World.func_175685_c(World.java:496)
	at net.minecraft.world.World.func_175722_b(World.java:439)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:380)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:925)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186)
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:478)
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739)
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	... 5 more
```
This occurs because the nested `catch` blocks begin to happen with very little stack room left, causing the loading of the ICrashReportDetail subclass to fail. We can fix this if we make sure that this class is loaded ahead of time. In my test mod, you can do this by first placing an `examplemod:runtimeexceptionblock` and changing its neighbor. Once you do this, if you then place a `stackoverflowblock`, you will get the right error:
```
java.lang.StackOverflowError
	at java.lang.Class.getEnclosingMethodInfo(Class.java:1064)
	at java.lang.Class.getEnclosingClass(Class.java:1264)
	at java.lang.Class.getSimpleBinaryName(Class.java:1435)
	at java.lang.Class.getSimpleName(Class.java:1301)
	at net.minecraft.crash.CrashReportCategory$Entry.<init>(CrashReportCategory.java:278)
	at net.minecraft.crash.CrashReportCategory.func_71507_a(CrashReportCategory.java:106)
	at net.minecraft.crash.CrashReportCategory.func_71499_a(CrashReportCategory.java:111)
	at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:100)
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:87)
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:40)
	at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:360)
	at net.minecraft.world.World.func_190524_a(World.java:554)
	at com.example.examplemod.ExampleMod$2.func_189540_a(ExampleMod.java:36)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:550)
	at com.example.examplemod.ExampleMod$2.func_189540_a(ExampleMod.java:36)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:550)
	at com.example.examplemod.ExampleMod$2.func_189540_a(ExampleMod.java:36)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:550)
	at com.example.examplemod.ExampleMod$2.func_189540_a(ExampleMod.java:36)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:550)
	at com.example.examplemod.ExampleMod$2.func_189540_a(ExampleMod.java:36)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
(snip the last 3 stack frames repeated hundreds more times)
```

Here's a few ways that we can fix this in Forge:
1. Catch `Exception` instead of `Throwable` in catch blocks that use ICrashReportDetail
2. Load all subclasses of ICrashReportDetail at startup
3. Surround `new ICrashReportDetail<String>() { /* ... */ }` with another try-catch layer to catch NoClassDefFoundError and make sure that the right exception still gets thrown

I'll make a PR for whichever one of these we decide is the right way to fix this.

**Comment by bs2609** [comment]
Suggestion 2. is supposed to happen already?
https://github.com/MinecraftForge/MinecraftForge/blob/16bfd8cef1d12ee9ca0de1122addaf9916767ae9/src/main/java/net/minecraftforge/common/MinecraftForge.java#L102-L130

**Comment by josephcsible** [comment]
It looks like that's intended to do so, but it actually only does for Forge's and other mods' implementations, not for any of vanilla's.

**Comment by josephcsible** [comment]
It looks like this used to work, but either a1a67e7 or e65218b broke it.

**Comment by LexManos** [comment]
Interesting, it wouldn't be https://github.com/MinecraftForge/MinecraftForge/commit/a1a67e76543bddc8ad32473d87b41642e5503723 as I explicitly tested that myself. Specifically for vanilla code. {I was the one that bugged them to add those identifiers so we could get rid of the hardcoded list} I also explicitly tested the other... maybe something down the line is causing it.. Something removed the call to this function for vanilla code, we'll have to re-add it.

**Comment by josephcsible** [comment]
I just started up Forge 12.17.0.1925 (the first build that included a1a67e7), and this was all that it logged:
```
[14:01:02] [Client thread/DEBUG] [FML/]: Preloading CrashReport Classes
[14:01:02] [Client thread/DEBUG] [FML/]: 	net.minecraftforge.fml.client.SplashProgress$1
[14:01:02] [Client thread/DEBUG] [FML/]: 	net.minecraftforge.fml.common.FMLCommonHandler$1
[14:01:02] [Client thread/DEBUG] [FML/]: 	net.minecraftforge.fml.common.Loader$3
```

**Comment by LexManos** [comment]
That would indicate to me that something went wrong in the scanning of the vanilla jar file. Which would cause other issues. Did the launcher change where the vanilla jar is?

**Comment by josephcsible** [comment]
Hmm, maybe. I'm just using a standard MultiMC installation. Here's my fml-client-latest.log: https://paste.ee/p/9CBOQ

And here's one from 1.12.2, just to show that we haven't fixed it since 1.9.4: https://paste.ee/p/GxZFa

**Comment by LexManos** [comment]
Not exactly sure when it broke. As we *should* be gathering all the annotations for the vanilla jar file in our classpath discoverer. But i've fixed it now by adding the annotation cache for the vanilla jar to our build process. Which should speed up load time slightly.

> [15:26:15] [main/INFO] [forge/forge]: Loading Vanilla annotations: sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@4d73b25b
> [15:26:15] [main/DEBUG] [forge/forge]: Preloading CrashReport Classes
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$10
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$11
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$12
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$13
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$14
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$4
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$5
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$6
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$7
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$8
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/Minecraft$9
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/multiplayer/WorldClient$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/multiplayer/WorldClient$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/multiplayer/WorldClient$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/multiplayer/WorldClient$4
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/particle/ParticleManager$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/particle/ParticleManager$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/particle/ParticleManager$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/particle/ParticleManager$4
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/EntityRenderer$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/EntityRenderer$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/EntityRenderer$4
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/RenderGlobal$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/RenderItem$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/RenderItem$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/RenderItem$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/RenderItem$4
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/texture/TextureAtlasSprite$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/texture/TextureManager$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/texture/TextureMap$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/texture/TextureMap$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/client/renderer/texture/TextureMap$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/crash/CrashReport$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/crash/CrashReport$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/crash/CrashReport$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/crash/CrashReport$4
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/crash/CrashReport$5
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/crash/CrashReport$6
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/crash/CrashReport$7
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/crash/CrashReportCategory$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/crash/CrashReportCategory$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/crash/CrashReportCategory$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/crash/CrashReportCategory$6
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/crash/CrashReportCategory$7
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/entity/Entity$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/entity/Entity$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/entity/Entity$4
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/entity/Entity$5
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/entity/EntityTracker$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/entity/player/InventoryPlayer$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/nbt/NBTTagCompound$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/nbt/NBTTagCompound$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/network/NetHandlerPlayServer$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/network/NetworkSystem$6
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/server/MinecraftServer$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/server/MinecraftServer$4
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/server/dedicated/DedicatedServer$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/server/dedicated/DedicatedServer$4
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/server/integrated/IntegratedServer$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/server/integrated/IntegratedServer$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/tileentity/CommandBlockBaseLogic$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/tileentity/CommandBlockBaseLogic$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/tileentity/TileEntity$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/tileentity/TileEntity$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/tileentity/TileEntity$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/World$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/World$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/World$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/World$4
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/World$5
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/chunk/Chunk$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/gen/structure/MapGenStructure$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/gen/structure/MapGenStructure$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/gen/structure/MapGenStructure$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/storage/WorldInfo$10
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/storage/WorldInfo$2
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/storage/WorldInfo$3
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/storage/WorldInfo$4
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/storage/WorldInfo$5
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/storage/WorldInfo$6
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/storage/WorldInfo$7
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/storage/WorldInfo$8
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraft/world/storage/WorldInfo$9
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraftforge/common/util/TextTable
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraftforge/common/util/TextTable$Alignment
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraftforge/common/util/TextTable$Column
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraftforge/common/util/TextTable$Row
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraftforge/fml/client/SplashProgress$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraftforge/fml/common/FMLCommonHandler$1
> [15:26:15] [main/DEBUG] [forge/forge]: 	net/minecraftforge/fml/common/Loader$1

**Comment by HenryLoenwind** [comment]
ok, now World$2 doesn't NoClassDefFoundError, but CrashReportCategory$4 does:

https://server.enderio.com/crash-reports/crash-2018-03-03_17.11.01-server.txt

**Comment by josephcsible** [comment]
Do we need to construct an instance of each class instead of just calling `Class.forName` on them?

**Comment by HenryLoenwind** [comment]
not sure. I usually put an empty static method into classes I want to manually classload...or simply make them @EventBusSubscribers ;)

**Comment by josephcsible** [comment]
Just changing false to true in Class.forName should accomplish that then.

**Comment by LexManos** [comment]
No the issue is this:
> [15:26:15] [main/DEBUG] [forge/forge]: net/minecraft/crash/CrashReportCategory$1
> [15:26:15] [main/DEBUG] [forge/forge]: net/minecraft/crash/CrashReportCategory$2
> [15:26:15] [main/DEBUG] [forge/forge]: net/minecraft/crash/CrashReportCategory$3
> [15:26:15] [main/DEBUG] [forge/forge]: net/minecraft/crash/CrashReportCategory$6
> [15:26:15] [main/DEBUG] [forge/forge]: net/minecraft/crash/CrashReportCategory$7

If you notice it goes from 3 to 6. That is because the vanilla jar had two extra anon classes in there that doesn't make it past Mojang's obfuscation.
The first solution that pops to mind is to just change the jar we extract the annotations out of to be the post-recompile jar. But that won't work. As if we didn't have this patch ( https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/crash/CrashReportCategory.java.patch ) The numbers skipping 4/5 would be correct.
So we need to hybrid the two. extract the annotations for both jars {in SRG names, which means the recomp jar would have to be re-obfed} and then merge the jsons together based on if we have the patch files or not. 

Not something I can tackle today. But if someone else wants to take a crack at it. Thats what needs to be done.

**Comment by josephcsible** [comment]
Can this be reopened so it doesn't get lost before it's fully fixed?
