### ISSUE TITLE
[1.12] possible network bug reportUntracedLeak

### ISSUE THREAD

**Issue by Project579** [MinecraftForge/MinecraftForge#4770]
When player disconnect sometimes the io.netty.util.ResourceLeakDetector detects a leak.

> Feb 24, 2018 3:49:34 PM io.netty.util.ResourceLeakDetector reportUntracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected.
Enable advanced leak reporting to find out where the leak occurred.
To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced'
or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html
for more information.

Error is not logged automatically so I cannot provide a log, it is only thrown in console.

**Comment by LexManos** [comment]
Use 1.12.2. Also forums.
