### ISSUE TITLE
WorldRenderer.java not patched in 1.8.8

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4771]
not patched/deobfuscated at all
![image](https://user-images.githubusercontent.com/34866475/36642572-b37e06aa-1a5a-11e8-9635-4ccd886c41df.png)
![image](https://user-images.githubusercontent.com/34866475/36642653-2b62a148-1a5c-11e8-9f04-c2884434b657.png)

**Comment by diesieben07** [comment]
The names are community provided.
Use a modern version of Minecraft and more names will be present.

**Comment by mezz** [comment]
This is the wrong place for mappings issues, you can report this issue here instead:
https://github.com/ModCoderPack/MCPBot-Issues
