### ISSUE TITLE
vanilla rails show non-vanilly powering behaviour

### ISSUE THREAD

**Issue by Shildifreak** [MinecraftForge/MinecraftForge#4772]
Power should only be transmitted between rails of same kind, but If you place a golden-rail and an activator rail next to each other and power one of them, the other one does get activated as well.

vanilla 1.12.2
![rails_vanilla-1 12 2](https://user-images.githubusercontent.com/13906242/36674983-fea07eee-1b07-11e8-9c6f-4988ade9e12c.png)
forge 1.12.2-14.23.2.2611 (no mods installed)
![rails_forge-1 12 2-14 23 2 2611](https://user-images.githubusercontent.com/13906242/36674991-0650d0a8-1b08-11e8-9c6c-ea6ddd4a96d5.png)

**Comment by ichttt** [comment]
Could possibly be caused by #4573, could you maybe verify if the bug was introduced in 1.12.2-14.23.1.2570?

**Comment by Shildifreak** [comment]
I just tested 1.12.2-14.23.1.2569 (can't see issue there) and 1.12.2-14.23.1.2570 (issue appears).
So, yes that's where the bug got introduced.

**Comment by josephcsible** [comment]
#4774
