### ISSUE TITLE
LootingLevelEvent does not work but doesn't crash the game

### ISSUE THREAD

**Issue by ReporterToTheMax** [MinecraftForge/MinecraftForge#4789]
After sometime exploring the forge events, I tried to use this event but it doesn't work. I've properly registered my event so my System.out.println works but when using the setlootinglevel, and printing the looting amount, it will just say 1 even if i have like add number over 10. But when using vanilla looting enchantment, it yields 2, 3 or 4 depending on the level.

**Comment by LexManos** [comment]
Use the forums, and always post example code if you think there is a issue.
