### ISSUE TITLE
TextComponentHelper doesn't handle FakePlayers

### ISSUE THREAD

**Issue by LatvianModder** [MinecraftForge/MinecraftForge#4792]
https://github.com/MinecraftForge/MinecraftForge/blob/dc459d6b868a0b1df521ca6e1a796bab136ff5aa/src/main/java/net/minecraftforge/server/command/TextComponentHelper.java#L47-L56

Will crash if you use FakePlayer, because it assumes all EntityPlayerMPs have `playerMP.connection.netManager`

It should be `if (sender instanceof EntityPlayerMP && !(sender instanceof FakePlayer))` (Because FakePlayer only exists in Forge, so it automatically is not a vanilla client)

**Comment by LatvianModder** [comment]
Unrelated, but it would be super helpful if this method was public, no real need to make it private

**Comment by LexManos** [comment]
Why are you using it? Its private because thats how it was made.

**Comment by mezz** [comment]
I made that method private because it's kind of gross and I didn't want the liability of mods depending on it. This way it can change whenever it needs to and nobody is broken by it.

**Comment by HenryLoenwind** [comment]
Then make createComponentTranslation() private, too. Even in the few dependencies of my dev env I find plenty calls from other mods.

**Comment by HenryLoenwind** [comment]
also, could you add a comment that fake players are not allowed to use commands?
