### ISSUE TITLE
Throwing an exception in WorldEvent.Load causes the game to never quit

### ISSUE THREAD

**Issue by Niko-sk2x** [MinecraftForge/MinecraftForge#4794]
I first noticed it when trying to debug a few issues with my mod which uses that event. So far the simplest way for me to reproduce it in forge dev environment that doesn't involve running a mod is to set a breakpoint in `IntegratedServer#loadAllWorlds` at the relevant `EVENT_BUS.post()` and make it evaluate `this.playerList = null` to crash the game on the next line.

The server stops successfully but the client thred keeps running, waiting for the server to start, which will never happen because the thread is already gone.

thread dump: https://pastebin.com/ceFqHKeX
log (console output): https://pastebin.com/z5AR0ca2
Sometimes it won't react to normal close and the process has to be killed, as in this case: https://pastebin.com/raw/CTzDsE26

I was unable to find any workaround for the issue (excluding a coremod). Calling `FMLCommonHandler.instance().exitJava(-1, false)` or even `FMLCommonHandler.instance().exitJava(-1, true)` has the same effect of leaving the client running waiting for the server to start.

This is a MAJOR issue for me because in certain very common error situations in my mod an exception is thrown there, which leaves the users wondering why their world just keeps generating forever (and since my generator is very slow for now, they sometimes end up waiting half an hour or more before killing the process).

**Comment by border999** [comment]
This may actually be the same issue I've been having where world gen starts and then hangs up and just stops, but doesn't crash or report any issue.

**Comment by Niko-sk2x** [comment]
It seems like it also occurs in vanilla 1.12. But vanilla doesn't have many mods potentially crashing there,

**Comment by border999** [comment]
Finding a method to fix this would also help mods not freeze world gen. Like cubic chunks.

**Comment by Niko-sk2x** [comment]
Looks like `FMLCommonHandler.instance().exitJava(-1, true)` was not working because I attempted to run it by evaluating expression from debugger.

I also found a fix:

in `Minecraft.launchIntegratedServer` change:
`if (!net.minecraftforge.fml.common.StartupQuery.check())`
to
`if (!net.minecraftforge.fml.common.StartupQuery.check() || this.integratedServer.isServerStopped())`

**Comment by LexManos** [comment]
Provide a test mod to reproduce

**Comment by Niko-sk2x** [comment]
The only reason I didn't include example mod is because it seemed to me about as simple to write one as it is to copypaste one, and it was actually more work for me to make such a mod run in forge dev environment than it was to just put a breakpoint that makes it crash in the intended place.

But there it is if you really want one:

```java
@Mod(modid = "exception_test", version = "1.0")
@Mod.EventBusSubscriber
public class TestException {
    @SubscribeEvent
    public void onLoad(WorldEvent.Load event) {
        throw new RuntimeException("This exception should stop the client");
    }
}
```
