### ISSUE TITLE
Rendering overlays on top of items in GUIs.

### ISSUE THREAD

**Issue by ExpensiveKoala** [MinecraftForge/MinecraftForge#4804]
#4803, was in the wrong direction. In order to not open up for GL calls, something else needs to be done.
@LexManos  said: 

> If you would like to readdress this as a series of prebuilt utilities to render extra bars or numbers over items in the inventory. Then we can readdress it as that.

So I'd like to try to come up with and discuss those utilities and how they could work.
The only real way I see for "utility methods" would be for them to contain GL calls. Especially for overlays like text. What do you think about a set of different classes which represent the "additional overlay" and a way to register them to a specific stack. The `renderItemOverlayIntoGUI`, which handles rendering the stack size and durability bar, will render the different overlay stuff depending on what's registered to the stack.

# Durability Bar
This one is the one I specifically want to use. 
It would have:
1. Color
2. Orientation (Vertical & Horizontal)
3. Value (Vanilla's durability bar is 13 pixels long, but seems to be 1 pixel too wide. Bug?)
4. OffsetX
5. OffsetY

# Text
It would have:
1. Color ?
2. Value (The text)
3. OffsetX
4. OffsetY

Is this a good direction? This way, GL is never opened up to the user, but it allows for easily attaching custom overlays without having to deal with creating quads only to render it in the GUI and nowhere else.

The one part I've not a clue about would be how to attach/register. Keep a registry on the client? A method in Item that returns a list of the overlays for a given stack? An event like `ItemOverlayEvent`, or something similar?

**Comment by Abastro** [comment]
You can simply add a special durability quad to the model, and apply the value afterwards with the model. No need to be done on forge side.
But text utilities could be helpful.
