### ISSUE TITLE
build 2629 broke server console

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4808]
Fixing of #4778 broke server console.

I see no ">" at begin of line, no written text etc.

Forge build 2628 works fine.

**Comment by 3TUSK** [comment]
Can confirm this is happening with just following environment:
* Minecraft 1.12.2 Server
* MinecraftForge 14.23.2.2629 (Edit: no Mercurius nor mercurius_updater)
* macOS High Sierra 10.13.3
* Java SE Runtime Env. build 1.8.0_144-b01

Typing directly in terminal will not echo back to the screen; in addition, executing command will cause the format codes being printed out verbatim:

```
[16:06:14] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: §cUnknown command. Try /help for a list of commands§r
```

Comparing with just vanilla 1.12.2 server, where one can see typed characters echoed back on screen:
```
wut
[16:08:08] [Server thread/INFO]: Unknown command. Try /help for a list of commands
```

**Comment by mezz** [comment]
I pushed a fix for this, please try it out and let me know if you find any more issues.

**Comment by 3TUSK** [comment]
![screen shot 2018-03-19 at 23 17 16](https://user-images.githubusercontent.com/9113033/37638761-af5bf19a-2bcb-11e8-9dd5-9a4838926e46.png)
![screen shot 2018-03-19 at 23 16 26](https://user-images.githubusercontent.com/9113033/37638762-af7895d4-2bcb-11e8-9757-61439813b7ef.png)

Can confirm it is fixed w/ 14.23.2.2631. This time also got SpongeForge covered.

**Comment by ghost** [comment]
working, thanks for fix!

**Comment by phit** [comment]
is the `[net.minecraft.server.dedicated.DedicatedServer]` owner for vanilla messages (and a bunch of other things) intentional? or a side effect of fixing logging

**Comment by mezz** [comment]
There used to be a special case for vanilla logs where it didn't show that. 
I left it in since it can be helpful for debugging since you will know where the message came from.

Maybe the console can have it stripped out, but show it in the log file? Not sure. Thoughts?

**Comment by phit** [comment]
would be nice, the current messages get kind of long because of it

**Comment by OrdinatorStouff** [comment]
I second the opinion that it would be better stripped from console (but can be useful in log). 

Aside from it being my personal preference a real-world example of why it might be better to strip from console is that hosting providers can have a fixed size console window in their control panel which sometimes makes horizontal space a commodity.

**Comment by mezz** [comment]
I am shortening the Minecraft log prefixes in a new PR, please take a look there: https://github.com/MinecraftForge/MinecraftForge/pull/4821

**Comment by mezz** [comment]
Also, if you have a niche logging issue you can override Forge's log configuration with your own.
You just have to set the `log4j.configurationFile` system property to point to your log configuration file.
