### ISSUE TITLE
Wrong mouse coordinates inside EntityRenderer.updateCameraAndRender

### ISSUE THREAD

**Issue by panoskj** [MinecraftForge/MinecraftForge#4814]
To begin, this is a vanilla bug. It doesn't affect vanilla however.

If we examine EntityRenderer.updateCameraAndRender we will find this code:
`final ScaledResolution scaledresolution = new ScaledResolution(this.mc);`
`int i1 = scaledresolution.getScaledWidth();`
`int j1 = scaledresolution.getScaledHeight();`
`final int k1 = Mouse.getX() * i1 / this.mc.displayWidth;`
`final int l1 = j1 - Mouse.getY() * j1 / this.mc.displayHeight - 1;`
`// skipped some lines`
`ForgeHooksClient.drawScreen(this.mc.currentScreen, k1, l1, this.mc.getTickLength());`

But in GuiScreen.handleMouseInput there is a slightly different version:
`int i = Mouse.getEventX() * this.width / this.mc.displayWidth;`
`int j = this.height - Mouse.getEventY() * this.height / this.mc.displayHeight - 1;`
`// skipped some lines`
`this.mouseClicked(i, j, this.eventButton);`

The difference isn't obvious until you try it with a modded GuiScreen that uses a custom scale (instead of ScaledResolution's scale). In this case, mouse input (clicking) works but mouse rendering doesn't. It renders as if mouse was at a different position.

This could be fixed if one overrode the GuiScreen.drawScreen method and scaled mouse coordinates accordingly before performing the rendering. However, FML lets other mods hook drawScreen, such as JEI. In which case, mouse coordinates sent to said mods will be incorrect.

Therefore, it should be fixed in FML, to support GUIs with a custom scale. For example, if a modded chest's GUI is too big to fit the screen, it will be possible for the modder to scale it down, so that the end user doesn't have to scale down every GUI in the game.

**Comment by LexManos** [comment]
First question, why are you using a different scale? 
Secondly do you have a simple demo case to reproduce this so we can verify any changes?

**Comment by panoskj** [comment]
There's a mod called Compact Storage, which lets you build pretty large chests. With a 1080p monitor, Minecraft auto GUI scale is set at 4x. I like this scale, but big chests don't fit my screen. Here is a screenshot: https://imgur.com/a/Ci0Je.

So, as a player, my options would be: using 3x scale for the whole game, switching scale whenever I want to use this chest, or using chests with smaller GUI.

I thought the most convenient solution for me would be to scale down the GUI itself. Here it is: https://github.com/panoskj/CompactStorage/tree/gui-scales-down.

To see the code added to perform the scaling, compare this branch with the previous version. Note that without modifying FML, the mouse will _appear_ to be at the wrong position.

Last but not least, the proposed fix is already being used for mouse input events so it is not going to break anything.

**Comment by HenryLoenwind** [comment]
panoskj, if this works, I think a couple of mods may want to use it for their books instead of using fontRenderers that scale their output---usually resulting in weird pixel ratios.

**Comment by panoskj** [comment]
@HenryLoenwind It does work like a charm and I don't know why they don't do it already. The sole reason I asked this to be added in FML is just for compatibility with other mods that render an overlay on the screen, such as JEI. Books don't need overlays afaik so they could work around this as I mentioned already. In fact, in the branch gui-scales-down, the code for the work around is there, just commented out.

**Comment by mezz** [comment]
There are places in JEI (outside that event) where I used the same `scaledResolution` calculation to figure out where the mouse is. I think I would need to update to work with this, or store the last known mouse position based on this event.

Personally I don't think it's a good idea to change the scale for a gui. I have been tempted with JEI since I could fit a lot more things on the screen and it could be easier to display, but it really comes down to an issue of accessibility. Players with low vision (for example) need to have things show up big on their screen so they can play. If you do not respect the standard configuration settings, there are often unintended side effects and you may be excluding people from using your mod.

**Comment by panoskj** [comment]
Hey @mezz, you are right, JEI would need some fixing to support this. But it can't be fixed in a simple manner unless FML fixes this inconsistency. In which case, I may fix JEI's code and create a PR for you.

I agree that changing GUI scale may hinder accessibility, but not necessarily. For example, I turned an almost unusable chest (it doesn't fit the screen!) into something that can actually be used. Note that my vision isn't low but I still like to play at the maximum scale. I wouldn't use "Normal" scale just because a single GUI was too big. So I scaled it down.

Another modder may use this for something else, even scale some special GUI _up_! In the end of the day it's up to the players to decide what's more accessible, so why not give them the option? Besides, the code already supports it, except for the inconsistency I've pointed out.

Finally, why do you think `GuiScreen.width` and `GuiScreen.height` exist? It seems to me they are for extensibility. Wouldn't it be better mezz, if your GUI had a slider, to let players decide what scale is better for them? Using a different scale for each GUI opens up completely new possibilities.
