### ISSUE TITLE
1.12.2 Multicraft issue

### ISSUE THREAD

**Issue by OldManCraft** [MinecraftForge/MinecraftForge#4815]
Server is running Forge 2627. I tried upgrading to 2631 and the server hangs at the end. It doesn't show that the server is up, and you CAN connect to it. I have tested with multiple packs. I have also tested the 2632 and still have the issue. Let me know if you need anything further. This is on Multicraft ver. 2.1.1

**Comment by raoulvdberge** [comment]
Have you tested *without* any mods?

**Comment by OldManCraft** [comment]
I can.

**Comment by OldManCraft** [comment]
I have just tried with no mods, Just Forge 2632 and it still is happening.

**Comment by raoulvdberge** [comment]
Do you have any relevant logs?

**Comment by OldManCraft** [comment]
[Forge Debug log.txt](https://github.com/MinecraftForge/MinecraftForge/files/1842316/Forge.Debug.log.txt)

all I got from the just forge server. There is server startup log at the bottom

**Comment by Cloudhunter** [comment]
Multicraft will probably need updating to handle the logging changes introduced here:

https://github.com/MinecraftForge/MinecraftForge/pull/4802

You should report this to the Multicraft developers.

**Comment by OldManCraft** [comment]
Been Reported.
