### ISSUE TITLE
Possible issue with KeyBinding categories being duplicated in GuiKeyBindingList

### ISSUE THREAD

**Issue by jabelar** [MinecraftForge/MinecraftForge#4820]
A potential bug was found during discussion of following forum thread: http://www.minecraftforge.net/forum/topic/63656-1102-key-bind-overflow/

Basically, in the constructor of the GuiKeyBindingList it gets the array of key bindings from GameSettings#keyBindings and then does a sort and then loops through. While doing so it checks to see if the category of the current iteration of the loop is equal to the category of the previous iteration and if not it adds another category to the listEntries field.

The issue (as observed in the thread and seemingly possible based on the code) is that this logic assumes that the sorting will be by category. But that doesn't make much sense because the array is of type KeyBinding and the sort is a Arrays.sort(). The sort() contract requires an implementation of a comparable interface but KeyBinding doesn't have that so it would end up being the default Object implementation.

The poster of the thread did debugging and found that the same category was getting into the listEntries, which would make sense if the sort ended up with those categories not being associated with consecutive array elements.

Maybe I'm missing something?

**Comment by mezz** [comment]
I took a look and `KeyBinding implements Comparable<KeyBinding>` 
```java
    public int compareTo(KeyBinding p_compareTo_1_)
    {
        if (this.keyCategory.equals(p_compareTo_1_.keyCategory)) return I18n.format(this.keyDescription).compareTo(I18n.format(p_compareTo_1_.keyDescription));
        Integer tCat = CATEGORY_ORDER.get(this.keyCategory);
        Integer oCat = CATEGORY_ORDER.get(p_compareTo_1_.keyCategory);
        if (tCat == null && oCat != null) return 1;
        if (tCat != null && oCat == null) return -1;
        if (tCat == null && oCat == null) return I18n.format(this.keyCategory).compareTo(I18n.format(p_compareTo_1_.keyCategory));
        return  tCat.compareTo(oCat);
    }
```

**Comment by jabelar** [comment]
Weird I specifically looked for that but missed it somehow.

So it looks like it has a built-in sort order for vanilla categories and uses alphabetical (or at least a string compare) for custom? Seems like that should work without creating duplicates...

Can you see any reason it might fail according to the forum thread that was referenced?

**Comment by mezz** [comment]
I'm not sure. I think they should try to simplify their setup instead of assuming it's fine.

I'm going to close this since this isn't the right place to do debugging. If you find out that this is a Forge bug feel free to open a new issue. You can also find me on Discord if you have some questions.
