### ISSUE TITLE
Extra hearts are not cleared upon player death

### ISSUE THREAD

**Issue by WesCook** [MinecraftForge/MinecraftForge#4824]
In vanilla, dying with extra hearts (from potion effects) will correctly set you back to 20 health.  In Forge however, the extra hearts will remain as ghost hearts.  It seems to be a client/server desync as the hearts cannot be filled, and relogging will fix the error.

To reproduce:

1. In chat type `/effect @p minecraft:health_boost`.  It will grant two hearts for 30 seconds.
2. Type `/kill`.
3. The hearts will remain as ghost hearts if using Forge, or disappear correctly if using vanilla.

Tested in Forge 1.12.2-14.23.2.2636.

**Comment by williewillus** [comment]
This might be caused by https://github.com/MinecraftForge/MinecraftForge/pull/4265

Which would be confusing because you want to clear them on death but not on dimension switch, but if I recall correctly both take the same code path in the client. I'll have to look into it.

**Comment by williewillus** [comment]
Yup, looks like `Minecraft.setDimensionAndSpawnPlayer` is run both on death and respawn, and it's impossible to tell clientside which it is.

I might try to redo #4265 to simply resend the attributes server side to avoid this problem.
