### ISSUE TITLE
PlayerDestroyItemEvent isnt emitted when eating food

### ISSUE THREAD

**Issue by nihiluis** [MinecraftForge/MinecraftForge#4827]
I use newest kind of forge

PlayerDestoryItemEvent is not emitted when eating food, even though from documentation I assume so (to process right click).

This guy from this issue say something similar: https://github.com/MinecraftForge/MinecraftForge/issues/4347

you can reproduce like this and check when player eat bread:

```kotlin
@Mod.EventBusSubscriber(Side.SERVER, modid = "your-mod")
class CoreEventHandler {
    companion object {
        @SubscribeEvent
        @JvmStatic
        fun onPlayerEaten(event: PlayerDestroyItemEvent) {
            println("EATING")
        }
    }
}
```

I get this in debug.log, it properly register^^
```
[18:54:19] [Server thread/DEBUG] [FML]: Attempting to inject @EventBusSubscriber classes into the eventbus for gss-client-core
[18:54:19] [Server thread/DEBUG] [FML]: Registering @EventBusSubscriber for gss.modcore.CoreEventHandler for mod gss-client-core
[18:54:19] [Server thread/DEBUG] [FML]: Injected @EventBusSubscriber class gss.modcore.CoreEventHandler
```

**Comment by Anyone700** [comment]
"I use newest kind of forge" is not a forge version. Please add your forge version

**Comment by LexManos** [comment]
And use valid java. Scala has nasynesses that probably make it so that you're not actually registering for the event.

**Comment by covers1624** [comment]
That's actually kotlin, im not even sure if that's registered properly, providing a java test case would be better.

**Comment by nihiluis** [comment]
```
@Mod.EventBusSubscriber(Side.SERVER, modid = "your-mod")
public class CoreEventHandler {
        @SubscribeEvent
        public static void onPlayerEaten(PlayerDestroyItemEvent event) {
           System.out.println("EATING")
        }
}
```
I think this is valid javo. but my kotlin event registration method always works. just not fo that event.

I think I have forge 1.12.2 2640

**Comment by kierajreed** [comment]
You're missing the `@Mod`...

**Comment by nihiluis** [comment]
I need `@Mod` for that in java? I didnt know. In Kotlin I dont think you need it.

**Comment by bs2609** [comment]
Are you playing single player?
It looks like you're confusing physical with logical sides here - the code you posted only subscribes for events on a dedicated server.

**Comment by nihiluis** [comment]
Nope its on a vps. Supposed to print something to the server log.

**Comment by JamiesWhiteShirt** [comment]
@nihiluis I can understand the confusion. The side of the EventBusSubscriber annotation is [what the docs refer to as a physical side](http://mcforge.readthedocs.io/en/latest/concepts/sides/). Read that and you will understand why you should leave the side of your EventBusSubscriber untouched.

**Comment by nihiluis** [comment]
nope. thats not the issue. nothing printed
