### ISSUE TITLE
Forge hook for Elytra flying

### ISSUE THREAD

**Issue by l-Luna** [MinecraftForge/MinecraftForge#4829]
Currently, in EntityLivingBase, it checks in some parts if the chestpiece instanceof ItemElytra, but at others it checks if the chestpiece == Items.ELYTRA, which makes it impossible to add custom ones without coremodding or putting custom movement code into onWornTick.

All that needs to happen is replacing a couple == Items.ELYTRA with instanceof ItemElytra.

I'd specifically ask if this could be added to 1.10.2 too.

**Comment by pau101** [comment]
Already in progress: https://github.com/MinecraftForge/MinecraftForge/pull/4476, I encourage you to search issues before submitting one.

**Comment by l-Luna** [comment]
I though Ilooked through PRs earlier... should I close this?
