### ISSUE TITLE
[1.13] Move some transformers to compile time rather than runtime

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/MinecraftForge#4836]
There are transformers in forge that need to run at runtime, but there are also some transformers that should work just fine when they are applied in FG at compile time, e.g. the EventSubscriptionTransformer and the EventSubscriberTransformer

A downside of moving them to compile time rather then runtime is that if we want to make changes to the transformer every mod needs to be recompiled, or we have to put a transformer in forge that fixes the broken compile time transformer. The question is if this disadvantage is higher than the advantage of removing the transformers from runtime and getting a few seconds faster into your game with a large modpack

Pinging @cpw as he is rewriting FML and the transformation system

**Comment by williewillus** [comment]
not sure how useful this would be in the grand scheme of things. load times in big packs are dominated by things that are not this: usually asset loading, model baking, and other caching and integrations people do.

**Comment by LexManos** [comment]
The problem with compile time transformers is there is no good system for integrating with IDEs. Find a good way to do that and i'll go for it.
As for the Event transformers, honestly you're talking such small times it doesnt really matter.
Would be worth providing and finding out the exact times.

1.13 is having the entire coremod system re-written. So a lot of things will change and potentially support caching/speedups. We'll see how it goes.

**Comment by ichttt** [comment]
I did some testing and it doesn't seem to infect performance by a lot. I tested this with the DNS Tech Pack which takes about 3 minutes and 45 seconds for me to startup and measured a time of 6-7 seconds for the EventSubscriptionTransformer and about 1 second for the EventSubscriberTransformer, so it really doesn't affect it as much as I thought...

**Comment by Earthcomputer** [comment]
I would say that's quite a lot of time, especially if there are coremods that also have similar systems.
If, as you say, those two transformers are taking 7-8 seconds together, then it could be that in some mod packs transformers like this could be wasting up to 15 seconds of load time, possibly more.
Saving 15 seconds of load time is definitely worth the effort IMO.

**Comment by LexManos** [comment]
Then find a solution to the IDE problem.
