### ISSUE TITLE
Different results from block registry by different mods

### ISSUE THREAD

**Issue by nihiluis** [MinecraftForge/MinecraftForge#4840]
I have some odd error for which Im unable to specify the reason. It might be a forge bug? or I might use the register wrong.

For some reason another mod (SpongeForge) is unable to get a proper block name. the expected result from `Block.REGISTRY.getNameForObject(block)` is `gssdecor:statuetest`. but for some reason SpongeForge gets only `statuetest`. However when I use that method on my mod, the id is correct, namely `gssdecor:statuetest`. How can that be?

There are more infos about the sponge side here: https://github.com/SpongePowered/SpongeCommon/issues/1845

This is how I check in my mod (sponge uses the same method):
```kotlin
        @SubscribeEvent
        @JvmStatic
        @SideOnly(Side.SERVER)
        fun blockPlace(event: BlockEvent.PlaceEvent) {
            println(Block.REGISTRY.getNameForObject(event.placedBlock.block))
            println(event.placedBlock.block.registryName!!.resourceDomain)
            println(event.placedBlock.block.registryName!!.resourcePath)
        }
```

I'm registering blocks like this
```kotlin
fun DecorativeBlock.activate() {
        unlocalizedName = "gssdecor.$id"
        setRegistryName(id)
        setCreativeTab(CreativeTabs.DECORATIONS)
        soundType = SoundType.STONE
}
@Mod.EventHandler
    fun preInit(event: FMLPreInitializationEvent) {
        Statues
        Trees

        Statues.blocks.forEach {
            it.activate()
            ForgeRegistries.BLOCKS.register(it)
            ForgeRegistries.ITEMS.register(ItemBlock(it).setRegistryName(it.registryName))
            if (event.side == Side.CLIENT) {
                it.registerRender()
            }
        }
        Trees.blocks.forEach {
            it.activate()
            ForgeRegistries.BLOCKS.register(it)
            ForgeRegistries.ITEMS.register(ItemBlock(it).setRegistryName(it.registryName))
            if (event.side == Side.CLIENT) {
                it.registerRender()
            }
        }

        logger = event.modLog
    }
```

**Comment by LexManos** [comment]
Everything related to Registries in Forge uses ResourceLocations, so there is no way to ever have a name without both parts. So some other mods you have installed, or coremod is screwing things up.
This isn't a Forge issue.
