### ISSUE TITLE
FluidRegistry allows modders to be too stupid to mod

### ISSUE THREAD

**Issue by HenryLoenwind** [MinecraftForge/MinecraftForge#4843]
`isFluidRegistered(Fluid)` only checks if there is any fluid registered with the same name as the given fluid. However, both `addBucketForFluid()` and `FluidStack#new` rely on it to check if the fluid they are given is valid. So if someone uses a `Fluid` that is not registered itself (`FluidRegistry.delegates` has no entry for it) but has the same name as a registered Fluid, the result is random crashes all over everything.

Sadly there are mods out there that do that.

**Comment by mezz** [comment]
FluidRegistry is bad, but there is hope in 1.13: https://github.com/MinecraftForge/MinecraftForge/pull/4098
