### ISSUE TITLE
EntityRegistration does not use custom factory from EntityEntryBuilder

### ISSUE THREAD

**Issue by Katrix** [MinecraftForge/MinecraftForge#4845]
When using `EntityEntryBuilder`, you can supply a custom factory which will be used instead of the default only world one. Seems like a nice feature, but sadly it does not work currently.  The reason is that `EntityRegistration`, even though it too can use a custom factory, still uses the original class based method.

What I would find neat was if the entry builder was used to create the entity, and then set the  default data(position data and id and such) as the class based one currently does.

**Comment by kashike** [comment]
...yes, it is used.
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/registry/EntityEntryBuilder.java#L263-L268
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/registry/EntityEntry.java#L65-L68

**Comment by bs2609** [comment]
It isn't used here:
https://github.com/MinecraftForge/MinecraftForge/blob/272b337aa33864ac3d9a855c5cd9ee1f79ac0a8b/src/main/java/net/minecraftforge/fml/common/network/internal/EntitySpawnHandler.java#L69-L138

**Comment by Katrix** [comment]
To make stuff clearer, this is the method which is the problem.
https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/registry/EntityEntryBuilder.java#L280

I don't care if another factory is used to set the one for `EntityRegistration `, as long as it is possible to define an entity with no only world constructor I'm happy.

**Comment by kashike** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/4846
