### ISSUE TITLE
[Forge-1.12.2-14.23.2.2653] Cannot Craft Non-Oak Fences and Sticks Out of Other Woods

### ISSUE THREAD

**Issue by fandomaniac** [MinecraftForge/MinecraftForge#4850]
Cannot Craft Non-Oak Fences and Sticks Out of Other Woods. For example: You cannot craft Eucalyptus sticks or fences. Eucalyptus planks make Oak Sticks, etc.

**Comment by LexManos** [comment]
There is no such thing as Eucalyptus in Minecraft.
Also just tested i'm able to craft all the fence variants in vanilla.

**Comment by bs2609** [comment]
Sounds like https://github.com/progwml6/Natura/issues/415.

**Comment by fandomaniac** [comment]
Sorry, my bad. It's Natura. I will file a report with them.
