### ISSUE TITLE
[Enhancement/Idea] Enforce RegistryName's Domain To Valid Modid Only

### ISSUE THREAD

**Issue by jredfox** [MinecraftForge/MinecraftForge#4851]
Forge currently doesn't enforce a registry name to an already loaded mod this is going to cause issues for mods that want to break other mods.

Example:
*Item item = new Item();*
*ForgeRegistries.ITEMS.register(item.setRegistryName("blizzardfox:23"));*

Printline:
*Loader.isModLoaded(item.getResgistryName().getResourceDomain() )*
Output:
*false*

blizzardfox is a fake mod never loaded into the game yet forge doesn't say hey this isn't a valid mod and crash. The mod should have to be loaded and it should be enforced that a domain for the registry name should be an already loaded mod. **I am not saying it has to be your domain just a valid modid**

Why: 
so it makes mods more compatible with each other for mods that are dynamic and/or utility mods
you already enforce toLowerCase() as a resource location this wouldn't be that much of an unreasonable step
it would force mod creators to use their resource domain or a domain of an already loaded mod

When would it crash:
when registering an item or
**more optimized**: doing a check after post init allowing all possible outcomes of failure or you could enforce option 1 less optimized.

**Comment by HenryLoenwind** [comment]
I don't understand what you are trying to say or accomplish, but it doesn't sound good.

**Comment by jredfox** [comment]
you have a broken mod that registers an invalid domain say something *random* like "overwatchisgood:block" when that mod isn't loaded. If that domain isn't loaded why wouldn't you enforce it. Most mods look at the registry name and say ok this modid is resourcelocation.getDomain() **well that mod isn't loaded it's going to cause many crashes** *so you might as well just enforce it right off the bat rather then having random incompatibilities between two mods*. The mod container will return null even though it's understood even by forge that the domain of the registry name resource location is suppose to be the mod conatainers modid. **this is why fml will log a big error even if it's a valid domain** so if it's an invalid domain(the domain of the object mod isn't loaded blizzardfox:block) where "blizzardfox" isn't loaded. So if that's the case forge should throw an error

Does that make more sense to you now?

Loader.isModLoaded(item.getResgistryName().getResourceDomain() ) > will return false if it's an invalid domain. I don't care if your modid is "examplemod" as long as your registry name is loaded it should be fine but, if it's not it should throw an error. so your example mod you replace minecraft:stick ok well that's fine but, if your examplemod and you say register item "oceans:subermine59" it should throw an error.

**Comment by jredfox** [comment]
well I was just saying it would make more compatibility if mods were forced to use a valid modid as their registry name resource domain. I wasn't saying it had to be yours just a loaded mod would only make sense. so if your "thermalfondation" as modid you could still add "coflib:item" just as long as "coflib" exists. 

But, I didn't write forge so do whatever I guess.
