### ISSUE TITLE
Possible obfuscation problem with Block#useNeighborBrightness (field_149783_u)

### ISSUE THREAD

**Issue by desht** [MinecraftForge/MinecraftForge#4852]
I encountered this when adding the newly-released EnderIO to the ``run/mods`` folder of an IntelliJ dev instance.  https://github.com/SleepyTrousers/EnderIO/issues/4527 has the full details, but in a nutshell:

* Tested against Forge 14.23.2.2611 and 14.23.2.2654
* EnderIO loads fine outside a dev instance
* Inside a dev instance, the instance crashes in pre-init with a ``NoSuchFieldError`` for ``field_149783_u`` - ``Block#useNeighborBrightness``.  This crash occurs with a minimal mod framework and no other mods in ``run/mods``.

See https://github.com/SleepyTrousers/EnderIO/files/1874963/crash.txt for the stacktrace.

**Comment by josephcsible** [comment]
Are you using a different MCP mapping version for your instance than EnderIO uses?

**Comment by HenryLoenwind** [comment]
BTW, the same happens with Block.blockState, but only in this one class (BlockTelePad). Block.getBlockState() works fine.

Using IntelliJ or Eclipse makes no difference.

**Comment by desht** [comment]
EnderIO appears to be using 1.12_snapshot_20171212 (at least in the github master & 1.12.2 release branches), while I'm using (in PneumaticCraft: Repressurized) 1.12_snapshot_20180125, and also tried 20180404.  However, the mapping hasn't changed in any of those three versions - ``field_149783_u`` maps to ``Block#useNeighborBrightness`` in all of them.

**Comment by HenryLoenwind** [comment]
Also, the snapshot used for obfuscating (whatever to field_149783_u) shouldn't matter for deobfuscating (field_149783_u to useNeighborBrightness). That's the whole idea behind the deobf of mods in dev. In the past we had to make unobfed "-dev" versions for this and all stay on the snapshot version.

**Comment by BrainStone** [comment]
I'm experiencing this issue too. Any updates on this?

**Comment by BrainStone** [comment]
Weirdly enough the file in the gradle deobf cache is deobfed correctly. But in eclipse the original file is included. This happens for all local dependencies as it seems. Though strangely enough it only crashes with enderIO. There's definetly omething funny going on.
