### ISSUE TITLE
spongeforge & forge

### ISSUE THREAD

**Issue by demon57730** [MinecraftForge/MinecraftForge#4858]
spongeforge-1.12.2-2611-7.1.0-BETA-3002.jar

forge-1.12.2-14.23.2.2654-universal.jar

https://pastebin.com/9nA6B0Rg

not compatible with the latest version of forge

the concern is that it is based on forge RECOMMENDED so when you solved problems we can not use the latest version of forge because it is not in RECOMMENDED

i also opened at spongeforge but the concern is, that it's based on the forge RECOMMENDED

______________________________________________________________________________________________________________

forge-1.12.2-14.23.2.2634-universal.jar works with sponge that uses recommender version but forge-1.12.2-14.23.2.2654-universal.jar does not work with sponge

**Comment by Eragonn1490** [comment]
This is not a forge issue in my opinion
