### ISSUE TITLE
[1.12.2 Build 2657] Server Crash on startup

### ISSUE THREAD

**Issue by fandomaniac** [MinecraftForge/MinecraftForge#4864]
The Forge 1.12.2 Build 2657 is crashing on startup. Console message is below.

11.04 11:14:17 [Server] main/INFO [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
11.04 11:14:17 [Server] main/INFO [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
11.04 11:14:17 [Server] main/INFO [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
11.04 11:14:17 [Server] main/INFO [FML]: Forge Mod Loader version 14.23.3.2657 for Minecraft 1.12.2 loading
11.04 11:14:17 [Server] main/INFO [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_152, running on Linux:amd64:3.11.0-26-generic, installed at /usr/lib/jvm/jre1.8.0_152
11.04 11:14:17 [Server] main/ERROR [LaunchWrapper]: Unable to launch
11.04 11:14:17 [Server] INFO java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at /. for Forge Mod Loader
11.04 11:14:17 [Server] INFO at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:109) ~[custom.jar:?]
11.04 11:14:17 [Server] INFO at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:85) ~[custom.jar:?]
11.04 11:14:17 [Server] INFO at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:47) ~[custom.jar:?]
11.04 11:14:17 [Server] INFO at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:62) ~[custom.jar:?]
11.04 11:14:17 [Server] INFO at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
11.04 11:14:17 [Server] INFO at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
11.04 11:14:17 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
11.04 11:14:17 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_152]
11.04 11:14:17 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
11.04 11:14:17 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
11.04 11:14:17 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [custom.jar:?]
11.04 11:14:17 [Server] INFO at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [custom.jar:?]
11.04 11:14:17 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/apache/maven/artifact/versioning/ArtifactVersion
11.04 11:14:17 [Server] INFO at net.minecraftforge.fml.relauncher.libraries.LibraryManager.findLibraryFolder(LibraryManager.java:122) ~[custom.jar:?]
11.04 11:14:17 [Server] INFO at net.minecraftforge.fml.relauncher.libraries.LibraryManager.setup(LibraryManager.java:76) ~[custom.jar:?]
11.04 11:14:17 [Server] INFO at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:104) ~[custom.jar:?]
11.04 11:14:17 [Server] INFO ... 11 more
11.04 11:14:17 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.apache.maven.artifact.versioning.ArtifactVersion
11.04 11:14:17 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_152]
11.04 11:14:17 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
11.04 11:14:17 [Server] INFO at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338) ~[?:1.8.0_152]
11.04 11:14:17 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
11.04 11:14:17 [Server] INFO at net.minecraftforge.fml.relauncher.libraries.LibraryManager.findLibraryFolder(LibraryManager.java:122) ~[custom.jar:?]
11.04 11:14:17 [Server] INFO at net.minecraftforge.fml.relauncher.libraries.LibraryManager.setup(LibraryManager.java:76) ~[custom.jar:?]
11.04 11:14:17 [Server] INFO at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:104) ~[custom.jar:?]
11.04 11:14:17 [Server] INFO ... 11 more
11.04 11:14:17 [Server] INFO A problem occurred running the Server launcher.[11:14:17] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: java.lang.reflect.InvocationTargetException
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at java.lang.reflect.Method.invoke(Method.java:498)
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:main:31]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.Runtime.exit(Runtime.java:107)
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at java.lang.System.exit(System.java:971)
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
11.04 11:14:17 [Server] main/INFO [STDERR]: [net.minecraftforge.fml.relauncher.ServerLaunchWrapper:run:67]: 	... 6 more
11.04 11:14:17 [Multicraft] Server shut down (starting)
11.04 11:14:17 [Multicraft] Restarting crashed server in 2.0 seconds
11.04 11:14:17 [Multicraft] Looks like a crash, check the server console. Return value: 1
11.04 11:14:17 [Multicraft] Server stopped

**Comment by diesieben07** [comment]
See my answer on the forums:
http://www.minecraftforge.net/forum/topic/63958-1122-build-2657-server-crash-on-startup/?tab=comments#comment-301923

**Comment by fandomaniac** [comment]
I replied on the forum.

**Comment by PhiProven** [comment]
Don't know what it's supposed to look like, but http://files.minecraftforge.net/maven/ seems a bit empty.
