### ISSUE TITLE
Capabilities in Forge don't get injected in build 2655+

### ISSUE THREAD

**Issue by malte0811** [MinecraftForge/MinecraftForge#4865]
Any capabilities in the Forge jar don't get injected in Forge build 2655+ (#4841, dependency extraction changes). This issue causes Ellpeck/ActuallyAdditions#1068 and BluSunrize/ImmersiveEngineering#2934 (but is present without any mods installed).
This only happens using a "normal"/obfuscated client (and probably server), not a dev environment. The forge jar is scanned for mods [here](https://github.com/MinecraftForge/MinecraftForge/commit/9d0771b3d736a1a1b26bcdfcbda193a626e95d59#diff-b3af1b66c89ea0b47400441c6f9a4334R398), which only happens in dev now. However the scan also makes capability injection possible, since the scan doesn't happen outside of dev now, neither does cap injection/discovery.
A crude fix (plus debug code) can be found [here](https://github.com/malte0811/MinecraftForge/commit/3bd6234d84edc5c556debe8bf7b7a88d53212b8f). That fix is *not* intended to go into Forge, it was mostly a way of checking that this is the actual cause.

**Comment by LexManos** [comment]
Apparently, there is an issue related to coremods's metadata that is being hidden-ish by the way mods are discovered. I could of sworn the necessary annotation data was being gathered by the injected containers but its not. Oh well i've applied a bandaid until I can cleanup THAT side of things as well.
