### ISSUE TITLE
Sided mods on the 'wrong' side are treated as non-mod libraries

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#4871]
A `ModCandidate` is considered to be a non-mod library if no `ModContainer`s are found.

See `ModDiscoverer.identifyMods`:
https://github.com/MinecraftForge/MinecraftForge/blob/d0566ebadc9f5a78c5566ae11bdf3ca50447863f/src/main/java/net/minecraftforge/fml/common/discovery/ModDiscoverer.java#L93-L101

However if there is an identified mod that chooses not to load in the given environment, such as a client-side mod on a server, it is not counted as a "discovered" `ModContainer`.

`JarDiscoverer.findClassesASM`:
https://github.com/MinecraftForge/MinecraftForge/blob/d0566ebadc9f5a78c5566ae11bdf3ca50447863f/src/main/java/net/minecraftforge/fml/common/discovery/JarDiscoverer.java#L114-L121

`ModContainerFactory.build`:
https://github.com/MinecraftForge/MinecraftForge/blob/d0566ebadc9f5a78c5566ae11bdf3ca50447863f/src/main/java/net/minecraftforge/fml/common/ModContainerFactory.java#L73-L79

If the only `ModContainer`s present are sided, this leads to the file being treated as a library and added to the classpath.

Example log output from loading a server with CTM present:
```
[Server thread/DEBUG] [FML]: Examining file CTM-MC1.12-0.2.3.12.jar for potential mods
[Server thread/TRACE] [FML]: Located mcmod.info file in file CTM-MC1.12-0.2.3.12.jar
[Server thread/DEBUG] [FML]: Identified a mod of type Lnet/minecraftforge/fml/common/Mod; (team.chisel.ctm.CTM) - loading
[Server thread/INFO] [FML]: Disabling mod ctm it is client side only.
[Server thread/DEBUG] [FML]: Skipping mod team.chisel.ctm.CTM, container opted to not load.
...
[Server thread/INFO] [FML]: FML has found a non-mod file CTM-MC1.12-0.2.3.12.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
```

It would probably be nice to have some distinction possible between "mods found" and "mods to load" here.

**Comment by mezz** [comment]
Yeah, there is no reason for those to be added to the classpath when on the "wrong" side.
