### ISSUE TITLE
OreDictionary allows people to be sloppy in their mod

### ISSUE THREAD

**Issue by DaedalusGame** [MinecraftForge/MinecraftForge#4873]
getOreID will happily add descriptive names like null or anything else you want really
doing the former will trip up any mod trying to get ore prefixes or suffixes (for example)
note here, that Unknown (case-sensitive) is the only name not permitted in the oredictionary (appears to be the default output for invalid ore ids)
Unknown can still be added by calling getOreID("Unknown"), but no itemstacks can be registered to it
discovered live so probably does happen in atleast one mod (wouldn't surprise me if it was more considering getOreID will zealously create entries for the supplied name if none exists)

**Comment by williewillus** [comment]
Hopefully with tags and unifier on 1.13 the OD will not be needed anymore. Discussion on other tickets (mobile so can't link them)

**Comment by DaedalusGame** [comment]
Unifier sounds like a disaster if it's *anything* like the Fluid Dictionary one
Excited to see full registry event support for "OreDict" related stuff though (right? right..?)

**Comment by KingLemming** [comment]
If your mod doesn't sanity check for oreNames, I dunno what to tell you. The only problem here is the use of mods which do dumb things. Don't use those mods.

**Comment by DaedalusGame** [comment]
Have fun trying to find out which mod doesn't sanity check a null oredict entry. *It'll happen to you*

**Comment by KingLemming** [comment]
Well, it's almost definitely not a popular one. So start with all of the little random ones you may have added.

**Comment by DaedalusGame** [comment]
I have 0 want or need to debug a mod-specific issue when this is clearly a structural issue *and forge will scream in the log for less*

**Comment by mezz** [comment]
Ideally OreDictionary is going away in 1.13.
You can read up on the Unifier here: https://github.com/MinecraftForge/MinecraftForge/pull/4457#issuecomment-373944422
