### ISSUE TITLE
DecorateBiomeEvent.Pre/Post get fired in genDecorations() instead of decorate()

### ISSUE THREAD

**Issue by ochotonida** [MinecraftForge/MinecraftForge#4877]
Currently, DecorateBiomeEvent.Pre and DecorateBiomeEvent.Post get fired on the event bus in the BiomeDecorator class in the genDecorations method, Pre gets fired at the very beginning of the method and Post at the very end. The same applies to OreGenEvent.Pre/.Post getting fired on the event bus in BiomeDecorator.generateOres().
Due to this, when a custom BiomeGenerator that adds to the existing generation is made for a biome, the entire genDecorations method must be copied (which is quite a lot) so that new generation can be added between the firing of DecorateBiomeEvent.Pre and .Post. An alternative to this would be to simply call the superclass method in the overriding genDecorations method and then add new generation. This, however, means that the chunk is being decorate after BiomeDecorateEvent.Post (or before BiomeDecorator.Pre) is fired, which should not happen. This is already the case in the custom BiomeGenerator for the BiomeMesa class, where gold ore is generated after OreGenEvent.Post has already been fired in the superclass generateOres method.
Firing these event right before and right after the genDecorations() call in BiomeDecorator.decorate() (and before/after the genOres() call in BiomeDecorator.genDecorations()) should resolve these issues.

**Comment by kierajreed** [comment]
Please clean up the formatting, as right now it's quite confusing and hard to read. Specifically, at least make it not just a single long paragraph.
