### ISSUE TITLE
Repositories: Artifacts not placed in groups, non-mod artifacts not added to classpath

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [MinecraftForge/MinecraftForge#4879]
The modlist+repository system is coming along nicely, but there are a few more bugs to iron out.

Artifacts are not placed in groups, which is caused by a tiny mistake here https://github.com/MinecraftForge/MinecraftForge/blob/d9dbec05463cff111268a26dbe136a09ac6beb0c/src/main/java/net/minecraftforge/fml/relauncher/libraries/Artifact.java#L126

It should be split by `"\\."`.

Setting the Maven-Artifact attribute in a contained non-mod library jar causes the jar to not be added to the ModClassLoader. Without the attribute, it seems to be added to the classpath only by being extracted to the `./mods/${mcversion}` folder.

**Comment by LexManos** [comment]
Did I ever mention how much I hate that split is done by regex? I'll work on a fix for this soon. You notice anything else? There are a couple of cases where things won't be added to the classpath. But that's on FML's end which means i'll need to talk to cpw to understand his thinking.
