### ISSUE TITLE
[1.12.2-14.23.0.2491] Potion type registry is incomplete (Not all possible effects have PotionTypes)

### ISSUE THREAD

**Issue by MFernflower** [MinecraftForge/MinecraftForge#4885]
The fact Mojang ships incomplete code is amazing!!!

If anything it should be an easy fix for you all as mcf modifies minecraft code and can fix the incomplete potiontype.class

![untitled](https://user-images.githubusercontent.com/3164942/38885274-747eef4c-4240-11e8-9642-be5b405d4fcf.png)
![qaadsa](https://user-images.githubusercontent.com/3164942/38885283-7f01bf3a-4240-11e8-9a00-49dc291d28ad.png)

**Comment by KingLemming** [comment]
This isn't really an issue. PotionTypes and MobEffects don't necessarily correlate, or have to.

**Comment by williewillus** [comment]
Yeah, there's no correspondence between the two. 

`MobEffect` is for general status effects, but people in the community mistakenly call them "Potion effects". There is no "Potion of Hunger", but there's a "Hunger" status effect.

`PotionType` is for actual potions and tipped arrows, and in general simply represents a set of `MobEffect`s, with strengths and durations. For example, the new potion type in 1.13 is a collection of 3 different `MobEffect`s.
