### ISSUE TITLE
Snapshot artifacts without timestamps in repositories cannot be resolved

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [MinecraftForge/MinecraftForge#4886]
I assumed this would be handled quickly in the fix for #4879, but it turned out to not be the case. I'm opening this issue so that it can be tracked.

A contained jar with the Maven-Artifact manifest attribute will be archived in the mod repository. If the artifact is a snapshot without a timestamp, the artifact cannot be resolved and will silently not be loaded or added to the classpath.

The workaround is setting the Timestamp attribute, or not setting the Maven-Artifact attribute so that the contained jar is not archived.

**Comment by LexManos** [comment]
Provide a sample jar.
If it's got a maven artifact then that artifact will be added to the mod list, which then will be scanned for mods just like the legacy files.

**Comment by JamiesWhiteShirt** [comment]
Investigating this further revealed that this is only affects snapshots without timestamps. Repositories are unable to resolve these artifacts. I assumed that this was defined behavior. This behavior should probably be defined, or fail fast.
