### ISSUE TITLE
Update to scala 1.12.5

### ISSUE THREAD

**Issue by heisluft** [MinecraftForge/MinecraftForge#4892]
Scala 1.11 does not allow me to compile against java 8. As I am not that experienced with scala I have to rely on java code sometimes, so it is not really an option to say "just don't use Java 8 features then".

My current workaround is to compile the scala library 2.12.5 myself, wich works well in dev environments, but leads to inconveniences in "end-user" environments as it is ugly to download such a huge non-mod library (which also obsoletes an existing one). Also Forge will complain about a loaded non-mod file in the mods folder, (maybe) raising unnessecary concerns about security (as huge libs are ought to look suspicious) 

My suggestion would be to update when forge gets updated for 1.13, as I see no sense in making a fuss in 1.12 anymore. 

Kind regards

**Comment by bs2609** [comment]
See https://github.com/MinecraftForge/MinecraftForge/pull/4029.

**Comment by heisluft** [comment]
thanks for the reference, guess i will use the solution provided then.
