### ISSUE TITLE
BungeeCord crash when switching server (0 mods, SpongeForge servers)

### ISSUE THREAD

**Issue by Aang23** [MinecraftForge/MinecraftForge#4901]
This issue has already been reported, but couldn't be resolved because all the crashes involved mods, which could be the cause. Now I got a SpongeForge + FML non-modded client to crash for the same issue.
For explanation of the method I used to obtain the crash report, logs, and others : https://github.com/SpigotMC/BungeeCord/issues/2413
@dualspiral Also figured out what's the exact issue : https://github.com/SpongePowered/SpongeForge/issues/1978

BungeeCord's devs says the issue comes from Forge, so as it doesn't happens when Vanilla is used (Even on only the client / server), no crash happens, they think that only Forge could cause this issue.

I hope this will get fixed, I also tested using the latest non - recommended build of FML, same result.

**Comment by LexManos** [comment]
Dualspiral didn't figure anything out, his vague 'just make a coremod to fix it!' attitude is not helpful.
As for the Bungee Devs, there are a lot of other issues with the way it hacks around things, we've had to add several hardenings to handle invalid states that Bungee throws at us. 
Please provide steps to reproduce using JUST Forge as Coremods like Sponge effect A LOT of things.
I think I may know part of the issue but I need a valid way to reproduce it without massive coremods like Sponge.

**Comment by Aang23** [comment]
Okay, so I will try to get the same error without Sponge, doing it right now.

**Comment by Aang23** [comment]
Got lucky, I already got it :
Exactly the same steps, but without Sponge on the backend servers, and ip forwarding to false in the Bungee config.
Here are some more infos : the servers and the proxy were running of my Ryzen 7 Linux PC, the client on another PC, running Win10. I tested with a FML client running on a Raspberry PI 2, same issue, but happens more often (2/3).

Logs (Client) : https://pastebin.com/e5eVrBBr
Crash (Client) : https://pastebin.com/us7Z0S0c

I'm uploading my test setup as a .zip, with only the necessary files to use it. Link : https://www.dropbox.com/s/szdvqlne3vq3fd2/Parrot_Crash_Test_Server.zip?dl=1

Exact steps :
1) Setup 2 forge servers in offline mode, do not touch any other config unless the port on one of the 2 servers
2) Setup a Bungee proxy for those 2 servers, in offline mode too (faster for testing)
3) Connect with a "vanilla" FML client, and /send the player every 10 secondes from the proxy's console, after a few times the client will crash. it does not happen every time, so be patient while doing it.
4) To accelerate the process, making the MC process slower helps a lot, here I used an laptop i3 instead of my Ryzen 7 to get it so quickly.

**Comment by LexManos** [comment]
Lets see if this fixes it without exposing a bajillion other issues.
This WILL cause clients to be kicked from the server if they are running slowly and can't process the remappings before netty times out.
There may be a fix for this, or better yet a way to detect if the world is running. But not sure.
Resetting the mappings while the client knows about a world is NEVER a good idea. But we can't convince BungeeCord to reset the handshake outside of the world. So whatever.

**Comment by Aang23** [comment]
Is this is the latest build on the download page or I have to build it myself ?
(I built it and it seems to work now, will inform you if anything happens)

**Comment by Aang23** [comment]
Seems to be fixed ! Thanks !
Now the game freeze during mappings, so no ticking error. perfect !
A little improvement may be to show a loading screen during the freeze, but at least it's working.
Thanks again !
