### ISSUE TITLE
Incorrect javadoc for dependencies declaration

### ISSUE THREAD

**Issue by Pyrofab** [MinecraftForge/MinecraftForge#4918]
The documentation for `Mod#dependencies` indicates that the `required` prefix can be used by itself, and confirms it in the example with the entry `"required:forge@[14.21.1.2395,);"`. However actually using it that way results in forge failing silently and not considering the dependency string, leading to hard crashes. Using `required-after` or `required-before` works as intended.

Tested with forge version 1.12.2-14.23.3.2679 and the dependency string `required:forge@[14.23.3.2680,)`.

**Comment by mezz** [comment]
I think this doc is accurate but there is an unexpected catch.
The ability to leave off `after` or `before` is recent. It was added here https://github.com/MinecraftForge/MinecraftForge/pull/4403, in Forge 1.12.2-14.23.0.2501.
If the user has a version of Forge older than that, it will not work.
The javadoc should be updated to note that.

**Comment by mezz** [comment]
I have updated the javadoc with a note. Hopefully that makes it less of an issue.
We can remove the note in 1.13 since every version of Forge there will support the new syntax.

**Comment by Pyrofab** [comment]
I just tried with a very basic mod :
https://gist.github.com/Pyrofab/87fde88121ecd2ff03437a453e57b52c
I built that and loaded it on forge 1.12.2-14.23.2.2653, leading to this: 
![image](https://user-images.githubusercontent.com/25536265/39865022-e156b63c-544b-11e8-8871-cf9f1f559f51.png)

**Comment by bs2609** [comment]
See here:
https://github.com/MinecraftForge/MinecraftForge/blob/b6f8be6718c6a3bcba96983f37d25a463784d424/src/main/java/net/minecraftforge/fml/common/Loader.java#L255-L272

as opposed to here:
https://github.com/MinecraftForge/MinecraftForge/blob/b6f8be6718c6a3bcba96983f37d25a463784d424/src/main/java/net/minecraftforge/fml/common/Loader.java#L274-L287

The check for `required` dependencies only checks the version label, not if the supplied version is within the version range.

**Comment by bs2609** [comment]
Adding `mod.getRequirements()` to the `allDeps` list should fix this.

**Comment by mezz** [comment]
Thanks, I looked it over and you're right. `getRequirements` used to always be included in the other two lists, so we didn't really need to check it before. Fixed.
