### ISSUE TITLE
Loader.getIndexedModList throws NullPointerException when namedMods == null

### ISSUE THREAD

**Issue by Runemoro** [MinecraftForge/MinecraftForge#4919]
public Map<String,ModContainer> getIndexedModList() 
    {
        return ImmutableMap.copyOf(namedMods);
    }

This makes ImmutableMap.copyOf throw a NullPointerException if namedMods is null. If it is null, the method should return `ImmutableMap.of()`, the same way getModList() does:

    public List<ModContainer> getModList()
    {
        return instance().mods != null ? ImmutableList.copyOf(instance().mods) : ImmutableList.<ModContainer>of();
    }

**Comment by mezz** [comment]
Not sure when you're calling that to make it crash, but I looked over the VanillaFix mod and I trust you have a good case.
I pushed a fix for it like you described.

**Comment by Runemoro** [comment]
Thanks! The method was being called to add a "Suspected mod" detail to the crash report. The problem was that forge created a fake crash report on startup, before the mod list is created, to print system details.
