### ISSUE TITLE
Wither Health Bar doesn't update on spawn, when grows in size.

### ISSUE THREAD

**Issue by Insane96** [MinecraftForge/MinecraftForge#4921]
20180119 mappings

That happens because at line _420_ in _EntityWither_, `bossInfo.setPercent` is inside the `else` of `if (this.getInvulTime() > 0)`
So when the wither is invulnerable the health bar doesn't update

**Comment by Alpvax** [comment]
Surely if the wither is invulnerable, the health should not change, so the health bar not updating would not be an issue.
What is the use case for this change?

**Comment by bs2609** [comment]
[MC-99259](https://bugs.mojang.com/browse/MC-99259), but it is possible this is intended behaviour.

**Comment by kierajreed** [comment]
The Mojang bug is still open and needs to be patched, so this is to stay open too.

**Comment by mezz** [comment]
Unless someone is actively discussing a patch for it in Forge, I think it's better to leave vanilla bugs to the Mojang bug tracker.
