### ISSUE TITLE
[1.12.2] Forge NPE

### ISSUE THREAD

**Issue by PanSzelescik** [MinecraftForge/MinecraftForge#4923]
**Steps to reproduce:**
1. Connect to SpongeForge server with the same mods.
2. Disconnect.
3. Join to singleplayer world
4. This is not crash, I don't have crashreport

Minecraft looks like this:
![image](https://user-images.githubusercontent.com/26679785/39969419-9a21d6e2-56db-11e8-9fe8-33dd506c8cda.PNG)

[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/1998660/debug.log)
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/1998661/latest.log)

Minecraft: 1.12.2
Forge: 1.12.2 - 14.23.3.2655 (Recommended)
SpongeForge: 1.12.2-2611-7.1.0-BETA-3002 (Recommended)
**Mod list is in log**

**Comment by mezz** [comment]
Please try this with the latest version of Forge, 14.23.3.2689. It may be fixed already.

**Comment by PanSzelescik** [comment]
I can't join to server with latest Forge and the same mods

Minecraft: 1.12.2
Forge: 1.12.2 - 14.23.3.2689 (Latest)
SpongeForge: 1.12.2-2611-7.1.0-BETA-3002 (Recommended)

![image](https://user-images.githubusercontent.com/26679785/40007790-06f3d65e-579e-11e8-8b77-a0c39fc7f3d3.PNG)
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/2001516/latest.log)
[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/2001518/debug.log)
