### ISSUE TITLE
ForgeBlockStateV1 can accept a full transform definition but it's not the same format as vanilla

### ISSUE THREAD

**Issue by DaedalusGame** [MinecraftForge/MinecraftForge#4934]
I have provided in a blockstate json marked as a forge blockstate v1 the following variant
```
    "inventory":[{ "transform": {
      "gui": {
        "rotation": [ 120, 225, 0 ],
        "translation": [ 0, 0, 0],
        "scale":[ 0.625, 0.625, 0.625 ]
      },
      ...
    } }]
```
This does not work however as rotation does not expect euler angles as vanilla does, but instead quaternions. There are many things handled in parseRotation, like it will accept a json array as a quaternion, it will accept a json object as a quaternion and it will even accept the first element in a json array if said element is a json object. But none of these cover the euler angles used in the vanilla definition. It would probably be good to allow for this as quaternions are quite hard to work with if you need to do the math yourself.

**Comment by KingLemming** [comment]
It's annoying, but here's how you have to do it w/ ForgeBlockState:

https://github.com/CoFH/ThermalInnovation/blob/1.12/src/main/resources/assets/thermalinnovation/blockstates/drill.json

Also, note that the translation values are WAY different for some reason. I don't know the exact factor, but they need to be MUCH smaller in ForgeBlockState than the vanilla ones would suggest.

**Comment by DaedalusGame** [comment]
oh what in heck you're right, that's so bad. not sure why it wouldn't just parse 3 element arrays as axis rotation
the factor is 0.0625F - this is the value the vanilla transforms are multiplied with. This is equal to 1/16th so that makes sense. but real talk, i'm less angry about translations being off by a factor 16 and more angry about 3 element arrays not parsing as axis rotation when that's clearly a logical thing to do
you know, now that i look at it more intently, since 0.0625F is used internally aswell, I think we can consider that a bug too.

**Comment by LexManos** [comment]
Provide a small test mod&model and an explanation of what it should look like.
I'll take a look at it.
Fry re-did a bunch of this rendering crap when he redid the rendering engine.
When I originally wrote this things used the vanilla loading mechanics just in a way that generated the permutations. Not sure when it got so complicated.
The json king linked is needed if you don't specify the final value for the rotation as order matters when rotating a matrix. So we need to use objects to tell us what axis we're rotating on.
As for the translation, ya he doesn't do the 1/16th scaling, or the clamping to +-5. I expect this is to give the modder more freedom when moving things. But I would of preferred to keep the vanilla values if we used the same key, but he didn't do that. I don't see a way to fix that without redefining the format.

I would *like* to say 1.13 will drop support for BlockstateV1. As in theory vanilla supports it good enough with their multipart system. But we'll see.
