### ISSUE TITLE
Non-default recipes missing getIngredients()

### ISSUE THREAD

**Issue by mont-40** [MinecraftForge/MinecraftForge#4937]
A lot of the custom recipes (e.g. `RecipeBookCloning`) implementing `IRecipe` are missing implementations of the `getIngredients()`, which defaults to an empty `List`:
```
default NonNullList<Ingredient> getIngredients() {
    return NonNullList.<Ingredient>create();
}
```
I'm only assuming this should return the same set of `Ingredient`s that is checked in the `matches()` method, e.g.
```
if (itemstack1.getItem() == Items.WRITTEN_BOOK) {
    if (!itemstack.isEmpty()) {
        return false;
    }
    itemstack = itemstack1;
}
else {
    if (itemstack1.getItem() != Items.WRITABLE_BOOK) {
        return false;
    }
    ++i;
}
```
(taken from `RecipeBookCloning`).

**Comment by mezz** [comment]
These recipes have `isDynamic()` returning `true`, meaning they can't be simply displayed in the recipe book and they do not return ingredients to display from `getIngredients()`.
Generally they deal with items that have lots of permutations with NBT, and so they can't work properly in the recipe book.
