### ISSUE TITLE
Need recommended build on 2675 or higher

### ISSUE THREAD

**Issue by LemADEC** [MinecraftForge/MinecraftForge#4940]
FTB pushed their modpack FTB Direwolf20 1.12, to version 1.11.0 which includes twilightforest-1.12.2-3.7.424-universal.jar which requires Forge 2675 to fix a lighting bug causing large TPS drop.

Please consider a new recommended build to support the TwilightForest mod and related FTB Direwolf20 1.12 modpack.

**Comment by LexManos** [comment]
RBs will happen when RBs happen.
Its up to the modders to push for a RB. If a mod REQUIRES a version higher then the RB then the modder should be coming to us seeing what is needed before a RB.
