### ISSUE TITLE
Spiders Missing?

### ISSUE THREAD

**Issue by CosmicjLightning** [MinecraftForge/MinecraftForge#4941]
* Um don't feel like signing in or making a new account on another forum that would be forgotten in a day. 

* Anyway, At first I thought it was my mods, so I reinstalled latest forge, and latest optifine. And every time I load a map, go to night on hardmode there should be spiders crawling the forests, but there isn't. I can't find a single one. So I summon to see if they are still in game, and they are. 
* But these mobs are important, they give you string. So I was hoping it can be resolved either through your mod or optifine, I have no clue what is causing it. Normal 1.12.2 you can find them, so I have no clue. 
Pastebin doesn't allow me to past anymore, so attaching files i guess. 
[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/2023533/debug.log)
[2018-05-21-2.log.gz](https://github.com/MinecraftForge/MinecraftForge/files/2023536/2018-05-21-2.log.gz)

Anyhelp would be appreciative to figure out why I can't find any spiders. all other mobs are working well.

**Comment by liach** [comment]
Remove all your mods and test in a clean forge. If it does not keep happening, go to forge discord tech support channel to ask https://discord.gg/nzVYEMD or forge forums http://www.minecraftforge.net/forum/forum/18-support-bug-reports/
