### ISSUE TITLE
Forge universal bucket doesn't use snake-case registry name

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#4944]
Currently it's `bucketFilled`:
https://github.com/MinecraftForge/MinecraftForge/blob/f492e25bc9b99c9cd899a53e37c35ca6b8745824/src/main/java/net/minecraftforge/common/ForgeModContainer.java#L490

**Comment by liach** [comment]
The related pull request #4949 is still open.

**Comment by TeamSpen210** [comment]
Wouldn't this require a dataFixer to migrate save games (if that's going to be practical after flattening)?

**Comment by williewillus** [comment]
we can leave it be for 1.12, and I'm pretty sure forward compat to 1.13 is pretty much impossible so just change it outright there.
