### ISSUE TITLE
EntityRegistry doesn't crash when registering a mob with a spawn probability of 0

### ISSUE THREAD

**Issue by skyboy** [MinecraftForge/MinecraftForge#4950]
There are apparently mod developers that do this, and then other mod developers get blamed for these crashes.

Let's catch them out early and crash during the loading phase instead of worldgen phase?

`net.minecraftforge.fml.common.registry.EntityRegistry#addSpawn` ~ line 235

**Comment by LexManos** [comment]
What crash? Why is 0 an invalid number?  Quick glance over the vanilla code doesn't show any obvious error points for 0.

**Comment by skyboy** [comment]
The logic eventually passes through into `WeightedRandom#getRandomItem` and if all of the spawns for a particular `Biome` have a weight of 0 it throws an `IllegalArgumentExcpetion` while `WorldEntitySpawner#performWorldGenSpawning` is attempting to spawn the list 0-weight items.

If the list is empty, there is no problem. There's no good reason for setting a spawn weight to 0 instead of removing it entirely, either.

**Comment by bs2609** [comment]
Example issue: https://github.com/TeamTwilight/twilightforest/issues/459

**Comment by LexManos** [comment]
Adding a handler to EntityRegistry.addSpawn would be useless, as modders shouldn't be using that anymore. Instead they should be using the Entity Registry and associated builder.
However, even adding the hook there wouldn't help. As there is the WorldEvent.PotentialSpawns event.
Which can have any random entry added. 
What MAY be possible is to write up a List wrapper that validates entries as they are added. Tho technically a 0 value is valid as these spawn lists can be used as a list of known entities. And if there is any other entry in the list it will select the correct value.

**Comment by skyboy** [comment]
It may be worth revisiting the implementation of the `WorldEvent.PotentialSpawns` event, or removing it entirely in the future in favor of using the lists on `Biome` and adding hooks for allowing non-vanilla `MagGenStructure`s to override the spawn list much like ocean monuments and witch huts do.
But that would probably have to be a discussion for post 1.13.

As far as a `List` wrapper? it looks possible for covering just adding, but it will miss any mutating.
Bare-bones impl, may miss `Stream`-, `SubList`-, or `Iterator`-bound `add` logic:
```java
        public class ValidatedSpawnList extends ArrayList<SpawnListEntry> {

            UnaryOperator<SpawnListEntry> NOT_ZERO = e -> { if (e.itemWeight <= 0) throw new IllegalArgumentException(); return e; };

            @Override public boolean add(SpawnListEntry spawnListEntry) {
                Objects.requireNonNull(spawnListEntry);
                return super.add(NOT_ZERO.apply(spawnListEntry));
            }

            @Override public boolean addAll(Collection<? extends SpawnListEntry> c) {
                Objects.requireNonNull(c);
                c.forEach(e -> NOT_ZERO.apply(e));
                return super.addAll(c);
            }

            @Override public boolean addAll(int index, Collection<? extends SpawnListEntry> c) {
                Objects.requireNonNull(c);
                c.forEach(e -> NOT_ZERO.apply(e));
                return super.addAll(index, c);
            }

            @Override public void replaceAll(UnaryOperator<SpawnListEntry> operator) {
                Objects.requireNonNull(operator);
                super.replaceAll(e -> NOT_ZERO.apply(operator.apply(e)));
            }

            @Override public SpawnListEntry set(int index, SpawnListEntry element) {
                Objects.requireNonNull(element);
                return super.set(index, NOT_ZERO.apply(element));
            }

            @Override public void add(int index, SpawnListEntry element) {
                Objects.requireNonNull(element);
                super.add(index, NOT_ZERO.apply(element));
            }
        }
```

It would most likely be better to validate when a `SpawnListEntry` is added to the spawn lists, and then change the impl. of `PotentialSpawns` to not expose the `List`, instead having dedicated contains/add/(predicated-)remove functions, then a `get` for using `WeightedRandom`. At least for so long as `SpawnListEntry` is not immutable.

**Comment by LexManos** [comment]
Hiding the list behind API would be a better idea yes, however that would require waiting for 1.13 as it's a breaking change. Everything in 1.13 will be audited so we can keep it in mind.
It would also not handle mutation cases same with your list wrapper.
One possibility would be to clone the SpawnListEntry. So that mutation of the object doesn't break things.
Also, a suite of utility lists may be in order here. 
1) A generic 'Validated List' similar to the one you posted. But less tied to SpawnListEntry.
2) A WeightedRandom specific list that validates >0 and keeps a running total of weight. So that it doesn't have to re-compute it every time it needs to generate a entry.
Just some thoughts. Needs to be fleshed out and implemented.
