### ISSUE TITLE
Deprecate ibxm.*/paulscode.sound.codecs.CodecIBXM and remove for 1.13, or update.

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#4951]
As far as I remember, it was only added there for AudioMod compatibility, which as of 1.7.x is definitely no longer necessary. In addition, the version in Forge is outdated.

I recommend deprecation and removal, as I fail to see why something so specific as a MOD/S3M/XM player library belongs in Forge, especially as mods generally do not utilize it and can trivially provide a shadowed copy if necessary.

Otherwise, the newest version of the IBXM library seems to be available [here](https://github.com/martincameron/micromod/blob/master/ibxm/IBXM.java). CodecIBXM may or may not work out of the box with it, however, as the one in Forge seems to be 9 years older, and was already outdated by the time of Forge's very first release.

Other than not bundling an outdated library, the benefit would be in bandwidth usage (IBXM takes up about 50-100KB, but it is bundled in every Forge release) and licensing (one fewer license notice to take care of, even if it's non-copyleft and permissive).

The two mods I'm aware of using it as of 1.12.2 are:

* Correlated, for its built-in music records
* Charset Audio, for exporting MOD/S3M/XM audio onto blank record discs (but I do not mind shadowing IBXM if necessary)

**Comment by Aeronica** [comment]
I agree, the with asie. It serves no real purpose anymore. It's not really useful in-game because it generates the audio on the fly and in my experiments the audio stutters at times during use.

**Comment by LexManos** [comment]
Ya, its on my list of 'why do we need this anymore' At the very least we can provide it as a standard library. It'll be deleted in 1.13.

**Comment by mezz** [comment]
I have already done this on a branch locally as part of my own 1.13 todo list.

**Comment by LexManos** [comment]
Removed in 1.13.
