### ISSUE TITLE
-Dfml.enableJsonAnnotations=true causes certain mods not being recognized in 14.23.4.2703

### ISSUE THREAD

**Issue by 3TUSK** [MinecraftForge/MinecraftForge#4953]
### Synopsis
When add `-Dfml.enableJsonAnnotations=true` to JVM arguments settings of launcher, a certain number of mods cannot be loaded as usual. The common trait shared by those failed-to-be-loaded-mods is having annotation data in JSON format (`META-INF/fml_cache_annotation.json` exists), based on observation.

### Reproduction
1. Having the following correctly installed and configured:
    * MultiMC 0.6.2-1163 or other launchers that allow editing JVM arguments
    * Minecraft 1.12.2
    * Forge 14.23.4.2703
    * TwilightForest 1.12.2-3.7.424
    * Baubles 1.12-1.5.2
2. Launch the game as usual.
3. Observe that there are 6 mods recognized by FML (`mcp`, `FML`, `forge`, `minecraft`, `baubles`, and `twilightforest`). (Note: even it is in 1.12.2, modid `FML` is capitalized for unknown reason. Here it is taken as it is here.)
4. Exit game, and add `-Dfml.enableJsonAnnotations=true` to JVM arugments via MultiMC (or other launchers). 
5. Relaunching the game.
6. Observe that `twilightforest` is not present. Only 5 mods are recognized by FML (`mcp`, `FML`, `forge`, `minecraft`, and `baubles`).

### Screenshots & log files

[debug.log](https://paste.ee/p/27z4j), without `-Dfml.enableJsonAnnotations=true`.
[debug.log](https://paste.ee/p/uJj4X), with `-Dfml.enableJsonAnnotations=true`.

Without `-Dfml.enableJsonAnnotations=true`:
![2018-05-26_10 36 14](https://user-images.githubusercontent.com/9113033/40578862-c6361b7c-60d0-11e8-9225-fbbe25665335.png)

With `-Dfml.enableJsonAnnotations=true`:
![2018-05-26_10 38 07](https://user-images.githubusercontent.com/9113033/40578872-f20c8042-60d0-11e8-94c0-f80d35f24f30.png)

### Analysis
No comprehensive investigation has been conducted.
However, after setting up several breakpoints (using remote debugger from IDEA), it is observed that, when examining `twilightforest-1.12.2-3.7.424-universal.jar`, [this block of code is doing nothing](https://github.com/MinecraftForge/MinecraftForge/blob/32438d2e00632d40238776d5e85a27535e0048fc/src/main/java/net/minecraftforge/fml/common/discovery/JarDiscoverer.java#L145-L165), or in another word, the loop is not executed even once.
My best guess, based on debugging, is `for (ASMData data : annos.get(type.getClassName()))` (line 145 of `JarDiscoverer`) was iterating over empty collection.
Hope this rough investigation is correct.

### Final thoughts
No particular thoughts, but based on my understanding, caching annotation data at compile time would speed up game launching (especially when a mod contains large number of `*.class` files, as regular `ASMModParser` will read the whole class anyway), so hope this functionality will be enabled by default one day.

**Comment by bs2609** [comment]
Here's a gist of the entry for the mod class from the extracted `fml_cache_annotation.json` file:
https://gist.github.com/bs2609/8135cb9c89fba079291759b97899f212

It seems like the name entry in the json (`"name": "Lnet/minecraftforge/fml/common/Mod;"`) might not match the format used by the loading code?

**Comment by 3TUSK** [comment]
If I recall right, the format used by loading code is `net.minecraftforge.fml.common.Mod` (return value of `type.getClassName()`), based on debugging.

**Comment by LexManos** [comment]
That should fix it, I understand what the issue is now. When I was first dissecting cpw's code I saw it using internal names for parts of it, then assumed that it was all internal. 
Guess I was wrong. but TwilightForest loads in dev for me as a jar with this enabled, so it should be good.
