### ISSUE TITLE
[Feature] Additional mods directory based on profile name.

### ISSUE THREAD

**Issue by dscalzi** [MinecraftForge/MinecraftForge#4955]
Currently two directories are scanned for coremods, `{gamedir}/mods` and `{gamedir}/mods/{mcversion}`. I think it would be benefitial if another directory could be scanned, this one [based on the provided `--version` argument](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/launcher/FMLTweaker.java#L110). This would enable multiple mod configurations to be stored for the same version. If the `mcversion` and profile name are the same, then of course this would have no impact.

Ex. `{gamedir}/mods/production-1.11.2` and `{gamedir}/mods/staging-1.11.2`

The feature should be realtively simple to implement, requiring an additional location to be initialized here https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/relauncher/CoreModManager.java#L317 and here https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/relauncher/libraries/LibraryManager.java#L74.

Thank you for considering this. If implemented, could this be backported to 1.11.2 as well?

**Comment by liach** [comment]
i think right now you can add mods from command line

**Comment by LexManos** [comment]
No, this would most likely cause more problems with world incompatibilities then its worth.
The official stance is if you're wanting multiple mod sets, use multiple game dirs.
This protects your settings, and worlds from accidental corruption.

But, Liach is correct, you can specify custom mod lists using the --modlist command line argument if you're so inclined.
