### ISSUE TITLE
ProxyInjector does not delegate instantiation to language adapter

### ISSUE THREAD

**Issue by ChloeDawn** [MinecraftForge/MinecraftForge#4959]
When data is processed for SidedProxy annotations, Forge attempts to create a new instance of the target class without delegating it to `ILanguageAdapter#getNewInstance`.

https://github.com/MinecraftForge/MinecraftForge/blob/bea02348e2845ef6b1f49b0692f79dbc097d2706/src/main/java/net/minecraftforge/fml/common/ProxyInjector.java#L85

**Comment by JamiesWhiteShirt** [comment]
`ILanguageAdapter#getNewInstance` appears to be designed only to get an instance of the class that was annotated with `@Mod`, and not proxies.

In my opinion, proxy classes should not be singletons so you should not need this in the first place.

**Comment by mezz** [comment]
I am under the impression that FML is pretty far from properly supporting language adapters right now. Thankfully cpw's rewrite for 1.13 should be taking this into consideration from the very beginning.
