### ISSUE TITLE
[request] Proper Data pack support

### ISSUE THREAD

**Issue by Frontrider** [MinecraftForge/MinecraftForge#4961]
It would be a really good feature to have.

In vanilla, data packs are stored either in minecraft itself, or overridden by a map. I don't think it's that unreasonable to ask that forge mods could have the same feature. It could give modpack/mapmakers a good default tool to edit recipes (directly exposing the json apis what mod devs can use to do that) and loot tables.(especially combined with a mod like the resource loader) It could achieve close to craft tweaker level of config out of the box.

I don't know what is forge's stance on an another related thing, but it would also mean that every information in there must be re loadable at runtime, since that is the default behavior of data packs. (recipes, loot tables, structures etc)

**Comment by liach** [comment]
Unfortunately, Minecraft has no data packs in the latest release. See https://minecraft.gamepedia.com/Data_pack and its version history. It will only be for Minecraft 1.13, which is under development right now; Forge seeks a total rewrite by that time. As a result, you should leave this proposal for later.

**Comment by Frontrider** [comment]
I see where I went wrong, the concept was out there in the air for too long, and I guess I got a little confused. Sorry.
