### ISSUE TITLE
Mod construction order does not respect dependencies

### ISSUE THREAD

**Issue by Aaron1011** [MinecraftForge/MinecraftForge#4968]
The Mod class states that [depending on a mod causes its event handlers to run before yours](https://github.com/MinecraftForge/MinecraftForge/blob/9cda586ebd402df2e0543444329cfc1dd08172ea/src/main/java/net/minecraftforge/fml/common/Mod.java#L127). 

However, `Loader` does not currently respect this. Currently, [`FMLLoadEvent` is fired before `sortModList` is called](https://github.com/MinecraftForge/MinecraftForge/blob/9cda586ebd402df2e0543444329cfc1dd08172ea/src/main/java/net/minecraftforge/fml/common/Loader.java#L569). Since `FMLLoadEvent` is responsible for causing `ModContainer#registerBus` to be called [via `LoadController`](https://github.com/MinecraftForge/MinecraftForge/blob/9cda586ebd402df2e0543444329cfc1dd08172ea/src/main/java/net/minecraftforge/fml/common/LoadController.java#L112), the order in which FML event listeners are registered does not depend on mod dependencies. Since mods register their listeners with `MinecraftForge.EVENT_BUS` bus via FML event listeners, all mod event registration will not take into account the mod dependency order.

**Comment by LexManos** [comment]
MinecraftForge.EVENT_BUS order is not garented anywhere, and has nothing to do with sort order.
That documentation is only referring to the mod lifecycle events. Which are peroxided behind a separate event bus that IS sorted.

**Comment by Aaron1011** [comment]
@LexManos From what I can see, a regular Forge `EventBus` is passed to `ModContainer#registerBus`. Since this happens when `FMLLoadEvent` is fired, before `sortModList` is called, the order in which mod lifecycle listeners are registered (via `FMLModContainer#registerBus`) doesn't depend on mod dependencies.

**Comment by LexManos** [comment]
Actually no a [subclass](https://github.com/MinecraftForge/MinecraftForge/blob/9cda586ebd402df2e0543444329cfc1dd08172ea/src/main/java/net/minecraftforge/fml/common/LoadController.java#L110) of Guava's EventBus is passed in, its a NEW event bus unique to every single mod. 
It is NOT MinecraftForge.EVENT_BUS.

_Edited: Changed because I forgot we never got around to moving away from Guava in FML._

**Comment by Aaron1011** [comment]
@LexManos: My bad - I misread that method.
