### ISSUE TITLE
ItemStack getBlock() Possibility

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4981]
Hi Forge,
i want to check block but i have only the possibility to check it only by ItemStack but itemstack not have getBlock() or getBlockState(),

can you implement it for future update ?

**Comment by liach** [comment]
use Block.getBlockFromItem and Block.getStateFromMeta instead.

**Comment by ghost** [comment]
yea but "net.minecraftforge.client.event.RenderTooltipEvent.Color color"
use ItemStack with color.getStack() and not Other
if i use my implement class,
it's not used for block but only item
i use already switch with stack.getStack().getItem().getRegistryName().getResourcePath() to get block name but i dont want to use this for my mods.

**Comment by liach** [comment]
create a custom itemblock class for your block then.

**Comment by ghost** [comment]
Sorry, Block.getBlockFromItem() working,
but is not realy intuitive, will adding getBlock() is easy to found the funtions with ItemStack and not with import Block.
thanks :+1:  for help

**Comment by liach** [comment]
I suggest you to create a utility class in your mod to do this job instead.
```java
public final class ItemStackUtils {
  private ItemStackUtils() {}

  public static IBlockState getStateFromStack(ItemStack stack) {
    Block block = Block.getBlockFromItem(stack.getItem());
    if (block == null) {
      return Blocks.AIR.getDefaultState();
    }
    return block.getStateFromMeta(stack.getMetadata());
  }
}
```
This code should be good enough. In code, you can call this method to retrieve the state you want. To get a more accurate result, you can use [`getStateForPlacement`](https://github.com/MinecraftForge/MinecraftForge/blob/fa50d98357fe6a52333fade830a714e2bfeffb40/patches/minecraft/net/minecraft/block/Block.java.patch#L1509) in place of `getStateFromMeta`.

**Comment by ghost** [comment]
i will use this after few test with armor,
thanks for help :+1:

**Comment by diesieben07** [comment]
Blindly passing the stack metadata into the block metadata is wrong. Vanilla wool is an example.
But this is a discussion for the forums.
