### ISSUE TITLE
When forge is used with optifine glowing effect makes the player appear as a solid color

### ISSUE THREAD

**Issue by axemwa** [MinecraftForge/MinecraftForge#4983]
When forge is used with optifine the glowing effect makes the player appear as a solid color, tested optifine without forge and the glowing effect seems to work/look like normal

**Comment by mattmess1221** [comment]
Did you also report this to optifine?

**Comment by axemwa** [comment]
Oops I will now thanks for reminding me.

**Comment by LexManos** [comment]
Optifine is a closed source, coremod that breaks into everything. We are not responsible for any issues that arise while you use it. You're best off going to them to figure it out.

**Comment by axemwa** [comment]
I was just seeking assistance nothing more wasn't sure where I had to turn to thats all, all that needed doing was to turn off fast render, issue resolved :)
