### ISSUE TITLE
Bug with "before" and "after:*" tags.

### ISSUE THREAD

**Issue by VladoCC** [MinecraftForge/MinecraftForge#4984]
I think, that this tags in need to work properly together.
Before firstly will set position for one mod, then after:* will set postion for all other mods.
But practicly this is not working correctly.
If mod will have this two tags together, then Forge will just show screen about cycles in load order.

Can you fix this? 
Because my mod Get Back To Home want to load after Hunger Overhaul and we with HO evs already add "before" tag for my mod, but they have "after:*" tag to change food values for all other mods.
And with this problems I can not run mods together.

**Comment by mezz** [comment]
I think `after:*` may not be a good idea. Can you change food values at a later loading stage like `PostInit`?

**Comment by KingLemming** [comment]
after: * is a VERY VERY bad idea and they should not be using it. That is the actual problem.

**Comment by VladoCC** [comment]
This is not my mod.
Maybe I can ask HO devs about it, but they asking on issues not frequently.

Are you approved that this is error?

**Comment by VladoCC** [comment]
I know that this is bad way, but this is their way and I need to work with it

**Comment by KingLemming** [comment]
It's technically allowed by Forge due to the parsing, but it's really just a bad idea and no mod should use it. You should raise an issue with them rather than asking Forge to hardcode strange exceptions.

**Comment by VladoCC** [comment]
I am not asking for strange exceptions.
I just want to ask you make that before and after:* will work together.

**Comment by VladoCC** [comment]
Is not this logically will be better than just throw exceptions?

**Comment by pau101** [comment]
An exception is the correct behavior. As said by the error screen: "A dependency cycle was detected in the input mod set so an ordering cannot be determined." FML can not determine the order to load mods in, as there are at least two mods which depend on each other, therefore creating a circular dependency.

**Comment by liach** [comment]
If you want to move that mod you load before to the after block, I suggest topological sort with a secondary integer index, etc. so that even though the original index of your "before" mod may be higher than yours, it must be moved back because of its low primary index.
