### ISSUE TITLE
[1.13] Will coremods be merged into the main mod jar again?

### ISSUE THREAD

**Issue by UpcraftLP** [MinecraftForge/MinecraftForge#4985]
With the coming changes to coremods in 1.13 and the fact that they will be written in JS, will you allow them to be placed in the main mod jar again?
If needed, forge could still extract the coremod files like it does with the jar-in-jar stuff in 1.12.

**Comment by LexManos** [comment]
No. They should still be a separate jar. The same guidelines for coremods will apply to them in 1.13.

**Comment by UpcraftLP** [comment]
ok, thanks for clarifying ^^
