### ISSUE TITLE
FillBucketEvent.result ItemStack can be null, and always is if universal buckets is disabled

### ISSUE THREAD

**Issue by primetoxinz** [MinecraftForge/MinecraftForge#4994]
[FillBucketEvent](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/event/entity/player/FillBucketEvent.java).result is firstly not initialized as ItemStack.EMPTY.
Secondly, FillBucketEvent.setFilledBucket() is only ever in an event registered when Universal Buckets is enabled, as can be seen [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fluids/UniversalBucket.java#L247)

**Comment by liach** [comment]
where is the event fired then?
