### ISSUE TITLE
EntityPlayer.getBedLocation() can return null but says it shouldn't

### ISSUE THREAD

**Issue by LemADEC** [MinecraftForge/MinecraftForge#4996]
As of Forge 1.12.2-14.23.4.2707, EntityPlayer.getBedLocation() has a contract to never return null but actually does. For exemple, the following code is valid while IdeaJ will detect a constant condition since it cannot be null:

```
final EntityPlayer player = xxxx;
					
BlockPos bedLocation = player.getBedLocation(player.world.provider.getDimension());
if (bedLocation != null)
{
    player.setSpawnChunk(bedLocation.offset(EnumFacing.NORTH, 16),
                    false, targetWorld.provider.getDimension());
}
```

On a similar note, the EntityPlayer.isSpawnForced(int dimension) is documented as 'may return null' while it's actually returning a primitive type which can't be null, and the code will return false instead.

**Comment by mezz** [comment]
`EntityPlayer.getBedLocation()` is a vanilla method, Forge does not add the annotations for those.

If you are interested in correct null annotations for vanilla methods, check out my project for adding them with IntelliJ here: https://github.com/mezz/MinecraftAnnotations

The issue with `getBedLocation` has already been fixed there: https://github.com/mezz/MinecraftAnnotations/blob/34237f94a4b3b6fdfa096391f27409db0ca1a2cf/net/minecraft/entity/player/annotations.xml#L35-L37

Please feel free to contribute any other fixes you come up with.
