### ISSUE TITLE
crash with personal modpack, confused and frazzled...help please

### ISSUE THREAD

**Issue by TwistedHnagman** [MinecraftForge/MinecraftForge#5002]
Error: java.lang.NoSuchMethodError: cofh.api.util.ThermalExpansionHelper.addCompactorStorageRecipe(ILnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V

**Comment by MajorTuvok** [comment]
This is something for the support forums (and there you should post the stacktrace, not only the exception)
