### ISSUE TITLE
Unable to remove AI task

### ISSUE THREAD

**Issue by Frost2779** [MinecraftForge/MinecraftForge#5012]
I was attempting to remove an AI task from a couple of vanilla mobs and after doing all the necessary checking for LivingEntity and such i found that I wasn't able to remove the task. After some spelunking into the code i found that i believe the EntityAiTasks#removeTask, is comparing the tasks within the entity list and the one you pass in incorrectly as I can't find a way to reference the task directly. would the `==` comparison be more accurate as a `instanceof` comparison?

**Comment by liach** [comment]
@frost2779 you can always iterate through the task collection and look for the ones you want to remove (and keep in a list of your own). Then remove the tasks you found. do not remove in the loop because that will lead to concurrent modification exceptions.

**Comment by LexManos** [comment]
Instanceof would be wrong as it is valid to have multiple instance of the same task, potentially with different states. So this seems like something for the forums.
