### ISSUE TITLE
-Dfml.enableJsonAnnotations=true causes array data not being wrapped in a `java.util.List`

### ISSUE THREAD

**Issue by 3TUSK** [MinecraftForge/MinecraftForge#5021]
### Synopsis

When using `-Dfml.enableJsonAnnotations=true`, `ASMData::getAnnotationInfo()` will have array value for array element. That said, `asmData.getAnnotationInfo().get("value")` will return an array if there is an array element named `value` in said annotation. However, the previous behavior, or the behavior when using `-Dfml.enableJsonAnnotations=false`, is returning `List<?>`. This may bring issue for those mods that have array of data in their annotation, as previous assumption on the actual type will fail.

### Reproduction

  1. Test snippet:
      ```java
      @TestBreakingChange.TestAnnotation("huh")
      @Mod(modid = "test_mod_please_ignore", name = "T.M.P.I.", version = "0.0.0")
      public final class TestBreakingChange {
      
          public @interface TestAnnotation {
              String[] value() default { "foo", "bar", "baz" };
          }
      
          @Mod.EventHandler
          public void preInit(FMLPreInitializationEvent event) {
              event.getAsmData()
                      .getAll(TestAnnotation.class.getName())
                      .forEach(data -> System.out.println(
                              data.getAnnotationInfo().get("value").getClass().getCanonicalName()
                      ));
          }
      }
      ```
  2. Compile the snippet, and run the mod with `-Dfml.enableJsonAnnotations=true`.
  3. There should be console output that looks like:
    
    [09:24:26] [main/INFO] [STDOUT]: [info.tritusk.test.TestBreakingChange:lambda$preInit$0:18]: java.lang.String[]
    
  4. Close game, and run the mod with `-Dfml.enableJsonAnnotations=false`.
  5. This time, there should be console output that looks like:
    
    [09:41:24] [main/INFO] [STDOUT]: [info.tritusk.test.TestBreakingChange:lambda$preInit$0:18]: java.util.ArrayList

### Analysis
No analysis has been conducted yet. However, notice that that `Map<String, Object>` will have array value for arrays of primitives, `String[]` and `Class<?>[]`, if using JSON cache:
https://github.com/MinecraftForge/MinecraftForge/blob/5624afbc3273c670ab22efa169bd3493f7a39897/src/main/java/net/minecraftforge/fml/common/discovery/json/ASMInfo.java#L67-L76

### Final thoughts
N/A

**Comment by LexManos** [comment]
God I hate the old way of loading stuff. Soo undefined.
The problem is, how to tell the difference between what should be a String[] and what should be a list...
I'll need too double check cpw's stuff before 1.13 drops too make sure this is all sanitized.

**Comment by 3TUSK** [comment]
If I read the current source right, this is still technically an issue for `1.13-pre` branch.
It seems that the replacement of `ASMDataTable` would be [`ModFileScanData` located under ForgeSPI](https://github.com/MinecraftForge/ForgeSPI/blob/bdc5c54a3c0f5f4e06d3f42d6634e8ae24c16360/src/main/java/net/minecraftforge/forgespi/language/ModFileScanData.java), whose instances are provided by the new mod loading mechanics (specifically `net.minecraftforge.fml.loading.moddiscovery`). However, right now, the actual type of these harvested annotation data still depend on how classes are scanned (i.e. implementation detail of `net.minecraftforge.fml.loading.moddiscovery.Scanner` if I read this right), and there is still no documentations on FML side that make some form of guarantee(s) on the actual types.
Still, since cpw is in charge of the new loader, I guess he will have the final words to say.

> Also the JSON annotation cache seems still missing, but that would be off-topic.
