### ISSUE TITLE
An event when the CPacketChatMessage packet is sent?

### ISSUE THREAD

**Issue by Revxrsal** [MinecraftForge/MinecraftForge#5028]
An event which is posted before, while and after the player sends a message to the chat. This can be handy to modify the player message content before it being sent. I'm pretty sure it can be very handy for chat-based mods

Pretty much just making the event class, post a Pre and Post in the EntityPlayer#sendChatMessage where the packet is being sent.

**Comment by diesieben07** [comment]
`ClientChatEvent`.
