### ISSUE TITLE
I found some Forge error logs on my server

### ISSUE THREAD

**Issue by MoeShimaKaze** [MinecraftForge/MinecraftForge#5030]
Error logs:https://pastebin.com/rVKY4XxB
Forge Version:1.12.2-14.23.4.2705
SpongeForge Version:1.12.2-2705-7.1.0-BETA-3291
Mod list:https://pastebin.com/Zsf5A1wL
Plugins List:https://pastebin.com/bfLvYCpr

**Comment by diesieben07** [comment]
Please use [the forums](http://www.minecraftforge.net/forum/).

**Comment by MoeShimaKaze** [comment]
hmm,okey

**Comment by loordgek** [comment]
if you use SpongeForge do you get support from forge ??
due to the amount of asm "hacks"
