### ISSUE TITLE
Performance issues with Capabilities event in ItemStacks

### ISSUE THREAD

**Issue by Sir-Will** [MinecraftForge/MinecraftForge#5035]
I have been working on improving the performance of my server the past months and I did create and look through hundreds of nps files. During this time I did encounter multiple occasions where the EventBus#post of gatherCapabilities in the ItemStack class was showing up with a very long time.

It would be great if we can find a solution for this issue.

<details>
<summary>Profiling Screenshots</summary>
ItemStack forgeInit:
Botania:
![](https://i.imgur.com/3eSr8R2.jpg)

Thermal Dynamics:
![](https://camo.githubusercontent.com/02197e26ed5808f7984bb515b9b30a6bbacdf43c/68747470733a2f2f692e696d6775722e636f6d2f554d76474949592e6a7067)
![](https://camo.githubusercontent.com/63b1bb96a534fa2dd03685214cd31c70f78e5c9f/68747470733a2f2f692e696d6775722e636f6d2f7778656b4232342e6a7067)

RefinedStorage:
![](https://i.imgur.com/voZZ8KT.jpg)

DankNull:
![](https://i.imgur.com/BO60arI.jpg)

mcjtylib:
![](https://i.imgur.com/MPZSfLE.jpg)

ExtraUtilties2:
![](https://i.imgur.com/gZH1flV.jpg)
</details>
</br>
forge-1.12.2-14.23.4.2705

**Comment by LexManos** [comment]
Remove the mods that are being expensive. The event is as cheap as possible on our end as it can be.
Not to mention we dont support anything related to Sponge "performance issues".
And as always, the forums are where you wanna go for simple stuff like this.

**Comment by Sir-Will** [comment]
That would be over 5 mods I would need to remove, that's not a solution.

**Comment by LexManos** [comment]
That doesnt change the fact that we cant make a for loop any more efficient then it is already. If you cant live without the laggy mods then start yelling at the mod authors to be more efficient on their end.
