### ISSUE TITLE
getToolClasses and getHarvestLevel aren't equivalent at ItemTool level

### ISSUE THREAD

**Issue by DaedalusGame** [MinecraftForge/MinecraftForge#5039]
- setHarvestLevel can be used to add toolclasses to an item
- getToolClasses returns all such toolclasses for subclasses of item
- getToolClasses returns a) if toolclass is null the same as above b) only the toolclass for subclasses of itemtool
- calling something like setHarvestLevel("pickaxe",1) on an axe will work and add the toolclass to the item for the purposes of getHarvestLevel, but getToolClasses will only ever return a set {"axe"}

This feels odd to me as it means you can't rely on getToolClasses for all instances of ItemPickaxe, ItemAxe and ItemSpade ever giving you truly all the toolclasses they have.

[Min mod to reproduce (I hope)](https://gist.github.com/DaedalusGame/e7c47fb7287338b853a54c3b0158df1a)

**Comment by LexManos** [comment]
It is not intended to set the tool level of things that arnt yours. Its a old function that has been around because nobody has remember to remove it.

**Comment by DaedalusGame** [comment]
not the point i was making, this also happens if you set your own axe's harvestlevel. well, unless you mean the correct way is to override getToolClasses and getHarvestLevel, then that is a valid point.

**Comment by LexManos** [comment]
The correct way when using ItemTool is to set your material's harvest level correctly. But yes it's been pointed out that ItemTool.getHarvestLevel is implemented incorrectly. It shouldn't care about super.
