### ISSUE TITLE
Lang file loading issues

### ISSUE THREAD

**Issue by Vastrix** [MinecraftForge/MinecraftForge#5045]
The pirate speak lang file isn't being loaded/parsed

I've tried `en_us`, `en_gb` and `en_7s`(pirate speak), only the later isn't being parsed
I assume it's the numeric character in the file name that's screwing things up?

**If Someone could confirm the issue** that'd be much appreciated :)

**Version**: `1.12.2-14.23.4.2738`

**Comment by 3TUSK** [comment]
![2018-07-16_22 52 46](https://user-images.githubusercontent.com/9113033/42765688-2c1318e4-894b-11e8-9763-060b554995bd.png)
![2018-07-16_22 52 55](https://user-images.githubusercontent.com/9113033/42765695-2d621678-894b-11e8-8a13-0fdd936f595e.png)
![2018-07-16_22 54 00](https://user-images.githubusercontent.com/9113033/42765696-2e146990-894b-11e8-8196-bd0ad572fdc9.png)
![2018-07-16_22 54 43](https://user-images.githubusercontent.com/9113033/42765735-4253fe16-894b-11e8-8545-2ccc1c377a8d.png)

Cannot confirm.

**Comment by Vastrix** [comment]
Nono, I meant, modded `en_7s.lang` files :p

**Comment by 3TUSK** [comment]
https://github.com/search?utf8=%E2%9C%93&q=filename%3Aen_7s.lang&type=
Guess there was a change from `en_PT` to `en_7S` (also `en_pt` to `en_7s`)... so not a forge issue.

Ref: https://minecraft.gamepedia.com/index.php?title=Language&oldid=1238116

**Comment by Vastrix** [comment]
Ah indeed, forge seems to still go with `en_pt`..
as changing the file name to `en_pt.lang` did the trick

**Comment by Vastrix** [comment]
Hardly worth whining about.. :p
