### ISSUE TITLE
Biome.SpawnListEntry.newInstance doesn't use entity factories

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#5046]
Currently this just looks for a constructor with a single `World` parameter and uses that to construct the entity.
It'd be nice if this deferred to `EntityEntry.newInstance` similarly to `EntityList.newEntity`, but I don't know if the `TODO` here would need to be addressed first for this to not be a performance hit:
https://github.com/MinecraftForge/MinecraftForge/blob/ab228832f24e53436d058a96ff9483376a917b02/src/main/java/net/minecraftforge/fml/common/registry/EntityRegistry.java#L376-L386

**Comment by liach** [comment]
you can just patch spawnlistentry class.

not necessary to adress that. if you go on and add a fast class to entry map, it would be an internal impl detail than a public api. btw vanilla also iterates over all furnace recipes every time to find a match, too. it won't hurt that bad.

**Comment by mezz** [comment]
I wouldn't want to iterate over the whole registry each time something is spawned, but this is only called on each new `SpawnListEntry` which is only done a few times at startup so it should be fine.

**Comment by bs2609** [comment]
That wouldn't be strictly correct however, as it wouldn't take any subsequent registry changes into account.

**Comment by liach** [comment]
anyways the lookup efficiency is not related to the issue itself. We can easily address the lookup in another pull request

**Comment by mezz** [comment]
Hmm ok. If you are making it so that `SpawnListEntry` handles registry changes, then I see what you're saying.
If you are going to be calling `getEntry` for each spawned entity, I think we definitely need to maintain a lookup map that gets updated along with the registry.

**Comment by bs2609** [comment]
As another point, even discounting later registry changes, an eager lookup will cause problems with `SpawnListEntry` instances created from `new Biome(...)` calls, as biome registration occurs before entity registration at present.
