### ISSUE TITLE
Looking for armatures is extremely slow

### ISSUE THREAD

**Issue by Runemoro** [MinecraftForge/MinecraftForge#5048]
The `loadVanillaAnimation` method in `ModelBlockAnimation` is extremely slow, taking around 90% of the model load time (found using JProfiler). Almost no models have an armature json, therefore an IOException is created for every model, which is slow because its stacktrace needs to be filled.

I suggest calling `manager.getAllResources(armatureLocation)` rather than `manager.getResource(armatureLocation)`, to avoid creating an IOException for nearly every model.

**Comment by bs2609** [comment]
I don't think that would make any difference:
```java
if (list.isEmpty())
{
    throw new FileNotFoundException(location.toString());
}
else
{
    return list;
}
```

**Comment by Runemoro** [comment]
Oh, you're right. But this still really needs to be optimized, maybe by implementing a `List<IResource> getAllResources(ResourceLocation location, boolean allowEmpty)` method in forge. To avoid breaking the interface, in case some modders create a custom resource manager, it could have a default implementation of calling `getAllResources(ResourceLocation location)` and handling the exception, but efficiently implemented for `FallbackResourceManager` by Forge.

**Comment by mezz** [comment]
I don't get the same results when sampling with VisualVM.
On the FTB Continuum pack, `loadVanillaAnimation` took 716ms total time during loading with regular Forge.
After changing `getResource` to return null instead of throwing `FileNotFoundException`, it took 510ms.

I pushed my code here if you want to test for yourself and see if you get different results: https://github.com/mezz/MinecraftForge/commit/ceab81ad5c049fd46947886fcb0eee76ca3b0393

If you do find a significant difference I can make a PR.

**Comment by Niko-sk2x** [comment]
The results may be wildly different when doing instrumented profiling, because that makes it impossible for the JVM to do some of the optimizations, which can distort the timing. So I would say, try with sampler instead of profiler.

**Comment by Darkhax** [comment]
I've ran a few tests around this today and was able to reproduce some of the performance benefits. When running a modified version which always returns the default animation data, I was able to save an average of 16.085 seconds of load time with the SevTech modpack.

**Comment by LexManos** [comment]
making something return empty obviously is less costly then making it actually do a function.
If you're claiming that you see something in a profiler.. then provide that profiler data for us to process.
But yes, a non-explody way to check if a resource exists would be nice.
