### ISSUE TITLE
Missing Scala libraries in compiled

### ISSUE THREAD

**Issue by jredfox** [MinecraftForge/MinecraftForge#5049]
build:1.12.2 - 14.23.4.2739

test: in pre-init call this line of code
DeCompiled: works
Compiled:crashes    
scala.actors.threadpool.Arrays.asList(new String[]{"a","b"});

Steps to reproduce:
install forge using windows installer 
compile the code above in pre-init as the library exists in decompiled
run said mod in compiled and you get the crash

Crash Report:
https://pastebin.com/mi6fiwYL

**Comment by JamiesWhiteShirt** [comment]
You probably meant to use `java.util.Arrays.asList(String...)`.

**Comment by jredfox** [comment]
yeah I know I accidentally used scala but, for people that use scala libraries it should be there in compiled as well
