### ISSUE TITLE
[Enhancement] Add Oredict for items from recent MC versions

### ISSUE THREAD

**Issue by Nightenom** [MinecraftForge/MinecraftForge#5050]
Add more Oredicts for items made from wood with any wood variant: boats and doors.
Also beds and other dyeable items from latest MC versions

**Comment by Generalcamo** [comment]
Already done for doors, see #5036

**Comment by kierajreed** [comment]
I think this is a good idea. I'll PR shortly.

**Comment by Eragonn1490** [comment]
@SkyHawkB merge it into #5036 instead of spamming for the same end result

**Comment by kierajreed** [comment]
Just merge my `item-unify` branch into your repo.

**Comment by Eragonn1490** [comment]
@SkyHawkB  I tested your changes, the beds are broken (if you check the logs) I don't have the spare time to fix right now so go ahead and make a second pull

*inside of the logs*

**Comment by Nightenom** [comment]
Ok, doors are merged, boats seem to be easy even for me, can someone do beds?

**Comment by kierajreed** [comment]
I tried beds, it didn't seem to work.
