### ISSUE TITLE
Missing Mod-Rejection-Message für Clients

### ISSUE THREAD

**Issue by chaos234** [MinecraftForge/MinecraftForge#5053]
I want to suggest to not check only about version missmatches besides client and server. It should also error out if you want to connecto to a server with mods which are not installed on the server.

In 1.12.2-14.23.4.2739 it ends up on permanently disconnecting from the affected server becasue mods, which must be installed on the server and on the client are not checked if they are installed on both sides.

If there are no field for the mods entry file then add them please to declare them as e. g. *server*, *client*, *both* so that forge can check against those values and reject the player, if the requirements are not met.

It would be nice because it is horrible to figur out why you are getting DC'ed

**Comment by MajorTuvok** [comment]
Actually there is the possibilty to declare a mod clientsideonly or serversideonly so there is no need to add a field...

**Comment by mezz** [comment]
I think all the things you have requested already exist and are working correctly.
It is still possible for mods to make a small mistake and break it though, like [here](https://github.com/rwtema/modjam2018/issues/33).

Do you have a specific example where this happens?

**Comment by tyler489** [comment]
How about this https://github.com/SleepyTrousers/EnderIO/issues/4747

Henry seems to think its relevent?

**Comment by LemADEC** [comment]
To summarize, mods can be:
- client side only (for example: CustomMainMenu)
- server side only (for example: FastLeafDecay)
- client or server side, or both (for example: JourneyMap)
- both side exclusively (for example: EnderIO)

In the latest case:
- there's no proper way to declare it.
- the `@NetworkCheckHandler` annotation doesn't support a clean message to inform players.

**Comment by LemADEC** [comment]
So I guess we'll still have this design issue on 1.13?

**Comment by tyler489** [comment]
Still relevant I believe..  would be nice to see a way to do this in 1.14

**Comment by LexManos** [comment]
Mod can already error if they dont have the corresponding side They have access to the mod list.
We are not adding N* different ways to make the logic more complex. The current system works just fine.

**Comment by tyler489** [comment]
This it not about having a way to check, but a way to display an actual, human-readable message instead of a cryptic stacktrace,  telling me I'm missing actually additions rather than a generic error makes your player's experience alot better .

**Comment by LexManos** [comment]
It should be a screen for the end user that lists all missing mods already. As well as a log message.
Also, no that is not what this issue is about, that may be what you want {and we already have} but this issue is about adding yet another way to check if mods are on the other end.
