### ISSUE TITLE
Add hook for what blocks a EntityFallingBlock can destroy

### ISSUE THREAD

**Issue by Ellisthion** [MinecraftForge/MinecraftForge#5054]
When an EntityFallingBlock falls on something, it checks `world.mayPlace()` to see what happens. Notably, the behaviour of an Anvil destroying some blocks (like torches) is rather hardcoded:

```java
else if (iblockstate1.getMaterial() == Material.CIRCUITS && blockIn == Blocks.ANVIL)
{
  return true;
}
```

It would be useful if that behaviour were accessible, to allow custom falling blocks to destroy torches etc or perhaps even destroy other blocks if the mod needs it.

**Comment by coaster3000** [comment]
I currently have some edits I am working on that will implement this. I will submit a pull request once it is fully tested and is suitable for submission.

**Comment by coaster3000** [comment]
This issue is still relevant. A pull request is open that addresses this as well.
