### ISSUE TITLE
Furnace Doesn't Save Fuel As Int to the disk

### ISSUE THREAD

**Issue by jredfox** [MinecraftForge/MinecraftForge#5056]
furnace stores and parses fuel time burn time etc as int but, then when saving they are all casted to short. This is a bug causing mods to have nor more then short max value for fuel without breaking minecraft furnace.

Short max value isn't much greater then the default coal block if I recall it's not enough for op rare fuel time so for that reason and others it should be high priority
![capture](https://user-images.githubusercontent.com/9736369/43194777-d44db7ac-8fc8-11e8-869c-ca7e79e9e0e0.PNG)

**Comment by mcenderdragon** [comment]
Short.MAX_VALUE would be 32767. This should be 163.83 items.

**Comment by jredfox** [comment]
has nothing to do with items it's the burntime burntime all and cooktime need to be their original int values that's stupid loosing fuel data

**Comment by kierajreed** [comment]
Again, you're pointing out a "problem" in the Minecraft code, and not saying why it should be fixed.

**Comment by KingLemming** [comment]
This is just a Mojang holdover from when the furnace used to save (and read) these as shorts.

There's a case to be made for adjusting this, but it's simple enough that maybe a PR is the right way to do it, and not just an issue.

**Comment by jredfox** [comment]
either keep everything short or keep everything as int because keeping it as short is loosing data and **fuel handlers return int as well as everything else it's a vanilla optimization do not support it when mods return int**

**Comment by KingLemming** [comment]
Sure. Yes. Make the PR.

**Comment by jredfox** [comment]
I shouldn't have to make a pull request for 3 lines of code especially when there is no actual minecraft source code to edit here on the github. Can't make a pull request if I don't know how to use MCP .patch files.

**Comment by 0xilly** [comment]
uhhh after about five seconds of searching on the readme http://mcforge.readthedocs.io/en/latest/forgedev/

**Comment by loordgek** [comment]
fixed in 1.13 https://github.com/MinecraftForge/MinecraftForge/blob/1.13-pre/patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
