### ISSUE TITLE
Shapeless Recipes Break Again

### ISSUE THREAD

**Issue by jredfox** [MinecraftForge/MinecraftForge#5059]
Build: forge-1.12.2-14.23.4.2739

Issue: create a shapless recipes using GameRegistry and next thing you know every recipe that is shapeless becomes the output stack you put in if it doesn't have a recipe like a stick. 

Test:
https://pastebin.com/5Qwj8vZH
Output stick = 9 charcoal 
Problem:Code stated that one charcoal block = 9 charcoal not a stick = 9 charcoal

Steps To reproduce:
like in test you register any shapeless recipe
then you watch as the matches method breaks everything that doesn't have a recipe will output to your shapeless output

**Comment by kierajreed** [comment]
Now, why are you using `GameRegistry` and not JSON recipes?

**Comment by kierajreed** [comment]
Also, you should describe the issue in more detail rather than just saying "it's not working".

**Comment by KingLemming** [comment]
Dude, learn to make Pull Requests. It's not hard to make a patch.

**Comment by jredfox** [comment]
`"Now, why are you using GameRegistry and not JSON recipes?"`
no because I generate the recipes dynamically cannot/will not use jsons. **I am a coder not a resource pack maker** I prefer to code it's in the code to register it has been since the dawn of forge needs to be fixed. Even use to work in older versions of 1.12 forge Also this is a legit bug and needs to be addressed.

`"Dude, learn to make Pull Requests. It's not hard to make a patch."`
*I am not going to make 400 pull request to patch forge when forge should patch forge **I don't know what the issue is they can fix this in < hour**.*

**Comment by jredfox** [comment]
`"Also, you should describe the issue in more detail rather than just saying "it's not working"."`

If you read the comment I stated that any output is 9 charcoal for everything that doesn't have a recipe rather then just the charcoal block. I never only stated that "it doesn't work". So you didn't read it then claim I am at fault lol

**Comment by micahlaster98** [comment]
still is an issue that should be fixed

**Comment by LexManos** [comment]
Follow community standards and get with the times, Json recipes are the way to go. 
Also just tested and verified that it is indeed not a real issue it is your code that is screwed up. 
You didn't even pastebin valid example code. 

@micahlaster98 Do not hop on bandwagons without verifying things for yourself.
