### ISSUE TITLE
When to indicate mod id in EventBusSubscriber, Instance, Metadata, and SidedProxy annotations.

### ISSUE THREAD

**Issue by Phylogeny** [MinecraftForge/MinecraftForge#5071]
Mod#EventBusSubscriber's documentation for 'modid 'reads:
> Optional value, only nessasary if tis annotation is not on the same class that has a @Mod annotation. Needed to prevent early classloading of classes not owned by your mod.

Mod#Instance's and Mod#Metadata's documentation for 'owner' reads:
> Optional owner modid, required if this annotation is on something that is not inside the main class of a mod container. This is required to prevent mods from classloading other, potentially disabled mods.

SidedProxy's documentation for 'modId' reads:
> The name of a mod to load this proxy for. This is required if this annotation is not in the class with @Mod annotation. Or there is no other way to determine the mod this annotation belongs to. When in doubt, add this value.

There is no indication that these 'other classes' are only of concern if they are your own classes in your own source.  However, the message of the commit (160427b12c9706e73c2fed41e8498bf565dfad73) where these fields were introduced contains:

> Effects the @EventBusSubscriber, @instance, @metadata, @SidedProxy annotations.
If the target modid is not in the annotation data, and there are multiple mods in the source, it will attempt to find it by matching the annotation's class names.

So is it still advisable to explicitly pass your mod id to these annotation if you don't have multiple mods in your source, or is it completely useless to do so? I'm guessing it's useless, but I'd like to be sure.

- If it's useless, then the "multiple mods in the source" bit should be added to the fields' documentation.
- If it's not useless, then at least EventBusSubscriber's field not being optional has a big potential for causing problems, given how commonly it is used outside the main class.

**Comment by kierajreed** [comment]
IIRC, it should be a lot clearer in 1.13 because of the rewrite.

**Comment by kierajreed** [comment]
Although, it is a good idea to clean this up in 1.12 as well.

**Comment by Phylogeny** [comment]
Although 160427b12c9706e73c2fed41e8498bf565dfad73 seems quite clear to me that specifying modId/owner does absolutely nothing if there are not multiple mods in the source, it would be nice to get some confirmation, so that we can move forward with improving the documentation for 1.12.

**Comment by LexManos** [comment]
When in doubt, add it. Forge will try and guess the context of these annotations based on:
What jar file they are in - If they are in a jar file with a single mod id it'lll guess that it's for that mod ID.
What Class they are in - If they are in a class KNOWN to be tied to a specific mod id {typically IN the @Mod'd class} then it'll use that.

So, again, When in doubt, add it.
