### ISSUE TITLE
[Enhancement] Option to change loading screen text color

### ISSUE THREAD

**Issue by Davoleo** [MinecraftForge/MinecraftForge#5077]
Disclaimer: I KNOW this is not necessary at all, but if it is simple to add I think it would be nice to have it!
I would even try to code it by myself but since my experience in MC coding is quite much low I wouldn't even try to bother trying to code something in Minecraft Forge

I was wandering if a option in [SplashProgress.java](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/client/SplashProgress.java) to change the color of the text in the loading screen could be added. 
I think it would be a nice improvement because it allows you to experiment many more combination of FML loading screen colors, like black backgrounds or black loading bars...

**Comment by Stormwind99** [comment]
The vanilla splash text already supports color - see [301 Colormatic](https://minecraft.gamepedia.com/Splash):

> 301 | Colormatic | This splash is stored as "§1C§2o§3l§4o§5r§6m§7a§8t§9i§ac" in splashes.txt; the "§" and the character following are color codes that determine the color of the text following the code.
-- | -- | --

Similar features can also be implemented via mods.  For example, see the [Better Title Screen](https://minecraft.curseforge.com/projects/better-title-screen) mod.

**Comment by Davoleo** [comment]
mmh, I probably explained myself bad, I mean the color of the text in FML loading screen

**Comment by 3TUSK** [comment]
![image](https://user-images.githubusercontent.com/9113033/43624224-85db0bcc-9718-11e8-9b18-46ac62401a3b.png)

If you mean something like this:

  1. Go to `%minecraft_dir%/config/`, find `splash.properties`
  2. Set `font=0x0` to something else, in the screenshot it's `font=0x1100FF`.

**Comment by Davoleo** [comment]
Yes, I mean that, by the way I didn't know you could already to that, thanks for the info!
closing this issue...
