### ISSUE TITLE
[Enhancement] Add custom icon for advancements

### ISSUE THREAD

**Issue by Nightenom** [MinecraftForge/MinecraftForge#5083]
Now you can use `item` key for any item or block (in `icon` in an advancement json). For custom images you need to create a proxy item and register one for each image.
My idea is that it could also handle `image` with `ResourceLocation` so we don't need to create around 20 proxy items (in modpacks this number can grow a lot)

**Comment by Nightenom** [comment]
Any ideas on this?

**Comment by smitherwin** [comment]
#6010

**Comment by Nightenom** [comment]
not sure if it will be enough, but I found a way to do this

**Comment by Nightenom** [comment]
Btw, the problem is this
![image](https://user-images.githubusercontent.com/17338378/62898020-ce722380-bd54-11e9-87d5-709e960ac84c.png)
