### ISSUE TITLE
[Suggestion] Add setters for DrawScreenEvent's MouseX and MouseY

### ISSUE THREAD

**Issue by panoskj** [MinecraftForge/MinecraftForge#5090]
Remove final modifiers and add setters for these fields. Currently, their values can be set using reflection but it would be more efficient with setters.

Why do this? To scale GuiScreen independently of the game's scaled resolution. Some time ago I made issue #4814 which explains that vanilla doesn't calculate mouse coordinates consistently. Hence, overwriting their values is required if a GuiScreen is to be scaled in the aforementioned way.

**Comment by Wyn-Price** [comment]
Can't you use an AccessTransformer?

**Comment by panoskj** [comment]
I thought they work for Minecraft's classes only, I guess I'm wrong. Thanks for the tip.

EDIT: nope they don't seem to work for this case.

**Comment by Wyn-Price** [comment]
They work for all classes, however changing the mouseX / mouseY won't do anything. They're passed in as parameters to ForgeHooksClient#drawScreen so changing those values on the event won't change those values on the actual GUI screen. 

https://github.com/MinecraftForge/MinecraftForge/blob/a935859b24916d45287b692f87765a14c3cd29d9/src/main/java/net/minecraftforge/client/ForgeHooksClient.java#L378-L383

**Comment by panoskj** [comment]
You are right, the workaround is canceling DrawScreenEvent.Pre event and firing it manually with the correct parameters. My problem was with DrawScreenEvent.Post (in which JEI performs the rendering for example). It can't be canceled, so I was setting the coordinates with reflection.

On a side note, Forge's code could be updated to use the event's parameters, alongside with adding setters for the coordinates, which would make this possibility more obvious.
