### ISSUE TITLE
[1.12.2] Character turning after exiting menu

### ISSUE THREAD

**Issue by ChaonicTheDeathKitten** [MinecraftForge/MinecraftForge#5091]
This one is a tricky one to explain. And as far as I can tell, it only appeared just now for me. I can perfectly recreate this issue with no mods installed whatsoever and not matter how often I restart Minecraft. The severity of it seems to depend on... lag? (I have a high performance machine, and it runs most times at perfect 60fps)

What I'm doing: I open any menu like inventory, crafting menu, pause the game. Depending on where I move the mouse, my character turns after closing it. It doesn't ALWAYS happen, and how long I keep my mouse still seems to influence it, too.
Removing all mods doesn't fix it, but it seems to make it less... severe?

Here's a video of what's happening.
https://puu.sh/BbTm1/cc3acb6515.gif

I am using forge version 14.23.4.2747.

**Comment by zeroeightysix** [comment]
I've experienced this before as well. Not certain under what circumstances though.

**Comment by Alpvax** [comment]
Does it happen at all in vanilla? Or is this forge-specific?

**Comment by zeroeightysix** [comment]
I believe this happens in vanilla as well.

**Comment by Alpvax** [comment]
Is there a vanilla issue in the bug tracker? 
Should this be moved to the forum until the cause is identified?
