### ISSUE TITLE
[1.12.2] Registering Crafting Condition Factories does not allow for actual Resource Locations

### ISSUE THREAD

**Issue by UpcraftLP** [MinecraftForge/MinecraftForge#5092]
When registering custom `IConditionFactory`s via a `_factories.json` file, there is no way to register these using a different namespace, due to CraftingHelper *always* prefixing the string with the current modid.
https://github.com/MinecraftForge/MinecraftForge/blob/afd6de3e305ed7f88c8f8a2f478b25e1af1e4e7e/src/main/java/net/minecraftforge/common/crafting/CraftingHelper.java#L579

Imo this should check for a modid prefix before substituting the current modid.

**Comment by temp1011** [comment]
Why would you want to register a condition for another mod?

**Comment by Pyrofab** [comment]
It can be useful when your mod delegates registration to a library

**Comment by LexManos** [comment]
This is intentional and will not change. If you MUST donlibrary stuff, then register the factory in the "library" and use the full name in the recipe itself. Thats why we force the namespaces, and load them from all mods before loading the recipes themselves. So you can depend on anothers factory.
