### ISSUE TITLE
Possible null pointer dereference in AttackEntityEvent.java

### ISSUE THREAD

**Issue by bounc3-paradise-on-e** [MinecraftForge/MinecraftForge#5099]
The problem involved in the article talking about java source code, mostly consisting of attempts performed to determine the originality of the method's context, may be accoplished either by redefining the complex (but also default interface's method), which is explained [here](https://bugs.openjdk.java.net/browse/JDK-8196141), or to decentralize event listener processing.

Most users rely on arbitrating methods that are polymorphically redefined in the parent class space where each method is either a non-static method of the parent class describing a way of handling events that occur in the non-configured environment, or belongs to the semi-integrated space where quasi-implemented interface is not exensible from the local class. Both approaches yield a non-recoverable exception that may occur (like it is described [in this post](https://github.com/hazelcast/hazelcast-nodejs-client/pull/327/files) - worth considering rechecking the code itself), but since the entirely user-defined class compiles to a separate bytecode differencies, a new migration of the such interface may result in allocating an array that couldn't be garbage collected (when we talk about consider performance - the priority is to allocate enough cache memory for storing element pointers).

```java
@Override
protected void onCreate(Bundle savedInstanceState)
{
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_list_view_test);

    mInflater = LayoutInflater.from(this);

    mListView = (ListView) findViewById(R.id.id_listview);
    mListView.setAdapter(new ArrayAdapter<String>(this, -1, mStr)
    {
        @Override
        public View getView(int position, View convertView, ViewGroup parent)
        {
            if (convertView == null)
            {
                convertView = mInflater.inflate(R.layout.item_music_list, parent, false);
            }

            TextView tv = (TextView) convertView.findViewById(R.id.id_tv_name);
            tv.setText(mStr.get(position));
            return convertView;
        }
    });
}
```

Also see the relevant discussion here: [hostprotect/java-binding#2174 (comment)](https://github.com/triplea-game/triplea/pull/3779#issuecomment-412248587). The main cause of the test failure was related to the strict assertion from the method calling `releaseOldBinding(Object *elem, int *t)`, but since the original implementation interferes with the bundled chunk loading system, it means that iterative approach would result in exponential time. The algorithm is based on the assumption that any data from the array are backtrackable (in the same order, or reversed), but *not* on parity checksums, so handling of the inner scope is processible withing two functions separated by a distribution of maining the bald wag men in spikke assego meu

In order to solve the problem, we may introduce an extensible implementation of the Dijkstra's algorithm for non-recursive deserialization of poly-vectorized data structures.

**Comment by vtesterlwg** [comment]
what

**Comment by MajorTuvok** [comment]
Why are you posting Android code to Minecraftforge? (Haven't read your issue completly yet, but sure you copied the right code in there? I can't see what populating a ListActivity has to do with forge code?!?)

And what artcile about java source code are you referring to?

And why do you deliberatly set out to confuse people by doing things like referring to Polymorphism without really a context or posting some senseless C++ code in there (your Object and int pointers...)?!?

**Comment by vtesterlwg** [comment]
Quick summary: technobabble, bullshit, nonsense, and trolling that means nothing. he's fucking with us @MajorTuvok

**Comment by MajorTuvok** [comment]
Ah thanks @vtesterlwg and I was like: 
that doesn't have anything to do with Minecraft
And you can't directly dereference in java...
