### ISSUE TITLE
Vanilla Hopper does not respect inventory size limits

### ISSUE THREAD

**Issue by Draco18s** [MinecraftForge/MinecraftForge#5101]
This was previously reported and had a pull request, #597
However, it does not appear that that change was ever applied to 1.12

**Comment by Draco18s** [comment]
Has not been fixed:

            else if (canCombine(itemstack, stack))
            {
                int i = stack.getMaxStackSize() - itemstack.getCount();
                int j = Math.min(stack.getCount(), i);
                stack.shrink(j);
                itemstack.grow(j);
                flag = j > 0;
            }

**Comment by Draco18s** [comment]
Still has not been addressed.

**Comment by diesieben07** [comment]
Not sure how this is relevant. Custom inventories should use `IItemHandler`, which means `insertItem` will be called, which will just return the remainder if the slot overflows. This would only be relevant for custom `IInventory` implementations, which I don't think is something that should be supported.
Even for vanilla TEs that implement `IInventory` this is "fixed" by Forge, because `LockableTileEntity` (effectively the superclass for all inventory TEs in vanilla) exposes an `IItemHandler` wrapper, which the hopper prefers and which respects the inventory slot limit. This however doesn't even matter, since no vanilla inventory-TE changes the slot limit.

**Comment by Draco18s** [comment]
@diesieben07 See the comments on the [PR I made against 1.10](https://github.com/MinecraftForge/MinecraftForge/pull/3444).

**Comment by diesieben07** [comment]
I don't understand what you are referencing in that PR. mezz made the same remark I did and told you to "test and see". To which you said: "Ok" and then the conversation ends.

**Comment by Draco18s** [comment]
> To which you said: "Ok" and then the conversation ends.

My life's been all over the place since summer 2015, so constructing a chain of events at this point is difficult. You are correct that that conversation does do that, but what I mean is, I don't remember what was going on that I never got around to it (or did and never posted). I have literally moved cross country three times, held five different jobs, and bought two new computers.

That said, *that* part had been fixed. However the reason I referenced it was because what I want is to have hopper-like behavior without duplicate 230 lines of private hopper code. Yes, Capabilities is better than IInventory. I have never questioned that. But having to rewrite hopper code to be natively cap driven is ridiculous (and I am having to do it in 1.14--because of ContainerType--and its a huge hassle).

*This* issue is that a *private static function* of the Hopper, consisting of 53 lines and referenced from a public static function (which is itself referenced from BlockDropper as well as the Hopper TE), has an issue correctly combining stacks, as it does not correctly take into account the Hopper's own stack size limits separately from the item stack's stack limits, per the comment on Feb 8. This results in unexpected behavior when subclassing the hopper and giving it a lower stack size limit than 64.

**Comment by DaemonUmbra** [comment]
Is this still the case in 1.14.x and/or 1.15x?

**Comment by Draco18s** [comment]
@DaemonUmbra Haven't checked 1.15, but it does affect 1.14. I had to [completely re-implement the hopper's core functionality](https://github.com/Draco18s/ReasonableRealism/blob/1.14.4/src/main/java/com/draco18s/industry/entity/AbstractHopper.java) so that I could create a "wooden hopper" that could only handle stacks of size 16 correctly (as well as make it use IItemStackHandlers, but that was done just because if I was going to have to reimplement everything, may as well do it "right").

A cursory check of the 1.15 code says that "yes, it is still an issue":

     private boolean isFull() {
        for(ItemStack itemstack : this.inventory) {
           //note the lack of checking this.getInventoryStackLimit()
           if (itemstack.isEmpty() || itemstack.getCount() != itemstack.getMaxStackSize()) {
              return false;
           }
        }
        return true;
     }

and:

         } else if (canCombine(itemstack, stack)) {
         //note the lack of checking destination.getInventoryStackLimit()
            int i = stack.getMaxStackSize() - itemstack.getCount();
            int j = Math.min(stack.getCount(), i);
            stack.shrink(j);
            itemstack.grow(j);
            flag = j > 0;
         }

**Comment by diesieben07** [comment]
My above remark (which was never addressed) also still applies.

**Comment by Draco18s** [comment]
@diesieben07 
*Hopper insertion* respects stack limits (that is, when another hopper inserts an item into it), but not *hopper extraction* and dropped item capture.
https://youtu.be/wm5hwRQk5j4
Having a bit of an issue at the moment getting the mod-hopper to actually tick (and thus show extraction exceeding slot limits), but the captureItem method hooks in differently (and is definitely broken). This was recorded on Forge 1.14.4-28.1.39

Edit, ah that's why:

    public HopperTileEntity() {
        super(TileEntityType.HOPPER);
    }

Can't actually specify the mod TE type, so it doesn't get seen as tickable.

**Comment by pupnewfster** [comment]
@Draco18s I believe this is no longer an issue in 1.15 though feel free to correct me if I am wrong as I am a bit unsure about the exact issue based on the discussion of `IInventory` vs `IItemHandler`. For `IItemHandler`s not being able to insert items past their max stack size even if their slot limit allows for it got fixed in https://github.com/MinecraftForge/MinecraftForge/commit/035c01e2229a1a67e56bc860d0e8004708f5af1e in regards to the vanilla implementation and interaction with `IInventory` (which it seems your complaint was with), from what I can tell that is intended to keep items from stacking past their max stack size (unless already stacked together past it), and would break vanilla mechanics if changed.

**Comment by Draco18s** [comment]
> from what I can tell that is intended to keep items from stacking past their max stack size (unless already stacked together past it), and would break vanilla mechanics if changed.

The issue is not "*the stack* can only stack to 16" (eg. Snowballs) but "*this container* can only hold stacks up to size 16." That is, even if the *stack* had a higher limit, the *slot* had a lower one and hoppers would not respect it. This was important for a hopper variant I had created that had stack size limitations, but could be constructed out of wood. Lowering *the number of slots* doesn't work, as that artificially restricts *different item types* as well.

> `IItemHandlers` not being able to insert items past their max stack size even if their slot limit allows for it got fixed in 035c01e 

That does look like the issue I was reporting being addressed. I will have to double check now that I am aware of that patch.
