### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/network/NetworkRegistry

### ISSUE THREAD

**Issue by npofsi** [MinecraftForge/MinecraftForge#5104]
After install. I launch the game then game crashed and throws this.

**Comment by mattmess1221** [comment]
Please provide a crash report with it. It's no help without it.

**Comment by kierajreed** [comment]
This should go on the forum instead. This issue board is only for issues within Forge itself, not end-user crashes.

**Comment by npofsi** [comment]
I
