### ISSUE TITLE
ItemStack.copy() assigns NBT data after AttachCapabilitiesEvent<ItemStack> is posted

### ISSUE THREAD

**Issue by dmarcuse** [MinecraftForge/MinecraftForge#5110]
When `ItemStack.copy()` is called, it constructs a new `ItemStack` without the item's NBT data, and then afterwards assigns it. This means that when the `AttachCapabilitiesEvent<ItemStack>` event is posted, the item may not have its NBT data. This can prevent subscribers from properly adding capabilities that are dependent on NBT data.

It's not totally clear to me whether this is a bug or intended behavior, but given that `ItemStack(NBTTagCompound)` assigns the NBT _before_ posting the event, it seems like one.

I propose adding a new constructor with the following signature:

```java
ItemStack(Item itemIn, int amount, int meta, @Nullable NBTTagCompound capNBT, @Nullable NBTTagCompound nbtData)
```

 The `nbtData` would then be assigned before `forgeInit` is called and the `AttachCapabilitiesEvent<ItemStack>` is posted. `ItemStack.copy()` would then be updated to use the new constructor instead of assigning NBT data itself after constructing the copy.

**Comment by LexManos** [comment]
Stacks are constructed without NBT all over the place. Your handler should not care about NBT. It would be far to impractical to garentee that valid NBT is added before this event is called.

**Comment by dmarcuse** [comment]
Is there a best practice to handle this case then? Attaching a handler to every item that could potentially have the appropriate NBT seems performance-intensive.

**Comment by KingLemming** [comment]
The best practice is to not have items which rely on NBT to determine their capabilities. Caps should be an inherent part of the item.

**Comment by dmarcuse** [comment]
Unfortunately that's not feasible for my case, adding capabilities from another mod to arbitrary items. Thanks anyways though!

**Comment by KingLemming** [comment]
Yeah, IMO that sorta means you shouldn't be doing that then. Forcing code on other mods is not super kosher.

**Comment by dmarcuse** [comment]
Hmm, I'll look for alternative methods then. Currently I'm using TC6 infusion to add the Forestry `ArmorApiarist` capability to arbitrary pieces of armor, but maybe a bauble would be better.
