### ISSUE TITLE
Could you please remove the 32768 block limit from /fill?

### ISSUE THREAD

**Issue by NoahJelen** [MinecraftForge/MinecraftForge#5124]
I feel like that limit is extremely stupid and is not needed. Can you please make it so Minecraft does not impose that limit on /fill?

**Comment by kierajreed** [comment]
I'm pretty sure there's a reason for that.
If you want a better `/fill`, use WorldEdit.

**Comment by LexManos** [comment]
There are many reasons. Not the least of which is performance. Split things up so you dont murder the server.
