### ISSUE TITLE
I have a pretty recent forge version in my mods folder but in crash logs it says I have a super outdated one.

### ISSUE THREAD

**Issue by Foxxer15** [MinecraftForge/MinecraftForge#5149]
![image](https://user-images.githubusercontent.com/42725256/45596866-f0cfb580-b9ba-11e8-80b4-658909196540.png)
So i've tried to open Minecraft 1.12.2 with a version of forge that should work with the mod 'OutFox', but in crash logs, it shows that the downloaded version of forge is really old and not compatible with OutFox. It works with other mods.

**Comment by raoulvdberge** [comment]
It's not because you have the installer .exe in your mods/ folder that you are on a recent Forge.

This also has to go on the forums and not on the issue tracker.
