### ISSUE TITLE
Patches left to review for 1.13

### ISSUE THREAD

**Issue by tterrag1098** [MinecraftForge/MinecraftForge#5162]
* net.minecraft.advancements:
  - [x] AdvancementManager
  - [x] AdvancementRewards
  - [x] DisplayInfo
  - [x] PlayerAdvancements
* net.minecraft.advancements.critereon:
  - [x] ItemPredicate
* net.minecraft.block:
  - [x] Block
  - [x] BlockBanner
  - [x] BlockBed
  - [x] BlockBush
  - [x] BlockButton
  - [x] BlockCactus
  - [x] BlockChest
  - [x] BlockChorusFlower
  - [x] BlockCocoa
  - [x] BlockCrops
  - [x] BlockDeadBush
  - [x] BlockDoor
  - [x] BlockDoublePlant
  - [x] BlockDragonEgg
  - [x] BlockDropper
  - [x] BlockDynamicLiquid
  - [x] BlockEnchantmentTable
  - [x] BlockEnderChest
  - [x] BlockFalling
  - [x] BlockFarmland
  - [x] BlockFence
  - [x] BlockFenceGate
  - [x] BlockFire
  - [x] BlockFlowerPot
  - [x] BlockGrass
  - [x] BlockHugeMushroom
  - [x] BlockIce
  - [x] BlockLadder
  - [x] BlockLeaves
  - [x] BlockLiquid
  - [x] BlockLog
  - [x] BlockMobSpawner
  - [x] BlockMushroom
  - [x] BlockMycelium
  - [x] BlockNetherWart
  - [x] BlockNewLeaf
  - [x] BlockNote
  - [x] BlockObserver
  - [x] BlockOldLeaf
  - [x] BlockOre
  - [x] BlockPane
  - [x] BlockPistonBase
  - [x] BlockPistonMoving
  - [x] BlockPortal
  - [x] BlockPotato
  - [x] BlockPumpkin
  - [x] BlockQuartz
  - [x] BlockRailBase
  - [x] BlockRailDetector
  - [x] BlockRailPowered
  - [x] BlockRedstoneComparator
  - [x] BlockRedstoneDiode
  - [x] BlockRedstoneOre
  - [x] BlockRedstoneTorch
  - [x] BlockRedstoneWire
  - [x] BlockReed
  - [x] BlockRotatedPillar
  - [x] BlockSapling
  - [x] BlockSkull
  - [x] BlockSlab
  - [x] BlockSnow
  - [x] BlockStairs
  - [x] BlockStaticLiquid
  - [x] BlockStem
  - [x] BlockTallGrass
  - [x] BlockTorch
  - [x] BlockTrapDoor
  - [x] BlockVine
  - [x] BlockWall
  - [x] BlockWeb
  - [x] SoundType
* net.minecraft.block.state:
  - [x] BlockPistonStructureHelper
  - [x] BlockStateBase
  - [x] BlockStateContainer
  - [x] IBlockProperties
* net.minecraft.client:
  - [x] ClientBrandRetriever
  - [x] LoadingScreenRenderer
  - [x] Minecraft
* net.minecraft.client.audio:
  - [x] SoundHandler
  - [x] SoundManager
* net.minecraft.client.entity:
  - [x] AbstractClientPlayer
  - [x] EntityOtherPlayerMP
  - [x] EntityPlayerSP
* net.minecraft.client.gui:
  - [x] FontRenderer
  - [x] GuiBossOverlay
  - [x] GuiButton
  - [x] GuiControls
  - [x] GuiCreateWorld
  - [x] GuiEnchantment
  - [x] GuiIngame
  - [x] GuiIngameMenu
  - [x] GuiKeyBindingList
  - [x] GuiLanguage
  - [x] GuiListWorldSelectionEntry
  - [x] GuiMainMenu
  - [x] GuiMultiplayer
  - [x] GuiOverlayDebug
  - [x] GuiScreen
  - [x] GuiScreenBook
  - [x] GuiScreenDemo
  - [x] GuiSleepMP
  - [x] GuiSlot
  - [x] GuiSpectator
  - [x] GuiUtilRenderComponents
  - [x] GuiVideoSettings
  - [x] MapItemRenderer
  - [x] ServerListEntryNormal
* net.minecraft.client.gui.advancements:
  - [x] GuiAdvancementTab
  - [x] GuiScreenAdvancements
* net.minecraft.client.gui.inventory:
  - [x] GuiContainer
  - [x] GuiContainerCreative
* net.minecraft.client.gui.recipebook:
  - [x] GuiRecipeBook
  - [x] GuiRecipeOverlay
* net.minecraft.client.gui.toasts:
  - [x] RecipeToast
* net.minecraft.client.model:
  - [x] ModelBase
  - [x] ModelBox
  - [x] ModelRenderer
  - [x] PositionTextureVertex
  - [x] TexturedQuad
* net.minecraft.client.multiplayer:
  - [x] ChunkProviderClient
  - [x] GuiConnecting
  - [x] PlayerControllerMP
  - [x] WorldClient
* net.minecraft.client.network:
  - [x] NetHandlerHandshakeMemory
  - [x] NetHandlerLoginClient
  - [x] NetHandlerPlayClient
  - [x] ServerPinger
* net.minecraft.client.particle:
  - [x] Particle
  - [x] ParticleManager
* net.minecraft.client.renderer:
  - [x] ActiveRenderInfo
  - [x] BlockFluidRenderer
  - [x] BlockModelRenderer
  - [x] BlockModelShapes
  - [x] BlockRendererDispatcher
  - [x] BufferBuilder
  - [x] ChestRenderer
  - [x] EntityRenderer
  - [x] InventoryEffectRenderer
  - [x] ItemModelMesher
  - [x] ItemRenderer
  - [x] OpenGlHelper
  - [x] RenderGlobal
  - [x] RenderItem
  - [x] WorldVertexBufferUploader
* net.minecraft.client.renderer.block.model:
  - [x] BakedQuad
  - [x] BakedQuadRetextured
  - [x] FaceBakery
  - [x] IBakedModel
  - [x] ItemCameraTransforms
  - [x] ItemOverrideList
  - [x] ItemTransformVec3f
  - [ ] ModelBakery
  - [x] ModelBlockDefinition
  - [x] ModelManager
  - [x] ModelResourceLocation
  - [x] ModelRotation
  - [x] SimpleBakedModel
  - [x] Variant
  - [x] WeightedBakedModel
* net.minecraft.client.renderer.block.statemap:
  - [x] StateMap
* net.minecraft.client.renderer.chunk:
  - [x] ChunkRenderDispatcher
  - [x] RenderChunk
* net.minecraft.client.renderer.color:
  - [x] BlockColors
  - [x] ItemColors
* net.minecraft.client.renderer.entity:
  - [x] RenderEntityItem
  - [x] RenderFish
  - [x] RenderItemFrame
  - [x] RenderLivingBase
  - [x] RenderManager
  - [x] RenderPlayer
  - [x] RenderVillager
  - [x] RenderZombieVillager
* net.minecraft.client.renderer.entity.layers:
  - [x] LayerArmorBase
  - [x] LayerBipedArmor
  - [x] LayerHeldItem
* net.minecraft.client.renderer.texture:
  - [x] LayeredColorMaskTexture
  - [x] Stitcher
  - [x] TextureAtlasSprite
  - [x] TextureManager
  - [x] TextureMap
  - [x] TextureUtil
* net.minecraft.client.renderer.tileentity:
  - [x] TileEntityItemStackRenderer
  - [x] TileEntityPistonRenderer
  - [x] TileEntityRendererDispatcher
  - [x] TileEntitySpecialRenderer
* net.minecraft.client.renderer.vertex:
  - [x] VertexFormat
  - [x] VertexFormatElement
* net.minecraft.client.resources:
  - [x] FallbackResourceManager
  - [x] IResourceManagerReloadListener
  - [x] Language
  - [x] Locale
  - [x] SimpleReloadableResourceManager
* net.minecraft.client.settings:
  - [x] GameSettings
  - [x] KeyBinding
* net.minecraft.client.shader:
  - [x] Framebuffer
  - [x] ShaderGroup
  - [x] ShaderLoader
  - [x] ShaderManager
* net.minecraft.client.util:
  - [x] RecipeBookClient
  - [x] RecipeItemHelper
* net.minecraft.command:
  - [x] CommandBase
  - [x] CommandFill
  - [x] CommandGameRule
  - [ ] CommandHandler
  - [ ] EntitySelector
* net.minecraft.command.server:
  - [x] CommandSetBlock
* net.minecraft.crash:
  - [x] CrashReport
  - [x] CrashReportCategory
* net.minecraft.creativetab:
  - [x] CreativeTabs
* net.minecraft.enchantment:
  - [x] Enchantment
  - [x] EnchantmentFrostWalker
  - [x] EnchantmentHelper
  - [x] EnchantmentThorns
  - [x] EnumEnchantmentType
* net.minecraft.entity:
  - [ ] Entity
  - [x] EntityAgeable
  - [x] EntityFlying
  - [x] EntityHanging
  - [x] EntityLeashKnot
  - [x] EntityList
  - [x] EntityLiving
  - [x] EntityLivingBase
  - [x] EntitySpawnPlacementRegistry
  - [x] EntityTracker
  - [x] EntityTrackerEntry
  - [x] SharedMonsterAttributes
* net.minecraft.entity.ai:
  - [x] EntityAIAttackMelee
  - [x] EntityAIBreakDoor
  - [x] EntityAIEatGrass
  - [x] EntityAIHarvestFarmland
  - [x] EntityAIMate
  - [x] EntityAIRunAroundLikeCrazy
  - [x] EntityAIVillagerMate
* net.minecraft.entity.boss:
  - [x] EntityDragon
  - [x] EntityWither
* net.minecraft.entity.boss.dragon.phase:
  - [x] PhaseSittingFlaming
* net.minecraft.entity.effect:
  - [x] EntityLightningBolt
* net.minecraft.entity.item:
  - [x] EntityArmorStand
  - [x] EntityBoat
  - [x] EntityEnderPearl
  - [x] EntityFallingBlock
  - [x] EntityItem
  - [x] EntityItemFrame
  - [x] EntityMinecart
  - [x] EntityMinecartCommandBlock
  - [x] EntityMinecartContainer
  - [x] EntityMinecartEmpty
  - [x] EntityMinecartFurnace
  - [x] EntityMinecartHopper
  - [x] EntityMinecartMobSpawner
  - [x] EntityXPOrb
* net.minecraft.entity.monster:
  - [x] EntityCreeper
  - [x] EntityEnderman
  - [x] EntityEvoker
  - [x] EntityIronGolem
  - [x] EntityMagmaCube
  - [x] EntityMob
  - [x] EntityShulker
  - [x] EntitySilverfish
  - [x] EntitySlime
  - [x] EntitySnowman
  - [x] EntitySpider
  - [x] EntityZombie
  - [x] EntityZombieVillager
* net.minecraft.entity.passive:
  - [x] AbstractHorse
  - [x] EntityHorse
  - [x] EntityMooshroom
  - [x] EntityOcelot
  - [x] EntityParrot
  - [x] EntityRabbit
  - [x] EntitySheep
  - [x] EntityVillager
  - [x] EntityWolf
  - [x] HorseArmorType
* net.minecraft.entity.player:
  - [ ] EntityPlayer
  - [ ] EntityPlayerMP
  - [x] InventoryPlayer
* net.minecraft.entity.projectile:
  - [x] EntityArrow
  - [x] EntityFireball
  - [x] EntityFishHook
  - [x] EntityLargeFireball
  - [x] EntityLlamaSpit
  - [x] EntityShulkerBullet
  - [x] EntitySmallFireball
  - [x] EntityThrowable
  - [x] EntityWitherSkull
* net.minecraft.init:
  - [x] Bootstrap
* net.minecraft.inventory:
  - [x] Container
  - [x] ContainerBeacon
  - [x] ContainerBrewingStand
  - [x] ContainerEnchantment
  - [x] ContainerPlayer
  - [x] ContainerRepair
  - [x] Slot
  - [x] SlotCrafting
  - [x] SlotFurnaceOutput
* net.minecraft.item:
  - [x] Item
  - [x] ItemArmor
  - [x] ItemArrow
  - [x] ItemAxe
  - [x] ItemBed
  - [x] ItemBlock
  - [x] ItemBlockSpecial
  - [x] ItemBow
  - [x] ItemBucket
  - [x] ItemBucketMilk
  - [x] ItemDoor
  - [x] ItemDye
  - [x] ItemFlintAndSteel
  - [x] ItemHoe
  - [x] ItemLilyPad
  - [x] ItemMap
  - [x] ItemMinecart
  - [x] ItemSeedFood
  - [x] ItemSeeds
  - [x] ItemShears
  - [x] ItemSkull
  - [x] ItemSlab
  - [x] ItemSnow
  - [x] ItemStack
  - [x] ItemSword
  - [x] ItemTool
* net.minecraft.item.crafting:
  - [x] CraftingManager
  - [x] FurnaceRecipes
  - [x] IRecipe
  - [x] Ingredient
  - [x] RecipeBookCloning
  - [x] RecipeFireworks
  - [x] RecipeRepairItem
  - [x] RecipeTippedArrow
  - [x] RecipesArmorDyes
  - [x] RecipesBanners
  - [x] RecipesMapCloning
  - [x] ShapedRecipes
  - [x] ShapelessRecipes
  - [x] ShieldRecipes
  - [x] ShulkerBoxRecipes
* net.minecraft.nbt:
  - [x] CompressedStreamTools
  - [x] NBTSizeTracker
  - [x] NBTTagCompound
  - [x] NBTTagList
  - [x] NBTTagString
* net.minecraft.network:
  - [ ] NetHandlerPlayServer
  - [ ] NettyPacketEncoder
  - [ ] NetworkManager
  - [ ] NetworkSystem
  - [ ] PacketBuffer
  - [x] ServerStatusResponse
* net.minecraft.network.datasync:
  - [x] EntityDataManager
* net.minecraft.network.handshake.client:
  - [ ] C00Handshake
* net.minecraft.network.login.server:
  - [ ] SPacketLoginSuccess
* net.minecraft.network.play.client:
  - [ ] CPacketClickWindow
  - [ ] CPacketCreativeInventoryAction
  - [ ] CPacketCustomPayload
* net.minecraft.network.play.server:
  - [ ] SPacketCustomPayload
  - [ ] SPacketSpawnMob
* net.minecraft.pathfinding:
  - [x] FlyingNodeProcessor
  - [x] WalkNodeProcessor
* net.minecraft.potion:
  - [x] Potion
  - [x] PotionEffect
  - [x] PotionHelper
  - [x] PotionType
* net.minecraft.profiler:
  - [x] Profiler
* net.minecraft.realms:
  - [x] RealmsConnect
* net.minecraft.server:
  - [x] MinecraftServer
* net.minecraft.server.dedicated:
  - [x] DedicatedServer
  - [x] ServerHangWatchdog
* net.minecraft.server.gui:
  - [x] MinecraftServerGui
* net.minecraft.server.integrated:
  - [x] IntegratedServer
* net.minecraft.server.management:
  - [x] PlayerChunkMapEntry
  - [x] PlayerInteractionManager
  - [ ] PlayerList
* net.minecraft.server.network:
  - [ ] NetHandlerHandshakeTCP
  - [ ] NetHandlerLoginServer
* net.minecraft.stats:
  - [ ] RecipeBook
  - [ ] RecipeBookServer
  - [ ] StatList
* net.minecraft.tileentity:
  - [x] MobSpawnerBaseLogic
  - [ ] TileEntity
  - [x] TileEntityBeacon
  - [x] TileEntityBrewingStand
  - [x] TileEntityChest
  - [x] TileEntityFurnace
  - [x] TileEntityHopper
  - [x] TileEntityLockable
  - [x] TileEntityLockableLoot
  - [x] TileEntityNote
  - [x] TileEntityPiston
  - [x] TileEntityShulkerBox
  - [x] TileEntitySign
* net.minecraft.util:
  - [x] ActionResult
  - [x] BlockRenderLayer
  - [x] ChatAllowedCharacters
  - [x] ClassInheritanceMultiMap
  - [x] EnumFacing
  - [x] IntIdentityHashBiMap
  - [x] MouseHelper
  - [x] ScreenShotHelper
  - [x] ServerRecipeBookHelper
  - [x] Session
  - [x] SoundEvent
  - [x] TabCompleter
* net.minecraft.util.datafix:
  - [x] DataFixesManager
* net.minecraft.util.math:
  - [x] RayTraceResult
  - [x] Vec3d
* net.minecraft.util.text:
  - [x] ITextComponent
  - [x] Style
  - [x] TextComponentBase
* net.minecraft.util.text.translation:
  - [x] LanguageMap
* net.minecraft.village:
  - [ ] Village
  - [ ] VillageCollection
* net.minecraft.world:
  - [x] BossInfo
  - [x] BossInfoServer
  - [x] ChunkCache
  - [x] DimensionType
  - [x] Explosion
  - [x] IBlockAccess
  - [x] ServerWorldEventHandler
  - [x] Teleporter
  - [x] World
  - [x] WorldEntitySpawner
  - [ ] WorldProvider
  - [x] WorldProviderEnd
  - [x] WorldProviderSurface
  - [x] WorldServer
  - [x] WorldServerMulti
  - [x] WorldType
* net.minecraft.world.biome:
  - [x] Biome
  - [x] BiomeDecorator
  - [x] BiomeDesert
  - [x] BiomeForest
  - [x] BiomeHills
  - [x] BiomeJungle
  - [x] BiomeMesa
  - [x] BiomePlains
  - [x] BiomeProvider
  - [x] BiomeSavanna
  - [x] BiomeSnow
  - [x] BiomeSwamp
  - [x] BiomeTaiga
* net.minecraft.world.border:
  - [x] WorldBorder
* net.minecraft.world.chunk:
  - [x] BlockStateContainer
  - [ ] Chunk
* net.minecraft.world.chunk.storage:
  - [x] AnvilChunkLoader
  - [x] AnvilSaveHandler
  - [x] ExtendedBlockStorage
  - [x] RegionFile
* net.minecraft.world.end:
  - [x] DragonFightManager
* net.minecraft.world.gen:
  - [x] ChunkGeneratorEnd
  - [x] ChunkGeneratorFlat
  - [x] ChunkGeneratorHell
  - [x] ChunkGeneratorOverworld
  - [ ] ChunkProviderServer
  - [ ] MapGenCaves
  - [ ] MapGenRavine
* net.minecraft.world.gen.feature:
  - [x] WorldGenAbstractTree
  - [x] WorldGenBigMushroom
  - [x] WorldGenBigTree
  - [x] WorldGenBirchTree
  - [x] WorldGenBush
  - [x] WorldGenCanopyTree
  - [x] WorldGenDeadBush
  - [x] WorldGenDungeons
  - [x] WorldGenGlowStone1
  - [x] WorldGenGlowStone2
  - [x] WorldGenHellLava
  - [x] WorldGenHugeTrees
  - [x] WorldGenIceSpike
  - [x] WorldGenLakes
  - [x] WorldGenLiquids
  - [x] WorldGenMegaJungle
  - [x] WorldGenMegaPineTree
  - [x] WorldGenMinable
  - [x] WorldGenSavannaTree
  - [x] WorldGenShrub
  - [x] WorldGenSwamp
  - [x] WorldGenTaiga1
  - [x] WorldGenTaiga2
  - [x] WorldGenTallGrass
  - [x] WorldGenTrees
  - [x] WorldGenerator
  - [x] WorldGeneratorBonusChest
* net.minecraft.world.gen.layer:
  - [x] GenLayer
  - [x] GenLayerBiome
* net.minecraft.world.gen.structure:
  - [ ] MapGenStronghold
  - [ ] MapGenStructure
  - [x] StructureComponent
  - [x] StructureStart
  - [x] StructureVillagePieces
* net.minecraft.world.gen.structure.template:
  - [x] Template
* net.minecraft.world.storage:
  - [x] DerivedWorldInfo
  - [x] MapData
  - [x] MapDecoration
  - [x] SaveFormatOld
  - [x] SaveHandler
  - [x] WorldInfo
  - [x] WorldSavedData
* net.minecraft.world.storage.loot:
  - [x] LootContext
  - [x] LootEntry
  - [x] LootEntryEmpty
  - [x] LootEntryItem
  - [x] LootEntryTable
  - [x] LootPool
  - [x] LootTable
  - [x] LootTableManager
* net.minecraft.world.storage.loot.conditions:
  - [x] LootConditionManager
  - [x] RandomChanceWithLooting
* net.minecraft.world.storage.loot.functions:
  - [x] LootingEnchantBonus

**Comment by williewillus** [comment]
not a patch, but `IThrowableEntity` and its supporting code should go. It looks like extremely old compat code, and nothing uses it.

**Comment by williewillus** [comment]
Additionally, I also think the old `BrewingRecipeRegistry` (and its patches to vanilla) can go as well. Looking at the interfaces provided in `IBrewingRecipe`, it's superseded completely by the vanilla systems in PotionHelper, since now we have flexible `Ingredient`s that can be extended for arbitrary matching behaviour

**Comment by Shadows-of-Fire** [comment]
I think it would be a good idea to remove all the patches from `TileEntityItemStackRenderer` and move to a forge-owned item renderer class, preferably with more context.

**Comment by chylex** [comment]
`Block.addLandingEffects` has a duplicate `IBlockState` parameter, this would be good to fix for the major version update: [EntityLivingBase.java.patch#L28](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch#L28)

**Comment by NQNStudios** [comment]
Hi all! I'm a dev working with an academic research team that uses Forge for modding. Soon I'll have the time and energy that I could contribute back to Forge; our work would benefit by having 1.13 support so I'd be down to help with that. Is this issue the basic roadmap for the upgrade?

**Comment by mezz** [comment]
The current work is extremely specialized, and mostly being done by Lex and cpw.
We will be more open to contributions once the patches have been ported and things have stabilized a little bit. Until then there is not really a way to help out.

This issue is difficult to maintain so I am not sure it reflects the current progress, you can directly see the state of patch porting progress here (updated yesterday): https://github.com/MinecraftForge/MinecraftForge/commit/b687180e12f6b8292b406e26447c6fcfd9bd7317

**Comment by chimericdream** [comment]
@mezz @LexManos @cpw 

Once things are a little closer (i.e. patches ported and things stabilized as you mentioned), will there be any kind of "here's how you can help" document or issue? I'm an experienced Java developer, but something as big as Forge is so daunting that it's hard to know where to start. For as much as I have gotten from Forge and the modding community, I'd love to help out in whatever ways I can.

Keep up the good work, and thanks for everything you've done so far!

**Comment by mezz** [comment]
The project is too big to jump in at random, so I am starting to look for things to fix in Forge by trying to port mods. I quickly ran into things that are missing or not working. When things are more stable next month, more modders will be trying to port their mods and reporting issues in the tracker here, and there should be plenty to take a look at!

**Comment by Noiwex** [comment]
Why is it like this nowadays? I remember back in the old days you needed to wait 1 week max after update to play modded minecraft. Now, half a year passed and there's still no mod support for 1.13. Is minecraft modding dying?

**Comment by Noiwex** [comment]
Why was my comment deleted?

**Comment by NQNStudios** [comment]
Now that this is closed, what does that mean for the 1.13 release? Any way I or the rest of my research team can help out?

**Comment by Shadows-of-Fire** [comment]
It means the main patchwork has been done, forge is now currently in a stage of bugfixing and feature addition in the form of PR's.  Any issues that can be reproduced with just forge should be reported to the tracker with either an accompanying PR or reproruction steps so someone else can make a PR.

**Comment by tterrag1098** [comment]
Forge for 1.13.2 is released as a beta. Any further patches are on the backburner or not necessary. This part of the port is complete. As for what needs to be done, there are lots of open issues tagged "1.13" that need to be fixed, and lots of other things yet to be discovered I'm sure. Discord is a great place to communicate about what needs doing.
