### ISSUE TITLE
[1.13] About support Java9 or above

### ISSUE THREAD

**Issue by NekoCaffeine** [MinecraftForge/MinecraftForge#5174]
Will Forge support Java9 or above at 1.13?
If you don't plan, can I send a pull request to provide support?
Java SE 11 is the next LTS release, so I think it is necessary to support.
For example, ZGC([JEP 333](http://openjdk.java.net/jeps/333)) is still great.

**Comment by 3TUSK** [comment]
Yes. (If the citation is valid)

Citation: https://gist.github.com/xt9/55a04226728cebe729fe37cc7aa9d10f#113-general
