### ISSUE TITLE
[1.12.2] pressure plate emit at least 1 signal.

### ISSUE THREAD

**Issue by Tronif** [MinecraftForge/MinecraftForge#5175]
forge : 14.23.4.2765

According to the title.
pressure plate works correctly at forge version 14.23.4.2759.

**Comment by liach** [comment]
do you mean it no longer emits redstone signal? what pressure plate do you mean?

**Comment by LexManos** [comment]
![https://puu.sh/BFtnE/90dc7e688c.png](https://puu.sh/BFtnE/90dc7e688c.png)
Iron outputs a little because villagers suffocate when I add more.
