### ISSUE TITLE
[1.13] Allow easy removals from tags with json

### ISSUE THREAD

**Issue by liach** [MinecraftForge/MinecraftForge#5178]
The 1.13 tags can be added easily but cannot be removed with ease. I wish forge can add a way to remove tag entries.

Use case: Removal of blocks from enderman carry list

**Comment by LexManos** [comment]
That is what the replace argument is for in the json.
Going into chains of "who wins" when it comes to adding and removing is bad.
At the end of the day if you remove you should be the authority, likely being the  single end mod pack creator.

**Comment by liach** [comment]
the issue is that if two mods want to replace tags at the same time, one of them will fail due to order, much like what happens to fluid block mapping right now

**Comment by LexManos** [comment]
Neither would fail. Its just the last one would take precedence. This is intentional design by the Mojang team in how they wanted data packs to interact with the tag system.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/220bf8730a58cdd7fca14b46e1018953cb0d2568
