### ISSUE TITLE
[1.13][Enhancement] Make ObjectHolders more general

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#5183]
1.13 brings the flattening, which means mods will generally have a lot more item and block instances around.

Doing things "right" to handle replacements would involve writing all of these instances out as fields and sticking ObjectHolder on them, which is way too much boilerplate. Especially if your mod deals with having everything come in 16 variants for each color, so we stuff them into a map keyed by EnumMapColor or something. And some mods have items with tons of meta-variants that could never be enumerated flattened out (unless you want multi-thousand line java files).

Can't we just have a simple and general "post registry event" fired when the registry and all replacements are settled stable, so we can pull things out of the registry and stick them into maps and fields? It really doesn't have to be all magical and annotation-y to be useful.

Right now there's a steep tradeoff between doing it right and doing it conveniently. Modders will pick the latter every time, so let's make doing it right easier and more convenient.

cc @InsomniaKitten

**Comment by marvin-roesch** [comment]
IIRC, https://github.com/MinecraftForge/MinecraftForge/blob/1.13-pre/src/main/java/net/minecraftforge/fml/RegistryObject.java is the replacement (or rather intended backend) for ObjectHolder in 1.13.

**Comment by Daomephsta** [comment]
@williewillus ObjectHolder doesn't need to go on every field, it can also go on the class, in which case value should be the modid. It then gets registry object names by lowercasing the field names and using the value of the class level ObjectHolder as the domain.

**Comment by bs2609** [comment]
> Can't we just have a simple and general "post registry event" fired when the registry and all replacements are settled stable, so we can pull things out of the registry and stick them into maps and fields?

We already have `FMLModIdMappingEvent`, which basically serves this purpose?

**Comment by williewillus** [comment]
@Daomephsta 
It still requires a field per item

@bs2609 
nice, wasn't aware of that (it's pretty badly named)

**Comment by williewillus** [comment]
the event will do, I guess
