### ISSUE TITLE
[Suggestion] Improve Version JSON

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#5186]
1)GZIP Support:
As most version JSON are hosted on webservers which can be enabled to use gzip, we could support gzip downloading. This could decrease download times as the files are smaler. 

PR:
In ForgeVersion$1#openUrlStream (L:213) add:
`con.setRequestProperty("Accept-Encoding", "gzip");`
And
```
if ("gzip".equals(con.getContentEncoding())) 
    in = new GZIPInputStream(con.getInputStream());
```

2)Json array support
Currently multiline changes are a single String connected with \n, we could simply add support for a JSON array, then it would be better readable.
PR:
In ForgeVersion$1 L:313
`Map<String, String> tmp = (Map<String, String>)json.get(MinecraftForge.MC_VERSION);`
we would need a Map<String, Object> and check if if the Object is an Array and just use either toString or Arrays.toDeepString on it.

**Comment by williewillus** [comment]
Are update jsons big enough that gzip actually helps without adding extra overhead?

**Comment by mcenderdragon** [comment]
In my case they are, and such things can be handled by the webserver. (It is linked to our git server so as soon as we have 10 versions, the size diff is noticeable)

**Comment by mcenderdragon** [comment]
For example: you are running an dold version (lets say 210) the changelog will look like [this ](https://redsnake-games.de/fpgit/Futurepack/Updates.php?version=26.3.210). For the most recent version only like [this](https://redsnake-games.de/fpgit/Futurepack/Updates.php?version=26.3.417). 

According to Mozilla Net Logger: 
(210) 28,06 KB uncompressed,  9,02 KB compressed.
(417) 2,79 KB down to 1,40 KB

**Comment by malte0811** [comment]
About the second point: why do you want the update JSON to be (human) readable? If you want a changelog for humans to (directly) read something like markdown is much more suitable, and it isn't hard to generate an update JSON from that changelog (as long as the markdown changelog uses a consistent format). That's what we do in IE and it works quite well for everything (including weird things like including the changelog up to the current version as a JSON in the mod file).

**Comment by mcenderdragon** [comment]
The json array thing is only personal I guess, it feels better if its an json array, but mainly my point is about the compression.
