### ISSUE TITLE
[Suggestion] Sweeping Attack Event

### ISSUE THREAD

**Issue by Quarris** [MinecraftForge/MinecraftForge#5193]
Currently you can access the AttackEntityEvent and cancel the entity being hit, but that doesn't mean that the target won't get hit using sweeping attack if you attack a different target. It would be nice to have an event that fires when an entity is being hit by a sweeping attack, and be able to cancel it and modify it in some ways.

**Comment by UpcraftLP** [comment]
indeed, this would be a good feature.
maybe as well let that event modify the damage ratio that's applied for the sweep attack

**Comment by Alpvax** [comment]
We could add a nullable secondaryTargets collection to the current event. Or have a secondaryEffect field which could be assigned a sweep effect.
I think improving the current event (in a non breaking way) would be better, as that way you could e.g. increase the damage based on the number of targets hit.
