### ISSUE TITLE
Crash in Main Menu

### ISSUE THREAD

**Issue by TimGoll** [MinecraftForge/MinecraftForge#5194]
I spent quite some time tracking down this issue and I'm not sure where it comes from. Some googling said it was forge. Forge forge-1.12.2-14.23.4.2760 works but forge-1.12.2-14.23.4.2765, forge-1.12.2-14.23.4.2768 and forge-1.12.2-14.23.4.2770 all crash with this issue. Disabling Optifine and Foamfix didn't help either.

Issue on the web: https://www.minecraftforum.net/forums/support/java-edition-support/2929511-crash-on-main-menu

My Issue: https://gist.github.com/TimGoll/31267ab92dc022765c9e93e100831618

**Comment by Mrbysco** [comment]
Try the forge support forum

**Comment by TimGoll** [comment]
Thanks, I didn't know about this forum. I found the [same issue](http://www.minecraftforge.net/forum/topic/66908-game-crash-at-main-menu/) in this forum. At least I'm not alone. It seems to be caused by better foliage
