### ISSUE TITLE
[1.13?] Block.getRenderBoundingBox should be relative

### ISSUE THREAD

**Issue by Player3324** [MinecraftForge/MinecraftForge#5199]
Currently the method yields an AABB with absolute coordinates, which doesn't allow caching the return value globally and is inconsistent with vanilla having changed most other AABBs to be relative.

**Comment by LexManos** [comment]
You're referring to TileEntity.getRenderBoundingBox, as Block doesn't have said function.
As they are TEs you can cache this value in the TE itself.
The trade off is some RAM for less RAM & CPU usage.
So we're keeping it absolute.
