### ISSUE TITLE
[Documentation] Error page when trying to search on readthedocs webpage

### ISSUE THREAD

**Issue by Lothrazar** [MinecraftForge/MinecraftForge#5205]
Whenever I try to search on the "readthedocs.io" webpage I get "sorry this sorry does not exist"

https://mcforge.readthedocs.io/en/latest/search.html?q=block
https://mcforge.readthedocs.io/en/latest/search.html?q=village
https://mcforge.readthedocs.io/en/latest/search.html?q=item

I was told these docs are official and this search should work.

**Comment by TehNut** [comment]
Report this on the Documentation project https://github.com/MinecraftForge/Documentation
