### ISSUE TITLE
CullFace Issue when picking up EntityItem

### ISSUE THREAD

**Issue by NullSector76** [MinecraftForge/MinecraftForge#5208]
Forge Version:2702

issue: when picking up a block very visible with the mob spawner cullface changes and your able to see all 6 sides of the block for a split second.**it's not reproducable in vanilla 1.12.2 or older versions of minecraft with forge** This is a recent issue please fix it. 

*Yes there are no other mods besides forge installed.*

Steps to reproduce:
get a spawner
look down
throw spawner
wait for it to be in transition for pickup and observe cullface acting up

pic:
![2018-10-31_18 57 03_2](https://user-images.githubusercontent.com/38586645/47825246-d40af980-dd3e-11e8-8d7a-7a6bc808b533.png)

**Comment by liach** [comment]
Isn't the mob spawner meant to be translucent?

**Comment by NullSector76** [comment]
yes but, the cullface changes when in transition of being picked up. it's a
bug not suppose to happen unless your in f5 mode
