### ISSUE TITLE
New Event - Item/Entity Out Of World

### ISSUE THREAD

**Issue by liketechnik** [MinecraftForge/MinecraftForge#5215]
I wanted to write a mod for skyblock worlds that counts the items a player throws into the void and after a certain amount summons a mob next to the player. Problem: It seems like there is no easy way to detect if an item was thrown into the void, e. g.  it fell out of the world and got despawned.

I already looked how this is handled in forge/vanilla code and it seems fairly easy to add an event for this case. If the general idea would be accepted, I'd prepare a PR with the necessary changes.

**Comment by liach** [comment]
I suggest listening to entity death events (through forge or IWorldEventListener) and see which ones have y positions less than zero.

**Comment by liach** [comment]
~~An alternative is to check [`LivingDeathEvent`'s damage source](https://github.com/MinecraftForge/MinecraftForge/blob/f9c2f715fd63bed9d4bd78b332ed348ad7383a30/src/main/java/net/minecraftforge/event/entity/living/LivingDeathEvent.java#L51) and see if its source is void (out of world) damage. However, it cannot identify if the damage source is the `/kill` command.~~

Uh no, an item is not a mob, so the content above in this comment does not apply.

**Comment by liach** [comment]
This issue appears not to be closed properly.
