### ISSUE TITLE
A single server tick takes 60s

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [MinecraftForge/MinecraftForge#5218]
https://pastebin.com/wmGSdB4S

**Comment by Niko-sk2x** [comment]
It probably doesn't. It's most likely detected as such because of a vanilla bug (happens when server is running a few times slower than it should for some amount of time).

**Comment by LordRalex** [comment]
Watchdog is not a bug, it is a feature of the vanilla server which is that if a single tick takes more than max-tick-time, then the server is assumed to be crashed and it kills it.

This is exactly what the error means, and it's not a bug. Your server took too long to do something.

**Comment by Nessiesson** [comment]
@LordRalex: [not necessarily](https://bugs.mojang.com/browse/MC-121586)
