### ISSUE TITLE
update 2761 player/vehicle patch causes weapons to aim incorrectly while in vehicle

### ISSUE THREAD

**Issue by m1k3s** [MinecraftForge/MinecraftForge#5232]
With the PaperMC patches applied for player/vehicle sync, this causes the bow to aim in the direction (Yaw and Pitch) of the vehicle not the player. 
My parachute mod allows shooting the bow from the parachute and as of update 2761 the bow now aims with the parachute and not the player. The patched code in minecraft/network/NetHandlerPlayServer.java on lines 399 and 405 sync the player yaw and pitch with the vehicle. The bow fires the arrow using the players yaw and pitch in ItemBow.java on line 117. 
This is in Forge version forge-1.12.2-14.23.4.2761.

**Comment by ghost** [comment]
https://minecraft.curseforge.com/projects/the-flying-things/issues/5
same here
