### ISSUE TITLE
Remove mojang server blacklist from forge

### ISSUE THREAD

**Issue by raedainfossaest** [MinecraftForge/MinecraftForge#5247]
Forge should not include a component enforcing an arbitrary server blacklist from mojang, especially when that component gives a fake "Network is unreachable" error message when you attempt to connect. Note that the addons to netty are now called com.mojang:patchy:1.1 in the version jsons.

**Comment by FinnT730** [comment]
Mate, this is not forge doing that, go to Minecraft bug report and complain there! Mojang added that for a reason, because some servers let you l pay for nothing in return. I would say, if kids go on those servers, parents would become angry...

**Comment by LexManos** [comment]
For Future reference, No the blacklist isn't arbitrary, it's for servers that break the EULA.
And no, we will never include anything that works around Mojang's express wishes like that.
Especially for servers that EXPLICITLY sell ours/Mojangs/others work for profit. Which is what most of them on that list are there for.
