### ISSUE TITLE
Add hook for getting villager professions with unknown ID

### ISSUE THREAD

**Issue by UpcraftLP** [MinecraftForge/MinecraftForge#5252]
Currently, there's only `VillagerProfession#getRandomCareer()` and `VillagerProfession#getCareer()`, however there is no way to remove the professions or to iterate through them.
Since the ID is assigned dynamically, there is also no way to get a specific modded career (vanilla careers pretty much have static IDs),
and since there is no getSize() exposed for the career list, one cannot easily iterate over all careers.

**Comment by bs2609** [comment]
So, something like a `getCareer(String)` method to get a career by name and perhaps a view-returning `getCareers()` method to see all careers?

**Comment by UpcraftLP** [comment]
ideally, yes, however that'd need to change the `careers` list to a map.
So I'd be fine with just getting access to that list, or the size of it at least so I can properly iterate over it.

**Comment by bs2609** [comment]
A map can be added, but as the number of careers is probably quite small, simple linear searching of the list would probably be fine anyway.
