### ISSUE TITLE
Latest Version of Forge prevents Minecraft from even Starting up

### ISSUE THREAD

**Issue by ScienceDrummer** [MinecraftForge/MinecraftForge#5263]
I'll launch Minecraft in Technic launcher, it'll start using up CPU and RAM in Task manager and then CPU usage will go down to 0 and RAM will remain at around 666,000K and just stay there until I manually end the task.

Forge Version(s): 14.23.5.2781+

Log: https://paste.dimdev.org/otosikahon.md

**Comment by tterrag1098** [comment]
Optifine is broken with new forge versions.
