### ISSUE TITLE
PotionRemoveEvent doesn't fire when clearing effects by command or milk

### ISSUE THREAD

**Issue by CammiePone** [MinecraftForge/MinecraftForge#5264]
I was using the new potion events, and when I did /effect Player clear, to see if the remove event fired properly, it didn't fire. It also doesn't fire when you drink milk to remove potion effects, or when a potion effect expires naturally.

Forge version is: 14.23.5.2794
Mappings is: stable_39

**Comment by mcenderdragon** [comment]
we probaply want to hook into `EntityLivingBase#onFinishedPotionEffect`

**Comment by CammiePone** [comment]
That would probably be good. And probably whatever /effect (player) clear and milk do when removing potion effects. I'm so glad for these new events, though. They are a life saver!

**Comment by mcenderdragon** [comment]
And performance improvers ^^.

**Comment by mcenderdragon** [comment]
Do you need to cancel them on only get notified ?

**Comment by CammiePone** [comment]
I just need to send a packet using them.

**Comment by tterrag1098** [comment]
The problem with `onFinishedPotionEffect` is that it does not have a result and thus is not cancelable. I'm working on improving the API of this event set however.

**Comment by CammiePone** [comment]
Good luck!

**Comment by tterrag1098** [comment]
Resolved via https://github.com/MinecraftForge/MinecraftForge/commit/dd27209565fd86d46ad91c5d36d202b704f0632c
