### ISSUE TITLE
Error I noticed when leaving server NETTY

### ISSUE THREAD

**Issue by RainOfPain125** [MinecraftForge/MinecraftForge#5288]
When leaving - https://pastebin.com/cSWqRHYM
When joining - https://pastebin.com/zWTVxdPT

**Comment by Shybella** [comment]
Netty is loaded with issues in 1.12 - I think this has been resolved more in 1.13

**Comment by RainOfPain125** [comment]
@Shybella This is a 1.12.2 modpack. There is no possible way for me to simply go onto 1.13

**Comment by tterrag1098** [comment]
Seems like issues with IngameInfoXML, a mod, not forge.
