### ISSUE TITLE
ForgeHooks method isInsideOfMaterial() behaves wrongly for down flowing liquids

### ISSUE THREAD

**Issue by oOMitchOo** [MinecraftForge/MinecraftForge#5292]
If a player hops into my custom fluid block (which is an instance of BlockFluidClassic by Forge), and the fluid is flowing down from a source block, the player only starts drowning inside the source, the drowning flickers on and off, when the player swims through the flowing fluid blocks under the source block, though they also fill the whole block space.

I think the error lies in ((IFluidBlock)block).getFilledPercentage(), which is used, when the block is a forge liquid (instanceof IFluidBlock).
The hook should rather use a method like getFluidHeightForRender() (which isn't in IFluidBlock though, but in BlockFluidBase).

I mean, I can always override getFilledPercentage() for my extension of BlockFluidClassic, but I don't think it is intended the way it is now.

**Comment by bs2609** [comment]
This was most likely fixed a while ago by #5206, have you actually tested this on the current version?

**Comment by oOMitchOo** [comment]
Yes, you're right. I'm sorry, it didn't look like it changed.
