### ISSUE TITLE
[1.13] Cannot set an Item's container item to itself

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#5305]
Setting the container item must be done through `Builder`, and we can't reference the Item until it's done being constructed.

trying to do tricks like `super(builder.containerItem(this));` doesn't work either, java complains that the superclass constructor must complete before we use `this`

**Comment by williewillus** [comment]
as an aside, items being their own container items is a common technique in the past to have items that are not consumed when used in a recipe (or take damage, etc.)

**Comment by liach** [comment]
we can change this to refer to an id instead, like how advancement builders refer to their parents. in the long run, we should aim to replace this functionality with ingredients that support custom remainder items.

Edit: my long-run suggestion is #4449

**Comment by williewillus** [comment]
actually this is a non-problem.
Although you can't use the builder to set container item to itself you can just override getContainerItem instead.
