### ISSUE TITLE
[1.13] Useful Block.Builder methods are protected

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#5310]
Only 2-3 methods are public and thus usable from mod code, everything else can't be called
![cap](https://user-images.githubusercontent.com/2015032/50531085-98847580-0aca-11e9-83b3-3af3eb3e5264.jpg)

**Comment by EmosewaPixel** [comment]
Being on the topic of Builders, maxDamage() in Item.Builder is private.

**Comment by williewillus** [comment]
Resolved
