### ISSUE TITLE
[1.13] Cannot create FluidStacks of vanilla fluids

### ISSUE THREAD

**Issue by TheLimePixel** [MinecraftForge/MinecraftForge#5314]
Currently there are 2 types of fluids, minecraft.fluid.Fluid and minecraftforge.fluids.Fluid, which seem incompatible with each other. Vanilla fluids are of the first type and FluidStacks take the second type, making it so you can't create a fluidstack of water or lava.

**Comment by TeamSpen210** [comment]
This is still an issue in current Forge. It might make sense to remove `minecraftforge.fluids.Fluid` and move everything that was there into `minecraftforge.common.extensions.IForgeFluid`, so they're both effectively the same? This [Fluid Rewrite](https://github.com/MinecraftForge/MinecraftForge/projects/1) project also seems relevant.

**Comment by gigaherz** [comment]
The new forge fluid system has now landed and is ready for testing.
