### ISSUE TITLE
Minecraft server crashes 

### ISSUE THREAD

**Issue by DEDarkLightZ** [MinecraftForge/MinecraftForge#5318]
Hello, when i start my minecraft forge server it crashes instantly. I use the minecraft 1.7.10
[fml-server-latest.log](https://github.com/MinecraftForge/MinecraftForge/files/2719598/fml-server-latest.log)

**Comment by FinnT730** [comment]
You should upgrade, Bauble's is not able to be download because Dropbox deleted the file on there site. You should upgrade you're server and game to 1.12.2, because mod-makers won't support MC 1.7.10 anymore because it is out-dated.
