### ISSUE TITLE
[1.13] RuntimeEnumExtender references deleted EnumHelper class

### ISSUE THREAD

**Issue by JDLogic** [MinecraftForge/MinecraftForge#5321]
It appears that EnumHelper was accidentally deleted in this commit c4cf950863256ed048a46e098401a969dfe4cb2e as it is still used in RuntimeEnumExtender.

https://github.com/MinecraftForge/MinecraftForge/blob/6baddc7e261d959301392e02787cea4aebd1d986/src/fmllauncher/java/net/minecraftforge/common/asm/RuntimeEnumExtender.java#L184

**Comment by tterrag1098** [comment]
It was not accidental, we just need to resurrect that one method and place it elsewhere.

**Comment by tterrag1098** [comment]
I have a proposed patch here: https://github.com/tterrag1098/MinecraftForge/commit/f86551a9835d065cbb0f2d5ef4d0ce9586c1d844

Just waiting on approval of my implementation (I'm not 100% sure this is the intended use case of `UnsafeHacks`)

Edit: take 2: https://github.com/tterrag1098/MinecraftForge/commit/0d1a2f2af343bbd6907a74607ff156eefa6cfcc3

**Comment by bs2609** [comment]
Is this resolved now?

**Comment by tterrag1098** [comment]
Yes, fixed via 0d1a2f2af343bbd6907a74607ff156eefa6cfcc3
