### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#5324]
When installing version 14.23.5.2797-2806 through twitch (likely not an issue, but wanted to mention it) the minecraft launcher incorrectly interprets it as being a 1.13.2 instance. Clicking play will download and install vanilla 1.13.2 and run it as expected. I presume this is a fault with the prep work leading up to the 1.13 stuff, but I could be wrong.

I did go through the instance file twitch made and it seems to be referencing 1.12.2 as it should.
[minecraftinstance.txt](https://github.com/MinecraftForge/MinecraftForge/files/2730766/minecraftinstance.txt)

**Comment by DaemonUmbra** [comment]
This is not even a Forge issue, has been mentioned on the Forums, and has [apparently been fixed](http://www.minecraftforge.net/forum/topic/68119-anything-higher-than-2796-loads-1132-version-of-minecraft-from-the-twitch-launcher/?do=findComment&comment=328958).

**Comment by ghost** [comment]
No need to be rude, I've not run into this kind of issue before. Anyway, thanks for the link, I'll apply the fix mentioned.
