### ISSUE TITLE
[1.13] [Suggestion] Offer a way to integrate with NativeImage

### ISSUE THREAD

**Issue by james090500** [MinecraftForge/MinecraftForge#5331]
In 1.12.2 Minecraft used BufferedImage as there main image input. For methods such as IImageBuffer which allowed useful image manipulation when an image was downloaded from an external source. However in 1.13 they've moved over to NativeImage which is a lot more restrictive and there is currently no way of manipulating an image loaded into memory with NativeImage. Would it be possible to add a way of converting NativeImage to so Graphics.

**Comment by tterrag1098** [comment]
No. AWT cannot be reliably used with LWJGL3. There are ways to manipulate images with the included bindings for STBImage.

**Comment by james090500** [comment]
As far as I can see STBImage/Resize/Write doesn't offer anyway of placing specific pieces of an image on a specific location, for example adding a 4x4 image with an 8px H offset to a 64x64 image.

**Comment by tterrag1098** [comment]
What do you mean? NativeImage itself has methods to set any arbitrary pixel. Writing code to place an image at an offset should be rather trivial.

**Comment by james090500** [comment]
I can't believe I've missed it. Thank you, feel like an idiot now.
