### ISSUE TITLE
Failed to download libraries [forge-1.13-24.0.77-1.13-pre-installer]

### ISSUE THREAD

**Issue by Kzitold** [MinecraftForge/MinecraftForge#5356]
![image](https://user-images.githubusercontent.com/19679143/51113231-5dbf5480-17cf-11e9-847d-24e4cd4bb9e0.png)

Done with a fresh .minecraft folder.

1. Moved existing .minecraft to desktop
2. Started launcher.exe and entered credentials, which created a fresh .minecraft
3. The usual stuff. New launcher profile, launched Vanilla 1.13, closed, and ran the installer

**Comment by Alpvax** [comment]
Are you using a proxy? Have you checked your network config?

**Comment by Kzitold** [comment]
Still happens after turning off NordVPN.
Does it work for you?

**Comment by AManWith2Eyes** [comment]
> Are you using a proxy? Have you checked your network config?

Definitely not just an issue on @Kzitold 's end.  The exact same libraries fail to download when updating from 24.0.76 to 24.0.77 on my end as well.
![error](https://user-images.githubusercontent.com/46683747/51127577-c4566980-17f3-11e9-960c-c3fb11e49c21.jpg)

**Comment by Kzitold** [comment]
Not updating. Only Vanilla 1.13, then ran the installer.
No other previous version in the directory.

**Comment by LexManos** [comment]
cpw updated some libraries without publishing them to our maven. This has been corrected, so the installers should work now.
