### ISSUE TITLE
[1.12.2] Config defaults in comment written to file incorrectly

### ISSUE THREAD

**Issue by justinrusso** [MinecraftForge/MinecraftForge#5363]
Updating from 14.23.5.2785 to 14.23.5.2807 has introduced an issue where the default value in the comments printed in the config files are being updated when the pack is run with incorrect values. I've attached an image below showing a diff on one of the config files, but this is happening to seemingly every config file. This is happening on both my SevTech and SkyFactory 4 dev instances and is also happening to Darkosto.

I had first caught this when Darkosto committed his changes and noticed I was not having that issue. I brought all of my mods up to date with him and was not having the issue until updating forge to the same version as him. I then downgraded the mods to their previous versions so that Forge was the only thing I changed and I was still getting the same issue.

![image](https://user-images.githubusercontent.com/25138621/51223063-4dfa5a00-190e-11e9-804c-8f304f98a5fd.png)

**Comment by bs2609** [comment]
Probably caused by #5125.

Before:
https://github.com/MinecraftForge/MinecraftForge/blob/3dd8c8ae6f197c75b23008f5533160b2794a1c85/src/main/java/net/minecraftforge/common/config/Configuration.java#L1601-L1608

After:
https://github.com/MinecraftForge/MinecraftForge/blob/d3f27cf6fbb36f5ff7189fba0c985955e3cf45b5/src/main/java/net/minecraftforge/common/config/Configuration.java#L1699-L1707

Note the change from `prop.getDefault()` to `defaultValue`.

**Comment by Phylogeny** [comment]
@bs2609 The only way that `defaultValue` would be different from the return value of `Property#getDefault` within a `Configuration#setPropertyAndGetString` method call is if `Configuration#get` returned a null property in [line 1701 of that same method call](https://github.com/MinecraftForge/MinecraftForge/blob/d3f27cf6fbb36f5ff7189fba0c985955e3cf45b5/src/main/java/net/minecraftforge/common/config/Configuration.java#L1701); which would throw an NPE.

Regardless, `Configuration#setPropertyAndGetString` isn't even called when only the above example mod (Waddles) is installed.

**Comment by bs2609** [comment]
The `defaultValue` parameter is a `String[]`, whereas `Property#getDefault` returns a `String` - they aren't the same thing here.

See the implementation of `get` used, which calls `Property#setDefaultValues` (note the plural):
https://github.com/MinecraftForge/MinecraftForge/blob/da7c299f7e975c44759cb3b9f34480e6ab1affab/src/main/java/net/minecraftforge/common/config/Property.java#L540-L548

(to be clear, the method cited was `setPropertyAndGetStringList`, not `setPropertyAndGetString`)

**Comment by Phylogeny** [comment]
@bs2609 Ahh, I see. I was looking at (and breaking on) `Configuration#setPropertyAndGetString`, rather than `Configuration#setPropertyAndGetStringList`. Yes, the problem is as you say.
