### ISSUE TITLE
[1.13] Trying to create a custom enum results in a NoClassDefFoundError

### ISSUE THREAD

**Issue by GoryMoon** [MinecraftForge/MinecraftForge#5370]
When trying to use the `create` method of `EnumPlantType` or `BiomeType` the following error occurs:
https://haste.gorymoon.se/gapayejofi

Looks like there are still some references to `EnumHelper` in `RuntimeEnumExtender` since it were removed here: https://github.com/MinecraftForge/MinecraftForge/commit/c4cf950863256ed048a46e098401a969dfe4cb2e#diff-5926d0626c9ab3d2cc49f1884f27fba8

**Comment by bs2609** [comment]
See #5321.

**Comment by GoryMoon** [comment]
Just saw it
