### ISSUE TITLE
[1.13] Game crash when trying to print missing textures

### ISSUE THREAD

**Issue by GoryMoon** [MinecraftForge/MinecraftForge#5373]
When the game is trying to print that its missing textures it crashes with the following log:
https://haste.gorymoon.se/suxopucamo.mccrash

This is probably known from the part implementation of `ClientHooks` but I saw no issue about it and felt it could be good to be tracked.

**Comment by mcenderdragon** [comment]
A fix would be quite easy:
as https://github.com/MinecraftForge/MinecraftForge/blob/1.13-pre/src/main/java/net/minecraftforge/fml/client/ClientHooks.java#L268 just want the map from `SimpleReloadableResourceManager.namespaceResourceManagers`

**Comment by cpw** [comment]
Reopening. ObfuscationReflectionHelper was killed because it breaks j9 in the most ghastly of ways. There's other ways of doing this.

**Comment by LexManos** [comment]
ReflectionHelper shouldn't break j9. At least not in the tests i ran. As MC doesnt define a proper module, and thus gets the default which is supposed to be open. But if it does we just need to add. 'opens' statement to mc's modual definition. Reflection is a major thing in the MC workflow. Yes ats exist but they can be very fragile.

**Comment by cpw** [comment]
Closing, fixed name remapping..
