### ISSUE TITLE
[1.13] ModThreadContext and FMLModLoadingContext doesn't get updated for registry events

### ISSUE THREAD

**Issue by vrtl** [MinecraftForge/MinecraftForge#5375]
This works in previous versions of Forge but seems to be missing in 1.13. It has no effect other than this message being printed to the log for every custom entry that gets registered using the registry events.

"_Potentially Dangerous alternative prefix \`modid\` for name \`entry\`, expected \`minecraft\`. This could be a intended override, but in most cases indicates a broken mod._"

**Comment by williewillus** [comment]
This problem's more general, it's that EventBus doesn't set the active mod when dispatching to each listener. So the problem applies to basically all MinecraftForge.EVENT_BUS events. Perhaps post to https://github.com/MinecraftForge/EventBus?

**Comment by vrtl** [comment]
Yeah, I was thinking that but was a little unsure. The FMLModContainer also has it's own EventBus now, and manually updates both contexts itself before sending mod lifetime events to it. I'll post there and reference this issue.

**Comment by vrtl** [comment]
https://github.com/MinecraftForge/EventBus/issues/9

**Comment by cpw** [comment]
Closing, should be fixed in recent forge.
