### ISSUE TITLE
Large Dimension IDs Bloat level.dat

### ISSUE THREAD

**Issue by googleben** [MinecraftForge/MinecraftForge#5378]
The [dimension manager](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/common/DimensionManager.java) stores whether or not dimensions have been registered in a BitSet (the field [dimensionMap](https://github.com/MinecraftForge/MinecraftForge/blob/da7c299f7e975c44759cb3b9f34480e6ab1affab/src/main/java/net/minecraftforge/common/DimensionManager.java#L83)), which gets [serialized](https://github.com/MinecraftForge/MinecraftForge/blob/da7c299f7e975c44759cb3b9f34480e6ab1affab/src/main/java/net/minecraftforge/common/DimensionManager.java#L431-L446) to the level.dat as a NBT compound tag containing an int array that represents the BitSet. The issue arises when mods register a dimension with a very large ID, since the BitSet also contains a bit for every unused ID between 0 and (the word boundary above) the highest registered ID - [this can result in unreasonably long save/load times and a bloated level.dat](https://www.reddit.com/r/feedthebeast/comments/ahgktr/psa_pack_the_used_dimension_ids_to_avoid_a_lag/).

**Comment by tterrag1098** [comment]
Superceded by #5249
