### ISSUE TITLE
[forge-1.13-24.0.81-1.13-pre] EntityArgument.mutiplePlayers() doesn't exist on server side even though mappings say so

### ISSUE THREAD

**Issue by staj-d** [MinecraftForge/MinecraftForge#5382]
I've been trying to make a new command in 1.13 and it works fine on the client, but not on a dedicated server. According to the MCP Mappings "20180921-1.13" - `EntityArgument.mutiplePlayers()` or `func_197094_d()` is both client and server sided, yet I still get a `java.lang.NoSuchMethodError: net.minecraft.command.arguments.EntityArgument.func_197093_b()Lnet/minecraft/command/arguments/EntityArgument;` when I run the code on the server.

**Comment by staj-d** [comment]
Bump

**Comment by liach** [comment]
Well, `func_197093_b` is different from `func_197094_d`.
