### ISSUE TITLE
[1.12] Duplicate on craft tables (two players)

### ISSUE THREAD

**Issue by yaroslav4167** [MinecraftForge/MinecraftForge#5383]
This bug working in versions 1.12.2 - 14.23.5.2768 - 1.12.2 - 14.23.5.2807.
This works in workbenches that allow two players to be in them simultaneously.
TConstruct: [https://youtu.be/Aex9fl405as](https://youtu.be/Aex9fl405as)
RealBench: [https://youtu.be/Xf2eZrAOrts](https://youtu.be/Xf2eZrAOrts)
I'm tested this bug with mods: TConstruct, RealBench, Thaumcraft (Bug works)

**Comment by liach** [comment]
@mezz can you label this issue again? the bot was down by random
