### ISSUE TITLE
[1.13] Issues with Registries

### ISSUE THREAD

**Issue by ThexXTURBOXx** [MinecraftForge/MinecraftForge#5387]
Running on version 24.0.94-1.13-pre.
I updated to the "new Registry method" by registering my registerBlock/registerItem methods and so on to the Mod Event Bus, like that:
```
ReforgedRegistry reg = new ReforgedRegistry();
FMLModLoadingContext.get().getModEventBus().addListener(reg::registerItems);
FMLModLoadingContext.get().getModEventBus().addListener(reg::registerBlocks);
FMLModLoadingContext.get().getModEventBus().addListener(reg::registerEntities);
FMLModLoadingContext.get().getModEventBus().addListener(reg::registerTileEntities);
```
But now, I need to check in each of those methods, if the generic type of the registry is right, because every of these methods gets called on every registry call (I see this in the log file):
```
[00:35:00] [Client thread/INFO] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Firing event for modid forge : net.minecraftforge.event.RegistryEvent$Register
[00:35:00] [Client thread/INFO] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Firing event for modid reforged : net.minecraftforge.event.RegistryEvent$Register
registerItems: net.minecraft.block.Block
registerBlocks: net.minecraft.block.Block
registerEntities: net.minecraft.block.Block
registerTileEntities: net.minecraft.block.Block
```
My register methods look like this (I only paste two here as examples, the other ones look similar, but of course with the other generic types):
```
@SubscribeEvent
public void registerBlocks(final RegistryEvent.Register<Block> event) {
    System.out.println("registerBlocks: " + event.getGenericType().getTypeName());
}
@SubscribeEvent
public void registerItems(final RegistryEvent.Register<Item> event) {
    System.out.println("registerItems: " + event.getGenericType().getTypeName());
}
```

Edit 1: To let mod developers know about this change, you should update the ExampleMod

**Comment by cpw** [comment]
AddGenericListener is required. Sadly, it's difficult to detect the wrong addListener call being used, as genericity isn't known at the time.

**Comment by ThexXTURBOXx** [comment]
Okay, the addGenericListener Method works  correctly, but I'll leave the issue open, so you can close it, when you want to

**Comment by cpw** [comment]
Yup. It's an issue with the eventbus. See  MinecraftForge/EventBus#10. I'll close this in favour of that.
