### ISSUE TITLE
The game crashed whilst exception in server tick loop The game crashed whilst exception in server tick loop Error: java.lang.IllegalArgumentException: Duplicate id value for 23!

### ISSUE THREAD

**Issue by betaninja** [MinecraftForge/MinecraftForge#5410]
06:38:27 | FML | Exception caught during firing event net.minecraftforge.event.entity.EntityEvent$EntityConstructing@47778cf6: java.lang.IllegalArgumentException: Duplicate id value for 23! 	at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:64) 	at com.tihyo.legends.entities.ExtendedLiving.<init>(ExtendedLiving.java:22) 	at com.tihyo.legends.entities.ExtendedLiving.register(ExtendedLiving.java:31) 	at com.tihyo.legends.handlers.ExtendedPlayerEventHandler.onEntityConstructing(ExtendedPlayerEventHandler.java:39) 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_49_ExtendedPlayerEventHandler_onEntityConstructing_EntityConstructing.invoke(.dynamic) 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) 	at net.minecraft.entity.Entity.<init>(Entity.java:179) 	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119) 	at jp.mc.ancientred.starminer.core.entity.EntityLivingGravitized.<init>(EntityLivingGravitized.java:49) 	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:68) 	at net.minecraft.entity.EntityCreature.<init>(SourceFile:23) 	at net.minecraft.entity.monster.EntityMob.<init>(SourceFile:14) 	at com.fabiulu.farlanders.common.entity.EntityEnderGolem.<init>(EntityEnderGolem.java:49) 	at com.fabiulu.farlanders.common.entity.EntityEnderGolem.<init>(EntityEnderGolem.java:69) 	at com.fabiulu.farlanders.common.worldgen.WorldGenFarlanderHouse5.func_76484_a(WorldGenFarlanderHouse5.java:693) 	at com.fabiulu.farlanders.common.worldgen.FarlandersWorldGenerator.generateSurface(FarlandersWorldGenerator.java:132) 	at com.fabiulu.farlanders.common.worldgen.FarlandersWorldGenerator.generate(FarlandersWorldGenerator.java:22) 	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) 	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) 	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055) 	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) 	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265) 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78) 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
-- | -- | --
06:38:27 | FML | Index: 1 Listeners:
06:38:27 | FML | 0: NORMAL
06:38:27 | FML | 1: ASM: com.tihyo.legends.handlers.ExtendedPlayerEventHandler@2a209eef onEntityConstructing(Lnet/minecraftforge/event/entity/EntityEvent$EntityConstructing;)V
06:38:27 | FML | 2: ASM: mods.battlegear2.WeaponHookContainerClass@7fd35d4a onLivingConstructor(Lnet/minecraftforge/event/entity/EntityEvent$EntityConstructing;)V
06:38:27 | FML | 3: ASM: jp.mc.ancientred.starminer.core.common.SMCommonEventHandler@7cdb3de8 registerExtendedProperty(Lnet/minecraftforge/event/entity/EntityEvent$EntityConstructing;)V
06:38:27 | FML | 4: ASM: com.inventorypets.InventoryPetsEventHandler@44df3074 onEntityConstructing(Lnet/minecraftforge/event/entity/EntityEvent$EntityConstructing;)V
06:38:27 | net.minecraft.server.MinecraftServer | Encountered an unexpected exception java.lang.IllegalArgumentException: Duplicate id value for 23! 	at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:64) 	at com.tihyo.legends.entities.ExtendedLiving.<init>(ExtendedLiving.java:22) 	at com.tihyo.legends.entities.ExtendedLiving.register(ExtendedLiving.java:31) 	at com.tihyo.legends.handlers.ExtendedPlayerEventHandler.onEntityConstructing(ExtendedPlayerEventHandler.java:39) 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_49_ExtendedPlayerEventHandler_onEntityConstructing_EntityConstructing.invoke(.dynamic) 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) 	at net.minecraft.entity.Entity.<init>(Entity.java:179) 	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119) 	at jp.mc.ancientred.starminer.core.entity.EntityLivingGravitized.<init>(EntityLivingGravitized.java:49) 	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:68) 	at net.minecraft.entity.EntityCreature.<init>(SourceFile:23) 	at net.minecraft.entity.monster.EntityMob.<init>(SourceFile:14) 	at com.fabiulu.farlanders.common.entity.EntityEnderGolem.<init>(EntityEnderGolem.java:49) 	at com.fabiulu.farlanders.common.entity.EntityEnderGolem.<init>(EntityEnderGolem.java:69) 	at com.fabiulu.farlanders.common.worldgen.WorldGenFarlanderHouse5.func_76484_a(WorldGenFarlanderHouse5.java:693) 	at com.fabiulu.farlanders.common.worldgen.FarlandersWorldGenerator.generateSurface(FarlandersWorldGenerator.java:132) 	at com.fabiulu.farlanders.common.worldgen.FarlandersWorldGenerator.generate(FarlandersWorldGenerator.java:22) 	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) 	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) 	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055) 	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) 	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) 	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265) 	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78) 	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
06:38:27 | net.minecraft.server.MinecraftServer | This crash report has been saved to: C:\Users\betan\AppData\Roaming\.minecraft\crash-reports\crash-2019-01-28_06.38.27-

Tryed asking the forge website. Didn't help...

**Comment by mcenderdragon** [comment]
What Forge Version do you use ? (Dont say something like latest)

**Comment by bs2609** [comment]
They are using 1.7.10, as has been mentioned on their [forum thread](http://www.minecraftforge.net/forum/topic/68480-the-game-crashed-whilst-exception-in-server-tick-loop-error-javalangillegalargumentexception-duplicate-id-value-for-23/).

Don't just post your issue elsewhere because you didn't like the answer you got there.

**Comment by Phylogeny** [comment]
Red flags:
1. That title
2. Opening a new issue, rather than just editing the description of the old one
3. Un-linked partial crash report
