### ISSUE TITLE
[1.13] EntityArgument.multipleEntities

### ISSUE THREAD

**Issue by staj-d** [MinecraftForge/MinecraftForge#5413]
My issue #5382 was closed earlier while the forum said to make an issue on the forums, while the forum said to make the issue here.
http://www.minecraftforge.net/forum/topic/68339-113-pre-entityargumentmutipleplayers-doesnt-exist-on-server-side/

**Comment by LexManos** [comment]
Dont spam the github with crap like this until you actually understand the problem you're having.
If I say that this is not the place for the issue, then it is not the place for the issue. Don't let some rando on the forums tell you to do something I explicitly told you not to.
