### ISSUE TITLE
Help? It crashes without even starting

### ISSUE THREAD

**Issue by Niilyx** [MinecraftForge/MinecraftForge#5415]
https://pastebin.com/sHj3DkdA

WHAT does this mean? It's a log not a crash report. I tried to install Railcraft but for that I need that version or higher :/

**Comment by Phylogeny** [comment]
AppliedEnergistics/Applied-Energistics-2#3726:
> [...] for the next report please use pastebin to post the Log, this wall of text is quite painfull to read [...]
> --mindforger

Yes, please do.

**Comment by Niilyx** [comment]
Okay
