### ISSUE TITLE
Basic Primer for 1.13

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#5416]
As Lex wanted a basic primer: here is one https://gist.github.com/mcenderdragon/6c7af2daf6f72b0cadf0c63169a87583.

If its bad I will improve it.

**Comment by williewillus** [comment]
--no-deamon should be --no-daemon

**Comment by williewillus** [comment]
your section on running needs to make it clear whether it's for userdev or forgedev

**Comment by Alpvax** [comment]
You also have a typo under setup forge: "./gardlew eclipse"

**Comment by kierajreed** [comment]
also eclipse is optional, because intellij exists *or vim or anything*

**Comment by mcenderdragon** [comment]
I have updated the gist and hopefully its is now more clear.

**Comment by Sana36** [comment]
One spelling mistake unless they are different parts of the code "for those wishing to work on forge directly" and one suggestion of a grammar change 'If it crashes try running it again, as this sometimes helps'.

**Comment by mcenderdragon** [comment]
Should be fixed now.

**Comment by Sana36** [comment]
One less 'h' in wish and looks good to me :-)

**Comment by tterrag1098** [comment]
This should probably be a page on the docs.

**Comment by Sana36** [comment]
Does much need to change in the docs?

**Comment by kierajreed** [comment]
In my opinion the docs need to be remade from scratch. So maybe not specifically here, but docs need to be worked on.
