### ISSUE TITLE
[1.13] Player inventory desync on the client

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#5421]
The inventory on the client will sometimes get desync'd from the server. This can be reproduced by filling your inventory with items and running the `/clear` command, or opening the creative inventory and shift clicking on the trash slot. 

Forge: 24.0.147
MC: 1.13

**Comment by SquidDev** [comment]
I've been able to reproduce this just by dropping/picking up items, or running the `/give` command. Any interaction outside of an inventory appears not to be synced correctly.

**Comment by Darkhax** [comment]
@SquidDev Alexbegt says he has traced the issue back to [this](https://github.com/MinecraftForge/MinecraftForge/blob/1.13-pre/patches/minecraft/net/minecraft/inventory/Container.java.patch#L7) patch.

**Comment by williewillus** [comment]
also chiming in to say I had this issue a couple days ago, didn't know what it was but it went away after a relog.
