### ISSUE TITLE
[1.13] Grass stacking on top of each other in worldgen

### ISSUE THREAD

**Issue by abyssnyan** [MinecraftForge/MinecraftForge#5422]
I am seeing these kinds of odd grass formations in worlds created by the modded client, my guess is that this has something to do with worldgen.
Tested on 1.13-forge-24.0.150

> Screenshot from a world created by a modded client.
![screenshot from 2019-02-02 22-30-37](https://user-images.githubusercontent.com/29151752/52169038-b6cd3900-273a-11e9-8791-c1ac58c4c8f2.png)
> Screenshot from a world created by the vanilla client. (opening in a modded client doesn't reproduce in already created worlds.)
![screenshot from 2019-02-02 22-31-08](https://user-images.githubusercontent.com/29151752/52169037-b5037580-273a-11e9-81c7-56e414dd87dc.png)

**Comment by LexManos** [comment]
Probably a typo when porting a patch, if you can find a issue around a world spawn, shoot over the world seed and coords so we can test please.

**Comment by abyssnyan** [comment]
Seed is 333666 and pics are taken ~30 blocks forward from spawn.

**Comment by tterrag1098** [comment]
Superceded by #5434

**Comment by LexManos** [comment]
Fixed in https://github.com/MinecraftForge/MinecraftForge/pull/5434
