### ISSUE TITLE
[1.13] Dedicated server fails to start due to non existing world folder

### ISSUE THREAD

**Issue by ashpieboop** [MinecraftForge/MinecraftForge#5429]
When you start a server in a working directory that doesn't contain an empty "world" directory (or whatever it has been configured to), the server tries to access world/serverconfig/forge-server.toml and fails to create the world/ folder.

Creating the missing "world" (only this one, not any subfolder, not even serverconfig) manually fixes this issue.

Tested with 1.13 mdk 150

See : https://github.com/MinecraftForge/MinecraftForge/blob/1.13-pre/src/main/java/net/minecraftforge/fml/server/ServerLifecycleHooks.java#L66
[crash-2019-02-03_14.21.08-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/2825539/crash-2019-02-03_14.21.08-server.txt)
[2019-02-03-2.log](https://github.com/MinecraftForge/MinecraftForge/files/2825544/2019-02-03-2.log)

**Comment by cpw** [comment]
Reopening. This solution breaks linked paths on linux _completely_.
