### ISSUE TITLE
[1.13] RenderingRegistry doesn't work?

### ISSUE THREAD

**Issue by ThexXTURBOXx** [MinecraftForge/MinecraftForge#5431]
I have already created a thread in the forums about this issue:
http://www.minecraftforge.net/forum/topic/68588-113-entities-dont-get-rendered/
It seems like, the RenderingRegistry doesn't work.
Even literally copying any of Minecraft's Render-classes and registering them for own entities doesn't work.
The entities spawn just fine (their logic works, you can even hear them e.g. splashing into water), but they aren't shown in-game.

**Comment by GirafiStudios** [comment]
Please only post issue you're actually sure about is a problem on the issue tracker.
I personally have RenderingRegistry working perfectly fine in 1.13. Just tested with 24.0.150.

**Comment by ThexXTURBOXx** [comment]
I am sure, it's a bug with Forge, because, as I said, all my Render classes work fine in 1.12.2, but don't in 1.13 (even when _literally_ copying Minecraft's Render classes)

**Comment by williewillus** [comment]
This needs to be pinned down, agreed. My entities are rendering just fine in 1.13 as well. Go to the forums and discord to hash it out more.
