### ISSUE TITLE
[1.13] eclipse Project points to the wrong output folders

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#5438]
after setting up the MDK and importing it into the workspace forge is able to launch but with out the own mod. This is caused because the eclipse source set still point to "/bin/<something>" as their output folder (I wish is default I guess). 

I made the following changes and it worked:
- `src/main/java`: `/bin/main` -> `/build/classes/java/main`
- `src/main/resources`: `/bin/main` -> `build/resources/main`

So I think the pattern is quite obvious, but I dont know where in build.gradle I need to change something to make a PR.

**Comment by LexManos** [comment]
Ya, just ran into this myself. 
It's going to be a bigger pain in the ass then it should be.
The places to start looking if you want to look into it before I get a change is:
https://github.com/MinecraftForge/ForgeGradle/blob/FG_3.0/src/common/java/net/minecraftforge/gradle/common/util/RunConfig.java#L174
https://github.com/MinecraftForge/ForgeGradle/blob/FG_3.0/src/common/java/net/minecraftforge/gradle/common/util/EclipseHacks.java#L105

**Comment by mcenderdragon** [comment]
I have tested a little bit and found something interresting: if you set it once you can run `gradle eclipse` as many times a you wont, it will override your changes. bt If you delete the `.classpath` file and let gradle recreate it the output foders point again to `bin/main`
Edit: the Launch configuration seems to be always correct, so only the classpath file needs changes:
https://github.com/MinecraftForge/ForgeGradle/blob/FG_3.0/src/common/java/net/minecraftforge/gradle/common/util/EclipseHacks.java#L69-L89

**Comment by mcenderdragon** [comment]
How (where) do I tell the eclipse plugin to use other output folder then the default ones? I could just override them in task.doLast , but I guess there is a more elegant way.

**Comment by tterrag1098** [comment]
Fixed via MinecraftForge/ForgeGradle#546
