### ISSUE TITLE
[1.13] Crosshair attack indicator texture issue

### ISSUE THREAD

**Issue by Aeltumn** [MinecraftForge/MinecraftForge#5442]
See image below, the crosshair attack indicator has a texture issue. Using latest commit as of posting this issue.

![Image](http://i64.tinypic.com/nqz785.png)

**Comment by GirafiStudios** [comment]
I have seen this aswell. Does not happen always, and couldn't reproduce it consistently. But happens even once in a while.

**Comment by Aeltumn** [comment]
It happens consistently for me on every launch, [reference image of F3 screen with GPU/CPU information](http://oi65.tinypic.com/x3xvyq.jpg).

**Comment by Cloudhunter** [comment]
F3 + C in order to produce a crash report with all the information contained would be appreciated.

**Comment by Aeltumn** [comment]
[Crash report](https://pastebin.com/N6niMk5J)
