### ISSUE TITLE
Config Looses property comments if not fetched

### ISSUE THREAD

**Issue by NullSector76** [MinecraftForge/MinecraftForge#5444]
Issue: create a config load up all data like normal using the older config system. Load up the config again not grabbing everything only what you need that isn't commented and the comments will wipe.

proof of error:
https://pastebin.com/vcGGDweS

the fallowing simple example will result in the wiping of the comments like the example above. This is forge  you can reproduce using your own code that was just an example. I am not asking for help I understand this isn't forge forums this is a bug report.

**Comment by LexManos** [comment]
This is intentional. And Not going to be fixed, this entire thing is nuked in 1.13, so it's not worth fixing.
