### ISSUE TITLE
[1.13] DimensionType.create(...) returns null

### ISSUE THREAD

**Issue by ashpieboop** [MinecraftForge/MinecraftForge#5448]
When I try to create a new dimension type (on FMLServerAboutToStart event) it just returns null, so I assume the method body is not getting replaced/hooked - or whatever it is supposed to be - by the RuntimeEnumExtender.

I have not tested other enums create() method, so I don't know if it's an isolated case.

**Comment by LexManos** [comment]
1) Forums
2) Logs.
