### ISSUE TITLE
No new Gradle versions support?

### ISSUE THREAD

**Issue by CommanderTvis** [MinecraftForge/MinecraftForge#5453]
I'm working with ForgeGradle using Gradle 5.2.  

This plugin DSL causes build die with weird reason.  

```gradle
plugins {
    id 'net.minecraftforge.gradle.forge' version '2.0.2'
}
```

Stacktrace of build: https://gist.github.com/CommanderTvis/8802a29de28da13da5b41ed3687bc87a. 

It seems that Forge and mods can be built only with Gradle 2.14 lol

**Comment by GirafiStudios** [comment]
I'm running Gradle 4.9 with no issue at all, but anything never than that'll break it seems.
Also this should go on the Forums, have nothing to do with Forge itself.

**Comment by LordMonoxide** [comment]
This has been reported in the ForgeGradle repo already: (MinecraftForge/ForgeGradle#552)
