### ISSUE TITLE
[1.13] SSL connection to files.minecraftforge.net fails on java 8 < 101

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/MinecraftForge#5454]
Java versions below 101 do not know the let's encrypt root certificate and therefor do not trust the connection to https://files.minecraftforge.net
This is important, as the update checker fetches the update JSON from the server, and other mods may supply urls with https that use Let's encrypt as well, and the native launcher ships j8u51 (at least under windows)
1.12 and below avoids this problem by just not using https, but this will break if files.minecraftforge.net enforces https.
For 1.12 and below, there is also a mod that ships the let's encrypt certificate and installs it if not present in the java version currently used (See [LetsEncryptCraft](https://github.com/Cloudhunter/LetsEncryptCraft))
There are two ways to fix the update check for forge:

1. Use the unsafe http and rely on files.minecraftforge.net to never enforce ssl
2. Use the safe https and ship the LE root ce with forge and install it if not present

Currently, version checking fails more or less silently, [as the error message is only logged at debug level](https://github.com/MinecraftForge/MinecraftForge/blob/8084ca43b92b5d2feeea56e9caa8a7a86f985755/src/main/java/net/minecraftforge/fml/VersionChecker.java#L276)

**Comment by LexManos** [comment]
Ya, this is something that we need to address. I'm not a fan of shipping/installing root certificates. But if it's done properly and verified that it's the original certificate. I'd be fine with it. I'll poke cpw, and look into what options we have. If someone wants to propose the technical side of the implementation we can look at it.

**Comment by cpw** [comment]
Should be fixed with latest release for standard java installations such as the one embedded in the launcher. f1feac76b3f2b95674afa18140ad375567f6c42f
