### ISSUE TITLE
[1.13] Crash when mod's missing pack.mcmeta

### ISSUE THREAD

**Issue by autaut03** [MinecraftForge/MinecraftForge#5461]
Hey. When mod doesn't have `pack.mcmeta` file, the game crashes: https://hastebin.com/bonegilusa.makefile

Using Forge `1.13-24.0.183-1.13-pre`.

Not every mod needs a pack, so this should be optional, unless something depends on mod having a resource pack.

**Comment by LexManos** [comment]
Every mod is added as a resource pack, thus allowing recipes, models, textures, etc... 
I'm also a fan of us no longer shipping a 'default pack.mcmeta' as it just led to most people ignoring it and messing up their resource packs.
So yes, add a pack.mcmeta.

**Comment by autaut03** [comment]
Okay, thanks!
