### ISSUE TITLE
[1.12.2] Slot clicks of type QUICK_MOVE report stacks of air

### ISSUE THREAD

**Issue by brandonhoughton** [MinecraftForge/MinecraftForge#5465]
Desired behavior:
When a player performs a `QUICK_MOVE` slot click, `slotClickEvent.getItemStack()` should return the item-stack the player clicked on

Current behavior:
When a player performs a` QUICK_MOVE` slot click, `slotClickEvent.getItemStack()` returns the item stack remaining in the slot after click is processed (often air)
Specifically in the use case of monitoring craftResult slots, `slotClickEvent.getItemStack()` always results in a stack of air given that `slot5.canTakeStack(player)` is false for all output (craft / smelt result) slots in containers

Reproduction:
1) Open a crafting table
place recipe (e.g. 4 planks for a crafting table)
SHIFT-click craft result
observe `slotClickEvent.getItemStack()` is air (desire minecraft:crafting_table)
2) Open a container with an empty slot
SHIFT-click an item in local inventory
observe `slotClickEvent.getItemStack()` is air (desire moved item)
3) [Current behavior] Open a container with only one slot free and no partial cobblestone stacks
Fill the container with 31 cobblestone
SHIFT-click a _full_ stack of cobblestone from  inventory
observe `slotClickEvent.getItemStack()` is 33x cobblestone (desire 31x minecraft:cobblestone)

Use Case:
Use slotClick events to determine what items players have take out of various inventory containers. Currently all other known slot click types report the item-stack retrieved rather than remaining. If this is desired behavior perhaps an additional field could be added allow both moved and remaining stacks to be observed.

Relevant Code - net.minecraft.inventory.Container

```
 public ItemStack slotClick(int slotId, int dragType, ClickType clickTypeIn, EntityPlayer player) {

                ...

                Slot slot5 = this.inventorySlots.get(slotId);

                if (slot5 == null || !slot5.canTakeStack(player))
                {
                    return ItemStack.EMPTY;
                }

                for (ItemStack itemstack7 = this.transferStackInSlot(player, slotId); !itemstack7.isEmpty() && ItemStack.areItemsEqual(slot5.getStack(), itemstack7); itemstack7 = this.transferStackInSlot(player, slotId))
                {
                    itemstack = itemstack7.copy();
                }

                ...

```

**Comment by tterrag1098** [comment]
As this is a vanilla issue, a PR would probably go further.
