### ISSUE TITLE
[1.13] Different class loaders are used where they shouldn't, during mod loading

### ISSUE THREAD

**Issue by autaut03** [MinecraftForge/MinecraftForge#5467]
Hey. I'm developing a [mod language provider for Kotlin](https://github.com/autaut03/Forgelin/blob/1.13-rewrite/src/main/kotlin/net/shadowfacts/forgelin/FMLKotlinModLanguageProvider.kt).

Basically, it fails with `java.lang.ClassCastException: net.shadowfacts.forgelin.FMLKotlinModContainer cannot be cast to net.minecraftforge.fml.ModContainer` [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.13-pre/src/main/java/net/minecraftforge/fml/ModLoader.java#L172) because of [this](https://github.com/autaut03/Forgelin/blob/1.13-rewrite/src/main/kotlin/net/shadowfacts/forgelin/FMLKotlinModTarget.kt#L15). After debugging, I found out that it was due to different class loaders, so I thought I'll use FML's approach to this and copy the code from [there](https://github.com/MinecraftForge/MinecraftForge/blob/1.13-pre/src/main/java/net/minecraftforge/fml/javafmlmod/FMLJavaModLanguageProvider.java#L70).

`FMLJavaModLanguageProvider` uses `Thread.currentThread().contextClassLoader` to load ModContainer class, and that's how `ModLoader` is loaded. They have no issues with casting `FMLModContainer` (java one's) to it's base class `ModContainer`.

However, when I tried to do the same thing, it failed with the exact same `ClassCastException` again.  `Thread.currentThread().contextClassLoader` gives the same instance of `TransformingClassLoader` both times. The difference is that in case of `FMLJavaModLanguageProvider`, `TransformingClassLoader` delegates class resolving to it's subclass, `DelegatedClassLoader`, which finds needed `FMLModContainer` and returns it.

On the other hand, when trying to resolve my mod container (`FMLKotlinModContainer`), `DelegatedClassLoader` throws an exception, because it only knows of a Forge jar and nothing else. Then, `TransformingClassLoader` catches it and instead delegates it to it's parent - `Launcher$AppClassLoader`. Yes, it does know about both the class I need and it's parent `ModContainer`, but it's in fact a different class from one `DelegatedClassLoader` knows about and one loaded/used all over Forge.

I tried to describe it as best as I could, but feel free to ask anything. I want this finally done.

Here's a link to an imgur album that describes it better: https://imgur.com/a/SinMR2T

**Comment by cpw** [comment]
Not a bug. You have to load the modcontainer using the supplied classloader. Refer to FML's language provider for an example. You seem to have the correct code commented out. It might be a "fallback" issue, where your code is also available on the system classpath, and it's failing to load for some reason in the transformer. Enabling CLASSLOADER debugging marker should reveal a lot more of what's going on.

**Comment by autaut03** [comment]
Resolved in https://github.com/MinecraftForge/MinecraftForge/commit/78455ac3c01dfbec042e88e26249a2b977902814 , thanks.
