### ISSUE TITLE
[1.13.2] ItemBlocks do not render in creative inventory

### ISSUE THREAD

**Issue by drekryan** [MinecraftForge/MinecraftForge#5470]
ExampleMod: https://github.com/drekryan/ExampleMod
Note: Everything is setup in the ExampleMod provided in the link above, just git clone and run. It registers a Block, slab, and stair which all have the issue as well as provides an ItemGroup.

**Brief Description:**
Registered ItemBlocks are not rendering or displaying tooltips in the creative inventory or item group tabs. This does not appear to affect regular Items, just ItemBlocks.

**Steps to Reproduce:**
1. Create a basic mod with Block and Item registry events hooked up
2. Create a new Block in the Block Registry Event ```blockRegistryEvent.getRegistry().registerAll(
                    altar_stone = new Block( Block.Properties.create( Material.ROCK ) ).setRegistryName( "examplemod", "altar_stone" )
            );```
3. Create an appropriate blockstate, model, and texture for the block (I used the cube_all model and a texture but a texture may not even be needed as a missing texture should appear)
4. Create an ItemBlock for the Block in the Item Registry event ```itemRegistryEvent.getRegistry().registerAll(
                    new ItemBlock( altar_stone, new Item.Properties() ).setRegistryName( "examplemod", altar_stone.getRegistryName().toString() )
            );```

**What I expected to happen:**
I expected the item block to appear in the all items tab of the creative inventory with proper rendering and tooltip. Also assigning an ItemGroup to the item I also expect it to appear in the ItemGroup tab.

**What happened:**
The ItemBlock was properly registered. I can use .give to get the item and hold it in my inventory but I can not obtain it from the creative inventory or see it rendered.

**Versions:**
Minecraft: 1.13.2
Forge: 25.0.9

![2019-02-15_04 25 13](https://user-images.githubusercontent.com/1168966/52847321-da4c9800-30d9-11e9-9158-6a92b208b797.png)
![2019-02-15_04 25 27](https://user-images.githubusercontent.com/1168966/52847322-da4c9800-30d9-11e9-98fd-f5c95d575259.png)
![2019-02-15_04 25 40](https://user-images.githubusercontent.com/1168966/52847323-da4c9800-30d9-11e9-9164-7d2db411e9ee.png)

**Comment by SquidDev** [comment]
So it appears the patch to redirect `Item.BLOCK_TO_ITEM` to Forge's registry was dropped (https://github.com/MinecraftForge/MinecraftForge/commit/ca72710937a88ffbcccb9f748ae1890ea9887514#diff-d0164446501bbeeb653e67a161393d00L12), meaning that the `BLOCK_TO_ITEM` map is never updated with modded blocks, and so `new ItemStack(someBlock)` returns air instead.

I'm happy to put a PR together if desired?

**Comment by drekryan** [comment]
Thanks for looking into this issue!

**Comment by LordMonoxide** [comment]
As a temporary fix you can add this to your block class:
```java
  //TODO: remove this once the forge registry is fixed
  @Override
  public Item asItem() {
    return ForgeRegistries.ITEMS.getValue(this.getRegistryName());
  }
```
**Note**: my `ItemBlock`s are registered with the same registry name as the `Block` they belong to.  You may have to change `this.getRegistryName()` to whatever name you used to register the `ItemBlock`.

**Comment by drekryan** [comment]
As of 25.0.20 and PR #5483, this issue has been resolved. Closing...
