### ISSUE TITLE
Unable to compile 1.7.10 (or any version of Forge?) Maven issues?

### ISSUE THREAD

**Issue by StargateMC** [MinecraftForge/MinecraftForge#5472]
Hi All,

Looks like something might be wrong with the Maven repo for Forge? 
http://files.minecraftforge.net/maven/net/minecraftforge/forge/json results in 0 for every version available?
Compiling with gradlew.bat results in 'no such version exists'.
If this is not something you all look after,  or not relavent here please close it off, sorry for bothering you.

Regards,
Bysokar

**Comment by tterrag1098** [comment]
It's a known issue caused by the 1.13 build process. Fixes for legacy FG versions are forthcoming.

**Comment by StargateMC** [comment]
Thanks @tterrag1098.. nice of someone to let me know rather than just closing haha :) Cleared gradle cache and all good now :)
