### ISSUE TITLE
[1.13.2] Logo in Mods list isn't scaled

### ISSUE THREAD

**Issue by PanSzelescik** [MinecraftForge/MinecraftForge#5475]
![image](https://user-images.githubusercontent.com/26679785/52874145-035c3f80-3151-11e9-8629-15ed5d370191.png)
Tested with 400x400, 64x64 and 16x16

**Comment by drekryan** [comment]
Does commit 329f26e close this issue?

**Comment by tterrag1098** [comment]
Yes.
