### ISSUE TITLE
[1.13.2] BlockEvent.PlaceEvent not getting fired

### ISSUE THREAD

**Issue by MJRLegends** [MinecraftForge/MinecraftForge#5476]
Hello, so i seems the BlockEvent.PlaceEvent event only get fired when placing a lily pad not any block. 

![](https://i.gyazo.com/1db3bd674e9fb99f0ce83df054ff0554.png)

Seems ForgeHooks#onPlaceItemIntoWorld seems to be commented out..

![](https://i.gyazo.com/3818ead7b95db55d5b1b82c977dea063.png)

**Comment by rcrosby-ti** [comment]
Seems to me this might be best addressed by splitting it into 2 separate events: a cancelable pre-placement event and an uncancelable post-placement notification event.  The way it's set up now, it actually places the block and then tries to remove it if it gets canceled.  That's not a cancel; that's an undo.  Some blocks cause changes to neighboring blocks when placed and will be a pain to "reverse/rollback".
