### ISSUE TITLE
[1.13.2] Unable to make commands with an EntityArgument

### ISSUE THREAD

**Issue by marcus8448** [MinecraftForge/MinecraftForge#5479]
Hello, I'm trying to make a mod in 1.13.2 that allows the user to use numbers in '/gamemode' ([Source here](https://github.com/marcus8448/GamemodeOverhaul/blob/master/src/main/java/io/github/marcus8448/mods/gamemodeOverhaul/GamemodeOverhaul.java)). But the problem is that `EntityArgument.multiplePlayers` and `EntityArgument.multipleEntities` don't exist on the server-side. Yet /gamemode and [/forge setdimension](https://github.com/MinecraftForge/MinecraftForge/blob/36ccb3bbfec293e388d11b04053805aa2ec0c5b3/src/main/java/net/minecraftforge/server/command/CommandSetDimension.java#L49) both use `EntityArgument.multipleEntities` without a problem.

[Log](https://gist.github.com/marcus8448/6b7b796c31d08c388bea481811db4a4c)

**Comment by tterrag1098** [comment]
It appears to be looking for a srg name when you're running in dev? Is that what's happening? Neither of those methods are client-only.

**Comment by marcus8448** [comment]
Yeah, that's what is happening, I should've clarified. It works on a non-dev environment server.

**Comment by tterrag1098** [comment]
This seems like an issue with your setup, not a bug. You can ask for further help on discord or the forums.
