### ISSUE TITLE
[1.13.2] InputEvent.KeyInputEvent not getting fired

### ISSUE THREAD

**Issue by zlainsama** [MinecraftForge/MinecraftForge#5481]

**Comment by Funwayguy** [comment]
Can confirm, not firing for me either. Not sure if it's suitable for your use case but I'm currently working around this in Ore Excavation by polling keys through the client tick event.

**Comment by cpw** [comment]
Not currently implemented. Not sure if it can be easily implemented the way it was before. I welcome analysis of feasible implementations.

**Comment by GirafiStudios** [comment]
I believe that @alexbegt had looked into it a few weeks back.

**Comment by 0uti** [comment]
could be implemented in net.minecraft.client.KeyboardListener in function "onKeyEvent"
