### ISSUE TITLE
Farming & Food Issues 1.13 v192

### ISSUE THREAD

**Issue by Sana36** [MinecraftForge/MinecraftForge#5485]
Noticed in v156 - confirmed in v192 today. I haven't seen any mention in issues or pull requests until this report today http://www.minecraftforge.net/forum/topic/68803-breaking-crops-age-7-yield-no-drops-1132/

I am finding Wheat (age 7) and beets (age 3) - only get seeds (no wheat or beetroots). Seeds are still only dropping from tall grass. (Ratios first 12 broken yielded 3, then 18 till next drop.)

Carrots & potatoes low yields - sometimes when harvesting (age 7) don’t get even one to replant (0-3 as the range, averaging between 1&2)

~Also there are low food animals. I have seen none at all on land [I haven't yet been able to confirm chickens spawning in the ocean as I haven't found an ocean biome yet in v192, v156 none except chickens spawned in the water/ocean. Dolphins, squid and fish look to be normal]

~~Only aggressive mobs drowned and phantoms

I have included the latest log if needed, there are no other logs as there is no crashes etc. https://gist.github.com/Sana36/1d31729ad3f58e4c985d61d62a586962 if a more detailed context is needed let me know.

**Comment by tterrag1098** [comment]
Superseded by #5490
