### ISSUE TITLE
[1.13.2] Only water mobs are spawning, Creative tabs' tool tip is not displaying, LivingSpawnEvent.CheckSpawn is not getting fired

### ISSUE THREAD

**Issue by zlainsama** [MinecraftForge/MinecraftForge#5486]
Like drowned zombies and squids and fishes, they are spawning fine.
No zombies, creepers and others.
Passive mobs also don't spawn during terrain generation, and they still don't spawn after generation.
Mobs spawned with structures like villagers are spawning.
A superflat world can showcase this well.

Creative tabs in creative menu is not displaying their tool tips when mouse is hovering above them.

Also, LivingSpawnEvent.CheckSpawn is not getting fired.
At this point, i think a lot of events are not getting fired now.

Screenshots: https://imgur.com/a/V8iN1wF

**Comment by tterrag1098** [comment]
Superseded by #5490
