### ISSUE TITLE
[1.14.x] Improve vanillas chunk force loading system

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#5487]
In 1.13.2 we have the `forceload` command which uses `getForcedChunks` `isForcedChunk(x,z)` `setChunkForced(x,z,foced)` (These methods are inside the World).
This is realy nice and works for vanilla systems very well but I see some upcomming problems with this system in modded:
- [ ] we can not tell appart who foced the chunk, it could be a player with the command it could be a mod, or any thing
- [ ] mod can cancel each other out: a querry is mining an area and thus loading it. A chunkloading turtle passes above and unfoced the chunks behind it. Now parts of the querry are unloaded without anyboding noticing it
- [ ] no config, I know alot of servers have reduced the foced chunk count per mod very much and also have unice configs per mod. Currently its just one giant list.

My current idea would be to implement a chunk system on top of vanillas and add mod id and a custom string for a "cause". But I also want to hear other opinions on that matter.

**Comment by Niko-sk2x** [comment]
I've seen this system is completely changed in 1.14, including actual ticket system, so this is probably going to be mostly unnecessary there.

Is it actually worth it to implement something that won't be needed in the next version, with not many people actually using this one?

**Comment by mcenderdragon** [comment]
It depens on how long 1.13.2 will be used and how annoying it gets for the end user. Maybe this is a non issue, because when in serveral month big mods are finaly ported this wont be needed anymore.

**Comment by Niko-sk2x** [comment]
I think only something simple to avoid mods cancelling each other's chunkloading would be a good thing to do on 1.13, as that will actually break mods. All the other things are enhancements that aren't strictly needed for things to work, and from what I've seen, that was a big part of the old ForgeChunkManager.

**Comment by autaut03** [comment]
I was watching cpw's stream, where he got rid of ForgeChunkManager, so I don't think it's coming back in the same way it was before. Also as Barteks said, 1.14 is coming, so imo it's not worth it.

**Comment by mcenderdragon** [comment]
As `ForcedChunksSaveData` handles most of the stuff, it should be easy to atleast add a modid, so mods wont overwrite each other.

**Comment by cpw** [comment]
In my opinion, we shouldn't focus on a temporary system for 1.13.2 when 1.14 will land in the next couple of months.

**Comment by LexManos** [comment]
That's going to be the official stance of Forge. 1.13 is a stepping stone to 1.14. Modder SHOULD still update/test/provide feedback so that Forge can be ready for 1.14. But the chunk system, and the fluid system are known to be majorly re-factored by Mojang in 1.14. So we will not be putting in to much effort for those.

**Comment by mcenderdragon** [comment]
@Barteks2x can you point me in the right direction to look for, currently in the ServerWorld in 1.14 I only see `public LongSet getForcedChunks()` `public boolean forceChunk(int chunkX, int chunkZ, boolean add)` . You mentioned there was a ticket system of sorts.

**Comment by mcenderdragon** [comment]
Opinions on #6434?
