### ISSUE TITLE
[1.13.2] IForgeEntity.shouldDismountInWater is never called

### ISSUE THREAD

**Issue by bl4ckscor3** [MinecraftForge/MinecraftForge#5494]
A custom entity that overrides IForgeEntity.shouldDismountInWater and returns false will still dismount its rider when they submerge into water.  
Example: When riding the Merpig from [this mod](https://github.com/BuiltBrokenModding/SBM-Merpig/tree/cf2bcb06f7da34a71415f7ccdb5228cab9f196ef) under water, the player gets immediately dismounted, but on land the player stays on the entity.

**Comment by DarkGuardsman** [comment]
Line 338 of EntityLivingBase contained this.getRidingEntity().canBeRiddenInWater(this) and could be wrappered to the interface? 

Looking at the code:

1.13 line
` if (!this.world.isRemote && this.isPassenger() && this.getRidingEntity() != null && !this.getRidingEntity().canBeRiddenInWater(this)) {`

1.12 line
` if (!this.world.isRemote && this.isRiding() && this.getRidingEntity() != null && this.getRidingEntity().shouldDismountInWater(this))`

As far as I can tell its the same method, ignoring the name different which could be mappings. The only difference in 1.13 we have a rider sensitive version. Maybe its a naming flaw in the interface? I really do not know but I found the location. Hopefully that helps as the shouldBeRiddenInWater() does work for my needs in the mod.
