### ISSUE TITLE
[1.13.x] Armor needs a way to handle damage to it

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#5502]
My only use of ISpecialArmor was to have custom durability logic. There is no way to reliably intercept and replicate this in 1.13. Although stack has a `damageItem` method, there's nothing on `Item` that gives you that granularity. I'm sure you could do some hacks around setDamage, but a dedicated hook is probably better.

This is probably more general to all items and not just armor

**Comment by LexManos** [comment]
What information do you need, would a simple item redirect for attemptDamageItem be enough, or what?

**Comment by williewillus** [comment]
pretty much, yeah
