### ISSUE TITLE
[1.13.2] forge's at contains old-version name

### ISSUE THREAD

**Issue by Yaossg** [MinecraftForge/MinecraftForge#5504]
Forge: 25.0.10, File: in forge's src jar, accesstransformer.cfg
```
public net.minecraft.world.biome.BiomeForest *()
public net.minecraft.world.biome.BiomeHills *()
public net.minecraft.world.biome.BiomeMesa *()
public net.minecraft.world.biome.BiomePlains *()
public net.minecraft.world.biome.BiomeSavanna *()
public net.minecraft.world.biome.BiomeSnow *()
public net.minecraft.world.biome.BiomeTaiga *()
public net.minecraft.world.biome.Biome$BiomeProperties *()
```
These names are not in 1.13.2 but in 1.12.2
These changes (on whose name is corrected) are still useless because the rewritten minecraft's code

By the way, the README is 1.12.2's, too. and MinecraftForge's comments still introduce TERRAIN_GEN_BUS and ORE_GEN_BUS to us

**Comment by LexManos** [comment]
The README needs to be updated, someone better at writing properly then I will need to do that.
However the AT I've just removed those lines locally. To be reassesed if they are nessasary at all in the new world gen stuff.
