### ISSUE TITLE
[1.13.2] Data packs are not disabled properly

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#5506]
Currently using /datapack disable on a modded data pack (a provided one, like "mod:attained_drops") will disable the pack, but does not properly mark it as disabled, so /datapack enable is unable to reactivate the pack.  /reload will re-enable it, as it was never marked as disabled.  I'm unsure if this has to do with the `"mod:"` prefix on the pack, or something else, as the prefix makes it act strange in the command.  Vanilla's pack is not prefixed with anything, it is simply `vanilla`.

**Comment by liach** [comment]
Data pack names are plain strings. Why are they namespaced? If you mean default data packs from mods, we should prohibit disabling those.

**Comment by Shadows-of-Fire** [comment]
I am referring to default datapacks, yeah.

**Comment by liach** [comment]
Do you agree that the solution should be banning disabling default packs from mods?

If someone wants to override, they can put their pack in the world save directory on their own with entries that override.

**Comment by Shadows-of-Fire** [comment]
Since vanilla data can be disabled, no, i think mod data should also be able to be disabled.

**Comment by cpw** [comment]
what does it even mean to disable a mod's datapack?
For example: if you disable the forge datapack, then forge will simply stop working, completely.

**Comment by Shadows-of-Fire** [comment]
I think it would mean to disable the loading of provided mod recipes, advancements, or other things that the server loads as "data" that is provided by that mod.

**Comment by liach** [comment]
Hmm, I now have another question: If mods move their server logic related config to data packs and have packs disabled, the mods just cannot find their config. Moreover, there is no way to generate data while running the game, unlike the existing configs. The runtime disabling of data packs sound... a little bit troublesome.

**Comment by smmmadden** [comment]
Forge or Bukkit isn't dependent on the existence of a data pack, so disabling them only disables the features provided in that data pack.  https://minecraft.gamepedia.com/Tutorials/Creating_a_data_pack

Some data pack owners provide an option to disable/enable their own.  TBH, this may be the best direction to take and not leave it up to Forge or Bukkit, since there is currently no standard naming convention or guaranteed way to properly disable them.  I think DP's, RP's, TP's, Mods and Plugins all should be up to their respective developers to provide options to enable or disable (if they choose).

**Comment by williewillus** [comment]
i think a big benefit/demonstration of the success of "data-driven" stuff, is the ability in vanilla to disable the vanilla datapack and just have a barebones game with no recipes, loot, advancements, etc. Vanilla handles it all robustly.

It should be possible for mods to be disabled in much the same way.
Maybe not for forge if there's any core stuff in its datapack, but certainly for regular mods.

**Comment by liach** [comment]
Hmm, then how about constants json in the data packs? Will they get disabled as well, or what?

**Comment by williewillus** [comment]
this is approaching off-topic, but datapacks are disabled as an atomic unit.
