### ISSUE TITLE
[1.13.2] Player is instant-killing other entities

### ISSUE THREAD

**Issue by zlainsama** [MinecraftForge/MinecraftForge#5510]
Create a world, find/spawn some entities, punch them, they die.
https://imgur.com/a/CuAYmOH

**Comment by Mrbysco** [comment]
There's a pr that fixes this https://github.com/MinecraftForge/MinecraftForge/pull/5473

**Comment by zlainsama** [comment]
Oh, i didn't search for PRs. Thanks
