### ISSUE TITLE
[1.13.2] Mobs die in one hit

### ISSUE THREAD

**Issue by 128-bit-guy** [MinecraftForge/MinecraftForge#5511]
When i hit any vanilla mob with my hand or any weapon, it dies immediately.
This also happens when any vanilla mob falls from any height more then 3 blocks.
Forge version : 25.0.22
Minecraft version: 1.13.2

**Comment by 128-bit-guy** [comment]
Sorry, found PR that fixes it

**Comment by tterrag1098** [comment]
Superseded by #5473
