### ISSUE TITLE
[1.13.2]Forge cannot load from other location

### ISSUE THREAD

**Issue by Ghost-chu** [MinecraftForge/MinecraftForge#5515]
Before 1.13.2, we can run Forge in a standalone folder not same folder with Forge jar file.
(e.g Forge and Minecraft Server JAR file in `/server/jar` and real running folder is `/server/run`)
But in 1.13.2, it will throw missing library exception.
It important for IDC, please add that back, thanks.

Edit:
I try change the gameDir in `server_launcher.properties` but it report sha-256 excepiton.
and i delete the sha-256 info in META-INF, and it throw java

**Comment by LexManos** [comment]
What SHA exception, provide logs. And the folder structure for the server is nessasary.
A lot of files even in 1.12 wouldn't be found if you move working directories. Actually, refreshing myself with the code, there should be nothing wrong with having a different working directory. You just need to make sure your classpath is correct, as we use that to determine the root 'libraries' directory.

**Comment by Ghost-chu** [comment]
@LexManos Load from external location is working fine before 1.13.2 any version.
It make us more easily to update the Forge for many servers, and important for the Minecraft Host too.

The problem is libraries can't load correctly, yes, the forge self can load correctly, because it path write in file `server_launcher.properties`, BUT it protected by SHA-256 signature, I can't edit it, properties lose the it significance.

**Comment by LexManos** [comment]
As it sits, this properties file is only used to fill in default command arguments.
You can replace them with your own arguments by passing them in through the command line.
This file will not be unsigned, as it's a good rule to keep everything in the jar signed.
However, if someone wants to go through we can add support for an external "forge_version.properties" or something in the working directory.

**Comment by Ghost-chu** [comment]
I try use command line to replace that, but it doesn't work....
And yes, If have external support, that will awesome :D

**Comment by LexManos** [comment]
Then you're using the command line wrong. The server run is purely a wrapper to add arguments. It's completely optional and can be bypassed by passing the correct arguments in.

**Comment by Ghost-chu** [comment]
I trying use `-gameDir [Target]` to replace that, hope this correct cuz i not found any wiki or help have about this.
Thanks.

**Comment by LexManos** [comment]
It is not. Please go to the forums or discord for this. This is a non-issue. User error/ignorance. I'll leave this open until I decide how I want to allow for more flexible configurations. but all the functionality you want already exists.

**Comment by Ghost-chu** [comment]
Thanks for quickly response!
And okay :D

**Comment by cpw** [comment]
This is now resolved with 0bcc60fbe3842861092508589fef89a3b3d9014b

You should be able to install forge in `</path/to/dir1>` and by doing `java -jar </path/to/dir1/forge...>` it will launch and run correctly, with the current dir as the "server" directory.

Here's two servers (srv1 and srv2) both running from a common install location: `/home/cpw/tmpsrv/forgeinst` by executing `java -jar /home/cpw/tmpsrv/forgeinst/forge-1.13.2-25.0.59.jar` in `/home/cpw/tmpsrv/srv1` and `/home/cpw/tmpsrv/srv2` respectively.

![screenshot from 2019-02-26 10-52-30](https://user-images.githubusercontent.com/1217211/53426656-5cc83800-39b5-11e9-9de5-c8839f2e138f.png)
