### ISSUE TITLE
[1.13.2] Customs Recipes Feature Helped

### ISSUE THREAD

**Issue by Rumaruka** [MinecraftForge/MinecraftForge#5518]
Hello Forge Team <3

I don`t undestand about new System Recipes

`{
  "type": "simplegrinder:grinder",
  "ingredient": { "item": "minecraft:wheat" },
  "result": "simplegrinder:flour",
  "count": 1,
  "experience": 1.4,
  "cookingtime": 150
}`
Part Code: https://pastebin.com/YJ4PYJ3S

Console Error about it 
`com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'simplegrinder:grinder'
	at net.minecraft.item.crafting.RecipeSerializers.deserialize(RecipeSerializers.java:45) ~[?:?]
	at net.minecraft.item.crafting.RecipeManager.onResourceManagerReload(RecipeManager.java:54) [?:?]`

**Comment by williewillus** [comment]
you need to register a recipe serializer,see `RecipeSerializers.register`

**Comment by Rumaruka** [comment]
@williewillus I have this registry https://pastebin.com/tsa0LMrN
🤔

**Comment by Shadows-of-Fire** [comment]
Registering a type is not sufficient, you need to register a json (de)serializer with the method specified above
