### ISSUE TITLE
[Feature Request] Join server with missing mods anyway

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#5520]
Self explanatory title. While most mod devs mark mods as client side when they are, some forget, and some are never properly informed. An option to manually connect to the server anyway and accept anything that may come of it would be welcome for advanced users.

**Comment by Alpvax** [comment]
I feel that this would make it too easy for non 'advanced users' to bypass the useful error messages and spam everywhere with "it says I'm missing item X! What do I do"

**Comment by james090500** [comment]
Client side mods wouldn't be installed on the server though. Therefore makes this argument invalid.

All that would happen if this was added would the client would crash as it wouldn't know how to handle the modded items. 

Please name a realistic scenario when you'd need to join a server with missing mods

**Comment by LexManos** [comment]
No, if a mod says they require the client side, then we respect that.
There is no overriding.
You may think you're advanced, but this would cause far more issues then it'll fix.
This is like asking "ya, I know better then the server, so let me override the ID list with my own IDs"
If there is a mod that incorrectly states it needs the client side. Then talk to that mod author and have them fix it.

**Comment by ghost** [comment]
> Client side mods wouldn't be installed on the server though. Therefore makes this argument invalid.
> 
> All that would happen if this was added would the client would crash as it wouldn't know how to handle the modded items.
> 
> Please name a realistic scenario when you'd need to join a server with missing mods

Client side mods do end up installed on servers, so that point is invalid. Trying to track down what mods are actually needed on a given end isn't straightforward, since the only ways to tell is if the server logs it as such on startup, or the dev lists such (rare).

I actually ran into one today that has this issue, waitingtime.

And fair point lex, but there are edge cases where overrides are needed. While reporting for fixing is the optimal solution, sometimes it isn't so simple.

**Comment by LexManos** [comment]
There are no edge cases where overriding is necessary. It is by definition of mod issue and we will not be adding a hack into Forge to "fix" a non-forge issue.

And yes, client side mods may be installed on the server. but we already have mechanics in place to have the serve rnot load those mods if they are declared to be client side only.

So again, that is a Modder issue NOT a Forge issue.
