### ISSUE TITLE
[1.13.2] Exclusively underwater mob spawning, after world generation.

### ISSUE THREAD

**Issue by mrburger** [MinecraftForge/MinecraftForge#5523]
In Forge 25.0.34, all worlds generated will not spawn ANY passive or hostile mobs besides aquatic mobs. Even in newly created worlds, this issue occurs. Tested both with and without mods, in dev environment and outside dev environment using vanilla launcher. Issue persists in all world types, including custom-made World Types.

**Comment by LordMonoxide** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/5490
