### ISSUE TITLE
Seagrass - regular works but tall doesn't drop

### ISSUE THREAD

**Issue by Sana36** [MinecraftForge/MinecraftForge#5524]
Using shears on seagrass: works on regular seagrass dropping one but tall seagrass drops nothing.

**Comment by bs2609** [comment]
`BlockSeaGrassTall` extends `BlockShearableDoublePlant` which has this currently:
https://github.com/MinecraftForge/MinecraftForge/blob/785d9b8deb68ad25826811a7f28d38f9bd0dde87/patches/minecraft/net/minecraft/block/BlockShearableDoublePlant.java.patch#L28-L31

`BlockSeaGrass` doesn't implement `IShearable` at all at the moment.
