### ISSUE TITLE
[1.13.2] IWorld.getDimension().getType().getRegistryName() returned null for vanilla dimensions

### ISSUE THREAD

**Issue by zlainsama** [MinecraftForge/MinecraftForge#5527]
Forge Version: 1.13.2 - 25.0.36

**Comment by LexManos** [comment]
Yes, it's on my todo to remove them from IForgeRegistryEntries.

**Comment by zlainsama** [comment]
Okay.
~~After that, one would just retrieve unique identifier from vanilla equivalent method?~~
Edit: i found it.
