### ISSUE TITLE
[1.13.2] Any Block can be broken with any tier of the needed tool

### ISSUE THREAD

**Issue by TheLimePixel** [MinecraftForge/MinecraftForge#5529]
I'm unsure whether the issue comes from the harvest level of the blocks or the tools, but currently, provided that you're using the right tool, you can break a block with any tier of said tool. For example, you're able to break Iron Ore, Diamond Ore, Gold Ore and Obsidian with a Wooden Pickaxe.

**Comment by bs2609** [comment]
Harvest levels aren't currently being set as `initTools` isn't called, it still needs to be hooked in.

Currently this is all uncalled:
https://github.com/MinecraftForge/MinecraftForge/blob/785d9b8deb68ad25826811a7f28d38f9bd0dde87/src/main/java/net/minecraftforge/common/MinecraftForge.java#L70-L84
