### ISSUE TITLE
Dupe Class Cache

### ISSUE THREAD

**Issue by NullSector76** [MinecraftForge/MinecraftForge#5532]
hi I looking at the 1.12.2 launch class loader randomly and discovered you cache both the transformed class and the untransformed class one is in byte array form. 
LaunchClassLoader#resourceCache 

For modpacks and libraries this is going to take a lot of extra ram to run I suggest removing it if you haven't done so already. You can get isObf with a single class not the entire dupe class array as bytes loaded in to. Please save our ram and fix this

If it's already fixed for 1.13 sorry I couldn't find the class easily

**Comment by LexManos** [comment]
That class no longer exists in 1.13 as the launch system has been completely rewritten.

**Comment by NullSector76** [comment]
alright as long as there is no massive byte dupe cache in 1.13 thank you.

**Comment by NullSector76** [comment]
Hey @tterrag1098 I noticed that ClassLoader objects don't require any class storage at all and storing them anywhere is unoptimized. The jvm stores them for you please remove it if it still exists not sure what the current ClassLoader is just found out this new info and was updating you.

I tested this using a transformer that printed with the world class. Used reflection and played for 20 minuets with only one output of transforming the world class.

**Comment by LexManos** [comment]
Please do your research and know what you're talking about before coming to the repo.
This is not a place for random guesses and spam.
