### ISSUE TITLE
[1.13.2] Missing events for client side connection, like ClientDisconnectionFromServerEvent

### ISSUE THREAD

**Issue by zlainsama** [MinecraftForge/MinecraftForge#5536]
I couldn't find them anymore.
In previous versions, they were at net.minecraftforge.fml.common.network.FMLNetworkEvent.
I want to do some cleanup after client disconnected from server.
It is doable using TickEvent.

**Comment by 0uti** [comment]
net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedOutEvent()  possible?

**Comment by zlainsama** [comment]
That is on server side.

**Comment by cpw** [comment]
I'll take a look... Networking was completely revamped. Plenty of stuff is missing.

**Comment by irtimaled** [comment]
Please also include the ClientConnectedToServerEvent as well.

**Comment by cpw** [comment]
OK. Rather than simply porting the mess of 1.12 events to 1.13, I want to know what people are looking for in terms of networking. There's already calls when you connect and disconnect, via the channel code. If you're trying to do networking without a channel what are you looking for?

**Comment by SquidDev** [comment]
I currently use them to clear various client side registries when the player logs onto/off a server ([see here](https://github.com/dan200/ComputerCraft/blob/master/src/main/java/dan200/computercraft/shared/proxy/ComputerCraftProxyCommon.java#L601-L611)). These are something which are added to and removed from as computers are loaded/unloaded, rather than being sent at the initial connect.

**Comment by irtimaled** [comment]
I use these client events to load structure data based on the name/ip of the server, and to clear down server specific caches

**Comment by zlainsama** [comment]
I use them to clear caches about players. They are fairly small and doesn't change much so i keep them in memory on a per profile basis, but it requires a cleanup upon connect/disconnect.

**Comment by maxanier** [comment]
I also have a collection of values/dynamically generated configuration that is sever specific which I currently prepare when a connection is established and clear when the client disconnects
