### ISSUE TITLE
[1.13.2] Switch to Non-Null FluidStacks

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#5538]
With all the changes that are happening, it seems like 1.13 would be a good time to re-evaluate the fluid system and move to non-null fluidstacks in a similar pattern to how Itemstacks are done now.  

It would also be a good time to bring consistency between IFluidHandler and IItemHandler with regards to parameter names and expected results (#4693)

**Comment by gigaherz** [comment]
This has been implemented as of forge 28.0.74 for 1.14.4.
