### ISSUE TITLE
[1.13.2] The config does not actually reload when config file changes

### ISSUE THREAD

**Issue by zlainsama** [MinecraftForge/MinecraftForge#5541]
ModConfigEvent.ConfigReloading was fired in these two situations:
- Received synced config from server
https://github.com/MinecraftForge/MinecraftForge/blob/329f26ee2099f1747895aa67706a8daeec04a749/src/main/java/net/minecraftforge/fml/config/ConfigTracker.java#L97-L98
- Config file changed in the disk
https://github.com/MinecraftForge/MinecraftForge/blob/329f26ee2099f1747895aa67706a8daeec04a749/src/main/java/net/minecraftforge/fml/config/ConfigFileTypeHandler.java#L73-L74

In the first situation, the config data was updated before event was fired.
In the second situation, the watcher does not reload the config before sending event.
And, ModConfig.setConfigData() is not visible from a mod, ConfigTracker does not permit duplicates.

Are mods responsible to reload the config by themselves? If so, how?

**Comment by cpw** [comment]
No, this is probably a behavioural bug. I'll investigate..

**Comment by olee** [comment]
Having the same issue here - event is fired but config still has old values
(On 1.14.3 though)
