### ISSUE TITLE
[1.13.2] (Suggestion / Question) Allow clients to get the current server´s maximum player count

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [MinecraftForge/MinecraftForge#5542]
In 1.12 you could use `Minecraft.getMinecraft().getConnection().currentServerMaxPlayers` to get the maximum player count.
In 1.13 the field `currentServerMaxPlayers` does no longer exist. If there is any alternative to get the max player count on the **client side** or the field was just moved to another class let me know. If not could this get re-implemented?

**Comment by williewillus** [comment]
you can investigate this yourself by looking at the client's server list gui screen, it has to store the count somewhere to display it to the user.

**Comment by MJRLegends** [comment]
Server
```
MinecraftServer#getMaxPlayers()

or if you dont have a MinecraftServer object then

ServerLifecycleHooks.getCurrentServer().getMaxPlayers()
```

Client
`Not sure you'd have to look that up`

**Comment by ErdbeerbaerLP** [comment]
That is serverside only

**Comment by MJRLegends** [comment]
Updated my message, You could always just send the data yourself through a packet

**Comment by MJRLegends** [comment]
With a two second look, ServerPinger class seems to be a good place to start for client side server info

**Comment by LexManos** [comment]
Looking into it, the server pinger is the way to go. It lists the active players and max, as you can see inside the multiplayer server gui.
Not sure where the 'current' data is stored while in game. It probably isn't as it doesn't seem to be something that is needed.

But ya, this shouldn't need anything in Forge. You just need to dig into MC.
