### ISSUE TITLE
Open gui does not send container contents (or too early)

### ISSUE THREAD

**Issue by HyCraftHD** [MinecraftForge/MinecraftForge#5543]
If you call `NetworkHooks.openGui(playermp, (IInteractionObject) tileentity, buf -> buf.writeBlockPos(pos));`
to open a gui container from a tileentity (server side) it should sync the inventory contents from the server to the client. (Only happens if the client side does not know the inventory contents. e.g. world rejoin.
The method calls `player.openContainer.addListener(player);` which calls the sync method `listener.sendAllContents(this, this.getInventory());`.
But it dont reach the client side, because the forge packet to open the gui arrives later that the SPacketWindowItems so the packet does nothing.

You can fix it (as a modder for now) if you call `playermp.sendAllContents(...)` your self after the gui open call.

**Comment by williewillus** [comment]
The issue here is forge packets and vanilla packets aren't properly ordered

**Comment by cpw** [comment]
OK. Will look tonight

**Comment by cpw** [comment]
Should be fixed by 8d1ff45c718b7e1ec2b2b42b76ff205607883918
