### ISSUE TITLE
[1.13.x] Can't seem to setup the workspace.

### ISSUE THREAD

**Issue by LoudSoftware** [MinecraftForge/MinecraftForge#5546]
I am using IDEA IntelliJ IDEA 2018.3.4 Build #IU-183.5429.30 and am trying to follow the instructions in the wiki to setup the dev environment but I noticed that a few things were missing. Have the instructions changed, or am I missing something?

I can't seem to find any gradle task to setup the decompilation workspace, so each time I try to compile the whole project, I get tons of errors stating that `net.minecraft.foo` can't be resolved.

**Comment by Superloup10** [comment]
You just have to import the build.gradle into IDEA.

**Comment by 0uti** [comment]
or just run "./gradlew setup" from command line
(Windows: "gradlew.bat setup" )

**Comment by LoudSoftware** [comment]
Hmm, everything seems to work right now. I started from scratch and checked out 1.12.x imported it's build.gradle and then checked out to 1.13.x without importing the changes. Then I ran setup and synced after.

Just as a safety net, I'll try from scratch again with 1.13.x and no funky stuff and report back.

**Comment by LoudSoftware** [comment]
Welp, everything seems to work out of the box today. No clue why it wasn't working earlier.
