### ISSUE TITLE
[1.13.2] GuiScreenEvent.ActionPerformedEvent not getting fired

### ISSUE THREAD

**Issue by zlainsama** [MinecraftForge/MinecraftForge#5548]

**Comment by LexManos** [comment]
These events are not fired because the entire input chain changed in 1.13. From looking at it, this should NOT need to be fired. As you can just add any handlers you want to the child list of GuiEventHandler and you should be golden.

**Comment by zlainsama** [comment]
ActionPerformedEvent was fired for all buttons clicked.
I was using it to shift other buttons i added when a recipebook component changes position of the gui.
There is no problem in custom gui since you can easily use a custom button for that recipebook component, but when you add buttons to the normal player inventory gui, you will need to re-add a altered GuiButtonImage for that recipebook component, which will break if other mods are doing the same thing.
Because of how GuiEventHandler works, if one of the children answered mouseClicked, other children won't be notified unless they are added before that. Even if they are notified due to they are ahead of that one, they wouldn't be able to know if that one will be triggered in this mouseClicked event.
I'm currently using DrawScreenEvent.Pre to shift my added buttons around when the gui changed by a recipebook component. A RecipeBookToggleEvent would also solve my problem.

**Comment by LexManos** [comment]
Closing as your usecase should be able to be accomplished using the vanilla button interact list. If not, go to the forums for some community debugging and if you find it is a feature that needs expanding in Forge open another issue with a test mod.
