### ISSUE TITLE
Error when installing forge-1.13.2-25.0.45-installer

### ISSUE THREAD

**Issue by RayzoRayy** [MinecraftForge/MinecraftForge#5549]
I receive an error saying I can't download the forge libraries. I've tried 2 different versions of Forge but both show same issue. The versions I tried were 25.0.45 , and 25.0.44. Here is the log that was compiled from the installer.
https://pastebin.com/ngPDecRr
![79624434_forgefail thumb png 4d1421ef1a102e59d9128a3af9424323](https://user-images.githubusercontent.com/9391592/53211389-fa66e480-360e-11e9-9da1-1f7e95e14d8e.PNG)

**Comment by DaemonUmbra** [comment]
This looks more suited to the forums.
