### ISSUE TITLE
[1.13.2] Config does not allow leading or trailing '.'

### ISSUE THREAD

**Issue by MajorTuvok** [MinecraftForge/MinecraftForge#5554]
Hello... I was just trying to find out, why parsing the Pattern ".\*" from Config does not work. It turned out, that the Config always returned me "\*". The List containing the said config is defined as follows:
```
blockWhitelist = SERVER_BUILDER
                    .comment("Allows you to define a whitelist, allowing Patterns to be defined in the same way as the blacklist.")
                    .translation(LANG_KEY_BLACKLIST + ".blockWhitelist")
                    .defineList("Whitelisted Blocks",ImmutableList.of(".*"),obj -> obj instanceof String);
```

with the Corresponding part of the config being:
```
#Configure your Blacklist-Settings here
["Blacklist Settings"]
	#Allows you to define a whitelist, allowing Patterns to be defined in the same way as the blacklist.
	"Whitelisted Blocks" = [".*"]
	#All Blocks added to this will be treated similar to TileEntities. Not at all.
	#Notice that you can use Regular Expressions as defined by Java Patterns to express more complex name combinations.
	#Use for example "awfulmod:.*" to blacklist all awfulmod Blocks.
	"Blacklisted Blocks" = ["minecraft:.*_door.*", "minecraft:piston_head"]
```
I naturally attempted to escape the leading '.' but that apperently resulted in it Failing to load because of an "Invalid Escapement: \\.". So could we maybe allow leading '.''s or if that is not possible allow them to be escaped? [If it is a non-leading '.' it is parsed as expected by the way... So I guess there is some kind of trimming, which destroys this here]
(Tested in 25.0.48)

**Comment by MajorTuvok** [comment]
I just tested: trailing "." are removed as well.

**Comment by cpw** [comment]
Try `\\.` instead. `\.` is not a valid regular expression.

**Comment by MajorTuvok** [comment]
I guess you're referring to \\ in the File, not in code (\. obviously doesn't work in code...) I'll try doing \\\\ in Code (or \\. In the File resepctively)

**Comment by MajorTuvok** [comment]
I just noticed, that I overlooked that github also needs \\\\ to make an \\ if you don't mark it as code
```
Only Default value: ".*"
File: [".*"]
Given List contains: "*"
Only Default value: "\\.*"
File: ["\\.*"]
Given List contains "*"
Only Default value: "\\\\.*"
File: ["\\\\.*"]
Given List contains "*"
```

**Comment by MajorTuvok** [comment]
The way I got to an `\.*` was by manually editing the File instead of the default value... I didn't think that it would work, but one could have hoped.

**Comment by MajorTuvok** [comment]
Ok so in the most recent Forge Version (25.0.74) changed something (It has been a while since I last tested, so I don't know when it changed): It know loads correctly during Mod loading everything works fine, but as soon as I enter a World, the `ModConfig.Loading` event made me check, that the config lost leading '.'s again:
![image](https://user-images.githubusercontent.com/25031360/54075485-356c4780-42a0-11e9-8b26-015f1543c1ee.png)

**Comment by MajorTuvok** [comment]
When writing an examplemod in 25.0.79, this magically resolved itself in this newer version.
