### ISSUE TITLE
Iron ore frequency - very low 1.13.2. beta v48

### ISSUE THREAD

**Issue by Sana36** [MinecraftForge/MinecraftForge#5557]
Previous frequencies of iron ore seemed to be quite generous, in this version (v48) it is really very low. This is as found in normal survival gameplay. A comparison coal stopped mining around 5x64, took many days (20s) of exploring in and through mountains to find seven iron ore in one grouping.

Has anyone else noticed a drop?

**Comment by LexManos** [comment]
Vanilla: 
![](http://puu.sh/CRHda/4ba7cabe84.jpg)

Forge:
![](http://puu.sh/CRHi6/f0cc5b82cd.jpg)

Roughly the same location. But this most definitely illustrates that this issue can not be reproduced. Iron ore is quite prevalent.
