### ISSUE TITLE
[1.13.2] Alternative NetworkHooks.openGui()

### ISSUE THREAD

**Issue by zlainsama** [MinecraftForge/MinecraftForge#5558]
I switched to use NetworkHooks.openGui(), but it calls closeScreen() instead of closeContainer().
closeScreen() will spawn a SPacketCloseWindow causing client close currently opened Gui.
This is undesired behavior in a scenario of switching between extended player inventory gui and normal player inventory gui.
Because the mouse cursor will be reset to the middle of the screen.
And constructor FMLPlayMessages.OpenContainer() is not visible from a mod.
One would still need to use self written code to open a gui in cases described above.

**Comment by williewillus** [comment]
I would just change it to use closeContainer, the constructor has no reason to be public

**Comment by cpw** [comment]
Fixed by 8d1ff45c718b7e1ec2b2b42b76ff205607883918
