### ISSUE TITLE
[1.13.2] Missing event for CustomPacketRegistrationEvent on server side

### ISSUE THREAD

**Issue by irtimaled** [MinecraftForge/MinecraftForge#5565]
Previous versions were here https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/client/FMLClientHandler.java#L856

This is super useful to only send content to clients with mod installed and channel registered.

**Comment by cpw** [comment]
Please _greatly_ expand what you expect to happen here? There are many ways to send data to the client, especially during a login phase. I'd rather you use those than this.

**Comment by irtimaled** [comment]
In earlier versions I had an issue where vanilla clients couldn't connect to forge servers because they didn't like the custom packets I was sending from my mod. To solve this I used the CustomPacketRegistrationEvent on the server side to know when a client has the mod installed, and then only send subsequent packets to those clients that have the mod.

I raised this issue after seeing it wasn't implemented in the 1.13.2 forge codebase. Happy to try other avenues if you can suggest how I can, from the server, know if a mod is installed on the client.

**Comment by cpw** [comment]
This should no longer be an issue, if you declare compatibility with vanilla. All vanilla connections are marked with ConnectionType.VANILLA.
