### ISSUE TITLE
[1.13.2] Incompatible with JNA?

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [MinecraftForge/MinecraftForge#5575]
The game fails to load JNA for some reason...
__Log:__
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/2911639/latest.log)
__Crash Report:__
[crash-2019-02-27_18.59.41-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/2911704/crash-2019-02-27_18.59.41-client.txt)

__This is additionally shown below the log in the launcher log:__
```
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
	at de.erdbeerbaerlp.discordrpc.DRPC.lambda$clientSetup$14(DRPC.java:69)
	at java.lang.Thread.run(Thread.java:745)
AL lib: (EE) alc_cleanup: 1 device not closed
```

When attaching to the process and start debugging it opens this line upon crash: https://github.com/MinnDevelopment/java-discord-rpc/blob/master/src/main/java/club/minnced/discord/rpc/DiscordRPC.java#L42

(This does not happen in development environment)

**Comment by HyCraftHD** [comment]
I think this might be your fault and not forge ones. Probably you should check you class and resource paths (``Native library (com/sun/jna/win32-x86-64/jnidispatch.dll) not found in resource path``)

**Comment by ErdbeerbaerLP** [comment]
If you tell me how to do that with the vanilla launcher (since it works in dev environment) i can do that.
(Also edited the link to link to the correct discord rpc repository, had used a different one as the link)
