### ISSUE TITLE
Problem with custom ingredient serialization

### ISSUE THREAD

**Issue by HyCraftHD** [MinecraftForge/MinecraftForge#5577]
When you want to connect to a server with a custom recipes and ingredients the server must send the recipe with ingredients to the client. 

It will cause an error on the client like shown: 
![grafik](https://user-images.githubusercontent.com/7681220/53530369-e845e400-3aef-11e9-8445-8dad72caf2ab.png)

If you make a try catch on the read method in a recipe the stacktrace is:
https://pastebin.com/DHKZsnwk

The error therefore must be in the method ``PacketBuffer.readString``.

So lets investigate what the serverside sends to the client. (Class net.minecraftforge.common.crafting.CraftingHelper)
![grafik](https://user-images.githubusercontent.com/7681220/53530637-cd27a400-3af0-11e9-97ba-d4aa850f892b.png)
It will send a varInt and then a resourcelocation which will be send as a string.
The string then will first send a varInt with its length and then its content.

The clientside tries to read the PacketBuffer. (Class net.minecraft.item.crafting.Ingredient)
![grafik](https://user-images.githubusercontent.com/7681220/53530710-0233f680-3af1-11e9-911e-8385002ea671.png)
First it will mark the current index for reading. Then it will read the first varInt which is negative 1 because its a custom ingredient. In the if it will reset the buffer to the first varInt. 
Now it tries to read the ResourceLocation. This is a string and read the varInt and then the content.
And here is the Problem. Because of the resetReaderIndex the wrong varInt is readed and this is -1 and so it will crash here.

An easy fix is to remove the resetReaderIndex, because I dont see any use here.

**Comment by LexManos** [comment]
Actually the reset isnt needed at all, this was me thinking about ItemStacks. So removing and should be fine.
