### ISSUE TITLE
Playing sounds crashes the client

### ISSUE THREAD

**Issue by VsnGamer** [MinecraftForge/MinecraftForge#5584]
This is probably related to #5408 

When playing modded sounds, crashes the client.

However it only occurs when the mod is built and installed on a normal forge instance, it does NOT occur on the testing environment (runClient).

[Here's](https://pastebin.com/1RgTKPdN) the log when the client crashes (I can provide more if necessary)

Thank you for your attention

**Comment by VsnGamer** [comment]
Also lang files are not loaded (they are also loaded correctly in the test environment).

**Comment by williewillus** [comment]
definitely related (@cpw)

whatever fix for this needs to be careful not to reintroduce the original issue

**Comment by VsnGamer** [comment]
Ok, the sound problem seems to be fixed, but lang json files are a little buggy

On my desktop dev environment they load fine (IDEA runClient), on normal build client they don't load.

But today I cloned the dev environment to my laptop and lang files did not load even on debug client(IDEA runClient)

**Comment by VsnGamer** [comment]
Update: I looked to vanilla lang files and renaming the file from "en_US.json" to "en_us.json" (like vanilla) did fix the lang everywhere.

(Idk how "en_US.json" worked in my desktop environment I guess it was a cache related matter)
