### ISSUE TITLE
Is Optifine working in latest 1.13.2 forge?

### ISSUE THREAD

**Issue by axemwa** [MinecraftForge/MinecraftForge#5586]
Is optifine working in latest 1.13.2 forge?
If so how do I get it to work, as the old way isn't working?

**Comment by LexManos** [comment]
Optifine needs to add support for the re-written loading system. This is on them as it has always been, not us. They will specifically say when they are compatible.

**Comment by axemwa** [comment]
ok thankyou for informing me
