### ISSUE TITLE
[1.13.2] NoSuchMethodError thrown for vanilla methods called from mods in run/mods

### ISSUE THREAD

**Issue by BlakeBr0** [MinecraftForge/MinecraftForge#5587]
Example crash: https://gist.github.com/BlakeBr0/4bdb92191cbfd7ae33954e72a6716c0c

This also happens in the latest MDK.

**Comment by LexManos** [comment]
Yes, it does not deobf mods in the mods folder. Use deobf demps in your build.gradle.

**Comment by BlakeBr0** [comment]
The only reason I tried putting mods there was because the dependencies weren't loading when I would start the game. I'm probably just doing something wrong though.
