### ISSUE TITLE
[1.13.2] Impossible to teleport player to modded dimensions

### ISSUE THREAD

**Issue by naritanara** [MinecraftForge/MinecraftForge#5593]
In the 1.13.2 forge beta, you can register dimensions, but it's impossible to take the player to them.

I've made a repo with a simple example that can be tryed: https://github.com/rdvdev2/1.13-dimension-test

To test it compile the mod, open a creative world, type /give PlayerXXX examplemod:item, and right-click the item. Nothing will happen.

I don't know if that is my fault, but I have been investigating for a few hours and I haven't seen anyone's code that works.

**Comment by LexManos** [comment]
That is because your using it wrong. Do not make static DimensionTypes, use The DimensionManager.
You need to use the DimensionType that the manager creates. As this is re-created every time the server starts.

**Comment by naritanara** [comment]
Thanks for anwsering. I have investigated the class and I don't find a way to get that instance. I haven't seen any method for that in the DimensionManager and the methods on DimensionType return me null.

**Comment by williewillus** [comment]
you can get it by querying `DimensionManager.getRegistry` (though it is marked deprecated, and registerDimension returns void)

**Comment by naritanara** [comment]
I will try, thanks!

**Comment by LexManos** [comment]
Do not use getRegistry it's an internal function. Hence why it's marked deprecated and commented as such. There should be a way to access it without internal stuff. Perhaps in the register event...
It may need looking into, registerDimension mgiht need to change to return the DimensionType instance.
For convenience. But again, remember this should be done in the Register event we fire.
Should probably also add getExisting(ResourceLocation) to the RegisterDimensionsEvent. So they can query the ones we've loaded from disc...

**Comment by naritanara** [comment]
Currently I'm registering the dimension in the RegisterDimensionsEvent, and when I inspect the DimensionManager registry with the IDEA debugging tools, my dimension type isn't here.

**Comment by LexManos** [comment]
Provide your proper updated code.
As you can see on our end, it clearly adds it: https://github.com/MinecraftForge/MinecraftForge/blob/1.13.x/src/main/java/net/minecraftforge/common/DimensionManager.java#L105

**Comment by naritanara** [comment]
I've just updated the repo: https://github.com/rdvdev2/1.13-dimension-test

**Comment by LexManos** [comment]
After digging more into this. When i got time to debug your code. It's an obvious user error.
Proptip: Make sure your event handlers are actually getting called.
You registered your setup function on the wrong bus.

**Comment by naritanara** [comment]
That was the error, now all is working right. Thanks for all the help!
