### ISSUE TITLE
[1.13.2] Add a more performance efficient way to check if a command argument exists

### ISSUE THREAD

**Issue by The-Fireplace** [MinecraftForge/MinecraftForge#5597]
Currently, when overriding `Command.run(CommandContext<S>)`, there is no performance efficient way to check if a tag exists. The current options, because `CommandContext.arguments` is private, are to use [try and catch around `CommandContext.getArgument(String, Class)`](https://github.com/The-Fireplace-Minecraft-Mods/Grand-Exchange/blob/master/src/main/java/the_fireplace/grandexchange/GeCommands.java#L144-L148), as shown in the linked example, or to use access transformers to make `CommandContext.arguments` public, or to use reflection to get the value of arguments. Obviously, none of these options are good for performance or other reasons, and as shown in the file linked above, being able to check if an argument exists is useful for being able to execute a command with optional arguments.

Possible solutions:
I see several possible solutions to this issue. I'm considering writing a Pull Request, but I'd like feedback on the best solution before I start working on one.
1. Add a new function called `hasArgument(String, Class)` to `CommandContext`. This would check that `CommandContext.arguments` contains the correct key and that the value in the map is the correct type.
2. Change the visibility of `CommandContext.arguments` to protected or public. This would allow commands to use `arguments.containsKey(String)` to see if the argument is there. I feel that while this would allow fewer changes to vanilla Minecraft code, it would mean more lines of code have to be written by mods if they want to verify that the argument is the correct type.

**Comment by williewillus** [comment]
> being able to check if an argument exists is useful for being able to execute a command with optional arguments.

this should be a dedicated split in your command tree when you register the command. ad-hoc "testing" for the presence of args is exactly what the old system was and what brigadier tries to avoid

**Comment by The-Fireplace** [comment]
> a dedicated split in your command tree when you register the command

As in, having two different versions of a command, one that runs without the argument and a different version that runs with the argument present? I suppose that's doable. I didn't realize brigadier was intentionally trying to avoid situations like this. Thanks.

**Comment by williewillus** [comment]
the same command can recognize forms that explicitly don't specify the option and process them differently. 

if you desugar how `GiveCommand` does this you'll see it in action. You can stop early without a count or give it a count, and in either case it executes the same method, just passing in a default value. Example:
![annotation 2019-03-06 214843](https://user-images.githubusercontent.com/2015032/53931161-ab32a200-4059-11e9-8e31-efc08ec11073.png)

This says "after getting a target and item, either execute if there's nothing left or take a count then execute". Make sure to get the parentheses right.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/1.13.x/src/main/java/net/minecraftforge/server/command/CommandGenerate.java#L52 A simple example on how to use optional arguments. The new command system is powerful, Use it.

**Comment by The-Fireplace** [comment]
Ah, yes. Those are perfect examples (and slightly better optimized) of what I was thinking of doing after I saw williewillus's first response. Thanks again, and I'll definitely use the power of the new command system.
