### ISSUE TITLE
ItemStackHandler onContentsChaged() is unreliable when used in combination with SlotItemHandler

### ISSUE THREAD

**Issue by Archengius** [MinecraftForge/MinecraftForge#5598]
SlotItemHandler implementation of isItemValid has special case for IItemHandlerModifiable, calling setStackInSlot with air and then previous stack.
```
if (handler instanceof IItemHandlerModifiable) 
{
            IItemHandlerModifiable handlerModifiable = (IItemHandlerModifiable) handler;
            ItemStack currentStack = handlerModifiable.getStackInSlot(index);
            handlerModifiable.setStackInSlot(index, ItemStack.EMPTY);

            remainder = handlerModifiable.insertItem(index, stack, true);

            handlerModifiable.setStackInSlot(index, currentStack);
 }
```
Yet, setStackInSlot call results a call of onContentsChaged() in ItemStackHandler, with new content being air stack first, and then old item. If onContentsChaged is overriden, it's unreliable to use it for tracking item change, because every time somebody calls isItemValid it will be called too with air stack.
My use-case was filter upgrade, where removing filter wipes out filtering preferences, and current implementation makes system think that filter is removed when clicking on slot with item that can't be inserted.

**Comment by loordgek** [comment]
can we call
https://github.com/MinecraftForge/MinecraftForge/blob/1.13.x/src/main/java/net/minecraftforge/items/IItemHandler.java#L121
from SlotItemHandler isItemValid ??

**Comment by LexManos** [comment]
We DO call IItemHandler.isItemValid from SlotItemHandler.isItemValid. He just needs to override that function that has existed for 8 months. The old code is backwards compat code.
But thanks for reminding me to delete it.
