### ISSUE TITLE
[1.13.2] ItemPickaxe and ItemSword take in an int for their attack damage but cast themselves to a float

### ISSUE THREAD

**Issue by HarryTechRevs** [MinecraftForge/MinecraftForge#5599]

**Comment by HarryTechRevs** [comment]
public ItemSword(IItemTier tier, int attackDamageIn, float attackSpeedIn, Item.Properties builder) {
      super(tier, builder);
      this.attackSpeed = attackSpeedIn;
      this.attackDamage = (float)attackDamageIn + tier.getAttackDamage();
   }

protected ItemPickaxe(IItemTier tier, int attackDamageIn, float attackSpeedIn, Item.Properties builder) {
      super((float)attackDamageIn, attackSpeedIn, tier, EFFECTIVE_ON, builder.addToolType(net.minecraftforge.common.ToolType.PICKAXE, tier.getHarvestLevel()));
   }

**Comment by williewillus** [comment]
not seeing how this is a problem?

**Comment by HarryTechRevs** [comment]
All the other tools take in float for this value, and tool materials also use float. I have to cast the tool material value to an int and then it gets casted back in the subsequent class

**Comment by LexManos** [comment]
Yes, im not seeing this as a problem. Yes it's some unnecessary casts, but Vanilla has those all over the place. Adding the cost of maintaining new constructors for all of these classes and setting the president of adding helper methods is not worth it. Just cast the value.
