### ISSUE TITLE
Invalid signature state when game crashes early

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#5604]
If the game crashes before a mod has been constructed, that mod will be reported as having no signature. This can, and has, lead to speculation that some mods have been tampered with when they are perfectly fine. I would like to propose that the system shows a different status when it's not loaded, or maybe even check the signature before the mod is constructed. 

You can reproduce this issue by installed [BiomeSpecificDungeons 1.0.0](https://minecraft.curseforge.com/projects/biome-specific-dungeons) and [Bookshelf 2.3.577](https://minecraft.curseforge.com/projects/bookshelf/files/2683823). BiomeSpecificDungeons needs a class in Bookshelf at construction time but it loads before Bookshelf causing a crash. (Yes, this is my issue and is a big stupid on my part). Crashing at this stage of loading causes both BSD and Bookshelf to report as having no signature, when they actually do and both are validly signed. 

[Example Log](https://gist.github.com/darkhax/e1563d530c9baa831545f6f755e0d41a)

**Comment by LexManos** [comment]
Please provide the actual crash/error message you are getting for debugging purposes when we get a time to look into it.

**Comment by Darkhax** [comment]
I've attached a crash log to the original post. Please keep in mind that the nature of the crash in this instance is my own fault due to forgetting to specify load order dependencies. The issue that this issue report is about can be reproduced by any crash that happens during this loading stage.
