### ISSUE TITLE
[1.13.x] Need way to have different collision VoxelShapes depending on entity

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#5612]
In the past we could override `Block.addCollisionBoxesToList`, which received an entity allowing us to change collision based on the entity (for example, if the entity is sneaking, let them fall through the block; or if it's a certain type of entity, use different colliding rules)

since everything moved to getCollisionShape, there's no longer a way to do that

**Comment by tterrag1098** [comment]
I added a new method to ISelectionContext to retrieve the entity. It seems that vanilla properly uses the entity context in most spots, but it's possible I missed one where it should. It requires further testing, but this should cover 99% of cases at least.
