### ISSUE TITLE
[1.13.2] Other mods' Access Transformers not applied while in a deobf environment

### ISSUE THREAD

**Issue by Tamaized** [MinecraftForge/MinecraftForge#5620]
Discovered this while debugging:
https://github.com/mezz/JustEnoughItems/issues/1512#issuecomment-473707301

To reiterate, I had placed a breakpoint here:
https://github.com/MinecraftForge/AccessTransformers/blob/2b9c7950bfd2e6b654fde244b789727eefaa8bc1/src/main/java/net/minecraftforge/accesstransformer/AccessTransformerEngine.java#L34
And I've noticed `fn.name` shows a mapped name while `fieldTransformers` contains all srg names (obviously) thus checking against `.containsKey(fn.name)` will always fail.
As shown here: https://cdn.discordapp.com/attachments/418125698486632448/556912816930684932/unknown.png

I did a test where instead of srg names in the dependency `accesstransformer.cfg` file, I used mapped names instead. Tossed the new test jar into my workspace and had no issues whatsoever.

**Comment by cpw** [comment]
I'll look at this next time I'm home. Sadly that's likely a week from now :rage:

**Comment by cpw** [comment]
I already have infrastructure in place to try and help solve this.

**Comment by cpw** [comment]
Closing, implemented in cdbd84249495e1385e2657fca986229779dd0efc
