### ISSUE TITLE
[1.12.2] EnchantRandomly loot function does not check isAllowedOnBook

### ISSUE THREAD

**Issue by FreneticScribbler** [MinecraftForge/MinecraftForge#5625]
```java
public ItemStack apply(ItemStack stack, Random rand, LootContext context) {
Enchantment enchantment; 
if (this.enchantments.isEmpty()) { List<Enchantment> list = Lists.<Enchantment>newArrayList(); for (Enchantment enchantment1 : Enchantment.REGISTRY) { 
if (stack.getItem() == Items.BOOK || enchantment1.canApply(stack)) { list.add(enchantment1); 
}
} 
```
The check for an item being a book is hard coded. I suggest either this is changed from an OR function to an AND one, or more sensibly that this is patched to check isAllowedOnBook. (The other vanilla loot function is already patched to use the check because it delegates to a patched method)

**Comment by Tfarcenim** [comment]
this still an issue in 1.14?
