### ISSUE TITLE
[1.13.2] NPE on Server join

### ISSUE THREAD

**Issue by Foorcee** [MinecraftForge/MinecraftForge#5626]
This error comes a few times when I try to enter a server.
Bungeecord / spigot server
Version: 1.13.2

`Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException at java.util.concurrent.FutureTask.report(FutureTask.java:122) at java.util.concurrent.FutureTask.get(FutureTask.java:192) at net.minecraft.util.Util.func_181617_a(SourceFile:200) at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:761) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:358) at net.minecraft.client.main.Main.main(SourceFile:144) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:497) at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$289/1237912220.call(Unknown Source) at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19) at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32) at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) at cpw.mods.modlauncher.Launcher.run(Launcher.java:56) at cpw.mods.modlauncher.Launcher.main(Launcher.java:42) Caused by: java.lang.NullPointerException at net.minecraft.scoreboard.Scoreboard.func_96511_d(SourceFile:199) at net.minecraft.client.network.NetHandlerPlayClient.func_147247_a(NetHandlerPlayClient.java:1715) at net.minecraft.network.play.server.SPacketTeams.func_148833_a(SourceFile:122) at net.minecraft.network.play.server.SPacketTeams.func_148833_a(SourceFile:16) at net.minecraft.network.PacketThreadUtil.func_210405_a(SourceFile:10) at net.minecraft.network.PacketThreadUtil$$Lambda$1686/724946449.run(Unknown Source) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at net.minecraft.util.Util.func_181617_a(SourceFile:199) ... 14 more`

**Comment by Morpheus1101** [comment]
Im able to join a Spigot server the 1st time aok then after an hr if i get disconnected for any reason i'll get the below error, but thats all i get, logs show nothing for me.
> Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException

**Comment by ForceUpdate1** [comment]
The error does not always come

**Comment by Morpheus1101** [comment]
Im able to consistently reproduce it with my setup and the time period i mentioned.

**Comment by JoJoDeveloping** [comment]
I tend to get this the second time I join a server. The first time everything works fine.
