### ISSUE TITLE
[1.13.2] Mouse click, release, drag Post are never reported in GuiContainers

### ISSUE THREAD

**Issue by YaLTeR** [MinecraftForge/MinecraftForge#5627]
`GuiContainer.mouse{Clicked,Released,Dragged}()` return `true` unconditionally thus suppressing all Post events. I think I need these for Mouse Tweaks so it doesn't interfere with any container-specific behavior.

**Comment by bs2609** [comment]
Seems like the same type of issue as in #5367, perhaps that should be updated to cover mouse handling as well?

**Comment by YaLTeR** [comment]
cc @mezz

**Comment by mezz** [comment]
I took a look, but `GuiContainer#mouseClicked` is very complicated so I do not want to put it in the same PR. I did add it to the vanilla issue though, [MC-146650](https://bugs.mojang.com/browse/MC-146650).

**Comment by YaLTeR** [comment]
@mezz you noted in the Minecraft issue:

> I misinterpreted the purpose of this return value. There is no bug, please close this issue.

So, this can be closed, then? Also, what's the purpose of that return value? And, I guess, I should use `Pre`?

**Comment by pau101** [comment]
The return value is success/fail. As such it returns false only to pass though what is on screen. If you need to intercept events you may formally add a widget to the gui or use pre to potentially hijack a click.

**Comment by YaLTeR** [comment]
For Mouse Tweaks I ended up using Post for `MouseScrollEvent` (which for example allows the creative container to handle its scrolling instead of Mouse Tweaks overriding it), but Pre for `Mouse{Clicked,Released,Drag}Event` due to this issue. This means that Mouse Tweaks is prioritized over any potential custom container click/release/drag behavior. Whether there exists a mod container for which this is an issue, I'm not aware.

**Comment by FinnT730** [comment]
So...... 1.13.2 is not supported anymore.
So does this also happen in 1.14.4 or 1.15.2?

**Comment by YaLTeR** [comment]
I will re-check in 1.15 tomorrow.

**Comment by YaLTeR** [comment]
Confirming this is the same on 1.15.2-31.1.0. Those methods still return true unconditionally.

**Comment by pau101** [comment]
As brought up before, they do not return true "unconditionally", the meaning of returning false is the click passes to the game, triggering keybindings, e.g. right clicking in background of inventory while holding ender pearl and it throwing. Actually, it permanently holds the key until pressed again for bugged reasons. You can see this effect in vanilla if you decrease your game window width such that the recipe book switches to on top of inventory and click outside of it.

To reinstate the Post click events more is required than simply changing return values.

**Comment by YaLTeR** [comment]
Oh, I see. Yeah, I wasn't aware of these specifics—I just noticed that the mouse wheel sent Post events in containers and other mouse events didn't.

Now that I think of it, even if the methods returned true only when the click was "handled" by the container (as in, some items were put in slots for example), Mouse Tweaks would _need_ to override them in certain cases, so it would need to use Pre anyway.

Feel free to close this then.
