### ISSUE TITLE
EntityItem setNoDespawn does not work as intended

### ISSUE THREAD

**Issue by CreativeMD** [MinecraftForge/MinecraftForge#5628]
Hey there,

after somebody reported an issue related to itemphysic (https://github.com/CreativeMD/ItemPhysic/issues/79) about despawning items, I tried to figure out what was going wrong.

It appears like `EntityItem.setNoDespawn()` does not work as intended. It sets the age to -6000, which essentially doubles the life time, but it's not infinite.

I'm not sure if this is a vanilla issue or an issue of forge.  The nether star is supposed to stay forever, which is not the case using Forge ([wiki](https://minecraft.gamepedia.com/Nether_Star)).

```java
public void onUpdate() {
    [...]
    if (this.age != -32768)
    {
        ++this.age;
    }
    [...]
}
```
In `Entity.onUpdate()` it checks whether the age is not `-32768`, if true it will increase the age. This value is also used when combing EntityItems together (to prevent combining despawning and infinite items together). So my assumption is that `EntityItem.setNoDespawn()` should set the age to `-32768`.

However somebody reported this issue to Mojang (https://bugs.mojang.com/browse/MC-125027) and they marked it as `works as intended`. Maybe the mcp name is confusing and the method should instead be called something like `setDoubleLifeSpan()`?

In Regards
CreativeMD

**Comment by bs2609** [comment]
> However somebody reported this issue to Mojang (https://bugs.mojang.com/browse/MC-125027) and they marked it as works as intended. Maybe the mcp name is confusing and the method should instead be called something like setDoubleLifeSpan()?

https://github.com/ModCoderPack/MCPBot-Issues/issues/607

**Comment by CreativeMD** [comment]
Looks like it has been forgotten? No idea, anyway I will close the issue for now. Thanks for your help!
