### ISSUE TITLE
Dev launch providers do not find test mod classes

### ISSUE THREAD

**Issue by tterrag1098** [MinecraftForge/MinecraftForge#5640]
Currently the dev launch providers (`FMLDevClientLaunchProvider` / `FMLDevServerLaunchProvider`) only look up the jar path for `net/minecraftforge/versions/forge/ForgeVersion.class`, which will not find the path for test mod classes. 

https://github.com/MinecraftForge/MinecraftForge/blob/3003e3307425ade9dc4dbebe2069b2534c7e5157/src/userdev/java/net/minecraftforge/userdev/FMLDevClientLaunchProvider.java#L96

In eclipse, the test sourceset compiles to /bin/test rather than /bin/main. I have no doubt IntelliJ behaves similarly. To make the test mods load in dev, this new exploded directory location must be added to the target list.

I have a minimum working example here: https://github.com/tterrag1098/MinecraftForge/commit/9a3f26b43b5c756a777d8ca5ff41fc9a6481168d

The method to get and add the test mod classes to the exploded targets is not perfect, but it shows what is needed to get this working.

**Comment by cpw** [comment]
Added new launchers that add the test classes.
