### ISSUE TITLE
DataFixers are no longer possible to implement

### ISSUE THREAD

**Issue by Gamebuster19901** [MinecraftForge/MinecraftForge#5650]
It is no longer possible to implement DataFixers in 1.13. The api to add them was removed in https://github.com/MinecraftForge/MinecraftForge/pull/5151

(Specifically, https://github.com/MinecraftForge/MinecraftForge/commit/c4cf950863256ed048a46e098401a969dfe4cb2e#diff-85ea4b7dcfe222b98097a6572be5b822)

**Comment by tterrag1098** [comment]
The vanilla system was completely ripped out and replaced with the datafixerupper library. Not sure what you expected, the code had to go. Non-issue.

**Comment by Gamebuster19901** [comment]
Yes, I'm trying to add my own DataFix. The issue is not that the code was removed, the issue is that it (appears) to be impossible to add a datafix at all, when it previously was possible (I.E. feature regression). 

Unless I'm missing something, as far as I can tell, it's even impossible to add your own DataFix instance to the vanilla DataFixerUpper, even with reflection. 

The DataFixerUpper created in DataFixesManager is coded in such a way where it is impossible to add additional DataFixes to it.

See

com.mojang.datafixers#DataFixerUpper()
net.minecraft.util.datafix.DataFixesManager#DATA_FIXER
net.minecraft.util.datafix.DataFixesManager#createFixer(), net.minecraft.util.datafix.DataFixesManager#addFixers().

Additionally, minecraft will only use the DataFixerUpper in Minecraft#dataFixer and MinecraftServer#dataFixer, so we can't just create more DataFixerUppers in order to use a DataFix. (though I suppose one could wrap those instances with their own DataFixerUpper, but that seems hacky).

**Comment by williewillus** [comment]
yes, no one has figured out how to extend the new vanilla system to mods yet. If you need it, you can help figure it out and reintroduce ways for mods to use it.

**Comment by Gamebuster19901** [comment]
I'll see what I can do.
