### ISSUE TITLE
[1.12.2] Chests are infinitely tileable

### ISSUE THREAD

**Issue by SirDavidLudwig** [MinecraftForge/MinecraftForge#5651]
## Description
In the latest 1.12.2 build of Forge (`1.12.2-14.23.5.2823`), chests can be infinitely placed side by side, making them infinitely tileable. I inserted some example screenshots below to demonstrate the issue.

## Cause of Issue
As @bs2609 pointed out, the issue seems to come from [#5057](https://github.com/MinecraftForge/MinecraftForge/pull/5057)

## Screenshots
![2019-03-26_18 10 27](https://user-images.githubusercontent.com/13006946/55039540-7d0a0780-4ff2-11e9-832d-f3cbd6bec279.png)
![2019-03-26_18 10 24](https://user-images.githubusercontent.com/13006946/55039542-7da29e00-4ff2-11e9-9ada-21a966df8bbd.png)

**Comment by bs2609** [comment]
Probably caused by https://github.com/MinecraftForge/MinecraftForge/pull/5057#issuecomment-473572527, actually.

**Edit:**
Just tested, build 2817 introduces the issue, so #5057 is the culprit here.

**Comment by SirDavidLudwig** [comment]
Ah yes that seems better. Thanks!
