### ISSUE TITLE
[1.13.2] Immediate NPE on startup using java 11

### ISSUE THREAD

**Issue by ConnorJC3** [MinecraftForge/MinecraftForge#5652]
When using java >= 11 (tested with both openjdk and oracle java) the forge client immediately crashes with a NPE. This does not occur with java <= 10. I have confirmed that pure vanilla works with java 11 for me, while the addition of only forge does not.

Details:
Forge version:  1.13.2 - 25.0.100 
OS: Linux (kernel 5.0.4-arch1-1-ARCH)
`java -version` for non-working java 11:
```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+4)
OpenJDK 64-Bit Server VM (build 11.0.3+4, mixed mode)
```
`latest.log`: https://pastebin.com/FxYn160G
(Note: sometimes the last two lines are not in the latest.log, sometimes only the first of the two is, sometimes neither are in the log)
This is using new Mojang launcher, forge was installed using the installer downloaded from https://files.minecraftforge.net

**Comment by ConnorJC3** [comment]
~Update: linux seems to be a factor. Forge 1.13.2 works on windows with oracle JRE 11.0.2, but I cannot get it to work using any of 11.0.1/2/3 on linux.~

Edit: got tricked by the bundled java with the minecraft launcher on windows, this crash is reproducible on both linux and windows

**Comment by cpw** [comment]
Java 11 is not yet supported for running Forge. Probably in 1.14...
