### ISSUE TITLE
Don't show proper mods with russian lang

### ISSUE THREAD

**Issue by robertmakrytski** [MinecraftForge/MinecraftForge#5653]
1)set russian lang in minecraft.
2)If you change  the folder from .minecaft to test and run 1.13.3(1.13.2-25.0.100) it will show error.
` [mException in thread "Thread-7" java.lang.NullPointerException
> 	at org.lwjgl.system.Checks.check(Checks.java:99)
> 	at org.lwjgl.openal.ALC10.alcDestroyContext(ALC10.java:229)
> 	at net.minecraft.client.audio.LibraryLWJGL3.cleanup(SourceFile:155)
> 	at paulscode.sound.SoundSystem.CommandNewLibrary(SoundSystem.java:1521)
> 	at paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2572)
> 	at paulscode.sound.CommandThread.run(CommandThread.java:121)
> [32m[16:42:59.914] [Client thread/INFO] [renderer.texture.TextureMap/]: Max texture size: 16384
> [m[32m[16:43:00.197] [Client thread/INFO] [renderer.texture.TextureMap/]: Created: 512x512 textures-atlas
> [m[32m[16:43:01.367] [Client thread/INFO] [NarratorLinux/]: Narrator library successfully loaded
> [m[1;31m[16:43:01.647] [Client thread/ERROR] [ForgeI18n/]: Illegal format found {0,choice,0#Без модов|1#1 мод|5>{0} мода|4<{0} модов} загружено
> [m java.lang.IllegalArgumentException: Choice Pattern incorrect: 0#Без модов|1#1 мод|5>{0} мода|4<{0} модов
> 	at java.text.MessageFormat.makeFormat(MessageFormat.java:1519) ~[?:1.8.0_192]
> 	at java.text.MessageFormat.applyPattern(MessageFormat.java:479) ~[?:1.8.0_192]
> 	at org.apache.commons.lang3.text.ExtendedMessageFormat.applyPattern(ExtendedMessageFormat.java:191) ~[commons-lang3-3.5.jar:3.5]
> 	at org.apache.commons.lang3.text.ExtendedMessageFormat.<init>(ExtendedMessageFormat.java:125) ~[commons-lang3-3.5.jar:3.5]
> 	at org.apache.commons.lang3.text.ExtendedMessageFormat.<init>(ExtendedMessageFormat.java:110) ~[commons-lang3-3.5.jar:3.5]
> 	at net.minecraftforge.fml.ForgeI18n.parseFormat(ForgeI18n.java:100) ~[?:?]
> 	at net.minecraftforge.fml.ForgeI18n.parseMessage(ForgeI18n.java:92) ~[?:?]
> 	at net.minecraftforge.fml.BrandingControl.computeBranding(BrandingControl.java:45) ~[?:?]
> 	at net.minecraftforge.fml.BrandingControl.getBrandings(BrandingControl.java:53) ~[?:?]
> 	at net.minecraftforge.fml.BrandingControl.forEachLine(BrandingControl.java:62) ~[?:?]
> 	at net.minecraft.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.java:294) ~[?:?]
> 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:348) ~[?:?]
> 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:654) ~[?:?]
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:793) ~[?:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:358) ~[?:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:144) ~[1.13.2-forge-25.0.100.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_192]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_192]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_192]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_192]
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.13.2-25.0.100.jar:25.0]
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19) [modlauncher-0.12.1.jar:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32) [modlauncher-0.12.1.jar:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-0.12.1.jar:?]
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:56) [modlauncher-0.12.1.jar:?]
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:42) [modlauncher-0.12.1.jar:?]
> Caused by: java.lang.IllegalArgumentException
> 	at java.text.ChoiceFormat.applyPattern(ChoiceFormat.java:214) ~[?:1.8.0_192]
> 	at java.text.ChoiceFormat.<init>(ChoiceFormat.java:315) ~[?:1.8.0_192]
> 	at java.text.MessageFormat.makeFormat(MessageFormat.java:1516) ~[?:1.8.0_192]
> 	... 25 more`
it doesn't work proper for win,mac,linux.

**Comment by tterrag1098** [comment]
Someone again translated the message keys...

**Comment by tterrag1098** [comment]
Fixed in crowdin, ref https://crowdin.com/translate/minecraft-forge/15/en-ru#341
