### ISSUE TITLE
[1.13.2] Mods in mods [minecraftroot]/mods/1.13.2 do not load

### ISSUE THREAD

**Issue by drewc5131** [MinecraftForge/MinecraftForge#5654]
Mods are required to be in the root of the mods folder, and will not load if in the 1.13.2 subfolder, whereas previous versions would do so. I personally organize all my mods since I occasionally switch between versions, and prefer not to manually swap the mods every time

**Comment by GirafiStudios** [comment]
That is an intended change, as a result of the FML rewrite.
Already adressed in https://github.com/MinecraftForge/MinecraftForge/pull/5637

**Comment by drewc5131** [comment]
That is a terrible and really stupid change. Sounds like laziness to me. I shouldn't have to redo my settings and worlds every time a new version comes out.
