### ISSUE TITLE
[1.13.2 ]Invalid mod files

### ISSUE THREAD

**Issue by Eragon-Argetlam** [MinecraftForge/MinecraftForge#5656]
Trying to load a few simple mods, this happened. Log of the attempted load here:
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/3020884/latest.log)

**Comment by DaemonUmbra** [comment]
This is more a matter for the forums.
But as they are down at this time, you are trying to load Rift mods, Optifine (which I don't think has Forge support yet), and a 1.12.2 mod.
If you want further explanation, please wait for the forums to come back up and make a thread.

**Comment by cpw** [comment]
Closing. This is not a bug in forge.
