### ISSUE TITLE
[1.13.2] Tile entity models

### ISSUE THREAD

**Issue by 128-bit-guy** [MinecraftForge/MinecraftForge#5657]
For example, i want to make a multipart mod. Right now, the only way i can render my multipart tile entity is using TileEntityRenderer. It's not the best way of doing this, because multipart changes rarely in comparsion to how much times it's drawn. I wish i can add my vertices to chunk vertex bufer.

I suggest adding a new block render type - tile entity model. Blocks with this render type will be rendered with TileEntityModel. It will have a method render, wich will take TileEntity, IWorldReader, BlockPos, BufferBuilder and Random as arguments. TileEntityModels will be bound to tile entities, like TileEntityRenderers.

I apologise for bad english.

**Comment by williewillus** [comment]
This is exactly what TileEntityFastRenderer is

**Comment by williewillus** [comment]
additionally you can wait for #5564 to be merged and use a custom baked model instead

**Comment by 128-bit-guy** [comment]
TileEntityRendererFast rebuilds buffer each frame. I want to rebuild buffer only when tile entity changes. I will wait for PR to be merged.

**Comment by tterrag1098** [comment]
It sounds like what you actually want is a normal block model. Why use a TER for something that doesn't animate?
