### ISSUE TITLE
/forge setdimension claims to use same logic as vanilla portal (it does not)

### ISSUE THREAD

**Issue by chainingsolid** [MinecraftForge/MinecraftForge#5659]
net.minecraftforge.server.command.CommandSetDimension.checkEntity() has a comment saying "use vanilla portal logic, try to avoid doing anything too silly" yet the logic there differs from net.minecraft.block.BlockPortal.onEntityCollision() when it comes to bosses. Vannilla doesn't allow bosses where as you have to be a boss for /forge setdimension to work. Confirmed by "/forge setdimension @e -1 1 1 1" moving a wither to the nether from the overworld and not the sheep, or player that where also present.

https://github.com/MinecraftForge/MinecraftForge/blob/e0361047f7790b5d66f183c1fb4d5ca0dbce3712/src/main/java/net/minecraftforge/server/command/CommandSetDimension.java#L75-L79

**Comment by bs2609** [comment]
This is because the logic wasn't inverted correctly in the 1.13 port:

https://github.com/MinecraftForge/MinecraftForge/blob/e0361047f7790b5d66f183c1fb4d5ca0dbce3712/src/main/java/net/minecraftforge/server/command/CommandSetDimension.java#L75-L79

https://github.com/MinecraftForge/MinecraftForge/blob/e7beed487531d199ca1ddffa7b7cc314024bf8a8/src/main/java/net/minecraftforge/server/command/CommandSetDimension.java#L99-L103

**Comment by tterrag1098** [comment]
The comment should be updated to reference where this "vanilla portal logic" is, as I cannot find it.

**Comment by chainingsolid** [comment]
> 
> 
> The comment should be updated to reference where this "vanilla portal logic" is, as I cannot find it.

The vanilla portal logic I'm referring to is in "net.minecraft.block.BlockPortal.onEntityCollision()", which I directly reference in the initial comment, maybe I should have put in the "()" at the end of it. (I'll edit the comment to have that, to differentiate it from a field).
Heres the method body containing said logic, if you still cain't find it.
```
if (!entityIn.isPassenger() && !entityIn.isBeingRidden() && entityIn.isNonBoss()) {
         entityIn.setPortal(pos);
 }
```

I'm running Forge 25.0.102 MCP 20190213.203750, In case a differing of version in either of these 2 would cause any variable/class/package names to be different between what I'm looking at and your looking at.

**Comment by Alpvax** [comment]
> The vanilla portal logic I'm referring to is in "net.minecraft.block.BlockPortal.onEntityCollision()", which I directly reference in the initial comment ...

I believe tterag meant in the in-code comment. Put a link to the method in the comment, so we can easily find it later if something changes.

**Comment by tterrag1098** [comment]
I did, but I also missed that it was mentioned above. The logic was indeed inverted incorrectly, however I think it would be better to keep it consistent with the vanilla code, and just invert the predicate.

**Comment by bs2609** [comment]
For reference, this is also the logic used in `BlockEndPortal.onEntityCollision()` and can be found by looking at the usages of the relevant method `isNonBoss` (despite the name: https://github.com/ModCoderPack/MCPBot-Issues/issues/649).
