### ISSUE TITLE
Forge <1.13 will try to load 1.13+ mods, and crash horrible

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/MinecraftForge#5661]
The problem is that forge 1.12 and all version below will try to load 1.13+ mods, as there is no way to specify a minimum version that forge < 1.13 will understand.
So instead of a nice mod error message, players will get a hard NoClassDefFoundError or something like that.
See http://www.minecraftforge.net/forum/topic/69766-error-javalangnoclassdeffounderror-netminecraftforgeeventbusapiieventbus/

**Comment by Cadiboo** [comment]
Solution: Update to 1.13:tm:

**Comment by LexManos** [comment]
The real "silution" is to inject a dummy mc version into the annotation at build time. like we are doing for 1.12< so if someone wants to port my fg2 code for this to fg3 that'd do it.

**Comment by cpw** [comment]
This is not a valid analysis. The 1.13 @Mod annotation does not contain a "modid" entry - this will result in the mod not even being considered a valid candidate for 1.12. _Unless_ some fuckery with 1.12 coremods was resulting in the mod somehow still being considered valid. There is a problem with the specific mod - it seems that 1.12 and 1.13 have somehow gotten merged together in his source, but that's not what caused this. I don't think we can add that annotation easily, and I don't think it would have made a difference in this case either (lack of modid is considered as bad as mismatched MC version).

**Comment by cpw** [comment]
I have made a small change to 1.12 to try and better detect 1.13 mods. There's a lot of paths that will fail, and lex's code won't work, because it's actually very late in the mod loading cycle, relatively speaking.
1f12642a05e4f97ff1d83abb1a7c787422490900
