### ISSUE TITLE
[1.13] Self-AT fields crashing at runtime

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#5662]
```
java.lang.IllegalAccessError: tried to access field 
net.minecraft.client.gui.GuiIngame.remainingHighlightTicks from class 
vazkii.botania.client.core.handler.HUDHandler
```

the field in question is AT-ed and compiles properly, but fails at runtime.

**Comment by cpw** [comment]
Which runtime?

**Comment by williewillus** [comment]
userdev environment

**Comment by LexManos** [comment]
ated by whom? and which runtime? what command are you using? is this a dep.imported to another project? more Info is needed

**Comment by williewillus** [comment]
AT-ed only by botania itself (no deps involved), the AT is [here](https://github.com/Vazkii/Botania/blob/1.13/src/main/resources/META-INF/accesstransformer.cfg#L40), declared by buildscript [here](https://github.com/Vazkii/Botania/blob/1.13/build.gradle#L32)

crash is in userdev whenever I reach a codepath that actually needs to touch that field

**Comment by LexManos** [comment]
interesting, and what is the full class path you're running? or should be the same as compile. how are you executing the game?

**Comment by williewillus** [comment]
I'm using the run configs generated by genIntellijRuns, here's the crashlog if it helps: https://hastebin.com/uhodedajuk.sql

**Comment by LexManos** [comment]
Interesting, there should be more specific debugging there. However its using forge-1.13.2-25.0.107_mapped_snapshot_20190313-1.13.2-recomp.jar which is NOT an ated jar, which is your issue. So .. be sure to regen the intellij run configs after adding the ats.

**Comment by williewillus** [comment]
hmm, this AT has been in there for a long time now, and I just recently updated forge to 107 so the environment should be clean (deleted workspace, ran genIntellijRuns twice, reimported build.gradle)

in the Intellij module config it also shows the AT jar is a dependency of my main mod module, so not sure how it's picking up the other jar

**Comment by LexManos** [comment]
post your full run/workspace config. so we can get the full classpath. Also gunna poke @cpw as my last changes should be working.. not sure what's changed in the last week.

**Comment by cpw** [comment]
Haven't touched that stuff lex. I'll take a look on Friday

**Comment by cpw** [comment]
Have you tried with the newest forge? It might fix this.

**Comment by williewillus** [comment]
seems to have worked, thanks!
