### ISSUE TITLE
[1.13] Vanilla shaped/shapeless recipes do not support NBT on result

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#5663]
In 1.12, specifying `nbt` on the `result` part of a recipe json was possible thanks to forge patches, but looks like the hook was dropped accidentally. Vanilla recipes call into `ShapedRecipe.deserializeItem` to get the result but it doesn't support NBT. Probably needs redirect to `CraftingHelper.getItemStack`

**Comment by tterrag1098** [comment]
I think we need a deeper reconsideration of CraftingHelper. It doesn't seem right to rewrite the vanilla deserializing logic and just hope for the best. We should probably just be decorating their logic, not replacing it wholesale.
