### ISSUE TITLE
ForgeHooks.canToolHarvestBlock item.canHarvestBlock not working right

### ISSUE THREAD

**Issue by Raycoms** [MinecraftForge/MinecraftForge#5665]
I'm using minecraft 'net.minecraftforge:forge:1.13.2-25.0.107'

And I found out that the ForgeHooks.canToolHarvestBlock and item.canHarvestBlock calls return wrong results for a number of blocks.

(In this I am able to destroy bedrock, able to destroy stone with shovels)...etc. 

Combined with that I noticed that the durability of my tools extending the vanilla tool classes also does not match the durability of the vanilla tool classes weirdly.

**Comment by tterrag1098** [comment]
Need a test case for this, cannot reproduce with vanilla tools.

**Comment by Raycoms** [comment]
https://github.com/ldtteam/vanilla-tools/blob/1.13.2/src/main/java/com/ldtteam/supertools/SuperTools.java#L128

This is the class where I do the checks.
I added some small workarounds for shovels to make it work more or less. But it's still not working very well.

I debugged both the ForgeHooks.canToolHarvestBlock(world, pos, item) and the item.canHarvestBlock(state) and they don't seem to be returning the right values for the right blocks.

The hammer:
https://github.com/ldtteam/vanilla-tools/blob/1.13.2/src/main/java/com/ldtteam/supertools/items/HammerSuperTools.java

The spade:
https://github.com/ldtteam/vanilla-tools/blob/1.13.2/src/main/java/com/ldtteam/supertools/items/ShovelSuperTools.java

Where I register them:

https://github.com/ldtteam/vanilla-tools/blob/1.13.2/src/main/java/com/ldtteam/supertools/items/ModItems.java

**Comment by tterrag1098** [comment]
By a test case I meant something I can easily copy paste into my environment to reproduce the issue. Not your entire mod.

**Comment by Raycoms** [comment]
Pasting the one event handler and the two tools over should be relatively easy, no?
