### ISSUE TITLE
[1.14.x] Add way to say "Please load and bake this model for me"

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#5667]
Models are automatically loaded and baked if they're part of a block or item or item json override, but otherwise MC does not touch them.

Before, this could be hacked around by passing extra unrelated MRL's along with an item to `ModelBakery.registerItemVariants`, but that's gone in 1.13 now.

For mods that load and use baked models that aren't tied to any specific block or item, it's useful for them to be able to say "please load and bake this model", similar to how you say "please load and stitch this texture for me" in `TextureStitchEvent.Pre`.

Mojang has a hardcoded line in `ModelBakery` line 311 for the trident_in_hand model, I just want a similar hook point right there so modders can add more models to load.

**Comment by williewillus** [comment]
I can PR this, would an acceptable solution be to split ModelBakeEvent into pre/post variants? post variant fired where it is right now, pre variant fired at the line I mentioned above to collect extra paths to load.

**Comment by bs2609** [comment]
We already have `ModelRegistryEvent`, is an extra event really needed?
This seems like the sort of thing we have `ModelLoader` for.

**Comment by williewillus** [comment]
Using that event is fine too

**Comment by KnightMiner** [comment]
I agree that makes sense too, ModelRegistryEvent is currently just for timing but makes sense to give some functionality rather than implementing another event.
