### ISSUE TITLE
[1.13.2] The Tooltip For Not Having The Right Mods To Join A Server Isn't Localized

### ISSUE THREAD

**Issue by TheLimePixel** [MinecraftForge/MinecraftForge#5676]
![image](https://user-images.githubusercontent.com/25333164/55686800-fea05480-5965-11e9-8076-2d137bfc8994.png)

**Comment by JoJoDeveloping** [comment]
Weird.. I mean, it's there in the lang file: https://github.com/MinecraftForge/MinecraftForge/blob/1.13.x/src/main/resources/assets/forge/lang/en_us.json#L20

What does the log say - especially about why the server was found to be incompatible?

**Comment by ichttt** [comment]
@JoJoDeveloping The en_us in the repo may not be the same as in the final jar, as translations are pulled from crowdin. It seems like this string has not been synced to crowdin, so someone needs to add it to the forge crowdin project and do a new build (or wait until a new commit is pushed)

**Comment by cpw** [comment]
We need to push the language file to crowdin. Until then they'll be missing in the downloaded mod.

**Comment by tterrag1098** [comment]
crowdin updated
