### ISSUE TITLE
Add logical and/or/not conditions for the loot tables.

### ISSUE THREAD

**Issue by zcaliptium** [MinecraftForge/MinecraftForge#5677]
There are already such conditions for recipes (``forge:not``, ``forge:and``, ``forge:or``) defined at CraftingHelper class. They allow enable or disable recipes in very flexible way. I really like it.  

So... Why not add LootConditions with the same functionality? That will reduce pain (i.e. no need implement it ourself or make ``inverse`` flag for every LootCondition added by our mods) and make vanilla loot table system feeling more complete.

**Comment by williewillus** [comment]
this is already coming in 1.14

 https://minecraft.gamepedia.com/Loot_table#Conditions (`alternative` and `inverted` serve `or` and `not`). `and` is already possible by just specifying multiple conditions in the array.

**Comment by zcaliptium** [comment]
Hmmmm... Didn't knew about such functionality in 1.14. I should check changelogs with more attention. But we should take in mind that a lot of time will pass until we get 1.14 and stable Forge for it. )

@williewillus Also... ``and`` is possible currently only because all conditions sitting in root and they processed as AND.

But... Even with 1.14 functionality we anyway need ``and`` implemented by our own. Without it such logic for example impossible:
``Condition1 OR (Condition2 AND Condition3)``

**Comment by KnightMiner** [comment]
Well, not technically impossible with a bit of boolean alegbra: `NOT (NOT A OR NOT B)` is the same as `A AND B`. Of course a dedicated AND would be cleaner, but its a pretty rare use case so it might be easier to just have the mod using it implement it instead

----

On the topic of 1.14 adding these, would it make sense to just have Forge add `alternative` and `inverted` itself and just remove them in the 1.14 port, or is 1.13 expected to be that short lived?

**Comment by williewillus** [comment]
1.13 is really expected to be that short lived, it will never receive a forge RB. we are expecting 1.14 within the next couple months and forge should not take long to move to it.

I'm pretty sure your example is also possible using the new 1.14 entry types as well (`group` and `children`). need to investigate the vanilla loot tables more to see what they actually do.
