### ISSUE TITLE
[1.13.2] Lang files not 'loaded/mapped' before FMLCommonSetupEvent fired

### ISSUE THREAD

**Issue by Wabbit0101** [MinecraftForge/MinecraftForge#5679]
Per the javadocs FMLCommonSetupEvent is fired after the registry events so it's pretty late in the startup process. However, calls to get translation strings don't work at this point (and I'm assuming neither within item registration). My use case is I'm looking for a couple translation strings within an event handler's construction in a mod that has no items/blocks/etc (the use of the strings is not confined to GUIs/etc so I cannot use the clientside-only I18n).

Simple test: I put the following 2 lines in a FMLCommonSetupEvent callback and in a InterModProcessEvent callback (note I'm using all the non-client-only ways to get a translated key I found from scanning sample code). The 'item.pef_box.name' is a test string in my mod's 'en_us.json' and the other is a key for a builtin forge key as a comparison.

FMLCommonSetupEvent code:
```
TextComponentTranslation eh = new TextComponentTranslation("item.pef_box.name");
_modLog.info(" DOINK(early): "+eh.getFormattedText()+"  |||  "+LanguageMap.getInstance().translateKey("fml.menu.mods.normal")+"  |||  "+ForgeI18n.parseFormat("fml.menu.mods.normal"));
```

FMLCommonSetupEvent output (all 3 methods returned the input key):
> [modloading-worker-1/INFO] [PEf/]:  DOINK(early): item.pef_box.name  |||  fml.menu.mods.normal  |||  fml.menu.mods.normal

InterModProcessEvent code:
```
TextComponentTranslation eh = new TextComponentTranslation("item.pef_box.name");
_modLog.info(" DOINK(later): "+eh.getFormattedText()+"  |||  "+LanguageMap.getInstance().translateKey("fml.menu.mods.normal")+"  |||  "+ForgeI18n.parseFormat("fml.menu.mods.normal"));
```

InterModProcessEvent output (all 3 found and translated the to the proper strings):

> [modloading-worker-1/INFO] [PEf/]:  DOINK(later): Personal Effects  |||  Off  |||  Off

**If this is working as it should**, when IS the best startup context to retrieve translated strings?

**Comment by liach** [comment]
i don't think the readiness of registry indicate the readiness of a resource pack. listen to resource reload, i guess

**Comment by williewillus** [comment]
yeah, at the point of the registry events a ton of MC's internal subsystems don't even exist yet (including resource manager), so try a later event.

**Comment by Wabbit0101** [comment]
Ok, thanks. I just wanted to confirm that things either were or were not working as expected so I could re-code accordingly.
