### ISSUE TITLE
[1.13] EventBus does not shutdown when fatal loading errors occur

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/MinecraftForge#5682]
In 1.12, we shutdown the main forge event bus using https://github.com/MinecraftForge/MinecraftForge/blob/1f12642a05e4f97ff1d83abb1a7c787422490900/src/main/java/net/minecraftforge/fml/common/eventhandler/EventBus.java#L194, but in EventBus libary of 1.13, this function or anything else that shuts down the bus is missing. This is bad, because some mods (including the broken one) might already have registered event handlers, and many events like tick, draw screen, ModelBakeEvent and so on are still fired, which can cause further crashes if some init code is not executed.

**Comment by cpw** [comment]
Closed with 5cd82f16f21108ad6754e9e4298bd81909bb8948
