### ISSUE TITLE
Buttons in the error screen are incorrectly rendered if they are extremely long

### ISSUE THREAD

**Issue by Gamebuster19901** [MinecraftForge/MinecraftForge#5687]
![image](https://user-images.githubusercontent.com/7155747/55992632-04a27800-5c7b-11e9-8426-41523738c0e0.png)

**Comment by mezz** [comment]
I think the solution here should be to limit the max width of the buttons, that size is just too big.

A more general solution is to implement a 9-slice texture that can be resized infinitely with repeating inner sections. I have implemented that for JEI and could move it into Forge if there is some other need for it.

**Comment by Gamebuster19901** [comment]
For reference, this is what it looks like in the PR.

![image](https://user-images.githubusercontent.com/7155747/61015317-1dddc200-a359-11e9-9eb2-04f449835f77.png)

Also, perhaps consider renaming GuiButtonExt to ExtendableButton or similar because of the new naming convention.
