### ISSUE TITLE
[1.13.2] Options in a generated config.toml have the wrong order

### ISSUE THREAD

**Issue by Ruuubi** [MinecraftForge/MinecraftForge#5688]
Actually not sure if this is a bug, intended or if I'm doing something wrong here:
While using the Forge config system to create a toml-file, the output has a different order than in the source code. This results in a messed up config if you chose to put similar options together, because they can appear in a different order.

Example input and output: https://i.imgur.com/obD85Nx.png

**Edit:**
Tested with Forge-25.0.110

**Comment by MajorTuvok** [comment]
Sorry for commenting, but this accidentally got the 1.12 label even though it's only relevant for 1.13...

**Comment by tterrag1098** [comment]
PR made upstream.

**Comment by TheElectronWill** [comment]
Fixed in [NightConfig v3.5.3](https://github.com/TheElectronWill/Night-Config/releases/tag/v3.5.3)
