### ISSUE TITLE
Build 134 is breaking old existing code about AIPathNodeType

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#5691]
Build 134 on 1.13.2
```
Error executing task java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.block.Block.getAiPathNodeType(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/IBlockReader;Lnet/minecraft/util/math/BlockPos;)Lnet/minecraft/pathfinding/PathNodeType; at java.util.concurrent.FutureTask.report(FutureTask.java:122) at java.util.concurrent.FutureTask.get(FutureTask.java:192) at net.minecraft.util.Util.func_181617_a(SourceFile:200) at 
```
https://github.com/MinecraftForge/MinecraftForge/commit/2baa05ace9112637caea812b5cfb42a7d6425ee1#diff-9a5c62d37028fa638279e3ec8a1618a1R923
as no other method was existing before this deprecation
Edit : Ideally, it would be fine to keep the old method as deprecated for a time, or at least a version bump, as a mod using this method should have a version before this build and after this build...

**Comment by tterrag1098** [comment]
Not an issue, this is a forge beta and breaking changes are to be expected. Now is the time to remove deprecations not add more.

**Comment by ghost** [comment]
Thanks for the precision, it's a beta of 6 months any way.
