### ISSUE TITLE
[1.12.x][Bug] Special spawn event not firing consistently

### ISSUE THREAD

**Issue by rootmenu** [MinecraftForge/MinecraftForge#5694]
Hey Folks!

The special spawn event is not fired in many cases. There allready was a PR #5389 with a similar title, which didn't catch those cases. (I can't currently make a PR myself as I didn't set up the forge project yet) 

The bug is located in two locations: 

`net.minecraft.tileentity.MobSpawnerBaseLogic.java` in function updateSpawner() where it says
```java
    if (entityliving == null || net.minecraftforge.event.ForgeEventFactory.canEntitySpawnSpawner(/*params omitted*/))
        if (this.spawnData.getNbt().getSize() == 1 && this.spawnData.getNbt.hasKey("id", 8) && entity instanceof EntityLiving)
        {
            if (!net.minecraftforge.event.ForgeEventFactory(doSpecialSpawn(/*params omitted*/));
            ((EntityLiving)entity).onInitialSpawn(/*params omitted*/);
        }
```
The condition `this.spawnData.getNbt().getSize() == 1` is too restrictive. I assume this condition was placed to assure the event only firing if the spawnData has a field `id` **but**
* `this.spawnData.getNbt.hasKey("id",8)` allready implies a Nbt size of at least 1
* `getSize() == 1` prohibits the event from firing if there is **more** nbt data

To demonstrate here is a use case: [ArmoreableMobs](https://minecraft.curseforge.com/projects/armoreablemobs) (I am not the mod author) The mod listens for SpecialSpawn events to equip spawned mobs with gear chosen from a script using CraftTweakers ZenScript. Additionally you can set special nbt checks on the mobs, e.g. health > 60. Unfortunately the mod only works on 'standard' entities spawned with no additional nbt data, so you can't currently spawn e.g. a zombie with high health and have ArmoreableMobs gear him specifically as a miniboss or special foe. 

The problem is the SpecialSpawn event not firing if `getNbt().getSize()` is **greater than 1** and as there allready is a condition checking for an id the condition `this.spawnData.getNbt().getSize() == 1` could therefore be **omitted entirely**

The second location is 
`net.minecraft.command.server.CommandSummon.java` in function execute(_..._) where it says

```java
nbttagcompoind.setString("id", s);
Entity entity = AnvilChunkLoader.readWorldEntityPos(/*params omitted*/);

if (entity == null)
{
    throw new CommandException(/*params omitted*/);
}
else
{
    entity.setLocationAndAngles(/*params omitted*/);

    if (!flag && entity instanceof EntityLiving)
    {
        ((EntityLiving)entity).onInitialSpawn(/*params omitted*/)
    }
    notifyCommandListener(/*params omitted*/);
}
```

The /summon command **does not** fire a SpecialSpawn event at all. For consistency this should either incorporate a conditional event trigger like the MobSpawner 

```java
    if (!flag && entity instanceof EntityLiving)
    {
        if (!net.minecraftforge.event.ForgeEventFactory(doSpecialSpawn(/*params omitted*/));
            ((EntityLiving)entity).onInitialSpawn(/*params omitted*/)
    }
```

**OR** the SpecialSpawn event should be triggered from `EntityLiving.onInitialSpawn` function instead. This, of course, would entail the removal of all other event triggers of the SpecialSpawn event to avoid duplicates. According to the description of the `onInitialSpawn` function this would be the more robust solution, provided the function is correctly called by the different spawning methods. 

```java
/**
* Called only once on an entity when first time spawned, via egg, mob spawner, 
* natural spawning etc, but not called when entity is reloaded from nbt. Mainly 
* used for initializing attributes and inventory
*/
@Nullable
public IEntityLivingData onInitialSpawn(DifficultyInstance difficulty, @Nullable IEntityLivingData livingData) {/*...*/}
```

**Comment by LexManos** [comment]
I dont think the spawner not triggering is a bug, as adding any extra NBT data is indication that you are spawning an exact copy and should not be modified by outside sources. There isn't anything we can do to flag it as 'Its ok to touch these parts of the entity but not the parts im overriding'

As for the spawn command, same thing.
SpecialSpawn is for the random in-world spawned entities not for things you craft the nbt itself.
