### ISSUE TITLE
PlayerLoggedOutEvent gets fired without PlayerLoggedInEvent if client doesn't have matching mod list

### ISSUE THREAD

**Issue by LatvianModder** [MinecraftForge/MinecraftForge#5696]
If client is not whitelisted or is banned from server, when it tries to connect, vanilla handles it and neither LoggedIn nor LoggedOut events get fired. However, if client is ok to connect by vanilla standards, but Forge denies connection because of missing mods on client side, player gets kicked out of game without properly logging in first.

There are only two real solutions, log in player and then immidiently kick after that or handle disconnecting differently without firing PlayerLoggedOutEvent at all.

This explains why you only see "Player left the game." message in chat without ever seeing "Player joined the game" message before that. This would also explain quite few crashes for me personally, especially why sometimes data goes missing next time they come back online with proper mod list. 

My best solution so far is keep a `HashSet<UUID> LOGGED_IN_PLAYERS`, add UUID on log in and only do something on log out event `if(LOGGED_IN_PLAYERS.remove(event.player.getUniqueID()))`.

**Comment by Gamebuster19901** [comment]
I'd recommend disconnecting without firing LoggedOutEvent. (you can't log out if you're not logged in).

**Comment by Alpvax** [comment]
Maybe fire a new LoginDenied event instead? Or add a `wasLoggedIn` boolean to the LoggedOutEvent (for a non-breaking change)
