### ISSUE TITLE
Feature Reqest - Add BungeeCord/Waterfall/Tavertine IP Forwarding Support

### ISSUE THREAD

**Issue by Eizock** [MinecraftForge/MinecraftForge#5701]
We have Multiple Forge servers, we would like to have behind a Tavertine Proxy.
Please Implement the IP Forwarding/UUID Forwarding used in BungeeCord/Waterfall/Tavertine.
There is SpongeForge which implements this, but it seems to break Mods. (Atleast on FTB Interactions)
I tried Implementing it into a Coremod, but Ultimately failed (Lack of Knowlege dealing with Java Bytecode and Minecraft/Forge inner Workings).
References:
- Vanilla Implementation: https://github.com/ME1312/VanillaCord/
- Sponge Forge: https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/core/network/packet/MixinC00Handshake.java

I saw this issue: https://github.com/MinecraftForge/MinecraftForge/issues/2784
and I don't know how much has changed since then, but maybe someone could propose a less hacky way of going about this.

**Comment by LexManos** [comment]
There should be no change on our end that needs to be done. We use the same field to identify ourselves to the servers as Forge. And kick off the handshake. But we do it in such a way that is expandable by the BungeeCord people to add their own data in. So it's on them to add that data when forwarding connections.
