### ISSUE TITLE
[1.13] Problems with layered item model

### ISSUE THREAD

**Issue by FoxSamu** [MinecraftForge/MinecraftForge#5703]
I found a weird bug in Forge (or vanilla, I don't know), regarding layered item models. I have this texture for a so called 'Wireplant':
![wireplant](https://user-images.githubusercontent.com/11669132/56343758-e88f6100-61bb-11e9-94f7-44fd3d5e9914.png)
My item model for this 'Wireplant' is a layered item model. In 1.12.2, the item just looks like any other item with a layered model. But when I load the same layered item model in 1.13.2, it looks like this:
![2019-04-18_09 20 37](https://user-images.githubusercontent.com/11669132/56343884-53409c80-61bc-11e9-8500-cb75dade0aa2.png)
This must probably be a bug in Forge's `ItemLayerModel` that hasn't been solved yet... I'm using the latest version of Forge, though it also happens in all other 1.13.2 versions...

**Comment by FoxSamu** [comment]
![2019-04-19_09 02 30](https://user-images.githubusercontent.com/11669132/56411852-746bc080-6282-11e9-9060-35ac64fd22fa.png)
It seems to happen to vanilla items too

**Comment by tterrag1098** [comment]
Does this still occur on 1.14?

**Comment by RedGalaxySoftware** [comment]
I cannot test that: 1.14.2 glitches completely with forge (forgot to take a screenshot)...

**Comment by FoxSamu** [comment]
No, 1.14 layered item model just works fine:
![2019-06-15_00 11 35](https://user-images.githubusercontent.com/11669132/59541600-5c22c580-8f02-11e9-8ccc-af1fda0bbbc6.png)

**Comment by FoxSamu** [comment]
I just noticed this only happens when forge is installed. In pure vanilla it's fine...

**Comment by FoxSamu** [comment]
It works again in 1.14
