### ISSUE TITLE
Cannot read resource bundles from inside built jars

### ISSUE THREAD

**Issue by theminecoder** [MinecraftForge/MinecraftForge#5705]
When attempting to load resource bundles a `java.util.MissingResourceException` is thrown. This only happens inside built jar, IDE dev environment read things just fine

I have tried to the get resource file directly but that also returns null. My theory is something in the custom classloader isn't checking the right place/jar for the files.

For context the resource files are in the root of the jar (and cannot be moved due to coming from a shaded dependency) as follows 
![image](https://user-images.githubusercontent.com/1396368/56361159-fa0f5200-6229-11e9-8831-aaf54bad268e.png)

**Comment by tterrag1098** [comment]
This should have been fixed a while ago, reconfirm?
