### ISSUE TITLE
The ClassLoader used to load the mod classes is unable to locate classpath resources

### ISSUE THREAD

**Issue by Adrodoc** [MinecraftForge/MinecraftForge#5713]
The ClassLoader used to load the mod classes is unable to locate classpath resources. Calls to `getClass().getResource()` or `getClass().getClassLoader().getResource()` (and other variants) always return `null`.
Using the threads context classloader (`Thread.currentThread().getContextClassLoader()`) works fine.
It looks like the issue arises, because the _normal_ classloader (which is an instance of `cpw.mods.modlauncher.TransformingClassLoader.DelegatedClassLoader`) has no parent classloader for some reason, whereas the context classloader (which is an instance of `cpw.mods.modlauncher.TransformingClassLoader`) has a parent (a `sun.misc.Launcher.AppClassLoader`) which is used to load the resource (in `java.lang.ClassLoader.getResource(String)`).

This has been tested in single player using eclipse and in single player using a built mod jar.

Forge Version: 1.13.2-25.0.191

The following Mod illustrates the issue by loading a resource with the contents `hello` named `greeting.txt` located in `src/main/resources`.

# Output
```
[27Apr2019 16:39:32.955] [Server thread/INFO] [com.example.examplemod.ExampleMod/]: ClassLoader: cpw.mods.modlauncher.TransformingClassLoader@45efd90f
[27Apr2019 16:39:32.955] [Server thread/INFO] [com.example.examplemod.ExampleMod/]: Resource: modjar://examplemod/greeting.txt
[27Apr2019 16:39:32.957] [Server thread/INFO] [com.example.examplemod.ExampleMod/]: Content: hello
[27Apr2019 16:39:32.957] [Server thread/INFO] [com.example.examplemod.ExampleMod/]: ClassLoader: cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader@75c56eb9
[27Apr2019 16:39:32.957] [Server thread/INFO] [com.example.examplemod.ExampleMod/]: Resource: null
```

# Modified ExampleMod:
```java
package com.example.examplemod;

import static java.nio.charset.StandardCharsets.UTF_8;
import java.io.IOException;
import java.net.URL;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import com.google.common.io.Resources;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.gameevent.PlayerEvent.PlayerLoggedInEvent;

@Mod("examplemod")
public class ExampleMod {
  private static final Logger LOGGER = LogManager.getLogger();

  public ExampleMod() {
    MinecraftForge.EVENT_BUS.register(this);
  }

  @SubscribeEvent
  public void onEvent(PlayerLoggedInEvent event) throws IOException {
    EntityPlayer player = event.getPlayer();
    String resource = "greeting.txt";
    printResource(resource, player, Thread.currentThread().getContextClassLoader());
    printResource(resource, player, getClass().getClassLoader());
  }

  private void printResource(String resource, EntityPlayer player, ClassLoader classLoader)
      throws IOException {
    print(player, "ClassLoader: " + classLoader);
    URL url = classLoader.getResource(resource);
    print(player, "Resource: " + url);
    if (url != null) {
      print(player, "Content: " + Resources.toString(url, UTF_8));
    }
  }

  private void print(EntityPlayer player, String message) {
    LOGGER.info(message);
    // This somehow causes java.lang.NoSuchMethodError:
    // net.minecraft.entity.player.EntityPlayer.sendMessage(Lnet/minecraft/util/text/ITextComponent;)V
    // outside the dev environement
    // player.sendMessage(new TextComponentString(message));
  }
}
```

**Comment by Adrodoc** [comment]
Further investigation shows that the issue was introduced here https://github.com/cpw/modlauncher/commit/2ac5413d0fa889aae60b4ed6af32c619fca79e68#diff-d25f532beaaa7c9d9088e09eadc7b728R125.
It seems to me that
```java
DelegatedClassLoader(TransformingClassLoader cl) {
  super(cl.specialJars, null);
  this.tcl = cl;
}
```
should maybe be:
```java
DelegatedClassLoader(TransformingClassLoader parent) {
  super(parent.specialJars, parent);
  this.tcl = parent;
}
```
But I am not going to pretend like I have read the whole code to understand exactly what is going on here.
The correct way to solve this might also be:
```java
DelegatedClassLoader(TransformingClassLoader cl) {
  super(cl.specialJars);
  this.tcl = cl;
}
```
If for some reason it is not wanted to have the `TransformingClassLoader` as the parent.
Just like in the `TransformingClassLoader` this would cause the system classloader (`java.lang.ClassLoader.getSystemClassLoader()`) to be used as the parent.

**Comment by HyCraftHD** [comment]
To use resources in your mod you can use the `ModFile.findResource` method.

**Comment by Adrodoc** [comment]
@HyCraftHD The method `ModFile.findResource` can only find resources in the mod jar file whereas `getClass().getResource()` finds resources on the classpath. This is neccessary for loading things distributed across multiple jar files, for instance by using java's [ServiceLoader mechanism](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html).
Luckily the ServiceLoader uses the thread context classloader by default, but it is supposed to work with the normal classloader too.

**Comment by cpw** [comment]
Should be fixed with recent forge builds, using ModLauncher 1.1+
