### ISSUE TITLE
Containers do not validate with IItemHandler::insertItem() when dragging items or shift clicking.

### ISSUE THREAD

**Issue by SHsuperCM** [MinecraftForge/MinecraftForge#5717]
It seems as if IItemHandler::insertItem() is only called when clicking once normally on a slot and doesn't get checked when working through item dragging or using merge/transferStackInSlot from Container.

**Comment by tterrag1098** [comment]
On what version? Do you have a way to reproduce or the location of the vanilla code where this behavior is missing?
