### ISSUE TITLE
Disable pointless Vanilla advancement reloading

### ISSUE THREAD

**Issue by Aaron1011** [MinecraftForge/MinecraftForge#5719]
Currently, the Vanilla `AdvancementManager` constructor unconditionally causes all advancements to be reloaded from disk. Since `WorldServer#init()` creates a new `AdvancementManager`, every world load causes a full reload of all advancements from disk.

The only possible way for this reload to do anything would be if either the minecraft jar or a mod jar was modified *at runtime*, since recipe JSON files are loaded from within jars. Assuming that Forge doesn't want to support such a bizarre use case, we could cut down on both world loading time and log spam (in the case of missing advancement recipes) by performing advancement loading exactly once.

Note that runtime jar modification isn't even possible on Windows, since a file cann't be modified while it's being held open by a program (e.g. Java). Any mod that tried to change its own jar file at runtime would only work on Linux and (possibly) OS X.

If there's interest in this idea, I can make a PR implementing it.

**Comment by williewillus** [comment]
how would we do this, by passing in the existing AdvancementManager of the overworld, or?

**Comment by Aaron1011** [comment]
We could just add a static boolean to `AdvancementManager`, and check it in `reload`. If we want to retain compatibility with mods that create their own (unlreated) `AdvancementManager` instance, we could add a new constructor to `AdvancementManager`, which performs a check before calling `reload`

**Comment by Tralomine** [comment]
and how do you load advancements or recipes from datapacks ?
and worlds that disable vanilla datapacks ?

**Comment by Aaron1011** [comment]
@Tralomine: I was only considering this for 1.12 - I haven't look at how things work in 1.13.

**Comment by bs2609** [comment]
Even in 1.12, custom advancements in the world folder are a thing. How would you be proposing to deal with them, given they effectively override builtin advancements?
