### ISSUE TITLE
Piston Events

### ISSUE THREAD

**Issue by itsmeow** [MinecraftForge/MinecraftForge#5722]
# What am I proposing?
I'd like to propose the idea of some piston events. For 1.12+ there's no good way to determine if a piston pushes. I was hoping Forge could add a few events that fire at various stages of piston pushing to allow canceling a piston push as well as setting different PistonPushResults in the event.

# Why would this be helpful?
- Crafting with pistons
- Claim/Land control mods to block stealing stuff with sticky pistons (my personal issue)
- Changing piston functionality on certain blocks
That's all I could think of.

Kind of duplicate of #1844

**Comment by williewillus** [comment]
we'd have to be careful with this, pistons already generate enough gc pressure as is

**Comment by bs2609** [comment]
See #3481 (and its many predecessors).

**Comment by Alpvax** [comment]
I would suggest that we make it a block move event instead of specifically piston-based.
That way it would work with slime blocks and (provided modders fired the event themselves) any other mod-added blocks which can move others.

My suggestion would be to have a cancelable "AttemptMove" and a "BlockMoved" event (or Pre- and Post- Events).

**Comment by itsmeow** [comment]
Blocks don't "move", they get removed and placed somewhere else, so a "BlockMoved" event is impossible. A "block changed" event would make massive event pressure on the game as every time something changes, an event fires.

**Comment by Alpvax** [comment]
If we accept that a "move" is a removal and a clone, then the end result is the same. 

I believe that pistons create an entity of the block while it is in motion, which would constitute a move. (I'm not sure if it is much different to a falling block entity).

**Comment by itsmeow** [comment]
Pistons only remove and re-place the block at the intended spot. There is no way to generalize this as it is impossible to identify that any given removal/placement was the result of a piston without actually hooking to the piston. And my argument of event performance stands, I think there's a reason there's not a "Block Changed" event. Closest thing is NeighborNotify.

**Comment by itsmeow** [comment]
I will look at making an updated PR for this later.

**Comment by Alpvax** [comment]
My point was that we could make the event control that remove and replace.
I.e. if the event is cancelled, do nothing. Otherwise perform the removal and placement

**Comment by tterrag1098** [comment]
Superseded by #5727
