### ISSUE TITLE
[1.13.2]CreateFluidSourceEvent not triggers?

### ISSUE THREAD

**Issue by MSandro** [MinecraftForge/MinecraftForge#5723]
I am trying to get the CreateFluidSourceEvent to work. But what ever I do, it will be never triggered. 

Forge 25.0.191

**Comment by loordgek** [comment]
the fluid system is not ported yet, wait until 1.14

**Comment by Terpo** [comment]
I just tested this event with forge 1.14.4 - 28.1.96 (current latest) and it seems that it is still not triggered. 

As I have no clue how to help you with patches and so on maybe this is a helpful starting point
net.minecraft.fluid.FlowingFluid#calculateCorrectFlowingState Line 174
"if (this.canSourcesMultiply() && j >= 2) "
