### ISSUE TITLE
[1.12.2] Crafting recipes using ore dictionary ingredients can't specify to ignore damage values.

### ISSUE THREAD

**Issue by alcatrazEscapee** [MinecraftForge/MinecraftForge#5731]
As per the title, I want to make a crafting recipe that uses an ore dictionary item, but ignores damage on said item. During init I am adding the ore name:
```java
OreDictionary.registerOre("pickaxeWoodAnyDamage", new ItemStack(Items.WOODEN_PICKAXE, 1, WILDCARD_VALUE));
```

This recipe works as intended (i.e. accepts a pickaxe with any damage value)
```json
{
  "type": "forge:ore_shapeless",
  "ingredients": [
    {
      "item": "minecraft:wooden_pickaxe",
      "data": 32767
    }
  ],
  "result": {
    "item": "minecraft:planks",
    "data": 0
  }
}
```

This recipe does not work - it only accepts items that have zero damage, despite the ore name being defined to use wildcard value.
```json
{
  "type": "forge:ore_shapeless",
  "ingredients": [
    {
      "type": "forge:ore_dict",
      "ore": "pickaxeWoodAnyDamage"
    }
  ],
  "result": {
    "item": "minecraft:planks",
    "data": 0
  }
}
```

**Comment by Tristrian** [comment]
Have you tried to with a shaped version instead ? 
I had similar issue with the shapeless version.
