### ISSUE TITLE
[1.13.2] Build 199 introduced crash-on-launch error. (InvocationTargetException)

### ISSUE THREAD

**Issue by Unnoen** [MinecraftForge/MinecraftForge#5735]
https://github.com/MinecraftForge/MinecraftForge/commit/6a1337aa92365420290a0533937adbc2b6e26890 Introduced an error that prevents Minecraft from starting. (Build 199)

Log: https://gist.github.com/Unnoen/fef045aa8950e633fc764e3b018313ae

Creating an issue as it effects both users and modders, at first I thought it was just MDK related.

**Comment by ThexXTURBOXx** [comment]
Can confirm this happening in the IDE

**Comment by cpw** [comment]
This is happening in probably _all_ environments, sadly. I am investigating.

**Comment by tterrag1098** [comment]
Fixed upstream via https://github.com/cpw/modlauncher/commit/f622c62418f5a327d6c05efa7da96f34f2694fd1

Included automatically in next forge build, v25.0.203
