### ISSUE TITLE
[1.13.2] Crash on register dimensions mid-game

### ISSUE THREAD

**Issue by RobertSkalko** [MinecraftForge/MinecraftForge#5739]
Doing DimensionManager.registerDimension in-game crashes with

https://hastebin.com/egotadocug.cs

Reason for use: Random/Dynamic on demand dimensions.

Mods like rftools dimensions and myscraft(i think) allow players to configure and create their own dimensions. If i'm right they can't do that in 1.13.2 anymore and that's why they didn't update. My mod also does this. I have a path of exile-like map system where map items create new dimensions, where players adventure into and each map needs to be new, unique and random. Maps last a limited amount of time to discourage mob farms. World files are deleted when map expires and it unloads. (this worked great in 1.12.2)

Suggested solutions:
williewillus: copy world array on the getter > rejected by lex due to performance concerns ( i tested a bit and it seems its like 3 milliseconds on vanilla getter and 40 max with the array copy. I have tested a bit more and only when i copy the world array a few hundreds of thousands of times per tick does the server come to a crawl, so i think the perf should be fine)

**Comment by williewillus** [comment]
alternative: catch register calls while ticking is happening and delay their insertion into the world list until the end of the tick. I don't like this because it's way more complex and bug-prone vs just copying the list, but it's an idea.

EDIT: and I'm not even sure how "delay insertion" would work since the world then wouldn't be visible in the registry immediately which could cause subtle bugs mod-side.

**Comment by Spectre0987** [comment]
Even calling DimensionManager#getWorld() crashes with a CME if it's done during ticking and the dimension isn't loaded. My whole mod's an ungodly mess of addScheduledTask.

**Comment by Gamebuster19901** [comment]
Perhaps some sort of ConcurrentHashMap that's sorted by identity?

https://stackoverflow.com/a/27809294/6047804

**Comment by Quantum64** [comment]
Seems to be resolved in 1.14.3.
