### ISSUE TITLE
[MC 1.8.9] Server texture pack downloads trigger a crash

### ISSUE THREAD

**Issue by DarkArc** [MinecraftForge/MinecraftForge#5741]
I "fixed" it for myself, but forge doesn't appear to create the server resource packs directory, which can result in a crash.

"Fix": https://github.com/packet-loss-gaming/Monocle/commit/7330ae0a62df18556335fcb5d1f20d7bf0cae9a2

Affects the recommended build: 1.8.9 - 11.15.1.1722
As well as the latest build: 1.8.9 - 11.15.1.2318

**Comment by Gamebuster19901** [comment]
1.8.9 is unsupported.

**Comment by 0xilly** [comment]
Closing: I will re-open if this can be reproduced on a supported version of forge.
