### ISSUE TITLE
[1.13.2] When is the first stable release

### ISSUE THREAD

**Issue by daboluo666** [MinecraftForge/MinecraftForge#5742]
When is the first stable release for 1.13.2?
I'm sorry to ask this question, but I really care about it

**Comment by williewillus** [comment]
1.13.x is not receiving a stable release, 1.14 is coming sometime "soon"

**Comment by loordgek** [comment]
why does it need to be stable? you can use it now

**Comment by daboluo666** [comment]
@williewillus @loordgek 
Currently, many mod cannot be loaded due to forge's own problems, such as optifine.

> OptiFine is mostly updated to be compatible with Forge 1.13.2.
One standing problem is that Forge can't load the OptiFine class transformer from the mods folder.
It only works when OptiFine is installed as a library in the classpath.
@cpw knows what is missing and has plans how it can be fixed.

**Comment by loordgek** [comment]
https://www.minecraftforge.net/forum/topic/69030-forge-1132-not-compatible-with-optifine/?tab=comments#comment-342494
