### ISSUE TITLE
[1.14.3] Issues with registry replacement

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#5747]
There's currently two main issues with registry replacements.  May be a few more but these are the ones that I've hit before I can't load up any further.

Block Replacement - This errors due to `Block#toString` doing a registry lookup, which fails for the old block that is no longer in the registry.
Solution: Patch `Block#toString` to use `ForgeRegistryEntry#getRegistryName` instead of `IRegistry.BLOCK.getKey(Block)`

Item Replacement - This errors due to a class cast exception when the item is replaced.
Solution: `GameData$ItemCallbacks#onAdd` must not reference `BLOCK_TO_ITEM` as a `BiMap`, since it is now a `HashMap`.  (GameData L471)

**Comment by cjm721** [comment]
This still exists in 1.14.3-27.0.14

**Comment by Shadows-of-Fire** [comment]
Closed by #5922
