### ISSUE TITLE
Crash 'OTGWoodLandMansionGen' Singleplayer world

### ISSUE THREAD

**Issue by Wizzzeeerrrddd** [MinecraftForge/MinecraftForge#5748]
Forge version - 1.12.2-forge1.12.2-14.23.5.2837

Issue - World was pregenerated using ChunkPregenerator to the world border and crashes as it tries to load WoodLandMansion, unable to load into the world now as it tries to generate the structure each time.

[crash-2019-05-19_14.07.10-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/3195106/crash-2019-05-19_14.07.10-server.txt)

**Comment by skyecodes** [comment]
I don't think it has something to do with Forge. You should probably open an issue on OTG's issue tracker : https://github.com/PG85/OpenTerrainGenerator/issues

**Comment by kierajreed** [comment]
Please use [hastebin](https://hastebin.com/) for error logs and stack traces.
