### ISSUE TITLE
Generate Tags code dynamically

### ISSUE THREAD

**Issue by tterrag1098** [MinecraftForge/MinecraftForge#5753]
To avoid endless issues with keeping the code in sync with the tag jsons, we should generate one or both with a gradle task. It would work similarly to updateLicenses, run manually to synchronize the code with the jsons or vice versa.

**Comment by KnightMiner** [comment]
Is this something that can easily be made generic and part of Forge gradle/another library so mods can also use the method?

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/e1cdb2e5580b3da68ff8c142142e678fe20d9b00

**Comment by tterrag1098** [comment]
This problem still exists somewhat, since there are still two sources of information, one in Forge*TagsProvider classes and one in Tags.Block/Item etc.
