### ISSUE TITLE
Can someone help me?

### ISSUE THREAD

**Issue by SmallEnderman** [MinecraftForge/MinecraftForge#5759]
I've made a modpack and wanted to make my server launch it. but for some reason it keeps crashing?

https://pastebin.com/pLHfjpt4

if someone is able to help me that would be kind
(Also i might have put this in the wrong topic/place but idk where else to place it)

**Comment by GirafiStudios** [comment]
Questions like this should go on the Minecraft Forge forums :)
Link: https://www.minecraftforge.net/forum/

**Comment by FinnT730** [comment]
This is not the place for bugs that mods makes, like someone else said, go to the Forums.
This is also not a forge issue, a mod...

**Comment by SmallEnderman** [comment]
i know but idk where else to put it... and i know github has fast response so i thought maybe these people could help.. could you pls help me

**Comment by FinnT730** [comment]
You should go here: https://www.minecraftforge.net/forum/

This is not the place for things like this, the forums are the place you should go

https://www.minecraftforge.net/forum/
