### ISSUE TITLE
[1.13.2] BrewingRecipeRegistry doesn't work properly

### ISSUE THREAD

**Issue by FuGu0416** [MinecraftForge/MinecraftForge#5765]
**BrewingRecipeRegistry.addRecipe()** doesn't seems to make a proper recipe due to the **isInput()** and **isIngredient()** method from **BrewingRecipe.java** checks the same array.

The result is that the only way to get the desired output, I have to put the ingredient both in the input slot and the ingredient slot.

**Comment by ExpensiveKoala** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/cb21e95e0b0c9549f7e6c0a3def6e8667716f029

Was fixed a bit ago in that commit (for 1.14)
