### ISSUE TITLE
[1.14] Clients can only connect to a dedicated server once

### ISSUE THREAD

**Issue by Gamebuster19901** [MinecraftForge/MinecraftForge#5767]
An issue was discovered on the minecraft modding discord where clients can only connect to a dedicated server once. If they leave and attempt to reconnect, the connection will always time out. The client must be restarted in order for it to connect to the server again.

This issue has existed for a while, from before version (1.13.2 - 25.0.110), up to the latest version as of this report (1.13.2 - 25.0.219)

No useful data is logged in latest.log or debug.log which would help trace the issue. The issue does not occur if no mods are installed. 

We used [This mod](https://github.com/Gamebuster19901/Better-Paths) on both versions, and another private mod on version (1.13.2 - 25.0.110). The issue existed all three times. If you need access to the private mod, I can make it public, but the simple mod linked should be enough.

**Comment by cpw** [comment]
Impossible to reproduce, at least I think so? I need a lot more data on the exact symptoms here, and how you go about reproducing the problem. Do you have to immediately try and log in again? If you wait a second, it's fine?

**Comment by LexManos** [comment]
I'm able to reproduce, on a somewhat regular bases.
However, this is deep in netty code. Something in netty isn't doing it's job and reading bytes from the socket. The channel gets initalized, but nothing ever enters Minecraft code again.

**Comment by Gamebuster19901** [comment]
> Impossible to reproduce, at least I think so? I need a lot more data on the exact symptoms here, and how you go about reproducing the problem. Do you have to immediately try and log in again? If you wait a second, it's fine?

After disconnecting for any reason, simply try to reconnect at any point in the future. The client will be stuck at this screen:

![image](https://user-images.githubusercontent.com/7155747/58757110-f2eb8d00-84d3-11e9-859b-a9fec4e3b7bd.png)

The server and client are both forge with the mod provided above.

Finding out the first version of forge this occurs in should help narrow down the bug though.

**Comment by cpw** [comment]
Watch my stream. I was able to connect dozens of times in a row. Something weird is happening.

**Comment by Gamebuster19901** [comment]
Stream timestamp for reference: https://www.twitch.tv/videos/433227176?t=01h33m06s

**Comment by Gamebuster19901** [comment]
> Watch my stream. I was able to connect dozens of times in a row. Something weird is happening.

I watched your stream the timestamp above. I noticed you didn't have any mods installed. But I stated in the first post, that the bug only happens if you have a mod installed.

**Comment by Gamebuster19901** [comment]
Were others able to experience the issue without any mods installed?

**Comment by LexManos** [comment]
The issue does NOT only happen with mods installed. Tho technically, Forge is one mod just like any other mod. I am able to reproduce with just Forge. However as I said, it is deep in netty code. The channel is initialized, no errors are thrown, but no read events are ever fired again.
Netty is one thing I hate with a fiery passion, and I have no place to even start debugging its internals.

Also, please do not use these issues as a chat room, form your messages fully before posting, and edit your message if you need to add more before someone posts.

**Comment by chylex** [comment]
Experiencing this in 1.14.2 basically every time I want to relog to a dedicated server, even when logging out of Forge server and attempting connection to a vanilla server (same IP).

I find that opening a singleplayer world allows me to reconnect to the dedicated server again ~75% of the time (every time, so if it doesn't work first time, opening SP again will most likely fix the issue).

Perhaps this resets some internal Netty state, and is something that could be triggered manually as a workaround?

**Comment by TheNullablePrototype** [comment]
Same problem. This is terrible.
https://www.youtube.com/watch?v=HHbrFQ6_0mE&feature=youtu.be

**Comment by DaemonUmbra** [comment]
If you have this issue at least have the decency to provide client and server logs from the latest version of Forge.

**Comment by TheNullablePrototype** [comment]
[bug.zip](https://github.com/MinecraftForge/MinecraftForge/files/3445658/bug.zip)

**Comment by robertmakrytski** [comment]
een]: Connecting to mc.mineblaze.su., 25565
> [18:55:52.349] [Netty Client IO #1/INFO] [ne.mi.fm.ne.NetworkHooks/]: Connected to a vanilla server. Catching up missing behaviour.
> [18:55:53.674] [Client thread/WARN] [minecraft/ClientPlayNetHandler]: Unknown custom packed identifier: minecraft:register
> [18:55:53.678] [Client thread/INFO] [minecraft/NewChatGui]: [CHAT] | Зарегистрируйтесь » /reg [пароль]
> [18:55:54.124] [Client thread/WARN] [minecraft/ClientPlayNetHandler]: Unknown custom packed identifier: minecraft:register
> [18:55:59.145] [Client thread/INFO] [minecraft/ConnectingScreen]: Connecting to mc.mineblaze.su., 25565
(in this place i got timeout)

I tested on 28.0.29 for 1.14.4(i tested without mods)
There are --server --port argument for minecraft and i get (70 % of timeouts)
when i try to connect by button Direct connect , it works worse then Join server, vannilla doesn't have this problem( i can go to the game after i go to the main menu and connect again to this server i get (timeout)
This problem i can't get in linux(ubuntu), i get the problem only in windows
And there is different between Connect and Direct connect(it works worse)

**Comment by HexedHero** [comment]
Confirmed. Can only join a server once or twice at most and its forever on "connecting"

**Comment by LexManos** [comment]
We do not need any more confirmations. This is a issue that's been tracked down into the depths of netty code. Netty simply refuses to send us the data the socket is receiving. If you have any possible solutions, feel free to post. But 'confirmed' Is not useful.

Also, it wont stick forever, it'll time out, and eventually the issue in netty will timeout and you can connect again l. this is NOT the same timeout error screen, it's just a reference to if you let the client sit without connectingnforna while it'll work again without restart.

**Comment by guilhermewerner** [comment]
II'm having this same issue on 1.18.2. I will collect more information and post it here.

**Comment by gigaherz** [comment]
Please do not resurrect an old issue. If you have reason to believe this is a regression link to the issue in your new issue instead.
