### ISSUE TITLE
[1.13.2] Can't run server on OSX

### ISSUE THREAD

**Issue by ReeceXW** [MinecraftForge/MinecraftForge#5770]
I've just created a fresh new project and am able to run the client fine.
Attempting to run the server just terminates after a few seconds

```
13:11:43: Executing task ':prepareRunServer'...
> Configure project :
New Dep: net.minecraftforge:forge:1.13.2-25.0.219_mapped_snapshot_20180921-1.13

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :downloadMCMeta UP-TO-DATE
> Task :downloadAssets
> Task :extractNatives UP-TO-DATE
> Task :prepareRuns
> Task :prepareRunServer

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2s
5 actionable tasks: 1 executed, 4 up-to-date
13:11:46: Task execution finished ':prepareRunServer'.
```

It doesn't do anything else from this.
There is no added code, crashes or anything. This was the example from the MDK

On OSX 10.14.3

**Comment by mezz** [comment]
Please ask this type of question in the `modder-support-113` channel on discord: https://discord.gg/UvedJ9m
You should get a quick response there, too.

I think you need to use the `runServer` task, but the log above shows you are using `prepareRunServer`.
