### ISSUE TITLE
1.14.2 Forge Error launching the client inside of IntelliJay

### ISSUE THREAD

**Issue by RayzoRayy** [MinecraftForge/MinecraftForge#5780]
The issue is that it says the package for Blocks does not exist. Here is a picture of the issue. Also I have not done anything, this is just the Example Mod packaged with Forge.
Using Forge version 26.0.2

https://imgur.com/a/PH49eZx

**Comment by tterrag1098** [comment]
Superseded by #5781

**Comment by GirafiStudios** [comment]
Can be closed, since https://github.com/MinecraftForge/MinecraftForge/pull/5781 got merged.
