### ISSUE TITLE
[1.14.2] userdev runClient NullPointerException on launch

### ISSUE THREAD

**Issue by Unnoen** [MinecraftForge/MinecraftForge#5783]
`forge-1.14.2-26.0.5_mapped_snapshot_20190607-1.14.2`

Running `./gradlew runClient` grants me this.

https://gist.github.com/Unnoen/620158fdec17030e13d2d9dd30eefa38

**Comment by Unnoen** [comment]
Seem to have found it, the example mod still lists Forge `25,` and Minecraft `1.13.2` for required dependencies. What should be happening is Forge displays the errors and what's wrong, however `i18n` is never loaded, thus throwing a null exception.

**Comment by marcus8448** [comment]
#5781 fixes this

**Comment by Unnoen** [comment]
While that did fix it, it's not the cause of the problem, cpw appeared to have fixed it with https://github.com/MinecraftForge/MinecraftForge/commit/2d32929dc546758df070c38f61b6e0756aa5b77e though, so closing this for now.
