### ISSUE TITLE
[1.14.2] userdev runServer UnrecognizedOptionException on launch

### ISSUE THREAD

**Issue by Unnoen** [MinecraftForge/MinecraftForge#5784]
`forge-1.14.2-26.0.5_mapped_snapshot_20190607-1.14.2`

Getting this on runServer:

https://gist.github.com/Unnoen/0b9c74b536e562fcebbf4a070fb180f2

**Comment by willis81808** [comment]
This issue also occurs on 26.0.8, and appears to be platform independent. The exact same `UnrecognizedOptionException: gameDir` exception is thrown for standalone servers running Windows10 and Ubuntu16

**Comment by Unnoen** [comment]
It's the result of the `optionparser` in MinecraftServer.java not accepting the argument `gameDir`.

Removing the gameDir argument isn't possible since it seems to be required for loading mods, however I don't think it's used by the server at all. 

Adding `OptionSpec<Void> optionspec13 = optionparser.accepts("gameDir");` to the list of accepted arguments fixes this but I don't think it's a good permanent fix.

Hopefully this helps.

**Comment by Unnoen** [comment]
Fixed by https://github.com/MinecraftForge/MinecraftForge/commit/1434419e479f1f11487478f28b01f86f75a1f32e

ty Lex
