### ISSUE TITLE
[1.14.2] Process Error Invalid output

### ISSUE THREAD

**Issue by Mythblood** [MinecraftForge/MinecraftForge#5794]
Looks similar to #5547 

I tried uninstalling mine craft and getting a fresh install.. but still get this:
![image](https://user-images.githubusercontent.com/32394271/59166086-ddd1b800-8aea-11e9-8817-81aa75ae05fc.png)

 

>  Data  version.json
>   Processor failed, invalid outputs:
>     C:\Users\gardner\AppData\Roaming\.minecraft\libraries\net\minecraft\client\1
> .14.2\client-1.14.2-extra.jar
>       Expected: 8e7c4fa876381116984795af4a43aee35906a227
>       Actual:   307e5ac271dbd6651ca599059e41b657bbfbb916
>     C:\Users\gardner\AppData\Roaming\.minecraft\libraries\net\minecraft\client\1
> .14.2\client-1.14.2-slim.jar
>       Expected: d784ffb5343e4750c5f61f63f94d26bc032c2c48
>       Actual:   a7491a8df4b9f5c8b3bfe646f8d7cd1efa737fc0

Forge version: 26.0.12
running the jar install

i tried downgrading to Forge 13.2, and minecraft as well, but once again got a similar error about the hashes not matching...

**Comment by Mythblood** [comment]
Noticed 26.0.13 came out, came error still persists.

**Comment by LexManos** [comment]
1) Unable to reproduce and neither can the tons of people who install daily.
2) Try deleting the offending file and reinstalling
3) Use the forums for basic tech support.
