### ISSUE TITLE
1.14.2 breaking crops yields no results

### ISSUE THREAD

**Issue by RayzoRayy** [MinecraftForge/MinecraftForge#5796]
Updating my mod, noticing that breaking my crops yields no drops. Even vanilla ones have no drops when breaking potatoes, carrots, etc. If im not mistaken this bug existed in 1.13.2 also when Forge first came out. This is pretty much the same issue.

Forge version- 26.0.13
Minecraft Version- 1.14.2

**Comment by LexManos** [comment]
![](http://puu.sh/DEdZY/1c95fd755d.png)
Unable to reproduce, Vanilla crops drop just fine.
