### ISSUE TITLE
About villageSiege in 1.14.2

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#5800]
The forge event is returning false in the villageSiege, preventing the loop to continue to iterate the players, it also fires the event before knowing if the vector is not null.
https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/patches/minecraft/net/minecraft/village/VillageSiege.java.patch#L7
Also, the zombies can't appear at all (null entityType)
```java
        @Nullable
        private Vec3d findRandomSpawnPos(BlockPos pos) {
            for (int i = 0; i < 10; ++i) {
                BlockPos blockpos = pos.add(this.world.rand.nextInt(16) - 8, this.world.rand.nextInt(6) - 3, this.world.rand.nextInt(16) - 8);
                //within Village Radius
                if (this.world.func_217483_b_(blockpos) && WorldEntitySpawner.canCreatureTypeSpawnAtLocation(PlacementType.ON_GROUND, this.world, blockpos, null)) {
                    return new Vec3d((double) blockpos.getX(), (double) blockpos.getY(), (double) blockpos.getZ());
                }
            }

            return null;
        }
```
```java
   public static boolean canCreatureTypeSpawnAtLocation(EntitySpawnPlacementRegistry.PlacementType placeType, IWorldReader worldIn, BlockPos pos, @Nullable EntityType<?> entityTypeIn) {
      if (entityTypeIn != null && worldIn.getWorldBorder().contains(pos)) {
         return placeType.canSpawnAt(worldIn, pos, entityTypeIn);
      }
      return false;
   }
```

**Comment by LexManos** [comment]
You are right, the event got missapplied by a line.
However, the canCreatureSpawnAtLocation returning false for null is a vanilla mechanic. As is them sending in null.
So looks like you found a vanilla bug in 1.14.2 that disables Sieges. Congrats. See if its been reported to them, and get a bug ID we can tag this with.

**Comment by ghost** [comment]
[MC-154328](https://bugs.mojang.com/browse/MC-154328)
