### ISSUE TITLE
[1.14] Wrong Minecraft version in mods.toml causes crash

### ISSUE THREAD

**Issue by 128-bit-guy** [MinecraftForge/MinecraftForge#5801]
When I tried to launch Minecraft in dev environment, Minecraft crashed with this:
https://gist.github.com/128-bit-guy/8cf4f90aecd160dca320696927995ee7
After that I tried to remove all event handlers from mcmod.info. That didn't help. It crashed again with same exception.

**Comment by tterrag1098** [comment]
You likely have an `@Mod` without an entry in your mods.toml, or vice versa. Please double check your log for fatal/warn errors.

**Comment by Nacoma** [comment]
I received this same exception and was able to run the mod using `runClient` by changing the `versionRange` in mods.toml to

```
    versionRange="[1.14.2]"
```

This required modifying the mods.toml in the MDK for 1.14.2. It's possible that I've done something incorrectly.

**Comment by 128-bit-guy** [comment]
Changing minecraft and forge version fixed it. I think, nice user friendly menu should be shown instead of crash

**Comment by LexManos** [comment]
Thanks to cpw the error screens are now back. You should have a nicer error message now.
![](http://puu.sh/DKHta/332624a52f.png)
