### ISSUE TITLE
[Services] Certificate error preventing HTTPS access (ForgeGradle/etc)

### ISSUE THREAD

**Issue by Unnoen** [MinecraftForge/MinecraftForge#5807]
Putting this here as a placeholder issue to be linked to for the inevitable flood of questions.

The certificate for `minecraftforge.net` *is* valid, however the intermediate certificate isn't being sent.

The Forge team are aware, the people who can fix it are currently away/sleeping. 

A workaround is to add the intermediate  certificate to your keystore, I won't be providing instructions as it involves security and I don't want to be liable.

**Comment by Unnoen** [comment]
Certificate problem has been fixed and ForgeGradle and such are working again. 

You may need to restart any tools before they work.

**Comment by LexManos** [comment]
cpw changed the cert we use to a single central one for all subdomains. And set it to send only our cert, thinking nginx's 'fullchain' config option would automatically combine necessary certs. Apparently it didn't. 

Anyways this was just a temporary thing, that only effected some users {contrary to claims, as I tested on 4 different environments and didn't have issues in FG} but it's resolved now.
