### ISSUE TITLE
[1.13.2] Creating coremod for divided class breaks class

### ISSUE THREAD

**Issue by PlanetTeamSpeakk** [MinecraftForge/MinecraftForge#5808]
Whenever I make a coremod for a class that is not related to Minecraft, it seems to pass an empty ClassNode, it has no fields, no methods or anything along the lines of it. It even fully breaks the class even without modifying or transforming it at all. E.g. when not changing anything at all, it throws an IllegalAccessError once used stating that whatever class is using it does not have access to do so, then when I change its accessibility to public, it says that whatever method is being called does not exist. I highly doubt I am doing something wrong as this seems to solely be the case for non-Minecraft classes.

**Comment by PlanetTeamSpeakk** [comment]
Edit: it seems to be when the class is divided into pieces. E.g. com.mojang.brigadier.CommandDispatcher has another class called com.mojang.brigadier.CommandDispatcher$1.  *That* is what makes the transformation break.

**Comment by cpw** [comment]
It seems you're not very familiar with how classloading works, and how inner classes function. Please seek help on the forums or discord.
