### ISSUE TITLE
[1.14.2] Block side rendering

### ISSUE THREAD

**Issue by Snownee** [MinecraftForge/MinecraftForge#5810]
Faces of block model (like the composter in this picture) are incorrectly culled in some cases

![2019-06-13_18 01 08](https://user-images.githubusercontent.com/16059084/59424684-09181800-8e07-11e9-9069-f9fa0088ce7c.png)

Forge 1.14.2-26.0.25

**Comment by Unnoen** [comment]
Does this happen in vanilla?

**Comment by Snownee** [comment]
![2019-06-13_18 21 47](https://user-images.githubusercontent.com/16059084/59425320-3fa26280-8e08-11e9-9bd8-8cb7e6d74337.png)

@Unnoen Unfortunately no
