### ISSUE TITLE
[Native Launcher beta] Version manifest was corrupt

### ISSUE THREAD

**Issue by GoryMoon** [MinecraftForge/MinecraftForge#5815]
The new native launcher beta doesn't allow the url in a library to be empty and won't launch the game. [Twitter announcement of the new version.](https://twitter.com/slicedlime/status/1139554652083691520)
It works in the stable version of the launcher.

To get the beta version, go to the settings, click the beta checkbox and relaunch.
The [1.14.2-forge-26.0.25.json](https://gist.github.com/GoryMoon/2a52adba20b5f01cabaae5d2ee4e9c30) is unmodified from a fresh install of forge. 

Filling the empty url field with anything, as long as it's not empty, enables the launcher to start minecraft.

<img width="1375" alt="Screenshot 2019-06-14 at 18 04 11" src="https://user-images.githubusercontent.com/987002/59522572-4942cd80-8ecf-11e9-9649-77c14e310a9b.png">

**Comment by bs2609** [comment]
Probably belongs on https://github.com/MinecraftForge/Installer/issues/43, please add this information there.
