### ISSUE TITLE
Nested client hack sometimes explodes on servers.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#5821]
The nested supplier hack will sometimes break in subtle ways which cause all sorts of issues when using Forge/FML. The main example of this exploding can be observed by assigning an unsafe object to a field, variable, or passing it to a method. I've written two basic test mods that can identify this issue. This issue affects all 1.13 and 1.14 versions of Forge.

# Working Example
```java
@Mod("examplemod")
public class ExampleMod {

    public ExampleMod () {

        SimpleChannel channel = NetworkRegistry.newSimpleChannel(new ResourceLocation("gamestages:main"), () -> "1.0.0", s -> s.equals("1.0.0"), s -> s.equals("1.0.0"));
        
        BiConsumer<MessageData, PacketBuffer> encoder = (msg, buf) -> {};
        Function<PacketBuffer, MessageData> decoder = (buf) -> new MessageData();
        BiConsumer<MessageData, Supplier<Context>> handler = (msg, ctx) -> {
            
            System.out.println("Is Client player null? " + Minecraft.getInstance().player == null);
        }; 
        
        channel.registerMessage(0, MessageData.class, encoder, decoder, handler);
    }
    
    class MessageData {
        
    }
}
```

# Not Working Example
```java
@Mod("examplemod")
public class ExampleMod {

    public ExampleMod () {

        SimpleChannel channel = NetworkRegistry.newSimpleChannel(new ResourceLocation("gamestages:main"), () -> "1.0.0", s -> s.equals("1.0.0"), s -> s.equals("1.0.0"));
        
        BiConsumer<MessageData, PacketBuffer> encoder = (msg, buf) -> {};
        Function<PacketBuffer, MessageData> decoder = (buf) -> new MessageData();
        BiConsumer<MessageData, Supplier<Context>> handler = (msg, ctx) -> {
            
            EntityPlayer player = Minecraft.getInstance().player;
            System.out.println("Is Client player null? " + player == null);
        }; 
        
        channel.registerMessage(0, MessageData.class, encoder, decoder, handler);
    }
    
    class MessageData {
        
    }
}
```

**Comment by cpw** [comment]
Not a bug. Sadly, there's no way to make every possible variable assignment scenario work. You're leaking class references all over the show in the second example, due to the lvar assignment. If you think you can make it work without breaking the API as it stands, I welcome suggestions. I don't believe there is such a mechanism in Java however.

**Comment by Darkhax** [comment]
That's the same conclusion I came to a few hours ago. Unfortunately it looks like this is going to be one of those pitfalls modders will hit if they're not careful. The only suggestion I would have would be to split the API itself up and require registering on both sides, but that's still not ideal and a breaking change.

For anyone who finds this issue in the future, there are a few ways around it. The general approach is to use lambdas instead of method references. You can still run into issues if you're not careful though. To reduce the most amount of risk I would also recommend splitting things up into multiple classes. For example your message class should just be a POJO. You should also have a separate dedicated class for each physical side that handles the encoding/decoding/handling for that side. This level of separation isn't strictly necessary but I have personally found that it helps avoid issues. An example of this approach can be found [here](https://github.com/Darkhax-Minecraft/Game-Stages/blob/f6e5361dcd5392f8ff114a5321585f49495c14a6/src/main/java/net/darkhax/gamestages/GameStages.java#L27)
