### ISSUE TITLE
Vanilla tags getting overridden 

### ISSUE THREAD

**Issue by Naxanria** [MinecraftForge/MinecraftForge#5824]
When trying to add blocks to a vanilla tag, original tag gets overridden. Ignoring the `"replace"` value in the json. This value can be set to true/false or missing, makes no difference.

For example:

My logs.json in data/minecraft/blocks/
```json
{
  "replace": false,
  "values": [
    "#nom:cinnamon_logs"
  ]
}
```

My own logs do get added but the vanilla ones lose the tag:

![image](https://user-images.githubusercontent.com/3246224/59564521-2ab41200-9048-11e9-950a-f3e68e60ea1d.png)

This is on forge 1.14.2-26.0.32

**Comment by mcenderdragon** [comment]
Is it working on forge 1.14.2-26.0.23 ?

**Comment by Naxanria** [comment]
It does not.

**Comment by mcenderdragon** [comment]
Then it is most likely not connected to the inverse tags

**Comment by LexManos** [comment]
Unable to reproduce, 
![](http://puu.sh/DGPZp/9bedeabd79.png)

**Comment by Naxanria** [comment]
Adding to the vanilla tags works, but it overwrites the existing ones:
![image](https://user-images.githubusercontent.com/3246224/59568797-4f2be080-9080-11e9-8f6c-f1968d7f8830.png)
![image](https://user-images.githubusercontent.com/3246224/59568798-56eb8500-9080-11e9-823e-1d0a6c26f5c5.png)
Without the logs.json : 
![image](https://user-images.githubusercontent.com/3246224/59568809-a29e2e80-9080-11e9-8aa8-bc00fc5034b2.png)

**Comment by LexManos** [comment]
I was able to reproduce this, it is not a tag issue. It is a resource manager issue. Something messed up and any extra resource packs added override the vanilla one. I'll look into it tomarrow.

**Comment by LexManos** [comment]
![](http://puu.sh/DHi7l/2daed52b1e.png)  
![](http://puu.sh/DHi7G/19840569d1.png)
