### ISSUE TITLE
[1.14.2] Vanilla `IRecipeType` has replaced `RecipeType`

### ISSUE THREAD

**Issue by alcatrazEscapee** [MinecraftForge/MinecraftForge#5825]
In #5312, forge added a recipe type system in 1.13. This seems to have been replaced by the new vanilla `IRecipeType<T extends IRecipe<?>>`. From what I've found it functions very much the same as the forge system. Thus `RecipeType` and the related things can probably be removed.

Forge also used a `Map<RecipeType, List<IRecipe>` to avoid iterating the entire list of recipes every lookup, which seems to have been adopted into vanilla as well.

Changes:
 - `ForgeRecipeManager` -> This functionality should be covered by `RecipeManager`.
 - `RecipeType` -> Replaced with `IRecipeType`
 - `VanillaRecipeTypes` -> Held the two vanilla recipe types previously, they are now in `IRecipeType`
 - `IForgeRecipe` -> this added `getType()` to `IRecipe`, which has already been added in vanilla, so it can be removed.
 - `IRecipeType`s are now in a vanilla registry in `Registries`. I think this should get wrapped into a forge registry as well, similar to `IRecipeSerializer`?

**Comment by liach** [comment]
Ah yes.
https://github.com/MinecraftForge/MinecraftForge/pull/5312#issuecomment-455829213
The update won't be too difficult.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/a14c2233e07f1f3a371cb82a20281fe406b681f7
