### ISSUE TITLE
[1.13+] [Feature] Support for array of strings in lang file (multiline text)

### ISSUE THREAD

**Issue by hnOsmium0001** [MinecraftForge/MinecraftForge#5826]
Mojang switched to .json language files at 1.13, I think this is a chance for some more advanced features.

Currently it localization only supports simple `key:text` pairs, where `text` is a plain string. If we want to include localization for multi-line text , we must insert `\n` in the text or make multiple entries like:
```json
"example.multiLineText.1": "First line",
"example.multiLineText.2": "Second line"
```

I suggest adding support for `text` being an array of strings, therefore allowing simple way to localize multi-line texts:
```json
"example.multiLineText": [
	"First line",
	"Second line"
]
```

In code, this could be either
1. Add a indicator the the end of the key. For example, `example.multiLineText` that has 3 lines become `example.multiLineText.1`, `example.multiLineText.2`, and `example.multiLineText.3`
2. Add another format method that returns a `List<String>` instead of a plain `String`.
3. Other ways that I haven't think of yet.

**Comment by cpw** [comment]
Why? What's wrong with embedded newlines? I'll also point out that this, in general, causes big headaches for translations. Forcing an arbitrary split, means you presume all translations are of similar length, which is a foolish and frustrating assumption.

**Comment by liach** [comment]
the string list, imo, is better reserved for random translation entries.
