### ISSUE TITLE
[1.14.2] HarvestDropsEvent not fired

### ISSUE THREAD

**Issue by HyCraftHD** [MinecraftForge/MinecraftForge#5828]
No calls to ForgeEventFactory.fireBlockHarvesting from Block.
There are probably other events not fired e.g FluidPlaceBlockEvent.

**Comment by darkevilmac** [comment]
So this is still an issue, not sure if it's being looked at. If it's not then let me know and I'll make a PR to fix it.

**Comment by GirafiStudios** [comment]
@darkevilmac the Forge team have a lot of other stuff to focus on right now. Making a PR would probably be a good idea :)

**Comment by HyCraftHD** [comment]
@darkevilmac +1

**Comment by RayzoRayy** [comment]
Is this still Broken ?

**Comment by darkevilmac** [comment]
Created a PR for a fix, feedback welcome. #5871

**Comment by Kolatra** [comment]
is this still being looked at?

**Comment by gigaherz** [comment]
Oh forgot about this. I pushed the results of #6267, #6401 and #6554 to 1.14.4 last night, so it is now possible to use the global loot modifiers feature to achieve most/all of the same things HarvestDropsEvent would allow.
