### ISSUE TITLE
A feasible blocking measures against Netease pirated Forge Mod (personal opinion)

### ISSUE THREAD

**Issue by Yaktsar-0619** [MinecraftForge/MinecraftForge#5832]
I am a player of Minecraft in China.As I know,Netease Company in China is agent to release the Minecraft and that company steal many mods made from Forge Mod.And I have an idea to against this action.
  Maybe the Forge Mod must be installed on the registered user's computer and encrypt the Forge Mod itself.
  我是一个中国的MC玩家，可能我的英语水平不是很过关(笑)。据我所知，网易在代理了MC之后，肆意盗取Forge Mod本身和由Forge Mod衍生的Mod。
  我认为唯一的办法就是开放注册，让注册用户才可以安装并使用Forge Mod，然后再在Forge Mod本身中加密以防止这样的窃取行为延续。

**Comment by LexManos** [comment]
Forge will NEVER add DRM.
We are not happy with the whole Netease situation, but we will not punish end users because of it.
End of discussion.
