### ISSUE TITLE
[1.14.2] Core Mod Path

### ISSUE THREAD

**Issue by Hallowizer** [MinecraftForge/MinecraftForge#5834]
Hi! I am working on a coremod, and I put a coremod in `coremods.json` that points to `core-plugin.js`. When I ran Minecraft, the core mod did not load, and when I looked through the log, this is what it said:

`[18Jun2019 10:34:00.628] [main/ERROR] [CoreMod/]: Error occurred initializing CoreMod
java.nio.file.NoSuchFileException: /Users/hallowizer/Documents/Modding/Mods/descript/descript/bin/main/core-plugin.js/core-plugin.js`

It looks like the file name is showing up twice in the path, at least in a dev workspace. Can this be fixed?

**Comment by Cadiboo** [comment]
Post your coremods.json file. I remember getting this error and I’m pretty sure this is a problem with your mod and not Forge
