### ISSUE TITLE
[1.14.2] Lighting update issue

### ISSUE THREAD

**Issue by Sunekaer** [MinecraftForge/MinecraftForge#5839]
Hey 

Having problems with lighting updates not happening, as you can see on the images (First image is forge and second is vanilla.) i used a structure block to remove the block in both forge and vanilla 
Tested with forge 1.14.2-26.0.16 and 1.14.2-26.0.33 and no mods
Forge:
![image](https://s1.sunekaer.com/i/19-06-2019_22-32-25_javaw.png)
Vanilla:
![image](https://s1.sunekaer.com/i/19-06-2019_22-34-48_javaw.png)

**Comment by Cloudhunter** [comment]
Can confirm this issue exists. Can easily be confirmed on a flat world with this command:

```
/fill ~32 ~-1 ~32 ~ ~ ~ minecraft:air destroy
```

It'll leave an ugly black square.

**Comment by LexManos** [comment]
I am able to reproduce with the fill command. On some cases. It seems to be a threading/order issue. The lighting IS updating, it's just thinking it has 0 light. We dont touch anything in the light engine. Will keep looking into it.
