### ISSUE TITLE
[1.14.2] Custom TNT is unergonomic/impossible to implement

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#5841]
In 1.12, you were able to extend `BlockTNT`, override the `explode` method to spawn your own custom primed entity, and from then have extremely easy custom TNT that works with everything in the game (flint and steel, fire, dispensers, etc.)

In 1.14, the `explode` method is now static and calls to this static method come from all over the codebase. It's impossible to get true feature parity back without using hacks like mixins (e.g. to ignite the tnt on fire spread) in every mod wanting this.

Proposed solution: Patch an instance method back into `TNTBlock` and redirect the static method to do `world.getBlockState().getBlock().explode`

**Comment by cosmicdan** [comment]
Maybe firing a new event from the vanilla explode method is better?

**Comment by LexManos** [comment]
What cases actually trigger the 'explode' function? Are you just wanting a generic 'caughtFire' function? Something not specific to TNT/Exploding. The other area should be fine, as you already have redstone reaction ability.

**Comment by williewillus** [comment]
mainly it's fire spread and the flint and steel dispenser behaviour that call the static explode externally.
a bunch of TNTBlock's internal instance methods call it too and it'd be nice to not have to copy paste those impls from the superclass just to change which explode method it calls

**Comment by LexManos** [comment]
Ya, seems that a `caughtFire` callback on block would be the way to go then.
As for the implementation for TNTBlock itself, You're right, this needs a lot of patches to fix. But may be worth doing.
