### ISSUE TITLE
[1.14.2] Registry IDs are no longer synced on login

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#5844]
I was testing a modded server and I pushed an update to one of my mods which added another block.  Since the world was preexisting, the ID map was no longer the "default" load-order id map.

However forge is supposed to resolve this by sending the IDs on login so that everything matches, but that did not happen.  To the server, everything was correct, so the level.dat is not corrupted, but on the client, everything was visually shifted (as one would expect from a mismatched ID map).

Not sure as to why the id sync fails (or never happens, I can't really tell).

**Comment by LexManos** [comment]
Should be fixed by https://github.com/MinecraftForge/MinecraftForge/commit/e5acea60e63facf30f060dcc4905ba8f18dfb1cb Let us know.

**Comment by Shadows-of-Fire** [comment]
Can confirm this is now working properly
