### ISSUE TITLE
Misplaced backslash in Forge 1.8.9

### ISSUE THREAD

**Issue by Nixinova** [MinecraftForge/MinecraftForge#5845]
**Forge version:** 11.15.1.2318 (Minecraft 1.8.9 latest)

In the "Mods" section, the search label says "Search\:" instead of "Search:"

![2019-06-22_16 50 23](https://user-images.githubusercontent.com/42429413/59959552-ddcfb000-950d-11e9-8020-59124f69e97c.png)

**Comment by tterrag1098** [comment]
1.8,9 is no longer receiving updates.
