### ISSUE TITLE
[1.14.3] OBJLoader fails to load OBJ models

### ISSUE THREAD

**Issue by Iunius118** [MinecraftForge/MinecraftForge#5847]
`OBJLoader` fails to load models when the first `ModelBakeEvent` is dispatched because `OBJLoader.manager` remains `null` when the model loader is registered.

**Comment by Iunius118** [comment]
I add a detailed report.

**Minecraft Version:** 1.14.3

**Forge Version:** 1.14.3-27.0.15

**Steps to Reproduce:**
[Source code](https://gist.github.com/Iunius118/6aec0ce96b26ea3d85c6d8ca7c465623)

 1. I try to load an OBJ model on `ModelBakeEvent`
 2. Run Client
 3. On the first `ModelBakeEvent`, `OBJLoader` fails to load the model
 4. Join a world
 5. Press F3+T and reload resources
 6. On the second `ModelBakeEvent`, `OBJLoader` fails to load the model again
 7. Press F3+T and reload resources again
 8. On the third `ModelBakeEvent`, `OBJLoader` succeeds in loading the model

**Description of bug:**
This problem may contain two bugs:

 - `OBJLoader` is not given any resource manager on its initialization
 - In reloading resources, `OBJLoader.onResourceManagerReload()` is called after `ModelBakeEvent` fired

Step 4:
![2019-06-30_05 51 32](https://user-images.githubusercontent.com/18502177/60389528-c429fc00-9afd-11e9-9157-6e883b17ec7e.png)

Step 6:
![2019-06-30_05 51 59](https://user-images.githubusercontent.com/18502177/60389532-c7bd8300-9afd-11e9-9ff1-3ba333e2a96e.png)

Step 8:
![2019-06-30_05 52 08](https://user-images.githubusercontent.com/18502177/60389534-cb510a00-9afd-11e9-95a9-8a546ed6530c.png)

**Comment by Nuchaz** [comment]
Can confirm. I am also working with .obj models and I have to hit F3-T 2 times before they start rendering. This is still present in forge v27.0.25
