### ISSUE TITLE
[1.14.2] [Feature Request] Fluid capabilities

### ISSUE THREAD

**Issue by realmayus** [MinecraftForge/MinecraftForge#5848]
Are fluid capabilities planned to be added to 1.14.2 forge? 1.13 didn't seem to have it and several people wrote that Forge will have it again in 1.14 because it needs a full rewrite. 
I can't seem to find it in 1.14. Is it still work in progress or already in the MDK?

**Comment by loordgek** [comment]
still wip

**Comment by gigaherz** [comment]
Fluids were reimplemented in #5983
I'll consider this accomplished once #6098 is done and merged.

**Comment by gigaherz** [comment]
Calling this done. If there's something we missed in the current implementation, feel free to open followup issues.
