### ISSUE TITLE
[1.14.2]Crash when try to get tag of block on MP

### ISSUE THREAD

**Issue by Sunekaer** [MinecraftForge/MinecraftForge#5852]
Crash log: [Crashlog](https://s1.sunekaer.com/files/crash-2019-06-22_22.18.52-server.txt)
Code: [Github - class code](https://github.com/Sunekaer/ToolKit/blob/master/src/main/java/com/sunekaer/mods/toolkit/commands/CommandOreDist.java)

Hey 
Im getting this check on MP when trying to get tags from block, this works fine in SP, am i doing something or here? or is this a bug?

**Comment by tterrag1098** [comment]
getOwningTags is `@OnlyIn(CLIENT)`

**Comment by LexManos** [comment]
Fixed in https://github.com/MinecraftForge/MinecraftForge/commit/216b5369673f5a496a5f587b532a2ecaf8ec79a6
