### ISSUE TITLE
[1.14.2] Fresh Forge install crashes on startup

### ISSUE THREAD

**Issue by Da-Technomancer** [MinecraftForge/MinecraftForge#5853]
A fresh install of the latest Forge (26.0.48) crashes on startup, even with no mods, resourcepacks, datapacks, etc. installed. 

Crashlog here: https://gist.github.com/Da-Technomancer/08287a7cbe8b6664fe59d0db54e2f1dd

26.0.47 works fine. 

Looks like some sort of race condition where the resourcepack loader is using the modlist before it has been built.

**Comment by GirafiStudios** [comment]
This is a known issue, and CPW is going to look into it when he gets time it seems :)
I would recommend using 26.0.43 for now, since 26.0.7 still have some issues that could break stuff in some mods.

**Comment by GirafiStudios** [comment]
Fixed in 26.0.49+

**Comment by cpw** [comment]
Fixed. Closing

**Comment by PackersOP** [comment]
Well now 1.14.3 is crashing even though it was working literally 1 hour ago.
