### ISSUE TITLE
[1.14.2] Vines not climable

### ISSUE THREAD

**Issue by Sinhika** [MinecraftForge/MinecraftForge#5856]
Vanilla vines, when placed against a vertical solid block, are not climbable when Forge 1.14.2 is installed. I have tested this with patches 26.0.32 and 26.0.56.  In a pure vanilla installation of Minecraft 1.14.2, vines are climbable like ladders, as they have been traditionally.

**Comment by Sinhika** [comment]
I did a bit of diagnostic spelunking in the Forge code. The problem appears to be that LadderBlock, VineBlock, and ScaffoldingBlock all inherit isLadder() from the IForgeBlock interface, but only LadderBlock overrides the default and returns true. VineBlock.isLadder() and ScaffoldingBlock.isLadder() return the default, false. I'm guessing the IForgeBlock.isLadder() interface was put in so that mod ladders could be created? If that is the intention, the fix would be to override isLadder() in VineBlock.java and ScaffoldingBlock.java.  If that is merely a relic of old code, then I'm off base and don't know what's going on.

**Comment by Eragonn1490** [comment]
I believe you are right. I’ll be able to confirm later today if no one else does first

**Comment by legobmw99** [comment]
This was fixed in 1.14.3-27.0.2
