### ISSUE TITLE
[1.14.x] Effect registration event is fired after the item registration effect, preventing adding custom effects to foods

### ISSUE THREAD

**Issue by KnightMiner** [MinecraftForge/MinecraftForge#5859]
Currently, the item registration event is one of the first to register, being run before most other events including effect. This is a problem with the new item builder system as items must have all their potion effects added on construction. Specifically, this is done through `Item.Properties::food()` and `Food.Builder::effect()` which requires an `EffectInstance`. At the time this builder is used, the `Effect` object holder used in creating that `EffectInstance` will be null resulting in a crash when that food is eaten.

This can be worked around by instantiating the potion effects in the item event then storing them statically until the effect event, but that is a pretty messy solution and does not work with registry substitutions. 

A quick fix for this issue would be to [move the effects registry before items](https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/main/java/net/minecraftforge/registries/GameData.java#L901-L905), but it was mentioned on discord that a more proper registry sorting system is in the works.

**Comment by LexManos** [comment]
This has been discussed quite a few times before. Manually making everything sorted is not a solution.
The better way to do it would be to build your cross registry dependencies using a delegate system. So that you can react to registry replacements and delay entry creations/lookup until needed. For this order issues.
So if you want to create a PR adding, say a `Food.Builder::effect(ResourceLocation effectname)` then it may be considered. But will WILL NOT be sorting registries.

**Comment by KnightMiner** [comment]
One of the issues with the food builder is it requires an effect instance, so I'd have to store a list of not only effect resource locations, but also time and amplifier.

Would an acceptable solution be to patch EffectInstance's constructor to take a ResourceLocation instead of an effect, then lazy load the effect from the registry? The crashes caused by this do not happen until it attempts to apply the effect in world so it will lazy load late enough.

Otherwise, I could look into patching the builder, but I have a feeling it will be a larger patch as I will need the resource location and time/amplifier method, an extra variable to store unloaded effects in Food, and logic to ensure they load later when requested.
