### ISSUE TITLE
[1.14.3] EntityJoinWorldEvent not firing for PlayerEntity instances on the server

### ISSUE THREAD

**Issue by fredtargaryen** [MinecraftForge/MinecraftForge#5868]
**Minecraft Version:** 1.14.3

**Forge Version:** 27.0.9

**Description of bug:**
Quite confident of the above. My EntityJoinWorldEvent handler executes for client-side players and entities, server-side entities, but not server-side players.

**Comment by Niko-sk2x** [comment]
Will be fixed by https://github.com/MinecraftForge/MinecraftForge/pull/5827, I just need to regenerate patches after 1.13.3 update.

**Comment by fredtargaryen** [comment]
Ah, thank you!

**Comment by fredtargaryen** [comment]
Fixed as of 27.0.31.
