### ISSUE TITLE
[1.14.3] PlayerEvent.Clone does not preserve capabilities during death

### ISSUE THREAD

**Issue by legobmw99** [MinecraftForge/MinecraftForge#5869]
**Minecraft Version:** {1.14.3}

**Forge Version:** {27.0.10}

**Description of bug:**
When a player dies, their capability is not preserved by the clone event. This leads to calling getCapability on event.getOriginal() failing. 

This was supposed to be fixed in 1.13 by #5728 but comments on that issue suggest it was only fixed for dimension changing, not death

**Comment by LexManos** [comment]
Provide test cases. As all of mine work fine.

**Comment by legobmw99** [comment]
The issue was noticed [here](https://github.com/legobmw99/Allomancy/blob/master/src/main/java/com/legobmw99/allomancy/handlers/CommonEventHandler.java#L70) in my mod. The code does not run during respawns, and similar methods of doing essentially the same thing failed (For example, the 1.12 version of the [same code](https://github.com/legobmw99/Allomancy/blob/1.12/src/main/java/com/legobmw99/allomancy/handlers/CommonEventHandler.java#L83) no longer worked).

The error appears to be somewhat strange, as using the debug explorer inside the event says that [the capability is attached,](https://i.imgur.com/8MS11ur.png) but evaluation using getCapability yields [this](https://i.imgur.com/V81g5NA.png), where the first's supplier is null

**Comment by legobmw99** [comment]
I had not noticed the revive() method, my apologies
