### ISSUE TITLE
Mod list description wrapping doesn't trim leading space

### ISSUE THREAD

**Issue by thecodewarrior** [MinecraftForge/MinecraftForge#5872]
**Minecraft Version:** 1.14.2

**Forge Version:** 26.0.63

**Full Log:** N/A

**Steps to Reproduce:**
 1. Create a mod with a long description in the `mods.toml`
 2. Open the mod list
 3. Select the mod

**Description of bug:**

**Expected behavior:**
The start of each wrapped line is aligned along the left edge.

**Actual behavior:**
All wrapped lines have a leading space character.

The bug appears to be on [this line](https://github.com/MinecraftForge/MinecraftForge/blob/be415091cdafd72acb179988970960e5007e8529/src/main/java/net/minecraftforge/fml/client/gui/GuiModList.java#L185). The second to last argument of `splitText` controls whether to delete spaces when wrapping. By setting it to false when the text is split before a space it isn't removed from the next line, meaning that line is indented by one space.

**Comment by LexManos** [comment]
Okay, so looking into this GUI is going to be a bit more complex. The whole clicking and scrolling doesn't work. Vanilla's AbstractList doesn't seem to be feasible for this GUI.

However, for your specific request, I don't agree with it. I like the extra space. It makes wrapped things like author/update url be `tabed` correctly.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/0a7f5ff9fa5012ac1a21b1f1efc273cb024d4465
