### ISSUE TITLE
org.ow2.asm gone missing

### ISSUE THREAD

**Issue by Techjar** [MinecraftForge/MinecraftForge#5879]
**Minecraft Version:** 1.11.2 or earlier

**Forge Version:** N/A

**Full Log:**
```
Failed to download file.
Name: asm-all-5.0.3.jar
URL: http://files.minecraftforge.net/maven/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
Error details: The requested URL returned error: 404 Not Found
Filename on disk: asm-all-5.0.3.jar
Path: C:\Users\[redacted]\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar
Exists: Nonexistent
```

**Steps to Reproduce:**
 1. Install any Forge version for 1.11.2 or older on a fresh .minecraft directory.
 2. Attempt to launch.

**Description of bug:**
The org.ow2.asm library has gone missing from the Forge maven repository, which many older versions rely on, rendering them unlaunchable on new installs without manually editing the json or downloading the library.

**Comment by LexManos** [comment]
What EXACT version are you installing. We shouldn't be targeting 5.0.3.

**Comment by Techjar** [comment]
This is actually Vivecraft's json, we forgot to target the newer version when updating. This is irrelevant though as I checked the maven repo manually and the entire org/ow2 directory is gone.

**Comment by LexManos** [comment]
It is not gone. We just dont do directory listing. So this is a issue on your end using the wrong version. Cool. Closing.

**Comment by Techjar** [comment]
This is still valid though as it affects much older versions like 1.7.10 and 1.10.2.

Edit: I checked Forge's json and only 1.12 and up target the newer version, earlier ones use 5.0.3.

**Comment by LexManos** [comment]
Then do as I said and provide the EXACT version. So i can verify that we are actually targeting 5.0.3 as we should not be.
Forge targets/ships 5.2 and 5.0.2. You are literally the first one to report that we're tarting 5.0.3. And I would assume SOMEONE else would of had this issue before if it was true as we do not delete files off our maven. So, again Post the EXACT FORGE VERSION. And where you're getting it from.

**Comment by Techjar** [comment]
Okay, apparently this is where it comes from: https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/jsons/1.11.2-rel.json#L34

But I think I see what's happened here. We changed the repository to Forge as it was trying to download the library from Mojang's servers, and apparently they stopped hosting it. What I'm confused about is this only says serverreq, but I thought the library was used on the client too.

**Comment by LexManos** [comment]
Serverreq specifies that the server installer needs to download it.
The client launcher will auto-download it.
And since there is no URL, it is hosted on Mojang's servers.
If they removed it, then speak to them.

**Comment by Techjar** [comment]
Ah, well that clears things up. Sorry for the trouble, ~this is something we did I believe a couple years ago so I totally forgot about it.~

Edit: Actually this is a recent change that I didn't notice. GG, now I feel like a dumbass.
