### ISSUE TITLE
Crash when updateJSONURL in mods.toml is empty

### ISSUE THREAD

**Issue by Senmori** [MinecraftForge/MinecraftForge#5881]
**Minecraft Version:** 1.14.3

**Forge Version:** 1.14.3-27.0.15

**Full Log:** https://gist.github.com/Senmori/d81b205c206b18d25311e1be40f18704

**Steps to Reproduce:**
 1. Leave `updateJSONURL` in `mods.toml` empty. (Not commented out)
 2. Run Client.

**Description of bug:**
[ModInfo](https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/ModInfo.java#L77) is attempting to retrieve an empty string and map it to a new URL via [StringUtils::toURL](https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/fmllauncher/java/net/minecraftforge/fml/loading/StringUtils.java#L44). This results in `StringUtils.toURL` throwing an exception before it can return null.

My mods.toml: https://i.imgur.com/t8f6llF.png

**Comment by diesieben07** [comment]
Yes. An empty string is not a valid URL.
