### ISSUE TITLE
Invalid update url in updateJSONURL errors

### ISSUE THREAD

**Issue by Senmori** [MinecraftForge/MinecraftForge#5882]
**Minecraft Version:** 1.14.3

**Forge Version:** 1.14.3-27.0.15

**Full Log:** https://gist.github.com/Senmori/3b56ea3dd221e3a6e3c0fd3bf949add6
I snipped the rest of the log for brevity. I can post it all on request.

**Steps to Reproduce:**
 1. Put invalid website in `updateJSONURL` entry.
 2. Run client.

**Description of bug:**
When an invalid website is the value of `updateJSONURL` the ForgeVersionCheck will produce a JsonSyntaxException. 
Invalid in this case meaning a website that does not conform to the [documentation](https://mcforge.readthedocs.io/en/1.13.x/gettingstarted/autoupdate/) (i.e. Google).

Secondary:
It seems all websites must be prefixed with a protocol (i.e. https://) in order for the URL to be created in `StringUtils::toURL`. ~~I don't know if this is intended or not.~~(This is indeed default java URL behavior when no protocol is present)
Although it would seem trivial to have a check for a protocol.

My mods.toml: https://i.imgur.com/GFx62xq.png

**Comment by diesieben07** [comment]
> When an invalid website is the value of updateJSONURL the ForgeVersionCheck will produce a JsonSyntaxException.

Yes. What else do you expect?
> It seems all websites must be prefixed with a protocol (i.e. https://) in order for the URL to be created in StringUtils::toURL. I don't know if this is intended or not.(This is indeed default java URL behavior when no protocol is present)

Yes. That's how URLs work. They need a protocol.

**Comment by iTitus** [comment]
Maybe throw a more user friendly error, like `not a valid URL`.
