### ISSUE TITLE
[1.14.x] Forge Blockstate loader model path is inconsistent with vanilla blockstates

### ISSUE THREAD

**Issue by KnightMiner** [MinecraftForge/MinecraftForge#5892]
**Minecraft Version:** 1.14.3

**Forge Version:** 27.0.17

**Description of bug:** Currently, Forge loads block models from blockstates by [prefixing the path with `block/`](https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/main/java/net/minecraftforge/client/model/ForgeBlockStateV1.java#L449-L453); however in either 1.13 Mojang added the `block/` prefix to all their blockstate models and removed the hardcoded prefix. The result is when switching from a vanilla blockstate to a Forge one, you have to modify every model path to remove the `block/` prefix, plus some models available in the vanilla blockstate are unavailable without aliasing in Forge.

**Comment by LexManos** [comment]
The downside is that it breaks every model that exists in v1 format. Besides telling modders/resource makers to sod off, is there a good solution to fix this?
What does vanilla do to support older resource packs?

**Comment by tterrag1098** [comment]
They don't handle it that I know of. The version flag is just to mark incompatibility in the UI, there are no adapters.
