### ISSUE TITLE
[1.14.3] shear with dispenser give shears instead of wool

### ISSUE THREAD

**Issue by sedounet** [MinecraftForge/MinecraftForge#5895]
Minecraft v1.14.3

Forge 1.14.3 27.0.23

sorry in don't know where to find log. 

In game, créative or survival on my system, when attemp to shear a sheep with a dispenser, the sheap is sheared but drop shears.

PS : sorry for my english, i'm french and d'ont practise :)

**Full Log:** {Link to GitHub Gist with full latest.log}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of bug:**

**Comment by Unnoen** [comment]
Most likely related to https://github.com/MinecraftForge/MinecraftForge/issues/5806

**Comment by sedounet** [comment]
> Most likely related to #5806

yes, except when shear with shears in hand it drop wool correctly

**Comment by Unnoen** [comment]
Yeah I meant that the bug is probably related, that first one got fixed. I was just putting it here for reference.

**Comment by sedounet** [comment]
ho, ok. it's my first bug report, so my appologize for "wrong answers" :)

**Comment by FullMetalMaster** [comment]
1 get sheep and dispenser 2 shear 3 UNIMPLEMENTED SHEARS!
