### ISSUE TITLE
Installer not downloading some libraries

### ISSUE THREAD

**Issue by Geodude6** [MinecraftForge/MinecraftForge#5900]
**Minecraft Version:** 1.14.3

**Forge Version:** 27.0.24

**Full Log:** [forge-1.14.3-27.0.24-installer.jar.log](https://github.com/MinecraftForge/MinecraftForge/files/3360632/forge-1.14.3-27.0.24-installer.jar.log)

**Steps to Reproduce:**
 1. Open Launcher
 2. "Install client"
 3. Get error message "these libraries failed to download"

**Description of bug:** 
[These libraries failed to download](https://user-images.githubusercontent.com/26030289/60689901-4ce6c600-9e77-11e9-9af8-44bcb85417eb.PNG)

**Comment by srs-bsns** [comment]
Update your java installation to atleast `8u110`.

**Comment by DaemonUmbra** [comment]
Try the forums first next time
