### ISSUE TITLE
[1.14.3] Custom Sounds don't quiet with distance

### ISSUE THREAD

**Issue by KingPhygieBoo** [MinecraftForge/MinecraftForge#5902]
Minecraft 1.14.3

Forge 1.14.3, 27.0.23

No log to provide.

After registering some custom sounds, play them from a distance. They don't seem to quiet down until out of hearing distance, in which case you just don't hear it at. For example, if I have a mob with a custom hurt sound, and I shoot it with a bow from around 5 blocks away, the sound will play just as loud, as if I were standing next to it. This doesn't seem to happen if I were to make a new sound event for an existing sound, it has to be within the mod's assets folder. (ex. making a new sound event that uses the vanilla cow hurt sound will act as expected)

**Comment by ChloeDawn** [comment]
Did you ensure your sound is entirely mono? The positional audio system is incompatible with stereo audio.
