### ISSUE TITLE
[1.7.10]: "Silently" catching entity tracking error. spam in console

### ISSUE THREAD

**Issue by SoonBanned** [MinecraftForge/MinecraftForge#5903]
I don't know what to do with this thing that get spammed in my console : https://pastebin.com/zxuB85aq

**Comment by SoonBanned** [comment]
I fixed this error by changing a config in enderio file and now I'm crashing with this error : https://pastebin.com/kmf4yUfe

**Comment by diesieben07** [comment]
1. 1.7.10 is ancient and no longer supported. Update.
2. This is something for the forums.
