### ISSUE TITLE
[1.14.x] Changing hotkeys for hotbar will cause item not to be swap-able anymore in the inventory

### ISSUE THREAD

**Issue by TheKeymaster** [MinecraftForge/MinecraftForge#5904]
**Minecraft Version:** {Minecraft version}

1.14.2

**Forge Version:** {Forge version. *Version number, not latest/rb*}

26.0.33

**Full Log:** {Link to GitHub Gist with full latest.log}

Not required.

**Steps to Reproduce:**

1. Go to Options > Controls... > Inventory. Here change the Hotbar slot "9" to something like "J". 
1. Open your inventory.
2. Changing slot 1 with 2 should work when hovering over slot 2 and pressing "1".
3. BUT changing slot 2 with slot 9 will not work when hovering over slot 2 and pressing 9 or the configured hotkey ("J").

**Description of bug:**

It should work swapping items in your inventory even when you change your configured key in the settings.

**Comment by FinnT730** [comment]
Is this not just a Vanilla bug?

**Comment by TheKeymaster** [comment]
Nope I tried it in vanilla and it worked just fine.

**Comment by LexManos** [comment]
Unable to reproduce following the exact described steps using the current version of Forge..
So Update and try again.
