### ISSUE TITLE
[1.14.3] No debug log produced, Forge log config unused

### ISSUE THREAD

**Issue by octylFractal** [MinecraftForge/MinecraftForge#5907]
**Minecraft Version:** 1.14.3

**Forge Version:** 27.0.25

**Full Log:** https://gist.github.com/kenzierocks/e32632459637215e852815a2e5a91067

**Steps to Reproduce:**
 1. Install Forge into the client
 2. Launch it.

**Description of bug:**
No `debug.log` is generated, and furthermore, Forge's logging config is never used. Setting a breakpoint in `LoggerContext.reconfigure(URI)` (line 617 in log4j2 2.11.2) and inspecting the resulting configuration will show it is loaded from the vanilla `client-1.12.xml` file.

This means there is no way to retrieve debug log messages, severely hampering the ability to debug in the live environment.

**Comment by LexManos** [comment]
This is a known issue with Mojang's new launcher. They have a fix for it and will be releasing it next time they release a launcher update.
