### ISSUE TITLE
Items Don't Stack properly

### ISSUE THREAD

**Issue by JustPlayn10** [MinecraftForge/MinecraftForge#5913]
For some reason Forge isn't stacking items properly. For example, I have two dirt "stacks" where in a normal world could easily be one stack.

**Comment by Cloudhunter** [comment]
Can you provide more details - Forge version, Minecraft version, and have you tested this in Vanilla to ensure this isn't a Vanilla bug?

You haven't given us much to go on unfortunately.

**Comment by mcenderdragon** [comment]
I think I also experienced that one time. Forge 25.0.191 (for 1.13.2) I had the item in slot 0 in the itembar then placed and broke it but instead of staking it created a new stack in slot 3 (and there they did stack). So maybe it is not checking the first slot ?

**Comment by LexManos** [comment]
![](http://puu.sh/DQpus/bccd99965e.jpg)

Not reproduceable. And not filed correctly.
