### ISSUE TITLE
Explosions can blow grave in 1.14.3

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#5914]
In 1.14.3, the explosions are able to explode "block"(grave in my case) that appears between the 2 steps of an explosion without any way to prevent them (even with high resistance and indestructible)
It happens because the forge event to remove the explodable positions happens in the step 1 of the explosion : during this step, the block(grave) is not yet present, but the player dies making it to appear.
During the second step of the explosion, we have no way to prevent the grave to be exploded... it seems to be a missing forge patch as it's not reproductible in 1.12.2.
![debug_explosion](https://user-images.githubusercontent.com/17954109/60774540-850b3480-a115-11e9-85f1-241a6af5d550.png)
Edit : easy step to reproduce is by setting a block indestructible on playerDeath, and make the player dies from TNT.
Edit again : in 1.12 we had :
```java
    /**
     * Called when the block is destroyed by an explosion.
     * Useful for allowing the block to take into account tile entities,
     * state, etc. when exploded, before it is removed.
     *
     * @param world The current world
     * @param pos Block position in world
     * @param explosion The explosion instance affecting the block
     */
    public void onBlockExploded(World world, BlockPos pos, Explosion explosion)
    {
        world.setBlockToAir(pos);
        onExplosionDestroy(world, pos, explosion);
    }
```
and in 1.14.3 :
```java
               this.world.setBlockState(blockpos, Blocks.AIR.getDefaultState(), 3);
               block.onExplosionDestroy(this.world, blockpos, this);
```

**Comment by mcenderdragon** [comment]
How is bedrock/obsidian not affected by this ? Also can you just return false on canDropFromExplosion (or would that break at another end)?

**Comment by Alpvax** [comment]
I don't think you quite understand the issue mce. The block is being added to the world in between the explosion starting and ending (added when the player dies to said explosion).
The reason the block is not explosion proof is presumably because it is only supposed to resist the explosion that "created" it.

**Comment by ProsperCraft** [comment]
The Tombstone graves are completely safe from explosions, after created.(I tested this) The issue comes when it is initially in the process of creation they are destroyed leaving a key that opens a grave that doesn't exist.
