### ISSUE TITLE
1.14.3 Processor failed, invalid outputs

### ISSUE THREAD

**Issue by ConnieSykes** [MinecraftForge/MinecraftForge#5915]
**Minecraft Version:** 1.14.3

**Forge Version:** 1.14.3 *27.0.25*

**Main part of the log:** Processor failed, invalid outputs:
    C:\Users\Connie\AppData\Roaming\.minecraft\libraries\net\minecraft\client\1.14.3\client-1.14.3-slim.jar
      Expected: 26e8580ce23d59759c2db41756a834a6df292313
      Actual:   06502fbec8594c88e64e2f54b3eb90627c0ffc24
    C:\Users\Connie\AppData\Roaming\.minecraft\libraries\net\minecraft\client\1.14.3\client-1.14.3-extra.jar
      Expected: e0a45cca33d23f63b149b4546978ee0e4d858167
      Actual:   78b49627eb4663bde854da7fd3e0c61c8b08ea0d

**Steps to Reproduce:**
Well, it started with the "failed to download these libraries", so I downloaded them manually and it worked, but I hit the forge installer and now it shows up the "invalid outputs" thing, tried to change them manually through the notepad but when I restart the installer it says the same, literally like if I didn't do anything.

**Full log:**
[forge-1.14.3-27.0.25-installer.jar.log](https://github.com/MinecraftForge/MinecraftForge/files/3366223/forge-1.14.3-27.0.25-installer.jar.log)

-Just noticed, it says that the client-1.14.3-slim.jar and client-1.14.3-extra.jar are missing, but here they're...idk what to do.
[Files.zip](https://github.com/MinecraftForge/MinecraftForge/files/3366225/Files.zip)

**Comment by lewishamilton22** [comment]
what a coincidence, i have exactly done the same thing. downloaded every library by my own, put them in the libraries folder and got stuck at de.oceanlabs.mcp:mcp_config:1.14.3-20190624.152911@zip . Put that in the folder as well and got the same error like you. its torture

I think the input is responsible to create the output, dont think its possible to just change the output

**Comment by lewishamilton22** [comment]
Okay, so i found a solution which works for me. 
I installed Minecraft in Linux in a virtual box. There I could install forge 1.14 without any problems. For the next step I swapped the libraries folder from windows with the one from linux. I then run the forge 1.14 installer under windows and got the success message! I am not sure if the last step is important but now forge works. 

I think there is a general problem with Minecraft or Forge. Windows 10 doesn't come with Java anymore which is good. Minecraft brings their own Java. At this point it gets "hard" for the user. you need to be comfortable with the console and execute Java from the terminal, which would be fine if there wasn't the problem with missing libraries. In the end i think it is unreasonable to invest such amount of time to get forge running.

Edit: I am new to GitHub but i think that my solution is also a solution not only to this issue: "1.14.3 Processor failed, invalid outputs", but as well for "These libraries failed to download. Try again."

**Comment by LexManos** [comment]
That is just wrong. Vms and manual running of java isnt the issue. If you can run the installer it already is in java. The issue is for some unknown reason you are getting invalid output from running the same code as thousands of other people. Which, in java land should be impossible. 

Also do NOT hijack others issues and claim you have the same one when its obviously a different issue.

**Comment by MarineBob** [comment]
Created an account and dropping in.
I have also the exact same issue:

Failed downloading the libraries (some handshake or certificate issue). Downloaded them manually using the links from the log files and placing them in their folders. Now the Forge installer is accepting all the files but stops at data.json with that slim and extra .jar

My "actual" hashes are the same as Connie's. Deleting the .jar.cache files and launching the vanilla game doesn't do anything. Rerunning Forge will yield the incorrect 2 .jar.cache from above again. Renaming the cache files to .jar files doesn't work either.

Send help
