### ISSUE TITLE
[1.14.x] EffectType in Effect is only in Client. Regression from 1.12

### ISSUE THREAD

**Issue by cjm721** [MinecraftForge/MinecraftForge#5920]
Methods using EffectType in itself (getting text format) and Effect (isBeneficial / getEffectType) are client side only. 

EffectType is used server side in Effect constructor but all of its usage beyond that are only used in the client. In 1.12 these were available on both sides.

**Comment by LexManos** [comment]
A lot of things change in vanilla. Especially related to sidedness.
If someone wants to PR the removal of the annotations we can evaluate that.
However,  justification beyond "it was this way in 1.12" will be needed.

**Comment by cjm721** [comment]
Use case for this is being able to remove all effects of x type. For example an item / splash potion that can remove all beneficial affects from an entity. 

Could currently get around the limitation by manually comparing against potion instances but that would mean it would have no affect on modded effects.

**Comment by cjm721** [comment]
Fixed via #5925 merge
