### ISSUE TITLE
Abbreviated Log in Dev Environment

### ISSUE THREAD

**Issue by Hallowizer** [MinecraftForge/MinecraftForge#5930]
**Minecraft Version:** 1.14.3

**Forge Version:** 26.0.32

**Logs:** https://pastebin.com/9vJB2f1P

**Steps to Reproduce:**
 1. Launch MinecraftForge in Dev Workspace

**Description of issue:**
I noticed that in the console of the client, at least in a dev environment, the parts of the package name are all abbreviated to two letters. I am not sure if this is intentional, but this makes it difficult to find the packages sometimes.

**Comment by srs-bsns** [comment]
That is intentional for the sake of brevity in logs. In 99.9% of all cases it should be quite easy to discern what the actual full package name is.
