### ISSUE TITLE
Commands are swallowing exceptions

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#5931]
**Minecraft Version:** 1.14.3

**Forge Version:** 27.0.50

**Logs:** No logs, they're being swallowed.

**Steps to Reproduce:**
 1. Find a command that is broken. (`/forge setdimension @p minecraft:the_nether`)
 2. Run the command
 3. The exception will be swallowed and you wont be able to see it.

**Description of issue:**
When an exception happens during the execution of a command the exception will not be logged to the console. This makes debugging issues with commands, or reporting issues to mod authors incredibly difficult.

**Comment by LexManos** [comment]
```
            StringTextComponent stringtextcomponent = new StringTextComponent(exception.getMessage() == null ? exception.getClass().getName() : exception.getMessage());
            ITextComponent itextcomponent = stringtextcomponent;
            if (LOGGER.isDebugEnabled()) {
               StackTraceElement[] astacktraceelement = exception.getStackTrace();

               for(int j = 0; j < Math.min(astacktraceelement.length, 3); ++j) {
                  itextcomponent.appendText("\n\n").appendText(astacktraceelement[j].getMethodName()).appendText("\n ").appendText(astacktraceelement[j].getFileName()).appendText(":").appendText(String.valueOf(astacktraceelement[j].getLineNumber()));
               }
            }

            source.sendErrorMessage((new TranslationTextComponent("command.failed")).applyTextStyle((p_211704_1_) -> {
               p_211704_1_.setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, itextcomponent));
            }));
```
Seems Mojang decided to hide the info behind a debug check. It sends it in the chat channel. But in this specific instance the chat is hidden so you dont see it.

**Comment by Darkhax** [comment]
After updating to Forge 27.0.57 the issue can no longer be reproduced with the `/forge setdimension @p minecraft:the_nether` command. I am guessing this was inadvertently fixed by https://github.com/MinecraftForge/MinecraftForge/commit/3d78f30d18586429be2854228b7f181a97a051d4

**Comment by LexManos** [comment]
No, the error in setdim was fixed by https://github.com/MinecraftForge/MinecraftForge/commit/a46b7cb67a903d0d4814a2f563b66daf69c8acb6#diff-66531a6c0289a9654ce522f047a8827eR252
As I pointed out, you can make it write the command errors to the log file by modifying the logging config.
So this particularly doesn't need a fix.
