### ISSUE TITLE
Eating food causes missing sprite particles.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#5934]
**Minecraft Version:** 1.14.3

**Forge Version:** 27.0.50

**Logs:** https://gist.github.com/Darkhax/03b467ecacc7cff269a74b48b4bcc654

**Steps to Reproduce:**
 1. Go into survival mode
 2. Use `/effect give @p minecraft:hunger 100 100` to deplete your food.
 3. Use `/give @p minecraft:bread` to give yourself some bread to eat.
 4. Eat the bread, make sure you finish the eating animation.

**Description of issue:**
When the eating animation finishes it will spawn the black/purple missing item sprite for the food particles instead of the actual item.

**Comment by Sicariana** [comment]
I'm also having this problem.

**Comment by LexManos** [comment]
![](http://puu.sh/DTzkU/467130a09d.jpg)
Unable to reproduce.

**Comment by Darkhax** [comment]
@LexManos The issue can only be reproduced if you have a stack size of one. Could you please try again with only one item.
