### ISSUE TITLE
Sprinting in spectator mode spawns particles

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#5935]
**Minecraft Version:** 1.14.3

**Forge Version:** 27.0.50

**Logs:** https://gist.github.com/Darkhax/03b467ecacc7cff269a74b48b4bcc654

**Steps to Reproduce:**
 1. Go into spectator mode `/gamemode spectator`
 2. Hit the ctrl key while moving to start sprinting.
 3. Fly into the ground while sprinting and look down. The particles that spawn when running on top of a block are spawning.

**Description of issue:**
When you sprint while in spectator mode the block sprinting particles will still be spawned for blocks you are moving through.

**Comment by srs-bsns** [comment]
This is a characteristic of vanilla. There have been several similar issues reported in the past in older versions and marked as being resolved.

**Comment by bl4ckscor3** [comment]
https://bugs.mojang.com/browse/MC-46417

**Comment by LexManos** [comment]
Non-critical purely cosmetic bug I dont care to fix in Forge. So i'm not going to look into this any further.
