### ISSUE TITLE
[1.14.3] Random ConcurrentModificationException without any mods

### ISSUE THREAD

**Issue by RobertSkalko** [MinecraftForge/MinecraftForge#5938]
To reproduce: load world, shoot snowball into nether portal
forge version 1.14.3-27.0.50

Try that a few times and chances are you'll crash once in a while. Keep shooting the snowballs for a while. If you don't crash, you'll lag a bunch.

here's the crash report
https://paste.gg/p/anonymous/a1b4e577d40f43c69197917cf012d1f4

I'd like someone to try reproduce it to make sure it isn't a vanilla bug. I tried restarting vanilla mc a few times to get it to crash but couldn't. Forge crashed a few times tho.

I think i saw this crash a few other times.

I reproduced it again just now on a clear world that was started with just forge installed. (just in case it was leftover added dimensions by other mods)

**Comment by Gamebuster19901** [comment]
Wasn't able to reproduce in vanilla.

If I was to guess though, the snowballs are causing the nether to load while MinecraftServer#getWorlds() is being iterated.

It's probably happening here: https://github.com/MinecraftForge/MinecraftForge/blob/ad64d383e1261ef0b6625ce4ecdc15fd974c0b2c/src/main/java/net/minecraftforge/common/DimensionManager.java#L212
