### ISSUE TITLE
[1.14.3] Biome registry event is firing before Feature registry event

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#5940]
**Minecraft Version:** {1.14.3}

**Forge Version:** {27.0.51}

**Logs:** { https://pastebin.com/aRZNLXHE } (another modder's log)

**Description of issue:**
The registration event for Biomes appears to fire before the registration event for Features even though Biomes relies on the existence of the Features. Because of this, Minecraft will throw a NoClassDefFoundError issue.

Currently, this is the Forge comment for the registry which states that because it is going through the registration alphabetically, Biomes will always be registered before Features which is a problem due to biome's reliance on the features.
```
 /**
     * Register your objects for the appropriate registry type when you receive this event.
     *
     * <code>event.getRegistry().register(...)</code>
     *
     * The registries will be visited in alphabetic order of their name, except blocks and items,
     * which will be visited FIRST and SECOND respectively.
     *
     * ObjectHolders will reload between Blocks and Items, and after all registries have been visited.
     * @param <T> The registry top level type
     */
    public static class Register<T extends IForgeRegistryEntry<T>> extends RegistryEvent<T>...
```

The workaround that two other modders in the Discord I'm in have done is to create a public static instance of the feature out side registration, refer to it in the biome classes, and then do normal forge registration afterwards. The other modder decided to just create a new instance of the feature directly in the biome class. 

Hopefully this can be patched soon as I'm still having trouble making my workaround work for this issue.

**Comment by naritanara** [comment]
I'm not sure about it, but I think that you're supposed to add the features on your biomes the way you did (with public static instances), because vanilla Minecraft works the same way.

**Comment by KnightMiner** [comment]
See #5859, Lex does not believe registries should be sorted, he would rather rework the code so they can fire in any order.

**Comment by LexManos** [comment]
Any order, with any number of events missing from the global register events.
The number one issue is how do you decide what order to execute them?
You'd have to have some rather complex sorting system and hope modders dont screw it up.
OR you could do it so that inter-registry objects such as this work on Delegates/Wrappers instead of directly on the registry object. And avoid this entire situation.
