### ISSUE TITLE
Infinite Loop With Missing Block Model

### ISSUE THREAD

**Issue by TheTurkeyDev** [MinecraftForge/MinecraftForge#5941]
**Minecraft Version:** 1.14.3

**Forge Version:** 27.0.51

**Logs:** https://gist.github.com/Turkey2349/69e3ede190881da53b2ff63a98b5ba4e
Video: https://www.twitch.tv/turkey2349/clip/StrangeAuspiciousCucumberBIRB

**Steps to Reproduce:**
Load game with a missing Block model?

**Description of issue:**
when you attempt to load the game with a missing block model, the game infinite loops between the loading screen and the main menu

**Comment by LexManos** [comment]
Update

**Comment by TheTurkeyDev** [comment]
I've Updated to the latest and it still occurs to the same extent

**Comment by LexManos** [comment]
> Forge Version: 27.0.51

That is not the latest. The issue you've described as reported earlier and fixed in https://github.com/MinecraftForge/MinecraftForge/commit/a46b7cb67a903d0d4814a2f563b66daf69c8acb6#diff-d13f368ca489b676f2d809716b955d63R25
