### ISSUE TITLE
Forge does not allow @OnlyIn(Dist.CLIENT) in main mod file?

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#5942]
**Minecraft Version:** 1.14.3

**Forge Version:** 27.0.56

**Logs:** https://gist.github.com/MrIbby/82d19fffa5ce9c45710b06e1a300a4ed

**Steps to Reproduce:**
 1. Set up a Forge server
 2. Install [Ender Compass 2.1.1](https://www.curseforge.com/minecraft/mc-mods/ender-compass/files/2738259)
 3. Start up the server

**Description of issue:**
It seems that Forge can't find this field when instantiating the mod: https://github.com/MrIbby/ender-compass-2/blob/forge/src/main/java/com/github/mribby/endercompass/EnderCompassMod.java#L31-L32

I could fix this on my side, but I thought I should submit an issue here.

**Comment by LexManos** [comment]
You are using ASM hacks wrong. Stop using @OnlyIn
