### ISSUE TITLE
[1.14.3] Inverted symbol in the multiplayer menu

### ISSUE THREAD

**Issue by Da-Technomancer** [MinecraftForge/MinecraftForge#5949]
**Minecraft Version:** 1.14.3

**Forge Version:** 27.0.59

**Logs:** N/A

**Steps to Reproduce:**
Open a vanilla server. Open a forge client, and add the vanilla server. The icon will be inverted.

**Description of issue:**
In the multiplayer menu, the "V" icon that is shown under the server connection strength is drawn upside down (compared to Forge versions for MC1.12.x). 

This is a very minor issue. 

![image](https://user-images.githubusercontent.com/11035641/61545096-a7098e80-aa14-11e9-8390-dcd7b31675d9.png)

**Comment by JoJoDeveloping** [comment]
The upside-down V means vanilla "but may be incompatible".
Is the server in the correct version?

**Comment by Da-Technomancer** [comment]
The server for this screenshot was actually a compatible modded server that was still initializing.

**Comment by GirafiStudios** [comment]
@Da-Technomancer servers that is still starting up have shown up like that as long as the "Old" tag have been a thing in the multiplayer menu. Does also happen for vanilla servers.

**Comment by Da-Technomancer** [comment]
I'm aware- the icon showing up isn't a bug that I'm reporting. What I'm reporting is that the V icon is upside down compared to how it would be rendered normally in earlier versions.

**Comment by Unnoen** [comment]
Using latest Forge (28.1.56) this does not appear to happen. If it is still a problem for you, feel free to reopen this issue.
