### ISSUE TITLE
[1.14.4] Crash on vanilla launcher

### ISSUE THREAD

**Issue by Sunekaer** [MinecraftForge/MinecraftForge#5954]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.2

**Logs:** https://pastebin.com/3zs6qj6u

**Steps to Reproduce:**
 1. Install forge 28.0.2 on the vanilla launcher or twitch launcher
 2. click play
 3. instance crash

**Comment by Virologicbody** [comment]
As above, instant crash..

https://pastebin.com/ww1bwNmh

**Comment by ichttt** [comment]
fixed in 28.0.3 (#5955)

**Comment by Sunekaer** [comment]
Confirmed working in 28.0.3

**Comment by Joe78man** [comment]
Latest I find in https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.14.4.html
is 28.0.22, where is 0.3?

**Comment by LexManos** [comment]
Protip: The number 22 is HIGHER then the number 3.

**Comment by Joe78man** [comment]
Is it?? It never ocurred to me. I was always looking at versions number as if decimals: 0.3 > 0.22
Thanks for the tip, learned something new

**Comment by DaemonUmbra** [comment]
Yeah it's easier to see when it's #.#.# but even when it's just #.# it's two separate numbers.
https://semver.org/
