### ISSUE TITLE
[1.14.3] PlayerEvent.Clone Capability Provider is invalid

### ISSUE THREAD

**Issue by Iuhegi** [MinecraftForge/MinecraftForge#5956]
**Minecraft Version:** 1.14.3

**Forge Version:** 1.14.3-27.0.59

**Logs:** Here is a test mod https://gist.github.com/LukeGi/578a40ba11d60787a4414f10d44dd586

**Steps to Reproduce:**
 1. Use this test mod
 2. do `/kill @p`
 3. Read the log

**Description of issue:**
I'm trying clone my capability when the player dies, but the capability provider on the original player is invalid so the lazy optional returned is empty.

**Comment by gigaherz** [comment]
Can reproduce in 1.14.3 and 1.14.4, by dying from fall height or getting killed by a mob.

**Comment by pau101** [comment]
Repeat of #5869, you can `Entity#revive()` the original player to access its capabilities.
Just as @gigaherz has done here: 

https://github.com/gigaherz/ToolBelt/blob/e2b0994ca7493580dd54699f668bbf2c8b7ba32e/src/main/java/gigaherz/toolbelt/slot/BeltExtensionSlot.java#L182-L186

**Comment by gigaherz** [comment]
That is a workaround, not expected by the code. Forgot to mention it here, since we were discussing that on Discord.

**Comment by juliand665** [comment]
Thanks to the changes in 1bd70ac, this issue is resolved in singleplayer, but it still occurs on dedicated servers, requiring the `revive()` workaround.
