### ISSUE TITLE
[1.14.4] Config data not reloaded

### ISSUE THREAD

**Issue by GoryMoon** [MinecraftForge/MinecraftForge#5959]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4 - 28.0.11

**Steps to Reproduce:**
 1. Change value in config file and save
 2. Get that value from your `ConfigValue` in your `ConfigSpec`
 3. The returned value is unchanged

**Description of issue:**
Data from `ConfigValue` isn't updated after you save the config file. From the sound of it when I asked it should be done.

To get the latest data you need to reload the file manually by using something like below:
```java
@SubscribeEvent
public void onFileChange(ModConfig.ConfigReloading event) {
    ((CommentedFileConfig)event.getConfig().getConfigData()).load();
}
```

Accidentally pressed enter when writing the title so posted it too early.

**Comment by Exidex** [comment]
This was fixed in 81ec8b99ac01c85d9d773395bcabcd47d6f8d07f and can be closed
