### ISSUE TITLE
[1.14.3] Smelting and Blast recipes can return stacksize > 1

### ISSUE THREAD

**Issue by Wabbit0101** [MinecraftForge/MinecraftForge#5960]
Minecraft: **1.14.3**
Forge: **1.14.3-27.0.50**

This might be an oversight on Mojang's part, but the furnace and blast-furnace recipe serializers do not look for "count" information eventhough items are stored as ItemStacks like other recipes. For modded environment this omission is more painful because it breaks older recipe with >1 stack outputs and makes the utility of the new serializers less.

**Comment by LexManos** [comment]
vanilla has never supported more then one output in smelting recipes.
It's something we've patched in for quite a while.
