### ISSUE TITLE
[1.14.4] Unable to /fml confirm console input on windows and linux is not allowed.

### ISSUE THREAD

**Issue by ProsperCraft** [MinecraftForge/MinecraftForge#5963]
> Run the command /fml confirm or or /fml cancel to proceed.
> Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.

**Description of issue:**
The console will not take input, the only option is to add the -Dfml.queryResult=confirm to the start script, this was happening in 1.14.3 as well.

**Minecraft Version:** 1.14.4

**Forge Version:** forge-1.14.4-28.0.13

**Steps to Reproduce:**
 1. Add a mod that adds things to the world
 2. Start the world without that mod.

**Comment by srs-bsns** [comment]
I can not reproduce this with `28.0.13`. Everything seems to be working fine.

I was able to successfully enter the command into both the console and the server GUI.

**Comment by ProsperCraft** [comment]
This is most likely also related to the times where the console doesn't respond to commands, /stop for example, have to log in tot he server, and type /stop from ingame.

This only happens sometimes.

**Comment by 0xilly** [comment]
I can't reproduce this

**Comment by LexManos** [comment]
Nobody is able to reproduce this.
Feel free to reopen if you can find reproduceable steps. But it soundss like a Java/OS issue not sending keystrokes to the window. Not something on our end.

**Comment by ProsperCraft** [comment]
Console goes unresponsive, the problem is intermittent, and I can't reproduce it reliably, I often have to wait for a server save and press Ctrl+c to stop the server or log in and stop it from ingame, but only at times, one of those mods must be breaking something but only intermittently, we will find it down the line someday and this issue will be referenced.

I am the only one reporting it possibly because others are not running full-time servers with lots of players 24/7 with 143 mods.
