### ISSUE TITLE
Mod setup deadlock by event static initialization and acquired listener list read lock

### ISSUE THREAD

**Issue by pau101** [MinecraftForge/MinecraftForge#5965]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.13

**Logs:** [Stacktraces of deadlocked threads](https://gist.github.com/pau101/b4580fc3dee2abe41b9f3726443acdcd)

**Steps to Reproduce:**
 1. Setup userdev environment or run game launcher
 2. Run client
 3. Game freezes during mod setup, else repeat steps 1-3

**Description of issue:**

Any register to the forge event bus for any event type of `TickEvent` during mod setup creates a race condition of either succeeding registration or locking the game up. Forge has an event subscriber internally which does so, [ForgeInternalHandler](https://github.com/MinecraftForge/MinecraftForge/blob/ae3d002ac626b86234f71084ec23f744b6205d09/src/main/java/net/minecraftforge/common/ForgeInternalHandler.java#L72-L83), and any additional mod subscribers increase the likelihood of this deadlock.

The aforementioned stacktrace logs taken from a thread dump during the deadlock show a modloading worker thread was in the process of registering `ForgeInternalHandler` listeners to client and server tick events. The thread obtained the read and write lock for [EventListenerHelper.getListeners](https://github.com/MinecraftForge/EventBus/blob/1a5fa312249baa0904c3ae34c35abb19f6158ec2/src/main/java/net/minecraftforge/eventbus/api/EventListenerHelper.java#L59-L67) and was in the process of [instantiating the event](https://github.com/MinecraftForge/EventBus/blob/1a5fa312249baa0904c3ae34c35abb19f6158ec2/src/main/java/net/minecraftforge/eventbus/api/EventListenerHelper.java#L90-L91) to access its listener list.

Meanwhile, the main client thread was in the process of firing `TickEvent.ClientTickEvent`, and as it was the first need of this class, static initialization was started. The static initialization of this class includes the inserted code by [EventSubclassTransformer](https://github.com/MinecraftForge/EventBus/blob/1a5fa312249baa0904c3ae34c35abb19f6158ec2/src/main/java/net/minecraftforge/eventbus/EventSubclassTransformer.java#L162-L167). As such, the thread also attempts to acquire the read lock for `EventListenerHelper.getListenerList` and subsequently finds itself waiting indefinitely.

This deadlock was introduced by this change to eventbus: https://github.com/MinecraftForge/EventBus/commit/6ffc87b4757ae23ba1f29d1311e05fcfe355d74f

There is the potential for this issue to occur with anything that causes any event class to start static initialization on the main client thread or any other modloading thread.

**Comment by ichttt** [comment]
IIRC you should not lock a read lock when you hold a write lock, as the write lock makes sure no read locks are present.

**Comment by cpw** [comment]
We know there's a race in the eventbus. First construction of an Event type is a source of potential deadlocks.

**Comment by cpw** [comment]
Should have been fixed with the latest eventbus release.

https://github.com/MinecraftForge/EventBus/commit/aa7cc33fdb88f7f1f55f0eedbf6f942c008ea0b2
