### ISSUE TITLE
Game crash on FarmlandWaterManager

### ISSUE THREAD

**Issue by tostamista23** [MinecraftForge/MinecraftForge#5966]
**Minecraft Version:** 1.12.2
**Forge Version:** 1.12.2-14.23.5.2836

**Logs:** https://pastebin.com/Bti36Fn4

**Description of issue:** https://github.com/Buuz135/Industrial-Foregoing/issues/581

**Comment by ichttt** [comment]
Yeah, this is known, I already proposed a fix in #5861, just waiting for the 1.12.2 maintainers to review...

**Comment by bl4ckscor3** [comment]
The PR by ichttt was merged, this can be closed.
