### ISSUE TITLE
makeObfSourceJar undefined in build.gradle

### ISSUE THREAD

**Issue by AlexModGuy** [MinecraftForge/MinecraftForge#5967]
Minecraft Version: 1.14.4

Forge Version: 28.0.13

Steps to Reproduce:
`    // Simply re-run your setup task after changing the mappings to update your workspace.
    mappings channel: 'snapshot', version: '20190719-1.14.3'
    // makeObfSourceJar = false // an Srg named sources jar is made by default. uncomment this to disable.
`

to

`    // Simply re-run your setup task after changing the mappings to update your workspace.
    mappings channel: 'snapshot', version: '20190719-1.14.3'
    makeObfSourceJar = false // an Srg named sources jar is made by default. uncomment this to disable.
`

Description of issue:
makeObfSourceJar is commented out (and has text above it to uncomment it to enable a deobf jar). doing so(in order to get a deobf jar) results in an error.

in build.gradle in a new project

**Comment by LexManos** [comment]
1) That's not how you add extra arguments to things
2) That part needs to be deleted that is no longer a feature and you shouldn't be publishing a 'deobfed' jar/source. As FG makes that for you.

**Comment by ChrisLane** [comment]
@LexManos The comment for `makeObfSourceJar` is still there. Perhaps this was forgotten?
https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/mdk/build.gradle#L29
