### ISSUE TITLE
Typo in MDK build.gradle

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#5970]
https://github.com/MinecraftForge/MinecraftForge/blob/61bea2b/mdk/build.gradle#L123

**Comment by Gamebuster19901** [comment]
What is the typo? The space after `-Vendor"`?

If so then that shouldn't cause any problems...

**Comment by DaemonUmbra** [comment]
One for the Omnibus

**Comment by LexManos** [comment]
Not a typo
