### ISSUE TITLE
[1.14.4] Slimes not splitting

### ISSUE THREAD

**Issue by Krappa322** [MinecraftForge/MinecraftForge#5973]
**Minecraft Version:** 1.14.4
**Forge Version:** 28.0.13

**Steps to Reproduce:**
 1. Spawn a slime
 2. Kill the slime

**Description:**
Very simple. Slimes never split. Not in single player and not in multiplayer. Using same vanilla version they split just fine.

Multiplayer test had no mods installed other than forge.
Singleplayer test had HWYLA and forge installed.

**Comment by zeavic** [comment]
how do you use this

**Comment by LexManos** [comment]
Update your Forge version to a version that has this commit.

**Comment by LiamStockwell** [comment]
I'm running a server with just,  MINECRAFT FORGE 1.14.4 (28.1.22), Still getting this issue, got any ideas that'll help as i thought it patch should have been in the update for a while.
don't know if it will matter but when we started the server we were on an early version. 

and yeah, only just got round to attempting a slime farm.
