### ISSUE TITLE
[1.14.3] Recipe _constants.json not being loaded

### ISSUE THREAD

**Issue by Wabbit0101** [MinecraftForge/MinecraftForge#5974]
**Minecraft Version:** 1.14.3

**Forge Version:** forge:1.14.3-27.0.50

**Steps to Reproduce:**
 1. Define a _constants.json and put in <mod_id>/recipes data directory
 2. Use a constant in a recipe definition

**Description of issue:**
Any recipe using a constant is flagged as not loadable due to missing "constant". 
Review of logs shows _constants.json trying to be loaded as a recipe definition. 
Review of code shows no reference to the function "CraftingHelper::reloadConstants(r)" but this could be due to my potato Eclipse IDE search limits...

Just to double-check, I intentionally put in a broken json syntax in the _constants.json (should've thrown an error from reloadConstants)...nuthin' happened (same errors)

Example _constants.json and recipe here: https://pastebin.com/XqDdiSY3

Example error in log:

> com.google.gson.JsonSyntaxException: Ingredient referenced invalid constant: vanillafoodpantry:portion_large_water

**Comment by KnightMiner** [comment]
Is constants still needed in 1.14? I wonder if there is anything they do that cannot be replaced with tags. Only case I can think of that might be different is the constanrs conditions which last I checked don't exist for tags

**Comment by GirafiStudios** [comment]
Constants is not used anymore. You need to register your conditions with CraftingHelper#register.
Also this should have gone on the forums.

**Comment by Wabbit0101** [comment]
I thought constants were being used for things like:
```
  {
    "name": "portion_large_heat",
    "item": {
      "type": "carrots:filled_bucket",
      "fluid": "lava",
      "mod_bucket": "#carrots:portions_large_heat"
    }
  }
```

_This is not a recipe condition_, it's a utility for complex ingredient declarations that are a royal pain to copy into dozens and dozens of recipes. Furthermore, what the constants definition is as defined in 1.14.x's code is different to its 1.12 version and the code IS present and called as recipes are read in -- the initial file loader is just never called (see CraftingHelper), but the use of constants seems as if the intent was to be be used. 

If constants are not supported (in the 1.14 form -- not the 1.12 one), then I can close this issue.

**Comment by GirafiStudios** [comment]
I thought you were referring to the recipe condition on line 33, my bad.

**Comment by LexManos** [comment]
With the introduction of in-code data generators. {The Data run config} constant files are no longer needed.
So... Build your recipes with data generators.
It'll be nice to not have to deal with yet another hacky system on top of vanilla's stuff.
