### ISSUE TITLE
PlayerInteractEvent.RightClickBlock and PlayerInteractEvent.RightClickItem events not working

### ISSUE THREAD

**Issue by henkelmax** [MinecraftForge/MinecraftForge#5975]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.1 - 28.0.18

**Steps to Reproduce:**
 1. Subscribe to the `PlayerInteractEvent.RightClickBlock` event
 2. Subscribe to the `PlayerInteractEvent.RightClickItem` event

**Description of issue:**

The `PlayerInteractEvent.RightClickBlock` and the `PlayerInteractEvent.RightClickItem` event is not working.
I think the problem lies in the `PlayerInteractionManager` class.

The following lines existed in the code [prior to the 1.14.4](https://github.com/MinecraftForge/MinecraftForge/commit/eff42f6066673db0c4e12e1c1e18a98ec1e9c0a2) update:

https://github.com/MinecraftForge/MinecraftForge/blob/eff42f6066673db0c4e12e1c1e18a98ec1e9c0a2/patches/minecraft/net/minecraft/server/management/PlayerInteractionManager.java.patch#L171-L172

https://github.com/MinecraftForge/MinecraftForge/blob/eff42f6066673db0c4e12e1c1e18a98ec1e9c0a2/patches/minecraft/net/minecraft/server/management/PlayerInteractionManager.java.patch#L150-L151

After the 1.14.4 update they don't exist anymore.

**Comment by LexManos** [comment]
Known deleted patch in 1.14.4. The area we patched got completely revamped by Mojang and our system no longer applies.
Same goes for block snapshots and the like.
If anyone wants to take a look and redesign it go a head.
