### ISSUE TITLE
TileEntity registry event sometimes does not fire

### ISSUE THREAD

**Issue by ercanserteli** [MinecraftForge/MinecraftForge#5981]
**Minecraft Version:** 1.13.2

**Forge Version:** 25.0.219

**Logs:** https://gist.github.com/ercanserteli/3c1a3c9faa625f6aece13e738aaa93e4

**Steps to Reproduce:**
 1. Start a server
 2. Join it
 3. If you are unlucky, the event did not fire and all of the precious tile entity data got deleted on world load because they were unregistered.

**Description of issue:**
The TileEntity registry event with the argument of type RegistryEvent.Register<TileEntityType<?>> sometimes is not fired. I verified this by putting a log on the first line of the event handler that prints "Registering tile entities". In the log files I provide you can see two start ups of the exact same server with the same world and mods, except in one of them the event is fired and in the other one it is not. Blocks and items were registered normally in both runs. The register event not firing results in "Skipping BlockEntity with id  ..." warnings during loading and "class ... is missing a mapping! This is a bug!" errors during play.

I could not find out the reason for this as it seems to be a rare occuracance, and I only encountered it on a remote server. However, after only happening once, the loaded blocks that have associated tile entities seem to get their data deleted, so it causes a permanent problem. 

I do not know if it only happens on a dedicated server but I never encountered it on single player.

**Comment by Tfarcenim** [comment]
stop using 1.13

**Comment by cpw** [comment]
Yup. This was a known problem with the eventbus in highly concurrent situations, since resolved. Update to 1.14.4.

**Comment by ercanserteli** [comment]
I wanted to delay updating to 1.14 until it is stable since I'm still suffering PTSD from updating 1.9 to 1.13 a few months ago. It is sad to see Forge straight up abandoning a perfectly fine, major version of Minecraft. Good to know that it is fixed in the newer versions.

**Comment by LexManos** [comment]
1.13 was always going to be a stepping stone. This was known and stated when we decided to spend the time to re-write everything.
Beyond that, you should always be working towards the current version of Minecraft. No reason to pick arbitrary versions that you like.

And ESPECIALLY no reason to complain that something isn't working if you're not using the latest version.
