### ISSUE TITLE
ModConfig.Type.SERVER saves to world instead of config

### ISSUE THREAD

**Issue by raziel23x** [MinecraftForge/MinecraftForge#5982]
**Minecraft Version:** {Minecraft version}
1.14.4
**Forge Version:** {Forge version. *Version number, not latest/rb*}
forge-1.14.4-28.0.20
**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**
Server configs are saved inside world folder inside save folder instead of config folder making creating modpacks impossible to modify server files

**Comment by cpw** [comment]
Nope. this is by design. Server configs are _specific_ to the server. They have to be saved as part of the server. defaultconfigs have been added that can supply defaults for a server at creation time.
