### ISSUE TITLE
[1.14.3] Use tags as a resource location path

### ISSUE THREAD

**Issue by artillect** [MinecraftForge/MinecraftForge#5988]
I've been working on making a resource pack with mod support, and I thought it'd be really useful if you could use an item or block's tag in a resource pack. For example, instead of the path being /assets/foo/block/iron_ingot.png, it could be /assets/oredictionary/block/ingotIron.png. This would help people creating resource packs for modpacks a lot.

**Comment by liach** [comment]
vanilla no longer supports uppercase letters in resource locations since 1.11, and ore dictionary has been removed in favor of tags.

**Comment by artillect** [comment]
I've edited my suggestion a little bit, I don't see why you couldn't just use the lowercase versions of tags in the resource names. And sorry, I didn't realize that the oredictionary has been phased out in favor of tags.

**Comment by LexManos** [comment]
This has nothing to do with tags. What I *think* you're asking for, is a common place to share assets.. I mean there isn't anything stopping you from doing this. Just picking a namespace that everyone can share. 

As for people making resource packs for mods, the models define the texture location so they can share textures however much they want.
