### ISSUE TITLE
[1.14.4] IForgeItem#initCapabilities called before Capabilities are registered

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#5989]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.19

**Logs:** https://gist.github.com/Choonster/2ee4d06856ca409f85b89728e9ddd47e

**Code:** https://github.com/Choonster-Minecraft-Mods/TestMod3/tree/ba1306dd180514cc7dd135b21262f8eb72cdd305

**Description of issue:**
After updating to 1.14.4 and attempting to run the client (the first time since updating to 1.14), I encountered a crash due to [`LastUseTimeModelItem#initCapabilities`](https://github.com/Choonster-Minecraft-Mods/TestMod3/blob/ba1306dd180514cc7dd135b21262f8eb72cdd305/src/main/java/choonster/testmod3/item/LastUseTimeModelItem.java#L38-L41) being called when [`LastUseTimeCapability.LAST_USE_TIME_CAPABILITY`](https://github.com/Choonster-Minecraft-Mods/TestMod3/blob/ba1306dd180514cc7dd135b21262f8eb72cdd305/src/main/java/choonster/testmod3/capability/lastusetime/LastUseTimeCapability.java#L33-L37) was still `null`.

It appears that an `ItemStack` of this `Item` is being created in `Minecraft#populateSearchTreeManager`, which is called towards the end of `Minecraft#init`. `ClientModLoader.begin` is called earlier in `Minecraft#init` to start loading mods, but this doesn't actually fire `FMLCommonSetupEvent` (the event that Capabilities are registered in) directly; instead it registers a resource reload listener that fires the event (and the other setup events). The initial reload that calls this listener doesn't happen until the very end of `Minecraft#init` (after `Minecraft#populateSearchTreeManager`).

It feels counter-intuitive that `IForgeItem#initCapabilities` can be called before Capabilities have actually been registered, but is this a bug or is it intended behaviour?

I originally reported this on the [forums](https://www.minecraftforge.net/forum/topic/73665-1144-iforgeiteminitcapabilities-called-before-capabilities-are-registered/), but I thought it's probably worth reporting here.

**Comment by LexManos** [comment]
Register your cap in your constructor and hope it is called before anything anywhere creates a ItemStack.
Since that's not feasible in a multithreaded world, better solution, add null protection to your createProvider code.

**Comment by Choonster** [comment]
It's not ideal, but that will have to do. Thanks.

**Comment by Choonster** [comment]
It turns out that the constructor of the `@Mod` class is too early to call `CapabilityManager#registerCapability` as it uses the `CapabilityManager#callbacks` map, but this is only initialised between `RegistryEvent.NewRegistry` and `RegistryEvent.Register` being fired.

Due to this, I kept the capability registration in `FMLCommonSetupEvent` and just added `null` protection to the `IForgeItem#initCapabilities` implementations. This fixed the crash.

**Comment by DietmarKracht** [comment]
public ICapabilityProvider initCapabilities(ItemStack stack, @Nullable CompoundNBT nbt) {
        return YOUR_CAPABILITY!= null ? new YourCapability.Provider() : null;
    }

**Comment by josephtarbit** [comment]
There's cases where this isn't viable, for example when Minecraft loads its item search tree. I've had to use the unpleasant solution of registering the capabilities in the static initializer of my capability class.

**Comment by DietmarKracht** [comment]
YOUR_CAPABILITY is an instance of your capability. It is important to register these at the FMLCommonSetupEvent otherwise the CapabilityManager might not be present. At least the callback object will be null if registering the capabilities at first before registering anything else.
