### ISSUE TITLE
[1.14.4] missing feature: player.changeDimension with teleporter argument

### ISSUE THREAD

**Issue by RobertSkalko** [MinecraftForge/MinecraftForge#5990]
Needed because you want to be able to teleport players without spawning a portal. (in my mod, the teleport location is different based on certain factors so if i spawned portals, they'd be everywhere)

I made my own by ATing some fields and deleting the portal code but its prone to errors. I think 1.12.2 had this feature with ITeleporter argument.

**Comment by LexManos** [comment]
It did, but it was a massive amount of patches that did not port correctly.
The entire ITeleporter system needs a redesign.
Feel free to discuss and PR replacement with usecases.

**Comment by Hugman76** [comment]
I think that while ITeleporter surely needs a redesign, we should definitely bring the missing argument back for the time being.
