### ISSUE TITLE
Custom Entities not obeying max entity limit per chunk in Swamp Biomes

### ISSUE THREAD

**Issue by SmellyModder** [MinecraftForge/MinecraftForge#5991]
Minecraft Version: 1.14.4

Forge Version: 28.0.24

Steps to Reproduce:
 1. Add an entity to spawn in any biome
 2. Give it a spawn cap of anything per chunk
 3. It will not obey the spawn cap and will spawn tons over time

**Comment by SmellyModder** [comment]
I could only reproduce this in swamps biomes*

**Comment by LexManos** [comment]
Explain better, there is no per chunk spawn limit. It's global. Provide code/example.

**Comment by SmellyModder** [comment]
Turns out it was a mod doing it. I'll close this, sorry for the inconvenience
