### ISSUE TITLE
Add the DamageSource as a member of LivingKnockBackEvent and change its call position

### ISSUE THREAD

**Issue by RaycusMX** [MinecraftForge/MinecraftForge#5994]
Cannot get the immediate damage source from LivingKnockBackEvent currently. Only the true source. So I'd like to have the DamageSource object as a member of LivingKnockBackEvent. In this case the event should be called before the invoking of **knockback** method in **attackEntityFrom** of EntityLivingBase.

This would allow modders to determine whether to knockback or not according to the type of the projectile.

**Comment by diesieben07** [comment]
Like I already told you on discord: `attackEntityFrom` is not the only place `knockBack` is called from. `knockBack` is even public, any random mod can call it at any time.

**Comment by RaycusMX** [comment]
> Like I already told you on discord: `attackEntityFrom` is not the only place `knockBack` is called from. `knockBack` is even public, any random mod can call it at any time.

ok. i didn't understand your meaning. sorry about that.
