### ISSUE TITLE
IForgeBlock#getPickBlock calls Block#getItem but is not marked as client side only

### ISSUE THREAD

**Issue by MajorTuvok** [MinecraftForge/MinecraftForge#5995]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.27

**Logs:** [a crash report from an user](https://pastebin.com/Phy17W0J). Related issue is Direwolf20-MC/BuildingGadgets#336

**Steps to Reproduce:**
 1. Call `IForgeBlock#getPickBlock` (which calls through to `IForgeBlock#getItem(World, BlockPos, BlockState)`) on a dedicated Server with some Block that does not override this Method
 2. Watch it die, because of `NoSuchMethodError`

**Description of issue:**
`IForgeBlock#getPickBlock`  seems to be callable both on Server and Client, but because it calls a Client only Method it dies Server Side. Checking whether it is called on the Server and running some other default behaviour would for example be a fix, or marking it as `@OnlyIn` as well. I don't know what would be the apropiate way to do it here...
Also, is this Method even needed, now that we have LootTables everywhere?

**Comment by LexManos** [comment]
Awesome, this introduces 18 patches. 
We need a better system to remove the Sided-ness of things more generically.
Perhaps something like an AccesssTransformer, that allows build time removal.
It would need to force the extra binary patches when there are no corresponding .patch file.
