### ISSUE TITLE
[1.14.4] Mod List GUI size

### ISSUE THREAD

**Issue by Hallowizer** [MinecraftForge/MinecraftForge#5996]
**Minecraft Version:** 1.14.3

**Forge Version:** 27.0.60

**Logs:** https://pastebin.com/a28sNcWN {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Load forge
 2. Open the mods screen

**Description of issue:**
The mod description area is very short when forge is launched normally, but it is fine in the dev workspace.

<img width="1920" alt="Screen Shot 2019-07-31 at 10 23 52 PM" src="https://user-images.githubusercontent.com/40325350/62267742-210d2080-b3e2-11e9-96c8-19176873058c.png">

**Comment by LexManos** [comment]
Closed for being way out of date.
