### ISSUE TITLE
Swamp Trees Underwater

### ISSUE THREAD

**Issue by fivelol** [MinecraftForge/MinecraftForge#6000]
Swamps generate trees underwater when forge is installed, this happens with no mods present, but not with vanilla Minecraft. For the following screenshots, I used vanilla Minecraft 1.14.4 and forge 28.0.29.

https://imgur.com/a/zCaXfqw

**Comment by fivelol** [comment]
Don't know if that label was added automatically or if I did, apologies in advance

**Comment by pau101** [comment]
I've been seeing this as well.

It appears to be from the patch to `isAirOrLeaves` to call `canBeReplacedByLeaves`:
https://github.com/MinecraftForge/MinecraftForge/blob/318fc6ffe8365b34170b0e4a01a73f08af4e0589/patches/minecraft/net/minecraft/world/gen/feature/AbstractTreeFeature.java.patch#L32-L38

And there appears to be a logical error in the default implementation, given the parentheses it looks like it was intended to be `(air || leaves) && !opaque`, however I would find this opaque check inappropriate regardless.
https://github.com/MinecraftForge/MinecraftForge/blob/318fc6ffe8365b34170b0e4a01a73f08af4e0589/src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java#L366-L369

**Comment by LexManos** [comment]
Reviewing the places this is called from, seems vanilla removed the opaque check in 1.13.
So yes it'd need to have the default implementation adjusted.
Note: It's not only called from that one location.
