### ISSUE TITLE
[1.14.4] Carriage return character shown in mod descriptions.

### ISSUE THREAD

**Issue by JustPyrrha** [MinecraftForge/MinecraftForge#6002]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.29

**Steps to Reproduce:**
 1. Using a text editor that inserts carriage return characters, create a multi-lined mod description. (mods.toml)
 2. Run Minecraft.
 3. Open mods list and click on your mod.
4. The description should have little "CR" icon/char at the end of each line.

**Description of issue:**
Some text editors add a carriage return character at the end of a line where there's another line below it which Minecraft renders as a visible character in text (screenshot below).

![Screenshot](https://i.imgur.com/qtqJz3P.png)

**Comment by DaemonUmbra** [comment]
I don't get this symbol and I think this should have passed through the forums first.

**Comment by JustPyrrha** [comment]
Was told to post here from Discord

**Comment by LexManos** [comment]
Welcome to the world on Minecraft text rendering. It does not split lines based on CR, just LF.
