### ISSUE TITLE
[1.14.4] Config inconsistency [Invalid] [Moved to forums]

### ISSUE THREAD

**Issue by F43nd1r** [MinecraftForge/MinecraftForge#6004]
`ForgeConfigSpec.get(s)` behaves differently from `ForgeConfigSpec.ConfigValue.get()`.
The former calls through to `ForgeConfigSpec.config`, while the latter calls `ForgeConfigSpec.childConfig`.

I would expect both to behave the same and call to `ForgeConfigSpec.childConfig`.

**Comment by LexManos** [comment]
No they shouldn't. As the ConfigSpec.config is the Config Spec. So calling get on it will return the ValueSpec of the config.
Where ConfigValue is specifically designed to get the REAL value.
Should probably not expose get. No reason anyone should need access to those values.

**Comment by F43nd1r** [comment]
So how do I retrieve a real value without the ConfigValue object?

**Comment by LexManos** [comment]
With the ConfigValue object.

**Comment by F43nd1r** [comment]
I don't have that in a `IConditionSerializer`. Having to build my own registry for ConfigValue objects seems undesirable.

**Comment by LexManos** [comment]
http://xyproblem.info/
Move to the forums or discord and dig into the real issue. Not here.

**Comment by F43nd1r** [comment]
Moved to https://www.minecraftforge.net/forum/topic/74070-1144-get-config-in-iconditionserializer/
