### ISSUE TITLE
[1.14.4] Search Tree should be populated after config load

### ISSUE THREAD

**Issue by F43nd1r** [MinecraftForge/MinecraftForge#6006]
As discussed here https://www.minecraftforge.net/forum/topic/74068-1144-disabling-blockitems-based-on-configuration/?tab=comments#comment-355585, the creative search tree should be populated after mod configurations were loaded.

**Comment by LexManos** [comment]
They are loaded at startup, and then reloaded again after data packs are loaded.

**Comment by F43nd1r** [comment]
Alright, idk whats going on here. One guy tells me to create an issue, the other closes it instantly.

As Animefan8888 noted, this is a real issue: I shouldn't have to call `populateSearchTreeManager` after the `ModConfig.ModConfigEvent`.
