### ISSUE TITLE
[1.14.4] Crafting recipes sometimes choose a less specific item tag recipe over one that requires a specific item.

### ISSUE THREAD

**Issue by SilverDavidMC** [MinecraftForge/MinecraftForge#6022]
**Minecraft Version:**
1.14.4

**Forge Version:**
28.0.45

**Logs:**
None to provide as no console errors are produced. However here is an [imgur album](https://imgur.com/a/JZHKgEm) showing the crafting in action, with the item tag and recipe files.
Worth noting I did test this in vanilla 1.14.4 using 20 different recipes that work the same as these with no issues.

**Steps to Reproduce:**
 1. Create an item with a mod.
 2. Tag the item under "minecraft:items/planks"
 3. Make a recipe that uses your item that's in the same shape as a chest, but produces something different than a chest.
 4. Sometimes it will create a chest using the item tag "minecraft:planks" while other times it creates what your recipe told it to make with your item. It's rather inconsistent as to what will trigger this.

**Description of issue:**
When making two crafting recipes where one uses an item tag and the other uses an item in said tag, with both being the same shape, it sometimes prioritizes the less specific "tag" recipe. In my case, I'm making different wood types for chests by using different planks. Let's say I have a recipe that says the item "my_mod:planks" in the shape of a chest recipe creates a spruce chest. "my_mod:planks" is also included in the "minecraft:planks" item tag. In some cases, the recipe will look at the less specific vanilla chest recipe that requires anything in the item tag "minecraft:planks" instead of the more specific recipe using "my_mod:planks", and as such produce the wrong output.

**Comment by Shadows-of-Fire** [comment]
The inconsistency is unusual, but this is (by definition) a recipe conflict.  It is not supported behavior.
