### ISSUE TITLE
CropsBlock.getSeedsItem is client-side only

### ISSUE THREAD

**Issue by TheLimePixel** [MinecraftForge/MinecraftForge#6024]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.45

**Description of issue:**
 `getSeedsItem` in `CropsBlock` (and all its child classes) is a client-side only method. Aside from this generally being useful for getting which seed item is used for planting a crop, it causes the issue where it's used in `getItem` which isn't client-only.

**Comment by Draco18s** [comment]
PR #6013 fixes this and got merged in last night.
This issue is now resolved.
