### ISSUE TITLE
TransformingClassLoader fails to load Resources via getResources outside of Eclipse

### ISSUE THREAD

**Issue by Adrodoc** [MinecraftForge/MinecraftForge#6029]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4-28.0.45

**Steps to Reproduce:**
See <https://github.com/Adrodoc/minecraft-forge-6029-reproducer>.
 1. `git clone https://github.com/Adrodoc/minecraft-forge-6029-reproducer.git`
 2. `gradlew reobfJar`
 3. Copy the jar file `build/libs/modid-1.0.jar` into a forge server mod dir

**Description of issue:**
The Mod-ClassLoader (TransformingClassLoader) always returns an empty enumeration for [getResources(String)](https://github.com/Adrodoc/minecraft-forge-6029-reproducer/blob/master/src/main/java/com/example/examplemod/ExampleMod.java#L35) when running outside of Eclipse. If the mod is run from Eclipse using the run configuration generated by `gradlew genEclipseRuns` then it works fine. Using the method `getResource` also works fine.
I suspect the issue stems from the fact that TransformingClassLoader overrides [`findResource(String)`](https://github.com/cpw/modlauncher/blob/3.2.0/src/main/java/cpw/mods/modlauncher/TransformingClassLoader.java#L143-L146), but not `findResources(String)`, but I have no idea why it works when started from Eclipse.

**Comment by Adrodoc** [comment]
Related to #5713.

**Comment by Adrodoc** [comment]
By the way this completely prevents mods from using java's [ServiceLoader mechanism](https://docs.oracle.com/javase/8/docs/api/java/util/ServiceLoader.html).

**Comment by cpw** [comment]
Not a forge issue. I'll move this to modloader project.

**Comment by Adrodoc** [comment]
> Not a forge issue. I'll move this to modloader project.

@cpw I can't find a corresponding issue there. Was this forgotten?
