### ISSUE TITLE
GetCollisionBoxesEvent is never fired

### ISSUE THREAD

**Issue by Tfarcenim** [MinecraftForge/MinecraftForge#6033]
Minecraft version : 1.14.4
Forge version : 28.0.45

**Steps to Reproduce:**
 1. Subscribe to GetCollisionBoxesEvent
 2. It doesn't fire at all

**Description of issue:**
One of my mods relied on it to make a walk on fluids effect, but when porting it to 1.14.4 it doesn't work correctly because of the missing event

**Comment by srs-bsns** [comment]
After a quick look, it appears the new target of this event should likely be `net.minecraft.world.IWorldReader#getCollisionShapes(Entity, AxisAlignedBB)` which returns a `Stream<VoxelShape>`
The event could be changed to accept the stream instead of a `List<AxisAlignedBB>`.
