### ISSUE TITLE
[1.14.4] Null pointer exception thrown when two mods inject same loot table

### ISSUE THREAD

**Issue by cweckerl** [MinecraftForge/MinecraftForge#6034]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.45

**Logs:** https://pastebin.com/TFvAwy73

The two mods I am testing both inject the vanilla grass loot table to have more drops. However, this causes a null pointer exception to be thrown and the block loot table to be unparsable.

**Comment by noobanidus** [comment]
I believe this stems from the `name` parameter of the builder not being called on the loot table itself; despite the fact that Forge tests `pool.getName().equals` it doesn't test to see whether the name is null or not -- and passing a non-null table name does not appear to be a requirement as there is no error thrown for failing to do so.
