### ISSUE TITLE
Wrong parameter names in gui Button class

### ISSUE THREAD

**Issue by Draco18s** [MinecraftForge/MinecraftForge#6039]
This is against Forge 1.14.4 build 28

The button class takes in 4 int parameters as its first four parameters:

    Button(int widthIn, int heightIn, int p_i51141_3_, int p_i51141_4_, ...);

It passes these to super:

    super(widthIn, heightIn, p_i51141_3_, p_i51141_4_, text);

Which has this signature:

    public AbstractButton(int xIn, int yIn, int widthIn, int heightIn, String msg)

I am pretty sure that `p_i51141_3_` is actually `widthIn` and `widthIn` is actually `xIn` (ditto height and y).

**Comment by LexManos** [comment]
https://github.com/ModCoderPack/MCPBot-Issues/issues

**Comment by Draco18s** [comment]
Thanks Lex, I didn't even know they had a git repo.
