### ISSUE TITLE
Items with multiple item states don't change texture in hotbar

### ISSUE THREAD

**Issue by inboundbark** [MinecraftForge/MinecraftForge#6044]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.45

**Steps to Reproduce:**
 1. Pull bow back
 2. Look at bow in hotbar
 3. compare with vanilla minecraft

**Description of issue:**
Items like the bow, crossbow, or fishing rod stay as their default texture even when they are pulled back or the fishing line is cast. Especially noticable with the crossbow, where it stays completely static in the hotbar as opposed to the hand.

**Comment by inboundbark** [comment]
![image](https://user-images.githubusercontent.com/50455200/62938920-51848f80-bdd0-11e9-902d-5824cda23af7.png)

Here you can see the crossbow is pulled back but the hotbar stays static./

**Comment by LexManos** [comment]
![](http://puu.sh/E5z1Y/476968a36c.jpg)
Not reproducible.
