### ISSUE TITLE
[1.14] Cancelling block breaking (InteractEvent) causes movement issues

### ISSUE THREAD

**Issue by Aeltumn** [MinecraftForge/MinecraftForge#6048]
I'm investigating this and will PR when I find a solution or when someone else finds it but doesn't want to make a PR.

**Steps to reproduce**
1) Have an PlayerInteractEvent.LeftClickBlock event.
2) setCancelled(true);
3) (optional) Turn on view bobbing, it makes the effect clearer.
4) Press left click, hit a block, and keep the button pressed.

If these steps work for you the same way it works for me, you'll notice movement is broken. It's completely broken for me, if I keep left click pressed I can't move at all.

Here's the code:
```java
@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.FORGE)
public class Test {
    @SubscribeEvent
    public static void onInteract(PlayerInteractEvent.LeftClickBlock e) {
       e.setCanceled(true);
    }
}
```

This also happens if an item cancels onBlockStartBreak or through any other method of cancelling block breaking. (except #6047, that one doesn't have this problem)

EDIT: This is probably a problem on the server-side, because logging in to a vanilla server with a forge client cancelling the event works fine.

EDIT2: This has been mentioned before in https://github.com/MinecraftForge/MinecraftForge/pull/5976#issuecomment-515775586, but I do feel that this needs to be addressed. I don't mind writing a PR to sort it out.

**Comment by GotoLink** [comment]
Going through the process, i think the issue is a cancelled left click on server side sends back a restoration "PlayerDigging" packet to the client, which ultimately calls PlayerController#func_225323_a where player.setPositionAndRotation is called.
Not sure what purpose setting back the player serves in this case.
Assuming we want to keep that function, i suppose updating the field_225326_k more accurately would be the way to go. Either with timestamp or a different DiggingPacket.Action value.

**Comment by Aeltumn** [comment]
Looking at the code it does indeed appear to be the method you described. Whenever the server cancels the digging it responds with a SPlayerDiggingPacket with the same action as the CPlayerDiggingPacket it received. And the client then fixes the player's location if the returned action was not START_DESTROYING_BLOCK. This would make it appear as if the server needs to respond with Action.ABORT_DESTROYING_BLOCK whenever the result is false. Though the vanilla code doesn't do this? I'll make a PR which makes the methods which cancel the breaking to return ABORT_DESTROYING_BLOCK but it might break vanilla somehow.

**Comment by Aeltumn** [comment]
See #6050 for more information, deemed a vanilla issue and not up to forge to fix.
