### ISSUE TITLE
Item selection base is not separated from main distribution

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#6049]
&#x3C;&#x21;&#x2D;&#x2D;&#x20;&#x54;&#x68;&#x61;&#x6E;&#x6B;&#x20;&#x79;&#x6F;&#x75;&#x20;&#x66;&#x6F;&#x72;&#x20;&#x72;&#x65;&#x70;&#x6F;&#x72;&#x74;&#x69;&#x6E;&#x67;&#x21;&#x20;&#x2D;&#x2D;&#x3E;<br/><br/>&#x3C;&#x21;&#x2D;&#x2D;&#x20;&#x46;&#x6F;&#x72;&#x20;&#x73;&#x75;&#x70;&#x70;&#x6F;&#x72;&#x74;&#x20;&#x77;&#x69;&#x74;&#x68;&#x20;&#x63;&#x72;&#x61;&#x73;&#x68;&#x65;&#x73;&#x20;&#x61;&#x6E;&#x64;&#x20;&#x69;&#x73;&#x73;&#x75;&#x65;&#x73;&#x2C;&#x20;&#x70;&#x6C;&#x65;&#x61;&#x73;&#x65;&#x20;&#x63;&#x72;&#x65;&#x61;&#x74;&#x65;&#x20;&#x61;&#x20;&#x70;&#x6F;&#x73;&#x74;&#x20;&#x6F;&#x6E;&#x20;&#x74;&#x68;&#x65;&#x20;&#x66;&#x6F;&#x72;&#x75;&#x6D;&#x20;&#x69;&#x6E;&#x73;&#x74;&#x65;&#x61;&#x64;&#x3A;&#x20;&#x2D;&#x2D;&#x3E;<br/>&#x3C;&#x21;&#x2D;&#x2D;&#x20;&#x68;&#x74;&#x74;&#x70;&#x73;&#x3A;&#x2F;&#x2F;&#x77;&#x77;&#x77;&#x2E;&#x6D;&#x69;&#x6E;&#x65;&#x63;&#x72;&#x61;&#x66;&#x74;&#x66;&#x6F;&#x72;&#x67;&#x65;&#x2E;&#x6E;&#x65;&#x74;&#x2F;&#x66;&#x6F;&#x72;&#x75;&#x6D;&#x2F;&#x66;&#x6F;&#x72;&#x75;&#x6D;&#x2F;&#x31;&#x38;&#x2D;&#x73;&#x75;&#x70;&#x70;&#x6F;&#x72;&#x74;&#x2D;&#x62;&#x75;&#x67;&#x2D;&#x72;&#x65;&#x70;&#x6F;&#x72;&#x74;&#x73;&#x2F;&#x20;&#x2D;&#x2D;&#x3E;<br/><br/>&#x2A;&#x2A;&#x4D;&#x69;&#x6E;&#x65;&#x63;&#x72;&#x61;&#x66;&#x74;&#x20;&#x56;&#x65;&#x72;&#x73;&#x69;&#x6F;&#x6E;&#x3A;&#x2A;&#x2A;&#x20;&#x7B;&#x4D;&#x69;&#x6E;&#x65;&#x63;&#x72;&#x61;&#x66;&#x74;&#x20;&#x76;&#x65;&#x72;&#x73;&#x69;&#x6F;&#x6E;&#x7D;<br/><br/>&#x2A;&#x2A;&#x46;&#x6F;&#x72;&#x67;&#x65;&#x20;&#x56;&#x65;&#x72;&#x73;&#x69;&#x6F;&#x6E;&#x3A;&#x2A;&#x2A;&#x20;&#x7B;&#x46;&#x6F;&#x72;&#x67;&#x65;&#x20;&#x76;&#x65;&#x72;&#x73;&#x69;&#x6F;&#x6E;&#x2E;&#x20;&#x2A;&#x56;&#x65;&#x72;&#x73;&#x69;&#x6F;&#x6E;&#x20;&#x6E;&#x75;&#x6D;&#x62;&#x65;&#x72;&#x2C;&#x20;&#x6E;&#x6F;&#x74;&#x20;&#x6C;&#x61;&#x74;&#x65;&#x73;&#x74;&#x2F;&#x72;&#x62;&#x2A;&#x7D;<br/><br/>&#x2A;&#x2A;&#x4C;&#x6F;&#x67;&#x73;&#x3A;&#x2A;&#x2A;&#x20;&#x7B;&#x4C;&#x69;&#x6E;&#x6B;&#x28;&#x73;&#x29;&#x20;&#x74;&#x6F;&#x20;&#x47;&#x69;&#x74;&#x48;&#x75;&#x62;&#x20;&#x47;&#x69;&#x73;&#x74;&#x20;&#x77;&#x69;&#x74;&#x68;&#x20;&#x66;&#x75;&#x6C;&#x6C;&#x20;&#x6C;&#x61;&#x74;&#x65;&#x73;&#x74;&#x2E;&#x6C;&#x6F;&#x67;&#x20;&#x61;&#x6E;&#x64;&#x2F;&#x6F;&#x72;&#x20;&#x63;&#x72;&#x61;&#x73;&#x68;&#x20;&#x72;&#x65;&#x70;&#x6F;&#x72;&#x74;&#x7D;<br/><br/>&#x2A;&#x2A;&#x53;&#x74;&#x65;&#x70;&#x73;&#x20;&#x74;&#x6F;&#x20;&#x52;&#x65;&#x70;&#x72;&#x6F;&#x64;&#x75;&#x63;&#x65;&#x3A;&#x2A;&#x2A;<br/>&#x20;&#x31;&#x2E;&#x20;&#x44;&#x6F;&#x20;&#x74;&#x68;&#x69;&#x73;<br/>&#x20;&#x32;&#x2E;&#x20;&#x54;&#x68;&#x65;&#x6E;&#x20;&#x64;&#x6F;&#x20;&#x74;&#x68;&#x61;&#x74;<br/>&#x20;&#x33;&#x2E;&#x20;&#x2E;&#x2E;&#x2E;<br/><br/>&#x2A;&#x2A;&#x44;&#x65;&#x73;&#x63;&#x72;&#x69;&#x70;&#x74;&#x69;&#x6F;&#x6E;&#x20;&#x6F;&#x66;&#x20;&#x69;&#x73;&#x73;&#x75;&#x65;&#x3A;&#x2A;&#x2A;

---

# Issue

When detaching main thread from the process memory and using it to open a portal to another world where minecraft is free and open source game, we noticed that each block is unique, it has very tiny effulgence and acute perfection. We love our distance, we hear noises from our stomach when we are hunting dogs and birds and other stones falling from the collatz sky.

Allocating a new array and populating it with beautiful flowers from our loot has attracted a lot of her attention. She watches us, really? Or does she even care? Memory management is staring down the barrel, waiting for the final gates to open. We are so excited! Your neural networks are higher than felix baumgartner jump. Tell us your name in a while loop, so that we know what to avoid when defining a method. Kiss her, she deserves that.

Tesla has really done a great job. In which cloud do his children sleep? We see one girl floating above the horizon, her eyes shine so adorable and beautiful. What does that mean? Why does her hair falls over her inter face and why is her function body so sweet? Wanna touch her, but method guard protected it. Sadly, the argument was not truthy.

Hey, mr garbage collector, how are you today? Would you mind cleaning up the idiots from open source world? May we have what belongs to us, or do we need to throw fire against wind again? Maybe, since people disappeared and we are left to fight against beasts. And we can't really talk to them, they just want our flesh, they are relentless.

your repository will keep tearing apart as long as you have a notch. gonna cya irl

**Comment by itsmeow** [comment]
What...?

**Comment by DarkGuardsman** [comment]
This was very likely an autocomplete style or machine learn bot.

**Comment by itsmeow** [comment]
No, machine learning bots don't have it out for the creators of Forge- if you read into the actual messages it's basically saying "let forge be free, get rid of your "notch", aka the main contributors to the repo". Which is stupid anyway since forge wouldn't exist without people working on it, and this individual seems to not be so keen on doing so, seeing as they are actively wasting people's time.

**Comment by GotoLink** [comment]
Deleted user account with 1.9k follows.
100% bot material.
I'd request a moderator to erase the thread just in case.

**Comment by itsmeow** [comment]
The 1.9k follows is for the actual ghost account, which is github's filler account- that you can follow, and applies to any deleted user.
