### ISSUE TITLE
[1.14.4] Not working on Java 12 or Java 11

### ISSUE THREAD

**Issue by Reonu** [MinecraftForge/MinecraftForge#6051]
**Minecraft Version:** {Minecraft version} 1.14.4

**Forge Version:** 28.0.45 (+Optifine)

**Logs:** 
[log.txt](https://github.com/MinecraftForge/MinecraftForge/files/3498246/log.txt)

**Steps to Reproduce:**
 1. Open the game with Java 12 or 11

**Description of issue:**
The game doesn't launch. I've read that Forge 1.14 was supposed to fix compatibility with Java 9 and beyond, but apparently not? Neither the game nor the server will work. I was particulary interested in running the server under Java 12 with the new experimental garbage collector since it improves performance on vanilla, but I can't.

**Comment by GirafiStudios** [comment]
You have misunderstood then. Forge 1.13 (FML to be exact) fixed compatibility with Java 9 specifically (Maybe Java 10, not sure). Not anything beyond that.

**Comment by Reonu** [comment]
Ah, I see. Is Java 12 support planned? I'd love to use the new garbage conector on my personal server. Performance is abysmal on 1.14 vanilla / forge. The new garbabe collector improves things, reduces rubberbanding a lot, but doesn't work with forge. And I don't want to use Paper.

**Comment by Reonu** [comment]
Also, I'm trying Java 9 right now and I can't join my server because it complains about the authentication servers being down for manteinance? But I can join with Java 8.

**Comment by FinnT730** [comment]
Forge uses whatever the Minecraft launcher is providing, so Java 8, Forge can work with Java 9 (maybe 10) but 8 is the version to use, since Minecraft is using it!

**Comment by LexManos** [comment]
FML and our launcher mechanisms were redesigned to be compatible with future java versions. However there currently is no way we can be compatible with 11+ while still running on J8. So until Mojang updates, we have to keep targeting J8.

There are some tricks to screw with things and make it work, but it. breaks things in other edges. Sorry for now, use J8/J9.

**Comment by cpw** [comment]
J10 works as well. I believe we could support j11/12 with an asm update, but that's a breaking change right now, so wouldn't happen this release. I haven't delved deep into other impacts of j11+ yet. It will be investigated for 1.15

**Comment by Reonu** [comment]
@cpw for me java 10 insta crashes and java 9 makes so that I can't join my server because "the authorization servers are offline for manteinance"
