### ISSUE TITLE
[1.14.4] Forge EffectInstance coremod not working correctly

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/MinecraftForge#6052]
I have a mod that replaces the poison potion, but when I take a posion bottle out of the creative tab, performEffect is called on the old vanilla potion on the server side.
The issue is that the coremod transformer is redirecting the field to the getPotionRaw method instead of the getPotion method. This is not helpful, as getPotionRaw just returns the old field instead of checking for delegates.

**Comment by bs2609** [comment]
It seems the transformer was not ported correctly, it isn't supposed to redirect to `getPotionRaw()`, it's supposed to redirect all field access to `getPotion()` *except* in `getPotionRaw()`.

1.13:
https://github.com/MinecraftForge/MinecraftForge/blob/1.13.x/src/fmllauncher/java/net/minecraftforge/common/asm/FieldRedirectTransformer.java

1.14:
<https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/main/resources/META-INF/fieldtomethodtransformers.js>

**Comment by cpw** [comment]
This probably needs a slight tweak to the redirector in asmapi so you can force an exclusion. Though I thought I actually had that already??
