### ISSUE TITLE
[1.14.4] LivingExperienceDropEvent is not called for PlayerEntity

### ISSUE THREAD

**Issue by FireController1847** [MinecraftForge/MinecraftForge#6053]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.45

**Logs:** N/A

**Steps to Reproduce:**
1. Listen to the LivingExperienceDropEvent
2. Add a system.out to the event so you know when it's called
3. Launch the game & give the player some experience
4. Kill an animal
5. Kill the player
6. Observe as killing an animal calls it, but killing the player does not

**Description of issue:**
[I opened an issue on the forum](https://www.minecraftforge.net/forum/topic/74600-1144-livingexperiencedropevent-not-called-for-playerentity/) that talks about this, and it goes into a little more detail.

The LivingExperienceDropEvent works entirely fine for every other entity than the PlayerEntity. The forum post describes what I was trying to do when I discovered this. The code there works perfectly fine in the latest 1.14.3, so it must have been something that got changed in 1.14.4.

Knowing my luck, I just managed to miss something incredibly obvious, however I've spend a couple days on this issue studying for a couple hours each day and cannot find a rhyme or a reason as to why it's not being called.

**Comment by GotoLink** [comment]
The event is only fired server side, so maybe the player kill isn't synced ?
That would mean the issue is way before this event call.

**Comment by FireController1847** [comment]
Soo has anyone been able to reproduce the issue?
