### ISSUE TITLE
[1.14.4] Provide spawn event(s) with additional context information.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#6056]
We now have a SpawnReason enum that is used when spawning a mob. This context is provided in `EntityType#spawn` which is one of the places where Forge fires the SpecialSpawn event. It should be relatively trivial to include this context in that event. The other place SpecialSpawn is fired is in `WorldEntitySpawner#performNaturalSpawning` which can just use `SpawnReason.NATURAL`.

This context would be useful for many mods that wish to respond differently to different types of spawning. For example a block that does something when a mob is birthed on top of it, but not when it naturally spawns on top. 

I am still short on time which is why I did not make a PR for this, however I believe it should be added before the RB to minimize changes to binary compat later on.

**Comment by Tslat** [comment]
Oh dear god yes, please.

**Comment by bl4ckscor3** [comment]
The PR was merged, this can be closed.

**Comment by Darkhax** [comment]
Awesome, thank you so much @bl4ckscor3
