### ISSUE TITLE
[1.15.2] ContainerType and IFactory create are client only

### ISSUE THREAD

**Issue by GotoLink** [MinecraftForge/MinecraftForge#6065]
The factory methods of ContainerType are client only, but the underlying Container constructors are not.
This makes the registry and factory useless on server side for all vanilla containers.

I would have some use for it in a mod with a command for checking recipes.
I could make a PR for a simple patch but I am not sure how much is involved to make those methods accessible on server side.

**Comment by Shadows-of-Fire** [comment]
Mojang's design appears to make an expectancy that containers don't have to use the factories on the server side, so unless that changes, I don't know how feasible this is.

**Comment by GotoLink** [comment]
Still relevant in 1.15.2. Changed title to reflect that.
