### ISSUE TITLE
1.12.x branch no longer auto-building 

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/MinecraftForge#6066]
The latest changes to the 1.12.x branch have not been published to forge maven.
Starting with 3a62514e60b16873cd87a36119db7fbeb60eedc2, no new versions have been released.

**Comment by LexManos** [comment]
Yes, the old jenkins is slowly dieing, this time its a ssl error.
The plan is to eventually move 1.12 to the new Jenkins, but that involves someone writing a Jenkins file and needed changes to make the version number work out.

**Comment by ichttt** [comment]
Fixed, 1.12 is now on nee jenkins
