### ISSUE TITLE
PlayerDestroyItemEvent Not Calling Properly

### ISSUE THREAD

**Issue by FunAverage57** [MinecraftForge/MinecraftForge#6067]
Minecraft Version: 1.14.4

Forge Version: 28.0.49

Note: The follow link is a video to show the issue, at the time I recorded the video the lastest version of forge was 28.0.45, but as of me typing this issue, I had tested it again on 28.0.49 and the issue is still present
Link: [https://www.youtube.com/watch?v=j0A5-M6tgKs&feature=youtu.be](url)

Issue: The PlayerDestroyItemEvent does not fire in specific cases when it should fire.
Event triggers when an Item is destroyed by:
- Block Breaking
- Shield Breaks

Event doesn't triggers when an item is destroyed by:  
- Hitting an Entity
- Using a Hoe on Grass
- Using a Bow
- Using Flint and Steel﻿

**Comment by FunAverage57** [comment]
@LexManos thank you for fixing the issue! However loading up the latest version of forge (28.0.74) The event doesn't trigger when an item is destroyed by hitting an entity? Is that how it should be or is there still an issue?

**Comment by LexManos** [comment]
I tested with swords attacking entites and it triggered just fine in my testss.
if you find cases where it doesn't be exact.

**Comment by FunAverage57** [comment]
@LexManos I used a Diamond Sword, Hoe, and Axe to attack a cow and sheep, and the event doesn't trigger, But other than the attacking with entity, everything else seems to be fixed, which again thank you so much.

**Comment by LexManos** [comment]
And I used both wooden and diamond sword to kill chickens, sheep, slimes and villagers. And it's triggering for me with my changes.

**Comment by FunAverage57** [comment]
@LexManos I found the issue, i had a method that oddly cancelled out the fix, i fixed it and now everything working as it should, thank you so much! and sorry for wasting your time on the matter
