### ISSUE TITLE
[1.14.4] Chunk load failure when entering End portal

### ISSUE THREAD

**Issue by rawalter21** [MinecraftForge/MinecraftForge#6068]
[Latest Log
](https://gist.github.com/rawalter21/8529756cce88cc7a048ad1e38eb94a51)

**Steps to Reproduce:**
 1. Enter The End
 2. Beat the Ender Dragon
 3. Enter the End portal to return to spawn point

**Description of issue:**
If you follow the steps above, the credits roll for a bit and then you are disconnected from the server. If you look at the above log you can see the exact error at the end of the file. If you escape the credits before being disconnected you find yourself falling straight down below The End dimension. I have this issue playing with and without mods. The server is running on the latest Minecraft and Forge versions as of 8/18/2019 on a Ubuntu 18.04 Server using OpenJDK 1.8.0_222.

**Comment by Unnoen** [comment]
Uh oh. Related to https://github.com/MinecraftForge/MinecraftForge/issues/5978?

Lex is going to have a blast with this one.

**Comment by Unnoen** [comment]
Does this trigger *only* during the credit scene? Are you able to return afterwards and jump through or does it freeze/crash regardless or credit scene or not?

Edit: It happens regardless of credit scene or not and I can only reproduce on a dedicated server.

**Comment by Unnoen** [comment]
I'm able to repro, happens only on a dedicated server, kill dragon, jump through portal, server freezes. 
My log (28.0.49): https://gist.github.com/Unnoen/a5ecf1f33a4d79f64e3f4caffb6ed26b

Using an earlier build (28.0.19-custom) Lex made to narrow down #5978: https://gist.github.com/Unnoen/a1bf5c3aab440421cdd7f7648f670dd5

**Comment by rawalter21** [comment]
Its possible that its related to #5978 but I died in the Nether on version 28.0.45 and didn't have a problem spawning back at the spawn point. I've only ever had issues with the End and I was able to reproduce it like 10 times in a row.

**Comment by wh0isit** [comment]
Same issue here. Nearly identical log file. 
Running jre 8u221 vice openjdk.

**Comment by wh0isit** [comment]
More info: I loaded up a world with the dragon killed already. No crash when coming back through the portal.

**Comment by rawalter21** [comment]
@Unnoen and @LexManos, I tested this issue again today myself using version 28.0.51 and it is still occurring with pretty much exactly the same error. The only difference now is that it doesn't actually crash until the overworld starts loading again instead of immediately after entering the portal but it is causing the exact same error. It is also logging "ThreadedAnvilChunkStorage (DIM1): All chunks are saved" over and over again until the credits are over as well.

**Comment by rawalter21** [comment]
@Unnoen and @LexManos, please ignore my last message. It appears that 28.0.55 resolved my issue. Thanks for resolving this!
