### ISSUE TITLE
[1.14.4] Add a hook for net.minecraft.world.World#getSeaLevel

### ISSUE THREAD

**Issue by Yaossg** [MinecraftForge/MinecraftForge#6071]
I found codes related to sea levels all depend on this method in `net.minecraft.world.World`
```
   public int getSeaLevel() {
      return 63;
   }
```
It doesn't allows modders to set their own sea levels. Maybe we need a hook.

**Comment by tterrag1098** [comment]
For what purpose would you need to alter the vanilla sea-level? How could that be usable by more than one mod at a time?

**Comment by Yaossg** [comment]
> For what purpose would you need to alter the vanilla sea-level? How could that be usable by more than one mod at a time?

I don't think so.
1. Before 1.13 update, sea levels can be customized easily even by not only modders, but also players(through vanilla "customized" world type's sea level option). We lost this ability once we had.
2. Mods which want to add brand new dimensions and world types might need this. I think those can be more than one. Mods about customization also need this.

**Comment by tterrag1098** [comment]
Removing customized worlds was vanilla's decision, and one they plan to reverse. Custom dimensions get their own chance to alter these values in their worldgen code.

**Comment by Yaossg** [comment]
> Custom dimensions get their own chance to alter these values in their worldgen code.

I'm afraid not, unless we rewrite all vanilla codes used `getSeaLevel()`. I found a lot of usages of this method by IDE. worldgen features and carvers(which are _hardcoded_ to call this method), structures about ocean, animals around water(and even not around water like bats), several monsters are all related to sea level. So I think sea level is a **world property** instead of a _worldgen paramter_.

**Comment by srs-bsns** [comment]
If you look at `OverworldGenSettings#field_202215_m` it is a private field set to a constant value of 63 but has 0 uses (not even a getter), which would suggest that this is a placeholder for a sea level setting that will be reintroduced in the future.

The value of `63` that you see in `ChunkGenerator#getSeaLevel` and `World#getSeaLevel` is most certainly set from a constant value somewhere else (which gets inlined during optimization) that Mojang is using as a shim until they bring back world customization.

Although this hardcoding is unfortunate, it might be best to wait and see what changes come in 1.15 before messing with it.

**Comment by tterrag1098** [comment]
Closed via 01a862db30a69d2bf2c8f945867172bbfd9d01ff
