### ISSUE TITLE
Chunk load failure when entering exit portal 

### ISSUE THREAD

**Issue by wh0isit** [MinecraftForge/MinecraftForge#6072]
**Minecraft Version:** 1.14.4
**Forge Version:** 28.0.51

**Logs:** 
[latest.log](https://gist.github.com/wh0isit/1da1bd3a7c49bddd1f70b594b6384355)
[crash-2019-08-20_16.08.32-server.txt](https://gist.github.com/wh0isit/c14daefbe56c7197296e036b94af19b5)

**Steps to Reproduce:**
 1. Enter the End
 2. Kill dragon
 3. Jump into exit portal

**Description of issue:**

These steps will give a timeout error on the client. In this example the credits were escaped out of immediately, but if they are allowed to roll, the error:
`[Server thread/INFO] [net.minecraft.world.server.ChunkManager/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved`
is logged multiple times per second before the chunk loading error line.
Reproduced on a local & a remote server.

Also tested an existing world with the dragon killed previously and could use exit portal without issue.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/283c3d1664eac2bc4947cf83925f71f9aab195f7
