### ISSUE TITLE
PlayerTickEvent not firing when dead, even if player isn't removed from world yet

### ISSUE THREAD

**Issue by BlayTheNinth** [MinecraftForge/MinecraftForge#6074]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.49

**Description of issue:**

The fix introduced for #5978 made it so players do not tick when dead, even if they haven't been removed from the world. This is because the `isAlive()` function not only checks for `!removed`, but also returns true if the player health is <= 0.

My mod [Hardcore Revival](https://www.curseforge.com/minecraft/mc-mods/hardcore-revival) has players remain in world with zero health upon death, counting down a timer during which they can be rescued instead of having to respawn. This is no longer possible, as they won't have tick events fired.

From the comments in the linked issue it sounds like it was a problem with being ticked while removed from the world, so narrowing down the check to only `!removed` (instead of `isAlive()`) should solve the problem.

**Comment by Orange1861** [comment]
Could you post a PR that fixes this without reverting the previous fix?
