### ISSUE TITLE
Implement IExtensibleEnum in more enums.

### ISSUE THREAD

**Issue by SilverDavidMC** [MinecraftForge/MinecraftForge#6086]
Some enums don't currently use the IExtensibleEnum interface, making them not extendable when doing so would be useful. Two examples being:

SpellcastingIllagerEntity.SpellType
MusicTicker.MusicType

**Comment by alexbegt** [comment]
IExtensibleEnum is also needs to be added to PlantType as it got missed when the interface was added.

**Comment by LexManos** [comment]
Make a list with proper justifications and we can consider it.
But we are NOT shotgunning it like we did in the past. It's a PITA and it doesn't help us provide a usecase to Mojang to make them NOT enums.

**Comment by MakcSan** [comment]
will this be fixed in future?
