### ISSUE TITLE
[1.14.4] Login Payload Packet functionality is not usable

### ISSUE THREAD

**Issue by HellFirePvP** [MinecraftForge/MinecraftForge#6087]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4-28.0.55

**Logs:** https://gist.github.com/HellFirePvP/8d5d14a557e879a8ac3a2c8d573c421b

**Steps to Reproduce:**
 1. Define a LoginPayload packet (MessageBuilder with either buildLoginPacketList or markAsLoginPacket) and loginIndex setter & getter
 2. Return some form of acknowledge packet when this login payload packet is sent to the client.
 3. Startup game and try login to a server (integrated or dedicated)

**Description of issue:**

The Login Handshake doesn't complete.

Responible for this is the server waiting for an Acknowledge from clientside regarding the payload packets sent - or rather their login index.
The point where it is continuously waiting for those acknowledgements to arrive is [in the FMLHandshakeHandler](https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/main/java/net/minecraftforge/fml/network/FMLHandshakeHandler.java#L259); more specifically, it waits until "sentMessages" - a list of indices of the previously sent login payload packets - is empty.
Login indices are supposed to be removed out of that list when the acknowledge packet arrives back at the server after the client has processed the login payload.

However, the only way to remove indices is through [FMLHandshakeHandler # handleIndexedMessage](https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/main/java/net/minecraftforge/fml/network/FMLHandshakeHandler.java#L158) which processes a LoginIndexedMessage and removes its ID from that list. Debug logging showing this can be found in the "Logs" above. This method is package-private though, so outside access directly to this to allow for other mods to add login payloads and remove that login payload's ID as acknowledgement is not possible.
The only other method calling this is [NetworkInitialization # indexFirst](https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/main/java/net/minecraftforge/fml/network/NetworkInitialization.java#L126) which is again a private method and thus inaccessible. Forge's own Acknowledge packets do call this [indexFirst during their handling](https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/main/java/net/minecraftforge/fml/network/NetworkInitialization.java#L44) and thus can have their login payload packets acknowledged when sent back from client to server.

**Proposed solution:**

A way to allow for a mod to remove a login index out of "sentMessages" as a means of acknowledgement.

**Comment by HellFirePvP** [comment]
Example mod to replicate this behavior can be found at:
https://github.com/HellFirePvP/ForgeTestLoginPayload

Relevant log output displaying network communication in the example:
https://gist.github.com/HellFirePvP/087588d22b6be935448f86d90644537f

**Comment by cpw** [comment]
Login payloads weren't really fully fleshed out as an API. You should never need to fiddle with index numbers, or the indexed message list directly. This should be a property of the login messages, which you just inherit.

**Comment by HellFirePvP** [comment]
Unfortunately at this moment this is a specific property to forge's own login payloads and is inaccessible to anything outside of those.
What 'could' work is replying with forge's acknowledge packet on forge's handshake channel. However, that one is also package private and thus inaccessible to send acknowledges back to the server with.
