### ISSUE TITLE
Idea: Layered config system for 1.14

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/MinecraftForge#6088]
**The Problem**
We currently have a system with a defaultconfig folder, and a config folder that may be per world (in case of server configs) or per minecraft installation folder (in case of common and client).
The problem is that a modpack author cannot change the config values for a world that already exists, and a mod author cannot change the values in a config file to a new default that already exists.
This is beacuse we cannot know if the user explicitly set the config option, or if it was the default in previous versions.
**The Idea**
My suggestion is that we create all config files "commented-out", with each config line starting with a `#`.
We should add a note to the top to say that to overwrite a value you need to uncomment it.
If we load a config file, we correct the default values of the commented out lines if nessecary. Then the config option is evaluated by checking in layers:
- If a config option is present in the world folder, we take that one.
- If not, we check if a config option is present in the defaultconfig folder.
- If not, we take the default value the mod provides.

This way, we can keept the maximum flexibility, and can update default values much more easily.

**Comment by cpw** [comment]
Yes, this is something I want to support. Though I don't want weird stuff like your suggestion, that sounds complex and would be difficult to present in a Gui or command form. Additionally, it might not even make sense for per-server stuff.

I'll leave the issue open, but I'm looking for ideas on how an "updated" config could be presented to the config system, in a meaningful way, without breaking everything about existing configs.
