### ISSUE TITLE
Clicking "No" on missing registry entries screen prevents loading of other worlds

### ISSUE THREAD

**Issue by bl4ckscor3** [MinecraftForge/MinecraftForge#6095]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.18

**Log:** https://gist.github.com/bl4ckscor3/bd30857d5082ba75eddd82160bd42ad8

**Steps to Reproduce:**
 1. Load a world which was previously loaded with mods that are no longer present
 2. Click "No" when prompted
 3. Try to load any world

**Description of issue:** When loading a world that has missing registry entries and the player chooses the "No" option, worlds can no longer be loaded and throw you back to the main menu.
Visual description: https://gfycat.com/parchedsnoopygoldfinch

**Comment by cpw** [comment]
I suspect the embedded server didn't properly shutdown with no.

**Comment by bl4ckscor3** [comment]
This issue is still present in Forge 31.1.18. I have updated the log accordingly.
