### ISSUE TITLE
Can't fill empty buckets with FluidBucketWrapper

### ISSUE THREAD

**Issue by henkelmax** [MinecraftForge/MinecraftForge#6099]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.73

**Steps to Reproduce:**
 1. Fill an empty bucket via `FluidUtil.tryFillContainerAndStow`

**Description of issue:**

The FluidBucketWrapper does not recognize an empty bucket because its contained fluid is not null.

https://github.com/MinecraftForge/MinecraftForge/blob/bae2ee0420a7741236fab074d25efb0eefe5be08/src/main/java/net/minecraftforge/fluids/capability/wrappers/FluidBucketWrapper.java#L70-L82

This causes this method to return 0:
```
getFluid() != null
```
https://github.com/MinecraftForge/MinecraftForge/blob/bae2ee0420a7741236fab074d25efb0eefe5be08/src/main/java/net/minecraftforge/fluids/capability/wrappers/FluidBucketWrapper.java#L120-L123

**Comment by gigaherz** [comment]
Thanks for the report. 
This will be fixed by PR #6098

**Comment by gigaherz** [comment]
Should be fixed with d9f6659
