### ISSUE TITLE
FluidStack.EMPTY is not empty

### ISSUE THREAD

**Issue by henkelmax** [MinecraftForge/MinecraftForge#6100]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.73

**Description of issue:**

The `isEmpty` variable is not set when creating a `FluidStack` and the function `updateEmpty()` is not called in the constructor.
This causes `FluidStack.EMPTY` to return false when calling `isEmpty()`.

**Comment by gigaherz** [comment]
Thanks, I missed that one.
I'll include a fix in PR #6098

**Comment by gigaherz** [comment]
Should be fixed with d9f6659
