### ISSUE TITLE
SingleItemRecipe.Serializer cannot be extended due to inaccesbible type

### ISSUE THREAD

**Issue by waitingtocompile** [MinecraftForge/MinecraftForge#6105]
Currently SingleItemRecipe.Serializer cannot be extended as its constructor requires a SingleItemRecipe.Serializer.Factory, which is package private. Therefore any attempt to extend SingleItemRecipe must fully re-implement a serializer from scratch, even if its functionality is identical to its parent.

**Comment by Shadows-of-Fire** [comment]
Or they could use an AT...
