### ISSUE TITLE
[1.14.4] FML not loading resources in non-main source sets

### ISSUE THREAD

**Issue by hnOsmium0001** [MinecraftForge/MinecraftForge#6108]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.0.74

**Logs:** https://pastebin.com/qpA5h5T7 (latest)

**Steps to Reproduce:**
 1. Add a mod class/mods.toml in a non-main source set, such as test
 2. Add the source set to launch config 
 3. Launch the game 
 4. Forge will say unable to find metadata for the mod

Note: this is also tested with other assets (specifically lang) and it doesn't work either

**Description of issue:**
It seems like FML don't load resources outside of the main module, such as test.

debug.log would probably be more helpful, but it it way too long. I will upload it if necessary.

**Comment by cpw** [comment]
by design. the main module is the only one considered by default. You can extend through configuration of the run profiles to access other modules.

**Comment by hnOsmium0001** [comment]
~~Can you explain how exactly would I do that? I have tried adding `sourceSets.test` into `sources` and calling `resources` on `$buildDir/resources/test/` and they don't seem to work.~~

Solved.
I did not run `genIntellijRuns` after adding a new mod, so the environment args don't include `src/test/resources`.
