### ISSUE TITLE
Invalid payload REGISTER! 

### ISSUE THREAD

**Issue by AngelosNaoumis** [MinecraftForge/MinecraftForge#6113]
Using version .83,which fixes the payload REGISTER problem, with minecraft version 1.14.4 and I cannot login to my server. Below is attached server log (spigot 1.14.4). Non forge client logs in successfully.

![firefox_02_14-36-15](https://user-images.githubusercontent.com/25444260/64112125-2f5aad80-cd8f-11e9-966a-388597d035b0.png)

**Comment by DaemonUmbra** [comment]
As this involves Spigot I'm not sure the fault is on Forge, regardless this should pass through Discord or the Forums first.

**Comment by 0xilly** [comment]
this isnt a forge issue

**Comment by AngelosNaoumis** [comment]
.76 version works perfect. .81+ do not let me log in.

**Comment by cpw** [comment]
I can't fix that the bukkit/spigot plugin is using an illegal name. 76 works because it doesn't actually talk to spigot properly.

**Comment by diesieben07** [comment]
Fixed with https://github.com/MinecraftForge/MinecraftForge/commit/3ef1d6919c6dba2cda97f8c3ae752feb4bfaeffe#diff-fc21cefd3561305b390d2d4eb0667470L697.
