### ISSUE TITLE
No protocol error when URL in json file is empty

### ISSUE THREAD

**Issue by denuno** [MinecraftForge/MinecraftForge#6116]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4-28.0.83

**Logs:** Error was ...`No protocol:` (blank) 

It was a malformedUrlException, sorry no logs, but cause is clear.

**Steps to Reproduce:**
 1. install the latest forge on linux
 2. try to start the forge profile

**Description of issue:**
No idea why it was empty, when I get a chance I'll check the MS box and see if it's missing there (Windows instance started no issue), but the main thing is this shows up on *nix so maybe that's the difference.

Anyhow, the problem was the `url` being empty in the library list for the actual forge jar in the json manifest.  Every other lib jar had a url, and it was the only blank one— filling it in got things going again and nixed the error.

Might just be my setup as I generate all this stuff normally, but figured I'd file this since a nicer error would help a noob.

BTW I saw the new note about ads, and please no automating installs, in the config file— it seems like it'd be a better idea to do in-game ads, than to make it harder for people to get in the game.  I know how hard it is to make money on open source software, but generally you want to lower bars, versus raise them, as far as distribution.  Maybe let some of the YT heads who make decent money know that helping you helps them?  Ads in open source are getting popular (shareware basically), but it's a pretty big turn off for me at least, so I'm starting to mention it. (Thus this addendum, heh) Wish ya the best though and thanks for neat software ads or no! :smiley:

**Comment by DaemonUmbra** [comment]
Please take this to the forums

**Comment by denuno** [comment]
To get the issue addressed?  The ads stuff doesn't matter really that was just an aside.  I can take a look at submitting a patch later, seems like it should be an easy one.  Unless bugs need to go through the forums?

**Comment by Unnoen** [comment]
Nothing has changed as far as installing Forge goes, the note about no installing is just a polite request. It hasn't been made harder out of spite or anything.

**Comment by denuno** [comment]
I didn't mean to imply that the two were related, sorry about that.  If there's a forum link for discussing ads I can share my 2 cents about that there.  This is just about the empty URL in the json config (which again could be due to something wonky on my end, or nix vs. windows, but should probably be handled a little more elegantly regardless).

**Comment by DaemonUmbra** [comment]
I wanted to ask you a few further questions without bloating this issue.

**Comment by cpw** [comment]
Not a forge issue. The modder needs to fix their mods.toml.

**Comment by denuno** [comment]
It was actually due to using an old launcher.jar (1.6.89-j) from the forum:

> The launcher version is there in the log, and it's the same problem— I was using an old java launcher jar versus installing the new native-ish launcher.  I prefer the jar as long as it works, which it does, except for this.  Looks like the old launcher is unsupported by Forge so never mind, basically. 😃

Potential fixes:

> If you want to avoid more rando people asking this question, you can modify build.gradle to not put the URL element in there, versus the blank key, which seems to work with both the old and new launchers.  Guess it's just a matter of time until the old launcher doesn't work for MC itself, but for now at least tweaking that might cut down on the noise (though more traffic == more ad revenue generated so YMMV).  Better still would be to add a check for the min supported launcher version to nip this — and potential similar future problems — in the bud.

Feel free to close this though basically :smiley:

**Comment by LexManos** [comment]
See this is a issue where you havent provided enough information and cpw was confused about which url you were referring to.
Anyways, we can't just NOT have the url entry, because then it would try and download Forge from Mojang's servers, which would just shift the error.
The solution is to use the modern launcher.
This empty URL is something we've been doing for years, not sure what Mojang did to break it on the java launcher but the current native launcher works just fine.

**Comment by denuno** [comment]
In retrospect the launcher log would have been great, and I should have taken some time to create one, but the problem is more of an issue where the version of something Forge depends on isn't checked.

The older config files, as noted by the guy who did provide his logs in the forum, do not match structurally.  Take a look at one from a previous version if you're not sure.  In sum I doubt it's Mojang's fault (they probably just added a null check to the new launcher), but you would know better.

Without internet and without the URL element, there was no error, FWIW.

**Comment by LexManos** [comment]
The problem is we cant check the version of the launcher. As we dont run code by then. 
The issue is 6 years of old crappy 'hey it works' hacking the vanilla launcher, and the vanilla launcher trying to keep that compatibility.
One day Mojang just needs to sit down and create a PROPER extensible spec for the launcher and accept breaking old tools that use it.

The missing entry issue causes 1/2 the old java versions to use Minecraft's CDN, but also some just use null fine.
Others NPE, others try pinging the cdn and get 403 errors. There are A LOT of launchers out there that do weird thing.
So, sadly, we have to only target a sane set. Which is the current version of the public launcher. Sorry.

**Comment by denuno** [comment]
I get how flying a helicopter can suck.  You either keep adding shims (and tests, &c.) or you stick with the latest.  I'm able to work with all open source projects now, but I know how dealing with a closed-source component can be a major PITA (e.g. tests).  More power to you!

No need to to be sorry, I didn't know it was an existing issue that was recently fixed (probably for the new launcher :helicopter:), but that would explain why the config is different now (versus being this way for years).

FWIW, I was chatting with someone who's working on the launcher the other day, and it sounds like things may be improving (which I also assume means things might be changing again, maybe even for 1.15, just FYI).
