### ISSUE TITLE
Crash when creating a recipe ingredient from a tag

### ISSUE THREAD

**Issue by JDLogic** [MinecraftForge/MinecraftForge#6122]
**Minecraft Version:** 1.14.4
**Forge Version:** 28.0.92

This only happens when using the launch configuration for data generators as it does not load mod configs. The exception stems from the patch linked below. Attempting to read the `treatEmptyTagsAsAir` value from the forge server config causes an exception as the config is not loaded.

https://github.com/MinecraftForge/MinecraftForge/blob/a4aa85259e7267f876949d0fabdc91540b67cc8f/patches/minecraft/net/minecraft/item/crafting/Ingredient.java.patch#L104-L106

**Comment by LexManos** [comment]
I could have sworn that my tests loaded the config. I'll address this here soon. As this was MOSTLY intended for the data provider use. And I needed to work on expanding our vanilla recipe replacements.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/3ef1d6919c6dba2cda97f8c3ae752feb4bfaeffe#diff-fc21cefd3561305b390d2d4eb0667470L697
