### ISSUE TITLE
Latest Version System Broken in Forge 1.14.4

### ISSUE THREAD

**Issue by ARandomGuy231** [MinecraftForge/MinecraftForge#6123]
This has been going on for a few forge versions now but when you are on the main menu of Minecraft, it says your forge version on the left and if there is a newer version then it shows that version on the right. But even though I am on the latest version it still says I am not up-to-date even though the version number on the left and right are the exact same. It is a small issue but an of an annoying one.

**Comment by LexManos** [comment]
![](http://puu.sh/EdOhk/a51713246e.jpg)
Not reproducible.
