### ISSUE TITLE
Patches do not contain all side annotations

### ISSUE THREAD

**Issue by octylFractal** [MinecraftForge/MinecraftForge#6125]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4-28.0.93

**Logs:** https://gist.github.com/kenzierocks/92d2045f171b9c7cd15a10fbe5afaa65

**Steps to Reproduce:**
1. Setup a project.
2. Attempt to resolve the source jar.

**Description of issue:**
The patches in MinecraftForge are missing some `@OnlyIn` annotations, causing hunk failures, e.g. for the `Block.java` patch, hunk 11:
```java.patch
@@ -677,6 +681,7 @@
       p_176216_2_.func_213317_d(p_176216_2_.func_213322_ci().func_216372_d(1.0D, 0.0D, 1.0D));
    }   
 
+   @Deprecated // Forge: Use more sensitive version below: getPickBlock
    public ItemStack func_185473_a(IBlockReader p_185473_1_, BlockPos p_185473_2_, BlockState p_185473_3_) {
       return new ItemStack(this);
    }   

```
does not match the actual source from the output of MCP's `patch` step:
```java
      p_176216_2_.func_213317_d(p_176216_2_.func_213322_ci().func_216372_d(1.0D, 0.0D, 1.0D));
   }   

   @OnlyIn(Dist.CLIENT)
   public ItemStack func_185473_a(IBlockReader p_185473_1_, BlockPos p_185473_2_, BlockState p_185473_3_) {
      return new ItemStack(this);
   }   

```

**Comment by m00nl1ght-dev** [comment]
For some reason, the SideAnnotationStripper task did not run. Are you using the latest version of ForgeGradle? Maybe try `gradlew --refresh-dependencies`

**Comment by octylFractal** [comment]
You were indeed correct. Everything is importing fine now.
