### ISSUE TITLE
game crashes when trying to generate a single player world.

### ISSUE THREAD

**Issue by Shadder-1-5** [MinecraftForge/MinecraftForge#6127]
Minecraft Version: 1.14.1
Forge Version: 1.14.4 - 28.0.92

I made this modlist to tryout my own 1.14.4 modding experience, got this error, dont know which mod from
[crash-2019-09-05_22.12.53-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/3582296/crash-2019-09-05_22.12.53-server.txt)

**Comment by alexbegt** [comment]
Update your forge to build 93 and see if this crash goes away.

**Comment by Shadder-1-5** [comment]
I updated to forge build 93 and added lyncanites mobs, this is the report i got when generating a single player world
[crash-2019-09-06_15.56.51-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/3585940/crash-2019-09-06_15.56.51-server.txt)

**Comment by DaemonUmbra** [comment]
Please take this to the forums
