### ISSUE TITLE
[1.14.4] IForgeItem::doesSneakBypassUse is unused

### ISSUE THREAD

**Issue by Da-Technomancer** [MinecraftForge/MinecraftForge#6133]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4-28.0.95

**Logs:** N/A

**Steps to Reproduce:**
1. Make a simple item override doesSneakBypassUse to return true
2. It doesn't work

**Description of issue:**
Despite the forge added method doesSneakBypassUse existing in Item, it is not called by anything in the game code. The forge added method does not function at all, despite functioning in earlier MC versions.

**Comment by bl4ckscor3** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/6114
