### ISSUE TITLE
[1.14.4 - 28.0.95] Random server disconnect and impossible rejoin.

### ISSUE THREAD

**Issue by 2iguys** [MinecraftForge/MinecraftForge#6134]
**Minecraft Version:** {1.14.4}

**Forge Version:** {28.0.95}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/3587129/latest.log)
[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/3587130/debug.log)
![forgeserverdisconnect](https://user-images.githubusercontent.com/9800376/64481072-7975d180-d189-11e9-97bb-4e36d6def32b.PNG)

**Steps to Reproduce:**
 1. start a new forge server
 2. connect using a matching forge client
 3. issue a command in console such as op (username)
 4. client gets disconnected and displays (see screenshot pasted)
 5. if attempting to rejoin same (screenshot) appears.

**Description of issue:**
I am unable to join my forge 1.14.4 server, no mods loaded or anything special.
server then shows 
||
**Could not serialize net.minecraftforge.server.command.EnumArgument@60ee650b (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[07Sep2019 15:52:44.107] [Netty Server IO #2/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.common.command.StructureArgument@377bf911 (class net.minecraftforge.common.command.StructureArgument) - will not be sent to client!
[07Sep2019 15:52:44.116] [Netty Server IO #2/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.EnumArgument@60ee650b (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!**
||
which proceeds to cause the same error after each session.

**Comment by 2iguys** [comment]
feel dumb, just found this issue with the same problem, can confirm that /op in console is the cause as far as my testing is concerned, however make use of my logs to help find a solution :) thank you!

as for now, keeping your player deopped and deleting the old ops.json seems to resolve being able to reconnect.

https://github.com/MinecraftForge/MinecraftForge/issues/6132

**Comment by LexManos** [comment]
@tterrag1098 Broke it, go back to 28.0.94(one version) until he pushes his fix.

**Comment by tterrag1098** [comment]
Duplicates #6132
