### ISSUE TITLE
Class#forName produce NullPointerException

### ISSUE THREAD

**Issue by hohserg1** [MinecraftForge/MinecraftForge#6136]
**Minecraft Version:** 1.12.2

**Forge Version:** 1.12.2-14.23.4.2703

**Logs:** https://pastebin.com/BV3MhX15

**Steps to Reproduce:**
Call Class#forName with nonexistent class name
Example code
```java
private static Object createInstance(AnnotationNode annotationNode) {
        String className = Type.getType(annotationNode.desc).getClassName();
        try {

            HashMap<String, Object> map = new HashMap<>();

            Class<Annotation> annotationClass = (Class<Annotation>) Class.forName(className); //here
```

**Description of issue:**
Class#forName will throw ClassNotFoundException if class not found

**Comment by DaemonUmbra** [comment]
Is ClassNotFoundException not the intended result of calling Class.forName with a class that doesn’t exist?

**Comment by LexManos** [comment]
https://docs.oracle.com/javase/7/docs/api/java/lang/Class.html#forName(java.lang.String)
Indeed it is.

**Comment by hohserg1** [comment]
Yes, it expected result
![image](https://user-images.githubusercontent.com/35610168/64491815-46107100-d275-11e9-8f14-b1143f9cb855.png)

**Comment by hohserg1** [comment]
Well, why am I getting NPE in the log?

**Comment by LexManos** [comment]
Because the logger is screwed up, disable debug mode and move on with your life.
https://github.com/Mojang/LegacyLauncher/blob/master/src/main/java/net/minecraft/launchwrapper/LaunchClassLoader.java#L179

**Comment by hohserg1** [comment]
Oh, thanks you. Now I got it. I was surprised why the unchecked exception is not the last in the log
