### ISSUE TITLE
Greatest new feature of all time?

### ISSUE THREAD

**Issue by Spontini** [MinecraftForge/MinecraftForge#6143]
First of all this feature suggestion is more useful for servers than singleplayer, the feature is simple
Forge should've it's own launcher and for example you want to join a random modded server once you click on Join button it detects the mods and it's versions and starts to download the mods automatically for the person who requested to join into server, it downloads the mods and let the person join the server without any problems.

With this feature modded factions, pvp, minigames, custom made modpacks and a lot more you can think of can get famous so quickly.

**Comment by gigaherz** [comment]
This feature has been wanted for almost as long as mods have existed, however there's two major things that make it impossible in practice:
1. Unloading code: there is no practical way to unload code from the JVM once it has been loaded.
2. Coremods: It is not feasible to apply modifications to code that has already been loaded, and it is not feasible to "un-patch" code that had been patched previously, due to point 1.

**Update**: Oops I misread the request. On second read, you are talking about a launcher, not for the feature to be inside forge. That is not as impossible, but it does have its own set of complexities that probably make it out of the scope of the Forge project

**Comment by JoJoDeveloping** [comment]
Also, there are potential legal issues around rehosting mods..

**Comment by gigaherz** [comment]
I'm assuming forge would never download mods from the server itself, but rather rely on well-known sources such as curseforge.

**Comment by mura3277** [comment]
Perhaps it could make more sense for modded servers to somehow supply a curseforge pack link to modded clients? Since cpw has already recently added the capability to download a curse pack. Obviously requiring the user to close the game and reopen the newly created profile

**Comment by Spontini** [comment]
> I'm assuming forge would never download mods from the server itself, but rather rely on well-known sources such as curseforge.

Yes, that's what i thought as well. Just giving a simple example, a mod pack came outs, there is a single mod that cause crashes but you can't update it, you have to wait till the modpack itself to get updated cuz people (especially if you own a big network) will not update their mods manually but with this way the launcher can detect the updated mod and just update it automatically.

**Comment by LatvianModder** [comment]
I once had this feature in my mod. Didn't realize you can force clients to download viruses like that, who would've thought! Removed that feature pretty quickly.

**Comment by Spontini** [comment]
> I once had this feature in my mod. Didn't realize you can force clients to download viruses like that, who would've thought! Removed that feature pretty quickly.

I mean if you accept only curseforge they can't download viruses?

**Comment by LatvianModder** [comment]
As if, vazkii uploaded a virus there. Not exactly malicious but still something mod shouldn't do, so they don't check it most likely. Even if someone reported it as virus, it could already be too late

**Comment by simon816** [comment]
>I mean if you accept only curseforge they can't download viruses?

What stops someone uploading malware to curseforge?

**Comment by Spontini** [comment]
> > I mean if you accept only curseforge they can't download viruses?
> 
> What stops someone uploading malware to curseforge?

The launcher can make a list of the mods and it can show the person ``you're abou to download this, this and this (with the links perhabs) do you accept?` and there it is, it's the persons fault if they download a malware for not being carefull.

**Comment by cpw** [comment]
Put simply, the server cannot be trusted to supply any information about itself. It is too easy to create a malicious server that distributes malware, either through stealth curseforge "viruses" or otherwise. I don't believe we can ever support this model of behaviour therefore.

**Comment by 0xilly** [comment]
I have to agree with @gigaherz that this is outside the scope of Forge

**Comment by LexManos** [comment]
1) Mojang explicitly states they do not want anyone creating any external launcher, or anything that takes user credentials.
2) Forge will NEVER download executable code from anywhere. especially from random servers, or services we do not control. It is WAY to much of a security risk, and we are not going to be responsible for that.
