### ISSUE TITLE
1.14.4 - Modded Spawn Eggs not being dispensed

### ISSUE THREAD

**Issue by JimiIT92** [MinecraftForge/MinecraftForge#6145]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4 - 28.0.102

**Steps to Reproduce:**
 1. Create an Entity and register a SpawnEggItem for that entity
 2. Run the game and put the Spawn Egg in the dispenser
 3. Activate the dispenser

**Description of issue:** Instead of spawning the Entity, the Spawn Egg is dispensed as item. With Animefan8888 we discovered that the DispenseItemBehavior for the spawn egg is not registered for the Mod's Spawn Eggs (or is registered before the item registration). You can find the full discussion on the Forum [here](https://www.minecraftforge.net/forum/topic/75881-1144-spawn-custom-entity-from-dispenser/?tab=comments#comment-363500)

If you add manually the behavior after the item registration they works as intended, however this should be done automatically by Forge. We tested this with the source code in [this repository]
(https://github.com/JimiIT92/AntiblazeMod). In praticular in [RegisterEntities](https://github.com/JimiIT92/AntiblazeMod/blob/master/src/main/java/com/antiblaze/events/RegisterEntities.java) and [AntiBlazeEntities](https://github.com/JimiIT92/AntiblazeMod/blob/master/src/main/java/com/antiblaze/core/AntiBlazeEntities.java) you should find all the code needed to reproduce and investigate on this bug

**Comment by LexManos** [comment]
Register the dispense handlers yourself. Its a simple system, not sure why you think this should be done by Forge...

**Comment by JimiIT92** [comment]
Because i don't think there are many mod makers that doesn't want specifically their mobs to be spawned from dispensers :/ Also the modded spawn egges are already registered into the dispenser "EGGS" field, so if they don't interact correctly with it why would the game add them to that map? Don't mind me, i'm fine with registering the behavior myself, but in older versions of Forge (like 1.10.2), this behavior was already implemented when you register a spawn egg (again, why wouldn't you spawn the mob from dispenser?) ¯\_(ツ)_/¯

**Comment by LexManos** [comment]
In other versions of Forge, we were hijacking the the vanilla egg item. And just using extra NBT data. So there was no extra behavior to register. But if modders made their own eggs, such as the safari net, they had to register them selves.
Since the flattening, you have to make your own item. 
It seems odd to special case this one Item.
