### ISSUE TITLE
[1.14.4] Client classes called in invalid Dist when registering messages

### ISSUE THREAD

**Issue by Aizistral** [MinecraftForge/MinecraftForge#6146]
**Minecraft Version:** 1.14.4

**Forge Version:**28.0.104

**Logs:** [Click](https://pastebin.com/cYJESpiT)

**Steps to Reproduce:**
 1. Create a message that uses client-only methods or classes in it
 2. Try to register it
 3. Launch a server
 4. Behold!

**Description of issue:**
I've tried for a while, but I just can't wrap my head around this issue. The thing is, when you register a message with some code in it's handling method that should only be executed on client-side, starting up the server with it may result into crash. I double checked that methods code is never actually called or executed, but for some reason it still throws an exception saying that a client-side only class was attempted to be loaded on server side (check out the attached log).

Here is my message class:

```
public class PacketHandleItemPickup {
	  
	  private static final Random random = new Random();
	  private int item_id;
	  private int pickuper_id;

	  public PacketHandleItemPickup(int itemID, int pickuperID) {
		  this.item_id = itemID;
		  this.pickuper_id = pickuperID;
	  }

	  public static void encode(PacketHandleItemPickup msg, PacketBuffer buf) {
		  buf.writeInt(msg.item_id);
		  buf.writeInt(msg.pickuper_id);
	  }

	  public static PacketHandleItemPickup decode(PacketBuffer buf) {
	    return new PacketHandleItemPickup(buf.readInt(), buf.readInt());
	 }

	  public static void handle(PacketHandleItemPickup msg, Supplier<NetworkEvent.Context> ctx) {

		    ctx.get().enqueueWork(() -> {
		    	
		    	System.out.println("lul");
		      
		      Entity pickuper = Minecraft.getInstance().world.getEntityByID(msg.pickuper_id);
		      Entity entity = Minecraft.getInstance().world.getEntityByID(msg.item_id);
		      
		      Minecraft.getInstance().particles.addEffect(new ItemPickupParticle(Minecraft.getInstance().world, pickuper, entity, 0.5F));
		      Minecraft.getInstance().world.playSound(entity.posX, entity.posY, entity.posZ, SoundEvents.ENTITY_ITEM_PICKUP, SoundCategory.PLAYERS, 0.2F, (random.nextFloat() - random.nextFloat()) * 1.4F + 2.0F, false);
		    });
		    ctx.get().setPacketHandled(true);
	  }

}
```

Here is how it's registered in FMLCommonSetupEvent:

```
packetInstance = NetworkRegistry.ChannelBuilder.named(new ResourceLocation(EnigmaticLegacy.MODID, "main"))
                .networkProtocolVersion(() -> PTC_VERSION)
                .clientAcceptedVersions(PTC_VERSION::equals)
                .serverAcceptedVersions(PTC_VERSION::equals)
                .simpleChannel();

...

packetInstance.registerMessage(11, PacketHandleItemPickup.class, PacketHandleItemPickup::encode, PacketHandleItemPickup::decode,
				PacketHandleItemPickup::handle);
```

The thing is, I have a bunch of other client-sided messages that work just fine, and of course there are a lot of other examples since people were somehow using them up to this moment. But I can't see what's wrong with this exact one, in my mind it should work totally fine - so I consider this to be a bug.
I've also noticed that when I tried to create PlayerEntity object and assign player from Minecraft.getInstance().player in messages I've made before, it thrown the same exception, but stopped doing that when I simply reclassified my object as ClientPlayerEntity.

**Comment by TeamSpen210** [comment]
The problem I believe is that when you register the message, that causes the class to be loaded, and so it tries to classload everything needed to run those methods - including the client-only `
Minecraft`. Try wrapping the content of `enqueueWork` in `DistExecutor.runWhenOn()`, which nests stuff deeply enough to avoid the load on servers.

**Comment by MrCrayfish** [comment]
If I know that the handling of a packet contains client only code, I create a method in my proxy to handle the code. Inside your Runnable, just call the method from the proxy and pass data in the parameters.

**Comment by LexManos** [comment]
The handler is both sides, there doesn't seem to be a differentiation between C->S and S->C.. so.. How do you exact this to work?
There are a few things you can do to fix this, as MrCray/TeamSpen said, you can also get away with `(a,b) -> PacketHandleItemPickup.handle(a,b)` to delay the loading.

**Comment by Shadows-of-Fire** [comment]
I wrap my packet handling code in a double lambda similar to how the distexecutor does.
That has successfully delayed loading for most cases, tho I think it still dies if you cause a capturing checkcast thing, like storing client.world in a World var

**Comment by Aizistral** [comment]
Alright, this is understandable.

I tried to use DistExecutor.runWhenOn() like this:
```
public static void handle(PacketHandleItemPickup msg, Supplier<NetworkEvent.Context> ctx) {

		    ctx.get().enqueueWork(() -> {
		    	
		      DistExecutor.runWhenOn(Dist.CLIENT, () -> () -> {
		    	
		      System.out.println("lul");
		      
		      Entity pickuper = Minecraft.getInstance().world.getEntityByID(msg.pickuper_id);
		      Entity entity = Minecraft.getInstance().world.getEntityByID(msg.item_id);
		      
		      Minecraft.getInstance().particles.addEffect(new ItemPickupParticle(Minecraft.getInstance().world, pickuper, entity, 0.5F));
		      Minecraft.getInstance().world.playSound(entity.posX, entity.posY, entity.posZ, SoundEvents.ENTITY_ITEM_PICKUP, SoundCategory.PLAYERS, 0.2F, (random.nextFloat() - random.nextFloat()) * 1.4F + 2.0F, false);
		    
		      });
		      
		      });
		    ctx.get().setPacketHandled(true);
	  }
```
The error remained exactly the same. The proxy method worked however (I couldn't even imagine what could have gone wrong with it).

Still, I want to understand the logic behind this. It may be intended, but I expected more consistent behavior - however, the following message, for instance, works perfectly fine without any excessive manipulations:
```
public class PacketPlayerRotations {
	
	private float rotationYaw;
	private float rotationPitch;
	private float rotationYawHead;

	  public PacketPlayerRotations(float rotationYaw, float rotationPitch, float rotationYawHead) {
	    this.rotationYaw = rotationYaw;
	    this.rotationPitch = rotationPitch;
	    this.rotationYawHead = rotationYawHead;
	  }

	  public static void encode(PacketPlayerRotations msg, PacketBuffer buf) {
	     buf.writeFloat(msg.rotationYaw);
	     buf.writeFloat(msg.rotationPitch);
	     buf.writeFloat(msg.rotationYawHead);
	  }

	  public static PacketPlayerRotations decode(PacketBuffer buf) {
	     return new PacketPlayerRotations(buf.readFloat(), buf.readFloat(), buf.readFloat());
	  }


	  public static void handle(PacketPlayerRotations msg, Supplier<NetworkEvent.Context> ctx) {

		    ctx.get().enqueueWork(() -> {
		    	ClientPlayerEntity player = Minecraft.getInstance().player;
		    	
		    	player.rotateTowards(msg.rotationYaw, msg.rotationPitch);
		    	player.rotationYawHead = msg.rotationYawHead;
		      	
		    });
		    ctx.get().setPacketHandled(true);
	  }

}
```

What exactly causes the difference between this one and the one I had error with previously? Both are using client-only fields and methods, both are registered the same way.
What am I missing?

**Comment by pau101** [comment]
The reference type of `Minecraft#world` is `ClientWorld` and you pass it into the `ItemPickupParticle` constructor argument of type `World`. The jvm verifies assignability such as this on class load so you have to write your code to only reference the class for the appropriate side.

**Comment by Shadows-of-Fire** [comment]
You are able to access an already casted world from `Minecraft.getInstance().player.world`

**Comment by Aizistral** [comment]
> You are able to access an already casted world from `Minecraft.getInstance().player.world`

Alright. I've actually done this before. But then the error arises on ParticleManager, and there is seemingly now way to avoid it if Minecraft.getInstance().particles object is called or used in any way: [Log](https://pastebin.com/L2qqz52q)

The handle method is as following:

```
public static void handle(PacketHandleItemPickup msg, Supplier<NetworkEvent.Context> ctx) {

	ctx.get().enqueueWork(() -> {
		      
		Entity pickuper = Minecraft.getInstance().player.world.getEntityByID(msg.pickuper_id);
		Entity entity = Minecraft.getInstance().player.world.getEntityByID(msg.item_id);
			      
		Minecraft.getInstance().particles.addEffect(new ItemPickupParticle(Minecraft.getInstance().player.world, pickuper, entity, 0.5F));
			      
		Minecraft.getInstance().player.world.playSound(entity.posX, entity.posY, entity.posZ, SoundEvents.ENTITY_ITEM_PICKUP, SoundCategory.PLAYERS, 0.2F, (random.nextFloat() - random.nextFloat()) * 1.4F + 2.0F, false);
		    	
		});
			  
	ctx.get().setPacketHandled(true);
	}
```

Why does that happen then?

**Comment by ZeroNoRyouki** [comment]
Lambdas are just sinctactic sugar. The compiler convert them to (static or not) methods of the class where they are defined so are subject to the usual checks performed at class loading time. Particle is a client only class so when the JVM load and verify your message class the FML class loader throws the exception you are getting. If your other code works it's bacause there are no client side classes referenced by the lamda code body. Put your client side code in your proxy

**Comment by Aizistral** [comment]
> If your other code works it's bacause there are no client side classes referenced by the lamda code body

Maybe I am wrong, but ClientPlayerEntity obtained by Minecraft.getInstance().player appears to be client-only class. This also holds true for a bunch of other things I've been doing with packets. Just another example:
```
 public static void handle(PacketSlotUnlocked msg, Supplier<NetworkEvent.Context> ctx) {

		    ctx.get().enqueueWork(() -> {
		      ClientPlayerEntity player = Minecraft.getInstance().player;
		      ItemStack stack;
		      
		      if (msg.type.equals("ring"))
		    	  stack = new ItemStack(EnigmaticLegacy.ironRing);
		      else if (msg.type.equals("scroll"))
		    	  stack = new ItemStack(EnigmaticLegacy.thiccScroll);
		      else if (msg.type.equals("spellstone"))
		    	  stack = new ItemStack(EnigmaticLegacy.voidPearl);
		      else
		    	  stack = new ItemStack(EnigmaticLegacy.ironRing);
		      
		      IToast toast = new SlotUnlockedToast(stack, msg.type);
		      EnigmaticEventHandler.scheduledToasts.add(toast);
		      EnigmaticEventHandler.deferredToast.put(player, 5);
		      
		    });
		    ctx.get().setPacketHandled(true);
	  }
```

The IToast is obviously a client-only class, and so is the SlotUnlockedToast. But for some reason creating and operating with this object works fine.

Checkcast thing mentioned earlier on in this discussion may make more sense, but... Well, actually, all my previous experience in Java was telling me that no matter how wrong mess you have anywhere in the code, if it's not executed - there won't be any errors. Of course compiler and/or workspace usually prevents you from making obvious errors like using unexistent methods or fields, and may refuse to run invalid code after looking through it, showing you the mistakes you've made. But in more complex cases, it tends to work fine until the invalid method or class is called. So it was when I've been working on a mod on 1.7.10.
Why exactly it's working the other way in this case?

**Comment by ZeroNoRyouki** [comment]
Are those classes market with @OnlyIn(CLIENT)? (Can't check right now)

**Comment by Aizistral** [comment]
> Are those classes market with @OnlyIn(Dist.CLIENT)? (Can't check right now)

Yes, IToast is marked with it, SlotUnlockedToast is marked with it, ClientPlayerEntity is also marked with it.

**Comment by gigaherz** [comment]
A reminder that this is not a forum, you can discus which classes are more or less safe in the actual forums, or the discord server.

The solution is simple: just put your implementations in a separate class, and avoid triggering the verifier through implicit casts. @pau101 has explained why this is important.

My suggestion is to have a ClientPacketHandlers class, and just do enqueueWork(ClientPacketHandlers::handleThisPacket), which mimics the vanilla packet handling behaviour, but other suggestions, such has having a dedicated nested class per packet, are also valid.

**Comment by Aizistral** [comment]
Alright then, this definitely taken up much more words then should have been. The problem is essentially exhausted, so... Thanks to everyone who participated for the help and explanations, it was really useful.
