### ISSUE TITLE
Structures appear twice in autocomplete

### ISSUE THREAD

**Issue by Bricktricker** [MinecraftForge/MinecraftForge#6151]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.0

**Logs:** --

**Steps to Reproduce:**
 1. Enter command /locate
 2. Look at the suggestion list, every structure appears twice

**Description of issue:** When using the /locate command every structure appears twice, as minecraft:{structure} and {Structure} in the autocomplete suggestions.
E.g. minecraft:mineshaft and Mineshaft

**Comment by Unnoen** [comment]
Vanilla structures appear with the minecraft prefix as to not break vanilla behaviour.

tterrag on the subject:
![image](https://user-images.githubusercontent.com/6127568/64872842-3cc74000-d68b-11e9-8d53-b7fb9a789cb1.png)

**Comment by Bricktricker** [comment]
ok, didn't know that.
