### ISSUE TITLE
Ability to disable the creation of the "forge" profile when installing/updating Forge.

### ISSUE THREAD

**Issue by Cyphall** [MinecraftForge/MinecraftForge#6153]
For people like me who manage their own launcher profiles, it is a bit annoying to have to delete the "forge" profile everytime we update forge.
Could we get a checkbox on the Forge installer to disable this?
Thanks

**Comment by DaemonUmbra** [comment]
If you leave the profile alone it won't make another one

**Comment by Cyphall** [comment]
I know but I like when everything is organized and having this ghost profile in my profiles list is... meh.

**Comment by LexManos** [comment]
I understand your thought, but we are targeting the average user who has no idea what they are doing. Having that check box would just add a ton of extra support requests to our forums asking why a profile was never created {Because they clicked the box and didn't think it through}

**Comment by Cyphall** [comment]
Well, that makes any front modification problematic.
Maybe we could have a flag we can manually set in the profiles json file or smth like that to disable the creation even tho I admit it's not very practical (provided that Minecraft Launcher doesn't remove any unrecognized json element from the file).
Beside that, I don't see any other way to implement this feature.
(ofc I will understand if you don't want to go this far for such a little feature)

**Comment by Cyphall** [comment]
Nevermind, I realised I could simply make a Python script to both delete the forge profile and update my own with the new Forge version.

**Comment by chylex** [comment]
Could you skip creating the profile if a `Forge` profile already exists? Default profiles in the launcher are capitalized (`Latest release`, `Latest snapshot`) so I prefer consistent naming, but then whenever I install Forge, I end up with two profiles - `Forge` and `forge`.
