### ISSUE TITLE
2+gb logfile: Need to be able to turn off logging

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [MinecraftForge/MinecraftForge#6159]
I forgot to turn of me PC, I was away about 5+hrs. and had left my minecraft with 230 mods running. I came back, and the log file was 2+GB large.

Christ almighty, forge needs an option to turn off logging completely or only log certain events like INFO, CRITICAL or something to that effect.

**Comment by Unrepentant-Atheist** [comment]
That said, is there any "hacky" way or any way to turn off logging or only log certain events right now?

**Comment by gigaherz** [comment]
You can disable specific forge logging channels through jvm commandline parameters, but to disable mod loggers or such, I think you'll need to provide an alternative log4j configuration xml. I don't however know how to do that.

**Comment by Unrepentant-Atheist** [comment]
I do. Don't need to add anything by forge. It works just fine: https://www.reddit.com/r/admincraft/comments/69271l/guide_controlling_console_and_log_output_with/

This should be added to Forge FAQ or something.

**Comment by Unnoen** [comment]
You should probably find what's the cause of the giant log file as that isn't Forge's fault. It's probably a mod doing something, and if it is, that should be fixed.
