### ISSUE TITLE
Mod List scales incorrectly on HiDPI Setups

### ISSUE THREAD

**Issue by juliand665** [MinecraftForge/MinecraftForge#6162]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.6

**Logs:** https://gist.github.com/juliand665/05f1b6b2ee1201750621ae907e5d2464

**Steps to Reproduce:**
 1. Start up the game
 2. Click the "Mods" button
 3. (Optionally) click any mod to see the full effect of the issue

**Description of issue:**
On setups with more than 1 pixel per point (tested on a Mac with retina display, but it might happen on other OSs too), the mod list description area is cut off. You can't scroll up either, it's purely visual.

Without HiDPI:
![Screen Shot 2019-09-17 at 15 03 45](https://user-images.githubusercontent.com/827762/65044669-a41c1300-d95d-11e9-878e-8380da88cc6a.png)

With HiDPI:
![Screen Shot 2019-09-17 at 15 03 54](https://user-images.githubusercontent.com/827762/65044678-a8483080-d95d-11e9-8990-3773fbe818ed.png)

Looks like this is the same issue as #5996, although that one was less than helpful.

**Comment by LordMonoxide** [comment]
This isn't an issue in Windows 10.  I use a 4K TV at 200% scale.

**Comment by juliand665** [comment]
Interesting, so I guess it is macOS specific after all.

**Comment by gigaherz** [comment]
Could be differences in how hidpi is exposed (or hidden) from the app. Eg maybe one of the platforms "lies" to the app about the real dimensions of the screen while the other does not. In any case, it should be a matter of making sure the drawing dimensions are calculated based on the real pixel size of the opengl backbuffer, and not the virtual screen dimensions.
