### ISSUE TITLE
Registering Entity without data fixer still causes problems in dev environment.

### ISSUE THREAD

**Issue by temp1011** [MinecraftForge/MinecraftForge#6177]
While https://github.com/MinecraftForge/MinecraftForge/commit/fcd9582133cfd87e1585588afb08c0ed09a1a265 catches the entity data fixer exception, It is still thrown below because `SharedConstants.developmentMode` is now true, maybe as a result of a recent change.

Forge Version: 28.1.11
[Here](https://gist.github.com/temp1011/082df566c7736bd9b5663ab836c0f360) Is my log.
[Here](https://github.com/temp1011/ForestryMC/tree/f8fcbfe15a1221e71c45660bd31b7771f0cb5ab9) is the code that causes this, specifically [this](https://github.com/temp1011/ForestryMC/blob/f8fcbfe15a1221e71c45660bd31b7771f0cb5ab9/src/main/java/forestry/apiculture/entities/ApicultureEntityTypes.java) file. I can provide a simpler repro if needed.

**Comment by gigaherz** [comment]
There's no write usages of developmentMode in the forge or mc codebase. It is a mojang internal value that should remain set to false for our use cases. I don't know what's setting it to true in your mod, but it's not Forge.

**Comment by temp1011** [comment]
I can't find any usages of it either, but I agree that this is not a Forge issue.
