### ISSUE TITLE
-Dfml.﻿d﻿oNotBackup=﻿﻿﻿tru﻿﻿﻿﻿e not working with the latest forge.

### ISSUE THREAD

**Issue by Josh65-2201** [MinecraftForge/MinecraftForge#6179]
**Minecraft Version:**
1.12.2

**Forge Version:**
14.23.5.2847

**Description of issue:**
Not sure if this is a multimc issue but when i enable and put -Dfml.﻿d﻿oNotBackup=﻿﻿﻿tru﻿﻿﻿﻿e in the java arguments it still backups the world.

**Comment by Unnoen** [comment]
Please provide a log and more details, what are you doing to trigger the backup?

**Comment by Josh65-2201** [comment]
Forge backs up when I remove a mod or it gets updated and there's missing block/items in the save.

**Comment by Josh65-2201** [comment]
heres some logs:
debug:
[debug 1.txt](https://github.com/MinecraftForge/MinecraftForge/files/3800514/debug.1.txt)
[debug 2.log](https://github.com/MinecraftForge/MinecraftForge/files/3800515/debug.2.log)

logs:
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/3800509/latest.log)
