### ISSUE TITLE
[1.14.4] java.lang.NullPointerException: Ticking entity when attacking a zombie while invisible

### ISSUE THREAD

**Issue by raziel23x** [MinecraftForge/MinecraftForge#6185]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.0-28.1.0 - 28.1.22

**Logs:** https://paste.dimdev.org/akonuzitoh.mccrash

**Steps to Reproduce:**
 1. find or spawn in a zombie
 2. attack the zombie while invisible
 3. game crashes

**Description of issue:**
If i go back to forge versions 28.0.x the crash goes away but when i update to any version of forge to 28.1.x that is when the crash happens 
when attacking a zombie the game crashes
I started looking through all the source code in all the mods that added new mobs or messed with the loot tables for mobs i have loaded none of them have touched the code for the zombie and from talking with Animefan8888 and he said this could be the issue https://www.minecraftforge.net/forum/topic/76145-forge-281x-causing-crash-when-killing-zombies/?tab=comments#comment-366371

**Comment by raziel23x** [comment]
with more investigation i finally pinpointed the issue with having the invisibility affect on you

**Comment by Quatroctus** [comment]
> 
> 
> with more investigation i finally pinpointed the issue with having the invisibility affect on you

Have you tested this without Lycanite's Mobs? Because that mod as I pointed out did some stuff with the Revenge Target and the Attack Target. Technically speaking this is a problem with Lycanite's Mobs until the LivingSetAttackTargetEvent is called in LivingEntity#setRevengeTarget.

**Comment by raziel23x** [comment]
I forgot to test it with the invisibility on with that mod disabled and when i disabled at your request even when invisible there is no crash so i sent these results to them in a new issue with more information from all the testing you have had me try

**Comment by LexManos** [comment]
So, not a bug with our code, but another mod causing issues. Thats what I suspected on the forum. Good to know.
