### ISSUE TITLE
Custom world types specified in server.properties are not recognized.

### ISSUE THREAD

**Issue by Dooglamoo** [MinecraftForge/MinecraftForge#6189]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4-28.1.11

**Logs:** NA

**Steps to Reproduce:**
 1. Create a mod with a new world type
 2. Specify the world type in server.properties
 3. run the "Server" configuration

**Description of issue:**
The new world type is not used. The server runs with "default" world type instead.
It appears that the server.properties file is loaded before the mod is loaded, so the new world type that the mod creates is not yet in the world types list at the time that server.properties is loaded.

**Comment by StigLennart** [comment]
fwiw, I found a workarround: 

You can create a dooglamoo world in singleplayer, then simply copy/paste that savedata towards your server/world folder. 

from here on I found that Minecraft will generate the terrain accordingly, even though the properties file will still reset to 'default'. This way you also have the added bonus of being able to customize the dooglamoo world gen through the singleplayer menu options
