### ISSUE TITLE
Incorrect GUI partial ticks

### ISSUE THREAD

**Issue by Ocelot5836** [MinecraftForge/MinecraftForge#6194]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.26

**Description of issue:**

In `GameRenderer#569`, instead of passing in `this.mc.getRenderPartialTicks()`, `this.mc.getTickLength()` is passed. This causes problems where interpolation using the `partialTicks` method variable is not possible.

**Comment by Niko-sk2x** [comment]
This patch shows that this is what vanilla uses https://github.com/MinecraftForge/MinecraftForge/blob/78cdb705d46f41421eab21c8496b081cc8108e5a/patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch#L44-L45

This is more likely to be a case of incorrectly named parameter name. Or a vanilla "bug" that just happens to not cause any detectable issues.
~~And why do you even need ticks in GUI rendering here? There is no clearly defined concept of a tick in GUI.~~ Looks like I'm wrong there

**Comment by diesieben07** [comment]
> And why do you even need ticks in GUI rendering here? There is no clearly defined concept of a tick in GUI.

`Screen#tick` is called every tick. It is needed for playing animations properly at variying framerates.

**Comment by pau101** [comment]
This is the intended behavior. The function `Minecraft#getTickLength` along with forge's `partialTick` parameter in the draw screen event are misnomers.

This function returns `Timer#elapsedPartialTicks`, which is the instantaneous tick delta. While partial tick is the accumulated tick delta. This parameter of `Screen#render` is used for screens to know how much time has past. A couple of the usages are for credit screen scrolling and main menu panorama rotation.
