### ISSUE TITLE
Make it in forge that all the blocks are hexagons

### ISSUE THREAD

**Issue by anakrusis** [MinecraftForge/MinecraftForge#6199]
_

- **With the recent new innovative development of hexagon based game play such as  civilization 5 and modern warfare, it is no doubt that the direction of modern gaming is indeed the sleek and smooth hexagon. These little polygons sure do pack a lot of power. As such therefore the minecraft needs to adapt and avolve to better fit its surroundings. I propose that the minecraft forge uses a hexagon based block system which will encourage the user to use creativity in their building technique. Minecraft forge has the potential to really change the way minecraft users are playing minecraft even more if it uses the hexagon instead of the cube.
- 
- Thank you, best regards**

_

**Comment by anakrusis** [comment]
Wait no this is a bad idea

**Comment by 0xilly** [comment]
wat!?
