### ISSUE TITLE
[1.14.4] Forge 28.1.31 has persisting entities

### ISSUE THREAD

**Issue by HexedHero** [MinecraftForge/MinecraftForge#6203]
**Minecraft Version:** {Minecraft version}
1.14.4

**Forge Version:** {Forge version. *Version number, not latest/rb*}
28.1.31

**Steps to Reproduce:**
 1. Login a server
 2. Change worlds on the server with entities around you
 3. They stay on the client

**Description of issue:**
A perfect example of the bug
http://cdn.hexedhero.com/u/t6NrGhAHOQ.mp4
It doesn't happen on 28.1.30 forge so Its something to do with the new dimension changes on the version above.

**Comment by cpw** [comment]
Do you actually change dimension?

**Comment by HexedHero** [comment]
It seems to do it on both dimension changes and normal world changes (same dimension) another side effect of this I've also found recently is that sometimes if I go into the end it'll look like the normal overworld in terms of the sky

**Comment by HexedHero** [comment]
http://cdn.hexedhero.com/u/8mQxudyA2h.jpg
http://cdn.hexedhero.com/u/Sri38bjN7y.jpg
http://cdn.hexedhero.com/u/sL0uo9Tgq1.jpg
End and Nether both look like the overworld

News on the actual entity bug. It seems to be only a thing on servers when you switch servers within a bungee network and the entities are kept at the same cords they were previously. I think the easiest way to re-do this bug is go on hypixel and go into skyblock do /hub then /home then /hub and go back into skyblock, you'll see it keeps every single entity from previous servers/"worlds" and again not of these issues happen on previous editions of Forge pior the recent dimension changes. I've had a hard time trying to redo the bug on my own single server or single player
