### ISSUE TITLE
Forge 28.1.31 Missing Forge Client Resource

### ISSUE THREAD

**Issue by arduino5144** [MinecraftForge/MinecraftForge#6204]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.31

**Logs:** https://gist.github.com/arduino5144/bf532f548c0608f4b10153b566355c15

**Steps to Reproduce:**
 1. Install with installer, in new folder
 2. Launch Minecraft
 3. Read log

**Description of issue:**
Whenever I run Minecraft, it says missing resource.

**Comment by Unnoen** [comment]
Does this issue persist on the latest version of Forge? (28.1.56)
