### ISSUE TITLE
Dimensions are not working again...

### ISSUE THREAD

**Issue by Krevik** [MinecraftForge/MinecraftForge#6205]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.31

**Logs:** http://ntpd.eu/xkdpD

**Steps to reproduce:**
1. Create custom dimension and enter it
2. Exit world
3. Load world

**Description of issue:**
After re-entering custom dimension (after exiting the game) the crash happens.

**Comment by tterrag1098** [comment]
Your dimension type seems to already exist on the client before login which is an invalid state. Please show your code for registering the dimension.

**Comment by Krevik** [comment]
> Your dimension type seems to already exist on the client before login which is an invalid state. Please show your code for registering the dimension.

nvm. fixed in 28.1.34 :D I had double dimension registration - because in the other way it wasn't registred on server, so I had to register it in both: FMLCommonSetupEvent and on: RegisterDimensionsEvent. And it seems that I still need double registration.
