### ISSUE TITLE
Custom armor item implementing IDyeableArmorItem not rendering colored texture on player

### ISSUE THREAD

**Issue by keller11** [MinecraftForge/MinecraftForge#6215]
Minecraft Version: 1.14.4

Forge Version:28.1

I created a class that extends IDyeableArmorItem, and the color is implemented via code/config file. I have overridden getColor with a method that provides the correct color (as verified utilizing a logger and debug messages), overridden hasColor to be both true and false (for testing), and have overridden removeColor and setColor to be empty functions. When in the player's inventory, the color shows correctly, but when rendering on a player/armor stand, it does not tint the model, just displays the base model with no color
I should also mention that the render doesn't color when I hardcode a value for the color

**Comment by tterrag1098** [comment]
Show your code and images of what happens.

**Comment by keller11** [comment]
`
public class ItemArmorMaterial extends ArmorItem implements IItemColor, IBakedModel, IDyeableArmorItem {

    public ItemArmorMaterial(IArmorMaterial p_i48534_1_, EquipmentSlotType p_i48534_2_, Properties p_i48534_3_) {
        super(p_i48534_1_, p_i48534_2_, p_i48534_3_);
        ArmorList.ARMOR_ITEMS.add(this);
        ItemList.MATERIAL_ITEMS.add(this);
    }

    @Override
    public List<BakedQuad> getQuads(@Nullable BlockState state, @Nullable Direction side, Random rand) {
        String item = StringHelper.getItemByPath(this.getRegistryName().getPath());
        IBakedModel parent = new ItemMaterial("template_" + item);
        return parent.getQuads(state, side, rand);
    }

    @Override
    public boolean isAmbientOcclusion() {
        return false;
    }

    @Override
    public boolean isGui3d() {
        return false;
    }

    @Override
    public boolean isBuiltInRenderer() {
        return false;
    }

    @Override
    public TextureAtlasSprite getParticleTexture() {
        return null;
    }

    @Override
    public ItemOverrideList getOverrides() {
        return null;
    }



    //to color render on entity
    @Override
    public boolean hasColor(ItemStack p_200883_1_) {
        return false;
    }
    @Override
    public int getColor(ItemStack stack) {
        return ColorHelper.getIntFromHex(ResourceHelper.getResourceFromName(StringHelper.getResourceByPath(stack.getItem().getRegistryName().getPath())).getColorDetails().getPrimary());
    }
    @Override
    public void removeColor(ItemStack p_200884_1_) { }
    @Override
    public void setColor(ItemStack p_200885_1_, int p_200885_2_) { }


    @Override
    public ITextComponent getDisplayName(ItemStack itemStack) {
        return new StringTextComponent(StringHelper.getDisplayName(itemStack.getItem().getRegistryName().getPath()));

    }

    @Nullable
    @Override
    public String getArmorTexture(ItemStack stack, Entity entity, EquipmentSlotType slot, String type) {
            return slot == EquipmentSlotType.LEGS ? Reference.mod_id + ":textures/models/armor/template_layer_2.png" : Reference.mod_id + ":textures/models/armor/template_layer_1.png";
    }

    @OnlyIn(Dist.CLIENT)
    public int getColor(int layer) {
        return (layer == 0) ? ColorHelper.getColorFromItem(this, 0) : Color.WHITE.getRGB();
    }
    @Override
    public int getColor(ItemStack itemStack, int i) {
        return (i == 0) ? ColorHelper.getIntFromHex(ResourceHelper.getResourceFromName(itemStack.getItem().getRegistryName().getPath()).getColorDetails().getPrimary()) : Color.RED.getRGB();
    }
}
`
Also, `@Override
    public boolean hasColor(ItemStack p_200883_1_) {
        return true;
    }` gives the same results
![2019-10-08_17 37 21](https://user-images.githubusercontent.com/17502564/66438471-5d688880-e9f2-11e9-83c0-b7637d207a1c.png)
Armor is not rendering any color, these are the base textures.
