### ISSUE TITLE
DimensionType registry not always cleared when switching to a different world

### ISSUE THREAD

**Issue by kirderf1** [MinecraftForge/MinecraftForge#6219]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4-28.1.37

**Steps to Reproduce:**
 1. Enter a singleplayer world (world A)
 2. Register a new dimension type to world A specifically
 3. Leave world A and create a new world B **without** doing any of this in between: closing and reopening the application, or enter a different existing world.
 4. Observe that the newly created world B now also has the dimension type that was registered to world A.

**Description of issue:**
The registry with dimension types is under regular circumstances cleared on world load in `DimensionManager.readRegistry()`, right before the dimension types in the loaded world is read and created. This is the only time that the registry is cleared, and as such the registry will not be cleared in other circumstances, where the world loaded does not have the data needed to reach `DimensionManager.readRegistry()`. Or more noticeable: when creating a new world.

**Comment by cpw** [comment]
I don't think this is a regression - this seems to be the result of actually making client side dim types work. It looks like we need to freeze/unfreeze the dimtype registry on the client. Hmmmm.
