### ISSUE TITLE
[1.14.4 - 28.1.40] Launch Crash

### ISSUE THREAD

**Issue by HexedHero** [MinecraftForge/MinecraftForge#6220]
**Minecraft Version:** {Minecraft version}
1.14.4

**Forge Version:** {Forge version. *Version number, not latest/rb*}
28.1.40

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://gist.github.com/HexedHero/180bf9b5be24f646124ab61cf197a604

**Steps to Reproduce:**
 1. download and run 28.1.40
 2. crash
 3. ??

**Description of issue:**
Forge crashes on launch, doesn't on 28.1.39

**Comment by gigaherz** [comment]
Do you have Optifine installed? I believe that crash is due to optifine not being compatible with the changes in 28.1.40.
You will have to remove optifine or wait for optifine to become compatible

**Comment by HexedHero** [comment]
> Do you have Optifine installed? I believe that crash is due to optifine not being compatible with the changes in 28.1.40.
> You will have to remove optifine or wait for optifine to become compatible

Ahh, I do! Most likely that was the issue.
