### ISSUE TITLE
Grass paths lost their shading

### ISSUE THREAD

**Issue by HexedHero** [MinecraftForge/MinecraftForge#6226]
**Minecraft Version:** {Minecraft version}
1.14.4

**Forge Version:** {Forge version. *Version number, not latest/rb*}
28.1.44

**Description of issue:**
Grass paths, farmland and more have recently lost their shading in newer forge versions
forge: http://cdn.hexedhero.com/u/NpneXFoAit.jpg
vanilla: http://cdn.hexedhero.com/u/zxNks5HhUY.jpg

**Comment by DaemonUmbra** [comment]
Disabling Smooth Lighting in Vanilla produces the same effect.
(Tested in 28.1.64)

**Comment by HexedHero** [comment]
My issue has been fixed, not sure when tho
http://cdn.hexedhero.com/u/go4TGuizIN.jpg
