### ISSUE TITLE
RCON Server is broken on multiple MC Versions with Forge

### ISSUE THREAD

**Issue by iTitus** [MinecraftForge/MinecraftForge#6228]
The Minecraft RCON Server doesn't in the Forge Dev Environment.
I tested the 1.12.2 and 1.14.4. Vanilla & Forge Production Servers and they work fine.

I suspect this being a decompiler issue.
The decompiled code is a try-catch-finally statement in a while-loop with continue statements spread all over. After data is received the continue statement jumps out of the try-block and thus triggers the finally-block. There the socket gets closed and set to null, which leads to a NPE in the next loop while trying to ask the socket for more data.

Cleaned Code:
https://gist.github.com/iTitus/3f87c7e53f3775f34994dd0ff34b0b37

**Comment by iTitus** [comment]
After further testing it seems to only happen in dev environments

**Comment by iTitus** [comment]
Python Script for Testing: https://gist.github.com/iTitus/d5f1046963f4fb93e811c376e275ec56

**Comment by iTitus** [comment]
Sadly I'm don't know where to start with fixing this bug in the decompiler, so someone else with more experience needs to take a look at this.

**Comment by iTitus** [comment]
Did this get fixed in 1.14.4 by https://github.com/MinecraftForge/MCPConfig/issues/43 ?

**Comment by JDLogic** [comment]
Yes, but forge needs to update to the new MCPConfig version that has it fixed. That may take some time as I expect the team will be focusing on getting Forge for 1.15 functional, so people can start testing.
