### ISSUE TITLE
fatal error when trying to join my server

### ISSUE THREAD

**Issue by lars0hendriks** [MinecraftForge/MinecraftForge#6238]
Minecraft Version: 1.7.10

Forge Version: 1.7.10 - 10.13.4.1614

Logs: 
[fml-server-latest (1).log](https://github.com/MinecraftForge/MinecraftForge/files/3726058/fml-server-latest.1.log)

so when i'm trying to join my own server i get a fatal error anyone knows how to fix it?

**Comment by gigaherz** [comment]
The error is with Thaumcraft, not Forge. And in any case, forge for 1.7.10 has been out of support for 4 years. You should ask the modpack author, or the Thaumcraft author.
