### ISSUE TITLE
ContainedDeps/Jar-In-Jar unimplemented

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#6239]
Seems like https://github.com/MinecraftForge/MinecraftForge/blob/40bdde204321a3903ec28bf20f8bc7af92df5ad9/src/main/java/net/minecraftforge/fml/relauncher/libraries/LibraryManager.java#L80 isn't being called from anywhere.

What were the plans for this?

**Comment by fraenkelc** [comment]
The setup method still seems not to be called. Furthermore the documentation site still lists Dependency extraction as a forge feature: https://mcforge.readthedocs.io/en/1.15.x/gettingstarted/dependencymanagement/#dependency-extraction

**Comment by williewillus** [comment]
No longer need this

**Comment by fraenkelc** [comment]
@williewillus could you please point me to the commits that fixes this or the mechanism that is meant to replace jar in jar packaging ?

**Comment by williewillus** [comment]
It's not fixed
When I asked about this some months ago, the response I got basically amounted to "there's no replacement"

**Comment by gigaherz** [comment]
It's still wanted, just it appears no one has both the time to work on this, and the interest to do so.
Meanwhile you can use shading & relocation. It's not a proper replacement, but it gets things working.
