### ISSUE TITLE
[ERROR] Need help NetworkDispatcher exception error

### ISSUE THREAD

**Issue by semirotta** [MinecraftForge/MinecraftForge#6240]
**Minecraft Version:** 1.12.2

**Forge Version:** forge-14.23.5.2847

**Logs:** https://hastebin.com/bikiwificu.rb The only thing that shows something. Everything else checks out, works fine. This is the only thing that pops out.

**Steps to Reproduce:**
 1. Friend joins
 2. Friend plays
 3. Friend sometimes gets the issue

**Description of issue:** Weird time out issue on a friend of mine on our server. I've done everything I can to help him get rid of it. Not sure what is causing it. All I see is what the error throws. There are no work arounds to this what so ever, I tried increasing the time out timer but it didn't seem to help.

**Comment by DaemonUmbra** [comment]
Try making a thread on the forums with a complete debug.log
