### ISSUE TITLE
Event: EntityJoinWorldEvent not firing

### ISSUE THREAD

**Issue by lazynessmind** [MinecraftForge/MinecraftForge#6247]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4-28.1.56

**Logs:** The issue doesn't throw errors to console.

**Steps to Reproduce:**
 1. SubscribeEvent -> EntityJoinWorldEvent
 2. Log something when the entity joins the world

**Description of issue:**

When trying to check if entities joined the world using the event **EntityJoinWorldEvent**, doesn't work.

**Comment by issork** [comment]
Just switched to 28.1.56, works fine for me.

Edit: Did you make sure to subscribe the class itself to the forge event bus?

**Comment by lazynessmind** [comment]
Yes, is my main registry class. Thats weird, im gonna try again, maybe my workspace isnt setup correctly.
