### ISSUE TITLE
Forge 28.1.56 is crashing on 1.14.4 with JDK 1.8.0_231

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#6251]
**Minecraft Version:** 1.14.4

**Forge Version:** Forge version. *28.1.56*

**Logs:** https://gist.github.com/FellFromTheSky/e089429c561c8cd23e58fbc51392223d

**Steps to Reproduce:**
 1. Update Java 8 from 1.8.0_221 to 1.8.0_231
 2. Preferably use the 1.6.93 Java Launcher :
     https://minecraft.gamepedia.com/Launcher_version_history
     https://launcher.mojang.com/v1/objects/eabbff5ff8e21250e33670924a0c5e38f47c840b/launcher.jar
 3. Then install Forge 28.1.56
 4. Then install OptiFine 1.14.4 HD U F4 pre10 for 1.14.4
 5. Try to create a new world or load an existing one.
 6. The game will surely crash.

**Description of issue:**
Forge 28.1.56 is crashing on 1.14.4 with JDK 1.8.0_231.
It's due to Optifine.

**Comment by Tfarcenim** [comment]
Optifine bugs have nothing to do with Forge.

**Comment by DaemonUmbra** [comment]
> It's due to Optifine.
