### ISSUE TITLE
Feature: add Serverside Reload Event

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#6260]
Similar too #4217 but directly hooked to MiencraftServer#reload.

**Why is this needed?**
As recipes, tags and so on can now change during runtime something like this is needed to clear caches or reload custom recipes/data.

So I would like to ask what parameters could be interesting.
Do we want/need pre and post events like here: https://github.com/rguy96/MinecraftForge/commit/1aa74a4ae301363c6ea5063b506f5be5afab68f4 ?

**Comment by williewillus** [comment]
I don't see the benefit of a pre event, a post event should be enough

**Comment by mcenderdragon** [comment]
Curretnly there is a work around for this:
you can register a `IFutureReloadListener` to the `IReloadableResourceManager` of the MinecraftSever. the best time to do this is the `FMLServerAboutToStartEvent` so you also get the 1st resource load when the world is loaded.

```
IReloadableResourceManager res = event.getServer().getResourceManager();
res.addReloadListener(RELOAD_LISTENER);
```
