### ISSUE TITLE
Events not firing

### ISSUE THREAD

**Issue by lazynessmind** [MinecraftForge/MinecraftForge#6261]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4-28.1.61

**Logs:** doesnt log anything

**Steps to Reproduce:**
 ![Anotação 2019-10-21 164634](https://user-images.githubusercontent.com/52864251/67220840-6873dd80-f422-11e9-9f50-2276e5529f03.png)

**Description of issue:**

None of the events showed above prints to the console.

**Comment by Alpvax** [comment]
How are you registering that class?

**Comment by lazynessmind** [comment]
```java

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class RegistryEvents {
         
   @SubscriveEvent
   public static void nameFunctuin(Event event){

   }
}

```

**Comment by lazynessmind** [comment]
> 
> 
> How are you registering that class?

```java

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class RegistryEvents {
         
   @SubscriveEvent
   public static void nameFunctuin(Event event){

   }
}

```

**Comment by alexbegt** [comment]
The above events is fired on the forge event bus and not the mod bus.
