### ISSUE TITLE
[1.14.4] ForgeFlowingFluid.Properties missing setter for tickRate

### ISSUE THREAD

**Issue by Wabbit0101** [MinecraftForge/MinecraftForge#6272]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.39

**Description of issue:**
ForgeFlowingFluid.Properties does not have a setter for the block's tickRate. It's initialized to 5 but cannot be altered.

**Comment by gigaherz** [comment]
This is still relevant, bot, even in 1.15.

**Comment by gigaherz** [comment]
Fixed in 9a6d1c390 and 27bd0de5e
