### ISSUE TITLE
[1.14] LivingDeathEvent - DamageEvent#getTrueSource -> return null

### ISSUE THREAD

**Issue by lazynessmind** [MinecraftForge/MinecraftForge#6276]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4-28.1.64(28.1)

**Logs:** dont throw errors to console.

**Steps to Reproduce:**
 1. @SubscribeEvent LivingDeathEvent
 2. System.out.print(event.getSource().getTrueSource())
 3. prints null

**Description of issue:**

Actual code: 

```java
@SubscribeEvent
    public static void onEntityDeath(LivingDeathEvent event) {
        if (event.getEntity().world.isRemote) {
            if (event.getEntity().getType().getClassification() == EntityClassification.CREATURE) {
                System.out.println("is a creature, like a chicken");
                if(event.getSource().getTrueSource() instanceof PlayerEntity){
                    System.out.println("player is the guy: " + event.getSource().getTrueSource());
                    //...
                }
            }
        }
    }
```
`System.out.println("player is the guy: " + event.getSource().getTrueSource());`

Never prints because the getTrueSource() returns null

**Comment by diesieben07** [comment]
Client-side damage source information will always be incomplete. This is not a bug.
