### ISSUE TITLE
Modpack crashes at 2/7

### ISSUE THREAD

**Issue by FierceDragon680** [MinecraftForge/MinecraftForge#6278]
**1.7.10**

**forge 10.13.4.1558** 

**https://gist.github.com/FierceDragon680/49f2c3af6f85a8a19f14d7865ec26f66** 

Giant mod pack crashes at 2/7. not sure what mod is causing the issue. Base is CrazyCraft 3.0

**Comment by gigaherz** [comment]
This is not an issue with forge. And 1.7.10 is out of forge support in any case. Go ask the modpack authors, or the author of the mod that is causing the exception.
```
java.lang.NullPointerException
	at HxCKDMS.HxCEnchants.Keybinds.Keybinds.init(Keybinds.java:16) ~[Keybinds.class:?]
```
