### ISSUE TITLE
[1.14.4] JSON recipes overrided by forge cannot be overrided by mod

### ISSUE THREAD

**Issue by yanny7** [MinecraftForge/MinecraftForge#6287]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.70

**Steps to Reproduce:**
 1. Create recipe override for e.g. wooden axe
 2. Run game & check recipe for wooden axe
 3. Wooden axe recipe remains unchanged

**Description of issue:**
Recipes which are overrided by forge (due to extended forge tags) cannot be overrided by user recipes.

**Comment by oitsjustjose** [comment]
I just wanted to pop in and give my two cents. How are you trying to override recipes? I was successfully able to override the wooden axe recipe with no problem, see [here](https://github.com/oitsjustjose/Natural-Progression/blob/c8f86b1fca342eaf4ee4b97536a04c3b2ad9f885/src/main/resources/data/minecraft/recipes/wooden_axe.json).

**Comment by yanny7** [comment]
I used your JSON recipe, but without success. I suspect that this issue is MODID dependent - in my case I used "age_zero"

**Comment by oitsjustjose** [comment]
What do you mean modid dependent? No matter what your mod name is, you want to put your vanilla recipe override in `src/main/resources/data/minecraft/recipes/`. You should put recipes unique to *your* mod in `src/main/resources/data/age_zero/recipes/`.

**Comment by yanny7** [comment]
Problem is not where are stored, but how they are loaded by forge (or Minecraft, dont know who is responsible for loading resources)

All recipes overrides (for each mod) are stored in one List, in my case there are overrides from vanilla as default, then from my mod and at last from forge. And this is problem, because when is requested "wooden_axe" this list of resources are requested from last element and first occurence of override is returned and in my case, override from forge is returned.

So I think that for someone there is order of resources correct as in your case

See attached screenshot of debugger:
https://imgur.com/a/MfMtd6T

**Comment by intrepid249** [comment]
Just to bump this, I'm trying to remove the recipes for all the wooden tools in my mod. I'm developing for Forge 1.14.4 using the stable release. I've noticed comments about file location and things like that.

well, I've recorded a gif showing some particularly illuminating details that show that it doesn't matter about the file location. You can see that I've even tried implementing the recipe suggested in one of the earlier comments for the wooden_axe. 

So, the pickaxe, hoe, and shovel all successfully override their recipes to minecraft:air however the axe, located in the same directory does not. To prove that the vanilla method also did not work, you can see that the sword is located inside of the suggested minecraft/recipes folder and still doesn't override the recipe. Additionally, if I move the 3 working recipes to minecraft/recipes, then they no longer override the vanilla recipes

https://i.imgur.com/OuhfyfS

If this has been addressed in a more recent patch for 1.14.4 Forge, then I guess I'll have to update.

**Comment by intrepid249** [comment]
I like how this is still an issue but it's been closed without comment
