### ISSUE TITLE
[1.14.4] Interface to mark FluidBlock as one, which has a corresponding ModdedBubbleColumnBlock

### ISSUE THREAD

**Issue by oOMitchOo** [MinecraftForge/MinecraftForge#6288]
I'm not sure, how exactly Forge works and how much Minecraft Code is overwritten by it, but I've noticed that both Soul Sand and Magma Blocks use the static method BubbleColumnBlock._placeBubbleColumn_ on the BlockPos above, which then checks if there's a vanilla water source in that position.

Three small changes, would make it possible, that both Soul Sand and Magma Block can make bubble columns in modded Fluids too.

1. Make an interface IBubblyFluidBlock with one method called _getBubbleColumnPlacer_ (modders would then have to implement that interface in their bubbly fluid blocks and add their own bubble column placer [ideally their new bubble block itself] to it). _getBubbleColumnPlacer_ would return an Object of type ICanPlaceBubbleColumn, ...
2. Make an Interface ICanPlaceBubbleColumn with the two methods _placeBubbleColumn_ and _canHoldBubbleColumn_ which could stay as they are in the vanilla BubbleBlock when implemented, except it would check for the corresponding modded fluid source block and place the new modded bubble block.
3. Make Soul Sand and Magma Block in their _tick_ method check the block above, if it is the vanilla water block, call the vanilla _placeBubbleColumn_, if it is an instanceof IBubblyFluidBlock, call _getBubbleColumnPlacer().placeBubbleColumn_.

(The Magma Block would need a little change in _updatePostPlacement_ too)

It could be compacted down to one interface, which functions as the modded bubble column block placer too, but that would be less 'minecrafty'.

I've tested it in my mod (except that I had to use a modded soul sand and magma block) and it works great. But it would be so much better, if I could use the vanilla soul sand and magma block to make bubble columns in my Fluids and with those interfaces everyone could.

**Comment by TeamSpen210** [comment]
You might want to look at the slightly different approach in #5458, though that was closed due to inactivity. There it used tags instead which might be preferable if no actual code needs to be run.

**Comment by oOMitchOo** [comment]
> You might want to look at the slightly different approach in #5458, though that was closed due to inactivity. There it used tags instead which might be preferable if no actual code needs to be run.

That's a different thing though. In #5458 he wants his own blocks to make vanilla bubble blocks in vanilla Water. (this is no issue in 1.14.4 as far, as I can see. Just add a block, which calls BubbleColumnBlock._placeBubbleColumn_ **edit:** still an issue, since they destroy themselfes if not placed on Soul Sand or Magma Blocks)

I want the vanilla Soul Sand and Magma Block to NOT ONLY make vanilla bubble blocks in vanilla water, but ALSO make modded bubble blocks in modded fluids.

(if the mod author has marked that fluid(block) as one, which can make bubble columns that is.)

**Comment by oOMitchOo** [comment]
Out of a players perspective (a player, that has no experience in modding) it makes no sense, that Soul Sand and the Magma Block won't work to make bubble elevators in modded water.

And it could work... with the right interface.
