### ISSUE TITLE
Cursor Does Not Appear In GUI

### ISSUE THREAD

**Issue by GhostDog98** [MinecraftForge/MinecraftForge#6296]
**Minecraft Version:** 1.8.9

**Forge Version:** 1.8.9-forge1.8.9-11.15.1.2318-1.8.9

**Logs:** NA

**Steps to Reproduce:**
 1. Boot up Minecraft
 2. Cursor is invisible
 3. Move cursor out of minecraft window
4. Return back into it
5. Cursor is now visible

**Description of issue:**
Cursor does not show up upon boot or in gameplay UI's (Custom or otherwise), even with no mods installed, it still has this problem.

**Comment by FinnT730** [comment]
Maybe it is time to update?
And I think this is not a Forge issue, but a Vanilla bug.
We don't support anything under 1.12 anymore, so please update.

**Comment by diesieben07** [comment]
Update to a modern version.
