### ISSUE TITLE
[1.14.4] ChunkPrimerWrapper.getWorldForge() returns null instead of its Chunk's world

### ISSUE THREAD

**Issue by The-Fireplace** [MinecraftForge/MinecraftForge#6297]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4-28.1.79

**Steps to Reproduce:**
1. Call IChunk#getWorldForge() on a ChunkPrimerWrapper
2. You will get null instead of its chunk's world

**Description of issue:**
This causes problems with `ChunkEvent.Load` when the server is still starting and it loads the world, as the chunks being loaded are ChunkPrimerWrappers, so `WorldEvent.world`, which for ChunkEvents comes from `IChunk.getWorldForge()`, is null when it should not be.

Other methods in ChunkPrimerWrapper, such as getTileEntity, getBlockState, getFluidState, etc, all do `this.chunk.whateverMethod`, so I believe the same should be done for getWorldForge.

**Comment by tterrag1098** [comment]
I'd say the problem is that the load event is fired with incomplete chunks. `getWorldForge` is properly nullable for this case.

**Comment by The-Fireplace** [comment]
Though I do take your point, and agree that the load event shouldn't be fired for incomplete chunks, I'd also say that even though it's properly nullable, there is a value for World in that case so it should be provided rather than null.

**Comment by LexManos** [comment]
Chunk Primers do not have a valid world context. That is the reason this has the nullable marker. Also this particular function is for internal use hence the Forge suffix instead of a clean name. But that's not important.
