### ISSUE TITLE
JVM hang during worldgen on latest Forge (no mods)

### ISSUE THREAD

**Issue by drekryan** [MinecraftForge/MinecraftForge#6305]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.86 (vanilla forge with no mods)
**Logs:** I seem to just hang and don't believe a crash report is being generated

**Steps to Reproduce:**
 1. Create a new creative world with the following seed 1822390592933872730
 2. Load into the world
 3. profit... I seem to get a JVM hang at this point

**Description of issue:**
This issue where the JVM hangs seems to happen on the generation of some chunks but I believe to have found a seed where this is reproducible with the spawn chunks (ie. when loading into the world the first time)

It also appears to be a regression between forge 28.1.70 as I don't experience the issue on that version. Maybe a change since then has caused this issue.

**Comment by williewillus** [comment]
related to https://github.com/Vazkii/Quark/issues/1649

suspected to be related to the lighting changes in 81

profiler capture during the hang (it happened clientside for me): https://cdn.discordapp.com/attachments/454376090362970122/642050562359033856/unknown.png

**Comment by octylFractal** [comment]
Can confirm as well, clientside hang for me as well while using WorldEdit: ![profiler capture](https://drive.google.com/uc?id=1bIZUL-z6llcVgvJsigmWTFN44fI9LB6H)
