### ISSUE TITLE
Crash when trying to attach YourKit profiler agent at startup

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#6306]
**Minecraft Version:** 1.14.4

**Forge Version:** 85

**Logs:** https://gist.github.com/williewillus/d49cfd62ad682a5b1453ac8efdaf6635

**Steps to Reproduce:**
 1. Install yourkit
 2. Add `-agentpath:C:\PROGRA~1\YOURKI~1.1-B\bin\win64\yjpagent.dll=delay=30000` to JVM args (change as appropriate for your install)
 3. Launch game

**Description of issue:**
Crash. Seems really weird/fishy. Either a really bad bug in eventbus or the loader/transformer systems, or just an incompatibility with the profiler agent. I remember this working properly in older versions of MC though, so consider it a regression.

**Comment by LexManos** [comment]
Feel free to yell at TypeTools to fix it.
Or yell at YourKit to stop breaking class structure.
Either way its just another instance of the lambda 'helper' functions having situations where it doesn't work.

**Comment by mixxit** [comment]
also having this

**Comment by andrewsf** [comment]
I can't see the gist above anymore, but assuming it's the same issue I hit in 35.1.4 (1.16.5), I can launch w/ JDK 8 by [disabling object allocation recording and CPU tracing](https://www.yourkit.com/docs/java/help/startup_options.jsp), e.g.:

```
-agentpath:C:\progra~1\YOURKI~1.9-B\bin\win64\yjpagent.dll=disablealloc,disabletracing
```

You do have to disable _both_ of these features.
