### ISSUE TITLE
Multiplicative Swim Speed

### ISSUE THREAD

**Issue by tyler489** [MinecraftForge/MinecraftForge#6309]
**Minecraft Version:** {Minecraft version} 1.12.2

**Forge Version:** {Forge version. *Version number, not latest/rb*}
Reported with 14.23.5.2847
Reproduced with 1.12 - 14.21.1.2443
**Logs:** 
n/a
**Steps to Reproduce:**
 1. Make a mod that modifies swim speed
2. enchant boots with depth strider
 3. you go lighting fast in water faster than chunks will load
**Description of issue:**
SWIM_SPEED attribute is applied by multiplication to the entity speed values after friction is applied in net.minecraft.entity.EntityLivingBase.moveRelative which is called by net.minecraft.entity.EntityLivingBase.travel which already muliplies the DepthStriderModfier into friction. 
The DepthStriderModifer  is Multiplied with the SWIM_SPEED attribute plus DepthStrider that gives ludicrous speed

reported by @Karthas077

**Comment by LetterShapedGlyphs** [comment]
This sounds to me like this is behaving as expected. but I really can't be sure because you don't say how much you modify it by in the steps to reproduce. How much are you increasing it by? 10%? 100%? 1000%?


Because swim speed and friction are both multipliers, it doesn't matter what order you apply them in (1 * 0.02 * 2 = 1 * 2 * 0.02)
Even at Depth Strider 3 (and walking on the sea floor), that just means you're now moving at a multiplier of your land speed.

**Comment by tyler489** [comment]
That is not quite correct. Having depth strider causes the term 0.02F + (this.getAIMoveSpeed() - 0.02F) * DepthStriderModifier / 3.0F; to be multiplied with the swim speed attribute instead of 0.02F. With a full level 3 depth strider and without sprinting, that term is 50 times bigger than without.
Ender IO's modifier is +1.0 

This then gets worsened by the fact that people have a normal speed boost enabled, which is not usually in effect while swimming, but comes in from getAIMoveSpeed() with depth strider...

**Comment by LetterShapedGlyphs** [comment]
> Having depth strider causes the term 0.02F + (this.getAIMoveSpeed() - 0.02F) * DepthStriderModifier / 3.0F; to be multiplied with the swim speed attribute instead of 0.02F.

That's... not what happens.

With the Swim_Speed attribute, Depth Strider causes you go from `movement * 0.02F * SwimMultiplier` to `movement * this.getAIMoveSpeed() * SwimMultiplier`

Without the Swim_Speed attribute, Depth Strider causes you to go from `movement * 0.02F` to `movement * this.getAIMoveSpeed()`

It's still just multiplying both circumstances by the swim multiplier. A 2x boost is still a 2x boost.
