### ISSUE TITLE
PacketBuffer#readString is client side only!

### ISSUE THREAD

**Issue by owmii** [MinecraftForge/MinecraftForge#6314]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.87

`PacketBuffer#readString` has an unnecessary `@OnlyIn(Dist.CLIENT)` annotation, this will cause a lots of server crashes that the mod-devs will not notice until someone use there mods in a dedicated server.

**Comment by DaemonUmbra** [comment]
`@OnlyIn` is not a choice thing, it's a marker symbolizing what is in each distribution of Minecraft (Server/Client).
If something is marked with `@OnlyIn(Dist.CLIENT)` it means that this field, method, or class is NOT PRESENT in the SERVER Dist.
If this particular marker was applied in error, please provide evidence as such.

**Comment by Tfarcenim** [comment]
It was probably present in the original source code but proguard stripped it out in the server dist because it wasn't used there.

**Comment by pupnewfster** [comment]
I don't remember how injecting JavaDoc comments works, but it might make sense to add one with a warning pointing out that the method is only available on the client. Just so it is *slightly* easier for people to notice if they are looking at the javadocs for a specific method in their IDE without viewing the source (as the annotation would not show up via the javadoc preview).

**Comment by desht** [comment]
There's also an argument that this method *shouldn't* be present on the server, since it could allow malicious (grossly oversized) client packets to cause server memory issues.  Note that there is also a `PacketBuffer#readString(int maxlen)` method which *is* present on the server-side, which should really be used by a careful mod maker.
