### ISSUE TITLE
Translucent blocks should be able to specify if they should render the water texture on the sides when submerged

### ISSUE THREAD

**Issue by Vazkii** [MinecraftForge/MinecraftForge#6319]
Currently, vanilla hardcodes which blocks should not render the flowing water texture in FluidBlockRender line 232.

![image](https://user-images.githubusercontent.com/1794735/68941578-237f6480-079e-11ea-8f86-168f391ab4bb.png)

Relevant Issue: https://github.com/Vazkii/Quark/issues/1672

**Comment by pupnewfster** [comment]
Was looking back through the issues, and this can probably be closed given 31.1.1 implements this <https://github.com/MinecraftForge/MinecraftForge/commit/f93289e01c7a5a36aa8105c5ade2eb8402a6a49c>
