### ISSUE TITLE
[1.14.4] Mod resources not loaded during data generation

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#6322]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.90

**Logs:** https://gist.github.com/Choonster/2ee4d06856ca409f85b89728e9ddd47e

**Steps to Reproduce:**
 1. Create a class that extends `BlockStateProvider` and register it during `GatherDataEvent`
 2. In the `registerStatesAndModels` method, call `BlockStateProvider#simpleBlock(Block)` with a block belonging to the mod being developed.
3. The call to `ModelBuilder#texture` (in the methods called by `BlockStateProvider#simpleBlock(Block)`) throws an exception like the following: `IllegalArgumentException: Texture <texture> does not exist in any known resource pack`

See my [test mod](https://github.com/Choonster-Minecraft-Mods/ForgeBlockstateDataGeneratorTestMod) for a full demonstration of this.

**Description of issue:**
Mod resources aren't being loaded during data generation, so `ModelBuilder#texture` throws an exception saying that the texture doesn't exist for texture files that actually do exist.

**Comment by HyCraftHD** [comment]
You need to add this to your build.gradle. Then it should find the existing resource pack:
https://github.com/MC-U-Team/Useful-Backpacks/blob/32922cd74ddb41f04897613dee301dd392fc3b88/build.gradle#L67

**Comment by Choonster** [comment]
@HyCraftHD Thanks, that fixes it.

The MDK's **build.gradle** should probably be updated to include that argument or it should have a default value set in the data generator code itself.

**Comment by DaemonUmbra** [comment]
Like this?
https://github.com/MinecraftForge/MinecraftForge/blob/5d622610826b8217d7ecc5d5b3cc19882ba26ff3/mdk/build.gradle#L77

**Comment by Choonster** [comment]
@DaemonUmbra That's where the argument would go, but it doesn't specify the `--existing` argument at the moment.

**Comment by DaemonUmbra** [comment]
Oh, I missed that bit
