### ISSUE TITLE
[1.14.4] Server list says "Server mod list is not compatible" if the server is missing clientside-only mods

### ISSUE THREAD

**Issue by aaronhowser1** [MinecraftForge/MinecraftForge#6329]
**Minecraft Version:** 1.14.4

**Forge Version:** forge-28.1.93

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Make a modpack that has clientside mods
 2. Make a server using it, remove the clientside mods from it
 3. Add that server to the server list of a client that has the clientside mods

**Description of issue:**
![](https://cdn.discordapp.com/attachments/372214002719391745/647939987500826637/unknown.png)
![image](https://user-images.githubusercontent.com/15698722/69495512-4d671400-0e8d-11ea-96af-f7294108df05.png)
![image](https://user-images.githubusercontent.com/15698722/69495516-53f58b80-0e8d-11ea-9787-06d30a22993d.png)

**Comment by JoJoDeveloping** [comment]
Well, it shouldn't. Can you tell us which modpack you are using? It's quite likely that there actually is a mod that doesn't correctly implement the compatibility check functions, leading forge to assume it's not compatible.

Alternatively, post a debug.log, because that contains further information about what mods cause rejection and why..

**Comment by aaronhowser1** [comment]
The modpack is unreleased, but here's the modlist:
![image](https://user-images.githubusercontent.com/15698722/69548372-d9943c80-0f5c-11ea-9d9e-5e932bee2822.png)

I'll be able to post the debug.log later

**Comment by aaronhowser1** [comment]
[Here is the debug.log](https://s1.sunekaer.com/files/debug.log)

**Comment by JoJoDeveloping** [comment]
Your log seems to be the server log yet the information about why the client is misprocessing the data is found in the client debug.log

**Comment by aaronhowser1** [comment]
Oh right, sorry. Here's my client's 
[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/3888379/debug.log) from launching the game, opening the multiplayer menu (but not joining), and then going to resource packs to more quickly get the file.

**Comment by JoJoDeveloping** [comment]
Thank you. There are several problems I see here - one is that dcintegration apparently sends itself across the network which it shouldn't..
Apart from that some other client mods also apparently have DISPLAYTEST extensionpoint registered which indicates failure although I can't see which from the debug log. I'll test this some more. It'ld be helpful if you could release the mods list in a more usable format.

**Comment by aaronhowser1** [comment]
Here's all the file names

- AmbientSounds_v3.0.14_mc1.14.4.jar                                    
- AppleSkin-mc1.14.4-forge-1.0.12.jar                                   
- bambooeverything-1.14-1.4.0.jar                                       
- BetterCaves-1.14.4-1.0.1.jar                                          
- BetterThanBunnies-1.14.4-1.2.0.jar                                    
- BetterThanLlamas-1.14.4-1.1.0.jar                                     
- ChunkNoGoByeBye-1.14.4-1.0.3.jar                                      
- Clumps-4.0.0.jar                                                      
- CobbleForDays-1.0.2.jar                                               
- cofh_core-1.14.4-0.1.1b.jar                                           
- comforts-FORGE-1.14.4-2.0-beta4.jar                                   
- Controlling-5.0.4.jar                                                 
- CraftingTweaks_1.14.4-10.1.4.jar                                      
- create-mc1.14.4_v0.1.1a.jar                                           
- CyclopsCore-1.14.4-1.6.0.jar                                          
- Ding-1.14.4-1.1.0.jar                                                 
- earthmobsmod-1.14.4-0.1.0.4-Beta.jar                                  
- embellishcraft-1.14.4-1.3.1.jar                                       
- ensorcellation-1.14.4-0.1.1b.jar                                      
- EverlastingAbilities-1.14.4-1.6.0.jar                                 
- FastFurnace-1.14.4-2.2.4.jar                                          
- FastLeafDecay-v17.jar                                                 
- FastWorkbench-1.14.4-2.1.4.jar                                        
- findme-1.14.4-1.1.0.13.jar                                            
- FTBUtilitiesBackups-2.0.0.11.jar                                      
- furniture-7.0.0-pre12-1.14.4.jar                                      
- Harvest-forge-1.14.4-1.2.10-23.jar                                    
- healingcf_1.14-1.7.jar                                                
- inventorysorter-1.14.4-16.2.0.jar                                     
- jei-1.14.4-6.0.0.25.jar                                               
- JustEnoughResources-1.14.4-0.10.0.66.jar                              
- MCFurnace-1.14.4-DEV-1.3.2.jar                                        
- modnametooltip_1.14.3-1.12.1.jar                                      
- moreoverlays-1.16.1.jar                                               
- Morpheus-1.14.4-4.2.43.jar                                            
- mysticallib-1.14.4-1.8.0.jar                                          
- mysticalwildlife-1.14.4-1.3.3.jar                                     
- mysticalworld-1.14.4-1.6.10.jar                                       
- nhacampfire_1.14-1.5.jar                                              
- nifty-1.14.4-2.7.1.jar                                                
- Placebo-1.14.4-2.3.5.jar                                              
- quartz-chests-1.0.0.1.jar                                             
- seals-1.14.4-1.0.2.jar                                                
- ShadesOfNether-0.1.jar                                                
- SimpleDiscordRichPresence-1.0.2.jar                                   
- SimpleStorageNetwork-1.14.4-0.1.0.jar                                 
- simplylight-0.9.0.jar                                                 
- speedyhoppers-1.14.4-7.jar                                            
- StevesFactoryManager-1.14.4-3.0.0-alpha19.jar                         
- StoneChest-1.14.4-1.0.1.jar                                           
- StorageDrawers-1.14.4-6.0.5.jar                                       
- theoneprobe-1.14-1.4.37.jar                                           
- tombstone-4.1.7-1.14.4.jar                                            
- TOOLKIT-1.2.0.jar                                                     
- watercan-1.14.4-2.1.0.jar                                             
- wildnature-2.0.5.jar

**Comment by JoJoDeveloping** [comment]
Yeah, so downloading these mods manually (which took about an hour), and looking at the data coming from your server shows that there are three mods not playing nice:
* AmbientSounds
* MoreOverlays
* DiscordIntegration

MoreOverlays can be run on the server, where it won't do anything (also not taking up any resources). AmbientSounds says it's client side only via mods.toml, but that is actually not something you can specify in there.  So you should be able to also run it on the server, where it will not take up any ressources, not do anything but stop the client mod from being confused about it's server side missing.
DiscordIntegration is the tricky one - IDK how it handles being installed on the client.


But apart from that these mods should be aware of the fact that they're supposed to be client side only. However they're naughty and do not override the DISPLAYTEST extensionpoint, where they would have the option of not interfering with the client compatibility checking. So if you want this fixed and the mods can't simply be put onto the server, go yell at their authors.

**Comment by aaronhowser1** [comment]
bad bot

**Comment by phit** [comment]
would be nice to show in the log like in previous versions which mods are incompatible, so one can go yell at the devs to set DISPLAYTEST
