### ISSUE TITLE
Unbound keys show up as conflicting keys

### ISSUE THREAD

**Issue by Naxanria** [MinecraftForge/MinecraftForge#6333]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.93

**Description of issue:** 
The unbound keys show up as having conflicts when showing the conflicts
![image](https://user-images.githubusercontent.com/3246224/69498106-88e0fd00-0ee4-11ea-84e4-ca72a48a4ede.png)

**Comment by DaemonUmbra** [comment]
Do you have [Controlling](https://www.curseforge.com/minecraft/mc-mods/controlling "Controlling on CurseForge") installed? To my knowledge "show conflicts" is part of Controlling, not Forge.

**Comment by TeamSpen210** [comment]
No, it's definitely either Forge or even vanilla.

**Comment by DaemonUmbra** [comment]
Ok so I may be misunderstanding.
Do you mean there is a checkbox to filter to conflicting keys, or do you mean the red text?

**Comment by TeamSpen210** [comment]
A checkbox to show conflicting keys no, so that would be that mod or something like it.

**Comment by DaemonUmbra** [comment]
The screenshot provided doesn't really help much, as I can see conflicting keys, unbound controls, and controls that are bound and not conflicting.

**Comment by Naxanria** [comment]
Oh yes, Controlling is installed. I thought it was forge providing that functionality. My apologies.
