### ISSUE TITLE
[1.14.4] Mod structures listed under minecraft namespace in /locate

### ISSUE THREAD

**Issue by daedalus4096** [MinecraftForge/MinecraftForge#6336]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.0

**Logs:** n/a

**Steps to Reproduce:**
 1. Register a custom Structure feature for world gen
 2. Run the game
 3. Type /locate and examine suggestion list

**Description of issue:**
When creating a custom structure and attempting to find it with the /locate command, the structure is listed by name, but with the "minecraft" namespace in its resource location instead of the appropriate mod ID.  This can lead to player confusion and/or name conflicts.

The problem appears to be in net.minecraftforge.registries.GameData$FeatureCallbacks#onAdd.  The key passed to Registry.register on line 636 is simply the string structure name, instead of a full ResourceLocation object with the structure's registered namespace.

Example case shown below, with my mod's Primal Shrine structure:
![2019-11-28_17 44 25](https://user-images.githubusercontent.com/1577528/69838475-8e9e5180-1208-11ea-9232-e381e3112b7b.png)

**Comment by daedalus4096** [comment]
This issue still appears to exist in Forge 31.2.0 for Minecraft 1.15.2.  Attached is a screenshot of the locate menu with the inappropriately namespaced structure.
![2020-06-02_22 39 49](https://user-images.githubusercontent.com/1577528/83599985-662e4180-a522-11ea-8d83-5a1e7f65708d.png)

**Comment by tterrag1098** [comment]
This is a mod issue. That's the only name available. Add the correct namespace to it.
