### ISSUE TITLE
Unable to overwrite vanilla loot

### ISSUE THREAD

**Issue by Athamax** [MinecraftForge/MinecraftForge#6341]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.96

**Steps to Reproduce:**
 1. Put a custom lootpool grass.json into data.minecraft.loot_tables.blocks
 2. Run the client
 3. The content of grass.json is ignored, because grass retains the vanilla loot pool.

**Description of issue:**
I cannot find a way to edit what grass drops when broken. It seems to retain the vanilla loot. I can't find any other way than this suggested online and there is no documentation on the matter. This should work, but it doesn't appear to.

**Comment by DaemonUmbra** [comment]
I'm not seeing this issue, please make a thread on the forums and provide your datapack so we can sort out what's wrong with your datapack.
