### ISSUE TITLE
Outdated AT version

### ISSUE THREAD

**Issue by someaddons** [MinecraftForge/MinecraftForge#6343]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.96

**Description of issue:** Forge is downloading the old 0.1.14 version of the AT instead of using the latest, which fixed the final removal issue. https://github.com/MinecraftForge/AccessTransformers/issues/8

**Comment by LexManos** [comment]
```json
        {
            "name": "net.minecraftforge:accesstransformers:1.0.1-milestone.0.1+94458e7-shadowed",
            "downloads": {
                "artifact": {
                    "path": "net/minecraftforge/accesstransformers/1.0.1-milestone.0.1+94458e7-shadowed/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar",
                    "url": "https://files.minecraftforge.net/maven/net/minecraftforge/accesstransformers/1.0.1-milestone.0.1+94458e7/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar",
                    "sha1": "88bab5e041ae458e6b2cd6bc4de6c3d738def6b6",
                    "size": 444436
                }
            }
        },
```
Straight from 96's version.json, so no.. it's using the fixed version.

**Comment by Unnoen** [comment]
I had to re-clone the MinecraftForge repo and I can confirm it's still using 0.14.4 (At least the forgedev is.)

https://gist.github.com/Unnoen/5a6d8bd79412bbfe78253210f52be826

**Comment by Unnoen** [comment]
The installer (forge-1.14.4-28.1.101-installer.jar) does indeed download the correct version however.

**Comment by Unnoen** [comment]
Turns out version doesn't matter for Forgedev, but I can also confirm it's working fine for the installer, you need more information for this issue if it continues.
