### ISSUE TITLE
Fake Player NPE on potion added

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#6358]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.106

**Logs:** https://gist.github.com/Darkhax/e78af4d1cfe560c1f530ffe21b106a50

**Steps to Reproduce:**
 1. Create a fake player, and have it tied to something that does damage. Like a player damage spike.
 2. Summon a bunch of pillager entities around the tile and have them be killed.
 3. Eventually a pillager with a banner will spawn. Killing this pillager gives the bad omen potion effect.
4. When the bad omen potion effect is applied, it will try to send a potion update packet. This causes a NPE.

**Description of issue:** The default implementation of fake player does not account for potion effects being added to them or the resulting packet that is sent. This can cause a NPE under a common use case for fake players.

**Comment by pupnewfster** [comment]
It probably would be better to get this fixed in forge itself, but overriding this method in FakePlayer:
```java
public boolean isPotionApplicable(@Nonnull EffectInstance effect) {
    return false;
}
```
does end up working as a patch for this.

**Comment by Tfarcenim** [comment]
I have a fix for this bit of annoyance https://github.com/Tfarcenim/SpikeTraps/blob/master/src/main/java/com/tfar/spiketraps/LessCrashProneFakePlayer.java

**Comment by Darkhax** [comment]
@Tfarcenim Creating a new fake player object for every damage tick should probably be avoided. Forge's FakePlayerFactory solves this issue, but does not allow for modded variants at the moment.

**Comment by Tfarcenim** [comment]
Yes, it's an ugly fix, but it stops the crash reports and I hope a proper fix comes in forge soon so I can remove it.

**Comment by pupnewfster** [comment]
You can do your own handling just updating a singular FakePlayer, and using WeakReferences. This is what Mekanism has done since 9.7.0 in 1.12.2 https://github.com/mekanism/Mekanism/blob/1.14.x/src/main/java/mekanism/common/MekFakePlayer.java

**Comment by Shadows-of-Fire** [comment]
My solution to this in clickmachine has been to apply this https://github.com/Shadows-of-Fire/ClickMachine/blob/1.14/src/main/java/shadows/click/util/NetHandlerSpaghettiServer.java to the fake player.  This also resolves crashes associated with a fake player trying to open a container.

**Comment by Darkhax** [comment]
This issue is still relevant and reproducible on 1.15.2 31.2.x
