### ISSUE TITLE
[1.15] Installer fails to download required libraries.

### ISSUE THREAD

**Issue by Unnoen** [MinecraftForge/MinecraftForge#6360]
Some libraries required for Forge 1.15 are not in the Forge maven causing the installer to fail.

Libraries:
```
org.ow2.asm:asm:7.2
org.ow2.asm:asm-commons:7.2
org.ow2.asm:asm-tree:7.2
com.electronwill.night-config:core:3.6.2
com.electronwill.night-config:toml:3.6.2
net.jodah:typetools:0.6.1
```

This issue is acting as a tracker and catch-all for people who may come here to create an issue, the Forge team is aware of this problem.

**Comment by LexManos** [comment]
I uploaded them

**Comment by Unnoen** [comment]
Yep, working.
