### ISSUE TITLE
[1.15.1] Incorrect "partialTicks" when calling ForgeHooksClient.dispatchRenderLast

### ISSUE THREAD

**Issue by thexaero** [MinecraftForge/MinecraftForge#6380]
**Minecraft Version:** 1.15.1

**Forge Version:** 30.0.11

**Description of issue:** 
A wrong variable is used as an argument for _partialTicks_ when calling _ForgeHooksClient.dispatchRenderLast_ in _GameRenderer_.

**Comment by Thutmose** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch#L43

Here is the offending line, it is still present in forge 31.1.0

**Comment by maxanier** [comment]
@gigaherz You are the (new) master of rendering and have write permission, right?
Could you have a look at this and do a quick fix, if you have time. Not really worth doing a PR for this.

In the line Thutmose linked the `finishTimeNano`(`p_228378_2_`) should probably be `partialTicks`(`p_228378_1_`)

**Comment by sciwhiz12** [comment]
This issue has been fixed as of 31.1.19, which merged #6536 (see the second commit).
