### ISSUE TITLE
AccessTransformers are not loaded from modjar

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#6384]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.107

**Logs:** https://gist.github.com/mcenderdragon/baa0fb83494358811a2bdb7bdbaf2d84

**Steps to Reproduce:**
 1. make an AT (my_at.cfg)
 2. add via `setAccessTransformers sourceSets.main.resources.files.findAll{it.name.endsWith("_at.cfg")}.toList()`
 3. tranform a field `public-f net.minecraft.world.World field_72986_A # worldInfo`
 4. access field from your mod
 5. build the mod
 6. it crashes when your mod tries to access the field

**Description of issue:**
the my_at.cfg is inside the build jar (/META-INF/my_at.cfg) but gets not loaded and is also not linked from any file.

**Comment by mcenderdragon** [comment]
Maybe this is still this: https://github.com/mezz/JustEnoughItems/issues/1512#issuecomment-473707301

> I dug real deep into this and it seems mod ATs do not get applied unless their AT file is named accesstransformer.cfg

**Comment by mcenderdragon** [comment]
1.14.x is affected: https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java#L137
1.15.x is also affected: https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java#L137

**Comment by gigaherz** [comment]
Err, if my understanding is correct, the file MUST be called  `accesstransformer.cfg`, no other filename will work on the jar. You can use the gradle processResources task to rename / combine the AT files, if you need to.

**Comment by mcenderdragon** [comment]
IMO when we even have the ability to have mutliple AT, we should also have something like this already in place. In forge Gradle I mean. Maybe I make a PR to add this...

**Comment by LexManos** [comment]
The file must be named correctly as that is the only file fml will find at runtime.
