### ISSUE TITLE
Remove the sidedness from IArmorMaterial.getName

### ISSUE THREAD

**Issue by Wabbit0101** [MinecraftForge/MinecraftForge#6385]
For modded armor materials there is no way to examine the name for commonality (eg. "Steel" or "Emerald") between mods. ArmorMaterial is not extended via IExtensibleEnum so the builtin ArmorMaterial enum only ever refers to vanilla materials even if examined via reflection.

**Comment by DaemonUmbra** [comment]
Sidedness is not something we control, if something has ``@OnlyIn(Dist.XXXXX)`` on it, it means that method is "physically" only on that side.

**Comment by tterrag1098** [comment]
It is possible to change the sidedness of methods (we do so in many situations), however I'm not sure that `getName` would be valuable on the server. The only real use seems to be for generating texture paths, the name might more accurately be `getTextureName`. IArmorMaterial is not a registry and there is no real use in determining "commonality" between mods.

**Comment by DaemonUmbra** [comment]
Today I learned

**Comment by Wabbit0101** [comment]
The commonality in my particular case is used explicitly on the server -- to determine cost/value ranges for different categories of materials. Rather than having tag groups from hell (one per type of possible thing made of that material), the idea was to have a cost per general categories of materials (so repairing or enchanting or leveling-up an "iron" thing is less expensive than doing a "steel" thing whatever that thing might be).

**Comment by Shadows-of-Fire** [comment]
It may be valuable to provide a registry or otherwise require an identifier for materials (both armor and tools)
I found myself needing to strip config options that allowed users to change possible random names and enchantability of items based on material, since there is now no way to tell what a material is.
