### ISSUE TITLE
LootTableLoadEvent not firing on 1.12

### ISSUE THREAD

**Issue by el-germi** [MinecraftForge/MinecraftForge#6386]
**Minecraft Version:** 1.12.2

**Forge Version:** 14.23.5.2846

**Logs:** N/A, nothing happens

**Steps to Reproduce:**
```
@EventBusSubscriber
public class RegistryHandeler {
//(...)
	@SubscribeEvent
	public void onLootTablesLoaded(LootTableLoadEvent e) {
		System.out.println("never got here");
		FMLCommonHandler.instance().exitJava(-1, true);
	}
}
```

**Description of issue:**
the LootTableLoadEvent never fires, not on minecraft launch, not on server start, and not on /reload
i want to use the event to add custom loot to "minecraft:chests/simple_dungeon", but the event never enters (I added the exitJava to see if it would do something)

**Comment by Tfarcenim** [comment]
![unknown](https://user-images.githubusercontent.com/44327798/71380546-9f3eaf00-259d-11ea-8784-9ed3f81ec484.png)

**Comment by el-germi** [comment]
OMG I'm so sorry :C
