### ISSUE TITLE
[1.15] CompositeModel does not stitch textures from submodels

### ISSUE THREAD

**Issue by Snownee** [MinecraftForge/MinecraftForge#6388]
**Minecraft Version:** 1.15.1

**Forge Version:** 30.0.15

**Description of issue:**
https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/src/main/java/net/minecraftforge/client/model/composite/CompositeModel.java#L231
I think there is something missing

**Comment by gigaherz** [comment]
Found the issue. And found some other issues while debugging this. Fix coming soon.

**Comment by gigaherz** [comment]
Should be fixed in e8ce61d4
