### ISSUE TITLE
Javadoc or Source-level annotation for methods and fields which holds the obfuscated/srg names of those members, as well as its index

### ISSUE THREAD

**Issue by VinyarionHyarmendacil** [MinecraftForge/MinecraftForge#6392]
Not a PR because it would add to literally every single patch and could break easily.
This would be useful for modders wishing to write Reflection code that can run both in the development environment and after it is distributed. Looking up obfuscated names can be annoying sometimes.
Yes, the more "hacky" mods get, the less compatible they become, but this could also be useful to fix such problems more easily.

**Comment by LexManos** [comment]
No, its probably nothing but spam and easily looked up yourself with the bot. Plus, doing so does nothing but encourage people to use hacky systems like reflection instead of using proper accessors or api's we have in place.

**Comment by VinyarionHyarmendacil** [comment]
Fair enough. Thanks anyways.
