### ISSUE TITLE
EntityEvent.CanUpdate is never called

### ISSUE THREAD

**Issue by coderbot16** [MinecraftForge/MinecraftForge#6394]
**Minecraft Version:** 1.14, 1.15

**Forge Version:** all 1.14 and 1.15 versions up to and including https://github.com/MinecraftForge/MinecraftForge/commit/e8ce61d4cd2de3250a27b1d4b8aa20d88e53c0d7

**Logs:** not applicable

**Steps to Reproduce:**
 1. Search for construction of `EntityEvent.CanUpdate` and see that it is only ever created in `ForgeEventFactory#canEntityUpdate`
2. Search for uses `ForgeEventFactory#canEntityUpdate` and see that no patch ever calls it

**Description of issue:**

It appears that this event was forgotten during the move to 1.13. To avoid confusion, it should be commented out until it is properly implemented, or if there are no plans to implement it, it should be removed.

**Comment by bl4ckscor3** [comment]
In 1.14 and 1.15 there's Entity#canUpdate.

**Comment by coderbot16** [comment]
It seems like it would make sense to just flat out remove this event in that case.

**Comment by coderbot16** [comment]
> If this issue is still relevant and should remain open, please reply with a short explanation

I have checked the code and have verified that EntityEvent.CanUpdate is still never called. It would probably be better to comment out the event or remove it instead of leaving it around, otherwise people may try to use it without realizing that it is never called.

**Comment by coderbot16** [comment]
Still an issue

**Comment by Shadows-of-Fire** [comment]
This should be handled by #7916 when that gets completed.

**Comment by sciwhiz12** [comment]
This event has been removed in 1.19.
