### ISSUE TITLE
[1.15] Mod list screwed up

### ISSUE THREAD

**Issue by Water-Moon** [MinecraftForge/MinecraftForge#6397]
**Minecraft Version:** 1.15

**Forge Version:** 1.15-29.0.4, under DEV environment

**Logs:** N/A

**Steps to Reproduce:**
 1. Load Minecraft
 2. Open "Mods" screen
 3. this shows up
![图片](https://user-images.githubusercontent.com/43123946/71563366-43bc6780-2a5c-11ea-89c8-29a7ec7626ee.png)

**Description of issue:**
the sidebar for mod name is just messed up

**Comment by Unnoen** [comment]
Update to 1.15.1 builds, this was fixed very early on.
