### ISSUE TITLE
Modded shears get dropped from dispensers instead of shearing the target entity.

### ISSUE THREAD

**Issue by coderbot16** [MinecraftForge/MinecraftForge#6409]
**Minecraft Version:** 1.14, 1.15

**Forge Version:** All 1.14 and 1.15 versions up to and including https://github.com/MinecraftForge/MinecraftForge/commit/1e053298be3bf36c0e09929c7513297befa99b9e

**Logs:** No crash is triggered, no relevant log messages are produced.

**Steps to Reproduce:**
 1. Get a mod that adds shears, such as [SBM Wooden Shears](https://www.curseforge.com/minecraft/mc-mods/sbm-wooden-shears).
 2. Place one of the shears it adds into a dispenser.
 3. Place a sheep in front of the dispenser.
 4. Power the dispenser with a torch or lever.
 5. Observe that the shears are dispensed out of the dispenser and that the sheep remains unsheared.

**Description of issue:** Vanilla hardcodes the shears dispenser behavior to only work with vanilla shears:

```java
DispenserBlock.func_199774_a(Items.field_151097_aZ.func_199767_j(), new OptionalDispenseBehavior() {
```

Or, translated into Yarn names:

```java
DispenserBlock.registerBehavior(Items.SHEARS.asItem(), new FallibleItemDispenserBehavior() {
```

**Solution:** Patch `DispenserBlock#getBehaviorForItem` (or the equivalent MCP name) to return the proper behavior for all instances of `ShearsItem`: 

```java
Item item = stack.getItem();

if(item != Items.SHEARS && item instanceof ShearsItem) {
	return BEHAVIORS.get(Items.SHEARS);
}
```

**Comment by KingLemming** [comment]
Can't mods just add their own dispenser behaviors?

**Comment by coderbot16** [comment]
That would definitely be possible, but if so that should be documented somewhere. It seems like modders expect that extending `ShearsItem` will work automatically.

**Comment by LexManos** [comment]
Nothing in the dispenser system shows any indication that class inheritance would be taken into account.
It is on the modder to register behaviors for their items.
