### ISSUE TITLE
[1.14.4] getSaveHandler().getWorldDirectory() world change doesn't work

### ISSUE THREAD

**Issue by Edivad99** [MinecraftForge/MinecraftForge#6415]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.4 - 28.1.111

**Logs:**
https://github.com/Edivad99/DimStorage/blob/d828aa262b5afac3fb1c433820d2c215898b6e21/src/main/java/edivad/dimstorage/manager/DimStorageManager.java#L105

**Steps to Reproduce:**
 1. Create a world
 2. Check what the function I linked returns
 3. Get out of the world
 4. Create another world
 5. Check what the function I linked returns
 6. The function returns the same path even though I changed the world

**Description of issue:**
```
MinecraftServer server = LogicalSidedProvider.INSTANCE.get(LogicalSide.SERVER);
this.saveDir = new File(server.getWorld(DimensionType.OVERWORLD).getSaveHandler().getWorldDirectory(), "DimStorage");
```
I think the problem is not in the code I wrote but in the forge functions. I may have said bullshit, in which case I apologize :)

**Comment by diesieben07** [comment]
1. Please provide minimum test-case to reproduce. Looked at your repo for a little bit and it looks like `DimStorageManager` never invalidates it's server-side manager.
2. Why on earth are you re-inventing the wheel? Use capabilities to store data.

**Comment by Edivad99** [comment]
Okay, I'm porting from 1.12 to 1.14.4. In 1.12.2 I managed the files I saved and it always worked. 
If there are these methods why can't I use them, and why don't they work? 
Are there any tutorials on how to implement these capabilities besides the ones on the forge page?

**Comment by diesieben07** [comment]
At this point this is no longer something for the forge issue tracker.
Please either provide a reproducible test case or ask your question on the forum.

**Comment by Edivad99** [comment]
But the methods doesn't work ...

**Comment by diesieben07** [comment]
> provide a reproducible test case
