### ISSUE TITLE
--server doesn't work proper

### ISSUE THREAD

**Issue by robertmakrytski** [MinecraftForge/MinecraftForge#6418]
1)when i add --server mc.dexland.ru argument for version 1.15 or 1.15.1 (forge 30.0.33) and for old too
2)i run unstable minecraft and will get disconnect from server after (15-30 seconds)
[tlauncher3.txt](https://github.com/MinecraftForge/MinecraftForge/files/4037226/tlauncher3.txt)

**Comment by DaemonUmbra** [comment]
We do not support pirate launchers

**Comment by robertmakrytski** [comment]
could you write launcher where i can use 1.15 and --server for fast game?

**Comment by DaemonUmbra** [comment]
We don't write custom launchers, nor do we provide special support for anyone who does.
Forge will only ever provide support for the Official Mojang launcher.
