### ISSUE TITLE
[1.14.4-1.15.2] Failed to create and enter a new world after denying a world update/backup in singleplayer

### ISSUE THREAD

**Issue by zlainsama** [MinecraftForge/MinecraftForge#6419]
**Minecraft version:**
1.14.4-1.15.2

**Forge version:**
28.1.113, 30.0.35, 31.0.8, 31.1.0

**Steps to Reproduce:**
 1. Create a world with mods that added contents
 2. Start an instance of Forge client without any mods
 3. Try open the world created by step 1
 4. Select "No" to deny the world update/backup
 5. Proceed to create a new world
 6. Observe the client return to the main menu

**Description of issue:**
After denying a world update/backup, the game failed to create and enter a new world.

**Note:**
The game log shows that the integrated server is started in the background and is generating the spawn while the client's screen is returned to the main menu.

**Comment by LexManos** [comment]
Can not reproduce locally with test mods {CNGBB} please provide a small test world/mod.

**Comment by zlainsama** [comment]
A 3 minutes video that reproduce this in forge-1.15.2-31.0.8 with BiomesOPlenty-1.15.2-10.0.0.300: https://youtu.be/t_bOFDmczqg
The world created in the making of the video:
[TESTA.zip](https://github.com/MinecraftForge/MinecraftForge/files/4130798/TESTA.zip)
The game log after the video:
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/4130815/latest.log)

**Comment by zlainsama** [comment]
Still happens in 1.15.2-31.1.0.

**Comment by zlainsama** [comment]
No longer happens in latest 1.15.2 Forge, and is irrelevant in 1.16.1.
