### ISSUE TITLE
runData args paths not generating correctly

### ISSUE THREAD

**Issue by MelanX** [MinecraftForge/MinecraftForge#6426]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.111

**Steps to Reproduce:**
 1. Create a project in a directory with spaces (e.g. "D:/this is a path/mods/example")
 2. Setup your runData
 3. generate the runs
4. The runs will not work as expected

**Description of issue:**
the paths should be surrounded by ```"``` to work properly

**Comment by LexManos** [comment]
FG is in charge of this, not Forge.
