### ISSUE TITLE
TracingPrintStream incorrectly handles being called from printStackTrace(PrintStream)

### ISSUE THREAD

**Issue by Niko-sk2x** [MinecraftForge/MinecraftForge#6440]
note: I may submit a PR to fix this.

Minimal code that shows the issue:
 `new Throwable().printStackTrace(System.err)`

[TracingPrintStream](https://github.com/MinecraftForge/MinecraftForge/blob/983a47a7d670127048277a936040880703fc3d3a/src/fmllauncher/java/net/minecraftforge/fml/loading/TracingPrintStream.java) assumes that the 7th element (4 after base) is the caller, which is true when it's the no argument `printStackTrace` being called. Calling it with `System.err` as argument bypasses that and shortens the stacktrace by 1 element. This is not a major issue as the worst that happens is that the log will show wrong class/method name ~~, but it can cause an ArrayIndexOutOfBoundsException to be thrown if it's called directly from a run() method from a thread (this actually happened, which is why know about it)~~

**Comment by ichttt** [comment]
This should not be able to read out-of-bounds, as it falls back to the last element of the stack if the computed value exceeds the array length (note the Math.min statements)...

**Comment by Niko-sk2x** [comment]
Ok, so it can't crash. The actual error happened in 1.12.2 and I didn't notice the difference in code between 1.12.2 and 1.15.x. I checked if the code has changed (I was wrong, should have actually tested it on 1.15.x), and didn't see a difference, so submitted this.

**Comment by Niko-sk2x** [comment]
I forgot that not crashing doesn't mean that there is no bug when closing, so reopening.

**Comment by LexManos** [comment]
Honestly, this is a best attempt hack, we can't cover all cases and I don't really care to try. This is specifically done to address idiots not using the logging system correctly. I don't want to spend more brainpower on it then needed. So.. this is good enough. Feel free to PR better handling if you care. or better yet, stop using System.err/out
