### ISSUE TITLE
[1.15] IForgeBlockState.getAiPathNodeType is never called

### ISSUE THREAD

**Issue by Snownee** [MinecraftForge/MinecraftForge#6441]
**Minecraft Version:** 1.15.1

**Forge Version:** 30.0.16

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/patches/minecraft/net/minecraft/pathfinding/WalkNodeProcessor.java.patch#L27 Yes it is.

**Comment by Snownee** [comment]
@LexManos Sorry, I mean the mob-sensitive version. And it is only called by WalkNodeProcessor

**Comment by LexManos** [comment]
Of corse, the entity version cant be called by WalkNodeProcessor, as it doesn't have that data.
And the entity version IS called by the non-entity version.
https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java#L857
So.. Your report is still invalid/incomplete.

**Comment by Snownee** [comment]
@LexManos I am trying to make specific mob (bee in my case) able to pass through my block. As NodeProcessor is not using the mob-sensitive version, it seems I have to make a new NodeProcessor. Then implement a new PathNavigator that can create my NodeProcessor. Then replace the default PathNavigator when mob joining world. As the entity is stored in NodeProcessor (`NodeProcessor.entity`, `field_186326_b`), I think it is easier to just call the entity-sensitive version of the method. This also solves conflicts if there are mods doing the same.
