### ISSUE TITLE
cant compile 1.15 (also occurs on 1.14)

### ISSUE THREAD

**Issue by hYdos** [MinecraftForge/MinecraftForge#6446]
**Minecraft Version:*1.15*

**Forge Version:** {LATEST}

`**Logs:**`
```
* Where:
Build file 'C:\Users\Hayden\Desktop\important\plainForgeClient\build.gradle' line: 200

* What went wrong:
A problem occurred evaluating root project 'Forge'.
> Cannot invoke method describe() on null object
```

**Steps to Reproduce:**
 1. run gradlew setupForge
**Description of issue:** unable to compile latest version of forge 1.15

if i made a common mistake im sorry im new to compiling forge and using gradlew

**Comment by LexManos** [comment]
You did not clone the Forge git correctly.
