### ISSUE TITLE
Server Logic Freezes on Large Light Updates

### ISSUE THREAD

**Issue by LostCoderSoul** [MinecraftForge/MinecraftForge#6447]
Hello, I was testing a offthread chunkgeneration in minecraft, which works fine but after going from version 42, to 114 the logic started to break because of lightengine freezing the main thread.
I isolated the issue down to [124c78c](https://github.com/MinecraftForge/MinecraftForge/commit/33307fb1bde14ac06ccc95665e7be68bffbf34a9) and its previouse patch.

So what exactly is the issue: 
when a chunksection is not fully in need of relighting (which is the most common case) you rather iterate over the map then getting all possible things to delete.
Sadly there is a giant visible bug in this logic/approach, with 2 issues.

- Issue 1: Its not a linked map its a normal hashmap that means you iterate over the full size of the hashmap that means even if there is not 256 entires in it you will iterate over full array which if there is more then 127 entires you have a full 256 iterator. So performance is gone there.
Potential fix: Switch the Long2ByteOpenHashMap to a Long2ByteLinkedOpenHashMap and the optimization actually might help.

- Issue 2: You remove entires as you iterate over the hashmap, eh big no no no. Iterating over something that you delete will cause issues. Hashmaps rehash after they reach half size to shrink the array and also can cause that you actually miss entries. Because keyset/entryset/values do not get notified that this change happend and then have incorrect data. Also if you would try this with java HashMaps instead of FastUtil ones you would get a concurrent exception since that is not allowed. (FastUtil just assumes you are not doing this.)
Fix here is: Copy the keyset and then execute it. That would only make sense though if the iteration is only below 127 entries assuming you are having linked set and not a normal set. With a normal set it would only make sense with 63 entries or less.

I have 3 potential fixes here:

- 1: Remove the Performance Improvement attempt, because the current one is nice on paper but bad in execution. Minecrafts logic already skips the non existing values pretty quickly before even a performance loss could happen. And this is not the main source of delay. (Heavily suggested, unless you can tell me with evedince that this is massivly faster)

- 2: Fix the issues that I listed and hope that the performance drop (its at least 50% slower right now) is not as bad anymore and worth keeping.
- 3: Add a config section for this if it should be used or not. Then people could at least decide if they want it or not.

Thanks for reading.

Edit: Added Link to Patch

**Comment by LexManos** [comment]
Most of these patches have been removed as vanilla did similar changes on 1.15.2, so it's not applicable to current dev.
