### ISSUE TITLE
Item interaction with doors

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#6448]
Related versions : 1.14.4 & 1.15.1
Description :
When an item interacts with a block, we have a method in IForgeItem allowing to prevent the vanilla behavior :
```java
    /**
     * This is called when the item is used, before the block is activated.
     *
     * @return Return PASS to allow vanilla handling, any other to skip normal code.
     */
    default ActionResultType onItemUseFirst(ItemStack stack, ItemUseContext context)
    {
        return ActionResultType.PASS;
    }
```
In 1.12.2, it was working correctly, but in the versions mentioned above, it creates a strange behavior where the door is half opened (visually) :
![item_first_use](https://user-images.githubusercontent.com/17954109/72560523-80cf8900-38a7-11ea-8742-c3bfdded9e3c.png)
I made a small test mod to test it (the mod adds 3 sticks in the tab "misc" named result_pass, result_fail and result_success : [LINK](https://cdn.discordapp.com/attachments/498120654982479884/667464376294441010/examplemod-1.0.0.jar)

**Comment by LexManos** [comment]
So, this issue here is client and server desync.
This will happen with any desync, such as the RightClickBlock event.
We don't really have a good way to roll back the client side side effects of using a block.
If anyone has issues, let me know.

**Comment by ghost** [comment]
I just tested it with the version containing the PR of Aeltumn, and everything works so I think I can close the issue (thank you)

**Comment by ghost** [comment]
I think it's still a trouble but differently. By returning SUCCESS on clientside in onItemUseFirst() makes the serverside method to never occur.
```java
            if (this.currentGameType != GameType.SPECTATOR)
            {
                EnumActionResult ret = itemstack.onItemUseFirst(player, worldIn, pos, hand, direction, f, f1, f2);
                if (ret != EnumActionResult.PASS)
                {
                    // The server needs to process the item use as well. Otherwise onItemUseFirst won't ever be called on the server without causing weird bugs
                    this.connection.sendPacket(new CPacketPlayerTryUseItemOnBlock(pos, direction, hand, f, f1, f2));
                    return ret;
                }
```
code in 1.12.2
```java
if (this.currentGameType == GameType.SPECTATOR) {
            this.connection.sendPacket(new CPlayerTryUseItemOnBlockPacket(p_217292_3_, p_217292_4_));
            return ActionResultType.SUCCESS;
         } else {
            ItemUseContext itemusecontext = new ItemUseContext(p_217292_1_, p_217292_3_, p_217292_4_);
            if (event.getUseItem() != net.minecraftforge.eventbus.api.Event.Result.DENY) {
               ActionResultType result = itemstack.onItemUseFirst(itemusecontext);
               if (result != ActionResultType.PASS) return result;
            }
```
code in 1.15.2 (PlayerController)

**Comment by ghost** [comment]
```java
    @Override
    public ActionResultType onItemUseFirst(ItemStack stack, ItemUseContext context) {
        // other code before
        if (context.getWorld().isRemote && context.getPlayer() != null) {
            ((ClientPlayerEntity) context.getPlayer()).connection.sendPacket(new CPlayerTryUseItemOnBlockPacket(context.getHand(), new BlockRayTraceResult(context.getHitVec(), context.getFace(), context.getPos(), context.isInside())));
        }
        return ActionResultType.SUCCESS;
    }
```
tested to work by doing something similar to the comparaison of code 1.12.2/1.15.2 shown above

**Comment by ghost** [comment]
no need to keep it open when there is no respect (it was the last time I posted in forge a problem)
