### ISSUE TITLE
[1.15] RenderType Map should be converted to an IRegistryDelegate-based map

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#6449]
Currently, replacing blocks voids their existing render types, when block replacement and render types should be totally detatched unless the render type is being edited.

As is done with the color maps, the render types should be using delegates.

**Comment by Snownee** [comment]
Btw, `ComposterBlock.CHANCES`, `AxeItem.BLOCK_STRIPPING_MAP`, `FireBlock.encouragements` and `FireBlock.flammabilities` have similar problems

**Comment by pupnewfster** [comment]
If `AxeItem.BLOCK_STRIPPING_MAP` has the same issue I am guessing `ShovelItem.SHOVEL_LOOKUP` and `HoeItem.HOE_LOOKUP` may also have the issue, though I have not tested to make sure.
