### ISSUE TITLE
[1.15.1] Mobs randomly spin or have jerky rotation

### ISSUE THREAD

**Issue by chylex** [MinecraftForge/MinecraftForge#6454]
**Minecraft Version:** 1.15.1 and 1.14.4

**Forge Version:** 30.0.41 (1.15) and 28.1.115 (1.14)

**Steps to Reproduce:**
 1. Create a world
 2. Find or spawn some animals
 3. Punch them or wait until they start moving
 4. Watch them spin/jerk around

**Description of issue:**
This is what happens in Forge, notice the frequent jerky rotations:
![mobspin-forge](https://user-images.githubusercontent.com/3685160/72671502-c3ca6180-3a4b-11ea-9f87-0d53378147ee.gif)

This is what happens in vanilla, the pathfinding is a bit temperamental but the mobs never suddenly rotate back and forth, or spin around:
![mobspin-vanilla](https://user-images.githubusercontent.com/3685160/72671501-c3ca6180-3a4b-11ea-94b7-0fffa3cefe86.gif)

**Comment by Ommina** [comment]
#6456 I'd imagine.

**Comment by Unnoen** [comment]
Should be fixed by https://github.com/MinecraftForge/MinecraftForge/commit/2d30419a310083bb7ebbce736ddd0aefa9d142c5 Can you test and confirm?

**Comment by chylex** [comment]
It seems to work exactly like in vanilla now, unfortunately vanilla is still quite buggy.

I don't know if it's in scope to fix this particular vanilla issue too, #6456 does actually show a bit of the vanilla jerky motion that still happens in 1.15.2. It's really easy to see if you go into superflat, spawn one or more large animals like pigs or cows (higher quantity = more likely to occur), hold carrots or wheat, and move backwards (happens even when walking in a straight line). You should see them spin around every few seconds.

Happens also with hostile mobs that walk towards you, but you may need to move at a slight angle or strafe around them, especially if they have a small width.

I can't find anything filed on the vanilla bug tracker, 94054 mentioned in the patch is apparently only for cave spiders even though they've closed reports of other mobs as duplicates... but it seems like a bigger issue with pathfinding. If there isn't interest in fixing this in Forge, then the issue can be closed, in either case I'll look around the vanilla tracker a bit more and report it there.

EDIT: [MC-163410](https://bugs.mojang.com/browse/MC-163410)

**Comment by tianbis** [comment]
Is there a way to merge the fix (2d30419 ) into 28.1 (for MC 1.14.4)?

**Comment by pupnewfster** [comment]
It already has been merged? https://github.com/MinecraftForge/MinecraftForge/commit/b67c37fd6c1ddffe91de7ee6c57393a9169bfec5

**Comment by chylex** [comment]
@eltian That resolved the original issue, but the exact same buggy behavior remains in vanilla, it just happens less frequently.
