### ISSUE TITLE
World generation with Forge differs from Vanilla.

### ISSUE THREAD

**Issue by Unnoen** [MinecraftForge/MinecraftForge#6469]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.0.1

**Logs:** N/A

**Steps to Reproduce:**
1. In Vanilla, create new world with seed `-8103374476192659048`
2. `/tp -27.5 70.0 8.5`
3. Look North
4. Repeat in Forge

**Description of issue:**
The world generation is different in Forge, it *appears* to be decorations as I only noticed with trees.

Screenshots:
Vanilla: 
![2020-01-24_11 57 01](https://user-images.githubusercontent.com/6127568/73036954-4fefe500-3ea1-11ea-808f-318cd2b3353e.png)
Forge:
![2020-01-24_11 57 44](https://user-images.githubusercontent.com/6127568/73036961-54b49900-3ea1-11ea-8750-27449ed917bd.png)

**Comment by pau101** [comment]
This is how vanilla world generation has behaved for quite some time, see [MC-55596](https://bugs.mojang.com/browse/MC-55596)

**Comment by Unnoen** [comment]
Hmm, odd, I've never run into this before, but it does make sense considering it just seemed to be the decorations.

**Comment by pau101** [comment]
Here is what it looked like for me, even more different:
![2020-01-23_18 33 24](https://user-images.githubusercontent.com/5201207/73047134-9a357f80-3e29-11ea-9271-c5802a6cbe98.png)

**Comment by LexManos** [comment]
Ya, it seems that some parts of the world gen in MC are not fully determinstic, I generated the same world twice in the same instance of vanilla Minecraft.
And got two results. So im going to sit the trees as a Vanilla bug. Which if you feel like digging into go for it. But Doesn't seem like our fault.
![](https://puu.sh/F53h2/bc3de60e99.jpg)
![](http://puu.sh/F53iY/f2c34e6103.jpg)
