### ISSUE TITLE
Shadows darker/stronger in Forge than Vanilla.

### ISSUE THREAD

**Issue by Unnoen** [MinecraftForge/MinecraftForge#6470]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.0.1

**Logs:** N/A

**Steps to Reproduce:**
(Make sure graphics are set to Fancy and Smooth Shadows are on Maximum)
 1. In Vanilla, create new world with seed `-5097585848872419723`
 2. `/tp 71.5 79.0 -329.5`
 3. Look North and take a screenshot
 4. Load world in Forge
 5. Take screenshot and compare

**Description of issue:**
Forge's shadows appear to be stronger, as well as the vignette on the sides of the screen. Compare the screenshots and flick between them, it becomes a lot more apparent.

Screenshots:
Vanilla:
![2020-01-24_12 10 03](https://user-images.githubusercontent.com/6127568/73037465-41a2c880-3ea3-11ea-845f-051655b29c83.png)
Forge:
![2020-01-24_12 11 24](https://user-images.githubusercontent.com/6127568/73037467-46677c80-3ea3-11ea-80c8-c54a64f01d9c.png)

**Comment by gigaherz** [comment]
Testing seems to indicate my changes in 6551ccc fixed this issue.
The vignette differences are purely because the vignette slowly disappears over time when logging into the game, so the timing of when the screenshot was taken explains that difference completely.
Closing as fixed.
