### ISSUE TITLE
ItemStacks passed through packet get empty tag

### ISSUE THREAD

**Issue by Pi-Man** [MinecraftForge/MinecraftForge#6472]
**Minecraft Version:** {1.14.4}

**Forge Version:** {28.1.111}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Send ItemStack with null tag through packet, specifically PacketBuffer#readItemStack and PacketBuffer#writeItemStack
 2. after reading stack, the tag is now an empty CompoundNBT instead of null
 3. ...

**Description of issue:**

when comparing itemstacks to see if they can merge in the inventory, if one tag is empty and the other tag is null, minecraft says they can not merge.  The result of this is if a stack is sent through a packet it will not be able to merge with a stack in the inventory that it should be able to merge with because it has been given an empty tag instead of a null tag

**Comment by tterrag1098** [comment]
A quick read of those methods in PacketBuffer determines this not to be true. It must be something you are doing. Please confirm bugs before reporting them.
