### ISSUE TITLE
Terminal  freeze after running with forge of 1.12.2

### ISSUE THREAD

**Issue by papadave66** [MinecraftForge/MinecraftForge#6482]
**Minecraft Version:** 1.12.2

**Forge Version:**  2847

**Logs:** [gist url](https://gist.github.com/papadave66/1870e3d154bbcd47f27d7e0d9d8f65ab)

**Steps to Reproduce:**
 1. Run forge in Solaris terminal
 2.  `/fml confirm`
 3.  We lost our terminal control. You can't ctrl+c or anything . the terminal freeze

**Description of issue:**
And if you run with mods. the server stuck at ' not start up now' situation.

_stty\_version_

``` [minecraft@router]:[34]:[~/chemistry/logs]:$ stty --version               
stty (GNU coreutils) 8.5                                                          
Copyright (C) 2010 Free Software Foundation, Inc.                                 
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.    
This is free software: you are free to change and redistribute it.                
There is NO WARRANTY, to the extent permitted by law.                             
                                                                                  
Written by David MacKenzie.

OS: Oracle Solaris
```

**Comment by FinnT730** [comment]
Please update to a modern version, AKA 1.14.4 or 1.15.2 to get support.
