### ISSUE TITLE
[1.15.2] Forge blockstates not loading

### ISSUE THREAD

**Issue by Rexbas** [MinecraftForge/MinecraftForge#6483]
**Minecraft Version:** 1.15.2

**Forge Version:** 1.15.2-31.0.14

**Logs:** https://gist.github.com/Rexbas/55f71c47bdf86dd6171243ce1e17d688

**Steps to Reproduce:**
 1. See my test repository: https://github.com/Rexbas/BugReproduce
 2. OR Create a block with a forge blockstate and property horizontal facing

**Description of issue:**
After updating from 1.14.4 (forge: 1.14.4-28.1.117) to 1.15.2 (forge: 1.15.2-31.0.14), forge blockstates no longer load.

**Comment by KnightMiner** [comment]
They were removed. You should be using data generators or vanilla multipart for most cases that previously used a forge block state. For the remaining, look into the new model loader system.
