### ISSUE TITLE
[1.15.2] Entity and sound registry mixup when joining vanilla server after visiting singleplayer

### ISSUE THREAD

**Issue by chylex** [MinecraftForge/MinecraftForge#6487]
**Minecraft Version:** 1.15.x, not sure about previous versions

**Forge Version:** 31.0.14

**Logs:** https://gist.github.com/chylex/b81413a3d365bd4bda7dd524e41016bc

**Steps to Reproduce:**
1. Launch a Forge 1.15.2 client (no other mods)
2. Launch a vanilla 1.15.2 server
3. Open [this world](https://github.com/MinecraftForge/MinecraftForge/files/4141012/Corruption.Test.zip) in singleplayer
   - This is a freshly created world I made in the same version of Forge with a random seed
   - **It is not the only world that triggers it**, but not every world I generate triggers it either
   - **If a world happens to trigger the issue, it will do so consistently**
   - Using the Re-Create function or creating a new world using the same seed (2381088473551440320 in the world I linked), **does not guarantee that world will also cause this issue**, it might but it seems very rare
4. Join the vanilla server, **most entities and sounds should be completely mixed up**, good idea to turn the volume down
   - The items should turn into item frames
   - Fish should turn into Sheep, Cows, etc.
   - Zombie Pigmen should turn into Polar Bears
   - If you see a Pufferfish on the ground, it should burp as it moves around
   - and so on... the mixup is consistent every time
   - because the client-side constructs the wrong entities, they have the wrong client-side data manager that doesn't know how to respond to server packets, you can see the result in the linked log file (in that log file, I opened a different, older world that also caused the issue)

![2020-01-31_18 04 01](https://user-images.githubusercontent.com/3685160/73568429-aabcaa00-4468-11ea-8220-d1517d62ab99.png)
![2020-01-31_18 04 31](https://user-images.githubusercontent.com/3685160/73568438-aee8c780-4468-11ea-91dc-6503a251d00e.png)

**Comment by ichttt** [comment]
I already found out a time ago that the registries are never reverted to frozen, but forgot about it again. Could this be releated to this?

**Comment by gigaherz** [comment]
Based on the conversation on Discord, I'm 99.9% certain that's exactly the issue here.

**Comment by ichttt** [comment]
Should be fixed by #6497
