### ISSUE TITLE
[1.14.4 - 1.15.2] Missing patch to enable the use of GL_STENCIL_TEST

### ISSUE THREAD

**Issue by Funwayguy** [MinecraftForge/MinecraftForge#6489]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.1.117

**Description of issue:**
An old patch that enables the use of the OpenGL stencil buffer has not yet been restored making the creation of some advanced elements such as scrolling UIs far more difficult.

**Link to old patch:**
https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/patches_old/minecraft/net/minecraft/client/shader/Framebuffer.java.patch

**Comment by diesieben07** [comment]
From checking the code it seems that in 1.14 (and 1.15) Framebuffers are always used (the GameSettings option is gone).
Can someone confirm this? If that's true it should be pretty simple to port the patch and just remove the check for enabled framebuffers.

**Comment by Funwayguy** [comment]
At this point I don't care whether 1.14.4 gets this fixed any more as long as I can get _some_ current version with stencil buffers enabled that I can make use of. This is possibly the only thing left that I need to port my UI render code. With 1.16 snapshots rolling out and this issue not even triaged after a month I'm getting really concerned that I'm going to have to abandon my UI rendering for some janky hack job.

**Comment by LexManos** [comment]
The option is always there for you to submit a pr and test restoring it. The render engine changed quite a bit so it may not be an easy port. As it's well known I'm not a rendering guy.

**Comment by gigaherz** [comment]
Fixed in 1.15 as of ec7d9d41.
