### ISSUE TITLE
Minecraft Forge 1.12.2 server mods wont work

### ISSUE THREAD

**Issue by LochlainPotato** [MinecraftForge/MinecraftForge#6492]
Idk if this is the right place for it but, I'm trying to start a server for me and my friends, I went through all the network stuff and my friends can join flawlessly but the mods don't seem to work. I try to start forge none server in server files to see if it needs to run first but when i do that it says: Potentially Dangerous alternative prefix 'MINECRAFT' followed by the mod name. It also says that some of the mods arent signed or dont have a version annotation. All of the mods worked perfectly in single player. Then it crashes that window. IDK what to do

**Comment by Unnoen** [comment]
[We no longer support 1.12.2](https://www.minecraftforge.net/forum/topic/79304-112114-and-lts-system/). Please update to receive support from us.

In the future, questions like this are for our [Discord server](https://discord.gg/UvedJ9m) and [forums](https://www.minecraftforge.net/forum/forum/18-support-bug-reports/).
