### ISSUE TITLE
[1.15.2] PlaySoundEvent#getVolume NPE

### ISSUE THREAD

**Issue by AfterRebelion** [MinecraftForge/MinecraftForge#6500]
Related forum post: [Forge Forum](https://www.minecraftforge.net/forum/topic/80384-1152-playsoundevent-getvolume-npe/)

**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.0

**Logs:** [Crash Report](https://gist.github.com/AfterRebelion/21ec972eade98965088d509dd3266bac)

**Steps to Reproduce:**
 1. Call `getSource().getVolume()` on `PlaySoundEvent` for a sound that extends Minecraft `LocatableSound` (All of vanilla sounds).
 2. Get an NPE

**Description of issue:**
When trying to use `getSound().getVolume()` or `getSound().getPitch()` methods on PlaySoundEvent, it will generate a NullPointerException if called for any Minecraft sound.

This happens because `net.minecraft.client.audio.LocatableSound`, the main class every sound in Minecraft extends, uses `this.sound.getVolume()` and `this.sound.getPitch()`, but as [at the time the ForgeHook is implemented](https://github.com/MinecraftForge/MinecraftForge/blob/d86f58a0df1e8fda0303fa8250ef7cb0a8f8807d/patches/minecraft/net/minecraft/client/audio/SoundEngine.java.patch#L23) the sound field has not yet been initialized, it's null, and generates the NPE.

The accessor is just below, so it seems very probable that moving the hook one line will fix this, but needs testing.

**Comment by diesieben07** [comment]
> The accessor is just below, so it seems very probable that moving the hook one line will fix this, but needs testing.

The event allows overriding the sound being played by allowing to specify a different `ISound`. We can't just move the hook until after calling `createAccessor`, because that would disable overriding the sound.

Is there a reason why you need `getVolume` and/or `getPitch` specifically?

**Comment by AfterRebelion** [comment]
I can work around it, the one I really need is `getSound()`, that right now returns `null`
I'm working on a ASM free version of https://github.com/djpadbit/Sound-Physics .
My aproach right now is use PlaySoundEvent to get the sound that's going to play, copy it's data to a new sound class, and play it on my own soundmanager, as the one Mojang implemented in 1.14+? to replace Paulscode lacks essential parts.
So if I can't get the sound, I can't play it on my own soundmanager.
Maybe there is another event that gets access to the sound, so I can work around this?

**Comment by diesieben07** [comment]
So really what we need is a 2nd event, one that is fired for the `ISound` (which is the _type of sound_) and then one after `createAccessor` has been called (which determines the actual sound to play, e.g. from a pool of random ones).

Correct?

**Comment by AfterRebelion** [comment]
I totally forgot about this issue. I found a workaround using [PlaySoundSourceEvent](https://github.com/AfterRebelion/Sound-Physics/blob/2b162c2f60e9fde1fdfb5c4c379c7bed51a5190e/src/main/java/com/sonicether/soundphysics/soundsystem/SoundEventHandler.java#L19) instead, that's fired later, so it has the required information. Closing.
