### ISSUE TITLE
RenderWorldLast.getPartialTicks() returns nano time instead

### ISSUE THREAD

**Issue by Thutmose** [MinecraftForge/MinecraftForge#6504]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.0

**Logs:** No logs, this is noticed in development environment reading calls

**Steps to Reproduce:**
 1. Look at https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/patches/minecraft/net/minecraft/client/renderer/GameRenderer.java.patch#L43
 2. Notice it passes the long instead of the float to the event
 3. ...

**Description of issue:**

The event is handing the "finishTimeNano", which is generally of order 1e11 or so, instead of partialTicks, which is in range of 0-1, this can cause problems if you try to use it as a partialTicks value

**Comment by pau101** [comment]
What is the reason for closing? This appears to still be an issue.

**Comment by pupnewfster** [comment]
Pretty sure they closed it because they noticed #6380

**Comment by pau101** [comment]
Yep just found that myself, oops. Good to link it here for reference.
