### ISSUE TITLE
Vanilla commands unable to be used in console with Forge 31.1.1 [1.15.2]

### ISSUE THREAD

**Issue by TheDarkPreacher** [MinecraftForge/MinecraftForge#6507]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.1

**Logs:** Debug log: https://pastebin.com/HVyGfNaB
               Latest.log: https://pastebin.com/Y7W84EiQ

**Steps to Reproduce:**
 1. create 1.15.2 instance in launcher (GDLauncher, Twitch Launcher, your choice.)
 2. Install Forge 31.1.1
 3. Start game, create new world with cheats enabled
 4. open console, attempt to type in '/gamerule DoDaylightCycle false'
 5. have command fail, close Minecraft
 6. remove Forge, restart instance
 7. repeat step 4
 8. Have command succeed.

**Description of issue:**
 Vanilla commands are not able to be used, such as "gamerule", "gamemode", "kill", if Forge is installed. Mod related commands still work.

**Comment by diesieben07** [comment]
The gamerule is called `doDaylightCycle`, not `DoDaylightCycle`. Step 4 when done exactly (with uppercase gamerule name) fails in both Forge and Vanilla 1.15.2.
`doDaylightCycle` works fine in both Forge and Vanilla 1.15.2.

`gamemode` and `kill` also work fine in latest Forge for 1.15.2.

Unable to reproduce.
