### ISSUE TITLE
[1.14] PlayerChangedDimensionEvent fired with wrong fromDim from ServerPlayerEntity.teleport()

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#6512]
Copy of #6457 but for 1.14.4

**Minecraft Version:** 1.14.4

**Forge Version:** 28.2.0

**Description of issue:**
ServerPlayerEntity.teleport() fires a dimension changed event at its end, but passes the DimensionType of the target world into the "fromDim" parameter instead of the DimensionType from the previous world, causing both fromDim and toDim to be the same.

**Comment by ichttt** [comment]
Fixed in #6513
