### ISSUE TITLE
[1.14.4] Wrong blockstate generation of states with AttachFace

### ISSUE THREAD

**Issue by PssbleTrngle** [MinecraftForge/MinecraftForge#6520]
**Minecraft Version:** 1.14.2

**Forge Version:** 28.2.0

**Steps to Reproduce:**
 1. Generate a blockstate using a data provider
 2. Use a block containing a property of the type `AttachFace`

**Description of issue:**

The method below is extracted from the `VariantBlockStateBuilder.PartialBlockstate` being used to generate blockstates using a data provider.
The method is used to parse the PartialBlockstate into what will be printed into the JSON file.

The problem here is that the property value of the blockstate is appended to the StringBuilder, resulting in a call to the `toString` method of the object. With enums like `Direction` thats not a problem, as these override the `toString` method, but the `AttachFace` class does not.
The result in the JSON file is that the property value is printed in uppercase, instead of lowercase.

The solution to this problem is calling the `getName` method every IStringSerializable (every IProperty class) must have.

```java
@Override
        public String toString() {
            StringBuilder ret = new StringBuilder();
            for (Map.Entry<IProperty<?>, Comparable<?>> entry : setStates.entrySet()) {
                if (ret.length() > 0) {
                    ret.append(',');
                }
                ret.append(entry.getKey().getName())
                        .append('=')
                        .append(entry.getValue());
            }
            return ret.toString();
        }
```

Resulting JSON line in blockstate file:
```JSON
"face=WALL,facing=north,powered=false": { ...
```

**Comment by PssbleTrngle** [comment]
This could also be solved by adding a default `toString` method to IStringSerializable calling `getName`

**Comment by PssbleTrngle** [comment]
The problematic line is
```java
.append(entry.getValue())
```

**Comment by pau101** [comment]
This is a situation where `IProperty#getName(T)` should be used. Making `entry.getValue()` effectively become `entry.getKey().getName(entry.getValue())`.

**Comment by MapperTV** [comment]
This problem also exists in Forge 31.1.18 for 1.15.2. I talked about it on Discord and tterrag suggested me to make a PR to fix it but I can't get my fork of Forge to import correctly in Eclipse... Maybe someone who already has a Forge setup can do it? Thanks.
