### ISSUE TITLE
forge:and condition doesn't skip if one of the conditions doesn't exist

### ISSUE THREAD

**Issue by bageldotjpg** [MinecraftForge/MinecraftForge#6525]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.2.0

**Logs:**
Log:
https://gist.github.com/bageldotjpg/e7da9b54cec1b1d78480618c9b617093
Recipe:
https://gist.github.com/bageldotjpg/f4ba34413259c8f83ee4c101a8249336

**Steps to Reproduce:**
 1. Use a forge:and condition
 2. Make one of the conditions use a flag from an unloaded mod

**Description of issue:**
If a condition / flag doesn't exist, such as it's from another mod, it should just skip the recipe, instead of giving a parsing error.
It should do this, which happens when both conditions exist:

[21Feb2020 16:37:12.280] [Server thread/INFO] [net.minecraft.item.crafting.RecipeManager/]: Skipping loading recipe atmospheric:aspen_leaf_carpet as it's conditions were not met

But instead you get a long parsing error.

**Comment by Daomephsta** [comment]
> If a condition / flag doesn't exist, such as it's from another mod, it should just skip the recipe, instead of giving a parsing error.

This would lead to difficult to debug issues caused by typos in mod IDs. A better solution would be to make `forge:and` short-circuiting. That could be tricky/messy to do, I have an idea I want to try though.

**Comment by Niko-sk2x** [comment]
It currently is short circuiting when evaluating a condition but parsing happens before evaluation. And parsing it requires everything to exist. And you can't only partially parse it unless you do evaluation while parsing.

**Comment by LexManos** [comment]
Ya, we should probably move the deserialzier to default to a always false condition for things that can't parse. But this comes into the issue of hiding recipe typos... or other issues... so we'd need to log some error...
There needs to be some compromise of non-spammy vs not-hiding things.

**Comment by bageldotjpg** [comment]
Perhaps it could just be made shorter, like 
"Skipping loading recipe atmospheric:aspen_leaf_carpet as it's conditions were not found" or
"Skipping loading recipe atmospheric:aspen_leaf_carpet as one of it's conditions were missing"

**Comment by Daomephsta** [comment]
> And you can't only partially parse it unless you do evaluation while parsing.

Lazily parsing would also work, it can be done quite cleanly too.
https://gist.github.com/Daomephsta/73370cf57ddb174f6fea9ef2cf482d28
OrCondition & AndCondition would wrap their children in that.

**Comment by LexManos** [comment]
Lazy parsing just delays the error until later which again just hides the errors :/

**Comment by Daomephsta** [comment]
Unfortunately it does delay any errors. But it also means that conditions which aren't tested aren't parsed, making it possible to guard mod provided recipe conditions with a `mod_loaded` condition.
It could be made slightly better by parsing immediately in a mod dev env, though that means datapack authors don't get the errors immediately.
