### ISSUE TITLE
A suggestion for Netease to modify Forge.

### ISSUE THREAD

**Issue by SNWCreations** [MinecraftForge/MinecraftForge#6529]
@LexManos 
I hope to add the function of mandatory display of copyright information to all versions!
I just read about Netease modifying forge based on LGPL but not open code, which makes me angry.
I'm also a Minecraft player and I respect forge.
I haven't studied Java programming, but I think this function should be implemented.  : )
If implemented, mandatory updates should be added.
Tip: my network is very strange. I can access GitHub at normal speed. Should GitHub's server be close to China?
But I can't visit Google. I can only translate it in China. If I can't understand it, please forgive me!

**Comment by LexManos** [comment]
Forge will not add any form of DRM. if they are not publishing the license and code then they are already in violation of our license so there isnt much we can do. Microsoft and Nerease has much more money for lawyers then we do.

**Comment by SNWCreations** [comment]
Well, thank you.

**Comment by SNWCreations** [comment]
But I still support Forge. : )

**Comment by SNWCreations** [comment]
Hmm... is a problem.

**Comment by SNWCreations** [comment]
From your answers, money is a question.
@LexManos

**Comment by LexManos** [comment]
Stop spamming our issues.
