### ISSUE TITLE
defaultconfigs not working on servers

### ISSUE THREAD

**Issue by Sunekaer** [MinecraftForge/MinecraftForge#6541]
**Minecraft Version:** 1.15.2 

**Forge Version:** 31.1.18

**Logs:** https://paste.feed-the-beast.com/view/88760436

**Steps to Reproduce:**
 1. Install forge server.
 2. copy the defaultconfigs folder and mods folder from client to server.
 3. start server

**Description of issue:**
configs from defaultconfigs doesnt get copied over.

Example file from defaultconfigs folder:
![image](https://user-images.githubusercontent.com/18720460/75628367-a525c180-5bd8-11ea-82b5-47600c4902a2.png)

File from config after server start:
![image](https://user-images.githubusercontent.com/18720460/75628378-b242b080-5bd8-11ea-9612-8ad8cbf600ab.png)

**Comment by Unnoen** [comment]
Is this when there is *no* existing config? It's known at the moment that defaultconfigs will not override existing configs.

As per: https://github.com/MinecraftForge/MinecraftForge/commit/cd826f7bcf2fc7f6795cfa6a0125005742043e24 "I am thinking about ways to force a specific
config override for an existing config."

**Comment by Sunekaer** [comment]
When there is no existing config.
Im aware it doesnt overwrite existing

**Comment by Darkere** [comment]
It seems to work fine for -server configs. I had no idea it was supposed to work for other types too.

**Comment by Darkere** [comment]
This issue is unique to silent's mechanisms. 
Tested with my own config and also tested Quark. Both are working fine.

**Comment by KnightMiner** [comment]
Default config is for server config, is it not? The issue appears to be showing a common config. Server configs are stored in the world save and are suffixed with `-server`

**Comment by Sunekaer** [comment]
Hi 
Its been a while since i last looked at this.
Yes common config, because both client and server is supposed to take the files from defaultconfig folder and place them in the config folder and the server config folder under config generation, and it did only do it for server config files on a dedi and not both

**Comment by gigaherz** [comment]
There's really no point at all in placing non-server configs in the defaultconfigs folder. The entire purpose of that folder is to copy those files to the serverconfigs folder when creating a new world folder. It should work regardless, but it doesn't really change anything because the non-server configs can just be placed in the main config folder by default, since the main config folder is already shared by all installations of the modpack.

**Comment by Darkere** [comment]
It does allow people to keep their config changes if the pack author doesn't specifically ship the configs to overwrite something from the previous version.

**Comment by Sunekaer** [comment]
defaultconfig folder is meant for both client/common and server config, so you only ship the changed files and not the whole config folder.
There is 2 issues tho
1: client/common doesn't get overwritten on servers but does on the client, server config files work fine on both.
2: there is no way to overwrite config files in the config/serverconfig folder with defaultconfig, so you need to ship that config folder to overwrite files in the config folder and use Darkere's [mod](https://www.curseforge.com/minecraft/mc-mods/serverconfig-updater) to overwrite server config

**Comment by Darkere** [comment]
>client/common doesn't get overwritten on servers but does on the client

A Server doesn't generate the -client files at all. It does generate the -common files and also copies them from the defaultconfig foler if the file exists there. 

Silent's mechanisms from your initial post uses a special ConfigWrapper (can't find the code for it @SilentChaos512), which breaks it for that specific mod.

**Comment by Shadows-of-Fire** [comment]
My understanding of this issue is that this is either a mod issue or is working-as-intended with the config system.
