### ISSUE TITLE
minecraft:leaves stopped working in custom recipes for 31.1.18

### ISSUE THREAD

**Issue by WilxGaming** [MinecraftForge/MinecraftForge#6544]
Minecraft Version: 1.15.2

(modded) forge-31.1.18

After updating from forge-31.1.14 to forge-31.1.18 custom recipes I made with minecraft:leaves or minecraft:wool stopped working. They will work with minecraft:oak_leaves, but not the generic term.

Here is the actual recipe for dirt.json if you're interested:
______________________________________________________________________________________________________
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "iii",
    "iii",
    "iii"
  ],
  "key": {
    "i": {
      "item": "minecraft:leaves"
    }
  },
  "result": {
    "item": "minecraft:dirt"
  }
}

**Comment by srs-bsns** [comment]
`minecraft:leaves` is a `tag` not an `item`

**Comment by WilxGaming** [comment]
> minecraft:leaves is a tag not an item

Thank you. Tag solved the problem. Yes I'm new to this.
