### ISSUE TITLE
Mod depend in crash-report/log cann't be showed |"unknown"

### ISSUE THREAD

**Issue by tiararinne** [MinecraftForge/MinecraftForge#6548]
**Minecraft Version:1.12.2** 1.12.2

**Forge Version:forge-1.12.2-14.23.5.2847-universal** forge-1.12.2-14.23.5.2847-universal

**Logs:https://paste.ubuntu.com/p/JDhdSqXgWs/** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. install some mod without hard-depend
 2. start the server
 3. crash,and take a look at crash-report or log.lastest

**Description of issue:**
If some mods that depend other lib-mod had been installed into a forge server,then crash-report cann't show what mod they need.
Logs:https://paste.ubuntu.com/p/JDhdSqXgWs/
Just display "Unknown"
It should be displayed like this:https://paste.ubuntu.com/p/QvsbmZ7X3M/

**Comment by diesieben07** [comment]
1.12 is no longer supported by Forge.
