### ISSUE TITLE
[1.15.2] Placing or destroying a block near tall grass and flowers makes them invisible with alwaysSetupTerrainOffThread set to true

### ISSUE THREAD

**Issue by ImpSpy2** [MinecraftForge/MinecraftForge#6552]
**Minecraft Version:** 1.15.2

**Forge Version:** 1.15.2-31.1.18

**Steps to Reproduce:**
 1. Change alwaysSetupTerrainOffThread to true in config
 2. Place block near tall grass or flowers

**Description of issue:**
Placing a block or destroying a block near tall grass, flowers, cactus and maybe some other plants causes them to turn invisible with alwaysSetupTerrainOffThread set to true.

**Comment by Excaliburning** [comment]
Confirming this bug is still happening on build 1.15.2 - 31.1.30.
It also includes other "normal" grass, if you destroy wild grass, others become invisible, including tall grass, flowers, etc.

**Comment by ImpSpy2** [comment]
Having tested further the issue also makes nearby water invisible and causes visual glitches but the issue does not happen when using optifine with optiforge.

**Comment by SkyProgs** [comment]
I can confirm that it still happens in build 1.15.2 - 31.1.77 (just forge, no other mods installed).
It also happens with redstone and campfires. 
It also causes really strange render bugs (this happend when placing redstone and turning around sometimes):

![grafik](https://user-images.githubusercontent.com/8573170/81443028-e99f8180-9174-11ea-98ae-4b7add3df21b.png)
