### ISSUE TITLE
Updating Chunk causing unknown crash in the vanilla multiplayer server

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#6555]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.18

**Logs:** https://pastebin.com/hZhvqyCC

**Steps to Reproduce:**
Not really sure about how to reproduce an issue.

**Description of issue:**
When doing something like updating block in the chunk it seems to cause a random crash.
https://www.youtube.com/watch?v=PH25CpNSlyE

**Comment by mindsolve** [comment]
I am also experiencing this crash (same stacktrace), in my case when pressing a button to a redstone piston-based door.  
In my case, the game crashes immediately while pressing the button (before depress is able to happen).

**Minecraft Version**: 1.15.2

**Forge Version**: 31.1.0, 31.1.34 and 31.1.50

**Logs**:
- https://pastebin.com/yPV7vnG2 (Forge 31.1.50)
- https://pastebin.com/edm7uhuN (Forge 31.1.0)

**Installed mods:** None (but also with Journeymap and JEI)

**Comment by jamierocks** [comment]
I've spent a little while trying to reproduce this - unsuccessfully.

To confirm, this is an issue for Forge clients on Vanilla server? and have you confirmed that the Forge server doesn't suffer the same issue?

And would it be possible either to have a demonstration world, or clear screenshots of whatever contraptions you have so we can reproduce this?

**Comment by mindsolve** [comment]
I am no longer experiencing this issue.

I am playing on a PaperMC 1.15.2 server over multiple Paper-versions.
When destroying, placing or using (in my case) one specific button, my game would crash 100% of the time, even if I was not the one using/destroying/placing it. This would happen up to around 5 chunks in line-of-sight away from that button.

To diagnose further, we began dismantling the redstone circuit. The pistons were not the (direct) cause of my problems, rather a redstoneblock that was used in the circuit. After destroying and re-placing it, I had no further crashes.

As such, I am unfortunately no longer able to assist in the deeper analysis.

**Comment by SteveKunG** [comment]
Can't reproduce right now.
