### ISSUE TITLE
[1.15.2] Dimension Deletion API

### ISSUE THREAD

**Issue by Senmori** [MinecraftForge/MinecraftForge#6568]
#### Summary:
This feature would allow developers and server administrators to have a certain level of control
of when and how the server dimensions are deleted.

As of Minecraft 1.15.2 there is no way via the MinecraftForge API to schedule a dimension for deletion. A server administrator has to manually delete the dimensions they no longer want.

This feature should allow server admins to control what dimensions should be deleted, or even if dimensions should be deleted at all. These options should be in the `forge-server.toml` config.
The potential options for server admins would be (in order of importance):
1. Allowing dimensions to be deleted.
2. If deletion enabled, either a whitelist or blacklist of dimensions to be processed.
4. On deletion, logs should be generated that include the Mod and Dimension.
5. If deletion enabled, specify when the dimensions should be deleted (startup, shutdown, unload, etc.)

There are some options that would be nice for server owners to perform maintenance when they have many worlds without needing to resort to manual deletion or third-party tools (these are just nice things to have, not something that should absolutely be implemented).
1. Adding specific wildcards to specify/prevent certain namespaces from having their dimensions processed. 
   - `rftools:*` would prevents rftools dimensions from being deleted if configured appropriately
   - `rftools:dim-*` would delete rftools dimensions if their names(or directories) start with `dim-`.
     - This options would allow server admins to manage lots of dimensions without having to  constantly monitor disk space or which dimensions haven't been used recently.
2. Adding time controls to prune worlds after 'x' amount of time.
    - This should probably be in days; other time measurements don't make sense for this scope.

Example configuration:
```toml 
[options]
mode = "whitelist"  # This will determine how the entries in 'dimensions' are handled
dimensions = [ 
"world", "nether", "the_end", "mining_world"
]
[controls]
delete-after = 7 # Will delete all appropriate dimensions after 7 days.
```
The options shown above are not absolute, they are just there to show how time controls could operate.

With this feature developers would be able to create "temporary" dimensions that would allow them programatically delete their own dimensions ~~and to, optionally, specify a processor that would be used to process their dimension directory~~.
The potential options for developers would be (in no order of importance):
1. New abstract `ModDimension` subclass to house the deletion functionality.
2. ~~New method(s) in `ModDimension` to specify the processor a mod should use~~
3. New Manager that can handle the scheduling, calling, and registering of new dimensions to delete.
4. Forge event(s) that can be used to notify other mods of pre/post-dimension deletion.

These options are by no means a final list of options. We should assume they will all be changed and/or possibly removed as development occurs.

As well, there should be a way to query if a given `DimensionType` is scheduled for deletion during runtime. This could be used for third-party APIs to determine if that dimensions should/could be used for their purposes.

#### Limitations:
Limitations refer to forced API limitations. Not limitations to which files/folders should be deleted.

1. All scheduling of deletions should include the `ModContainer` and `DimensionType` so proper logging can be done.
2. The deletion must happen when developers can retrieve the server's world folder location, and the dimension's directory.
3. The deletion of dimensions should be limited by an explicit registration process; regardless of how it is implemented.
4. Server administrators should have the final option of whether dimensions are deleted, and if so, which dimensions should     be deleted. (either via whitelist or blacklist).
5. Deletion of vanilla worlds should be strictly controlled. (Though not necessarily blocked)
6. The deletion of the `level-name` directory should not be allowed.

#### Potential Impact
The deletion of worlds while the server is still running will always be a contentious ordeal. Especially for mods like RFTools who have items in other worlds that can reference a now-deleted world. How those mods reference the dimensions could be problematic.
The deletion of large worlds could potentially have a large impact on the server as a whole, and should ideally be pushed onto a new thread so as to minimize impact.

#### Opinion
I believe many developers and server admins would like this functionality introduced into Forge. This would save many server admins and developers from having to worry about useless dimensions.

**Comment by diesieben07** [comment]
See also:
https://github.com/MinecraftForge/MinecraftForge/pull/6515

I will try to look at it again tonight.

**Comment by Senmori** [comment]
Thank you @diesieben07. 

Now that I've had a night to sleep on this, I don't think these are good ideas:
> to, optionally, specify a processor that would be used to process their dimension directory.

> New method(s) in ModDimension to specify the processor a mod should use


I think Forge should be responsible for deleting the directories to ensure the deletions are done correctly. How it's done isn't important so much as doing it correctly; someone can always extract a method to it's own class later on if it becomes important to have different ways of deleting directories.

**Comment by diesieben07** [comment]
Yes, thats what the linked PR implements.
A mod can say "I do not need this dimension anymore" and Forge will take care to clean it up properly.

**Comment by Senmori** [comment]
Yes, but what if a server owner wants to keep that world? Obviously vanilla worlds should not be easily discarded, but I don't think we should completely say we can't. For example, what if they wanted to do a weekly/biweekly/monthly reset of the end so that they can fight the dragon. 
I think there's use-cases where resetting a vanilla world would be useful.

**Comment by diesieben07** [comment]
Resetting is something different to deletion. Deletion means the dimension is _gone_ (this requires a server reboot). Resetting should already be possible by mods today (unload dimension, delete data, load dimension again).

**Comment by Senmori** [comment]
Yeah, resetting was a bad word. While it might be possible with mods, a server owner is not necessarily going to know how to accomplish that. They will just stop the server, delete the dimension, and restart.

I should be able to start working on this today and this weekend so that should, hopefully, make things easier to discuss.

**Comment by diesieben07** [comment]
Still not sure what you want Forge to do here.
