### ISSUE TITLE
[1.15.2]Using mods in development workspace doesn't work

### ISSUE THREAD

**Issue by undertrox** [MinecraftForge/MinecraftForge#6584]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.0

**Logs:** https://gist.github.com/undertrox/a2aca8e14b80fe8c1ec333a0f23f49b8 (this is an example using Biomes o plenty, but the bug was reproducible with every mod I tested, so I assume it is probably reproducible with any mod

**Steps to Reproduce:**
 1. Put any mod in the run/mods directory
 2. Start the game

**Description of issue:**
the Game starts with an error message if you try to start it with mods in the run/mods folder. The error message changes slightly, depending on the mod, but it's usually either a NoSuchFieldError or a NoSuchMethodError. I also posted in the Forge forum: https://www.minecraftforge.net/forum/topic/82314-1152using-mods-in-development-workspace/ and was told to open an issue here. I didn't test this with other Minecraft versions besides 1.15.2

**Comment by Jkmcameron** [comment]
The mods are obfuscated so the forge development environment doesn't know how to read them, I already ran into this issue and gave up because I couldn't find the solution

**Comment by undertrox** [comment]
Biomes o plenty has an unobfuscated jar, I tried to use that, but it still didn't work, so I don't think that is the only reason. In older versions of the game (1.12 for example) it works even with normal jars, so there should be a solution

**Comment by Wavebrother** [comment]
You need to tell forge to deobfuscate the jar. 
`runtimeOnly fg.deobf("mezz.jei:jei-1.15.2:6.0.0.2") `
That goes in your dependencies section of build.gradle. Yours will be different, unless you are using JEI. 
You also need to tell forge where the maven repository is. 
```repositories {  
  maven {  
    // location of the maven that hosts JEI files  
    name = "Progwml6 maven"  
    url = "https://dvs1.progwml6.com/files/maven/"  
  }  
  maven {  
    // location of a maven mirror for JEI files, as a fallback  
    name = "ModMaven"  
    url = "https://modmaven.k-4u.nl"  
  }  
} 
```
This is what I use for JEI in build.gradle. I don’t know where the maven repository is for Biomes O Plenty, or if there is one.
