### ISSUE TITLE
Forge freezes if you add too many instances of IntegerProperty to the Block's StateContainer

### ISSUE THREAD

**Issue by Jkmcameron** [MinecraftForge/MinecraftForge#6587]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.19

**Logs:** No crash so no crash report, game freezes so log is useless too, to last few lines of the log before freezing are as follows:

```
[Render thread/DEBUG][ne.mi.fm.ModList/LOADING]: Dispatching synchronous event LifecycleEvent:LOAD_REGISTRIES
[Render thread/DEBUG] [ne.mi.fm.ja.FMLModContainer/LOADING]: Firing event for modid forge : RegistryEvent.Register<minecraft:block>
[Render thread/DEBUG] [ne.mi.fm.ja.FMLModContainer/LOADING]: Fired event for modid forge : RegistryEvent.Register<minecraft:block>
[Render thread/DEBUG] [ne.mi.fm.ja.FMLModContainer/LOADING]: Firing event for modid t3l : RegistryEvent.Register<minecraft:block>
```

**Steps to Reproduce:**
 1. Create a class that extends Block
 2. Register a bunch of IntegerProperties to the StateContainer
 3. watch as client freezes

Relevant code:

```
public class WoodBlock extends RotatedPillarBlock
{
    public static final IntegerProperty RADIUS = IntegerProperty.create("radius", 2, 16); 
    public static final IntegerProperty LOG_ABOVE_RADIUS = IntegerProperty.create("log_above_radius", 0, 16);
    public static final IntegerProperty LOG_BELOW_RADIUS = IntegerProperty.create("log_below_radius", 0, 16);
    public static final IntegerProperty LOG_TO_LEFT_RADIUS = IntegerProperty.create("log_to_left_radius", 0, 16);
    public static final IntegerProperty LOG_TO_RIGHT_RADIUS = IntegerProperty.create("log_to_right_radius", 0, 16);
    public static final IntegerProperty LOG_TO_FRONT_RADIUS = IntegerProperty.create("log_to_front_radius", 0, 16);
    public static final IntegerProperty LOG_TO_BACK_RADIUS = IntegerProperty.create("log_to_back_radius", 0, 16);
    public static final BooleanProperty HAS_BARK = BooleanProperty.create("has_bark");

    public WoodBlock(Properties properties)
    {
	super(properties);

	setDefaultState(stateContainer.getBaseState().with(RADIUS, 8).with(LOG_ABOVE_RADIUS, 0).with(LOG_BELOW_RADIUS, 0).with(LOG_TO_LEFT_RADIUS, 0).with(LOG_TO_RIGHT_RADIUS, 0).with(LOG_TO_FRONT_RADIUS, 0).with(LOG_TO_BACK_RADIUS, 0).with(HAS_BARK, true));
    }

    @Override
    protected void fillStateContainer(StateContainer.Builder<Block, BlockState> builder)
    {
	super.fillStateContainer(builder);

	builder.add(RADIUS);
	builder.add(LOG_ABOVE_RADIUS);
	builder.add(LOG_BELOW_RADIUS);
	builder.add(LOG_TO_LEFT_RADIUS);
	builder.add(LOG_TO_RIGHT_RADIUS);
	builder.add(LOG_TO_FRONT_RADIUS);
	builder.add(LOG_TO_BACK_RADIUS);
	builder.add(HAS_BARK);

    }
    ...
}
```

I use each of these properties in my custom ModelLoader, I don't know of any other way to store information about individual blocks that can be accessed from the `public List<BakedQuad> getQuads(BlockState state, Direction side, Random rand)` function of IBakedModel. Debugging in Eclipse tells me that the freeze happens in the default Block constructor, somewhere between these two lines:

```
public Block(Block.Properties properties) {
      StateContainer.Builder<Block, BlockState> builder = new StateContainer.Builder<>(this);
      this.fillStateContainer(builder);
      this.material = properties.material;
      this.materialColor = properties.mapColor;
      this.blocksMovement = properties.blocksMovement;
      this.soundType = properties.soundType;
      this.lightValue = properties.lightValue;
      this.blockResistance = properties.resistance;
      this.blockHardness = properties.hardness;
      this.ticksRandomly = properties.ticksRandomly;
      this.harvestLevel = properties.harvestLevel;
      this.harvestTool = properties.harvestTool;
      final ResourceLocation lootTableCache = properties.lootTable;
      this.lootTableSupplier = lootTableCache != null ? () -> lootTableCache : properties.lootTableSupplier != null ? properties.lootTableSupplier : () -> new ResourceLocation(this.getRegistryName().getNamespace(), "blocks/" + this.getRegistryName().getPath());
      this.slipperiness = properties.slipperiness;
      this.speedFactor = properties.speedFactor;
      this.jumpFactor = properties.jumpFactor;
      this.variableOpacity = properties.variableOpacity;
      this.lootTable = properties.lootTable;
      this.isSolid = properties.isSolid;
      *****this.stateContainer = builder.create(BlockState::new);*****
      *****this.setDefaultState(this.stateContainer.getBaseState());*****
   }
```
I can't tell if its freezing on the first line or immediately after running the first line, I suspect the second line is the issue. Not sure why though.

**Comment by diesieben07** [comment]
All possible block states are pre-calculated. In your case that is `14 * 16^5 * 2 = 29360128` possible states.
This is not a bug, you are simply creating too many states.

**Comment by Jkmcameron** [comment]
> All possible block states are pre-calculated. In your case that is `14 * 16^5 * 2 = 29360128` possible states.
> This is not a bug, you are simply creating too many states.

work around? And yes, that is still an issue. throw an exception somewhere or something, don't just allow it to freeze

**Comment by FinnT730** [comment]
Maybe not make that amount?? Why in the world do you need that much?

**Comment by Jkmcameron** [comment]
> Maybe not make that amount?? Why in the world do you need that much?

[I just made a feature request](https://github.com/MinecraftForge/MinecraftForge/issues/6588), my block's model changes depending on it's neighbors and there isn't a way to query what blocks are adjacent to the block being processed in `bakeQuads` without sneaking that information in using blockstates. And like I said previously, regardless of how my case is resolved, there needs to be an exception thrown instead of freezing the thread

**Comment by Jkmcameron** [comment]
> Maybe not make that amount?? Why in the world do you need that much?

Ideally I'd store a single IntegerProperty for each block, ranging from 2 to 16, but since I can't query neighboring blocks storing the same property of each neighboring block was the only solution I could think of, and what you see here is the consequence of that

**Comment by Jkmcameron** [comment]
So... the thread is just closed? And for what reason? Don't even care to throw an exception?

**Comment by gigaherz** [comment]
It's not about threads dying. It's about the thread taking exponentially long time to finish, and using exponentially more memory. You are encountering a combinatoric issue. There's no hard line for it. You add too many properties, the result is combinatoric explosion. How many is too many, is entirely dependant on what the purpose is. But "hundreds of thousands" is most definitely way beyond this fuzzy line.

Also, you **can** already obtain information about neighbours, by implementing getModelData inside your IBakedModel. You can then use that model data inside getQuads. If you need more information about this, you can ask in the forums or the discord server. This isn't the place for that.
