### ISSUE TITLE
During worldgen, structures with campfires can throw a NullPointerException due to a vanilla bug

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#6591]
I was told to report this vanilla crash to here as it could be a potential Forge patch. The original bug report was made to Mojang on Jira here: https://bugs.mojang.com/browse/MC-173067?jql=project%20%3D%20MC%20AND%20text%20~%20%22campfire%20crash%22

----------------------------------------

**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.27

**Logs:** https://gist.github.com/TelepathicGrunt/ea12a310746b241097097528f4470e9f (File is truncated. Click view full file and then ctrl+f "net.minecraft.crash.ReportedException: Feature placement" to jump to the relevant part of the crash which is line 10028)

**Steps to Reproduce/Description of issue:**
From the Mojang issue report:
```
When a structure:
-Contains a campfire
-The campfire is placed where a fluid was previously
-During world generation (does NOT occur by placing the structure with a structure block)
```

**Comment by FoxSamu** [comment]
Code that causes the bug:
```java
// CampfireTileEntity.java
public void dropAllItems() { // = func_213986_d, the method where the crash happened
   if (!this.getWorld().isRemote) { // Upon world generation, 'getWorld()' returns null, resulting in NPE
      InventoryHelper.dropItems(this.getWorld(), this.getPos(), this.getInventory());
   }

   this.inventoryChanged();
}
```
This is a Mojang issue because Forge didn't patch anything here... Try to reproduce in vanilla to create a Forge-free crash report and hint Jira again, e.g. using a buffet world.

**Comment by TelepathicGrunt** [comment]
Resolved in 20w18a. guess 1.15.2 won't be getting a Forge patch for this. Rip 1.15.2 worldgen structure mods with campfires lol.
