### ISSUE TITLE
Infinite loop if IllegalStateException thrown in vanilla ParticleManager::loadTextureLists

### ISSUE THREAD

**Issue by TheGreyGhost** [MinecraftForge/MinecraftForge#6592]
I've found this specific issue but I think it might perhaps be a more general issue related to Forge's use of CompletableFutures for some tasks. 

If ParticleManager::loadTextureLists throws an IllegalStateException, it causes an infinite loop, where loadTextureLists keeps getting invoked and throwing an exception.

It appears that the Forge code doesn't handle this failed Future properly?  Might be a vanilla bug; I'm not sure.

This project branch reliably causes the issue:
https://github.com/TheGreyGhost/MinecraftByExample/tree/forgeregistrybug

-TGG

**Comment by CmdrNorthpaw** [comment]
I'm also experiencing this bug
