### ISSUE TITLE
[1.15.2] When client resource loading fails, the resource manager keeps reloading infinitely

### ISSUE THREAD

**Issue by FoxSamu** [MinecraftForge/MinecraftForge#6593]
When client resource loading fails (mostly upon a `CompletionException`), Minecraft tries to remove all selected resource packs to reload again and solve the problem. In case of mods however, that doesn't solve the issue, causing an infinite loading loop instead of Forge showing the exception. 

Examples of cases where this happens:
- A mod resource failed loading, such as a particle texture list
- A registry entry is registered twice, causing an exception
    - `java.util.concurrent.CompletionException: java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!`
- An uncaught exception shows up when a mod is loading a custom resource

**Comment by TheGreyGhost** [comment]
Looks like the same as the one I reported about the same time :)
https://github.com/MinecraftForge/MinecraftForge/issues/6592
