### ISSUE TITLE
Model "transform" block rotation misbehaving

### ISSUE THREAD

**Issue by TBoshoven** [MinecraftForge/MinecraftForge#6603]
**Minecraft Version:** 1.15.2
**Forge Version:** 1.15.2-31.1.35

**Steps to Reproduce:**
 1. Create a composite model for a block with one of the parts rotated. I used the following for testing:
```json
{
  "loader": "forge:composite",
  "parts": {
    "anvil1": {
      "parent": "minecraft:block/anvil"
    },
    "anvil2": {
      "parent": "minecraft:block/anvil",
      "transform": {
        "rotation": [{"y": 90}]
      }
    }
  }
}
```
 2. Place a block with this model in the world

**Expected behavior:**
Block looks like two anvils crossing each other.

**Actual behavior:**
One of the two anvils is displaced.

**Description of issue:**
It seems like rotation goes by corner base where in 1.14.4 (through the backported system) it rotates with a center base. This is what I would expect as the "correct" behavior.
Furthermore, it seems to be behaving inconsistently when loaded through a variant blockstate with a rotation in it as well.

Anvil configuration with no rotation in the blockstate:
![2020-04-04_12 40 41](https://user-images.githubusercontent.com/1949124/78456420-8734fc00-7671-11ea-84cf-4216556a9ab5.png)

Anvil configuration with a 90-degree rotation over the Y axis in the blockstate:
![2020-04-04_12 37 20](https://user-images.githubusercontent.com/1949124/78456359-2c030980-7671-11ea-8558-25dd0d3f45c4.png)

(ignore the stuff rendering underneath; I just threw this model on an existing block in my mod)

**Comment by gigaherz** [comment]
Fixed in c23ea1e
