### ISSUE TITLE
[1.15.2] Missing tag on Bone Meal and Ink Sac

### ISSUE THREAD

**Issue by TheUntamed** [MinecraftForge/MinecraftForge#6608]
Forge: 31.1.36

Bone Meal and Inc Sacs don't have the tags "forge:dyes" and "forge:dyes/white" / "forge:dyes/black".
I think they should have, that would make it easier to create recipes using the dye tag instead of the hardcoded item. Cactus green has these tags as well.
And I think it also wouldn't hurt anyone because if someone means the item not the dye he/she can still put the item itself in the recipe and not the dye tag.

**Comment by bl4ckscor3** [comment]
Bone Meal and Inc Sacs are no longer used as dyes. There are now specific White/Black Dye items which replace the other items' dyeing functionality, and, in fact, are part of the respective tags.

**Comment by gigaherz** [comment]
Bone meal and ink sacs are not dyes themselves anymore. You create the dyes from them by placing them in the crafting grid, same as with lapis.

Bone Meal -> White Dye
![image](https://user-images.githubusercontent.com/685851/78893383-8fbf7500-7a6b-11ea-96be-02e5d6745753.png)

Ink Sac -> Black Dye
![image](https://user-images.githubusercontent.com/685851/78893393-94842900-7a6b-11ea-8693-c0e2f700c30e.png)

You can't dye wool with ink sac
![image](https://user-images.githubusercontent.com/685851/78893480-b41b5180-7a6b-11ea-9c5d-41bcbad92803.png)

But you can with black dye.
![image](https://user-images.githubusercontent.com/685851/78893491-b9789c00-7a6b-11ea-86b6-1e91910ec103.png)

**Comment by TheUntamed** [comment]
uhh...
shame on me
