### ISSUE TITLE
Allow mods to cooperate on network channels

### ISSUE THREAD

**Issue by octylFractal** [MinecraftForge/MinecraftForge#6612]
For WorldEdit, we expose a CUI service over the `worldedit:cui` channel that is intended to be consumed by mods that are _not_ WorldEdit, and do not necessarily depend on WorldEdit itself. An example of a mod that consumes this channel is the [WorldEditCUI](https://github.com/mikroskeem/WorldEditCUI) (WECUI) mod. Unfortunately, on Forge, mods cannot pick the side to register their channel on, and so any port of WECUI to Forge would not function in single-player, because both WorldEdit and WECUI would try to register the `worldedit:cui` channel and this is prohibited.

I wish to either (1) be able to pick the side that a channel is registered on, or (2) detect if there is already a channel registered and re-use it. The former is preferred by far, as the latter is subject to ending up with a channel whose properties aren't controlled by you. Additionally, Fabric already has this network channel separation, so it would be nice to increase feature parity.

I was told to tag @cpw on this, so I am. Also, I would be willing to write a PR for the method preferred by the Forge team, but I don't know which option that is.

Related: #2783

**Comment by simon816** [comment]
Allowing one-sided channels would solve the problem. However I wonder whether a pub/sub model over the network could be a consideration for Forge?
e.g. a server broadcast message can be subscribed by any client-side mod. Something akin to Android's [broadcast system](https://developer.android.com/guide/components/broadcasts)

**Comment by LexManos** [comment]
Its been two months and nobody are dug into this more. Ya it would be nice to have the idea of just spamming the client with extra data. But you run into issues of how/who deserializes. What channels are required and what are optional on the other end? If someone wants to step up and design something feel free. But this isn't going to be getting any of our attention as there are too many other things to work on.
