### ISSUE TITLE
ItemEntity replacement code for custom ItemEntities calls itself

### ISSUE THREAD

**Issue by Darkere** [MinecraftForge/MinecraftForge#6626]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.45

**Logs:** {https://pastebin.com/FGtt1i13}

**Steps to Reproduce:**
 ``` @Override
    public boolean hasCustomEntity(ItemStack stack) {
        return true;
    }
    
    @Nullable
    @Override
    public Entity createEntity(World world, Entity location, ItemStack itemstack) {
        Vec3d entityPos = location.getPositionVec();
        return new ItemEntity(world, entityPos.getX(), entityPos.getY(), entityPos.getZ(), itemstack);
    }
```

**Description of issue:**
in `ForgeInternalHandler.onEntityJoinWorldEvent` when a custom entity is used the method will call `event.wold.addEntity` which itself calls another EntityJoinWorldEvent causing an infinite loop. 

A possible solution would be to call `addEntity` on the events Chunk instead (and calling ServerWorld.onEntityAdded).

**Comment by diesieben07** [comment]
If you want to have custom item entities, do not use `ItemEntity`, use a subclass or a separate class entirely.
