### ISSUE TITLE
[1.15.2] MilkBucketItem calls clearActivePotions -- it should not

### ISSUE THREAD

**Issue by Wabbit0101** [MinecraftForge/MinecraftForge#6627]
**Minecraft Version:** 1.15.2

**Forge Version:** 1.15.2-31.1.18

**Steps to Reproduce:**
Create an EffectInstance that returns false for isCurativeItem for a milk bucket (and to be sure an empty list for curatives). In game, do action to install that effect instance. Drink milk bucket -- the effect is cleared.

**Description of issue:**
In **MilkBucketItem::onItemUseFinish**, this line seems wrong (compared to ItemBucketMilk as well as logically). I think the patch line (see first code line's comment in function) replaced this line but the original code was never removed!
```
if (!worldIn.isRemote) {
    entityLiving.clearActivePotions();
}
```

**Comment by KnightMiner** [comment]
This is addressed by #6609, so we have reference between the issue and pull request.

**Comment by KnightMiner** [comment]
#6609 was merged, can this be closed?

**Comment by Wabbit0101** [comment]
For me, yes.
