### ISSUE TITLE
Trouble using bundled runtime environment

### ISSUE THREAD

**Issue by donoya** [MinecraftForge/MinecraftForge#6636]
I've been getting this error every time I try to launch minecraft in 1.15.2
![image](https://user-images.githubusercontent.com/12679064/79687629-8073c080-81fd-11ea-844d-3250a20b978e.png)
. I've tried updating java and doing all kinds of things and I finally got vanilla minecraft to work by changing the java executable to a local install of the most recent JDK (as of the time of posting this) in 'program files/java/jdk-14.0.1/bin/javaw.exe'. When trying this with a forge install, I get a crash.
[crash-2020-04-19_05.01.13-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/4498924/crash-2020-04-19_05.01.13-client.txt)

**Comment by Alpvax** [comment]
Forge requires Java 8. Also this kind of issue should be on the forum
