### ISSUE TITLE
Switching to Maximized Screen while loading crashes the game

### ISSUE THREAD

**Issue by mk0003** [MinecraftForge/MinecraftForge#6639]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.47

**Logs:** https://gist.github.com/mk0003/757150064ee6fab11eb9ce6c11066bf0

**Steps to Reproduce:**
 1. Start the game but not maximized
 2. At loading screen click maximize button
 3. Game will crash

**Description of issue:**
I am playing a custom 1.15.2 modpack via Twitch Launcher on Windows 10. By default game starts as a small window. After early loading phase but before loading completed i am pressing maximize button to maximize window. It maximizes window and instantly crashes.

**Comment by ArcanoxDragon** [comment]
Was just about to report this myself; here's a stack trace from a dev environment using the latest mapping:

https://gist.github.com/briman0094/a122ed406eeb871dfd03bfb89ec61931

**Comment by jamierocks** [comment]
I was unable to reproduce this on https://github.com/MinecraftForge/MinecraftForge/commit/a7e4cdcc49afb5bd68d252e54a0207830e36f964 on macOS.

It looks as if this was [resolved](https://github.com/MinecraftForge/MinecraftForge/commit/438c969fefbec86bcb8d512cf8e1e508f3b774d4#diff-0bd1d200e8528dffd6283858ac697a13R170) by cpw a little over a week ago. I was able to [reproduce](https://gist.github.com/jamierocks/b93c13e5b372206dfdb3cbbd1c4f536e) the issue by removing that check

**Comment by LexManos** [comment]
Spent a while trying to reproduce this, was unable to, there isn't much we can do. It's a NPE in a random spot. Probably some stupidity in lwjgl's management of states in multiple threads.
Simple workaround, don't go fullscreen until after the loading is done. If someone else wants to come along and figure out what is screwing up feel free.
