### ISSUE TITLE
Misleading documentation for WorldSavedData

### ISSUE THREAD

**Issue by dhharris** [MinecraftForge/MinecraftForge#6642]
**Minecraft Version:** 1.14.4

**Forge Version:** 1.14.x

**Logs:** N/A

**Steps to Reproduce:**
 1. Go to [documentation ](https://mcforge.readthedocs.io/en/1.14.x/datastorage/worldsaveddata/)for WorldSavedData
 2. Observe that the example code references methods that do not exist in MCForge

**Description of issue:**
The documentation for WorldSavedData was a bit misleading. It doesn't mention the required methods `read` and `write`, and the example code (see below) references outdated methods from the Minecraft API. For example, the `World` class does not have a method `getMapStorage`. It seems like all of the data is now stored using the NBT classes in Minecraft.

```
public static ExampleWorldSavedData get(World world) {
  // The IS_GLOBAL constant is there for clarity, and should be simplified into the right branch.
  MapStorage storage = IS_GLOBAL ? world.getMapStorage() : world.getPerWorldStorage();
  ExampleWorldSavedData instance = (ExampleWorldSavedData) storage.getOrLoadData(ExampleWorldSavedData.class, DATA_NAME);

  if (instance == null) {
    instance = new ExampleWorldSavedData();
    storage.setData(DATA_NAME, instance);
  }
  return instance;
}
```

**Comment by LexManos** [comment]
The documentation isn't mean to be copy paste code.
And this is the wrong repo for reporting documentation issues to.

**Comment by dhharris** [comment]
@LexManos  where can I report documentation issues then? This isn't simply an issue of "I can't copy paste this and make it work". It's documenting a completely different API than the actual one.

**Comment by Unnoen** [comment]
https://github.com/MinecraftForge/Documentation
