### ISSUE TITLE
[1.15.2] RegistryObject#isPresent causes NullPointerException when false

### ISSUE THREAD

**Issue by SmellyModder** [MinecraftForge/MinecraftForge#6647]
The title basically explains it all. 
Inside the boolean getter `isPresent()` in `RegistryObject` it calls the method `RegistryObject#get` meaning that if this boolean is false the game will crash with a `NullPointerException`. 
This currently makes it impossible to effectively use the boolean as a way to safeguard missing registry objects without having to use Reflection

**Comment by LexManos** [comment]
Yup, looks like @tterrag1098 messed it up in one of his cleanups.
https://github.com/MinecraftForge/MinecraftForge/commit/155836258384da2efe80c566b73fc1ca3e3ee48f#diff-3504a3960eb6e1bfb59454d9337652f6L96
