### ISSUE TITLE
Is it fair to assume that an empty ItemStack should not have capabilities?

### ISSUE THREAD

**Issue by brandon3055** [MinecraftForge/MinecraftForge#6651]
**Minecraft Version:** 1.15.x

**Description of issue:**
I don't think this is a major issue just some odd behavior i noticed. 
When an itemstack that has a capability is converted to an empty itemstack via its count becoming 0
Its capabilities are not cleared so its still possible to retrieve capabilities from empty ItemStack's. 
This is obviously easy to work around. I just figured i should mention it. 
![](https://ss.brandon3055.com/b5c9b)

**Comment by KingLemming** [comment]
So...this is tricky IMO. There are cases when you want to use a "locked" item in something and the size ends up going to 0. But you will want the caps to exist.

Personally, any time a slot count goes to <= 0, I replace the stack with ItemStack.EMPTY to ensure no shenanigans.

**Comment by covers1624** [comment]
Perhaps `ItemStack` can override `getCapability` to hotwire `LazyOptional.empty()` when its empty, otherwise delegate to `CapabilityProvider`. Cases where the stack is 'revived' from being empty will still continue to have their caps, but whilst the stack is empty, it will appear as it does not.

**Comment by pupnewfster** [comment]
At one point I had a conversation with lex about capabilities on empty stacks. This is the start of the conversation: https://discordapp.com/channels/313125603924639766/454376090362970122/681200008447524909

**Comment by josephtarbit** [comment]
I think it’s best to let the modder decide the behaviour of this because as stated above, there are circumstances where you would want an empty stack to still have its capabilities and if you don’t, just set the stack to ItemStack.EMPTY.

**Comment by LexManos** [comment]
We're not gunana force it, people have reasons to resuscitate empty stacks and forcing it would cause such a shitstorm of arguing.
