### ISSUE TITLE
Global Loot Modifier fires twice on some tables.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#6657]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.50

**Logs:** [Trace of Dupe](https://gist.githubusercontent.com/Darkhax/2053c1e134ffc85ab0d67ac7b8d815d2/raw/c7745d7cafcd5eade508c042a17926a3ab13f6b5/entity.log)

**Steps to Reproduce:**
 1. Add a global loot modifier which always adds an item to any loot pool.
 2. Kill an entity and you get two.
 3. Break a block and you get one.
 4. Open a chest and you get one.

**Description of issue:** Some types of loot tables such as entity tables will cause loot modifiers to be applied twice. In my test case I was using [this modifier](https://github.com/Darkhax-Minecraft/Bookshelf/blob/1.15.2/src/main/java/net/darkhax/bookshelf/loot/modifier/ModifierAddItem.java) to add a diamond to the pool. This is the [global_loot_modifiers.json](https://gist.githubusercontent.com/Darkhax/2053c1e134ffc85ab0d67ac7b8d815d2/raw/c7745d7cafcd5eade508c042a17926a3ab13f6b5/global_loot_modifiers.json) and this is the [add_item_test.json](https://gist.githubusercontent.com/Darkhax/2053c1e134ffc85ab0d67ac7b8d815d2/raw/c7745d7cafcd5eade508c042a17926a3ab13f6b5/add_item_test.json). This is [a trace](https://gist.githubusercontent.com/Darkhax/2053c1e134ffc85ab0d67ac7b8d815d2/raw/c7745d7cafcd5eade508c042a17926a3ab13f6b5/entity.log) of the duplicate calls caught from within the modifier's doApply.

**Comment by LordMonoxide** [comment]
Can confirm that my entities also drop their items twice. Interestingly, my condition is executed four times for every kill.

**Comment by gigaherz** [comment]
it's a simple oversight. LivingEntity calls modifyLoot explicitly, with the result of lootTable.generate .... which itself calls modifyLoot.
