### ISSUE TITLE
Global Loot Modifiers NPE when no conditions are specified.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#6658]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.50

**Logs:** [npe stacktrace](https://gist.github.com/Darkhax/cf98f1c4747ebd82031f1bd544fac872)

**Steps to Reproduce:**
 1. Create a global loot modifier entry with no conditions property
 2. Load a world
 3. npe

**Description of issue:** If a global loot modifier does not have any conditions specified it will cause an NPE when reading the file. Specifying an empty array will fix this and allow the table to be read. Ideally there would be a null check here.

**Comment by Alpvax** [comment]
What is the use case for a global unconditional modifier?

**Comment by jamierocks** [comment]
I think its worthwhile working out whether this patch is really needed. I've drafted a [patch](https://github.com/jamierocks/MinecraftForge/commit/34f1a9852f8d94ca17351860252c31bff7c4862e) for this, should it be deemed worthwhile.

**Comment by LexManos** [comment]
I know it makes slightly more verbose jsons. But I am more of a fan of letting it crash if you supply null.
As you *should* be passing in a empty list. And leaving the crash prevents us from having to keep track of default cases and legacy data support. Plus, data gens should solve the verbose json issue.

**Comment by Darkhax** [comment]
That's fair enough, not worth another patch over this anyhow.
