### ISSUE TITLE
Crash when starting freshly installed server

### ISSUE THREAD

**Issue by bl4ckscor3** [MinecraftForge/MinecraftForge#6661]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.60

**Logs:** https://gist.github.com/bl4ckscor3/3ddb11ec407f35831d850ffa509f608b

**Steps to Reproduce:**
 1. Create a fresh install of a forge server using the provided installer on https://files.minecraftforge.net
 2. Create `eula.txt` with contents `eula=true` in the server's folder
 3. Start the server

**Description of issue:** Shortly after starting a fresh install of a forge server, the server crashes.

**Comment by 3TUSK** [comment]
#6660
