### ISSUE TITLE
[1.15.2] GuiScreenEvent.ActionPerformedEvent is dead

### ISSUE THREAD

**Issue by mont-40** [MinecraftForge/MinecraftForge#6665]
[1.15.2] Forge 31.1.0

**Description of issue:**
I've registered a `@Mod.EventBusSubscriber(Dist.CLIENT)` on `ClassX` with the following method that never fires:
`
@SubscribeEvent
public static void onActionPerformed(GuiScreenEvent.ActionPerformedEvent.Post event) {
    // Do something here
}
`
This happens for the `Pre` event too. My IDEA doesn't show any references to this event either.

**Comment by LexManos** [comment]
Many events die between MC versions.
This one was not deleted. It will be for 1.15.
If you need it explain why and we can see what we can do about providing a better hook for the new Buttons.
