### ISSUE TITLE
Problems with importing in Idea

### ISSUE THREAD

**Issue by hohserg1** [MinecraftForge/MinecraftForge#6671]
**Minecraft Version:** 1.12.2

**Forge Version:** branch 1.12.x commit 87a63bc5e08f7f1e7085fc62c7800a4071c94291

**Logs:** gradle clean setup log: https://gist.github.com/hohserg1/2695178cf6cd4d30317e7aeee698d322

**Steps to Reproduce:**
 1. Clone repo to local
 2. Switch branch to 1.12.x
 3. Import build.gradle into intellij idea by instructions from docs: https://mcforge.readthedocs.io/en/latest/forgedev/#intellij-idea

**Description of issue:**
I want to setup workspace for develop Forge itself.
Execution of `gradle clean setup` task is failed and I dont know what should I do next.
Thx in advance

**Comment by DaemonUmbra** [comment]
We don't actively develop 1.12 anymore

**Comment by hohserg1** [comment]
Last commit in 1.12.x will be 20 days ago. Are you serious?

**Comment by DaemonUmbra** [comment]
Those were toolchain changes just so people would stop posting issues involving the old toolset.
This is not up for debate.

Oh and just so you know, most issues people report with 1.12 are either user error or go away with a refresh.

**Comment by hohserg1** [comment]
I did reinstall gradle and it began to work :D
