### ISSUE TITLE
FML turns on bracketed paste mode in Linux with a control code

### ISSUE THREAD

**Issue by ShadwDrgn** [MinecraftForge/MinecraftForge#6683]
[02:18:56] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading

When FML prints "[Server thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient..." it also prints ^[[?2004h for some strange reason. this is an ANSI escape sequence that enables bracketed paste mode making it difficult to paste things on linux if it's been printed to your console at any point.

If there's a good reason for this sequence to be written it would sure be nice if at the end of the line it printed the sequence to disable bracketed paste mode again so users don't have to go crazy trying to figure out why they can never paste anything  into their shell ever again. I tried to find the code that's printing this but I assume the text is localized and idon't know where FML keeps it's localization files to look at, but "Invalid recipe" is found nowhere in the repo.

**Comment by jamierocks** [comment]
> for Minecraft 1.12.2

Minecraft Forge is no longer maintained for Minecraft 1.12.
