### ISSUE TITLE
Minecraft crashing

### ISSUE THREAD

**Issue by Chargedion** [MinecraftForge/MinecraftForge#6685]
I just installed some mods for minecraft, but when I open a world it crashes, no idea what's causing it.
Im using:
BiomesOPlenty-1.15.2-10.0.0.345-universal
DoubleSlabs-1.15-2.2.7
goprone-1.15.x-1.3.0
Immersive-Portals-Mod-1.15.2
mcw-doors-1.0.0-mc1.15.2
mcw-windows-1.0.1-mc1.15.2_1.15.1
swampexpansion-1.15.2-1.6.1
TerraForged-1.15.2-0.0.13
themidnight-0.5.7-3
torchslabmod-1.15.2_v1.6.8
worldedit-forge-mc1.15.2-7.1.0
Xaeros_Minimap_20.9.0_Forge_1.15.2

**Comment by hanetzer** [comment]
Logs.
