### ISSUE TITLE
Composter's do not expose IItemHandler

### ISSUE THREAD

**Issue by pupnewfster** [MinecraftForge/MinecraftForge#6691]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.1.81

**Description of issue:**

Composter's do not expose an IItemHandler making it impossible to interact with them with modded systems without specifically implementing support for them and the ISidedInventory they provide. I am opening this as an issue instead of making a PR as I am not sure of the proper way to fix this as Composter's do not have a Tile Entity and from what I can tell Hopper's have a special case that looks for blocks that implement `ISidedInventoryProvider`.

**Comment by gigaherz** [comment]
Fixing this would require designing a sane API for blocks to provide capabilities. I feel like special-casing ISidedInventoryProvider may be the only choice here.

```java
    public static LazyOptional<IItemHandler> getBlockInventoryForSide(BlockState blockState, IWorld world, BlockPos pos, Direction side) 
    {
        Block block = blockState.getBlock();
        if (block instanceof ISidedInventoryProvider)
        {
            return LazyOptional.of(() ->
                    new SidedInvWrapper(((ISidedInventoryProvider)block).createInventory(blockState, world, pos), side)
            );
        }
        else 
        {
            return LazyOptional.empty();
        }
    }
```

However I don't think a helper like this belongs in Forge, because that LazyOptional is not safe to save for later, and people would get the wrong idea.

**Comment by LexManos** [comment]
There is no sane way to make Blocks provide capabilities. If you can think of one feel free to start a discussion about it. Until then, sorry, this isn't gunna happen.
