### ISSUE TITLE
Advancement completed chat messages are not fired though ServerChatEvent

### ISSUE THREAD

**Issue by Aurilux** [MinecraftForge/MinecraftForge#6695]
Minecraft Version: 1.15.2

Forge Version: 31.1.0

Steps to Reproduce:
Register an event handler for the ServerChatEvent and print something to the console when it is triggered, then in-game complete an Advancement and notice how nothing is printed.

Description of issue:
I am trying to append some information to the end of the message that gets sent when the player completes an advancement. I thought I could do this with the aforementioned event. However, it seems it uses the ServerPlayNetHandler#sendPacket method instead of ServerPlayHandler#processChatMessage, which bypasses the ForgeHooks call.

**Comment by diesieben07** [comment]
`ServerChatEvent` is when the server _receives_ a player's chat message, not when it sends out a chat message.
