### ISSUE TITLE
ForgeHooks#canEntityDestroy causes server lag

### ISSUE THREAD

**Issue by IzzelAliz** [MinecraftForge/MinecraftForge#6696]
**Minecraft Version:** 1.14.4

**Forge Version:** 28.2.0

**Logs:** https://gist.github.com/IzzelAliz/deae4877e7eb0454ae0f07aa280178a5

**Steps to Reproduce:**
 1. Let any entity executes the `BreakDoorGoal`
 2. The `shouldExecute` calls the `canEntityDestroy`
 3. The door chunk loads and unloads

**Description of issue:**

The `BreakDoorGoal#shouldExecute` 

```java
    public boolean shouldExecute() {
      if (!super.shouldExecute()) {
         return false;
      } else if (!net.minecraftforge.common.ForgeHooks.canEntityDestroy(this.entity.world, this.doorPosition, this.entity)) {
         return false;
      } else { // something... }
   }
```

https://github.com/MinecraftForge/MinecraftForge/blob/999b5df9336ae1685efb75115ca48378fdf6685d/src/main/java/net/minecraftforge/common/ForgeHooks.java#L1152-L1156

If the `doorPosition`'s chunk(the 0,0 chunk if no pos is provided) is not loaded, the `getBlockState` call loads the chunk, and later this chunk will unload, which causes a lot of lags.

**Comment by LexManos** [comment]
What are you doing that causes the door position to be 0?
As the shouldExecute function is calling it's parent. Which sets the door position to something that is loaded. Either a door on it's path, or the entities current position. Both of which already precheck for the door existing.
So, this doesn't seem to be an issue on our end.
