### ISSUE TITLE
[1.15.2] SpecialSpawn is not fired from Mob Spawners

### ISSUE THREAD

**Issue by Mrbysco** [MinecraftForge/MinecraftForge#6700]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.2.0

**Logs:** 
[Gist](https://gist.github.com/Mrbysco/264af2f3de045b249cdd428f301e690e) (spawners get placed around line 221)

**Steps to Reproduce:**
 1. Subscribe to the `LivingSpawnEvent.SpecialSpawn` event
 2. Make it log the spawn reason
 3. Place down a mob spawner and see how it never logs any mobs spawned from that spawner. 
(To exclude natural spawns set doMobSpawning to false)

**Description of issue:**
SpecialSpawn doesn't get fired for mobs spawned from mob spawners.
 
It had been reported before for 1.14.4 https://github.com/MinecraftForge/MinecraftForge/issues/6005 and went stale but it's still relevant.

**Comment by AtlaStar** [comment]
What benefit would having the AbstractSpawner class invoke the doSpecialSpawn() hook bring that it invoking canEntitySpawnSpawner() currently does not provide?

Currently the canEntitySpawnSpawner() method posts a LivingSpawnEvent.CheckSpawn event, which is basically identical to the SpecialSpawn event in terms of what is stored and its methods except that CheckSpawn has a isSpawner() method to check if the entity was spawned with a spawner.

More or less unless there is a compelling reason to make the change I don't think one will be made as currently you can currently just subscribe to the CheckSpawn event that is actually submitted and call isSpawner() if there are certain things you wish to do based on mobs spawning from a spawner block.

**Comment by AtlaStar** [comment]
Also should note I am obviously not one that can make those decisions, I just don't see something being implemented that isn't necessary.
