### ISSUE TITLE
`SRecipeBookPacket` needs patch to allow huge number of recipes

### ISSUE THREAD

**Issue by diesieben07** [MinecraftForge/MinecraftForge#6703]
**Minecraft Version:** 1.15.2 (1.14.4 probably, too, but not tested there)

**Forge Version:** 31.2.0 and earlier

**Logs:** n/a, this issue is not visible in the logs.
![image png 7b47f08be4cafdcec9962da5083f9a89](https://user-images.githubusercontent.com/1915984/82185675-e3827100-98e9-11ea-95eb-bae71abdeadc.png)

When there are too many recipes, `SRecipeBookPacket` gets too large for the network protocol and fails with the above error. Some kind of workaround patch is needed.

**Comment by diesieben07** [comment]
After some discussion on Discord, this is a vanilla bug. You can probably reproduce this with just datapacks on vanilla.
Still might want to have a Forge patch here?

**Comment by diesieben07** [comment]
The fix could be as simple as literally just sending the `INIT` packet multiple times (splitting the data), as the packet handler appends. This would even work in vanilla.

**Comment by LexManos** [comment]
Someone needs to make a datapack for vanilla that triggers this.
So that we can submit it to Mojang and have them fix it.
As this is something I told them about from the very beginning and I don't think it should be on us to fix.

**Comment by Cyborgmas** [comment]
https://bugs.mojang.com/browse/MC-185901

**Comment by noncom** [comment]
My colleague had created such datapacks and we have verified that they reproduce the problem on Vanilla Minecraft client-server setup.

[DataPack_001.zip](https://github.com/MinecraftForge/MinecraftForge/files/4694474/DataPack_001.zip)  - this datapack contains 32 994 recipes and exhibits the issue.
[DataPack_002.zip](https://github.com/MinecraftForge/MinecraftForge/files/4694475/DataPack_002.zip) - this datapack contains 20 392 tags and also reproduces the problem when being used alone.

The evidence of the second datapack means that it's not only recipes that can happen to be an issue. We think that any datapack content can cause this.

@diesieben07 @LexManos what is the best way to proceed with this, are you going to create a bug to Mojang yourself or should I create it or should I add all this information to the bug created by Cyborgmas?

**Just in case:** the datapacks are built automatically by data-generators, the project that my colleague used to generate the datapacks is here: https://github.com/metanchik/MinecraftRandomDataPackGenerator it's based on Forge MDK, but it's not a mod and the datapack generation routines have their own entry points.

PS: Ha, @Cyborgmas we had a very close timing :)

**Comment by LexManos** [comment]
Yes, any colossal packet that is data driven will cause this issue. It is a issue in Mojang's syncing design at the root. It is up to them to change how these things are synced, as it's an obvious issue. So file it with them.
If/When they do fix it. We can see if it's possible to backport.
But again, this is a network protocol issue. That means that we can not do it as we must maintain network compatibility.

**Comment by noncom** [comment]
Ok, I've added a comment to the issue by Cyborgmas in Mojang JIRA.

**Comment by diesieben07** [comment]
> But again, this is a network protocol issue. That means that we can not do it as we must maintain network compatibility.

The SRecipeBookPacket receving code in vanilla allows sending the packet multiple times, splitting the recipe list.

**Comment by diesieben07** [comment]
Is there any interest in me spending the effort to implement this splitting workaround?

**Comment by diesieben07** [comment]
Welp.
More digging and terrible debugging later...
It's not actually `SRecipeBookPacket`. It's `SUpdateRecipes`. Which means this cannot be fixed without changing the network protocol, as far as I can tell.

**Comment by Cyborgmas** [comment]
ah which would explain why tags also caused the issue with the STagsListPacket

**Comment by Shadows-of-Fire** [comment]
It might be possible to cancel the original packet if it would be too large, and resend split packets if the connection was forge-forge, but I'm not sure if that's worth doing before vanilla implements a fix.

**Comment by NahCandyGRDev** [comment]
> The fix could be as simple as literally just sending the `INIT` packet multiple times (splitting the data), as the packet handler appends. This would even work in vanilla.

What's is ''INIT''? I have been with this error for months and I can not solve it.

**Comment by diesieben07** [comment]
This has been fixed in Forge for over a year. Update Forge if you have this issue.

**Comment by NahCandyGRDev** [comment]
> This has been fixed in Forge for over a year. Update Forge if you have this issue.

Thanks!
