### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [MinecraftForge/MinecraftForge#6704]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Minecraft Forge on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by FinnT730** [comment]
Why is this needed?
You have given 0 info on why this is needed and what it will do for the end user.

**Comment by LexManos** [comment]
No
