### ISSUE TITLE
Website GUI's broken

### ISSUE THREAD

**Issue by GhostFire90** [MinecraftForge/MinecraftForge#6707]
**Minecraft Version:Not on MC

**Forge Version:** 1.14.x

**Logs:** 

**Steps to Reproduce:**
 1. goto https://mcforge.readthedocs.io/en/1.14.x/blocks/interaction/GUIs
 2. you are done

**Description of issue:** On blocks/interaction they link to this portion of the site, did it get removed or is this just an issue?

**Comment by GhostFire90** [comment]
If this is the wrong repo where should i put this?

**Comment by pupnewfster** [comment]
If I had to guess: https://github.com/MinecraftForge/Documentation
