### ISSUE TITLE
Add a way to disable the Forge Handshake

### ISSUE THREAD

**Issue by Bixilon** [MinecraftForge/MinecraftForge#6711]
According to https://wiki.vg/Minecraft_Forge_Handshake forge sends a mod list to the specific minecraft server. I do not want this. Is there any way to disable Forge networking stuff (such as plugin channels like FML and so on)?

**Comment by diesieben07** [comment]
No, the data needs to be sent so that the server and client can figure out if the connection is possible (same mods / compatible versions).
What's your use case?

**Comment by Bixilon** [comment]
My use case are vanilla servers. They also work without the handshake. 

Of course, a modded server will not work without it

**Comment by diesieben07** [comment]
Forge will connect to a vanilla server just fine, provided all client-side mods accept the vanilla connection.

**Comment by Bixilon** [comment]
I know:)

But if the server says, that he is a forge server, he will receive the list.

**Comment by diesieben07** [comment]
Correct, for the reason I stated above.
Again: What is your use case? You said "vanilla servers", but now you say Forge server again...?

**Comment by covers1624** [comment]
The only 'use' case I can see for this would be hiding what mods are installed on the client / fmls existence from the server. The only reason you would want to do that is if the server is not allowing specific mods installed and they likely have a reason for doing that.

**Comment by Bixilon** [comment]
Okay. I play on a vanilla server. The server uses Bungeecord or Waterfall with the forge option enabled. So it lies and says it is a modded server to receive the mod list. I want to make this list private.

@covers1624 Yes and no. I only play with Labymod (everywhere allowed) (okay, this mod also registers an channel called LMC). But I simply do not want, that the server knows which mods I am using. And even if I would cheat, I could simply clone Wurst and change the mod id. Not a big deal:)

**Comment by diesieben07** [comment]
This is not a supported use case.

**Comment by covers1624** [comment]
And now your dragging hacked clients into this, no.

**Comment by Bixilon** [comment]
@covers1624 No, it was just an example.

@diesieben07 It is, because I requested it:)

It is a simple question, a feature request.

So you can not help me?

**Comment by diesieben07** [comment]
A Forge client will always report it's mods to a Forge server. Otherwise the "can this connection be made" check is not possible.

**Comment by Bixilon** [comment]
Why? Do I need to patch my forge version my self?

I agree with you, that it makes sense to send this handshake. But in some cases it is useful (privacy and debugging).


But if you can not help me, I'll write a patch for myself....

**Comment by diesieben07** [comment]
Threatening "I'll just jarmod it in if you won't do what I want" is not really a good argument for your suggestion.

So far the only use case you've provided is "I don't want servers to detect that I am using mods". For which the only reason is that the mods are forbidden, so you are cheating.

**Comment by Bixilon** [comment]
You're right, it is not an good argument from me.


I know, it that you think that I am cheating and it is the obvious reason. But it is not my case.

I tried to make an example with Wurst up there in my other comment. It is pretty easy to change and fake the mod id. Its just not a big deal (so I could cheat on this way even better and easier, because the expenditure is lower than writing an issue and discussing with you).


My problem is: It is simply not the server's concern, which mods I use. And because of this, I want an option to disable forge networking.

I hope you can understand my position in this discussion. It is not cheating.

**Comment by diesieben07** [comment]
> It is simply not the server's concern, which mods I use.

Yes, it is. Otherwise it cannot know if it is possible for you to connect.

**Comment by Bixilon** [comment]
It is, if the sever is a "real" modded server and not just a forge server with 0 mods.

I mean I request a simple line in the config of forge where I can say: Act like vanilla. The connection will fail, if it is a real modded server.

**Comment by diesieben07** [comment]
I know what you want. And like I said, it is not a supported use-case.

**Comment by Heleilton** [comment]
> Por quê? Eu preciso corrigir minha versão do forge?
> 
> Eu concordo com você, que faz sentido enviar este aperto de mão. Mas em alguns casos é útil (privacidade e depuração).
> 
> Mas se você não puder me ajudar, vou escrever um patch para mim ....

Hallowed. Were you able to accomplish the feat?
