### ISSUE TITLE
How do I build .jar file in intellij?

### ISSUE THREAD

**Issue by huntert1004** [MinecraftForge/MinecraftForge#6712]
**Minecraft Version:** {Minecraft version}

**Forge Version:** {Forge version. *Version number, not latest/rb*}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

**Comment by FinnT730** [comment]
What is the point of this?
Why did you make a new issue?
