### ISSUE TITLE
Forge Patch in RedstoneWireBlock::canConnectTo has logic error

### ISSUE THREAD

**Issue by TheGreyGhost** [MinecraftForge/MinecraftForge#6718]
The patch for RedstoneWireBlock::canConnectTo has this statement in it
`         return blockState.canConnectRedstone(world, pos, side) && side != null;`
This means that canConnectTo will always return false if side is null, regardless of what canConnectRedstone returns for side==null.

This means that canConnectRedstone can't be used for mod blocks which are trying to mimic vanilla redstone, eg where the redstone is climbing up the side of a stone block to connect to the mod block.

I suggest to remove the side != null and let canConnectRedstone handle that case.

I also suggest making the javadoc for the IForgeBlock::canConnectRedstone more explicit for side, i.e.
   /**
     * Determine if this block can make a redstone connection on the side provided,
     * Useful to control which sides are inputs and outputs for redstone wires.
     *
     * @param state The current state
     * @param world The current world
     * @param pos Block position in world
     * @param side if not null: the side of the wire that is trying to make a horizontal connection to this block.  If null: test for a stepped connection (i.e. the wire is trying to run up or down the side of solid block in order to connect to this block)
     * @return True to make the connection
     */
    default boolean canConnectRedstone(BlockState state, IBlockReader world, BlockPos pos, @Nullable Direction side)
    {
        return state.canProvidePower() && side != null;
    }

**Comment by pupnewfster** [comment]
I am not sure the check is a bug as a redstone wire can't connect to something that isn't actually in the world (on one of the sides). Also if you look at the [patch](https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/patches/minecraft/net/minecraft/block/RedstoneWireBlock.java.patch#L56-L57) the `side != null` is mirrored from what vanilla had. Though I do agree making the docs more explicit may make sense.

**Comment by TheGreyGhost** [comment]
yeah the vanilla func_185897_m() is just canProvidePower without any side information, which is why the side != null information is necessary for vanilla but not for the forge extension.

side==null means that the redstone is trying to climb up the side of a solid block to connect to this block.  The only vanilla block that returns true for side==null is redstone wire because it's hard-coded into canConnectTo.

For example some slightly deobfuscated code from RedstoneWireBlock:

```
private RedstoneSide getWireSideState(IBlockReader worldIn, BlockPos thisPos, Direction whichSide) {
    BlockPos sideBlockPos = thisPos.offset(whichSide);
    BlockState sideBlockState = worldIn.getBlockState(sideBlockPos);
    BlockPos upBlockPos = thisPos.up();
    BlockState upBlockState = worldIn.getBlockState(upBlockPos);
    // first: check if the wire can go up:
    //     the block above the wire is empty, and
    //     the block to the side has a solid top (eg stone block, or slab placed in upper half space), and
    //     the block on top of the block to the side can be connected to using side==null
    //   if so: check the side of the side block: if solid (eg stone block), redstone runs up the side of the block
    //            if side is not solid (eg slab): redstone goes to the side of the block but does not run up the face
    if (!upBlockState.isNormalCube(worldIn, upBlockPos)) {
       boolean sideBlockHasSolidTop = sideBlockState.isSolidSide(worldIn, sideBlockPos, Direction.UP) || sideBlockState.getBlock() == Blocks.HOPPER;
       BlockPos aboveSideBlockPos = sideBlockPos.up();
       BlockState aboveSideBlockState = worldIn.getBlockState(aboveSideBlockPos);
       if (sideBlockHasSolidTop && canConnectTo(aboveSideBlockState, worldIn, aboveSideBlockPos, null)) {
          if (sideBlockState.isCollisionShapeOpaque(worldIn, sideBlockPos)) {
             return RedstoneSide.UP;
          }
          return RedstoneSide.SIDE;
       }
    }
    // if we can connect to the side of the block, return SIDE
   //  otherwise, if the block to the side is empty and the block below the block to the side can be connected to side==null, SIDE
    if (canConnectTo(sideBlockState, worldIn, sideBlockPos, whichSide)) return RedstoneSide.SIDE;
    if (sideBlockState.isNormalCube(worldIn, sideBlockPos)) return RedstoneSide.NONE;
    if (canConnectTo(worldIn.getBlockState(sideBlockPos.down()), worldIn, sideBlockPos.down(), null)) return RedstoneSide.SIDE;
    return RedstoneSide.NONE;
 }
```

**Comment by pupnewfster** [comment]
Oh so is `null` used as the side for when it is basically going at a diagonal up and over (or down and over)? I sort of forgot that that case exists and wouldn't just be `Direction.UP` type of thing when typing my previous comment.

**Comment by TheGreyGhost** [comment]
yeah that's right
Actually, come to think of it, it would actually be helpful for canConnectRedstone to have that as a separate flag entirely
i.e.  so that the block can tell the difference between
1) redstone trying to connect horizontally
2) redstone trying to climb up and over onto a given side of a block

eg 
```
    /**
     * Determine if this block can make a redstone connection on the side provided,
     * Useful to control which sides are inputs and outputs for redstone wires.
     *
     * @param world The current world
     * @param pos Block position in world
     * @param side the side of the wire that is trying to make a horizontal connection to this block.
     * @param diagonaldirection UP or DOWN for a stepped connection (i.e. the wire is trying to run up or down the side of solid block in order to connect to this block)
     * @return True to make the connection
     */
    default boolean canConnectRedstone(IBlockReader world, BlockPos pos, Direction side, Direction diagonalDirection)
    {
        return getBlockState().getBlock().canConnectRedstone(getBlockState(), world, pos, side, diagonalDirection);
    }

and

private RedstoneSide getSide(IBlockReader worldIn, BlockPos thisPos, Direction whichSide) {
    BlockPos sideBlockPos = thisPos.offset(whichSide);
    BlockState sideBlockState = worldIn.getBlockState(sideBlockPos);
    BlockPos upBlockPos = thisPos.up();
    BlockState upBlockState = worldIn.getBlockState(upBlockPos);
    // first: check if the wire can go up:
    //     the block above the wire is empty, and
    //     the block to the side has a solid top (eg stone block, or slab placed in upper half space), and
    //     the block on top of the block to the side can be connected to from this side
    //   if so: check the side of the side block: if solid (eg stone block), redstone runs up the side of the block
    //            if side is not solid (eg slab): redstone goes to the side of the block but does not run up the face
    if (!upBlockState.isNormalCube(worldIn, upBlockPos)) {
       boolean sideBlockHasSolidTop = sideBlockState.isSolidSide(worldIn, sideBlockPos, Direction.UP) || sideBlockState.getBlock() == Blocks.HOPPER;
       BlockPos aboveSideBlockPos = sideBlockPos.up();
       BlockState aboveSideBlockState = worldIn.getBlockState(aboveSideBlockPos);
       if (sideBlockHasSolidTop && canConnectTo(aboveSideBlockState, worldIn, aboveSideBlockPos, side, Direction.UP)) {
          if (sideBlockState.isCollisionShapeOpaque(worldIn, sideBlockPos)) {
             return RedstoneSide.UP;
          }
          return RedstoneSide.SIDE;
       }
    }
    // if we can connect to the side of the block, return SIDE
   //  otherwise, if the block to the side is empty and the block below the block to the side can be connected to from this side, SIDE
    if (canConnectTo(sideBlockState, worldIn, sideBlockPos, whichSide, whichSide)) return RedstoneSide.SIDE;
    if (sideBlockState.isNormalCube(worldIn, sideBlockPos)) return RedstoneSide.NONE;
    if (canConnectTo(worldIn.getBlockState(sideBlockPos.down()), worldIn, sideBlockPos.down(), whichSide, DOWN)) return RedstoneSide.SIDE;
    return RedstoneSide.NONE;
 }
```

**Comment by LexManos** [comment]
I dont consider the current state a bug. It mimics vanilla behavior so we're keeping it. If you actually want more detailed looks then work on explaining a better use case. Your 'fake position' could just use a valid side.

**Comment by TheGreyGhost** [comment]
Howdy

Your current patch implementation doesn't allow modders to write their own redstone.

Redstone wire gets a special check in canConnectTo, i.e. it returns true even if side is null (i.e. when the caller is attempting to connect vertically).  This lets redstone climb up the side of a block to connect to the redstone wire on top of the block.

The current patch will always return false for the modder's block if side is null.

if you removed the "&& side != null" from the patch, it would allow modders to return true when side==null, in the same way that redstone wire does.

Cheers
  TGG

```
   protected static boolean canConnectTo(BlockState blockState, IBlockReader world, BlockPos pos, @Nullable Direction side) {
      Block block = blockState.getBlock();
      if (block == Blocks.REDSTONE_WIRE) {
         return true;
      } else if (blockState.getBlock() == Blocks.REPEATER) {
         Direction direction = blockState.get(RepeaterBlock.HORIZONTAL_FACING);
         return direction == side || direction.getOpposite() == side;
      } else if (Blocks.OBSERVER == blockState.getBlock()) {
         return side == blockState.get(ObserverBlock.FACING);
      } else {
         return blockState.canConnectRedstone(world, pos, side) && side != null;
      }
   }
```
