### ISSUE TITLE
Build fails using forge:1.15.2-31.2.5

### ISSUE THREAD

**Issue by stragulus** [MinecraftForge/MinecraftForge#6720]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.2.5

**Logs:** https://gist.github.com/stragulus/9ed916d002f930c95c2ed64a90e52392

**Steps to Reproduce:**
 1. Edit build.gradle, change forge version to 31.2.5
 2. Run gradle compileJava or build target from IntelliJ
 3. Witness stack trace

**Description of issue:**

Reproduced by changing back and forth between 31.2.0 (works) and 31.2.5 (fails) a few times. Somehow I do not get this build failure when running this through gradlew CLI after stopping the gradle daemon and removing the ~/.gradle/caches directory. However the same target in IntelliJ consistently fails, after which the CLI build also fails.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/ForgeGradle/commit/f44e6808f5d5102cf627a6771daf341b4b6e7f1c
