### ISSUE TITLE
Forge Dynamic Bucket model generates inner quads upside down

### ISSUE THREAD

**Issue by KnightMiner** [MinecraftForge/MinecraftForge#6726]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.2.5

**Steps to Reproduce:**

The model JSON below will reproduce this bug. Placing the bucket in an item frame will make the issue easier to visualize.

```json
{
  "loader": "forge:bucket",
  "fluid": "minecraft:empty",
  "textures": {
    "particle": "item/bucket",
    "base": "item/bucket"
  }
}
```

**Description of issue:**

The Forge dynamic bucket model generates the inner quads of the model using the opposite Y coordinate, causing gaps to appear in the model.
[This screenshot](https://user-images.githubusercontent.com/12155288/82991664-a42be280-9fc3-11ea-850c-ae19f57f6d19.png) demonstrates the issue well.

**Possible solution:**

Replacing [this line](https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/src/main/java/net/minecraftforge/client/model/ItemLayerModel.java#L127) with 
```java
int alpha = sprite.getPixelRGBA(f, u, vMax - v - 1) >> 24 & 0xFF;
```
appears to fix the issue, as shown in [this screenshot](https://user-images.githubusercontent.com/12155288/82991805-d9d0cb80-9fc3-11ea-9ee7-9840eb8d9254.png). However, I would like some feedback from @gigaherz as he has more experience with this area of the code (and will have a better idea if that is the right place to patch). I am willing to make a pull request if that fix is considered correct.

**Comment by gigaherz** [comment]
Fixed by 28f7b5d
