### ISSUE TITLE
fastutils out of bounds exception during common_setup

### ISSUE THREAD

**Issue by Pannoniae** [MinecraftForge/MinecraftForge#6728]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.2.5

**Logs:** See the linked issue

**Steps to Reproduce:**
 1. Start the game
 2. Watch it crash

**Description of issue:**
The game sometimes (about half the time) crashes with an arrayindexoutofbounds exception in some fastutils array when loading (in the common_setup phase) There is an error log by another user in the issue linked below but I also get the same error. If you want I can post an error log myself too.

**Comment by Pannoniae** [comment]
https://github.com/Markus1002/Autumnity/issues/11

**Comment by Pannoniae** [comment]
What is the reason for closing, is this an invalid issue?

**Comment by LexManos** [comment]
Nothing to do with Forge. And linking random other issues in comments is not how you file an issue. On top of that, use the forums for basic debugging and MAKE SURE it's a forge issue.
