### ISSUE TITLE
Javadoc for IForgeBlock::canConnectRedstone is incorrect

### ISSUE THREAD

**Issue by TheGreyGhost** [MinecraftForge/MinecraftForge#6743]
The Javadoc for IForgeBlock::canConnectRedstone is incorrect.

canConnectRedstone is strictly for outputs only, not inputs.
If a side of your block is an input, but returns true for canConnectRedstone, then the redstone will visually join to the side, but it still won't inject power into that side of the block unless it is pointed at the block, rather than just "passing by".

See also https://github.com/TheGreyGhost/MinecraftByExample/issues/48

```
    /**
     * Determine if this block can make a redstone connection on the side provided,
     * Useful to control which sides are inputs and outputs for redstone wires.
     *
     * @param state The current state
     * @param world The current world
     * @param pos Block position in world
     * @param side The side that is trying to make the connection, CAN BE NULL
     * @return True to make the connection
     */
    default boolean canConnectRedstone(BlockState state, IBlockReader world, BlockPos pos, @Nullable Direction side)
    {
        return state.canProvidePower() && side != null;
    }

```

**Comment by LexManos** [comment]
This is used for rendering the connected redstone points it doesnt mess with logic. The input or output is purely your own deal and are just concepts. The docs are fine IMO.

**Comment by TheGreyGhost** [comment]
Howdy 
>This is used for rendering the connected redstone points it doesnt mess with logic.
I don't think that's correct (see getWeakPower --> isPowerSourceAt --> canConnectRedstone) but it's beside the point.

My point is, canConnectRedstone is useless for inputs.  It only makes sense to return true if that side of your block is an output.  If you return true, the redstone will visually connect to that side of your block, but when your block asks the redstone for power, it won't get any unless the redstone is pointed at your block, in which case it would have drawn a connection even if canConnectRedstone returned false.

So the JavaDoc should say

    /**
     * Determine if this block should always visually connect redstone on the side provided.
     * Useful to specify which sides are outputs for redstone wires.

-TGG
