### ISSUE TITLE
Wolf pathing finding does not match vanilla

### ISSUE THREAD

**Issue by percivalalb** [MinecraftForge/MinecraftForge#6755]
**Minecraft Version:** 1.15.2

**Forge Version:** 32.2.9

**Steps to Reproduce:**
 1. Tame a vanilla wolf
 2. Walk away from the wolf so that the direct path between it and you crosses lava
 3. Watch the dog make no attempt to path around and kill itself

**Description of issue:**
Wolves in forge make no attempt to avoid lava whereas vanilla wolves will path around it.

Forge: https://gfycat.com/lankysnarlingenglishpointer
Vanilla: https://gfycat.com/tinyaggravatingequine

I assume this applies to other entity's pathing too.

**Comment by jamierocks** [comment]
perhaps something to do with the patches in https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/patches/minecraft/net/minecraft/pathfinding/WalkNodeProcessor.java.patch ?

**Comment by percivalalb** [comment]
https://github.com/MinecraftForge/MinecraftForge/blob/5dbea9ea8dbda01ad11d91a713eb29cc973c10eb/patches/minecraft/net/minecraft/pathfinding/WalkNodeProcessor.java.patch#L17
Is missing the change in x, y, z arguments, should be 
`func_189553_b(p_193578_0_, i + p_193578_1_, j + p_193578_2_, k + p_193578_3_);`

This does not fix this issue but still needs fixing. I have found that removing this part of the patch does fix it.
https://github.com/MinecraftForge/MinecraftForge/blob/1.14.x/patches/minecraft/net/minecraft/pathfinding/WalkNodeProcessor.java.patch#L52-L53

**Comment by percivalalb** [comment]
I think the problem is that `WalkNodeProcessor.getAiPathNodeType` returns `PathNodeType.LAVA` in vanilla and returns `PathNodeType.DANGER_FIRE`  in forge (this is when the block is a fluid contained in the lava tag)
