### ISSUE TITLE
no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no

### ISSUE THREAD

**Issue by TheoBuzz** [MinecraftForge/MinecraftForge#6774]
this is stupid fabric is already good this is bad fuck you delete this shit ur forg sucks use fabric mother fuckers forge sucks fabric is perfect awesome good for mod needs no forge is hacks hacks HACKS patchs stupid kill your self im gay btw

**Comment by haykam821** [comment]
I agree!

**Comment by TheoBuzz** [comment]
friend
