### ISSUE TITLE
/datapack disable "mod:forge" not working

### ISSUE THREAD

**Issue by IchHabeHunger54** [MinecraftForge/MinecraftForge#6776]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.2.0

**Logs:** https://gist.github.com/IchHabeHunger54/297ae4650db3ca4c6744724825a67a0a (debug.log)

**Steps to Reproduce/Issue Description:**
Run Minecraft Forge, type <code>/datapack disable "mod:forge"</code>
Expected behavior: The datapack gets disabled properly.
Actual behavior: There is a chat message that the datapack was disabled, while it was not, <code>/datapack disable "mod:forge"</code> still works, while the command parser doesn't accept <code>/datapack enable "mod:forge"</code>.

The issue is not only present within forge, but also within any mod you'd like (in the log, I tested it with Iron Chests and, in other instances, also with mods such as Buzzier Bees, Carbonado or Quark). 
<code>/datapack disable vanilla</code>, however, works, as well as a custom datapack in the world directory.

**Comment by SquidDev** [comment]
There's some relevant discussion in #5506 about this, though it has since been closed as stale.

**Comment by IchHabeHunger54** [comment]
Just tested it: It also doesn't work in 31.2.19 (currently latest)
