### ISSUE TITLE
Incompatible JNA packages brought in as libraries

### ISSUE THREAD

**Issue by ameisen** [MinecraftForge/MinecraftForge#6780]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.2.19

**Description of issue:**

By default, the libraries brought in by Forge have incompatible package versions for JNA.

`net.java.dev.jna:jna` is `4.4.0` whereas `net.java.dev.jna:platform` is `3.4.0`.

This is likely due to the fact that the `platform` package was renamed `jna-platform` after `3.5.2`. `net.java.dev.jna:jna-platform`, as far as I can tell, is API-compatible and has equivalent versions to the `jna` package.

Please consider bringing in [`jna-platform`](https://mvnrepository.com/artifact/net.java.dev.jna/jna-platform/4.4.0) instead of `platform` with an equivalent version. I haven't noticed any issues resulting from this yet, but these two packages should be loaded with the same version.

**Comment by LexManos** [comment]
Mojang is the one who specifies the libraries and what versions to import. 
https://launchermeta.mojang.com/v1/packages/97e7f6c94e2f9841d128011d4d9192fabdc874d4/1.15.2.json
