### ISSUE TITLE
Forge re-introduces bug converting coarse dirt and podzol to dirt after sapling is grown, breaking tree farms 

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#6781]
A user found a bug with Forge but was unable to post it here due to Forge's anti-spam measures. So I am reposting their issue report they had posted on Botania back to here where it properly belongs. 

Original issue report: https://github.com/Vazkii/Botania/issues/3329

Content of issue report:
--------
# Version Information
Forge version: forge-31.2.20
Botania version: Botania-r1.15-385.jar

# Further Information
https://bugs.mojang.com/browse/MC-57884 fixed back in 2014

Additionally according to this
Mycelium should NOT allow saplings to be planted on it (verified for vanilla 1.15.2) but once Forge is installed (tested up to latest forge-31.2.20)  mycelium allows the planting of saplings again. (also bad.)

Once the sapling grows, the Coarse Dirt, and Podzol (and apparently erroneously, Mycelium) get converted back to plain dirt again.

this breaks several modded operations/options not the least of which is Botania Tree Farms for which you use the Rannuncarpus to select the coarse dirt to plant the saplings on to differentiate from regular dirt or grass nearby.

screenshot: https://imgur.com/0NwIANg

I have made multiple attempts at filing this report with Forge this morning after confirming the bug, but cannot get past their blasted spam registration protection to create an account with and either search the forums properly to see if the bug is even reported yet, or submit my own.

Confirmed this bug exists SOLELY when 1.15.2 + forge-31.2.20 and no other mods installed. so NOT a botania issue, but directly affects botania, so you were my second choice for getting this reported upstream since I cannot register at minecraftforge.net. (grr. apologies.)

**Comment by TelepathicGrunt** [comment]
Someone in discord has pointed out the issue is because of canSustainPlant method that forge added to the Blocks class (line 1016) and has added their own isSoil method to AbstractTreeFeature which calls canSustainPlant. Since canSustainPlant is also called for saplings and mycelium is in the dirt tag that canSustainPlant uses, this is what is causing saplings to be placed on mycelium as well.

All these issues seems to tie into how canSustainPlant is setup and should be looked into how to improve that method to resolve these problems.

**Comment by marchermans** [comment]
Was able to reproduce this as well.
Indeed the logic in and around canSustainPlant needs an overhaul.

**Comment by TheCurle** [comment]
This will be fixed with the PlantType overhaul in 1.17, which will most likely be backported to 1.16 when the time comes.
For 1.15... we'll see.
