### ISSUE TITLE
Potential datagen sorting issue.

### ISSUE THREAD

**Issue by hanetzer** [MinecraftForge/MinecraftForge#6783]
**Steps to Reproduce:**
 0.  must be run on a linuxy system (my case was gentoo ~amd64)
 1. `git clone https://github.com/SlimeKnights/TinkersConstruct`
 2. `gradlew runData`
 3. `git diff src/generated/resources/.cache/cache`

**Description of issue:**
One or more of the developers of Tinkers Construct use windows, and I use linux.
When I do runData for new recipe/loot table/etc I always get the following change:
```diff
diff --git a/src/generated/resources/.cache/cache b/src/generated/resources/.cache/cache
index 0e711a6af0..8f4b661397 100644
--- a/src/generated/resources/.cache/cache
+++ b/src/generated/resources/.cache/cache
@@ -64,13 +64,13 @@ f1062a73b4417d8772ebb9aa9189aa4064f649e0 data/forge/tags/items/ores/ardite.json
 05669b0f8399c31b028661957b82d60cc4b10a9c data/forge/tags/items/ores/cobalt.json
 f6d948da59e46d26cfc34188b9b140dd37f437d1 data/forge/tags/items/rods.json
 cb4d6289ec4c32cf5b57f3fa21419376486a7cae data/forge/tags/items/rods/stone.json
-2513ecf2fc1caedde8be0b41be0e6bf4e149dab6 data/forge/tags/items/slimeballs.json
 9ecc2c411681c0fc1a42acc3cdf7510783ffaec7 data/forge/tags/items/slimeball/blood.json
 8a9941607c1100a061f3c47d203b834dc91dc243 data/forge/tags/items/slimeball/blue.json
 a7629398a73eef2b5267342d79f1cebcf2b1eec4 data/forge/tags/items/slimeball/green.json
 1cb76aaacdb5b68a408abf6fac03a3b8a3a5d7d4 data/forge/tags/items/slimeball/magma.json
 caa063b792e2560c06105fd235ef20ffb152058f data/forge/tags/items/slimeball/pink.json
 cd0c3987c9be5c4d2fe8e9352734c581e1d60f15 data/forge/tags/items/slimeball/purple.json
+2513ecf2fc1caedde8be0b41be0e6bf4e149dab6 data/forge/tags/items/slimeballs.json
 67c5756a5424da1261b7e83f7ce0ced0763f5196 data/forge/tags/items/stained_glass.json
 ea3d6efc7f691cff6c7ad0eb59cf13ad9597afe1 data/forge/tags/items/storage_blocks.json
 74fb0e0d20e0081c34e64f3506802d8f4321ee01 data/forge/tags/items/storage_blocks/alubrass.json
```

This change of sorting always occurs, even on a clean checkout of the code. I think
this may do with the locale used to sort the second column.

[Related TiC issue/pr](https://github.com/SlimeKnights/TinkersConstruct/pull/4132)

**Comment by diesieben07** [comment]
Problem is this patch to [DirectoryCache](https://github.com/MinecraftForge/MinecraftForge/blob/6345f2670c4b38ab2e14db0102beca81d180995b/patches/minecraft/net/minecraft/data/DirectoryCache.java.patch#L8).
It aims to make the output predictable, but [Path.compareTo](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#compareTo-java.nio.file.Path-) depends on the OS.
I'll make a PR.

**Comment by diesieben07** [comment]
Actually, thinking about it a bit more, why are you committing the cache?

**Comment by LordMonoxide** [comment]
Is committing the cache wrong? I just commit the entire directory

**Comment by diesieben07** [comment]
I don't see the point of committing it, but I'm not sure.

**Comment by KnightMiner** [comment]
See also #6508. It's not been removed from the default .gitignore

**Comment by hanetzer** [comment]
On a bit more investigation, I had thought its to do with the sorting
happening before the `\\->/` swap. But `\` has a hex value of `0x5c`,
`s` has a value of `0x73`, and `/` has a value of `0x2f`, so the sort
order is `/\s` so that's not it I guess.

**Comment by LexManos** [comment]
try adding .sorted() to line 59, before collect but after map.
That way it'll do string sorting not path sorting.

**Comment by hanetzer** [comment]
hanetzer/MinecraftForge@4503a7ade5c4f7b140a30cfe826353fd2517fab4
It caused some rearrangements of the cache file. Could someone on windows
give this a test? gradle task is `forge forge test data`

**Comment by hanetzer** [comment]
Its now sorting by the hash instead of the path, so no nice clusters anymore but
it should be consistent?

**Comment by KnightMiner** [comment]
Sorting by the hash may get annoying. Its nice when you update a file that it stays in the same place for commits. Of course, consistent across OS is more important

**Comment by hanetzer** [comment]
Perhaps there is some flag you could set on the Path element to make it
a unixy path ahead of time, without needing to do the `\\ -> /` swap after
the fact?

**Comment by LexManos** [comment]
Ah right it includes the hash, you'll have to make it split out just the path

**Comment by diesieben07** [comment]
`Joiner.on('/').join(path)` will turn a `Path` into a `String` OS-independent.

**Comment by hanetzer** [comment]
> `Joiner.on('/').join(path)` will turn a `Path` into a `String` OS-independent.

Not in a position to try this just yet, but I assume you mean to replace the
.toString() call with this?

**Comment by diesieben07** [comment]
Currently there is no `toString`. `toString` would already be better, except for the file separator. Currently `compareTo` is used, which is completely os dependent.

**Comment by hanetzer** [comment]
No I mean [here](https://github.com/MinecraftForge/MinecraftForge/blob/6345f2670c4b38ab2e14db0102beca81d180995b/patches/minecraft/net/minecraft/data/DirectoryCache.java.patch#L17), this `toString()` and friends.

**Comment by diesieben07** [comment]
That doesnt actually change the sorting, that is determined by the TreeMap.

**Comment by hanetzer** [comment]
Ah. I couldn't find any compareTo in the class itself. So what is your suggestion, then;
to turn the `Map<Path, String>` to a `Map<String, String>`, where the other string
is from that Joiner snippet?

**Comment by diesieben07** [comment]
Make a custom comparator instead of just letting TreeMap use compareTo

**Comment by hanetzer** [comment]
tbqf even if I could do the logic properly I don't actually get where compareTo
is being used to replace it, unless its Object.equals() calling it.

**Comment by diesieben07** [comment]
TreeMap when used without explicit comparator uses compareTo.

**Comment by hanetzer** [comment]
Could someone give this a go, and let me know how the cache file
is altered?
```diff
diff --git a/src/test/java/net/minecraftforge/debug/DataGeneratorTest.java b/src/test/java/net/minecraftforge/debug/DataGeneratorTest.java
index 0da4153cb..e92b3300b 100644
--- a/src/test/java/net/minecraftforge/debug/DataGeneratorTest.java
+++ b/src/test/java/net/minecraftforge/debug/DataGeneratorTest.java
@@ -205,6 +205,19 @@ public class DataGeneratorTest
                 .add(BlockTags.STONE_BRICKS)
                 .addOptional(BlockTags.getCollection(), new ResourceLocation("chisel", "marble/raw"))
                 .addOptionalTag(new ResourceLocation("forge", "storage_blocks/ruby"));
+
+            // Hopefully sorting issues
+            getBuilder(new BlockTags.Wrapper(new ResourceLocation(MODID, "thing/one")))
+                    .add(Blocks.COBBLESTONE);
+            getBuilder(new BlockTags.Wrapper(new ResourceLocation(MODID, "thing/two")))
+                    .add(Blocks.DIORITE);
+            getBuilder(new BlockTags.Wrapper(new ResourceLocation(MODID, "thing/three")))
+                    .add(Blocks.ANDESITE);
+
+            getBuilder(new BlockTags.Wrapper(new ResourceLocation(MODID, "things")))
+                    .add(Blocks.COBBLESTONE)
+                    .add(Blocks.DIORITE)
+                    .add(Blocks.ANDESITE);
         }
     }
 
```
Theoretically this should show the same kind of sorting issue as above.

**Comment by hanetzer** [comment]
Or better yet. gimme a bit, I'll just put up the craptastic code I have and we'll see.

**Comment by hanetzer** [comment]
hanetzer/MinecraftForge@894132c5899a3ba166fcabf10920b6e3fd72d141
