### ISSUE TITLE
URL for Missing dependencies

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#6798]
When defining dependencies in the TOML we could add a optional url to get said dependency. If the mod is installed but the version is outdated the URL defined from that mod should have priority.

This would require changes in ForgeSPI aswell and as cpw made it I would like to hear his feedback on this.

**Comment by LexManos** [comment]
No, we will not download and run arbitrary code try o end users computers.

**Comment by Alpvax** [comment]
I read it as displaying a clickable URL to the mod download page (e.g. curseforge), not automatically downloading anything.
