### ISSUE TITLE
./gradlew genIntellijRuns not working

### ISSUE THREAD

**Issue by BradCol** [MinecraftForge/MinecraftForge#6801]
When I run ./gradlew genIntellijRuns it says Could not find org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822.
The full error here:

iMac:CrystallineGateways myname$ ./gradlew genIntellijRuns
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.9/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
New Dep: net.minecraftforge:forge:1.12.2-14.23.5.2854_mapped_snapshot_20171003-1.12

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'CrystallineGateways'.
> Could not resolve all files for configuration ':_compileJava_1'.
   > Could not find org.lwjgl.lwjgl:lwjgl-platform:2.9.2-nightly-20140822.
     Searched in the following locations:
       - https://files.minecraftforge.net/maven/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
       - https://files.minecraftforge.net/maven/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
       - file:/Users/myname/.gradle/caches/forge_gradle/bundeled_repo/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
       - file:/Users/myname/.gradle/caches/forge_gradle/bundeled_repo/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
       - https://libraries.minecraft.net/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
       - https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.pom
       - https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/lwjgl-platform/2.9.2-nightly-20140822/lwjgl-platform-2.9.2-nightly-20140822.jar
     Required by:
         project : > net.minecraft:client:1.12.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6s

**Comment by sciwhiz12** [comment]
> 1.12.2-14.23.5.2854

You are using an outdated version of Minecraft (1.12.2), and is out of support by Forge.
Please update to a modern and supported version.

**Comment by FinnT730** [comment]
we told this in the Discord even -_-
