### ISSUE TITLE
[1.16.1] Forge brings back a Snapshot visual bug.

### ISSUE THREAD

**Issue by Bass2style** [MinecraftForge/MinecraftForge#6814]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.6

**Logs:** no logs but screenshots :
when not hovering : http://image.noelshack.com/fichiers/2020/26/5/1593139473-2020-06-26-04-42-11.png
when hovering : http://image.noelshack.com/fichiers/2020/26/5/1593139473-2020-06-26-04-42-18.png

**Steps to Reproduce:**
 1. get some items that stacks
 2. open your inventory
 3. hover items, and you see the number of stacked items over the tooltips.

**Description of issue:**
screenshots will be obvious, but when you hover stacked items, the number of the stacked items appairs over the tooltip box.

i have no mods installed (i removed all of them), and this bug is not present in vanilla 1.16.1. (but well in older snapshots.)

**Comment by Cyborgmas** [comment]
this should be fixed in #6815
