### ISSUE TITLE
[1.16.1] strange behavior when sneaking underwater

### ISSUE THREAD

**Issue by Bass2style** [MinecraftForge/MinecraftForge#6816]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.6

**Logs:** no crash reports, but a vid (actually treated by YT, sorry) : https://youtu.be/ThJ0IcAEdVU

**Steps to Reproduce:**
 1. move to your favorite watered spot
 2. let sink into it
 3. sneak !

**Description of issue:** when sneaking, it's acting like when you press space, and you go back to the surface. (but you are visually sneaking in F5)
this is not a Vanilla bug, tested before reporting, and i have no mods installed.

**Comment by Yunus1903** [comment]
Fixed in #6817
