### ISSUE TITLE
[1.16.1] When change Block's RenderType, The BlockItem's RenderType doesn't change.

### ISSUE THREAD

**Issue by FledgeXu** [MinecraftForge/MinecraftForge#6823]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.1

**Logs:** 
There are not any logs.

**Steps to Reproduce:**
1. Create a block and register it.
2. Create a BlockItem and register it.
3. Change Block's RenderType.

**Description of issue:**
1.15.2
![image](https://user-images.githubusercontent.com/16664654/85839837-1a438500-b7ce-11ea-9726-485b51547aca.png)
1.16.1
![image](https://user-images.githubusercontent.com/16664654/85839857-23cced00-b7ce-11ea-9c8f-97f5cb006cc1.png)

**Source Code**
[Code](https://github.com/FledgeXu/BosonSourceCode/tree/master/src/main/java/com/tutorial/neutrino/special_render_type)

**Comment by Cyborgmas** [comment]
This was pulled and should be closed, but take a look at what I say in #6833

**Comment by TheCurle** [comment]
6832 was merged, closing. 
Conversation moved to 6833
