### ISSUE TITLE
RenderGameOverlay missing getter method for matrix stack

### ISSUE THREAD

**Issue by korti11** [MinecraftForge/MinecraftForge#6828]
**Minecraft Version:** 1.16.1
**Forge Version:** 32.0.7

**Description of issue:**
Correct me if I'm wrong or this is intended but the [MatrixStack variable](https://github.com/MinecraftForge/MinecraftForge/blob/cbac95de0f29a056374fea5dfc27617c8d21aec0/src/main/java/net/minecraftforge/client/event/RenderGameOverlayEvent.java#L74) in the [RenderGameOverlayEvent](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/client/event/RenderGameOverlayEvent.java) is missing a getter method.

**Comment by Cyborgmas** [comment]
Very possible, GUI stuff now have a MatrixStack everywhere

**Comment by TheCurle** [comment]
Related PR was merged, closing.
