### ISSUE TITLE
1.16.1 How to deal with fabulous graphics options for BlockItem entities

### ISSUE THREAD

**Issue by Cyborgmas** [MinecraftForge/MinecraftForge#6833]
While making #6832 noticed that the custom block item entity I debugged with was not getting the "fabulous" render type (Atlases.field_239279_C_) while vanilla ones were.

This is because in ItemRenderer#renderItem , flag1 is set to an instance check of BreakableBlock and StainedGlassPaneBlock and it is responsible for whether or not the entity will receive fancy or fabulous transparency.

This is of course an easy fix, I made the custom block extend BreakableBlock and it works, receiving teh correct transparency.

However, unsure if forge would want to make a better way of determining if a block should be Fabulously transparent. As in have a function in IForgeBlock and IForgeBlockState to do this instead.

**Comment by TheCurle** [comment]
It may be worth refactoring BreakableBlock to TranslucentBlock, or ShaderBlock. 
Thoughts?
