### ISSUE TITLE
[1.16.1][32.0.15]Swimming doesn't "speed boost" the player

### ISSUE THREAD

**Issue by Bodiw** [MinecraftForge/MinecraftForge#6835]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.15

**Logs:** None,as I doubt the log can collect this issue

**Steps to Reproduce:**
Try to swim.
<https://youtu.be/oyeuwKP9ysg>
Video with the issue

**Description of issue:**
While attempting to swim,the "speed boost" isnt applied,in other words,why am I so slow?
Tested 3 times on just made worlds ,survival and creative.
Reproduced with and without any active mods.

**Comment by tehbiga** [comment]
I was _JUST_ about to create this same issue.

Similar to this, swimming is _super_ slow in general on forge. I just did a side by side comparison _(no real numbers)_ and forge water locomotion is very slow.

**Comment by Bodiw** [comment]
You got beaten by seconds sir.

**Comment by TheCurle** [comment]
#6845 seems to have the fix for this.

**Comment by TheCurle** [comment]
6845 was merged, closing.
