### ISSUE TITLE
[1.16] Incorrect forge versions

### ISSUE THREAD

**Issue by Tom-The-Geek** [MinecraftForge/MinecraftForge#6852]
**Minecraft Version:** 1.16.1

**Forge Version:** 1.16.1-32.0.14

**Description of issue:**
When specifing forge/minecraft dependency versions in mods.toml, the game fails to launch with incorrect dependency versions:

![image](https://user-images.githubusercontent.com/23531706/85919209-4bb96080-b861-11ea-948f-39a3cf8cd549.png)

***My `mods.toml`:***
https://pastebin.com/raw/ya3DqNq5

**Comment by ichttt** [comment]
You need to re-genereate your run configs when updating. Also use the forums for support
