### ISSUE TITLE
[1.16.1] ItemEntity patch port error, readAdditional code is in writeAdditional

### ISSUE THREAD

**Issue by ricksouth** [MinecraftForge/MinecraftForge#6854]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.23

**Logs:** N/A

**Steps to Reproduce:**
```
	@SubscribeEvent
	public void onItemJoinWorld(EntityJoinWorldEvent e) {
		World world = e.getWorld();
		if (world.isRemote) {
			return;
		}
		
		Entity entity = e.getEntity();
		if (entity instanceof ItemEntity == false) {
			return;
		}
		
		ItemEntity ie = (ItemEntity)entity;
		CompoundNBT nbtc = ie.serializeNBT();
		nbtc.putInt("Lifespan", 20); // set lifespan in ticks
		ie.read(nbtc);
	}
```

**Description of issue:**
Hi! First of all, thank you for the quick update to 1.16. Appreciate all the work you do very much.

In 1.15, this code was able to change the lifespan of all ItemEntitities in the world. By changing the NBT value. In 1.16 I can't seem to change the lifespan, even though I don't see any changes in the immediate code. Not experienced enough with the Forge format to make a pull request, hope this can be of some use though.

**Comment by pau101** [comment]
It does appear there is a patch port error, where the code intended to be in `readAdditional` is inside `writeAdditional` instead.

In regards to your code though you could just be setting the `lifespan` field directly, which is in fact public and has always been.

**Comment by ricksouth** [comment]
That does sound like a quicker road to Rome! Thanks for the advice.

**Comment by TheCurle** [comment]
There is indeed a regression here, but the user's issue has been solved. This issue will remain open until the patch error has been fixed.

**Comment by sciwhiz12** [comment]
I assume, as the PR mentioning this issue has been resolved, that this issue can be safely closed?

**Comment by ricksouth** [comment]
Correct, thanks forge team!
