### ISSUE TITLE
forums.minecraftforge.net doesn't work(404)

### ISSUE THREAD

**Issue by nkdmSum** [MinecraftForge/MinecraftForge#6856]
**Minecraft Version:** N/A

**Forge Version:** N/A

**Logs:** https://forums.minecraftforge.net | Image:
<img width="1429" alt="Снимок экрана 2020-06-27 в 14 47 24" src="https://user-images.githubusercontent.com/51021475/85923266-1f660a00-b88a-11ea-9bcc-019397b56557.png">

Go to https://forums.minecraftforge.net

**Description of issue:**
If you try to go to https://forums.minecraftforge.net , then you will see what you see above.
https://files.minecraftforge.net works just fine!

**Comment by FinnT730** [comment]
It is a known issue.
