### ISSUE TITLE
Unable to use existing tags in Data Generators

### ISSUE THREAD

**Issue by pupnewfster** [MinecraftForge/MinecraftForge#6857]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.23

**Logs:** https://gist.githubusercontent.com/pupnewfster/b81e396d26730c5a3351de46e441d502/raw/dda5ebfca9467f2c25601d19b60fccb89060dc72/gistfile1.txt

**Steps to Reproduce:**
 1. Download the test mod https://github.com/pupnewfster/DataGenerator-Failure and try to run the data generator

**Description of issue:**
Due to the changes in the tag system it seems that it is no longer possible to use tags in recipe data generators if you are not adding to the tag yourself. and instead get the error message: `Tag x used before it was bound` for example in the test mod trying to use forge's cobblestone tag gives the error `Tag forge:cobblestone used before it was bound`.

**Comment by TBoshoven** [comment]
I've been looking into this problem, but kind of gave up for now.
What I did find is that Forge itself has this issue as well. Running Forge datagen fails on a recipe with this exact error.

Reproduction steps:
* Set of Forge development
* Run the `forge_data` task in Gradle

```
java.lang.IllegalStateException: Tag minecraft:acacia_logs used before it was bound
at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:77)
```

**Comment by covers1624** [comment]
God damnit, I ran into this _exact_ issue when I was fixing patches (only it was on launch not datagen). We need to build the TagCollections and do something similar to `NetworkTagManager.func_232980_f_` and call `BlockTags.setCollection` and so on. Tags now get a callback when the collection is updated to refresh their internal cache, and since the collection is never updated, you hit that exception.

**Comment by Cyborgmas** [comment]
Yeah what i found is that in forge, there are calls to retrieve the Tag, using `NamedTag#func_232944_c_`  but vanilla never uses that

**Comment by pupnewfster** [comment]
Resolved by https://github.com/MinecraftForge/MinecraftForge/commit/d5aa0c4a9121558f9c19db8c3a21b8b12217086a
