### ISSUE TITLE
FMLServerAboutToStartEvent fires too late on integrated servers

### ISSUE THREAD

**Issue by pupnewfster** [MinecraftForge/MinecraftForge#6859]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.23

**Description of issue:**
I used the `FMLServerAboutToStartEvent` to add a reload listener for some custom tags between vanilla's tag reload listener, and vanilla's recipe reload listener. In 1.16, `FMLServerAboutToStartEvent` is fired after recipes already start loading on an integrated server, but on a dedicated server this event is fired at the expected time and I am successfully able to add my listener and have it get fired before recipes load. I am not sure but I would not be fully surprised if the reload listeners don't do their initial firing at all on an integrated server due to the `FMLServerAboutToStartEvent` being fired after after the reload listeners start running.

**Comment by Cyborgmas** [comment]
I think this one is due to #6842

**Comment by pupnewfster** [comment]
I don't think so, as these are custom tag types and I have my own tag manager that I am trying to add in a specific place, and I am only able to do so on a dedicated server and not an integrated one.

**Comment by Cyborgmas** [comment]
oh mb read that the other way around, that dedicated was not working

**Comment by pupnewfster** [comment]
Closing this as I am not sure this is even an issue and I believe I was mainly just confused due to not realizing that how reload listeners are managed changed internally. I also believe #6849 will work well enough for my needs.
