### ISSUE TITLE
[1.16.1] Eclipse Workspace missing certain rendering methods

### ISSUE THREAD

**Issue by PT400C** [MinecraftForge/MinecraftForge#6869]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.24 / latest

**Logs:** -
**Steps to Reproduce:**
 1. Setup a blank Eclipse Forge 1.16.1 workspace
 2. Then simply open the file `com.mojang.blaze3d.systems.RenderSystem` and look for the method `setupGui3DDiffuseLighting`
 3. Check if it points to the method `GlStateManager.func_237513_b_(p_setupGui3DDiffuseLighting_0_, p_setupGui3DDiffuseLighting_1_)` which seems to NOT exist

**Description of issue:** Check the steps above

**Comment by diesieben07** [comment]
Cannot reproduce. `GlStateManager#func_237513_b_` exists (both in Eclipse with latest MDK and also check in IntelliJ).
Please provide more details.

**Comment by PT400C** [comment]
I'm performing some tests too. My Gradle cache might just be corrupted after using some early 1.16.1 Forge builds. If this proves to be right, I'll just close the issue.

**Comment by PT400C** [comment]
~ ForgeGradle cache was the cause
