### ISSUE TITLE
1.16 - How to approach new tags 

### ISSUE THREAD

**Issue by Cyborgmas** [MinecraftForge/MinecraftForge#6870]
Tags need to be created/updated/removed with 1.16, I propose to discuss them here as to what should be done.

My suggestions are here: https://gist.github.com/Cyborgmas/60203cda033297b1f84b2293499bdca5 , comment on what sounds good/bad/terrible and what I missed.

**Comment by TBoshoven** [comment]
I think there are at least some that so far everyone has agreed with. We could start by making a PR to sort those out.

**Comment by Alpvax** [comment]
Re vanilla gold ore tag, I would suggest making the vanilla tag inherit from the forge one, so that modders still add to the forge tag for consistency
