### ISSUE TITLE
Datapack validation failed! 1.16.1

### ISSUE THREAD

**Issue by Blaueschmied** [MinecraftForge/MinecraftForge#6898]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.38

**Logs:** [debug.log](https://github.com/MinecraftForge/MinecraftForge/files/4862493/debug.log)

**Steps to Reproduce:**
 1. Create a new World
 2. Try to add a datapack rough the button in the caw screen

**Description of issue:**
If you try to add a datapack trough the Create a World screen. i says "datapack validation failed!"
![problem](https://user-images.githubusercontent.com/59196184/86326227-ad067880-bc41-11ea-8b09-d0c682ec0bd8.gif)

**Comment by sciwhiz12** [comment]
Please post your issues first to the [Forge Support Forum](https://forums.minecraftforge.net/forum/18-support-bug-reports/), as this issue tracker is for final bug reports.

Have you tried loading without the datapack? If so, then the issue most likely exists with the datapack.

**Comment by Cyborgmas** [comment]
I verified it was a bug, see #6913
