### ISSUE TITLE
Game cant start anymore

### ISSUE THREAD

**Issue by Cap-Salt** [MinecraftForge/MinecraftForge#6900]
**Minecraft Version:** {Minecraft version} 1.15.2

**Forge Version:** {Forge version. *Version number, not latest/rb*} 31.2.30

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/4864908/latest.log)

**Steps to Reproduce:**
 1. I just tried to start the game
 2. Then do that
 3. ...

**Description of issue:**The start process is aborted shortly after pressing the play button and the start window opens with the message that the game has crashed

**Comment by sciwhiz12** [comment]
You are using OptiFine. Beware that this is not officialy supported, as OptiFine is a closed-source project, and as such only sp614x, OptiFine's author, can debug most issues.

That being said, it seems that OptiForge is causing the issue. Update that mod, or remove it altogether.
Also, in the future, please bring your issues first to the [forums](https://forums.minecraftforge.net/forum/18-support-bug-reports/).

**Comment by Cap-Salt** [comment]
Yeah I asked on Discord too and they told me that too I removed optifine and the game started again but I cant join or create any world

**Comment by Cap-Salt** [comment]
I uploaded a the debug.log on gist
