### ISSUE TITLE
.harvestTool() and .harvestLevel() still not working.

### ISSUE THREAD

**Issue by Agilapathy** [MinecraftForge/MinecraftForge#6906]
**Minecraft Version:** 1.16.1
**Forge Version:** 32.0.46

**Logs:** N/A

**Steps to Reproduce:**
 1. Add .harvestTool() and/or .harvestLevel() to your block's properties

**Description of issue:**
When adding these properties to your block, you are still able to collect blocks with a conflicting tool tier or tool type.

**Comment by sciwhiz12** [comment]
Have you tried calling `AbstractBlock$Properties#func_235861_h_`? This function sets a boolean flag as true (`field_235806_h_`), which controls if a block requires that the held itemstack can harvest the block.

See `PlayerEntity`, L709 for the harvest check event call, specifically the second argument: 
```java
!blockStateIn.func_235783_q_() || this.inventory.getCurrentItem().canHarvestBlock(blockStateIn)
```
The first conditional requires that the function `func_235783_q_` [which only returns what `field_235806_h_` is set to] returns true for the harvest check to continue to the second conditional.
Note that the function `func_235783_q_` is also called by `ForgeHooks.canHarvestBlock`; specifically, if the value is false, then the harvest check hook returns true, regardless of the harvest tool or level given.
