### ISSUE TITLE
[1.16] IForgeBlock.isBeaconBase does not check vanilla tag

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#6910]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.47

**Logs:** n/a

**Steps to Reproduce:**
 1. Add a block to the vanilla `beacon_base_blocks` tag
 2. Make a beacon with it
 3. Doesn't activate

**Description of issue:**
https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java#L550
needs to be updated to check the tag instead of a hardcoded list.

**Comment by Alpvax** [comment]
I would suggest removing the method now vanilla support has been added.
However, if there is a use case for some blockstate specific behaviour (e.g. blocks which can be toggled with redstone to enable/disable the beacon effects) then I could see a reason to keep the method.

**Comment by KnightMiner** [comment]
I honestly cannot think of a usecase. Any conditional beacon base is going to end up being more complicated to use than iron, so you may as well use iron. Not like there is an advantage to smaller beacons.

**Comment by Alpvax** [comment]
Yeah, hence my first sentence. That was the only use case I could see, and it's pretty weak

**Comment by sciwhiz12** [comment]
This issue can be closed, as a PR has been merged which fixes this.
