### ISSUE TITLE
[1.16] Translucent blocks do not render when being moved by a piston

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#6915]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.47

**Logs:** N/A

**Steps to Reproduce:**
 1. Put a sticky piston on a clock with stained glass
 2. Turn on clock
 3. Glass disappears when in motion
 4. Repeat in vanilla and note it stays rendered

**Description of issue:**
https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/patches/minecraft/net/minecraft/client/renderer/tileentity/PistonTileEntityRenderer.java.patch#L7

The patched-out call to `func_239221_b_` is important as it checks if the block is for the TRANSLUCENT layer and returns in its stead TRANSLUCENT_MOVING_BLOCK (yarn name). Not using that layer means it doesn't render (for some reason)

**Comment by Cyborgmas** [comment]
trying to debug and fix this , small note its only on fabulous settings

**Comment by diesieben07** [comment]
See https://github.com/MinecraftForge/MinecraftForge/pull/6847

**Comment by Vazkii** [comment]
Can still reproduce in 1.16.3 with Forge 34.1.32
