### ISSUE TITLE
[1.16] Obfuscation in 1.16.1 Forge code is incredibly annoying.

### ISSUE THREAD

**Issue by DieselDorky16** [MinecraftForge/MinecraftForge#6916]
When looking at the source code for Minecraft in 1.16.1 Forge, there is a lot of new things that are listed as field_(number) instead of the actual name.

### Examples 
Current as of Forge 32.0.47:
In line 89 of net.minecraft.world.biome.Biomes: 
`public static final Biome field_235251_aB_ = register(173, "basalt_deltas", new BasaltDeltasBiome());`

In line 861 of net.minecraft.block.Blocks: 
`public static final Block field_235395_nI_ = register("quartz_bricks", new Block(AbstractBlock.Properties.from(QUARTZ_BLOCK)));`

What It Should Be:
In line 89 of net.minecraft.world.biome.Biomes: 
`public static final Biome BASALT_DELTAS = register(173, "basalt_deltas", new BasaltDeltasBiome());`

In line 861 of net.minecraft.block.Blocks: 
`public static final Block QUARTZ_BRICKS = register("quartz_bricks", new Block(AbstractBlock.Properties.from(QUARTZ_BLOCK)));`

**Comment by DieselDorky16** [comment]
How can this not be fixed?

**Comment by FinnT730** [comment]
Welcome to the world of decompiled code.........
If you want it fixed, make a PR to fix it.

**Comment by DaemonUmbra** [comment]
Not the case in this instance, Finn...

It will be deobfed, this is a conversation we've had with many people, the bot used to manage mappings is not fully under the control of the Forge team and they're working on a replacement. The request has gone out to one of the few people who can update the bot to accept mappings for 1.16.1 but until one of these things happens mappings can't be submitted for these fields.

**Comment by FinnT730** [comment]
My bad then ¯\_(ツ)_/¯
