### ISSUE TITLE
Block break effects. How should i implement this PR?

### ISSUE THREAD

**Issue by brandon3055** [MinecraftForge/MinecraftForge#6923]
Ok so i'v run into an issue and i need to  make a pr. But there are a number of i can fix this issue and i'm not sure which is the best / most likely to get merged. So i figured it couldn't hurt to get some suggestions before i make my PR.

My issue is related to the block break effect which is triggered via `world.playEvent(2001, pos, Block.getStateId(state));`. 
In 1.12 this was called in `PlayerControllerMP#onPlayerDestroyBlock`.
But in 1.15 it has been moved to `Block#onBlockHarvested` which is called by `IForgeBlock#removedByPlayer`
these are essential methods that need to be called when a player harvests a block.
The problem is when creating things like mining tools that have a large AOE the sheer number of particles that spawn can create a significant lag spike.
Take this worst case example from my mod. I have a tool with a max AOE of 11x11. That's 121 blocks. And each block spawns up to 64 particles for a total of 7744 particles plus 121 simultaneous break sounds per mining operation.
In 1.12 i solved this by simply not calling the break event for every block and instead handled the effect myself. But that's not currently an option in 1.15. 

I have a few pr ideas that could resolve this but i'm not sure which one to go with.

The simplest option would be to add a cancelable event that is called in the implementations of `IWorld#playEvent(PlayerEntity, int, BlockPos, int)` That would allow you to cancel any of the vanilla "events"
But covers1624 suggested this pr probably wouldn't get merged.

Another option would be to add an event in `ParticleManager#addEffect` that allows you to prevent particles from spawning. I could then use this in conjunction with `PlaySoundEvent` to block the block break particles and sound. There is already a similar pr #6805 but that's for server spawned particles which does not help me.
However for my particular use case this would be rather inefficient. Assuming the same 11x11 AOE I would have to send a packed to the client telling my event handler to "start blocking events" then break the blocks which would send 121 break event packets, My event handler would then cancel all 7744 particles and block all 121 break sounds. And finally i would send another packet telling my event handler to "stop blocking events"

So the only other option i can think of would be to modify `Block#onBlockHarvested` and `IForgeBlock#removedByPlayer` to add a "playEvent" boolean. But that would require that new methods be added and the current ones deprecated. I just dont know if that kind of pr would have any chance of getting accepted.

**Comment by LexManos** [comment]
Don't pretend to be a player when removing the block...
Be a proper machine, get the harvest, and just remove the block.

**Comment by KingLemming** [comment]
From what I can tell this is a non-issue anyways as the event is only called directly from the client. I can't even *make* this behavior happen where many particles spawn.

**Comment by brandon3055** [comment]
The problem is this isn't a machine acting as a player acting as a player... My use case is an AOE mining tool which is used by a player. So it just acts as if the player is mining each block "normally" Calls all the relevant functions both server and client side.

**Comment by KingLemming** [comment]
Yeah mine is doing the same but I'm realizing that the way it's structured now is the worst of both possible worlds. The particles do NOT spawn for the client but DO spawn for every other player.
