### ISSUE TITLE
No modded blocks in debug world

### ISSUE THREAD

**Issue by se7kn8** [MinecraftForge/MinecraftForge#6924]
**Minecraft Version:** 1.16.1

**Forge Version:** forge-1.16.1-32.0.47

**Logs:** [debug.log](https://gist.github.com/SE7-KN8/915604617b74ae8bc50cfaed81f9d2f2)

**Steps to Reproduce:**
 1. Create a new world with "Debug" type
 2. See that there are no modded blocks

**Description of issue:**
In the Debug world type, there are no modded blocks (only tested in dev-environment). In 1.15 this was not the case and all modded blocks were in the debug world too.

No blocks visible:
![2020-07-06_10 53 16](https://user-images.githubusercontent.com/35075354/86575604-dabc2c00-bf77-11ea-9974-870c58f5e3f4.png)

But they are registred:
![2020-07-06_10 53 27](https://user-images.githubusercontent.com/35075354/86575655-ea3b7500-bf77-11ea-977a-5ca7fbd7525b.png)

**Comment by sciwhiz12** [comment]
1.16 changed how the `DebugChunkGenerator` is created. `DebugChunkGenerator` has three `private static final` fields: the list of possible blockstates (from `Registry.BLOCK`), and two ints defining the grid width and height based on the list. As these are `static` fields, they are initialized during class static initialization, i.e. classloading.

Previously in 1.15, an instance factory is registered at startup at `ChunkGeneratorType.DEBUG` and an instance is made in `OverworldDimension#createChunkGenerator` once world generation starts, which is well after the `Block`s registry is loaded.

However, with the new changes in dimensions in 1.16, this has changed from a factory-based method to a singleton. `DebugChunkGenerator` creates its singleton at `field_177464_a` at classloading, which means that when the class is first classloaded, the list of blockstates and the grid width and height are initialized for the rest of the game's life.

This means that, if `DebugChunkGenerator` is classloaded before mods can register their blocks (which, as far as I tested, is the case), then no modded blocks will be present in the blockstate list and will not be created in debug worlds.

There are a few possible solutions to this, of which I can think of two:
  1. Only initialize the list and the grid width and height on the first call to `DebugChunkGenerator#getBlockStateFor`, which is the only place that references the aforementioned fields.
  2. Definalize the fields, and create a `BakeCallback`, or some callback that is called when the registry is done being added by vanilla and mods, that initializes the fields.

I have done #&#8203;1, and it works (see the [debug_world_fix_1 branch on my fork][debug_world_fix_1]); however, it will only be initialized once, which will break when Forge (at some point in the future) changes to registy events firing for live reloads. #&#8203;2, in my mind, is the cleaner and more-future-proof solution (no patching, just AT and replace), but I don't know where to put the callback (maybe in `GameData#BlockCallbacks`?).
_Edit: Implemented the second option on the [debug_world_fix_2 branch on my fork][debug_world_fix_2], planning to make a PR for this_

<details> 
  <summary> Image of fix #&#8203;1 in-game, using Forge test mods </summary>
   <p><img src="https://user-images.githubusercontent.com/21304337/86589912-1e875380-bfc1-11ea-8669-3fcb8aa0c66f.png"/> </p>
</details>

[debug_world_fix_1]: https://github.com/sciwhiz12/MinecraftForge/tree/debug_world_fix_1
[debug_world_fix_2]: https://github.com/sciwhiz12/MinecraftForge/tree/debug_world_fix_2
