### ISSUE TITLE
Rendering title without subtitle through `title` command crashes

### ISSUE THREAD

**Issue by sciwhiz12** [MinecraftForge/MinecraftForge#6925]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.47

**Logs:** [Crash report][crashlog] _(ignore the `TEST2.zip` pack, it's out of scope of this issue)_

**Steps to Reproduce:**
 1. `/title @a clear` _(makes sure that title and subtitle are clear)_
 2. `/title @a title "Hello"`

**Description of issue:**
When running the `title @a title <text>` command (any player can be in place of `@a`, only those players will crash) to render a title on-screen without a previous call to `title @a subtitle <text>` to record a subtitle to be rendered alongside it, a crash occurs.

The cause is in `ForgeIngameGui#renderTitle`, the Forge replacement for `IngameGui`, which does not include null checks for `this.displayedSubTitle` and `this.displayedTitle`, which means that not having a recorded subtitle will cause a crash. 
`displayedTitle` should not really be affected, since the `title @a title <text>` command sets its value and then renders the title immediately after.
`IngameGUI` has both of these null checks present.

[Original bug report on forums][bugreport]

[crashlog]: https://gist.github.com/sciwhiz12/7b8ae9866ff0706ecc781e10629ef6b9
[bugreport]: https://forums.minecraftforge.net/topic/88028-kicked-out-from-game-abruptly/

**Comment by diesieben07** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/6907
