### ISSUE TITLE
[1.16] Unable to add attributes to existing entity types

### ISSUE THREAD

**Issue by maxanier** [MinecraftForge/MinecraftForge#6928]
So with the new vanilla `GlobalEntityTypeAttributes` system it does not seem to be possible to add attributes to existing entity types (e.g. player entities) anymore.
Forge patches the corresponding static method in `PlayerEntity` to introduce its `REACH_DISTANCE` attribute, but for mods there currently isn't a solution. Right?

As all of the relevant code is static, this will get ugly to resolve.

So far, I see four alternatives
1) Replace the `ImmutableMap` Building Line `GlobalEntityTypeAttributes#73` with a call to Forge file that does the same, but additionally posts an event or checks a static registry before the attribute map is finalized.
Con: this means when MC updates this line, the changes have to be transferred to the Forge file
2) Patch `LivingEntity` and put a wrapper around the `AttributeModifierManager` which allows registering new attributes per Entity after creation
Con: Wrapper adds additional "bug-prone" layer and runtime overhead is introduced
3) Patch the `AttributeModifierMap` to remove the "immutability", allowing mods to register new attributes per entity type after the `GlobalEntityTypeAttributes` have been initialized
Con: Might be more error prone, if mods change things at the wrong time.
4) Patch each entity's static attribute builder method to post an event or check a static registry. 
Con: Number of patches to high -> non viable
Alternative: Just patch `LivingEntity` (to allow adding attributes to all interesting entities) and potentially `PlayerEntity` for player specific things

I tried discussing this on Discord, but didn't get any response. But I would like to get some feedback before I waste time with a PR for this

**Comment by maxanier** [comment]
An alternative attempt is to use an AT entry to make the `AttributeModifierMap#field_233802_a_` (the map where the attributes (and their ModifieableInstance are stored) public and non-final.
Then, somewhere in the setup phase, one could copy that (immutable) map into a new (immutable) map, add the desired attributes and overwrite the original map.

The main issue with this, is the concurrency between mods (in the loading phase). If
```
mod1->copyOrginalMap
mod2->copyOriginalMap
mod1->writeNewMap
mod2->writeNewMap
```
The additions of mod1 will be ignored.
There aren't any non-parallel events at the end of the loading phase, right?

**Comment by LexManos** [comment]
We don't want to add yet another event fired during every entity construction.
And making the map public non-final is a obviously bad idea.
We would have to have a end bake step for the whole registry system that rebuilds/merges these default maps.

**Comment by ChampionAsh5357** [comment]
Closed by https://github.com/MinecraftForge/MinecraftForge/commit/ba15737fe3d3c6286cfb90c0dca96e2381914245
