### ISSUE TITLE
LivingEvent.LivingJumpEvent not called when horse jumps via player control.

### ISSUE THREAD

**Issue by Agilapathy** [MinecraftForge/MinecraftForge#6929]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.57

**Logs:** N/A

**Steps to Reproduce:**
 1. @SubscribeEvent
    public void onHorseJump(LivingEvent.LivingJumpEvent event)
    {
        System.out.println("Something Living Jumped");
        
        if(event.getEntityLiving() instanceof AbstractHorseEntity)
        {
            System.out.println("Horse Jumped");
        }
    }

**Description of issue:**
"Something Living Jumped" prints as intended. "Horse Jumped" does not print when a horse jumps via player control.

**Comment by Cyborgmas** [comment]
weird https://github.com/MinecraftForge/MinecraftForge/commit/4178885e29332760c9a242d991e105fe7c728a31
