### ISSUE TITLE
Ignore Minecraft mod version

### ISSUE THREAD

**Issue by arduino5144** [MinecraftForge/MinecraftForge#6930]
I think you should add a config option for version ignoring. This will make you able to ignore the check that, say, if you're using 1.15.2, it will try to load 1.14.4 mods, instead of ignoring them. Please do this!

**Comment by LexManos** [comment]
No, Remove mods from the mods folder if you don't want to run them.
The launcher allows you to have completely seperate game directories, and you should as it prevents you from screwing up your world irrecoverably.
