### ISSUE TITLE
broken datapack

### ISSUE THREAD

**Issue by Warbringer12** [MinecraftForge/MinecraftForge#6942]
**Minecraft Version:** {Minecraft version}1.16.1

**Forge Version:** {Forge version. *Version number, not latest/rb*}32.0.61

**Logs:** 
[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/4895206/debug.log)

**Steps to Reproduce:**
 1. started singleplayer
 2. says datapack failed to load
 3. checked datapack section and its default one..

**Description of issue:**
says errors in currently selected datapacks prevented world from loading
you can either try to load only with vanilla datapack
or go back to title screen and fix it manually

**Comment by sciwhiz12** [comment]
Your `debug.log` is incomplete, there are no errors relevant to this issue.
This might be related to #6898.
