### ISSUE TITLE
1.12.2 server file download issues

### ISSUE THREAD

**Issue by skiprocks999** [MinecraftForge/MinecraftForge#6946]
**Minecraft Version:** 1.12.2

**Forge Version:** all 1.12.2 versions (forge-1.12.2-14.23.5.2851 for parity's sake)

**Steps to Reproduce:**
 1. Download universal installer from official forge website https://files.minecraftforge.net/
 2. Install server to empty folder (with whatever name you give it)
 3. Run the minecraft-server.jar to generate EULA and set to "true"
 4. Run it again to generate files
 5. Run forge.jar
 6. And nothing happens

**Description of issue:**
I have tried posting about this on the forums, but it gets yeeted due to "not being supported", so this is my next best option. Upon running the forge.jar directly, nothing occurs as it wont even start. I receive the message "no main manifest attribute" when attempting to run the file through a .BAT file and adding a pause command after the launch command (I have attached a screencap of this) on a fresh install. Upon trying to run pre-generated files (MC Eternal Server Pack v1.3.6), I receive a "InvocationTargetException" which was caused by a "ClassCastException" (also attached). 

Is the issue causing this known, or is this something being caused by the latest version of Java?

Or (and I hope this is not the case) are 1.12.2 modded servers no longer possible? 

![InvocationTargetException](https://user-images.githubusercontent.com/49321049/87165088-457aa980-c28f-11ea-8452-e8f85beeb3ef.PNG)
![no main manefest atribute](https://user-images.githubusercontent.com/49321049/87165089-46134000-c28f-11ea-8a2f-d44def348d8a.PNG)

**Comment by sciwhiz12** [comment]
1.12, and all versions below 1.15.2, are *not supported*, because of its old age (6 years old).
*Please do not directly report on this issues tracker* until and unless you have posted on the forums and the people over there agree that there is a problem.

If you must know, you must use Java 8 and nothing above it.
Please close this issue.

**Comment by S809488** [comment]
i want to download eaglercraft 1.12.2 in my school chromebook using github which i couldn't found any could you pls add a link to download eaglercraft 1.12 in github
