### ISSUE TITLE
1.16.1 Recipe condition "forge:not" not working in recipe

### ISSUE THREAD

**Issue by JaisDK** [MinecraftForge/MinecraftForge#6949]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.62

**Logs:** https://gist.github.com/JaisDK/1d421efba507a844a45cae514209d958

**Steps to Reproduce:**
 1. Create a recipe, any type will do (tested with custom and shapeless recipe types)
 2. Add a forge:not condition
 ```
   "conditions": [
        {
            "type": "forge:not",
            "value": {
                "type": "forge:tag_empty",
                "tag": "minecraft:logs"
            }
        }
    ]
```
 3. Behold, recipe is not working

**Description of issue:**

forge:tag_empty condition is working fine, it's the forge:not wrapper condition that's causing issues.

**Comment by JaisDK** [comment]
An update to this. If I log out of the world and back in, the recipes are working.  Here's a log of that https://gist.github.com/JaisDK/c3894277b0328cc6db762e24e57617eb

**Comment by sciwhiz12** [comment]
From what I have debugged, it seems that on the first load of a world, the tag is still empty (`field_232942_b_` is `null`), so the condition does not succeed and the recipe isn't loaded. After the first world load (or a `/reload`, I assume), the tag is already loaded, so the condition succeeds and the recipe is loaded.
The most plausible explanation that I can think of for this is that recipes are loaded before tags.
