### ISSUE TITLE
[1.15.2] ChunkDataEvent.{Load/Save} use different data tags

### ISSUE THREAD

**Issue by Elec332** [MinecraftForge/MinecraftForge#6957]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.2.27

**Description of issue:**
When attempting to use the chunk data events, I noticed that my data was always lost. After some debugging I found that the Save event gets called for the "root" chunk tag, which has the two tags shown in step 2. When the Load event gets called however, the "Level" tag (present in the root tag) is used for the event, shown by the output described in step 3.

In net.minecraft.world.chunk.storage.ChunkSerializer#read, line 63, the following can be found: 
`CompoundNBT compoundnbt = compound.getCompound("Level");`
Forge then uses the "compoundnbt" for the ChunkDataEvent.Load, instead of "compound"

**Steps to Reproduce:**
 1. Create an eventlistener listening to ChunkDataEvent.Save and ChunkDataEvent.Load, print the keys inside the data:

```
@SubscribeEvent
public void chunkLoadFromDisk(ChunkDataEvent.Save event) {
        System.out.println(event.getData().keySet());
}

@SubscribeEvent
public void chunkLoadFromDisk(ChunkDataEvent.Load event) {
        System.out.println(event.getData().keySet());
}
```

 2. When saving the output will be: `[Level, DataVersion]`
 3. When loading, the output will be: `[Status, zPos, LastUpdate, Biomes, InhabitedTime, xPos, Heightmaps, TileEntities, Entities, isLightOn, TileTicks, Sections, PostProcessing, Structures, LiquidTicks]`

**Comment by sciwhiz12** [comment]
I misread this issue. This issue is reported for 1.15.2, but it's tagged for 1.16. And, this issue also exists on 1.16.1, 32.0.63. So, this issue is missing the 1.15 tag.
