### ISSUE TITLE
Potential broken patch in Screen.java in MC 1.16

### ISSUE THREAD

**Issue by malte0811** [MinecraftForge/MinecraftForge#6965]
**Minecraft Version:** 1.16.1

**Forge Version:** Building against 1.16.1-32.0.57, using mapping version 20200707-1.16.1

**Logs:** https://pastebin.com/TrK1is9E (not really relevant, but the closest to a relevant log there is)

**Description of issue:**  
Something seems to be broken about [this](https://github.com/MinecraftForge/MinecraftForge/blob/065ebde57e12b94ab448286b28aad64623ffe568/patches/minecraft/net/minecraft/client/gui/screen/Screen.java.patch#L18-L24) patch ([equivalent 1.15 patch](https://github.com/MinecraftForge/MinecraftForge/blob/043cb331eeddaa16a8278a86bc5e3f9014748bc9/patches/minecraft/net/minecraft/client/gui/screen/Screen.java.patch#L18-L24), which works correctly): We call the overload added by Forge in IE in one place. It was not obfuscated properly in the build (causing https://github.com/BluSunrize/ImmersiveEngineering/issues/4069), and caused compile errors in our CI ([log](https://ci.blamejared.com/job/Immersive%20Engineering/job/1.16/1/console)), but works when compiling locally for both @BluSunrize and me.  
My guess is that some part of the tooling isn't happy that 2 methods use the same SRG-style name, but I wouldn't know where to look for that issue.

**Comment by LexManos** [comment]
The issue is that patched in methods shouldn't be using SRG names.
It means we have to add annoying extra SRG lines and that's just a can of worms.
I've renamed the method for 1.16+
If someone wants to port the exec and srg lines to 1.15, go for it.
