### ISSUE TITLE
 Exception in server tick loop

### ISSUE THREAD

**Issue by lakehope** [MinecraftForge/MinecraftForge#6971]
hello, last time I have problem, when generate new terrain.
forge version: 1.12.2-forge1.12.2-14.23.5.2847

can we help? what I need do?
description below:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreModLoader (Sound-Physics-Mod-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 7/15/20 6:12 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at net.minecraft.world.World.func_147448_a(World.java:1949)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1519663136 bytes (1449 MB) / 3992977408 bytes (3808 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version           | Source                                     | Signature                                |
	|:------ |:--------------------------------- |:----------------- |:------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2            | minecraft.jar                              | None                                     |
	| LCHIJA | mcp                               | 9.42              | minecraft.jar                              | None                                     |
	| LCHIJA | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar              | None                                     |
	| LCHIJA | forge                             | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar              | None                                     |
	| LCHIJA | voxelmap                          | 1.9.10            | VoxelMap-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | bspkrscore                        | 7.6.0.1           | [1.12]bspkrsCore-universal-7.6.0.1.jar     | None                                     |
	| LCHIJA | treecapitator                     | 1.43.0            | [1.12]TreeCapitator-client-1.43.0.jar      | None                                     |
	| LCHIJA | ctm                               | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                  | None                                     |
	| LCHIJA | jei                               | 4.15.0.296        | jei_1.12.2-4.15.0.296.jar                  | None                                     |
	| LCHIJA | chisel                            | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar               | None                                     |
	| LCHIJA | cucumber                          | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                  | None                                     |
	| LCHIJA | orelib                            | 3.6.0.1           | OreLib-1.12.2-3.6.0.1 (1).jar              | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | dsurround                         | 3.6.1.0           | DynamicSurroundings-1.12.2-3.6.1.0.jar     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCHIJA | endercore                         | 1.12.2-0.5.76     | EnderCore-1.12.2-0.5.76.jar                | None                                     |
	| LCHIJA | enderio                           | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                  | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                  | None                                     |
	| LCHIJA | enderiobase                       | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                  | None                                     |
	| LCHIJA | enderioconduits                   | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                  | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                  | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                  | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                  | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                  | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                  | None                                     |
	| LCHIJA | enderiomachines                   | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                  | None                                     |
	| LCHIJA | enderiopowertools                 | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                  | None                                     |
	| LCHIJA | firstaid                          | 1.6.              | firstaid-1.6.6.jar                         | 7904c4e13947c8a616c5f39b26bdeba796500722 |
	| LCHIJA | waila                             | 1.8.24            | Hwyla-1.8.24-B39_1.12.jar                  | None                                     |
	| LCHIJA | wumpleutil                        | 2.12.9            | wumpleutil-1.12.2-2.12.9.jar               | None                                     |
	| LCHIJA | foodfunk                          | 4.9.6             | foodfunk-1.12.2-4.9.6.jar                  | None                                     |
	| LCHIJA | hardcoredarkness                  | 2.0               | HardcoreDarkness-MC1.12.2-2.0.jar          | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | mekanism                          | 1.12.2-9.8.3.390  | Mekanism-1.12.2-9.8.3.390.jar              | None                                     |
	| LCHIJA | mekanismgenerators                | 1.12.2-9.8.3.390  | MekanismGenerators-1.12.2-9.8.3.390.jar    | None                                     |
	| LCHIJA | millenaire                        | Millénaire 8.1.0  | millenaire-8.1.0.jar                       | None                                     |
	| LCHIJA | mysticalagriculture               | 1.7.5             | MysticalAgriculture-1.12.2-1.7.5.jar       | None                                     |
	| LCHIJA | railcraft                         | 12.0.0            | railcraft-12.0.0.jar                       | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | reborncore                        | 3.15.5.467        | RebornCore-1.12.2-3.15.5.467-universal.jar | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCHIJA | soundphysics                      | 1.0.4             | Sound-Physics-Mod-1.12.2.jar               | None                                     |
	| LCHIJA | stevescarts                       | 2.4.32.137        | StevesCarts-1.12.2-2.4.32.137.jar          | None                                     |

	Loaded coremods (and transformers): 
CoreModLoader (Sound-Physics-Mod-1.12.2.jar)
  com.sonicether.soundphysics.CoreModInjector
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Authlib is : /C:/Users/nuda9/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.15.5.467
		Runtime Debofucsation 1
		RenderEngine: 1
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['lakehope'/321, l='Nowy worldcraft', x=598.91, y=62.21, z=-127.03]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 2
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13572 Compatibility Profile Context 19.11.1 26.20.13031.10003
	OpenGlRenderer: Radeon RX 570 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by FinnT730** [comment]
1.12 is out of support. Please update to 1.15 or 1.16 to get support.

**Comment by lakehope** [comment]
not all mods have version for 1.15, so I search help for 1.12

**Comment by Yunus1903** [comment]
You won't get support for that here
