### ISSUE TITLE
Blackstone is not included in the forge:cobblestone tag

### ISSUE THREAD

**Issue by BetaCarotina** [MinecraftForge/MinecraftForge#6972]
**Minecraft Version:** {1.16.1}

**Forge Version:** {32.0.66}

**Steps to Reproduce:**
 1. Try to craft stone tools using Blackstone
 2. Realize you can't
 3. ...

**Description of issue:**
Blackstone is not included in the forge:cobblestone tag, meaning that it can't be used to create stone tools as Forge overrides the recipe
There are 2 possible solutions:
1. add blackstone to forge:cobblestone
2. add forge:cobblestone to minecraft:stone_tool_materials and use the default recipe

**Comment by diesieben07** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/6894
