### ISSUE TITLE
New Commands registered during reload don't get suggested

### ISSUE THREAD

**Issue by Darkere** [MinecraftForge/MinecraftForge#6974]
**Minecraft Version:** {Minecraft version}
1.16.1
**Forge Version:** {Forge version. *Version number, not latest/rb*}
32.0.67

**Steps to Reproduce:**
 1. Register a new command during /reload (issue is not present if the command exists before this)
 2. The new command works but is not recognized as option for autocomplete

**Description of issue:**
The command works but it does not get recognized properly, showing this error: 

![image](https://user-images.githubusercontent.com/4283717/87595025-314f0600-c6ee-11ea-9fb5-128bb0343ba2.png)

Paging @jaredlll08 who made the PR for it.

**Comment by jaredlll08** [comment]
> Register a new command during /reload

please post code on how you're doing that

**Comment by Darkhax** [comment]
I've ported Bookshelf to use Jared's new event and can not reproduce the issue using the steps you described.

![image](https://user-images.githubusercontent.com/2250798/87597596-994b1f80-c6e1-11ea-91fc-666bc1a84d64.png)

**Comment by Darkere** [comment]
Code can be found here https://github.com/Darkere/CommandAlias/blob/6c8c9b1cb796b53f0d768aded46aa3f83559e817/src/main/java/com/darkere/commandalias/AliasRegistry.java#L31

Stupidly complicated because I wanted to support command aliases with spaces.

**Comment by Darkere** [comment]
@Darkhax  did that command exist before the reload? I'm registering an entirely new command.

**Comment by Darkhax** [comment]
If i prevent the registration on only the first load I can reproduce this issue. 
![image](https://user-images.githubusercontent.com/2250798/87600042-4d00df00-c6e3-11ea-85b3-3e73ef0d5bf6.png)
