### ISSUE TITLE
Task runData throws exception during initialization

### ISSUE THREAD

**Issue by nkirby** [MinecraftForge/MinecraftForge#6979]
**Minecraft Version:**
1.16.1

**Forge Version:**
Forge 32.0.67

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
[latest.log](https://gist.github.com/nkirby/6d8827c1d3c36822ad7cf53497593753)

**Steps to Reproduce:**
 1. Start a new project as usual
 2. Run `runData` task
 3. Watch as it crashes before launch

**Description of issue:**
This occurs even with a brand new MDK project with no data generators yet set up. Running the project via `runClient` works as expected. 

My hunch is this has to do with the fact that I'm running on a Mac, but don't have any alternate system at hand right now to test against.

It's not a huge deal, I can rig something up using an older copy of Forge (I know, for instance, 31.1.27 works, which I was porting something from).

**Comment by ChampionAsh5357** [comment]
Assuming you are not using an M1, you could most likely fix this issue by adding `-Dfml.earlyprogresswindow=false` to the startup arguments. Otherwise, you'll just have to wait on mojang to update to 3.3 LWJGL. Closing this issue as it was more a question for the forums.
