### ISSUE TITLE
Negative Density Finite Fluid Blocks render oddly

### ISSUE THREAD

**Issue by CovertJaguar** [MinecraftForge/MinecraftForge#698]
They render as a flat plane until they hit something.

![1](http://i.imgur.com/izhiF8V.jpg)
![2](http://i.imgur.com/1NcKBgz.png)
![3](http://i.imgur.com/ZLYcYvq.jpg)

**Comment by CovertJaguar** [comment]
Ok.....so setting the meta to 15 results in this:
![](http://i.imgur.com/ePLYDXR.png)
Not quite what I expected either.

**Comment by Madsthunder** [comment]
Close Please?

**Comment by williewillus** [comment]
is it solved?

**Comment by covers1624** [comment]
This is still an issue.
The fluid render seems to cull the top face of the fluid as well.

TestMod: https://gist.github.com/covers1624/0dde75048294705ea0bba405ad112fa9
Results:
![](https://puu.sh/svWNA/00e1167633.png)
![](https://puu.sh/svWOC/8f486c2a9e.png)

**Comment by HenryLoenwind** [comment]
One of the y values is computed wrong for negative density fluids (getFluidHeightForRender()). The culling of the top quad is actually correct, that fluid should hug the stone block.

**Comment by covers1624** [comment]
Ah, Think you could make a PR to fix this @HenryLoenwind ?

**Comment by HenryLoenwind** [comment]
I don't really understand the existing logic, I just threw in what I needed for my single case in there. And I have no finite liquid either. For non-finite liquids changing ```IBlockState up = world.getBlockState(pos.down(densityDir));``` to ```IBlockState up = world.getBlockState(pos.up());``` may do the trick, but the finite ones need more work.

**Comment by HenryLoenwind** [comment]
Update: My previous diagnosis was wrong. It actually works ok for a normal fluid if you set a negative density AND set gaseous to true. At least for my fluid, there may still be error cases.
