### ISSUE TITLE
Server crashing when any mods are added 

### ISSUE THREAD

**Issue by NR472** [MinecraftForge/MinecraftForge#6980]
**Minecraft Version:** {1.16.1}

**Forge Version:** {Forge version. 32.0.68}

**Logs:** {https://mclo.gs/MNoFTQP}

**Description of issue:** Error: Exception caught during firing event

**Comment by bl4ckscor3** [comment]
A mod called `ElrolsUtilities` is not compatible with the changes made in Forge 32.0.67. Report that to the mod author.
