### ISSUE TITLE
1.16.1 BlockEvent.CreateFluidSourceEvent is not called anywhere

### ISSUE THREAD

**Issue by Edivad99** [MinecraftForge/MinecraftForge#6987]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.69

I wanted to prevent the formation of infinite water, so I did a test, but the event doesn't seem to work. I am attaching the code on [pastebin](https://pastebin.com/K50yxjxV)

Edit:
I also found this issue that reports the same problem #5723

**Comment by Yunus1903** [comment]
The event is used in a method that is never used `ForgeEventFactory#canCreateFluidSource`.
Apparently the method is also not in use in 1.15
