### ISSUE TITLE
Entities using ClimberPathNavigator spinning in navigation when width is small 

### ISSUE THREAD

**Issue by Yunus1903** [MinecraftForge/MinecraftForge#6993]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.70

**Logs:** N/A

**Description of issue:**
Entities which use `ClimberPathNavigator` (like a spider) with small width's (something like `0.2F`) start spinning when their path navigation is finished.

~~This issue was fixed before in #6091 but disappeared between the update from 1.15 to 1.16~~
It's caused by a mojang bug (https://bugs.mojang.com/browse/MC-94054), which is still unresolved.

GIF shows the bug in action (In this case I've changed the spider's width to be `0.2F`)

![ezgif com-optimize](https://user-images.githubusercontent.com/6954501/87864575-2dc7b300-c96a-11ea-9366-271829c9f52f.gif)

**Comment by Yunus1903** [comment]
I'll try to fix and PR this

**Comment by Yunus1903** [comment]
I tried applying the same fix as the PR that fixed it in pre-1.16 versions, didn't work.
Trying some other things now.

**Comment by GirafiStudios** [comment]
This issue is different than the PR you linked.
It'll happen for any entity that have smaller width, that uses the ClimberNavigator. The issue have existed since at least 1.12 and is easily fixed by adding a custom Climber Navigator, that increases the width it checks for by 0.5

**Comment by Yunus1903** [comment]
> This issue is different than the PR you linked.
> It'll happen for any entity that have smaller width, that uses the ClimberNavigator. The issue have existed since at least 1.12 and is easily fixed by adding a custom Climber Navigator, that increases the width it checks for by 0.5

Thanks for pointing this out, this was indeed the issue. Did some testing and indeed increasing the witdh it's checking for in `ClimberPathNavigator` fixes this.

Not sure if this fix (rather a hack) would be appropriate for a PR though. I'll give it a try.

**Comment by Yunus1903** [comment]
So the bug only happens when the entities width is 0.9 or smaller
