### ISSUE TITLE
[1.16] PlayerSetSpawnEvent is not fired

### ISSUE THREAD

**Issue by legobmw99** [MinecraftForge/MinecraftForge#7006]
**Minecraft Version:** 1.16.1

**Forge Version:**  32.0.70

**Steps to Reproduce:**

1. Subscribe to PlayerSetSpawnEvent
2. Set the spawn using the command, bed, or respawn anchor
3. Nothing happens

**Description of issue:**

PlayerSetSpawnEvent is not fired. Using code navigate shows that ForgeEventFactory.onPlayerSpawnSet is never called by Forge. Expectation was that event would be fired by beds and command as in past, and with new respawn anchor (possibly with some way of denoting which occurred?).

**Comment by diesieben07** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/6977

**Comment by diesieben07** [comment]
Fixed as of https://github.com/MinecraftForge/MinecraftForge/commit/c9f9fd01b5e90c31f76efe19d04f481932f03273.
