### ISSUE TITLE
Ability to hook into a canStickTo in IForgeBlock interface

### ISSUE THREAD

**Issue by BlueDuckYT** [MinecraftForge/MinecraftForge#7122]
Please add the ability to hook into this interface method so we can create sticky blocks that don't interact with vanilla sticky blocks (honey and slime)

**Comment by diesieben07** [comment]
Define "hook into". You can already override this method in your custom block.

**Comment by BlueDuckYT** [comment]
You can't change how it behaves with vanilla blocks, causing slime blocks and honey blocks to connect to the custom block in some cases.

**Comment by SizableShrimp** [comment]
Fixed by #8837.
