### ISSUE TITLE
Unsupported Enviroment.

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#7168]
**Minecraft Version:** {Minecraft version}
1.12.2

**Forge Version:** {Forge version. *Version number, not latest/rb*}
2854
**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
No need for any log as it's not a crash it's just an issue i have no idea to fix as it gives me a handicap.
**Steps to Reproduce:**
Get windows server.
Make Start.bat
Open Start.bat

**Description of issue:**
This issue makes the colors in the console not showing and it's giving me troubles finding issues and other errors in the console.

**Comment by FinnT730** [comment]
1.12 is not supported anymore. Please update to 1.15.2 or 1.16 to receive support

**Comment by ghost** [comment]
Bruh it's the same issue on every version it doesn't matter.

**Comment by ghost** [comment]
i could've used 1.16 and it would be the same issue

**Comment by TheCurle** [comment]
Provide logs for 1.16.

**Comment by sciwhiz12** [comment]
And post your issues to the [Forge Support Forums][support] first. This issues tracker is for final bug reports and complete feature requests only. 

[support]: https://forums.minecraftforge.net/forum/18-support-bug-reports/
