### ISSUE TITLE
Forge 14.23.5.2854 thinked he is 14.23.5.2838 at client

### ISSUE THREAD

**Issue by avescarelo** [MinecraftForge/MinecraftForge#7169]
**Minecraft Version:** 1.12.2

**Forge Version:** forge-1.12.2-14.23.5.2854 or  forge-1.12.2-14.23.5.2852

)

**Steps to Reproduce:**
 1. Install forge 1.12.2-14.23.5.2854 on client
 2. Run minecraft
 3. Get errors by mods about outdated forge (14.23.5.2838) or message about update if without mods

**Description of issue:**
For some unknown reason, Forge claims to be an older version. Without mods, it offers an upgrade.

The client them says about version: 14.23.5.2854

**Comment by TheCurle** [comment]
1.12.2 is not supported any more.
Update.
