### ISSUE TITLE
IndexedMessageCodec (and by extension SimpleChannel) doesn't do much of anything with the messageType

### ISSUE THREAD

**Issue by Techjar** [MinecraftForge/MinecraftForge#7170]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.71

**Logs:** N/A

**Steps to Reproduce:** N/A

**Description of issue:** 
I was getting really confused trying to understand the lambdas in `SimpleChannel.registerMessage`, so I took a look at the underlying code and upon going down the usage chain, I discovered that the `messageType` argument (which sets the generic) is ultimately never actually used. The only thing referencing it is the `newInstance` method in `IndexedMessageCodec`, which has no usages.

This seems like a huge design oversight. The way the old `FMLIndexedMessageToMessageCodec` (which this appears to replace) worked was it would instance the packet class for you to be passed to the decoder method. This new implementation appears to be set up to do that, but currently the design requires you to instantiate your own packet classes (the decoder takes in a `PacketBuffer` and returns a `MSG` instance, which means you have to keep track of the discriminator -> class mapping yourself, which doesn't seem like how it was meant to work given the arguments passed to `registerMessage`. I'm not even sure how to do this from `SimpleChannel`, as the discriminator isn't passed to the decoder method.

As it is, the implementation of `SimpleChannel` appears to be unusable in any sane fashion and I'm going to have to make my own wrapper around `IndexedMessageCodec`.

**Comment by cpw** [comment]
Not a bug. It's there to set the generic type. That's it's entire purpose. You can arguably subvert it, but this is absolutely standard Java design.

**Comment by Techjar** [comment]
Did you actually read my entire issue report and look at the code in question? I don't believe that you did. Please reopen this, the implementation is legitimately broken and causing me to have to write vastly more complex code than intended to make it work.

**Comment by gigaherz** [comment]
The system works just fine. 
Take this as an example of a packet: https://github.com/gigaherz/ElementsOfPower/blob/master/src/main/java/gigaherz/elementsofpower/network/SynchronizeSpellcastState.java
And this as an example of registration: https://github.com/gigaherz/ElementsOfPower/blob/master/src/main/java/gigaherz/elementsofpower/ElementsOfPowerMod.java#L364
No need for manual tracking of discriminators or anything like what you describe, just basic method references.

**Comment by Techjar** [comment]
That is unnecessarily verbose and terrible. The old `FMLIndexedMessageToMessageCodec` was elegantly simple in how you registered discriminators.

**Comment by gigaherz** [comment]
You can also use registerMessage in the same way. You just can't use the boolean return and have to manually call ctx.get().setPacketHandled(true);
See this, was 1.14 code but should work exactly the same in 1.16: https://github.com/gigaherz/ToolBelt/blob/78962cf1b95b37eea453561c13d11aeb3b98669d/src/main/java/gigaherz/toolbelt/ToolBelt.java#L110
Now if you have more concerns about the networking system, we should discus them on the forums or discord server first, this could have been answered without opening an issue report.
