### ISSUE TITLE
[1.16] [Urgent] Crashing while creating a world

### ISSUE THREAD

**Issue by Cheaterpaul** [MinecraftForge/MinecraftForge#7182]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.85

**Logs:** https://gist.github.com/Cheaterpaul/05087381cc28bd8dd45d4ae3743cc143

**Steps to Reproduce:**
 1. Simply run the game
 2. Create a new default world

**Description of issue:**
The game simply crashes on world creation. Likely has something to do with #6990

**Comment by TheCurle** [comment]
This is a known issue, introduced in 27798c
Revert to .81 for a temporary fix.

**Comment by Cheaterpaul** [comment]
solved with 7717795f428d5d7ab2fc4c43197e7f06f820cf62
