### ISSUE TITLE
"Missing License, please supply a license." on loading any mod on server...

### ISSUE THREAD

**Issue by Xetaxheb** [MinecraftForge/MinecraftForge#7184]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.92

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://gist.github.com/Xetaxheb/365112df07d97e762c62eab6b71fb00f

**Steps to Reproduce:**
 1. Download forge 32.0.92 installer, install to empty folder
 2. Install literally [any mod](https://www.curseforge.com/minecraft/mc-mods/netherportalfix) 
 3. Run with command line "java -jar forge-1.16.1-32.0.92.jar nogui"

Server basically instantly sudoku's itself, even before creating eula.txt>eula=false.
Running with 0 mods installed works fine and functions as a vanilla server.
Installing *any* mod causes this, take for example [Nether Portal Fix](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)

**Comment by LexManos** [comment]
Yes, we know, cpw added the license as a required field.

**Comment by DaemonUmbra** [comment]
cpw decided to break api and require all mods to have a license field in their mods.toml.
Any mods without this field will crash (including mods made before this change).
Only thing you can do is backdate to .88 and wait for mods to update.

**Comment by Xetaxheb** [comment]
Ah good to know, for google searches/issue searches it might be wise to detail clear instructions to mod authors how to do that here (keep in mind some people may not be as knowledgeable as you are)

**Comment by Xetaxheb** [comment]
For anyone wanting a mod to load or any mod authors not sure how to do so, here are the steps you can take: 

1. Open the .jar file with 7-zip ( https://www.7-zip.org/download.html )
2. Open the META-INF folder that's inside
3. **Extract** the mods.toml file
4. Open the mods.toml file **you extracted** with notepad
5. Insert as the very first new line (or on its own line above [[mods]] at least)
`license="why is this breaking change not held off until 1.17???"`
6. Drag and drop the edited mods.toml file back into the META-INF folder inside of 7-zip
7. When it asks "are you sure you want to copy files to archive", say yes.

That's it!

**Comment by LexManos** [comment]
This is resolved, telling people to modify internals of other mods to bypass their license is not going to fly.
It was done in 1.16.2 because contrary to the numbering it IS a **MAJOR** Minecraft version, with all the internal changes Mojang did. So we considered it a good enough time to make this SMALL change.
