### ISSUE TITLE
ModelRegistryEvent is not marked as IModBusEvent

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#7185]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.93

**Steps to Reproduce:**
 1. Try to register to ModelRegistryEvent
 2. Crash

**Description of issue:**
`ModelRegistryEvent` is fired on the mod bus but not marked as such.

**Comment by ichttt** [comment]
5104824a1b48756c0971d7fc1d15293d92522828
