### ISSUE TITLE
"Took too long to log in" forge 1.16.1

### ISSUE THREAD

**Issue by FullMetalMaster** [MinecraftForge/MinecraftForge#7206]
using forge 1.16.1 32.0.88 i get an issue were it the server kicks you from login in and says Took too long to log in. only happens sometimes on some pcs using a pack called Ridiculous BS 

it starts with the player logging in with there code then about 30 secs later it says disconnecting with a sting of stuff and the took to long to log in 2 times. over and over

**Comment by Yunus1903** [comment]
This place is more for technical issues/bugs or feature requests. You might be better off asking this on the [Forums](https://forums.minecraftforge.net/) or on discord. (You should also provide logs)
