### ISSUE TITLE
dry farmland is destroyed regardless if crops are in it

### ISSUE THREAD

**Issue by zachman42** [MinecraftForge/MinecraftForge#7211]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.98

**Steps to Reproduce:**
 1. Till some farmland without water and plant some crops in them
 2. the farmland will turn to dirt, destroying the crops.

**Description of issue:** In normal minecraft, crops will sort of hold farmland into place, keeping it from turning to dirt. In Forge, the crops are uprooted and the farmland turns to dirt regardless

![2020-08-03_13 40 41](https://user-images.githubusercontent.com/68206966/89216720-887b2480-d590-11ea-8197-be10642f90a6.png)

**Comment by diesieben07** [comment]
Looking at the git history, this bug has existed since 2018... Fun times.
PR incoming.

**Comment by zachman42** [comment]
That was fast. Appreciate it.
