### ISSUE TITLE
Add the current Locale to the Crash Report

### ISSUE THREAD

**Issue by shartte** [MinecraftForge/MinecraftForge#7229]
While we could certainly add this ourselves, every mod adding it is probably pointless.

Since we've hit problems with toLowerCase and turkish locales (due to two variants of lower case i being available in the locale, and the non-ascii one being chosen), it'd be nice to have the user's locale in the crash report.

p.s: I don't think this is the "Current Language: English (US)" field, that is the selected translation, I believe.

**Comment by XFactHD** [comment]
Why don't you use ```toLowerCase(Locale.ROOT)```
or ```toLowerCase(Locale.ENGLISH)```
to circumvent this problem entirely?

**Comment by shartte** [comment]
We do now. (We had forgotten it in a few places)

**Comment by diesieben07** [comment]
So, which problem is solved by this?

**Comment by shartte** [comment]
The user's locale is a property of the environment that affects how code runs and it would be useful to see that in a crash report?

**Comment by diesieben07** [comment]
That's not an argument, that's just saying "it's useful". I am asking _why_ it is useful, i.e. which actual problem would be solved by having this info in the crash report.

**Comment by shartte** [comment]
A bug that only materializes on certain locales is described in the first post. Knowing about the user's locale helps with finding such bugs. It's described in the first post.
