### ISSUE TITLE
ItemStack#copy() is not copying runtime-only capabilities

### ISSUE THREAD

**Issue by Nightenom** [MinecraftForge/MinecraftForge#7237]
**Minecraft Version:** 1.16.1

**Forge Version:** 1.16.1-32.0.106

**Logs:** not related

**Steps to Reproduce:**
 1. Create item and client-sided runtime-only capability for it similar to this <https://gist.github.com/Nightenom/015b304cc743e6dcd8c1387d76ab1f07>
 2. Set it up with some values
 3. Trigger ItemStack#copy() anyhow, even manually
 4. Try to access the old values -> nope new capability is created instead

**Description of issue:**
ItemStack#copy() is using CapabilityProvider#serializeCaps() which simply does not bring over your runtime-only capabilities.
Not sure if it has any cavities but it seems the most logical for me to add copy method to ICapabilityProvider interface. This could be also used for carrying over capabilities for entity respawns.
```java
/**
 * Returns a new stack with the same properties.
 */
public ItemStack copy() {
    if (this.isEmpty()) {
    return EMPTY;
    } else {
    ItemStack itemstack = new ItemStack(this.getItem(), this.count, this.serializeCaps());
    itemstack.setAnimationsToGo(this.getAnimationsToGo());
    if (this.tag != null) {
        itemstack.tag = this.tag.copy();
    }

    return itemstack;
    }
}
```

**Comment by ChampionAsh5357** [comment]
The setup you provided is a bit flawed. First, you use a capability and don't serialize the data in any form so it wouldn't get stored anyways. Second, why would you need a capability that's only stored on the physical client? That would mean your mod only stored information on a singleplayer world with an integrated server. It would never be able to run in some multiplayer host. Capability data is stored on the logical server.

**Comment by LexManos** [comment]
This is working as intended.
If you want the data to persist across copies, the network, saves, whatever. You have to serialize it.

**Comment by Nightenom** [comment]
> 1. Create item and client-sided runtime-only capability for it similar to this

I told you that my capability is client-sided and non-persisting. If I'm going to serialize it I will crash on next world load, IMHO there is no feasible way to delete one capability from every ItemStack, but I will keep looking I guess...

edit: ChampionAsh5357: it just holds a reference to attached rendering event, makes no sense to save nor send to the server

**Comment by diesieben07** [comment]
> If I'm going to serialize it I will crash on next world load

What? This sounds like user error and something for the forums or Discord.
