### ISSUE TITLE
[1.16.x] No difference between AnimalEntity.func_204701_dC() and AgeableEntity.func_213743_em()

### ISSUE THREAD

**Issue by EdwinMindcraft** [MinecraftForge/MinecraftForge#7238]
**Minecraft Version:** 1.16

**Forge Version:**  32.0.108

**Description of issue:**
There is a naming conflict between AnimalEntity#func_204701_dC and AgeableEntity#func_213743_em since both have the same name (canBreed) in the mappings forge is built against despite being different in the original code, which means that currently, func_204701_dC is removed in favor of func_213743_em.

**Comment by Lanse505** [comment]
It's not something contributed by the mapping sheet at least.
Those two names don't exist on there.

Meaning it's an old mapping issue, unless someone screwed something up 🤔 
Either way this shouldn't be an issue for the MinecraftForge issue tracker, it's a mapping issue, not a forge issue.

**Comment by Lanse505** [comment]
Looking into a 1.15 build I can see that previous to 1.16, "canBreed" didn't exist in AgeableEntity.
Meaning it got added in 1.16, however it wasn't added by the mapping spreadsheet.

**Comment by EdwinMindcraft** [comment]
I posted it here because it has an impact on the patch generation (Turtle and Hoglin patches are unnecessary without this error) and thus affects forge, I do however agree that this is a mappings issue, but I don't know the right place to post those.
