### ISSUE TITLE
Cannot connect to 1.16.2 Forge servers

### ISSUE THREAD

**Issue by bl4ckscor3** [MinecraftForge/MinecraftForge#7244]
**Minecraft Version:** 1.16.2
**Forge Version:** 33.0.0

**Logs:** (Server and client logs) https://gist.github.com/bl4ckscor3/4ef611b345e3caf46d4b9ac3d7945cc7

**Steps to Reproduce:**
 1. Install a fresh Forge server
 2. Start it, and try to connect to it with a Forge client without mods

**Description of issue:** Connecting to a Forge server fails. The client displayed this screen in my test https://i.imgur.com/pWt0bqH.png

**Comment by Cyborgmas** [comment]
see #7245
