### ISSUE TITLE
Crash from missing license, but doesnt say what mod

### ISSUE THREAD

**Issue by Sunekaer** [MinecraftForge/MinecraftForge#7247]
**Minecraft Version:** 1.16.2

**Forge Version:** 33.0.0

**Logs:** https://pst.ksun.io/okucadobum.sql

**Description of issue:**
When instance crash with "Missing License, please supply a license" but doesn't say which mod there is missing the license.
And when you are trying to build a modpack its a lot of work to go through them one by one to find the one or multiple there is missing the license

**Comment by Yunus1903** [comment]
There's already a  PR for this #7241

**Comment by spnda** [comment]
#7241 has been merged. As of 33.0.3 the error now looks like this:
```
net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing License, please supply a license. (jei-1.16.1-7.0.0.6.jar)
 	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.lambda$new$2(ModFileInfo.java:68)
```
