### ISSUE TITLE
[1.16.2] Sneaking on non-liquid block makes player swim

### ISSUE THREAD

**Issue by blackjack26** [MinecraftForge/MinecraftForge#7248]
**Minecraft Version:** 1.16.2

**Forge Version:** 33.0.2

**MCP Version:** 20200813-1.16.1

**Steps to Reproduce:**
 1. Find a non-liquid block
 2. Use the sneak control and hold

**Description of issue:**
When the player does a sneak on a non-liquid block, the player appears to be swimming on the ground.

**Comment by Yunus1903** [comment]
Cannot reproduce this.

**Comment by TheCurle** [comment]
Can you provide a screenshot?

**Comment by blackjack26** [comment]
![image](https://user-images.githubusercontent.com/6426155/90180497-0dc6bc00-dd7d-11ea-92f8-41bbd2dde7b5.png)

**Comment by TheCurle** [comment]
![image](https://user-images.githubusercontent.com/42079760/90181448-5e9fda00-dda8-11ea-99c8-0373b9a2716a.png)

I cannot reproduce.

**Comment by blackjack26** [comment]
Alright so when I use the `20200723-1.16.1` mappings it works fine, but when I use the `20200813-1.16.1` mappings I get this problem.

**Comment by Matlauk** [comment]
There's an issue with the isSwimming() call under ClientPlayerEntity. Also, it probably needs to override from the super class.
![image](https://user-images.githubusercontent.com/8014895/90341796-7305f180-dfb7-11ea-9a4b-494c98831218.png)

**Comment by TheCurle** [comment]
In 0723, this function is named differently.
![image](https://user-images.githubusercontent.com/42079760/90341839-f72d9880-dffa-11ea-88ab-de41efbd177e.png)

Likely, the mappings spreadsheet needs to be updated, as there is already a working isSwimming function.

**Comment by TheCurle** [comment]
For reference, the existing isSwimming function:
![image](https://user-images.githubusercontent.com/42079760/90341859-3b209d80-dffb-11ea-84c3-227eb135951e.png)

**Comment by gigaherz** [comment]
Changing that method does indeed fix the issue. I'll publish a new version soon.

**Comment by TheCurle** [comment]
Once the release is published, this issue will be closed.
