### ISSUE TITLE
(1.16.2) Nether Portals can't be created

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#7249]
Minecraft: 1.16.2
Forge Version: 1.16.2-33.0.2
Log: https://gist.github.com/TheAGamePlayer/92994f63970e09bfe0c2c3b86666f94a
Steps to Reproduce:
1) Make a nether portal
2) Attempt to ignite it
3) Wonder why it doesn't work >.>

Description:
When updating my mod to the new 1.16.2 version, I realized you could not go into the nether. Nether Portals would not ignite regardless of what I would use to ignite it. I provided a gif as video evidence containing the broken feature.
![bug](https://user-images.githubusercontent.com/58047374/90209428-44fa9480-dda0-11ea-945f-0126fd57b40a.gif)

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/680c4062f49c07eb1b53a39ade89df217f7b2223
