### ISSUE TITLE
Breaking waterlogged blocks occasionally displays air for a frame

### ISSUE THREAD

**Issue by zachman42** [MinecraftForge/MinecraftForge#7253]
**Minecraft Version:** 1.16.2
**Forge Version:** 33.0.3

**Steps to Reproduce:**
 1. place a waterloggable block underwater
 2. break it
 3. you may have to do this a couple times to see the effect

**Description of issue:**
Title says it all.
![ezgif-4-425c9733913c](https://user-images.githubusercontent.com/68206966/90282923-d287c400-de34-11ea-82a3-aba2813d4b36.gif)

**Comment by ChampionAsh5357** [comment]
This is a result of `ForgeHooks#onBlockBreakEvent` not taking into account the `FluidState` before setting the block to air for non-tile entities. Currently, it just sets sends a packet to the client setting the block to air. So, this probably just needs to send over a `BlockState` of any associated `FluidState` the original block had.
