### ISSUE TITLE
Game hangs upon switching dimension with `forge setdimension`

### ISSUE THREAD

**Issue by Drullkus** [MinecraftForge/MinecraftForge#7254]
In 1.16.2, the game hangs when you invoke `forge setdimension @p minecraft:nether`, but using `execute in minecraft:the_end run teleport ~ ~ ~` works just fine. Since vanilla commands now support switching dimensions I recommend removing this command or executing the command by proxy

**Comment by Redstoneguy129** [comment]
Might be something to do with chunks being loaded. When i go to nether then come back the command works.

**Comment by 50ap5ud5** [comment]
I can confirm this issue is able to be reproduced in 1.16.3.

**Comment by Redstoneguy129** [comment]
Might be something to do with chunks not being loaded where the player is teleported to. So try making a fix by forcing those chunks to be loaded. I think this because after going to nether through portal i can then use setdimension within those chuncks ive loaded. Nether portals load chuncks.

**Comment by pupnewfster** [comment]
This got fixed as part of https://github.com/MinecraftForge/MinecraftForge/commit/8536521b7b4d4543fc3906c2fc2b5b7f2deabb94 (Forge 34.1.23+)
