### ISSUE TITLE
ServerPlayerEntity.func_241153_a_() does not pass 4th argument to the Forge Event.

### ISSUE THREAD

**Issue by Echo343** [MinecraftForge/MinecraftForge#7269]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.108 or higher

**Description of issue:**
* ServerPlayerEntity.func_241153_a_ method has a 4th argument that it does not pass to the onPlayerSpawnSet forge event. This 4th argument is used to indicated whether or not the player initiated the set spawn event (ie. clicking on a bed as opposed to dying).
* Mods will need access to this 4th argument to know the difference between a respawn or a bed/anchor click.

**Comment by diesieben07** [comment]
The parameter indicates whether the player should be notified about the spawn change via a chat message. It has nothing to do with respawning.

**Comment by Echo343** [comment]
This is indeed true; the chat flag is true when the player clicks on a bed or respawn anchor, and the flag is false if it is the result of a death or command. While it only controls the chat message, it also indicates the code path that was taken to get there. This can be of help to mods that utilize this event.

**Comment by ChampionAsh5357** [comment]
To address your initial points in the first post, as dies said, the left out boolean is for determining if a chat message is sent about if the respawn point is set. The chat message is sent for actions that can be done in survival mode including respawn anchors and clicking on beds. To address your second comment, the code path that is taken to get to that point can be determined through any IDE by backtracing the calls. It does not provide any additional information that cannot be obtained by the player entity itself which is also passed in.

For those reasons, I will be labeling this as a `Won't Fix` issue and closing it. If you can provide another reason as to the usefulness of the parameter, you can post so here and I will reopen if necessary.
