### ISSUE TITLE
Forge 1.16.2 33.0.20 does not decompile

### ISSUE THREAD

**Issue by FireController1847** [MinecraftForge/MinecraftForge#7270]
**Minecraft Version:** 1.16.2
**Forge Version:** 33.0.20
**Logs:** https://gist.github.com/FireController1847/7764b5f1e3bcfcc043981876d786baea

**Steps to Reproduce:**
 1. Attempt to compile the shipped mdk for 33.0.20

**Description of issue:**
The MDK for 33.0.20 does not decompile with the attached error. However, 33.0.19 and previous versions do decompile without issue. This leads me to believe that there's decompile issues for this version, whether it be specific to my PC, or the fact I'm using IntelliJ, what have you. In the gist is also attached my `gradlew -v` output

**Extra info:**
![](https://cdn.discordapp.com/attachments/437001959950778368/747271642958397510/unknown.png)

**Comment by LexManos** [comment]
Not that Forge does would cause this to happen between versions. This is a decompiler issue.
Post your build\fg_cache\mcp\{mcpversion}\joined\{hash}\decompile\console.log

**Comment by FireController1847** [comment]
There is no fg_cache folder in my build folder. When it crashes, these are the only available folders:

![explorer_2020-08-23_23-07-19](https://user-images.githubusercontent.com/16494272/91005954-66743100-e595-11ea-9133-64462d73bd15.png)

**Comment by LexManos** [comment]
odd there should be. Either way, delete your build folder, as well as D:\Users\usfir\.gradle\caches\forge_gradle
Then run again with -Dfg.debugRepo=true

**Comment by FireController1847** [comment]
Thanks for the forge_gradle tip, that appears to have fixed things right up!
