### ISSUE TITLE
[1.16.2] Piglin item Dupe bug

### ISSUE THREAD

**Issue by Daejangnamu** [MinecraftForge/MinecraftForge#7281]
Please fix the bug.

Video: https://youtu.be/gZGTdPbAdZQ

**Comment by Yunus1903** [comment]
There already is a issue for this on Mojang's bug tracker https://bugs.mojang.com/browse/MC-198958 (altough it's invisible/private). I'd guess it'll get fixed next version (either 1.16.3 or 1.17)

**Comment by Yunus1903** [comment]
Looks like this issue is fixed in 1.16.3 Release Candidate 1.

https://bugs.mojang.com/browse/MC-198678

This issue can be closed.
