### ISSUE TITLE
[1.16.1/1.16.2] `ItemTags.getCollection().getTagMap()` empty during processing of conditional recipes

### ISSUE THREAD

**Issue by stfwi** [MinecraftForge/MinecraftForge#7284]
**Minecraft Version:** 1.16.1, 1.16.2
**Forge Version:**  1.16.1-32.0.21 to 1.16.2-33.0.22
**Logs:** https://gist.githubusercontent.com/BluSunrize/3a3897d94787b2d3bd07efd6baf79fdb/raw/28b356c35569425396aa13b793101fa4db8a015f/debug%2520crash

**Steps to Reproduce:**
1. Add log for `ItemTags.getCollection().getTagMap()` or a breakpoint in a `net.minecraftforge.common.crafting.conditions.ICondition::test()` method.
2. The return value of `ItemTags.getCollection().getTagMap()` is an empty map.

**Description of issue:**
I am not sure if this is a bug, or a side effect of a performance improvement, or a change that modders have to adapt to:

To select the best fitting recipe in a JSON list of `forge:conditional` recipes, mods may use a custom condition checking for
the existence of items and tags required for the listed recipes (e.g. using `ForgeRegistries.ITEMS` and `ItemTags.getCollection().getTagMap()`).

In the Forge versions for 1.16.1 and 1.16.2, `ItemTags.getCollection().getTagMap()` appears now empty when the recipe conditions
are evaluated. Hence, "ore-dict" tag dependent recipe conditions do not match anymore.

**Comment by Cyborgmas** [comment]
So pretty sure this is normal, `ItemTags`' `ITagCollection` will be updated when tags are loaded in, which is when datapacks are loaded in.
However, when in a serialization/deserialization context you should use `TagCollectionManager#func_242178_a` which will contain what you want.
EDIT: i am lazy and have not tested, leaving that up to you, but should be the solution.

**Comment by stfwi** [comment]
Tanks for the quick reply, I checked with the `TagCollectionManager`, and it's doing the trick.
For completeness and reference for others, the tag map access used is then for 1.16.1 (Forge 32.0.108):
```
final Map<ResourceLocation, ITag<Item>> itemTags = TagCollectionManager.func_232928_e_/*getInstance?*/().func_232925_b_/*getItemTags?*/().getTagMap();
```

For 1.16.2 (Forge 33.0.22):
```
final Map<ResourceLocation, ITag<Item>> itemTags = TagCollectionManager.func_242178_a/*getInstance?*/().func_241836_b/*getItemTags?*/().func_241833_a/*getTagMap?*/();
```

Presuming that the tags are all available (independent of the load order of mods etc), the ore-dict functionality during recipe processing is addressed, so this issue can be closed I think.

**Comment by LexManos** [comment]
Yes, tags and recipes and all those data driven system are typically loaded into a secondary manager that is then swapped out wholesale for the other active one. This allows things to be rebuilt and validated without effecting the currently used tags/whatever.

This isn't a Forge issue, this is how Minecraft works. It did change in 1.16.2, but a lot of things did.
You'll notice our test of it was update din 1.16.2: https://github.com/MinecraftForge/MinecraftForge/blame/1.16.x/src/main/java/net/minecraftforge/common/crafting/conditions/TagEmptyCondition.java#L59

**Comment by stfwi** [comment]
Ty for the additional info Lex.
