### ISSUE TITLE
Game crash on startup when Dualshock 4 controller plugged in

### ISSUE THREAD

**Issue by RedstoneLP2** [MinecraftForge/MinecraftForge#7285]
**Minecraft Version:** {Minecraft version}
1.14.4 - 1.16.2
**Forge Version:** {Forge version. *Version number, not latest/rb*}
28.1.39 - 33.0.22
**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://gist.github.com/RedstoneLP2/316dcc7fd8788e11a44d73c1d5d35a19
**Steps to Reproduce:**
 1. Install forge between said versions
 2. Start the game with DS4 controller plugged in
 3. Get crash

**Description of issue:**
This issue is found multiple times in the forums, and as vanilla seems to handle an "invalid" gamepad without crashing, it should be at least acknowledged in a GitHub issue in the hope of a potential "fix".
In some usecases (like playing on an HTPC with mods like "Controllable" by MrCrayfish or just leaving a gamepad plugged in) the workaround proposed in said threads, of unplugging the gamepad, is not necessarily applicable.
Note that this issue also occurs when no Bluetooth radio is connected to the pc and steam is not running

**Comment by TheCurle** [comment]
This seems to be an Early Progress window issue.
As a more usable workaround, you can disable the early window with `-Dfml.earlyprogresswindow=false`
We're looking into it.

**Comment by jochuan** [comment]
Is there any workaround for this bug ? Is annoying to always have to unplug the gamepad to play minecraft

**Comment by RedstoneLP2** [comment]
just pointing out it's still in the latest version of forge (35.1.15) and the workaround by TheCurle is working (at least for me).

the latest.log of the error w/ 35.1.15 in case it has a different cause:
https://gist.github.com/RedstoneLP2/5058807772d63d65abbbe70c5b266b4b
but it looks to me like the same thing and again the workaround is working

**Comment by AterAnimAvis** [comment]
~~When you get a second could you try the mod at https://github.com/AterAnimAvis/ForgeBugs/releases/tag/7285-1 - I believe this should fix your issue (without Curle's work arround) but I can't replicate on my end. (Logs from running the mod would be helpful).
If this does I'll clean it up and submit a patch~~

Scratch that looks like I didn't check my logs probably. That won't actually work (Applies to late).
Quick question are you capable of cloning and building a git branch (https://github.com/AterAnimAvis/MinecraftForge/tree/1.16-controller-fix)?

**Comment by jochuan** [comment]
How i, a normal user without coding knowledge can use this workaround ?

**Comment by DaemonUmbra** [comment]
> How i, a normal user without coding knowledge can use this workaround ?

1. Click Installations
2. Hover over the installation you're using
3. Click ``...``
4. Click Edit
5. Click More Options
6. Add ```-Dfml.earlyprogresswindow=false``` to the JVM Arguments

**Comment by RedstoneLP2** [comment]
Got it to compile. anything you need me to do?

**Comment by AterAnimAvis** [comment]
Run `gen<IDE>Runs` depending on what IDE your using.
Run `forge forge client` and grab the logs for it. (This should be the minimal fix for the crash)

Edit the `forge forge client` to add `-Dforge.7285.extra=true` as a vm option.
Run `forge forge client` and grab the logs for it. (This is slightly more involved but should definitely fix the crash)

Thats if I identified the main issue right.

**Comment by RedstoneLP2** [comment]
https://gist.github.com/RedstoneLP2/d9985faad37a211ced197370369d37d9
here are the logs. is it normal for the GLFW errors to be different on different starts?

**Comment by AterAnimAvis** [comment]
Thanks for this, I messed up the logic for enabling the `.extra` fix but from the logs it should fix your issues.

The errors are both [0x10004] the number after it is a memory pointer to the string description.

Can you rerun `forge forge client` with the new commit (The VM option doesn't matter anymore) and post the logs.

**Comment by RedstoneLP2** [comment]
https://gist.github.com/RedstoneLP2/714eaca1ac5fac112e7029e0a5169035
logs with the new commit

**Comment by AterAnimAvis** [comment]
Ah sorry should of specified that you need to run `setup` first (To ensure the new patch is applied).

**Comment by RedstoneLP2** [comment]
yay it doesnt crash anymore
here's the log, if needed
https://gist.github.com/RedstoneLP2/138f0f5de98f3c1592a8a731392ee1fd

**Comment by AterAnimAvis** [comment]
Sorry to be a pain but could you do `setup` and `forge forge client` and provide the log for the newest commit.

This should hopefully fix the problem in ClientVisualization such that a patch to GLX shouldn't be necessary, I just need confirmation this is the case.

I'll then work on cleaning this up into a PR.

**Comment by RedstoneLP2** [comment]
https://gist.github.com/RedstoneLP2/6e0a79536468f7ebcd2750101020ff8c

**Comment by AterAnimAvis** [comment]
If you get the time can you try out the pr. It should be the minimal fix for your Issue.

This should be solely a double check that I haven't messed anything up.

**Comment by RedstoneLP2** [comment]
https://gist.github.com/RedstoneLP2/ee05afb3f9dc9e722da458f9a7ed548d
seems to work

**Comment by AterAnimAvis** [comment]
That’s not the pr branch. you’ll need to target 1.16-controller-fix-pr

**Comment by RedstoneLP2** [comment]
hmm thought i changed the branch, guess not
anyway here the log
https://gist.github.com/RedstoneLP2/1ee7d8902263c4879c142b9854a8eb62
