### ISSUE TITLE
Custom ElytraItem's do not return correct EquipmentSlotType

### ISSUE THREAD

**Issue by Mason199004** [MinecraftForge/MinecraftForge#7290]
In MobEntity.java getSlotForItemStack checks to see if the ItemStack is Items.ELYTRA rather than instanceof ElytraItem causing custom ElytraItems to be unequipable unless they override getEquipmentSlot to return EquipmentSlotType.CHEST

**Comment by ChampionAsh5357** [comment]
Then override `IForgeItem#getEquipmentSlot`. It's javadocs clearly says:
> Override this to set a non-default armor slot for an ItemStack

If you are creating a custom item, you can easily do this.
