### ISSUE TITLE
The loading stops in the atlas stitching:blocks phase

### ISSUE THREAD

**Issue by Edivad99** [MinecraftForge/MinecraftForge#7293]
**Minecraft Version:** 1.16.2

**Forge Version:** 33.0.31

**Logs:** https://gist.github.com/Edivad99/64f3376d24a883dc96450bcf668ff9ec
**Steps to Reproduce:**
On intellij I was updating forge, but on loading it freezes
![mc freeze](https://user-images.githubusercontent.com/25778604/91831738-b95c8100-ec44-11ea-84f5-1ead12651537.png)

**Comment by ichttt** [comment]
This seems to be an issue on systems with 4 or fewer cores/hardware threads

**Comment by mrp-v2** [comment]
I'm having the same problem on a 6 core/thread machine.

**Comment by XFactHD** [comment]
Cannot reproduce on an i7 4790K (4 core/8 thread), neither in a mod workspace nor in a clean forge install in the MC launcher.

**Comment by mrp-v2** [comment]
I'm on a i5-9600k and it happens both in a mod workspace and with a fresh client install with no mods,
fresh client log: https://gist.github.com/mrp-v2/2670030aa71318782cdd44fd59098bfd
modding environment log: https://gist.github.com/mrp-v2/e0564e8ccde4cd2b0f2044b09c94c192

**Comment by XFactHD** [comment]
When turning off hyperthreading on my CPU I can also reproduce this issue.

Minecraft doesn't seem to freeze completely, as the heap memory usage is slowly rising (from 800 MB to 1200 MB in 10 minutes). No idea if this is just Java being Java or if this is an important detail.

**Comment by CodedSakura** [comment]
On a i5-9600KF (6 cores/threads) I have this problem, but on a i7-3770 (4 cores/8 threads) it launches just fine

**Comment by CodedSakura** [comment]
Can also report that this happens on 33.0.30 and 33.0.31, but not on 33.0.23

**Comment by mamatvoja** [comment]
Same thing happening to me

**Comment by LexManos** [comment]
Guys we get it. cpw will look into it when he gets some time.
However instead of just hopping on the bandwagon, actually be productive and give logs, mod packs, etc.
The smaller you can make the reproduction case the more likely we are to find the issue.
However this doesn't seem to be a "deadlock" like some have said, instead it seems to be a threading issue related to the stitching event. At least that's what the log says.
So be sure to provide your logs in their entirety and be sure that it is REALLY the same issue and not the same symptom.

**Comment by cpw** [comment]
Getting a stack trace would be very useful. It looks like something has somehow managed to deadlock, but I'm uncertain what that could be, since it's not in my code.

**Comment by XFactHD** [comment]
From what I can see it is deadlocking in AtlasTexture::makeSprites() on line 174
`CompletableFuture.allOf(list.toArray(new CompletableFuture[0])).join();`

**Comment by cpw** [comment]
> From what I can see it is deadlocking in AtlasTexture::makeSprites() on line 174
> `CompletableFuture.allOf(list.toArray(new CompletableFuture[0])).join();`

What an utterly useless statement. Please give stack traces. And a reproduction if possible.

**Comment by XFactHD** [comment]
This is the stacktrace from a breakpoint on that line: https://pastebin.com/N441X6HJ

Any breakpoint in the lambda that is wrapped in the CompletableFutures won't trigger.

As mentioned above this is reproducible in a Forge workspace without mods and a clean Forge install when running on a CPU with less than 8 virtual cores (disabling hyperthreading on a quad-core CPU also causes this).

**Comment by XFactHD** [comment]
The trace above is actually the one that succeeds, this one fails: https://pastebin.com/gWcFrGUU
