### ISSUE TITLE
Entity not removed from world using teleport command between dimensions

### ISSUE THREAD

**Issue by LIMachi** [MinecraftForge/MinecraftForge#7295]
**Minecraft Version:** 1.16.2

**Forge Version:** forge:1.16.2-33.0.32

**Steps to Reproduce:**
create a new world (in creative)
spawn a unique mob (for example a mooshroom if you are far from any mushroom island)
go to the nether
teleport the mooshroom using the command `/tp @e[type=minecraft:mooshroom] Dev` until the log prints `[Server thread/WARN] [minecraft/ServerWorld]: Trying to add entity with duplicated UUID <some uuid>. Existing minecraft:mooshroom#<id>, new: minecraft:mooshroom#<id>`

**Description of issue:**
The teleport command net.minecraft.command.impl.TeleportCommand#teleport does not remove an entity when it changes it's dimension (the actual code create a new entity in the targeted world, but does not remove the entity from it's original world), resulting on a entity duplication error on tp between dimension
LexManos pointed out some possible reasons in the links below:
https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/patches/minecraft/net/minecraft/command/impl/TeleportCommand.java.patch
https://github.com/MinecraftForge/MinecraftForge/commit/f5375783c6da5380e592fc727a730f58266d4f8a#diff-2e15f5ab35712398198eba887a4d7599

**Comment by ChampionAsh5357** [comment]
This is only applicable to 1.16.5 since 1.17.1 due to the misapplied patch adds back in the `#setRemoved` method.

**Comment by sciwhiz12** [comment]
1.16.x is now out of support.
