### ISSUE TITLE
ModelLoader.addSpecialModel is not threadsafe

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#7310]
**Minecraft Version:** 1.16.1/1.16.2

**Forge Version:** Any version above 32.0.107

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report} N/A

**Description of issue:**
`ModelRegistryEvent`'s threading properties have changed as of 32.0.107. It formerly was fired in `ClientModLoader.postSidedRunnable` which is executed on the `mainThreadExecutor`, but now is fired from whichever worker thread is responsible for loading model jsons.

`ModelLoader.addSpecialModel`'s javadoc encourages calling in `ModelRegistryEvent` but the `specialModels` field is not properly protected, either with a concurrent map or synchronization. `ModelLoaderRegistry.registerLoader` is also encouraged to be called in `ModelRegistryEvent` and its field `loaders` has the proper synchronization.

This has manifested as sporadic reports of Patchouli books not having their textures, as presumably the addSpecialModel calls are racing somehow.

**Comment by williewillus** [comment]
cc @gigaherz since he made the 107 changes

**Comment by cpw** [comment]
Is this still true after my event dispatch overhaul?

**Comment by cpw** [comment]
It doesn't fire on the Render thread, but this event stream is not dispatched as a parallel stream, so there shouldn't be conflicts here, unless it's being called multiple times..

**Comment by williewillus** [comment]
The reports I've been getting say it happens in any 1.16.1 version >= 107 and any 1.16.2 version (they used 42).

Yeah, it's a particularly weird issue, I haven't been able to reproduce it at all, but others have.

For anyone trying to reproduce: Install [Patchouli 1.16.2](https://www.curseforge.com/minecraft/mc-mods/patchouli) and [Essentials 1.16.2](https://www.curseforge.com/minecraft/mc-mods/essentials). Start the game and get Essentials' book from its creative tab and check if it has a missing texture or not.

**Comment by cpw** [comment]
Would love to see the debug log from 55+

**Comment by Darkere** [comment]
Installed latest forge (33.0.58) and the two mods willie mentioned. The guidebook texture was broken.

https://gist.github.com/Darkere/d4b89cb1b43616a3d113b153cb511112

Texture worked on 3rd launch: 
https://gist.github.com/Darkere/071a935481510cc209b55290d88699f8

**Comment by cpw** [comment]
Comparing the two relevant sections, I'm going to guess that one of those mods is trying to do activities related to model loading in either COMMON_SETUP or (worse, because it's _after_ everything here) CLIENT_SETUP.

https://gist.github.com/cpw/11d2d6ded07218c0b37b9d6e79fa3ce7

**Comment by cpw** [comment]
I can't even see a call to ModelLoaderRegistry.registerLoader in either mod?

**Comment by gigaherz** [comment]
I haven't had any time to look into it, but I would have thought calling addSpecialModel from within ModelRegistryEvent should be safe? But yes, there could be issues if other mods still call that method from a Setup event, which it was never intended to be done that way.

**Comment by cpw** [comment]
i've looked, and I can't see how it's a race condition _if they're doing it properly_. But both cited mods are clearly _not_ doing it properly: patchouli doesn't seem to use that event _at all_, and Essentials is only using it to register a RenderingRegistry artifact.

**Comment by williewillus** [comment]
transcribing from Discord

Essentials is not doing anything code side. What it does is declare the model it wants to use in its `book.json` [here](https://github.com/Da-Technomancer/Essentials/blob/1.16/src/main/resources/data/essentials/patchouli_books/manual/book.json#L6), and Patchouli will submit it on its behalf during `ModelRegistryEvent` [here](https://github.com/Vazkii/Patchouli/blob/master/src/main/java/vazkii/patchouli/common/item/PatchouliItems.java#L27-L43).

Then during `ModelBakeEvent` (same link as above) it replaces the old book model with a special one that dispatches to the proper model based on NBT it is -- this is because in Patchouli only one item is registered to represent all books.

**Comment by williewillus** [comment]
Custom loaders aren't involved here, just `addSpecialModel` and the two events named.

**Comment by cpw** [comment]
Well, I think I can't see anything wrong here from forge. The logs show the exact correct behaviour. I suspect that there's some kind of miscommunication in how the patchouli is expecting it's books to be set up, that I don't know how we can fix in forge. The events are working as expected, and there seems to be no collisions in either of the gists provided above.

**Comment by williewillus** [comment]
Yeah, i did some more digging and it might be a threading issue in patchouli. I'll close for now and come back if I find anything else, sorry for the noise

**Comment by cpw** [comment]
No worries. I reckon you probably just need to make sure that you fire the book collection stuff before modelevent. It might be useful to add a new IMC call in before all these events fire. :thinking:
