### ISSUE TITLE
I can't install Forge

### ISSUE THREAD

**Issue by Boe-Bio** [MinecraftForge/MinecraftForge#7311]
Every time I try to install forge, it gives me this message:
These libraries failed to download. Try again.

commons-io:commons-io:2.4

**Comment by TheCurle** [comment]
What version are you trying to install?

**Comment by FinnT730** [comment]
What version is this for?

**Comment by Boe-Bio** [comment]
I'm trying to install it on 1.16.1

**Comment by TheCurle** [comment]
If you go to this link [here](https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar), what does it do?

**Comment by Boe-Bio** [comment]
It downloads a jar file

**Comment by TheCurle** [comment]
That's what the installer is trying to download.
The URL isn't blocked, so you may have to try it again a few times.

**Comment by Boe-Bio** [comment]
I downloaded it, now what?

**Comment by FinnT730** [comment]
> That's what the installer is trying to download.
> The URL isn't blocked, so you may have to try it again a few times.

You do what Curle said :)

**Comment by TheCurle** [comment]
Downloading it yourself will do nothing, I only sent you to that link in case your network / router was blocking the URL.

Since your browser downloads the jar file, it's probably just a transient glitch.

**Comment by Boe-Bio** [comment]
So, what do I do? I'm confused

**Comment by TheCurle** [comment]
The installer, run it again

**Comment by Boe-Bio** [comment]
Still says the same thing

**Comment by TheCurle** [comment]
Then something is stopping the installer from reaching the URL. 
I suggest you check firewalls and all that.
