### ISSUE TITLE
ZipFileSystem memory leak

### ISSUE THREAD

**Issue by ImMorpheus** [MinecraftForge/MinecraftForge#7312]
**Minecraft Version:** 1.16.2

**Forge Version:** 33.0.42

**Logs:** no crash/log.

**Steps to Reproduce:**
 1. Start the server
 2. Create an heap dump
 3. Profit

**Description of issue:**
![](https://transfer.sh/CEzqH/zipfilesystem.png)

`inodes`:
![](https://transfer.sh/wblHz/inodes.png)

`FileSystem` is `Closeable` and `inodes` is set to null when closing a `ZipFileSystem`. Something seemed suspicious there.
Looking at it further here's what I was able to find:

1. **ModDiscoverer#findPath**

https://github.com/MinecraftForge/MinecraftForge/blob/15733a18e41e53961e486001b7720b36b77c20ad/src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/ModDiscoverer.java#L178

The FileSystem is not used and it's never closed. 
N.B. this is called more than once so multiple `FileSystem`s are created.

2. **MinecraftLocator**

https://github.com/MinecraftForge/MinecraftForge/blob/15733a18e41e53961e486001b7720b36b77c20ad/src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/ModDiscoverer.java#L149

A `ZipFileSystem` is stored in a field. `MinecraftLocator` is used by the `ModDiscoverer` https://github.com/MinecraftForge/MinecraftForge/blob/15733a18e41e53961e486001b7720b36b77c20ad/src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/ModDiscoverer.java#L88 which is stored in the FMLLoader in a static field https://github.com/MinecraftForge/MinecraftForge/blob/15733a18e41e53961e486001b7720b36b77c20ad/src/fmllauncher/java/net/minecraftforge/fml/loading/FMLLoader.java#L212

3. **ClasspathLocator#scanMods**

https://github.com/MinecraftForge/MinecraftForge/blob/15733a18e41e53961e486001b7720b36b77c20ad/src/userdev/java/net/minecraftforge/userdev/ClasspathLocator.java#L56

This one is calling `AbstractJarFileLocator#createFileSystem` https://github.com/MinecraftForge/MinecraftForge/blob/15733a18e41e53961e486001b7720b36b77c20ad/src/fmllauncher/java/net/minecraftforge/fml/loading/moddiscovery/AbstractJarFileLocator.java#L54

The FileSystem is stored in the map and never closed.

**Comment by cpw** [comment]
Not a bug. You have to have the filesystem open to read the file. It may not appear to be being used, but without this, it will crash immediately you try and access the content of the file.
