### ISSUE TITLE
Vanilla Log Block Pseudobuilder Access Transformer

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#7313]
I tried doing this by forking Minecraft Forge but I was having some problems with Eclipse.
I've tried this out in 33.0.22 in my mod and it works, this is the line for transforming func_235430_a_ (this function, after the removal of the LogBlock class returns a RotatedPillarBlock with properties of a log, like wood sound and wood material)
public net.minecraft.block.Blocks func_235430_a_(Lnet/minecraft/block/material/MaterialColor;Lnet/minecraft/block/material/MaterialColor;)Lnet/minecraft/block/RotatedPillarBlock;

**Comment by diesieben07** [comment]
RotatedPillarBlock is public and this method is trivial. Why?

**Comment by ChampionAsh5357** [comment]
As dies mentioned, creating your own variation of `Blocks#log` is trivial and would probably be much more extensible like adding additional block properties. Also, this would be a strange case to expose one of the helpers and not any of the others, so is there a reason for exposing only specifically this one?

Closing this issue for the above reason. If you can provide a case towards your point above, I will reopen the issue if needed.
