### ISSUE TITLE
IForgeBlock.canBeReplacedByLogs patch for AbstractBigMushroomFeature break vanilla behavior

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#7322]
In AbstractBigMushroomFeature.generateStem, the vanilla code calls 
`if (!world.getBlockState(blockPos).isOpaqueCube(world, blockPos)) {`
which was patched with canBeReplacedByLogs instead (and is only used in AbstractBigMushroomFeature)
`if (world.getBlockState(blockPos).canBeReplacedByLogs(world, blockPos)) {`

https://github.com/MinecraftForge/MinecraftForge/blob/fe43088c96cf65c6793260eae96416871a9eb8f2/patches/minecraft/net/minecraft/world/gen/feature/AbstractBigMushroomFeature.java.patch#L7-L8

Beside the patched method's name being wonky, taking a closer look at how canBeReplacedByLogs reveals that it is not a suitable replacement for `! isOpaqueCube`

https://github.com/MinecraftForge/MinecraftForge/blob/c75eb9e7cfbdcde418f1a20175883cf61f10d900/src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java#L317-L321

Essentially, the method is suppose to make giant mushroom stems replace any block that is not opaque. The forge patch here make it unable to replace many non-opaque blocks such as ferns, flowers, bamboo, ice, cocoa, lily pads, chorus plants. Furthermore, it will also replace Dirt, Grass Block, and Logs which are opaque blocks which directly contradicts what the original method was. 

It might be better to just remove this patch for now as it is really specific to just AbstractBigMushroomFeature's stem at the moment and fails to preserve vanilla behavior for it. Or change canBeReplacedByLogs to canBeReplacedByMushroomStem and have it implement `! isOpaqueCube` by default and let other mod override it to allow/disallow mushroom stem replacement.

**Comment by SizableShrimp** [comment]
Given `IForgeBlock#canBeReplacedByLogs` has been removed in 1.17+ and 1.16 is out of support, I'm closing this as resolved.
Note that a community member could make a PR fixing this for 1.16 if they so please and it might get merged, but the Core Team will not dedicate time to fixing this.
