### ISSUE TITLE
[1.16] Bug: Axe is not effective tool for Logs & more

### ISSUE THREAD

**Issue by cech12** [MinecraftForge/MinecraftForge#7324]
**Minecraft Version:** 1.16
**Forge Version:** 33.0.61

**Description of issue:**
The method `BlockState.isToolEffective(ToolType.AXE)` returns wrong values for the axe tool type. Logs and other blocks that are defined only via its materials in `net.minecraft.item.AxeItem` return false for `BlockState.isToolEffective(ToolType.AXE)`. 

I researched a bit and I found a TODO in `net.minecraftforge.common.ForgeHooks::initTools` that could reference to this issue:
```
        blocks.forEach(block -> blockToolSetter.accept(block, ToolType.PICKAXE, 0));
        blocks = getPrivateValue(ShovelItem.class, null, 0);
        blocks.forEach(block -> blockToolSetter.accept(block, ToolType.SHOVEL, 0));
        //TODO Axes check Material and Blocks now.
        blocks = getPrivateValue(AxeItem.class, null, 1);
        blocks.forEach(block -> blockToolSetter.accept(block, ToolType.AXE, 0));
```

I think there are two possibilities to fix this issue:
1. Add at the position of this TODO also a loop that adds the axe tool type to every block with a fitting material. Con: It could be difficult to get a list of all blocks to check their material.
2. Add a material check to the `net.minecraftforge.common.extensions.IForgeBlock::isToolEffective` method. Con: There could be a problem to get the private field of the AxeItem.

Which fix is the better one?

**Comment by pupnewfster** [comment]
Closing this as the PR fixing it was merged.
