### ISSUE TITLE
Additional Tag Types - TIleEntityType, Enchantments, and possibly others

### ISSUE THREAD

**Issue by Tfarcenim** [MinecraftForge/MinecraftForge#7326]
Recently, Forge has added the ability to create custom tag registries for any ForgeRegistry.  
However, mods can only create new ones if they are the owner of the Registry they came from and cannot create new vanilla ones such as TileEntityType.
Currently, Biome is the only supported one, I would like to see TileEntityType and Enchantment as well.

**Comment by KnightMiner** [comment]
I think for adding any new tag type, it is important to describe usecases for the tag if you want it added. As in, why do we need tile entity type tags and enchantment tags?

----

For enchantments, I could see it potentially being useful to mark an enchantment as an axe enchantment, a sword enchantment, etc. Though it may be better to do that the other way, to where an enchantment has a tag of items that are acceptable. Either way requires a small rework to how enchants work and would require a lot more discussion. Beyond these I cannot think of another good use.

For tile entity type, I cannot think of one case that is not handled already by block tags, as you cannot have a tile entity without blocks. Especially with the fact that tile entity types have a closed list of blocks, you are not going to be seeing new blocks being added with an existing tile entity type that often.

The one other case I can think of being useful is potions (the forge registry calls this by the old name of `POTION_TYPE`, not referencing the effects). Could be used to tag all variants of a potion for instance. However, I think I am the only mod that uses "potions" as a crafting input, and you can always write my recipes with a list of potions instead, so I am not sure that is enough case for this.

----

Overall, this may be a discussion we should have on the forum first, then come back here with reasoning for specific tag types.

**Comment by Tfarcenim** [comment]
> For enchantments, I could see it potentially being useful to mark an enchantment as an axe enchantment, a sword enchantment, etc. Though it may be better to do that the other way, to where an enchantment has a tag of items that are acceptable. Either way requires a small rework to how enchants work and would require a lot more discussion. Beyond these I cannot think of another good use.

My usecase was providing a user friendly way of adding enchants to a specific item (spikes in this case).  Another usecase that I saw earlier is for a common tag space for enchants that should be mutually exclusive like soulbound.

For example if 3 mods add soulbound, then it would be possible to mark incompatibility with other soulbound enchants without hardcoding via
enchantment.isIn(EnchTags.SOULBOUND), instead of having to rely on a list of strings or grabbing every soulbound mod's id.

> For tile entity type, I cannot think of one case that is not handled already by block tags, as you cannot have a tile entity without blocks. Especially with the fact that tile entity types have a closed list of blocks, you are not going to be seeing new blocks being added with an existing tile entity type that often.

The problem here is some mods use blockstate sensitive block entities which wouldn't be filtered out by block tags.  This is where the tile entity type tag would be useful (and what I used pre-1.16).  The only other option to filter block entities accurately without hardcoding is to use the tile entity classes(fragile and prone to breaking) or use the blockstate(s) they're made from which are both more annoying to setup compared to a tag.

**Comment by SquidDev** [comment]
One other use case for enchantments would be classifying those with similar effects. For instance, fire aspect/flame, or knockback/punch. 

I've previously made recipes which require "any item with a fire-related enchantment". Tags would definitely be a nicer solution there compared with hard-coding the enchantments.

**Comment by Rongmario** [comment]
For TileEntityTypes, it could be used when attaching capabilities to do one isIn check.

I agree with all the aforementioned reasons for having enchantment tags, would be extremely useful.

**Comment by mrp-v2** [comment]
Does #7379 close this issue?

**Comment by pupnewfster** [comment]
Ya forgot to close the issue when it got merged, thanks.
