### ISSUE TITLE
PlayerContainerEvent.Open not fired for PlayerContainer

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#7340]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.0.1

**Logs:** N/A

**Steps to Reproduce:**
 1. Add a listener to PlayerContainerEvent.Open
 2. Put a syso that prints the name of the container  `System.out.println(event.getContainer().getClass().getName());`
 3. Open the player inventory and no message is printed.
 4. Open a furnace and the message is printed.

**Description of issue:** The PlayerContainerEvent.Open event is not fired for the player inventory container. The close event is however.

```java
    
    private void onContainer(PlayerContainerEvent event) {
        
        System.out.println(event.getClass().getName() + " " + event.getContainer().getClass().getName());
    }
```

**Comment by diesieben07** [comment]
The player container is always open. The server does not know whether you are looking at your inventory or not.
When the inventory is opened, the client simply displays a Screen. The server is not involved.
