### ISSUE TITLE
[1.12.2] Mouse misbehaving when mouse is captured by remote game streaming software.

### ISSUE THREAD

**Issue by ronankeane2** [MinecraftForge/MinecraftForge#7342]
This does not happen in Minecraft Forge 15.2, 16.2...

Host computer runs Windows 10. The primary plugged in mouse has no problems.

However, when the host mouse is "captured" by the game streaming software I am using (Rainway), then mouse inputs are corrupted.

_Basically, the movement of the mouse is much exaggerated, and it ends up spinning stuck looking up at the sky or down at the ground._

Same thing happens with Forge 1.7.10 which I tested. I also tested Forge 15.2 and 16.2 and this does not happen.

**Comment by TheCurle** [comment]
What? It doesn't happen in 1.15.2 or 1.16.2, but it does happen in 1.7.10?
This is an issue with your dodgy streaming software, and this is asking for help with an old version, and none of it adds up.
