### ISSUE TITLE
Mod logos cannot use paths as suggested by documentation

### ISSUE THREAD

**Issue by ChloeDawn** [MinecraftForge/MinecraftForge#7348]
**Forge version:** 1.16.3-34.0.13

In Forge's documentation, [the example mod](https://mcforge.readthedocs.io/en/1.14.x/gettingstarted/structuring/#the-modstoml-file) suggests that paths can be used for the logo
```toml
logoFile="assets/examplemod/textures/logo.png"
```
However, Forge uses `ResourcePack#getRootResourceStream`, which results in an `IllegalArgumentExceptiom` at runtime.

https://github.com/MinecraftForge/MinecraftForge/blob/0484f695fb51a4e266f9c0d0404ea9e640bf51cc/src/main/java/net/minecraftforge/fml/client/gui/screen/ModListScreen.java#L422

```
java.lang.IllegalArgumentException: Root resources can only be filenames, not paths (no / allowed!)
```

**Comment by TheCurle** [comment]
The documentation is outdated. I suggest you submit a PR there.

**Comment by ChloeDawn** [comment]
What is the reason for disallowing paths?

**Comment by TheCurle** [comment]
Most mod directories are hardcoded now. Such is life. The documentation should be fixed.

**Comment by ChloeDawn** [comment]
Thanks for the info ^^ I'll just use a symlink then
