### ISSUE TITLE
[1.16.3] There is no way to add separation settings for custom structures, making it impossible to get them to actually generate in the world

### ISSUE THREAD

**Issue by xyroc** [MinecraftForge/MinecraftForge#7349]
This is more or less a duplicate of #6996 

It was never possible in 1.16.x to add structure separation settings for your own structures, but with 1.16.2, Minecraft changed its behavior of handling nonexistant separation settings from using a default settings set to simply not spawning the structure at all.

As far as I know, this is the last thing that is keeping mods that add structures from updating from 1.16.1 to 1.16.3

#7331 and #7232 offer possible solutions to this problem. It would be nice if this gets dealt with in the upcoming RB.

**Comment by Aizistral** [comment]
I haven't investigated all that much on structure generation yet, but I do know a couple examples of mods that do successfully add structures that actually generate with valid seperation between them. They didn't seem to have any issues porting above 1.16.1 either. For instance: https://github.com/ValhelsiaTeam/Valhelsia-Structures/tree/1.16

Is there something I miss about the outlined issue?

**Comment by xyroc** [comment]
My bad, it is actually doable with an access transformer.
