### ISSUE TITLE
IE, Productive Bees and Forge Server = Crash

### ISSUE THREAD

**Issue by kman3107** [MinecraftForge/MinecraftForge#7354]
### Description of the issue:
NB! This only happens when running the forge server install!
Normal forge client works just fine.

1. Drill for Core Sample, get Core Sample but it has no texture aside the Stone like.
2. Crash is when hovering the mouse over the Core Sample in the inventory.
3. Crash also when looking at a placed Core Sample in the world

Happened several times during my live stream.
This is a highlight of the first time I crashed https://www.twitch.tv/videos/751380402

### Crashlog:
https://pastebin.com/46vNRdNC - This is a crash when looking at a placed Core Sample in the world. (Enigmatica 6)
https://pastebin.com/SE1X0btK - This is a crash when hovering the mouse over the Core Sample in the inventory. (Enigmatica 6)
https://pastebin.com/2NFVnGzk - This crash is when hovering the mouse over the Core Sample in the inventory. (Only 3 mods+forge)

### Versions & Modlist
Forge Server: 1.16.1-32.0.108
IE: 1.16.1-4.0.0-118
Productive Bees: 1.16.1-0.3.3 and 0.3.5
JEI: 1.16.1-7.0.1.10

I spent a LOT of time just to figure out what was causing my crashes. I can say with 100% that IE, Productive Bees and Forge Server with the versions mentioned above are not going to work together . Tried on 2 different pcs. (Client on same pc, but server on 2 different servers). Honestly I don't know if this is an issue with IE, Productive Bees, or Forge.

PS: I'm just reporting the issue. I don't need help.

**Comment by diesieben07** [comment]
Not a Forge issue. ImmersiveEngineering is crashing.
