### ISSUE TITLE
[1.16.3] Particles that use texture lists cannot be loaded.

### ISSUE THREAD

**Issue by Shadows-of-Fire** [MinecraftForge/MinecraftForge#7358]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.0

**Logs:** https://gist.github.com/Shadows-of-Fire/1bf7315b789468eccf785ee44d902f2b

**Steps to Reproduce:**
1. Register a particle that uses the vanilla atlas-texture system (extends SpriteTexturedParticle)
2. Register a particle type for said particle.
3. Provide a `<particle id>.json` file that points to the texture, and try to launch the game, you will crash with the following report from in the gist.  

**Description of issue:**
Loading textured particles appears to be broken in the RB of 1.16.3, I'm not sure why.  It works correctly on 1.16.2-33.0.22.

This crash happens during startup (right around when the texture stitch event is fired), and the game never reaches the main menu.

**Comment by Shadows-of-Fire** [comment]
This appears to be a race condition, actually.  Since this crash happens if ParticleManager#registerFactory has not been called for a given particle type before textures are loaded.  Since that method is not threadsafe, it needs to be enqueued to run later on the main thread, and sometimes the queued work does not happen before texture stitch, which causes this crash.

**Comment by diesieben07** [comment]
> Since that method is not threadsafe, it needs to be enqueued to run later on the main thread, and sometimes the queued work does not happen before texture stitch, which causes this crash.

Use the correct event to register your particle factories: `ParticleFactoryRegisterEvent`. Please confirm if that fixes your issue.

**Comment by Shadows-of-Fire** [comment]
That does work, but is that safe?  My understanding is that all of the mod bus events run in parallel, in which case registering factories could cause a race condition here.  Am I mistaken in that assumption?

**Comment by diesieben07** [comment]
> Am I mistaken in that assumption?

You are. Not all events on the mod bus are parallel.
