### ISSUE TITLE
[1.16] Attempting to teleport player in LivingDeathEvent crashes... sometimes

### ISSUE THREAD

**Issue by Aizistral** [MinecraftForge/MinecraftForge#7365]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.0.7

**Logs:** https://gist.github.com/Extegral/18797c705b6bf0a810bab93aadbc1871

**Steps to Reproduce:**
 1. Subscribe to `LivingDeathEvent` in your event handler;
 2. Try to teleport player to other dimension in this event - whether or not the event is cancelled does not matter;
 3. Behold!.. probably.

**Description of issue:**
The crash seems to only happen if player is killed by any entity that is instance of `IAngerable`, like an Enderman. I am clueless to why it does happen under such weird requirement, but it's surprisingly consistent if the requirement is met, and there's seemingly no way around it. The crash itself seems to happen because the player entity is removed in `ServerPlayerEntity#changeDimension`, but this doesn't explain why player is supposedly ticked while event is fired and why they aren't if they die from cause different than neutral mob attack.

It seems to have been the case at least since 1.16.1, but only recently I was reported about this happening in my mod and was able to confirm it across 1.16.1-1.16.3.

**Comment by diesieben07** [comment]
Not a forge bug. You cannot remove entities from the world during the entity tick. What is happening in your crash is that a zombie attacked the player and you then tried to teleport them. That won't work, because this is during the entity tick.
