### ISSUE TITLE
[1.16.3] LootTableLoadEvent not fired for overridden tables

### ISSUE THREAD

**Issue by Aizistral** [MinecraftForge/MinecraftForge#7366]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.0

**Logs:** https://gist.github.com/Extegral/1d2c291bcb904905904810dae49fd78f

**Steps to Reproduce:**
 1. Override some of the vanilla loot tables by placing .json files for them in your mod's data;
 2. Watch people report issues to countless mods who add their loot via `LootTableLoad` event on the topic of this loot not being added in their modpack, because your one mod is dumb enough to do that and screw up other people's custom loot.

**Description of issue:**
To test this, I specifically added simple debug line in my event handler for `LootTableLoadEvent`:

```
	@SubscribeEvent(priority = EventPriority.LOWEST)
	public void onLootTablesLoaded(LootTableLoadEvent event) {
		System.out.println("LootTable loaded: " + event.getName());
		...
```

The log I attached clearly shows that event is never fired for simple_dungeon, ruined_portal and pillager_outpost, which are the exact 3 loot tables I have overriden for the sake of this test in my mods' data:

![image](https://user-images.githubusercontent.com/47505981/94356816-d98c2e00-0092-11eb-88cc-266e1f1ff73e.png)

This issue is a duplicate of #6107, which I reported two major Minecraft versions ago, and which have never received any attention, later being marked as stale and closed. It seems to have never been addressed since.

**Comment by diesieben07** [comment]
This is apparently intentional, the event is not fired for anything outside the default resource pack.
However the event is now basically deprecated, the way to modify loot is [global loot modifiers](https://mcforge.readthedocs.io/en/latest/items/globallootmodifiers/).

**Comment by Aizistral** [comment]
I have assumed at some point this might be intentional, but dismissed the thought granted how little potential issues it solved and how much of a headache created back in the day.

> However the event is now basically deprecated, the way to modify loot is global loot modifiers.

Sad, but understandable. Have a good day.

**Comment by TeamSpen210** [comment]
The reason is so that user datapacks are able to override loot tables without having to worry about mods silently replacing it. It’s not a good idea to directly override files in the mod data pack, since if multiple mods override the same file there’s no real way to know which will win.

**Comment by Aizistral** [comment]
I believe it should've been up to mod developers to expose ways to control loot they are adding/replacing. Botania used to do it by having basically a set of separate loot tables in it's data, that later had their contents injected into vanilla ones through this event. I the case of ultimate laziness, you can at least make a config option to turn off custom loot.

But it's a hissing to permit individial mods to break any custom loot added into vanilla tables so easily, except their own. The Forge itself does not provide any clues that overriding vanilla tables is datapack is a super bad idea, and a lot of unexperienced developers, especially those who had more experience with just datapacks in the past, have accidentally mislead themselves to implementing it like this. What's worse it that there's no telling to what exact mod is dumb enough to do this in the modpack - you have to look through every individual modfile to find out. It's an issue that affected both mod developers and modpack makers, in ways not exactly pleasant to resolve.

I do believe it should have been possible to at least discern datapacks embedded in mods from standalone datapacks, and either fire event for the former, or simply not load any loot table provided by mod if it is already loaded by vanilla.

**Comment by Extegral** [comment]
Does this code count as an insult?

https://github.com/Extegral/Enigmatic-Legacy/blob/1.16.X/src/main/java/com/integral/enigmaticlegacy/mixin/MixinForgeHooks.java

I hope this code counts as an insult.
