### ISSUE TITLE
[1.16] Forge Attributes cause error spamm on client

### ISSUE THREAD

**Issue by Flemmli97** [MinecraftForge/MinecraftForge#7368]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.0

**Logs:** Vanilla client log: [https://pastebin.com/XVQfmuyQ](url)

**Steps to Reproduce:**
 1. Setup a forge server
 2. Connect to it with a vanilla client

**Description of issue:**
Since forge adds their own attributes (see ForgeMod.SWIM_SPEED, or ForgeMod.REACH_DISTANCE) when those get sent to the client for update the client obviously doesnt know about them causing "Entity x does not have attribute null" error message spamm

**Comment by diesieben07** [comment]
This has been fixed as of 1.16.4-35.0.2.
