### ISSUE TITLE
[1.16.3] Forge attributes don't have proper translation key

### ISSUE THREAD

**Issue by Lykrast** [MinecraftForge/MinecraftForge#7372]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.0

**Description of issue:**
The forge attributes (reach, swimming speed, ...) don't have a proper translation key (or have an incorrect one) and thus don't display properly when shown in a tooltip, such as the "When in Main Hand" of swords via `getAttributeModifiers` or on potion effects, as seen here (with a vanilla attribute to compare):

![image](https://user-images.githubusercontent.com/8684850/94434240-bf894300-0199-11eb-806c-77793ec8e869.png)

**Comment by IsaacMSchultz** [comment]
Hello,

I am new to helping out with the open source community, is there any way you could provide some of the code that sets these attributes?

Thanks!

**Comment by ChampionAsh5357** [comment]
Look in the forge source yourself? You're quite literally on a github that shows all of forge code and can download to get an extrapolated version of vanilla code.

**Comment by ChampionAsh5357** [comment]
The attribute keys are simple enough to fix/add, the translations are what's needed though.
