### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by chickiyeah** [MinecraftForge/MinecraftForge#7375]
**Minecraft Version:** 1.12.2
**Forge Version:** forge-1.12.2-14.23.5.2854

**Logs:** java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:** java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker

**Comment by FinnT730** [comment]
1.12 is not supported

**Comment by TheCurle** [comment]
1.12.2 is not supported.

**Comment by chickiyeah** [comment]
Server cant boot..

**Comment by FinnT730** [comment]
and? 1.12.2 is not supported
