### ISSUE TITLE
Mods with modids before "forge" cannot override recipes that forge overrides

### ISSUE THREAD

**Issue by FlashFyreMods** [MinecraftForge/MinecraftForge#7376]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.0

**Logs:** None required as no error is thrown

**Steps to Reproduce:**
 1. Create mod with modid alphabetically before forge (starts with a, b, c , d, fa, fb, etc.)
 2. Override recipe (in my testing I overrode src\main\resources\data\minecraft\recipes\netherite_ingot.json, yes the directory is correct and there are no errors in the file)
 3. Test out vanilla recipe in game, you will notice it will work as normal even though you overrode the recipe, because forge overrode it after our mod. For this reason, even if I made a netherite_ingot.json that was blank, no errors would come up in the console.

**Description of issue:**
Mod recipes including Forge are loaded alphabetically - Forge does not treat itself as a special case when it should override recipes first, and as I was informed it overrides certain specific vanilla recipes (such as the netherite ingot). If a mod is earlier alphabetically then Forge will override your mod's recipes instead of vanilla ones. This obviously doesn't apply to most recipes, ones that forge doesn't override.

**Comment by sciwhiz12** [comment]
For anyone who encounters this issue; the solution is to change the Forge dependency in your mods.toml to `ordering=AFTER`.

The datapack load order is taken from the mod order, so this will position your mod to always be after Forge, so your recipe overrides will work even if Forge overrides them.
