### ISSUE TITLE
License Warning Text Cut Off When Resizing Client Window

### ISSUE THREAD

**Issue by Darkosto** [MinecraftForge/MinecraftForge#7382]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.1

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
debug.log = https://pastebin.com/uy9Nz2BY

**Steps to Reproduce:**
 1. Add mod that does not have a proper license setup
 2. Load up the pack
 3. Resize the window 

**Description of issue:** When a mod is missing the required license, the warning window comes up: 

![image](https://user-images.githubusercontent.com/10309699/94870551-a3391080-03fc-11eb-932f-3ec905a01ba0.png)

On window resize, the text does not wrap and cuts off the remainder of the file location:

![image](https://user-images.githubusercontent.com/10309699/94870570-af24d280-03fc-11eb-9b99-eb173b845603.png)

**Comment by diesieben07** [comment]
The "bug" here has nothing to do with resizing the window, at least not directly. The individual entries are limited to a height of 2 lines, because the underlying GUI widget (scrollable list) requires a fixed height for every entry.

**Comment by cpw** [comment]
The definite resource for any mod related crash should be the crash report linked from the button. The UI is meant as a convenience. Resizing of things is really annoying and hard to handle. Would recommend closing because it's really annoying.

**Comment by diesieben07** [comment]
Well, resizing is already handled. It's just that the scroll list slot is "too small".
But yes, not really possible to fix with the existing GUI widget.
