### ISSUE TITLE
[1.16.3] TameableEntity isSitting()/func_233685_eM_() is always false.

### ISSUE THREAD

**Issue by ricksouth** [MinecraftForge/MinecraftForge#7388]
**Minecraft Version:** 1.16.3

**Forge Version:** 1.16.3-34.1.1

**Logs:** N/A

**Steps to Reproduce:**
 1. Get a Tameable entity, e.g. WolfEntity or CatEntity.
 2. Check isSitting() when not sitting = false
 3. Check isSitting when sitting = false

**Description of issue:**
The isSitting() function, or func_233685_eM_() obfuscated, is always false in 1.16.3. In 1.15.2 everything works as intended. I also tried it directly with the CompoundNBT data, same problem. Seems to not be updated somewhere.

**Comment by diesieben07** [comment]
Cannot reproduce with a Wolf. Please provide a way to reproduce.

**Comment by ricksouth** [comment]
Further testing shows the isSitting() function works when run on the server-side, but not on the client-side. When the code is run on the client-side it doesn't matter if it's in singleplayer or multiplayer. Both always return false.

I assume the information should be available client-side. The (almost) same code worked fine in 1.14.4 and 1.15.2.


Example code:
```
//Main Class:
private void loadComplete(final FMLLoadCompleteEvent event) {
  if (FMLEnvironment.dist.equals(Dist.CLIENT)) {
    MinecraftForge.EVENT_BUS.register(new TestEvent());
  }
}

// Event Class:
@EventBusSubscriber
public class TestEvent {
	@SubscribeEvent
	public void onPlayerTick(PlayerTickEvent e) {
		PlayerEntity player = e.player;
		World world = player.getEntityWorld();
		if (!world.isRemote || !e.phase.equals(Phase.START)) {
			return;
		}
		
		if (player.ticksExisted % 20 != 0) {
			return;
		}
		
		Vector3d pvec = player.getPositionVec();
		List<Entity> entitiesaround = world.getEntitiesWithinAABBExcludingEntity(player, new AxisAlignedBB(pvec.x-5, pvec.y-5, pvec.z-5, pvec.x+5, pvec.y+5, pvec.z+5));
		for (Entity ea : entitiesaround) {
			if (ea instanceof TameableEntity == false) {
				return;
			}
			
			TameableEntity te = (TameableEntity)ea;
			
			boolean issitting = te.func_233685_eM_();
			System.out.println(te);
			System.out.println(issitting);
		}
	}
}```

**Comment by ricksouth** [comment]
<img width="737" alt="dsafsa" src="https://user-images.githubusercontent.com/38502394/94942557-c3d59900-04d6-11eb-8e2c-403b2532c4cf.PNG">

**Comment by MWall541** [comment]
Im pretty sure this is intentional behaviour. `func_233685_eM_()` Is a getter for the field that enqueues for sitting. That field is then used in the SitGoal of tameables, which then sets the data manager value for sitting. You should instead be using `func_233684_eK_()` which access this data.
