### ISSUE TITLE
[1.12.2] hello I have a problem connecting to the server that we created between some friends to play

### ISSUE THREAD

**Issue by Arzhel1109** [MinecraftForge/MinecraftForge#7389]
**Minecraft Version:** 1.12.2

**Forge Version:** forge-1.12.2-14.23.5.2854

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

 hello I have a problem connecting to the server that we created between some friends to play and it is that it bounces me sometimes it enters and sometimes it does not throw an error, I have located this error in the console it seems to be a chunk load error I have seen that when they load The chinks if they let me in but when they load 1 by 1 they boot me, change from joruney to voxel and the problem continued, I don't know what it is, I don't have much knowledge of the truth about this type of problem,

[Netty Client IO #9/INFO] [FML]: Server protocol version 2
Cliente> [13:28:40] [Netty Client IO #9/INFO] [FML]: Attempting connection with missing mods [voxelmap, blockdrops, classicbar, ctm, dropoff, dynamiclights, dynamiclights_onfire, dynamiclights_creepers, dynamiclights_dropitems, dynamiclights_entityclasses, dynamiclights_mobequipment, dynamiclights_flamearrows, dynamiclights_floodlights, dynamiclights_otherplayers, dynamiclights_theplayer, inventorytweaks, jeiintegration, jeresources, mousetweaks, neat, wailaharvestability] at SERVER
Cliente> [13:28:45] [Client thread/INFO] [FML]: Injecting existing registry data into this client instance
Cliente> [13:28:53] [Client thread/INFO] [FML]: Applying holder lookups
Cliente> [13:28:53] [Client thread/INFO] [FML]: Holder lookups applied
Cliente> [13:28:53] [Netty Client IO #9/INFO] [FML]: [Netty Client IO #9] Client side modded connection established
Cliente> [13:29:08] [Client thread/WARN] [minecraft/NetHandlerPlayClient]: Received passengers for unknown entity
Cliente> [13:29:10] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:10] [Netty Client IO #9/INFO] [Waila]: Received server authentication msg. Remote sync will be activated
Cliente> [13:29:10] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:10] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:11] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:11] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:11] [Netty Client IO #9/INFO] [Mekanism]: Received config from server.
Cliente> [13:29:11] [Netty Client IO #9/INFO] [Mekanism]: Received Cardboard Box blacklist entries from server (26 explicit blocks, 2 mod wildcards)
Cliente> [13:29:11] [Netty Client IO #9/INFO] [tconstruct-Config]: Syncing Config with Server
Cliente> [13:29:12] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:12] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:13] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:13] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:14] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:14] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:15] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:16] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:17] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:17] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:18] [Client thread/INFO] [minecraft/AdvancementList]: Loaded 511 advancements
Cliente> [13:29:18] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:19] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:20] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:21] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:21] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:22] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:23] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:23] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:24] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:25] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:25] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:27] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:27] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:28] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:29] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:29] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:30] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:31] [Voxelmap LiveMap Calculation Thread/FATAL] [CodeChickenLib]: A CCL controlled model has been improperly handled by someone and will NOT be rendered. No more information available.
Cliente> [13:29:39] [Netty Client IO #9/ERROR] [FML]: NetworkDispatcher exception
Cliente> java.io.IOException: Se ha forzado la interrupción de una conexión existente por el host remoto
Cliente> 	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_261]
Cliente> 	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_261]
Cliente> 	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_261]
Cliente> 	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_261]
Cliente> 	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_261]
Cliente> 	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[PooledUnsafeDirectByteBuf.class:4.1.9.Final]
Cliente> 	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[AbstractByteBuf.class:4.1.9.Final]
Cliente> 	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[NioSocketChannel.class:4.1.9.Final]
Cliente> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [AbstractNioByteChannel$NioByteUnsafe.class:4.1.9.Final]
Cliente> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [NioEventLoop.class:4.1.9.Final]
Cliente> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:4.1.9.Final]
Cliente> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:4.1.9.Final]
Cliente> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:4.1.9.Final]
Cliente> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
Cliente> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by DaemonUmbra** [comment]
We don't actively support 1.12 anymore.
Please update to a modern version to receive support.
