### ISSUE TITLE
Different sized slimes all have the same eye height

### ISSUE THREAD

**Issue by sekelsta** [MinecraftForge/MinecraftForge#7399]
**Minecraft Version:** 1.16.3

**Forge Version:** 1.16.3-34.1.10

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Press F3 + B to show hitboxes
 2. /summon minecraft:slime ~ ~ ~ {Size:10}
 3. Observe eye height very low (compared to vanilla where it's about halfway up)
 4. (Optional): summon more sizes of slimes, and all appear to have the same eye height

**Description of issue:**
I think the issue may be in Entity.recalculateSize(), where it calculates eye height using the old size instead of the new one when creating the EntityEvent.Size event. Aside from the slimes, when I mod entities to have different sizes, they always have the same eye height no matter their size.

**Comment by KnightMiner** [comment]
Probably related to #7305

**Comment by diesieben07** [comment]
Fixed with https://github.com/MinecraftForge/MinecraftForge/pull/7628
