### ISSUE TITLE
[1.16.3] Entries added to the list of WorldEvent.PotentialSpawns fail to spawn

### ISSUE THREAD

**Issue by McJty** [MinecraftForge/MinecraftForge#7402]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.5

**Logs:** No crash or log

**Steps to Reproduce:**
 1. Make an event handler for WorldEvent.PotentialSpawns
 2. Add a minecraft:blaze entry to the list (with weight 5, mincount 2, maxcount 5)
 3. Run MC. Observe how no blazes are spawning in the overworld

In 1.15.2 doing the steps above would cause blazes to spawn in the overworld. However in 1.16.3 the event is still called and the result seems to be used in WorldEntitySpawner. However func_234975_a_() returns false for the returned mobs because the blaze mob is not in the list returned by func_241463_a_() (which is basically the list of spawns supported by the biome). Due to this it seems that in 1.16.3 it is no longer possible to add spawns to the potentialspawn event that are not supported by the underlying biome.

**Comment by McJty** [comment]
hold on. Under investigation to see if BiomeLoadingEvent  fixes this

**Comment by alcatrazEscapee** [comment]
This is a duplicate of #7309 I believe.

**Comment by McJty** [comment]
Oh indeed. I'll close this one then. Sorry
