### ISSUE TITLE
IForgeBlockState::isAir and IForgeBlock::isAir lack parity with AbstractBlockState::isAir, vine blocks crash when above blocks that return differing values for these

### ISSUE THREAD

**Issue by Commoble** [MinecraftForge/MinecraftForge#7406]
**Minecraft Version:** 1.16.3

**Forge Version:** 1.16.3-34.1.12

**Logs:** https://gist.github.com/Commoble/e675e3ba0fa8366a6200c4eefd184f14

**Steps to Reproduce:**
 1. Define a block whose material is Material.AIR but whose Block.Properties does not set .setAir()
 2. Place this block below a vine block
 3. Wait for the vine block to incur a random tick, causing a crash

**Description of issue:**
This crash occurs because of two things:

A)
`IForgeBlockState.isAir(IBlockReader world, BlockPos pos)` returns `IForgeBlock.isAir(BlockState state, IBlockReader world, BlockPos pos)`, which in turn returns `state.getMaterial() == Material.AIR`

Meanwhile, AbstractBlockState.isAir() returns a value `isAir` in the blockstate, which defaults to false, but is set to true by calling `properties.setAir()` on the Block.Properties when defining the block instance.

If the creator of a block sets the block's material to AIR without setting the properties to air, and doesn't further override either isAir method, then state.isAir() != state.isAir(world, pos).

B)
In part of the random tick method of vine blocks, this occurs:
```
let abovePos = the position above the vine block
let belowPos = the position below the vine block
let belowState = the state below the vine block
if belowState.isAir(world, abovePos) OR belowState is vine block // there may be a typo in the patch file here
    if belowState.isAir() is false, let belowState = default vine block state
    call this.func_196544_a on belowState, which crashes if belowState isn't a vine block state
```
Assuming a given block overrides no methods related to airiness, the function at the end up there is called on a non-vine-state when both of the following are true:
-- the state below the vine block returns true for `belowState.isAir(world, pos)`, i.e. the block's material is Material.AIR
-- the state below the vine block returns false for `belowState.isAir()`, i.e. the block's Block.Properties was not set to .isAir()

This may cause confusing crashes, and in particular it is perfectly capable of crashing from vines being above plain ol' Block instances whose material and properties meet the above criteria (though such a block instance isn't present among vanilla blocks, thankfully).

This crash can be fixed forge-side in several ways; ensuring parity between the vanilla and forge isAir methods by changing `IForgeBlock::isAir(BlockState state, IBlockReader world, BlockPos pos)` to return `state.isAir()` would ensure isAir == isAir for blocks that don't overide either, which is probably a good idea. Patching the VineBlock class further to ensure all cases of isAir() are patched to isAir(state, world, pos) would also prevent the vine block from crashing when a block overrides one method or the other.

**Comment by LexManos** [comment]
Honestly, these edge cases are gunna pop up more and more, I've started a RFC for removal of our positional hooks in 1.17, They have existed since before blockstates/blocks were unlimited so I think it's time to remove them.
https://github.com/MinecraftForge/MinecraftForge/issues/7409
