### ISSUE TITLE
[1.16.3] Loading screen freezing

### ISSUE THREAD

**Issue by KhanhPham05** [MinecraftForge/MinecraftForge#7407]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.14

**Steps to Reproduce:**
 Just simply add about 70 mods into the game and run it with about 3,1GB of allocated (3500 MB in the twitch setting)

**Description of issue:**
The game not turn back to the main menu and still standing in the mod loading screen. The main menu music still on

It takes several times restart the game to load the main menu

**Comment by ChampionAsh5357** [comment]
You will need to add the `debug.log` of this problem. 2 mods can have the same problem depending on if they handle their data properly. I'm pretty sure this won't work for just any set of 70 mods.
