### ISSUE TITLE
Can't interact with entities and block 

### ISSUE THREAD

**Issue by JacobFrodermann** [MinecraftForge/MinecraftForge#7416]
**Minecraft Version:** {1.7.10}

**Forge Version:** {1.7.10-Forge10.13.4.1641

**Logs:** {[latest log (lBackup loaded)](https://github.com/MinecraftForge/MinecraftForge/files/5378082/latest.log)}

**Steps to Reproduce:**
 1. Install the mods from the [Mod list](https://github.com/MinecraftForge/MinecraftForge/files/5378083/Mod.list.txt)
 2. Open to Lan with cheats
 3. Wait a minuit
4. Close the world

**Description of issue:**
A short time after I opend the world I can't interakt with blocks or entities, it's like as if I'm on a server but with out any permission, if i close the world minecraft stops the shutting down proces at "Shutting down internal server" than minecraft does not react any more, restoring an Backup doesn't helps too.

**Comment by TheCurle** [comment]
First off, this is not a valid bug report for this repository, 
Second, 1.7.10 is ancient and long since unsupported. 
Update.
