### ISSUE TITLE
[1.16.3] Wrong Block player is facing returned

### ISSUE THREAD

**Issue by DevFeddy** [MinecraftForge/MinecraftForge#7419]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.0, 34.1.10, 34.1.21

**Logs:** No crash

**Steps to Reproduce:**
 1. Use `Minecraft.getInstance().objectMouseOver.getHitVec()` in a Mod
 2. Make a BlockPos from that
 3. Print the BlockPos or the coordinates from the BlockPos

**Description of issue:**
`Minecraft.getInstance().objectMouseOver.getHitVec()` returns the block next to the block you're looking at (the block in your direction) when you're looking from above the block, facing north or facing west (and look at the nearest side of the block). If you're looking from under the block, facing south or facing east it works.

**Comment by diesieben07** [comment]
The hit vector is not the block position.
