### ISSUE TITLE
Cant see skills when vampire

### ISSUE THREAD

**Issue by PresidentSwift** [MinecraftForge/MinecraftForge#7429]
Version 1.14.4
latest version of forge for 1.14.4

what I'm using
 1. go to twitch launcher
 2. download web of time modpack
 3. go onto the server I am staff on and am having issue on (ip: apollo.rnshosting.xyz:25579)

when I'm or any other player is a vampire we cant see the skills tree, you can go onto where it should be, by clicking the fangs under the crafting table in inventory but the only thing that is in there is 'Becoming a vampire' but nothing else, i also couldn't move when in there but i fixed that issue by relogging.
I posted something on the discord server by the haven't seem to have seen it before. I want to get this fix cuz there is a small player base that plays on the server and it would be a shame to get rid of it from the modpack. Thanks

-Swift

![image](https://user-images.githubusercontent.com/73315113/96930759-24dc0580-14b4-11eb-8499-b47c9ce7cfd4.png)

**Comment by ravenbuilder934** [comment]
1. Your Minecraft version (1.14.4) is not supported anymore
2. This sounds like the mod's fault and not Forge's

**Comment by PresidentSwift** [comment]
what do you suggest i do?

**Comment by DaemonUmbra** [comment]
Report it to the mod devs is all we can suggest.
