### ISSUE TITLE
FMLEnvironment.secureJarsEnabled is always false

### ISSUE THREAD

**Issue by ZekerZhayard** [MinecraftForge/MinecraftForge#7452]
**Minecraft Version:** 1.16.3

**Forge Version:** 34.1.35

**Description of issue:**
[`FMLEnvironment.secureJarsEnabled`](https://github.com/MinecraftForge/MinecraftForge/blob/06fe9ccda0fc0620a9152e8603cf55652c64c51f/src/fmllauncher/java/net/minecraftforge/fml/loading/FMLEnvironment.java#L34) is defined by checking `IEnvironment.Keys.SECURED_JARS_ENABLED` at the first time when `FMLEnvironment` initializing. However, at that time, [`SecureJarHandler`](https://github.com/cpw/modlauncher/blob/3310fe0af0011732005f7e5dcf2634f72d77ca89/src/main/java/cpw/mods/modlauncher/SecureJarHandler.java#L51) has not been loaded and `IEnvironment.Keys.SECURED_JARS_ENABLED` won't be updated, so that `secureJarsEnabled` will always be false and never be true.

An obvious effect is that `Secure mod features disabled, update JDK` will be always displayed in mod list screen no matter what JDK version is:
![image](https://user-images.githubusercontent.com/41327811/97717410-b9231980-1aff-11eb-884b-f2804ebcb476.png)

**Comment by cpw** [comment]
Heh. Thanks. I didn't realize it was that early LUL.
