### ISSUE TITLE
1.16.4 Example mods.toml loaderVersion and dependency version not up to date.

### ISSUE THREAD

**Issue by GeheimagentNr1** [MinecraftForge/MinecraftForge#7460]
In Version 1.16.4 - 35.0.1of the forge MDK the loadVersion and the dependency version range of forge are 34 and not 35.
And the version of the Minecraft dependency is 1.16.3 instead of 1.16.4

Here the zipped mods.toml:
[mods.zip](https://github.com/MinecraftForge/MinecraftForge/files/5482466/mods.zip)

**Comment by pupnewfster** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/38a5400a8c878fe39cd389e6d4f68619d2738b88
