### ISSUE TITLE
[1.17] Incorporate new Coremods scripting solution

### ISSUE THREAD

**Issue by cpw** [MinecraftForge/MinecraftForge#7470]
Incorporate new coremods scripting solution as part of 1.17 update.

Project here: https://github.com/orgs/MinecraftForge/projects/2

**Comment by LexManos** [comment]
This has been resolved in 1.16 by https://github.com/MinecraftForge/MinecraftForge/commit/dd10933ab0a973db5730caeae875d3aa3577abd6
