### ISSUE TITLE
FML Lifecycle Events involving starting the server not cancellable

### ISSUE THREAD

**Issue by TheGlitch76** [MinecraftForge/MinecraftForge#7473]
**Minecraft Version:** Tested on 1.15.2, offending code present to 1.16.4

**Forge Version:** Commit hash 9ea3f8f6f147e4a9a2ef97ca25edddd96f003196 was used for testing (this was tested in a forgedev workspace), but the code is the same up to and including 0d7f507f4e7337436e3208d5ba4054ef14895669 (latest at the time of reporting this issue)

**Logs:** https://pastebin.com/VVXSj1fC

**Steps to Reproduce:**
1. Look at the implementation of the FML life cycle events for the server starting and note that they are implemented as if they are cancellable.
2. Attempt to cancel one of these events (i.e. FmlServerStartingEvent)
3. The game crashes because the events are not marked `@Cancellable`

**Description of Issue:**
Some of the FML server lifecycle events in `ServerLifecycleHooks` are implemented in a way that is cancellable, but are not marked `@Cancellable`. FmlServerAboutToStart and FmlServerStarting are the two that I noticed, but others may exist.

**Recommended Fix:**
Either properly flag the events, or remove the dead code handling cancelling them.

**Comment by TheCurle** [comment]
Or... just don't cancel a non cancelable event and call it a bug?

**Comment by DaemonUmbra** [comment]
This sounds like "Take the gun away so I don't shoot my foot" honestly

**Comment by kitlith** [comment]
afaict the report is less the fact that it's crashing and more the fact that it's unclear if the event was intended to be cancellable or not. like, if the event is supposed to be cancellable but the annotation got dropped/removed, that's a bug. if the event is not supposed to be cancellable, that's dead code. either solution is fine, but that doesn't mean we know which is intended to submit a PR to fix it.
