### ISSUE TITLE
ConcurrentModificationException when making call to StartupMessageManager#addModMessage

### ISSUE THREAD

**Issue by josephtarbit** [MinecraftForge/MinecraftForge#7474]
**Minecraft Version:** 1.15.2

**Forge Version:** 31.2.45

**Logs:** https://gist.github.com/Sm0keySa1m0n/50b6303047d5a9286dc70677101637e1

**Steps to Reproduce:**
Seems to be a race condition, can't reliably reproduce.

**Description of issue:**
During `FMLClientSetupEvent`, making a call to `StartupMessageManager#addModMessage` will sometimes produce a `ConcurrentModificationException`.

**Comment by diesieben07** [comment]
Can confirm, this is a race condition due to the incorrect use of `CopyOnWriteArrayList`.
I will work on a fix.
