### ISSUE TITLE
Missing License Information in Mod File:

### ISSUE THREAD

**Issue by Derpchadas** [MinecraftForge/MinecraftForge#7477]
**Minecraft Version:** 1.16.4

**Forge Version:** 35.0.7

**Logs:** https://gist.github.com/Derpchadas/9e08efbbe3508f33b1c9812415135721

**Steps to Reproduce:**
 1. Download and install Forge 35.0.7
 2. Place any mod file in the Mods folder
 3. Open Forge and let it run
 4. Instead of being brought to the Minecraft menu you will be sent to an error screen

**Description of issue:**
Every mod I place in the Mods folder ends up giving me `"Error loading mods"`
`Missing License Information in file Mod File: (insert file path)` times however many mods you have in place

There are no fixes I can find for this except to have an empty Mods folder, in which case I'm just running vanilla, which while fun in itself doesn't give you that added bit of pleasure from mods

**Comment by TheCurle** [comment]
This is an issue with the mods, not with Forge.

**Comment by Derpchadas** [comment]
This problem is with every mod i try to use that is marked for Forge. That would currently be 13. Each one has had this issue.

**Comment by LexManos** [comment]
Yup, The license was made manditory in 1.16.2, They need to add the license entry to their mods.toml File.
Make sure you use mods written for the version of Minecraft you're trying to load.
