### ISSUE TITLE
[1.14.4] Dimensions that are registered won't show in game.

### ISSUE THREAD

**Issue by SpectrumFATM** [MinecraftForge/MinecraftForge#7480]
**Minecraft Version:** 1.14.4

**Forge Version:** {1.14.4 - 28.2.23

**Logs:** https://github.com/SpectrumFATM/TARDIS-Mod-Planets

**Steps to Reproduce:**
Unknown

**Description of issue:**
So, I've written my code for a dimension (Correctly as I've been told, although I am a beginner) and I've used DeferredRegistries to register the dimension and it just will not show up in game, I've tried building it and I've also tried others running it with 0 luck and downgrading forge doesn't work, this leads me to believe it was on my end but after comparing it to other mods and having 2 other people check my code I'm confident it is correct.

**Comment by TheCurle** [comment]
1.14 is unsupported. This isn't an issue with newer versions, as i understand it.
