### ISSUE TITLE
SCustomPayloadPlayPacket Buffer Leak Regression

### ISSUE THREAD

**Issue by pau101** [MinecraftForge/MinecraftForge#7486]
**Minecraft Version:** 1.13 - 1.16

**Forge Version:** 25.0 - 35.0.15

**Logs:** [Output of Netty Leak Detection](https://gist.github.com/pau101/e5af99da06886e336e80ee83083aadb6)

**Steps to Reproduce:**

1. Launch with JVM arg `-Dio.netty.leakDetection.level=advanced`
2. Join a multiplayer server

**Description:**

In #4512 two patches were added to resolve [MC-121884](https://bugs.mojang.com/browse/MC-121884), one in `SCustomPayloadPlayPacket` (then `SPacketCustomPayload`) to add the buffer release, and one in `ClientPlayNetHandler` (then `NetHandlerPlayClient`) to remove an arbitrary release for "MC|TrList". In https://github.com/MinecraftForge/MinecraftForge/commit/bf9158172fbb5123cd4eae59a5c65c2ed56ed30c the second patch became misapplied to new closeable of copied buffer. While the former patch was never reinstated leading to the memory leak still persisting.

To resolve this issue the packet buffer release patch would need to be reinstated while the current erroneous patch removed.

**Comment by illesdiana** [comment]
Hi, is this issue actual? I couldn't reproduce the issue. Can you give me more detailed description?
