### ISSUE TITLE
`NullPointerException` Hard Crash from Missing Mod Metadata

### ISSUE THREAD

**Issue by AterAnimAvis** [MinecraftForge/MinecraftForge#7487]
**Minecraft Version:** 1.16.4

**Forge Version:** 35.0.6

**Logs:** [StackTrace](https://gist.github.com/AterAnimAvis/9ca9c091ed0954a47a1d6ee62e623b3d)

**Steps to Reproduce:**
 1. Download MDK.
 2. Change `@Mod("examplemod")` to `@Mod("non_existing")`
 3. Launch Client or Server

**Description of issue:**
- https://github.com/MinecraftForge/MinecraftForge/commit/f78b943bdfde120fd03b69b06d73ada6ade5dca4 has a slight issue with `ModLoader#buildModContainerFromTOML` -> `ErroredModContainer#<init>` -> `ModContainer#<init>`
- In certain cases `ModLoadingException` can have null for `ModLoadingException#getModInfo` (Like at https://github.com/MinecraftForge/MinecraftForge/blob/f78b943bdfde120fd03b69b06d73ada6ade5dca4/src/main/java/net/minecraftforge/fml/ModLoader.java#L294)
- `ErroredModContainer` takes a `ModLoadingException` and calls it super (`ModContainer`) with `MLE`'s ModInfo.
- `ModContainer` calls `IModInfo#getModId` [here](https://github.com/MinecraftForge/MinecraftForge/blob/f78b943bdfde120fd03b69b06d73ada6ade5dca4/src/main/java/net/minecraftforge/fml/ModContainer.java#L68) on the null and causes a `NullPointerException`
- The `NullPointerException` then causes a Hard Crash

**Comment by TheCurle** [comment]
Is this fixed with 0c5ced1bbf91450024436573f16da8177b684c13?

**Comment by AterAnimAvis** [comment]
Fixed with Forge 35.0.17 (https://github.com/MinecraftForge/MinecraftForge/commit/0c5ced1bbf91450024436573f16da8177b684c13)
