### ISSUE TITLE
music off but on

### ISSUE THREAD

**Issue by jarn123** [MinecraftForge/MinecraftForge#7499]
**Minecraft Version:** {Minecraft version} forge 1.12.2-14.23.5.2854

**Forge Version:** {Forge version. *Version number, not latest/rb*}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. turn the music off
 2. 
 3. ...

**Description of issue:**
when you set the music off sometimes you hear the music i experienced this on skyfactory 4.2.2 and on sevtech ages(these have the same forge version)

**Comment by ravenbuilder934** [comment]
1.12 is not supported or updated anymore
