### ISSUE TITLE
[1.15+] No CheckSpawn event outside of WorldEntitySpawner

### ISSUE THREAD

**Issue by HellFirePvP** [MinecraftForge/MinecraftForge#7507]
With many new ways minecraft spawns mobs on regular intervals, such as patrols, phantoms, siege events, (...), Forge's CheckSpawn event should cover those cases to allow for prevention of such spawning behavior without the need of large overrides.

See:
1.15.2 OverworldChunkGenerator#spawnMobs (L156)
1.16.4 instances of ISpecialSpawner

**Comment by TheCurle** [comment]
Closed by #7569
