### ISSUE TITLE
[1.16.2 - 1.16.4] NullPointer breaking/updating multiple blocks at once

### ISSUE THREAD

**Issue by baileyholl** [MinecraftForge/MinecraftForge#7516]
**Minecraft Version:** 1.16.2 - 1.16.4

**Forge Version:** 1.16.4-35.0.22, also encountered in previous 1.16.2 builds. 

**Logs:** 
Crash: https://pastebin.com/qe0TWVJa
Full log: https://gist.github.com/baileyholl/92b9f7d14e860836155f3f97e2cad896

**Steps to Reproduce:**
This has only been reliably reproduced in seemingly random chunks. 99.9% of chunks in the game will not cause a crash with the following:

1) Iterate over a large area of BlockPos
2) Call world.destroyBlock
3) Call world.notifyBlockUpdate, same position, same state, and flag 3.

You can attempt to reproduce it with this item class that I built specifically for this bug:
https://pastebin.com/X1E0djRX

**Description of issue:**
This issue has only been found starting in 1.16 and above, I have found no similar crash in 1.15 using the same code. It cannot be reproduced reliably as to where and why it happens, but when it does, it is exclusively from destroying and updating multiple block states in the same tick. When it *can* be reproduced, it always happens within the same chunk as the original crash. You are unlikely to crash when moving over a chunk, or starting a new world. 

The best way to reproduce it is to fly around the world, spamming the item above until you find a chunk that crashes.

**Comment by Cyborgmas** [comment]
If this is a forge bug, try reproducing without any mods
