### ISSUE TITLE
Removing Datapack Dimensions causes Nether and End Dimensions to be permanently deleted

### ISSUE THREAD

**Issue by 50ap5ud5** [MinecraftForge/MinecraftForge#7526]
**Minecraft Version:** 1.16-1.16.4 (Present in all 1.16.x versions)

**Forge Version:** 1.16.4-35.1.7

**Description of issue:**

The critical vanilla bug, https://bugs.mojang.com/browse/MC-197860 is still present in current versions of Minecraft.

This significantly affects Forge mods more than vanilla because users will be removing and adding new mods that contain dimensions written as a datapack.

I have investigated the cause of the issue and have found the following:

### How the Nether and End Dimensions are Removed

The removal of the nether and end relate to the:
•	Dimension Registration Order
•	Logic used to remove erroring dimensions in SaveFormat#getServerLifecyclePair 

**Dimension Registration Order**

When the Dynamic<T> dynamic = nbt.get("WorldGenSettings").orElseEmptyMap();  in SaveFormat#getServerLifecyclePair is being constructed, the order of dimension registration is as follows:
1.	Overworld
2.	Datapack loaded custom dimensions
3.	Nether
4.	End

**Logic used to remove erroring Dimensions**

Another user who looked into the issue correctly identified that the DimensionGeneratorSettings CODEC (GeneratorOptions.CODEC in Yarn names) will return missing dimensions.

However, that is only half of the story. The Dynamic<T> that is parsed into the DimensionGeneratorSettings CODEC originates from SaveFormat#getServerLifecyclePair.

When the custom dimension is removed, DimensionGeneratorSettings.CODEC fails to fully parse the Dynamic<T>, so the DataResult<DimensionGeneratorSettings> only return the Either#Right part of the result, which only includes the Overworld.

The crucial aspect is the Pair that is returned to the method uses the DataResult#resultOrPartial method, whose PartialResult removes ALL objects AFTER the erroring object, in addition to the erroring object. 
i.e. The data result removes the erroring custom dimension, the Nether and the End, leaving only the Overworld.
 
When these two factors are put into effect, the subsequent ServerWorldInfo, which defines the settings for the World, will use the incorrect data.

### Why the Nether and End Dimensions do not show after reinstating the missing datapack

When the world is loaded after the datapack is reinstated, by this time the Dynamic<T> no longer includes the nether and end in its list of dimensions. Hence, only the Overworld is present alongside the custom dimension.

### Potential Solutions

So far, I have not found a suitable solution. Some ideas I've had are:

- Patching the DataResult<DimensionGeneratorSettings> with a value returned from a method inside ForgeHooks. The method in ForgeHooks could remove only the erroring object, but not other ones like the Nether and End. 
 I'm not sure about the logic that should be used for this, and am not familiar enough yet with Mojang's Serialisation system to come up with the fix.
- Modifying the order of dimension registration so that the Overworld, Nether and End are registered before Datapack dimensions. This would require a larger and more complex patch, which I don't think is optimal.

Feel free to point out corrections, ask questions and discuss this issue. Thank you for your time.

**Comment by alcatrazEscapee** [comment]
I think the best way to solve this would be to patch the `DimensionGeneratorSettings` codec construction such that it uses a modified `UnboundedMapCodec`. This *could've been* a 2-3 line change in DFU, if I'm understanding the issue correctly, and it would be lovely to get it fixed there, but given the low likelihood of that for 1.16, I would rather deal with just bodging a replacement codec in Forge.
