### ISSUE TITLE
No gui in forge documentation

### ISSUE THREAD

**Issue by Robertx999** [MinecraftForge/MinecraftForge#7541]
I dont know if i should report it here but on forge documentation site there is nothing about gui.
In blocks docs( [https://mcforge.readthedocs.io/en/1.15.x/blocks/interaction/#guis](https://mcforge.readthedocs.io/en/1.15.x/blocks/interaction/#guis) ) there is link to gui site( [https://mcforge.readthedocs.io/en/1.15.x/blocks/interaction/GUIs](https://mcforge.readthedocs.io/en/1.15.x/blocks/interaction/GUIs) ) and if i go there it says - page not found.

**Comment by TheCurle** [comment]
This should be in the documentation wiki https://github.com/MinecraftForge/Documentation
