### ISSUE TITLE
Forge server crash

### ISSUE THREAD

**Issue by AlanT59** [MinecraftForge/MinecraftForge#7542]
Hi! I want to play with my firends on something called Ultra-Modded-FunPack, mc version is 1.7.10 modpack itself works pretty flawless, but server has some issues, I've tried reinstall, changing Java (every from 7 to 11), removing some mods, changing forge version and many many others. I hope I just miss something in logs - maybe you will see this. Here are FML Log and MC Server log. Thanks!
[fml-server-latest.log](https://github.com/MinecraftForge/MinecraftForge/files/5665941/fml-server-latest.log)
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/5665942/latest.log)

**Comment by mrp-v2** [comment]
1.7.10 is not supported, update to at least 1.15.2 to receive support.
