### ISSUE TITLE
PlayerInventory.add() behaves differently depending on if the ItemStack isDamaged or not.

### ISSUE THREAD

**Issue by HeavensSword** [MinecraftForge/MinecraftForge#7547]
**Minecraft Version:** {Minecraft version}
1.16.4

**Forge Version:** {Forge version. *Version number, not latest/rb*}
1.16.4-forge-35.1.11

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://gist.github.com/HeavensSword/02d4901fa1827b3ee247c61d85436c6f

**Steps to Reproduce:**
 1.  Attempt to add a piece of Undamaged armor to the appropriate armor slot.
 2. Note that it is properly added and equipped.
 3. Attempt to add a piece of Damaged armor to the appropriate armor slot.
 4. Note that a java.lang.ArrayIndexOutOfBoundsException exception will be thrown.

**Description of issue:**
For Reference: Please note lines 2647 and 2749 in the attached gist log. You'll see two instances of where Netherite Boots are added to the player's inventory at index 36. The first attempt succeeds (undamaged boots), and the second attempt fails (damaged boots).

What I believe is happening, is inside PlayerInventory.add() there is a check whether the incomming stack isDamaged (Line 289) and depending on that the logic branches, but the inventories used differ between implementations.
In the case of damaged stacks, the code is specifically using "mainInventory", while in the case of undamaged stacks if you look at the methods addResource or storePartialItemStack (which calls addResource), then you will notice that addResource calls setInventorySlotContents which utilizes "allInventories". Using allInventories means Armor slots and the offHand slot can be set, meanwhile mainInventory will result in the aforementioned ArrayIndexOutOfBoundsException.

**Expected Behavior**
PlayerInventory.add should utilize allInventories for both If case implementations so that the behavior is consistent regardless of itemStack condition.

**Comment by diesieben07** [comment]
Considering this is a vanilla bug, which is apparently not triggered by vanilla code, I don't think we need to spend the patching effort to fix this. I would advise not using `PlayerInventory` directly, but use the unified capability interface that Forge uses for inventories: `IItemHandler`.
