### ISSUE TITLE
contribution to forge : build failed when I run the setup task

### ISSUE THREAD

**Issue by Romaindu35** [MinecraftForge/MinecraftForge#7550]
**Minecraft Version:** 1.15.2

**Forge Version:** 32.2.47

**Logs:** https://code.alwyn974.re/roqalozoto.js

**Steps to Reproduce:**
 1. Dowload zip in github
 2. Open the project with IDEA
 3. You have the error

**Description of issue:**
I would like to open the gradle project in 1.15.2 but when I run the setup task I have a failed build.

My error : 

PS F:\ROMAIN\Developpement\Minecraft\Forge\MinecraftForge-1.15.x> .\gradlew setup

> Configure project :
Java: 1.8.0_211 JVM: 25.211-b12

FAILURE: Build failed with an exception.

* Where:
Build file 'F:\ROMAIN\Developpement\Minecraft\Forge\MinecraftForge-1.15.x\build.gradle' line: 220

* What went wrong:
A problem occurred evaluating root project 'Forge'.
> Cannot invoke method describe() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
PS F:\ROMAIN\Developpement\Minecraft\Forge\MinecraftForge-1.15.x>

**Comment by DaemonUmbra** [comment]
You need to clone the repo using git, downloading the zip doesn't work as Forge uses git to generate its version number
