### ISSUE TITLE
MC-181464 issue persists if modded shields are picked up by Piglins

### ISSUE THREAD

**Issue by Thelnfamous1** [MinecraftForge/MinecraftForge#7553]
**Minecraft Version:** Any 1.16.x version will do.

**Forge Version:** Forge 32 and up.

**Logs:** No log since this does not crash the game, or won't be given specifically as the reason for the crash.

**Steps to Reproduce:**
 1. Drop a modded Shield near a Piglin (the vanilla shield does not cause this issue)
 2. Allow the Piglin to pick it up
 3. The gear equip sound will be infinitely played in the game, without ever stopping.

**Description of issue:**
StartAdmiringItemTask is the AI task responsible for handling when a Piglin has an item in its offhand and has no admiring item memory (either because it already finished admiring the item, or it never was admiring it in the first place). When determined to be able to execute, a method in PiglinTasks is called to, among many things, put the offhand item in a suitable equipment slot if it is an equippable item. 

Prior to 20w22a, since the offhand slot is determined to be the "correct" slot for a shield, it would be re-equipped to the offhand (thus playing the equip sound) and then StartAdmiringItemTask would reset (since it does not continue to execute) and start again repeatedly as there is still an item in the offhand and there is no admiring item memory present. 

Due to StartAdmiringItemTask now running a check to ensure that the offhand item is not "Items.SHIELD" before executing, Mojang was able to fix [MC-181464](https://bugs.mojang.com/browse/MC-181464). However, this means that if a Piglin picks up a modded shield, it will loop equipping it forever, thus allowing the bug to persist in a modded environment. 

This is a one-line fix so in my opinion, it's not necessary to make a PR for it.

My proposed change to StartAdmiringItemTask:

```java
protected boolean shouldExecute(ServerWorld p_212832_1_, E p_212832_2_) {
        return !p_212832_2_.getHeldItemOffhand().isEmpty() && p_212832_2_.getHeldItemOffhand().getItem() != Items.SHIELD;
    }
```

to:

```java
protected boolean shouldExecute(ServerWorld p_212832_1_, E p_212832_2_) {
        return !p_212832_2_.getHeldItemOffhand().isEmpty() && !p_212832_2_.getHeldItemOffhand().isShield(p_212832_2_);
    }
```

**Comment by pupnewfster** [comment]
It still would probably be helpful to make a PR, given otherwise it will have to wait for someone else to go ahead and make a PR. Also I believe it would be `!p_212832_2_.getHeldItemOffhand().isShield(p_212832_2_.getHeldItemOffhand())`. Given I have modded shields I probably will make a PR when I have time in a week or two if no one else has by then so people don't run into this while using them.

The one question I have is in a modded context would it make more sense to instead add another method that people can override that just defaults to isShield's result so that if people have some other item that is used in the offhand that they can disable piglins from improperly "spamming" it.

**Comment by Thelnfamous1** [comment]
I chose IForgeItemStack’s isShield(LivingEntity entity) because LivingEntity#getHeldItemOffhand returns an ItemStack that can call it and provide itself as the stack argument to the subsequent call to IForgeItem’s isShield(ItemStack stack, LivingEntity entity).

Perhaps it would be suitable to patch StartAdmiringItemTask with a method called something like doesNotTriggerAdmire (not the best name, but then again StartAdmiringItemTask is not the correct name for this AI Task) that allows modders to have more control of this behavior.

**Comment by LexManos** [comment]
What is the logic that makes it move to the offhand? Would it be better to just use that as the check instead? As it sounds like this is a issue for any of those items. Or is there no check for the admire task that makes sure the offhand is empty?

But yes the quick fix would be to convert it to a isShield call.

**Comment by Thelnfamous1** [comment]
Here's my interpretation of PiglinTasks#func_234477_a_ which gets called when StartAdmiringItemTask starts executing:

```java
protected static void stopAdmiringItem(PiglinEntity piglinEntity, boolean doBarter) {
      ItemStack offhandStack = piglinEntity.getHeldItem(Hand.OFF_HAND);
      piglinEntity.setHeldItem(Hand.OFF_HAND, ItemStack.EMPTY);
      if (piglinEntity.isAdult()) {
         boolean isPiglinCurrency = itemstack.isPiglinCurrency();
         if (doBarter && isPiglinCurrency) {
            dropItemStacks(piglinEntity, getBarteringLoot(piglinEntity));
         } else if (!isPiglinCurrency) {
            boolean didEquipItem = piglinEntity.equipItem(offhandStack);
            if (!didEquipItem) {
               addItemStackToInventoryDropRemainder(piglinEntity, offhandStack);
            }
         }
      } else {
         boolean didEquipItem = piglinEntity.equipItem(offhandStack);
         if (!didEquipItem) {
            ItemStack mainhandStack = piglinEntity.getHeldItemMainhand();
            if (isPiglinLoved(mainhandStack.getItem())) {
               addItemStackToInventoryDropRemainder(piglinEntity, mainhandStack);
            } else {
               dropItemStacks(piglinEntity, Collections.singletonList(mainhandStack));
            }

            piglinEntity.setItemStackToMainhandAndPersist(offhandStack);
         }
      }

   }
 ```
   
The method of note here is MobEntity#func_233665_g_ (listed above as **equipItem**), which gets called for adult Piglins if the item is not piglin currency and immediately for baby Piglins. A shield, obviously, will cause MobEntity#func_233665_g_ to be called in PiglinTasks#func_234477_a.
 
 Here is my interpretation of MobEntity#func_233665_g_:
   
```java
 public boolean equipItem(ItemStack stackToEquip) {
      EquipmentSlotType equipmentslottype = getSlotForItemStack(stackToEquip);
      ItemStack stackInSlot = this.getItemStackFromSlot(equipmentslottype);
      boolean shouldExchangeEquipment = this.shouldExchangeEquipment(stackToEquip, stackInSlot);
      if (shouldExchangeEquipment && this.canEquipItem(stackToEquip)) {
         double slotDropChance = (double)this.getDropChance(equipmentslottype);
         if (!stackInSlot.isEmpty() && (double)Math.max(this.rand.nextFloat() - 0.1F, 0.0F) < slotDropChance) {
            this.entityDropItem(stackInSlot);
         }

         this.equipItemAndPersist(equipmentslottype, stackToEquip);
         this.playEquipSound(stackToEquip);
         return true;
      } else {
         return false;
      }
}
```

And the cause of this entire predicament is MobEntity#getSlotForItemStack

```java
public static EquipmentSlotType getSlotForItemStack(ItemStack stack) {
      final EquipmentSlotType slot = stack.getEquipmentSlot();
      if (slot != null) return slot; // FORGE: Allow modders to set a non-default equipment slot for a stack; e.g. a non-armor chestplate-slot item
      Item item = stack.getItem();
      if (item != Blocks.CARVED_PUMPKIN.asItem() && (!(item instanceof BlockItem) || !(((BlockItem)item).getBlock() instanceof AbstractSkullBlock))) {
         if (item instanceof ArmorItem) {
            return ((ArmorItem)item).getEquipmentSlot();
         } else if (item == Items.ELYTRA) {
            return EquipmentSlotType.CHEST;
         } else {
            return stack.isShield(null) ? EquipmentSlotType.OFFHAND : EquipmentSlotType.MAINHAND;
         }
      } else {
         return EquipmentSlotType.HEAD;
      }
   }
```

As you can see, the "correct" slot for a shield is the offhand. And the shield being re-equipped to the offhand during the PiglinTasks function causes the sound loop part of the bug, while the continued presence of an item in the offhand that is not the vanilla shield causes the AI task to effectively loop.
