### ISSUE TITLE
Potential memory savings in vanilla - which ones might be acceptable in Forge?

### ISSUE THREAD

**Issue by malte0811** [MinecraftForge/MinecraftForge#7559]
I've made a [list](https://gist.github.com/malte0811/5746a8289962d1f67a61d21a7521a3b0) of the potential memory usage improvements I mentioned a few days ago, including estimates for patch size, CPU impact and (obviously) memory saved in a realistic instance. Are there any changes on this list that, just from the "abstract", would not be acceptable for Forge, whether it is due to general patch size, maintenance overhead, CPU impact or some other reason?  Note: I am **not** asking for a guarantee that the others will be accepted when they are fully fleshed out as PRs. But I also don't want to spend a day making a PR only to be told that "just from the PR description this is not acceptable".

Another topic that came up in this discussion was using Mixins in Forge. It didn't really become clear to me how soon that might become reality, and whether I should be targetting a clean Mixin implementation of these changes or patches. Can you make any comment on that?

I'm turning this into a GH issue because this sort of question tends to get lost on Discord, especially across time zones.

**Comment by TheCurle** [comment]
Personally, i'd like to see an implementation of 1 and 2. 
3's problems can be alleviated with AccessTransformer.
4 is too invasive to be worth it, in my eyes.

**Comment by malte0811** [comment]
> 3's problems can be alleviated with AccessTransformer.

I don't see how? `ImmutableMap` is in guava, and AFAIK ATs can't be applied to "basic" libraries. I'm not even sure if they can be applied to Forge, IIRC I've only used them for vanilla fields/methods so far.

**Comment by TheCurle** [comment]
Ahuh, i misunderstood:
> can't be easily extended due to package-private methods

as meaning there are package-private methods in the class in question that interact with the maps before finalizing them to immutability, like a Builder.

My bad.

**Comment by LexManos** [comment]
This has been discussed with cpw, and the merits and justifications of some of them are dubious. But i've left it up to him to decide if we want to implement these. It seems that he hasn't decided what to do with this. I've pinged him with this in discord. And brought the triage team up to speed.

**Comment by malte0811** [comment]
> and the merits and justifications of some of them are dubious.

Any chance of something more specific than that? All of it is based on practical results, but it's very possible that I either explained it badly or that we have different "thresholds" for what optimizations are worth what amount of effort.

**Comment by cpw** [comment]
OK. Lex wanted me to chime in here. Some of these are very high complexity for moderate (at best) gains. If we could get the simpler ones in, then that would be useful. But e.g. 4 is pretty complex and as such, might be challenging to maintain at present, esp with 1.17 looming.

Which ones would you be willing to create PRs for?

**Comment by malte0811** [comment]
I'm willing to create PRs for any subset (proper or non-proper) of the points in the gist. I can't give any guarantees on how quickly I'll be able to a) get them done and b) react to comments on them though, I have a live outside of modding :)  
One question that needs to be answered before I start making PRs is whether they should use Mixins vs patches. I believe you (@cpw) were the one who bought up that topic when this was discussed in FC 4 months ago? At that point using Mixins in Forge wasn't possible yet (IIRC), has that changed?

Another point: I've found more possible optimizations since I opened the issue. Most of them are probably not appropriate for Forge, but the first part of [this one](https://github.com/malte0811/FerriteCore/blob/60a4a0674c600a6a3abe2c3c88dd71da55dd100b/summary.md#5-string-instance-reduction-in-modelresourcelocation) might be something for Forge?

**Comment by malte0811** [comment]
I am no longer interested in contributing to Forge-owned projects, for multiple reasons, primarily the behavior of @LexManos. My implementation of these changes is MIT-licensed (in FerriteCore), but I explicitly do **not** approve of them being PRd to Forge by someone else.

**Comment by LexManos** [comment]
Due to personal issues with malte's style of development and community interaction. I decided to opt out of personally managing this and instead left my analysis of these changes in our team's private discussions. I left it to cpw to follow up with anything he wished to. However, It seems that malte and cpw never got to a consensus on what was actually worth pulling. A lot of factors could of lead to this, not the least of which being non-minecraft related issues that have arose in both cpw and my life. As well as this being very minor, unverified, 'fixes'.  The only real one that doesn't have unknown potential side effects is the optional tweak. Which is so minor it isn't worth the drama of just taking that one without the rest.
