### ISSUE TITLE
IForgeEntity#canBeRiddenInWater doesn't return Entity#canBeRiddenInWater

### ISSUE THREAD

**Issue by Chumbanotz** [MinecraftForge/MinecraftForge#7567]
**Minecraft Version:** 1.16.4

**Forge Version:** 35.1.13

**Description of issue:**
https://github.com/MinecraftForge/MinecraftForge/blob/2d9a1bc6f9d92d54cf5dc17cd3f390c722b428e2/src/main/java/net/minecraftforge/common/extensions/IForgeEntity.java#L141
IForgeEntity#canBeRiddenInWater permits any LivingEntity to continue to ride another entity while it's underwater. The default vanilla method is Entity#canBeRiddenInWater which LivingEntity overrides to false. The IForgeEntity#canBeRiddenInWater method should return the vanilla method, like so:
```java
default boolean canBeRiddenInWater(Entity rider)
{
    return getEntity().canBeRiddenInWater();
}
```

**Comment by diesieben07** [comment]
This was just fixed: https://github.com/MinecraftForge/MinecraftForge/commit/b6a92748708b4c336e5b6d062f8b8a257f022acd
