### ISSUE TITLE
Datapackcrash when joining world for the 3rd time in the same session.

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#7568]
**Minecraft Version:** 1.16.4

**Forge Version:** 35.1.7

**Logs:** https://hastebin.com/itiqapagav.properties

**Steps to Reproduce:**
 1. start the game
 2. join a world (can be a super flat world)
 3. exit the world
 4. do this 3 times and suddenly the datapack breaks.

**Description of issue:**
The logs indicate there are too many Tags with the same name.

**Comment by mcenderdragon** [comment]
Create the following setup:
"data.forge.tags.items.ores.bauxite" which can be empty.

And then reference the tag with "forge:ores/bauxit" (so e is missing)

**Comment by diesieben07** [comment]
Steps to reproduce are not complete, no datapack or code given that reproduces it.

**Comment by mcenderdragon** [comment]
After more investigation this was my own fault. For anyone having the same issue:
I used ItemTags.getOptionalTag(ResourceLocation) of "forge:ores/silver", "forge:ores/nickel", "forge:ores/iridium" and did not create these tags. The code crashes because all of these tag are bound to the same Tag.emptyTag() instance.
