### ISSUE TITLE
Having a screen shader applied removes texturing on the hotbar

### ISSUE THREAD

**Issue by Vazkii** [MinecraftForge/MinecraftForge#7575]
**Minecraft Version:** 1.16.4

**Forge Version:** 35.1.28

**Logs:** https://pastebin.com/96eMAMrx

**Steps to Reproduce:**
 1. Go to spectator mode
 2. Left click a creeper or enderman
 3. Press the number keys to open up the hotbar

**Description of issue:**
When a screen shader is applied, texturing on the hotbar is removed. I noticed this when adding a colorblind filter option, but it can be seen with vanilla by using the shaders provided by possessing a creeper or enderman in spectator mode.

![2020-12-30_08 05 29](https://user-images.githubusercontent.com/1794735/103338389-31617900-4a76-11eb-9ed3-e7a0c596c048.png)

**Comment by XFactHD** [comment]
This is a vanilla bug. If a screen shader is active, the textures are not reenabled causing the HUD to draw as white boxes. AFAIK this has not been reported to Mojang yet.
You can fix this from your mod by calling `RenderSystem.enableTextures()` in `RenderGameOverlayEvent.Pre` with `ElementType.ALL`.

**Comment by pupnewfster** [comment]
https://bugs.mojang.com/browse/MC-194675
