### ISSUE TITLE
Implementation of areItemsEqualIgnoreDurability is redundant

### ISSUE THREAD

**Issue by uecasm** [MinecraftForge/MinecraftForge#7577]
**Minecraft Version:** 1.16.4
**Forge Version:** 35.1.13

**Description of issue:**

(It's possible this is actually an issue in the underlying Minecraft code.  I'm not sure which parts are patched in by Forge and which parts are original.)

`ItemStack.isItemEqualIgnoreDurability` looks like it's doing something different from `ItemStack.isItemEqual`, but actually it isn't.  The two have absolutely identical results, just that the former has more long-winded code.  Neither one compares durability, since that's part of the tags now.  The same applies to `ItemStack.areItemsEqual`/`ItemStack.areItemsEqualIgnoreDurability`.

On a related note, `ItemStack.areItemStackTagsEqual` *does* compare durability and there's no way to make it ignore that.  That seems like it would be a useful addition.

**Comment by covers1624** [comment]
All of the methods you have mentioned are not added by Forge and are base Vanilla methods, as you can see [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/patches/minecraft/net/minecraft/item/ItemStack.java.patch). This is likely a left over artifact from metadata removal.
