### ISSUE TITLE
[Request] A chicken jockey event

### ISSUE THREAD

**Issue by Markus1002** [MinecraftForge/MinecraftForge#7583]
Currently it is not possible to reliably replace the mount of a chicken jockey when one spawns. In code it is impossible to tell if a zombie is riding a newly spawned chicken or an already existing chicken. If I wanted to, for example, replace the chicken with a biome-specific variant and the chicken that the zombie is riding is an already existing chicken, the chicken would be turned into another mob. This is why there should be an event that is fired after the game decides that a zombie is going to be a jockey and before a chicken is spawned. There should also be an event for when the game checks for surrounding chickens for the zombie to mount.

**Comment by diesieben07** [comment]
I am not sure I fully follow you - why is EntityMountEvent not enough?

**Comment by Markus1002** [comment]
Sometimes baby zombies mount existing chickens instead of creating a new one. If a zombie mounted an existing chicken and I replaced the chicken with another mob, the previously existing chicken would be removed.

**Comment by BlueAgent** [comment]
Maybe you can check the ticksExisted of the chicken?
If the chicken is too old then you can avoid replacing it (since you know it's an existing chicken being mounted and not a new one).

**Comment by Markus1002** [comment]
ticksExisted resets every time you open the world.

**Comment by diesieben07** [comment]
> ticksExisted resets every time you open the world.

Correct but the chance that a chicken and a zombie load (instead of spawn), the zombie is a baby zombie, they are next to each other and the zombie decides to mount the chicken all in the exact same tick is very, _very_ low.

**Comment by BlueAgent** [comment]
Found an opportunity to take a closer look.

The chicken that gets generated with the zombie and mounted is added to the world after it mounts the chicken.
So you could add an additional check to see if chicken is not currently in the world.
This may break in future versions if it is changed so that the chicken is added to the world before the zombie mounts it though.

**Comment by diesieben07** [comment]
Closing this as multiple ways for detection using existing events have been given.
