### ISSUE TITLE
Rename Forge registries for effects and potions

### ISSUE THREAD

**Issue by sciwhiz12** [MinecraftForge/MinecraftForge#7600]
Currently, the forge registries for `Effect`s and `Potion`s are named `POTIONS` and `POTION_TYPES`, respectively.
These names are confusing for people who are searching for these two registries, as `POTIONS` will lead them to think it's for the `Potion` class, and then be confused when seeing `POTION_TYPES`.

I propose in 1.17 that these two registries be renamed to `EFFECTS` and `POTIONS` respectively. This follows the 'standard' naming of the other forge registries (namely, being named after their respective registry type), and clears up confusion between the two registries.

**Comment by kreezxil** [comment]
With the unforeseen release of 1.16.5, would it be prudent to expect this change to occur somewhere within the 1.16.5 branch?

**Comment by sciwhiz12** [comment]
If my knowledge of Forge policy is correct, 1.16.5 will not allow any breaking changes, to allow mods from older minor 1.16.x versions to run without breakage (since 1.16.5 itself is a very minor code change, unlike major versions or 1.16.2). In effect, 1.16.5 is considered to already 'have' a recommended build from its first build. Therefore, this change will occur in 1.17.

**Comment by kreezxil** [comment]
ok, thanks for that information.

**Comment by TheCurle** [comment]
This has been implemented in 37.0.22
