### ISSUE TITLE
Inconsistent nullability of position for dig speed checks

### ISSUE THREAD

**Issue by malte0811** [MinecraftForge/MinecraftForge#7615]
**Minecraft Version:** 1.16.5

**Forge Version:** Code is present in 19f8d2a7937dc7968ecbef2f9785687193fcd210

**Description of issue:**
The position for the dig speed check is `@Nullable` here:
https://github.com/MinecraftForge/MinecraftForge/blob/19f8d2a7937dc7968ecbef2f9785687193fcd210/patches/minecraft/net/minecraft/entity/player/PlayerEntity.java.patch#L100-L108

`getBreakSpeed` passes the (potentially `null`) position directly to the `BreakSpeed` event, which does not mark the position as `@Nullable` and instead specifies y=-1 for unknown locations
https://github.com/MinecraftForge/MinecraftForge/blob/19f8d2a7937dc7968ecbef2f9785687193fcd210/src/main/java/net/minecraftforge/event/entity/player/PlayerEvent.java#L106
`getBreakSpeed` should either replace `null` positions with something like `(0, -1, 0)` or the annotation and Javadoc on the event should be updated.

See also BluSunrize/ImmersiveEngineering#4587. @desht suggested that this might be something to put in #7612. @TheCurle, what do you think about that?

**Comment by TheCurle** [comment]
I'll put this on the list for things to look over in my javadoc passthroughs.
Unless you get there first and make a PR to the omnibus, that is. :)
