### ISSUE TITLE
EntityType.loadEntityUnchecked can't be used for some vanilla mobs on the client

### ISSUE THREAD

**Issue by stepsword** [MinecraftForge/MinecraftForge#7619]
This is more of a vanilla issue, but basically Iron Golems, Wolves, Endermen, Polar Bears, Bees, and Zombie Pigmen can't be read from NBT on the client-side. 

In their `readAdditional` method they all do an unchecked cast `this.readAngerNBT((ServerWorld)this.world, compound);`, which, naturally, crashes on the client. 

AbstractSpawner uses this method 

`this.cachedEntity = EntityType.loadEntityAndExecute(this.spawnData.getNbt(), this.getWorld(), Function.identity());`

on the client side, and as a result can't actually render any of these entities. Would it be possible to put in an `instanceof ServerWorld` check on their read methods? It's understandable if not since it's technically a vanilla bug but it also prevents any mod makers, like myself, from reading generic entities from NBT without a try catch around it.

**Comment by TheCurle** [comment]
Closed by #7618
