### ISSUE TITLE
Mods List View Crash

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#7627]
**Minecraft Version:** `1.16.5`

**Forge Version:** `36.0.1`

_P.S. This same crash also occurs in Forge version _`35.1.37`_._

**Logs:**
[Latest.log](https://pastebin.com/BDErF5wF) (Apologies for initially cut-off paste, it's now fixed)
[Crash Report](https://hatebin.com/tohndaczkl)

**Description of issue:**
Attempting to view certain mods in the in-game mods list causes an immediate crash. I'm not an FML expert, but according to MORIMORI0317/GameMenuModOption#6 this may be due to missing info in `mods.toml`?

**Steps to Reproduce:**
 1. Install a mod like [Classic Combat](https://www.curseforge.com/minecraft/mc-mods/classic-combat).
 2. Start the game and enter the mods list from the main menu.
 3. Click on Classic Combat's entry in the list.
 4. Crash.

**Comment by ChampionAsh5357** [comment]
This is a bug with classic combat and not related to forge. It's trying to grab a nonexistent logo causing the exception to be thrown. Since this is an optional parameter, it can be commented out fixing the issue.

**Comment by LexManos** [comment]
An empty string is not a valid path. Thus the error.
If you don't want a logo, don't specify one.

**Comment by ghost** [comment]
Ah, thank you guys. Sorry for the non-issue!
