### ISSUE TITLE
Problem while trying to start Forge with Gradle

### ISSUE THREAD

**Issue by DxsSucuk** [MinecraftForge/MinecraftForge#7634]
MC Version: 1.16.5
Forge Version: 36.0.10

Log:
`Exception in thread "main" java.lang.NullPointerException
	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:33)
	at net.minecraft.client.main.Main.main(Main.java:123)
	at mcp.client.Start.main(Start.java:17)`
	
Steps:
I use Gradle to set everything up after that i used the Task setup.
After MCP was setuped i create a Run configuration with the Main Class mcp.client.Start and the Module Forge.forge.main.
If i try running it in debug or normal i always get this error!

**Comment by TheCurle** [comment]
MCP isn't supported. Use a proper mod loader.
