### ISSUE TITLE
Invalid patcher dependency

### ISSUE THREAD

**Issue by Coder-exn** [MinecraftForge/MinecraftForge#7637]
**Minecraft Version:** 1.12.2

**Forge Version:** 14.23.5.2854

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Go to the project directory (MDK)
 2. Run "gradlew build"
 3. Wait for the result

**Description of issue:**
When the "gradlew build" command is finished, it says:
---------------------------------------------------------------------------
22:07:37: Executing task 'build'...

> Configure project :
New Dep: net.minecraftforge:forge:1.12.2-14.23.5.2854_mapped_snapshot_20171003-1.12

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'testmod'.
> Invalid patcher dependency: net.minecraftforge:forge:1.12.2-14.23.5.2854:userdev3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
22:07:46: Task execution finished 'build'.
---------------------------------------------------------------------------
I've tried for many times, but it still hasn't been fixed.
My IDE shows (IntelliJ IDEA): 
![image](https://user-images.githubusercontent.com/76833453/106613176-e078ff00-65a4-11eb-9d1a-7e765d85fac3.png)

**Comment by ravenbuilder934** [comment]
(1.12 is not supported any more)

**Comment by Johan2403** [comment]
I think the userdev artifact was removed from the Forge maven
