### ISSUE TITLE
GLFW Error Apple Sillicon  M1

### ISSUE THREAD

**Issue by teteou** [MinecraftForge/MinecraftForge#7647]
**Minecraft Version:** { 1.16.5 }

**Forge Version:** { 36.0.14 }

**Logs:** [{ GLFW ERROR }](https://gist.github.com/teteou/05aaa964bd5a957bdd580f81e065e5ab.js)

**Steps to Reproduce:**
1. Just install the Forge.
2. As soon as you run it, you get the error

**Comment by TheCurle** [comment]
#7558
