### ISSUE TITLE
When changing the mod id, compiled mod jar will contain duplicate files

### ISSUE THREAD

**Issue by HendrikH01** [MinecraftForge/MinecraftForge#7656]
**Minecraft Version:** 1.15.2
**Forge Version:** 1.15.2-31.1.0

I changed the mod id of my mod halfway through the development process and I noticed that when I compiled it there were duplicate files. All the assets, data and source folders existed twice, once with the old and once with the new modid. Fixing this was very simple, I just deleted the folders with the old modid in build/resources/main and build/classes/etc.
Im not sure whether this is intended or not but to me it feels like a bug

**Comment by LexManos** [comment]
Yes, if you don't delete your old files your IDE/Whatever tool you use will not do it for you.
