### ISSUE TITLE
ScriptEngineManager breaks on Java8

### ISSUE THREAD

**Issue by IzzelAliz** [MinecraftForge/MinecraftForge#7662]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.0.14

**Logs:** https://paste.ubuntu.com/p/PQMQbcJs3c/

**Steps to Reproduce:**
 1. Have a mod with these code:
```java
@Mod("examplemod")
public class ExampleMod {
    public ExampleMod() {
    	new javax.script.ScriptEngineManager();
    }
}
```
 2. Start and wait for crash

**Description of issue:**

https://github.com/LexManos/NashornLegacyPackager has a class compiled against Java 9 in classpath.

**Comment by sciwhiz12** [comment]
This seems to be related to https://github.com/LexManos/NashornLegacyPackager/pull/1.
