### ISSUE TITLE
Teleport Command Args when using permissions API

### ISSUE THREAD

**Issue by WillPierson1** [MinecraftForge/MinecraftForge#7673]
**Minecraft Version:** 1.16.4

**Forge Version:** 1.16.4

**Steps to Reproduce:**
 1. Install Thutperms on a forge server
 2. Allow players teleport command
 3. See that arguments with the @ selector don't autocomplete and they can't be used by non-ops

**Description of issue:** 

Players with an op level of less than 2 can't use **some** args of a command they're not supposed to have (but do have due to a mod) including @a @s etc

See conversations between me and the mod creator

![image](https://user-images.githubusercontent.com/80073866/110040840-522aa100-7d3b-11eb-8533-a28c61c55e9c.png)

**Comment by TheCurle** [comment]
We plan to redo the permissions API in a much more extensive fashion. For now, this is a side effect of the zombie-like state the current API is in.

Hold for updates.

**Comment by WillPierson1** [comment]
Hi, would there be any temporary workarounds we could implement here? Ideally I'd like to have this as soon as possible for my server.

Thanks for your time,
Will.

**Comment by TheCurle** [comment]
Short of temporarily rewriting most of Minecraft, unfortunately no.
