### ISSUE TITLE
Wrong obfuscation for lambda-metafactory call in `LoadingErrorScreen`

### ISSUE THREAD

**Issue by diesieben07** [MinecraftForge/MinecraftForge#7679]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.0.48 

**Logs:** https://gist.github.com/diesieben07/77585d368194c66dab4074b90020905c

**Steps to Reproduce:**
 1. Provoke `LoadingErrorScreen` to appear by e.g. installing a mod without its dependencies.
 2. Observe the game crashing.

**Description of issue:**
This [lambda](https://github.com/MinecraftForge/MinecraftForge/blob/a95b968c1397a1597d4a6228d8e1abce6495570e/src/main/java/net/minecraftforge/fml/client/gui/screen/LoadingErrorScreen.java#L83) (implementing `IPressable`) becomes `lambda$init$1` in the final jar file (as in the one that the installer produces).
However the lambda-metafactory call references it as `func_213034_a`, which is a synthetic lambda method (with the same signature) from the superclass `ErrorScreen`.

**Comment by ichttt** [comment]
Maybe related to https://github.com/md-5/SpecialSource/issues/60 ?

**Comment by LexManos** [comment]
Well this is annoying, thought I tested this obf case.
But ya it seems to be. There is a pending fix for it https://github.com/md-5/SpecialSource/pull/61
I've poked md5 about it. We're just waiting on a upstream release and then we can move on.

**Comment by pupnewfster** [comment]
Should be fixed as of https://github.com/MinecraftForge/MinecraftForge/commit/0ad8e2c27f87d62dbc499714c1b7f2af8918013e

**Comment by SquidDev** [comment]
I realise not strictly speaking relevant to this issue, but would it be possible to have a bump of SpecialSource in FG too? Obviously modders can override the tool version, but this is likely to bite people who switch over to official mappings.

**Comment by pupnewfster** [comment]
> I realise not strictly speaking relevant to this issue, but would it be possible to have a bump of SpecialSource in FG too? Obviously modders can override the tool version, but this is likely to bite people who switch over to official mappings.

https://github.com/MinecraftForge/ForgeGradle/commit/314f40864a2c8c24333af7cf89cd72f53f35f0ff
