### ISSUE TITLE
Load jars from folder

### ISSUE THREAD

**Issue by svdgoor** [MinecraftForge/MinecraftForge#7681]
As I am currently regularly switching between Forge 1.8.9 and Forge 1.16.5,
I have come to experience issues with how each version loads mods.

The 1.8.9 version nicely loads mods from `.minecraft/mods/1.8.9/*`, and also from the main `.minecraft/mods/*` folder. 
The 1.16.5 version, on the other hand, only loads from `.minecraft/mods`.
This means that I have to move the mods I want to use for 1.16.5 out of the way when loading 1.8.9 and back in once I need to continue using 1.16.5. I would love if the 1.16.5 version would also load from `.minecraft/mods/1.16.5/*`, so I would not have to go through the trouble of moving them each time.

I'm currently in the middle of developing a plugin and also going to uni, which is why I make a feature request here instead of a PR or PR Draft, apologies if that is not the way of things here.

Would love to see this implemented.

**Comment by TheCurle** [comment]
This was deprecated in favor of the vanilla launcher's Installations feature. We do not intend to readd it.

**Comment by TheCurle** [comment]
To further that, the launcher's implementation is way more stable than what we could add. It also separates saves, configs, resource packs... creating a proper separation, and removing all need to manually manage those.

**Comment by svdgoor** [comment]
Thank you for the quick reply. I didn't realise this was already accommodated for. Have a good one!

EDIT: I managed to make it work very easily, you were totally right. Good choice on your end!
