### ISSUE TITLE
Classloading in Finalizer causes NPE

### ISSUE THREAD

**Issue by RogueLogix** [MinecraftForge/MinecraftForge#7683]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.0.1

**StackTrace:** https://gist.github.com/RogueLogix/f53aa163ac0ee2ecc7ae8ba3ef256186

**Steps to Reproduce:**
 1. Cause classloading from finalzier thread
 
**Description of issue:**
Triggering classloading form the finalizer thread will cause EventSubclassTransformer produces an NPE in the log
Thread.currentThread().getContextClassLoader() on line 62 returns null for this thread.

**Comment by diesieben07** [comment]
Yes, this is a bug. But please stop using finalizers. Use `PhantomReference`s and a reference queue.

**Comment by LexManos** [comment]
[In theory this has been addressed in EventBus](https://github.com/MinecraftForge/MinecraftForge/commit/37330058396d46481fd4aa4115dbde468be0611b)

**Comment by RogueLogix** [comment]
Yes, this was fixed.
