### ISSUE TITLE
Getting creatures mobs to spawn on custom blocks is difficult to do with mod compatibility in mind

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#7685]
In EntitySpawnPlacementRegistry, several vanilla mobs will register AnimalEntity's canAnimalSpawn method as their predicate for spawning. The issue is, this method is specifically hardcoded to vanilla's grass block:
`return worldIn.getBlockState(pos.down()).isIn(Blocks.GRASS_BLOCK) && worldIn.getLightSubtracted(pos, 0) > 8;` 

Furthermore, in WorldEntitySpawner's func_234966_a_ method (used for spawning mobs every tick), it calls func_234975_a_ which checks the registered spawn placement but does it before Forge's canEntitySpawn event can fire. Thus rendering the canEntitySpawn event useless to bypassing this hardcoded grass block check. 

The only workaround at the moment is to try gathering all creature mobs, get their spawn predicate, wrap it in your own that checks for your block and defers to the original behavior if your condition is false, and register that new spawn predicate to that mob. The issue is, other mods may also use this method for their mobs which may not always be a creature category. And checking if the original spawn is using canAnimalSpawn will be impossible to do if multiple mods wraps the predicate. 

A solution offers by someone was to replace canAnimalSpawn's `.isIn(Blocks.GRASS_BLOCK)` with a block tag for allowing mobs using that method to spawn on custom blocks in a more mod compatible way. `forge:creatures_can_spawn_on` or something along those lines might work as a name. Thoughts?

**Comment by TheCurle** [comment]
I have a slight issue with using a tag for this, because there's no granularity, but there it is. #7744
