### ISSUE TITLE
Campfire IRecipe usage differs from Furnace, Smoker and BlastFurnace

### ISSUE THREAD

**Issue by queekusme** [MinecraftForge/MinecraftForge#7689]
**Minecraft Version:** 1.16.5
**Forge Version:** 36.0.58

**Logs:** N/A

**Steps to Reproduce:**

Add the following into accesstransformer.cfg, this is not specific to the bug but required for the below code example to work
```
public net.minecraft.item.crafting.CookingRecipeSerializer$IFactory
```

Register custom recipes for the cooking based blocks (Campfire and Smoker shown but this also happens for furnace and blast furnace)
```
public static final DeferredRegister<IRecipeSerializer<?>> RECIPE_SERIALIZERS = DeferredRegister.create(ForgeRegistries.RECIPE_SERIALIZERS, "MOD_ID_HERE");

public static final RegistryObject<CookingRecipeSerializer<?>> SMOKER_TRANSFER_NBT
    = RECIPE_SERIALIZERS.register("smoker_transfer_nbt", () -> new CookingRecipeSerializer<>(TransferNBTSmokerRecipe::new, 100));
public static final RegistryObject<CookingRecipeSerializer<?>> CAMPFIRE_COOKING_TRANSFER_NBT
    = RECIPE_SERIALIZERS.register("campfire_cooking_transfer_nbt", () -> new CookingRecipeSerializer<>(TransferNBTCampfireRecipe::new, 100));

// Within mod construction method
RECIPE_SERIALIZERS.register(FMLJavaModLoadingContext.get().getModEventBus());
```

Example Campfire Class (Works in allowing editing of item before player recieves item)
```
public class TransferNBTCampfireRecipe extends CampfireCookingRecipe
{
    // Constructer ommitted for compactness

    @Override
    public ItemStack assemble(IInventory craftingInv)
    {
        ItemStack result = super.assemble(craftingInv);

        // Do something with output stack before returning to player

        return result;
    }
}
```

Example Smoker Class (Does not work as getResultItem is used instead)
```
public class TransferNBTSmokerRecipe extends SmokingRecipe
{
    // Constructer ommitted for compactness

    @Override
    public ItemStack assemble(IInventory craftingInv)
    {
        ItemStack result = super.assemble(craftingInv);

        // Do something with output stack before returning to player

        return result;
    }
}
```

Custom smoker recipe for testing
```
{
  "type": "MOD_ID_HERE:smoker_transfer_nbt",
  "ingredient": {
    "item": "minecraft:stick"
  },
  "result": "minecraft:blaze_rod",
  "experience": 0.35,
  "cookingtime": 100
}
```

Custom campfire recipe for testing
```
{
  "type": "MOD_ID_HERE:campfire_cooking_transfer_nbt",
  "ingredient": {
    "item": "minecraft:stick"
  },
  "result": "minecraft:blaze_rod",
  "experience": 0.35,
  "cookingtime": 100
}
```

**Description of issue:**
There is a level of differentiation between the use of an IRecipe for Campfire Recipes and for Smoking/Blasting/Smelting recipes...

- Campfire makes use of IRecipe::assemble which provides the inventory, allowing for modification of output items for example (CampfireTileEntity::cook)
- The others use IRecipe::getResultItem which is just a getter for the output item that cannot be easily (if at all) modified. (AbstractFurnaceTileEntity::burn)

This means that adding craft-time NBT such as moving NBT from the input item to the output item is restrictive.

As such it would be preferable if one or the other were set in stone as a difinitive solution, preferably using **assemble** since it allows for more functionality

**Comment by queekusme** [comment]
I'm reviewing the possibility of making these changes myself and submitting a PR.

Since I've never contributed to forge before I've been reading the documents and believe that this change would come under the following category.

https://mcforge.readthedocs.io/en/latest/forgedev/prguidelines/#breaking-changes-in-forge

As such, and imho, since this would end up breaking many existing mods, would this be something that would be considered for 1.17 as per `Forge accepts Breaking Changes at the beginning of new Minecraft versions`

This is also speculative that the MC devs don't also resolve this themselves.

**Comment by Shadows-of-Fire** [comment]
Changing the furnace subclasses to use `getCraftingResult` instead of `getRecipeOutput` would not be a breaking change.  It does not impact API in any way and it will not change the functionality of any recipes (except restoring functionality that is currently broken to recipes such as yours).

**Comment by Shadows-of-Fire** [comment]
Do note that there would need to be additional changes to `canSmelt` to account for the possibility of NBT-differing in recipe outputs, as it currently only checks the item and the stack size.

**Comment by queekusme** [comment]
> Do note that there would need to be additional changes to `canSmelt` to account for the possibility of NBT-differing in recipe outputs, as it currently only checks the item and the stack size.

I see what you mean here... `getResultItem` will also need changing for the `sameItem` calculation... well spotted, I would probs have missed that :), will deffo take that into account now!

> Changing the furnace subclasses to use getCraftingResult instead of getRecipeOutput would not be a breaking change. It does not impact API in any way and it will not change the functionality of any recipes

I kinda see what you mean, `getResultItem` and `assemble` are both abstract meaning that they both need implementing... Vanilla Recipe Implementations seem to do `this.result.copy()` in `assemble`, which imho is safer than just returning `this.result` which `getResultItem` does...

Some mods may break however from what I can see, this may end up being more down to specifics in each recipe...

What i'll probably do is once i have a few more feature changes in my mod I'll have a stab at a branch on this and see where it ends up...

Also, it took me a minute to reference function names as I believe we are looking at different mappings... hahaha...
`canSmelt` == `canBurn` etc...

**Comment by TheCurle** [comment]
From a cursory look, it seems like this would require very invasive patches to align fully, and has a high chance of inadvertently causing breaking changes.

I have a strange feeling we might just have to deal with the vanilla inconsistency for now.

**Comment by Shadows-of-Fire** [comment]
What invasive patches are necessary?  The furnaces and campfires require pretty minimal changes to get this running

**Comment by LexManos** [comment]
Then do them and PR it. However, I'm not sure if we should in the sense that Mojang is very adamant about keeping a lot of NBT out of recipes. We would also need to figure out what vanilla/modded recipes this effects.
We would also need to add config options to disable this because it could have unintended side effects.
Vanilla's crafting/item system is highly dependent on using simple items. It has a lot of side effects.

**Comment by queekusme** [comment]
The NBT comments are my specific use case and shouldn’t be necessary for the changes proposed… once I have time I intend to create a PR for this assuming someone else doesn’t beat me to the submission, it may be best to wait until then to review its suitability so we can see and test the specific implementations

**Comment by LexManos** [comment]
Ya, more information and concrete examples would be the way to go. As said, i'm a bit hesitant to change how vanilla works without knowing what we're changing in this reguard. Especially if it's soley to go against the vanilla concept of simple items.
We'll keep an eye out for your PR/More Info.

**Comment by queekusme** [comment]
Ive supplied a PR which fixes the original issue I was having allowing output items to be modified in an IRecipe assemble method rather than simply returning the output item

This now brings the functionality for Furnace, Smoker and Blast Furnace in-line with the Campfire, allowing outputs via custom IRecipes to modify output items before being provided to the player.
