### ISSUE TITLE
Keybinds conflict with one being multiple keys

### ISSUE THREAD

**Issue by DalekCraft2** [MinecraftForge/MinecraftForge#7691]
**Minecraft Version:** 1.16.5

**Forge Version:** forge-1.16.5-36.1.0

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/6158487/debug.log)

**Steps to Reproduce:**
1. Set a keybind to any key
2. Set another keybind to be more than one key, with one being the previous key
3. Keys conflict

**Description of issue:**
If two keybinds have similar keys, but one has more than one key, Forge will still detect it as a conflict (E.G. C and CTRL+C conflict).

**Comment by diesieben07** [comment]
Yes, this is correct.
C will trigger even if you hold down CTRL. Otherwise you couldn't move sideways while sprinting. Or for that matter, sprint at all (Shift + W by default, which are separate key bindings).
