### ISSUE TITLE
cannot open prject in Intellij

### ISSUE THREAD

**Issue by asdfghjkl403622** [MinecraftForge/MinecraftForge#7703]
I just ran the gradle command to set up the project for intellij and got this error: `Unsupported class file major version 60`
I tried changing the java version to 11 but it didn't work. I'm using forge mdk 1.16.5 on manjaro linux.

**Comment by josephtarbit** [comment]
So what version of Java are you actually using then? Because the error message would suggest something that isn't Java 8.

**Comment by Thelonedevil** [comment]
> Unsupported class file major version 60

Would appear to be JDK16 (which neither gradle nor forge support at the moment)
