### ISSUE TITLE
AnvilUpdateEvent has mismatched comment and actual behaviour

### ISSUE THREAD

**Issue by Rongmario** [MinecraftForge/MinecraftForge#7708]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.1.4

**Description of issue:**
Since #7442, AnvilUpdateEvent has the comment: `AnvilUpdateEvent is fired when the inputs (either input stack, or the name) to an anvil are changed.`  This is currently untrue/unclear as it is only fired when both left, right input ItemStacks are populated. The name field can change and not fire this event if the right ItemStack is empty.

**Comment by diesieben07** [comment]
This has been the case as far back as 1.12.2 at least (I couldn't check 1.7.10 as I couldn't get the workspace to work). Question is if we should change the behavior.

**Comment by Rongmario** [comment]
The behaviour before did fit the comment (just wasn't explicated enough) prior to the aforementioned PR: `AnvilUpdateEvent is fired when a player places items in both the left and right slots of a anvil.`

**Comment by TheCurle** [comment]
This is probably an issue for #7612, which aims to fix this type of comment mismatch. When i get around to rebasing that monster, i'll update you here.

**Comment by Matyrobbrt** [comment]
This issue has been fixed by https://github.com/MinecraftForge/MinecraftForge/commit/130953e519e0c7f4a32b4d6c3af3740a09f07f30.
