### ISSUE TITLE
Forge Website Down ;-;

### ISSUE THREAD

**Issue by Nishant1500** [MinecraftForge/MinecraftForge#7713]
Forge Websites Down.. You Can Go And Check It. If The Forge Website Starts Again Then i will close this issues :>

Website That Are Down:
https://www.minecraftforge.net/
https://forums.minecraftforge.net/

**Comment by KingLemming** [comment]
Oh interesting. I don't see where the website code is in this repo though.

Oh wait. It's not. You should go ahead and close this before it happens automatically and it's the last issue that you're able to create here.

**Comment by Nishant1500** [comment]
Can You please guide where to submit the report for website bugs?

**Comment by KingLemming** [comment]
https://discord.gg/UvedJ9m
