### ISSUE TITLE
getDamageSource() can return null in LootingLevelEvent due to global loot modifiers with RandomChanceWithLooting condition

### ISSUE THREAD

**Issue by vemerion** [MinecraftForge/MinecraftForge#7714]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.1.0

**Logs:** Here is an issue with a crash report: https://github.com/Beethoven92/BetterEndForge/issues/96#issuecomment-815442034

**Steps to Reproduce:**
 1. Create a global loot modifier that uses the RandomChanceWithLooting loot condition.
 2. Subscribe to the LootingLevelEvent.
 3. Print getDamageSource() in the LootingLevelEvent.
 4. Destroy a block in-game to see that getDamageSource() returns null.

**Description of issue:**
It turns out that there is a corner case with using the RandomChanceWithLooting LootCondition with global loot modifiers, since then the DamageSource will be null if there is no damage done (and this might happen because every loot modifier is run after every block destroyed etc). Normally this is not a problem, but if another mod subscribes to the LootingLevelEvent and assumes that the DamageSource is not null, there will be a null pointer exception. An example of a mod where this happens is the Unique Enchantments mod, on the exact source code line [here](https://github.com/TinyModularThings/UniqueEnchantments/blob/aa225de8cbbb2192b22c086adbbaf16df7ba5042/src/main/java/uniquee/handler/EntityEvents.java#L918).

I am unsure of exactly what the best fix for this would be. Just adding a Nullable annotation would mean that it would still be an issue until the problematic mods update. Maybe getDamageSource() could return some kind of 'dummy' DamageSource instead of null?

**Comment by diesieben07** [comment]
> but if another mod subscribes to the LootingLevelEvent and assumes that the DamageSource is not null, there will be a null pointer exception

Then it is a bug in said mod. If there isn't a DamageSource available, we can't exactly make one up.
However we might not want to fire the looting level event at all if there isn't a killer entity, because looting without killing an entity doesn't really make sense. That still would not mean there is always a DamageSource necessarily though.

**Comment by vemerion** [comment]
> Then it is a bug in said mod.

I agree with you that the fault lies partly on the mod makers, but I have stumbled upon at least two mods that assume it is never null, so it seems like a somewhat common misconception. I feel like at least a Nullable annotation and maybe a comment in LootingLevelEvent would be a good thing.

> However we might not want to fire the looting level event at all if there isn't a killer entity, because looting without killing an entity doesn't really make sense.

I like this idea. Do you think a pull request would be in order?

**Comment by diesieben07** [comment]
> Do you think a pull request would be in order?

Sure, why not.

**Comment by Random832** [comment]
> Then it is a bug in said mod. If there isn't a DamageSource available, we can't exactly make one up.

I've seen this issue a couple times when the ultimate damage source was a creeper explosion, though, and under normal circumstances [i.e. no GLM] the DamageSource isn't null [for entities, and the looting event doesn't get fired for blocks destroyed by the explosion]

**Comment by TheCurle** [comment]
Note for future triage: this issue is closed by #7717.
