### ISSUE TITLE
I have a problem opening Minecraft with mods.

### ISSUE THREAD

**Issue by Fport1** [MinecraftForge/MinecraftForge#7720]
I have a friend that is having an issue in Tlauncher. The problem happens at the moment he opens minecraft. He uses macos. When he opens forge 1.12.2 with no mods, he is able to play, when he uses the mods, he is not able to open Minecraft. Here is some pictures and hs_err_pid.

![d61dfdc7790bb93757467b8ae03c27cf](https://user-images.githubusercontent.com/79050843/114732749-64b7d300-9d08-11eb-82ad-e2444540b914.png)
![4e48ccf253be52be7d092edc4b7492ff](https://user-images.githubusercontent.com/79050843/114732751-65506980-9d08-11eb-8bc2-4db42171d18c.png)
![92d5cd53ec9f21d8d0233972c257a501](https://user-images.githubusercontent.com/79050843/114732753-65506980-9d08-11eb-8cb8-bffc952936b5.png)
![41b3da36d86bff04feff30be5fa9b725](https://user-images.githubusercontent.com/79050843/114732754-65e90000-9d08-11eb-9bae-f12aef2c46fc.png)

[hs_err_pid10178.log](https://github.com/MinecraftForge/MinecraftForge/files/6311725/hs_err_pid10178.log)
[hs_err_pid16774.log](https://github.com/MinecraftForge/MinecraftForge/files/6311726/hs_err_pid16774.log)
[hs_err_pid12837.log](https://github.com/MinecraftForge/MinecraftForge/files/6311727/hs_err_pid12837.log)

I hope you can let me solve this issue. Thanks.

**Comment by diesieben07** [comment]
Piracy is not supported, buy the game.
1.12 is ancient and no longer supported by Forge.
