### ISSUE TITLE
[forgedev, eclipse] Project 'forge' is missing required source folder: 'main-ressources'

### ISSUE THREAD

**Issue by Naheulf** [MinecraftForge/MinecraftForge#7721]
**__Minecraft Version:__** 1.16

**__Forge Version:__** c0e74bc8a8ae68ec07c30e86fc11284a18135bec (latest now)

**__Logs:__** There nothing useful in logs even using Gradle `--info` arg...

**__Steps to Reproduce:__**
 1. Follow the updated version of https://mcforge.readthedocs.io/en/1.15.x/forgedev/#getting-started available at [forgecommunitywiki/Documentation@96b862afeb45c90d2c18f4241de830617dabdfed/docs/forgedev/index.md](https://github.com/forgecommunitywiki/Documentation/blob/96b862afeb45c90d2c18f4241de830617dabdfed/docs/forgedev/index.md) : 

**__Actual behaviour:__**
When Eclipse try to compile project just after importing, it show this error:

> Project 'forge' is missing required source folder: 'main-ressources'

**__Expected behaviour:__**
No error should occur importing unmodified fork of MinecraftForge.

**__Description of issue:__**
At Eclipse step 3 (`./gradlew eclipse`) Gradle create all source BuildPath in `/projects/forge/.project` and `/projects/forge/.classpath`.
However there something odd. It create two entry (with the same path) for ["$rootDir/src/main/resources"](https://github.com/MinecraftForge/MinecraftForge/blob/c0e74bc8a8ae68ec07c30e86fc11284a18135bec/build.gradle#L138). One is named `main-resources` and the other on is only `resources`. And delete the first one at: https://github.com/MinecraftForge/MinecraftForge/blob/c0e74bc8a8ae68ec07c30e86fc11284a18135bec/build.gradle#L176-L177

So only `resources` remain. But Gradle use `main-resources`...

**__Note:__** I narrowed down the bug so I can say what happen and apply a work around (recreate main-resources) on my computer. However I don't know how to correct it properly for everyone.

**Comment by TheCurle** [comment]
After searching ForgeGradle and Forge's buildSrc scripts, "main-ressources" appears exactly 0 times, and "ressources" appears exactly 0 times.

I can only assume you accidentally typoed something while setting up, or hit a key by accident.
As it stands, user error isn't something we can easily fix with a commit.
