### ISSUE TITLE
Mod Update Menu Button

### ISSUE THREAD

**Issue by GittyUpMyHorsey** [MinecraftForge/MinecraftForge#7727]
Is there a way to remove the green notifier gem on the title screen mod button (even if there are updates) by editing the config file?

Thanks.

**Comment by sciwhiz12** [comment]
:wave:
In the future, please use the [Forge Support Forums](https://forums.minecraftforge.net/forum/18-support-bug-reports/) or the [Official Discord server](https://discord.gg/UvedJ9m) for support-related questions; this issue tracker is reserved for final bug reports and feature requests.

To answer your question, you can disable the update checker by changing the `versionCheck` setting in the `fml.toml` config file to `false`. There is currently no option to leave the update checker enabled while hiding the notification gem on the main menu.
