### ISSUE TITLE
Models and blockstates jsons improvements

### ISSUE THREAD

**Issue by GoogeTan** [MinecraftForge/MinecraftForge#7732]
My main idea is to create formulaic JSONs if it does not exist. For example, if blockstate had not been found, it will be:
`{
  "variants": {
    "": {
      "model": "<modid>:block/<registryname>"
    }
  }
}`
and a warning message will be sent. If an item model had not been found, it will be:
`{
  "parent": "item/generated",
  "textures": {
    "layer0": "<modid>:items/<registryname>"
  }
}`
Block models can be generated like item models or search files in `texture/block/` which starts with `<registryname>` and try to make a model by their suffixes(such as _top). I wanted to make it but I decided to ask here would my idea be accepted.

This change will help you not to write many same JSONs.

**Comment by gigaherz** [comment]
We have a data generator system which lets you declare the contents of the json in code, so adding those things to the game would be rather pointless. You can just write your own helpers to produce the right blockstate/model within forge's data generators.

**Comment by GoogeTan** [comment]
So, I have to write a similar huge code block in all my projects? It sounds bad. I have not already tried data generators but I don't think it is easy to write something like JSONs by pattern if absent.

**Comment by ChampionAsh5357** [comment]
I mean `simpleBlock` does exactly what you're asking for and it's a single method call and you can expand the helper to call `simpleBlockItem` to create the item parent. The standard item model would need a bit of writing, but it's essentially reduced down to one line with two chained method calls.

**Comment by tterrag1098** [comment]
Magic hardcoded fallback resources are terrible for user discoverability. Forge won't be adding this. Like others suggested, you can set this up in your data generators with a few lines of code.
