### ISSUE TITLE
Make ForgeI18n#parseMessage return ITextComponents instead of Strings

### ISSUE THREAD

**Issue by DarkEyeDragon** [MinecraftForge/MinecraftForge#7749]
Currently they are parsed and returned as Strings. The big issue here is that they include the new line character which components don't support so converting them into components after parsing is a bit of a pain.

A better solution would be to return a collection of text components if there should be new lines. (Or a single Textcomponent if just one line.)

**Comment by pupnewfster** [comment]
Forge patches [TranslationTextComponent](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/patches/minecraft/net/minecraft/util/text/TranslationTextComponent.java.patch#L7-L10) to be able to use the same formatting as ForgeI18n. So I would recommend just doing it through that/if that still has the same issue which looking at [this](https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/fml/TextComponentMessageFormatHandler.java#L31) it might, it may make more sense to just adjust how that part works to treat the text components in a more proper way.

**Comment by DarkEyeDragon** [comment]
It still calls the `ForgeI18n#parseMesssage` which results in the same issue. 

![image](https://user-images.githubusercontent.com/6131099/116783662-3835e200-aa90-11eb-9bfb-f897f3bc7f68.png)
I'm aware that this specific issue was fixed for the multiplayer tooltip but it just circumvents the underlying issue. So once you do 

```
TranslationTextComponent textComponent = new TranslationTextComponent("fml.menu.multiplayer.compatible", target.forgeData.mods.size());
```
for example, the actual component still contains new lines because they aren't handled by  the parse and just passed to the component.
