### ISSUE TITLE
Shallow clones of this repo cannot be built

### ISSUE THREAD

**Issue by sam-kirby** [MinecraftForge/MinecraftForge#7759]
**Minecraft Version:** 1.16.x

**Forge Version:** b6ce4fb

**Logs:** https://pastebin.com/uAJYXrkb

**Steps to Reproduce:**
 1. `git clone git@github.com:MinecraftForge/MinecraftForge.git --depth 1 --branch 1.16.x forge`
 2. `cd forge`
 3. `./gradlew setup`

**Description of issue:**
This may not be a terribly high priority issue, but the full Forge repo is currently over 100MiB. On slow internet connections, or for people with a data cap, this can represent a significant time or monetary cost.

Making it possible to build the project without a full git history would help in these instances.

My apologies if this should have been posted on the Forge Gradle project's repo.

**Comment by TheCurle** [comment]
Forge, like many projects, uses git tags to keep track of version history.
Like those many other projects, you need to clone the git tags along with the repository in order to build.

This is nothing new, but it's easily fixed.

**Comment by LexManos** [comment]
Not something we need to care about on our end. There is no presumption that shallow clones are buildable. However, you should be able to clone the repo, with tags, but also shallow. So it's just a matter of how you check it out. Again, not something we particularly care about. Especially considering the 3rd party libraries, and MC assets used to debug easily trump the 100MB size of the repo.
