### ISSUE TITLE
Custom tile entity data sided leak on integrated servers

### ISSUE THREAD

**Issue by KnightMiner** [MinecraftForge/MinecraftForge#7760]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.1.15

**Description of issue:**

Forge currently writes to NBT by just setting the current instance of its custom tile data into the [NBT `writeInternal`/`saveMetadata` method](https://github.com/MinecraftForge/MinecraftForge/blob/a95b968c1397a1597d4a6228d8e1abce6495570e/patches/minecraft/net/minecraft/tileentity/TileEntity.java.patch#L38). Additionally, it reads the NBT by just setting the custom tile data equal to the current NBT tag. While this works, this means the same NBT compound stored in the tile entity is now also stored in that tag, so updating one will update both.

**Steps to Reproduce:**

One case where this became a problem is when syncing tile data using `getUpdateTag()`. Most implementations will ultimately call `writeInternal`, which includes the implementation in vanilla tile entities. On a ~~dedicated~~ integrated server, the packet is sent directly between threads without serializing it to a packet buffer, so when its received again on the client side and read using `read`/`load`, the compound is still the same tag from the server side. This can lead to some very hard to trace bugs where setting NBT on one side updates it on the other without syncing.

It is possible there are other cases affected by this leak, though since the primary use of that method other than writing to disk is syncing, the only case I know of is syncing on a ~~dedicated~~ integrated server.

**Solution:**

Easiest fix is to call `copy()` on the data before writing and after reading. This will ensure the NBT in the packet is a unique instance so no other objects are modifying the internal tag. At minimum just adding a copy in one of the two places will fix the problem.

**Comment by LexManos** [comment]
You're a bit confused, as the leaking would only occur on the integrated server, not the dedicated server.
But besides that yes, you're correct, it stores a direct reference and thus can be updated in the background. The main issue is the cost of copying this data.
The other thing to considering, is does this 'customTileData' still need to exist. It seems like a rather cludgy system. Who is still using it, and for what? We now have the capability system which can be used to store arbitrary data on anyone else's TE.

**Comment by KnightMiner** [comment]
Ah yeah, meant integrated. Single player.

I don't strictly need it in my mod, my use of the system could easily move to read/write, only reason I did not do that originally was because I was just storing a single string in the TE so it was just easier to set up. I can easily migrate away from tile data, so I am not against just removing the system to reduce patches.

**Comment by KnightMiner** [comment]
For the record, this also seems to affect custom entity data in addition to tile entities. I cannot think of a specific case where it would be an issue, but if custom data is being removed from tile entities due to capabilities handing that, would make sense to remove from entities as well.

**Comment by 3TUSK** [comment]
> is does this 'customTileData' still need to exist

[Searching on GitHub using query `customTileData extension:java -filename:TileEntity.java`](https://github.com/search?p=1&q=customTileData+extension%3Ajava+-filename%3ATileEntity.java&type=Code) reveals that nearly nobody has an actual usage of this field or its getter. Most of results are not even Minecraft-related (looks like Android). There is even one case where a new `customTileData` field is declared and shadowed the original one…  
Overall, it sounds safe to assume that this `customTileData` hasn't been actively used recently.

On the other and, [searching on GitHub using query `getPersistentData minecraft entity extension:java`](https://github.com/search?p=1&q=getPersistentData+minecraft+entity+extension%3Ajava&type=Code) reveals much more Minecraft-related results. I haven't checked them one by one, so I am not certain about what `Entity.persistentData` are mainly used for.

Further context:

`TileEntity.customTileData` (`BlockEntity.customTileData` nowadays) was introduced in a PR #1755 whose intention is the same as `Entity.getEntityData()`.

`Entity.persistentData` can be traced back to this commit (I believe): [e26f1ab6](https://github.com/MinecraftForge/MinecraftForge/commit/e26f1ab671b630289599c73d5e81ebb63701a273#diff-ac4edb2980c1d8677c5ec5ef82704cf8ac0366ecf2f72f6272bddbd955132312R7-R8) whose original comment reads "[u]sed to store custom data for each entity." 

It looks like both functionalities have overlap with capability.
