### ISSUE TITLE
Certain forge installer doesnt work

### ISSUE THREAD

**Issue by Ectoniqua** [MinecraftForge/MinecraftForge#7765]
**Minecraft Version:** 1.12.2

**Forge Version:** {forge-1.12.2-14.23.5.2768-installer.jar}

**Logs:** https://gist.github.com/Ectoniqua/3703671bb8bf9d004d8069581aee7c4f

**Steps to Reproduce:**
 1. download forge-1.12.2-14.23.5.2768-installer.jar
 2. try to install it
 3. wont install 

**Description of issue:**
I downloaded this file and tried to install it, but it wont open, i tried with another version (forge-1.12.2-14.23.5.2855-installer.jar)
and it worked, but this version wont open. How do i fix this?

**Comment by SizableShrimp** [comment]
GitHub issues are not for support. We do not support 1.12 either. The latest installer of 1.12.2 will work. Use that.

**Comment by TheCurle** [comment]
The latest installer is tested to work.
