### ISSUE TITLE
1.16.5-36.1.6: Chunks generated+populated twice on exit/reload.

### ISSUE THREAD

**Issue by PG85** [MinecraftForge/MinecraftForge#7766]
Forge 1.16.5-36.1.6
Eclipse dev environment, SP client, view range 16.

**Description of issue:**
When creating a new default world with the SP client, joining the world, then exiting and rejoining, some chunks are generated/populated twice. This can cause resources that spawn across chunk borders (like trees) to be cut off.

**Steps to Reproduce:**
Easy way to test for chunks being generated/populated twice:
 1. Add code or a conditional breakpoint to NoiseChunkGenerator.fillFromNoise (terraingen) and ChunkGenerator.applyBiomeDecoration (population). Make it log the coords of the chunk being generated/populated and/or store the coords in a static list and check for duplicates.
 2. Create a new default world, jump in. Stand still, look around 360 degrees, wait for chunkgen/population to finish (no more log messages about fillFromNoise/applyBiomeDecoration calls), then exit the world to main menu.
 3. Rejoin the world, then move in any direction to generate chunks. A band of chunks 1 chunk wide along the borders of the previously generated (rectangular) area will be generated/populated for a second time.

I noticed this because we have some resources that don't regen properly, so if you generate/populate a chunk twice they vanish, clearly showing the affected chunks. Normally you'd only notice this when larger resources like trees spawn on chunk boundaries and are cut off when a chunk is discarded and regenerated on exit/rejoin.

**Comment by PG85** [comment]
![2021-05-14_23 17 01](https://user-images.githubusercontent.com/6781444/118332551-8e803780-b50a-11eb-8549-4826a92cadfd.png)

Tested with SP client, no mods. Created default world, let it finish generating chunks, jumped out, jumped back in (as per instructions), explored around spawn, found cut off tree nearby.

**Comment by Niko-sk2x** [comment]
This seems to be a vanilla bug https://bugs.mojang.com/browse/MC-224729

**Comment by PG85** [comment]
Yep, appears to be the exact same issue. Will wait for Mojang to fix it then, thanks!
