### ISSUE TITLE
Custom ladders don't work properly in combination with trapdoors

### ISSUE THREAD

**Issue by TheChildWalrus** [MinecraftForge/MinecraftForge#7775]
**Minecraft Version:** 1.16.5

**Forge Version:** 1.16.5-36.1.0

**Description of issue:**
Modded ladder blocks don't allow climbing through a trapdoor placed at the top. This is despite having the ladder block added to the `blocks/climbable` tag, so not a duplicate of [7692](https://github.com/MinecraftForge/MinecraftForge/issues/7692).

![image](https://user-images.githubusercontent.com/2998215/118414525-f6668780-b69c-11eb-9432-c08848caa416.png)

With a ladder and trapdoor placed in the above configuration, when the trapdoor is opened, vanilla ladders allow you to climb up through the trapdoor. But modded ladders don't.

This appears to happen because the trapdoor block considers itself to be ladder-climbable if a ladder block is placed below - but it only checks the vanilla ladder. The relevant patched code in `TrapDoorBlock.java`:

```
   //Forge Start
   @Override
   public boolean isLadder(BlockState state, net.minecraft.world.IWorldReader world, BlockPos pos, net.minecraft.entity.LivingEntity entity) {
      if (state.get(OPEN)) {
         BlockState down = world.getBlockState(pos.down());
         if (down.matchesBlock(net.minecraft.block.Blocks.LADDER))
            return down.get(LadderBlock.FACING) == state.get(HORIZONTAL_FACING);
      }
      return false;
   }
   //Forge End
```

It would be possible to "fix" this by replacing the `matchesBlock(net.minecraft.block.Blocks.LADDER)` call with one that checks if the block is in the `climbable` tag instead. But that would also include other blocks in the tag, vines & Nether vines etc. and a quick check on a vanilla-only installation tells me that wouldn't match vanilla functionality.

**Comment by pupnewfster** [comment]
I don't remember the MCP name for it (given you are using MCP names when showing the code) but couldn't you just override `Block#is(Block)` to return true when passed Blocks.LADDER?

**Comment by TheChildWalrus** [comment]
That'd achieve it, but from a code search I gather it would also interfere with a number of other things which use that method, most notably the Block Predicates involved in advancement criteria, /fill command, and so on. Seems the game wants that method to be a strict equality check.

**Comment by cech12** [comment]
Maybe adding a ladder tag and checking this tag at the given code position could fix this issue, too.

Edit: Or an `instanceof LadderBlock` check.

**Comment by KnightMiner** [comment]
There already is a ladder tag, more accurately a climbable tag. I suppose splitting it into 2 tags would be more consistent with vines though

**Comment by cech12** [comment]
This does not work here, because the checked block must be a ladder in this case (not vines or other blocks that are inside the climbable tag), because the trapdoor climbing mechanism should only work if there is a ladder below. (since MC 1.9 - 15w31a)

**Comment by cech12** [comment]
I didn't see, that your message was edited xD I don't know if splitting the tag is a good idea. Then all places that are using the climable tag must be changed. I think, in this case adding a tag where only ladders are included is a better solution. The tag could be called "below_trapdoor_it_is_climbable" or "makes_trapdoor_climbable" or something similar. The name "ladders" could confuse developers because there is the "climbable" tag.

**Comment by TheChildWalrus** [comment]
Thanks for looking into that @cech12 , fix looks great!
