### ISSUE TITLE
[1.16.5] PlayerEntity#sendMessage causes packet error in server - Error Encoding Packet

### ISSUE THREAD

**Issue by ratquaza** [MinecraftForge/MinecraftForge#7788]
**Minecraft Version:** 1.16.5

**Forge Version:** Forge 1.16.5-36.1.0

**Logs:** https://gist.github.com/ratquaza/44e60c6799f0a3c3a3378f818354aac9
**Steps to Reproduce:**
 1. Create a new command and register it that sends the source a message if they're a player.
 2. Run a server and connect to it with a client.
 3. Execute the command on the client.
 4. The message is not sent and the 

**Description of issue:**
When I create and register a new command like the gist, then execute it on a server (LAN or Dedicated), I receive an "Error Encoding Packet" exception. This has fired on both my mod and a fresh new mod.

**Comment by LexManos** [comment]
As discussed on discord, if you pass null to a function that expect not null. You'll cause a NPE.
