### ISSUE TITLE
[1.16.5] MC-121048 still exists for players

### ISSUE THREAD

**Issue by Chumbanotz** [MinecraftForge/MinecraftForge#7805]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.1.25

**Description of issue:**
[This](https://github.com/MinecraftForge/MinecraftForge/pull/4452) pull request fixed [MC-121048](https://bugs.mojang.com/browse/MC-121048) for mobs, but since players override LivingEntity#actuallyHurt, this fix was not applied in PlayerEntity#actuallyHurt as it was here:
https://github.com/MinecraftForge/MinecraftForge/blob/b98991dc70f8635f5d4ab89cf40274ebdfc70790/patches/minecraft/net/minecraft/entity/LivingEntity.java.patch#L290

**Comment by OneLemonyBoi** [comment]
can confirm
