### ISSUE TITLE
Can not build forge with error Execution failed for task ':compileJava'

### ISSUE THREAD

**Issue by Hypocisy** [MinecraftForge/MinecraftForge#7823]
**Minecraft Version:** 1.16.5

**Forge Version:** 1.16.5-36.1.32

**Logs:** 
[Error in console](https://paste.ubuntu.com/p/sFTqnNd5qT/)

**Steps to Reproduce:**
 1. donload forge mdk from [here](https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.1.32/forge-1.16.5-36.1.32-mdk.zip)
 2. unzip the mdk files.
 3. open Terminal and run `.\gradlew genIntellijRuns`
 4. open the mdk dir with Intellij.
 5. click the build button.

**Description of issue:**
```
java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```
System info: Windows 10 Pro	21H1
**Sorry for my bad english!!!**

**Comment by TheCurle** [comment]
Your gradle cache is corrupted. Delete it.
