### ISSUE TITLE
A mob's HurtByTargetGoal can trigger an NPE if you nullify their revenge target

### ISSUE THREAD

**Issue by Thelnfamous1** [MinecraftForge/MinecraftForge#7853]
Minecraft Version: Any 1.16.x version will do.

Forge Version: Forge 32 and up.

Logs: Crash log will always show a NullPointerException thrown by `HurtByTargetGoal` when trying to change the revenge target for a mob.

Steps to Reproduce:
- During a LivingSetAttackTargetEvent handler for any mob that has a `HurtByTargetGoal` (example: Bee), set the revenge target for the entity to null via `LivingEntity#setRevengeTarget` in MCP mappings or `LivingEntity#setLastHurtByMob` in Mojmap mappings.
- Launch the game.
- Trigger the event handler (in the Bee example, trigger their revenge behavior by attacking them or breaking their hive in survival mode).
- Game will crash with NPE.

Description of issue:
A mob's `HurtByTargetGoal` does not check for null when accessing the revenge target in `HurtByTargetGoal#alertOthers` (IntelliJ will show you this if you can access the class in a write-enabled capacity), which means if you try to prevent the mob from engaging in revenge behavior via the above event or any other point, the game will crash by NPE. 

This means if you say, try to make Bees not engage in revenge behavior when you attack them, the game will crash and there's no easy way to avoid this.

A simple fix is to just wrap the revenge target accessor call with a null check via a patch.

**Comment by WhyNot180** [comment]
Going to work on this if nobody else is currently
