### ISSUE TITLE
Forge for 1.17

### ISSUE THREAD

**Issue by Minionguyjpro** [MinecraftForge/MinecraftForge#7855]
Please make Forge for 1.17

**Comment by Minionguyjpro** [comment]
Why?

**Comment by diesieben07** [comment]
It will be done when it's done.

**Comment by SizableShrimp** [comment]
It already exists and is private for the time being. If you want to know why, join the discord and read the announcements. This is not the place.

**Comment by Minionguyjpro** [comment]
Is it being Public soon?
