### ISSUE TITLE
Bonemeal don't trigger CropGrowEvent

### ISSUE THREAD

**Issue by shBLOCK** [MinecraftForge/MinecraftForge#7856]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.1.32

**Description of issue:**
CropGrowEvent doesn't trigger when use bonemeal to grow a crop.

**Comment by saksham4106** [comment]
use `BonemealEvent` instead? It triggers just before bonemeal is used.

**Comment by baileyholl** [comment]
I believe (or hope) this is intended behavior. Otherwise, how will you know if crop growth is a natural event vs bonemeal? We need the distinction, or context given to the event if this is not intended.

**Comment by sciwhiz12** [comment]
I'd have to agree with @baileyholl. Looking at the original PR which implemented the crop growth events, #3320, it seems that the intention of the PR author as indicated in the javadocs for `CropGrowthEvent.Pre` is that the event is only for natural growth -- that is, when a random tick causes the crop block to advance to the next growth stage:

https://github.com/MinecraftForge/MinecraftForge/blob/998a78c3c1634b1b5bf4ddab07642e1769c7adc7/src/main/java/net/minecraftforge/event/world/BlockEvent.java#L302-L314

If this were to be changed, it would be a breaking change (as it changes the contract of the event, from fired for natural growth to fired from both natural growth and artificial growth stimulated by bonemealing the crop), and it would open up the question of whether any mod which does manual crop growth that does not go through either bonemeal or random tick will have to fire this event.
