### ISSUE TITLE
Forge 1.16.5-36.1.0 just makes most blocks render as missing texture

### ISSUE THREAD

**Issue by AntikoreDev** [MinecraftForge/MinecraftForge#7863]
I looked through all the whole web and I haven't found anybody having this same issue.
Basically, even with no mods, forge basically makes most blocks render as black and purple.

The screenshots below attached were taken without any mods, but I had this same issue with a modpack of around 211 mods, and before all of these, another attempt with only 3 mods.
![2021-07-11_11 01 39](https://user-images.githubusercontent.com/27287801/125189535-dc7a9880-e238-11eb-9049-afd5d4f74ff0.png)
![2021-07-11_11 01 13](https://user-images.githubusercontent.com/27287801/125189536-de445c00-e238-11eb-98c7-c0ed1e984a98.png)
![2021-07-11_11 01 38](https://user-images.githubusercontent.com/27287801/125189539-df758900-e238-11eb-9466-94bd123b7e32.png)

Worth noting that Minecraft works perfectly fine without forge in 1.16.5, and forge in 1.12.2 works fine (the one I use normally)
without these issues.
Also, these blocks that render incorrectly in world, does actually render good in hand.

I'm using Windows 10 and I'm using the Curseforge Launcher, just in case it's necessary info

**Comment by MelanX** [comment]
Try latest Forge instead of recommended. This *should* work fine.
