### ISSUE TITLE
Add Update light flag to BlockFlags

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#7867]
in Level#setBlock there is a flag check against 128 (1<<7) to prevent light updates, this flag is not yet in BlockFlags implemented.

**Comment by sciwhiz12** [comment]
1.16.x is now out of support. Furthermore, the `Constants` class was deprecated in 1.17 and removed in 1.18 in favor of the natural constants found within the MC codebase, as Mojang's obfuscator was configured starting in 1.17 to not strip out unused classes, methods, and fields.

Users should reference the [javadocs on the Constants class as of 1.17.x](https://github.com/MinecraftForge/MinecraftForge/blob/1.17.x/src/main/java/net/minecraftforge/common/util/Constants.java) to see the vanilla-provided alternatives. In this case of this issue, `Block#UPDATE_SUPPRESS_LIGHT` is the appropriate flag.
