### ISSUE TITLE
1.17.1 Forge should pause the game in dev if it detects unregistered worldgen elements

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#7883]
This is more of an idea that I would like to put on the table so there is some discussion around it. The issue seen in 1.16.2 and onwards is that while the new worldgen system is both a blessing and a curse, it does require modders to register their ConfiguredFeatures, ConfiguredStructures, and ConfiguredCarvers. Failure to register these can cause rare hard-to-debug issues where the unregistered worldgen element nukes the registered ones from the same biome and generation stage.

How prevalent was this issue in 1.16? Very. I even made a mod called Blame to try and detect unregistered worldgen elements and it caught many mods. So many that I cannot keep up with reporting the issues and at one point, it found I forgot to register a ConfiguredFeature myself! Here is a picture of a tiny slice of all the mods with unregistered worldgen stuff that I reported to. A small slice.
![unregistered](https://user-images.githubusercontent.com/40846040/126711053-577a7c61-637b-4afb-a647-a67ef1255d32.png)

Now that Forge is on 1.17.1, I think this may be a good time to think about having Forge annoy modders in some way to register their worldgen elements but ONLY in development environment. An idea is to use Util.pauseInIde and just pause the IDE in dev to force modders to read the comment at the spot about Forge finding an unregistered worldgen element (would only pause once max per run). The reason I propose pausing the IDE is because I worry that logs may be ignored and a pause makes absolutely certain the modder sees it. 

Of course, how and where to check for unregistered worldgen elements may be tougher without iterating over all biomes and their contents manually. But that may be needed.

Thoughts on this? Is this something worth looking into and for someone to make a PR for? (I might be able to do it when I get some free time later if it is something people really want added to Forge)

**Comment by Commoble** [comment]
I'm okay with this

**Comment by williambl** [comment]
Why not just crash the game with a clear message in the log to register them?

**Comment by TelepathicGrunt** [comment]
@williambl ngl, I actually would love that but several people expressed displeasure when I said for Forge to just crash the game for unregistered worldgen stuff lol. Pausing the IDE is less harsh and should get the same point across hopefully.

**Comment by Pechayland** [comment]
That happened when I tested Twilight Forest mod "The game crashed whilst colliding entity with block"
Log: https://gist.github.com/Pechayland/6bd112690ff688e26c1d97bfc376861f

**Comment by LexManos** [comment]
Last I looked it was a Codec issue that required  ALL features to be either registered or not, and we fixed that to allow both in the same json array.  So this should be a non-issue.
There is only so much we can do to  make modders do things correctly.
There isn't much we can do about people giving invalid  data in datapacks.
So ya, im not in favor.

**Comment by Cyborgmas** [comment]
> Last I looked it was a Codec issue that required ALL features to be either registered or not, and we fixed that to allow both in the same json array. So this should be a non-issue.

As far as I can tel this is not the case, there is no such patch. I had made this pr #7582 but the issue was just upstreamed and not merged.
