### ISSUE TITLE
fg.deobf(...) not working

### ISSUE THREAD

**Issue by henkelmax** [MinecraftForge/MinecraftForge#7889]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.1

**Logs:** https://gist.github.com/henkelmax/dc4d91453059ddfaff058ff87acb0d80

**Steps to Reproduce:**
 1. Add a dependency with `fg.deobf(...)`
 2. Run Gradle

**Description of issue:**

When using `fg.deobf(...)` with ForgeGradle 5.1 and MC 1.17.1, it fails to decompile the dependency (`Unsupported class file major version 60`). My guess is that the decompiler still works with Java 8 and thus doesn't understand Java 16 Class version 60.

I made sure both projects are on Java 16 and compiled with Java 16. The Gradle wrapper is also up to date.

**Comment by SuperMartijn642** [comment]
When using `fg.deobf` for jars compiled with Java 8 it seems to work fine, so like @henkelmax said, it seems the decompiler still uses Java 8.

**Comment by LexManos** [comment]
Not a Forge issue, Also please don't cross post on multiple repos.
