### ISSUE TITLE
[1.17.1] Pickaxes don't have a tooltype in their item properties

### ISSUE THREAD

**Issue by desht** [MinecraftForge/MinecraftForge#7892]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.1

**Logs:** n/a

**Steps to Reproduce:**
 1. Create a pickaxe itemstack (any vanilla pickaxe) and call `IForgeItem#getTooltypes()` on its item.
 2. Instead of a set containing `ToolType.PICKAXE`, you will get an empty set

**Description of issue:**

This appears to be because the constructor for `PickaxeItem` does not call `.addToolType(net.minecraftforge.common.ToolType.PICKAXE, tier.getLevel())` to augment the item properties, as it did in 1.16.5.  Not sure if this is a simple oversight or due to some deeper internal changes in how vanilla works, but I see that tooltypes are still properly initialised for `AxeItem`, `ShovelItem` and `HoeItem`.

**Comment by Lupicus** [comment]
I think you use the new block tags, like BlockTags.MINEABLE_WITH_PICKAXE and BlockTags.NEEDS_DIAMOND_TOOL.

**Comment by desht** [comment]
Sorry if I wasn't clear. I'm taking about vanilla pickaxes here, not a modded pickaxe that I made.

**Comment by ricksouth** [comment]
Have the same issue here. Only in 1.17.1.

**Comment by ricksouth** [comment]
Looks like the PickaxeItem patch is missing: https://github.com/MinecraftForge/MinecraftForge/tree/1.17.x/patches/minecraft/net/minecraft/world/item

**Comment by TheCurle** [comment]
We're moving to the vanilla minable tags, so these patches and methods will likely be dropped in the future.

**Comment by Shornana** [comment]
> We're moving to the vanilla minable tags, so these patches and methods will likely be dropped in the future.

May I ask how at the moment we can make a block minable by pickaxe? I am a bit new to modding on Forge and when the ToolType.PICKAXE didn't function, I couldn't find much else.

**Comment by TheCurle** [comment]
Add your Block to the minecraft:minable/pickaxe tag.

As is described in the Minecraft wiki on the subject.
