### ISSUE TITLE
[1.17.1]'Task :runClient FAILED' in IDEA

### ISSUE THREAD

**Issue by Coloryr** [MinecraftForge/MinecraftForge#7893]
**Minecraft Version:** 1.17.1

**Forge Version:** 1.17.1-37.0.1

**Logs:** 
![pic](https://user-images.githubusercontent.com/26276037/126791020-f8e23de8-53aa-4d7e-be62-0c078ccbf1bc.png)

**Steps to Reproduce:**
 1. just run task

**Comment by Angular-Angel** [comment]
Same issue in eclipse, or thereabout: 

```
Task :runClient FAILED
Exception in thread "main" java.lang.module.ResolutionException: Module gson reads more than one module named cpw.mods.securejarhandler
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:908)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:729)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:379)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
	at cpw.mods.bootstraplauncher@0.1.15/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:77)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runClient'.
> Process 'command '/usr/lib/jvm/java-16-openjdk-amd64/bin/java'' finished with non-zero exit value 1
```

**Comment by Angular-Angel** [comment]
Steps to reproduce:
*Download the MDK
*Create a new project
*Dump the MDK in
*Import the project in eclipse
*Run the 'GenEclipsRuns' task
*Try and run the 'RunClient' task

**Comment by TheCurle** [comment]
From Shrimp:

```How to fix module x reads more than one module named cpw.mods.securejarhandler on 37.0.1
1. Add this to your dependencies {} block: 
implementation('cpw.mods:securejarhandler') { version { strictly '0.9.45' } }

2. Refresh Gradle and reimport the project
3. Rerun genIntellijRuns or genEclipseRuns depending on your IDE of choice
4. Restart IDE / Invalidate cache if all else fails

```

**Comment by Angular-Angel** [comment]
Hey, it works! Thats the big dependencies block further down build.gradle, not the little one at the top. The block that starts with:

```
dependencies {
    // Specify the version of Minecraft to use. If this is any group other than 'net.minecraft', it is assumed
    // that the dep is a ForgeGradle 'patcher' dependency, and its patches will be applied.
    // The userdev artifact is a special name and will get all sorts of transformations applied to it.
    minecraft 'net.minecraftforge:forge:1.17.1-37.0.1'
```

**Comment by SpencerBurgess** [comment]
Ran into the same issue using Eclipse. This fixed it for me. Thanks!

**Comment by xiaohugit1** [comment]
me too;
IntelliJ IDEA Community Edition 2024.1.4
forge 1.12.2-14.23.5.2859 
Liberica JDK 8u422 
Also installed Liberica JDK 17-7.0.12 
Windows x86 msi 
Deleted org.gradle.jvmargs=-Xmx3G
Steps to reproduce:
*Download the MDK
*Create a new project
*Dump the MDK in
*Import the project in IntelliJ IDEA.
*Run the 'Execute Gradle Task' task
*Try and run the 'RunClient' task
Can you help me?

**Comment by PaintNinja** [comment]
Go to the discord or forums for help.

1.12.2 requires Java 8, can't use Java 17.
You need 64bit Java.
You removed a required jvm arg, don't do that, it's needed for the decompile process to work.
