### ISSUE TITLE
Rundata issue when run

### ISSUE THREAD

**Issue by RealYusufIsmail** [MinecraftForge/MinecraftForge#7899]
**Minecraft Version:** {Minecraft version}
1.17.1

**Forge Version:** {Forge version. *Version number, not latest/rb*}
37.0.1

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
<img width="827" alt="Screenshot 2021-07-23 at 18 53 55" src="https://user-images.githubusercontent.com/67903886/126822059-d06fffbe-761b-450a-8216-47c9d93ad20f.png">

**Description of issue:**
The issue is when i run Rundata i get this error.

**Comment by saksham4106** [comment]
Ask in Discord for support, not GitHub. Check the pins of #modder-support-117
> How to fix module x reads more than one module named cpw.mods.securejarhandler on 37.0.1
> 1. Add this to your dependencies {} block: 
> `implementation('cpw.mods:securejarhandler') { version { strictly '0.9.45' } }`
> 2. Refresh Gradle and reimport the project
> 3. Rerun genIntellijRuns or genEclipseRuns depending on your IDE of choice
> 4. Restart IDE / Invalidate cache if all else fails
