### ISSUE TITLE
[1.17.1] LivingExperienceDropEvent is not fired (no event injected)

### ISSUE THREAD

**Issue by FireController1847** [MinecraftForge/MinecraftForge#7900]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.1

**Logs:** N/A

**Steps to Reproduce:**
 1. Utilize the LivingExperienceDropEvent
 2. It doesn't get fired

**Description of issue:**

LivingExperienceDropEvent is not fired at all. Analyzing Forge's code, in 1.16 you can trace back from the event to ForgeEventFactory#getExperienceDrop, and find usages from there to bring you to LivingEntity#dropExperience wherein you can find the method being called. In 1.17, this method call is missing entirely.

**Comment by TheCurle** [comment]
Oops! That's my fault, i missed the patch when porting. I'll have a fix ready soon.

**Comment by FireController1847** [comment]
Hey there Curle, I don't want to rush this and no worries, I just didn't know if there was a status update on getting this event fired once again. Again no worries if nothing's happened yet, just want to know what the plan is.

**Comment by TheCurle** [comment]
Some things have happened in the interim that mean im unable to complete this.

Calling on @pupnewfster and @OrionDevelopment to get this done.

**Comment by FireController1847** [comment]
@AterAnimAvis Hey there, not to push anything onto this cuz I really appreciate your guy's work on Forge and I don't want to seem impatient, but it's been a bit, is there a status update on this at all with the release of 1.18? Honestly and truthfully, I guess I have no right to complain if I could implement the feature myself, but I figure there's no harm in asking.
