### ISSUE TITLE
pack.mcmeta uses version 6, instead of 7

### ISSUE THREAD

**Issue by Angular-Angel** [MinecraftForge/MinecraftForge#7903]
**Minecraft Version:** 1.17

**Forge Version:** 37.0.1

**Steps to Reproduce:**
 1. Download the MDK and create a new mod.
 2. Check the pack.mcmeta file. It lists the pack version as 6, instead of 7.

**Description of issue:**
When creating a new mod, that mods pack.mcmeta is a version 6 data pack, instead of a version 7 data pack.

**Comment by srs-bsns** [comment]
Already addressed in: #7884
