### ISSUE TITLE
[1.17.1] Hook for side-specific redstone connections

### ISSUE THREAD

**Issue by Da-Technomancer** [MinecraftForge/MinecraftForge#7915]
In MC1.16 (and before), overriding `Block::canConnectRedstone` allowed modded blocks to specify that redstone connections based on side.
An example use of this would be something like a repeater, where redstone connects on only two sides.
As of MC1.17, `Block::canConnectRedstone` is gone, and redstone dust connections are all-or-nothing based on `BlockBehaviour::isSignalSource`. Vanilla repeaters are special cased in `RedstoneWireBlock::shouldConnectTo`, which mods don't have access to.

As of 1.17, mods cannot cleanly add redstone components similar to repeaters.

I suggest that Forge re-implements `Block::canConnectRedstone` or something similar in 1.17.

**Comment by rikka0w0** [comment]
#8014 adds the fully functional `canConnectRedstone` hook, the 1.17.x version will behave as it was back in 1.16.5.

**Comment by ChampionAsh5357** [comment]
Closed as of #8014.
