### ISSUE TITLE
[1.17.1] RenderingRegistry.registerEntityRenderingHandler doesn't register anything

### ISSUE THREAD

**Issue by alexsocha** [MinecraftForge/MinecraftForge#7920]
**Minecraft Version:** 1.17.1

**Forge Version:** 1.17.1-37.0.7

**Logs:** https://gist.github.com/alexsocha/792e1b2132dec79a243625b6b74027db

**Steps to Reproduce:**
1. Register a custom entity
2. Register a custom entity renderer in the FMLClientSetupEvent event:
```
RenderingRegistry.registerEntityRenderingHandler(myEntityType, MyEntityRenderer::new);
```
2. Start Minecraft and summon the entity
3. Try to look at the entity

**Description of issue:**
Since we are unable to register a renderer using `RenderingRegistry.registerEntityRenderingHandler`, the game will raise a NullPointerException every time it tries to render the custom entity.

**Suspected Cause**
After a renderer is registered, `RenderingRegistry.loadEntityRenderers` is never called.

**Workaround**
Call `RenderingRegistry.loadEntityRenderers()` manually after registering all entity renderers.

**Comment by ChampionAsh5357** [comment]
For right now, you can just call `EntityRenderers#register` yourself and make sure its within the synchronous work queue of the client setup event (e.g. `#enqueueWork`) since the vanilla base is not thread-safe.

**Comment by gigaherz** [comment]
I have been working on a fix for this since last night. It's mostly done, just needs testing. It will however be a "major" breaking change when I push this: <https://github.com/gigaherz/MinecraftForge/tree/renderer-events>

**Comment by gigaherz** [comment]
See <https://github.com/MinecraftForge/MinecraftForge/blob/1.17.x/src/test/java/net/minecraftforge/debug/client/rendering/EntityRendererEventsTest.java> for how to use the new feature.
