### ISSUE TITLE
[1.17.x] LiquidBlock's fluid field being left null causes various crashes with methods calling the fluid field

### ISSUE THREAD

**Issue by Eelt** [MinecraftForge/MinecraftForge#7922]
**Minecraft Version:** 1.17

**Forge Version:** 37.0.7

**Logs:** 
Crash:
https://gist.github.com/Eelt/c7b876a9652d2be5794417c0a0899788
Latest.log:
https://gist.github.com/Eelt/c93cb1ad7354c2b4d15bb50c1620bcbd

**Steps to Reproduce:**
 1. Create a custom fluid that uses `LiquidBlock`'s constructor that takes in a supplier (line 58)
 2. Run the game and place the fluid
 
Basically having an issue with `LiquidBlock#fluid` in that anything that calls this using the non-deprecated constructor will have the fluid left as null, and anything that calls `LiquidBlock#fluid` (eg. `LiquidBlock#shouldSpreadLiquid`, `LiquidBlock#neighborChanged`, etc). Which causes various crashes relating to the fluid being null, preventing me from porting my fluids over to 1.17.

I'm aware that this is under a TODO.

**Comment by AterAnimAvis** [comment]
Related and fixed by Fluid Overhaul PR: #7992
