### ISSUE TITLE
ForgeRenderTypes do not define a ShaderState

### ISSUE THREAD

**Issue by malte0811** [MinecraftForge/MinecraftForge#7928]
**Minecraft Version:** 1.17.1

**Forge Version:** Tested on 37.0.2, confirmed in code in 6ddf56ef158af0282696f33d10ebed452a751375 (current latest 1.17 commit)
**Logs:** Not relevant

**Steps to Reproduce:**
 1. Define a layered item model using render types from `ForgeRenderTypes`, e.g. by using the `forge:bucket` loader.
 2. Observe a crash when the item is rendered.

**Description of issue:** In 1.17 render types need to define a `ShaderState`, otherwise `BufferUploader._end()` will throw an NPE. None of the render types in [`ForgeRenderTypes`](https://github.com/MinecraftForge/MinecraftForge/blob/6ddf56ef158af0282696f33d10ebed452a751375/src/main/java/net/minecraftforge/client/ForgeRenderTypes.java) define one, defining them should also address the `TODO`s in that class.

A related thought: Is there ever a situation where a `RenderType` without a `ShaderState` makes sense in 1.17? If there isn't it might be a good idea to throw in `CompositeRenderType::new` if the parameter has a `null` shader state.

**Comment by gigaherz** [comment]
Fixed in 80d08dbf3a8e0341962c23dc4737b9af289ef7de
