### ISSUE TITLE
[1.17.x] StructureSpawnManager breaks structure based mob spawns

### ISSUE THREAD

**Issue by SilverDavidMC** [MinecraftForge/MinecraftForge#7935]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.12

**Logs:** N/A

**Steps to Reproduce:**
 1. Go to an Ocean Monument, Witch Hut, etc.
 2. Run `StructureSpawnManager.getStructureSpawns(...).unwrap()` for a position inside the structure and print the output list.

**Description of issue:**
The `StructureSpawnManager` sets the spawn list for a structure to an empty `WeightedRandomList` in `gatherEntitySpawns` if mob spawns have been added for the relevant mob category.
https://github.com/MinecraftForge/MinecraftForge/blob/0ea9401d90573383cc3d6a0461a2ced8898e9d4c/src/main/java/net/minecraftforge/common/world/StructureSpawnManager.java#L79

**Comment by sciwhiz12** [comment]
This seems to have been fixed by #8020.

**Comment by TheCurle** [comment]
Confirmed.
