### ISSUE TITLE
stuck on safe mode help!

### ISSUE THREAD

**Issue by portalxd6** [MinecraftForge/MinecraftForge#7948]
how to fix?

**Comment by TheCurle** [comment]
I fail to see how "safe mode" is something we can reasonably support.

**Comment by portalxd6** [comment]
how ı can fix it help!

**Comment by portalxd6** [comment]
okay ı sorry ıts just one outdated mod issue

**Comment by gigaherz** [comment]
Please keep in mind that the issue tracker is not the place to ask for help. We have [the forums](https://forums.minecraftforge.net/) and [Discord server](https://discord.gg/UvedJ9m) as the proper ways to ask for end-user help.
