### ISSUE TITLE
[1.17.1] ClasspathLocator fails to validate manifests

### ISSUE THREAD

**Issue by Janrupf** [MinecraftForge/MinecraftForge#7957]
**Minecraft Version:** 1.17.1

**Forge Version:** 1.17.1-37.0.13

**Logs:** [latest.log](https://paste.labymod.net/totimocuhi.sql) (Note, see below for identified issue, the log is only added for completeness)

**Related to:** https://github.com/MinecraftForge/MinecraftForge/commit/7d4c23816590087e0baa995425a24051b98a1fae

**Steps to Reproduce:**
 1. Create an empty gradle project
 2. Add a forge mod as a gradle subproject
 3. Add a java library as a gradle subproject
 4. Configure gradle to add `FMLModType: LIBRARY` to the manifest of the java library
 5. Add an `implementation` dependency
 6. Add any class to the library
 7. Reference the class from your mod in some start event handler (or statically, doesn't matter)
 8. Observe a `ClassNotFoundException`  

**Description of issue:**
This seems to be an issue which occurred while porting over the `ClasspathLocator` from Forge 1.16. 
In Line `97` `sj.getRootPath()` is called, returning `/` on Unix systems (and I would guess `<drive letter>:\` on NT systems). This ends up in an `IOException`, as the root directory is not a jar file.

https://github.com/MinecraftForge/MinecraftForge/blob/7d4c23816590087e0baa995425a24051b98a1fae/fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ClasspathLocator.java#L97

**Proposed fix:**
From what I can tell, the wanted method seems to be `SecureJar#getPrimaryPath()`. This (correctly) returns the full path of the Jar file.

**Comment by SizableShrimp** [comment]
This fix is included in https://github.com/MinecraftForge/MinecraftForge/pull/7947

**Comment by thedarkcolour** [comment]
Here's a test for this issue regarding language providers:
<details>
<summary>Copied from #8090</summary>

**Forge Version:** 37.0.67
**Steps to Reproduce:**
 1. In a git bash or cmd prompt, run `git clone --branch 2.x https://github.com/thedarkcolour/KotlinForForge` to get KFF for 1.17 (as a test language provider)
 2. Run `gradlew --refresh-dependencies` to import Gradle and Forge
 3. Run `gradlew genIntellijRuns` or the equivalent for your IDE to get the run configurations
 4. Use `runClient` to get the first image/log
 5. Run `gradlew build` to get compiled mod jar `kotlinforforge-2.0.0-obf.jar` and run in a game launcher to get second image/log
</details>
