### ISSUE TITLE
[1.17.1] EntityJoinWorldEvent not firing on Server for existing entities

### ISSUE THREAD

**Issue by Cobbs3** [MinecraftForge/MinecraftForge#7962]
**Minecraft Version**: 1.17.1

**Forge Version**: 1.17.1-37.0.13

**Logs**: Not Applicable

**Steps to reproduce**:
Implement EntityJoinWorldEvent
Server side, log the names of every entity's class that joins
Load a save game / start a server
Only the player and newly spawned entities show up

**Description**:
The event only fires for newly created entities where the documentation suggests it should also fire when saved entities are loaded for the first time. It does fire in this way on the client and did in 1.16.5 on both sides. Wanted to check if this is an intended change or a bug.

**Comment by ricksouth** [comment]
EntityJoinWorldEvent is also not fired for Villager entities in newly created villages. I assume this is part of the same issue. Only in 1.17.1.

**Comment by ricksouth** [comment]
Also not fired for Mooshroom cows spawned fresh in a mushroom biome.

**Comment by Xyndra** [comment]
I've got the same error too
