### ISSUE TITLE
More types in BiomeDictionary.

### ISSUE THREAD

**Issue by Angular-Angel** [MinecraftForge/MinecraftForge#7965]
Going to comment to say I think that biomes should have more tags and/or types - by specific tree type would be nice, for example. Also, the absence of a tag should NEVER be used to communicate information other than the absence of the tag. For example, with the tree-based tags, 'Specifying no tag implies a biome has temperate trees (Such as Oak)', but what if someone adds a new category, such as arctic, desert, or volcanic trees, or wants to tag their biome as having no trees at all? Now any biome that has those types/tags is going to also scan as temperate. Also, checking !SAVANNA and !CONIFEROUS and !JUNGLE is way more annoying than just checking TEMPERATE. I'd be prepared to write  PR for this, if I can expect to see it merged.

**Comment by Thelnfamous1** [comment]
There should be enough types such that each of the vanilla biomes and modded ones that are very similar can be identified through their types. For example, having all nether biomes only use “HOT, DRY, NETHER” is kind of annoying when trying to make sure X only spawns in Crimson Forest-type biomes and necessitates having to create a custom type for each. Things like “CRIMSON”, “WARPED”, “DELTA”/“BASALT” and “SOULSAND” would be ideal for each of them.

**Comment by SizableShrimp** [comment]
`BiomeDictionary` was removed in Forge 1.19 with the much better `BiomeModifier` system. Please use that instead. This issue is resolved, as we are not planning on changing anything about `BiomeDictionary` on LTS versions and it is removed in the Latest version (currently 1.19.x).
