### ISSUE TITLE
RFC - Remove ForgeRegistryEntry and ForgeRegistries being Type bound

### ISSUE THREAD

**Issue by Cyborgmas** [MinecraftForge/MinecraftForge#7969]
This would allow to make any registry a forge registry.
- Right now functional interfaces can't be forge registries
- Can't have more than one registry per class, while mojang for instance has 2 Codec registries (`BIOME_SOURCE` and `CHUNK_GENERATOR`).

This would however mean registry objects won't be aware about being in a registry, so `#setRegistryName` and `#getRegistryName` would be no more.

However, there would still be a need to handle delegates so a `DelegatedRegistryEntry` might be needed where possible, but would not be a requirment.

Is this desired by forge/modders ? Have I missed any constraints about this change?

**Comment by LexManos** [comment]
Yes, sometime in the future we need to re-write the Forge registry system to not be IForgeRegistryEntry based. This will be a fundemental shift in the way that registry entries work tho. They will no longer know what registry they belong to. All related functions, ObjectHolders, Delegates, Register events, etc... would need to be redesigned.
Its a really large project that has no real need right now. So it hasn't been worked on.

**Comment by Cyborgmas** [comment]
Worked on this a while back, but did not have time to continue. 

If anyone wants to continue working on this, feel free to use [what I've done](https://github.com/Cyborgmas/MinecraftForge/tree/rewrite-registries-118) and to ping me on discord for any questions about my work.

The main thing that is missing is a way to handle re-registration, i.e. data-driven objects, like Biomes. 
Also needs a lot of testing eventually, porting worlds could cause issues.

**Comment by userofbricks** [comment]
It would be really nice if something like the deferredRegister system was kept. It is my primary way of registering things. However that said it could be really nice if it worked off of the vanilla classes instead of forge ones. This my already be the case as I’m not at my computer right now and it has been a while since I had to start afresh with a mod.

**Comment by SizableShrimp** [comment]
As discussed on #8538, this change will be included in Forge 1.19.
To see (most of) the upcoming changes, please view #8538 (based on 1.18.2).
IForgeRegistryEntry/ForgeRegistryEntry will no longer exist, and IForgeRegistry/ForgeRegistry no longer has a type bound.

**Comment by sciwhiz12** [comment]
The registry rework has been published in 1.19, which means this RFC is complete. Goodbye `IForgeRegistryEntry`, you had a good run.
