### ISSUE TITLE
LiquidBlock doesn't use Supplier in shouldSpreadLiquid

### ISSUE THREAD

**Issue by rehwinkel** [MinecraftForge/MinecraftForge#8002]
**Minecraft Version:** 1.17.1
**Forge Version:** 37.0.33
**Logs:** https://gist.github.com/rehwinkel/9b62e91ab2926fb7847cdd7ee08c1307

**Steps to Reproduce:**
 1. Create a Fluid and a LiquidBlock referencing that Fluid using the Supplier-Constructor.
 2. Place Fluid in World using Bucket
 3. Error appears in Console, Fluid is briefly placed, then disappears.

**Description of issue:**
This issue is due to the Supplier-Constructor of LiquidBlock setting `this.fluid = null;`, which causes an NPE in `shouldSpreadLiquid` because that method uses `this.fluid` instead of `this.getFluid()`.

**Comment by rehwinkel** [comment]
Fixed by Fluid Overhaul PR: #7992

**Comment by remplerus** [comment]
same request as #7922

**Comment by AterAnimAvis** [comment]
Closing as duplicate of #7922
