### ISSUE TITLE
[1.17.1] Forge NoSuchMethodError | net.minecraft.client.Minecraft.m_91087_()

### ISSUE THREAD

**Issue by hrenacher228** [MinecraftForge/MinecraftForge#8010]
'net.minecraft.client.Minecraft net.minecraft.client.Minecraft.m_91087_()'

Minecraft.getInstance().getUser().getName()
After compiling the mod into a jar
Minecraft.m_91087_().m_91094_().m_92546_()

**Comment by Harleyoc1** [comment]
Are you running this code on a server? Keep in mind that `Minecraft` is a client-only class. 

(either way this issue tracker is not meant for support, this does not look like a Forge issue)

**Comment by hrenacher228** [comment]
@Harleyoc1 I ran this on the client
Exception in thread "Thread-11" java.lang.NoSuchMethodError: 'net.minecraft.client.Minecraft net.minecraft.client.Minecraft.m_91087_()'

**Comment by gigaherz** [comment]
Can you come over to the forge discord and ask in the #modder-support-117 channel? Github issues are meant for actual bugs in the code and not to get tech support.

**Comment by hrenacher228** [comment]
@gigaherz 
Can you give me an invite to the forge discord server,
Isn't this a compiler error?

**Comment by gigaherz** [comment]
<https://discord.gg/UvedJ9m>

**Comment by hrenacher228** [comment]
It turned out that I created a mod for the regular version of Minecraft (not dev) and tried to run it on the dev version
