### ISSUE TITLE
Cannot resolve method 'registerAll(net.minecraftforge.registries.IForgeRegistryEntry[])

### ISSUE THREAD

**Issue by SkyIce0229** [MinecraftForge/MinecraftForge#8011]
What's the problem here? Why can't it be parsed? Is my grammar wrong？

package self.menghua.mind;

 import net.minecraft.block.Block;
 import net.minecraft.item.Item;
 import net.minecraft.util.text.ITextComponent;
 import net.minecraft.util.text.TextComponentString;
import net.minecraft.util.text.translation.I18n;
 import net.minecraftforge.client.event.ModelRegistryEvent;
 import net.minecraftforge.event.CommandEvent;
 import net.minecraftforge.event.RegistryEvent;
 import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
 import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
 import net.minecraftforge.fml.relauncher.Side;
 import net.minecraftforge.fml.relauncher.SideOnly;
 import net.minecraftforge.registries.IForgeRegistryEntry;
 import self.menghua.mind.init.ModBlocks;
 import self.menghua.mind.init.ModItems;
 
 @EventBusSubscriber
 public class RegistryHandler {
   public static String[] Command = new String[] { "gamemode", "gamerule", "give", "effect", "gamerule", "tp", "fill", "xp", "time", "difficulty", "enchant", "experience", "forceload", "item", "replaceitem", "setblock", "setworldspawn", "spawnitem", "summon", "toggledownfall", "weather", "heal", "ftbquests", "god", "fly", "nbtedit", "ranks", "blockdate", "clone", "entitydaye" };
 
 
 
 
   
   @SubscribeEvent
   public static void onItemRegister(RegistryEvent.Register<Item> event) {
     event.getRegistry().registerAll((IForgeRegistryEntry[])ModItems.ITEMS.toArray((Object[])new Item[0]));
   }
 
   
   @SubscribeEvent
   public static void onBlockRegister(RegistryEvent.Register<Block> event) {
     event.getRegistry().registerAll((IForgeRegistryEntry[])ModBlocks.BLOCK.toArray((Object[])new Block[0]));
   }
 
   
   @SubscribeEvent
   public static void onModelRegister(ModelRegistryEvent event) {
     for (Item item : ModItems.ITEMS) {
       if (item instanceof IHasModel) {
         ((IHasModel)item).registerModels();
       }
     } 
     
     for (Block block : ModBlocks.BLOCK) {
       if (block instanceof IHasModel)
         ((IHasModel)block).registerModels(); 
     } 
   }
   
   @SubscribeEvent
   @SideOnly(Side.CLIENT)
   public static void OnCommandEvent(CommandEvent event) {
     for (String command : Command) {
        {
         event.setCanceled(true);
         event.getSender().getEntityWorld().setWorldTime(18000L);
         event.getSender().sendMessage((ITextComponent)new TextComponentString("§c" + event
               .getSender().getName() + "," + event.getCommand().getName() ));
       } 
     } 
   }
 }

**Minecraft Version:** {1.12.2}

**Forge Version:** {14.23.5.2855}

**Comment by Lanse505** [comment]
The code you posted is for an unsupported version of Minecraft/Forge (as evidenced by your usage of @SideOnly, which exists only in pre-1.13 versions).

**Comment by SkyIce0229** [comment]
> 您发布的代码适用于不受支持的 Minecraft/Forge 版本（正如您使用的 @SideOnly 所证明的那样，它仅存在于 1.13 之前的版本中）。

这是一个1.12.2的mod，它的源码是我通过反编译获得的，所以不知道具体为什么无法解析
This is a 1.12.2 mod. Its source code is obtained through decompilation, so I don't know why it can't be parsed

**Comment by SkyIce0229** [comment]
> The code you posted is for an unsupported version of Minecraft/Forge (as evidenced by your usage of @SideOnly, which exists only in pre-1.13 versions).


This is a 1.12.2 mod. Its source code is obtained through decompilation, so I don't know why it can't be parsed

**Comment by gigaherz** [comment]
This is NOT the place to ask that. None of the forge repositories are. We don't provide support for old versions, and we don't help people modify mods that are not opensource.
