### ISSUE TITLE
Game crashes with "Colliding entity with block" when testing Twilight Forest mod

### ISSUE THREAD

**Issue by PechayClub** [MinecraftForge/MinecraftForge#8015]
**Twilight Forest Version:** 4.0.577 (Also happened in 4.0.569 and 4.0.566.)

**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.34 (That also happened in 37.0.33)

**Logs:** https://gist.github.com/Pechayland/6bd112690ff688e26c1d97bfc376861f

**Steps to Reproduce:**
 1. Go to the Twilight Forest. (Maybe other mods are affected?)
 2. See glitched loading screen.
 3. Crash.

**Description of issue:**
The loading screen glitches like this before the game crash:
![2021-08-13_18 03 10](https://user-images.githubusercontent.com/65995040/129341711-8555cba8-69ba-49c2-8ebe-c62cb3d1d773.png)

**Comment by TheCurle** [comment]
This is an issue with how Twilight Forest has set up their Reflection. Not something we can fix.

**Comment by PechayClub** [comment]
Thanks
