### ISSUE TITLE
Malfunctioning screen buffer

### ISSUE THREAD

**Issue by TeraV8** [MinecraftForge/MinecraftForge#8034]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.34

**Logs:** https://gist.github.com/TeraV8/7e60bf3c60842b1d2b8eae59e6ffe74c

**Steps to Reproduce:**
Unknown. Issue occurred without warning or trigger.

**Description of issue:**
A large portion of the screen buffer was experiencing a malfunction consisting of displaying flickering images of old frames and the current frame. The issue was exhibited only in the Minecraft window. It was recorded, but the recording shows no sign of the event (other than my reaction).

Mods used:
- Xaero's World Map 1.16.1_Forge_1.17.1
- Xaero's Minimap 21.15.1_Forge_1.17.1

OS: Linux version 5.12.19-hardened1-1-hardened (linux-hardened@archlinux) (gcc (GCC) 11.1.0, GNU ld (GNU Binutils) 2.36.1) #1 SMP PREEMPT Tue, 20 Jul 2021 17:48:41 +0000
X11 version: 1.20.13-2
Graphics device: AMD Radeon HD 5450

**Comment by TheCurle** [comment]
This sounds like an issue with your desktop environment / compositor. If a recording from the raw GLFW window shows no issue, this issue cannot be diagnosed or fixed by us.
