### ISSUE TITLE
/locatebiome and /locate command small bug in dev.

### ISSUE THREAD

**Issue by marios-andr** [MinecraftForge/MinecraftForge#8035]
Minecraft Version: 1.17.1
Forge Version: 37.0.45

When you use the /locatebiome or /locate command the output in the chat highlights the coordinates of the biome/structure and makes you able to click them to automatically fill your terminal with the command to teleport to the biome/structure. But this does not appear to be the case when you're in the dev environment. Coordinates are accurate you just can't click them. This is a small bug but quite annoying if you're working with biomes and structures. I also checked outside the dev environment in the same versions and it works fine.

**Comment by Badernnbbxx** [comment]
H

**Comment by marios-andr** [comment]
> H

Excuse me?

**Comment by sciwhiz12** [comment]
Could not replicate this issue on `1.17.1-37.0.47`, both in userdev and forgedev environments: I am able to use `/locate` and `/locatebiome`, and clicking on the highlighted coordinates in the chat window inserts the teleport command correctly into the chat message bar (and the teleport command works).

**Comment by marios-andr** [comment]
I see, then it's a problem with my minecraft, although I'm not sure what could cause it since I didn't do anything to interfere with it. Thank you.
