### ISSUE TITLE
Mod crashes without crash log when versionRange/mod is (set to) the wrong version

### ISSUE THREAD

**Issue by ricksouth** [MinecraftForge/MinecraftForge#8036]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.45

**Logs:** debug.log: https://gist.github.com/ricksouth/9d4e193ef6d196784d79a31f28435513

**Steps to Reproduce:**
 1. Include a mod in Forge which has the version set wrongly. I found the error via https://www.curseforge.com/minecraft/mc-mods/better-jumping. MCCreator goodness (not). This mod has set the Minecraft version to 1.17, but the mod is made for 1.16.
 2. Load the game. It crashes without an error log.

**Literally all versions have been added to it on CurseForge.**
![](https://i.imgur.com/KBBLJUA.png)

**Description of issue:**
### The problem occurs when scrolling through mods and adding interesting ones. Then launching the modpack to see if it works. But the game exits without a crash log. Making finding the culprit very difficult.

In this case the mod has the following mods.toml:
```
[[dependencies.better_jump]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
```

This was logged (sort of) in the debug.log, at the end:
`Found 1 mod requirements missing (1 mandatory, 0 optional)`

However it does not state which mod. Nor what the missing mandatory requirement is. In this case 1.16.5 Forge but the environment is 1.17.1.

A solution would be to improve the information shown in
```
[net.minecraftforge.fml.loading.moddiscovery.ModFileInfo/LOADING] or
[net.minecraftforge.fml.loading.moddiscovery.ModFile/LOADING].
```

To include what the missing requirement is.

**Comment by SuperMartijn642** [comment]
I think this is the same as #7993. Outside of the dev environment, if any dependency is not fulfilled, the game exits without the mod loading error screen and without generating a crash report.

**Comment by ricksouth** [comment]
Yea this is basically a dependency on the wrong Forge version. Not entirely duplicate as it's not a mod dependent but it stems from the same issue.
