### ISSUE TITLE
Extended bundle tooltip not rendered

### ISSUE THREAD

**Issue by MelanX** [MinecraftForge/MinecraftForge#8037]
**Minecraft Version:** 1.17.1
**Forge Version:** 37.0.45

**Steps to Reproduce:**
 1. `/give Dev minecraft:bundle`
 2. Add an item to the bundle
 3. Hover over the bundle

**Description of issue:**
No extended rendering for the bundle.
Wrong: 
![image](https://user-images.githubusercontent.com/26039509/131258287-4a0a6bd8-9dc5-4feb-9851-d1e075a5857a.png)

Right: 
![image](https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c1/MinecraftBundle.jpg)

**Comment by diesieben07** [comment]
This is caused by Forge's tool tip hooks. I'm working on a rewrite/cleanup.

**Comment by Mysterious-Dev** [comment]
And maybe add an hook for custom tooltip like bundle ?

**Comment by diesieben07** [comment]
Yes, already exists in vanilla :) The system is already pluggable

**Comment by Mysterious-Dev** [comment]
Yep, but render of 1.17 tooltip is hardcoded if I'm not mistaken.

**Comment by noeppi-noeppi** [comment]
> The system is already pluggable

Not really... You can create custom `TooltipComponent`s on the server side but when the client converts them into a `ClientTooltipComponent`, it fails if it is not a `BundleTooltip`. This happens in `ClientTooltipComponent#create(TooltipComponent)`. Maybe a forge patch is necessary there.

**Comment by diesieben07** [comment]
Ah you are right noeppi. I'll add something for that.
