### ISSUE TITLE
ModConfigEvent is fired too late

### ISSUE THREAD

**Issue by rikka0w0** [MinecraftForge/MinecraftForge#8045]
The `ModConfigEvent` is fired after the `EntityAttributeCreationEvent`, making it impossible to load customized attributes from config files.

I would suggest that, the config should be loaded as early as possible (just after the registration phase is complete).

**Comment by ChampionAsh5357** [comment]
Configs are loaded directly after registration is finished and frozen. `EntityAttributeCreationEvent` is fired directly after the registries are loaded to check if they can revert to vanilla.

If you wanted to add configuration data, you could simplify add attribute modifiers to your entity with the base attributes being static. It will function the exact same as changing the loading order as mentioned above. For that reason, this will not be changed.
