### ISSUE TITLE
Mods with "forge" in jar name not loading in 1.17.1-37.0.53

### ISSUE THREAD

**Issue by klikli-dev** [MinecraftForge/MinecraftForge#8063]
Mods with "forge" in jar name not loading in 1.17.1-37.0.53
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.53

**Logs:** https://gist.github.com/klikli-dev/8b34b63c3b17d3f3cd7f72d9208b716f

**Steps to Reproduce:**
 1. Add the curios maven to `repositories {}:`
 ```
    maven {
        name = "Curios Maven"
        url = "https://maven.theillusivec4.top/"
    }
 ```
 2. Add curios to `dependencies {}`
 ```
 compileOnly fg.deobf("top.theillusivec4.curios:curios-forge:1.17.1-5.0.0.1:api")
 runtimeOnly fg.deobf("top.theillusivec4.curios:curios-forge:1.17.1-5.0.0.1")
 ```
 3. Build + runClient 

**Description of issue:**

Mods that contain "forge" in the jar name are not loaded on runClient. 
If they are a mandatory dependency, the dependency check will warn it is missing, if they are not set as dependency classloading will fail. 

While .29 fixed a similar issue in bootstraplauncher, the equivalent logic ClasspathLocator was not updated, leading to this issue. 

A temporary workaround is to update the ignoreList via build.gradle to contain the current forge version: `property 'ignoreList', "bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,client-extra,fmlcore,javafmllanguage,mclanguage,forge-${forge_version}"`.

**Comment by sciwhiz12** [comment]
This was fixed by 5e2e4048289077f3ab3e0505362d0e7a5d8eb944, released as `1.17.1-37.0.75`.
