### ISSUE TITLE
JEI- 1.15.5-7.7.1.121 ON SERVER  :  Not Showing Any Recipes Besides Default Minecraft Ones 

### ISSUE THREAD

**Issue by SlickEcho** [MinecraftForge/MinecraftForge#8067]
**Minecraft Version:** {1.16.5}

**Forge Version:** {Forge-1.16.5-36.2.2)

**Logs:** No errors in Logs to report

**Steps to Reproduce:**
Setup Minecraft server and install same versions of Forge, JEI, and jeiintegration- 1.16.5-7.0.1.15. Add tinker construct to see one example of my issue. 

**Description of issue:*
Small server with only 25 mods or so. Most issues have been with Minecraft version and just bad luck of mods not working proper; however, jei I've installed like 4 different versions and all the same issue. I've also changed my optifine version to G7 and that fixed a shading issue but I've researched for like two days now and can't find a solution. 

Notes:
I have tried basically the top 10 on google search for solutions and none of them worked.
I have the same mods and versions of mods in my local and server mod folder. 
Hosting site is Hostinger (which could be the problem in of its self) with my luck).
Only Minecraft has working recipes but every single one of my mods recipes do not work at all, I have a few that will show information about the spawning or other information related to it. 

(also first post ever here so I do apologize if this is in the wrong spot or doesn't retain the correct information for finding solutions)

**Comment by gigaherz** [comment]
This is the Minecraft Forge repository, not the JEI repository. You need to ask the authors of JEI or JEIIntegration, there's probably issue tracker links in their mod pages.
