### ISSUE TITLE
BlockFlag has wrong JavaDoc

### ISSUE THREAD

**Issue by rlnt** [MinecraftForge/MinecraftForge#8082]
**Minecraft Version:**
1.16 and 1.17

**Forge Version:**
1.16.5 - 36.2.4
1.17.1 - 37.0.61

**Description of issue:**
The BlockFlag for `UPDATE_NEIGHBORS` has a wrong Javadoc.
Currently it mentions that neighbors would be updated when passing the flag but the exact opposite is the case, it prevents it.
https://github.com/MinecraftForge/MinecraftForge/blob/b027a92dd287d6810a9fdae4d4b1e1432d7dc9cc/src/main/java/net/minecraftforge/common/util/Constants.java#L184

This can be seen in `net.minecraft.World#markAndNotifyBlock()`:
```
if ((pFlags & 16) == 0 && pRecursionLeft > 0) {
  int i = pFlags & -34;
  blockstate.updateIndirectNeighbourShapes(this, pPos, i, pRecursionLeft - 1);
  pState.updateNeighbourShapes(this, pPos, i, pRecursionLeft - 1);
  pState.updateIndirectNeighbourShapes(this, pPos, i, pRecursionLeft - 1);
}
```

**Comment by TheCurle** [comment]
With 1.17 deprecated and the Constants class removed in 1.18, this remains as a matter of LTS.

A 1.16 omnibus will fix this in the future, but time scales can't be determined right now.

**Comment by sciwhiz12** [comment]
1.16.x is now unsupported.
