### ISSUE TITLE
CraftingHelper.getItemStack does not throw a JsonSyntaxException for unknown items

### ISSUE THREAD

**Issue by ochotonida** [MinecraftForge/MinecraftForge#8086]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.67

**Logs:** -

**Steps to Reproduce:**
 1. Pass a JsonObject with an unknown item to `getItemStack` in `CraftingHelper`
 2. The method returns an empty stack instead of throwing an exception

**Description of issue:**
`getItemStack` throws an exception when the result of `ForgeRegistries.ITEMS.getValue` is null. Because `getValue` returns the default value (`minecraft:air`) for invalid keys, the exception is never thrown

**Comment by ChampionAsh5357** [comment]
Closed by #8105. Air will be properly disallowed in vanilla recipes in 1.18 unless otherwise stated by Mojang's implementation with the changes made in the PR.
