### ISSUE TITLE
[1.17.1] PermissionsChangedEvent logic prevents op changes for online players when NOT cancelled

### ISSUE THREAD

**Issue by AterAnimAvis** [MinecraftForge/MinecraftForge#8088]
**Minecraft Version:** 1.17.1

**Forge Version:** 1.17.1-37.0.55+

**Logs:** N/A

**Steps to Reproduce:**
 1. Start a Server
 2. run a `/op` of an online player
 3. `op.json` file won't update / the player is not opped

**Description of issue:**
<https://github.com/MinecraftForge/MinecraftForge/blob/675bf8bde2a58fd69f6baea334fc6d72f30f7ef5/src/main/java/net/minecraftforge/event/ForgeEventFactory.java#L789-L798>
`EventBus#post` returns `true` if the event is cancelled. The current logic of the hook and it's usage are based on the premise that `true` is continue to process.

This breaks op-ing and deop-ing of online players in Forge Versions .55+ <https://github.com/MinecraftForge/MinecraftForge/pull/8023>

*From Discord Report*

**Comment by TheCurle** [comment]
Thanks for the swift write-up.
