### ISSUE TITLE
(1.17.1) Blocks like Gravel or Sand do not obey gravity under y Coordinates 0

### ISSUE THREAD

**Issue by Inonedn** [MinecraftForge/MinecraftForge#8091]
**Minecraft Version:** 1.17.1

**Forge Version:** 1.17.1-forge-37.0.68

**Steps to Reproduce:**
 1. Enable the C&C Datapack or a dimension that goes under 0 coordinates
 2. Place either Anvils, Gravel, or Sand. Dripstone seems to work
 3. Block is floating

**Description of issue:**
Blocks under Y coordinates 0 do not obey gravity despite the world height being extendable

**Comment by alcatrazEscapee** [comment]
Forge patches out a call to `Level#getMinBuildHeight` and replaces it with `0`... that would be the issue I should think

https://github.com/MinecraftForge/MinecraftForge/blob/b2dbe9de51d6b03cb0badd79e97e9d9e26b25b36/patches/minecraft/net/minecraft/world/level/block/FallingBlock.java.patch#L7-L8

**Comment by sciwhiz12** [comment]
From investigating the patch as it was in 1.16.x vs now in 1.17.x, this is most probably a porting error: 

https://github.com/MinecraftForge/MinecraftForge/blob/a95b968c1397a1597d4a6228d8e1abce6495570e/patches/minecraft/net/minecraft/block/FallingBlock.java.patch#L7-L8

In 1.16.5 (the above commit snippet), the patch added a call to (what is now) `LevelReader#isEmptyBlock`, which is patched to use the positional `isAir` extension method provided by Forge. 

In 1.17.1, the positional `isAir` method was removed (see https://github.com/MinecraftForge/MinecraftForge/issues/7409#issuecomment-888279149), which meant that this specific patch in FallingBlock was useless and removed: `m_53241_` is the static method `isFree` which includes a check that calls the regular `isAir`, and the `isEmptyBlock` method was reverted to calling the regular `isAir`, so no loss of functionality with regards to `isAir`.

However, the porting issue is I presume a copy-paste from 1.16.5 to 1.17.1, which overwrote the `Level#getMinBuildHeight` call with 1.16's `0` (as world height was hardcoded then to 0-256). This means that, as the issue describes, placing any falling block below y level 0 will not cause the `if`-check to succeed even if air exists below it, and so the falling block will never create a falling block entity to actually do the fallling.
