### ISSUE TITLE
Querying capabilities from Item#getDamage causes NPE during loading

### ISSUE THREAD

**Issue by sciwhiz12** [MinecraftForge/MinecraftForge#8093]
**Minecraft Version:** 1.17.1
**Forge Version:** 1.17.1-37.0.68
**Logs:** https://gist.github.com/sciwhiz12/02cb5a5b26f7dce76137a5a78c05d262
Note that the `latest.log` contains the exception and stacktrace, not the `debug.log`

**Steps to Reproduce:**
 1. Download the following archive containing a minimal reproducible example: [`examplemod.zip`](https://github.com/MinecraftForge/MinecraftForge/files/7190907/examplemod.zip)

    Source is available at [`examplemod-source.zip`](https://github.com/MinecraftForge/MinecraftForge/files/7190908/examplemod-source.zip). For quick overview, the source file and recipe (`data/examplemod/recipes/damaged_item.json`) contained with the mod is available at https://gist.github.com/sciwhiz12/40a3f98d43b2fd43b56bc46c0ac01f63.

 1. Install the mod into a dedicated server with the above given Forge version.
 1. Run the server (if error does not occur, accept the EULA and try again).
 1. __Observe as the server fails to load with a datapack loading error.__

## History

This issue [was first reported](first-report) to The Forge Project discord by user `The Magic Chad#9337`, having tried to run the [All the Mods 7 modpack][atm7] with Forge version 37.0.68 and failing because of an error during server loading.

After the report and confirming provisionally through code review of the mod involved ([ElementalCraft][elementalcraft] by @Sirttas) and Forge that the issue seems to be a Forge issue, I first confirmed that the issue exists through an installation of a Forge server with the above version and the aforementioned mod (along with its two dependencies).

Having confirmed the issue with the above setup, Iproceeded to create the minimal reproducible example mod attached above, and tested that it crashes when ran in the user development environment and in the Forge server installation. The log given above is from the Forge server installation with the MRE mod.

## Description of issue

The core issue lies with the following lines in the method:

https://github.com/MinecraftForge/MinecraftForge/blob/30a33f5c3eee95337179c1df276c372eea8cea8c/src/main/java/net/minecraftforge/common/capabilities/CapabilityProvider.java#L89-L93

The problem is that when the call to `doGatherCapabilities` is reached, `lazyParentSupplier` is almost certain to be `null` (as the code which sets its value is in `doGatherCapabilities` itself). As `lazyParentSupplier` is `null`, this cause an NPE when `get` is called on the supplier.

This error situation can be reached if a mod's custom item overrides `getDamage` (or any method called from `ItemStack`'s constructor, chiefly prominent being `getDamange`) and from that method queries any capability, and an item stack is created with that item -- in this case, a recipe triggers the creation of the item stack with the custom item, which triggers the above situation.

[first-report]: https://discord.com/channels/313125603924639766/437001959950778368/888947502164889680
[atm7]: https://www.curseforge.com/minecraft/modpacks/all-the-mods-7
[elementalcraft]: https://www.curseforge.com/minecraft/mc-mods/elemental-craft

**Comment by marchermans** [comment]
Interesting. Indeed if you would access the `CapabilityProvider` in `getDamage(ItemStack stack)` then this issue arises. 

Checking the original code before #7945 and #8085 was merged, this would have never properly worked in the first place, since `gatherCapabilities` was not called.

Although right now this throws an exception because people actually tried to access the `CapabilityProvider`, the proper fix would be to call `forgeInit` before the: 
```java
if (this.item != null && this.item.isDamageable(this)) {
   this.setDamageValue(this.getDamageValue());
}
```
section. This would fix the issue permanently, including properly loading the capabilities properly, with the proper NBT data before the call.

**Comment by marchermans** [comment]
@sciwhiz12 Talked about this internally.
Your null pointer is a good idea, but does not actually solve the issue.

To solve it I would suggest moving the `forgeInit` call to after the `delegate` is initialized.
