### ISSUE TITLE
[1.17, 1.18] Textures smaller than 16x16 cannot be used in resource packs, modded or otherwise

### ISSUE THREAD

**Issue by shittothecore** [MinecraftForge/MinecraftForge#8094]
**Minecraft Version:** {1.17.1}

**Forge Version:** {37.0.61}

**Logs:** {[latest.log](https://gist.github.com/shittothecore/cf108d3131a48951f0ea1526ee7853c8)}

**Steps to Reproduce:**
 1. Place resource pack archive in to .minecraft/resourcepacks/
 2. Launch minecraft and load resourcepack from main menu or in game pause menu
 3. Load in to world/unpause to get a better look

**Description of issue:**
GUI textures load but in game textures do not work, purple and black missing textures display on blocks etc, the resourcepacks I tried worked in vanilla minecraft.

**Comment by diesieben07** [comment]
Does this happen with any resource pack?

**Comment by shittothecore** [comment]
@diesieben07 I only tried two but it happened with both of them, Pollachius and simply8x8 if there's one you want me to try lmk

**Comment by AterAnimAvis** [comment]
Effects any textures smaller than 16 pixels.

Replicatable with the attached resource pack for `minecraft:stone` [Forge8094.zip](https://github.com/MinecraftForge/MinecraftForge/files/7192647/Forge8094.zip)
Pack format is `6` so the pack is loadable on 1.16.5 and 1.17.1 (if with a warning on 1.17.1).

[Resulting in this non-fatal stacktrace](https://gist.github.com/AterAnimAvis/0346115546064f3bafe75ddd32efa9a8)

Description:

Forge [patches](https://github.com/MinecraftForge/MinecraftForge/blob/1.17.x/patches/minecraft/net/minecraft/client/renderer/texture/TextureAtlas.java.patch#L24-L25) `Texture Atlas` to not reduce the MipMap level https://github.com/MinecraftForge/MinecraftForge/pull/3087
Following down the call chain, `MipmapGenerator#generateMipLevels` then performs mipmap level number of `>> 1` on the width / height in a loop as it generates the Mipmap textures.
This calls `NativeImage#<init>` which checks to ensure that width and height are both bigger than 0.
In the case that the original texture is smaller than 16 pixels in `width` / `height` and the mipmap level is at 4 (The default), the loop ends up trying to create a `NativeImage` with `width` / `height` of `0` (`1 >> 1`) which then throws, resulting in the missing texture.

In 1.16 `NativeImage` didn't perform these validations checks and as such didn't throw, allowing the generation to complete if even if the lower Mipmap Level Textures where invalid/corrupt.
Note that `NativeImage`'s methods overall do more validation for out of bounds positions, etc.

**Comment by Mapleshade20** [comment]
The same issue
![image](https://user-images.githubusercontent.com/62641761/139253125-029aad9c-2d2e-4c27-b807-d39495bc5f8d.png)
A resource pack was successfully loaded with my original client. However, when i download it from my server which is set up with the mod 'ServerPropertiesLAN" 1.17.1, it appeared to be wrong, and the resources are missing, failed to load.

**Comment by Mapleshade20** [comment]
P.S. you can find the resource pack at https://gitee.com/zhangchenhao15/lol/raw/master/Tank.zip

**Comment by diesieben07** [comment]
This happened in the 1.13.x update when [this patch](https://github.com/MinecraftForge/MinecraftForge/blob/3dd8c8ae6f197c75b23008f5533160b2794a1c85/patches/minecraft/net/minecraft/client/renderer/texture/TextureUtil.java.patch#L16-L24) was missed.
The relevant code is now `MipmapGenerator#generateMipLevels`. The code will attempt to generate 0-sized `NativeImage` instances, which then throws.

This just came up again on the forums (https://forums.minecraftforge.net/topic/111211-1182-4010-empty-mods-folder-8x-and-below-resource-packs-failing/).

The problem is that just not lowering the mipmap level is also not ideal, because for textures this small it will look bad. I don't how to fix this, as I know too little about the mipmapping process.
