### ISSUE TITLE
Custom ITransformationServices don't work in development environment

### ISSUE THREAD

**Issue by noeppi-noeppi** [MinecraftForge/MinecraftForge#8095]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.53

**Description of issue:**

If I understand this correctly, there is [ModDirTransformerDiscoverer](https://github.com/MinecraftForge/MinecraftForge/blob/1.17.x/fmlloader/src/main/java/net/minecraftforge/fml/loading/ModDirTransformerDiscoverer.java) to find jars with custom transformer services in the mods folder and load them into the service layer, so their transform services can be loaded. However, in development, this does not work as there is no mods folder. So the transform service is just not found.

**Comment by sciwhiz12** [comment]
Confirmed on 1.18.1-39.0.88 using a custom `ITransformationService` in userdev and in production which simply logs a message when it is loaded and initialized.
