### ISSUE TITLE
NPE when loading Obj without Mtl 

### ISSUE THREAD

**Issue by Shadlock0133** [MinecraftForge/MinecraftForge#8102]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.70

**Logs:** [latest.log](https://github.com/MinecraftForge/MinecraftForge/files/7206190/latest.log)

**Description of issue:**
Following [docs](https://mcforge.readthedocs.io/en/1.17.x/models/files/#wavefront-obj-models), I'm trying to use ,obj file for a model. There is no .mtl file paired with it. .obj file doesn't mentions any other files, and consists only of `v, vt, g, f` commands.

Looking at logs, this seems to be main cause:
```
Caused by: java.lang.NullPointerException: Cannot read field "diffuseColorMap" because "mesh.mat" is null
at net.minecraftforge.client.model.obj.OBJModel$ModelObject.lambda$getTextures$0(OBJModel.java:556) ~[forge-1.17.1-37.0.70_mapped_official_1.17.1.jar%2374%2380!:?]
```

`blockstates/transformer.json`:
```json
{
    "variants": {
        "": { "model": "rp2re:block/transformer" }
    }
}
```
`models/block/transformer.json`:
```json
{
    "loader": "forge:obj",
    "model": "rp2re:models/block/transform.obj",
    "textures": {
        "0": "minecraft:block/stone"
    }
}
```

**Comment by ChampionAsh5357** [comment]
Well that would be expected behavior. You need a `.mtl` to be able to render some textures onto the mesh within the `.obj`. You can't default a texture here since material files are stored alongside object ones making an NPE notifying you about it a good alternative.
