### ISSUE TITLE
1.7.10, 1.8.9, 1.12.2 on newer Java versions

### ISSUE THREAD

**Issue by s5bug** [MinecraftForge/MinecraftForge#8122]
- [x] I am aware that 1.7.10, 1.8.9, and 1.12.2 are considered EOL
- [x] I am aware that if I want to see this happen I will have to implement it myself

I want to be able to use older versions of Forge on newer Java versions to take advantage of [ZGC](https://wiki.openjdk.java.net/display/zgc). I'm willing to implement this myself, however I don't know where to start. I don't know how to set up a development environment for Forge itself, nor how to test whether everything actually works.

Where should I start? What do I need to look out for? How big of an undertaking will this be?

**Comment by ChampionAsh5357** [comment]
As you said, Forge does not provide support for EOL versions. Also, Forge only supports Java versions that are support by vanilla at that level, making this a non-issue.

**Comment by s5bug** [comment]
For the record, all three of those versions run perfectly well on Java 17.

![Minecraft 1.7.10, 1.8.9, and 1.12.2 all running on the same Java 17 instance](https://user-images.githubusercontent.com/7751296/134821251-c678dbf9-97aa-4033-892f-351e8b42663b.png)

Anyways, the real answer to my question was "look at https://mcforge.readthedocs.io/en/latest/forgedev/". That's where I'll start.

**Comment by snoopchallenge** [comment]
Any updates on this?

**Comment by TheCurle** [comment]
This isnt something that needs an update. It was resolved by the author. Read the threads.
