### ISSUE TITLE
RenderTooltipEvent objects have an empty ItemStack when fired by recipe book tooltips

### ISSUE THREAD

**Issue by daedalus4096** [MinecraftForge/MinecraftForge#8124]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.59

**Steps to Reproduce:**
 1. Subscribe to RenderTooltipEvent.PostBackground events in mod code
 2. Set a breakpoint in the subscribed event handler
 3. Launch the game in debug mode
 4. Open the crafting table's recipe book
 5. Mouse over a recipe button, triggering the breakpoint
 6. Observe that the result of the event's getStack() method is an empty item stack

**Description of issue:**
Mods are currently not able to rely on the presence of an ItemStack object when handling tooltip code for the recipe book.  This can prevent various tooltip-augmenting features from working as intended.

The ultimate cause of the issue appears to be in the RecipeBookPage#renderTooltip method.  Before calling renderComponentTooltip, the page must call GuiUtils#preItemToolTip with the ItemStack object returned by the hovered button's current recipe.  The recipe book page must then call GuiUtils#postItemToolTip after the call to renderComponentTooltip is complete.

**Comment by diesieben07** [comment]
Fixed by https://github.com/MinecraftForge/MinecraftForge/pull/8038
