### ISSUE TITLE
[1.17] New issue with creating Custom Sign WoodTypes

### ISSUE THREAD

**Issue by SmellyModder** [MinecraftForge/MinecraftForge#8131]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.0+

**Description:** Due to the new model system implemented by Mojang in 1.17.1, a new issue has popped up with trying to add custom signs using the features added in this PR: https://github.com/MinecraftForge/MinecraftForge/pull/7623
The method `ModelLayerLocation#createSignModelName()` is now hardcoded to use `minecraft` as the namespace when creating a new `ResourceLocation` for a given `WoodType` causing a `ResourceLocationException` to be thrown when initializing the `ResourceLocation`.

**Solution:**
Patch `ModelLayerLocation#createSignModelName()` to use of the namespace and path of a given `WoodType`.
```Java
public static ModelLayerLocation createSignModelName(WoodType type) {
      ResourceLocation location = new ResourceLocation(type.name());
      return new ModelLayerLocation(new ResourceLocation(location.getNamespace(), "entity/signs/" + location.getPath()), "main"));
}
```

**Comment by gigaherz** [comment]
~~You don't need to use those helpers. Just use `new ModelLayerLocation` directly.~~
EDIT: Err, scratch that. it's kinda more hardcoded in the SignRenderer than I thought it was.

**Comment by ShroomAgent27** [comment]
This is confirmed. Using the [CustomSignsTest](https://github.com/MinecraftForge/MinecraftForge/blob/1.17.x/src/test/java/net/minecraftforge/debug/block/CustomSignsTest.java) will produce [this crash report](https://github.com/FoalFreePress/TestingForgeMods/blob/571cadec5738cdca9292fa529f180748d0fa4ffc/crash-reports/8131/crash-2021-09-30_19.44.39-client.txt)

Edit: typos be like
