### ISSUE TITLE
Canceling EntityInteractSpecific does not work as intended for armor stands

### ISSUE THREAD

**Issue by ochotonida** [MinecraftForge/MinecraftForge#8143]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.78

**Steps to Reproduce:**
 1. Subscribe to `EntityInteractSpecific` and cancel the event
 2. Right click an armor stand with an armor item in the main hand
 3. The item is put on the armor stand despite the interaction being cancelled
 4. If the cancellationresult was not set to `SUCCESS`, the event is called again for the off hand. The item is unequipped from the armor stand and put in the off hand

**Comment by TjardH** [comment]
couldn't you solve that with an if condition in the setItemSlot and getItemBySlot method in the ArmorStand class, which checks whether the EntityInteractSpecific is canceled?

**Comment by Lupicus** [comment]
This also happens in 1.18.2, probably all versions after 1.17.1, which didn't happen in 1.16.5. It affects other entities that use Entity#interactAt (e.g. mekanism robit). The problem with cancelling is that the action is perform before the event is sent, see performInteraction in ServerGamePacketListenerImpl.
