### ISSUE TITLE
Internal Exception: Payload may not be larger than 1048576 bytes

### ISSUE THREAD

**Issue by diegomejia21** [MinecraftForge/MinecraftForge#8192]
Minecraft version 1.16.5

Forge version 1.16.5-forge-36.2.4

I have a server running on a seperate computer. I am attempting to add the mod "Allthecompressions". I've tried removing several mods with no success. Is this due to a limiting factor for the amount of mods or is it an issue on my end? The mods are exactly the same. 

[2021-11-10-1.log.gz](https://github.com/MinecraftForge/MinecraftForge/files/7516759/2021-11-10-1.log.gz)

**Comment by TheCurle** [comment]
Github seems to be having a moment, so i'll do this manually. 

Github is not the place to seek support for issues or crashes. This is for feature requests or final bug reports.

You should be on [the forums](https://forums.minecraftforge.net).
