### ISSUE TITLE
`ChoiceFormat` isn't enough to express Russian numerals

### ISSUE THREAD

**Issue by CommanderTvis** [MinecraftForge/MinecraftForge#8197]
Java `ChoiceFormat` isn't enough to express Russian numerals which are used in localization strings like `fml.menu.loadingmods`. In Russian, declension of words with numerals is based on the last digit of the numeral which `ChoiceFormat` doesn't support.

In pseudocode it works like this:
```java
    RussianNumeral numeral(int number) {
        return switch (number % 10) {
            case 1 -> RussianNumeral.ONE;
            case 2, 3, 4 -> RussianNumeral.FEW;
            case 5, 6, 7, 8, 9, 0 -> RussianNumeral.MANY;
            default -> throw new IllegalStateException();
        };
    }

    enum RussianNumeral {
        ONE,
        FEW,
        MANY,
    }
...
    RussianNumeral.ONE -> "%d мод"
    RussianNumeral.FEW -> "%d мода"
    RussianNumeral.MANY -> "%d модов"
```

I don't know how to integrate this logic into MinecraftForge, but it will certainly improve the grammar quality of the Russian translation.

**Comment by LexManos** [comment]
Unfortunately. There are many instances like this in many languages where you simply have to deal with it. Language files are not designed to have complex logic and extending that with the logger api is rather a pain. And not really worth the effort, even for the little we do already.
