### ISSUE TITLE
Can the permission system be increased?

### ISSUE THREAD

**Issue by SharpIceX** [MinecraftForge/MinecraftForge#8198]
Can the permission system be increased?

(Similar to Android's permission system)

**Comment by AterAnimAvis** [comment]
I'll point to the open pr https://github.com/MinecraftForge/MinecraftForge/pull/7780 to revamp the Permissions API, if this doesn't cover your needs, feel free to add additional information or detail to this issue or add to the discussion on that PR.

Seeing as this is incredible vague, I'm closing this for the moment.
