### ISSUE TITLE
Unnecessary durability bar methods in item extension

### ISSUE THREAD

**Issue by PepperCode1** [MinecraftForge/MinecraftForge#8201]
`IForgeItem` contains the following three methods to define how and when a durability bar should be rendered for a particular `ItemStack`: `showDurabilityBar`, `getDurabilityForDisplay`, and `getRGBDurabilityForDisplay`. However, these methods are no longer necessary and can in fact create confusion because 1.17 added exact replacements for all three. Because the `ItemRenderer` patch removes usage of the vanilla methods and replaces it with the Forge ones, the vanilla ones become completely useless.
Replacements (Forge -> Mojmap):
`showDurabilityBar` -> `isBarVisible`
`getDurabilityForDisplay` -> `getBarWidth`
`getRGBDurabilityForDisplay` -> `getBarColor`
The best solution I ended up at, after discussion in the Forge Discord, was to deprecate the `IForgeItem` methods for removal in 1.18, remove the patched lines in `ItemRenderer`, and patch the vanilla methods to redirect to the Forge methods. I may make a PR for these changes if time permits.

**Comment by TheCurle** [comment]
You're totally right. I have no idea how this slipped past us, thanks for the heads up.
