### ISSUE TITLE
[1.17.1] ITextureAtlasSpriteLoader sometimes cannot be parsed from .mcmeta

### ISSUE THREAD

**Issue by nikita488** [MinecraftForge/MinecraftForge#8204]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.109

**Logs:** https://gist.github.com/nikita488/755e6bd2ce030b1f966d6c54a6a148fd

**Steps to Reproduce:**
 1. Create a ITextureAtlasSpriteLoader
 2. Register it during FMLClientSetupEvent using MinecraftForgeClient.registerTextureAtlasSpriteLoader
 3. Have a .png file with .mcmeta file that uses this loader
 4. Run the game

**Description of issue:**
Sometimes when the game is starting, there is an error in the log that ITextureAtlasSpriteLoader wasn't loaded from .mcmeta file, and the blocks that use this texture have a missing texture.
It happens most of the time, but sometimes it works just fine (or when you reload resources when playing).
Seems like some kind of race condition to me (It's working fine in 1.16.5).

**Comment by diesieben07** [comment]
Seems `FMLClientSetupEvent` is too late for this in 1.17, because resources already start to reload while that is happening. Register it in your mod constructor and you shouldn't have this issue. The documentation will have to be adjusted or a new event introduced.

**Comment by sciwhiz12** [comment]
In 1.18, `ITextureAtlasSpriteLoader`s should be registered as early as possible, in the mod constructor. In 1.19, register during the `RegisterTextureAtlasSpriteLoadersEvent` to ensure they are registered at the proper time.
