### ISSUE TITLE
[1.17.1] Bundle is missing progress bar and item slots are misplaced

### ISSUE THREAD

**Issue by bageldotjpg** [MinecraftForge/MinecraftForge#8212]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.112

**Steps to Reproduce:**
 1. Give yourself `minecraft:bundle`
 2. Put some items in

**Description of issue:**
Vanilla 1.17.1 - as you can see, the durability/progress bar is visible on top of the item and the item slots are shown above the ID and item counter.
![image](https://user-images.githubusercontent.com/55970498/143375661-9d416835-2918-4b10-9428-df467eaa0ac7.png)
Forge 37.0.112 - the progress bar is not visible and the slots are below the item ID and item counter.
![image](https://user-images.githubusercontent.com/55970498/143375718-cae0349a-121b-43d0-8d6f-493554367e80.png)

**Comment by gigaherz** [comment]
The bars issue will be fixed in #8214
