### ISSUE TITLE
[RFC] Non-BlockEntity block capabilities

### ISSUE THREAD

**Issue by Technici4n** [MinecraftForge/MinecraftForge#8216]
Opening this issue to know if Forge would be interested in supporting capabilities offered by blocks without block entities such as composters (or cauldrons, please don't mention fluid units in this issue).
Here is a rough outline of how this would work, though I probably don't have time to implement it myself.

## A simple API extension?
Modders should just get the capability from the world:
```java
// World extension method:
public interface IForgeWorld {
    public <T> LazyOptional<T> getBlockCapability(Capability<T> cap, BlockPos pos, @Nullable Direction direction) {
        BlockState state = world.getBlockState();
        return state.getBlock().getCapability(cap, this, pos, state, direction);
    }
}
// Block method:
public interface IForgeBlock {
    public <T> LazyOptional<T> getCapability(Capability<T> cap, World world, BlockPos pos, BlockState state, @Nullable Direction direction) {
        if (hasBlockEntity(state)) return world.getBlockEntity(pos).getCapability(cap, direction);
        else return LazyOptional.empty();
    }
}
// block entity unchanged, except that getCapability() is marked as "override only" (if that's possible)
```

## What about LO invalidation?
This is the tricky part. Blocks can't reliably keep track of their lifetime... or can they? This would be quite easy with such a helper, probably a `World` patch:
```java
// In each World, would handle cap storage and chunk unloads:
Map<BlockPos, List<LazyOptional<?>> blockCapMap;
// Register a cap to be invalidated when the pos is unloaded, or manually with invalidateCapsAt(pos) below.
public T LazyOptional<T> invalidateOnUnload(BlockPos pos, LazyOptional<T> opt) {
    blockCapMap.computeIfAbsent(pos, p -> new ArrayList<>()).add(opt);
    return opt;
}
public void invalidateCapsAt(BlockPos pos) {
    List<LazyOptional<?>> opts = blockCapMap.remove(pos);
    if (opts != null) opts.forEach(LazyOptional::invalidate);
}
// Listen to chunk/world unload events, and properly invalidate the LOs at the target position.
```

Exposing a cap on a block would then just be:
```java
// Implementing getCapability on a block
    public <T> LazyOptional<T> getCapability(Capability<T> cap, World world, BlockPos pos, BlockState state, @Nullable Direction direction) {
        if (cap == ITEM_HANDLER_CAP) return world.invalidateOnUnload(() -> new ComposterHandler(...)).cast(ITEM_HANDLER_CAP);
        else return LazyOptional.empty();
    }
    public void onBlockStateReplaced(World world, BlockPos pos, ...) {
        world.invalidateCapsAt(pos);
    }
```

Thoughts?

**Comment by pupnewfster** [comment]
Just making this comment to link this issue with #6691 as this is sort of a continuation of that issue except with a proposed solution.

**Comment by Technici4n** [comment]
Just thought about something more: the proposed system to keep track of LazyOptionals at a given location could be expanded to also contain empty LazyOptionals. Blocks or tiles that wish to offer caps should invalidate previous empties at the target position. Then this would mean that empty results would be cacheable too. @gigaherz, this might be what you were looking for. 😉

**Comment by tmvkrpxl0** [comment]
In order to prevent tons of capability instances getting created, this should be attahed to block and not to each blockpos.
I may work on this myself later

**Comment by Technici4n** [comment]
Implemented in https://github.com/neoforged/NeoForge/pull/73.
