### ISSUE TITLE
[1.18.1] Particles go fullbright for a bit when picking up items or experience

### ISSUE THREAD

**Issue by bageldotjpg** [MinecraftForge/MinecraftForge#8221]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.126

**Steps to Reproduce:**
 1. Go into Survival
 2. Mine a block
 3. Pick up the drops

**Description of issue:**
The particles from the broken block will briefly become fullbright and black upon picking up an item or experience from a block. This is very similar to previously fixed #6706

**Image of issue:**
![image](https://user-images.githubusercontent.com/55970498/145718465-4312cdde-69d7-4553-bec7-f9ac0d6e02ab.png)

**Comment by sciwhiz12** [comment]
Confirmed on 1.18-38.0.14, and my testing shows that the first reproducible version from 1.17.x is 1.17.1-37.0.120.

**Comment by bageldotjpg** [comment]
Confirmed on 1.18.1-39.0.0 as well, and I updated with an image of what it looks like.
