### ISSUE TITLE
[1.18] Crash on launch

### ISSUE THREAD

**Issue by james090500** [MinecraftForge/MinecraftForge#8222]
**Minecraft Version:** 1.17

**Forge Version:** 38.0.0

**Logs:** https://gist.github.com/james090500/3863d39b4ab2efdc5eabd36cff2fc75c

**Description of issue:**
Launching Minecraft after installing Forge 38.0.0 crashes before the menu screen

**Comment by sciwhiz12** [comment]
This issue has been fixed as of 38.0.1.
