### ISSUE TITLE
[1.18] No longer able to call HandshakeHandler#indexFirst due to package locked HandshakeConsumer argument.

### ISSUE THREAD

**Issue by MrCrayfish** [MinecraftForge/MinecraftForge#8241]
**Minecraft Version:** 1.18
**Forge Version:** 38.0.8

I utilise login/handshake packets to make sure clients get the required data from the server before everything is loaded. It seems that the  the network code was slightly refactored during the 1.18 update. Previously it there was a `ThreeConsumer`, which was public, but has now been converted to a package locked interface, `HandshakeConsumer`. This make it impossible to create an acknowledge packet since it needs to call `HandshakeHandler#indexFirst`

**Comment by gigaherz** [comment]
Spoke to cpw. I thought this was for forge internal uses but it seems I was wrong. My bad.
