### ISSUE TITLE
[1.18]  Deepslate ores problem

### ISSUE THREAD

**Issue by pauloeduardods** [MinecraftForge/MinecraftForge#8258]
**Minecraft Version:** [1.18] 

**Forge Version:**  38.0.15

**Description of issue:** When looking with F3 open at a normal (not deepslate) minecraft ore the forge:ore tag is correct applied
But not the same thing happens when looking at the new ores (deepslate ores)
The only deepslate ore that has the right tag applied is the gold, probably because it also exist on nether
The issue, i think, is the lack of the letter S on the word ores
In path forge/src/generated/resources/data/forge/tags/blocks/ores/
working one (gold) = "#minecraft:gold_ores"
not working (iron/diamond) = "minecraft:iron_ore" / "minecraft:diamond_ore" 

**Consequences** various ores prospectors from various mods (cyclic/silengear) not being able to recognize the 
new deepslate ores.

**Comment by KnightMiner** [comment]
#7891 is already opened, addressing this. There is some ongoing discussion regarding other 1.17/1.18 tags before it can be merged.

**Comment by sciwhiz12** [comment]
Fixed by #7891 (`39.0.18`).
