### ISSUE TITLE
No pillagers spawning at pillager outpost

### ISSUE THREAD

**Issue by Campbell314** [MinecraftForge/MinecraftForge#8265]
Minecraft Version: 1.18 (no mods)

Forge Version: 38.0.15 and 38.0.16

Logs: (Don't know how to get logs)

Steps to Reproduce:
 1. Create new world with seed: 7049875907157468887

Description of issue:
 1. Travel to closest pillager outpost at: -169, 84, 729
 2. Notice a lack of pillagers
 3. Wander around trying different distances and gamemodes 
 4. Notice a continued lack of pillagers

**Comment by Campbell314** [comment]
No change with Forge Version 38.0.17

**Comment by Campbell314** [comment]
No change with 

Minecraft Version: 1.18.1 (no mods)

Forge Version: 39.0.0

**Comment by sciwhiz12** [comment]
Confirmed by taking about 5 minutes each sitting in the same world generated in 1.18 with the given seed (at the pillager outpost located at `-688, 1328`), in the following versions:
 - Vanilla 1.18 - pillagers spawn as expected;
 - Forge 1.18-38.0.17 - no pillagers spawn;
 - Vanilla 1.18.1 - pillagers spawn as expected; and
 - Forge 1.18.1-39.0.0 - no pillagers spawn.

**Comment by Tabbinski** [comment]
I'm getting the same behaviour:

Pillagers don't spawn at Outposts though they do spawn in the wild as patrols and will raid when the captain is slaughtered.

- I've tried both forge-1.18.1-39.0.0 & 39.0.7
- Vanilla 1.18.1 - pillagers spawn as expected;
