### ISSUE TITLE
[1.12.2] Extra character '{' and '}' in logs

### ISSUE THREAD

**Issue by MrMks** [MinecraftForge/MinecraftForge#8280]
**Minecraft Version:** 1.12.2

**Forge Version:** 14.23.5.2856

**Logs:** [log in 2855](https://gist.github.com/MrMks/310e802963bbd8409625eb8b967b8e04), [log in 2856](https://gist.github.com/MrMks/9ce05fed57d1c6762cdddd50b9a20a3b)

**Steps to Reproduce:**
 1. Run the client before upgrade to 2856
 2. Close the client and upgrade to 2856
 3. Run the client again

**Description of issue:**
Client logs in 2856 have different format from logs at 2855, with a '{' at the begin and a '}' at the end.

**Comment by srs-bsns** [comment]
This is fixed in 14.23.5.2857

**Comment by MrMks** [comment]
i got it, thank you
