### ISSUE TITLE
Javascript coremod for MobBucketItem commented out

### ISSUE THREAD

**Issue by eerussianguy** [MinecraftForge/MinecraftForge#8298]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.0

**Description of issue:** A small regression. In the 1.17 update the coremod that makes the supplier-ified MobBucketItem constructor useful was commented out. It is linked below. As a result trying to construct a custom bucket using the class is useless.

https://github.com/MinecraftForge/MinecraftForge/blob/456a48b12a61ae62bc86a36fe824245781cfab19/src/main/resources/coremods/field_to_method.js#L57-L65

**Comment by sciwhiz12** [comment]
Seems to be confirmed by inserting the following item declaration into a mod and testing out the resulting item in-game, resulting in a block of water being placed without an entity (tested in a Forgedev instance on commit 0320c185b534a014d02573b5c021b0061fec0ec1): 
```java
public static final RegistryObject<MobBucketItem> PIG_BUCKET = ITEM_REGISTER.register("pig_bucket",
        () -> new MobBucketItem(EntityType.PIG.delegate, Fluids.WATER.delegate, SoundEvents.BUCKET_EMPTY_FISH.delegate,
                new Item.Properties().stacksTo(1).tab(CreativeModeTab.TAB_MISC)));
```
