### ISSUE TITLE
StructureSpawnManager does not respect insideOnly

### ISSUE THREAD

**Issue by Commoble** [MinecraftForge/MinecraftForge#8301]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.5

**Logs:** N/A

**Steps to Reproduce:**
 1. Register a structure that returns true from IForgeStructureFeature#getDefaultRestrictsSpawnsToInside and overrides in IForgeStructureFeature#getDefaultSpawnList
 2. Have it spawn in the world and visit it
 3. Mob spawns use the structure's spawn list anywhere in the structure's AABB rather than just inside the structure's pieces' AABBs
 
**Description of issue:**

##### Background
* Normally, what mobs can spawn at a location is determined by the biome at the location
* If a structure is also present at that location, the structure can optionally override the biome's spawn list by overriding getDefaultSpawnList
* The unpatched vanilla behavior in NoiseBasedChunkGenerator#getMobsAt is for swamp huts and nether fortresses to only override spawns within the AABBs of the individual pieces of the structure, while pillager outposts and ocean monuments override spawns within the entire outer AABB of the structure
* Forge patches getMobsAt to check forge's structure spawn registry instead, allowing mods that register structures or use the StructureSpawnListGatherEvent to define what mobs spawn in structures

##### The Issue
* However, forge does not currently check the spawn AABB restriction state of any structure defined via getDefaultRestrictsSpawnsToInside or via the StructureSpawnListGatherEvent during this (StructureSpawnManager#getStructureSpawns only checks structureManager#getStructureAt and never structureManager#getStructureWithPieceAt
* Therefore, all structures use the primary AABB instead of individual piece AABBs for spawn overriding (including vanilla structures that should use the piece AABBs, as far as I can tell)

##### Possible Fix
* Have StructureSpawnManager#getStructureSpawns check StructureSpawnInfo#insideOnly and use structureManager#getStructureWithPieceAt instead of structureManager#getStructureAt if true

**Comment by PickleDre** [comment]
sorry if this is a dumb question, how can i fix this? i see the possible fix section above but cant find anything to download called structure spawn manager

**Comment by Commoble** [comment]
> sorry if this is a dumb question, how can i fix this? i see the possible fix section above but cant find anything to download called structure spawn manager

StructureSpawnManager is part of Forge. The possible fix has to go into forge itself. Sciwiz's linked PR includes (among other things) a fix for this, which would be applied to forge if/when the forge team approves the PR and merges it into Forge.

**Comment by PickleDre** [comment]
ahhh right, thanks for clearing that up for me
