### ISSUE TITLE
forge wont run first time

### ISSUE THREAD

**Issue by bobstar3233** [MinecraftForge/MinecraftForge#8306]
**Minecraft Version:**1.18.1

**Forge Version:** 39.0.5
**Steps to Reproduce:**
 1. make curseforge profile
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/7739804/latest.log)
[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/7739805/debug.log)

**Comment by sciwhiz12** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the [Forge Support Forums](https://forums.minecraftforge.net/forum/18-support-bug-reports/). Please create a new topic on the support forum with this issue, and the conversation can continue there.
