### ISSUE TITLE
New mountain and cave biomes don't have biome dictionary tags

### ISSUE THREAD

**Issue by FlashFyreMods** [MinecraftForge/MinecraftForge#8307]
**Minecraft Version:** 1.18

**Forge Version:** 39.0.5

The registerVanillaBiomes method in the BiomeDictionary class does not call addTypes for the new mountain biomes - stony peaks, meadow, snowy slopes, grove, jagged peaks and frozen peaks.

**Comment by sciwhiz12** [comment]
The issue of missing biome dictionary tags for the new 1.18 biomes will be fixed by #8246.
