### ISSUE TITLE
[1.12.2] version.json removed from newer buils

### ISSUE THREAD

**Issue by bentalexanderhaase** [MinecraftForge/MinecraftForge#8312]
**Minecraft Version:** 1.12.2

**Forge Version:** 14.23.5.2847 and 14.23.5.2851+

**Logs:** No crash

**Steps to Reproduce:**
 1. Download 14.23.5.2847 and 14.23.5.2851+
 2. Then open .jar file with archiver
 
![image](https://user-images.githubusercontent.com/5788982/146838498-05a927f8-6372-4fa3-9d3d-b87d859be5e9.png)

**Description of issue:**

In newer builds, `14.23.5.2851` and above the `version.json` files is missing from the builds. This breaks Technic Launcher which throws an error like this / relies on this version file.

```F
File version.json not found in [...]\.technic\modpacks\(The modpack)\bin\modpack.jar
```

Of course this technically is not a Forge bug, but is there a reason the `version.json` file was removed / this was not documented in the changelog? This makes updating older packs with the latest version of Forge to mitigate the log4j CVE impossible if hosting on Technic.

**Comment by TheCurle** [comment]
This is an issue with Technic. The use of the universal jar here is the problem - it was never meant to be used like this.
I suggest you ask them for a competent support person.

**Comment by bentalexanderhaase** [comment]
> This is an issue with Technic. The use of the universal jar here is the problem - it was never meant to be used like this. I suggest you ask them for a competent support person.

Any reason why this was changed for older Forge releases?

**Comment by TheCurle** [comment]
Because we've been updating the older Minecraft versions to a newer toolchain.

**Comment by TheCurle** [comment]
As per the request of a few team members, i'm posting the solution here.
![image](https://user-images.githubusercontent.com/42079760/146842722-e920d766-eaa1-45ca-a1f0-02768a5b6634.png)

This is a rather ridiculous issue with Technic - why do they require the installer to be able to start the game!? - but hopefully this will mean we won't get bombarded with requests like this as much in the future.
