### ISSUE TITLE
Game Crashed when using Academy Craft

### ISSUE THREAD

**Issue by Peter-JY** [MinecraftForge/MinecraftForge#8320]
**Minecraft Version:1.12.2** {Minecraft version}

**Forge Version:14.2.3.5.2860 14.2.8.5.2355 14.2.8.5.2354** {Forge version. *Version number, not latest/rb*}

**Logs:**[crash-report.zip]() {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
Install Forge and Academy Craft, then run the game.

**Description of issue:**
Game crashed.
In addition, I'm unwilling to tell you the author of this mod has passed away about half a year ago, and that mod could be used before more than 1 year ago. SO the only solution is in Forge.

**Comment by TheCurle** [comment]
We have no business fixing ancient outdated unsupported mods with no developers.

Forge cannot help you with this.
