### ISSUE TITLE
Start command

### ISSUE THREAD

**Issue by AngelDeaD** [MinecraftForge/MinecraftForge#8321]
Hi,

I'm not reporting bug, I need help about start command.
In past few years I installed several Forge versions in my custom GamePanel 1.6.4-1.16.5 (versions that have minecraft_serverXXX.jar)
Now one of my clients wanted newer version, I noticed that there is no minecraft-serverXXX.jar and that starting process is different.
All builds and versions that my GamePanel supports are based on `java -jar minecraft.jar`
Can you give me one line command that will start Forge 1.17.x and 1.18.x ?

I tried to make one line start command, but I get this error:
`line 193: Use:: command not found`

This is my start line:
`java -Xmx 4096M -p libraries/cpw/mods/bootstraplauncher/0.1.17/bootstraplauncher-0.1.17.jar:libraries/cpw/mods/securejarhandler/0.9.54/securejarhandler-0.9.54.jar:libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar:libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar:libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar:libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar:libraries/org/ow2/asm/asm/9.1/asm-9.1.jar \
--add-modules ALL-MODULE-PATH \
--add-opens java.base/java.util.jar=cpw.mods.securejarhandler \
--add-exports java.base/sun.security.util=cpw.mods.securejarhandler \
-DignoreList=bootstraplauncher-0.1.17.jar,securejarhandler-0.9.54.jar,asm-commons-9.1.jar,asm-util-9.1.jar,asm-analysis-9.1.jar,asm-tree-9.1.jar,asm-9.1.jar \
-DlibraryDirectory=libraries \
-DlegacyClassPath=libraries/cpw/mods/securejarhandler/0.9.54/securejarhandler-0.9.54.jar:libraries/org/ow2/asm/asm/9.1/asm-9.1.jar:libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar:libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar:libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar:libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar:libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar:libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar:libraries/net/minecraftforge/eventbus/5.0.3/eventbus-5.0.3.jar:libraries/net/minecraftforge/forgespi/4.0.10/forgespi-4.0.10.jar:libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar:libraries/cpw/mods/modlauncher/9.0.7/modlauncher-9.0.7.jar:libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar:libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar:libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar:libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar:libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar:libraries/org/apache/logging/log4j/log4j-api/2.15.0/log4j-api-2.15.0.jar:libraries/org/apache/logging/log4j/log4j-core/2.15.0/log4j-core-2.15.0.jar:libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.15.0/log4j-slf4j18-impl-2.15.0.jar:libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar:libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar:libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar:libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar:libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar:libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar:libraries/net/minecraftforge/fmlloader/1.18-38.0.17/fmlloader-1.18-38.0.17.jar:libraries/net/minecraft/server/1.18-20211130.085255/server-1.18-20211130.085255-extra.jar:libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar:libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar:libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar:libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar:libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar:libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar:libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar:libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar:libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar:libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar \
cpw.mods.bootstraplauncher.BootstrapLauncher \
--launchTarget forgeserver \
--fml.forgeVersion 38.0.17 \
--fml.mcVersion 1.18 \
--fml.forgeGroup net.minecraftforge \
--fml.mcpVersion 20211130.085255`

This '--fml.mcpVersion 20211130.085255` is 193rd line.

I extracted this start command from your `run.sh`

**Comment by diesieben07** [comment]
You should simply run the run.sh file.
