### ISSUE TITLE
Block particles appear trough wall when breaking/getting items

### ISSUE THREAD

**Issue by GuardianWorld** [MinecraftForge/MinecraftForge#8324]
**Minecraft Version:** 1.18.1 

**Forge Version:** 39.0.8

**Steps to Reproduce:**
 1. Break a block like deep slate
 2. There you go...

**Description of issue:**
When breaking blocks on Minecraft Forge 1.18.1, particle entities appear trough walls as black spots.
Tested with ONLY forge 39.0.8 installed, no additional mods.
![2021-12-25_01 40 40](https://user-images.githubusercontent.com/12464623/147377548-72837678-8963-4ac0-b51c-3a0cc50fd60d.png)
.

OBS: I believe this issue is also present on Forge 1.17, but i don't remember the version.

**Comment by sciwhiz12** [comment]
Closing as this seems to be related to and fixed by #8378 (1.18.1-39.0.17).
