### ISSUE TITLE
Getting the following error when attempting to run a forge server

### ISSUE THREAD

**Issue by Blitzgott1309** [MinecraftForge/MinecraftForge#8326]
**Minecraft Version:** {1.12.2}

**Forge Version:** {1.12.2-14.23.5.2847-universal}

**Logs:**
[logs.txt](https://github.com/MinecraftForge/MinecraftForge/files/7777537/logs.txt)

**Steps to Reproduce:**
 1. Launch server.bat
 2. Get this error

**Description of issue:**
I am getting this error when attempting to run a server and am not sure what it pertains to. Any help would be appreciated!

**Comment by TheCurle** [comment]
1.12 is not supported. 
This is not a support forum.
