### ISSUE TITLE
%minecraftFormatting issue on Centos7 [forge-1.12.2-14.23.5.2860]

### ISSUE THREAD

**Issue by faitarus** [MinecraftForge/MinecraftForge#8327]
Im using Centos7 and forge-1.12.2-14.23.5.2860.

On the console all commands/logs are replaced by the message "%minecraftFormattig".

Any fixes?
![2021-12-27 10_12_46-Window](https://user-images.githubusercontent.com/60380712/147456497-21b6b3bc-daa1-4fb9-a72a-d2f9ff14470b.png)

**Comment by sciwhiz12** [comment]
First, 1.12 is unsupported.
Second, I cannot confirm this issue locally using a fresh installation of 1.12.2-14.23.5.2860: the console both in the command prompt (or PowerShell, in my case) and the server GUI shows the logging messages as expected.

**Comment by faitarus** [comment]
It isn't very helpful to close the ticket directly.. Very bad Support here.

Btw i found the Issue

**FIX:
If it is a update from another Forge Version is necessary to copy the server library folder too.
Also a simple replace of the .JAR will not work like the other version.**
