### ISSUE TITLE
TileFluidHandler is a poor reference due to doing a few things incorrectly

### ISSUE THREAD

**Issue by pupnewfster** [MinecraftForge/MinecraftForge#8332]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.9

**Description of issue:**

When looking at usages of `BlockEntity#save` while porting to make it easier that I don't miss moving any of my calls over I noticed that forge's "reference implementation" for `IFluidHandler` (`TileFluidHandler`) is still using [`BlockEntity#save`](https://github.com/MinecraftForge/MinecraftForge/blob/1.18.x/src/main/java/net/minecraftforge/fluids/capability/TileFluidHandler.java#L55) instead of `saveAdditional`.

It also doesn't invalidate the lazy optional it provides from `getCapability` inside of `invalidateCaps`.

**Comment by tmvkrpxl0** [comment]
@sciwhiz12 Hey I think this issue has already been addressed
