### ISSUE TITLE
RegistryObject cannot retrieve registry objects if created after registries load

### ISSUE THREAD

**Issue by Commoble** [MinecraftForge/MinecraftForge#8339]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.9

**Logs:** https://gist.github.com/Commoble/a09deca41db8a30b3445ef9b21d78e68
(I was in the middle of some forge dev and needed to whip up a quick example of RegistryObjects crashing, so I added this to the start of ForgeMod's common setup event)

 ```java
     public void preInit(FMLCommonSetupEvent evt) // occurs after registration
    {
        RegistryObject<Block> dirtObj = RegistryObject.of(new ResourceLocation("minecraft:dirt"), ForgeRegistries.BLOCKS);
        Block dirt = dirtObj.get(); // NPEs
    }
````

**Steps to Reproduce:**
 1. Create a RegistryObject after standard registries have concluded using RegistryObject#of
 2. Call RegistryObject#get
 3. NPE

**Description of issue:**
RegistryObjects, rather than using conventional lazy evaluation or memoization, are created by registering a callback to the ObjectHolderRegistry, telling forge to populate the registry object when registration is performed. This works perfectly well when the RegistryObject is created before registration occurs, but causes NPEs when the RegistryObject is created post-registration.

**Comment by TheCurle** [comment]
I believe this intended.
RegistryObject exists to defer collection of objects until they are populated.

If they are created after the population happens, then there is nothing to signal the object to retrieve the object.

In this way, it is more idiomatic Java to simply take the two already hardcoded arguments (`new ResourceLocation("minecraft:dirt"), ForgeRegistries.BLOCKS`) and query the registry directly.

**Comment by diesieben07** [comment]
It may be intended, but it can cause problems even if you use `RegistryObject` in the "intended" way.
Example: 
```java
static final RegistryObject<Block> WHATEVER = RegistryObject.of(new ResourceLocation("some_other_mod", "whatever"), ForgeRegistries.BLOCKS)
```
There is no guarantee that this runs before registries are populated. If you only access this class from FMLCommonSetupEvent then it'll classload at that point and the RegistryObject will populate.
