### ISSUE TITLE
Main menu rendering error

### ISSUE THREAD

**Issue by XerwinXpl2** [MinecraftForge/MinecraftForge#8355]
after starting the game and after the mods  loading phase when the background and buttons is not loaded yet, this green dot from the "mod" button is rendered. this results bad look.
you can see this bug 1-2 second after end of mod loading phase.

**Comment by AterAnimAvis** [comment]
Confirmed by Sciwhiz in Forgecord, `NotificationModUpdateScreen#render` doesn't respect the fade in transparency
