### ISSUE TITLE
Race condition / deadlock loading world in `Ingredient` constructor.

### ISSUE THREAD

**Issue by alcatrazEscapee** [MinecraftForge/MinecraftForge#8359]
Forge version: 39.0.5
Minecraft version: 1.18.1
This was initially reproduced with JEI 9.1.1.48 in a mod dev environment. 
The affected bits of Forge code in this issue are identical to the latest at time of writing (39.0.10)

---

[Forge patches `Ingredient`](https://github.com/MinecraftForge/MinecraftForge/blob/1.18.x/patches/minecraft/net/minecraft/world/item/crafting/Ingredient.java.patch) to add all instances to a `Collections.newSetFromMap(new WeakHashMap<>())`. This is not a thread safe data structure and in particular during, i.e. recipe reloading, ingredients can be created from multiple threads. This has the *potential* to cause a deadlock.

I have reproduced this irregularly (three times now) in a mod development environment, and observed the following conditions:

- During world loading or creation (both have caused this), everything seems to halt, just after JEI finishes logging:

```
[20:54:03] [Render thread/INFO]: Building recipe registry...
[20:54:03] [Render thread/INFO]: Building recipe registry took 13.32 ms
```

- Inspecting via the debugger shows that most threads are parked except for one:
- The thread that is not parked is suck in a stacktrace of `Ingredient.<init>`, somewhere within a `WeakHashMap` method call.

I have written up a [mock example](https://gist.github.com/alcatrazEscapee/531cee8ec0cb5736dfc23399eda31cba), which confirms that this data structure can indeed deadlock under some unpredictable threaded creation of instances. I believe this is what is occurring here as well. I do not have a minimal test case to reproduce it Minecraft.

---

Suggestion: wrap the cached map in a `Collections.synchronizedMap`. I have done this in my mod dev environment via Mixin, and can (anecdotally) say that I have not experienced the issue since doing so.

**Comment by diesieben07** [comment]
Might want to use `new MapMaker().weakKeys().makeMap()` from Guava instead, which is more like `ConcurrentHashMap` instead of having to use synchronization.
