### ISSUE TITLE
`ICloudRenderHandler` and `ISkyRenderHandler` are missing `Matrix4f` parameter in their respective `render()` methods.

### ISSUE THREAD

**Issue by Dizzlepop12** [MinecraftForge/MinecraftForge#8362]
**Minecraft Version:** 
1.18.1

**Forge Version:** 
1.18.1-39.0.10

**Description of issue:**
ICloudRenderHandler and ISkyRenderHandler are missing the Matrix4f parameter supplied by the `renderClouds()` method and `renderSky` method in `LevelRenderer`. Mojang uses this at line 2032 and line 1848 in `LevelRenderer`. Without Matrix4f being supplied by these interfaces, creation of custom sky/cloud renderers in dimensions is more complicated than it needs to be.

![image](https://user-images.githubusercontent.com/11151901/148632640-56a7fe90-e5c0-43f2-a1ae-837a3a28705c.png)

![image](https://user-images.githubusercontent.com/11151901/148632628-5bf69d3b-dacb-46e7-a4ab-9d530cb82347.png)

**Comment by AllShamNoWow101** [comment]
This is also for all sky render methods

**Comment by MrScautHD** [comment]
you can just do: (it does also work)
Matrix4f starmatrix4f = RenderSystem.getProjectionMatrix();

**Comment by Dizzlepop12** [comment]
> 

yeah that's what I ended up doing, but it should still be added in the render method itself anyway,
