### ISSUE TITLE
New version of MinecraftForgeGradlew

### ISSUE THREAD

**Issue by QuinouDEV** [MinecraftForge/MinecraftForge#8365]
Hello,

I have a question. I happen to be unable to use the forge source to be able to create 1.6.4 mods due to a problem with the http and https queries from the maven servers.
Like you did with 1.4.7, I would like to create mods in 1.6.4 so I would like to know if you are going to create a forge version for 1.6.4 or how could I go about it? to update gradlew for this version.

Best regards, Quinou

**Comment by TheCurle** [comment]
We haven't done anything with 1.4.7, and changing the maven URLs to use https is trivial with a text editor.
