### ISSUE TITLE
Attribute for step height

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#8369]
Step height is one of those old things that people manipulate by hand with += and -= which is brittle and noncomposable.

It would be nice if we could do the same thing as we've done for reach distance, and introduce an attribute mods can use to modify it.

If no objections or volunteers, I'll probably send a patch for this in a few weeks.

**Comment by sciwhiz12** [comment]
Implemented by #8389 (which was reverted due to breaking changes) and #8607 (re-adds the feature in a non-breaking way), published as `1.18.2-40.1.16`.
