### ISSUE TITLE
Vanilla death messages for falling off of climbable blocks (e.g. ladders) don't appear

### ISSUE THREAD

**Issue by Sonicwave** [MinecraftForge/MinecraftForge#8370]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.14

**Description of issue:**
In vanilla, falling to your death off of a ladder, vine or other climbable block produces a custom death message (e.g. `<player> fell off a ladder`, `<player> fell off some vines` or `<player> fell while climbing` for climbable blocks without their own death message). With Forge however, these messages do not appear and the standard `<player> fell from a high place` shows instead. It seems the `lastClimbablePos` field of the `LivingEntity` class which is used to determine the block fallen off of never gets updated.

**Steps to Reproduce:**
* Fall off the side or bottom of a ladder or vine variant high enough to cause instant death
* Repeat in Vanilla to see the behavior difference

**Comment by sciwhiz12** [comment]
Confirmed on 1.18.1-39.0.14 by testing and on 1.16.5-36.2.22 by examination of code compared to 1.18 and 1.15. It seems that 1.16 added the `lastClimbablePos` field, but the Forge ladder hook wasn't adapted during the 1.16 patch and update cycle to use the field, therefore causing this issue.
