### ISSUE TITLE
Seeds for Custom Dimensions does not work (Small MC Bug)

### ISSUE THREAD

**Issue by MrScautHD** [MinecraftForge/MinecraftForge#8396]
**Minecraft Version:** 1.18.1

**Forge Version:** 1.18.1-39.0.20

**Steps to Reproduce:**
This is a Minecraft issue but a small one i heared Forge does fix small bugs of minecraft, so i hope you can fix it :D

The Link to the issue:
https://bugs.mojang.com/browse/MC-195717

**Comment by sciwhiz12** [comment]
#7955 fixes the vanilla bug mentioned by this issue. I will leave this issue open for tracking and visibility purposes.

**Comment by MrScautHD** [comment]
> #7955 fixes the vanilla bug mentioned by this issue. I will leave this issue open for tracking and visibility purposes.

does you know when #7955 go merged?

**Comment by sciwhiz12** [comment]
The PR will be merged when the Core Team is available and have considered the PR as ready for merging. It will possibly be merged before the release of the Recommended Build.

**Comment by MrScautHD** [comment]
> The PR will be merged when the Core Team is available and have considered the PR as ready for merging. It will possibly be merged before the release of the Recommended Build.

nice!, do you maybe know a way how i can fix that with my own chunk generator?
