### ISSUE TITLE
Wrong entity type passed to canLivingConvert

### ISSUE THREAD

**Issue by Lupicus** [MinecraftForge/MinecraftForge#8399]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.0

**Description of issue:**
The call to canLivingConvert in Zombie#tick has the wrong second argument (i.e. the outcome type), it should be EntityType.DROWNED

**Comment by sciwhiz12** [comment]
Confirmed on 1.18.1, commit a3449f2866e3aec9f063c0e4562e915803a17af7 (39.0.36), and 1.16.5, commit ed1f83047c1aedee3e9728add5808ef02518262f (36.2.23). Seems to be an unnoticed bug in the PR that introduced the feature: #7386.
