### ISSUE TITLE
Incorrect sample code in IExtensionPoint

### ISSUE THREAD

**Issue by quat1024** [MinecraftForge/MinecraftForge#8407]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.5 but it does affect current `1.18.x` HEAD rn

**Description of issue:** This sample code: 

https://github.com/MinecraftForge/MinecraftForge/blob/eb1a9b57c6cc4d5cb4ad3c4305c2a73015d28917/fmlcore/src/main/java/net/minecraftforge/fml/IExtensionPoint.java#L43-L47

makes references to the class `FMLNetworkConstants`, which no longer exists.

**Comment by sciwhiz12** [comment]
The `net.minecraftforge.fmllegacy.network.FMLNetworkConstants` class was renamed to `net.minecraftforge.network.NetworkConstants` in 1.18 (as part of the removal of the `fmllegacy` package and renames of classes therein); however, the javadocs were not fixed at the time to reflect this class rename.

**Comment by Shadows-of-Fire** [comment]
There's more wrong with it than just the class rename, as `registerExtensionPoint` now takes a `class` and an instance of that class, instead of the enum and a Pair.

**Comment by sciwhiz12** [comment]
Fixed by #8568, released as `1.18.2-40.1.11`.
