### ISSUE TITLE
Forge update causing java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag 

### ISSUE THREAD

**Issue by figori** [MinecraftForge/MinecraftForge#8409]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.45

**Logs:** https://github.com/AllTheMods/ATM-7/issues/344

**Steps to Reproduce:**
 1. All the Mods 7 updated and used the latest Forge update.
 2. Server boots, and then crashes.

**Description of issue:**

Remove references to the now-broken BlockEntity#save(CompoundTag) method (#8235) appears to be causing issues.

**Comment by SizableShrimp** [comment]
This is not a bug, this removal was intended. As noted by the .0 middle part of the version, Forge is still in beta and breaking changes should be expected. The "fix" would be downgrading your version to before the change was made, and updating the mods using the old method.

**Comment by sciwhiz12** [comment]
As @SizableShrimp says, releases before the first RB (Recommende Build, i.e. those with the middle part of the version as `0`) may contain breaking changes that break compatibility with previous releases (and mods built for those releases).[^1]

As also suggested, you will have to downgrade your Forge version to the immediate version before the breaking change, or follow up on the mods within the modpack which are broken by the change to release an update which fixes compatibility.

[^1]: This is an unavoidable aspect of Forge development, as we must be able to make breaking changes within a given window (in this case, before the first RB) for various features and bugfixes.
