### ISSUE TITLE
Crashing during launch (Forge 39.0.52)

### ISSUE THREAD

**Issue by Nyaromight** [MinecraftForge/MinecraftForge#8411]
Hey, 
did a own Modpack and it crashes with the Versions 39.0.46 - 39.0.52. With the .45 version it works fine.
Minecraft Version 1.18.1. I cant see why it even crashes.

Log is attached
[2022-01-20-7.log](https://github.com/MinecraftForge/MinecraftForge/files/7908977/2022-01-20-7.log)
.

**Comment by SirEndii** [comment]
3 Mods can't be loaded. 
`de/maxhenkel/corpse`, `de/maxhenkel/gravestone`, `me/jellysquid/mods/sodium/`
These mods are probably not up to date if they work with an older forge version.

And your log does not seem to be right, it's like cut at the end :P

**Comment by Nyaromight** [comment]
Thank you :D Solved
