### ISSUE TITLE
Game crashes because of .DS_STORE on MacOS

### ISSUE THREAD

**Issue by prggTheProgrammer** [MinecraftForge/MinecraftForge#8413]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.36

**Logs:** https://gist.github.com/prggTheProgrammer/ab67ef823eecc41fca7c9913a908d7ae

**Steps to Reproduce:**
 1. Install forge mdk normally with eclipse
 2. Make your mod with an assets folder
 3. Run the game and see that it crashes

**Description of issue:**
The issue is that the game crashes because of a file called .DS_Store:
`net.minecraft.ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: .DS_Store:sounds.json`

What is .DS_Store?
.DS_Store is a metadata file that is automatically created by MacOS (I believe it's created when you move files around with finder, but I'm not sure)

So the workaround for this issue is to remove the .DS_Stores every time you run minecraft. But it would be better if forge would automatically ignore this file, so it never gives this error.

**Comment by diesieben07** [comment]
The solution would be to patch/change the resource pack implementations of `getNamespaces` to ignore hidden files I think.

**Comment by gigaherz** [comment]
As a temporary workaround until we consider possible solutions, you can disable .DS_Store generation by running this in a terminal.
```
defaults write com.apple.desktopservices DSDontWriteNetworkStores true
```
But you may need to cleanup the existing .DS_Store files manually, which may or may not be complicated to do from within macOS.

EDIT: Apparently this may only work in network shares, and will not prevent DS_Store files on normal filesystem folders.

**Comment by prggTheProgrammer** [comment]
@gigaherz To cleanup the existing .DS_store files you can run `find . -name ".DS_Store" -exec rm {} ";"` in your project directory.

**Comment by 91leMAC** [comment]
> @gigaherz To cleanup the existing .DS_store files you can run `find . -name ".DS_Store" -exec rm {} ";"` in your project directory.

Doesn't work on my mac.

**Comment by prggTheProgrammer** [comment]
> > @gigaherz To cleanup the existing .DS_store files you can run `find . -name ".DS_Store" -exec rm {} ";"` in your project directory.
> 
> Doesn't work on my mac.

The issue should already be fixed with the latest release, so you don’t need to cleanup the .DS_Store files anymore. But if you still want to remove them, you could give more details about your problem, I am glad to help.
You first need to run `cd path/to/project` Where path/to/project is the complete path to your project dir (e.g. ~/Documents/projects/MyMod)
