### ISSUE TITLE
Cheat hack

### ISSUE THREAD

**Issue by joaoespanhol** [MinecraftForge/MinecraftForge#8418]
**Minecraft Version:** {1.12.2/1.16.5}

**Forge Version:** {Last}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. install mod: https://github.com/theic2/Xeno1.12
 2. use cheat

**Description of issue:**
with this mod, you can get any item from the server or duplicator.

Happens in all versions of minecraft forge.

**Comment by OrionDevelopment** [comment]
This is not related to MinecraftForge,
Take it up with the make of said mod.
