### ISSUE TITLE
[1.18.1] Regression in entity onAddedToWorld() / onRemovedFromWorld() vs. 1.16.5

### ISSUE THREAD

**Issue by desht** [MinecraftForge/MinecraftForge#8427]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.59

**Logs:** n/a

**Description of issue:**

The Forge-added `onAddedToWorld()` and `onRemovedFromWorld()` in `IForgeEntity` are not getting called in 1.18.1 as they did in 1.16.5:

* `onAddedToWorld()` is getting called on both client and server when a new entity is added to the world, *but* only on the client when loaded from saved chunk data
* `onRemovedFromWorld()` is getting called only on the client when an entity is removed (mob dies, item is picked up...). Doesn't appear to be getting called server-side, at all.

**Comment by sciwhiz12** [comment]
Could you please provide reproducible steps (preferrably, with example code) for cases in which `onAddedToWorld()`/`onRemovedFromWorld()` _should_ be called, but are not called in 1.18.x?

**Comment by desht** [comment]
Code isn't needed to reproduce this.  Following should be sufficient:
* Create an empty world (I used superflat/redstone-ready)
* Get a spawn egg for any mob
* Put IDE breakpoints on `Entity#onAddedToWorld()` and `Entity#onRemovedFromWorld()`
* Spawn the mob; observe that `Entity#onAddedToWorld()` is called on both client and server
* Quit and re-enter the world; observe that `Entity#onAddedToWorld()` is *not* called on the server this time, only the client
* Kill the mob; observe that `Entity#onRemovedFromWorld()` is only called on the client
