### ISSUE TITLE
Forge 1.18.1 fails to install on linux.

### ISSUE THREAD

**Issue by Fox2Code** [MinecraftForge/MinecraftForge#8430]
**Minecraft Version:** 1.18.1

**Forge Version:** forge-1.18.1-39.0.59

**Logs:** [forge-1.18.1-39.0.59-installer.jar.log](https://github.com/MinecraftForge/MinecraftForge/files/7952764/forge-1.18.1-39.0.59-installer.jar.log)

**Steps to Reproduce:**
 1. Open the installer
 2. Click install

**Description of issue:**
The installer fails (See screenshot)

![ForgeErrorInstall2](https://user-images.githubusercontent.com/42963271/151416362-80bbf88b-c3da-4de0-b2e7-ec3a64f93ed9.png)

**Comment by sciwhiz12** [comment]
:wave: We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the [Forge Support Forums](https://forums.minecraftforge.net/). Please create a new topic on the support forum with this issue, and the conversation can continue there.
