### ISSUE TITLE
Unknown or incomplete command when join BungeeCord server

### ISSUE THREAD

**Issue by wtnpmt** [MinecraftForge/MinecraftForge#8435]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.46

**Steps to Reproduce:**
 1. Join a server with BungeeCord or Waterfall。
 2. Type any command about BungeeCord or BungeeCord plugins(/bungee,/server,/lpb e.g.)
 3. Unknown or incomplete command

**Description of issue:**
![image](https://user-images.githubusercontent.com/25454317/151652893-37761526-f9cf-4ba6-ac87-6f0894e16f17.png)

**Comment by marchermans** [comment]
BungeeCord is not related to forge, neither is it a server system we support.

**Comment by wtnpmt** [comment]
This is a client bug, it not happend on forge 39.0.45 or vanilla.it happend since 39.0.46 Add Client Commands (#7754)
