### ISSUE TITLE
New JDK version crashes Forge on startup

### ISSUE THREAD

**Issue by HexedHero** [MinecraftForge/MinecraftForge#8436]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.2.23

**Logs:**
https://www.toptal.com/developers/hastebin/qidafaxivo.md

**Steps to Reproduce:**
 1. Launch forge with jdk8u322-b06

**Description of issue:**
Using Temurin **jdk8u322-b06** breaks forge startup whereas Temurin **jdk8u312-b07** works just fine.

**Comment by sciwhiz12** [comment]
This is a known issue (see McModLauncher/modlauncher#91) and will be fixed by #8423.
