### ISSUE TITLE
Forge mod causing LuckPerm commands to not register in client

### ISSUE THREAD

**Issue by TheMethodicalJosh** [MinecraftForge/MinecraftForge#8438]
**Minecraft Version:** {Minecraft version}
Minecraft 1.18.1 Client with Forge (Optifine & Controllable Mods)

**Forge Version:** {Forge version. *Version number, not latest/rb*}
Forge Mod 39.0.46 - 39.0.63 (Issue Versions)
Forge Mod 39.0.40 - 39.0.45 (Working Versions)

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://paste.ee/p/nFncj - Debug Log
https://paste.ee/p/nknCg - Latest Log (Edited for redaction)

**Steps to Reproduce:**
 1. Run Minecraft 1.18.1 Server with LuckPerms Plugin (v5.3.98)
 2. Install Forge Mod version between 39.0.46 - 39.0.63 on client running forge of versions above
 3. Run any LuckPerms server side issued command to verify issue on client running forge of versions above

**Description of issue:**

When running seemingly any version of Forge 39.0.46 through 39.0.63 (latest as of submission), this causes the client to not register any Luck Permissions plugin command on server as if command is not being entered at all. There is no log of event on client or server side, it just purely acts like the command isn't being entered and nothing happens. _This issue **DOES NOT** happen as tested with Forge Versions 39.0.40 or 39.0.45 and works as expected._

**Comment by TheCurle** [comment]
How are you running a plugin on Forge?

Most of these Bukkit/Sponge/whatever else hybrid solutions leave a lot to desired, it is my guess that whatever you're using is not suited for this purpose.

It looks to me like the server's commands are simply not being sent to the client in advance, so our addition of client commands are taking precedence (as they should) and causing the server to not be able to evaluate the command.

I suggest you take this up with the plugin system, not here. We do everything we can.

**Comment by LexManos** [comment]
However, if you can reproduce an issue where the [server correctly sends the commands](https://wiki.vg/Protocol#Declare_Commands) and we ignore it. Then we can take a look. However in all our tests, even non-vanilla commands are processed correctly.

**Comment by TheMethodicalJosh** [comment]
> How are you running a plugin on Forge?
> 
> Most of these Bukkit/Sponge/whatever else hybrid solutions leave a lot to desired, it is my guess that whatever you're using is not suited for this purpose.
> 
> It looks to me like the server's commands are simply not being sent to the client in advance, so our addition of client commands are taking precedence (as they should) and causing the server to not be able to evaluate the command.
> 
> I suggest you take this up with the plugin system, not here. We do everything we can.

I'm not sure how you've made this out that I'm running a plugin on Forge. I clearly and purely state I'm running the LuckPerms plugin on a Minecraft 1.18.1 Paper **SERVER**, and I'm running a **CLIENT** with Forge with a controllable mod and optifine in the range of the versions clearly stated above.

**Comment by TheCurle** [comment]
Your steps imply to install Forge on the server, so that is not clearly and purely stated.

However, the issue remains the same.

**Comment by TheMethodicalJosh** [comment]
> Your steps imply to install Forge on the server, so that is not clearly and purely stated.
> 
> However, the issue remains the same.

I have corrected that with an edit, however it should have been implied that forge was installed on the client with the very first line of the issue ticket if it was read.

Yes indeed, the issue still remains and can verify on fresh installs of multiple machines that an update from 39.0.45 does indeed break the luckperm commands.

**Comment by TheMethodicalJosh** [comment]
#7754 - 39.0.46 Add Client Commands

Extensive testing and searching shows that issue does indeed start at Forge Version 39.0.46 when PR for "Add Client Commands" was requested.

**Comment by TheCurle** [comment]
Temporarily locking this issue as nothing is being added.
We know what caused this. 
We're trying to see if there's anything we can do to fix this, but i honestly doubt it.
LuckPerms (or Spigot/Paper/Whatever) isn't sending the client information about the commands.

**Comment by TheCurle** [comment]
For those who are still keeping track of this, it seems like the issue here is that the commands *are* being sent, but only via the command tree, and not as executable commands.
For LuckPerms this can be traced to their use of Commodore, but both use the old (< 1.13) methods of registering commands, which is why they broke when Forge updated to explicitly require support for these.

From the author of the Client Commands PR that exposed this problem:
> seems like both bungeecord and luckperms send the commands but they don't mark them as executable since they are only sending them in brigadier format for the client since they both still use the command registration method that was removed in 1.13 on the backend
