### ISSUE TITLE
PlayerChangeGameModeEvent doesn't use the game mode set in the event

### ISSUE THREAD

**Issue by GoryMoon** [MinecraftForge/MinecraftForge#8439]
**Minecraft Version:** 1.16.3 -> 1.18.1

**Forge Version:** 34.1.20 -> 39.0.64 (since the event was added)

**Logs:** No logs

**Steps to Reproduce:**
 1. Setup an event handler for `PlayerChangeGameModeEvent`
 2. Try to set a new game mode with `setNewGameMode` and nothing happens

**Description of issue:**
The `PlayerChangeGameModeEvent` is not hooked up to use the value changed with `setNewGameMode`.
To work around this I just cancel the event and set the game mode on the player.

The doc of the `setNewGameMode` method:
> Sets the game mode the player will be changed to if this event is not canceled.

I think it should either be hooked up to use that value if not canceled like the doc say or just remove it as it's just as easy to set the game mode on the player manually. With the method being like it is right now it's confusing why it doesn't work until you start debugging why it doesn't work.

The event was added in #7355

**Comment by TheCurle** [comment]
That's a mighty oversight.

Thanks for the report.
