### ISSUE TITLE
Crash Report: Minecraft Forge 39.0.64 gives Error Code 0 on AMD based processor.

### ISSUE THREAD

**Issue by GlitchySavvy** [MinecraftForge/MinecraftForge#8446]
**Minecraft Version:** {1.18.1}

**Forge Version:** {Forge version. *39.0.64*}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
![image](https://user-images.githubusercontent.com/74983805/152449378-99d9fabc-a70c-4b78-a13b-70861d04c866.png)
**Description of issue:**
When I use an Intel Processor, everything works just fine. But when you use it on an AMD, it gives an error code 0.

**Comment by TheCurle** [comment]
Please go to the [Forums](https://forums.minecraftforge.net), not here.
This is not tech support.
