### ISSUE TITLE
[1.18] EntityLeaveWorldEvent is not called server side

### ISSUE THREAD

**Issue by P3pp3rF1y** [MinecraftForge/MinecraftForge#8448]
In 1.18 EntityLeaveWorldEvent is no longer called server side. 

From what I can gather there's missing block in `tick` method in https://github.com/MinecraftForge/MinecraftForge/blob/1.18.x/patches/minecraft/net/minecraft/server/level/ServerLevel.java.patch  that would call `removeEntityComplete` when entity is removed and that used to be there in 1.16 https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/patches/minecraft/net/minecraft/world/server/ServerWorld.java.patch#L87

**Comment by sciwhiz12** [comment]
This is related to and should be fixed by #8434.
