### ISSUE TITLE
Failed to start the minecraft server

### ISSUE THREAD

**Issue by laboriens** [MinecraftForge/MinecraftForge#8450]
minecraft 1.18.1
forge 39.0.66
log: https://textup.fr/612024Zk

the server launches perfectly in 39.0.65, but does not launch in 39.0.66

**Comment by sciwhiz12** [comment]
:wave: We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the [Forge Support Forums](https://forums.minecraftforge.net/). Please create a new topic on the support forum with this issue, and the conversation can continue there.
