### ISSUE TITLE
[1.18.1] Memory Leak on Player Join

### ISSUE THREAD

**Issue by LunafeyLazuli** [MinecraftForge/MinecraftForge#8453]
**Minecraft Version:** {Minecraft version}
1.18.1

**Forge Version:** {Forge version. *Version number, not latest/rb*}
39.0.64

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://pastebin.com/0Xks6hkM

**Steps to Reproduce:**
1. Add -Dio.netty.leakDetection.level=advanced as a start up parameter
2. Wait for server to start and for players to join
3. Watch as every time a player joins or connects to a new dimension, in the console it will start posting memory leak warnings every time this happens
4. After a few hours the RAM usage get's eaten up faster then a drunk man eating cheerios on a sunday morning
5. Once the RAM caps out after constant TPS issues and constant Time outs, the server will eventually "soft crash" as players are not able to join the server and the server is basically stuck where neither players can connect, yet it still states the server is online with players even though no one is on

**Description of issue:**
As described above ^ we've been having a lot of RAM issues and Time Out issues lately and so we decided to test and see if it was a possible mod that was having memory leak issues, but turns out it's just upon player join and switching dimensions that we get memory leak warnings in the console and causes the the server to lag extremely hard due to low TPS and constant Time Outs

**Comment by TheCurle** [comment]
That's interesting. Can you provide a profiler log so that we can track down what's causing this?

**Comment by LunafeyLazuli** [comment]
Sure! How would I go about doing that?

**Comment by TheCurle** [comment]
Use VisualVM, take a profile of the game while this memory leak happens, and export it to a sensible format.

**Comment by LunafeyLazuli** [comment]
I guess my next question would be, how would I do this on a hosted server? (I've never done this before so I just want to make sure I do this the right way)

**Comment by LunafeyLazuli** [comment]
Because I do have this, as bisect has it's own visual of the server stats that I can look at from the console https://i.gyazo.com/8d87017f29191feb13d33317a4ef0a05.png

**Comment by TheCurle** [comment]
If you don't have control of the server hardware then you unfortunately can't do that.
That leads me to the question of, can you replicate this by running the server on your own PC?

**Comment by LunafeyLazuli** [comment]
I can try but, but since I've always used a hosting service, I've never been able to successfully run a server off my own computer, hopefully that screenshot helps even a bit, that's with 16GBs of RAM for the server

**Comment by LunafeyLazuli** [comment]
Ah yeah here we go, just got this from the console page and all the visual stuff going 
![image](https://user-images.githubusercontent.com/85852051/152696986-4bfaac78-7fb5-41c9-b4a5-e5e6c59b91b7.png)

**Comment by TheCurle** [comment]
Unfortunately that doesn't help us at all - i can't replicate this issue on my own computer, so i'm currently suspecting this is a problem with Bisect.

**Comment by LunafeyLazuli** [comment]
I hope not ;-; is there anything that you think might be causing this?

**Comment by TheCurle** [comment]
Not a clue. That's why i want the profiler log, it'll tell us in no unclear terms what the problem actually is.

**Comment by LunafeyLazuli** [comment]
I gotcha, I'll see if I can figure out a way to get that for you and see if Bisect support can look into it as well

**Comment by TheCurle** [comment]
Please join [the Forge Discord](https://discord.gg/forge) and message me (Curle) if you get that.
Closing this issue as resolved for now.
