### ISSUE TITLE
Brigadier throws exception when commands are not exist

### ISSUE THREAD

**Issue by Jenya705** [MinecraftForge/MinecraftForge#8456]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.66

**Logs:** https://gist.github.com/Jenya705/7dbeef72bb4c2747047ad8c3dcb5d7cd

**Steps to Reproduce:**
 1. Join the server which is not registering the commands
 2. type the `/some command`

**Description of issue:**
When you are typing the command on the server without registered comnand, then it type in the chat `An unexpected error occurred trying to execute that command`. Vanilla client doesn't type that message.

**Comment by AterAnimAvis** [comment]
What's your server setup for this? I don't believe this is possible under a standard forge or vanilla server. You'd need to be able to send commands before you've received a `ClientboundCommandsPacket`.

**Comment by Jenya705** [comment]
> 

it is possible on the limbo server, which does not send this packet

**Comment by AterAnimAvis** [comment]
Closing this as [Limbo](https://github.com/LOOHP/Limbo) (which looks like a custom lobby server implementation) isn't a server system we support.

Note this is related to #8435 and #8438.
