### ISSUE TITLE
[1.19] Style method patches can be removed

### ISSUE THREAD

**Issue by kadir1243** [MinecraftForge/MinecraftForge#8457]
I think we can safely remove net/minecraft/network/chat/Style class patch because:
setUnderlined -> withUnderlined method exists in vanilla
setStrikethrough -> withStrikethrough method exists in vanilla
setObfuscated -> withObfuscated method exists in vanilla

**Comment by TheCurle** [comment]
Noted. I'll look into this in 1.19, because this is a binary breaking change.

**Comment by Alpvax** [comment]
They should probably be deprecated in 1.18 to encourage modders to switch (and make the 1.19 transition easier).
