### ISSUE TITLE
`EntityTeleportEvent.EnderEntity` is never dispatched for Shulkers

### ISSUE THREAD

**Issue by AizistralWasTaken** [MinecraftForge/MinecraftForge#8474]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.64

**Logs:** _unapplicable_

**Steps to Reproduce:**
 1. Read the javadocs of `EntityTeleportEvent.EnderEntity` and think that it will be dispatched for shulkers;
 2. Subscribe to the event and try to use it with this assumption;
 3. Be horribly disappointed.

**Description of issue:**
Doesn't seem like compatibility with aforementioned event is implemented at all for Shulkers.

**Comment by sciwhiz12** [comment]
Confirmed through code inspection. This seems to be [a 1.16.x patch](https://github.com/MinecraftForge/MinecraftForge/blob/cae822ced9f7ddfc9f5aafc59c73033d4c3de0ff/patches/minecraft/net/minecraft/entity/monster/ShulkerEntity.java.patch#L28-L40) that was dropped during the 1.17 update and patch cycle.
