### ISSUE TITLE
Item tags not loading

### ISSUE THREAD

**Issue by Jackbusters** [MinecraftForge/MinecraftForge#8491]
**Minecraft Version:** 1.18.2

**Forge Version:**40.0.1

**Logs:** 
[Latest](https://pastebin.com/xDdSyJWA)

**Steps to Reproduce:**
 1. Create an tag under `items`. In this case, arrows.json
 2. Assign the values of items which are correctly registered
 3. As shown in the latest log linked above, an error will output listing missing references, but the references were correctly registered. This same code & tags worked in 1.18.1.

**Description of issue:**
Use of the tag system, seemingly data tags under `items` specifically (arrows.json, piglin_loved.json), fail to load as they did in previous versions.

**Comment by MrEyeballs29** [comment]
It has confirmed that I have the same exact issue as well. Here is the link for it https://pastebin.com/qQSLS0bj. I am trying to find a way to correctly fix those tags but I unable to get them working successfully. I tried countless methods to get the tags loaded correctly but then I get errors every time.
