### ISSUE TITLE
1.18.2 - Creating Block or Item objects during Mod construction results in a locked registry Exception

### ISSUE THREAD

**Issue by Vazkii** [MinecraftForge/MinecraftForge#8504]
**Minecraft Version:** 1.18.2
**Forge Version:**  40.0.12

**Logs:** https://gist.github.com/Vazkii/4fb80634a7a4469ab41595230afe65f9

**Steps to Reproduce:**
 1. Construct an Item or Block object inside a code path called from a Mod's \<init>
 2. cry

**Description of issue:**
Attempting to construct a Block or Item object during construction (not registering, just construction) causes an IllegalStateException thrown from the `createIntrusiveHolder` call that generates the `builtInRegistryHolder` value.

In my case, Quark is structured assuming that early constructing is fine as long as registry is correctly done in the appropriate event.  This behavior was not present in 1.18.1 or prior versions, and these objects were safe to construct (not register) in this modloading phase.

Through a naive look at the usage of this field, I do not see the need to assign it at construction immediately, and it can be deferred to be assigned on register.

**Comment by SizableShrimp** [comment]
This is not a Forge bug. It is now Vanilla behavior. You cannot create any instances of Item, Block, EntityType, or BlockEntityType outside of the forge-provided registry events.

**Comment by Vazkii** [comment]
I do not see a reason for this to be the case. The restriction seems to be arbitrary given the uses for the field.

**Comment by SizableShrimp** [comment]
This is just how Vanilla works now. Vanilla locks its own registries. Forge unlocks them when it needs to for forge registry events, then locks them back. You should defer any creation of these classes to be within these registry events, not sure what else to tell you.

**Comment by XFactHD** [comment]
Also worth noting that construction of registered objects was always supposed to be done in the relevant registry event or the supplier passed to the deferred register and never in static init. Forge just didn't enforce it. This should have been obvious from the log spam warning about "an unexpected namespace, possibly intended override but most likely broken mod" when setting the registry name outside of the registry events
