### ISSUE TITLE
Is there a maven repo?

### ISSUE THREAD

**Issue by ThnksCJ** [MinecraftForge/MinecraftForge#8507]
For a pom.xml file is there a maven repo that works for imports like

```java
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
```

**Comment by TheCurle** [comment]
Yes.
The code you have given is not for a supported version, so we expect you to be able to do at least four seconds of research on the Internet before sending support requests to an issue tracker.
