### ISSUE TITLE
MissingMappings Event Bus

### ISSUE THREAD

**Issue by dhyces** [MinecraftForge/MinecraftForge#8513]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.0.15

**Description of issue:**
The MissingMappings event is fired on the MinecraftForge event bus rather than the Mod event bus, even though it inherits from RegistryEvent, which is fired on the mod bus. I feel as though it should either not inherit from a class that implements IModEvent or that it should fire on the mod bus.

**Comment by sciwhiz12** [comment]
This is a known peculiarity of the `MissingMappings` event, which kept getting forgotten as its use is niche enough that most people don't use it. There are plans to address this in 1.19 alongside some reworking of registry code.
