### ISSUE TITLE
[1.18.2-40.0.19] EntityTravelToDimensionEvent only fires for ServerPlayer

### ISSUE THREAD

**Issue by mrbooboostank** [MinecraftForge/MinecraftForge#8520]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.0.19

**Steps to Reproduce:**
 1. Replace ExampleMod.java with [this version](https://pastebin.com/uigu4KUe)
 2. Travel through a Nether/End Portal
 3. Transport some Entities through a Nether/End Portal
 4. Observe in the console that EntityTravelToDimensionEvent only fires for ServerPlayer

**Description of issue:**
EntityTravelToDimensionEvent claims to fire before an Entity travels to a dimension, but the event only fires for ServerPlayer. This seems to be because ForgeHooks#onTravelToDimension() is only called by ServerPlayer in ServerPlayer#changeDimension() and ServerPlayer#teleportTo().

**Comment by sciwhiz12** [comment]
Confirmed through code examination on 1.18.2-40.0.32. The hook in `Entity` seems to have been removed during the [1.16 update and patch cycle](https://github.com/MinecraftForge/MinecraftForge/commit/6d15febdb35b5676b1795b2965d6eb527bb336e6#diff-2b71f5e71155963095e35429b33c3ab4def410481bdc2b72210698c757b73ebaL233).
