### ISSUE TITLE
Brewing stand doesn't allow placing stacked items in the bottle slots without unstacking them manually first

### ISSUE THREAD

**Issue by Random832** [MinecraftForge/MinecraftForge#8521]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.0.19

**Logs:** no relevant log

**Steps to Reproduce:**
 1. Create a recipe with a stackable item [such as honey bottles] as the potion input
 2. Attempt to place a stack of more than one of this item in the brewing stand's bottle input slots [left click or right click while holding the items, or shift click from inventory]
 3. Expected: places a single item from the stack in the slot (or one in each slot for shift click), shrinking the source stack by one [or up to three for the shift click case]
 4. Actual: does not apparently accept the item at all. The recipe itself works, and if the stack is separated into single-item stacks before attempting to insert they work normally [side note: I got inconsistent results trying to insert through the item handler capability, though hoppers work fine.]

**Description of issue:**
The code responsible for this issue is in BrewingStandMenu, but I don't know the best way to approach fixing it while keeping patch size in mind.

This issue does not arise in vanilla because in vanilla the brewing stand only accepts potion bottles in these slots.

**Comment by ChampionAsh5357** [comment]
Can confirm, this is a two line issue as both `BrewingStandMenu#quickMoveStack` and `BrewingRecipeRegistry#isValidInput`  have checks to make sure that the stack is a single item. Since Minecraft has splitting logic within its menus, these two pieces can be removed with no adverse effects.
