### ISSUE TITLE
%minecraftFormatting

### ISSUE THREAD

**Issue by Morketh** [MinecraftForge/MinecraftForge#8526]
**Minecraft Version:** 1.12.2

**Forge Version:** forge-1.12.2-14.23.5.2860-universal.jar

**OS Version:** Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-171-generic x86_64)

**Logs:**

[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/8319821/latest.log)
[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/8319823/debug.log)
[screen.log](https://github.com/MinecraftForge/MinecraftForge/files/8319825/screen.log)

**Steps to Reproduce:**
 1. Launch minecraft with 

```
#!/bin/bash

MAX_MEMORY=10G
MIN_MEMORY=2G

# Server Home directory
SERVER_HOME=/opt/progs/minecraft

# Which Java
java=/opt/progs/java/jre1.8.0_251/bin/java

## System variables DO NOT EDIT ##
#JAR=forge-1.12.2-14.23.5.2854-universal.jar # Upgraded from Version 3/21/2022
JAR=forge-1.12.2-14.23.5.2860-universal.jar

$java -Xmx$MAX_MEMORY -Xms$MIN_MEMORY -jar -XX:+CMSClassUnloadingEnabled -Dfml.queryResult=confirm $SERVER_HOME/$JAR nogui

```
**Description of issue:**

Console spams `%minecraftFormatting` Latest.log (see above) is readable information, however the main console (stdout/stderr screen.log) is unreadable. 
Directory permissions are _not_ setup properly and the crash is a result of bad filesystem permissions since i normally run the minecraft server as the minecraft user/group in a screen daemon this should not affect the console read out to my knowledge.

**Comment by Shadows-of-Fire** [comment]
Minecraft 1.12 is not supported.
