### ISSUE TITLE
1.12.2 Forge

### ISSUE THREAD

**Issue by PandaGhost6** [MinecraftForge/MinecraftForge#8537]
1.12.2 Forge 14.23.5.2860

https://pastebin.com/0Qb7DLef
Error: net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk Exit Code: -1

**Comment by marchermans** [comment]
1.12 is not supported anymore.

**Comment by Ecdcaeb** [comment]
Mixin Error.
A full log please. a full log contains a crash-report and more than it.
