### ISSUE TITLE
(1.18.2 - 40.0.32) Non-functional Water Bucket

### ISSUE THREAD

**Issue by AstromanGaming** [MinecraftForge/MinecraftForge#8540]
**Minecraft Version:** {1.18.2}

**Forge Version:** {40.0.32}

**Logs:** {[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/8355700/latest.log)}

**Steps to Reproduce:**
 1. Craft a burket
 2. Click in the water
 3. Empty bucket

**Description of issue:**
I played in my solo world, I upgraded my forge. I was going to mined and I wanted to take water in a bucket, but suddenly this bug happened. (I know it's not the mods, because it was working before.)

**Comment by PlatinPython** [comment]
Tried it just now with that forge version, nothing installed besides forge and it worked fine. Can pick up water without any problems. So I'm just gonna guess one of your mods is causing the problem.

**Comment by AstromanGaming** [comment]
Strange, I will check that out, thanks and sorry for the unnecessary report.
