### ISSUE TITLE
Mods not loading

### ISSUE THREAD

**Issue by pedro2555** [MinecraftForge/MinecraftForge#8542]
What am I doing wrong?

![image](https://user-images.githubusercontent.com/1645623/160250872-4b643cf8-2e7b-46fe-ab51-61bb055a7684.png)
![image](https://user-images.githubusercontent.com/1645623/160250881-a7b03cb6-906c-4df3-ba3f-385fe93b40ee.png)
![image](https://user-images.githubusercontent.com/1645623/160250896-68e4834e-5c89-44bc-a0b0-0aff997551cb.png)

Windows 10, Minecraft Java Edition. Minecraft comes with java, apparently, but had to install Java anyway to run the forge installer, not sure what that amounts to.

[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/8356013/debug.log)

**Comment by gigaherz** [comment]
Those are fabric mods, not forge mods. And this is not a support forum. Please use the actual forge forums or Discord server in the future.
