### ISSUE TITLE
reload crash

### ISSUE THREAD

**Issue by blockgoblin31** [MinecraftForge/MinecraftForge#8544]
when I run /reload, the game crashes *sometimes*. probably a mod, but I have no idea which one.
Crash Report: https://pastebin.com/Q4M9SvTW

**Comment by blockgoblin31** [comment]
1.16.5

**Comment by sciwhiz12** [comment]
:wave: We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the [Forge Support Forums](https://forums.minecraftforge.net/). Please create a new topic on the support forum with this issue, and the conversation can continue there.

**Comment by blockgoblin31** [comment]
It could be, but it's currently over a month later and nothing's happened. Problem was adv. rocketry generating a bad datapack upon opening the world.

**Comment by TheCurle** [comment]
As sci mentioned, this issue tracker is not tech support. This is for reporting actual Forge bugs (when you know the real cause), not mod incompatibility issues. Use the forums.
