### ISSUE TITLE
Exception stopping the server after failed to bind port

### ISSUE THREAD

**Issue by gravit0** [MinecraftForge/MinecraftForge#8545]
**Minecraft Version:** 1.18.2

**Forge Version:** 1.18.2 - 40.0.32

**Logs:** https://gist.github.com/gravit0/617b21ab802ab766d9f5a90e14835af0

**Steps to Reproduce:**
 1. Install forge server
 2. Change port to busy or start another server on standard port
 3. Start forge server

**Description of issue:**
Incorrect shutdown after a failed port binding

**Comment by TheCurle** [comment]
This is not a Forge bug.
It's relatively harmless (no resource leaks since the JVM is shutting down anyway) so we're not going to take the initiative to fix this.

It'll be fixed when Mojang fix it, presumably in 1.19.

As per sciwhiz, the Mojang bug report: https://bugs.mojang.com/browse/MC-230525
