### ISSUE TITLE
%minecraftFormat console issue in 2860

### ISSUE THREAD

**Issue by AceSardonyx** [MinecraftForge/MinecraftForge#8551]
Ignore this. I solved it.
I was using the client forge for server.
My mistake, I should've looked first 🥲
It worked in previous versions if it is intended for server use though. I wouldn't think so. Switching out the client jar with the server one fixed tbe issue :]

**Comment by AceSardonyx** [comment]
The server still runs at least but it crashes time to time due to just upgrading and I can't see what it is and how to fix it :/

**Comment by ChampionAsh5357** [comment]
Hello, 1.12.2 is not supported by Forge. If you would like to receive help, please update to either the latest (currently 1.18.2) or LTS (1.16.5) versions.

**Comment by AceSardonyx** [comment]
Oh, ok
