### ISSUE TITLE
[1.18.2-40.0.36] Json dimensions in mods do not apply on first serverside world creation

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#8552]
When using a mod that has json dimensions inside, the initial creation of the world folder on a server will not contain that mod's dimension. This forces server owners to restart their server after the first time in order for the modded dimension to show up in game. Example of this can be seen using The Bumblezone mod but it also impacts many other dimension mods as well.

Bumblezone mod: https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge

Add the mod along with its dependencies to the mods folder for a server. Make sure the world folder is deleted or non-existent on the server. Start the server. Give yourself op and then do `/execute in` and see how the autocomplete does not show the modded dimension at all. Restart the server and try again without deleting the world folder. Now the command will show the modded dimension.

After initial world creation on server:
![image](https://user-images.githubusercontent.com/40846040/161433251-346dd0ef-e9b6-43e0-bea4-12e808927cb2.png)

After a server restart:
![image](https://user-images.githubusercontent.com/40846040/161433399-b1f21935-1fd4-438d-bf09-41a38036646e.png)

World folders:
[worldwithoutdimension.zip](https://github.com/MinecraftForge/MinecraftForge/files/8404753/worldwithoutdimension.zip)
[worldafterrestart.zip](https://github.com/MinecraftForge/MinecraftForge/files/8404765/worldafterrestart.zip)

Note how the in the level.dat file, the Data/WorldGenSettings/dimensions package is missing the modded dimension on first creation but gets it on restart.

**Comment by sciwhiz12** [comment]
Confirmed in 1.18.2-40.0.49, using the Forgedev's test sourceset -- specifically, checking for the dimensions added by `dimension_seed_test`: [`server_seed_dimension`](https://github.com/MinecraftForge/MinecraftForge/blob/c1874bb5ab10a5585ebb445da74cca08514aacf5/src/test/resources/data/dimension_seed_test/dimension/server_seed_dimension.json) and [`fixed_seed_dimension`](https://github.com/MinecraftForge/MinecraftForge/blob/c1874bb5ab10a5585ebb445da74cca08514aacf5/src/test/resources/data/dimension_seed_test/dimension/fixed_seed_dimension.json).

**Comment by sciwhiz12** [comment]
Additionally, (as found by @Cyborgmas) this seems to be a regression in behavior, due to the removal of a patch in `net/minecraft/server/Main` during 1.18.2's patch and update cycle. This was probably  dropped because of the refactors relating to world loading (driven by the changes in registries IIRC). https://github.com/MinecraftForge/MinecraftForge/blob/34291c1fb26d78b83755ca5b6a92cf1cf0ca1e11/patches/minecraft/net/minecraft/server/Main.java.patch#L72-L80
