### ISSUE TITLE
Adding an event that fire post /reload

### ISSUE THREAD

**Issue by skiprocks999** [MinecraftForge/MinecraftForge#8556]
Hello,

I have run into a situation where having an event that fires post-data pack reload (/reload) would be useful. 

Essentially, I have a JSON files that stores references to both tags and items. When the JSON is parsed initially, I am able to parse individual items instantly. However, at that point, tags have not been populated, so I must store everything related to tags in a temporary location. The catch is that I also need to sync the values I parse with the client, To handle this, I handle the tag values using ServerStartedEvent, as that fires before OnDatapackSyncEvent and after tags have been populated. 

The issue arises when I need to handle the tag values again that have been generated from /reload. Since the server has already started, the ServerStartedEvent will not fire to handle the temporarily stored tags. For now, I am able to get around this problem by modifying the supplier for my OnDatapackSyncEvent handler, but having a dedicated event that fires post datapack reload and before 
OnDatapackSyncEvent would be much cleaner.

I would attempt to add this myself, but I don't have nearly the experience to attempt something like this.

**Comment by TheCurle** [comment]
We have ReloadListeners for this purpose. Is there something they lack, or did you just not notice their existence?

**Comment by skiprocks999** [comment]
I was asked by Senor Sleepy to submit this one. I have it working via my ReloadListner currently.

**Comment by ChampionAsh5357** [comment]
Why are you resolving tags in the first place? All one would need to do is construct the tag key and then check it when necessary on whatever you were looking at.

This seems like a non issue especially in 1.18.

**Comment by Shadows-of-Fire** [comment]
Given that the condition context is now available from the `AddReloadListenerEvent`, does this issue have any merit (i.e. would this event solve any real issues?)

**Comment by Shadows-of-Fire** [comment]
Closing as I believe the condition context fulfills this request.
