### ISSUE TITLE
OpenGL ERRORS which probably cause freezes in Minecraft Forge 1.16.5

### ISSUE THREAD

**Issue by HarperV** [MinecraftForge/MinecraftForge#8558]
[](https://user-images.githubusercontent.com/103311577/162566506-bad69ecd-0b8b-48f7-befc-d4ec8ca2aae6.png)[](https://user-images.githubusercontent.com/103311577/162566638-359b9d73-3140-485f-8458-cf8714dd197e.png)I noticed in my latest log file such errors
image
Came to a conclusion that they coincides with the momets the game freezes when I render chunks on my map. It happens every time on the same chunks.
What does this error mean and how I can fix it?
Mods:
image
1.16.5
Forge - 36.2.33

**Comment by sciwhiz12** [comment]
:wave: We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the [Forge Support Forums](https://forums.minecraftforge.net/). Please create a new topic on the support forum with this issue, and the conversation can continue there.
