### ISSUE TITLE
PlaySoundAtEntityEvent's pitch and nullability issues

### ISSUE THREAD

**Issue by sciwhiz12** [MinecraftForge/MinecraftForge#8560]
**Minecraft Version:** 1.16.5 / 1.18.2
**Forge Version:** 1.16.5-36.2.33 / 1.18.2-40.0.44
**Logs:** _not applicable_

#### Steps to reproduce
 1. Investigate the call sites of `ForgeEventFactory#onPlaySoundAtEntity`.
 2. _Observe that in all call sites, the `pitch` parameter is not reassigned with the value from the event._
 3. _Observe that in all call sites except the one in `ClientPlayerEntity`/`LocalPlayer`, the player entity parameter is marked as `@Nullable`._
 4. _Observe and keep in mind that the `if`-conditional checks that `PlaySoundAtEntityEvent#getSound()` is `null` for stopping the sound from playing._
 5. Investigate the definition of `PlaySoundAtEntityEvent`.
 6. _Observe that the return value of `#getSound()` and the parameter to `#setSound(SoundEvent)` are not marked as `@Nullable`._

#### Description of issue
There are three issues with the current definition and implementation of `PlaySoundAtEntityEvent`.

  1. The call sites of the event's factory method do not reassign the `pitch` parameter with the value from the event's `getPitch()`, which renders any modification to the sound's pitch from event as useless.

  2. The `getEntity()` getter for the event (and the corresponding parameter of the event's factory method) is not marked as `@Nullable`, even though four out of the five call sites have the parameter marked as `@Nullable` (and indeed, there are many calls to those methods which pass a `null` entity).
  
     This may cause confusion for consumers of the event, which expect that the entity in the event is never `null` (according to the convention where nullable fields, parameters, and return values are marked with the `@Nullable` annotation).
  
  3. The call sites check the nullability of the return value of the event's `getSound()`, even though neither the getter nor the parameter of the corresponding setter is marked `@Nullable`.

**Comment by SizableShrimp** [comment]
The number of issues associated with this event seems to point to a lack of usage. Is there a good reason to keep this event? At the very least, I think it would make sense to overhaul in 1.19 into a `PlaySoundEvent` with subclasses `Position` and `Entity` for relevant data assuming there is a usecase.

**Comment by SizableShrimp** [comment]
These issues will be fixed with the new `PlayLevelSoundEvent` with subclasses `AtPosition` and `AtEntity` in 1.19. This event has been removed in favor of those two.

**Comment by sciwhiz12** [comment]
As 1.19 has released (quite a while ago), closing this issue as resolved.
