### ISSUE TITLE
I think forge can run a interlayer betwen forge and mods such as "kubejs"

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#8569]
I think forge can run a interlayer betwen forge and mods such as "kubejs" but that's jar file.
The interlayer can translation forge's method name to a stable method name.
That devloper can change his mod to another forge version or minecraft version.

**Comment by TheCurle** [comment]
Forge is a modloader. It loads mods, like KubeJS. It's not an abstraction layer.
