### ISSUE TITLE
[1.16.5] Netty non-heap memory leaking issue

### ISSUE THREAD

**Issue by XenonDB** [MinecraftForge/MinecraftForge#8573]
**Minecraft Version:** 1.16.5

**Forge Version:** 1.16.5.36.2.29

**Logs:** See links at Description below

**Description of issue:**
As the researching result says here: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4469
Someone took off the `packetbuffer.release()` and cause memory leaking.
This modifying already exist since forge 1.14
https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/patches/minecraft/net/minecraft/client/network/play/ClientPlayNetHandler.java.patch#L117

I'm wondering why release() be taken off here.

**Comment by marchermans** [comment]
Yes, this is known, at the moment this is not fixable due to a limitation in the integrated server.

If a packet in an exposed to LAN world is sent this way, then the packet's underlying buffer would immediately be released, because the first `ClientPlayNetHandler` is the one of the local player, (and Netty does in-memory transfer of data), and that prevents the sending net handler from reusing the buffer crashing the server and disconnecting the remote client.

**Comment by marchermans** [comment]
Reopening, because I fixed it in 1.18, so that needs to be backported.
This is not something I currently have the time though for: #8181 and #8042 are the templates for it.

**Comment by XenonDB** [comment]
> Yes, this is known, at the moment this is not fixable due to a limitation in the integrated server.
> 
> If a packet in an exposed to LAN world is sent this way, then the packet's underlying buffer would immediately be released, because the first `ClientPlayNetHandler` is the one of the local player, (and Netty does in-memory transfer of data), and that prevents the sending net handler from reusing the buffer crashing the server and disconnecting the remote client.

which one? `p_147240_1_` or `packetbuffer`?
`packetbuffer` is created by calling `copy()` of `p_147240_1_`, this will create an independent buffer from `p_147240_1_`
They don't interfere each other.

**Comment by marchermans** [comment]
> `packetbuffer` is created by calling `copy()` of `p_147240_1_`, this will create an independent buffer from `p_147240_1_`

It is not if the server is an exposed to LAN integrated server.
Hence it requires an additional check on the release of the buffer, and an unconditioned pre-send copy.

**Comment by XenonDB** [comment]
> > `packetbuffer` is created by calling `copy()` of `p_147240_1_`, this will create an independent buffer from `p_147240_1_`
> 
> It is not if the server is an exposed to LAN integrated server. Hence it requires an additional check on the release of the buffer, and an unconditioned pre-send copy.

You mean if the server is an exposed to LAN integrated server, the definition of `getData` in `SCustomPayloadPlayPacket` isn't `return new PacketBuffer(this.data.copy());` or `copy()` in `PacketBuffer` isn't `return this.source.copy();`?

**Comment by marchermans** [comment]
You can compare the patches applied between 1.16 and 1.18 and you will see that no copy behaviour on the data buffer is applied (getInternalData() in 1.16.x vs getData() in 1.18.x)

Doing the release without handling the copy behavior breaks all exposed to LAN scenarios, because the buffer is released to early.
You can see the relevant patches applied to later versions in my earlier comment.

**Comment by XenonDB** [comment]
I don't see anything wrap packetbuffer into NetworkEvent or getInternalData() called in handleCustomPayload()
Thus I don't understand why getInternalData() is relative with this

**Comment by XenonDB** [comment]
It seems you think even if there's no `release()` here, `packetbuffer` should be released somewhere right?

**Comment by marchermans** [comment]
Obviously yes, but that release() is not possible untill the handling of the packet in that particular environment is fixed.

**Comment by XenonDB** [comment]
According the log here https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4469#issuecomment-1100662507
You can see when copy() is called, netty create an InstrumentedUnpooledUnsafeNoCleanerDirectByteBuf. (in Java 8)
Notice it's "NoCleaner", that means this byte buffer will not use cleaner to recycle unused direct buffer.
Because NoCleaner is unsupported in Java 16, netty always create byte buffer with cleaner. 

When I force netty not to use NoCleaner mode by adding argument `-Dio.netty.maxDirectMemory=0`, there's no such memory leaking happened.

Therefore, could we force netty to not use NoCleaner mode on any byte buffer that we can't fully control to avoid such issue?

**Comment by Matyrobbrt** [comment]
1.16 is now out of support.
