### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by zMasterSkill** [MinecraftForge/MinecraftForge#8579]
**Minecraft Version:** 1.12.2

**Forge Version:** 1.12.2 - 14.23.5.2860

**Logs:** None

**Description of issue:**
Im trying to create a forge server, but when i try to start it, i get an error. (screenshot)
Could someone help me fix it?
Im using Java 17.0.1 on Windows 11.

![cmd_UXOWysSd0U](https://user-images.githubusercontent.com/67023945/164551949-3cad2c8b-36e7-418e-96d1-d2e13e332dbd.png)

**Comment by TheCurle** [comment]
You were told no on the Discord, and this issue tracker is not tech support.
