### ISSUE TITLE
Can't execute /tutorial args command

### ISSUE THREAD

**Issue by Nononitas** [MinecraftForge/MinecraftForge#8580]
**Minecraft Version:** 1.18.2

**Forge Version:**  40.0.40

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
Use a bukkit plugin which add a /tutorial command with some args
Then execute for example the "/tutorial next" command
 Error appears

**Description of issue:**
When executing a bukkit registered command named /tutorial args on a vanilla/paper server I will get these errors. 
Without forge it works
![grafik](https://user-images.githubusercontent.com/47149720/164808974-0d4658b5-186d-4768-8b84-e0d9ee50e594.png)

**Comment by DaemonUmbra** [comment]
Do you have a specific setup I could test with?
Paper version and Plugin name and version perhaps?

**Comment by Nononitas** [comment]
Yes https://ci.pufferfish.host/job/Pufferfish-1.17/22/
Plugin is private I can't share that, but the command is simply "/tutorial next" executed by the chat component from within the chat

**Comment by DaemonUmbra** [comment]
You can confirm that is the server version? I cannot connect to that version with a 1.18.2 client.

**Comment by Nononitas** [comment]
Using Viaversion and Protocollib (forgot to mentioned that)
https://www.spigotmc.org/resources/viaversion.19254/

**Comment by DaemonUmbra** [comment]
I'm unable to reproduce this issue with the following:
  * Client:
    * Forge 1.18.2-40.1.0 (8ade7bbaebdaa263b0391fd165d5e4e033b52c60)
  * Server:
    * [Pufferfish](https://ci.pufferfish.host/job/Pufferfish-1.17/22/)
    * Plugins:
      * [ViaVersion](https://www.spigotmc.org/resources/viaversion.19254/)
      * [ProtocolLib](https://www.spigotmc.org/resources/protocollib.1997/)
      * [Simple Tutorials](https://www.spigotmc.org/resources/simple-tutorials.88583/)

Result:
![java_8etPtcBaNB](https://user-images.githubusercontent.com/5004171/164837006-271c9f8f-b25b-4f5e-a405-16756c9c072c.gif)

**Comment by Nononitas** [comment]
As I said for example "/tutorial args" or as shown in the screenshoot /tutorial next or /tutorial cancel

**Comment by Nononitas** [comment]
The base command also works for me but not with args

**Comment by DaemonUmbra** [comment]
For the test to work I need a plugin that is confirmed to have a command to test, I am not familiar with Bukkit plugins and you are not providing me with any examples, this I am missing a key piece in testing.

**Comment by Nononitas** [comment]
Well I can't share the plugin if you want to try it out yourself, you can join on my server keinsurvival.de and I will guide you there.

**Comment by DaemonUmbra** [comment]
Well can you provide a different plugin that has the same issue?

**Comment by Nononitas** [comment]
So you want me to code a plugin for you because you don't want to just join a server?

**Comment by DaemonUmbra** [comment]
No I want you to find and provide a plugin that has the issue. I need a server that I control for proper testing.

**Comment by Nononitas** [comment]
https://file.io/t7KIzjOcRBPQ
First add tutoiral points with /tutorial addPoint description
Add like two points 
then execute /tutorial and click in the chat on the green or red message

**Comment by DaemonUmbra** [comment]
![image](https://user-images.githubusercontent.com/5004171/164936233-c6181ee5-bd57-4406-82af-9a0ba4a7a657.png)

**Comment by Nononitas** [comment]
.-. then write me a discord pm please Nononitas#9256
