### ISSUE TITLE
CapabilityDispatcher.serializeCaps can produce empty tags

### ISSUE THREAD

**Issue by Technici4n** [MinecraftForge/MinecraftForge#8586]
```java
    @Override
    public CompoundTag serializeNBT()
    {
        CompoundTag nbt = new CompoundTag();
        for (int x = 0; x < writers.length; x++)
        {
            nbt.put(names[x], writers[x].serializeNBT());
        }
        return nbt;
    }
```
I think this should return `null` if there are no serializable caps instead of currently returning an empty tag, not sure though.

**Comment by Shadows-of-Fire** [comment]
`CapabilityDispatcher` implements `INBTSerializable` which specifies a prototype of `T serializeNBT();`, which is not nullable.
