### ISSUE TITLE
my game is crashing when i run forge 1.12.2

### ISSUE THREAD

**Issue by TheCodeInjection** [MinecraftForge/MinecraftForge#8592]
**Minecraft Version:** {1.12.2}

**Forge Version:** {1.12.2-forge-14.23.5.2859}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:** crashing

**Comment by TheCurle** [comment]
Dear God. I don't think i've seen a worse issue report in my life.

Cannot reproduce.
