### ISSUE TITLE
minecraft crash

### ISSUE THREAD

**Issue by TheCodeInjection** [MinecraftForge/MinecraftForge#8593]
**Minecraft Version:** {1.12.2}

**Forge Version:** {1.12.2-forge-14.23.5.2859}

**Logs:** {[Link(s) to GitHub Gist with full latest.log and/or crash report](https://gist.github.com/TheCodeInjection/c3b0cf7f9148920d9efc9eab7596132a)}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**my minecraft launcher is crashing everytime i try to start forge**

**Comment by TheCurle** [comment]
Please stop.
