### ISSUE TITLE
FoodProperties call is not guaranteed to be on the same item for which edibility is checked

### ISSUE THREAD

**Issue by yrsegal** [MinecraftForge/MinecraftForge#8602]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.1.0

**Logs:** https://gist.github.com/yrsegal/9e4ac09a904aa4d4c5d150818ec326a0 (not my log, but same issue)

**Steps to Reproduce:**
 1. Use any mod that simulates a right click with a BlockItem that isn't in the player hand (i.e. Quark with the seed pouch or trowel)
 2. Simulate a click with a BlockItem that's also edible.
 3. The game crashes.

**Description of issue:**
The code [here](https://github.com/MinecraftForge/MinecraftForge/blob/f9380513732131d11aaf9d643ee14681ba1b3d99/patches/minecraft/net/minecraft/world/item/Item.java.patch#L36-L39) doesn't check that the item in the hand is the same one for which `this.isEdible()` (srg `m_41472_`) is being invoked. This means that items which are inedible will be treated as though they are edible, and then NPE due to not having food properties of their own.

**Comment by sciwhiz12** [comment]
Could you please provide a small code example of an item which can demonstrate this issue, with instructions on how to use said item?

**Comment by yrsegal** [comment]
https://github.com/VazkiiMods/Quark/blob/370060283398aadb5de14e12b7f90f3acd327d1a/src/main/java/vazkii/quark/content/tools/item/SeedPouchItem.java

Put some carrots or potatoes in here, then try to click on something that isn't farmland.

**Comment by sciwhiz12** [comment]
Confirmed on Forge 1.18.2-40.1 in a Forgedev workspace, using the following item as temporarily registered through the `CustomShieldTest` test mod. 

To replicate the crash:
- Obtain the item through `/give @s custom_shield_test:item_placer`.
- Put the item in any slot of the hotbar except the rightmost one.
- Put a potato item (`minecraft:potato`) in the immediately-right slot of that item.
- Right-click on any block that is not the top-part of a farmland block (on farmland, it plants the potato).

<details>
<summary>Test code of <code>net.minecraftforge.debug.item.ItemPlacerItem</code></summary>

For the purposes of copyright, this code is under CC0.
```java
package net.minecraftforge.debug.item;

import net.minecraft.world.InteractionResult;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.context.UseOnContext;
import net.minecraft.world.phys.BlockHitResult;
import org.jetbrains.annotations.Nullable;

/**
 * An item which, on right-click on a block, uses the item in the adjacent slot if it is a
 * {@linkplain Inventory#isHotbarSlot(int) hotbar slot}.
 */
public class ItemPlacerItem extends Item
{
    public ItemPlacerItem(Properties properties)
    {
        super(properties);
    }

    @Override
    public InteractionResult useOn(UseOnContext context)
    {
        @Nullable final Player player = context.getPlayer();
        if (player == null) return super.useOn(context);

        final int currentSelectedSlot = player.getInventory().selected;
        final int nextSlot = currentSelectedSlot + 1;
        if (!Inventory.isHotbarSlot(nextSlot)) super.useOn(context);

        final ItemStack nextSlotStack = player.getInventory().getItem(nextSlot);
        if (nextSlotStack.isEmpty() || nextSlotStack.getItem() == this) return super.useOn(context);

        final UseOnContext newContext = new UseOnContext(context.getLevel(), context.getPlayer(), context.getHand(), nextSlotStack,
                new BlockHitResult(context.getClickLocation(), context.getClickedFace(), context.getClickedPos(), context.isInside()));

        return nextSlotStack.useOn(newContext);
    }
}
```

</details>
