### ISSUE TITLE
[1.19.x] The Fluid API Overhaul

### ISSUE THREAD

**Issue by ChampionAsh5357** [MinecraftForge/MinecraftForge#8608]
# Introduction

[Previous PR](https://github.com/MinecraftForge/MinecraftForge/pull/7992) | [Current Fork](https://github.com/ChampionAsh5357/MinecraftForge/tree/fluid-redesign)

One of the few things that has been massively unfinished is the implementation of a feature complete fluid API within Forge. This is due to the massively hardcoded nature of fluids and their behavior since the Flattening back in 1.13. This issue aims to discuss the current conditions of fluids within Forge along with what changes have been taken to remedy their changes. Additionally, this issue will look at fluid implementations within the Forge ecosystem and fix any issues or concerns that may not have been addressed in previous versions, along with provide new extensions and hooks as needed to support an extensible use case.

If there are any suggestions or changes that should be discussed, please leave it below or ping me in the discord. I would like to incorporate as many usecases as possible to make Forge's fluid API as feature complete as possible.

## Current Progress

#7992 which defined the previous changes made to overhaul fluids is currently under a full redesign due to certain issues that have arisen as a result of choices made by Forge's original PR. For a current view of the progress done on fluids, you can view [this branch](https://github.com/ChampionAsh5357/MinecraftForge/tree/fluid-redesign) on my fork. I will be updating it as needed such that when 1.19 comes around, the current progress can be easily transitioned.

For redesign purposes, all previous fluid code within Forge has been marked as deprecated. This does not mean it will be removed, just that it hasn't been looked over yet during the redesign process. The only types mentioned for removal are those annotated with `forRemoval` set to true.

## Limitations

There are certain things that will not be up for discussion as they were decided beforehand or do not have a fully defined agreement. Any new limitations after this issue opens will also appear here.

- The Fluid Size of a bucket will remain at 1000. This has been fully decided by Forge when #8166 was closed.

# The Fluid API

This will be broken down into four sections: Common, Physics, Rendering, and Capability. These sections may be left empty and completed over time depending on how much work has currently been done in those sections. Additionally, sections that contain checkboxes will determine whether the task has been completed and pushed to the branch on the above fork.

## Common

- [x] Introduce a new method of linking fluids together between their source block and flowing block.

This method was necessary as a result of wanting to decouple fluid logic from tags. As such, fluids were given a new required registry object called `FluidType`. This defines the behavior and traits of a fluid whether flowing or the source. This will be used to represent the fluid as a whole and not as a source block or flowing block. This deprecates the behavior of `FluidAttributes` for removal as it was never a unique static object to accurately represent the fluid. Most of the properties for `FluidAttributes` will be moving onto the `FluidType` as a result. `FluidType` can also be additionally extended to provide for complex logic on overrides which are not typically available through the builder.

As `FluidType` is a registry object, it must be registered to be able to use within your fluid. It can be set on a fluid by overriding `Fluid#getFluidType`.

- [x] Give fluids a description id.

Previously known as `translationKey`, the description id, when specified, represents the translation key of the `FluidType`. If none is specified during building, it will default to `fluid_type.modid.registry_name` as defined by vanilla syntax.

- [x] Sounds

Fluids tend to have different sounds depending on certain actions whether filling/emptying a bucket or stepping into and swimming. Sounds in fluids are represented using a SoundAction which defines what sound should be played during the given action for a sound. Current SoundActions are BUCKET_FILL and BUCKET_EMPTY to replicate previous behavior.

- [x] Hydration

Fluids are able to hydrate blocks around them such as concrete, farmland and sponges. Hydration follow the following call hierarchy; at any point the property can be overridden to perform a different behavior from the global behavior defined by the method beneath.

- IForgeBlockState#canBeHydrated
- IForgeBlock#canBeHydrated
- IForgeFluidState#canHydrate
- IForgeFluid#canHydrate
- FluidType#canHydrate

These methods take in a `BlockGetter`, the state of the block being hydrated, the position of where the `BlockState` is/will be located, the state of the fluid hydrating the block, and the position of where the fluid is. Currently, hydration is supported for farmland, sugar cane, coral, sponge, and concrete powder.

- [x] Fluid Interactions

Fluid interactions are defined through the FluidInteractionRegistry. Each interaction is registered by the source which is checking the surrounding fluids, the predicate on when to execute a given interaction, and what to do on interaction. Vanilla uses lava as the source for checking the surrounding fluids for water or blue ice with soul soil underneath.

- [x] Properties

Fluids have common properties that can be applied in different circumstances. They may have different accessors depending on the use case.

- lightLevel: The light level emitted by the fluid
    - Empty: 0
    - Water: 0
    - Lava: 15
    - Default: 0
- density: Density of the fluid, arbitrary number where negative density is lighter than air. Approximately realistic to actual fluids.
    - Empty: 0
    - Water: 1000
    - Lava: 3000
    - Default: 1000
- temperature: Temperature of the fluid, arbitrary number where higher temperature indicates it is hotter. Approximately realistic to actual fluids.
    - Empty: 0
    - Water: 300
    - Lava: 1300
    - Default: 300
- viscosity: Resistance of movement through the fluid, arbitrary number where higher numbers means the entity moves slower through the fluid and vice versa. Negative values are not permitted. Approximately realistic to actual fluids.
    - Empty: 0
    - Water: 1000
    - Lava: 6000
    - Default: 1000

## Physics

- [x] Replace vanilla fluid physics using tags with a new system.

To accommodate the move from tag physics, the `FluidType` system will be used to denote the commonalities between multiple fluids instead. This system deprecates vanilla's system of handling fluid physics and as such, no longer handles any logic in relation to physics. A `FluidType` can define the following properties. Additionally, overrides which call these methods can be found in the associated entity extensions (`IForgeEntity`, `IForgeLivingEntity`, `IForgeBoat`).

- Motion scale: A scalar which determines an entities acceleration in the fluid
    - Empty: No scaling (1)
    - Water: Scaled by 0.014
    - Lava: Scaled by 0.007 in Ultrawarm dimensions, otherwise 0.0023
    - Default: Scaled by 0.014
- Pushing Entity: Whether an entity can be pushed by the fluid
    - Empty: False
    - Water: True
    - Lava: True
    - Default: True
- Fluid motion: How an entity can move through the specified fluid
    - Empty: As defined by vanilla
    - Water: As defined by vanilla
    - Lava: As defined by vanilla
    - Default: Uses water movement when false, otherwise custom movement when true
- Swimming: If the entity is able to swim in the fluid
    - Empty: False
    - Water: True
    - Lava: False
    - Default: True
- Drowning: If the entity is able to drown in the fluid
    - Empty: False
    - Water: True
    - Lava: False
    - Default: True
- Fall Distance Modifier: When the entity comes into contact with the fluid, how much should the fall distance be decreased every tick
    - Empty: No scaling (1)
    - Water: Scaled by 0
    - Lava: Scaled by 0.5
    - Default: Scaled by 0.5
- Extinguishing: If the entity can be extinguished by the fluid (this typically refers to fire in water, but it can be left up to the modder's discretion)
    - Empty: False
    - Water: True
    - Lava: False
    - Default: False
- Multiply Source Blocks: If the fluid can multiply its source blocks
    - Empty: False
    - Water: True
    - Lava: False
    - Default: False

Additionally, the entity defines some more properties which can be modified based on the fluid:

- Swimming: If the fluid permits swimming, then this will be checked to see whether the entity can swim in the fluid
    - Default: If the entity is sensitive to water, then as long as the fluid type is not water, otherwise true
- Rising/Sinking: Determines the movement of the entity when attempting to rise or sink in the fluid deliberately
    - Default: Copied from LivingEntity jumpInLiquid and sinkInLiquid respectively
- Drowning: If the fluid permits drowning, then this will be checked to see whether the entity can drown in the fluid, only is checked for standard air similar to the player uses
    - Default: If the type is water, then if the entity cannot breather underwater, else if it is a WaterAnimal but not a dolphin not in water then return true, otherwise if there is a fluid.

- [x] Handle Item Movements

Items are a special case of entity as their fluid logic is typically held internally. As such, the item logic can be specified by overriding `FluidType#setItemMovement`.

- Empty: As defined by vanilla
- Water: As defined by vanilla
- Lava: As defined by vanilla
- Default: Water movement

- [x] Boating

Boats are also a special case of entity since they are typically only reserved for water. This allows the mod to specify whether a fluid can be boated on via `FluidType#supportsBoating`.

- Empty: False
- Water: True
- Lava: False
- Default: False

- [x] Pathing

Entities may pathfind around fluids as blocks depending on their node evaluators. Fluids should be able to specify how an entity should pathfind in a given situation.

Pathing is implemented for the WalkNodeEvaluator for the current block and surrounding adjacent blocks. BlockPathTypes is also made an extensible enum for this purpose. Additionally, to support the difference between fluidloggable blocks, the logic can be applied at different times as necessary, though this is only used by water in vanilla.

- Empty: Null, Null
- Water: WATER, WATER_BORDER
- Lava: LAVA, Null
- Default: WATER, WATER_BORDER

## Rendering

- [x] IFluidRenderProperties

Implements the base type for handling rendering of a given a `FluidType` in Forge.

- [x] View Overlay

Fluids allow for an overlay to applied over the screen when submerged in a fluid. This can be done by specifying a texture for rendering in `IFluidTypeRenderProperties#getRenderOverlayTexture`. Additionally, custom rendering logic can be implemented via `#renderOverlay` instead.

- [x] Fog Rendering

Fluids allow for fog to be rendered as a way of giving the effect that view is limited under fluids. Custom fluids can either modify the color or rendering method used via `IFluidTypeRenderProperties#modifyFogColor` and `#modifyFogRender`. Otherwise, the default fog rendering will occur.

- [x] Fluid Models

Fluids are typically rendered through `LiquidBlockRenderer` which makes their rendering method hardcoded. This should be replaced with a custom model loader which defines the basic properties a fluid can take on. Additionally, the model loader should also be able to accept a dynamic renderer similar to block entities to allow for more diverse fluid renderings. The model loader will hold the information for the still, flowing, and overlay texture.

Didn't have time to finish before 1.19, so the still, flowing, and overlay textures will just be moved to `IFluidTypeRenderProperties` instead.

- [x] Color

The fluid's color will be determined by `IFluidTypeRenderProperties#getColorTint` which can be modifiable depending on the state of the fluid and the world around it.

## Capability

No time to look over before 1.19, so they will be left alone.

**Comment by eerussianguy** [comment]
Would be great to integrate bubble columns into this. Currently there's no good way to let for example magma blocks make bubble columns in your own fluid. Simplest way would be a hook in `BubbleColumnBlock#updateColumn` that lets you run your own logic to place something before vanilla does. And then if we wanted to be really nice to modders, we could add a forge bubble column block class that takes a fluid supplier.

The more expansive solution would be to allow fluids to know what their bubble column is, patch `Fluid` as a parameter into `updateColumn`, and then handle that automatically.

**Comment by florensie** [comment]
> This system deprecates vanilla's system of handling fluid physics and as such, no longer handles any logic in relation to physics

That's going to take a lot of patching, and will be hard to maintain.

**Comment by TheCurle** [comment]
Everybody involved knows this painfully well.

However, the current fluid API was designed a long long time ago, and it's just not enough any more. This is more or less essential.

**Comment by florensie** [comment]
Here's a reference for what it took for me to implement a simple swimming on/off event: https://github.com/florensie/ExpandAbility/tree/1.18/common/src/main/java/be/florens/expandability/mixin/swimming

**Comment by TheCurle** [comment]
You need not tell us how much work this is.

We know.

**Comment by florensie** [comment]
I thought it might help... ?

**Comment by gigaherz** [comment]
Help is appreciated, but you need to understand that this is just the newest iteration of the PR, the fluids team has been working on this for 2 years, and there have been discussions about this for longer.

**Comment by MrScautHD** [comment]
amazing!
