### ISSUE TITLE
Dependency addition failure.

### ISSUE THREAD

**Issue by 12345-mcpython** [MinecraftForge/MinecraftForge#8619]
**Minecraft Version:** 1.18.2

**Forge Version:**  40.1.0

**Logs:** https://gist.github.com/12345-mcpython/1363f4ea2fc16f1dcf4cc786d0bf2c82

**Steps to Reproduce:**
 1. Download 40.1.0 MDK
 2. Unzip
 3. gradlew runServer

**Description of issue:**

When I run "gradle runServer".It throws error.
[build.gradle](https://gist.github.com/12345-mcpython/a60614cf398f7fec941b02b4dac22e96)
Project structure:
![image](https://user-images.githubusercontent.com/63326494/167578354-efd850e6-d23f-4735-854c-75c44bad5239.png)

**Comment by AterAnimAvis** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the [Forge Support Forums](https://forums.minecraftforge.net/). Please create a new topic on the support forum with this issue, and the conversation can continue there. Or join our [Discord](https://discord.gg/forge)

Saying that in addition I'll point you to [this gist](https://gist.github.com/SizableShrimp/66b22f1b24c255e1491c8d98d3f11f83), that explains how to load libraries in Forge 1.17+. If you have further issues please visit either the Forum or Discord linked above.
