### ISSUE TITLE
[RFC 1.19] Replace `LazyOptional<T>` by `@Nullable T`

### ISSUE THREAD

**Issue by Technici4n** [MinecraftForge/MinecraftForge#8620]
_Please don't kill me, I just want productive and constructive technical talk to improve Forge. If you don't want it, feel free to close the issue, but hear me out first._

`LazyOptional` does 3 things:
- it provides a safe wrapper around `null` values (Optional),
- it allows lazy computation of values (Lazy),
- it allows invalidating the wrapped value, and listening to such invalidations.

I claim that 1 is fine, 2 is useless and 3 is nice in theory, but bad in practice, and it has a better alternative. So I suggest only keeping the "optional" part with `@Nullable T`. I'd also be fine with `Optional<T>` since I know some people prefer that.

## Why lazy is useless
The motivation for laziness is performance: it should allow checking if a capability instance exists without having to compute it. However, there is almost no use case for that: most queries need to use the returned instance. If someone has a proper counterexample, please let me know! Most examples I've seen involve actions that happen very rarely, and as such don't matter for performance. See the following example:

"When a pipe is placed it can quickly check if adjacent blocks support the item handler capability without having to resolve it."
Sure, but then if the capability exists, the pipe will have to query it to handle pipe I/O, and that's going to be _a lot_ more frequent and expensive than the one-off existence check.

## Why change invalidation is impractical
The motivation for change invalidation is again performance: queries can be expensive, and being able to cache queried capability instances means that it's not necessary to query them very often.

### On query performance
A capability query happens in two parts:
1. `world.getBlockEntity(pos)`
2. `blockEntity.getCapability(cap, side)`

Usually 1) is very expensive and 2) is very cheap (it's easy to store the capability instance in a block entity field and return it directly). 1) can easily be eliminated by caching the BE at the target position and invalidating the cache with BlockEntity load/unload events.

I wrote a helper to handle this transparently in the past and it was able to perform a few million capability queries per second IIRC. I can provide code and benchmarks to back that up if you'd like. I'd be happy to PR such a helper to Forge if this issue is accepted. Based on that, I think it's safe to say that the BE cache appropriately solves the performance issue.

### Problem 1: modders don't invalidate
An issue with this system is that some mods just don't invalidate their capabilities. Of course, you can dismiss this by saying it's their fault, but in light of the previous item I think the whole system can be considered unnecessary, and therefore there is no other incentive for modders to invalidate their caps other than "because Forge says you should".

The main advantage of the aforementioned caching system is that it doesn't require any special support from modders,
whereas LazyOptional invalidation requires quite a bit of effort and is easy to forget or get wrong.

### Problem 2: block capabilities
Another issue is allowing blocks without block entities to expose capabilities, for example lava cauldrons or composters (https://github.com/MinecraftForge/MinecraftForge/issues/6691). I proposed another solution in https://github.com/MinecraftForge/MinecraftForge/issues/8216, but removing LazyOptional would make this a lot easier.

## Conclusion
This is what offering a capability would look like:
```java
private IItemHandler topHandler = ...;

@Override
public <T> @Nullable T getCapability(Capability<T> cap, @Nullable Direction side) {
    if (side == Direction.UP) {
        return (T) topHandler; // equivalently and more idiomatic: cap.cast(topHandler);
    }
    return super.getCapability(cap, side);
}
```

This is what getting a capability would look like:
```java
@Nullable
IItemHandler maybeHandler = blockEntity.getCapability(CapabilityItemHandler.INSTANCE, side);
if (maybeHandler != null) {
    // Handler is present, optionally use it
}
// (could also be done with Optional instead)
```

I think this change would be best implemented in the 1.19 port if it is accepted, so I don't think it wouldn't make sense for me to PR it, but I can PR the BE caching system soon so it will be available to modders updating to early 1.19 Forge versions, as a drop-in replacement to the consumer side of LazyOptional.

In fact, I am offering to PR the following if this issue is accepted:
- (1.18) BE caching system.
- (1.19) block capabilities and their implementation for relevant vanilla blocks (lava cauldrons and composters).

**Comment by TheCurle** [comment]
Honestly, i think we should consider this seriously.
The current LazyOptional method is a point of confusion for new and experienced modders alike, and it's clear that the constant resolving of the capability data every time it's used is far outweighing any performance benefit we get from the first time it's used.

I'm not fully convinced that a simple Nullable return value is good enough, but something less significant than LazyOptional is something we should look into.

**Comment by LexManos** [comment]
No we have already discussed this if you actually read the history of the capability classes you would know that. You're essentially wanting us to revert to the original design which had issues that caused the change to the current design. I refuse to make this a perpetually circular development because some people dont understand how to read documentation or implement simple things like factories/suppliers. 

As for the issues with invalidation, your system doesnt actively monitor things that change during the lifespan of an object which is why the subscriber list exists. There is no way to automatically cover every case of a object changing its capabilities. There is a level of effort that has to be done on the modders side.

**Comment by DaRealTurtyWurty** [comment]
> because some people dont understand how to read documentation

It might help if there actually was some documentation. But ya kno, cant ask for the simple things nowdays can we?
