### ISSUE TITLE
Coremod can not find class in net.minecraft.network

### ISSUE THREAD

**Issue by Raw-fish** [MinecraftForge/MinecraftForge#8626]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.1.0

**Logs:** 
```
[165月2022 19:38:17.217] [pool-3-thread-1/DEBUG] [net.minecraftforge.coremod.transformer.CoreModBaseTransformer/COREMOD]: Transforming net/minecraft/nbt/TagParser
[165月2022 19:38:17.234] [pool-3-thread-1/DEBUG] [net.minecraftforge.coremod.CoreMod.jei/COREMODLOG]: got TagParser
[165月2022 19:38:18.020] [pool-3-thread-1/DEBUG] [net.minecraftforge.coremod.transformer.CoreModBaseTransformer/COREMOD]: Transforming net/minecraft/world/entity/monster/Blaze
[165月2022 19:38:18.025] [pool-3-thread-1/DEBUG] [net.minecraftforge.coremod.CoreMod.jei/COREMODLOG]: got Blaze
```

**Steps to Reproduce:**
 1. Write a coremod like this 
```
var ASMAPI = Java.type('net.minecraftforge.coremod.api.ASMAPI');

function initializeCoreMod() {
	return {
		'normal': {
			'target': {
				'type': 'CLASS',
				'name': 'net.minecraft.world.entity.monster.Blaze'
			},
			'transformer': function(node) {
				ASMAPI.log('DEBUG',"got Blaze");
				return node;
			}
		},
		'alsoNormal': {
			'target': {
				'type': 'CLASS',
				'name': 'net.minecraft.nbt.TagParser'
			},
			'transformer': function(node) {
				ASMAPI.log('DEBUG',"got TagParser");
				return node;
			}
		},
		'notFound': {
			'target': {
				'type': 'CLASS',
				'name': 'net.minecraft.network.CompressionDecoder'
			},
			'transformer': function(node) {
				ASMAPI.log('DEBUG',"got CompressionDecoder");
				return node;
			}
		}
	};
}
```
 3. Launch minecraft
 4. Try to find "got CompressionDecoder" in debug.log, but only found "got Blaze" and "got TagParser"

**Description of issue:** 
Coremod seems can not find any class or method in net.minecraft.network
Besides, there are something wrong in src/main/resources/coremods/add_bouncer_method.js
```
function initializeCoreMod() {
    return {
        "getLanguage_bouncer": addBouncer("net.minecraft.network.play.client.CClientSettingsPacket", "func_149524_c", "getLanguage", "()Ljava/lang/String;"),
    }
}
```
"func_149524_c" is an old name

**Comment by sciwhiz12** [comment]
:wave: We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the [Forge Support Forums](https://forums.minecraftforge.net/) or [Forge Discord](https://discord.gg/forge). Please create a new topic on the support forum with this issue or ask in the `#tech-support` channel in the Discord server, and the conversation can continue there.

Additionally, the purported issue in `src/main/resources/coremods/add_bouncer_method.js` does not affect anything, given that the class it tries to target does not presently exist. The entry will be removed in the future (when convenient to maintainers).

**Comment by Raw-fish** [comment]
Wait, you mean it's not a bug?
But coremod can't find net.minecraft.network.CompressionDecoder or any other class in net.minecraft.network, I thought it was a bug 🥺
net.minecraft.network.play.client.CClientSettingsPacket does not exist, but net.minecraft.network.CompressionDecoder should exist.
