### ISSUE TITLE
1.18.2 Forge Minecraft crashing.

### ISSUE THREAD

**Issue by NeoGalaxyEYesPhotonDragon** [MinecraftForge/MinecraftForge#8628]
A few days ago, I was playing modded Minecraft, but a day or two later, it crashes once the launcher loads. How could I solve the issue 'Exit Code 1'?, I've tried fixing it by re-installing Java 17,Forge and each of the mods' newest version, I tried running each mod individually in Forge Minecraft but they all crashed, displaying 'Exit Code 1', running Minecraft on its latest release doesn't crash, if that's any helpful data.

**Comment by sciwhiz12** [comment]
:wave: We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the [Forge Support Forums](https://forums.minecraftforge.net/) or [Forge Discord](https://discord.gg/forge). Please create a new topic on the support forum with this issue or ask in the `#tech-support` channel in the Discord server, and the conversation can continue there.
