### ISSUE TITLE
SimpleChannel messages are handled on the main thread

### ISSUE THREAD

**Issue by SquidDev** [MinecraftForge/MinecraftForge#8642]
**Minecraft Version:** 1.18.2
**Forge Version:** 40.1.0

**Description of issue:**

SimpleChannel (and the rest of Forge's networking stack) reads, writes and handles messages on the main thread (render/server thread, depending on side) rather than on the dedicated Netty threads.

**Steps to Reproduce:**
 1. Create and register a simple channel and message, and add a breakpoint inside its encoder, decoder and handler. Alternatively, add breakpoints inside Forge's built-in `HandshakeMessages`.
 2. Send your registered message.
 3. Observe the breakpoints are hit on the render or server thread, and not the network thread as expected.

**Further comments:**
It's not clear whether this is intended or not. `NetworkEvent.Context.enqueueWork` exists, which implies the initial packet handler is expected to be called off-thread. However, [the patch to handle packets server-side](https://github.com/MinecraftForge/MinecraftForge/blob/727c7780b30c4e5ded10fd6689b9b968266ac224/patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch#L83-L86) explicitly runs the handler on the main thread (and has done so since the 1.13 networking rewrite).

If this is a bug, fixing this may have to wait until 1.19, as I suspect there's quite a lot of mods which rely on the current behaviour.

**Comment by cpw** [comment]
Interesting. It should have been on netty thread handling. That was the original design. Perhaps someone decided that introduced too many problems, because interacting with the world and visuals requires being on the main threads, and made Simple Network simpler, by removing the requirement to run on netty thread.

**Comment by SquidDev** [comment]
Heh, if you're not sure either, then I'm really at a loss how it ended up this way! As far as I can tell, its been like that since the new system was introduced in 1.13 (see https://github.com/MinecraftForge/MinecraftForge/commit/d7e921769578296e04eb8f9b47ee174f5f7959da#diff-0a0f09b343f769725612b0e8cd07855f4ef3dcb49ed5df7590c1caa72193561d), but not sure how much of that commit is you or Lex. Glad to know that's not what was originally intended though.
