### ISSUE TITLE
[1.18] Forge does not use the stack sensitive translation key by default

### ISSUE THREAD

**Issue by KnightMiner** [MinecraftForge/MinecraftForge#8646]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.1.31

**Steps to Reproduce:**

1. Extend `FluidAttributes`
2. Override `getTranslationKey(FluidStack)`
3. Do not override `getDisplayName(FluidStack)`
4. Note your custom translation key is not used by callers of `getDisplayName(FluidStack)`

**Description of issue:**

In the default forge fluid attributes, `getTranslationKey()` and `getTranslationKey(FluidStack)` both exist, allowing a stack sensitive fluid name. However, `getDisplayName(FluidStack)` calls the stack insensitive `getTranslationKey()` instead of the stack sensitive one, meaning any override of `getTranslationKey(FluidStack)` must also override `getDisplayName(FluidStack)` to call the stack sensitive method. This is also inconsistent with the vanilla `ItemStack` behavior.

Issue is caused by [this line](/MinecraftForge/MinecraftForge/blob/1.18.x/src/main/java/net/minecraftforge/fluids/FluidAttributes.java#L216).

**Comment by sciwhiz12** [comment]
The 1.19 PR which fixes this issue, #8707, has been merged previously. This issue is now awaiting #8707, the 1.18 PR, before it will be closed.

**Comment by Shadows-of-Fire** [comment]
All fixes have been merged
