### ISSUE TITLE
[RFC][1.18.x] Rarity does not support colors outside of ChatFormatting

### ISSUE THREAD

**Issue by Nyfaria** [MinecraftForge/MinecraftForge#8647]
It would be a really nice Quality of Life feature to change it so Rarity can use Hex or Int colors instead of just being limited to ChatFormatting

**Comment by diesieben07** [comment]
Why not allow the whole `Style`?
```java
public Style applyStyle(Style style) {
    return style.applyFormat(this.color);
}
```

Then in the patches we can do `component.withStyle(rarity::applyStyle)`
