### ISSUE TITLE
People in China (Mainland) can't use CAPTCHA.

### ISSUE THREAD

**Issue by heipiao233** [MinecraftForge/MinecraftForge#8651]
![image](https://user-images.githubusercontent.com/81846300/171998979-8d66ad18-c355-42df-8268-cfa549f8790d.png)

Because it's a Google service. I can only tell you here.

**Comment by heipiao233** [comment]
And we can't see ADs in the download page, then we can't download.

**Comment by gigaherz** [comment]
Hi, this repository is for the forge software. ~~I'll move this issue to the right repository.~~ (EDIT: I can't manage /Web so I can't do that, you'll have to wait for someone else from the team)
For future reference, the website development is at https://github.com/MinecraftForge/Web

**Comment by heipiao233** [comment]
Sorry, I didn't found that repo
