### ISSUE TITLE
Missing registries in forge tags command suggestions

### ISSUE THREAD

**Issue by Mysterious-Dev** [MinecraftForge/MinecraftForge#8653]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.1.31

**Steps to Reproduce:**
 1. type the command /forge tags
 2. Scroll in the suggestions list

**Description of issue:**
This issue appen when we use the `forge tags` command. Somes registry are missing like `minecraft:worldgen/biome` in the suggestions list, but if we use the command with `minecraft:worldgen/biome` en paramètre, it's working.

All missing seems to be builtin registries.

![image](https://user-images.githubusercontent.com/40738104/172016932-334404e2-3b93-400e-8430-593286cdc24e.png)

![image](https://user-images.githubusercontent.com/40738104/172016953-78ce3a38-2701-427f-a756-e62cfb73a832.png)

**Comment by sciwhiz12** [comment]
This is a known issue and should be fixed by #8638.
