### ISSUE TITLE
PotionExpiryEvent

### ISSUE THREAD

**Issue by Natesky9** [MinecraftForge/MinecraftForge#8658]
Minecraft version 1.18.2
Forge version 40.0.52

Mod GitHub https://github.com/Natesky9/Patina-1.18.2/blob/master/src/main/java/com/natesky9/patina/EventsForge.java

What I'm trying to achieve is potion decay - when a potion expires it gets replaced with the same effect, at a lower potency, at the initial potion duration. However, PotionExpiryEvent is neither cancelable or Resultable despite being wrapped.

Trying to apply another effect instance with the same effect in the expiry event just removes it right after, since the expiry event is allowed to continue as normal

If cancelable,/deniable you could add your own effect logic to refresh effects without firing PotionAdded

**Comment by Tslat** [comment]
To better clarify this - it seems as though the forge event was incorrectly implemented, one way or another

It was implemented seemingly with the intention to be cancelable, given that it checks for the ForgeHooks result before continuing:
https://github.com/MinecraftForge/MinecraftForge/blob/abc3353375d7bb084ce88a1865a1e69548c1307a/patches/minecraft/net/minecraft/world/entity/LivingEntity.java.patch#L46

However the ForgeHook/event class for it specifies that it's not cancelable, and indeed is not.
The hook should either be patched to not bother checking for the boolean return, or actually be cancelable.

The latter is ideal, as it allows for users to re-apply the same effect on expiry, which could be useful in a number of circumstances

**Comment by Natesky9** [comment]
![1e6fa25efb93a0c169ca735934d7a775](https://user-images.githubusercontent.com/1789946/172198658-bfbc93db-90a8-476e-98ea-d144696cd1bf.png)
Why can't the event just be placed after onEffectRemoved?
Edit: because while adding the same effect would be fine, adding a different effect would break the iterator

**Comment by Natesky9** [comment]
An elegant solution was found by just adding the lower potency effect with a higher duration. The vanilla hidden effects behaves exactly as needed, using only two lines of code
https://gyazo.com/0107c6b6370ba4224e34d702736f37b2

Seeing this was the only usecase where the event *needed* to be cancelable, I don't see a need to cancel it
