### ISSUE TITLE
Duplicat config entries for forge light pipeline

### ISSUE THREAD

**Issue by aAndrew3030** [MinecraftForge/MinecraftForge#8662]
In a recent update to enable by default forgeLightPiplineEnabled = true, the old method of experimentalForgePipeLineEnabled = false was left in the config file. Not sure if that was intentional or a oversight, but this seems to conflict with some mods and causes a crash?

[crash-2022-06-05_21.12.59-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/8841251/crash-2022-06-05_21.12.59-client.txt)

[crash-2022-06-05_21.26.02-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/8841253/crash-2022-06-05_21.26.02-client.txt)

**Comment by KnightMiner** [comment]
I highly doubt that crash is caused by multiple config options. The config options existence has zero impact on a rendering crash. More likely that crash is caused by not supporting the now (not experimental) forge lighting pipeline. 

As for their being two options, see [here](https://github.com/MinecraftForge/MinecraftForge/pull/8629#issuecomment-1133702714)

**Comment by aAndrew3030** [comment]
Okay, thanks, I will report the issue to Botania

**Comment by Cicopath** [comment]
Oddly enough, I'm having a very similar crash. The only difference is that I do not have Sodium. This did not happen on Forge 40.1.31 or previous versions. From my searches and asking questions, it's definitely related to either Botania and/or MythicBotany doing something wonky, or something that changed with newer Forge versions which the developers did not know would be *that* crash-worthy.

[crash-2022-06-05_16.47.18-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/8841351/crash-2022-06-05_16.47.18-client.txt)

**Comment by eerussianguy** [comment]
This is the same crash i get with Botania and a mod of mine: https://github.com/VazkiiMods/Botania/issues/4030

Would love some clarity from someone on what people are doing that is breaking the forge lighting pipeline

Edit: to be clear the duped config options aren't the issue here

**Comment by TheCurle** [comment]
It turns out that Botania (and a few other mods) use hardcoded methods that only work with the vanilla render pipeline, so they will never work with the Forge pipeline. 

The accidental breaking change was deemed not worth it for now, so we reverted that change.
This should no longer be an issue.
