### ISSUE TITLE
very persistent issue with connecting to a server running forge 

### ISSUE THREAD

**Issue by kuba26038** [MinecraftForge/MinecraftForge#8672]
**Minecraft Version:** 1.18.2

**Forge Version: 40.1.47

**Logs: 
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/8855282/latest.log)

**Steps to Reproduce:**
i am unable to give such info

**Description of issue:**

this is a big one. it's been making my server impossible to attend since  i was one of the people affected. basically, ever since i switched to 1.18.2 from 1.16.5 i had this issue with connecting. it didn't start straight away actually, i think it started to refuse my connection after a few in-game deaths. after that whenever i tried joining, no chunks would load and i would start falling into the void. my ping display (modified by the mod BetterPingDisplay) said i had 0ms while all of that was happening. i thought that my internet was temporarily down, so i ignored it. here i am 4 months later, with 3 more people with amazing internet and the same issue. we tried everything, and the thing that fixed the problem was installing a vanilla server.jar and running the server through it. the person who was the last one to report having the issue during that period had max 30ms, where i had max 1000 (despite all, i still have bad internet). we decided to switch to the newest version of forge, since the one we deleted was 40.1.16. unfortunately, 40.1.47 has the same problem. at this point i have no clue what to do, except making a bug report here. oh god please help.

**Comment by TheCurle** [comment]
Hi. 

This is a support issue, not a bug in Forge or a feature to be implemented.

Please go to [the Forums](https://forums.minecraftforge.net) for support, as we do not provide help on this issue tracker.
