### ISSUE TITLE
[1.19] Mods' datapack registry (worldgen) jsons are not loaded when creating new singleplayer worlds

### ISSUE THREAD

**Issue by Commoble** [MinecraftForge/MinecraftForge#8676]
**Minecraft Version:** {Minecraft version} 1.19

**Forge Version:** 41.0.1

**Steps to Reproduce:**
 1. Start singleplayer with any mods that add datapack registry jsons (biomes, placedfeatures, etc) via the mod's builtin datapack.
 2. Create a fresh world (not an existing one).
 3. The mod's datapack registry jsons have not been loaded and do not exist on the server.

**Description of issue:**
Mods' datapack registries (worldgen jsons) are not automatically loaded when creating a new singleplayer world. Reordering datapacks via the datapack order screen in the create world menu, spinning up an existing world, and starting a new dedicated server world all cause datapack registries to load correctly.

This seems to arise from the fact that, in vanilla, global/builtin datapacks are not a thing, therefore there is no need to attempt to load datapacks for new singleplayer worlds in vanilla unless the user adds one via the datapack screen (causing datapacks to be (re)loaded and validated). Evidence of this is present in CreateWorldScreen#openFresh (invoked when creating new worlds), which loads builtin registries, but doesn't load datapacks into them.

**Comment by gohkenytp** [comment]
That's why I noticed natural mob spawning needs to be fixed.

**Comment by gohkenytp** [comment]
We were wondering if that issue is fixed yet
