### ISSUE TITLE
[1.19] Wrong active mod container during RegisterEvent

### ISSUE THREAD

**Issue by SuperMartijn642** [MinecraftForge/MinecraftForge#8680]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.1

**Steps to Reproduce:**
 1. Create a method accepting `RegistryEvent` as an argument.
 2. Add `System.out.println("active namespace: " + ModLoadingContext.get().getActiveNamespace())` to the method.
 3. Register the method as an event handler for the `RegistryEvent` using `FMLJavaModLoadingContext.get().getModEventBus().addListener(<method reference>)`.
 4. Run minecraft client and observe 'active namespace: minecraft' in the console.
 ```java
@Mod("modid")
public class MainModClass {
    public MainModClass(){
        FMLJavaModLoadingContext.get().getModEventBus().addListener(MainModClass::onRegisterEvent);
    }
    
    public static void onRegisterEvent(RegisterEvent e){
        System.out.println("active namespace: " + ModLoadingContext.get().getActiveNamespace());
    }
}
```

**Description of issue:**
When the `RegisterEvent` is fired, the default Minecraft mod container appears to be set as the active mod container. This is especially confusing since both `RegistryHelper#register(String, T)` and `IForgeRegistry#register(String, V)` methods, available through the `RegisterEvent` object, claim that "The supplied string key will be prefixed with the currently active mod's mod id."

**Comment by LexManos** [comment]
Small bug from some code cleanup that happened.
