### ISSUE TITLE
Forge 41.0.4 for 1.19 issue with Forge.REACH_DISTANCE.get() attribute modifier

### ISSUE THREAD

**Issue by mc-goodch** [MinecraftForge/MinecraftForge#8689]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.4

**Description of issue:**

The Forge.REACH_DISTANCE.get() attribute modifier does not appear to be working correctly. The block inside the normal tool reach distance break as expected. Block outside of the normal tool reach distance break and reappear immediately. The tool does show the +X Reach Distance tool tip, and the same code works fine in Forge 40.1.0. The logs do not show any warnings or errors. It seems that the server side is not applying the reach modifier as expected.

**Comment by Shadows-of-Fire** [comment]
Some of the patches probably got mangled... I'll take a look

**Comment by mc-goodch** [comment]
I see that there is a fix waiting for a review. Can someone please take a look at it? I'm waiting on this patch in order to release my mod update. Thank you.
