### ISSUE TITLE
[1.19] Entity capabilities invalidated at the wrong time

### ISSUE THREAD

**Issue by kirderf1** [MinecraftForge/MinecraftForge#8690]
**Minecraft Version:** 1.19

**Forge Version:** 1.19-41.0.4

**Steps to Reproduce:**
 1. Attach a capability to the player
 2. Jump
 3. Capabilities on the player has now been invalidated

**Description of issue:**

Entity capabilities are invalidated during `processFlappingMovement()` (mojang mappings), instead of on entity removal.
I assume that a patch from `remove(Entity.RemovalReason)` in mc 1.18.2 mistakenly ended up in `processFlappingMovement()` when ported to 1.19.

**Comment by gigabit101** [comment]
Well, I guess this explains my issues xD
