### ISSUE TITLE
[1.19] Incorrect entity parameter used for PlayLevelSoundEvent.AtEntity patch

### ISSUE THREAD

**Issue by diesieben07** [MinecraftForge/MinecraftForge#8708]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.5

**Logs:** https://forums.minecraftforge.net/topic/112255-forge-119-crashes-with-tridents/#comment-500011

**Steps to Reproduce:**
 1. Throw a trident
 2. Observe the game crashing

**Description of issue:**
The `AtEntity` event call in `ClientLevel#playSeededSound` uses the wrong entity parameter. It uses the nullable player instead of the entity.

**Comment by sciwhiz12** [comment]
Known issue, to be fixed by #8688.
