### ISSUE TITLE
[1.19] java.lang.IllegalStateException: Lock is no longer valid Error

### ISSUE THREAD

**Issue by KedisPL** [MinecraftForge/MinecraftForge#8713]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.16

**Logs:** https://gist.github.com/KedisPL/25c7a91b7e7be7b2430f2a4cd5e834fa

**Steps to Reproduce:**
1. Create a new world.
2. Once the world has been created, leave it.
3. Enter the world again.
4. When you try to enter, a message about experimental settings appears. Click proceed.
5. The game crashes.

**Description of issue:**
Mod with built-in worldgen datapack crashes when you re-enter the world after creating it and saving it.
After restarting the game and entering the world, the game no longer crashes.

**Comment by PlatinPython** [comment]
I have managed to reproduce this issue on the specified version with a very basic datapack that just adds a simple dimension to make the warning about experimental settings appear.

debug.log: https://gist.github.com/PlatinPython/b593a9eb1e155efac9615e9360f9050d
test datapack: https://github.com/MinecraftForge/MinecraftForge/files/8879053/test.zip
