### ISSUE TITLE
[1.18] Chat components aren't modified for anyone but the sender

### ISSUE THREAD

**Issue by phit** [MinecraftForge/MinecraftForge#8729]
**Minecraft Version:** {Minecraft version} 
1.18.2

**Forge Version:** {Forge version. *Version number, not latest/rb*}
I tried 40.1.0 a bunch of inbetween and latest (40.1.51) at the time, but considering this is also happening on Fabric I don't think it's relevant

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
Create a test mod with just this and throw it on a server

```java
    @SubscribeEvent
    public void onChat(ServerChatEvent event)
    {
        TextComponent main = new TextComponent("");
        TextComponent testSuffix = new TextComponent("test");
        testSuffix.withStyle(ChatFormatting.BLUE);
        Component comp = event.getComponent();
        main.append(comp);
        main.append(testSuffix);
        event.setComponent(main);
    }

```

Join with two clients, client A will send the message "hello" and see this, neither client has the test mod installed!

![2022-06-13_19 17 03](https://user-images.githubusercontent.com/2097483/173408936-7f149137-1432-4cfd-b4f8-5f578114319f.png)

client B connected to the server will see this message
![2022-06-13_17 17 52](https://user-images.githubusercontent.com/2097483/173409023-9d3857c9-5c0a-4387-9637-914cad4a4209.png)

just for completeness sake the server will show the messages [formatted](https://cdn.discordapp.com/attachments/915304642668290119/985952245780721735/unknown.png)

**Description of issue:**
Originally I noticed this issue last thursday June 9th, none of the messages of players on my server were formatted, just my own. I'm using FTBRanks to do the chat formatting and had done so for a week or so on this server and the server was not updated in any way during said week.
So now I finally had the time to test this, first I checked if the same issue happens on Fabric ([it does](https://cdn.discordapp.com/attachments/985923050350444624/985945370704109598/unknown.png), using FTBRanks to do this test). So I figured I will need to reproduce it with a minimal example, and it still does happen.

My first guess is that Mojang updated some client libraries maybe for their new chat filtering and signing introduced with 1.19 but according to https://github.com/MultiMC/meta-upstream/commits/master/mojang/versions/1.18.2.json there have been none.

I'm honestly way out of my comfort here and am lost how to troubleshoot this bizzare issue any further, let me know if you need any more information and thanks for reading!

**Comment by DLCIncluded** [comment]
I did happen to find this bit in the Minecraft change log for 1.19, it appears they did change the way servers send chat to the client:
![Screenshot_20220613-210806_Chrome.jpg](https://user-images.githubusercontent.com/23517228/173472283-1a0c7f4d-50c0-46f7-acca-1f93b78aed34.jpg)

I'm not sure if it's related, but if they updated libraries and possibly it messed with some of the libraries that 1.18 uses then maybe..

Hopefully this helps point us in the right direction! If not ignore me

**Comment by sirus628** [comment]
https://prnt.sc/TMRWnGaHcoOW

still an issue

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/f7dd6396e493ead3f68f8f41edd9131e0121a17f
Mojang's profanity filtering, which should only be on realms, was screwing it up. So have the above commit.
1.19.1, we're planning on removing this event entirely, and replacing it with something that uses Mojang's new preview system. However that hasn't been designed yet.
