### ISSUE TITLE
[1.19] [1.18?] LootItemRandomChanceCondition is incorrectly patched to incorrectly apply a looting bonus

### ISSUE THREAD

**Issue by Commoble** [MinecraftForge/MinecraftForge#8731]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.22

**Steps to Reproduce:**
 1. Use the "random_chance" looting condition in a mob loot pool with a low probability
 2. Kill the mob while the player has any level of the Looting enchantment
 3. The loot always drops

This affects the four vanilla fish mobs (salmon, cod, pufferfish, and tropical fish) as they use this loot condition for their bonemeal loot. In vanilla, looting does not guarantee the drop, but it does in forge.

**Description of issue:**
[LootItemRandomChanceCondition](https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/patches/minecraft/net/minecraft/world/level/storage/loot/predicates/LootItemRandomChanceCondition.java.patch)'s patch adds the loot context's looting level to the condition's probability field, using this math:

```java
return context.getRandom().nextFloat() < this.probability + (float) lootingLevel;
```

Where lootingLevel is the integer enchantment level. This results in the condition always returning true for any level of looting above zero.

Since vanilla also provides a LootItemRandomChanceWithLootingCondition (which has correct math in it), LootItemRandomChanceCondition's patch should probably be removed in favor of mods and packs using the intentionally-looting-senstive condition if they need to be sensitive to looting.

Judging by the commit history, this bug probably exists in 1.18.x as well (and has existed since 1.17) though I have only verified the bug's existence on 1.19.

**Comment by sciwhiz12** [comment]
Confirmed by code investigation. It seems like `LootItemRandomChanceCondition` was accidentally patched in 1.17 with a similar patch for `LootItemRandomChanceWithLootingCondition`, even though the former doesn't rely on the looting modifier (as the lack of `WithLooting` in its name implies).
