### ISSUE TITLE
Custom Fluid Swim does not rotate the Player

### ISSUE THREAD

**Issue by MrScautHD** [MinecraftForge/MinecraftForge#8736]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.30

**Steps to Reproduce:**

custom fluid (fuel):
![2022-06-15_10 36 05](https://user-images.githubusercontent.com/65916181/173782523-7ca33173-fb3d-43a9-8b3e-3161a76c2133.png)

water:
![2022-06-15_10 36 12](https://user-images.githubusercontent.com/65916181/173782549-3e50e4df-79e9-4f81-9fc2-5211bc47298c.png)

**Description of issue:**

The Player Rotate not in this direction in that he look

**Comment by sciwhiz12** [comment]
Please provide a minimal example to reproduce this bug, such as the code for the custom fluid and the steps taken to reach the position shown in the screenshots.

**Comment by MrScautHD** [comment]
sure:
Fluid Types:
https://github.com/MrScautHD/Beyond-Earth/tree/1.19/src/main/java/net/mrscauthd/beyond_earth/fluids/types

Fluids:
https://github.com/MrScautHD/Beyond-Earth/tree/1.19/src/main/java/net/mrscauthd/beyond_earth/fluids

Fluids Registry:
https://github.com/MrScautHD/Beyond-Earth/blob/1.19/src/main/java/net/mrscauthd/beyond_earth/registries/FluidsRegistry.java

Fluid Types Registry:
https://github.com/MrScautHD/Beyond-Earth/blob/1.19/src/main/java/net/mrscauthd/beyond_earth/registries/FluidTypesRegistry.java

**Comment by MrScautHD** [comment]
btw i found allot more bugs of the fluid, can i report it here or should i do a new issue

**Comment by marchermans** [comment]
@MrScautHD If they are considerably different make new issues.

**Comment by MrScautHD** [comment]
ok its not so different:
Items not swiming, no fog, no fluid sounds

**Comment by MrScautHD** [comment]
or need i to register anything else or has it really so many bugs?

**Comment by marchermans** [comment]
@ChampionAsh5357 This is your area of expertise I believe

**Comment by ChampionAsh5357** [comment]
Can't reproduce bug, tested with custom fluid and works fine.

Item not swimming is a bug created by reducing patch size.
Fog works as intended.
Fluid sounds when entering fluids is currently not supported, but that can be patched later.

Also, my dms are open for emergencies, not for asking questions which I will respond to on a discord server @MrScautHD.

**Comment by MrScautHD** [comment]
are you sure? you try to look down in swim mode, maybe you not seen it.

sry for the dm, i just found your dc tag on github

**Comment by ChampionAsh5357** [comment]
> are you sure? you try to look down in swim mode, maybe you not seen it.

Ok, rotation during diving and surfacing is different that rotation all together. All in all, still a simple fix.

**Comment by MrScautHD** [comment]
just to have a list!

Bugs and not Supported:
+ Item Movement not working
+ Player up and down Animation not working
+ No Sounds
+ No Particles
