### ISSUE TITLE
Fluid API Improvements

### ISSUE THREAD

**Issue by MrScautHD** [MinecraftForge/MinecraftForge#8739]
Hi, i saw the new Fluid API and i would like to see stuff like this:

+ Property to enable Fish can swim in this Fluid
![2022-06-15_17 01 11](https://user-images.githubusercontent.com/65916181/173861502-5aa245f7-854e-4f6b-9006-5a1146bc2c33.png)

+ Particle Support

+ Sound Support

**Comment by TheCurle** [comment]
These are already in progress.
Please do not spam our issue tracker with pointless comments and issues after being told this by multiple people involved with the fluid rewrite.
