### ISSUE TITLE
[1.19] Custom world types not selectable in `CreateWorldScreen`

### ISSUE THREAD

**Issue by MelanX** [MinecraftForge/MinecraftForge#8751]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.35

**Logs:** [latest.log](https://gist.github.com/MelanX/7e549796c461094c653ebd5a2b6d2be0)

**Steps to Reproduce:**
 1. Register a `ForgeWorldPreset`
 2. Start game
 3. Click `Create New World`
 4. Click `More World Options...`
 5. Search for your world type

**Description of issue:**
The `ForgeWorldPreset`s are never inserted to the list of all presets and are never present to select them. Thus, you can not play with this world type.

**Comment by alcatrazEscapee** [comment]
I was under the impression that 1.19 introduced datapack defined world presets which begs the question "why does `ForgeWorldPreset` exist", rather than "why does it not work". The whole infrastructure looks redundant now.

[Minecraft Wiki](https://minecraft.fandom.com/wiki/Java_Edition_1.19)
> - World presets/types and super flat world [presets](https://minecraft.fandom.com/wiki/Presets) in “Create World” screen can now be controlled by datapacks.
>   - New registry types `worldgen/world_preset`, and `worldgen/flat_level_generator_preset` were added to data-drive presents (like "Amplified" or "Single Biome").

**Comment by MelanX** [comment]
Oh, wow, that was unexpected... then I think I need to find a way to create that in code instead of a `ForgeWorldPreset`. Thank you!
