### ISSUE TITLE
MobEffectInstance syntax error with MDK 41.0.38

### ISSUE THREAD

**Issue by Thenemex** [MinecraftForge/MinecraftForge#8768]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.38

**Steps to Reproduce:**
 1. Installing the forge MDK 41.0.38 within the project
 2. Launching the automatic gradle setup thing within IntelliJ IDEA
 3. Trying to launch gradle tasks : build/clean/genIntellijRuns

**Description of issue:**
I'm getting a syntax error within the class net.minecraft.world.effect.**MobEffectInstance**
![Capture d’écran 2022-06-18 183146](https://user-images.githubusercontent.com/74834242/174448842-d8870301-d767-4872-a5aa-dce00fc09a02.png)

This file is located within : 
build/tmp/expandedArchives/forge-1.19-41.0.38_mapped_official_1.19-sources.jar_46df52ae8e82aaacb798d38dc461c081

**Comment by XFactHD** [comment]
Can't reproduce, looks like the setup went wrong and the file got corrupted. Try refreshing the gradle project again.

**Comment by Thenemex** [comment]
Okay, I'll retry in a few hours and repost here 👌

**Comment by Thenemex** [comment]
Okay I've relaunched a total clean setup for the gradle tasks, and the problem was coming somehow from a corrupted downloaded file(s) like you said, now everything is working fine !
Sorry for annoying you with a silly download corrupted file error 😄
