### ISSUE TITLE
Logspam about tags pointing to worldgen json files in mod’s data folder

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#8771]
![75A9E148-FE59-4759-88B9-01789A9ACE28](https://user-images.githubusercontent.com/40846040/174476313-85a71f2e-5c10-4b42-9e18-0df967bfb75d.jpeg)

The simple step to reproduce is to make a structure by json in a mod. Then make a structure tag that points to that structure. Next, run the game in dev and go to the world creation screen. The tag will be parsed and loaded before the mod’s worldgen json files are read, errors out, and logspams. However, continuing to create the world will release everything and the tag will function properly in the world.

So the issue is just logspam but not actually causing any issue. Here’s a structure mod repo that can be cloned and ran in dev to see the logspam in console.
https://github.com/TelepathicGrunt/RepurposedStructures

**Comment by AnonymousHacker1279** [comment]
This is more than logspam. When trying to use tags for custom biomes, they will fail on the world creation screen as mentioned above. However, they do *not* function properly when used in biome modifiers, for example. 

To reproduce:

1. Make a biome tag, under `data/modid/worldgen/biome/` which contains a custom biome.
2. Create a biome modifier which references this tag. For example:
```json
{
  "type": "forge:add_spawns",
  "biomes": "#modid:your_tag",
  "spawners": {
    "type": "modid:your_entity",
    "maxCount": 1,
    "minCount": 1,
    "weight": 100
  }
}
```
3. Load the world, check the biome used in the tag. The entity is not spawning.

To ensure this is not a spawn placement issue with the entity, the same entity can be added by changing the modifier to the `IS_OVERWORLD` tag (providing your biome is also added to `IS_OVERWORLD`), and the entity will spawn.

I talked about this with @Commoble on the Forge discord for a short while. The related conversation can be found [here](https://discord.com/channels/313125603924639766/983834532904042537/988618319345115217).

**Comment by TelepathicGrunt** [comment]
@AnonymousHacker1279 I am not sure what you are talking about. It is working just fine for me
<img src="https://user-images.githubusercontent.com/40846040/175519826-dbe173ee-c564-4d47-9d38-e2b21eb46860.png" data-canonical-src="https://user-images.githubusercontent.com/40846040/175519826-dbe173ee-c564-4d47-9d38-e2b21eb46860.png" width="500"/>(https://github.com/MinecraftForge/MinecraftForge/files/8975565/vanilla_worldgen_datapack_1.19.0.-.Copy.zip)

This datapack creates a new dimension called minecraft:test with a biome called minecraft:test. I tagged the test biome as ocean and badlands and jungle and all. Then I entered the dimension and flew around and found my jungle dungeon which is added by biome modifier to any minecraft:is_jungle tagged biome.

So the biome modifier is working just fine for me when using a tag that has a custom biome in it. Please double check your code/setup as your issue is more likely something with what you're doing if I am unable to reproduce it. See my repurposed structures repo above for how my dungeons are setup with biome modifier.

bonus pics of the other dungeons and a well spawning based on the minecraft:test biome being in the minecraft:is_badlands, minecraft:is_nether, minecraft:is_ocean, etc tags
<img src="https://user-images.githubusercontent.com/40846040/175520634-14ea6ba0-2fa6-4a0b-b695-a51aa907ab84.png" data-canonical-src="https://user-images.githubusercontent.com/40846040/175520634-14ea6ba0-2fa6-4a0b-b695-a51aa907ab84.png" width="200"/>
<img src="https://user-images.githubusercontent.com/40846040/175520691-eb29903a-60eb-446c-94db-df45636ae64c.png" data-canonical-src="https://user-images.githubusercontent.com/40846040/175520691-eb29903a-60eb-446c-94db-df45636ae64c.png" width="200"/>
<img src="https://user-images.githubusercontent.com/40846040/175521131-01760256-6b97-4c69-922c-e54ac4aa4bb4.png" data-canonical-src="https://user-images.githubusercontent.com/40846040/175521131-01760256-6b97-4c69-922c-e54ac4aa4bb4.png" width="200"/>
<img src="https://user-images.githubusercontent.com/40846040/175520930-ca3614cb-4a6d-4b9a-ab7b-6c696a7b23b8.png" data-canonical-src="https://user-images.githubusercontent.com/40846040/175520930-ca3614cb-4a6d-4b9a-ab7b-6c696a7b23b8.png" width="200" />

@Commoble tagging you since you had a discussion about this.

**Comment by sciwhiz12** [comment]
Could someone please provide a simple datapack which reproduces this issue? So we have an example case linked in this issue that isn't a full mod, for reproducing the issue in a Forgedev environment.

**Comment by TelepathicGrunt** [comment]
@sciwhiz12 this is not a datapack issue. This is a mod issue. The logspam occurs when you first enter the world creation screen. This is before you can even try to add on a datapack to the world. The only way to trigger it is to make a mod with tags in it. You would need to either make a test mod with worldgen tags in it or run a full mod alongside forgedev

**Comment by sciwhiz12** [comment]
Ah, sorry for misunderstanding. Still, could a `data` folder be provided that replicates the issue with a minimal set of files when added to the resources folder of a development environment?

**Comment by Apollounknowndev** [comment]
I stripped my mod down to just the custom biomes and tags (all in datapack format, no java files), and I get the same logspam. I've attached it here.

[logspam-tags-tectonic.zip](https://github.com/MinecraftForge/MinecraftForge/files/9760923/logspam-tags-tectonic.zip)
