### ISSUE TITLE
[1.19] Datagen cannot get config value before config is loaded: treatEmptyTagsAsAir

### ISSUE THREAD

**Issue by Rover656** [MinecraftForge/MinecraftForge#8785]
**Minecraft Version:** 1.19

**Forge Version:** 1.19-41.0.45

**Logs:** https://gist.github.com/Rover656/1513d75ac7504e6931e1dd084e3f357b

**Steps to Reproduce:**
 1. Use Ingredient#getItems in your datagen (we use it for building a list of mod dependencies for json conditions)
 2. Run datageneration
 3. Crash due to the `treatEmptyTagsAsAir` config not being loaded.

**Description of issue:**
When calling Ingredient#getItems duing datagen, it will crash due to the forge configs apparently not being loaded. This happens for the config value `treatEmptyTagsAsAir` inside Ingredient.TagValue#getItems

Could be a regression of #6122

**Comment by KnightMiner** [comment]
Ingredient#getItems has never worked in datagen, tags don't have values so you will not get an accurate list. I'd advise if you need that info, iterate over the internal values field on the ingredient. Some of those values are tag values which may have additional mod IDs for your logic.

In other words, it's not forges fault that a method that should not be called in datagen does not work in datagen

**Comment by Rover656** [comment]
Understood, thanks for the response :)
