### ISSUE TITLE
[1.19] TrunkPlacerType is private and requires an AT to register

### ISSUE THREAD

**Issue by baileyholl** [MinecraftForge/MinecraftForge#8789]
As of 1.19, mods are required to create and pass a TrunkPlacerType for custom trees in order for your tree to call the correct TrunkPlacer Place method during worldgen. This is not the case with saplings, as they do not appear to use the TrunkPlacerType, and an invalid/non-matching Type will still grow your tree. In 1.18, a Type was required, but regardless of the Type you gave it, your place method was consistently called in worldgen and saplings.

Because the TrunkPlacerType constructor is private, there is no way for mods to actually register or create a new type without using an AT themselves. A patch at the forge level on the constructor, or a utility method in the class would be helpful to avoid this.

**Comment by SizableShrimp** [comment]
This will be fixed by a Forge-added AT in 1.19.1, which will be released soon after Mojang's release this coming Tuesday.

**Comment by ChampionAsh5357** [comment]
Fixed as of 6845c094ab436298eac25e68d6657ab79de50a09
