### ISSUE TITLE
[Feature Request] Pulling in LWJGL Snapshot's instead of using Mojang's LWJGL version. 

### ISSUE THREAD

**Issue by hYdos** [MinecraftForge/MinecraftForge#8796]
It is apparently impossible for modders to be able to change the LWJGL version used within Minecraft due to the fact that mods are loaded way way too late for this to be possible. This makes it impossible for mods to use later lwjgl features and bug fixes. Is it possible Forge uses the latest LWJGL snapshot version available?

**Comment by TheCurle** [comment]
We are not going to allow changing the LWJGL version,
It would mean also changing natives and other related files, with the potential to royally screw up a system if done incorrectly.

**Comment by hYdos** [comment]
How are modder's meant to use newer LWJGL features otherwise?
Mojang only updates LWJGL when they need to
