### ISSUE TITLE
Can't rejoin modded server after leaving it unless I restart client

### ISSUE THREAD

**Issue by DrPork204** [MinecraftForge/MinecraftForge#8804]
When I try to reconnect it just says "connecting to server" then eventually says "failed to connect, timed out" I can only reconnect if I completely restart minecraft. Provided below are my debug and latest logs.

[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/8998711/debug.log)

[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/8998714/latest.log)

**Comment by glmdev** [comment]
How did you resolve this? Currently experiencing this issue on the latest version of Forge for 1.18.2.
