### ISSUE TITLE
PathResourcePack#getResources() throws exception when other mods have improperly-named resources

### ISSUE THREAD

**Issue by soir20** [MinecraftForge/MinecraftForge#8813]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.63

**Logs:** [example stacktrace](https://gist.github.com/soir20/215052334db7d3aa83243843d0ef0328)

**Steps to Reproduce:**
 1. Include a mod with resources that are improperly named ("read me.txt").
 2. Use `PathResourcePack#getResources(PackType, String, String, Predicate)` or a method that calls it to retrieve resource names from another mod.
 3. Observe that a `ResourceLocationException` is thrown.

**Description of issue:**
I'm the author of a mod that uses `PackResources#getResources(PackType, String, String, Predicate)` to retrieve files with a particular extension.

The issue is that other mods include resources that are not valid `ResourceLocation`s, such as "read me.txt" or "Capitalized.psd." In such cases, Forge's `PathResourcePack#getResources(PackType, String, String, Predicate)` throws a `ResourceLocationException` even if the invalid resources would be filtered out by the provided predicate.

I'm reporting this here because Minecraft's `FilePackResources` and `FolderPackResources` use `ResourceLocation#tryBuild(String, String)` with a null check, filtering out these improperly-named resources and preventing an exception. It would be ideal if Forge's `PathResourcePack` could use `tryBuild()` as well to prevent the exception.

I have submitted issues to the mods with these resources that have been reported to me. However, someone will have to submit an issue for every offending mod that pops up, or every mod author that wants to use this method will have to catch the exception. This seems like a minor change on Forge's end that improves compatibility and is more consistent with existing Minecraft implementations.

I'd be fine with submitting a PR for this if the Forge team wants to go forward with it.

**Comment by sciwhiz12** [comment]
It sounds sensible to me that our `PathResourcePack` should follow vanilla's lead to ignore (and log) invalid resource paths using `ResourceLocation#tryBuild`. If you wish to make a PR, please feel free to do so.
