### ISSUE TITLE
breaking textures

### ISSUE THREAD

**Issue by THATTHEREOTAKU** [MinecraftForge/MinecraftForge#8816]
Minecraft Version: better minecraft [forage] 1.16.5
Forge Version 36.2.29
Logs: 
[crash-2022-07-02_23.20.57-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/9034107/crash-2022-07-02_23.20.57-client.txt)

**Comment by sciwhiz12** [comment]
Please note that 1.16.5 is currently in a grace period of support, which will expire in less than a week from now. Update to a newer version of Minecraft to receive official support from the Discord or Forums.
