### ISSUE TITLE
[1.19] [Jar-in-Jar] [Bug] Crash when loading multiple Jars with same version

### ISSUE THREAD

**Issue by ApexModder** [MinecraftForge/MinecraftForge#8843]
**Minecraft Version:** 1.19
**Forge Version:** 41.0.80
**Logs:** [**Crash log**](https://paste.md-5.net/ufejobelop.sql) - (_From Vanilla Launcher log window, latest & debug log files did not contain this info_)

**Steps to Reproduce:**
 1. Compile mods which make use of Jar-in-Jar
 2. Include some library mod across them all (same libary version)
 3. Launch the game with these mods in the `mods` folder

**Description of issue:**
The game crashes when attempting to load mods which contain the same JarJar versions.

My mods folder (and contained jars look like so)
- apexcore-1.19-5.0.0.jar
    - commonality-1.19-2.0.0.jar
    - Registrate-MC1.19-1.1.3.jar

- itemresistance-1.19-9.0.0.jar
    - commonality-1.19-2.0.0.jar

If I bump the version of `commonality` (_2.0.0_ -> _2.0.1_) in either `apexcore` or `itemresistance` this error no longer happens and the game loads fine
It only crashes when it detects multiple jars with the same version (`commonality-1.19-2.0.0` existing twice across the JiJ's)

This is only going to be more of an issue down the line with my other mods that depend on `apexcore`

This would mean when playing with any of my mods there is a chance that the game is unlaunchable due to this bug
They would all come with `apexcore` self contained inside of them, which means chance of loading `apexcore` with same version (**crash**)
And `apexcore` would come with `registrate` & `commonality` self contained inside of that, which again chance of loading these with same version (**crash**)

You can find the source for the the above mods (and my _JiJ_ testing) here:
[**ApexCore**](https://github.com/ApexStudios-Dev/ApexCore/blob/1.19-JiJ/build.gradle#L139-L140)
[**ItemResistance**](https://github.com/ApexStudios-Dev/ItemResistance/blob/1.19-JiJ/build.gradle#L130-L131)

**Comment by marchermans** [comment]
Thanks for the repo I must have missed broken something in the latest update cause this worked during initial testing.

Perfect repro case so it should be easy to trace.
