### ISSUE TITLE
ZombieTurtleEggAttackGoal ai broken in 1.19

### ISSUE THREAD

**Issue by warjort** [MinecraftForge/MinecraftForge#8853]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.85

**Logs:**  N/A

**Steps to Reproduce:**
 1. Go to the nether and teleport away from 0,0 so that 0,0 is not loaded (break your portal so it doesn't force load chunks).
 2. Place down a turtle egg and spawn a zombified piglin
 3. It does NOT attack the turtle egg.
 4. Port back to 0,0 and repeat
 5. It DOES attack the turtle egg.

**Description of issue:**

The issue is with this code used by the ZombieAttackTurtleEggGoal - actually RemoveBlockGoal.canUse()

https://github.com/MinecraftForge/MinecraftForge/blob/05297fd72fa99e9ff020fee3ee365ad51bcaf8f0/src/main/java/net/minecraftforge/common/ForgeHooks.java#L1106

On initial pass, that code gets called before the block to break has been determined. 
This means it will check if 0,0,0 (BlockPos.ZERO in MoveToBlockGoal) is loaded and returns false if not. 
This stops the AI from working away from 0,0

Actually reported by Hsandin7 in the forums:
https://forums.minecraftforge.net/topic/113379-pigman-dont-go-after-turtle-eggs/

**Comment by drakray** [comment]
I think this problem also exist in 1.18.2, I use forge-1.18.2-40.1.73 and my nether gold farm is not working at X=300
When I put a chunkLoader at (nether)0,0 everything work normally

**Comment by warjort** [comment]
Create a new issue for 1.18.2
