### ISSUE TITLE
Issue in Tinkers Construct with Pick Block item swapping

### ISSUE THREAD

**Issue by ciserman** [MinecraftForge/MinecraftForge#8869]
Minecraft Version
1.18.2

Forge Version
40.1.60

Mantle Version
1.9.27

Tinkers' Construct Version
3.5.1.31

Describe your issue
When right clicking on a block Minecraft will swap your currently selected item to that block, if it is in your inventory. If it is not on your hotbar, and your hotbar is full, it will swap that item from your inventory with your current hotbar slot, unless you are currently holding a vanilla enchanted tool. If you have an enchanted tool it will swap with the next non-tool slot on your hotbar.
There is currently no consideration for this if you have a Tinker's tool as your current item. If you have your hotbar full, and have a Tinkers tool in hand, and use Pick Block (middle click by default), the block will replace your Tinkers tool: throwing off what may be your typical tool sorting order.

Steps to Reproduce:

1. Have a Tinkers tool in slot 1
2. Fill your other hotbar slots with other blocks
3. Have your tool in slot 1 currently active
4. Use the Pick Block command (middle-click by default) while looking at a block that is not on your hotbar, but is in your inventory

Expected Result:
The type of item you are looking at when using Pick Block will be swapped from your inventory with your item in the first non-tool slot (slot 2). This is how vanilla works with enchanted tools.
Actual Result:
The type of item you are looking at when using Pick Block swaps from your inventory with your tool, putting it out of your hotbar.

This is a copy of a ticket from the Tinkers Construct GitHub, where the it was determined that it was a Forge issue.
https://github.com/SlimeKnights/TinkersConstruct/issues/4939

**Comment by LexManos** [comment]
Just a clarification, the vanilla code is completely unchanged when it comes to this.
It's not checking for a 'tool' it's checking ItemStack.isEnchanted()
Which standard TiC are returning false from.
So... Enchant your TiC tool if you don't want it replaced?
We may  be able to expand a hook here for 'important' items,  tho we would need to make sure that it behaves exactly like vanilla.
