### ISSUE TITLE
Can't join dev servers

### ISSUE THREAD

**Issue by henkelmax** [MinecraftForge/MinecraftForge#8883]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.94-41.0.99

**Logs:** 
- [Client](https://gist.github.com/henkelmax/1cb4f8e7e4dbb65f50e57d5f098f12d2)
- No errors or anything unusual on the server

**Steps to Reproduce:**
 1. Download the MDK example project (Optionally remove all events and block/item registrations from the ExampleMod.java)
 2. Build it
 3. Install the mod on a production Minecraft client and run it
 4. Run the `runServer` task in the dev environment
 5. Try to join the server
 6. You can't join the server

![image](https://user-images.githubusercontent.com/13237524/179389960-661d662e-f75e-41a1-a20b-25e9f4ae1f01.png)

**Description of issue:**

For me this only happens with servers running in the dev environment. 
But I also had bug reports for people on normal servers with similar messages and the same log exception. See https://github.com/henkelmax/simple-voice-chat/issues/429

**Comment by TheCurle** [comment]
This is because the dev server has the GameTest system's argument types registered, but the production client does not.

It causes a mismatch in packet length which causes future packets to become misaligned and eventually leads to this crash.

I believe some people were working on a fix for this, but i'm not sure how that went.

**Comment by sciwhiz12** [comment]
The fix is contained in #8745, which has been merged into the 1.19.1 private development branch due to it being a network-breaking change. Once Forge 1.19.1 releases, this issue is considered fixed and will be closed.

**Comment by SizableShrimp** [comment]
The fix for now is disabling gametest in dev which can be done by specifying system property `forge.enableGameTest` to false (from memory).

**Comment by sciwhiz12** [comment]
Closing as Forge 1.19.1 (and now 1.19.2) has been released.
