### ISSUE TITLE
Crossbow does not use ArrowLooseEvent

### ISSUE THREAD

**Issue by Natesky9** [MinecraftForge/MinecraftForge#8886]
Mc version 1.18.2
Forge version 40.0.52

ArrowLooseEvent does not fire for Crossbows

solution: 
insert
if (net.minecraftforge.event.ForgeEventFactory.onArrowLoose(Stack, Level, Player, Charge, HasAmmo) < 0) return;
into CrossbowItem#performShooting

**Comment by TheCurle** [comment]
If someone wants to tackle this..
