### ISSUE TITLE
Multi-layer model rendering error

### ISSUE THREAD

**Issue by Darmstadtium271** [MinecraftForge/MinecraftForge#8904]
**Minecraft Version:** 1.18

**Forge Version:** 40.1.0

**Steps to Reproduce:**
1. Use forge mdk to add a block and it's item.
2. Give the block a multi-layer model.One layer's render type is "solid", the other's is "translucent".
3. Give the item a default blockitem model.
4. Setup the game.
5. The item's rendering is true.
6. Place the block, but the block just render the solid layer.
7. If you delete the solid layer, the block will be transparent.

Model files and textures: [Files.zip](https://github.com/MinecraftForge/MinecraftForge/files/9180608/Files.zip)

**Comment by sciwhiz12** [comment]
This looks to be correct behavior: the multi-layer model in 1.18 works by only returning the quads (elements) for the model which match the render type currently being rendered. 

In this case, the default render type for blocks is `RenderType#solid()`, so only the model defined under the `solid` key in the model JSON is being rendered. When that `solid` model is removed, no model matches so the block is rendered as nothing.

Likewise, if you set the render type for the example block as `RenderType#translucent()` using `ItemBlockRenderTypes#setRenderLayer(Block, RenderType)`, only the coal overlay texture shows as that is the model defined under the `translucent` key in the model JSON.

The solution is to register the render type for the block as a predicate which checks both the `solid` and `translucent` render types:
```java
ItemBlockRenderTypes.setRenderLayer(COAL_ANDESITE_ORE_BLOCK.get(), Predicate.<RenderType>isEqual(RenderType.solid()).or(Predicate.isEqual(RenderType.translucent())));
```

In 1.19, I believe the multi-layer model was removed in favor of the composite model, as each model can now specify what render type group it should render in, such as `minecraft:solid`/`solid` and `miencraft:translucent`/`translucent`
