### ISSUE TITLE
[1.19] Dedicated server fails to load with mods using JiJ

### ISSUE THREAD

**Issue by TheIllusiveC4** [MinecraftForge/MinecraftForge#8910]
**Minecraft Version:** 1.19

**Forge Version:** 41.0.110

**Logs:** [Gist](https://gist.github.com/TheIllusiveC4/d3310980d7c86dc51761aca89fb6582b)

**Steps to Reproduce:**
 1. Update to Forge 41.0.110 or above
 2. Add any mod that uses JiJ
    * Tested using any one of:
    * Comforts 6.0.0-beta.5+1.19 [CurseForge](https://www.curseforge.com/minecraft/mc-mods/comforts/files/3900251)/[Source](https://github.com/illusivesoulworks/comforts)
    * Fantasy's Furniture 1.19-4.3.0 [CurseForge](https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture/files/3901640)/[Source](https://github.com/ApexStudios-Dev/FantasyFurniture)
 4. Start a dedicated server instance

**Description of issue:**

Originally reported on the Comforts issue tracker: https://github.com/illusivesoulworks/comforts/issues/96

It seems that loading any mod that uses JiJ will fail to load when used on a dedicated server. This problem only occurs on 41.0.110 or above, downgrading to 41.0.109 or below will allow the server to load correctly. As far as I can tell, single player/client instances are not affected and load correctly regardless of the Forge version.

**Comment by marchermans** [comment]
So I was able to reproduce this. Buy only on the dedicated server in production. Somehow the jarjar library is loaded to late there which causes its Filesystems to not be available in time

**Comment by TigerWalts** [comment]
A temporary workaround for servers is to extract the jar files from within the `META-INF\jarjar` folder in the mod file and then place them into the server's `mods` folder. Then remove the `META-INF\jarjar` folder from the mod file.

Using 7-zip:

1. Open the mod file in 7-Zip
2. Navigate to the `META-INF\jarjar` folder
3. Extract the Jar files in this folder to the `mods` folder
4. Navigate up one level to `META-INF`
5. Remove the `jarjar` folder

I don't know if JiJ skips jars that are already loaded, if it does then you can skip steps 4 and 5.

This works for the Comforts mod.

**Comment by ApexModder** [comment]
I also ran into this issue on 1.19 & 1.19.1, the bandaid fix from @TigerWalts seemed to work for our mods too.

Our library mod that comes pre-packaged in our main line mods was not being loaded which was causing this for us.

[log file](https://paste.md-5.net/omeramuyol.sql)

**Comment by marchermans** [comment]
I am currently in the process of fixing this.
The main issue here is that SJH only loads FileSystems which are part of the none modularized classpath, however just smacking JarJar on there was not possible so we had to split this apart into modules.

I hope to have this fixed by the end of the day.
