### ISSUE TITLE
Thread Safety change in ItemBlockRenderType.setRenderLayer for fluids

### ISSUE THREAD

**Issue by warjort** [MinecraftForge/MinecraftForge#8911]
**Minecraft Version:** 1.19

**Forge Version:** 41.1.0

**Logs:** https://forums.minecraftforge.net/topic/114540-i-dont-understand-why-mekanism-generators-gives-an-error-before-that-it-worked-fine/#comment-508017

**Steps to Reproduce:**
 1. Install Mekanism and Mekanism Generators that do setRenderLayer() for fluids concurrently
 https://github.com/mekanism/Mekanism/blob/9baddb9d7f033f9e001c6a22e5e423ec53ee2b23/src/main/java/mekanism/client/ClientRegistration.java#L256
 
**Description of issue:**
Somewhere along the way in the client refactoring using setRenderLayer() for fluids seems to have become non-threadsafe?

1.18
https://github.com/MinecraftForge/MinecraftForge/blob/1dacb882e0b4293a21bed2f135b3ebc01c0fe065/patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch#L104
1.19
https://github.com/MinecraftForge/MinecraftForge/blob/3c1126a7b43dddc88d2ac50ebbac607905ee4872/patches/minecraft/net/minecraft/client/renderer/ItemBlockRenderTypes.java.patch#L115

I don't see this being explicitly mentioned or discussed in the #8685 #8786 patches?

**Comment by warjort** [comment]
Looks like this was fixed in this change? https://github.com/MinecraftForge/MinecraftForge/commit/2d3ee8a228a2e7ba81c6e8e363a491aea79b92ce

**Comment by AterAnimAvis** [comment]
Looks to be,
Closed by https://github.com/MinecraftForge/MinecraftForge/pull/9065
