### ISSUE TITLE
[1.19.1] There are no shadows on text displayed within the action bar

### ISSUE THREAD

**Issue by KabanFriends** [MinecraftForge/MinecraftForge#8916]
**Minecraft Version:** 1.19.1

**Forge Version:** 42.0.0

**Steps to Reproduce:**
 1. Join a world (with op permissions)
 2. Type `/title @s actionbar {"text":"Hello World!"}`
 3. See the text displayed in action bar
![image](https://user-images.githubusercontent.com/45000995/181698652-2db3cee5-e125-45a8-a7e6-5db651f8915f.png)

**Description of issue:** Mojang added shadows on action bar texts in 1.19.1 (A fix for [MC-72687](https://bugs.mojang.com/browse/MC-72687)) Looks like this change was reverted in forge patches.

**Comment by marchermans** [comment]
Closed in #8917
