### ISSUE TITLE
ClientChatReceivedEvent but for System messages (1.19.1)

### ISSUE THREAD

**Issue by DmitryLovin** [MinecraftForge/MinecraftForge#8923]
Previosly ClientChatReceviedEvent was fired even for system messages, but with null sender, and we was able to parse those messages, now we can't.
My example of usage:
On servers with essentials plugin I was using that event to parse chat after /homes command, to get all homes and open a "Home screen" so players can access to all their homes via gui, but on 1.19.1 (on 1.19 also actually) that event is never calls for such messages and there is nothing we can parse.

**Comment by Thomas7520** [comment]
Any news for that ?

**Comment by Thomas7520** [comment]
Hey, i'm sorry to come here again, but it still not working on latest 1.19.3 version with System Message...
