### ISSUE TITLE
when opening on minecraft launcher it doesnt work

### ISSUE THREAD

**Issue by DrinkWootaPlease** [MinecraftForge/MinecraftForge#8926]
it says error code 1 and something with java runtime environment

**Comment by FinnT730** [comment]
It is a general exit code, it means nothing
We need logs

`
To diagnose your issue we need the game log. Please provide the logs/debug.log file in the minecraft directory and put it in one of the following sites (preferably the first one):

Here's a list of some paste sites and their size limits:
    https://gist.github.com/:      [Free] [SignUp] 100MB
    https://paste.gemwire.uk/:  [Free] 10MB
    https://paste.ee/:                   [Free] 1MB, [SignUp] 6MB
    https://pastebin.com/:          [Free] 512KB, [SignUp] [Paid] 10MB
    https://hastebin.com/:          [Free] 400KB
    https://gist.github.com/:      [Free] [SignUp] 100MB
`
