### ISSUE TITLE
[1.18.2] Mixins don't work with JarJar

### ISSUE THREAD

**Issue by EdwinMindcraft** [MinecraftForge/MinecraftForge#8930]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.1.68

**Logs:** No applicable since this issue was fixed for 1.19 with #8900.

**Steps to Reproduce:**
 1. Include a mod with a mixin in another one using JarJar
 2. Launch the game
 3. Observe the mixin isn't injected

**Description of issue:**
Mixins fail to load when included if jars are not on the top level of the JarJar tree. This is more or less a backport request for #8900.

**Comment by marchermans** [comment]
I do not at the moment have time for this. But somebody else can feel free to backport this. Likely also a backport of #8931 is then needed.

**Comment by SizableShrimp** [comment]
Fixed by #9506.
