### ISSUE TITLE
Old vulnerable Log4j being installed with Forge 1.16.5 - 36.2.34 (recommended) and 1.16.5 - 36.2.39 (latest) installers

### ISSUE THREAD

**Issue by Ad-Blokker** [MinecraftForge/MinecraftForge#8950]
**Minecraft Version: 1.16.5**

**Forge Version: 36.2.34 (recommended)**
**Forge Version: 36.2.39 (latest)**

**Forge Installer Logs:** [Link to both log files on Github Gist](https://gist.github.com/Ad-Blokker/5ea6b58b12bb9890bac2be7a5efd40ca)
Raw link: https://gist.github.com/Ad-Blokker/5ea6b58b12bb9890bac2be7a5efd40ca

**Steps to Reproduce:**
 1. Run the forge installer and wait for it to finish
 2. During installing it downloads all log4j 2.15.0 files (this is the vulnerable version), example:
 ``` 
 Considering library org.apache.logging.log4j:log4j-core:2.15.0
  Downloading library from https://libraries.minecraft.net/org/apache/logging/log4j/log4j-core/2.15.0/log4j-core-2.15.0.jar
    Download completed: Checksum validated.
 ```
 3. Check the following directories: 
```
/libraries/org/apache/logging/log4j/log4j-api
/libraries/org/apache/logging/log4j/log4j-core
/libraries/org/apache/logging/log4j/log4j-slf4j18-impl
```
 4. All these log4j library folders contain log4j 2.15

**Description of issue + solution:**

- Forge downloads old libraries of log4j which could still enable the vulnerability to be used. The addition to the forge log4j config in the forge server files is not enough to fully mitigate (for example: `%msg{nolookups}%n`)
- All log4j libraries downloaded by the forge installer should be **at least** version 2.17.X

More context:
![image](https://user-images.githubusercontent.com/14195799/183709246-a49cf2a9-0136-4381-9330-3a21b18e109a.png)

The presence of the other vulnerable log4j JDNI manager entries could be simply removed from the .jar files when opening the file with for example 7-zip. 
If forge does not do the lookup then it should never try to use this class. If a lookup is tried the server will crash as java tries to access a class that is not present. (You can see that the Minecraft server files are trying to use the JNDI lookup)

![image](https://user-images.githubusercontent.com/14195799/183711436-771f4262-d5bb-41dd-94ae-e2b08bf0dfdc.png)

The problem with these Minecraft server files is that these are downloaded from mojang and the included log4j in these server files is not updated triggering an alert from the scanner. 

======

Used tool: https://github.com/fox-it/log4j-finder

**Comment by AterAnimAvis** [comment]
Duplicate of https://github.com/MinecraftForge/MinecraftForge/issues/8305
