### ISSUE TITLE
Sending a custom packet to all players in LAN causes a disconnect

### ISSUE THREAD

**Issue by pupnewfster** [MinecraftForge/MinecraftForge#8969]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.0.8

**Logs:** Nothing of interest appears in the log without #8965 just a disconnect happening (with #8965 it prints the `Received empty payload on channel` message and "gracefully" handles the error not disconnecting the client).

**Steps to Reproduce:**
 1. Create a simple channel and register a (server to client) packet to it
 2. Start a single player world and open it to LAN
 3. Have a second player join
 4. Try to send the packet from the server to all clients using `getChannel().send(PacketDistributor.ALL.noArg(), packet);`
 5. The second player will get disconnected by sending the packet (with #8965 they should receive an error in their log instead of being disconnected)

**Description of issue:**

Custom packets when sent to all players in a LAN world fail to send properly. From various testing I did my best guess is it may be related to how Minecraft/netty handles local connections in relation to how packets are sent and the host receiving and consuming the packet before it is sent to connected players (with an empty buffer), though I am unsure if that is the case because when I try explicitly sending to the host after the loop instead of after it still has issues (at least at times unsure if it maybe just causes it to be a race condition in that case. Below is some code of various testing I did trying to figure out what works and what doesn't and why I believe it seems to be related to sending a ***single vanilla packet*** instance to each player.

```java
public <MSG> void sendToAll(MSG message) {
    //Does not work
    getChannel().send(PacketDistributor.ALL.noArg(), message);
}

public <MSG> void sendToAllAlt(MSG message) {
    Packet<?> packet = getChannel().toVanillaPacket(message, NetworkDirection.PLAY_TO_CLIENT);
    MinecraftServer server = ServerLifecycleHooks.getCurrentServer();
    for (ServerPlayer player : server.getPlayerList().getPlayers()) {
        //Works
        //getChannel().send(PacketDistributor.PLAYER.with(() -> player), message);
        
        //Also works
        //player.connection.getConnection().send(toVanillaPacket(message, NetworkDirection.PLAY_TO_CLIENT));
        
        //Works for the first LAN host does not work for other players
        player.connection.getConnection().send(packet);
    }
}
```

**Comment by sciwhiz12** [comment]
Tested under the following conditions, and I couldn't reproduce a disconnect:
 - Two local clients ran by and connected to the same IDE, running in debug mode;
 - One client has a world opened to LAN, with the other client connected;
 - A packet with a single `int` value;
 - A command which triggers a packet to be sent to all clients using `PacketDistributor.ALL.noArg()` and `SimpleChannel#send(PacketTarget, MSG)`.

The packet is received and handled normally on both clients. I also checked that the second client which is connected to the LAN world has a non-`LocalChannel` connection. Could you please provide an example test mod which reproduces the error, along with instructions?

<details>
<summary>Snippet of mod code, inserted into a 1.19.2 MDK</summary>

```java
    public static final String PROTOCOL_VERSION = "1.0";
    public static final SimpleChannel CHANNEL = NetworkRegistry.ChannelBuilder.named(new ResourceLocation(MODID, "channel"))
            .networkProtocolVersion(() -> PROTOCOL_VERSION)
            .clientAcceptedVersions(PROTOCOL_VERSION::equals)
            .serverAcceptedVersions(PROTOCOL_VERSION::equals)
            .simpleChannel();

    public ExampleMod() {

		// --- snipped ---

        int messageId = 0;
        CHANNEL.messageBuilder(ModPacket.class, messageId++)
                .encoder(ModPacket::write)
                .decoder(ModPacket::new)
                .consumerNetworkThread(ModPacket::handle)
                .noResponse()
                .add();
    }

    @SubscribeEvent
    public void onRegisterCommands(RegisterCommandsEvent event) {
        final AtomicInteger integer = new AtomicInteger(0);
        event.getDispatcher().register(Commands.literal(MODID)
                .executes(ctx -> {
                    int number = integer.getAndIncrement();
                    ctx.getSource().sendSystemMessage(Component.translatable("Sending packet with number %s to clients...", number));
                    CHANNEL.send(PacketDistributor.ALL.noArg(), new ModPacket(number));
                    return Command.SINGLE_SUCCESS;
                })
        );
    }
```
```java
public record ModPacket(int number) {
    public ModPacket(FriendlyByteBuf buffer) {
        this(buffer.readVarInt());
    }

    public void write(FriendlyByteBuf buffer) {
        buffer.writeVarInt(number);
    }

    public boolean handle(Supplier<NetworkEvent.Context> context) {
        assert Minecraft.getInstance().player != null;
        Minecraft.getInstance().player.sendSystemMessage(Component.translatable("Received packet with number %s!", number));
        return true;
    }
}
```

</details>

**Comment by pupnewfster** [comment]
Small test mod with steps in README that seem to reliably reproduce the issue: https://github.com/pupnewfster/LANFailTest

**Comment by LexManos** [comment]
Once someone can reproduce, test this fix. https://github.com/MinecraftForge/MinecraftForge/compare/1.19.x...LexManos:MinecraftForge:ICustomPacket

**Comment by pupnewfster** [comment]
Leaving other people to see if they can reproduce as well, but did a bit of testing that that fix does seem to work.

**Comment by LexManos** [comment]
I was finally able to reproduce this issue myself. And my changes do indeed fix it, at least for me. As my suspicion was correct. The InMemoryConnection was processing the packet first, incrementing the reader index and then the write method was seeing an empty buffer.
