### ISSUE TITLE
[1.19.2] java.lang.NullPointerException: applyTransform() must not be called on a vanilla ArmPose!

### ISSUE THREAD

**Issue by baguchi** [MinecraftForge/MinecraftForge#8985]
**Minecraft Version:** {1.19.2}

**Forge Version:** {43.1.0}

**Logs:** https://gist.github.com/baguchan/da0966f7e8c321d21d356a22e74f73a6

**Steps to Reproduce:**
 1. Get The Goat Horn
 2. Use Goat Horn on Third Persion
 3. Crash

**Description of issue:**
This crash happened when I was modding.
Tried other UseAnims, but only "TOOT_HORN" crashed
After that, I tried with forge without mods, but it still crashed

**Comment by tmvkrpxl0** [comment]
wait I think I wrote it, let me check

Update: Yes, it is indeed, my code. My bad

**Comment by baguchi** [comment]
It's okey 😿
