### ISSUE TITLE
Chunks on server do not sum up to 42997962 but to 0 bytes

### ISSUE THREAD

**Issue by skrxf** [MinecraftForge/MinecraftForge#9001]
**Minecraft Version:** {Minecraft version}

**Forge Version:** {Forge version. *Version number, not latest/rb*}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**

**Comment by ChampionAsh5357** [comment]
Please provide the above information in the template. This error report does not say anything and would not be reproducible to verify the issue.

**Comment by ChampionAsh5357** [comment]
Closing as no additional information was provided.
