### ISSUE TITLE
[1.19.2] Cannot right click while looking at mobs at certain distance

### ISSUE THREAD

**Issue by orjfickel** [MinecraftForge/MinecraftForge#9006]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.3

**Logs:** https://gist.github.com/BlizzardFenix/6622bedc073c8f532fd981dca42ccc79

**Steps to Reproduce:**
 1. Approach a mob (or other entity)
 2. Hold a shield or any other item with use functionality
 3. Stand around 5 blocks away while looking at the entity
 4. Right click
 5. Nothing will happen

**Description of issue:**
Right clicking while looking at pickable entities from a certain distance (around 5 blocks) does not actually use the held item. This does not happen in vanilla Minecraft.
Also PlayerInteractEvent.RightClickItem does not get called in this case.

**Comment by sciwhiz12** [comment]
A bit of additional testing and a concurrence from @Meldexun shows that this issue only happens while in creative mode. Also, using an item while moving into the band of appromixately 5 to 6 blocks away from the entity does not get interrupted; it only affects starting to use an item while within that band.
