### ISSUE TITLE
Forge 1.19 Waterlogged minecarts move faster than they should

### ISSUE THREAD

**Issue by Emfire12345** [MinecraftForge/MinecraftForge#9011]
Tested in latest Forge version for 1.19 and 1.19.2

The bug makes Waterlogged minecarts on soulsand move much faster than they should, just create a line of soulsand, put eges around it, fill it with water and afterwords rails and send a minecart, the minecart moves faster in forge compared to vanilla, as result, breaking a lot of farms that relie on that slow movement.

Here a screenshot how it looks:
![2022-09-04_07 11 33](https://user-images.githubusercontent.com/108950145/188298510-bd7bfeb5-1eed-4c3d-a544-7802fd314011.png)

**Comment by MagnusHJensen** [comment]
I don't think this was actually fixed properly in #9033 

https://user-images.githubusercontent.com/32039051/194698846-93cb6d24-1962-4887-b480-a9f31a6d726c.mp4


https://user-images.githubusercontent.com/32039051/194698847-786d7e77-cc4d-4554-925a-fe73a8a4188a.mp4

**Comment by Emfire12345** [comment]
> I don't think this was actually fixed properly in #9033
> 
>  forge-waterlogged-minecart.mp4 
>  vanilla-waterlogged-minecart.mp4

So it isnt fixed yet, right? Would you perhaps know how long it takes till bugs like these are fixed?
And how do i even applie the fix, i cant find the file path that is shown in the fix.

**Comment by ChampionAsh5357** [comment]
So, essentially, there are more water checks due to `AbstractMinecart#getMaxSpeed`. Essentially, two speed checks need to be updated with the changing value of being in water to fix these issues.
