### ISSUE TITLE
[RFC] ScreenEvent has too much overlap

### ISSUE THREAD

**Issue by AbsolemJackdaw** [MinecraftForge/MinecraftForge#9020]
I am writing some logic that needs to fire when, and only when, a screen is fully closed. 
In other words : the player returns to the HUD. 

The current setup of ScreenEvent allows for detecting the opening of a screen and changing said screen if needed, or to detect what screen is closed. 

As you may notice, there is no way of knowing if the screen is effectively closed (back to hud) or another one is opened behind it. 

As discussed with Ama, a good way to tackle this would be to have three subevents : 

1. Opened
2. Opening
3. Closed

this would allow to expose the changes from one screen to another, and keep the other two events

**Comment by AbsolemJackdaw** [comment]
@sciwhiz12 I was suggested to ping you to label this issue correctly

**Comment by marchermans** [comment]
I am not entirely sure how modifying the firing order would fix your issue.
Especially since anybody can open another screen in the Closed event which would prevent the HUD from showing.

What exactly are you trying to achieve here?

**Comment by AbsolemJackdaw** [comment]
There is currently no way of knowing that a screen has been effectively closed (back to hud vs switch-to-a-new-screen closed).  
The mod I'm developing that asks for this logic is Public Gui Announcement, which shows a visual in-world on the player depending on the gui that is open for said player.
  
Being able to determine what screen has been opened is not a problem. 
The problem occurs when the closing screen is called. 
The switch operates on whether a screen is opened or closed. Changing screens will call the closed switch last, without knowing whether or not a new screen has been effectively set or removed is info that is never given. 

A fine example of this is opening the Player Inventory in creative. 
The screen opened is the Inventory screen, sending and opening request. The game then detects creative mode and sends a request to open up the Creative Inventory Screen instead. Doing so results in the normal inventory screen to close. 
The call order of these events are : open A, open B, Close A; effectively firing the close event as last request. Without a way to determine in the closing event wether or not the old screen replaced was null or an object, I cannot, within the closing event, determine to send a close/erase request to the visual queue in my mod. The close request will be send because the Close event was fired last. 

Checking if the screen is null in the opening event is also not possible given the null check that is made before firing it

**Comment by AbsolemJackdaw** [comment]
the idea for the events would be : 
1. Opened : expose the screen that has been requested to be opened(nonnull) and the old screen is null . ability to change given screen
2. Opening : fire in lieu of Opened when the old screen is not null. expose both to be edited if needed
3. Closed : fire if screen is set to null. exposes boolean to determine if the Opened or  Opening event was fired (new screen is non null)

this was my train of thought.

**Comment by marchermans** [comment]
That is an understandable thing to want to know, but I I would just like to point out that your closing event reorder does not solve the problem. I can easily use an event handler listen for the closing event and then open a different UI, which would result again in the same situation. Would it not?

In the end i think the only way to solve this if for you to list on tick and check for the players if they have something open or not.

**Comment by AbsolemJackdaw** [comment]
Then the author is to blame for not using the correct forge events that are to be used in this situation and they should be pointed to the correct usage of them. Hence making it their issue and not ours. 

I'm currently using a mixin to fix the issue either way. 

Just wanted to point out there used to be a way to detect the closing correctly trough the event (pre 1.19) and now there isn't anymore.

**Comment by marchermans** [comment]
> Then the author is to blame for not using the correct forge events that are to be used in this situation and they should be pointed to the correct usage of them. Hence making it their issue and not ours.
> 
> I'm currently using a mixin to fix the issue either way.
> 
> Just wanted to point out there used to be a way to detect the closing correctly trough the event (pre 1.19) and now there isn't anymore.

I would actually like to point out that the closed event does not restrict the modder from reopening another interface!
Nowhere in the contract is this defined, and additionally if it where it is also completely unenforceable. The method `Minecraft#openScreen` can be invoked anytime, including from the event handler.

And you don't really need a mixin to track this, a simple tick event handler which keeps track of the players open screens suffices here.
