### ISSUE TITLE
build.gradle not working

### ISSUE THREAD

**Issue by koen1711** [MinecraftForge/MinecraftForge#9022]
**Minecraft Version:** 1.12.2

**Forge Version:** 14.23.5.2860

**Logs:** https://gyazo.com/3efaf9893923dda34faaee9d382f122d?token=ab292b66823f08cca609409f60ab0229

**Steps to Reproduce:**
1. Install MDK.
2. Configure build.gradle.
3. Run it with VSC extension by Microsoft.

**Description of issue:**
So I am trying to make a mod but while trying to build the gradle it errors.

**Comment by ChampionAsh5357** [comment]
1.12.2 is no longer supported by Forge. Additionally, this is not an issue related to the Forge Mod Loader or API; it is an issue with your userdev setup. Closing for these reasons.
