### ISSUE TITLE
Rendering Error

### ISSUE THREAD

**Issue by wuggyfoot** [MinecraftForge/MinecraftForge#9025]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.24

**Logs:** https://gist.github.com/wuggyfoot/1c6827c2c0b146fd9fd2d2ccd1bf686b

**Steps to Reproduce:**
 1. Update to Forge 43.1.24
 2. Load into world

**Description of issue:**
Loading into any world in my instance with this version of Forge installed causes a strange light rendering bug. This does not happen with previous versions of Forge.
![javaw_HwStS6nLRf](https://user-images.githubusercontent.com/7423826/189220542-3e106497-b873-48b7-891c-455fa936b091.png)

**Comment by TheCurle** [comment]
What the..

**Comment by XFactHD** [comment]
Try removing Rubidium, Starlight and Radium one by one, it is possible that one of them cannot handle the recent changes since they heavily modify the rendering and other systems.

**Comment by wuggyfoot** [comment]
Seems to have been Rubidium. The recent update on their part also seems to have fixed this. Thanks ;)
