### ISSUE TITLE
Forge bypasses the server blacklist

### ISSUE THREAD

**Issue by untuned** [MinecraftForge/MinecraftForge#9034]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.25

**Logs:** N/A

**Steps to Reproduce:**
 1. Add a blacklisted server IP to your server list
 2. Observe it resolves and allows you to join

**Description of issue:** Simply installing forge seems to bypass the Minecraft server blacklist. (Related to #2845?)

**Comment by untuned** [comment]
This seems to work on any version 1.17+.

**Comment by Matyrobbrt** [comment]
This issue was fixed by https://github.com/MinecraftForge/MinecraftForge/commit/6f8ba9d2951a913686464c79edd1cd85eb3fb7d6.
