### ISSUE TITLE
[1.12.x] BUILD FAILED: Task :forge:checkLicenseCustomMain FAILED

### ISSUE THREAD

**Issue by Zipdox** [MinecraftForge/MinecraftForge#9042]
**Minecraft Version:** 1.12.2

**Forge Version:** 1.12.2-14.23.5.2860

**Logs:** https://gist.github.com/Zipdox/c9c4b3129bf89d1c6de5593a33cbbe5f

**Steps to Reproduce:**
 1. Clone 1.12.x repo
 2. gradlew setup
 3. gradlew build

**Description of issue:**
Build fails.

**Comment by ChampionAsh5357** [comment]
1.12.2 is no longer supported by Forge. Please update to latest (1.19.x) or LTS (1.18.x) to receive support. Additionally, this is for issues with Forge itself, not for receiving help on setting up Forge for userdev.

**Comment by FinnT730** [comment]
We can't keep every version in the world supported.
