### ISSUE TITLE
`CompositeHolderSet` crashing while serializing to NBT

### ISSUE THREAD

**Issue by Sirttas** [MinecraftForge/MinecraftForge#9043]
**Minecraft Version:** 1.19.2
**Forge Version:** 1.19.2-43.1.2

if you try to make for example an `AndHolderSet` that contains a tag and a `NotHolderSet` you'll end up with the following json:
```json
{
    "type": "forge:and",
    "values": [
      "#my_mod:tag1",
      {
        "type": "forge:not",
        "value": "#my_mod:tag2"
      }
    ]
  }
```

If you serialize it to NBT you will get the following `UnsupportedOperationException`: `Trying to add tag of type 10 to list of 8`. This is because the first element that was placed in the `ListTag` is `#my_mod:tag1` so it's a string (NBT type 8) but the second one is a `CompondTag` (NBT type 10).

There is a simple solution to this issue for modders: simply wrap tags in an `OrHolderSet`:
```json
{
    "type": "forge:and",
    "values": [
      {
        "type": "forge:or",
        "values": [
          "my_mod:tag1"
        ]
      },
      {
        "type": "forge:not",
        "value": "#my_mod:tag2"
      }
    ]
  }
```

**Comment by Random832** [comment]
Maybe instead of "#mymod:tag2" the format should be { "tag": "mymod:tag2" } [likewise { "entry": ... } for single entries], after how ingredients do it. That way all elements of the list are object/compound.

**Comment by Sirttas** [comment]
I don't know if it was clear but the json is not manual it is a result of datagen
