### ISSUE TITLE
[1.19.2] ForgeConfigSpec$ValueSpec#getDefault caches returned value, which is wrong

### ISSUE THREAD

**Issue by DBotThePony** [MinecraftForge/MinecraftForge#9045]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.1

**Steps to Reproduce:**
 1. Have a mod with config value which is mutable (e.g. a List)
 2. Start Minecraft Client
 3. Force `ValueSpec` validator to determine that config value is invalid (e.g. by tampering with config file on disk, or create a new world)
 4. Have default value appear in `ConfigValue`
 5. Modify config value in-game (through code, etc)
 6. Close the/Disconnect from world
 7. Tamper with saved config file to make value in question invalid again
 8. Load world
 9. Observe that `ConfigValue` in question hold array from step 5, and not actual default value (like you would expect at step 4)

**Description of issue:**

`ForgeConfigSpec$ValueSpec` constructs default value *once* it is requested and caches it there
https://github.com/MinecraftForge/MinecraftForge/blob/b0caea8e204a7f026646396558d6d58a02bff9d6/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L804-L809

This cause issue in next case, when config is requested to be reloaded it is validated by `ForgeConfigSpec#correct`, which then walk values and see if they are correct.

https://github.com/MinecraftForge/MinecraftForge/blob/b0caea8e204a7f026646396558d6d58a02bff9d6/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L220-L230

When value is determined to be incorrect `ValueSpec#correct` returns default value here:

https://github.com/MinecraftForge/MinecraftForge/blob/b0caea8e204a7f026646396558d6d58a02bff9d6/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L802

However, since we can reload config more than once per lifecycle of Minecraft (obvious example: Minecraft Client which can open multiple worlds in it's lifetime), this creates an issue, what if default value is, well, not of Value type? (has internal state and is mutable).

In this case, cached default value "bleeds" into `ConfigValue`, which means that default value can now be modified by just modifying value returned by `ConfigValue#get`

Obvious example of this bug can be seen even in Forge's provided value type, namely the `List` definition:

https://github.com/MinecraftForge/MinecraftForge/blob/b0caea8e204a7f026646396558d6d58a02bff9d6/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L390-L405

If deserialized list ends up being empty (due to Predicate validating zero elements or list itself was empty), a `getDefault()` value is returned:

https://github.com/MinecraftForge/MinecraftForge/blob/b0caea8e204a7f026646396558d6d58a02bff9d6/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L401

...which bleeds directly into config map...

https://github.com/MinecraftForge/MinecraftForge/blob/b0caea8e204a7f026646396558d6d58a02bff9d6/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L226-L227

...which ends up in `ConfigValue`, exposing value provided by default supplier

https://github.com/MinecraftForge/MinecraftForge/blob/b0caea8e204a7f026646396558d6d58a02bff9d6/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L864-L875

In live environment it looks like this:

(assuming defineListAllowEmpty returns a mutable list (which it does, it returns ArrayList if value is correct, supplier's value otherwise which is also mutable here))
```kotlin
val testList: List<String> by specBuilder.defineListAllowEmpty(listOf("test"),
	{ mutableListOf("correct value", "hey.") }, { it is String && (it == "correct value" || it == "hey.") })
```

Then we load into existing world without said config value, or create new world.

Then we tamper with our list, for example:

![bujYeedVfI](https://user-images.githubusercontent.com/6339511/190854303-6d314a60-5c10-4956-a804-c99914b4fb78.png)
![9PmJ5CSFN1](https://user-images.githubusercontent.com/6339511/190854311-55d3c111-c19d-4f15-ba00-07183777994d.png)
![0wIGjhXzim](https://user-images.githubusercontent.com/6339511/190854316-6ee4d8ec-28cf-48be-8821-23e29e724d05.png)

After we exit world *without closing the game*, we can see config value on disk was as expected updated with our added `"bleed!"` string:

![ycpqGxvKhf](https://user-images.githubusercontent.com/6339511/190854359-6d85e78a-45ca-444d-a170-691fe81606ce.png)

After this, we tamper with stored config value, so it becomes invalid:

![OJ373Sd32M](https://user-images.githubusercontent.com/6339511/190854373-45fd3c51-8516-49cc-a3e2-547396c97810.png)

After we load back into world, we notice that instead of proper default value in `ConfigValue` (array of "correct value" and "hey.") we end up with what was in previous game session:

![9zRYCCJOaJ](https://user-images.githubusercontent.com/6339511/190854425-340ed3bc-2036-4385-8d72-3ed8bc61e903.png)

Oopsie!

And while you are on it, please do check logic of `defineList` and `defineListAllowEmpty`; they don't *actually* differ (first just returns several lines earlier if config list is empty, second returns if list ends up empty, without checkint if it *was already* empty):

https://github.com/MinecraftForge/MinecraftForge/blob/b0caea8e204a7f026646396558d6d58a02bff9d6/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L397-L399

https://github.com/MinecraftForge/MinecraftForge/blob/b0caea8e204a7f026646396558d6d58a02bff9d6/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L377-L379

**Comment by marchermans** [comment]
When I designed the default value caching, I also looked into this.
As of now we don't consider this a bug.
The default value supplier should return a new instance every time it is invoked.
not sure if that is part of the documentation.

However, that said, it might be something we should discus.

**Comment by DBotThePony** [comment]
> The default value supplier should return a new instance every time it is invoked.

which is exactly the bug here, supplier is called *once* and it's return value is cached indefinitely (when it should be called again when default value is required to be provided because of validation failure)

If default value is mutable (e.g. a List), you end up modifying default value which will affect config loading/validating for all further invocations of config validation

Interestingly, all other parts of code *correctly* call supplier when default value is required, thus constructing new default value (whcih then should be put into config map).

**Comment by marchermans** [comment]
> > The default value supplier should return a new instance every time it is invoked.
> 
> which is exactly the bug here, supplier is called _once_ and it's return value is cached indefinitely (when it should be called again when default value is required to be provided because of validation failure)
> 
> If default value is mutable (e.g. a List), you end up modifying default value which will affect config loading/validating for all further invocations of config validation
> 
> Interestingly, all other parts of code _correctly_ call supplier when default value is required, thus constructing new default value (whcih then should be put into config map).

Ah now I understand the issue.
So it is only `getDefault()` that is broken, yeah that makes sense.
