### ISSUE TITLE
Model Transforms dont work for ObjModels

### ISSUE THREAD

**Issue by MehVahdJukaar** [MinecraftForge/MinecraftForge#9059]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.23

**Steps to Reproduce:**
 1. Update a mode that was using those obj models with transformations from 1.18 to 1.19 and the transformation wont be applied

**Description of issue:**
Seems like the actual transformation gets parsed fine as the syntax for the json didnt change, however its not applied on the model

**Comment by sciwhiz12** [comment]
Please provide an example of such a model, before and after being ported across versions.

**Edit:** Please also provide the logs.

**Comment by ghost** [comment]
I'm also working on this project, here is a before image:
![image](https://user-images.githubusercontent.com/66699756/192848597-ad81d816-261e-48b7-ba2a-9f8e37698d8f.png)

And after: 
![image](https://user-images.githubusercontent.com/66699756/192848851-449bdf95-2509-42f1-8b18-aa666ad1b38e.png)

Inventory Before:
I don't have one of before at the moment but I can get one soon.

Inventory After:
![image](https://user-images.githubusercontent.com/66699756/192848742-c55c3aaf-fceb-48ae-ad9d-79c74a4834ac.png)

**Comment by ghost** [comment]
I guess you can see the inventory GUI of them in the before image there, they all faced forward, etc, though I do want them to be angled, but it's clear it's not working properly.

**Comment by ghost** [comment]
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/9668296/latest.log)
[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/9668297/debug.log)

Here's mine :)

**Comment by amadornes** [comment]
Can confirm. Just looked through the code and I somehow missed this during my refactors and nobody noticed until now 😅

I'll be PRing a fix for this along with a couple other things in my work queue some time in the next day or two.

Edit: looking at my TODO list, I was apparently aware of this issue already. Whoops 🙃

**Comment by MehVahdJukaar** [comment]
Is this still not fixed after months? Should I look into it myself and make a PR?

**Comment by Technici4n** [comment]
Look at #9065
