### ISSUE TITLE
FakePlayerFactory returns players in different levels than requested

### ISSUE THREAD

**Issue by shartte** [MinecraftForge/MinecraftForge#9063]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.25

**Description of issue:**

The methods in `net.minecraftforge.common.util.FakePlayerFactory` return players that are in different levels than the ones passed to the methods, due to their internal caching. This *may* be intended, but in that case it should be documented.

We have switched to using the FakePlayer constructor directly  and maintaining our own internal per-level FakePlayer cache, since not doing this causes subtle bugs.

One such bug is trying to place blocks using a player obtained from `FakePlayerFactory#getMinecraft(level)`, when the same method was previously called with a **different** level (and the weak reference wasn't collected yet). When such a player is used to place a block (i.e. using `BlockItem#useOn`), the advancement trigger for placing blocks will cause the same block position to be loaded in the **other** level (the one the fake player is in).

**Comment by sciwhiz12** [comment]
Related to #8455, see https://github.com/MinecraftForge/MinecraftForge/issues/8455#issuecomment-1031072793 as well for another explanation. Keeping this open since this is more likely to be found by developers when searching, rather than the other one which is scoped to `BonemealEvent`.

**Comment by LexManos** [comment]
This is intended. The world is passed in solely because we need a world in order to construct the entity. Same thing with the other pr mentioning the position. The fake players are meant to be username/I'd permission nodes only.  I am open to expanding the functionality, but that was the original design. (Sorry about the close clicked wrong button on phone)
