### ISSUE TITLE
Missing translation for milk fluid type

### ISSUE THREAD

**Issue by Zeitheron** [MinecraftForge/MinecraftForge#9064]
**Minecraft Version:** 1.19.2
**Forge Version:** 43.1.32
**Logs:** None

**Steps to Reproduce:**
 1. ForgeMod.enableMilkFluid();

**Description of issue:**
The milk provided by Forge is not localized. 
Forge is missing the `fluid_type.minecraft.milk` translation key.

![image](https://user-images.githubusercontent.com/38943617/193452996-cab85b1f-6aa0-4ae9-b9cb-961c8c9cc97b.png)

**Comment by sciwhiz12** [comment]
Looks like this was an oversight from #8695. 

Previously, [`FluidAttributes` calculated the translation key](https://github.com/MinecraftForge/MinecraftForge/blob/e386229b667817fd0ea83203438b95f5e552ba2c/src/main/java/net/minecraftforge/fluids/FluidAttributes.java#L128) using `Util#makeDescriptionId` with the `"fluid"` object description type. When that PR rewrote and overhauled the Fluids API, rewriting `FluidAttributes` into `FluidType`, the [object description type was accordingly changed](https://github.com/MinecraftForge/MinecraftForge/blob/2a05c7c01d593fc3ecd01c21552c5ae7698991bb/src/main/java/net/minecraftforge/fluids/FluidType.java#L142) to `"fluid_type"`, but the existing translation keys for the milk fluid were left unchanged.
