### ISSUE TITLE
Mods can no longer override dependencies' resources

### ISSUE THREAD

**Issue by SquidDev** [MinecraftForge/MinecraftForge#9067]
**Minecraft Version:** 1.19.2
**Forge Version:** 43.1.33

**Steps to Reproduce:**
 1. Downloads mod_a.jar and mod_b.jar from [this repository](https://github.com/Squiddev/forge-pack-dependencies/). They're both lowcode mods, but the same should occur with full Java mods.
 2. Attempt to craft sticks by using the new minecraft:more_sticks recipe (two logs on top of each other).
 3. Note that the mod_a recipe (12 sticks) is used, despite mod_b depending on mod_a. If this is not the case, reverse the dependency in the two mods.toml files, rebuild the jars and relaunch - the same recipe as before should be the loaded, despite the dependencies having changed.

**Description of issue:**
In 1.14, #6287 added support for sorting datapacks based on mod dependency order. This means that if mod B depends on mod A, mod B can override A's resources.

However, this appears to have been broken in the 1.16 update. While `ResourcePackLoader.getSorter` still exists, it's not actually called anywhere!

**Comment by LexManos** [comment]
Unable to reproduce.
First world I created had 16 sticks as the result.
Edited mod_b.jar to BEFORE instead of AFTER.
Created the new world, now we have 12 as the result.
Be careful tho, datapack ordering IS saved in the world file. 
So either you'll have to use the datapack commands or create a new world in order for our sorting to manifest.

**Comment by SquidDev** [comment]
>  Be careful tho, datapack ordering IS saved in the world file.

Ahh, that does make sense. I was reusing the same world, so the previous order was preserved.

What would your thoughts be of enforcing an order for mod datapacks, only allowing user-supplied ones to be reordered? So effectively sorting the list by vanilla ≤ sorted mods ≤ user-ordered custom packs?

I'm not too worried either way - obviously in my case it's okay just to recreate the world, just the current behaviour does seem a little surprising.

**Comment by LexManos** [comment]
> What would your thoughts be of enforcing an order for mod datapacks, only allowing user-supplied ones to be reordered? So effectively sorting the list by vanilla ≤ sorted mods ≤ user-ordered custom packs?

Auto changing the order is a no go as it would screw up things like worldgen {IIRC}. Recipes would be fine but there is no concept of different sort orders for different parts of the datapack. And i think you can accomplish what you want manually by using he data pack commands.

**Comment by KnightMiner** [comment]
Would a forge command that resorts datapacks based on the mod load order (followed by world datapacks) be warranted? You could of course manually sort it, but its a bit of a pain to find what should be the correct order. Plus, the datapack command only lets you move one datapack at a time (and only to the start or end, not the middle)

**Comment by eerussianguy** [comment]
I could see the use for that. I have had users needing to do that. As long as it doesn't present maintenance concerns, I would be interested
