### ISSUE TITLE
If a mixin transformation fails due to missing dependency there is no user friendly error screen.

### ISSUE THREAD

**Issue by blackd** [MinecraftForge/MinecraftForge#9088]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.43

**Logs:** https://gist.github.com/blackd/7f24585e19d308149a28d757a3ca68c2

**Steps to Reproduce:**
 1. install [Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge/files/3925887)
 2. Install [Inventory Profiles Next](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/4029130) 
 3. start the game

**Description of issue:**

> Note:
> Inventory Profiles Next has declared dependency on [libIPN](https://www.curseforge.com/minecraft/mc-mods/libipn/files/4028723)

Game will crash during mixin transformation if the above dependency is missing and the user friendly error about the missing dependency won't be shown.

**Comment by Jonathing** [comment]
I don't know if there is a good solution to this, given how mixin loads early alongside modlauncher. If a mixin fails I don't think there is anything that Forge can do about it unless modlauncher handles it specifically. Those are just my initial thoughts on it. Given the nature of how the game and mod tools work, there won't ever be escaping reading crash logs manually in most scenarios.

**Comment by Shadows-of-Fire** [comment]
Poorly written / fragile mixins are not the responsibility of forge to fix or report errors on. Mixins should be hardened such that proper dependency error handling can be performed at the normal time.

**Comment by blackd** [comment]
The dependencies resolution is already done at that point https://gist.github.com/blackd/7f24585e19d308149a28d757a3ca68c2#file-console-output-txt-L72

My guess is that it will be possible to ignore failing transformations from non resolved mods and continuing until it's possible to show the message.

**Comment by ghost** [comment]
So what's current state about this?

**Comment by blackd** [comment]
this is how I handled it
https://github.com/blackd/Inventory-Profiles/blob/all-in-one/platforms/forge-1.19.3/src/main/java/org/anti_ad/mc/ipnext/forge/IPNMixinPlugin.kt

**Comment by ghost** [comment]
But other mods still have this problem

**Comment by blackd** [comment]
Well if it's missing dependency like in my case an error will be show in later stage of forge start.

**Comment by blackd** [comment]
In my opinion mods that don't resolve shouldn't have their mixins included in the class loafing at all but the decision is up to forge people.

**Comment by Shadows-of-Fire** [comment]
I don't entirely know how the dependency resolution process works, but running it before mixins get a chance to crash the game sounds quite difficult.

You would have to gather everything and do dep resolution before trying to load any mixins.

Realistically you should try to report issues to mods that cause mixin crashes like this when deps are missing, and see if they can resolve them.

**Comment by blackd** [comment]
the dependencies resolution is already done when mixin plugins are executed.
even if its not possible to completely exclude the mixins forge it self can provide a plugin that refuses load of mixins from non resolved mods. instead of every mod doing its own plugin.
