### ISSUE TITLE
ForgeSlider handle height does not respect the height of the widget

### ISSUE THREAD

**Issue by DaRealTurtyWurty** [MinecraftForge/MinecraftForge#9094]
**Minecraft Version:** 1.19.2

**Forge Version:** 1.19.2-43.1.43

**Logs:** N/A

**Screenshot:**
![image](https://user-images.githubusercontent.com/43997792/196047896-0a2685bc-0d3a-4e12-8906-8d054dc1070e.png)

**Steps to Reproduce:**
1. Create a screen.
2. Add a ForgeSlider component to the renderable widgets.
3. Input the height of the widget as anything other than `20`.

**Description of issue:**
When creating a `ForgeSlider` with any height other than `20`, the height of the slider handle does not change as it is hardcoded to `20`. This makes the `height` parameter *effectively*(imo) useless. As it doesn't make sense to want to have the height of the background area be a different height to the slider.

I can think of 3 solutions to this problem (all of which will provide a different result and I'm not sure which is generally preferred):
1. Override the `renderBg` method in `AbstractSliderButton`, replacing `20` with `this.height` - This will make the height of the handle respect the height of the widget.
2. (Probably not ideal) Remove the `height` parameter in the `ForgeSlider` constructor(s), passing `20` directly into the `super` - This means the height of the slider is hardcoded to `20`.
3. (Probably not ideal) Make it so that the slider background centres on the Y position of the slider handle (however, this would be much harder to achieve) - This means that the slider handle height will still not change however it would at least look a little better.

**Comment by Shadows-of-Fire** [comment]
The first approach can be taken without substantial changes.  We can draw the handle in a similar fashion to how mc draws variable length buttons: draw the top, an arbitrary length middle section that repeats the texture area, and then draw the end.
