### ISSUE TITLE
Goat horn Bug crash on multiplayer

### ISSUE THREAD

**Issue by Yrriel** [MinecraftForge/MinecraftForge#9110]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.1

**Logs:** The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: applyTransform() must not be called on a vanilla ArmPose!

**Steps to Reproduce:**
 1. (on multiplayer) Play with a friend 
 2. give him a horn
 3. let your friend use the horn
 4. **crashed on your client**

**Description of issue:**
I tried to horn, it works. but when my friend used it, the minecraft crashed.

**Comment by sciwhiz12** [comment]
Duplicate of #8985

**Comment by tmvkrpxl0** [comment]
This was my mistake, updating to 43.1.2 or higher would fix it
