### ISSUE TITLE
Add one-liner way to register builtin resourcepacks for mods

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#9119]
I wanted to add an optional builtin resourcepack for my mod that users can enable on their own like how Minecraft has a programmer art builtin resourcepack. I was then shown this is how that is done:
 https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/test/java/net/minecraftforge/debug/AddPackFinderEventTest.java

My thought is I feel like this could be simplified to a one liner registration for modders. Here’s the idea of such a system:

- Modders creates a folder called `resourcepacks` in their mod’s `resources` folder.
- Then the modder puts the resourcepack they want to use into that resourcepacks folder.
- Now the modder calls a single line while giving it a resourcelocation where the namespace is the modid of the mod’s resourcepacks folder to look under and the path is the name of resource pack itself to load as a built-in resourcepack. 

Something like:

event.registerResourcePack(new ResourceLocation(“modid”, “packfilename”), PackActivationType.DISABLED_DEFAULT, Component.literal(“Display Name Of Resourcepack”));

This may be easier for people to find and use as the current code to make builtin resourcepacks looks tricky to figure out on our own without asking the Forge discord. I had asked in another discord earlier and two people gave me incorrect/even more complex solutions which seems to show that this system is not well known. A simpler api may go a long way

**Comment by TheSilkMiner** [comment]
Why not devise a JSON-based system like JarJar, with Forge automatically discovering the packs instead?
I'd propose to put builtin resource packs in `META-INF/resourcepacks` and obtain information from `META-INF/resourcepacks/metadata.json`, if only just to make it consistent with other bundled resources.

The JSON structure could be akin to 
```json
{
  "packs": [
    {
      "identifier": "examplemod:cool_rp",
      "path": "META-INF/resourcepacks/my_builtin_resourcepack.zip",
      "display_name": { "text": "Text component in a format that can be parsed by vanilla" },
      "default_status": "One of DISABLED, ENABLED, FORCED"
    }
  ]
}
```

**Comment by Abbie5** [comment]
Hi, why was this issue closed? An API like this would be very useful IMO.

**Comment by TelepathicGrunt** [comment]
Moving over to neoforged instead. I don't want to keep up with my posts on forge repo. You are free to make a new issue report copying mine if you wish to keep it active for forge

**Comment by Abbie5** [comment]
That's understandable, I didn't see an issue in the NeoForge repo so just wanted to make sure.
