### ISSUE TITLE
Support pprof

### ISSUE THREAD

**Issue by sfxworks** [MinecraftForge/MinecraftForge#9128]
### Is your feature request related to a problem?

No

### Describe the solution you'd like.

Hi there. I would like the ability to use Grafana Phlare to gain a flame graph of servers. In order to do this, server cores need to provide a profiling data endpoint. In Paper's case, this would be jpprof https://grafana.com/docs/phlare/latest/operators-guide/configure-agent/language-support/jvm/

### Describe alternatives you've considered.

I have considered hiring a developer to make a plugin, though I feel that this would best be served at the core of paper as an enable/disable config option. 

### Other

I'm no java developer, but according to their documentation:

> If you’re using gradle, add the following dependency to your build.gradle:
```
dependencies {
// ....
    implementation 'com.grafana:jpprof:0.1.0'
//...
}
```

**Comment by zml2008** [comment]
you know, copy-pasting this issue across 3 repos works better if you actually customized the message for each project (though it's still generally frowned upon)

**Comment by ChampionAsh5357** [comment]
To quote [zml](https://github.com/SpongePowered/Sponge/issues/3785#issuecomment-1301536076):
> This is not Paper -- perhaps you are looking for a different repository?
> Based on actually reading the page, it looks like this is some sort of wrapper for async-profiler, one of the backends that [Spark](https://spark.lucko.me/) supports. Any sort of http endpoint for accessing those profiles has more of a chance of making sense there, where the plugin already focuses on profiling.

**Comment by sfxworks** [comment]
yikes! Youre right! sorry about that. let me correct this. I saw gradle and focused on copypasting the example.
