### ISSUE TITLE
Support pprof 

### ISSUE THREAD

**Issue by sfxworks** [MinecraftForge/MinecraftForge#9129]
Sorry for the initial copypasta! On 4 hours of sleep and just hunted for Gradle similarities.

I would like the ability to use Grafana Phlare to gain a flame graph of servers. In order to do this, server cores need to provide a profiling data endpoint. There' an example of it being done with jpprof here https://grafana.com/docs/phlare/latest/operators-guide/configure-agent/language-support/jvm/

I have considered hiring a developer to make a mod, though I feel that this would best be served at the core of Minecraft Forge as an enable/disable config option. 

At the same time, having it be in forge would assist in forge+serverplugin combos like SpongeForge or similar.

**Comment by ChampionAsh5357** [comment]
Regardless of the copypasta, vanilla already has its own profiler, although limited. Applications like spark, as zml mentioned, provide profiling for servers. So, generally, this would provide no additional benefit besides adding another system vanilla already has and other popular applications already have support for. You would be better off integrating with one of those available tools.

Additionally, `pprof` is a data visualization tool, so it would provide no benefit besides making a graph, which while making profiling data easier to read, is unnecessary. My opinion still stands.

**Comment by sfxworks** [comment]
>pprof is a data visualization tool

This is true, though I am talking about the ability serve runtime profiling data in the format expected by pprof by implementing this.

I've used spark before! Very well made. Though I have no way to scrape that data off of spark into a more permanent and organized place, and it would be inconsistent with other services inside a metrics collector. Perhaps I can take an issue to them to raise this concern.
