### ISSUE TITLE
Add a SprintEvent to allow cancelling/disabling sprinting

### ISSUE THREAD

**Issue by Alpvax** [MinecraftForge/MinecraftForge#9132]
Add an event hook into Entity#setSprinting to call a cancellable event to allow for restricting sprinting under certain conditions.

I currently don't have the time to setup the dev environment, so I thought I would throw it out for anyone else to implement, but if I get a chance I will create a PR.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/pull/9310#issuecomment-1636848686
