### ISSUE TITLE
[1.19.2-43.1.52] Certain modpacks do not show dependency screen when it needs to.

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#9152]
Discovered by people using 43.1.47 Forge with large modpacks noticing that they do not see the dependency screen at all for my Bumblezone mod requiring 43.1.52 Forge. Instead, they attempt to launch the game the game instantly closes. The latest.log file does show that Forge did reach and logged the dependency requirements found. It's just the dependency screen never shows up to show a user friendly screen.

I tested two modpacks (Enigmatica 9 and All the Mods 8) and both modpacks have this problem. Using just Forge and my mod alone, the dependency screen shows up properly. 

 I did test 43.1.52 Forge itself by editing my mod's mods.toml file to require 3.1.53 Forge and even the current Forge version has the issue with these modpacks. It seems there's a mod or some sort of conflict that interferes with showing the dependency screen. 
 
[enigmatica9_latest.log](https://github.com/MinecraftForge/MinecraftForge/files/10015173/enigmatica9_latest.log)
[allthemods8_latest.log](https://github.com/MinecraftForge/MinecraftForge/files/10015178/allthemods8_latest.log)

**Comment by TelepathicGrunt** [comment]
launcher_log.txt:
https://paste.ee/p/WQpAk

The log here doesn't make sense though. If the crashed due to the blockstate container access breaking Ferritecore, why does the game run normally if I change my mods.toml file to accept the current forge version but fail when I pick a future forge version requirement? Unless my version requirement triggers a pathway where mod init gets all confused and causes ferritecore to kill the game?  Odd

**Comment by malte0811** [comment]
The FC error is a known clash between my blockstate neighbor optimization in FC and that done by lithium/canary. Canary [disables](https://github.com/AbdElAziz333/Canary/blob/e35b3bf0883cb09e363397cfa95f837a70c80e02/src/main/java/com/abdelaziz/canary/mixin/CanaryMixinPlugin.java#L46-L48) their optimization when FC is present to avoid this. Is the data in `LoadingModList` invalid if any mod was missing a dependency, even though the queried mod continues to load? I had a similar report on FC a few days ago which was also caused by incorrect dependency versions (malte0811/FerriteCore#102), so that seems like a likely explanation.

CC @AbdElAziz333 (author of canary)

Edit: Probably the relevant code: https://github.com/MinecraftForge/MinecraftForge/blob/bc0517a404a0d766a715887fc554bbff4a9680ce/fmlloader/src/main/java/net/minecraftforge/fml/loading/ModSorter.java#L58-L63

**Comment by marchermans** [comment]
https://github.com/AbdElAziz333/Canary/blob/e35b3bf0883cb09e363397cfa95f837a70c80e02/src/main/java/com/abdelaziz/canary/mixin/CanaryMixinPlugin.java#L46 this is not sufficient!

The mixin plugin operates on service level and should also check for a valid environment before checking the mod list.

As such this is not a forge issue, but an issue in the way the mixin does the filtering, we already do our best to not crash, but we need to load a base set of classes and systems and mixin just operates on a too low level to handle that better.

Please send this to mixin authors: you will also need to check if there are early loading errors posted on they loading mod list else your mixin collision check will not work and when a collision occurs you will crash!

**Comment by TelepathicGrunt** [comment]
What about when two mods shade the same lib but forget to relocate it? (I already reached out to dev doing this to let them know to fix it). In this case, conflict on shaded lib also prevent forge from showing a conflict screen with no info in the latets.log file (launcher.log shows the info). Is there nothing that can be done to try and get the info at least into the latest.log file for users?

https://www.curseforge.com/minecraft/mc-mods/whisperwoods
https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus
`Exception in thread "main" java.lang.module.ResolutionException: Module betteranimalsplus contains package architectury_inject_IMDLib_common_0fb67318c8064bf3aee5ab008b47f9fa_e85031831e73db233f314ec823f974ac9abaadc875a784c26812906b6e8f0344imdlib119f00da719bc3b557d294420e37e9c843774559754devjar, module whisperwoods exports package architectury_inject_IMDLib_common_0fb67318c8064bf3aee5ab008b47f9fa_e85031831e73db233f314ec823f974ac9abaadc875a784c26812906b6e8f0344imdlib119f00da719bc3b557d294420e37e9c843774559754devjar to betteranimalsplus`
[launcher_log.txt](https://github.com/MinecraftForge/MinecraftForge/files/10025762/launcher_log.txt)
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/10025779/latest.log)

**Comment by marchermans** [comment]
> What about when two mods shade the same lib but forget to relocate it? (I already reached out to dev doing this to let them know to fix it). In this case, conflict on shaded lib also prevent forge from showing a conflict screen with no info in the latets.log file (launcher.log shows the info). Is there nothing that can be done to try and get the info at least into the latest.log file for users?
> 
> https://www.curseforge.com/minecraft/mc-mods/whisperwoods https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus `Exception in thread "main" java.lang.module.ResolutionException: Module betteranimalsplus contains package architectury_inject_IMDLib_common_0fb67318c8064bf3aee5ab008b47f9fa_e85031831e73db233f314ec823f974ac9abaadc875a784c26812906b6e8f0344imdlib119f00da719bc3b557d294420e37e9c843774559754devjar, module whisperwoods exports package architectury_inject_IMDLib_common_0fb67318c8064bf3aee5ab008b47f9fa_e85031831e73db233f314ec823f974ac9abaadc875a784c26812906b6e8f0344imdlib119f00da719bc3b557d294420e37e9c843774559754devjar to betteranimalsplus` [launcher_log.txt](https://github.com/MinecraftForge/MinecraftForge/files/10025762/launcher_log.txt) [latest.log](https://github.com/MinecraftForge/MinecraftForge/files/10025779/latest.log)

Granted that is something that should not really happen.
But this happens on an extremely low level, we would need to build a fallback mechanism into BSL to prevent this. @cpw Any thoughts?
