### ISSUE TITLE
Need hook to allow modded fluids to set wasTouchingWater field to true for entites

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#9154]
I noticed Blazes weren't taking damage when in my sugar water. In the past, I had it tagged as minecraft:water to do that effect.

Here's what I am noticing, `LivingEntity.aiStep()` calls `this.isSensitiveToWater() && this.isInWaterRainOrBubble() `to know when to do drown damage for the entity. 
![image](https://user-images.githubusercontent.com/40846040/202863255-367a4266-426a-483b-85d0-4426d8fbb436.png)

![image](https://user-images.githubusercontent.com/40846040/202863249-483fc769-b8b9-4478-884f-fdd1da8e4c8b.png)

The `isInWater` part checks the `wasTouchingWater` field. Which looks like it is set in `Entity.updateInWaterStateAndDoWaterCurrentPushing()` which is `callingthis.updateFluidHeightAndDoFluidPushing(FluidTags.WATER, 0.014D)`
![image](https://user-images.githubusercontent.com/40846040/202863236-a281b021-41e4-4f5b-b0e3-eedf2da88595.png)

And that last method looks hardcoded to vanilla fluids. 
![image](https://user-images.githubusercontent.com/40846040/202863234-c285a3c6-ad66-4494-a2f6-4e48747e659c.png)

**Comment by Thutmose** [comment]
Vanilla used to check the tag, but the forge patch is what made it no longer work properly, by changing the tag check to the check for `ForgeMod.WATER_TYPE`

Edit: specifically this patch here:
https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/patches/minecraft/net/minecraft/world/entity/Entity.java.patch#L232-L233

and in several other places I think?
