### ISSUE TITLE
Fatal Crash in Java environment, might be related to nvidia gpu drivers

### ISSUE THREAD

**Issue by 2el222** [MinecraftForge/MinecraftForge#9161]
[hs_err_pid11700.log](https://github.com/MinecraftForge/MinecraftForge/files/10057022/hs_err_pid11700.log)
Game crashes upon entering the world, only present after nvidia gpu drivers update, Forge 43.1.53 MC 1.19.2, submitted the crash to openjdk issues github and nvidia user feedback already

**Comment by FinnT730** [comment]
So, since you posted the JVM error dump, which contains your accessToken, I would recommend logging out from the launcher and in again. With that token, people can get access to your account.

As for the rest, no idea, sorry

**Comment by marchermans** [comment]
Report this upstream to Mojang.

**Comment by 2el222** [comment]
> So, since you posted the JVM error dump, which contains your accessToken, I would recommend logging out from the launcher and in again. With that token, people can get access to your account.
> 
> As for the rest, no idea, sorry

logged out as soon as I posted the file ;)

**Comment by 2el222** [comment]
> Report this upstream to Mojang.

Will do
