### ISSUE TITLE
1.11.2 --> Main Forge Installer cannot access this URL - It is forbidden - used to be able to 2 weeks ago

### ISSUE THREAD

**Issue by Bulbousonions13** [MinecraftForge/MinecraftForge#9162]
Hello,

I have to run the Forge Installer in multiple different modes for work - sometimes in Docker, sometime straight from the Windows.exe.

Recently we are getting this error regardless of the modality of running the installer.  This resource seems forbidden to the general public.

java.io.IOException: Server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.11.2/1.11.2.jar

![be98cd1e-614a-4d8f-805a-e2a4ec77c6d8](https://user-images.githubusercontent.com/22357299/203138844-06c24d5a-7927-4116-b22f-088098771b2b.jpg)

Is this an error on Forge's side, or are we supposed to have authenticated ourselves somehow?

Thanks

**Comment by James103** [comment]
I get the same error (HTTP 403) for the following URL:
https://s3.amazonaws.com/Minecraft.Download/
and all subdirectories of that URL (even those that don't exist).

**Comment by LexManos** [comment]
I have rebuilt all installers, Mojang removed that endpoint. I could of sworn we updated the legacy installers already but apparently not. Such is the issue with old versions. Sometimes people outside our control change things.

**Comment by Bulbousonions13** [comment]
Thank you! Just being annoying now, but does rebuilding them mean there will be new versions available here eventually? 
![image](https://user-images.githubusercontent.com/22357299/203420113-6fa203f0-b8a5-4903-9275-39819218245c.png)

**Comment by LexManos** [comment]
No, it means that the installer download has changed.
