### ISSUE TITLE
fatal error minecraft has mods that were not found 1.14.4

### ISSUE THREAD

**Issue by oriolprogamer712** [MinecraftForge/MinecraftForge#9165]
fatal error minecraft has mods weather2 1.14 that were not found 1.14.4

**Comment by oriolprogamer712** [comment]
![IMG_20221124_214639.jpg](https://user-images.githubusercontent.com/92949450/203860885-96c4d546-388b-4373-bfb3-122bc21a145a.jpg)

**Comment by RealMangorage** [comment]
The issue has to with that mod. "Weather2-1.18" Also that mod is for 1.18 not for 1.14...
