### ISSUE TITLE
Forge calls `updateNeighbourForOutputSignal()` twice, unnecessarily whenever a block entity calls `setChanged()`.

### ISSUE THREAD

**Issue by alcatrazEscapee** [MinecraftForge/MinecraftForge#9169]
The code is the same in 1.19.x (43.1.65) and 1.18.x (40.1.86) editions of Forge at time of reporting.

In vanilla, the following code is present when a block entity is set changed:

```java
protected static void setChanged(Level level, BlockPos pos, BlockState state) {
    level.blockEntityChanged(pos);
    if (!state.isAir()) {
        level.updateNeighbourForOutputSignal(pos, state.getBlock());
    }
}
```

However, note that Forge *patches* `Level#blockEntityChanged`, adding the following:

```java
public void blockEntityChanged(BlockPos pos) {
    if (this.hasChunkAt(pos)) {
        this.getChunkAt(pos).setUnsaved(true);
    }
    // vv The below line is added by Forge vv
    this.updateNeighbourForOutputSignal(pos, getBlockState(pos).getBlock()); //Notify neighbors of changes
}
```

by the following patch:

https://github.com/MinecraftForge/MinecraftForge/blob/dd8239c255b399720ce38e2b7d3195906521d873/patches/minecraft/net/minecraft/world/level/Level.java.patch#L152

This means that `updateNeighborForOutputSignal` is being called twice, unnecessarily, whenever a block entity is marked change. I noticed this when looking into a profile of a server with a lot of block entities that mark dirty frequently, due to consistently changing their saved data, and noticed this taking up 2.35% of server tick times when none of these calls needed to be there.

**Comment by KnightMiner** [comment]
For the record, in a lot of my mods I have opted to make my own faster version of `markDirty`/`setChanged` that does not call the comparator update at all, as most NBT changes do not affect comparators (if it does, I can call the vanilla method). Might be worth forge providing a similar fast version of set changed as I know I am not the only one adding such a method.

**Comment by LexManos** [comment]
You do realize this method is for more then just comparators right.... Anyways, you are right in one specific aspect, it doesn't need to call things twice for the same event. Looking at the patch history, it seems that [cpw screwed up a patch migration.](https://github.com/MinecraftForge/MinecraftForge/blob/6d15febdb35b5676b1795b2965d6eb527bb336e6/patches/minecraft/net/minecraft/world/World.java.patch) Seems like a simple enough thing to fix now that someone mentioned it. Also next time you make a profiling claim, feel free to submit your snapshot. As this doesn't have that much of a hit in any of my tests.

**Comment by KnightMiner** [comment]
Okay fine, a method for the sake of people who want a NBT change to persist on disk without being required to lookup 6 blockstates and call 3 neighbor change hooks on each block. Such a method is notably on internal NBT changes that would never impact neighbors

**Comment by alcatrazEscapee** [comment]
> Also next time you make a profiling claim, feel free to submit your snapshot.

https://spark.lucko.me/H8FKRgfvye

Note that like @KnightMiner mentioned, we already do bypass `setChanged()` with our own `markDirty()` which I had *thought* was bypassing these neighbor checks, hence was surprised when I saw them in the stack trace when they shouldn't be at all (as where we call `markDirty` from has no reason to update neighbors because again; lots of block entities that are frequently changing).
