### ISSUE TITLE
item_nbt output does not apply nbt on smithing recipes

### ISSUE THREAD

**Issue by RecyclingTiger** [MinecraftForge/MinecraftForge#9171]
**Minecraft Version:** {Minecraft version}
1.16.5
**Forge Version:** {Forge version. *Version number, not latest/rb*}
Forge 36.2.35 
**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/10145757/latest.log)

**Steps to Reproduce:**
 1. Create a smithing recipe that outputs an item with nbt
 2. Try to create the item
 3. It does not have the nbt that you specified

**Description of issue:**
Creating a smithing table recipe with a custom nbt does not give the item that was specified. It does show up in jei or other recipe showing mods, but when I try to craft the item it doesn't have it.

Here is an example datapack that gives the unbreakable nbt to an iron sword:
the crafting recipe correctly gives it the tag, the smithing recipe does not.
[nbtrecipepack.zip](https://github.com/MinecraftForge/MinecraftForge/files/10145760/nbtrecipepack.zip)

**Comment by sciwhiz12** [comment]
As reflected in our support policy, we only support the Latest and LTS versions, currently 1.19.x and 1.18.x respectively. 1.16.5 is out of support.
