### ISSUE TITLE
[1.19.3/Bug] Search tab not searching correctly

### ISSUE THREAD

**Issue by ApexModder** [MinecraftForge/MinecraftForge#9176]
**Minecraft Version:** 1.19.3

**Forge Version:** 44.0.0

**Logs:** https://paste.md-5.net/ipecolokal.md

**Steps to Reproduce:**
 1. Load 1.19.3 with forge installed
 2. Load any world existing or new in creative mode
 3. Search for `flint` in the search tab

**Description of issue:**
When loading a previous or freshly generated world on 44.0.0-1.19.3 the search tab in creative does not search for items correctly.

Searching for `flint` does not result in showing flint, flint & steal and other similarly named items, while searching for `oak` shows all the relevant oak like items (oak planks, logs, wood).

![image](https://user-images.githubusercontent.com/29412632/206423547-6a26d1fe-bb54-4f71-b9c3-7b733767163b.png)

Edit: Just tested on a production build (using prism launcher to setup profile) and the issue occurs outside of development environments too

**Comment by marchermans** [comment]
Okey interesting, so it only finds certain items?
Or is the tab just empty?

**Comment by ApexModder** [comment]
Yes only certain items are not found, and its not "items not in any tabs" as flint & steel is in the tools tab, its just some items are not found when searching

**Comment by marchermans** [comment]
Interesting is it always the same items?
Or do they fluctuate?

**Comment by ApexModder** [comment]
Always the same item from what ive seen, although I have only tried searching for `flint`/`oak` across various instances [dev/prod envs and new/existing worlds]

**Comment by ricksouth** [comment]
Spawn eggs are also not being found.

**Comment by Asek3** [comment]
![image](https://user-images.githubusercontent.com/64613894/206454954-c995ebf3-dd9f-41cd-a205-7284cef56553.png)
![image](https://user-images.githubusercontent.com/64613894/206455020-cf390fbc-9666-4996-9274-0fe18c68ec02.png)
Also can't find any things in other languages
