### ISSUE TITLE
`(Sided)InvWrapper` does not account for some `canPlaceItem` edge cases

### ISSUE THREAD

**Issue by Technici4n** [MinecraftForge/MinecraftForge#9178]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.1.25

**Steps to Reproduce:**
 1. Try to insert a stack of >1 buckets or bottles from the side of a furnace or brewing stand respectively using some modded automation. I used IE conveyors.
 2. Notice that the furnace or brewing stand accepts too many items: 
![image](https://user-images.githubusercontent.com/13494793/206462452-a7e964c8-1306-4705-97b4-8aac739e0438.png)
![image](https://user-images.githubusercontent.com/13494793/206462483-a8f17bd6-fcee-4c56-9d18-199ddc956732.png)

**Detailed explanation**
So, vanilla has two very hacky `Container#canPlaceItem` implementations to make some specifc items unstackable. They achieve this by allowing insertions if the current stack is empty. This works fine when inserting items 1 by 1, however in a modded context it doesn't work when multiple items are inserted at once.

The two offenders are the insertion of buckets in the furnace fuel slot and the insertion of brewing recipe inputs in slots 0/1/2:
![image](https://user-images.githubusercontent.com/13494793/206460797-63d4fe23-2431-4301-a0d5-80ff5c30c9f2.png)
![image](https://user-images.githubusercontent.com/13494793/206461087-6f7e6fa3-11fc-4cae-9b7c-472d36bff2ed.png)

`SidedInvWrapper` needs special logic to account for this edge case. I'll provide the patch in a bit.

**Comment by sciwhiz12** [comment]
Confirmed without using a modded item-moving automation by modifying `VanillaInventoryCodeHooks#insertHook` to use a larger stack size (changin the constant given to `HopperBlockEntity#removeItem`) and using a hopper to insert into a furnace or brewing stand.
