### ISSUE TITLE
AbstractTreeGrower patch may not be needed anymore / likely to cause issues porting mods

### ISSUE THREAD

**Issue by eerussianguy** [MinecraftForge/MinecraftForge#9183]
**Minecraft Version:** 1.19.3

**Forge Version:** 44+

**Description of issue:**

Relevant patch: https://github.com/MinecraftForge/MinecraftForge/blob/8255d7aed3c44129bb08b7b5961f0e9fe3a5a121/patches/minecraft/net/minecraft/world/level/block/grower/AbstractTreeGrower.java.patch

Before, mojang had AbstractTreeGrower only able to use code configured features as-is, so forge has a patch to allow datapack features with `Holder<CF>`. Modders were instructed to implement the abstract method provided by mojang and return null, because it was patched out. Now, that method returns a `ResourceKey`, and Mojang has migrated to JSON configured features, so we don't need this patch anymore, unless we decide that the extra context in the method is useful.

A related note is that now, returning `null` in the vanilla method as modders did before causes the tree to not grow, given the patch is in a slightly different spot.

Any fix to this would be breaking, but since the signature of the methods changed during porting (to allow ResourceKey), this is already something that broke for modders so it would not be as big of a deal to remove.

**Comment by Caio202Cesar** [comment]
I'm modding Minecraft 1.16.5 and I DON'T know how I add a tree to Minecraft in my mod. Can someone help me?

**Comment by Caio202Cesar** [comment]
How can I make a palm tree now?
