### ISSUE TITLE
[1.19.3] Using a DeferredRegister on a non-forge wrapped registry does not register entries

### ISSUE THREAD

**Issue by AlexModGuy** [MinecraftForge/MinecraftForge#9199]
**Minecraft Version:** 1.19.3

**Forge Version:** 44.0.1
**Logs:** https://gist.github.com/AlexModGuy/ccadfda276eb0414a9a8232b2ff21f67

**Steps to Reproduce:**
 1. Create a deferred registry to a vanilla registry that is unmapped by forge (Not in ForgeRegistries), examples include Registries.STRUCTURE_TYPE, Registries.LOOT_FUNCTION_TYPE, Registries.FROG_VARIANT etc...
 2. Register an entry to said deferred registry
 3. retrieve the wrapped object of the entry somewhere down the line using .get()
 4. IllegalStateException crash will follow, usually with the message similar to "Trying to access unbound value 'ResourceKey[minecraft:loot_function_type / cloudstorage:dye_randomly]' from registry net.minecraft.core.MappedRegistry$1@1c6ac73c"

**Description of issue:**
The Expected behavior of this is the same as 1.19.2, when you could register to unmapped vanilla registries using a deferred register. Now, in 44.0.1, it seems that entries registered to these deferred registries are registered too late or not at all.

**Comment by LexManos** [comment]
Someone provide a test mod for this, and if nobody has done it by monday i'll look into it.

**Comment by eerussianguy** [comment]
Log file:
https://pastebin.com/EN9zAqpZ

Test mod (built in the forge dev test mod suite, so just drop it in there and add it to the toml): 
https://gist.github.com/eerussianguy/9e27fab339830f01f89a888f9f442c19
