### ISSUE TITLE
[1.16.5] Attacking an entity crashes the game/server

### ISSUE THREAD

**Issue by Raburr0** [MinecraftForge/MinecraftForge#9201]
**Minecraft Version: 1.16.5**

**Forge Version: 36.2.34**

**crash report:** https://pastebin.com/NgBqrr4i
**logs:** https://gist.github.com/Raburr0/4d39bee1a84410ee47011de3cd5fcefa

i have over 120 mods in my modpack, as from the title attacking any kind of mob immediately crashes the client if in singleplayer, and the same for the server if in multiplayer.
i have tried to see from my own knowledge if there was any mods conflicting with eachother but yet i am unaware

**Comment by sciwhiz12** [comment]
As reflected in our support policy, we only support the Latest and LTS versions, currently 1.19.x and 1.18.x respectively. 1.16.5 is out of support. Also this is a place to report issues with Forge directly. If you have issues with mods refer to their authors/the forums.
