### ISSUE TITLE
--fml.mavenRoots document usage missing

### ISSUE THREAD

**Issue by Kenhuey** [MinecraftForge/MinecraftForge#9206]
Minecraft Forge Client 1.12.2

I am finding a solution to load specify mod with starter arguments.
But I had read and try https://github.com/MinecraftForge/MinecraftForge/wiki/FML , it dosen't work.

Wiki is not updates those FML arguments, how can I use those argument correctly?

commands be like:
```
# from other issue found
--fml.mavenRoots 
--

# from offical wiki
--fml.mods
--fml.modList
```

**Comment by sciwhiz12** [comment]
As reflected in our support policy, we only support the Latest and LTS versions, currently 1.19.x and 1.18.x respectively. 1.12.2 is out of support.

**Comment by Kenhuey** [comment]
> 正如我们的支持政策所反映的那样，我们仅支持最新版本和 LTS 版本，目前分别为 1.19.x 和 1.18.x。1.12.2 不受支持。

I tried 1.19.x  
But didnt see any arguments like --fml.mavenRoots 's usage document, official wiki is out of date.

**Comment by LexManos** [comment]
>The information in this document may be outdated due to the various refactors and changes done to FML over the years.
> It is recommended to take this document with a grain of salt, and to inspect the FML codebase for the current working logic.

Also the github wiki is not the official wiki. 
Also these arguments dont exist anymore.
Things change in many years of development. If you want help follow the proper channels and use supported versions.
