### ISSUE TITLE
ZombieTurtleEggAttackGoal ai broken in 1.18

### ISSUE THREAD

**Issue by SCPRedMage** [MinecraftForge/MinecraftForge#9241]
**Minecraft Version:** 1.18.2
**Forge Version:** 40.1.61

As reported for version 1.19 [here](https://github.com/MinecraftForge/MinecraftForge/issues/8853), the same issue exists in 1.18.2.

**Comment by SCPRedMage** [comment]
I'm not sure why this was labeled 1.19, when this is a report for 1.18.

**Comment by sciwhiz12** [comment]
Whoops, my mistake.
