### ISSUE TITLE
Problem using the Extract function in the installer.

### ISSUE THREAD

**Issue by luizinhoh2o1** [MinecraftForge/MinecraftForge#9249]
There is a problem using the "Extract" function of the Forge installer.

File downloaded from Forge recommended version -> "forge-1.19.2-43.2.0-installer"

When I use the "Extract" function, a Success message is displayed on the screen, however, no file is extracted in the selected location to extract.

**Comment by LexManos** [comment]
To be expected. I could of sworn we set the hideExtract option. Guess it got missed somewhere. 
There is nothing to extract from the installer that would be useful to end users.

**Comment by luizinhoh2o1** [comment]
> Era de se esperar. Eu poderia jurar que definimos a opção hideExtract. Acho que se perdeu em algum lugar. Não há nada para extrair do instalador que seja útil para os usuários finais.

I believe that many users have a problem, because we need Extract to create Modpack for Technic.

**Comment by luizinhoh2o1** [comment]
You can also make Universal Forge available for Modpack creators to use in Technic. The site indicates that the Universal Forge be renamed to the name "modapack" and placed inside a "bin" folder to create a modpack available to download and use in Technic.

**Comment by luizinhoh2o1** [comment]
Follow the tutorial link ->
https://technicpack.zendesk.com/hc/en-us/articles/204199345-How-to-make-a-Minecraft-modpack

**Comment by LexManos** [comment]
That tutorial is 5 years out of date. I'd also advise using a platform that is that far out of date. Either way this isn't a issue with us. Talk to whatever platform you're making packs for.
