### ISSUE TITLE
[1.19.2] Inconsistent vaporization in BucketItem & FluidType

### ISSUE THREAD

**Issue by cech12** [MinecraftForge/MinecraftForge#9261]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.2.1

**Description of issue:**

I found an inconsistency between the "vanilla" `BucketItem` and the `FluidType` class (or the `FluidUtil`). It lies in the default vaporization behaviour of fluids.

The `BucketItem` checks if the dimension is "ultrawarm" and the fluid has the `FluidTags.WATER` **tag**:

`BucketItem::emptyContents` (line 126)
```
} else if (p_150717_.dimensionType().ultraWarm() && this.content.is(FluidTags.WATER)) {
```

The [`FluidUtil::tryPlaceFluid`](https://github.com/MinecraftForge/MinecraftForge/blob/1.19.2/src/main/java/net/minecraftforge/fluids/FluidUtil.java#L574) method uses the [`FluidType::isVaporizedOnPlacement`](https://github.com/MinecraftForge/MinecraftForge/blob/1.19.2/src/main/java/net/minecraftforge/fluids/FluidType.java#L829) method to check,  if the fluid should vaporize:

```
    public boolean isVaporizedOnPlacement(Level level, BlockPos pos, FluidStack stack)
    {
        if (level.dimensionType().ultraWarm())
        {
            BlockState state = this.getBlockForFluidState(level, pos, this.getStateForPlacement(level, pos, stack));
            return state != null && state.getMaterial() == Material.WATER;
        }
        return false;
    }
```

Here, however, it is checked whether the **material** is `Material.WATER`. That doesn't match the BucketItem implementation.

That could lead to incompatibilities between mods. For example my BucketLib mod act differently to the bucket item of fluids that are generated KubeJS, because they are using the BucketItem implementation and my buckets are using the `FluidUtil` compatibility class. https://github.com/cech12/WoodenBucket/issues/7

This inconsistency seems to be for a while and can also be found in 1.19.3.

My question is, what is the best way to fix that? Should the BucketItem be changed to check the material instead of the tag or should the FluidType check the tag instead of the material?
Or is it intended to work like this?

Thanks for your help. I would open a PR if a decision is found. :)

**Comment by ChampionAsh5357** [comment]
So, in general, the Fluid PR was meant as a way to disambiguate all logic from it's hardcoded nature. As such, calls that were made directly to specific materials, fluids, or tags that wouldn't normally be replaced were swapped for more generic counterparts. Since this wasn't a change in the original fluid PR, except for the generalizability of `#isVaporizedOnPlacement`, I would assume this disambiguation has been there for a long while.

In general, this doesn't cause any issues if the mod overrides the default state. For ease of convenience, an additional else if statement could be added onto `BucketItem#emptyContents` to check `#isVaporizedOnPlacement` and then call `#onVaporize`.

**Comment by cech12** [comment]
Yes, I like that idea! :)
So, if I understand you correctly, it is intended to check the fluid material instead of the tag in the default implementation?

Then I would open a PR to add the mentioned else if branch to the BucketItem. :)

**Comment by ChampionAsh5357** [comment]
This stems all the way back to #2959, so it seems it was intended as such. Regardless, I do think it makes more sense to add the else if. Additionally, the level is ultrawarm should probably check for water since that's what that's intended for, but I don't think it'll be much of an issue.

**Comment by cech12** [comment]
Wow, that is way back^^ Minecraft 1.9 as far as I know. 

Yes, the else if should be added. 

The only question left is, that the default implementation should be changed to tags. In Minecraft 1.9 tags were not present. maybe with the changes over time it could be overseen that the vaprization behaviour was changed to the water tag. 
Maybe it is a good idea to change the default implementation of the fluid type to check the water tag instead of the material. But that decision is up to you :)

**Comment by ChampionAsh5357** [comment]
Forge currently doesn't want server logic within Forge associated with tags, hence the whole point of the fluid system tied to a `FluidType`. That's why I said the if statement in the vaporization check should check if the type is water and not in the water tag.

**Comment by cech12** [comment]
Okay, tomorrow I will open a PR. :)
