### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Kasia1403** [MinecraftForge/MinecraftForge#9263]
To add an ability to sleep a PC when Minecraft ( modded and unmodded ) is loading and also when a world is loading. This will help skip time when sleeping at night and when a player in real world will wake up then he will be able to play without wasting time for useless waiting.

**Comment by Kasia1403** [comment]
Why this is not planned ?

**Comment by LexManos** [comment]
Because this is not how computers work, and this is not something we'd ever want to do to Minecraft.
If you want to 'preload' the game while you're sleeping. Then just load the game and turn off your monitor.
