### ISSUE TITLE
[1.19.3] Implement Exception printing in Networking Exception Handler

### ISSUE THREAD

**Issue by hYdos** [MinecraftForge/MinecraftForge#9264]
In 1.19.3, `AbstractChannelHandler` has a method called `invokeExceptionCaught` which tries to handle an exception being thrown. I have found out that instead of this code printing the exception it instead catches it and tries to disconnect the client on the client side, Leading to a `ClassCastException` which is misleading and doesn't say much about the error. I would like `invokeExceptionCaught` to run `Throwable#printStackTrace` to be able to see the encoding issue with packets im writing

**Comment by LexManos** [comment]
If this is still an issue, please re-open and provide a sample mod that produces the issue you're seeing.
