### ISSUE TITLE
Spurious experimental features warnings in 1.19.3

### ISSUE THREAD

**Issue by warjort** [MinecraftForge/MinecraftForge#9272]
**Minecraft Version:** 1.19.3

**Forge Version:** 44.0.48

**Steps to Reproduce:**
 1. Download mdk
 2. runclient
 3. create new world
 4. warning about experimental features

**Description of issue:**
Previous issue for 1.18 having the same problem: https://github.com/MinecraftForge/MinecraftForge/issues/8414

**Comment by Mysterious-Dev** [comment]
I have the same issue for a clean Forge (1.19.3-44.1.4) installation.

https://youtu.be/-4NkZW0Q890
