### ISSUE TITLE
Update MDK Gradle Wrapper to 7.6 (or 8.0).

### ISSUE THREAD

**Issue by Mysterious-Dev** [MinecraftForge/MinecraftForge#9288]
The MDK is now in version 7.5.1 for the Gradle wrapper, 7.6.0 is released since November 25, 2022. Maybe an update of the wrapper for the MDK would be interesting (even if 8.0 is coming soon).

https://github.com/gradle/gradle/releases/tag/v7.6.0
https://github.com/gradle/gradle/releases/tag/v8.0.0-RC1

**Comment by SizableShrimp** [comment]
7.6 is broken with ForgeGradle which is why it is not in use at this point in time.

**Comment by Mysterious-Dev** [comment]
Oh right, I didn't know this fact. In that case, is the plan to wait for 8.0 to migrate ForgeGradle on it?

**Comment by PaintNinja** [comment]
Related: https://github.com/MinecraftForge/Artifactural/pull/5 (7.6 support in FG5)

Gradle 8 support will be in FG6
