### ISSUE TITLE
BuiltInRegistries.CONFIGURED_FEATURE missing in Minecraft 1.19.3

### ISSUE THREAD

**Issue by CodingNoob52** [MinecraftForge/MinecraftForge#9312]
It does not seem possible to register a new ConfiguredFeature in Minecraft 1.19.3 because BuiltinRegistries.CONFIGURED_FEATURE is not defined anymore. Is there any workaround or update needed in order to still be able to create custom ConfiguredFeatures?

**Comment by TelepathicGrunt** [comment]
@CodingNoob52 Mojang switched to only using json for the worldgen registries so you have to create your configured feature in json or use data generation to create the json. You can check the Forge discord 1.19 channel's pins to see some helpful resources

**Comment by marchermans** [comment]
This is a decision mojang made and not something we can fix. They are completely datadriven.
