### ISSUE TITLE
Forge added "milk" fluid has no sound for filling, emptying.

### ISSUE THREAD

**Issue by alcatrazEscapee** [MinecraftForge/MinecraftForge#9316]
**Minecraft Version:** 1.19.3 and 1.18.2

**Forge Version:** 44.1.5 (in 1.19.3), and 40.1.73 (in 1.18.2)

**Description of issue:**

Forge registers a milk fluid with no sounds for filling, emptying. The vanilla bucket is then silent when interacting with containers that just query the fill sound and play it. The code in 1.19.3:

https://github.com/MinecraftForge/MinecraftForge/blob/59ab01a55906cd2b5ff94b8a475add25cff27260/src/main/java/net/minecraftforge/common/ForgeMod.java#L524

is missing `.sound()` on the fluid type.

And the code in 1.18.2:

https://github.com/MinecraftForge/MinecraftForge/blob/aa170facb7284527bb0240d847a084ea09189cbb/src/main/java/net/minecraftforge/common/ForgeMod.java#L266

is missing `.sound()` on the fluid attributes.

This was reported as a bug in one of my mods, where milk was silent. But as we just enable Forge's milk fluid for Compatibility Reasons, the lack of a sound is due to it not being registered with a sound in the first place.

I don't see why this could not be registered with the vanilla water fill + empty bucket sounds, same as the vanilla water bucket.

**Note** that in 1.18.2, Forge already uses these sounds in creating attributes for vanilla water:

https://github.com/MinecraftForge/MinecraftForge/blob/aa170facb7284527bb0240d847a084ea09189cbb/src/main/java/net/minecraftforge/common/ForgeHooks.java#L920

**Comment by ChampionAsh5357** [comment]
The most important question is that what would the fill and empty sounds for milk would be? I believe the reason I didn't set anything originally was that the bucket fill and empty sounds are specific to the fluid. If that's the case, should the fill and empty sound be that for water, or should it be a unique sound provided by Forge? If the latter, how would we determine what the sound should be?

**Comment by KnightMiner** [comment]
Just use water, or a custom sound event if you wish that redirects to water. I don't see a need to overcomplicate Forge's milk further.

**Comment by ChampionAsh5357** [comment]
Fair enough. The second option makes more sense to me just to have more flexibility in those who wants to replace specific assets.
