### ISSUE TITLE
Game should check the mod folder and its subfolders on start

### ISSUE THREAD

**Issue by janSipiki** [MinecraftForge/MinecraftForge#9317]
I like to make large modpacks with Forge, and allowing you to place mod jars into sub-folders of mods, while still allowing the game to access them, would be really useful for organization. 

Hope this gets implemented!

**Comment by TheCurle** [comment]
We removed this feature when Mojang implemented the Game Directory system.
You can now choose in the vanilla launcher where your mods folder is, without needing to share saves, resource packs, etc between all different modpacks (and thus risk breaking a world by running it in a different version!)
