### ISSUE TITLE
[1.19.3] Block entities using INFINITE_EXTENT_AABB don't render at all angles

### ISSUE THREAD

**Issue by josephtarbit** [MinecraftForge/MinecraftForge#9321]
Starting from 1.19.3, returning `INFINITE_EXTENT_AABB` from `getRenderBoundingBox` has stopped working as it should. When looking up or down at a block entity using this, they don't render. Here's an example with beacons: 

Forge
![image](https://user-images.githubusercontent.com/26169906/214889006-9e6c1fae-bb81-4b7c-8dd2-58851414976a.png)

Vanilla
![2023-01-26_16 16 35](https://user-images.githubusercontent.com/26169906/214889298-95b0daed-7635-4d88-b989-9e7a73d81390.png)

I assume this is due to vanilla now using JOML's `FrustumIntersection` instead of its own frustum checks.

**Comment by sciwhiz12** [comment]
Confirmed on 1.19.3-44.1.8 with the beacon beam and structure block outline. The beam and outline disappears, wherever it may be rendering on the screen, if the player's rotation (and therefore, the look vector of the camera) is aligned with an axis, i.e. if either the pitch or the yaw of the player is a multiple of 90 (including 0 and negative values).

The following commands demonstrate the issue at different look vectors. For best results, construct 4 beacons in each of the four cardinal directions of the player such that the player can observe the beam of at least one beacon in all directions.

- `/tp @s ~ ~ ~ 0 45` - facing south below the horizon
- `/tp @s ~ ~ ~ 45 0` - facing south-west at the horizon
- `/tp @s ~ ~ ~ -135 -90` - facing north-east, directly upwards
