### ISSUE TITLE
It is saying my mods are incompatable in the console pls help me

### ISSUE THREAD

**Issue by felipe15y** [MinecraftForge/MinecraftForge#9322]
**Minecraft Version:** {Minecraft version}

**Forge Version:** {Forge version. *Version number, not latest/rb*}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this

 2. Then do that
 3. ...

**Description of issue:**
it said my mods are incompatable 
[crash-2023-01-27_13.19.46-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/10522033/crash-2023-01-27_13.19.46-client.txt)

**Comment by felipe15y** [comment]
can someone help me

**Comment by felipe15y** [comment]
Help me

**Comment by TheCurle** [comment]
Netherite Elytra's broke.

Now quit spamming our Github.
