### ISSUE TITLE
AutomaticEventSubscriber subscribes subclass' public listeners

### ISSUE THREAD

**Issue by dhyces** [MinecraftForge/MinecraftForge#9323]
**Minecraft Version:** At least 1.19.2

**Forge Version:** 44.1.5

**Steps to Reproduce:**
 1. Write abstract class with EBS class annotation and a public static listener method {Class1}
 2. Write concrete class extending prior abstract class with EBS class annotation {Class2}
 3. Breakpoint the method from Class1 and run so that the event is fired and backtrack the call stack to the post method. Viewing the listeners at this point reveals two listeners from the same method in each class

**Description of issue:**
Developers who are not expecting this to occur may find strange behavior. Is this expected behavior or should this be treated as a bug?

**Comment by LexManos** [comment]
First Wrong repo.
This is a intentional behavior. and was requested to be this way by people in the community. Dont have that discussion off hand. But it was requested and has been this way from atleast 4 years ago.
