### ISSUE TITLE
Decoupling the server monitoring panel so that the forge server no longer depends on jre with its graphics library.

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MinecraftForge/MinecraftForge#9324]
As an example: ftb's server integration package will be built using Forge server, and will **still crash** if run with server jre, even if the monitoring panel is turned off using the option.

This panel has caused problems for many people running Forge server for the first time in a linux distribution, and hopefully this feature can be removed from the core and added as a mod to the mods directory by default.

Translated by DeepL, my English is difficult to speak, sorry.

**Comment by marchermans** [comment]
This is not a Minecraft Forge issue but an FTB issue. Please report it to them
