### ISSUE TITLE
[Bug] Step height isn't canceled when sneaking

### ISSUE THREAD

**Issue by INooBTooMuch** [MinecraftForge/MinecraftForge#9330]
**Minecraft Version:** {1.18.2}

**Forge Version:** {40.2.0}

**Logs:** {I don't think is needed...}

**Steps to Reproduce:**
 1. Have step height on an armor piece (I use [Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis) for the affix and in their github it's mentioned that they use the normal Forge step height so I'm making the report here.)
 2. Move while holding shift (crouching) in front of a block. (Also works while moving backwards)

**Description of issue:**
As the title says step height still "happens" even if the player is crouching.
I don't know if this should be a feature request or if its intended but it really isn't helping and I think it makes it worse by not being controllable.

**Comment by tmvkrpxl0** [comment]
I believe this is intentional as in vanilla, sneaking doesn't prevent going up slab/staircases

**Comment by INooBTooMuch** [comment]
Then I would like to recommend this as a feature because its annoying under certain circumstances (mining, building and maybe others)

**Comment by KnightMiner** [comment]
Worth noting that while it's quite a bit of work to make sneak dependant attributes, it is possible for that to be done on the mod side. Would be a bit easier on forges side to use a flat value of sneaking

**Comment by Shadows-of-Fire** [comment]
@sciwhiz12 @TheCurle Do we want to change the sneak behavior to use a flat step-height (0.5b) when sneaking?  Or do we maintain the current behavior (step-height is normal while sneaking) and close this as a non-issue?

**Comment by sciwhiz12** [comment]
We can probably switch to a flat value for the step height when sneaking. If we decide to in the future, we could switch to _two_ attributes: (the current) one for an always-applied value and (a new) one that's applied only when not sneaking.

**Comment by LexManos** [comment]
If you modify you step height, then you modify your step height. There is no reason besides a player's false assumption to add a special case for sneaking. If a modder wishes to add that as a feature to whatever they have in their mod, that adjusts step height. They have the necessary hooks to do it on their end.
