### ISSUE TITLE
[1.16.5 Bug] Entities with multiple hitbox cannot be hit

### ISSUE THREAD

**Issue by GoldenTotem** [MinecraftForge/MinecraftForge#9349]
**Minecraft Version:** 1.16.5

**Forge Version:** 36.2.39

**Description of issue:**
Entities with multiple hitboxes cannot be hit. For example, twilightforest: hydra or twilightforest: naga or alexsmobs: cachalot_whale cannot be hit by weapons (ender dragon is ok), they can only be damaged by projectiles such as arrows.
**If I change forge to 36.2.35, this problem disappeared.** It only occurs in 36.2.39

**Comment by sciwhiz12** [comment]
The version you are using is no longer supported. Please update to a modern version of Minecraft to receive support. Currently supported versions are 1.19.3 (Latest), 1.19.2, and 1.18.2 (LTS).

In addition: we use the issue tracker exclusively for final bug reports and feature requests. Please direct all requests for support to the [Forge Support Forums](https://forums.minecraftforge.net/) or [Forge Discord](https://discord.gg/forge).
