### ISSUE TITLE
1.19.3 Bug.  Cancelling Break of Spawner Block  Not Working Properly (works in 1.18.2)

### ISSUE THREAD

**Issue by mactso** [MinecraftForge/MinecraftForge#9353]
When breaking a spawner (for example, a Skeleton Spawner) 

and cancelling the BlockBreak event by setting the event.setCancelled(true) 

the spawner incorrectly begins to display as a pig spawner (tho it still spawns the correct mob).   

Leaving the area and returning restores proper appearance.   Logging out and logging back in restores proper appearance.

We tested this code in 1.18.2 and it works correctly.  The broken spawner cage does not become a pig spawner.

This may affect other block entities that display based on CompoundTags.

**Comment by mactso** [comment]
FYI, this is a pig spawner in 1.19.2, or an empty spawner in 1.19.3 .   

I was using code that runs in 1.19.X so didn't notice this behavior change in 1.19.3 right away.

**Comment by LexManos** [comment]
This is one of the many desyncs that can happen if the client and server disagree on the block break event. From what you describe this is expected behavior with a minor graphical issue. Not something that we really care about. We roll back all the information we can.
