### ISSUE TITLE
[1.19.4] Custom Payload Packets don't work inside of Bundled Packets

### ISSUE THREAD

**Issue by shedaniel** [MinecraftForge/MinecraftForge#9390]
**Minecraft Version:** 1.19.4

**Forge Version:** 45.0.6

**Description of issue:**
1.19.4 added a new type of packet (`BundlePacket`), all packets inside the bundled packet are handled on the main Minecraft client thread:
![image](https://user-images.githubusercontent.com/34910653/225593966-37bab3d6-f0ed-4846-8e47-68668ea0887b.png)

However, `handleCustomPayload` by Forge checks `isSameThread` before passing it to the NetworkHooks custom payload method, so all packets inside of the bundle packets do not work properly:
https://github.com/MinecraftForge/MinecraftForge/blob/7e6c8351c3578819b236908af95a1e44c3b2686c/patches/minecraft/net/minecraft/client/multiplayer/ClientPacketListener.java.patch#L75

**Steps to Reproduce:**
 1. Minecraft Entities `getAddEntityPacket` is now bundled in vanilla
 2. Return a custom payload packet in the `getAddEntityPacket` method
 3. Watch it get ignored

**Comment by LexManos** [comment]
Just removed the filter, it serves no purpose. As long as modders mark their packet as handled, then it'll all work fine.

https://github.com/MinecraftForge/MinecraftForge/commit/31e73355c310430ce1816009895b3eff1b5f5fc4

**Comment by Matyrobbrt** [comment]
Closed by https://github.com/MinecraftForge/MinecraftForge/commit/31e73355c310430ce1816009895b3eff1b5f5fc4
