### ISSUE TITLE
[1.19.4] Vanilla Tool Tags

### ISSUE THREAD

**Issue by PepperCode1** [MinecraftForge/MinecraftForge#9393]
1.19.4 added the following item tags.
- `#minecraft:tools`
- `#minectaft:axes`
- `#minecraft:hoes`
- `#minecraft:pickaxes`
- `#minecraft:shovels`
- `#minecraft:swords`

Forge adds the following equivalent tags.
- `#forge:tools`
- `#forge:tools/axes`
- `#forge:tools/hoes`
- `#forge:tools/pickaxes`
- `#forge:tools/shovels`
- `#forge:tools/swords`

Forge also adds the following additional tool tags.
- `#forge:tools/shields`
- `#forge:tools/bows`
- `#forge:tools/crossbows`
- `#forge:tools/fishing_rods`
- `#forge:tools/tridents`

Since vanilla added six equivalent tool tags, I think those Forge tags should be deprecated and the vanilla tags should be modified to include the equivalent Forge tags until they are removed.

The vanilla `#minecraft:tools` tag includes the other five tags, along with the trident, but not shields, bows, crossbows, or fishing rods. It should be decided whether or not it is appropriate to add those to the vanilla tag as well. If not, the Forge `#forge:tools` tag could act as an extended tools tag, which would contain the vanilla `#minecraft:tools` tag along with the additional tool tags that Forge adds.

One thing to consider is that the Forge tool tags which do not have vanilla equivalents are not consistently named with the vanilla tool tags.

**Comment by ModernGamingWorld** [comment]
I think this would be a good idea to do, as then we don't have Mod Developers having multiple tags for the same thing. it doesn't make sense to me to have forge keep their tool tags when we can just use Minecraft that is provided for us

**Comment by warjort** [comment]
The `#minecraft:tools` item tag is 1.20's default definition of `#minecraft:breaks_decorated_pots`
Adding shieds, bows and fishing rods would mean different behaviour compared to vanilla.

**Comment by LexManos** [comment]
Forge's stance is that tags are for recipes only. Mojang likes to mix it into game logic. So we'll be keeping our top level tools tag. I'll deprecate the other tags.
