### ISSUE TITLE
[1.19.4] Unenchanted leggings have enchantment glint on wearer entity

### ISSUE THREAD

**Issue by Dejeh** [MinecraftForge/MinecraftForge#9394]
**Minecraft Version:** 1.19.4

**Forge Version:** 45.0.9

**Steps to Reproduce:**
 1. make world
 2. wear pant

**Description of issue:**
ALL items of armor type leggings have an enchantment glint when equipped.

**Comment by sciwhiz12** [comment]
Confirmed on 1.19.4-45.0.10. In addition to the leggings always showing the enchantment glint (or as the game code calls it, the enchantment foil), all other armor pieces will never show the glint, even if they're enchanted.

---

[The patch to `HumanoidArmorLayer#renderArmorPiece`](https://github.com/MinecraftForge/MinecraftForge/blob/d552ce5eac046c3d8bc3dc1f13b1a19aebd7c6ae/patches/minecraft/net/minecraft/client/renderer/entity/layers/HumanoidArmorLayer.java.patch#L17-L23) passes the wrong boolean parameter to `renderModel`. Vanilla passes the `flag` variable, which is set to `ItemStack#hasFoil()`; Forge's patch passes the `flag1` variable, which is set to `HumanoidArmorLayer#usesInnerModel(EquipmentSlot)`, which currently returns `true` if the slot is for leggings, explaining the aforementioned behavior.

The solution is to change the passed variable from `flag1` (`#usesInnerModel`) to `flag` (`ItemStack#hasFoil()`).
