### ISSUE TITLE
ForgeSlider uses wrong textures

### ISSUE THREAD

**Issue by HyCraftHD** [MinecraftForge/MinecraftForge#9405]
**Minecraft Version:** 1.19.4

**Forge Version:**  45.0.13

**Steps to Reproduce:**
 1. Create an menu screen with a ``net.minecraftforge.client.gui.widget.ForgeSlider``
 2. Open the menu screen
 3. Try to drag the slider
 4. Draging doesn't work for the slider, only clicking

[Small reproduction mod here](https://gist.github.com/HyCraftHD/c1a08880aa278d1a9482b22db337b9f0)
[Video](https://user-images.githubusercontent.com/7681220/226441255-abdbee8d-7adb-46ae-bb58-9ee10f494398.mp4)

**Description of issue:**
Slider does not work in AbstractContainerScreen.
The issue seems to be that AbstractContainerScreen overrides the method mouseDragged without a super call to handle widget dragging.

**Comment by Matyrobbrt** [comment]
The fact that widgets with custom with custom dragging implementations do not work in `AbstractContainerScreen` is not specific to `ForgeSlider` and is vanilla behaviour. If you want to support such widgets, override the method yourself.
The fact that the texture is wrong is true and I have created #9406 to fix that.
@autoforge title ForgeSlider uses wrong textures
