### ISSUE TITLE
Can't pickup other playersdropped items - 1.19.4 Multiplayer

### ISSUE THREAD

**Issue by warjort** [MinecraftForge/MinecraftForge#9412]
**Minecraft Version:** 1.19.4

**Forge Version:** 
45.0.9 - tested by me
45.013 - originally reported in the forums:
https://forums.minecraftforge.net/topic/122222-cant-pickup-other-players-dropped-items

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
n/a

**Steps to Reproduce:**
 1. In multiplayer throw an item to another player
 2. The other player can't pick it up
 3. Leave the game
 4. The other player can pick it up

**Description of issue:**
Item pickup not working in multiplayer

I would guess there is some issue with this new code?
https://github.com/MinecraftForge/MinecraftForge/blob/44c689f1712fcfb7ccb13262d1c02f0a880055be/patches/minecraft/net/minecraft/world/entity/item/ItemEntity.java.patch#L117

**Comment by XFactHD** [comment]
Known issue, see this PR: https://github.com/MinecraftForge/MinecraftForge/pull/9404.
The specific line you referenced is not the cause.
