### ISSUE TITLE
[1.19.4] Mostly redundant datapack reload on world creation screen

### ISSUE THREAD

**Issue by embeddedt** [MinecraftForge/MinecraftForge#9413]
**Minecraft Version:** 1.19.4

**Forge Version:** 45.0.22

**Logs:** N/A, explanation below

**Description of issue:**

In https://github.com/MinecraftForge/MinecraftForge/pull/8693, a patch was added to `CreateWorldScreen` that forceloads mod-provided datapacks immediately after the world creation screen is opened. However, this patch introduces a performance penalty when compared to vanilla, as it requires reloading server resources twice, once during the vanilla codepath and then once when Forge calls `tryApplyNewDatapacks`.

Based on the discussion in that PR, the reason for the double reload is that there need to be fallback resources in the event that modded datapacks fail to apply. However, that condition only occurs if there is actually an error within the mod datapack. In most cases, the datapack will load without issues, and so the first reload is a complete waste of time.

**Suggested fix:**

Rather than requiring world creation to perform two datapack reloads (each of which can cost 20-30 seconds), the patch should ensure that modded datapacks immediately get loaded on the first reload. If and only if they fail to load, a patch should be added that then loads the fallback resources the way vanilla would. This will avoid needlessly doing an extra reload most of the time.

**Comment by LexManos** [comment]
The problem is you can't reactively reload the datapacks from an exception that can happen anywhere in Mod/Minecraft code.
If you think there is a method to actually accomplish what you've requested feel free to try and implement it.
The 'double' load is sadly nessasary in all tests that I have looked at because of how Mojang access the data.
