### ISSUE TITLE
[1.19.4] ScreenEvent.Init not firing on window resize

### ISSUE THREAD

**Issue by tom5454** [MinecraftForge/MinecraftForge#9418]
**Minecraft Version:** 1.19.4
**Forge Version:** 45.0.22 (Development Enviroment)

Example code:
```java
@SubscribeEvent
public void initGui(ScreenEvent.Init.Post evt) {
	if(evt.getScreen() instanceof TitleScreen) {
		Button btn = Button.builder(Component.literal("Button!"), b -> {}).bounds(0, 0, 100, 20).build();
		evt.addListener(btn);
	}
}
```
The button disappears when the window is resized. It shows up again if you open any other menu and come back.
The `resize` method in Screen no longer calls the `init(mc, w, h)` method, and won't fire the event.

**Comment by ChampionAsh5357** [comment]
This one is a bit weird as some `Screen` subtypes call `init` on `resize` (e.g. `AnvilScreen`) while others do not.

**Comment by rikka0w0** [comment]
Screen.init should be called when the screen is created and resized. I'm 99% sure this is a bug.

**Comment by warjort** [comment]
In 1.19.3 `Screen.resize()` did a full reinit of the screen which fires the forge `Init.Pre/Post` events.

In 1.19.4 Mojang changed it so it now only does a `repositionElements()`/`rebuildWidgets()` in most screens.
There are a few exceptions that use the old logic like the `AnvilScreen` mentioned above.

Without the full init call all the modded widgets will be removed by `rebuildWidgets()` but no Init events will be fired.

**Comment by warjort** [comment]
`rebuildWidgets` does invoke the overridable screen init() method but not the full init.

Also, the `ScreenEvent.Init.Pre` is now invoked *after* the overridable screen `init()` during the full init method which looks wrong? In 1.19.3 it was *before* the `init()` invoked from `rebuildWidgets()`.
