### ISSUE TITLE
[1.19.4] Food gives double the intended saturation

### ISSUE THREAD

**Issue by Cinex20** [MinecraftForge/MinecraftForge#9422]
**Minecraft Version:** 1.19.4

**Forge Version:** 45.0.25

**Steps to Reproduce:**
 1. Take enough damage to lose hunger.
 2. Eat any food item, like cooked chicken.
 3. Observe the amount of health regained (or saturation with AppleSkin installed).

**Description of issue:**
All edible items restore twice as much saturation as they're supposed to. This is especially noticeable with medium tier food like cooked chicken or mutton, where eating them restores about as much saturation as higher tier food, such as cooked pork or golden carrots. The difference is very easy to see with the AppleSkin mod installed.

**Comment by alcatrazEscapee** [comment]
Oh look, a patch that duplicates a line. Can you guess which line?

https://github.com/MinecraftForge/MinecraftForge/blob/ae65f5a255b29851d746ecc9cbd03671c31cdfb8/patches/minecraft/net/minecraft/world/food/FoodData.java.patch#L4-L8

Correct! It's the line in `FoodData.eat()` which sets `saturationLevel`!
