### ISSUE TITLE
Discord link

### ISSUE THREAD

**Issue by MrBunnyDc** [MinecraftForge/MinecraftForge#9425]
The discord link dont work(https://discord.gg/UvedJ9m), please update it or create a unlimited time link please.

**Comment by ChampionAsh5357** [comment]
Discord link works just fine.

**Comment by MrBunnyDc** [comment]
What? I cant join.
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/95694941/228326936-05675be7-51d7-4b19-b2cf-4c5dda228120.png">

**Comment by MrBunnyDc** [comment]
Oh, sorry. Is the account. Sorry.
