### ISSUE TITLE
[1.19.2] Experimental settings warning still occurs

### ISSUE THREAD

**Issue by NovaViper** [MinecraftForge/MinecraftForge#9427]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.2.0

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report} None

**Steps to Reproduce:**
 1. Download installer
 2. Run installer to install Forge
 3. Run Minecraft
 4. Create a new world
 5. Bug occurs

**Description of issue:**
Same issue from 1.18 and 1.19.3 (#8414 and #9272 respectively). Seems to be unfixed still in 1.19.2

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/1f44339d6ef80827910b8db11de4907611c082e4

**Comment by NovaViper** [comment]
Even on the latest build for 1.19.2 (43.2.8), it still occurs. Will there be a backport of v44.1 (the version that has the fix) to 1.19.2?

**Comment by ChampionAsh5357** [comment]
If somebody chooses to backport the PR, sure.
