### ISSUE TITLE
Forge server incompatible with Java 20

### ISSUE THREAD

**Issue by DenuxPlays** [MinecraftForge/MinecraftForge#9438]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.2.0

**Logs:** 

![image](https://user-images.githubusercontent.com/83671398/229346627-1ab06f3b-3f8b-449e-b91c-694d66ac48b0.png)

**Steps to Reproduce:**
 1. Upgrade Java to 20
 2. start the server or try

**Description of issue:**

The forge server is incompatible with java 20...

Note:
Java 19 is no problem.

**Comment by TheCurle** [comment]
This is a mixin error with Create (a mod) caused by Mixin (a library Forge depends on) throwing a class related error.. in what way does this relate to Forge not supporting Java 20?

It's the mod that's throwing the error, ask the mod developer.

**Comment by DenuxPlays** [comment]
> This is a mixin error with Create (a mod) caused by Mixin (a library Forge depends on) throwing a class related error.. in what way does this relate to Forge not supporting Java 20?
> 
> It's the mod that's throwing the error, ask the mod developer.

Ah okay
Than I'll contact the mod developer thank you :)
