### ISSUE TITLE
[1.18.2] NBSP issue with russian OS language

### ISSUE THREAD

**Issue by GinDoyr** [MinecraftForge/MinecraftForge#9464]
**Minecraft Version:** 1.18.2
**Forge Version:** 40.2.2

**Steps to Reproduce:**
 1. Make russian language the OS language
 2. Play mc with Draconic Evolution
 3. Look at the cost to make anything with the injectors (screenshot attached)
![image](https://user-images.githubusercontent.com/109394929/233858192-33225279-0eee-4204-817d-17e816e09066.png)

**Description of issue:**
Nothing more to describe. If you try to play with english OS language the comma/space appears as usual.
The problem didn't occur on the 1.12.2 version of mc

**Comment by AterAnimAvis** [comment]
Not a Forge issue, you'll need to raise this with DE/BrandonsCore.
- Minecraft doesn't support rendering `nbsp`
- Russian uses `nbsp` for thousands separator
- Draconic Evolution (or more specifically BrandonsCore) uses `DecimalFormat` without a Locale (in [`Utils`](https://github.com/Draconic-Inc/BrandonsCore/blob/master/src/main/java/com/brandon3055/brandonscore/utils/Utils.java#L42)) and as such picks up the System Locale of Russian.

They should either be using a fixed Locale, or handle normalizing the output.
