### ISSUE TITLE
[1.19.4] When Experimental Feature Enable. LootTable cannot be additionally assigned

### ISSUE THREAD

**Issue by baguchi** [MinecraftForge/MinecraftForge#9470]
**Minecraft Version:** 1.19.4

**Forge Version:** 45.0.47

**Logs:** none

**Steps to Reproduce:**
 1. Start Game with LootTable Modifiring mod
 2. Create World with Experimmental Feature
 3. do the loot command
 4. LootTable has been replaced with the experimental feature LootTable. not add mod loot table one.(Even mod add those LootTable)

**Description of issue:**

I noticed this when I was modding EarthMobs
In fact, you may think that this is too much to worry about, but I felt that this could cause problems when playing mods and vannila's experimental features at the same time, so I open the issue.

**Comment by sciwhiz12** [comment]
Whoops. Mislabelled -- I was on the wrong tab.

Please provide more clear instructions. Specifically, provide a minimal[^1] example -- datapack, source repository -- of the issue, as well as the expected behavior and the current (erroneous) behavior.

[^1]: What I mean by minimal is the minimum amount of files required to reproduce the issue and nothing more. This means we will _not_ accept whole published (content) mods as minimum examples.

**Comment by baguchi** [comment]
To put it simply, by enabling the built-in datapack (experimental) from the beginning, it will overwrite the vanilla loot_table containing the original mod loot_table
My suggested solution is to adapt the source code here to experimental datapack

https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/patches/minecraft/net/minecraft/world/level/storage/loot/LootTables.java.patch#L9
```
LootTable loottable = net.minecraftforge.common.ForgeHooks.loadLootTable(f_79189_, p_79198_, p_79199_, res == null || !res.m_215506_().equals(net.minecraft.server.packs.repository.BuiltInPackSource.f_243761_), this);
```

**Comment by CombatReq** [comment]
![image](https://github.com/MinecraftForge/MinecraftForge/assets/149759574/a048c3ef-fbcd-4e83-9d02-a31ada763d50)

**Comment by baguchan** [comment]
Don't post WORST PICTURE EVER ON MY POST

**Comment by CombatReq** [comment]
![image](https://github.com/MinecraftForge/MinecraftForge/assets/149759574/fe368d15-d9d1-4f86-b3b4-f2d513b7c733)
мне поебать

**Comment by LexManos** [comment]
fucking spammers
