### ISSUE TITLE
DeferredRegister for Attributes not working correctly

### ISSUE THREAD

**Issue by lab3** [MinecraftForge/MinecraftForge#9509]
**Minecraft Version:** 1.18.2

**Forge Version:** 1.18.2-40.2.0

Crash Log: https://gist.github.com/lab3/e4aa578e4a78f5df16edba497ed9638c

**Steps to Reproduce:**
Crash on game launch

**Description of issue:**

I'm registering an attribute using a DeferredRegister
```java 
public class AttributeRegistry {

    private static final DeferredRegister<Attribute> ATTRIBUTES = DeferredRegister.create(ForgeRegistries.ATTRIBUTES, IronsSpellbooks.MODID);

    public static void register(IEventBus eventBus) {
        ATTRIBUTES.register(eventBus);
    }

    public static final RegistryObject<Attribute> COOLDOWN_REDUCTION = ATTRIBUTES.register("cooldown_reduction", () -> (new RangedAttribute("attribute.irons_spellbooks.cooldown_reduction", 1.0D, -10.0D, 10.0D).setSyncable(true)));
}
```

Then I'm registering an item that uses that attribute.
```java
public class ItemRegistry {
    private static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, IronsSpellbooks.MODID);

    public static void register(IEventBus eventBus) {
        ITEMS.register(eventBus);
    }

    public static final RegistryObject<Item> NETHERITE_SPELL_BOOK = ITEMS.register("netherite_spell_book", () -> new SimpleAttributeSpellBook(10, SpellRarity.LEGENDARY, AttributeRegistry.COOLDOWN_REDUCTION.get(), .20));
}
```

In the mod setup both of these are being registered
```java
IEventBus modEventBus = FMLJavaModLoadingContext.get().getModEventBus();
AttributeRegistry.register(modEventBus);
ItemRegistry.register(modEventBus);
```

When launching the game it crashes with a 
Failure message: Iron's Spells 'n Spellbooks (irons_spellbooks) encountered an error during the common_setup event phase
		java.lang.NullPointerException: Registry Object not present: irons_spellbooks:cooldown_reduction

We are back porting our mod from 1.19.2 to 1.18.2 and this approach is working fine in 1.19.2 .  Any idea what the issue might be in 1.18.2?

**Comment by ChampionAsh5357** [comment]
This is just an issue with your code. You're assuming attributes will be registered before items, which is not the case depending on the version. You should be storing a supplied instance instead of resolving it. You can ask for any additional help on the forums or the discord.
