### ISSUE TITLE
Allow Players to Put the Mods Folder in the Minecraft Forge Profile

### ISSUE THREAD

**Issue by TimberStalker** [MinecraftForge/MinecraftForge#9511]
I dont know how well I worded the title, but can we have a feature that will check for mods in the current active minecraft profile folder rather than the root minecraft directory? The current way makes it much harder for people to have different sets of mods for different versions or even different modpacks for the same version. Allowing players to put mods in the specific profile will make it much easier. No more copying the minecraft folder, no more moving swapping the mods folder to the correct one, just select the correct profile, and youre good. If you would like to preserve backwards compatibility, just have it check in the root folder if it cant find anything in the profile. I feel like this would be pretty easy to implement for anyone who knows the forge codebase (I looked into it to see if I could change it but its too convoluted for someone who hasnt seen it before). I dont know if theres some weird issue thats preventing this from being implemented, but the work to player satisfaction ratio would be insane if this simple change was made.

**Comment by PlatinPython** [comment]
You can just change the game directory in the profile settings and use any folder you want, which will keep mods and the like separate from other profiles.

**Comment by sciwhiz12** [comment]
I don't know what you're getting at, here.  As @PlatinPython says: In the Minecraft launcher, an installation (commonly called a profile, but I'll use the official launcher term here) may be configured to use a game directory different from the `.minecraft` game directory.

An installation with a different game directory is completely separate from any other installation with a different game directory. Forge will automatically honor this configured game directory, and only load from the `mods` folder under the game directory of the active installation.

We will not natively implement a feature which would allow mods to be loaded from a directory other than that under the game directory (of the active installation)[^modlocator]. Users are free -- and are indeed recommended -- to use a modpack manager, such as [CurseForge](https://www.curseforge.com/) or other publicly available ones, to manage mods for them in separate profiles/modpacks, automatically launching the official Minecraft launcher with preconfigured installations and the appropriate _separate_ game directory.

[^modlocator]: Mods may provide their own custom mod locators, which allow discovery of mods during runtime in other places as the mod may deem necessary, but that is up to mod developers and users to make and install.
