### ISSUE TITLE
Disabling modList handshake

### ISSUE THREAD

**Issue by kahveciderin** [MinecraftForge/MinecraftForge#9512]
https://wiki.vg/Minecraft_Forge_Handshake According to this, Forge sends the modlist to the server, when the server claims that it's a forge server. I want to disable this. I know this might cause problems when joining to a modded server, but if I am joining to a vanilla server and don't want the server to know the mods I have, afaik there isn't a way to do that.

My use case for that is I'm a member of a private SMP. They have a mod allowlist, and basically only optifine is on the list. The issue is that I want to run shader mods, replay mod etc, but the mod allow list doesn't have that, so I can't.

If there was a way to spoof the modlist handshake with the server and say that I don't have any mods installed, this would work. Again, I know this would cause issues when connecting to a Forge server with mods, in that case I think with this option enabled, it should fail to connect, but just spoofing the modlist to have no mods installed should be fine for vanilla servers that claim to be Forge just to get the modlist & check.

**Comment by TelepathicGrunt** [comment]
If the server owners only allow Optifine, don’t go against their wish and try to push through with mods that they may consider cheating or disallowed. Instead of trying to remove a feature that helps against cheaters, why don’t you contact the server owners and try to get them to allow the mods you want?

**Comment by Matyrobbrt** [comment]
The absence of the mod list in the handshake packet can facilitate cheating, as such, Forge will not add the option of removing it. 
In your case, if you're purely wanting to use shader or replay mods, speak to the server owner to add them to the whitelist.
