### ISSUE TITLE
Apply SymLink warning introduced in 1.20-vanilla to lower versions

### ISSUE THREAD

**Issue by teddyxlandlee** [MinecraftForge/MinecraftForge#9517]
As [Minecraft 1.20-pre7](https://www.minecraft.net/en-us/article/minecraft-1-20-pre-release-7) releases, it shows a warning screen when opening a world containing symbolic link.

[This official help article](https://aka.ms/MinecraftSymLinks) shows the necessity to apply this warning screen.

I've written an implementation for 1.19.4 (Fabric) in MojMaps [here](https://github.com/Featurehouse/symlink-check).

Wish you can implement this fix to lower versions like 1.19.x and 1.12.x.

Thank you.

**Comment by ChampionAsh5357** [comment]
Reading the article itself, Mojang does nothing to stop it besides provide a warning. It seems to be mostly to combat users who download worlds and run them without inspection. Mojang has not deemed it necessary to backport to previous versions, hence their statement 'starting with version 1.20'. As such, I don't see a reason for Forge to implement this themselves as it'll only provide guards to users who are using Forge and not the previous versions as a whole. Additionally, if Forge were to support it, it would only be added for the current latest and LTS, which wouldn't make much of a difference in the long run.

If a mod wanted to backport the feature, they are welcome to.
