### ISSUE TITLE
Uniform font rendering does not work in Forge 46.0.1 (1.20)

### ISSUE THREAD

**Issue by JDDev0** [MinecraftForge/MinecraftForge#9524]
**Minecraft Version:** 1.20

**Forge Version:** 46.0.1

**Logs:** *Not applicable*

**Steps to Reproduce:**
 1. Execute give command: `/give @p written_book{title:"",author:"",pages:['{"text":"test","font":"uniform"}']} 1`
 2. Open Book
 3. Font does not render correctly

**Description of issue:**
Only the font placeholder characters are displayed instead of the of uniform characters (Works in Vanilla though)

*Vanilla*:
![grafik](https://github.com/MinecraftForge/MinecraftForge/assets/37939362/cf2009ce-aa39-4030-8321-74d419df69ad)

*Forge*:
![grafik](https://github.com/MinecraftForge/MinecraftForge/assets/37939362/2be643e2-9df4-43b6-af69-b1153b91e274)

**Comment by ChampionAsh5357** [comment]
Unable to verify in Forge 1.20 with the example provided. Even unicode characters seem to work fine.

![image](https://github.com/MinecraftForge/MinecraftForge/assets/19510740/6b7c0cce-25e5-4a4c-97cb-e542ed43fd53)

![image](https://github.com/MinecraftForge/MinecraftForge/assets/19510740/8439bf4e-0f2a-4447-be5c-2c24eddff7a2)

**Comment by JDDev0** [comment]
I have managed to fix it by executing the `genIntellijRuns` task again.
