### ISSUE TITLE
(1.20) Weird lighting behavior

### ISSUE THREAD

**Issue by thexaero** [MinecraftForge/MinecraftForge#9527]
**Minecraft Version:** 1.20

**Forge Version:** 46.0.1

**Steps to Reproduce:**
 1. Place regular torch.
 2. Break torch.
 3. The blocks stay lit.

OR

 1. Place a redstone lamp first.
 2. Place a redstone block next to it, or power the lamp with redstone otherwise.
 3. Nothing is being lit.

**Description of issue:**
The block lighting doesn't update when breaking torches or using redstone to power light sources.
Works fine for glowstone or when placing a redstone lamp into a position which is already powered.

**Comment by justliliandev** [comment]
looks like a wrong patch in LightEngine. 
https://github.com/MinecraftForge/MinecraftForge/blob/09de4a2dcca0b48dba163b8571d7fd95f6998411/patches/minecraft/net/minecraft/world/level/lighting/LightEngine.java.patch#L8
it tries to compare the lightEmission with level and pos context, but it compares getLightEmission with getLightBlock, fixing this solves this problem
