### ISSUE TITLE
(1.20) Enchanting Table screen crash.

### ISSUE THREAD

**Issue by Zeitheron** [MinecraftForge/MinecraftForge#9543]
**Minecraft Version:** 1.20

**Forge Version:** 46.0.2

**Crash report:** https://pastebin.com/5uJSwwuE
**That same crash report, but in dev env, so all method names are more readable:** https://pastebin.com/L2x949gi

**Steps to Reproduce:**
 1. Open Enchanting Table
 2. Put any enchantable item in the slot
 3. ...crashed.

**Description of issue:**

The issue may arise from a weird remapping issue here: `this.menu.enchantClue[i1]`.
Instead of `i1` the variable here should be `l` (lowercase `L`) that is located in the `for(int l = 0; l < 3; ++l)` of `renderBg`
This is not an issue with non-modded game, and when installing forge (ONLY, no other mods were installed), this issue began to occur.

**Comment by Kathaxeuh** [comment]
Yeah I have the same problem kinda boring if someone could help us

**Comment by ChampionAsh5357** [comment]
The PR has been assigned to core. They will review and pull or send back for revision whenever they have time.
