### ISSUE TITLE
[1.20] Game without mods is crashing when trying to enchant an item

### ISSUE THREAD

**Issue by florian-berger** [MinecraftForge/MinecraftForge#9545]
**Minecraft Version:** 1.20

**Forge Version:** 46.0.2

**Logs:** [Forge 46.0.2: Enchanting Table Crash](https://gist.github.com/florian-berger/61e471edb12e56eeb18b1c60bc506779)

**Steps to Reproduce:**
 1. Place an enchanting table
 2. Place 18 bookshelfs around it (form of an "u")
 3. Right-click crafting table
 4. Put a diamond sword into the corresponding slot

**Description of issue:**
When you want to enchant an item, the game is crashing with the linked log. To make sure it's not crashing from an external mod, I removed all mods, created a new world and reproduced the issue. 
In Minecraft 1.20 Vanilla, it's possible to enchant a item without any problems.

**Comment by XFactHD** [comment]
Fixed by #9544, a new version including that is building right now.

**Comment by mpbb** [comment]
I had the same issue. Just placing a bow in the enchanting table crashes the game. Looking forward to the new build

**Comment by XFactHD** [comment]
46.0.10 finished building a few minutes ago.

**Comment by mpbb** [comment]
Confirmed working properly on forge 46.0.10 for me. Thanks!
