### ISSUE TITLE
(1.20) bug: all leggings always render with an enchantment glint

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [MinecraftForge/MinecraftForge#9546]
**Minecraft Version:** 1.20

**Forge Version:** 46.0.10

Wearing any pair of leggings will cause them to appear enchanted. This is caused by a what I can assume is a porting error in `HumanoidArmorLayer`. 
https://github.com/MinecraftForge/MinecraftForge/blob/1.20.x/patches/minecraft/net/minecraft/client/renderer/entity/layers/HumanoidArmorLayer.java.patch#L19-L23

The `flag` boolean that is passed into `renderModel` checks if the piece of armor uses the inner model, but that boolean is later used to decide whether the piece of armor in question should render enchanted through `ItemRenderer.m_115184_` (`ItemRenderer.getArmorFoilBuffer`), causing leggings to always appear enchanted.

**Comment by ChampionAsh5357** [comment]
Yeah, basically we need to update the implementation to match with vanilla now.
