### ISSUE TITLE
When the player is affected by the effect of a potion, the F3 menu appears in the background of the potion's graphical interface.

### ISSUE THREAD

**Issue by Lolothepro** [MinecraftForge/MinecraftForge#9548]
**Minecraft Version:** 1.20/1.19.4/idk

**Steps to Reproduce:**
 1. Be affected by a potion
 2. Open the F3 menu
 3. Compare with Minecraft Vanilla

**Screenshot:**

Forge:
![2023-06-10_10 46 19](https://github.com/MinecraftForge/MinecraftForge/assets/68275908/3cd6954b-7ab8-454a-9a86-b5730a8f5bcc)

![image](https://github.com/MinecraftForge/MinecraftForge/assets/68275908/c65983d2-7eb7-41ee-8ba3-34425e3547d5)

Vanilla:
![2023-06-10_10 47 14](https://github.com/MinecraftForge/MinecraftForge/assets/68275908/717ab1e1-3e81-40b0-a1ba-a6e37de0d2f0)

![image](https://github.com/MinecraftForge/MinecraftForge/assets/68275908/736835ed-c4c7-4988-a767-c021b69da72a)

**Comment by ChampionAsh5357** [comment]
It seems like the order of vanilla gui overlay renderers has changed, so it's just a matter of reordering them.
