### ISSUE TITLE
experimentalForgeLightPipelineEnabled breaks the light emitted by Sculk Sensors 

### ISSUE THREAD

**Issue by Lolothepro** [MinecraftForge/MinecraftForge#9552]
**Minecraft Version:** 1.20

**Forge Version:** 46.0.12

**Steps to Reproduce:**
 1. Use Sculk Sensors with experimentalForgeLightPipelineEnabled
 2. Use Sculk Sensors without experimentalForgeLightPipelineEnabled
 3. Compare

**Screenshot:**

With:
![image](https://github.com/MinecraftForge/MinecraftForge/assets/68275908/e204026f-d16a-4fd8-afb2-629bd3be76a4)
Without:
![image](https://github.com/MinecraftForge/MinecraftForge/assets/68275908/bcb47c1b-26d0-4385-81ff-87cdaf549cf2)

**Comment by XFactHD** [comment]
Can confirm, the experimental light pipeline completely breaks emissive rendering (specifically the way Mojang implemented it, the way Forge's model extension does it by baking the lighting into the vertex data works fine) on faces on the outer bound of the block. This therefore also applies to the Magma Block:

Experimental pipeline enabled:
![2023-06-10_23 18 25](https://github.com/MinecraftForge/MinecraftForge/assets/11262040/ecf542a0-458d-47d4-83bf-05480a6d95ff)

Experimental pipeline disabled:
![2023-06-10_23 19 18](https://github.com/MinecraftForge/MinecraftForge/assets/11262040/015fac80-b3f9-42e2-8548-6b123f60349a)
