### ISSUE TITLE
Entangled block crashes client when paired with Modern Industrialization energy source

### ISSUE THREAD

**Issue by Shoki17** [MinecraftForge/MinecraftForge#9560]
**Minecraft Version:** {1.19.2}

**Fabric Version:** {Fabric version. *0.76.0}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Place entangled block adjacent to MI machine you wish to power and link to turbine or storage unit.
 2. Wait for about 5 minutes and crash occurs.
 3. Upon trying to load into the world again, a crash will always occur with the entangled block showing on the crash report as the culprit.

**Description of issue:**
[crash-2023-06-11_17.42.43-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/11715983/crash-2023-06-11_17.42.43-client.txt)

**Comment by zml2008** [comment]
hey @Technici4n i think someone got lost

**Comment by 0xilly** [comment]
Not a forge issue
