### ISSUE TITLE
forge-1.19.2-43.2.14-installer can't open file selection window

### ISSUE THREAD

**Issue by Henryxjh** [MinecraftForge/MinecraftForge#9561]
**Minecraft Version:** not with minecraft

**Forge Version:** 1.19.2-43.2.14

**Logs:** [forge-1.19.2-43.2.14-installer.jar.log](https://raw.githubusercontent.com/Henryxjh/Henryxjh.github.io/main/forge-1.19.2-43.2.14-installer.jar.log)

**Steps to Reproduce:**
 1. Open the forge-1.19.2-43.2.14-installer
 2. press the "..." button to open the file selecter

**Description of issue:**
I can't open the file selection window. When I open the installer with powershell, it prints some error.

**Comment by TheCurle** [comment]
Our installer has a specific issue tracker. Use that.
