### ISSUE TITLE
Execution failed for task ':runClient'.

### ISSUE THREAD

**Issue by RobertSharp3662** [MinecraftForge/MinecraftForge#9567]
**Minecraft Version:** 1.20.1
**Forge Version:** 47.0.3

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Run the Client
 2. It fails

**Description of issue:**
I have freshly installed the new MDK for 1.20.1, but cannot run the client.
I have made no changes to the any of the files and am still using the unedited example mod.
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/11768955/latest.log)
[debug.log](https://github.com/MinecraftForge/MinecraftForge/files/11768964/debug.log)
[console_output.txt](https://github.com/MinecraftForge/MinecraftForge/files/11768992/console_output.txt)

**Comment by AterAnimAvis** [comment]
Your using outdated AMD drivers, updating to the latest "WHQL Recommended" (aka stable) version should fix your issue (<https://www.amd.com/en/support>).
If you have further issues please visit the forums or the discord

**Comment by PaintNinja** [comment]
Outdated AMD graphics drivers

It seems like you're on old, experimental beta drivers from 2022. Updating to the latest "WHOL Recommended" (aka stable) version should fix your issue.
https://www.amd.com/en/support
