### ISSUE TITLE
Cancelable EntityUpdateEvent

### ISSUE THREAD

**Issue by anti344** [MinecraftForge/MinecraftForge#958]
Why LivingUpdateEvent? Why not a whole EntityUpdateEvent for every entity in the world? I know, it'll be laggy, but you can split it like EntityItemUpdateEvent(the main reason i writing it), EntityThrowableUpdateEvent(arrows and snowballs), etc.

P. S. By EntityItemUpdateEvent i mean handling cancelable updates of every item in the world, not just mine(i know about that method in Item class).

**Comment by LexManos** [comment]
Still not convinced this is actually needed, And considering it is MASSIVE spam to the event bus it'd be nothing but a lag machine. 'Slowing' or 'Stopping' an entity shouldn't be to difficult you just grab it out of the update list for a while.
If you have actual issues and can show you've tried something let me know but I don't think this is nessasry.

**Comment by anti344** [comment]
Lol, since that time i've learned a lot =P
So now i know how to do stuff without submitting stupid issues, yay
