### ISSUE TITLE
[1.20.1-47.0.16] Loot Table Pool Names being enforced breaks nearly all mod's loot tables

### ISSUE THREAD

**Issue by TelepathicGrunt** [MinecraftForge/MinecraftForge#9589]
This PR here merged recently has broken loot tables for the overwhelming majority of mods out there on 1.20.1. https://github.com/MinecraftForge/MinecraftForge/pull/9573 

To reproduce, 

- Download 47.0.16 Forge. 
- Add any more with loot tables such as Repurposed Structures (repurposed_structures-7.0.0+1.20-forge). (can be loot tables for block, chest, entities...)
- Create any world.
- See errors in log about loot tables and now the loot tables will not spawn anything in the world. In Repurposed Structures, the structure chests will have no loot anymore.

Log file: [latest.log](https://github.com/MinecraftForge/MinecraftForge/files/11833858/latest.log)

![image](https://github.com/MinecraftForge/MinecraftForge/assets/40846040/9272105a-ac3f-42fb-9868-b289160c5005)

My Loot Tables: https://github.com/TelepathicGrunt/RepurposedStructures/tree/1.19.0-Forge/src/main/resources/data/repurposed_structures/loot_tables

**Comment by TelepathicGrunt** [comment]
To add more info, I make loot table files by hand. I do not use datagen and would rather not have to be forced to add a pool name that ultimately will go unused forever and provide no benefit for anyone with my mod. If I do have to add a pool name, I'll just whip up a python script to generate generic pool names like "1", "2", "3"...

**Comment by Commoble** [comment]
This doesn't just break mods, it makes any vanilla-targeted datapack with custom loot tables incompatible with forge

**Comment by lukebemish** [comment]
Also worth mentioning that, if I understand this right, this would prevent packaging many vanilla datapacks as lowcode mods without modification, which would be not great
