### ISSUE TITLE
Using [[feature.<modid>]] causes ClassCastException during modload

### ISSUE THREAD

**Issue by RogueLogix** [MinecraftForge/MinecraftForge#9600]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.0.16

**Steps to Reproduce:**
 1. Add this to mods.toml

> [[features.\<modid\>]]
>    openGLVersion="[3.3,)"

 2. Attempt to launch

**Description of issue:**

> Exception in thread "main" java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
> // truncated stack, internal stream impl stuffs
> 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.0.16/net.minecraftforge.fml.loading.moddiscovery.ModInfo.lambda$new$10(ModInfo.java:93)
>

**Comment by cpw** [comment]
OK. This is a simple fix. I made a mistake. the actual specification is
```
[feature.<modid>]
whatever=whatever
```
