### ISSUE TITLE
block breaking overlay flickers on campfire/sculk sensor/pointed dripstone/rail

### ISSUE THREAD

**Issue by Lolothepro** [MinecraftForge/MinecraftForge#9608]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.0.34

**Description of issue:**

## Expected Behavior

https://github.com/MinecraftForge/MinecraftForge/assets/68275908/078f2813-3625-419e-a484-02c202395a7b

## Actual Behavior

https://github.com/MinecraftForge/MinecraftForge/assets/68275908/d9b9b594-307b-402e-92d3-5b0aacaa693c

**Comment by marchermans** [comment]
Do you have the forge lighting pipeline enabled?

**Comment by LexManos** [comment]
I'm able to reproduce with it disabled. Clean ForgeDev.

**Comment by Lolothepro** [comment]
caused by https://github.com/MinecraftForge/MinecraftForge/commit/1936eb1f368d48dbda1ccb53f46a21dd8f497a9d

**Comment by LexManos** [comment]
Solved by https://github.com/MinecraftForge/MinecraftForge/pull/9664
