### ISSUE TITLE
FMLOnly doesn't work

### ISSUE THREAD

**Issue by Lolothepro** [MinecraftForge/MinecraftForge#9609]
[crash-2023-06-30_10.00.16-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/11914577/crash-2023-06-30_10.00.16-client.txt)

**Comment by cpw** [comment]
This
https://github.com/MinecraftForge/MinecraftForge/blob/1.20.x/fmlloader/src/main/java/net/minecraftforge/fml/loading/ImmediateWindowHandler.java#L136

Should not throw an exception 🤦

It's called by modloader, which is shared code. Returning "3.2" should be a safe choice always here. It's possible we could do more here as well.
