### ISSUE TITLE
The codes of Client Events was executed without judgment on the server

### ISSUE THREAD

**Issue by mlus-asuka** [MinecraftForge/MinecraftForge#9620]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.2.11

**Steps to Reproduce:**
 1. I changed codes in one mod that my server installed. For example.
 I wrote this 
![G)A5FD8(}6 `A$~I}I`Y4PW](https://github.com/MinecraftForge/MinecraftForge/assets/80941936/1ecba5b5-1874-401c-8b1a-a804b5e3a509)
into this event 
![UKOOKZG6{CF49C~2_FQBTQ8](https://github.com/MinecraftForge/MinecraftForge/assets/80941936/e64e2743-78f6-4017-bef4-83f8e28e71c6)
but the mod on server doesn't have it.
 2. Then join the server. just put your mouse on any item.
 3. You will found your inventory is filled by diamond.

**Description of issue:**
I guess this issue will happen to any other client events too. It is very dangerous if someone changes codes to cheat.

**Comment by AterAnimAvis** [comment]
That won't actually have any effect to the server, your experiencing client side desync, open any inventory and the server will force a resync.
