### ISSUE TITLE
Incorrect parameters IForgeDimensionSpecialEffects#adjustLightmapColors

### ISSUE THREAD

**Issue by FlashFyreMods** [MinecraftForge/MinecraftForge#9626]
Note that although these versions are correct, this issue is almost certainly on all newer and some older versions too, these are just the two I've checked.

**Minecraft Version:** 1.19.2, 1.20.1

**Forge Version:** {Forge version. 43.2.11, 47.0.35

**Description of issue:**
The "blockLight" parameter and the "skyLight" parameter names are the wrong way round.  Additionally, really the f9 variable in LightTexture#updateLightTexture should be passed in as blockLight instead of f7 but that isn't a big deal.

**Comment by LexManos** [comment]
So digging in a little bit, it does seem weird the variables that were chosen. But these are indeed the local variables that were captured in the [original PR](https://github.com/MinecraftForge/MinecraftForge/pull/8863). I would guess the following would be better:
```
f1 Sky Light
f7 Block Light
```
you can make f8/f9 with the i/j you are passed in.
Problem is changing the values that are passed in is a breaking change, does anyone actually use this hook?

**Comment by FlashFyreMods** [comment]
Luckily I did eventually realise I can make f9 using that way but one thing I'd say then is f7 being named blocklight is misleading as really it seems to be the flicker amount modified and f9 is the actual blockLight. Though like you say changing values is a breaking change and renaming parameters even more so. That being said from my experience it does seem like a hook that is pretty rarely used by modders. 

It's likely out of the scope of this issue but adding more of the variables as parameters may be useful for modders so they may not need to reconstruct as much logic if they want to adjust a particular aspect of the lightmap (e.g f3,  f4, f5). Whenever this issue is fixed it might make sense to do this at the same time...?

At the time of the original PR I don't think we looked much into the things that could be passed inc and only had the intention of getting the removed lightmap functionality (from 1.15 iirc) re-added.

**Comment by Jonathing** [comment]
> So digging in a little bit, it does seem weird the variables that were chosen. But these are indeed the local variables that were captured in the [original PR](https://github.com/MinecraftForge/MinecraftForge/pull/8863). I would guess the following would be better:
> 
> ```
> f1 Sky Light
> f7 Block Light
> ```
> 
> you can make f8/f9 with the i/j you are passed in. Problem is changing the values that are passed in is a breaking change, does anyone actually use this hook?

@FlashFyreMods and I use this hook pretty regularly in our project. I don't think it'd be a problem to create a new method with the correct parameters (i.e. by passing more in) and deprecating the old one. Let me know what you think.

**Comment by LexManos** [comment]
If you can keep bin compat and make it sane go for it.
