### ISSUE TITLE
[1.19.2] Advancement screen does'nt show buttoms to change pages

### ISSUE THREAD

**Issue by PabloRufianJimenez** [MinecraftForge/MinecraftForge#9628]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.2.14

**Steps to Reproduce:**
 1. Use datapack to add more than 26 advancements from different tabs in order to each more than the maximum amount of advancement tabs per page; a component will display saying "1/2"

**Description of issue:** No buttom to move from page to page appears when the maximum amount of advancement tabs per page is surpassed in the advancement screen.

**Comment by RealMangorage** [comment]
Can confirm that this is true

**Comment by Natesky9** [comment]
need to add super.render to render the renderables to the screen

**Comment by LexManos** [comment]
Fixed https://github.com/MinecraftForge/MinecraftForge/commit/03a505a3f2ac1327f8c94dcda6369d2693e81796
