### ISSUE TITLE
Exception_Access_Violation error

### ISSUE THREAD

**Issue by Awoken324** [MinecraftForge/MinecraftForge#9631]
**Minecraft Version:** 1.20

**Forge Version:** 1.20*47.1.0

**Logs:** 
[hs_err_pid9264.log](https://github.com/MinecraftForge/MinecraftForge/files/11995170/hs_err_pid9264.log)

**Steps to Reproduce:**
It's a segfault on the early loading screen.

**Description of issue:**
Unable to start

**Comment by MichaelHillcox** [comment]
To update this issue a little from our side (FTB). We've noticed a few users having these same issues with the early loading screen. We think it's something to do with the hardware. 

The issue has only started to present itself as of 1.20+

**Comment by PaintNinja** [comment]
Update your graphics drivers, you're using an old experimental beta version from last year. You want the one labelled "Recommended" - "Optional" is beta and doesn't auto-update.
https://www.amd.com/en/support

**Comment by Awoken324** [comment]
Thanks guys! Worked like a charm
