### ISSUE TITLE
`NotHolderSet` cannot be serialized durring datagen

### ISSUE THREAD

**Issue by Sirttas** [MinecraftForge/MinecraftForge#9634]
Minecraft Version: 1.20.1
Forge Version: 1.20.1-47.1.0

I'm trying to generate the same holder ser I use in https://github.com/MinecraftForge/MinecraftForge/issues/9043:

```
{
    "type": "forge:and",
    "values": [
      "#my_mod:tag1",
      {
        "type": "forge:not",
        "value": "#my_mod:tag2"
      }
    ]
  }
  ```
  
 Because `NotHolderSet` is holding a `RegistryLookup` when `canSerializeIn` is called it is different than the `HolderOwner` provided.
 Maybe https://github.com/MinecraftForge/MinecraftForge/blame/27614b46a6826aabee8711bf4f70c93893d4aa4c/src/main/java/net/minecraftforge/registries/holdersets/NotHolderSet.java#L132 should be `this.value.canSerializeIn(holderOwner);` instead?

**Comment by LexManos** [comment]
Can you please provide the code you are using to reproduce this error? The test cases that I have been able to make all work fine. And the last version of your mod on your github is 1.19.1, which is before the code you linked existed.
