### ISSUE TITLE
[experimentalForgeLightPipelineEnabled] Sides of light-emitting blocks that touch tinted glass appear dim 

### ISSUE THREAD

**Issue by Lolothepro** [MinecraftForge/MinecraftForge#9640]
## Screenshot

![2023-07-10_15 38 17](https://github.com/MinecraftForge/MinecraftForge/assets/68275908/eb367fd0-64cd-4dee-8ba9-7a7c1902f916)

Sodium fix:
https://github.com/CaffeineMC/sodium-fabric/pull/1384/commits/d0d980e6eff284bb873743d5bb0470e6600b3a7f

**Comment by Kovak** [comment]
It looks like this was also fixed by #9651

**Comment by Lolothepro** [comment]
> It looks like this was also fixed by #9651

yes
