### ISSUE TITLE
[Bug] Crash on 1.20.1 forge 47.1.8

### ISSUE THREAD

**Issue by Yukari316** [MinecraftForge/MinecraftForge#9645]
[forums topic](https://forums.minecraftforge.net/topic/125033-bug-crash-on-1201-forge-4718/)

**Minecraft Version:** 1.20.1

**Forge Version:** 47.1.8

**Logs:** [crash report](https://pastebin.com/FK6fMyv1)

**Steps to Reproduce:**
 1. Update forge to 47.1.8
 2. Join a game or server

**Description of issue:**
function loop call on forge 47.1.8

**Comment by Jonathing** [comment]
Fixed in 8df5a80725f7d1599299ccdfab87bfd3f040b8b6 (47.1.9). 47.1.10 recently got pushed to the [files site](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html), so go ahead and use it.

**Comment by Yukari316** [comment]
> Fixed in [8df5a80](https://github.com/MinecraftForge/MinecraftForge/commit/8df5a80725f7d1599299ccdfab87bfd3f040b8b6) (47.1.9). 47.1.10 recently got pushed to the [files site](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html), so go ahead and use it.

ok
