### ISSUE TITLE
Crash in The End

### ISSUE THREAD

**Issue by eff3Ctive** [MinecraftForge/MinecraftForge#9661]
Hi there Internet. im looking for a fix to enter The End..

What happened was me and my friend had built for 15hrs a world, okaying the game as intended, with a couple Mods ofc.
Been to the nether aswell, and just as we were to go to the end, everything crashed, and now we're stuck in the loading screen, and the server crashes.

I've tried to do a singleplayer world of the seed (with and without) mods installed. 
No luck.

**1.20.1:** {Forge version}

This is the crash report:

[crash-2023-07-17_02.22.40-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/12065538/crash-2023-07-17_02.22.40-server.txt)

**Comment by eff3Ctive** [comment]
Also, i have no idea how to code Java at all. just know how to edit the txt and configs of the mods unfortunately..

**Comment by LexManos** [comment]
Fixed in 47.1.24
