### ISSUE TITLE
LivingEntityRenderer.AddLayers hard casts to LivingEntityRenderer, crashing when renderers are replaced

### ISSUE THREAD

**Issue by MehVahdJukaar** [MinecraftForge/MinecraftForge#9683]
Noticed in mc 1.19.2 latest forge. Probably in 1.20 too
Basically if a mod were to (somehow) replace a living entity renderer with one that is not extending LivingEntityRenderer, the event add layer function, when called by another mod, would crash due to unsafe cast incorrectly blaming the latter mod.
Note that my main concern here is my mod (which used add layer event) being blamed and not the other one incase replacing renderers is done incorrectly

**Comment by LexManos** [comment]
Your post is very confusing. Would be better if you used the actual class names and/or produced a stacktrace shows the actual issue. But I think I understand what you're talking about. `net.minecraftforge.client.event.EntityRenderersEvent.AddLayers.getSkin(Model)` and `net.minecraftforge.client.event.EntityRenderersEvent.AddLayers.getRenderer(EntityType<? extends T>)` have generic return types that extend `LivingEntityRenderer` where as their backing maps only extend `EntityRenderer` so if someone were to NOT use the event, and register their renders directly to the vanilla fields somehow, then a class cast exception could be thrown.
