### ISSUE TITLE
Significant loss of performance from 37.0.0 to 47.1.43 on some systems

### ISSUE THREAD

**Issue by RealIndica** [MinecraftForge/MinecraftForge#9685]
**Minecraft Version:** 1.17.1 - 1.20.1

**Forge Version:** 37.0.0 - 47.1.43

**Logs:** https://gist.github.com/RealIndica/5c37099cae1145d47e6313112b1f4ff4

**Steps to Reproduce:**
1. Download Forge version between 37.0.0 - 47.1.43
2. Run Minecraft
3. Observe FPS significantly lower than vanilla

**Description of issue:**
Running forge with or without mods above version 37.0.0 causes a significant loss in performance. I also notice that chunks load a bit slower compared to vanilla. This issue is also happening with my friend with similar system specifications (Ryzen cpu + Nvidia gpu) and it is mentioned only once [here.](https://forums.minecraftforge.net/topic/125174-forge-is-laggy-even-without-anymods-although-vannila-and-fabric-work-perfect-1201)

I am unsure what change was made within Forge to produce this bug even after looking at the code. I have also found that spark has not produced anything useful but here is the profile regardless: https://spark.lucko.me/IbXry5DfAy

I have tried plenty of fixes and I am certain that my system and minecraft configurations are not the issues. 

**Example:**
Framerate with Forge (no mods)
![image](https://github.com/MinecraftForge/MinecraftForge/assets/20850442/78badd76-d511-4aba-94d6-80882d6a78a3)

Framerate without Forge
![image](https://github.com/MinecraftForge/MinecraftForge/assets/20850442/ec0610e7-097c-42ab-92ae-0a6ef2592011)

**Comment by RealIndica** [comment]
Some more data to work with. CPU usage is generally higher on one core with Forge in comparison to vanilla. Additionally, GPU usage is much lower with Forge in comparison to vanilla. 

**Usage Statistics (Vanilla):**
![image](https://github.com/MinecraftForge/MinecraftForge/assets/20850442/c4aa5042-fd8e-4781-acaf-e93b307b6d57)
![image](https://github.com/MinecraftForge/MinecraftForge/assets/20850442/f1900ad5-ec8a-448c-a3a5-afdb9937685c)

**Usage Statistics (Forge):**
![image](https://github.com/MinecraftForge/MinecraftForge/assets/20850442/254fcc5d-9538-4c95-9412-e51fc805a0d3)
![image](https://github.com/MinecraftForge/MinecraftForge/assets/20850442/78432f9e-da1f-4a18-a0d4-a669b8f78ec5)

**Comment by RealIndica** [comment]
This issue does not seem to be isolated to configurations with Ryzen + Nvidia components. Testing on a laptop with a 10th gen Intel i5 processor with integrated graphics 630, with vanilla we saw a maximum of 120fps and an average of 75. With forge (no mods), framerate dropped drastically to 20-30 fps during most of the gameplay. The only notable consistent thing between our devices is that we are running Pro versions of Windows (10 and 11) on the latest updates. 

Edit:

On my secondary machine (laptop) with a Ryzen 9 5900hx, RTX 3070 and 16gb ram, vanilla ran at about 500fps whereas forge ran at about 60-100fps. Again, Windows 11 pro.

**Comment by Quinnnnnq** [comment]
same here.running on i3-10100f, GTX960, Rubidium+Oculus added,60 mods in total.Win 10 Pro 22H2

**Comment by embeddedt** [comment]
Question: what launcher did you use to gather these results?

**Comment by RealIndica** [comment]
> Question: what launcher did you use to gather these results?

Default minecraft launcher from Windows store.

**Comment by PaintNinja** [comment]
This was resolved on Discord - the issue was outdated/broken drivers and outdated UEFI firmware, and confirmed not to be a problem with Forge itself.
https://discord.com/channels/1129059589325852724/1129069799545241703/1150847720190382090
