### ISSUE TITLE
Fire related mobs not taking enough freezing damage

### ISSUE THREAD

**Issue by Risttahukas** [MinecraftForge/MinecraftForge#9686]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.1.0

**Steps to Reproduce:**
 1. Submerge a Blaze fully in powdered snow
 2. Count how many times it takes damage before dying or use commands to show its health

**Description of issue:**
Blazes (and also Magma Cubes and Striders) should take 5hp of damage from freezing in powder snow (works as intended in vanilla). However when running the game with Forge, they only take 1hp of damage.

**Comment by Lupicus** [comment]
Appears that the patch for LivingEntity#hurt was done wrong in 1.19.4, the extra freeze damage is skipped unless doing shield blocking.

**Comment by LexManos** [comment]
Dont doubt it, I'll look into next time I get some time at a computer. Unless someone wants to pr it before i get there.
