### ISSUE TITLE
LoadingErrorScreen inner headers are not centered

### ISSUE THREAD

**Issue by zomabies** [MinecraftForge/MinecraftForge#9687]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.2.1

**Logs:** None

**Steps to Reproduce:**
 1. Add a `ModLoadingWarning` and a crash occurred later. Sample example is provided below.
```java
@Mod("test")
public class ExampleMod {

    public ExampleMod() {

        final IModInfo modInfo = ModLoadingContext.get().getActiveContainer().getModInfo();
        final ModLoadingWarning modLoadingWarning = new ModLoadingWarning(
                modInfo,
                ModLoadingStage.CONSTRUCT,
                "TEST warn");
        ModLoader.get().addWarning(modLoadingWarning);

        throw new IllegalStateException("Test");
    }
}
```
 2. Wait for it to finish loading
 3. Both inner error and warning header in `LoadingErrorScreen` are not centered

![](https://i.imgur.com/MGWYctt.png)

**Description of issue:**

Both header should be centered as shown in https://github.com/MinecraftForge/MinecraftForge/pull/5530. It is possible this issue exists since 1.16 based on https://github.com/MinecraftForge/MinecraftForge/blame/6d15febdb35b5676b1795b2965d6eb527bb336e6/src/main/java/net/minecraftforge/fml/client/gui/screen/LoadingErrorScreen.java#L155

**Comment by Ayush-Thakur-geek** [comment]
Hey @zomabies, I would like to work on this issue.
