### ISSUE TITLE
PLZ Continue the support of Minecraft Forge after NeoForged founded.

### ISSUE THREAD

**Issue by chenyuanxi11** [MinecraftForge/MinecraftForge#9692]
**The original Chinese version has more informations. My English skill cannot let me to translate it exactly. If you have skill or a tool to translate it, plz try to do it.**

I knew Minecraft Forge's development is very difficult now because NeoForged founded. Although NeoForge will provide a new way for us to develop and load mods in newer versions of Minecraft. But we think it will not make any version for older version of Minecraft or provide older versions of Minecraft Forge on its offical site. Now Minecraft Forge is still the only way to develop and load mods on older versions of Minecraft. Although we have enough data to develop or load a Forge Mod for an older version of Minecraft without offical support, we need a way to download Forge and MDK. The way is Forge's offical server. It's still an important bridge between Minecraft and Mods. Maybe Minecraft Forge will stop its developing one day, but Minecraft Forge cannot die! Minecraft Forge can stop its development, but the server cannot stop!

我了解到最近由于NeoForged团队分离而造成的Minecraft Forge开发困难。尽管NeoForge将会在Minecraft的新版本中为我们提供可能足以替代Minecraft Forge的Mod加载器解决方案，但是我们认为它并不会再重拾旧版——再制作一份适用于旧版本的或在其官网提供旧版的Minecraft Forge以弥补其缺陷。至今，Minecraft Forge仍是在旧版Minecraft中编写和运行Mod的唯一途径。尽管充足的资料使得我们足以在不借助任何官方支持的情况下完成任何旧版Forge Mod的开发，但是我们仍然需要一条获取Forge或MDK的途径，这条途径就是Minecraft Forge的官方服务器。它仍是连接Minecraft和其数以万计的Mod的重要桥梁。事已至此，Minecraft Forge或许就在某一天停止开发了，但是Minecraft Forge只能停更不能死！Minecraft Forge的服务器不能停服！

**Comment by PaintNinja** [comment]
There are no plans to discontinue Forge at this time. In the unlikely event that the Forge maven servers are closed, backups will likely be provided.

**Comment by Ecdcaeb** [comment]
Everything will be solved by ZekerZhayard.
