### ISSUE TITLE
Hi guys, i have a problem with FTBLIBRARY and forge on version 1.19.2

### ISSUE THREAD

**Issue by FERZ1** [MinecraftForge/MinecraftForge#9696]
i installed right forge and now i have this problem net.minecraftforge.fml.ModLoadingException: Mod §eftblibrary§r requires §6forge§r §o43.2.6 or above§r §7Currently, §6forge§r§7 is §o43.2.0
From my view, i install a right version of forge(forge-1.19.2-43.2.21-installer), but it still saying that i have 43.2.0. What do i do?

**Comment by Jonathing** [comment]
Make sure to select the correct version in the vanilla launcher after installing your newer version. In any case, this issue tracker is for issues with Forge itself and not for support, so I ask that you ask in [our Discord server](https://discord.minecraftforge.net) for more help in that regard.
