### ISSUE TITLE
Extended crash report to better identify the mod that caused the crash.

### ISSUE THREAD

**Issue by thedead2** [MinecraftForge/MinecraftForge#9717]
As the title says, I think it would be a good idea to extend the minecraft crash report in a way that in best case directly identifies the mod that caused the crash and provide the issue link of the mod inside the crash report. I have implemented this in a simple way inside my own mods via a class that simply scans  the generated crash report for the main class path of the mod and then appends additional infos to the crash report in a way like this:
<img width="1711" alt="Screenshot 2023-09-19 at 15 25 37" src="https://github.com/MinecraftForge/MinecraftForge/assets/62204843/9c7f7649-99c6-43d0-b8dc-73701c85cbca">

I think something like this would make it easier for everyone to identify what caused the game to crash, be it a normal user, a mod developer or a (mod) pack creator.

If you agree, I would create a pull request to implement it standardly in forge.

**Comment by Jonathing** [comment]
I can't guarantee that it would be implemented into Forge, but you're always welcome to open a pull request for anything if you want us to give it a look. If it isn't too intrusive it might have a good chance.

**Comment by thedead2** [comment]
Alright, thanks for the reply, then I will just program it and open a pull request.
