### ISSUE TITLE
Items in hand do not blend

### ISSUE THREAD

**Issue by Clashsoft** [MinecraftForge/MinecraftForge#972]
As you can see on this screenshot, items with multiple render passes do not render correctly if an icon is partly transparent. The transparency of that icon gets discarded and it becomes opaque. This only applies when the item is rendered in the player's hand.

![items](https://f.cloud.github.com/assets/4145923/2188902/6ba6825e-980d-11e3-8b13-ee405b0a7523.png)

**Comment by xhiyikfkox** [comment]
@Crashsoft I have your win in the bag, Glass Bottle is rendered clear! I have that for you as im working on the same thing you are :)
