### ISSUE TITLE
Mob Effects fail to register

### ISSUE THREAD

**Issue by Jackbusters** [MinecraftForge/MinecraftForge#9724]
**Minecraft Version:** 1.20.2

**Forge Version:** 48.0.1

**Logs:** https://gist.github.com/JackHTerrell/0747eca8db41d8d7ffd1c75ed3cee8d5

**Steps to Reproduce:**
 1. Attempt to register a mob effect using Deferred Registry.

**Description of issue:**
Registry was working in 1.20.1. I attempted to port to 1.20.2, making no changes to my mob effects registry, and got an error stating my mod failed to load correctly. All other registries (entities, items, creative mode tabs, and GLM) work without issue.

**Comment by LexManos** [comment]
You're not using DeferredRegistries correctly, you are creating/registering the MobEffect in your constructor.
`	at com.morearrows.XtraArrows.<init>(XtraArrows.java:30) ~[%23194!/:?]`
