### ISSUE TITLE
[1.20.2] FMLCommonSetupEvent does not get fired in datagen run

### ISSUE THREAD

**Issue by DBotThePony** [MinecraftForge/MinecraftForge#9740]
**Minecraft Version:** 1.20.2

**Forge Version:** 48.0.20

**Steps to Reproduce:**
 1. Download MDK for 48.0.20
 2. Open IDE
 3. gen*runs
 4. Execute task runData
 5. Observe no `HELLO FROM COMMON SETUP` printed in logs

**Description of issue:**

When launching game itself (runClient), FMLCommonSetupEvent *is* dispatched to mods.

**Comment by LexManos** [comment]
Correct, mods are just initialized.
