### ISSUE TITLE
[1.20.2] runClient Gradle task fails with Forge 48.0.18

### ISSUE THREAD

**Issue by Niels-NTG** [MinecraftForge/MinecraftForge#9741]
**Minecraft Version:** 1.20.2

**Forge Version:** 48.0.18

**Logs:** https://gist.github.com/Niels-NTG/e1d0860b679f279f7aa8f01fb8178ec9

**Steps to Reproduce:**
1. Create new project in IntelliJ IDEA 2023.2.2 using the template project from the 48.0.18 MDK
2. Set the project SDK to Microsoft OpenJDK 17.0.8.1 or Eclipse Temurin 17.0.8
3. Run the genIntellijRuns Gradle task with 
4. Run the runClient Gradle task
5. runClient task fails with a `ResolutionException`

**Description of issue:**
After upgrading the Forge version in my project from 48.0.13 to 48.0.18 the runClient Gradle fails with a `ResolutionException: Module com.github.oshi reads more than one module named com.google.errorprone.annotations` (see log file above for full trace). Clearing my Gradle cache did not make a difference. Nor did changing the JDK distribution. It seems unlikely to have anything to do with my own code, since I see the same behavior when creating a new project using the 48.0.18 MDK. Downgrading to 48.0.17 also resulted in the same issue.

**Comment by LexManos** [comment]
Solved in fg 6.0.14, so update your fg in your buildscript.

https://github.com/MinecraftForge/ForgeGradle/commit/8cc1ddc2859b1cd5925a5bf60a06001e64363ef9

**Comment by Niels-NTG** [comment]
Thanks. :+1: 

For those reading along: update the following item in the `plugins` section in your `build.gradle` file:
```gradle
id 'net.minecraftforge.gradle' version '[6.0.14,6.2)'
```

I assume this change will be included in the MDK of Forge 48.x.x in the near future.

**Comment by LexManos** [comment]
Yup, got it done locally. It'll be included in my next commit.
