### ISSUE TITLE
Should temperature belong to FluidStack?

### ISSUE THREAD

**Issue by Ecdcaeb** [MinecraftForge/MinecraftForge#9760]
FluidType#temperature
FluidType is type.And the fluidStack is a instance.I think temperature is a property of fluidStack instead of FluidType.The only thing FluidType need to do is "DefaultTemperature",not "temperature".

**Comment by KnightMiner** [comment]
This just sounds like a change that overcomplicates the API. This would force every modder who handles fluids to decide on a way to handle merging fluids of different temperatures, or force the player to wonder why two fluids are not merging. For how few mods actually use the temperature property, I see no gain to that.

You are absolutely free to include temperature as part of your fluid NBT, the `getTemperature` method is fluid stack sensitive.
