### ISSUE TITLE
Discord invite invalid

### ISSUE THREAD

**Issue by Spinoscythe** [MinecraftForge/MinecraftForge#9766]
**Minecraft Version:** N/A

**Forge Version:** N/A

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue: The discord invite link in project's *About* section*

**Comment by PaintNinja** [comment]
Could you be more specific? It looks correct for me 
![image](https://github.com/MinecraftForge/MinecraftForge/assets/3158390/dcfffdde-74f9-4204-9a2a-b452a380bd11)

**Comment by Kriiish7** [comment]
@PaintNinja https://discord.minecraftforge.net/ specifically

**Comment by PaintNinja** [comment]
That is the correct invite link

**Comment by Kriiish7** [comment]
![image](https://github.com/MinecraftForge/MinecraftForge/assets/149209853/999e32af-6686-4467-a0af-582688afe6d0)

**Comment by Ecdcaeb** [comment]
No.
There is no problem with the link.
