### ISSUE TITLE
1.20.1 Forge breaks consistent tag ordering, causing random world generation crash due to feature order cycle involving tags

### ISSUE THREAD

**Issue by alcatrazEscapee** [MinecraftForge/MinecraftForge#9774]
**Minecraft Version:** 1.20.1
**Forge Version:** 47.1.36, specifically this commit: https://github.com/MinecraftForge/MinecraftForge/commit/2745531f08bf159e1346f1b69cbe757ed7e8d67b

**Description of issue:**

[This mod](https://github.com/TerraFirmaCraft/TerraFirmaCraft/releases/tag/v3.0.0-beta) will create a world fine in 47.1.33, but crashes on world generation in 47.1.36 with a feature cycle. Using cyanide, it prints a completely random feature cycle every load, for example:

```
Description: Exception generating new chunk

com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.

Cycle:
At step 8
Feature 'tfc:volcano_rivulet'
  must be before 'tfc:cave_vegetation' (defined in 'tfc:volcanic_mountains' at index 0, 1 and 3 others)
  must be before 'tfc:bamboo' (defined in 'tfc:plateau' at index 2, 3 and 23 others)
  must be before 'tfc:forest' (defined in 'tfc:plateau' at index 3, 6 and 22 others)
  must be before 'tfc:volcano_caldera' (defined in 'tfc:volcanic_oceanic_mountain_lake' at index 4, 5 and 4 others)
  must be before 'tfc:iceberg_packed_rare' (defined in 'tfc:volcanic_oceanic_mountain_lake' at index 5, 6 and 1 others)
  must be before 'tfc:iceberg_packed' (defined in 'tfc:shore' at index 1, 2 and 10 others)
  must be before 'tfc:rare_bamboo' (defined in 'tfc:lowlands' at index 6, 7 and 4 others)
  must be before 'tfc:random_volcano_fissure' (defined in 'tfc:volcanic_oceanic_mountain_lake' at index 8, 9 and 3 others)
  must be before 'tfc:volcano_rivulet' (defined in 'tfc:canyons' at index 3, 4)

	at com.alcatrazescapee.cyanide.codec.FeatureCycleDetector.buildFeaturesPerStep(FeatureCycleDetector.java:141) ~[cyanide-forge-1.20.1-4.1.0.jar%23159!/:4.1.0] {re:mixin,re:classloading}
```

This feature cycle is bogus, as evidenced as it doesn't happen on prior Forge builds. What happened, is Forge made tag ordering unstable in the new `remove` feature additions:

[Reference](https://github.com/MinecraftForge/MinecraftForge/commit/2745531f08bf159e1346f1b69cbe757ed7e8d67b#diff-25fbb9cdc0f246b5c8f16799b4cbb56a374f5c14edaecc7decc6d959d8dc5766R15-R28)

![image](https://github.com/MinecraftForge/MinecraftForge/assets/35673674/25bc7c4d-5c8e-4b93-a507-7bd0ede46914)

Switching to a hash set instead of an immutable builder means tags do not preserve order anymore, which is very important when you have biomes that specify their features via tags, [as an example](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/8ff523f0b894b2409dca07ed49bcbd5faf8f9738/src/main/resources/data/tfc/worldgen/biome/plains.json#L22-L32)

**Comment by LexManos** [comment]
Interesting, nowhere in a Tag's implementation did I get the idea that order was important. As its all backed by Sets which are typically not ordered. But apparently ImmutableSet is. Should be simple enough to fix by just changing the HashSet to a LinkedHashSet

**Comment by LexManos** [comment]
Sorry, thought I had already fixed this, then forgot about it.
