### ISSUE TITLE
`EntitySizeEvent` is fired before the subclass constructors are finished, which can cause unexpected behavior (that leads to animals not spawning)

### ISSUE THREAD

**Issue by alcatrazEscapee** [MinecraftForge/MinecraftForge#9788]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.1.6

**Logs:**  https://pastebin.com/ztBZikuh

This log demonstrates trying to spawn an entity via spawn egg, and having it fail. This only occurs in Forge versions >=47.1.6, not in earlier versions. I'm not sure if this would be considered an issue in Forge, or if this behavioral change is to be expected, but this did cause us a difficult-to-track down issue, so I'm documenting it here for posterity, in case the constructor-firing-event-that-invokes-subclass-methods is undesirable behavior.

**Description of issue:**

TerraFirmaCraft has an issue in which passive animals will not spawn when Forge versions >= 47.1.6 are used. The basic sequence of events is this:

- A `TFCHorse` (which extends `Entity`) is attempted to be constructed, in order to spawn.
- `EntitySizeEvent` is fired during the constructor of `Entity`
- This calls `Entity#isBaby()`, which is overriden in one of TerraFirmaCraft's entity subclasses, `TFCHorse`
- This tries to access a config-dependent value, namely, "how many days does this animal have to age before not being a baby" (`isBaby()` -> `getAgeType()` -> `getDaysToAdulthood()` -> `animalConfig()` -> `this.config`)
- This config value `this.config` is dependent on a field set in the constructor, [here](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/2bdd99452feda67c432507e70178de7378e48eda/src/main/java/net/dries007/tfc/common/entities/livestock/horse/TFCHorse.java#L107)
- As a result, since the constructor is not yet ran, this NPEs at runtime and fails to spawn the entity.

**Comment by Jonathing** [comment]
Please confirm if the issue is still present with at least `47.2.0`

**Comment by alcatrazEscapee** [comment]
Unfortunately I can't, because 47.2.0 has another issue (#9774) which straight up causes a crash on world generation, which is still unfixed in 1.20.1. Thus I can at most support up to 47.1.35, and from user reports I've heard that everything through 47.1.6 to 47.1.30 all have the same issue. Thus the maximum Forge version I can support without issues is 47.1.5

**Edit** As I was writing this, I didn't see that the linked issue was actually fixed as of 47.2.14, I'll double check that specific version.

Yep, it appears to be fixed. Apologies for the old version issue report.
