### ISSUE TITLE
IPN WARNING - "any weapon" replace failed

### ISSUE THREAD

**Issue by Fidulus** [MinecraftForge/MinecraftForge#9797]
**1.20.2:** {Minecraft version}

**48.0.40:** {Forge version. *Version number, not latest/rb*}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Just equip any weapon in singleplayer world
 2. Happens after reload or any shot fired
 3. ...

**Description of issue:**
Can anyone please tell me what this error message means, and how to solve the issue?

![image](https://github.com/MinecraftForge/MinecraftForge/assets/48780170/02260d8e-4f25-4f68-a442-598dbd13a579)

**Comment by LexManos** [comment]
Not Forge related. Report to whatever mod adds the weapons
