### ISSUE TITLE
[1.19.2-43.3.5] Gradle build 1.19.2 branch source fails with java.lang.NullPointerException (no error message) line: 72 in build.gradle

### ISSUE THREAD

**Issue by SamTheProto** [MinecraftForge/MinecraftForge#9811]
**Minecraft Version:** 1.19.2
**Forge Version:** 43.3.5

**Logs:** 
[Gradle logs](https://gist.github.com/SamTheProto/4822fe5a66a563d88beddd30bc414a53) 
[Gradle stacktrace](https://gist.github.com/SamTheProto/aa85d14637636c380436e926080715c3)

**Steps to Reproduce:**
 1. Download 1.19.2 branch from [github](https://codeload.github.com/MinecraftForge/MinecraftForge/zip/refs/heads/1.19.2) and unzip to a folder
 2. Open the folder up in IntelliJ IDEA 2023.3
 3. Error appears in console
 
**Description of issue:**
*DISCLAIMER: I know that it's a Legacy branch.*
I wanted to make my own project that would've needed deep integration with the forge minecraft server but as soon as I even tried to initialize the 1.19.2 branch in my IDE gradle fails with no further info than a NullPointerException (no error message) on line 72 in build.gradle
I'm completely dumbfounded by this and cant find anyone else having this error

**Comment by PaintNinja** [comment]
Explained in Discord that you're not meant to make a custom build of Forge to make mods.
