### ISSUE TITLE
Pack overlays in mod files are not supported

### ISSUE THREAD

**Issue by Apollounknowndev** [MinecraftForge/MinecraftForge#9818]
**Minecraft Version:** 1.20.2+

**Forge Version:** any

**Description of issue:** Pack overlays in mod pack.mcmeta files do not function. This is a major issue for datapacks-packaged-as-mods which rely on overlays to function correctly on new versions, such as Terralith.

**Steps to Reproduce**
- Install [Terralith v2.4.11](https://modrinth.com/mod/terralith/version/2.4.11). This version of Terralith relies on pack overlays to support the `minecraft:grass` -> `minecraft:short_grass` change.
- Attempt to create a new world. The game will instantly crash due to errors with registries failing the load, which is due to the game still trying to parse the files with `minecraft:grass` in them.

**Comment by getCursorsExe** [comment]
Related to #9816? Insert the full crash log.

**Comment by Apollounknowndev** [comment]
This doesn't relate to #9816, as this crash is around pack overlays which were only added in 1.20.2. Here's the crash report, don't ask for the "above errors" as they just don't exist.

[crash-2023-12-12_14.39.13-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/13659455/crash-2023-12-12_14.39.13-client.txt)

**Comment by getCursorsExe** [comment]
Oh okay. Both of these crashes are in the same instance (net.minecraft.client.gui.screens.worldselection.SelectWorldScreen) by the way.

**Comment by Apollounknowndev** [comment]
Both crashes are due to the game invaliding a built-in datapack and not being able to disable it because it is built-in.

**Comment by LexManos** [comment]
[overlay_test.zip](https://github.com/MinecraftForge/MinecraftForge/files/13666455/overlay_test.zip)
Tested with this overlayed data pack.
If it worked a 3x3 of dirt = redstone block
If it doesn't a 3x3 of dirt = anvil
The whole system is complex/redundant so needs a rework, but this is good enough for now.
