### ISSUE TITLE
Conflict between Access Transformers and Mixins

### ISSUE THREAD

**Issue by SuperMartijn642** [MinecraftForge/MinecraftForge#9820]
**Minecraft Version:** 1.20.2 - 1.20.4

**Forge Version:** 48.0.32 - 49.0.3

**Logs:** https://gist.github.com/SuperMartijn642/4a4902e3ce60b0100667c8118a91427e (Part of the log is copied from the launcher's output window, hence the weird formatting)

**Steps to Reproduce:**
 1. Create a mixin for a private method which captures local variables. Here is an example for the `Entity#isStateClimbable` method:
 ```java
@Mixin(Entity.class)
public class EntityMixin {

    @Inject(
        method = "isStateClimbable",
        at = @At("HEAD"),
        locals = LocalCapture.CAPTURE_FAILHARD
    )
    private void isStateClimbable(BlockState state, CallbackInfoReturnable<Boolean> ci){
    }
}
```
2. Create an access transformer entry to change the method's visibility to public:
```cfg
# Entity
public net.minecraft.world.entity.Entity m_285776_(Lnet/minecraft/world/level/block/state/BlockState;)Z # isStateClimbable
```
3. Build the mod and launch the game **outside the dev environment**. (If the access transformer entry is applied in dev, the game will not crash.)
4. Observe a crash with the message `Caused by: org.spongepowered.asm.util.throwables.LVTGeneratorError: Could not locate method metadata for m_285776_ generating LVT in net/minecraft/world/entity/Entity`

**Description of issue:**
It appears that when there is an access transformer (AT) entry for a method, any mixins capturing local variables for that method will fail.
A crash like this was encountered by user between an AT entry in my core library mod and a mixin in Iceberg: https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/issues/57

The first Forge version affected was 48.0.32 for Minecraft 1.20.2 and the issue still persists in 49.0.3 (I haven't tested any later versions).
The following commits were included in Forge 48.0.32 and likely introduced the issue: https://github.com/MinecraftForge/MinecraftForge/commit/e34090c8095366ac9b9b5e63f272d2905ef557ca and https://github.com/MinecraftForge/MinecraftForge/commit/7a443276a503b280cda3fd824c8e59938f113dbe

**Comment by LexManos** [comment]
Interesting, was able to make a [test.zip](https://github.com/MinecraftForge/MinecraftForge/files/13709080/test.zip) to reproduce. 
Basically a small [typo](https://github.com/MinecraftForge/SecureModules/commit/bef5635a3bcf1c9a49891e52dceba99caefdfb50) when I was cleaning up SecureModules.
Interesting that it manifested in this way, also shows a few bugs in the old code/mixin code that worked because of unintended implementation details. Anyways bumping SM fixed it in my tests.
