### ISSUE TITLE
My modpack crushes after creating a new world, plz help!

### ISSUE THREAD

**Issue by LoputkaH** [MinecraftForge/MinecraftForge#9829]
**Minecraft Version:** {1.12.2 forge}

**Forge Version:** {forge-14.23.5.2859}

**Logs:** {https://gist.github.com/LoputkaH/fb74850a8154ae24ef51fff291a5d173#file-crash-2023-12-21_13-34-35-server}

**Steps to Reproduce:**
 1. Start Minecraft
 2. Create a new world
 3. Then, when you enter in world, you start falling into a void
 4. Then Minecraft crushes

**Description of issue:**
Minecraft work good in menu, but if you create a world, Minecraft ~3 sec after entering into world, was crushes

**Comment by JustRed23** [comment]
1.12.2 has been deprecated for a long time now, best move would be to upgrade to a newer version that is still supported

**Comment by JustRed23** [comment]
After reading the stacktrace, three things pop up, galacticraft, moreplanets and betterhurttimer. My guess is that Better Hurt Timer does not like being together with those two. Try disabling it for now
