### ISSUE TITLE
[1.20.4] Mod file name contains "[" or "]" cannot be loaded.

### ISSUE THREAD

**Issue by noriokun4649** [MinecraftForge/MinecraftForge#9842]
**Minecraft Version:** 1.20.4

**Forge Version:** 49.0.14

**Logs:**
```
Mod File: /C:/Users/admin/AppData/Roaming/.minecraft/mods/[]torchbowmod-1.0.0.jar
Failure message: TorchBowMod has class loading errors
	java.lang.IllegalArgumentException: Illegal character in path at index 55: file:///C:/Users/admin/AppData/Roaming/.minecraft/mods/[]torchbowmod-1.0.0.jar
Mod Version: 1.0.0
Mod Issue URL: NOT PROVIDED
Exception message: java.net.URISyntaxException: Illegal character in path at index 55: file:///C:/Users/admin/AppData/Roaming/.minecraft/mods/[]torchbowmod-1.0.0.jar
```
Full log:  https://gist.github.com/noriokun4649/2b91af0b991305df48fc43089531cfbc

**Steps to Reproduce:**
 1. Put mods that support 1.20.4 into the Mods folder.
 2. Add "[" to the mod file name.
 3. Minecraft launch.
 4. Error!

**Description of issue:**
If the Mod file name contains "[" or "]", the Mod cannot be loaded, though.
Is this the intended behavior?
In the previous FML, mods with "[" or "]" in the file name could be loaded.

**Comment by PaintNinja** [comment]
Modern Java doesn't allow square brackets at the start of a file name. I recommend using a more common format such as "ModName-MCVer-ModVer.jar" (i.e. TorchBowMod-1.20.4-1.0.0")

**Comment by noriokun4649** [comment]
@PaintNinja 
> Modern Java doesn't allow square brackets at the start of a file name.

I did not know this information. Thanks for sharing. I will try not to use square brackets in the future.

I see, that it's not an issue with FML but rather a problem related to Java's policy.
Since it appears to be behaving in accordance with Java policy, would it be advisable to close this issue?

**Comment by LexManos** [comment]
So, I was able to find a way around it, but yes the issue is that [Java itself](https://github.com/adoptium/jdk/blob/24823ba647d4bf412586372cd5076f35bbc131a5/src/jdk.zipfs/share/classes/jdk/nio/zipfs/ZipPath.java#L201) Produces URIs with invalid syntax. So I just bypass the whole URI system for this case. Which in my tests makes things work fine.

**Comment by noriokun4649** [comment]
@LexManos 
Thank you for fixing it.
