### ISSUE TITLE
[1.19.3(49.0)~1.20.4] Launcher profile files are generated with unintended/incorrect name.

### ISSUE THREAD

**Issue by PeyaPeyaPeyang** [MinecraftForge/MinecraftForge#9843]
**Minecraft Version:** 1.20.3~1.20.4

**Forge Version:** 49.0~

**Steps to Reproduce:**
 1. Download the Forge 1.19.3/1.20.4 from the [official site](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.3.html)
 2. Run it and install the Forge client.
 3. Files will begenerated in the place with unintended/incorrect names.

**Description of issue:**

Previous to this version of Forge, `<mcVersion>-forge-<forgeVersion>`(`.json`) was used as the folder/manifest-file name.  
(Launcher profile manifest file means the file located at `%AppData\versions\<versionName>`)  
However, from this version, is generated with the name without the hyphen before the Forge version like `<mcVersion>-forge<forgeVersion>`
As a result, some of our management systems are broken(**Is it an intended specification to be made with this name?**)

**Expected Behaviour:**

Files are generated as follows (1.20.4)

```
%Appdata%
|
|-.minecraft
| |-versions
| | |-1.20.4-forge-49.0.14
```

**Actual Behaviour:**

Files are generated as follows (1.20.4)

```
%Appdata%
|
|-.minecraft
| |-versions
| | |-1.20.4-forge49.0.14
                  ^ "-" expected
```

**Suggestion for Amendments to this issue.**

I have looked at the commit 6f9f0f0cfacc74d62be39359d773d5dda220ad73 and have found that the problem was caused from this commit.
Further investigation revealed that [this line](https://github.com/MinecraftForge/MinecraftForge/blob/6f9f0f0cfacc74d62be39359d773d5dda220ad73/buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/LauncherJson.groovy#L36) affected the problem.

So I believe the following simple changes can fix this:
```diff java
                _comment: [
                    "Please do not automate the download and installation of Forge.",
                    "Our efforts are supported by ads from the download page.",
                    "If you MUST automate this, please consider supporting the project through https://www.patreon.com/LexManos/"
                ],
-               id: "$mc-$project.name$forge",
+               id: "$mc-$project.name-$forge",
                time: timestamp,
                releaseTime: timestamp,
```

Thanks.

**Comment by LexManos** [comment]
Its intended your management software refers to data from the json using the data from the json. So unsure what is breaking on your end but this is a valid format.
But ya I can change it back because i don't feel like arguing too much. Its layout was just a slight counting error when converting [this stupid line](https://github.com/MinecraftForge/MinecraftForge/blame/16defac82efdb69b7489a96a27d2ee1dc03355f6/buildSrc/src/main/groovy/net/minecraftforge/forge/tasks/LauncherJson.groovy#L28) to something more sane.
