### ISSUE TITLE
[1.20.4] DNS SRV record lookup not working

### ISSUE THREAD

**Issue by PaintNinja** [MinecraftForge/MinecraftForge#9846]
**Minecraft Version:** 1.20.4

**Forge Version:** 49.0.14

**Logs:**
- https://forums.minecraftforge.net/topic/141971-mc-1204-forge-49014-connection-issues
- https://discord.com/channels/1129059589325852724/1129069799545241703/1192590118045896764 ([Forge discord](https://discord.minecraftforge.net), #user-support channel)

**Steps to Reproduce:**
 1. Setup a server that uses a SRV record
 2. Attempt to connect to the server

**Description of issue:**
My guess is an --add-exports was missed (or implied in the old system) when moving to the new launch method. The fix should be a simple case of adding an `--add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming` equiv. to the new launch system.

**Comment by LexManos** [comment]
No idea why the JDK would have a implementation of something that in itself is broken.
But we could probably work around it by using UnsafeHacks similiar to how I hack PowerMock to work

```java
public class UnsafeHacksUtil {
    public static void hackPowermock() throws Exception {
        addOpen(Object.class, Whitebox.class);
        addOpen(TransformationServiceDecorator.class, Whitebox.class);
    }

    private static Method implAddExportsOrOpens;
    private static void addOpen(Class<?> target, Class<?> reader) throws Exception {
        if (implAddExportsOrOpens == null) {
            implAddExportsOrOpens = Module.class.getDeclaredMethod("implAddExportsOrOpens", String.class, Module.class, boolean.class, boolean.class);
            UnsafeHacks.setAccessible(implAddExportsOrOpens);
        }
        implAddExportsOrOpens.invoke(target.getModule(), target.getPackageName(), reader.getModule(), /*open*/true, /*syncVM*/true);
    }
}
```
