### ISSUE TITLE
High CPU usage in QEMU

### ISSUE THREAD

**Issue by Th0rOnDoR** [MinecraftForge/MinecraftForge#9851]
**Minecraft Version:** 1.19.2

**Forge Version:** 43.5.x

**Logs:** No Crash Report, it work

**Steps to Reproduce:**
 1. Install Qemu
 2. Create a linux VM (arch or deb)
 3.  Install a forge server and start it (with or without mods)

**Description of issue:**
The forge server isn't using any ressource in the vm after it has started but the vm is taking a lot of ressources (cpu) for the host. **It only happens when the forge server is running.**

VM:
![image](https://github.com/MinecraftForge/MinecraftForge/assets/97974236/0fe3a441-7533-4d00-a455-8053d0c21c84)

HOST: (200% means 2 core are fully used to calculate something, i don't know what inside the virtual machine)
![image](https://github.com/MinecraftForge/MinecraftForge/assets/97974236/0b412d1c-9d0b-46cd-8473-51721385c2ab)

**Comment by LexManos** [comment]
No idea, when idle the server ticks a few chunks but thats about it. Something seems weird in your vm setup but I doubt its anything to do with Forge itself. But if you want to get real JVM level profiling then go for it. But there isn't much I can help you with at this level.
