### ISSUE TITLE
On building forge, checkLicenseMain fails

### ISSUE THREAD

**Issue by liam-clink** [MinecraftForge/MinecraftForge#9855]
**Minecraft Version:** 1.20

**Forge Version:** 49.0

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
1. `./gradlew setup`
2. `./gradlew build`

**Description of issue:**
Can't build MinecraftForge because of some license checking issue. There's no information about what header file is causing the issue, or what to do to resolve this. It's probably a simple thing that just isn't included in documentation.
```
> Task :clean:checkLicenseMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':clean:checkLicenseMain'.
> Header does not contain any of the required keywords: map(extension 'license' property 'keywords')
```

**Comment by liam-clink** [comment]
When running :fmlLoader:checkLicenseMain, I get this error, which specifies a few files:

```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fmlloader:checkLicenseMain'.
> License violations were found: src/main/resources/log4j2.xml, src/main/java/net/minecraftforge/fml/loading/targets/UnionHelper.java, src/main/java/net/minecraftforge/fml/loading/targets/ForgeDevLocator.java, src/main/java/net/minecraftforge/fml/loading/targets/ForgeUserdevLocator.java
```

**Comment by PaintNinja** [comment]
Please fill out the issue template properly. MC "1.20" corresponds with Forge 46.0.x and "49.0" doesn't tell us what version of Forge for 1.20.4 you're trying to build. A link to the full log would also help us help you.

**Comment by liam-clink** [comment]
Apologies, it seems I used tags instead of branches. Looks like the issue was found and fixed anyway though.
