### ISSUE TITLE
Crash on startup in a multiloader enviorment

### ISSUE THREAD

**Issue by CrypticVerse** [MinecraftForge/MinecraftForge#9856]
**Minecraft Version:** 1.20.4

**Forge Version:** 49.0.19

**Logs:** [Log](https://gist.github.com/CrypticVerse/73200048998977f50bb5416cde4b67dc)

**Steps to Reproduce:**
 1. Create multiloader project with blocks, items, and biomes
 2. Try launching the game

**Description of issue:**
Game launches, then crashes

**Comment by PaintNinja** [comment]
BetterBiomes appears to be attempting to write to registries too late. Forge doesn't allow this in order to prevent dynamic registration, which can be a pain for users to debug.

Consider using Forge's DeferredRegister or registry events, or make sure you register your things earlier.

**Comment by CrypticVerse** [comment]
How would I register things earlier? Since it is multiloader most of the things registered is using the CommonClass.init()

**Comment by PaintNinja** [comment]
You need to register before `FMLCommonSetupEvent` and `ModConfigEvent$Loading`.
The easiest way to do this is use Forge's `DeferredRegister` feature
https://docs.minecraftforge.net/en/latest/concepts/registries/

**Comment by CrypticVerse** [comment]
Thank you!

**Comment by CrypticVerse** [comment]
So I tried registering the commonclass.init() earlier, still crashes with a different error this time:

Modules terrablender and TerraBlender.common export package terrablender.core to module cloth_config.
It will not even launch the game.

I am using Terrablender and have reported an issue over there too.

**Comment by PaintNinja** [comment]
We use GitHub issues for bug reports, please move to the Discord server for support. https://discord.minecraftforge.net
