### ISSUE TITLE
SavedData broken since 1.20.2

### ISSUE THREAD

**Issue by Klyser8** [MinecraftForge/MinecraftForge#9859]
**Minecraft Version:** 1.20.4

**Forge Version:** 49.0.19

**Logs:** https://gist.github.com/Klyser8/dd04ceed0cd8dedf5fbaea45077f2beb

**Steps to Reproduce:**
1. Create a class extending SavedData
2. Attempt using it how Vanilla uses it

**Description of issue:**
When instantiating the Factory record found inside of the SavedData class, one of the parameters required is a "DataFixType".
Other modloaders allow passing "null" as a parameter to avoid dealing with it, however doing the same in Forge results in the error linked above. According to other devs, this has been broken since 1.20.2.

**Comment by PaintNinja** [comment]
Forge Discord #modder-support-1.20: https://discord.com/channels/1129059589325852724/1129069883813007360/1202922710049620000
MMD Discord #dev-mc-1-20: https://discord.com/channels/176780432371744769/1116090338122141766/1202924532592017408

Appears to be a missing patch to account for 1.20.2+'s changes to this.

**Comment by LexManos** [comment]
For note, nulls not working in a system that Mojang hasnt designed nulls to work is not a bug.
I can add a null check here, and then the deserializer will be responsible for managing their own format updates.
DataFixTypes could also get the IExtensibleEnum treatment. But I haven't looked into the side effects of that.
But honestly I like just adding the null check as it moves all the control to the modders.
