### ISSUE TITLE
Faild to include libs.

### ISSUE THREAD

**Issue by P1neapplell0** [MinecraftForge/MinecraftForge#9863]
I try to add a noise lib to my project by add:
`repositories {
  // releases
  mavenCentral()
  // snapshots
  maven {
    url "https://repo.spongepowered.org/repository/maven-public/"
  }
}

dependencies {
  implementation "org.spongepowered:noise:2.0.0-SNAPSHOT"
}`
It worked well in my Test.main(). But when I use it in custom ChunkGenerator and try to runClient it throw ClassNotFoundException and NoClassDefFoundError. By the way, I tried to add WorldEdit API and the same error occurred. But I used the same way to add Geckolib and it worked well. So how to include lib correctly? I'm confused...

**Comment by LexManos** [comment]
1) Use the [discord](http://discord.minecraftforge.net) for basic dev issues. Github is for bugs/thigns we can fix.
2) You need to use JarInJar or some other method (like shading) to include any extra libraries at runtime. FML doesn't just load random things into the game it has to be told.
