### ISSUE TITLE
Compatibility Issues of Forge with Docker in IPv6 Environment

### ISSUE THREAD

**Issue by Romain-GUILLEMOT** [MinecraftForge/MinecraftForge#9867]
**Minecraft Version:** 1.8-1.20.X

**Forge Version:** All (Tested on  49.0.27, 11.14.4.1577 and some others)

**Steps to Reproduce:**
 1. Setup a server with IPV6 only
 2. Setup a docker container with forge
 3. Try to connect to the Forge Server

**Description of issue:**

Hello,

I am reaching out to seek your expertise within this forum to clarify a technical situation I am encountering, suspecting a potential issue related to Forge in a Docker environment, specifically in an IPv6 context.

**Initial Configuration**: Debian 12 server, configured exclusively for IPv6, with Docker installed. Using the Docker image ghcr.io/pterodactyl/yolks:java_17, launching a Minecraft Vanilla server version 1.20.4 proceeds without any issues.

**Problem**: The issue arises when deploying a Minecraft Forge server version 1.20.4 with the same Docker image (ghcr.io/pterodactyl/yolks:java_17), where connecting to the server becomes impossible. Notably, this issue does not occur when launching outside of Docker, where the server functions as expected.

**Hypothesis**: This situation leads me to question the interaction between Forge and Docker, particularly in an IPv6-only configuration, despite several resolution attempts (testing with different versions of Forge, adjusting container network configurations (0.0.0.0, ::/0, and the server's ipv6), trials with various network settings, and modifications of Java options).

Further testing was conducted with and without the use of the Pterodactyl game panel, unsuccessfully. The parameter

-Djava.net.preferIPv4Stack=false

also did not provide a solution.

I tried to do the same things on multiple Minecraft server (include vanilla,spigot,fabric,sponge) and this work fine. The problem only happend with Forge.
This issue seem to happend on all forge versions.

I appreciate your time and assistance in advance.

**Comment by PaintNinja** [comment]
Forge added full IPv6 support in 1.18.2 and had partial support in earlier versions, but no support beyond Vanilla in 1.8 as far as I'm aware. Therefore I believe this isn't a Forge issue as it should behave the same as Vanilla.

Please join our Discord so we can troubleshoot your issue.

**Comment by Romain-GUILLEMOT** [comment]
So as I got the problem only on Forge on same docker image and same Minecraft version this seem to be strange. I'm going to check your discord.
