### ISSUE TITLE
[1.20.1] Config key correcting from default to default

### ISSUE THREAD

**Issue by VojtechSin** [MinecraftForge/MinecraftForge#9872]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.2.20

**Logs:** 
[latest.log](https://github.com/MinecraftForge/MinecraftForge/files/14346103/latest.log)

```log
Incorrect key Entities to spawn was corrected from [minecraft:zombie, minecraft:skeleton] to its default, [minecraft:zombie, minecraft:skeleton]. 
```

**Steps to Reproduce:**
 1. Create `ConfigValue` with type `List<String>`
 2. Start minecraft
 3. See warning in log and replaced config in config folder

**Description of issue:**
I have config key defined like this:
```java
public static final ForgeConfigSpec.ConfigValue<List<String>> rigEntitiesToSpawn = BUILDER
  .comment(
    "Format: \"modid:entityid\", for example: ",
    "\"minecraft:zombie\"",
    "\"minecraft:creeper\"",
    "SIDE: SERVER"
  ).define("Entities to spawn", List.of(
    "minecraft:zombie",
    "minecraft:skeleton"
  ));
```
But when i start minecraft the key gets "corrected" to its default every time...

**Comment by LexManos** [comment]
Thats because you're doing it wrong.
There are defineList methods you could use. 
```java
).defineList("Entities to spawn", List.of(
  "minecraft:zombie",
  "minecraft:skeleton"
), String.class::isInstance);
                      
```

**Comment by VojtechSin** [comment]
Thanks a lot. I'm stupid sometimes...
