### ISSUE TITLE
[1.20.4] DatapackBuiltinEntriesProvider from #9848 causes issues with forge registries

### ISSUE THREAD

**Issue by Luis-St** [MinecraftForge/MinecraftForge#9874]
**Minecraft Version:** 1.20.4

**Forge Version:** 49.0.30

**Logs:** https://gist.github.com/Luis-St/7d431850d2e9c4bf5e0632d4aaf08da1

**Steps to Reproduce:**
 1. Create a RegistrySetBuilder which contains a Forge Registry like:
    `ForgeRegistries.Keys.BIOME_MODIFIERS`
 2. Subscribe to `GatherDataEvent`
 3. Register a `DatapackBuiltinEntriesProvider` with the created `RegistrySetBuilder` 
 4. Run runData
 5. The run will fail because there is no cloner for the registry `forge:biome_modifier`

**Reason of issue:**
The patch of PR #9848 patched the RegistryPatchGenerator as follows:
```java
  RegistryDataLoader.WORLDGEN_REGISTRIES.forEach((p_313050_) -> {
    p_313050_.runWithArguments(cloner$factory::addCodec);
  });
+ RegistryDataLoader.DIMENSION_REGISTRIES.forEach(reg -> reg.runWithArguments(cloner$factory::addCodec));
```
The problem is that RegistryDataLoader.WORLDGEN_REGISTRIES does only include the vanilla registries.
Possible fix:
```java
- RegistryDataLoader.WORLDGEN_REGISTRIES.forEach((p_313050_) -> {
-   p_313050_.runWithArguments(cloner$factory::addCodec);
- });
+ net.minecraftforge.registries.DataPackRegistriesHooks.getDataPackRegistriesWithDimensions().forEach(registryData -> registryData.runWithArguments(cloner$factory::addCodec));
```

**Comment by Luis-St** [comment]
I'll create a PR as fast as possible

**Comment by BULL3TB0T** [comment]
The same issue persists on 15:40 at the third ".add".
[Youtube Link](https://youtu.be/GRJyJWtSnvQ?si=YQd-GuncWh5F6DhU&t=940
)
