### ISSUE TITLE
Issue with SleepFinishedTimeEvent in 1.19.2

### ISSUE THREAD

**Issue by RealAntEngineer** [MinecraftForge/MinecraftForge#9882]
**Minecraft Version:** {1.19.2}

**Forge Version:** {1.19.2-43.2.8}

**Description of issue:**
When a player tries to sleep in a custom dimension, the animation of sleeping fires then the time remain the same.

to recreate the sleep feature in custom dimension I had to do this :
    
    @SubscribeEvent
    public static void playerSleeping(SleepFinishedTimeEvent sleepFinishedEvent){
        for(ServerLevel serverlevel : sleepFinishedEvent.getLevel().getServer().getAllLevels()) {
            serverlevel.setDayTime((long)24000L);
        }
    }
this should be needed.
Can you fix that ?

**Comment by LexManos** [comment]
You're setting the time in all dimensions, which you shouldn't be.
And our code most definitly sets to the same time as vanilla does:
```java
            long j = this.levelData.getDayTime() + 24000L;
            this.setDayTime(j - j % 24000L);
```
```java
            long j = this.getDayTime() + 24000L;
            this.setDayTime(net.minecraftforge.event.ForgeEventFactory.onSleepFinished(this, j - j % 24000L, this.getDayTime()));
```
So you're gunna need to provide more context to what you're doing.

**Comment by RealAntEngineer** [comment]
Ok, so more context :

My mod is plagued by this bug : https://bugs.mojang.com/browse/MC-188578

so when trying to solved it I found out that the command /time set .... was using something different than the bed ( what I used in fact), so I used the SleepFinishedTimeEvent to set the time on every level and it works.

So I think there is an issue with level.setDayTime as it seems to only work in the Overworld

**Comment by RealAntEngineer** [comment]
the setDayTime does nothing in the DerivedLevelData maybe that the issue ?

**Comment by RealAntEngineer** [comment]
I just found out that doing this

   sleepFinishedEvent.getLevel().getServer().getLevel(Level.OVERWORLD).setDayTime(sleepFinishedEvent.getNewTime());

instead of that

  for (ServerLevel serverlevel : sleepFinishedEvent.getLevel().getServer().getAllLevels()) {
      serverlevel.setDayTime(sleepFinishedEvent.getNewTime());
 }

also works

**Comment by LexManos** [comment]
You're correct, I was mistaken thought Mojang had properly desynced world times. Guess they haven't anyways, no if you're sleeping in other dimensions and want the world time to pass in the overworld looks like you have to explicitly set it.
