### ISSUE TITLE
About Create Mod

### ISSUE THREAD

**Issue by Juner13** [MinecraftForge/MinecraftForge#9892]
Create Mod is a **Minecraft mod created by simibubi that allows players to make contraptions and automate processes using Rotational Power.** It adds many mechanical components and block variants to the game. This mod has good optimization and FPS, so it can be played on nearly any computer! The mod was created in July 18, 2019.

**Comment by Juner13** [comment]
Why did you close my issue and labeled as spam Jonathing?

**Comment by peachey2k2** [comment]
i bet when you said "it can run on any computer" he tried it on his toaster but it crashed. so he felt scammed and marked it as spam out of anger

**Comment by Jonathing** [comment]
This is an **issue tracker** for Forge, not an advertisement billboard. Want to discuss the wonders and magic of the Create mod? Great. That's what our [Discord server](https://discord.minecraftforge.net) is for. Please keep idle discussion out of the issue tracker so we can continue to use it as effectively as possible.
