### ISSUE TITLE
"Saving World" is not rendered with Forge

### ISSUE THREAD

**Issue by Lolothepro** [MinecraftForge/MinecraftForge#9926]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.2.23

**Steps to Reproduce:**
 1. Press Ecs in a world

**Description of issue:**
It seems that "Saving World" is not rendered when you press escape in a world with Forge.

Note: If possible, fix the bug in 1.20.1

**Comment by LexManos** [comment]
Unable to reproduce, the "Saving World" is rendered in the bottom right hand corner just like vanilla. It just goes away very quickly because saving happens very quickly.
