### ISSUE TITLE
[Bug] Minecraft version json file offer a wrong value of path

### ISSUE THREAD

**Issue by wuliaodexiaoluo** [MinecraftForge/MinecraftForge#9930]
**Minecraft Version:** 1.20.4

**Forge Version:** 49.0.10-49.0.46

**Logs:** None

** Step **
 1. Install a Forge
 2. Open the version json file
 3. At "name": "net.minecraftforge:forge:1.20.4-49.0.21:client", In next value block
 4. At  first value block in "downloads"  value block "artifact": ,first value "path"

My English is not very well ,Sorry :(

**Comment by LexManos** [comment]
Not exactly sure what you're talking about, but that file is not downloadable. So there is no download information for it. The json is correct.
