### ISSUE TITLE
Forge 47.2.0 is incompatible with GraalVM

### ISSUE THREAD

**Issue by Billnotic** [MinecraftForge/MinecraftForge#9940]
**Minecraft Version:** {Minecraft version}
1.20.1
**Forge Version:** {Forge version. *Version number, not latest/rb*}
47.2.0
**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Install forge
 2. set the executable to graalvm's
 3. forge will crash on launch

**Description of issue:**
forge is incompatible with the graalvm jdk, which blows because it is WAY better for high end pcs than g1gc or shenandoah (allegedly, cant confirm because its not working)

**Comment by PaintNinja** [comment]
Unable to reproduce - GraalVM Java 17 works fine with Forge 1.20.1. It sounds like you're trying to use Shenandoah with GraalVM, which it doesn't support. This isn't a Forge-specific issue.

**Comment by Billnotic** [comment]
I forgot to update this report sorry, it turns out the issue is with GraalVM for Java 22. That version specifically does not work. Downgrading to 21 works fine.

**Comment by PaintNinja** [comment]
You should use the same Java version as Vanilla does for a given MC version for stability and compatibility reasons (1.20.1 uses Java 17). If you want to use newer Java, you need to use a newer build of Forge that supports it. Chances are Java 22 (and GraalVM 22) will work fine on the latest Forge build for 1.20.1.

Please join the Discord or ask on the forums in future for support. We reserve GitHub issues exclusively for final bug reports
