### ISSUE TITLE
world/serverconfig configs keep resetting to default every time after restart, how can I disable this?

### ISSUE THREAD

**Issue by razenxc** [MinecraftForge/MinecraftForge#9941]
**Minecraft Version:** 1.20.1

**Forge Version:** 1.20.1-47.2.21

**Logs:** null

**Steps to Reproduce:**
1. Open random config of mod which exsists/works on server and edit something there.
2. Save file and restart server
3. It will be reseted to default config

**Description of issue:**
I can't edit anything in home/container/**world/serverconfig/** dir, because it after restart just resets to default.

_*I don't think that issue(which bug). But idk where I can ask about it, so I wrote it here_

**Comment by LexManos** [comment]
Use the discord or the forums for basic tech support.
Most likely the cause is obvious if you read your debug.log file. It'll say correcting the config to something.
