### ISSUE TITLE
[1.20.6] `EventNetworkChannel` not working

### ISSUE THREAD

**Issue by henkelmax** [MinecraftForge/MinecraftForge#9948]
**Minecraft Version:** 1.20.6

**Forge Version:** 50.0.0

**Logs:** No relevant logs/errors

**Steps to Reproduce:**
``` java
EventNetworkChannel channel = ChannelBuilder.named(<my-packet-id>)
                    .acceptedVersions((status, version) -> true)
                    .optional()
                    .networkProtocolVersion(0)
                    .eventNetworkChannel();
                    
channel.addListener(event -> {
    // This is never getting called
})
```

**Description of issue:**

EventNetworkChannels are not working.

My suspicion is:
`ServerCommonPacketListenerImpl` has 

``` java
@Override
public void handleCustomPayload(ServerboundCustomPayloadPacket p_300164_) {
    net.minecraftforge.common.ForgeHooks.onCustomPayload(p_300164_, this.connection);
}
```
which is getting called for `minecraft:brand` and `forge:*` in the login phase (I belive).

But when debugging, my payload gets handled in `ServerGamePacketListenerImpl` which doesn't seem to be handled by forge:

``` java
@Override
public void handleCustomPayload(ServerboundCustomPayloadPacket p_329963_) {
}
```

---

**EDIT**:

All networking related things also seem to still use `FriendlyByteBuf` and not `RegistryFriendlyByteBuf`.

**Comment by LexManos** [comment]
And yes, I wanted all networking things to use FriendlyByteBuf to keep the modder facing things more stable.
You can always cast if you need to.
