### ISSUE TITLE
[1.20.6] getArmorTexture bug

### ISSUE THREAD

**Issue by hummel009** [MinecraftForge/MinecraftForge#9960]
**Minecraft Version:** 1.20.6

**Forge Version:** 50.0.5

**Logs:** No crash

**Description of issue:**

Since 1.20.6 this code in any class, extending ArmorItem, has no effect:

```
@Override
public String getArmorTexture(ItemStack itemStack, Entity entity, EquipmentSlot equipmentSlot, String layer) {
	return "...";
}
```

**Comment by LexManos** [comment]
You're right, that system was re-written by Mojang in 1.20.6 for the new Dyable components system. The hooks need a rework.
