### ISSUE TITLE
[1.20.6] Shield does not work

### ISSUE THREAD

**Issue by Iunius118** [MinecraftForge/MinecraftForge#9966]
**Minecraft Version:** 1.20.6

**Forge Version:** 50.0.6

**Steps to Reproduce:**
 1. Use a shield.
 2. The blocking animation is shown.
 3. Take an attack while blocking.

**Description of issue:**
When using a shield, the blocking animation is shown but attacks cannot be blocked and damage is taken.

![2024-05-07_02 36 33](https://github.com/MinecraftForge/MinecraftForge/assets/18502177/a855b343-1ba9-4871-ae2e-b8ca01d8d35d)

**Comment by LexManos** [comment]
Thanks for the report, simple enough to fix just a missing !

**Comment by chenyu314** [comment]
i have the same problem on my server 1.20.6, do you know how i can fix this?

**Comment by PaintNinja** [comment]
@chenyu314 Update to Forge 50.0.8 or newer, which contains the fix
