### ISSUE TITLE
[1.20.6] Game crashes when reloading a world that uses custom placed features

### ISSUE THREAD

**Issue by JimiIT92** [MinecraftForge/MinecraftForge#9979]
**Minecraft Version:** 1.20.6

**Forge Version:** 50.0.24

**Steps to Reproduce:**
 1. Add a custom placed feature inside the mod's data folder
 2. Generate a new world with the custom placed feature enabled
 3. Generate some chunks, ensuring that the placed feature is actually generated inside the world
 4. Close the world
 5. CLose the game
 6. Relaunch the game
 7. Reopen the previous world
 8. Generate new chunks where the placed feature should be placed

**Description of issue:**
When a world is loaded with some custom palced features, like modded ores for examples, the game crashes with the following error:
`Index -1 out of bounds for length 34`
This happens because in ChunkGenerator.java, line 373, the method `indexMapping()` is called and for modded entries it returns -1.
Then, on line 383, the code tries to acces an array list using said index, in this case it tries to access an item from the array with the index -1, causing the error.

**Test mod**
To further help understand the issue I've setup a quick test mod that spawns a diamond block as ore inside the world (the ore is extremely common to make the error appear faster)
You can find the test mod here: [https://github.com/JimiIT92/TestPlacedFeatureError](https://github.com/JimiIT92/TestPlacedFeatureError)

**Comment by JimiIT92** [comment]
Just noticed a PR for this issue was submitted.
[https://github.com/MinecraftForge/MinecraftForge/pull/9980](https://github.com/MinecraftForge/MinecraftForge/pull/9980)

**Comment by Jonathing** [comment]
There are two PRs that aim to solve this issue. When either one is merged, I'll close it as finished. Re-opening it for now for tracking purposes.
