### ISSUE TITLE
The drawing order of page numbers in CreativeModeInventoryScreen is incorrect

### ISSUE THREAD

**Issue by BloCamLimb** [MinecraftForge/MinecraftForge#9983]
**Minecraft Version:** 1.20.1-1.20.6

**Forge Version:** 47-50

**Description of issue:**
The page number rendering in `CreativeModeInventoryScreen#render` should be moved before `for (CreativeModeTab creativemodetab : currentPage.getVisibleTabs())`.

https://github.com/MinecraftForge/MinecraftForge/blob/38b5b678cba101c2efd224d015e62efefd8e81fe/patches/minecraft/net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen.java.patch#L162-L168

Tooltips have transparency and its Z value is 400, if the tooltip is drawn first, then the page number will be discarded by depth test. Rendering should respect [Painter's algorithm](https://en.wikipedia.org/wiki/Painter%27s_algorithm).

**Comment by LexManos** [comment]
To be more clear, this only comes up when mods add transparency to the tooltips.
Before:
![](https://i.imgur.com/A02EgZL.jpeg)
After:
![](https://i.imgur.com/lTbnypU.jpeg)

**Comment by BloCamLimb** [comment]
This patch looks equivalent to the previous one. I pulled the latest Forge and confirmed that it has not been fixed.

![image](https://github.com/MinecraftForge/MinecraftForge/assets/14106648/7ea0a175-0f28-490d-a5cb-5a38df7b0953)

**Comment by LexManos** [comment]
Ya my bad, missed the save button before re-genning patches
https://github.com/MinecraftForge/MinecraftForge/commit/fd8a0f9c8b2dd68b543798dc9038c80a036b00d0
