### ISSUE TITLE
EntityInteractSpecific event isn't posted on the server side anymore

### ISSUE THREAD

**Issue by Lupicus** [MinecraftForge/MinecraftForge#9984]
**Minecraft Version:** 1.20.6

**Forge Version:** 50.0.28

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. subscribe to EntityInteractSpecific
 2. check side

**Description of issue:**
the event is only posted on client side now

**Comment by Kettle5000** [comment]
Got the same issue but in 1.20.1.

**Comment by Lupicus** [comment]
works for me in 1.20.1

**Comment by Kettle5000** [comment]
sorry. My fault.
