### ISSUE TITLE
Minecraft Cannot Connect to Servers Through a Proxy with Forge Installed

### ISSUE THREAD

**Issue by cnh29bx4983** [MinecraftForge/MinecraftForge#999]
I am using the latest Forge build (1.7.2-Forge10.12.0.1046) with no other mods installed. I am using the defalt Minecraft launcher. Here is my fml-client-latest.log: http://pastebin.com/gDpag5fp.

I usually have to play Minecraft through a proxy to get around an Internet block. I use a program called proxychains to connect to a SOCKS proxy. To play Minecraft through the proxy, I start the launcher with "proxychains java -jar minecraft.jar". With vanilla Minecraft, this works fine, and I am able to connect to and play on servers with no issue. However, when Forge is installed, I am not able to connect to any servers. All of the servers in my multiplayer menu say "Can't connect to server", and trying to connect to one failes with an "io.netty.channel.ConnectTimeoutException" (http://pastebin.com/s7snj53x).

This is what is outputted to the console when I click on the multiplayer menu without any mods installed, and with Forge installed: http://pastebin.com/smfdaAEp (The DNS-request lines and similar things are added to the log by proxychains).

This problem seems to be limited to connecting to servers, as when I install Liteloader and the VoxelCam mod (http://www.minecraftforum.net/topic/1999989-172-liteloader-voxelcam-minecraft-screenshot-manager-uploader-and-editor/), I am able to use VoxelCam to upload screenshots to Imgur, while still being unable to connect to any servers.

**Comment by kriation** [comment]
@cnh29bx4983 - I tested 1.8 with Forge11.14.1.1341, using socksify [using socks5], and was able to connect to a different remote server.
I also tested with vanilla 1.7.2 and 1.7.10 and was unable to connect to the remote server [mc.civcraft.vg]

Seems to me that this is an issue with how 1.7 handles connections through socks proxies, and not an issue with Forge.

**Comment by minecracker627** [comment]
Are you sure that the server is up.

On Tuesday, March 24, 2015, Armen Kaleshian <notifications@github.com>
wrote:

> @cnh29bx4983 <https://github.com/cnh29bx4983> - I tested 1.8 with
> Forge11.14.1.1341, using socksify [using socks5], and was able to connect
> to a different remote server.
> I also tested with vanilla 1.7.2 and 1.7.10 and was unable to connect to
> the remote server [mc.civcraft.vg]
>
> Seems to me that this is an issue with how 1.7 handles connections through
> socks proxies, and not an issue with Forge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MinecraftForge/MinecraftForge/issues/999#issuecomment-85515112>
> .
>


-- 
If you don't have something nice to say SHUTUP!

**Comment by kriation** [comment]
@minecracker627 - Server is up, as 1.8 client shows it running spigot 1.7.10
![2015-03-24_10 27 14](https://cloud.githubusercontent.com/assets/411916/6803801/737cd332-d210-11e4-9316-42542519fef5.png)

**Comment by minecracker627** [comment]
mc63821@gmail.com sent you an invitation to join MEGA.\n\n";

--- Message from user: ---
Hello, join me on MEGA and get access to encrypted storage and
communication. Get 50 GB free!
---

Please create your free MEGA account by clicking on the following
link:\n\n";
https://mega.nz/#newsignupcmVwbHkrMDBhZjYxNzdmNzRmNzQyYjY0NjMzMzdhYzhlNWE0MDIwNWQ3MGM4MmRjNmZlOWNhOTJjZjAwMDAwMDAxMTEyOTM0M2M5MmExNjljZTAxYmVjYzg5QHJlcGx5LmdpdGh1Yi5jb22eeKlGqbz1Eg

Best regards,

Team MEGA

**Comment by LexManos** [comment]
If anyone actually cares about this, open it up again. However Forge doesn't do anything special with networking or anything like that we use vanilla's mechanics and simply hook into them. There should not be any reason that proxies do not work except for potentially the fact that whatever proxifier you user does not support sub-class loaders in java.

**Comment by minecracker627** [comment]
So, if you take down the proxy or the network pivot it works just fine then?
