### ISSUE TITLE
[1.20.6] Serializing capabilities does not call `INBTSerializable#serializeNBT(HolderLookup.Provider)`

### ISSUE THREAD

**Issue by MrCrayfish** [MinecraftForge/MinecraftForge#9998]
**Minecraft Version:** 1.20.6
**Forge Version:** 50.0.31 but also present in 50.1.0

**Description of issue:**
Serializing capabilities does not call the `HolderLookup.Provider` sensitive version of `INBTSerializable#serializeNBT`. Unless you override the non-argument version, the game will fail to save since it returns a null tag.

**Comment by LexManos** [comment]
Correct, there is not enough context to bounce the non-holder lookup to the holder one.
The class is deprecated and should be removed in 1.21.
What cases are you wanting the data? Perhaps we can provide a stop-gap till 1.21.

**Comment by MrCrayfish** [comment]
I am simply trying to save an ItemStack, which needs a holder lookup. I am currently using a workaround, and getting the lookup from the entity the capability is attached to. I am good forever, and will switch if you plan to provide the lookup in 1.21.
