### ISSUE TITLE
#9997 Issue still not fixed for 1.20.1

### ISSUE THREAD

**Issue by Animeboynz** [MinecraftForge/MinecraftForge#9999]
Minecraft Version: {1.20.1}

Forge Version: {Forge version. 47.3.0}

Logs: {Link(s) to GitHub Gist with full latest.log and/or crash report}

Steps to Reproduce:

Log into any Minecraft world
place a boat down
Sit in it and not move
Now watch your distance by boat increase a lot over time.
(This is being checked in statistics but if you don't want to have to keep opening it here is the list of commands for scoreboard)
scoreboard objectives add boat minecraft.custom:minecraft.boat_one_cm
scoreboard objectives setdisplay sidebar boat

Now while you sit in your boat you can see your distance rise!

Description of issue:

Distance by Boat statistic increasing even though I'm not moving

**Comment by Animeboynz** [comment]
#9997

**Comment by Jonathing** [comment]
Please update your Forge version.

**Comment by Jonathing** [comment]
Ah actually, I apologize. This issue is for 1.20.1, which is valid. The original issue was fixed for 1.20.6.

**Comment by LexManos** [comment]
Ya https://github.com/MinecraftForge/MinecraftForge/commit/ff7085b95b1f486dc716bcd80e9252e029e24a1e needs backporting in the next round of back ports. Unless someone else wants to do it real quick.
